### ISSUE TITLE
用了这个adapter之后item点击事件会失灵

### ISSUE THREAD

**Issue by yuanmenghao** [CymChad/BaseRecyclerViewAdapterHelper#1000]
用adapter添加header 之后 item的点击事件会在某些情况下失灵，例如：一直加载更多，连续加载更多5次之后 点击item无反应，没有走simpleItemClick这个方法里。
或者 刷新之后先点击item再点击header，header的点击事件会失灵，这种点击冲突是发生在哪里呢？

**Comment by CymChad** [comment]
版本号。

**Comment by CymChad** [comment]
如果不是最新版本，请使用最新版本。
使用点击事件方式：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister
