### ISSUE TITLE
关于自动加载从后台分页加载数据的使用

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#1001]
这是我的代码
public class TestClass extends BaseActivity implements SwipeRefreshLayout.OnRefreshListener {

    @ViewInject(id = R.id.swiperefreshlayout)
    private SwipeRefreshLayout swipeRefreshLayout;
    @ViewInject(id = R.id.recyclerview)
    private RecyclerView recyclerView;

    View notDataView;
    private List<HomePagePlanModel> homePagePlanList = new ArrayList<HomePagePlanModel>();
    private HomePagePlanAdapter homePagePlanAdapter;
    private int skip = 0;
    private int take = AppSetting.MiddlePageSize;

    private int TOTAL_COUNTER = 0;
    private int mCurrentCounter = 0;
    private boolean isErr;
    private boolean mLoadMoreEndGone = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test);

        notDataView = getLayoutInflater().inflate(R.layout.layout_nodata, (ViewGroup) recyclerView.getParent(), false);

        initRecyclerView(recyclerView);

        initSwipeRefreshLayout(swipeRefreshLayout);

        int sortType = 0;
        int notFree = 0;
        int matchType = 0;
        int madeNotes = 0;
        int realPlan = 0;
        loadPlanList(10143, sortType, notFree, matchType, madeNotes, realPlan);

        initAdapter();
    }

    /**
     * 初始化RecyclerView
     *
     * @param recyclerView
     */
    private void initRecyclerView(RecyclerView recyclerView) {
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.addItemDecoration(new DividerItemDecoration(this, DividerItemDecoration.VERTICAL_LIST));
    }

    /**
     * 初始化SwipeRefreshLayout
     *
     * @param swipeRefreshLayout
     */
    private void initSwipeRefreshLayout(final SwipeRefreshLayout swipeRefreshLayout) {
//        swipeRefreshLayout.post(new Runnable() {
//            @Override
//            public void run() {
//                swipeRefreshLayout.setRefreshing(true);
//                loadPlanList(10143, sortType, notFree, matchType, madeNotes, realPlan);
//                initAdapter();
//            }
//        });
        swipeRefreshLayout.setOnRefreshListener(this);
    }

    /**
     * 初始化Adapter
     */
    private void initAdapter() {
        homePagePlanAdapter = new HomePagePlanAdapter(homePagePlanList, 10143);
        homePagePlanAdapter.openLoadAnimation(BaseQuickAdapter.ALPHAIN);
        recyclerView.setAdapter(homePagePlanAdapter);
        homePagePlanAdapter.setEmptyView(notDataView);
        mCurrentCounter = homePagePlanAdapter.getData().size();
    }

    /**
     * 加载数据
     *
     * @param membershipId
     * @param sorttype
     * @param notfree
     * @param matchtype
     * @param madeNotes
     * @param realPlan
     */
    private void loadPlanList(final int membershipId, int sorttype, int notfree, int matchtype, int madeNotes, final int realPlan) {
        OXPlanBLL.Instance().getMainHomePlan(membershipId, skip, take, sorttype, notfree, matchtype, madeNotes, realPlan, this, new DataCallBack<Result<List<HomePagePlanModel>>>() {
            @Override
            public void onSuccess(final Result<List<HomePagePlanModel>> homePagePlanModels) {
                if (homePagePlanModels.JsonData != null) {
                    homePagePlanList.clear();
                    homePagePlanList.addAll(homePagePlanModels.JsonData);
                    mCurrentCounter = homePagePlanAdapter.getData().size();
                    TOTAL_COUNTER = homePagePlanModels.TotalCount;
                    homePagePlanAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
                        @Override
                        public void onLoadMoreRequested() {
                            swipeRefreshLayout.setEnabled(false);
                            recyclerView.postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    if (mCurrentCounter >= TOTAL_COUNTER) {
                                        homePagePlanAdapter.loadMoreEnd(true);//true is gone,false is visible
                                    } else {
                                        if (!isErr) {
                                            homePagePlanAdapter.addData(homePagePlanModels.JsonData);
                                            mCurrentCounter = homePagePlanAdapter.getData().size();
                                            homePagePlanAdapter.loadMoreComplete();
                                        } else {
                                            isErr = true;
                                            Toast.makeText(TestClass.this, "加载失败", Toast.LENGTH_LONG).show();
                                            homePagePlanAdapter.loadMoreFail();
                                        }
                                    }
                                    swipeRefreshLayout.setEnabled(true);
                                }

                            }, 1);
                        }
                    });
                }
                swipeRefreshLayout.setRefreshing(false);
            }

            @Override
            public void onError(Context context, String errorCode, String title, String message) {
                super.onError(context, errorCode, title, message);
            }
        });
    }

    /**
     * 刷新
     */
    @Override
    public void onRefresh() {
        homePagePlanAdapter.setEnableLoadMore(false);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                homePagePlanAdapter.setNewData(homePagePlanList);
                isErr = false;
                mCurrentCounter = homePagePlanAdapter.getData().size();
                swipeRefreshLayout.setRefreshing(false);
                homePagePlanAdapter.setEnableLoadMore(true);
            }
        }, 1);
    }
}
这是我的布局文件
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swiperefreshlayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </android.support.v4.widget.SwipeRefreshLayout>

</LinearLayout>
版本号：2.8.3
我在做分页加载的时候是按照这样写的，但是在列表中显示的数据是重复的，麻烦帮我看下是哪一步出现了问题啊？

**Comment by 1109993488** [comment]
你应该在onLoadMoreRequested里去请求数据，拿到新数据在调用addData，你的写法就是拿同一个数据去不断添加
