### ISSUE TITLE
关于header的点击事件 和item的点击事件冲突问题

### ISSUE THREAD

**Issue by yuanmenghao** [CymChad/BaseRecyclerViewAdapterHelper#1002]
当用你的loadmore Adapter 滑动到底部并且点击item后，header的点击事件会失效，需要重新刷新列表。为什么会这样？怎么处理

**Comment by yuanmenghao** [comment]
忘了说了，header里是griview

**Comment by yuanmenghao** [comment]
是不是header里不能放griview

**Comment by AllenCoder** [comment]
header里面的点击事件，adapter默认不会处理，直接抛出交个headerview的onClick消费了

**Comment by yuanmenghao** [comment]
我知道adapter不处理，但是事实就是 header里的gridview的点击事件在loadmore之后被消费了。我用recyclerview替换gridview解决了，非常感谢

**Comment by AllenCoder** [comment]
ok ， 解决问题就好
