### ISSUE TITLE
关于刷新,头布局

### ISSUE THREAD

**Issue by shoushuai** [CymChad/BaseRecyclerViewAdapterHelper#1004]
列表加个头布局,刷新用的是Android-PullToRefresh,正在刷新时,点击item应用ANR,是不是添加头布局的问题,或者刷新框架的问题

**Comment by CymChad** [comment]
版本，crash日志。

**Comment by CymChad** [comment]
有问题再提

**Comment by 1987200988** [comment]
适配器加一个自定义下拉刷新的功能就完美了

**Comment by CymChad** [comment]
@1987200988 可以配合其他第三方的使用。

**Comment by shoushuai** [comment]
@CymChad 我先通过其他方式刷新了,以后再看看.
