### ISSUE TITLE
上拉自动加载后容器的问题...

### ISSUE THREAD

**Issue by zofnk** [CymChad/BaseRecyclerViewAdapterHelper#1005]
`
public class NewsActivity extends AppCompatActivity implements BaseQuickAdapter.RequestLoadMoreListener, SwipeRefreshLayout.OnRefreshListener {

    private int mPager = 1;

    private String mTitle;
    private List<DetailBean.ShowapiResBodyBean.PagebeanBean.ContentlistBean> mDataList;
    private RecyclerView mRcyNews;
    private NewsAdapter mNewsAdapter;
    private LoadingView mLoadingView;
    private SwipeRefreshLayout mSltNews;
    private int mAllPages;
    private List<DetailBean.ShowapiResBodyBean.PagebeanBean.ContentlistBean> mAllDataList = new ArrayList<>();

    public static void start(Context context, String title, String value) {
        Intent starter = new Intent(context, NewsActivity.class);
        starter.putExtra(ParamsKey.EXTRA_TITLE, title);
        context.startActivity(starter);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_news);
        mTitle = getIntent().getStringExtra(ParamsKey.EXTRA_TITLE);
        initToolBar();
        init();
        loadData();
    }

    private void init() {
        mSltNews = (SwipeRefreshLayout) findViewById(R.id.sltNews);
        mRcyNews = (RecyclerView) findViewById(R.id.rcyNews);
        RecyclerView.LayoutManager lm = new LinearLayoutManager(this);
        mRcyNews.setLayoutManager(lm);
        mSltNews.setOnRefreshListener(this);
    }

    private void initAdapter() {
        if (mNewsAdapter == null) {
            Log.e("initAdapter : ", "asdasda");
            mNewsAdapter = new NewsAdapter(mDataList);
            mNewsAdapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_BOTTOM);
            mNewsAdapter.setOnLoadMoreListener(NewsActivity.this, mRcyNews);
            mNewsAdapter.isFirstOnly(false);
            mRcyNews.setAdapter(mNewsAdapter);
            mNewsAdapter.setEmptyView(R.layout.layout_empty);   //bind recyclerView first
            mNewsAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
                @Override
                public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                    DetailActivity.start(NewsActivity.this, mAllDataList.get(position).getPubDate(), mAllDataList.get(position).getContent());
                }
            });
        }
    }

    private void initToolBar() {
        TextView title = (TextView) findViewById(R.id.tool_bar_title);
        if (!TextUtils.isEmpty(mTitle)) {
            title.setText(mTitle);
        }
        findViewById(R.id.iv_back).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                finish();
            }
        });
        findViewById(R.id.tv_share).setVisibility(View.GONE);
    }

    protected void loadData() {
        mLoadingView = new LoadingView(this);
        mLoadingView.show();
        DataServer.requestNewsDatas(mTitle, mPager, new CallBack() {
            @Override
            public void onSuccess(byte[] responseBody) {
                mLoadingView.dismiss();
                String data = new String(responseBody);
                DetailBean detailBean = GsonUtil.buildGson().fromJson(data, DetailBean.class);
                mAllPages = detailBean.getShowapi_res_body().getPagebean().getAllPages();
                mDataList = detailBean.getShowapi_res_body().getPagebean().getContentlist();
                mAllDataList.addAll(mDataList);
                initAdapter();
                Log.e("onSuccess : ", "" + mAllDataList.size());
            }

            @Override
            public void onFailure(byte[] responseBody, Throwable error) {
                mLoadingView.dismiss();
            }
        });
    }

    @Override
    public void onLoadMoreRequested() {
        if (mPager < mAllPages) {
            mPager++;
            Log.e("onLoadMoreRequested : ", "" + mPager);
            loadData();
            mNewsAdapter.addData(mDataList);
            mNewsAdapter.loadMoreComplete();
        } else {
            mNewsAdapter.loadMoreEnd();
            Log.e("onLoadMoreRequested : ", "" + mAllDataList);
        }
    }

    @Override
    public void onRefresh() {
        mPager = 1;
        loadData();
        mNewsAdapter.setNewData(mDataList);
        mSltNews.setRefreshing(false);
        Log.e("onRefresh : ", "" + mDataList);
    }
}

`

以上是代码 , 
其主要卡在onLoadMoreRequested()中的mNewsAdapter.addData(mDataList);这里
我每次上拉获取一个size=10的list , 然后addData , 
发现这样写的话数据一直在重复叠加(第一次获取10条,上拉后变成原本的10条上多了10+10 ,依次类推越来越多)
都是在前一次的基础上再叠加,请问是哪里出了问题? 卡了好久....

**Comment by 1109993488** [comment]
```
mNewsAdapter.addData(mDataList);
mNewsAdapter.loadMoreComplete();
这2句应该放到onSuccess方法里面
```
