### ISSUE TITLE
和AndroidSwipeLayout兼容问题

### ISSUE THREAD

**Issue by xiaogu-space** [CymChad/BaseRecyclerViewAdapterHelper#1007]
因为我要添加侧滑删除功能，所以用到了AndroidSwipeLayout，但是他需要继承“RecyclerSwipeAdapter”
是不是就不能用咱们这个了

**Comment by CymChad** [comment]
恩 是的，侧滑删除功能应该只是对item的view误操作。

**Comment by CymChad** [comment]
可组合BRVAH使用：https://github.com/anzaizai/EasySwipeMenuLayout

**Comment by shenshizhong** [comment]
组合使用 EasySwipeMenuLayout，但是删除某一项，布局会闪出删除按钮。就是个别布局会左滑一下。
