### ISSUE TITLE
新版V2.1.1的adapter 点击事件 为何都失效了呢？

### ISSUE THREAD

**Issue by nuilongxiang** [CymChad/BaseRecyclerViewAdapterHelper#1008]
![adapter](https://cloud.githubusercontent.com/assets/27342144/25040421/db1ad9cc-213b-11e7-8397-bacffbe204d1.PNG)
![default](https://cloud.githubusercontent.com/assets/27342144/25040422/de05bb16-213b-11e7-942a-e9cf42dac986.PNG)

**Comment by CymChad** [comment]
升级到最新的版本即可。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.12'

**Comment by nuilongxiang** [comment]
谢谢

2017-04-14 20:47 GMT+08:00 陈宇明 <notifications@github.com>:
