### ISSUE TITLE
建议在BaseHolder中添加获取网络图片的方法,好像能方便一点

### ISSUE THREAD

**Issue by bingtangdisanxian** [CymChad/BaseRecyclerViewAdapterHelper#1011]
public BaseViewHolder setImageUrl(int viewId, String url) {
        ImageView view =(ImageView)this.getView(viewId);
        Glide.with(UIUtils.getContext())
                .load(url)
                .fitCenter()
                .into(view);
        return this;
    }

    public BaseViewHolder setImageUrl(int viewId, String url, GlideCircleTransform circleTransform) {
        ImageView view =(ImageView)this.getView(viewId);
        Glide.with(UIUtils.getContext())
                .load(url)
                .fitCenter()
                .transform(circleTransform)
                .into(view);
        return this;
    }

    public BaseViewHolder setImageUrl(int viewId, String url, GlideRoundTransform glideRoundTransform) {
        ImageView view = (ImageView)this.getView(viewId);
        Glide.with(UIUtils.getContext())
                .load(url)
                .fitCenter()
                .transform(glideRoundTransform)
                .into(view);
        return this;
    }

**Comment by CymChad** [comment]
感谢你的建议，最开始的版本是有这个方法的后来去除了。加载网络图片这一块需要开发者自己加载，因为考虑到实战项目中都有自己的图片加载库，如果封装图片加载框架在里面就耦合了，不能强迫所有的开发者都使用框架内置的图片加载库，所以没有添加获取网络图片的方法。

**Comment by DarrenWorks** [comment]
@CymChad 
Hi,
在其他的三方库中受到的启发
你们可以提供一个抽象函数BaseImageLoader
让开发者去继承这个抽象函数，然后重写其中的抽象方法
在加载图片的时候传入BaseImageLoader的实现类来实现网络库的解耦。
希望能有所帮助。
