### ISSUE TITLE
设置GridLayoutManager并添加头部的时候界面出错

### ISSUE THREAD

**Issue by aa6868226** [CymChad/BaseRecyclerViewAdapterHelper#1012]
当设置GridLayoutManager 并添加头部，获取网络之后进行 适配  第一个条目就会跑到头部和头部重叠在一起

**Comment by CymChad** [comment]
版本。使用代码。

**Comment by CymChad** [comment]
有问题再提。

**Comment by aa6868226** [comment]
用了最新版还是有这错误  当使用GridLayoutManager的时候设置横向条目为>1 当弹出EditText或者界面改变的时候就会把第一个item顶到头部
