### ISSUE TITLE
关于小数据上拉加载

### ISSUE THREAD

**Issue by CocoForAndroid** [CymChad/BaseRecyclerViewAdapterHelper#1014]
我的列表里数据可能一开始只有两三条，所以我想当数据不足一屏的时候设置loadMoreEnd（true），但是我用findLastVisibleItemPosition方法始终返回-1，看源码似乎是child==null，本人新手，望大佬解答

**Comment by CymChad** [comment]
你可以使用`disableLoadMoreIfNotFullPage `这个方法达到你的目的.
