### ISSUE TITLE
 不能设置item的单独点击事件 

### ISSUE THREAD

**Issue by k354250377** [CymChad/BaseRecyclerViewAdapterHelper#1017]
我在 adapter 和 item点击事件都写了 setClickable和setEnabled 可是都无效 麻烦啦

**Comment by k354250377** [comment]
可能我 说错了 是不能设置个别item不可点击

**Comment by CymChad** [comment]
版本号

**Comment by AllenCoder** [comment]
不能单独设置，可以根据需求的场景，拦截不需要触发位置的postion 的点击事件
