### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by yishangfei** [CymChad/BaseRecyclerViewAdapterHelper#1019]
![image](https://cloud.githubusercontent.com/assets/15099278/25083142/f40d7e28-2387-11e7-84d4-72c297922201.png)
![image](https://cloud.githubusercontent.com/assets/15099278/25083150/fe679d0e-2387-11e7-82d4-880d97b23ab0.png)
![image](https://cloud.githubusercontent.com/assets/15099278/25083164/1239116e-2388-11e7-96ab-e691be0ce6d8.png)
![image](https://cloud.githubusercontent.com/assets/15099278/25083170/1a9c645a-2388-11e7-8e96-7e23580f207c.png)

**Comment by CymChad** [comment]
getItemCount,getItemViewType 这两个方法被你重写了。

**Comment by softsnow** [comment]
@yishangfei 请问你怎么解决的，我也想着这样在集合尾部多加一项，作九宫格的加号用。。

**Comment by softsnow** [comment]
@CymChad 请问我想实现这种该怎么写，就像在集合尾部增加一项

**Comment by yishangfei** [comment]
他给出的方案是加footview   我现在用的是原生写的        他这个我本来准备搞得   工作太忙了
https://github.com/yishangfei/Photo-Demo

**Comment by yishangfei** [comment]
@softsnow

**Comment by softsnow** [comment]
@yishangfei ok谢谢

**Comment by CymChad** [comment]
@yishangfei @softsnow 

compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.14'

设置头部，尾部不占一行（使用场景：gv添加+号）

setHeaderViewAsFlow
setFooterViewAsFlow
