### ISSUE TITLE
adapter内部类继承BaseViewHolder,有些手机会报转换异常错误，例如api25的华为P9,mate9,都出现了

### ISSUE THREAD

**Issue by yxyaxng** [CymChad/BaseRecyclerViewAdapterHelper#1020]
版本号2.9.12
单独建一个外部类继承BaseViewHolder，就正常，很纠结
java.lang.ClassCastException
com.chad.library.adapter.base.BaseViewHolder cannot be cast to *.homepage.adapter.DoMoLifeWelfareHeaderAdapter$BaseViewHolderHelper

**Comment by CymChad** [comment]
版本

**Comment by CymChad** [comment]
@QtyearLin

**Comment by CymChad** [comment]
这周末我有空看看

**Comment by QtyearLin** [comment]
最近太忙了 一直没抽出空来  有没有demo 


在 2017-04-19 14:36:06，"陈宇明" <notifications@github.com> 写道：


这周末我有空看看

**Comment by QtyearLin** [comment]
最近太忙了 一直没抽空看看  有没有demo   





在 2017-04-19 14:36:06，"陈宇明" <notifications@github.com> 写道：


这周末我有空看看

**Comment by CymChad** [comment]
只有指定机型会发生这个问题吗？还是全部的？

**Comment by hzqjyyx** [comment]
我的Android 7.0模拟器上会报这样的错误，别的机型还没有尝试

**Comment by CymChad** [comment]
@hzqjyyx  你有demo吗？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/965885/MyApplication.2.zip
我写了个demo没有发现出现你说的问题

**Comment by CymChad** [comment]
有问题再提，或者提供复现demo。

**Comment by CrazyStoneJy** [comment]
确实会有，在乐视手机会报ClassCastException，机型：Letv X500  android版本：6.0

**Comment by CrazyStoneJy** [comment]
在letv上继承BaseViewHolder的VIewHolder不声明为public就会报ClassCastException

**Comment by CymChad** [comment]
收到，由于Android机型问题，所以我们无法全部测试到，但是我会在文档中写上，谢谢你们提出的问题。 @yxyaxng   @CrazyStoneJy
