### ISSUE TITLE
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{6f40025 position=0 id=-1, oldPos=-1, pLpos:-1}                                                                         

### ISSUE THREAD

**Issue by gongxm0412** [CymChad/BaseRecyclerViewAdapterHelper#1022]
使用的是GridLayoutManager ,添加了多个headview ,
每次重新构建headview 的时候 会出现下面的异常
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{6f40025 position=0 id=-1, oldPos=-1, pLpos:-1}

**Comment by CymChad** [comment]
更新至最新版

**Comment by gongxm0412** [comment]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{309e966 position=0 id=-1, oldPos=-1, pLpos:-1}
还是有这个问题，
我们首页的界面
![首页](https://ww2.sinaimg.cn/large/006tKfTcgy1feqsus936gj30zca6au13.jpg)

我描述下我们这边首页的需求，请大神帮我看看我的做法对不对,我们首页上面 轮播图加4个真模块 放最上面，最下面试推荐商品  固定的，中间的模块都是通过接口动态配置的。
我的做法是，先加载最下面的数据   ，然后 把轮播图 作为headview ,其他的模块也都  加到headview 上面

**Comment by 1109993488** [comment]
贴下你添加Header的代码

**Comment by gongxm0412** [comment]
```
 private void addShopView(HomeModuleModel hmm) {
        ShopModuleView smv = new ShopModuleView(getActivity());
        smv.setHomeModuleModel(hmm);
        smv.setTag(hmm.getId());
        mHomeRefAdapter.addHeaderView(smv);
    }


    private void addProductView(HomeModuleModel hmm) {
        ProductModuleView pmv = new ProductModuleView(getActivity());
        pmv.setHomeModuleModel(hmm);
        pmv.setTag(hmm.getId());
        mHomeRefAdapter.addHeaderView(pmv);
    }

    private void addTitleView(HomeModuleModel hmm) {
        TitleModuleView tmv = new TitleModuleView(getActivity());
        tmv.setHomeModuleModel(hmm);
        tmv.setTag(hmm.getId());
        mHomeRefAdapter.addHeaderView(tmv);
    }
```

这是添加三种不同的模块布局

**Comment by 1109993488** [comment]
- removeAllHeaderView();然后addHeaderView();
- notifyItemChanged(0);
这2种情况会出这个错误，跟notifyDataSetChanged在一起写就不会出这个错误

**Comment by hankooxiaozei** [comment]
removeAllHeaderView();然后addHeaderView();更新最新版了，还是会抛这个异常,

**Comment by hankooxiaozei** [comment]
multipleItemAdapter.removeAllHeaderView();
mHandler.post(new Runnable() {
            @Override
            public void run() {

                multipleItemAdapter.addHeaderView(headerView,-1);
                Log.i(TAG,"multipleItemAdapter");

            }
        });
这样子之后不会蹦，但是。。。。是insert,header会被挡

**Comment by liangjingkanji** [comment]
这个问题我也还是出现了, removeAllHeaderView();然后addHeaderView();更新最新版了，还是会抛这个异常,
2.9.34
