### ISSUE TITLE
V2.9.12,设置disableLoadMoreIfNotFullPage()后，不满一屏时会调用onLoadMoreRequested方法

### ISSUE THREAD

**Issue by kuyue** [CymChad/BaseRecyclerViewAdapterHelper#1025]
在MyFollowedActivity中有如下代码：
```
 protected void haveData(List list) {
            adapter.setNewData(list);
            adapter.disableLoadMoreIfNotFullPage(mRecyclerView);
 }
```
```
 @Override
    public void onLoadMoreRequested() {//加载更多
        mRvList.post(new Runnable() {
            @Override
            public void run() {
                getActivity().runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        //请求下一页数据代码
                    }
                });
            }
        });
    }
```
从MyFollowedActivity跳转到AuthorHomeActivity，在AuthorHomeActivity中用EventBus发消息给MyFollowedActivity通知其刷新，MyFollowedActivity接收到消息后就请求网络数据，返回数据后再调用haveData方法。此时我返回到MyFollowedActivity时，onLoadMoreRequested就被调用了，导致了我去请求下一页的内容，这里的下一页是没有内容的，已经能在请求第一页的时候可以确定了，既然设置了disableLoadMoreIfNotFullPage，这里就不应该去调用onLoadMoreRequested方法。结果导致尾部出现了！。
![uazp zjd 5 cf3x_827nz8](https://cloud.githubusercontent.com/assets/10491881/25121662/09cc6f44-2455-11e7-81c7-d2322cb03e7f.png)
![2](https://cloud.githubusercontent.com/assets/10491881/25122161/7c0a1dee-2456-11e7-8f9b-c88179ebd629.png)
![3](https://cloud.githubusercontent.com/assets/10491881/25122242/c15f8474-2456-11e7-885f-e717ec237184.png)

**Comment by tysheng** [comment]
onActivityResult 回调的代码

**Comment by Cornflower1991** [comment]
这个问题 解决了吗

**Comment by kuyue** [comment]
@tysheng 没明白

**Comment by kuyue** [comment]
@Cornflower1991 我业务上是解决了，这个框架还没解决

**Comment by CymChad** [comment]
@kuyue 能提供demo吗？

**Comment by CymChad** [comment]
还有一种解决方法就是直接通过mQuickAdapter.loadMoreEnd(true);隐藏
