### ISSUE TITLE
未判NULL

### ISSUE THREAD

**Issue by kaku2015** [CymChad/BaseRecyclerViewAdapterHelper#1027]
release:2.9.12  -->  类：BaseQuickAdapter --> 1414 行

没有对获取到viewHolder做非空判断，一般当item不可见时获取到的为null值，造成空指针异常。

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.13'
