### ISSUE TITLE
上拉加载一下会加载好几次然后才调用请求数据

### ISSUE THREAD

**Issue by wlqjj0** [CymChad/BaseRecyclerViewAdapterHelper#1031]
5850e3b107916d2af0ee2b9ec389269a
exbm o2 a222 j 9 u e
fexy96 j zxgsf0 89b9br
问题重现：上拉加载一下会加载好几次然后才调用请求数据 版本号0.9.12 0，9，9也有，求解决 谢谢

**Comment by 1109993488** [comment]
加载回调后不调用loadMoreComplete就不会再回调的
