### ISSUE TITLE
关于Expandable

### ISSUE THREAD

**Issue by gyyak46** [CymChad/BaseRecyclerViewAdapterHelper#1036]
点击一个title如何关闭上一个title 因为每次点击position都会发生变化

**Comment by elfman** [comment]
viewHolder有个`getAdapterPosition`方法，用个变量记住上一个viewHolder

**Comment by gyyak46** [comment]
getAdapterPosition返回的positon 直接使用 collapse(oldpositon);关闭上一个标题栏吗, 如果先展开第4个item的标题栏再展开第2个的标题栏就关闭不了4个了

**Comment by gyyak46** [comment]
我可能还是不太懂你的意思 ,我想每次点击这些标题栏 都是只打开其中一个 如果是本身的话就关闭本  我想做这样的效果

**Comment by elfman** [comment]
position会变但是viewHolder不会变，当你要折叠一个item时，再通过`viewHolder.getAdapterPosition()`来获取position，记住每次打开的item对应的viewHolder

**Comment by Ykanade** [comment]
你好，你解决这个问题了吗？我放在全局viewholder获取的adapterposition总是为-1；
                helper.itemView.setOnClickListener(v -> {
                    int pos = helper.getAdapterPosition();
                    if(holder!=null){
                        Utils.showToast(pos+"+++++"+holder.getAdapterPosition());
                    }
                    if(rtz.isExpanded()){
                        collapse(pos);
                    }else {
                        expand(pos);
                        holder=helper;
                    }
                });
