### ISSUE TITLE
setVisible()这个方法差一个invisible

### ISSUE THREAD

**Issue by TheSadFrog** [CymChad/BaseRecyclerViewAdapterHelper#1037]
`public BaseViewHolder setVisible(int viewId, boolean visible) {
        View view = getView(viewId);
        view.setVisibility(visible ? View.VISIBLE : View.GONE);
        return this;
    }`
建议修改为 直接传View.VISIBLE ，View.GONE或者View.INVISIBLE

**Comment by AndroidJohnsonWang** [comment]
赞成

**Comment by FrankKwok** [comment]
@TheSadFrog View.INVISIBLE这个选项不太用吧

**Comment by CymChad** [comment]
这个确实之前没有考虑到，现在支持自定义ViewHolder了，可以由开发者任意修改ViewHolder，所以不打算在继续往BaseViewHolder中添加更多方法了，要不然后续会导致BaseViewHolder过度臃肿，还望理解。
