### ISSUE TITLE
关于切换LayoutManager后headerview和footerview的异常问题

### ISSUE THREAD

**Issue by MorganGeng** [CymChad/BaseRecyclerViewAdapterHelper#1038]
在做切换列表页布局的时候，通过给RecyclerView 设置LinearLayoutManager和GridLayoutManager来切换2中列表形式，遇到一个问题，我列表有添加2个headerview和1个footerview，切换到List形式之后headerview与footerview显示是正常的，但是再切回grid形式的时候，headerview和footerview就显示不正确了(成为了grid条目的一部分，而不是头和脚)。
给点建议？

**Comment by MorganGeng** [comment]
应该是切换之后headview和footview都变成了条目，只是list形式看不出大的差别，grid形式看到不同。

**Comment by bowen-xiao** [comment]
如何解决这个问题的？

**Comment by manburenshenglu** [comment]
同问，recycleview使用gridelayout，添加头部，有问题，变成了item了

**Comment by limengwei** [comment]
切换视图之后
