### ISSUE TITLE
headerView+瀑布流出现bug

### ISSUE THREAD

**Issue by woniu0936** [CymChad/BaseRecyclerViewAdapterHelper#104]
![9336f5fe-13ab-4e2f-a105-2ce593440b55](https://cloud.githubusercontent.com/assets/7264285/16327863/8ba51e42-3a06-11e6-96ec-fb849a79f89e.png)

如上图

**Comment by woniu0936** [comment]
补充：是图中有个错误，是Headerview盖住了瀑布流的item，不是瀑布流的item盖住了Headerview

**Comment by woniu0936** [comment]
补充：这个是因为瀑布流的item中的图片的高度做了动态设置引起的，希望修复这个bug

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.5'
