### ISSUE TITLE
BaseQuickAdapter 中 convert 方法

### ISSUE THREAD

**Issue by a1onexiang2** [CymChad/BaseRecyclerViewAdapterHelper#1040]
BaseQuickAdapter 中 convert(K helper, T item) 方法中为什么不传递一个 position 参数？
个人在开发中经常需要针对 position 做一些特殊处理，但是 BaseQuickAdapter, BaseViewHolder 类中均没有能获取 currentPosition 的方法。
例如从服务器端获取一个长度为 10 的列表，假设有 10 种类型，需要第一条和第四条高亮显示。这时没有 position 的场景下，需要 10 个 JavaBean 都实现 MultiEntity 接口，并且在数组上直接对第一条和第四条的 MultiEntity 实现做修改；而如果有 position，直接在 convert 方法中做一个简单判断就可以了。
想问一下是不是我的思路有问题？

**Comment by a1onexiang2** [comment]
并且，修改 convert 方法会导致版本不兼容，毕竟所有的 Adapter 都实现了这个方法，会产生巨大影响。
那能不能在 convert 方法中维护一个 currentConvertPosition 的整形，并在 Adapter 中新增一个 protected 方法，来获取到现在在绘制的具体 item 的 position，不止这样是否可行？

**Comment by CymChad** [comment]
位置参数可以通过，helper获取。wiki有：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Optimization-adapter-to-reduce-code  滑到底部

**Comment by a1onexiang2** [comment]
我有阅读源码，直接调用 getLayoutPosition() 有可能导致错位。
在 onBindViewHolder 方法中有如下代码：
`int position = holder.getLayoutPosition() - getHeaderLayoutCount()`
这个符合我的需求，但是每次调用代码量较大，可读性也不强。
