### ISSUE TITLE
setOnLoadMoreListener的监听事件

### ISSUE THREAD

**Issue by AlvinQiang** [CymChad/BaseRecyclerViewAdapterHelper#1045]
setOnLoadMoreListener的监听事件只能监听一次，再次滑动到底部时，监听不到了，很尴尬啊，请大神赐教

**Comment by AlvinQiang** [comment]
adapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                ToastUtil.showShort(context,"加载更多");
                adapter.addData(getData());
                adapter.notifyDataSetChanged();
            }
        }, recyclerView);
这是监听的代码

**Comment by CymChad** [comment]
可以看下demo或者wiki，你的使用姿势错误。

**Comment by AlvinQiang** [comment]
哦~~我明白了，我之前以为只要设置监听就可以了，没有特别注意 pullToRefreshAdapter.loadMoreComplete();这句话，每次加载结束以后要加上这一句，才能执行下一次监听O~O，多谢指点
