### ISSUE TITLE
 adapter.loadMoreFail();之后，点击“加载失败，重新请求” 没得反应

### ISSUE THREAD

**Issue by wxy520ll** [CymChad/BaseRecyclerViewAdapterHelper#1047]
不知道这部分代码咋写的，求教大神

**Comment by 1109993488** [comment]
点击加载失败没有回调加载更多吗？具体你可以看下demo

**Comment by wxy520ll** [comment]
demo 看了很多遍了。只看到你调用adapter.loadMoreFail()，就有用；我项目中运用点击重新请求没得反应； 而且我获取到footview。给footview添加监听，判断是不是加载失败状态； 从而自己写再次请求；；但是发现点击footview 没得反应
