### ISSUE TITLE
要怎么删除子级？

### ISSUE THREAD

**Issue by 287138531** [CymChad/BaseRecyclerViewAdapterHelper#1048]

**Comment by CymChad** [comment]
删除数据后，刷新

**Comment by 287138531** [comment]
terminalSelectLeve0Bean.getSubItems().add(terminalSelectLeve1Bean);
这样添加数据必须  手动点展开或者 收缩才会刷新界面notfi无效。或者调用展开和收缩的方法。
删除 也是有一个问题
ArrayList<MultiItemEntity> menuList;   
  比如我要删除某个 MultiItemEntity 里的一个   SubItems。

  menuList.remove(postion);
 t.getSubItems().remove(postion-1);
 我必须同时删除两个  才会有效，不然  展开或者 收缩数据又回来了。

这里操作  t.getSubItems().remove(postion-1);   是不能刷新界面的。

必须操作menuList 才会刷新。这里就会产生一个问题。。
希望可以给个例子，动态删除和添加子项数据的 demo。。

**Comment by CymChad** [comment]
我明天有时间看看。

**Comment by CymChad** [comment]
最近比较忙，你是否能提供一个有问题的demo，我这边帮你调试一下？

**Comment by 287138531** [comment]
抱歉我是在  项目上直接使用的，我暂时通过代码每次展开收缩达到刷新的效果，你可以在你的demo上补充动态添加和删除子项数据的例子，测试下就知道了

**Comment by CymChad** [comment]
ok

**Comment by CymChad** [comment]
我刚才测试了一下，你可以这样
```java
 int cp = getParentPosition(person);
 ((Level1Item)getData().get(cp)).removeSubItem(person);
 getData().remove(holder.getLayoutPosition());
 notifyDataSetChanged();
```

**Comment by CymChad** [comment]
如果需要删除动画，你可以将`notifyDataSetChanged();`替换成` notifyItemRemoved(holder.getLayoutPosition());`
