### ISSUE TITLE
急！！无法使用

### ISSUE THREAD

**Issue by stevenche** [CymChad/BaseRecyclerViewAdapterHelper#1049]
已经添加了：
1、maven { url "https://jitpack.io" }
2、 compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.9.13'
依然报错误：
Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.9.13

**Comment by stevenche** [comment]
删除版本中的v后正常：
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.13'
文档里都是v2.9.x，一直没有更新吗？

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/25309439/dd5bbd26-27ff-11e7-9270-c03e8ddcbb84.png)
最新的文档没有带v，请问你指的是那一块的文档？
