### ISSUE TITLE
loading为什么在切换请求的时候会出现?

### ISSUE THREAD

**Issue by wahyip** [CymChad/BaseRecyclerViewAdapterHelper#1050]
有几个选项, 分别切换不同的网络数据, 我在某一个选项中上拉加载过, 随后点击选项切换数据, 数据切换完后, loading出来了是怎么回事? 然后我现在初步解决是在点击切换网络数据前, 让recyclerview滚回到第一项, 之后替换数据loading就不会出来了..

**Comment by CymChad** [comment]
版本，代码
