### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by pengbs** [CymChad/BaseRecyclerViewAdapterHelper#1054]
下拉刷新成功后，我看目前这个库的处理setNewData是清空了所有老数据，其实下拉刷新很多时候只是往最上面添加新数据，但我调用addData(0, data)这个方法后列表不会滑动到最上面

**Comment by CymChad** [comment]
mRecyclerView.getLayoutManager().scrollToPosition(0);

**Comment by pengbs** [comment]
目前我是这样做的，但是如果有动画这样添加也会有动画效果
