### ISSUE TITLE
如何科学的用BRVAH实现以下布局

### ISSUE THREAD

**Issue by stevenche** [CymChad/BaseRecyclerViewAdapterHelper#1055]
用BRVAH实现以下布局可能会有几种方式，请教哪种更科学：
--------------------------

             Image View

---------------------------
button1   botton2  button3
---------------------------
                  item 1
---------------------------
                  item 2
---------------------------
                  item 3
---------------------------
                  item N
---------------------------

上下滑动时，全部控件都随之滚动。

方式1：
将Image View及button View 作为一个整体，设计成header View
方式2：
将Image View设计成header View, button view 及 item view 作为不同的item
方式3：
将Image View、button view 及 item view 都设计不同的item

请问哪种方式最科学，同时如何监听并区分不同button的事件？
谢谢！

**Comment by CymChad** [comment]
1，直接设置头部的时候，就设置button的点击事件即可。
