### ISSUE TITLE
上拉加载更多功能

### ISSUE THREAD

**Issue by NeverMore906065383** [CymChad/BaseRecyclerViewAdapterHelper#1056]
上拉加载功能开始有点疑问，之前用的还挺顺的，1.9,*的版本，中间做的别事情，一直没更新库，
然后看到demo里面的上拉加载更多是post形式的演示，自己修改了一下发现onLoadMore方法似乎是定时任务，然后就各种不服，，最后发现如果要正常使用onLoadMore的前提是recyclerview必须外层嵌套SwiprefreshLayout。。。。不要问我怎么知道的。。我们需求是加载本地引擎数据，不需要下拉刷新。。。。。

**Comment by CymChad** [comment]
你现在的版本是？

**Comment by NeverMore906065383** [comment]
2.9.13 如果使用onLoadMore()的recyclerview 外层没有嵌套swipeRefreshLayout 会持续触发onLoadMore();


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年4月24日(星期一) 晚上8:09
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "君无戏言"<906065383@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 上拉加载更多功能 (#1056)




你现在的版本是？

**Comment by 1109993488** [comment]
不是必须嵌套SwipeRefreshLayout的，加载更多是在onBindViewHolder里判断回调的。如果你没有设置setAutoLoadMoreSize，你可以看看为什么会回调onBindViewHolder(最后一个item)，比如嵌套Scrollview就会有冲突
