### ISSUE TITLE
2.9.13设置点击事件无效

### ISSUE THREAD

**Issue by ppg408331701** [CymChad/BaseRecyclerViewAdapterHelper#1059]
今天新项目直接用+号引用
 compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:+’

然后设置点击事件setOnItemClickListener死活不成功,换回2.8.9就好了

**Comment by AllenCoder** [comment]
已收到反馈，正在排查

**Comment by AllenCoder** [comment]
2.9.13 测试没有问题，你clean一下工程，重新试一下

**Comment by CymChad** [comment]
请参考demo，demo运行，点击事件正常使用。

**Comment by liu-hailin** [comment]
请参考demo，demo运行，点击事件正常使用。
