### ISSUE TITLE
小建议：SectionAdapter 改进

### ISSUE THREAD

**Issue by leavesfallenlord** [CymChad/BaseRecyclerViewAdapterHelper#106]
作者你好，提一个小建议，我在使用SectionAdapter  时发现 目前Section 下面的展示条目布局是固定的 如果把Section 下面的展示条目做成 可切换类似MultipleItemAdapter 那样的 就更好了 会使项目更加灵活。

**Comment by CymChad** [comment]
多谢建议，下周我会把分组的数据结构改变的。
