### ISSUE TITLE
当recyclerview设置StaggeredGridLayoutManager 或GridLayoutManager时item高度不能自适应。

### ISSUE THREAD

**Issue by Mytsw** [CymChad/BaseRecyclerViewAdapterHelper#1061]
就是当item为有imageview时image的高度不能自适应，只有LinearLayoutManager时才自适应。

**Comment by Mytsw** [comment]
就是当item为有imageview时image的高度不能自适应，

**Comment by CymChad** [comment]
你使用原生的adapter没有问题？adapter内部代码没有对item的高度做修改

**Comment by ArtanisHong** [comment]
@CymChad 我也遇到这个问题了  adapter中没有涉及到item高度的代码  但是最后显示出来的StaggeredGridLayout却是每行都等高

**Comment by CymChad** [comment]
StaggeredGridLayout  item的高度是由自己控制的。

**Comment by CymChad** [comment]
你可以看下，http://blog.csdn.net/duanymin/article/details/44979355   item的高度是由自己代码设置的
