### ISSUE TITLE
你好！public View getViewByPosition(RecyclerView recyclerView, int position, int viewId)这个方法中需要判空一下。

### ISSUE THREAD

**Issue by leguang** [CymChad/BaseRecyclerViewAdapterHelper#1062]
你好！非常感谢你们提供这么好用的框架并不断完善。

`public View getViewByPosition(RecyclerView recyclerView, int position, int viewId) {
        if (recyclerView == null) {
            return null;
        }
        BaseViewHolder viewHolder = (BaseViewHolder) recyclerView.findViewHolderForLayoutPosition(position);
        return viewHolder.getView(viewId);
    }`

这个方法中BaseViewHolder viewHolder = (BaseViewHolder) recyclerView.findViewHolderForLayoutPosition(position);找到的viewHolder有可能为空，比如滑出屏幕，所以在 return viewHolder.getView(viewId);之前要做判空，不然viewHolder在getView的时候会报错，所以我暂时还是用recyclerView.findViewHolderForLayoutPosition(position);来获取该View。

您看是不是这样？

**Comment by tysheng** [comment]
不是早就改成这样了吗？

不过话说回来，获取屏幕之外的view本身就是不可取的，应该避免这类操作

**Comment by leguang** [comment]
哦，我看了一下，我的版本还是2.9.0的，估计你们改了，我不知道。那没问题了。
