### ISSUE TITLE
加载更多失败时点击重新加载没有重新请求

### ISSUE THREAD

**Issue by mhhfut** [CymChad/BaseRecyclerViewAdapterHelper#1063]

**Comment by 1109993488** [comment]
你重写下onBindViewHolder看点击的时候是否回调，然后debug看是否调用autoLoadMore里的加载更多

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/906 请参考一下提问的正确方式，请给出详细的错误信息提示，才能让我们更快的找到问题并解决问题，谢谢配合 @mhhfut

**Comment by mhhfut** [comment]
@1109993488 thx，完美解决，原理是什么呢

**Comment by mhhfut** [comment]
我在回调中加了一个判断的条件导致请求失败，问题已解决
