### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by mhhfut** [CymChad/BaseRecyclerViewAdapterHelper#1065]
在recyclerview嵌套recyclerview的时候，如果最后一个子条目是一个recyclerview，而这个条目需要分页加载时，怎么样实现滑动到子条目的最后一个条目开始自动加载（也就是滑到底），而不是刚滑到这个子条目时就开始自动加载

**Comment by 1109993488** [comment]
目前没法实现你这样的需求，现在的软件不都是没滑动到底部就加载吗
