### ISSUE TITLE
BaseMultiItemQuickAdapter的convert方法中下载视频时使用了Handler，convert常刷新

### ISSUE THREAD

**Issue by llol** [CymChad/BaseRecyclerViewAdapterHelper#1066]
BaseMultiItemQuickAdapter的convert方法中下载视频时使用了Handler，当我在Fragment+TabLayout使用时，convert方法每隔4秒刷新一次，界面有明显的更新。

       //convert中视频下载代码
        VideoUtils.downLoadVideo(SystemConst.DEFAULT_DISC_IMG + url, new DownLoadCallback() {
            @Override
            public void onDownLoad(String filePath, int code) {
                if (code == 200 && TextUtil.getUnNullString(filePath, null) != null) {
                    //设置本地视频路径
                    item.setVideoPath(filePath);
                    Glide.with(mContext.getApplicationContext())
                            .load(Uri.fromFile(new File(filePath)))
                            .into(ivThum);
                }
            }
        });

//现在线程
 new Thread(new Runnable() {
            @Override
            public void run() {
                byte[] result = VolleyUtils.httpURL(url);
                if (null != result) {
                    String videoName = System.currentTimeMillis() + ".mp4";
                    final String videoPath = FileUtil.saveFile(result, videoName);
                    new Handler().post(new Runnable() {
                        @Override
                        public void run() {
                            callback.onDownLoad(videoPath, 200);
                        }
                    });
                } 
            }
        }).start();
//TabLayout初始化

 tabLayout = (TabLayout) findViewById(R.id.tb_disc_personal);
        viewPager = (MyAdaptiveViewPager) findViewById(R.id.vp_disc_personal);
        MyFragmentPagerAdapter fragmentAdapter = new  MyFragmentPagerAdapter(getSupportFragmentManager());
        List<Fragment> fragments = new ArrayList<>();
        List<String> tabs = new ArrayList<>();

        //主页fragment
        mainFragment = new DPersonalMainFragment();
        Bundle b1 = new Bundle();
        b1.putString("userId", userId);
        mainFragment.setArguments(b1);
        fragments.add(mainFragment);

        fragments.add(new DPersonalMainFragment());
        fragments.add(new DPersonalMainFragment());

        tabs.add("主页");
        tabs.add("体验服务");
        tabs.add("店铺动态");
        fragmentAdapter.addFragmengAndTab(fragments, tabs);
        viewPager.setAdapter(fragmentAdapter);
        viewPager.setOffscreenPageLimit(3);
        tabLayout.setupWithViewPager(viewPager);

//Fragment中调用
mAdapter = new DPostDynamicMultiAdapter(getActivity(), new ArrayList<Posting>());
        mAdapter.openLoadAnimation();
        mAdapter.isFirstOnly(false);
        mAdapter.setEnableLoadMore(false);
        recyclerView.setAdapter(mAdapter);

看看那里出了问题

**Comment by CymChad** [comment]
convert 本质上就是 onBindViewholder
