### ISSUE TITLE
 recyleview嵌套 recyleview,里面的recyleview抢点击事件

### ISSUE THREAD

**Issue by k354250377** [CymChad/BaseRecyclerViewAdapterHelper#1067]
里面的  recyleview会抢掉外面的点击事件 这个怎么处理啊?

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0Item%E4%BA%8B%E4%BB%B6

**Comment by AllenCoder** [comment]
采用 
```
 adapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemClick: ");
                Toast.makeText(ItemClickActivity.this, "onItemClick" + position, Toast.LENGTH_SHORT).show();
            }
        });
```

**Comment by scar1et** [comment]
@AllenCoder 我用的是这种方案，点击里面的item还是无法响应外面的事件

**Comment by scar1et** [comment]
我想只响应外边的recylevie的item点击事件，应该怎么处理呢？

**Comment by k354250377** [comment]
卡奈  有问题的不止我一个啊

**Comment by k354250377** [comment]
[Uploading MyApplication.zip…]()



 @CymChad

**Comment by scar1et** [comment]
@k354250377 解决了
我用的是这个
mRecyclerView.addOnItemTouchListener(new OnItemClickListener( ){

            @Override
            public void onSimpleItemClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(RecyclerClickItemActivity.this, "" + Integer.toString(position), Toast.LENGTH_SHORT).show();
                
            }
        });

**Comment by AllenCoder** [comment]
想要外层的reyclerView拦截点击事件不再向内部reyclerView分发，直接调用 

```java
mRecyclerView.addOnItemTouchListener(new OnItemClickListener( ){

        @Override
        public void onSimpleItemClick(BaseQuickAdapter adapter, View view, int position) {
            Toast.makeText(RecyclerClickItemActivity.this, "" + Integer.toString(position), Toast.LENGTH_SHORT).show();
            
        }
    });
```
