### ISSUE TITLE
更新不了最新版本。

### ISSUE THREAD

**Issue by luciferChou** [CymChad/BaseRecyclerViewAdapterHelper#1068]
我的BaseRecyclerViewAdapterHelper 只能用v2.9.2以前的版本。
然后用v2.8.9的时候打签名包的时候有这个异常
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Class.getModifiers()' on a null object reference
at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:857)
at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:843)
at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:826)
at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:822)
升级到v2.9.2还是有这个bug。签名包就报这个异常

**Comment by CymChad** [comment]
@QtyearLin

**Comment by CymChad** [comment]
你升级到最新版本试试

**Comment by CymChad** [comment]
我今天自己写了一个，打包成功了，并没有出现你说的问题。
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/965885/MyApplication.2.zip
我用的是这个demo，打包的。

**Comment by CymChad** [comment]
刚才发现原因了
这样就会报错
```java
public class InFullFlowerAdapter extends BaseQuickAdapter
```java
因为没加泛型，所以导致反射的时候没找到类型,正确的应该这样
```
public class InFullFlowerAdapter extends BaseQuickAdapter<Bean.VigourListBean, InFullFlowerAdapter.MyViewholder1> 
```

**Comment by luciferChou** [comment]
我所有的adapter都有加这个public class MomentItemAdapter extends BaseQuickAdapter<Moment, BaseViewHolder> 哦，我回头再看看

**Comment by luciferChou** [comment]
还有就是，我只能升到v2.9.2 这个版本，升级v2.9.15这个的时候一直提示
Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.9.15这个。

**Comment by CymChad** [comment]
com.github.CymChad：BaseRecyclerViewAdapterHelper：v2.9.15  没有 v
com.github.CymChad：BaseRecyclerViewAdapterHelper：2.9.15
