### ISSUE TITLE
最新版本上拉加载更多崩溃

### ISSUE THREAD

**Issue by springGir** [CymChad/BaseRecyclerViewAdapterHelper#1069]
包装自定义上拉加载更多和下拉刷新后，最新版本上拉加载更多崩溃，TinkerUncaughtExceptionHandler: uncaughtException:Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;用2.5.0的版本是可以的

**Comment by 1109993488** [comment]
应该是你的v4包的版本和sdk的v4版本不一致出现的，你更新下v4版本试试

**Comment by springGir** [comment]
我删除了我在gradle里面的v4包，还是报错了java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;

**Comment by 1109993488** [comment]
#913

**Comment by springGir** [comment]
compile('cn.qqtheme.framework:WheelPicker:xxxx') {
exclude group: 'com.android.support'
}

重要： exclude group: 'com.android.support'
cn.qqtheme.framework:WheelPicker这个是我用的别人的第三方的项目


这个方法解决了我的问题，WheelPicker里面引入了26.0.0的v4包，导致v4包不一致，所以报错了
