### ISSUE TITLE
BaseQuickAdapter don't initialize data

### ISSUE THREAD

**Issue by iagocanalejas** [CymChad/BaseRecyclerViewAdapterHelper#107]
Hi, nice library. Just a problem. There is a problem when you try to initialize a BaseQuickAdapter extended adapter like:
`new AdapterSummonerHistoric(activity, layout, data);`
The data is never showed.
To solve the problem i have to change my code and do:
`adapter = new AdapterSummonerHistoric(activity, layout, null);`
`adapter.setNewData(data);`
I don't know if this is an intentional behavior or is just a bug, thanks for watching.

**Comment by CymChad** [comment]
```java
 public BaseQuickAdapter(int layoutResId, List<T> data) {
        this.mData = data == null ? new ArrayList<T>() : data;
        if (layoutResId != 0) {
            this.mLayoutResId = layoutResId;
        }
    }
```

**Comment by CymChad** [comment]
```java
 /**
     * Get the data of list
     *
     * @return
     */
    public List getData() {
        return mData;
    }

```

**Comment by CymChad** [comment]
Please use the new version 1.8.5, bug fixes
