### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ibenlim** [CymChad/BaseRecyclerViewAdapterHelper#1070]
随便瞎点，突然报了一个这个错误：
java.lang.IndexOutOfBoundsException
Inconsistency detected. Invalid view holder adapter positionViewHolder{12e8f038 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}

1 android.support.v7.widget.RecyclerView$l.a(SourceFile:4499)
2 android.support.v7.widget.RecyclerView$l.a(SourceFile:4630)
3 android.support.v7.widget.RecyclerView$l.c(SourceFile:4611)
4 android.support.v7.widget.LinearLayoutManager$c.a(SourceFile:1988)
5 android.support.v7.widget.LinearLayoutManager.a(SourceFile:1384)
6 android.support.v7.widget.LinearLayoutManager.a(SourceFile:1347)
7 android.support.v7.widget.LinearLayoutManager.c(SourceFile:574)
8 android.support.v7.widget.RecyclerView.F(SourceFile:2977)
9 android.support.v7.widget.RecyclerView.k(SourceFile:2901)
10 android.support.v7.widget.RecyclerView.t(SourceFile:1457)
11 android.support.v7.widget.RecyclerView.c(SourceFile:147)
12 android.support.v7.widget.RecyclerView$1.run(SourceFile:285)
13 android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
14 android.view.Choreographer.doCallbacks(Choreographer.java:580)
15 android.view.Choreographer.doFrame(Choreographer.java:549)
16 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
17 android.os.Handler.handleCallback(Handler.java:739)
18 android.os.Handler.dispatchMessage(Handler.java:95)
19 android.os.Looper.loop(Looper.java:135)
20 android.app.ActivityThread.main(ActivityThread.java:5371)
21 java.lang.reflect.Method.invoke(Native Method)
22 java.lang.reflect.Method.invoke(Method.java:372)
23 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
24 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/590
