### ISSUE TITLE
当 RecyclerView 条数不满一页时，会不停的触发 BaseQuickAdapter 预加载；优化建议

### ISSUE THREAD

**Issue by jarylan** [CymChad/BaseRecyclerViewAdapterHelper#1071]
目前预加载是在渲染 item 时触发。当前 item 不足以铺满整个屏幕（假设只有 2 个 item），则会不停的触发预加载；
优化建议 ： 
将预加载方法 autoLoadMore(position) ； 放到滑动 RecyclerView 时去触发；在 setRecyclerView(RecyclerView recyclerView) 中添加滑动监听，如下：

 private void setRecyclerView(RecyclerView recyclerView) {
        mRecyclerView = recyclerView;
        mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if( dy > 0){
                    LinearLayoutManager manager = (LinearLayoutManager) recyclerView.getLayoutManager();
                    autoLoadMore(manager.findLastCompletelyVisibleItemPosition());
                }
            }
        });
    }

**Comment by CymChad** [comment]
检查是否满一屏，如果不满足关闭loadMore

mQuickAdapter.disableLoadMoreIfNotFullPage();

**Comment by jarylan** [comment]
恩；是可以的，不过每次更新数据都要调用这句代码。
这句代码我觉得有必要在 《BRVAH 源码分析》预加载那块说明。

**Comment by CymChad** [comment]
恩 好的，多谢提醒
