### ISSUE TITLE
IndexOutOfBoundsException: Inconsistency detected. Invalid view holder 

### ISSUE THREAD

**Issue by k354250377** [CymChad/BaseRecyclerViewAdapterHelper#1074]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{5b46802 position=1 id=-1, oldPos=2, pLpos:2 scrap [attachedScrap] tmpDetached no parent}  

我代码是这么写的
![Uploading image.png…]()

![Uploading image.png…]()

**Comment by 1109993488** [comment]
图片有问题，代码看不到。
你可能自己清空了数据源，没调用notifyDataSetChanged更新
