### ISSUE TITLE
有一个疑惑麻烦解答

### ISSUE THREAD

**Issue by xubuhang** [CymChad/BaseRecyclerViewAdapterHelper#108]
在BaseQuickAdapter里的  
public class OnItemChildClickListener implements View.OnClickListener {
        public int position;

        @Override
        public void onClick(View v) {
            if (mChildClickListener != null)
                mChildClickListener.onItemChildClick(BaseQuickAdapter.this, v, position - getHeaderViewsCount());
        }
    }
里面的position没有根据点击位置时重新赋值。我的办法是：position在onBindViewHolder时作为参数传到convert再绑到Listener上。

**Comment by CymChad** [comment]
你是如何使用的？在外面set OnItemChildClickListener 这样使用的吗？

**Comment by CymChad** [comment]
请更新最新版。你说的问题，已经在新的版本修改好了，感谢使用。

**Comment by xubuhang** [comment]
好，谢谢。
