### ISSUE TITLE
Expandable如何动态插入删除子项？

### ISSUE THREAD

**Issue by xiang23** [CymChad/BaseRecyclerViewAdapterHelper#1080]
直接addSubItem nofi无效

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1048

**Comment by SomnusWu** [comment]
添加子项  我现在也会有这个问题  。直接addSubItem nofi无效
断点看了下  在addSubItem之后 adapter中的数据是有的。但是我调用了 expandAll 以及 notifyDataSetChanged 还是没法展示出来 。

**Comment by SomnusWu** [comment]
pu~~~~  , 没去看源码 ，但是我感觉是更新方法的问题 。我先后调用了 collapse(x) ,expandAll(),notifyDataSetChanged() 可以出来了。
