### ISSUE TITLE
滑动删除功能，删除到最后一个item时程序崩溃

### ISSUE THREAD

**Issue by xie007** [CymChad/BaseRecyclerViewAdapterHelper#1081]

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/906

**Comment by CymChad** [comment]
请提供详细信息。

**Comment by xie007** [comment]
我把代码删了，现在还没时间测试，我是按照你项目domo编写的，[拖拽，滑动删除](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0%E6%8B%96%E6%8B%BD%E3%80%81%E6%BB%91%E5%8A%A8%E5%88%A0%E9%99%A4)你看看怎么回事，用最新版测试的

**Comment by CymChad** [comment]
恩，我测试一下。

**Comment by CymChad** [comment]
![2](https://cloud.githubusercontent.com/assets/7698209/25836875/fa7c3240-34bc-11e7-88ba-0c6f723b390d.gif)
经过测试并没有发生你说的问题，
