### ISSUE TITLE
加载失败的规则能否添加多一个方式，添加继续上拉刷新而不仅是点击刷新

### ISSUE THREAD

**Issue by axkza** [CymChad/BaseRecyclerViewAdapterHelper#1082]
现在加载失败是调用adapter.loadMoreFail();底部出现加载失败的布局，点击加载更多
但是我们的需求是：加载失败后跳到最后一个item，然后继续上拉加载更多（重点是继续上拉，非点击）

所以我想，能否加载失败直接跳到最后一个item，向上偏移一个px，然后就可以在上拉的过程中继续触发
Adapter.setOnLoadMoreListener？？

**Comment by 1109993488** [comment]
暂时没法实现这样的功能，现在滑动1px没法做到回调
