### ISSUE TITLE
大佬你好，当在item的控件中弹出popupwindow的时候，会发生位移

### ISSUE THREAD

**Issue by allnan** [CymChad/BaseRecyclerViewAdapterHelper#1083]
在一个Linear RecyclerView 中，我想在item的一个Button的上方弹出一个popupwindow。
用popupwindow的showAtLocation的方法，会让popupwindow直接在整个recyclerview的上方位置出现；
如果用showAsDropDown方法，在屏幕上半部分的会正常显示，但是在屏幕下方的popupwindow会在button的下方显示，同事说是Adapter的原因，请问这个有解决方法么。

版本号 2.9.12

**Comment by CymChad** [comment]
能提供demo吗？
