### ISSUE TITLE
加载更多，

### ISSUE THREAD

**Issue by axkza** [CymChad/BaseRecyclerViewAdapterHelper#1085]
在onCreated中写了mAdapter.setOnLoadMoreListener之后，会自动加载更多，但是我的需求是刚进去时是调用下拉刷新，而不是mAdapter.setOnLoadMoreListener里面的方法，需要怎么设置？
![https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=2600445114,3801831216&fm=117&gp=0.jpg]()
像这样，期望自动下拉刷新时，不出现自动加载更多

**Comment by 1109993488** [comment]
如果你的初始化数据不为0，就会回调加载更多，你可以onCreate请求数据回调后调用setLoadMoreListener

**Comment by axkza** [comment]
对哦，方法可行，谢谢了
