### ISSUE TITLE
上拉加载的问题

### ISSUE THREAD

**Issue by luXiuKun** [CymChad/BaseRecyclerViewAdapterHelper#1087]
当只有一条数据时，disableLoadMoreIfNotFullPage后依然会走OnLoadMoreListener

baseQuickAdapter.disableLoadMoreIfNotFullPage(recyview); baseQuickAdapter.setOnLoadMoreListener(HomeFragment.this,recyview);

**Comment by tysheng** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=disableLoadMoreIfNotFullPage
