### ISSUE TITLE
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{349680cf position=0 id=-1, oldPos=-1, pLpos:-1 no parent}

### ISSUE THREAD

**Issue by rongdongliu** [CymChad/BaseRecyclerViewAdapterHelper#1090]
我使用导入lib源码 的版本，大概是半个月之前的代码。
这个奔溃，不是必现的，今天发的版本，奔溃大概是1/10000
我记得之前有童鞋提交过这个bug的。

05-03 17:32:20.137 21267 21267 E DEBUG   : begin to generate java report
05-03 17:32:20.179 21267 21267 E DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-03 17:32:20.179 21267 21267 E DEBUG   : Basic Information: 'pid: 21267/tid: 21267/logver: 2/time: 20170503173220/cpu: armeabi-v7a/cpu hardware: mt6735'
05-03 17:32:20.182 21267 21267 E DEBUG   : Mobile Information: 'model: HUAWEI CUN-L22/version: 5.1/sdk: 22'
05-03 17:32:20.182 21267 21267 E DEBUG   : Build fingerprint: 'HUAWEI/CUN-L22/HWCUN-L6735:5.1/HUAWEICUN-L22/C567B128:user/release-keys'
05-03 17:32:20.182 21267 21267 E DEBUG   : Runtime Information: 'start: 20170503172725/maxheap: 134217728'
05-03 17:32:20.182 21267 21267 E DEBUG   : Application Information: 'version: 2.2.3/subversion: release/buildseq: 170503163400'
05-03 17:32:20.183 21267 21267 E DEBUG   : CrashSDK Information: 'version: 1.5.0.0/nativeseq: 0/javaseq: 160318104655/target: release'
05-03 17:32:20.183 21267 21267 E DEBUG   : _java.log
05-03 17:32:20.183 21267 21267 E DEBUG   : UUID: c4***3
05-03 17:32:20.183 21267 21267 E DEBUG   : Log Type: java
05-03 17:32:20.183 21267 21267 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
05-03 17:32:20.183 21267 21267 E DEBUG   : imei
05-03 17:32:20.183 21267 21267 E DEBUG   : : 
05-03 17:32:20.183 21267 21267 E DEBUG   : ****3601
05-03 17:32:20.183 21267 21267 E DEBUG   : country
05-03 17:32:20.183 21267 21267 E DEBUG   : : 
05-03 17:32:20.183 21267 21267 E DEBUG   : th
05-03 17:32:20.183 21267 21267 E DEBUG   : bid
05-03 17:32:20.183 21267 21267 E DEBUG   : : 
05-03 17:32:20.183 21267 21267 E DEBUG   : 1
05-03 17:32:20.183 21267 21267 E DEBUG   : isRoot
05-03 17:32:20.184 21267 21267 E DEBUG   : : 
05-03 17:32:20.184 21267 21267 E DEBUG   : false
05-03 17:32:20.184 21267 21267 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
05-03 17:32:20.184 21267 21267 E DEBUG   : Process Name: 'com.**.****t'
05-03 17:32:20.184 21267 21267 E DEBUG   : Thread Name: 'main'
05-03 17:32:20.184 21267 21267 E DEBUG   : Back traces starts.
05-03 17:32:20.184 21267 21267 E DEBUG   : java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{349680cf position=0 id=-1, oldPos=-1, pLpos:-1 no parent}
05-03 17:32:20.184 21267 21267 E DEBUG   : 
05-03 17:32:20.204 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.204 21267 21267 E DEBUG   : android.support.v7.widget.bx.a(SourceFile:692)
05-03 17:32:20.205 21267 21267 E DEBUG   : 
05-03 17:32:20.205 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.205 21267 21267 E DEBUG   : android.support.v7.widget.ah.a(SourceFile:239)
05-03 17:32:20.205 21267 21267 E DEBUG   : 
05-03 17:32:20.205 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.205 21267 21267 E DEBUG   : android.support.v7.widget.RecyclerView$h.a(SourceFile:7093)
05-03 17:32:20.205 21267 21267 E DEBUG   : 
05-03 17:32:20.205 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.205 21267 21267 E DEBUG   : android.support.v7.widget.RecyclerView$h.b(SourceFile:7070)
05-03 17:32:20.205 21267 21267 E DEBUG   : 
05-03 17:32:20.205 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.205 21267 21267 E DEBUG   : android.support.v7.widget.LinearLayoutManager.a(SourceFile:1430)
05-03 17:32:20.205 21267 21267 E DEBUG   : 
05-03 17:32:20.205 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.205 21267 21267 E DEBUG   : android.support.v7.widget.LinearLayoutManager.a(SourceFile:1377)
05-03 17:32:20.205 21267 21267 E DEBUG   : 
05-03 17:32:20.206 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.206 21267 21267 E DEBUG   : android.support.v7.widget.LinearLayoutManager.c(SourceFile:588)
05-03 17:32:20.206 21267 21267 E DEBUG   : 
05-03 17:32:20.206 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.206 21267 21267 E DEBUG   : android.support.v7.widget.RecyclerView.J(SourceFile:3315)
05-03 17:32:20.206 21267 21267 E DEBUG   : 
05-03 17:32:20.206 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.206 21267 21267 E DEBUG   : android.support.v7.widget.RecyclerView.onMeasure(SourceFile:2843)
05-03 17:32:20.206 21267 21267 E DEBUG   : 
05-03 17:32:20.206 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.206 21267 21267 E DEBUG   : android.view.View.measure(View.java:17970)
05-03 17:32:20.206 21267 21267 E DEBUG   : 
05-03 17:32:20.206 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.206 21267 21267 E DEBUG   : android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5710)
05-03 17:32:20.206 21267 21267 E DEBUG   : 
05-03 17:32:20.206 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.206 21267 21267 E DEBUG   : android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
05-03 17:32:20.207 21267 21267 E DEBUG   : 
05-03 17:32:20.207 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.207 21267 21267 E DEBUG   : android.widget.LinearLayout.measureVertical(LinearLayout.java:785)
05-03 17:32:20.207 21267 21267 E DEBUG   : 
05-03 17:32:20.207 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.207 21267 21267 E DEBUG   : android.widget.LinearLayout.onMeasure(LinearLayout.java:654)
05-03 17:32:20.207 21267 21267 E DEBUG   : 
05-03 17:32:20.207 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.207 21267 21267 E DEBUG   : android.view.View.measure(View.java:17970)
05-03 17:32:20.207 21267 21267 E DEBUG   : 
05-03 17:32:20.207 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.207 21267 21267 E DEBUG   : android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5710)
05-03 17:32:20.207 21267 21267 E DEBUG   : 
05-03 17:32:20.207 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.207 21267 21267 E DEBUG   : android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
05-03 17:32:20.207 21267 21267 E DEBUG   : 
05-03 17:32:20.207 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.208 21267 21267 E DEBUG   : android.view.View.measure(View.java:17970)
05-03 17:32:20.208 21267 21267 E DEBUG   : 
05-03 17:32:20.208 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.208 21267 21267 E DEBUG   : android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5710)
05-03 17:32:20.208 21267 21267 E DEBUG   : 
05-03 17:32:20.208 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.208 21267 21267 E DEBUG   : android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
05-03 17:32:20.208 21267 21267 E DEBUG   : 
05-03 17:32:20.208 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.208 21267 21267 E DEBUG   : android.view.View.measure(View.java:17970)
05-03 17:32:20.208 21267 21267 E DEBUG   : 
05-03 17:32:20.208 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.208 21267 21267 E DEBUG   : android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5710)
05-03 17:32:20.208 21267 21267 E DEBUG   : 
05-03 17:32:20.208 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.208 21267 21267 E DEBUG   : android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
05-03 17:32:20.208 21267 21267 E DEBUG   : 
05-03 17:32:20.209 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.209 21267 21267 E DEBUG   : android.widget.LinearLayout.measureVertical(LinearLayout.java:785)
05-03 17:32:20.209 21267 21267 E DEBUG   : 
05-03 17:32:20.209 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.209 21267 21267 E DEBUG   : android.widget.LinearLayout.onMeasure(LinearLayout.java:654)
05-03 17:32:20.209 21267 21267 E DEBUG   : 
05-03 17:32:20.209 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.209 21267 21267 E DEBUG   : android.view.View.measure(View.java:17970)
05-03 17:32:20.209 21267 21267 E DEBUG   : 
05-03 17:32:20.209 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.209 21267 21267 E DEBUG   : android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5710)
05-03 17:32:20.209 21267 21267 E DEBUG   : 
05-03 17:32:20.209 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.209 21267 21267 E DEBUG   : android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
05-03 17:32:20.209 21267 21267 E DEBUG   : 
05-03 17:32:20.209 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.210 21267 21267 E DEBUG   : com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2755)
05-03 17:32:20.210 21267 21267 E DEBUG   : 
05-03 17:32:20.210 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.210 21267 21267 E DEBUG   : android.view.View.measure(View.java:17970)
05-03 17:32:20.210 21267 21267 E DEBUG   : 
05-03 17:32:20.210 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.210 21267 21267 E DEBUG   : android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2438)
05-03 17:32:20.210 21267 21267 E DEBUG   : 
05-03 17:32:20.210 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.210 21267 21267 E DEBUG   : android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1418)
05-03 17:32:20.210 21267 21267 E DEBUG   : 
05-03 17:32:20.210 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.210 21267 21267 E DEBUG   : android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1642)
05-03 17:32:20.210 21267 21267 E DEBUG   : 
05-03 17:32:20.210 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.210 21267 21267 E DEBUG   : android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
05-03 17:32:20.210 21267 21267 E DEBUG   : 
05-03 17:32:20.211 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.211 21267 21267 E DEBUG   : android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6742)
05-03 17:32:20.211 21267 21267 E DEBUG   : 
05-03 17:32:20.211 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.211 21267 21267 E DEBUG   : android.view.Choreographer$CallbackRecord.run(Choreographer.java:826)
05-03 17:32:20.211 21267 21267 E DEBUG   : 
05-03 17:32:20.211 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.211 21267 21267 E DEBUG   : android.view.Choreographer.doCallbacks(Choreographer.java:629)
05-03 17:32:20.211 21267 21267 E DEBUG   : 
05-03 17:32:20.211 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.211 21267 21267 E DEBUG   : android.view.Choreographer.doFrame(Choreographer.java:597)
05-03 17:32:20.211 21267 21267 E DEBUG   : 
05-03 17:32:20.211 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.211 21267 21267 E DEBUG   : android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:812)
05-03 17:32:20.211 21267 21267 E DEBUG   : 
05-03 17:32:20.211 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.211 21267 21267 E DEBUG   : android.os.Handler.handleCallback(Handler.java:815)
05-03 17:32:20.212 21267 21267 E DEBUG   : 
05-03 17:32:20.212 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.212 21267 21267 E DEBUG   : android.os.Handler.dispatchMessage(Handler.java:104)
05-03 17:32:20.212 21267 21267 E DEBUG   : 
05-03 17:32:20.212 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.212 21267 21267 E DEBUG   : android.os.Looper.loop(Looper.java:194)
05-03 17:32:20.212 21267 21267 E DEBUG   : 
05-03 17:32:20.212 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.212 21267 21267 E DEBUG   : android.app.ActivityThread.main(ActivityThread.java:5929)
05-03 17:32:20.212 21267 21267 E DEBUG   : 
05-03 17:32:20.212 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.212 21267 21267 E DEBUG   : java.lang.reflect.Method.invoke(Native Method)
05-03 17:32:20.212 21267 21267 E DEBUG   : 
05-03 17:32:20.212 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.212 21267 21267 E DEBUG   : java.lang.reflect.Method.invoke(Method.java:372)
05-03 17:32:20.213 21267 21267 E DEBUG   : 
05-03 17:32:20.213 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.213 21267 21267 E DEBUG   : com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
05-03 17:32:20.213 21267 21267 E DEBUG   : 
05-03 17:32:20.213 21267 21267 E DEBUG   : 	at 
05-03 17:32:20.213 21267 21267 E DEBUG   : com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
05-03 17:32:20.213 21267 21267 E DEBUG   : 
05-03 17:32:20.213 21267 21267 E DEBUG   : Back traces ends.
05-03 17:32:20.213 21267 21267 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
05-03 17:32:20.213 21267 21267 E DEBUG   : meminfo:
05-03 17:32:20.214 21267 21267 E DEBUG   : MemTotal:         959968 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : MemFree:           33032 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Buffers:           10352 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Cached:           161196 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : SwapCached:         4216 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Active:           282940 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Inactive:         289668 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Active(anon):     199716 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Inactive(anon):   203768 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Active(file):      83224 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Inactive(file):    85900 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Unevictable:        1760 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Mlocked:               0 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : HighTotal:        511168 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : HighFree:           6804 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : LowTotal:         448800 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : LowFree:           26228 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : SwapTotal:        483324 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : SwapFree:          14312 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Dirty:                36 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Writeback:            12 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : AnonPages:        402756 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Mapped:            85900 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Shmem:               400 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Slab:              43900 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : SReclaimable:      13528 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : SUnreclaim:        30372 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : KernelStack:       18240 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : PageTables:        30852 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : NFS_Unstable:          0 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Bounce:                0 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : WritebackTmp:          0 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : CommitLimit:      963308 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : Committed_AS:   36287968 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : VmallocTotal:     499712 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : VmallocUsed:      112664 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : VmallocFilt:    
05-03 17:32:20.214 21267 21267 E DEBUG   :     9260 kB
05-03 17:32:20.214 21267 21267 E DEBUG   : VmallocChunk:     143744 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
05-03 17:32:20.215 21267 21267 E DEBUG   : status:
05-03 17:32:20.215 21267 21267 E DEBUG   : Name:	.infreewifi.cct
05-03 17:32:20.215 21267 21267 E DEBUG   : State:	R (running)
05-03 17:32:20.215 21267 21267 E DEBUG   : Tgid:	21267
05-03 17:32:20.215 21267 21267 E DEBUG   : Pid:	21267
05-03 17:32:20.215 21267 21267 E DEBUG   : PPid:	14526
05-03 17:32:20.215 21267 21267 E DEBUG   : TracerPid:	0
05-03 17:32:20.215 21267 21267 E DEBUG   : Uid:	10158	10158	10158	10158
05-03 17:32:20.215 21267 21267 E DEBUG   : Gid:	10158	10158	10158	10158
05-03 17:32:20.215 21267 21267 E DEBUG   : FDSize:	256
05-03 17:32:20.215 21267 21267 E DEBUG   : Groups:	1015 1028 3003 9997 50158 
05-03 17:32:20.215 21267 21267 E DEBUG   : VmPeak:	 1113960 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmSize:	 1104820 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmLck:	       0 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmPin:	       0 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmHWM:	   81484 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmRSS:	   73936 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmData:	  194848 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmStk:	    8196 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmExe:	      12 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmLib:	   89280 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmPTE:	     342 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : VmSwap:	   18388 kB
05-03 17:32:20.215 21267 21267 E DEBUG   : Threads:	64
05-03 17:32:20.215 21267 21267 E DEBUG   : SigQ:	0/7490
05-03 17:32:20.215 21267 21267 E DEBUG   : SigPnd:	0000000000000000
05-03 17:32:20.215 21267 21267 E DEBUG   : ShdPnd:	0000000000000000
05-03 17:32:20.215 21267 21267 E DEBUG   : SigBlk:	0000000000009204
05-03 17:32:20.215 21267 21267 E DEBUG   : SigIgn:	0000000000000000
05-03 17:32:20.215 21267 21267 E DEBUG   : SigCgt:	00000002000094f8
05-03 17:32:20.215 21267 21267 E DEBUG   : CapInh:	0000000000000000
05-03 17:32:20.215 21267 21267 E DEBUG   : CapPrm:	0000000000000000
05-03 17:32:20.215 21267 21267 E DEBUG   : CapEff:	0000000000000000
05-03 17:32:20.215 21267 21267 E DEBUG   : CapBnd:	0000000000000000
05-03 17:32:20.215 21267 21267 E DEBUG   : Seccomp:	0
05-03 17:32:20.215 21267 21267 E DEBUG   : Cpus_allowed:	f
05-03 17:32:20.215 21267 21267 E DEBUG   : Cpus_allowed_list:	0-3
05-03 17:32:20.215 21267 21267 E DEBUG   : voluntary_ctxt_switches:	4692
05-03 17:32:20.215 21267 21267 E DEBUG   : nonvoluntary_ctxt_switches:	2851
05-03 17:32:20.215 21267 21267 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
05-03 17:32:20.215 21267 21267 E DEBUG   : Dalvik:
05-03 17:32:20.215 21267 21267 E DEBUG   : MaxMemory: 134217728 TotalMemory: 23046848 FreeMemory: 4552680
05-03 17:32:20.215 21267 21267 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
05-03 17:32:20.215 21267 21267 E DEBUG   : logcat: 
[DEBUG] Read 655 lines, wrote 655 lines.

**Comment by rongdongliu** [comment]
有没有同学遇到这个问题啊，怎么解决呢

**Comment by CymChad** [comment]
版本，复现方式
