### ISSUE TITLE
大神，有没有这个stickyView

### ISSUE THREAD

**Issue by montotone** [CymChad/BaseRecyclerViewAdapterHelper#1091]
https://github.com/montotone/StickyLView/blob/master/gif/ezgif-3-21381ae72e.gif

**Comment by Troll4it** [comment]
PinnedSectionItemDecoration  项目的后面大佬不是给我们介绍这个库了吗

**Comment by montotone** [comment]
好吧，之前没有看到。谢谢你

**Comment by CymChad** [comment]
@Troll4it 感谢
