### ISSUE TITLE
recyclerciew嵌套listview会出现类型转换异常

### ISSUE THREAD

**Issue by AnJeremy** [CymChad/BaseRecyclerViewAdapterHelper#1093]

**Comment by CymChad** [comment]
#906  请描述清晰一些。

**Comment by AnJeremy** [comment]
就是我的recyclerview的adapter用的你的adapter然后recyclerview里面嵌套的一个listview用的adapter是系统自带的BaseAdapter,然后一运行就出现报错，说我的类型转换异常

**Comment by CymChad** [comment]
那你就getview拿到listview然后自己设置adapter

**Comment by Troll4it** [comment]
你说的这个问题应该不会的，因为我recyclerView嵌套过recyclerView，没有出现过你说的转换异常 。。可是宇明哥，在嵌套后我遇到一个问题，打开嵌套的activity，界面会自动滑动到被嵌套的recyclerView的第一个item,

**Comment by CymChad** [comment]
@Troll4it 这个应该是焦点被抢了，你可以通过代码重置一下最外层rv的滑动位置即可。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/984

**Comment by duboAndroid** [comment]
![default](https://cloud.githubusercontent.com/assets/22321282/26032222/893aabcc-38c0-11e7-9fef-f7a6cba597c5.png)
请问这个问题解决了嘛，貌似我也是这个 问题，我是想在recyclerView的item中，再加入recyclerView，出了这个 问题

**Comment by duboAndroid** [comment]
我是想实现这样的效果
![default](https://cloud.githubusercontent.com/assets/22321282/26032302/8e42277e-38c2-11e7-92bc-4607a1a12abe.png)
嵌套recyclerView

**Comment by Troll4it** [comment]
@duboAndroid 每个item的img个数是不定的吗？？感觉这个布局不用嵌套的

**Comment by Troll4it** [comment]
@duboAndroid 你可以去看下，宇明大哥这个Adapter     SectionAdapter extends BaseSectionQuickAdapter<MySection>,感觉能做到下面img个数不定的这个种效果

**Comment by Troll4it** [comment]
@CymChad 谢谢。。

**Comment by duboAndroid** [comment]
整个界面是recyclerView显示,但每个recyclerVier的item里有不固定的image,所以要用嵌套
,行我再看下,看有没有什么好的方法,谢谢大家

**Comment by Troll4it** [comment]
@duboAndroid 我写过recyclerView嵌套recyclerview，真的没有出现你说的那个情况，可能是你的代码有错误

**Comment by duboAndroid** [comment]
![default](https://cloud.githubusercontent.com/assets/22321282/26032370/71675a32-38c4-11e7-8344-dc7667a3205f.png)
这里有个setAdapter方法,我不太明白这个方法怎么用,按道理说这个方法还可以继续写一个adapter吧

**Comment by Troll4it** [comment]
你试下(RecyclerView)helper.getView(R.id.rv).setAdapter（ ）；

**Comment by Troll4it** [comment]
@duboAndroid 那个rv就是你的recyclerView，不好意思，我习惯这样命名****

**Comment by duboAndroid** [comment]
-_-,我再试试

**Comment by duboAndroid** [comment]
我这样写他要求是继承普通adapter
![default](https://cloud.githubusercontent.com/assets/22321282/26032459/ef5d3838-38c6-11e7-80be-e9c8554e951d.png)

**Comment by duboAndroid** [comment]
继承了普通的说是类型转换错误...

**Comment by Troll4it** [comment]
我没用过helper.setAdapter这个方法，不太了解，你能把这个方法改成正常setAdapter方法试试(RecyclerView)helper.getView(R.id.rv).setAdapter（ ）

**Comment by duboAndroid** [comment]
行, 感谢,找到好方法,告诉你

**Comment by duboAndroid** [comment]
最后用(RecyclerView)helper.getView(R.id.rv).setAdapter（ ）方法解决了

**Comment by Troll4it** [comment]
@CymChad 

    /**
     * Sets the adapter of a adapter view.
     *
     * @param viewId  The view id.
     * @param adapter The adapter;
     * @return The BaseViewHolder for chaining.
     */
    public BaseViewHolder setAdapter(int viewId, Adapter adapter) {
        AdapterView view = getView(viewId);
        view.setAdapter(adapter);
        return this;
    }

宇明大哥，helper.setAdapter方法的源码是这样的，看来下也没什么毛病。他们出现的类型转换错误，是因为AdapterView转换成RecyclerView或者listView出现的问题吗

**Comment by SephirothLT** [comment]
能请教一下你是怎么处理嵌套recyclerView的吗？

**Comment by SephirothLT** [comment]
@duboAndroid 能请教一下你是怎么处理嵌套recyclerView的吗

**Comment by Troll4it** [comment]
@SephirothLT 正常的一样，嵌套的就在adapter中写就好

**Comment by SephirothLT** [comment]
@Troll4it 那是再为嵌套的重新建一个Adapter，在这个新的Adapter中进行设置数据？这个新的adapter能不能卸载最外层的Adapter中（我是小菜鸟请见谅）

**Comment by Troll4it** [comment]
@SephirothLT 卸载什么意思

**Comment by SephirothLT** [comment]
@Troll4it 不好意思 是写在

**Comment by Troll4it** [comment]
就是写在嵌套Adapter中
