### ISSUE TITLE
第一页数据,remove掉之后偶尔会触发无限加载更多

### ISSUE THREAD

**Issue by dyfan** [CymChad/BaseRecyclerViewAdapterHelper#1094]
当第一页数据已经占满屏幕的时候,renmove掉前面的几个,这个时候加载更多的布局出来,会触发加载更多,这个时候加载更多是无限执行的.

**Comment by CymChad** [comment]
你可以在不满足一页的时候关闭掉上拉监听

**Comment by leijone** [comment]
我这是第一次加载更多正常，然后继续下拉加载更多，也会无限触发加载更多

**Comment by CymChad** [comment]
@leijone 版本，代码。

**Comment by leijone** [comment]
今天刚改用到最近版本，2.9.15
![222](https://cloud.githubusercontent.com/assets/12732626/25736591/707ae9fc-31a5-11e7-9da1-5ec336647dd9.jpg)
![111](https://cloud.githubusercontent.com/assets/12732626/25736599/76cd4f3e-31a5-11e7-8fd0-ffbcad35f29f.jpg)

**Comment by dyfan** [comment]
@leijone   你没有数据调用loadmoreend方法.

**Comment by dyfan** [comment]
@CymChad 
`mAdapter.setNewData(orderEntity.getDetail());
                            mAdapter.disableLoadMoreIfNotFullPage(mRecyclerView);
                            mProgressLayout.showContent();
                            if (mAdapter.getData().size() <= 0) {
                                showEmpty();
                            }`
我调用的这端代码,来处理的不满一屏,不加载更多,但是如果这个时候item充满一屏的情况下,我remove掉几个之后,加载更多的布局出来之后,就会触发无限加载更多

**Comment by leijone** [comment]
有数据的，每次获取数据都调用这个方法

private void setData() {
        dataList.clear();
        for (int i = 0; i < 10; i++) {
            ExamnationListData.ExamnationData data = new ExamnationListData().new ExamnationData();
            data.name = "刀魂体育文化活动策划有限公司";
            data.date = "2017.5.1-5.10";
            data.address = "北京市";
            data.tel = "郝经理 18688816888";
            dataList.add(data);
        }
    }

**Comment by leijone** [comment]
@dyfan Sorry,我知道哪里错了，dataList复用了，重新换了个集合来封装新的数据，就没有这个问题了

**Comment by CymChad** [comment]
@dyfan 你可以在回调里面做处理，判断如果数据不满足一屏幕的时候就关闭上拉加载

**Comment by huang3eng** [comment]
@leijone 请问datalist复用了是什么意思啊
