### ISSUE TITLE
关于触发loadmore功能的小bug

### ISSUE THREAD

**Issue by feer921** [CymChad/BaseRecyclerViewAdapterHelper#1101]
![autoLoadMore方法](https://cloud.githubusercontent.com/assets/6622321/25788777/25da93c6-33de-11e7-8de6-84c86fe007ad.png)

暂且假设mAutoLoadMoreSize = 1(默认值，且觉得这个变量表达意思不够清晰)，当getItemCount()中如果包含了getFooterLayoutCount()==1时，这时触发加载更多的position 代表的就是FooterView了，是不是错了？

**Comment by 1109993488** [comment]
先再是FooterView显示的时候回调的，也就是滑动到FooterView的顶部触发

**Comment by feer921** [comment]
变量名mAutoLoadMoreSize,让人误以为，mAutoLoadMoreSize = 6，当前列表数据大小>=6时就会触发加载更多，而代码实际为，getItemCount()[此时正好==6]-mAutoLoadMoreSize =0了，这时就出现理解上的或者界面上的bug了

**Comment by feer921** [comment]
变量名建议改为包含“偏移最后一个Position的偏移量”

**Comment by feer921** [comment]
变量名建议改为包含“偏移最后一个Position的偏移量”的含义，如;mOffsetLastPos4LoadMore

**Comment by 1109993488** [comment]
感谢你的建议

**Comment by CymChad** [comment]
感谢你的建议，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/1107 已更改名称。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.16'
