### ISSUE TITLE
debug版一切正常，打包成release版会报ClassCastException ViewHolder,混淆已配置！

### ISSUE THREAD

**Issue by CrazyStoneJy** [CymChad/BaseRecyclerViewAdapterHelper#1104]
debug版一切正常，打包成release版会报ClassCastException ViewHolder,混淆已配置！

**Comment by CrazyStoneJy** [comment]
@ChadCym

**Comment by Kusonprince** [comment]
@CrazyStoneJy 同样的问题，混淆配置，但是一打签名包就报这个错，解决了吗？

**Comment by AllenCoder** [comment]
```
-keep class com.chad.library.adapter.** {
   *;
}
```

另外主要main.dex分包问题，如果有必要，可能需要将adapter 分支在class1.dex即第一个dex文件中

**Comment by Kusonprince** [comment]
@AllenCoder 加了该混淆配置了，问题也已经解决了

**Comment by Kusonprince** [comment]
@CrazyStoneJy 我的解决了，对自定义的viewholder单独加混淆设置keep，就可以了

**Comment by CrazyStoneJy** [comment]
@AllenCoder 我的应该是分包的问题，我怎么将adapte放在class1.dex中？我的adapter都是写在不同的模块中

**Comment by CrazyStoneJy** [comment]
@AllenCoder  我反编译后发现继承BaseViewHolder的构造方法没了，这是怎么回事

public class RewardViewHolder extends BaseViewHolder
{

  @BindView(2131689912)
  DeiBeiTextView txt_duty_address;

  @BindView(2131689915)
  DeiBeiTextView txt_duty_location;

  @BindView(2131689910)
  DeiBeiTextView txt_duty_name;

  @BindView(2131689913)
  DeiBeiTextView txt_duty_reward;

  @BindView(2131689918)
  DeiBeiTextView txt_duty_state;

  @BindView(2131689911)
  DeiBeiTextView txt_duty_time;

  @BindView(2131689919)
  DeiBeiTextView txt_receive_duty;

  @BindView(2131689916)
  TextView txt_task_id;
}

**Comment by CrazyStoneJy** [comment]
@Kusonprince 我单独给ViewHolder设置keep还是不行。
#BaseRecyclerViewAdapterHelper
-keep class com.chad.library.adapter.** {
   *;
}
-keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter
-keep public class * extends com.chad.library.adapter.base.BaseViewHolder

**Comment by Kusonprince** [comment]
@CrazyStoneJy 看到你的回复后，赶紧又去打个包试试，我这的确没报错了

**Comment by CrazyStoneJy** [comment]
@Kusonprince  我的方法数超过限制了，做了分包处理，估计是这块的问题

**Comment by Kusonprince** [comment]
@CrazyStoneJy 不应该啊，我也做了分包

**Comment by CrazyStoneJy** [comment]
@Kusonprince 那你是怎么配的混淆

**Comment by Kusonprince** [comment]
@CrazyStoneJy 
public static class ViewHolder extends BaseViewHolder implements NonProguard
-keep interface com.********.NonProguard
-keep class * extends com.**********.NonProguard { *; }
NonProguard是个空接口，这种写法是以前的项目领导写的

**Comment by AllenCoder** [comment]
问题是否已解决？

**Comment by AllenCoder** [comment]
细节问题群上联系我。，或者邮件发送apk给我

**Comment by CrazyStoneJy** [comment]
自定义ViewHolder还是会报错，直接用BaseViewHolder是好的

**Comment by CrazyStoneJy** [comment]
@AllenCoder 好

**Comment by CrazyStoneJy** [comment]
@AllenCoder 群号多少

**Comment by AllenCoder** [comment]
558178792

**Comment by caldremch** [comment]
#添加以下混淆规则可解决
#保留继承于BaseViewHolder的内部类不被混淆
-keep class $ extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
(...);
}
