### ISSUE TITLE
能不能在加一个侧滑删除的功能啊

### ISSUE THREAD

**Issue by hegaojian** [CymChad/BaseRecyclerViewAdapterHelper#1106]

**Comment by missu263** [comment]
能不能 加一个侧滑菜单的功能

**Comment by CymChad** [comment]
侧滑菜单功能是itemview的功能，本库为adapter，如果添加了侧滑菜单就耦合了，建议可以配合独立的侧滑菜单的第三方lib进行组合使用，这样更为灵活。

**Comment by CymChad** [comment]
可组合BRVAH使用：https://github.com/anzaizai/EasySwipeMenuLayout
