### ISSUE TITLE
ExpandableListView 效果   点击group 如何更新 子item的数据啊

### ISSUE THREAD

**Issue by caoeryang** [CymChad/BaseRecyclerViewAdapterHelper#1108]

**Comment by FrankKwok** [comment]
@caoeryang 请详细描述问题

**Comment by caoeryang** [comment]
点击 group  更新该条目下 item 的数据  比如 group 是蜀国 item 是刘备     当我点击蜀国  我想把刘备改成诸葛亮   如何操作

**Comment by FrankKwok** [comment]
Group有getSubItems()方法，应该可以去里面找到要更新的数据

**Comment by CymChad** [comment]
@FrankKwok 正解，找到准确的数据源，进行更新即可。
