### ISSUE TITLE
给条目子View设置点击事件为什么条目也会有点击效果

### ISSUE THREAD

**Issue by liangjingkanji** [CymChad/BaseRecyclerViewAdapterHelper#1112]
点击效果就是点击有声音和振动反馈. 
能否修复

**Comment by liangjingkanji** [comment]
什么点击事件都不加也会有点击反馈....

**Comment by AllenCoder** [comment]
1. 贴出详细的item布局配置代码 
2. 使用最新版的adapter.setOnItemChildClickListener 监听itemchild的点击事件

**Comment by liangjingkanji** [comment]
什么点击事件都不加, Adapter什么都不写, 一样有点击反馈
![](http://ww1.sinaimg.cn/large/006tNbRwly1ffg3v45rfnj315408g0t7.jpg)

**Comment by CymChad** [comment]
我自己用了两台手机测试都没有出现你说的问题，是不是你手机设置了什么？你可以多找几台手机测试一下。

**Comment by liangjingkanji** [comment]
很郁闷啊, 为什么我就是有, 明明没有加任何点击事件

**Comment by CymChad** [comment]
@liangjingkanji 你测试所有手机都有？
你可以上传你的apk我这边试试看。

**Comment by liangjingkanji** [comment]
我怎么上传啊, 我没做加固, 要不我加你好友发你看看可以吗

**Comment by CymChad** [comment]
54050520 陈宇明

**Comment by liangjingkanji** [comment]
Adapter 默认给Item绑定了OnClickListener. 就会被系统认为是可点击的控件. 如果用户开了点击声音提示

**Comment by liangjingkanji** [comment]
Adapter如果默认给Item绑定了OnClickListener监听器, 会让系统认为该Item控件属于有点击事件的控件. 用户如果开了点击声音提示就会导致点击Item什么地方都会有声音提示. 用户体验不是很好. 建议取消默认的绑定点击监听器.

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.16'
