### ISSUE TITLE
关于setHeaderAndEmpty(true)

### ISSUE THREAD

**Issue by SheepYang1993** [CymChad/BaseRecyclerViewAdapterHelper#1114]
当数据为空的时候，同时显示headview和emptyview，emptyview的高度没有扣去headview的高度

**Comment by CymChad** [comment]
恩，是的，高度又开发者自定义的，adapter没有做任何处理。不过这个也可以当成一个可优化的建议。https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/907
