### ISSUE TITLE
scrollView中嵌套recyclery时

### ISSUE THREAD

**Issue by duboAndroid** [CymChad/BaseRecyclerViewAdapterHelper#1115]
scrollView中嵌套recyclery时，当界面显示有recyclerView的数据，这时recycler会有自己的滑动效果，怎么实现滑动的是scrollview呢？我在尝试添加footview

**Comment by SheepYang1993** [comment]
滑动冲突，计算recyclerView高度再设置

**Comment by duboAndroid** [comment]
最后我是在recycler中加了RelativeLayout

**Comment by CymChad** [comment]
解决方法有多种，两位说的都是解决方案之一，👍

**Comment by yxyaxng** [comment]
recyclery.setNestedScrollingEnabled(false) 最简单的设置
