### ISSUE TITLE
2.8.8 添加对item 点击，长按事件的支持方式有点太刻苦了。如果使用延迟的方式会好一些。

### ISSUE THREAD

**Issue by VectorWen** [CymChad/BaseRecyclerViewAdapterHelper#1116]
```java
    //代码片段来之v2.8.8
    ...
    default:
        baseViewHolder = onCreateDefViewHolder(parent, viewType);
        bindViewClickListener(baseViewHolder);
```
代码在创建ViewHolder 后立刻设计了监听器。（自己添加item 事件的做法，创建ViewHolder 的时候直接添加事件）。那么就会把自己设计的监听器覆盖掉了。（强硬点说已经不兼容以前版本了。）

建议：

```java
    //等用户需要item 点击事件才去绑定
    public void setOnItemClickListener(@Nullable OnItemClickListener listener) {
        bindViewClickListener();
        mOnItemClickListener = listener;
    }
```

**Comment by AllenCoder** [comment]
1. 这种添加方案确实是会强制添加，考虑到只需要在creatViewHolder时才会调用，效率会高很多，后续单独添加需要遍历itemView，效率比较低
2. 如果需要自己添加控制item的点击，后续版本新增一个开关，可以关闭这项功能，让用户自己实现item的点击

**Comment by VectorWen** [comment]
现在问题是，我开始使用的版本<2.8.8，那么我就要自己为item 添加事件，代码已经写了。之后升级到>2.88 版本，多了item 事件，但是我之前写的事件全部被覆盖了。如果我要使用新版本的库，那么我就要改掉我自己添加的事件监听。相当于，我升级到新版本，我的部分代码就不能跑了，相当于不兼容。现在强迫我只能使用2.8.7 版本。

**Comment by CymChad** [comment]
@VectorWen 收到问题，我们内部讨论一下，看有没有更好的解决方案。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.16'

**Comment by VectorWen** [comment]
效率好高哦。向你们学习。
