### ISSUE TITLE
上拉加载的问题，以及设置不现实动画条目数的问题！

### ISSUE THREAD

**Issue by 897902334** [CymChad/BaseRecyclerViewAdapterHelper#1117]
版本：2.9.15
今天用大神的库试了下，  上拉加载  只会触发一次，可以成功添加数据到列表中，但是当我第二次上拉的时候，只会有提示“正在加载中···”  但是没有走onLoadMoreRequested()方法，一直提示“正在加载中···”，  很是纠结！ 还有，我设置了adapter.setNotDoAnimationCount(7); 不让前7个条目显示动画效果，但是他还是显示！！！  

这是初始化方法：
protected void initData() {
        model=new CategoryModel(context);
        model.addResponseListener(this);
        setRefreshing(true); //开启下拉刷新
        recyclerView.setLayoutManager(new LinearLayoutManager(context));
        refreshLayout.setOnRefreshListener(this);
        adapter=new CategoryAdapter(R.layout.item_category_fragment,model.getCategoryList());
        adapter.setOnLoadMoreListener(this,recyclerView);
        adapter.setNotDoAnimationCount(7);
        recyclerView.setAdapter(adapter);
        loadData(); //请求数据
    }
------------------------------------------------

这是请求回调：

//这个是请求成功的回调
@Override
    public void onResponseSuccess(String code, Object result) {
        LogUtil.e(result);
        setRefreshing(false);
        if (!ArrayUtil.isEmptyList(model.getCategoryList())) {

            if (isFirst) { //如果是首次加载，那么就刷新adapter 不需要setNewData();
                adapter.notifyDataSetChanged();
                isFirst=false;
                return;
            }

            if (page == 1) { //如果页数等于1，那么说明是下拉刷新获取的数据
                adapter.setNewData(model.getCategoryList());
            }else{  //如果页数不是1 那么说明是上拉加载
                refreshLayout.setEnabled(false);
                adapter.addData(model.getCategoryList());
                adapter.setEnableLoadMore(true);
            }
            refreshLayout.setEnabled(true);

        }else {
            ToastUtil.showViewToast(context,"暂无数据");
        }
    }

**Comment by 1109993488** [comment]
#764

**Comment by 897902334** [comment]
上拉加载问题解决了！谢大神！！   那为啥 我设置了条目不显示动画，  不起作用呢？？？

**Comment by 1109993488** [comment]
你怎么设置的不显示动画？

**Comment by 897902334** [comment]
adapter.setNotDoAnimationCount(7);   这句话的意思不是     让 RecyclerView 的前7个条目不显示动画效果么？？？

**Comment by 1109993488** [comment]
对，如果设置了isFirstOnly(false)就没用了

**Comment by 897902334** [comment]
我设置的isFirstOnly(true) 它还是有动画，  不知道为啥！  因为条目复杂的情况，有动画在低配手机上显示很卡，所以我想把动画效果去掉，   或者说  有没有直接去掉动画效果的设置啊？？  我不要动画了！！！

**Comment by 1109993488** [comment]
不调用openLoadAnimation就不开启动画
