### ISSUE TITLE
滚动问题

### ISSUE THREAD

**Issue by jin4074** [CymChad/BaseRecyclerViewAdapterHelper#112]
感谢，很好用的一个库。
但我在使用时发现一个问题，我的item上有一个小图标，这个图标根据对象里面的某个变量变化，这样当我重复上下滚动的时候，这些图标就乱掉了，根对象的变量并不一致。比如1显示，0隐藏，然后重复滚动就会变成图标全部没掉了。
我现在的解决方法是创建多个相同布局viewType，有没有更好的解决方法呢？

**Comment by AllenCoder** [comment]
你好，欢迎使用这个库。上下重复滚动涉及到holder复用的的缓存问题，你应该解决是解决你的 item 里面 image 的缓存问题。你应该考虑到 item 里面初始化图标的类型，加载中，以及已经加载完成结果的图标，已经有很多成熟的第三库支持并解决了这个问题。图片库的处理超出了 apater 的职责范围了。其实你可以每次设置 image 前对图片资源或者背景清空，再重新设置，但这种暴力方式会造成 holder 的复用效果差。请酌情考虑。

**Comment by jin4074** [comment]
意思是只能通过在item里面直接指定图标类型来解决吗？不好意思，你所指的第三方库能否举例，我不知道应该以什么样的关键字来查找这个问题，谢谢。

**Comment by jin4074** [comment]
感谢回复，知道问题所在了。

**Comment by jesse920524** [comment]
@jin4074 请教这个如何解决的?
