### ISSUE TITLE
数据未满一屏的情况下，自动加载

### ISSUE THREAD

**Issue by xhf840147988** [CymChad/BaseRecyclerViewAdapterHelper#1122]
我在数据未满一屏的情况下，会出自动加载一次的情况，调用mQuickAdapter.disableLoadMoreIfNotFullPage()这个方法，无效，请问该如何解决？

**Comment by tysheng** [comment]
1.请看方法注释，一般能解决

2.在issue里搜索disableLoadMoreIfNotFullPage
