### ISSUE TITLE
在headView中包含一个 RecyclerView，进入页面后总是自动定位到header中的RecyclerView，而不是header顶部

### ISSUE THREAD

**Issue by zgh0711** [CymChad/BaseRecyclerViewAdapterHelper#1123]
如标题描述，在 headView 中包含一个 RecyclerView，进入页面后总是自动定位到 header 中的RecyclerView，而不是header顶部。
如果是单个 RecyclerView 就没有这个情况，单个 RecyclerView 添加了 header 后，进入页面后的初始位置就是在 header 顶部。
我想让 header 中有 RecyclerView 的时候进入页面时也是定位到 header 顶部，请问该怎么做？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/984
