### ISSUE TITLE
如果能将不同场景定义不同的adapter,能全部在一个adapter中实现就好了,这样就可只需要定义一个adapter就可以满足任何场景

### ISSUE THREAD

**Issue by HelloWmz** [CymChad/BaseRecyclerViewAdapterHelper#1124]

**Comment by CymChad** [comment]
你的意思是组合所有adapter的功能？

**Comment by CymChad** [comment]
如:多类型+分组？

**Comment by HelloWmz** [comment]
恩是的




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年5月15日(星期一) 下午3:50
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: ":...:"<1170155848@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 如果能将不同场景定义不同的adapter,能全部在一个adapter中实现就好了,这样就可只需要定义一个adapter就可以满足任何场景 (#1124)




如:多类型+分组？

**Comment by CymChad** [comment]
恩，感谢建议，我们也一直在想如何组合更好，正在预研中。

**Comment by HelloWmz** [comment]
我的意思就是能写一个adapter中包含所有的场景的方法就好了




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年5月15日(星期一) 下午4:31
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: ":...:"<1170155848@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 如果能将不同场景定义不同的adapter,能全部在一个adapter中实现就好了,这样就可只需要定义一个adapter就可以满足任何场景 (#1124)




恩，感谢建议，我们也一直在想如何组合更好，正在预研中。

**Comment by CymChad** [comment]
这样做法虽然可以实现，但是考虑到baseadapter无限的变大，显然是不太好的方案。

**Comment by CymChad** [comment]
#907
