### ISSUE TITLE
多样式的item，同时也要能够拖曳

### ISSUE THREAD

**Issue by OCNYang** [CymChad/BaseRecyclerViewAdapterHelper#1126]
因为我的Adapter不能同时继承BaseItemDraggableAdapter和BaseMultiItemQuickAdapter，那这样才能满足这两种需求呢？

**Comment by elfman** [comment]
新建一个Adpater继承BaseMultiItemQuickAdapter，把BaseItemDraggableAdapter的源码复制过来，然后使用这个Adapter，或者反过来应该也行
