### ISSUE TITLE
自动加载问题

### ISSUE THREAD

**Issue by hegaojian** [CymChad/BaseRecyclerViewAdapterHelper#1127]
您好，情况是酱紫的，数据只有2条，页面并没有充满，但是会出发加载更多的监听，再多请求一次，
我看了其他的issues, 于是我设置了 adapter.loadMoreComplete();
                                        adapter.loadMoreEnd(true);
                                        adapter.disableLoadMoreIfNotFullPage(xiaoheibanRecycleview);
但是并没有什么用呢，一进来activity还是会多请求一次，求大神指导

**Comment by CymChad** [comment]
你的版本

**Comment by CymChad** [comment]
参考 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1122
