### ISSUE TITLE
加载更多问题

### ISSUE THREAD

**Issue by Yanqilong** [CymChad/BaseRecyclerViewAdapterHelper#1129]
你好大大，加载更多情况下，当我没有更多数据加载的时候，调用了adapter.loadMoreEnd()，加载更多还是在底部显示，而且回触发我的网络请求多次，但道理应该显示“没有更多数据”，请问是什么原因？当没有数据的时候怎样才能显示“没有更多数据”？

**Comment by CymChad** [comment]
#906

**Comment by CymChad** [comment]
版本，代码。

**Comment by Yanqilong** [comment]
大大你看下，我的版本是2.9.15
代码：
if(mainGoodsAdapter.getData().size() > 0 && goodsBeanList.size() == 0) {
           // mainGoodsAdapter.setEnableLoadMore(true);   //临时解决
            mainGoodsAdapter.loadMoreEnd();
}


也有调用mQuickAdapter.disableLoadMoreIfNotFullPage();没起到效果

**Comment by 1109993488** [comment]
你debug下看是否执行loadMoreEnd，执行完loadMoreEnd是否执行了别的代码

**Comment by Yanqilong** [comment]
有执行的，loadMoreEnd放在我业务代码里面控制，当加载数量不够一页的时候，就会执行，但是没起到效果。我现在将mainGoodsAdapter.setEnableLoadMore(false)零时解决了问题，但是我想在数据加载完后显示提示文字。

**Comment by 1109993488** [comment]
贴一下处理代码

**Comment by CymChad** [comment]
@Yanqilong 问题解决了吗？

**Comment by yangkun19921001** [comment]
作者你好，我目前 使用 BaseAdapter 版本是 2.3.3 在加载更多数据的时候，我调用 mQuickAdapter.loadMoreEnd(); or  mQuickAdapter.loadMoreComplete(); 都没有效果 都报了一个错
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
这个错 当我设置 RecyclerView  滑动 监听的时候在调用 workListAdapter.loadMoreEnd(true); 就可以隐藏了，当数据没有充满屏幕的时候 ，调你提供的方法都没有效果，直接崩溃！麻烦作者看看，谢谢

**Comment by yangkun19921001** [comment]
目前更新到 2.9.16 也不行 直接崩溃

**Comment by 1109993488** [comment]
Cannot call this method while RecyclerView is computing a layout or scrolling，这个错是需要在post里调上面的方法，2.9.16崩溃的日志是？
