### ISSUE TITLE
2.9.16

### ISSUE THREAD

**Issue by Itachi110** [CymChad/BaseRecyclerViewAdapterHelper#1131]
Promotions promotions = JSON.parseObject(response, Promotions.class);
                        if (promotions != null) {
                            List<Promotions.PromotionsBean> promotionsBeanList = promotions.getPromotions();
                            if (offset == 0) {
                                list.clear();
                            }
                            if (promotionsBeanList != null && promotionsBeanList.size() != 0) {
                                list.addAll(promotionsBeanList);
                                adapter.loadMoreComplete();
                            } else {
                                adapter.loadMoreEnd();
                            }
                        } 

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{5b00d2a position=3 id=-1, oldPos=3, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}

问题描述：加了Header，然后加了加载更多，用的SwipeRefreshLayout的下拉刷新，A界面加载列表，点击后跳B界面操作完毕，回到A界面后刷新列表（这时请求到的数据少了一条），然后酒报数组越界错误

**Comment by 1109993488** [comment]
clear的shi'hou时候最好是调用setNewData，或者自己加上notifyDataSetChanged
