### ISSUE TITLE
recyclerview addheaderview为recyclerview

### ISSUE THREAD

**Issue by Anayuta** [CymChad/BaseRecyclerViewAdapterHelper#1132]
headview里的recyclerview的适配器的convert 不调用。。。。。还是我使用姿态不对 (┬＿┬)

**Comment by FrankKwok** [comment]
没太理解什么意思

**Comment by Anayuta** [comment]
@FrankKwok  就是原本有一个recyclerview,有一个适配器。我在这个recyclerview里addheadview，但是headview里也有一个recyclerview，头部的headview也有一个适配器，我发现头部headview里适配器的convert不执行。

**Comment by FrankKwok** [comment]
原来如此，没有这样用过，所以也没遇到这个问题

**Comment by Anayuta** [comment]
@FrankKwok  我也是第一次这样用，中枪了。已经蒙蔽。。。。

**Comment by FrankKwok** [comment]
怎么使用的，能看代码吗？

**Comment by Anayuta** [comment]
@FrankKwok 
添加的头部的view
mBaseRefreshAdapter.addHeaderView(getHeadView(), 0);
initAddHeadView(getHeadView());
======头部里的recyclerview=====
 mVideoCorrelationAdapter = new VideoCorrelationAdapter(null);
        LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        rlvVideoCorrelation.setLayoutManager(layoutManager);
        rlvVideoCorrelation.setAdapter(mVideoCorrelationAdapter);

**Comment by FrankKwok** [comment]
头部里的recyclerview的adapter使用的也是这个库吗？

**Comment by FrankKwok** [comment]
头部里的recyclerview的adapter使用的也是这个库吗？

**Comment by Anayuta** [comment]
@FrankKwok  是啊，都是这个库。头里的recyclerview的适配器的convert 不执行

**Comment by FrankKwok** [comment]
是不是没绑定布局xml

**Comment by Anayuta** [comment]
绑定了的

  public class VideoCorrelationAdapter extends BaseQuickAdapter<PublishInfo, BaseViewHolder> {

        public VideoCorrelationAdapter(@Nullable List<PublishInfo> data) {
            super(R.layout.item_recordview_headview_list, data);
        }

**Comment by FrankKwok** [comment]
那刷新头部数据的代码呢

**Comment by Anayuta** [comment]
if (isLoadMore) {
                    mVideoCorrelationAdapter.addData(datas);
                } else {
                    mVideoCorrelationAdapter.setNewData(datas);
                }

**Comment by FrankKwok** [comment]
……，我觉得都是对的啊，怎么会不执行呢

**Comment by Anayuta** [comment]
@FrankKwok 所以我就出现现在的蒙蔽状态了。。。。:-(

**Comment by Anayuta** [comment]
@FrankKwok   你要不搞个demo试试，我晚上回去也搞个demo试试。

**Comment by FrankKwok** [comment]
那只有明天在搞了

**Comment by Anayuta** [comment]
@FrankKwok  晚上回去注定不加班的节奏。😄

**Comment by FrankKwok** [comment]
😄是的，最近太累了

**Comment by Anayuta** [comment]
@FrankKwok 好吧，虽然是挺累的。但是还是得晚上回去整  😄。明天你也试试。

**Comment by FrankKwok** [comment]
怎么样了，我试了，确实是不调用convert的

**Comment by Anayuta** [comment]
@FrankKwok 是的，所以很纠结。

**Comment by Anayuta** [comment]
@FrankKwok 有没想到解决方案？把headview的列表适配器换一个？

**Comment by FrankKwok** [comment]
为什么需要在header里面加recyclerview

**Comment by Anayuta** [comment]
@FrankKwok  需要在那展示一系列的视频数据

**Comment by FrankKwok** [comment]
用viewpager呢？

**Comment by Anayuta** [comment]
？？？

**Comment by FrankKwok** [comment]
你是怎么展示视频数据？

**Comment by Anayuta** [comment]
recyclerview列表啊。原有的结构是评论数据，现在不改变原有的结构，在评论里addheadview。

**Comment by FrankKwok** [comment]
那用多类型item好了

**Comment by Anayuta** [comment]
这样感觉还是改变了原有的结构~~

**Comment by FrankKwok** [comment]
什么场景会是展示一堆视频，下面跟着一堆评论呢

**Comment by Anayuta** [comment]
相关视频，精彩评论。

**Comment by FrankKwok** [comment]
为什么相关视频不做成水平方向滑动的呢

**Comment by Anayuta** [comment]
这个就是ui这样搞，所以没办法。

**Comment by FrankKwok** [comment]
目前就想到多ItemType这个方案

**Comment by Anayuta** [comment]
itemtype的话，评论和视频的数据类型是不一样的。

**Comment by FrankKwok** [comment]
可以不一样的，你可以看Demo

**Comment by Anayuta** [comment]
好，实在不行就改吧。评论那个是共用的~~~尴尬

**Comment by FrankKwok** [comment]
你可以扩展的，不动评论类，增加一个PinglunAdapter类

**Comment by Anayuta** [comment]
MultiItemEntity 然后都得继承这个~

**Comment by FrankKwok** [comment]
可以让ShipinAdapter和PinglunAdapter继承MultiItemEntity,视频类与评论类都可以不动的

**Comment by Anayuta** [comment]
看看你的实现方案，估计我想的和你的不一样。

**Comment by FrankKwok** [comment]
私聊好了，加我QQ（823212676）

**Comment by Anayuta** [comment]
好

**Comment by CymChad** [comment]
headview里的recyclerview的适配器的convert 不调用，这个不科学，因为有很多问题是head为rv不置顶为题也就说明这个是可运行的然后才会出现焦点问题。

**Comment by Anayuta** [comment]
@CymChad 真不执行啊~~~

**Comment by CymChad** [comment]
稍等，我这边测试一下。

**Comment by Anayuta** [comment]
好  麻烦了。

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/26137287/cbc929fc-3af3-11e7-8115-622e3722c78a.png)

我这这边测试没有问题

**Comment by Anayuta** [comment]
@CymChad 这不科学啊，我和@FrankKwok 用的都不执行~~~

**Comment by CymChad** [comment]
我把相关代码打包，你测试看下吧。

**Comment by Anayuta** [comment]
好的

**Comment by CymChad** [comment]
[1132.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/1006509/1132.zip)
java和res我都打包了，你可以看下。

**Comment by CymChad** [comment]
我猜测是不是你获取头部的rv的时候也是获取到mian的rv去了。

**Comment by CymChad** [comment]
你先看看吧，有问题再提。

**Comment by FrankKwok** [comment]
[Demo](https://github.com/FrankKwok/RVInHeader),之前header里的RV忘记添加LayoutManager了，修改了之后是没问题的

**Comment by CymChad** [comment]
@FrankKwok 感谢
