### ISSUE TITLE
请问能实现仿照微信或者QQ的数据列表的侧滑吗？

### ISSUE THREAD

**Issue by qq84266454** [CymChad/BaseRecyclerViewAdapterHelper#1133]
请问如何实现类似QQ或者微信对于聊天条目左滑出现选项。点击选项执行不同的操作。

**Comment by CymChad** [comment]
不能，因为考虑到这是item view 的问题，如果adapter做了会有所耦合所以没有加入该功能，建议配置第三方独立的侧滑删除功能进行组合使用。

**Comment by CymChad** [comment]
可组合BRVAH使用：https://github.com/anzaizai/EasySwipeMenuLayout
