### ISSUE TITLE
请暴露空参的构造方法

### ISSUE THREAD

**Issue by Tiannuo** [CymChad/BaseRecyclerViewAdapterHelper#1135]
就是我不要自己传个list，直接用框架里面的list，现在是暴露的构造方法必须要传，希望保留不要传list的构造方法

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
今天会出一个版本

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.17'

**Comment by CymChad** [comment]
有问题，如果添加了空的构造，会导致开发者，新建adapter的时候，不会自动出现构造，需要手动添加构造，过于麻烦，所以有点得不偿失，下个版本将去除空构造

**Comment by Tiannuo** [comment]
大佬不是吧，之前因为默认构造方法没有所以继承的时候才会自动出现，但是这个不能为了去实现自动构造而构造把

**Comment by CymChad** [comment]
但是每次都需要自己写构造，然后调用父类构造。

**Comment by CymChad** [comment]
我觉得可以写一个只传布局的构造。

**Comment by Tiannuo** [comment]
好吧，我本来是想布局也放在adapter里面的

**Comment by CymChad** [comment]
你可以写成一个不需要传参的，但是一定要在adapter设置布局呀，这个不冲突吧？
