### ISSUE TITLE
关于拖拽和使用一个侧滑删除库的冲突

### ISSUE THREAD

**Issue by Tiannuo** [CymChad/BaseRecyclerViewAdapterHelper#1136]
https://github.com/mcxtzhang/SwipeDelMenuLayout
我使用了这个库之后，长按拖拽就不能使用了

**Comment by CymChad** [comment]
应该是事件触摸冲突了

**Comment by CymChad** [comment]
由于牵扯到第三方库的源码修改，所以目前无法解决冲突。

**Comment by Tiannuo** [comment]
谢谢大佬

**Comment by zjxuzhj** [comment]
无法解决你谢谢啥。。。我也卡着了

**Comment by CymChad** [comment]
https://github.com/anzaizai/EasySwipeMenuLayout  使用这个库

**Comment by CymChad** [comment]
@zjxuzhj @Tiannuo

**Comment by zjxuzhj** [comment]
@CymChad 我用了，但这个库的作者觉得侧滑和拖拽不应该同时使用，因此这个库也是冲突的
