### ISSUE TITLE
RecyclerView 在有虚拟按键的手机上例如华为mate7，只显示部分视图。

### ISSUE THREAD

**Issue by jamin918** [CymChad/BaseRecyclerViewAdapterHelper#1140]
如标题，setLayoutManager 为LinearLayoutManager，在华为mate7上面RecyclerView显示不全（待办事项一共有3个item，只显示了一个item），将虚拟按键隐藏后会显示多一点（显示出2个item）。在三星note3、oppo A59m这两款没有虚拟按键的手机上显示正常。使用的BaseRecyclerViewAdapterHelper版本是2.8.6。
   代码中使用：
mUndoAdapter = new QuickAdapter1(R.layout.item_journal_list);
private class QuickAdapter1 extends BaseQuickAdapter<Events, BaseViewHolder> {

        public QuickAdapter1(int LayoutId){
            super(LayoutId);
        }

        @Override
        protected void convert(BaseViewHolder helper, Events item) {

            helper.setText(R.id.tv_title, item.getTitle());
            helper.setText(R.id.tv_date, item.getDate());

            helper.addOnClickListener(R.id.iv_edit_journal);
            helper.addOnClickListener(R.id.iv_delete_journal);
        }
    }

List<Events> undoData = DataServer.getEventsUndoData(this, 3);
mUndoAdapter.setNewData(undoData);

[异常显示截图](https://github.com/jamin918/gif_repository/blob/master/test.gif)
布局如下：
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white_text_color"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="66dp"
        android:background="@color/bg_red">

        <ImageView
            android:id="@+id/iv_report_back"
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:layout_marginLeft="5dp"
            android:layout_marginBottom="15dp"
            android:layout_alignParentBottom="true"
            android:scaleType="centerInside"
            android:src="@mipmap/fanhui"/>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:layout_alignTop="@id/iv_report_back"
            android:textColor="@color/white_text_color"
            android:textSize="16sp"
            android:text="上报"/>

    </RelativeLayout>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <RelativeLayout
                android:id="@+id/rl_events_category"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp">

                <TextView
                    android:id="@+id/tv_events"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="true"
                    android:textColor="@color/black_text_color"
                    android:text="事件分类"/>

                <TextView
                    android:id="@+id/tv_event_category"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="30dp"
                    android:layout_toRightOf="@id/tv_events"
                    android:text="游行示威"/>

                <ImageView
                    android:id="@+id/iv_events_category"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="true"
                    android:layout_marginRight="15dp"
                    android:layout_alignParentRight="true"
                    android:src="@mipmap/zhankai"/>

            </RelativeLayout>

            <View
                android:layout_width="match_parent"
                android:layout_height="0.3dp"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp"
                android:background="@color/gray_text_color"/>

            <RelativeLayout
                android:id="@+id/rl_address"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp">

                <TextView
                    android:id="@+id/tv_address"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="true"
                    android:textColor="@color/black_text_color"
                    android:text="归属地"/>

                <ImageView
                    android:id="@+id/iv_chose_address"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="true"
                    android:layout_marginRight="15dp"
                    android:layout_alignParentRight="true"
                    android:src="@mipmap/zhankai"/>

                <TextView
                    android:id="@+id/tv_event_address"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="43dp"
                    android:layout_marginRight="15dp"
                    android:layout_toRightOf="@id/tv_address"
                    android:layout_toLeftOf="@id/iv_chose_address"
                    android:text="太原市晋源区金胜镇"/>

            </RelativeLayout>

            <View
                android:layout_width="match_parent"
                android:layout_height="0.3dp"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp"
                android:background="@color/gray_text_color"/>

            <RelativeLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp">

                <TextView
                    android:id="@+id/tv_events_desc"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="true"
                    android:textColor="@color/black_text_color"
                    android:text="事件说明"/>

                <EditText
                    android:id="@+id/et_events_desc"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="30dp"
                    android:layout_toRightOf="@id/tv_events_desc"
                    android:minWidth="180dp"
                    android:background="@null"
                    android:textSize="14sp"
                    android:hint="请输入事件的具体描述"/>

            </RelativeLayout>

            <View
                android:layout_width="match_parent"
                android:layout_height="0.3dp"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp"
                android:background="@color/gray_text_color"/>

            <RelativeLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp">

                <TextView
                    android:id="@+id/tv_contact_name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="true"
                    android:textColor="@color/black_text_color"
                    android:text="联系人"/>

                <EditText
                    android:id="@+id/et_contact_name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="45dp"
                    android:layout_toRightOf="@id/tv_contact_name"
                    android:minWidth="180dp"
                    android:background="@null"
                    android:textSize="14sp"
                    android:hint="请输入联系人姓名"/>

            </RelativeLayout>

            <View
                android:layout_width="match_parent"
                android:layout_height="0.3dp"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp"
                android:background="@color/gray_text_color"/>

            <RelativeLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp">

                <TextView
                    android:id="@+id/tv_contact_phone"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="true"
                    android:textColor="@color/black_text_color"
                    android:text="电话"/>

                <EditText
                    android:id="@+id/et_contact_phone"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="60dp"
                    android:layout_toRightOf="@id/tv_contact_phone"
                    android:inputType="number"
                    android:minWidth="180dp"
                    android:background="@null"
                    android:textSize="14sp"
                    android:hint="请输入联系电话"/>

            </RelativeLayout>

            <View
                android:layout_width="match_parent"
                android:layout_height="10dp"
                android:layout_marginTop="15dp"
                android:background="@color/bg_content"/>

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="25dp">

                <TextView
                    android:id="@+id/tv_upload"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textColor="@color/black_text_color"
                    android:text="上传\n(照片/视频)"/>

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recyclerView"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_toRightOf="@id/tv_upload"
                    android:layout_marginLeft="5dp"
                    android:choiceMode="singleChoice"
                    android:divider="@null"
                    android:fadingEdge="none"
                    android:listSelector="@android:color/transparent"
                    android:scrollbarStyle="outsideOverlay"
                    app:layoutManager="android.support.v7.widget.GridLayoutManager"
                    app:spanCount="3"
                    tools:listitem="@layout/item_list_image"/>

            </RelativeLayout>

            <Button
                android:id="@+id/btn_submit_report"
                android:layout_width="140dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="35dp"
                android:layout_marginBottom="30dp"
                android:layout_gravity="center_horizontal"
                android:background="@drawable/selector_round_red"
                android:textColor="@color/white_text_color"
                android:textSize="15sp"
                android:text="提交"/>

            
            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingLeft="15dp"
                android:paddingTop="10dp"
                android:paddingBottom="10dp"
                android:background="@color/bg_content"
                android:textColor="@color/text_red"
                android:text="待办事项"/>

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv_list_events_undo"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>

            <TextView
                android:id="@+id/tv_read_more_undo"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:clickable="true"
                android:layout_margin="15dp"
                android:layout_gravity="center_horizontal"
                android:text="@string/read_more"/>

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingLeft="15dp"
                android:paddingTop="10dp"
                android:paddingBottom="10dp"
                android:background="@color/bg_content"
                android:textColor="@color/text_red"
                android:text="已办事项"/>

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv_list_events_did"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>

            <TextView
                android:id="@+id/tv_read_more_did"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:clickable="true"
                android:layout_margin="15dp"
                android:layout_gravity="center_horizontal"
                android:text="@string/read_more"/>

        </LinearLayout>

    </ScrollView>

</LinearLayout>

**Comment by jamin918** [comment]
麻烦看一下是我使用姿势不对还是别的什么原因？谢谢。

**Comment by CymChad** [comment]
你可以用demo在你的手机上跑一下，看是不是也出现你说的问题。

**Comment by jamin918** [comment]
That is a good idea.

**Comment by jamin918** [comment]
找到问题的原因了：是ScrollView嵌套RecyclerView导致的，与本库无关，很感谢作者及时回复。
[遇到同样问题还没解决的童鞋，可以参考这个](https://my.oschina.net/yaly/blog/810324)

**Comment by CymChad** [comment]
👍
