### ISSUE TITLE
2.9.16 添加HeaderView后，notifyItemChanged(position)刷新的位置不对。

### ISSUE THREAD

**Issue by ZhengShang** [CymChad/BaseRecyclerViewAdapterHelper#1142]
你好 ~
比如我的RecyclerVIew里面有10条数据，添加headerView后，点击第三条item，此时的position=2，然后网络请求返回后，需要刷新item2，但是现实的效果确实第二条item被刷新了。

**Comment by FrankKwok** [comment]
notifyItemChanged是RecyclerView.Adapter中的方法，应该自己计算偏移量来刷新
