### ISSUE TITLE
Scrollview嵌套revycleview，会一直调用onLoadMoreRequested

### ISSUE THREAD

**Issue by luXiuKun** [CymChad/BaseRecyclerViewAdapterHelper#1145]
这个应该怎么处理？

banner作为头布局，如果没有数据，设置空布局，但是我想保留banner。。。。打算banner不作为头布局，外面在嵌套ScrollView,但是会一直回调onLoadMoreRequested

**Comment by CymChad** [comment]
#906

**Comment by luXiuKun** [comment]
我不知道是不是我写法有问题，空布局没效果

nodataView = LayoutInflater.from(getActivity()).inflate(R.layout.layout_nodata, (ViewGroup) recyview.getParent(), false);
        baseQuickAdapter.setHeaderAndEmpty(true);
        baseQuickAdapter.setEmptyView(nodataView);

**Comment by luXiuKun** [comment]
#510 这个方法也没了

**Comment by luXiuKun** [comment]
瞎比，关了吧，忘了数据有缓存了

**Comment by luXiuKun** [comment]
![image](https://cloud.githubusercontent.com/assets/14215762/26281537/9f4df83a-3e2c-11e7-8201-de0f9cfc67e5.png)
数据不满一屏时，会一直回调onLoadMoreRequested知道超过一屏，历史问题也看了，设置了也没用

**Comment by luXiuKun** [comment]
2.9.16版本

**Comment by tysheng** [comment]
用这个，你现在的做法糟糕透了
```
 /**
     * Call before {@link RecyclerView#setAdapter(RecyclerView.Adapter)}
     *
     * @param isHeadAndEmpty false will not show headView if the data is empty true will show emptyView and headView
     */
    public void setHeaderAndEmpty(boolean isHeadAndEmpty) {
        setHeaderFooterEmpty(isHeadAndEmpty, false);
    }
```

**Comment by luXiuKun** [comment]
用了，现在问题是 数据不满一屏时，会一直调用onLoadMore,直到数据满一屏，我也设置代码了，如上面的图片

**Comment by tysheng** [comment]
你最后 setOnLoadMoreListener 相当于又把 loadmore 给打开了啊

**Comment by luXiuKun** [comment]
啊？onLoadMore是自动调用的啊，不需要设置监听啊，囧

**Comment by tysheng** [comment]
你设置监听 相当于又打开了

2017年5月24日 18:52，"luXiuKun" <notifications@github.com>写道：

**Comment by AngelBo** [comment]
我也是的 早就发现这个问题了  一直存在这个问题

**Comment by AngelBo** [comment]
嵌套的话  不行哦  一直调用的 没到底部 就已经加载所有数据了  有多少数据就一直加载的哦

**Comment by grapefruit330** [comment]
那请问要如何解决这个问题呢

**Comment by Genuies** [comment]
遇见这个问题了，我说一下自己的解决思路，不要用adapter自带的自动加载更多，监听scrollview的滑动，滑动到底的时候，自己调用加载更多的方法

**Comment by heiyeliuying** [comment]
这个问题在2021年了，依旧存在，希望作者大大给大家做个好的demo示例。我的解决方案如下：
原来：scrollview嵌套了recyclerview。
修改后：去掉了scrollview这一层，通过该库的addHeaderView来增加哪些需要参与滚动的UI。
