### ISSUE TITLE
[Improve]Do not use notifyDataSetChanged() in setNewData.

### ISSUE THREAD

**Issue by dyguests** [CymChad/BaseRecyclerViewAdapterHelper#1146]
I saw code `notifyDataSetChanged();` in `com.chad.library.adapter.base.BaseQuickAdapter#setNewData`.

But,Is that better than use code below???:

```
        int oldSize = list.size();
        list.clear();
        list.addAll(items);
        int newSize = list.size();

        if (newSize == oldSize) {
            notifyItemRangeChanged(0, oldSize);
        } else if (newSize > oldSize) {
            notifyItemRangeChanged(0, oldSize);
            notifyItemRangeInserted(oldSize, newSize - oldSize);
        } else {
            notifyItemRangeChanged(0, newSize);
            notifyItemRangeRemoved(newSize, oldSize - newSize);
        }
```

Before code:All item will be flickered.

By this way:The item will not be flickered.

And sorry for my poor English.
:)

**Comment by dyguests** [comment]
话说我这啥不用中文？？？

总之通过 notifyItemRangeChanged(start,count)来更新的itemView时不会闪。
而用 notifyDataSetChanged()来更新的itemView都会闪一下啊。OTL。

**Comment by dyguests** [comment]
See  [https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemRangeChanged(int, int)](url)

This is an item change event, not a structural change event.

And it happened when I use BaseQuickAdapter.

**Comment by dyguests** [comment]
And see
[https://github.com/dyguests/Konachan/blob/master/app/src/main/kotlin/com/fanhl/konachan/ui/common/ListAdapter.kt#L41-L56](https://github.com/dyguests/Konachan/blob/master/app/src/main/kotlin/com/fanhl/konachan/ui/common/ListAdapter.kt#L41-L56)

**Comment by CymChad** [comment]
收到

**Comment by 1109993488** [comment]
notifyItemRangeChanged没有动画，怎么会闪？
如果setNewData的时候操作了Header、Footer可能就会有问题
如果开启加载更多，加载更多会影响item的数量，这样刷新就可能出错

**Comment by dyguests** [comment]
1.我一般会用 默认动画。
2.加载更多时影响item数量，这样刷新刷新的确可能出错，在所有Adapter的listsize变更时加锁怎么样？
2.1.否则的话，像 `addData()`等方法，同样会出现刷新时可能会出错啊。

所以，一种是在开发人员在代码中防止，另一种是做一个`SynchronizedBaseQuickAdapter`???

**Comment by 1109993488** [comment]
Header、Footer是不允许notifyItemChanged的
比如之前没头部刷新后添加了个头部
这时候notify操作的参数就不可控，notify指定条目刷新的时候如果控制不好就会崩溃

**Comment by dyguests** [comment]
Www，sorry，没考虑header的情况，暂时没啥好的解决办法。:(
