### ISSUE TITLE
不满一页的情况

### ISSUE THREAD

**Issue by KingJames6** [CymChad/BaseRecyclerViewAdapterHelper#1148]
调用disableLoadMoreIfNotFullPage虽然不会触发加载更多,但是能看到 加载更多中...  
因为初始化adapter时autoLoadMore()方法中都执行了mLoadMoreView.setLoadMoreStatus(LoadMoreView.STATUS_LOADING);

**Comment by tysheng** [comment]
上具体的代码

**Comment by CymChad** [comment]
有问题再提。

**Comment by Y-JH** [comment]
调用disableLoadMoreIfNotFullPage虽然不会触发加载更多,但是能看到 加载更多中...
因为初始化adapter时autoLoadMore()方法中都执行了mLoadMoreView.setLoadMoreStatus(LoadMoreView.STATUS_LOADING);

这个问题请问解决了吗？怎么解决的？
