### ISSUE TITLE
关于数据更新

### ISSUE THREAD

**Issue by shoushuai** [CymChad/BaseRecyclerViewAdapterHelper#1149]
数据用list.addAll()/list.clear(),刷新适配器用notifyDataSetChanged() ，列表不更新，难道必须用adapter.setNewData()/adapter.addData()吗

**Comment by shoushuai** [comment]
通过用studio自带模拟器加载不出来，使用真机没问题，请问这是什么原因？

**Comment by CymChad** [comment]
你可以同adapter.getData然后进行操作。

**Comment by shoushuai** [comment]
@CymChad 我现在还需要维护activity中的list数据源，虽然对adapter.getData做一些clear和add操作，那list数据没有变吧

**Comment by CymChad** [comment]
atc 的 list 本质上就是 adapter.getdata
