### ISSUE TITLE
adapter局部刷新问题

### ISSUE THREAD

**Issue by LcTerry** [CymChad/BaseRecyclerViewAdapterHelper#1150]
在调用` /**
     * change data
     */
    public void setData(@IntRange(from = 0) int index, @NonNull T data) {
        mData.set(index, data);
        notifyItemChanged(index + getHeaderLayoutCount());
    }`  这里调用了`notifyItemChanged(index + getHeaderLayoutCount());`     进行局部刷新的时候，如果item包含图片，会发生闪烁！希望能把这个方法`notifyItemChanged(int position, Object payload)`！谢谢

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
`notifyItemChanged `这个方法是系统方法。

**Comment by CymChad** [comment]
局部刷新是要配合DiffUtil，下个大版本的迭代我们会集成DiffUtil，敬请期待。

**Comment by xiaobailong24** [comment]
@CymChad 关注中，希望增加 DiffUtil.

**Comment by KomoriWu** [comment]
recyclerView.getItemAnimator().setChangeDuration(0);// 通过设置动画执行时间为0来解决闪烁问题
