### ISSUE TITLE
实现ExpandableListView 效果，添加头部 

### ISSUE THREAD

**Issue by zou1755815609** [CymChad/BaseRecyclerViewAdapterHelper#1151]
实现ExpandableListView效果 添加头部，点击的时候会报控制针，展开全部报空指针

**Comment by CymChad** [comment]
版本？

**Comment by CymChad** [comment]
已经复现出来了，今天会出一个版本修复

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.17'
