### ISSUE TITLE
BaseMultiItemQuickAdapter 使用中遇到的问题

### ISSUE THREAD

**Issue by yanxinmiao** [CymChad/BaseRecyclerViewAdapterHelper#1152]
比如在app 1.0版本时 某个列表有三种布局类型 （比如type 1,2，3）， 这时候肯定在adapter 构造方法中调用三次这个addItemType() ; 那下个版本1.1 列表的布局类型增加后 （比如type增加了4,5），服务端相应也会返回（4和 5的类型）， 1.0版本就会有问题 。
`
// 这个方法会报错， layouts.get 结果是 null 
    private int getLayoutId(int viewType) {
        return layouts.get(viewType) ；
    }

    protected void addItemType(int type, @LayoutRes int layoutResId) {
        if (layouts == null) {
            layouts = new SparseArray<>();
        }
        layouts.put(type, layoutResId);
    }
`
希望以后的版本能兼容这种情况

**Comment by FrankKwok** [comment]
这个客户端要做控制的，不应该是一个第三方库考虑的问题吧

**Comment by yanxinmiao** [comment]
@FrankKwok 客户端控制 ？ 难道在1.0 版本中解析数据时 把type 不是1 ，2,3的 都剔除掉 ？现在解析json 都是在用gson等工具啊，解析成LIST后再遍历 这样很低效 啊

**Comment by FrankKwok** [comment]
或者在服务端控制，难道正确性不是比效率更重要吗，而且你说的低效我也不是很理解

**Comment by yanxinmiao** [comment]
@FrankKwok 每次请求完服务端，都要遍历list ， 判断mode的type是不是已经是addItemType() 方法里的，感觉这么判断有点low

**Comment by FrankKwok** [comment]
只是low而已，没有更快的方法了，即使把问题延后到这个Helper里，也是没差别的呀，只是把问题扔给别人。。。，况且也不合适

**Comment by FrankKwok** [comment]
服务器根据APP版本返回不同的数据不行吗？

**Comment by CymChad** [comment]
com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.18
