### ISSUE TITLE
为什么直接引用库不行

### ISSUE THREAD

**Issue by ruanguihua** [CymChad/BaseRecyclerViewAdapterHelper#1153]
版本2.0.0

compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.0'这样不可用，必须导入library才能使用？

**Comment by FrankKwok** [comment]
因为这个库没有发布到maven中心库里，参见项目[Wiki](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki)配置之后就可以导入了

**Comment by CymChad** [comment]
@FrankKwok 正解

**Comment by haomengjie** [comment]
1.参见项目Wiki配置，依然gradle不到
2.为什么不发布到jcenter库
