### ISSUE TITLE
下拉刷新界面pull to refresh use 

### ISSUE THREAD

**Issue by qq2460932861** [CymChad/BaseRecyclerViewAdapterHelper#1156]
进入界面什么操作都没有，直接点击item的点击事件，经常响应不到。是需要满足什么条件吗？

**Comment by CymChad** [comment]
使用版本？使用代码？

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
我刚才看了下代码是应该，在adapter里面注册了子控件的点击事件导致的。
helper.addOnClickListener(R.id.img).addOnClickListener(R.id.tweetText).addOnClickListener(R.id.tweetName);

**Comment by CymChad** [comment]
去掉就好了。
