### ISSUE TITLE
加载更多的问题

### ISSUE THREAD

**Issue by imkobedroid** [CymChad/BaseRecyclerViewAdapterHelper#1158]
大佬  我在scrollview中嵌套了recyclerview，整个页面相当于是一个可以滑动的scrollview页面，然后在中间有一个recyclerview页面，滑动recyclerview时整个页面不动  当滑动到最下或者最上时整个页面才动  这个效果我用你的这个适配器实现了  但是每次滑动recyclerview加载更多时 只触发了一个onLoadMoreRequested这个方法  相当于只加载更多了一次 ，请问怎么解决呢

**Comment by CymChad** [comment]
版本？代码？

**Comment by imkobedroid** [comment]
2.9.16版本

[image: 内嵌图片 1]
[image: 内嵌图片 2]
[image: 内嵌图片 3]
[image: 内嵌图片 4]

2017-05-25 9:38 GMT+08:00 陈宇明 <notifications@github.com>:

**Comment by CymChad** [comment]
你的图片我这边看不到。

**Comment by 1109993488** [comment]
ScrollView嵌套有冲突，加载更多实现方式不支持
