### ISSUE TITLE
重写disableLoadMoreIfNotFullPage()方法以解决未满一屏上拉加载效果 失败。

### ISSUE THREAD

**Issue by zjllh** [CymChad/BaseRecyclerViewAdapterHelper#1159]
那个上拉加载的我还是没能解决。
我使用的是5月17日下载下来的项目的library。
问题是：loadview是作为rv的一个item加上去的。则findLastVisibleItemPosition可能会出现，包含这个或不包含这个loadview的情况。返回的值和getItemCount()的比较，就不能用！=了。则该是<=时，未满一页,不显示loadview。>时，超过一页，显示loadview。所以一开始我是这么打算的。
![image](https://cloud.githubusercontent.com/assets/16285517/26398120/1b303884-40ab-11e7-82f9-028583d6a65d.png)
又因为第二个要求是，上滑加载到没内容时，loadview是不显示的，loadview仅两种状态：正在加载和加载失败。。那么，我就该红框用disableLoadMoreIfNotFullPage里，就该用loadMoreComplete()，而不是 loadMoreEnd(false);

这样逻辑没问题吧？
结果出现一个问题，未满一页。自动调用了onLoadStart，多加载了一页。
![image](https://cloud.githubusercontent.com/assets/16285517/26398192/53a1f7ca-40ab-11e7-9029-23b833aa4520.png)
我是代码里在显示list时，已经调用过disableLoadMoreIfNotFullPage了。
我觉得可能是我有什么细节没看到。希望群主有空的时候，指出我的问题。
我是群里仁昌居士。请在早上的时间有空时@我。我家里电脑没项目进行测试。

**Comment by tysheng** [comment]
看了好几遍你写的东西，还是没看明白，我来说说我写这个方法的缘由和思路。

Q:为什么写这个方法？
A:原来没有这个方法的时候，我打开一个列表界面，如果条目比较少，没有满足一屏，就会第二次加载，然后显示『没有更多了』。因为没有铺满一屏，所以用户很容易的就可以知道，不能向下滑动，所以就不需要加载更多，以及显示『没有更多了』。所以我推荐，只在 setNewData 之后调用一次。

Q:该怎么实现？
A:大家都知道 layoutManager 提供了相关的 API 能够检查最后一个可见条目的位置，那么就很容易做了。直接检查一下不就完了。所以就在 setNewData 之后，直接调用了 findLastCompletelyVisibleItemPosition 进行比对，一运行，完全不行，因为 loadMore 的方法是 onBindViewHolder 中的，不是大家以为的通过手势触发。
那就反过来想，先把它关闭，再进行检查，如果超过一屏了，再打开也不迟，所以就这个方法就写成现在这个样子。在实际使用当中，发现有些复杂列表，即时判断的时候不够准确，所以就加了一点延迟。

**Comment by zjllh** [comment]
通过上面大佬帮助，已解决问题。源码是没有问题的！注意：调用了disableLoadMoreIfNotFullPage（）时，SwipeRefreshLayout的刷新结束不用再次开启上拉加载了。disableLoadMoreIfNotFullPage（）能自行判断是否要开启上拉加载。

**Comment by Y-JH** [comment]
请问调用disableLoadMoreIfNotFullPage（）在哪里调用的，怎么使用？我也出现 了同样的问题；第一次进入页面数据不足一屏，但是会出现加载更多的动画进行加载，显示加载动画然后消失。再次刷新又会在刷新的时候进行加载更多并显示加载动画。。。  请问怎么解决的？？！谢谢。。

**Comment by wxy520ll** [comment]
搞不懂  这个方法的逻辑，头大
