### ISSUE TITLE
设置字体颜色被覆盖

### ISSUE THREAD

**Issue by phomel** [CymChad/BaseRecyclerViewAdapterHelper#1162]
settextcolor和getview拿到textview控件都试过,需求是列表前三项标注NO,1,NO.2,NO.3显示不同的字体颜色

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
不好意思，这么晚才回你，我这边测试是正常的。

**Comment by CymChad** [comment]
![wechatimg26](https://cloud.githubusercontent.com/assets/7698209/26621121/30473eee-4618-11e7-946b-45b013685686.jpeg)
![wechatimg27](https://cloud.githubusercontent.com/assets/7698209/26621124/34b3a774-4618-11e7-9d2c-52b840f26bef.jpeg)

**Comment by xiaochaodevelop** [comment]
这样前三条可以，但是如果数据一多，item复用过后颜色就会错乱，请问有什么好解决方法吗

**Comment by NecoJack** [comment]
能否加上getContent,或者getActivity   在使用Color中的颜色是没问题的 但是如果应用R.color.xxx,颜色久不一样了
