### ISSUE TITLE
加载更多问题

### ISSUE THREAD

**Issue by cwyrzz** [CymChad/BaseRecyclerViewAdapterHelper#1164]
为什么还没拉到底部的时候已经加载数据了？

**Comment by 375277196** [comment]
加载更多问题 目前新版本 第一次加载更多能监听到底部  第二次加载更多监听不到 底部显示正在加载更多

**Comment by 1109993488** [comment]
@cwyrzz 你是否设置了setAutoLoadMoreSize或setPreLoadNumber？是否嵌套ScrollView？
@375277196 你的是没有在加载更多后调用loadMoreComplete

**Comment by cwyrzz** [comment]
没有，慢慢一条一条滑动就会看出来存在此情况，快速滑动就看不出来




------------------ 原始邮件 ------------------
发件人: "BlingBling";<notifications@github.com>;
发送时间: 2017年5月27日(星期六) 下午5:46
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "309107361"<309107361@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 加载更多问题 (#1164)




@cwyrzz 你是否设置了setAutoLoadMoreSize或setPreLoadNumber？是否嵌套ScrollView？
 @375277196 你的是没有在加载更多后调用loadMoreComplete

**Comment by CymChad** [comment]
版本，代码，运行效果。 @cwyrzz

**Comment by RxMurphy** [comment]
关闭预加载为什么不能给出一个开关呢

**Comment by CymChad** [comment]
默认就是没有预加载 @RxMurphy

**Comment by SephirothLT** [comment]
数据比较多的时候，快速滑动，只能加载两页的数据，慢慢的滑动，才可以将全部页的数据全部加载完，怎么解决？

**Comment by SephirothLT** [comment]
@CymChad

**Comment by CymChad** [comment]
重新开个issues @SephirothLT

**Comment by SephirothLT** [comment]
@CymChad  #1268
