### ISSUE TITLE
BaseMultiItemQuickAdapter 删除条目时候的问题

### ISSUE THREAD

**Issue by victorcatfish** [CymChad/BaseRecyclerViewAdapterHelper#1165]
在使用BaseMultiItemQuickAdapter 实现可扩展列表(类似ExpandableListView效果)的时候。在使用adapter.remove()方法的时候，如果条目是展开的状态，展开的部分(SubItem)不会从视图上消失掉。必须要将MultiItemEntity收缩起来再删除，目前使用的是2.8.0版本。

**Comment by CymChad** [comment]
删除代码
`  
int cp = getParentPosition(person);
                        ((Level1Item)getData().get(cp)).removeSubItem(person);
                        getData().remove(holder.getLayoutPosition());
                        notifyItemRemoved(holder.getLayoutPosition());`
