### ISSUE TITLE
希望可以增加一个传数组id的点击方法，如下

### ISSUE THREAD

**Issue by Tiannuo** [CymChad/BaseRecyclerViewAdapterHelper#1166]
/**
     * @param viewIds 增加点击事件
     */
    protected void addClick(int... viewIds){
        int[] ids=viewIds;
        if (ids!=null&&ids.length>0){
            for (int viewId:ids){
                View clickView=getContentView().findViewById(viewId);
                if (clickView!=null){
                    clickView .setOnClickListener(this);
                }
            }
        }
    }

**Comment by AllenCoder** [comment]
非常感谢你的提议，这个api可以实现，经慎重考虑，不建议添加，因为部分用户不需要添加这么多控件id，用的次数会很少，原来的api，可以多次addOnClickListener(R.id.xxx).addOnClickListener(R.id.xxx);
非常感谢你的使用，有更多使用建议欢迎提出。

**Comment by Tiannuo** [comment]
还真的有功能扩展的建议，我最近总结一下。

**Comment by CymChad** [comment]
期待你的建议总结
