### ISSUE TITLE
上拉加载失败，点击重试的时候，加载进度和提示重合

### ISSUE THREAD

**Issue by lovestart** [CymChad/BaseRecyclerViewAdapterHelper#1169]
上拉加载失败，点击重试的时候，加载进度和提示重合。
应该是提示文字消失，加载进度出现。如果加载还是失败的话，加载进度消失，提示显示
![qq 20170601114542](https://cloud.githubusercontent.com/assets/8360241/26663829/05194b38-46c0-11e7-9a55-aa49283e5cd2.png)

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/838
