### ISSUE TITLE
头布局可以删除吗？

### ISSUE THREAD

**Issue by FloydP** [CymChad/BaseRecyclerViewAdapterHelper#117]
是否可以移除头布局

**Comment by CymChad** [comment]
可以的，addHeadView（null）

**Comment by FloydP** [comment]
代码里不是不能设空吗？？
public void addHeaderView(View header) {
        if(header == null) {
            throw new RuntimeException("header is null");
        } else {
            this.mHeaderView = header;
            this.notifyDataSetChanged();
        }
    }

**Comment by CymChad** [comment]
你更新一下最新的版本1.8.5就有了
