### ISSUE TITLE
setEmptyView

### ISSUE THREAD

**Issue by wgl656544** [CymChad/BaseRecyclerViewAdapterHelper#1170]
我只要一设置 setEmptyView 就报这个错please bind recyclerView first!
看了源码，bindRecyclerveiew，setRecycleview 也都不行，请问是怎么回事？

**Comment by wgl656544** [comment]
不好意思！问题已经解决！是自己疏忽了！
adapter.setEmptyView(R.layout.item_no_data_layout);
用的是上面的方法，而没有用下面的方法
adapter.setEmptyView(R.layout.item_no_data_layout,(ViewGroup) rlProduct.getParent());

**Comment by wgl656544** [comment]
下午测试的时候又出现问题了，设置adapter.setEmptyView(R.layout.item_no_data_layout);的时候会报
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHe
这个错误。
但是如果在setEmptyView之前调用adapter.setNewData(null);
就不会报错，但是空布局的高度没有填满屏幕。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1069
