### ISSUE TITLE
6.0适配问题

### ISSUE THREAD

**Issue by dacaoyuan** [CymChad/BaseRecyclerViewAdapterHelper#1174]
发现当在滚动布局下，垂直放两个recycleView时，为避免与滚动布局的滑动冲突，同时把两个recycleView的滑动事件禁止后（mRecyclerView.setNestedScrollingEnabled(false);）；滑动是比较流畅啦，但是在6.0版本下，放在上面的recycleView会显示不全。不过，在6.0版本以下，没问题。希望，大神后续能分析一下。

**Comment by cervy** [comment]
测试环境变量只是系统版本的区别吗？

**Comment by CymChad** [comment]
请描述，版本，复现操作，使用代码。

**Comment by CymChad** [comment]
你看下是不是这个问题？https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1140
