### ISSUE TITLE
item点击事件有问题

### ISSUE THREAD

**Issue by wobenhetu** [CymChad/BaseRecyclerViewAdapterHelper#1176]
问题描述：提供的点击事件有问题。点击第一页的任何一条正常；点击第二页出现重复；继续点击下一页：继续重复； 
解决方案：
//rv   RecycleView        
        rv.removeOnItemTouchListener(listener);
        rv.addOnItemTouchListener(listener);

final OnItemClickListener listener = new OnItemClickListener() {
        @Override
        public void onSimpleItemClick(final BaseQuickAdapter baseQuickAdapter, final View view, final int i) {
        //点击跳转逻辑
        }
    };

**Comment by Troll4it** [comment]
你使用adapter引出的点击方法，我前面也遇到过

**Comment by AllenCoder** [comment]
rv.addOnItemTouchListener(listener); 源码处，如果一直addOnItemTouchListener 会一直添加listener，内部是一个listener集合，如果要避免此类问题，选用新版本提供的

adapter.setOnItemClickListener（listener）可以避免此类问题
