### ISSUE TITLE
MultiItemEntity默认的构造器

### ISSUE THREAD

**Issue by JackLeeMing** [CymChad/BaseRecyclerViewAdapterHelper#118]
MultiItemEntity的默认构造器是不是应该是带itemType的构造器，而不是无参数的构造器，否则，继承此类后忘记设置itemType的数值可能会造成不必要的错误。加入默认的带参数构造器，其子类一定得对itemType设置才能用，不是很好吗？

**Comment by CymChad** [comment]
恩，多谢提醒！
