### ISSUE TITLE
一个小建议？

### ISSUE THREAD

**Issue by xiongke15117937934** [CymChad/BaseRecyclerViewAdapterHelper#1182]
建议优化下 折叠的adapter，参考下[https://github.com/bignerdranch/expandable-recycler-view](https://github.com/bignerdranch/expandable-recycler-view)
先说缺点吧
1. 就是说比如我要删除一个子项时候，想知道父级节点索引不知道
2.删除一个子项节点 后，更新下面的节点索引

**Comment by xiongke15117937934** [comment]
想要一个写的像ExpandableListView暴露出的方法一样，可惜ExpandableListView不支持MD。

**Comment by CymChad** [comment]
收到 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/907
