### ISSUE TITLE
有header时候datas 数据排序问题

### ISSUE THREAD

**Issue by LcTerry** [CymChad/BaseRecyclerViewAdapterHelper#1183]
使用版本：2.9.18
当使用SectionEntity进行有头部数据adapter,但是这样无法对数据进行排序（比如根据每一个ResultSection中的ResultEntity的index进行排序，但是由于header中的ResultSection中没有ResultEntity，无法排序）

  示例代码：

`    if (questionsBeans != null && questionsBeans.size() > 0) {
                for (int x = 0; x < questionsBeans.size(); x++) {
                    QuestionsBean questionsBean = questionsBeans.get(x);
                    ResultEntity examResultEntity = new ResultEntity();
                    //每一个examResultEntity 的序号
                    examResultEntity.setTopicNo(x + 1);
                    boolean isRemark;
                    if (questionsBean.getSign() == null) {
                        isRemark = false;
                    } else {
                        isRemark = questionsBean.getSign();
                    }
                    examResultEntity.setRemark(isRemark);
                       examResultEntity.setContent(EswiUtils.YNToChinese(questionsBean.getStudentAnswer()));
                    examResultEntity.setType(questionsBean.getResult());
                    //0 答错 1 答对 2 半对
                    if (questionsBean.getResult() == 0) {
                        wrongAnswerLists.add(new ResultSection(examResultEntity));
                    } else if (questionsBean.getResult() == 1) {
                        rightAnswerLists.add(new ResultSection(examResultEntity));
                    } else if (questionsBean.getResult() == 2) {
                        halfAnswerLists.add(new ResultSection(examResultEntity));
                    }
                }
                if (questionsBeans.size() >= 20) {
                    if (wrongAnswerLists != null && wrongAnswerLists.size() > 0) {
                        //添加header
                        mExamResultEntityList.add(new ResultSection(true, "答错(" + wrongAnswerLists.size() + "/" + questionsBeans.size() + ")"));
                        mExamResultEntityList.addAll(wrongAnswerLists);
                    }
                    if (halfAnswerLists != null && halfAnswerLists.size() > 0) {
                        //添加header
                        mExamResultEntityList.add(new ResultSection(true, "半对(" + halfAnswerLists.size() + "/" + questionsBeans.size() + ")"));
                        mExamResultEntityList.addAll(halfAnswerLists);
                    }
                    if (rightAnswerLists != null && rightAnswerLists.size() > 0) {
                        //添加header
                        mExamResultEntityList.add(new ResultSection(true, "答对(" + rightAnswerLists.size() + "/" + questionsBeans.size() + ")"));
                        mExamResultEntityList.addAll(rightAnswerLists);
                    }
                } else {
                    mExamResultEntityList.addAll(wrongAnswerLists);
                    mExamResultEntityList.addAll(halfAnswerLists);
                    mExamResultEntityList.addAll(rightAnswerLists);
                }
            }

//        if (mExamResultEntityList != null && mExamResultEntityList.size() > 1) {
//            Collections.sort(mExamResultEntityList, (o1, o2) -> {
//                ResultEntity examResultEntity1 = o1.t;
//                ResultEntity examResultEntity2 = o2.t;
//                Integer no1 = examResultEntity1.getTopicNo();
//                Integer no2 = examResultEntity2.getTopicNo();
//                return no1.compareTo(no2);
//            });
//        }
        //想设置数据前排序根据getTopicNo排序，但是由于header中没有ResultEntity 所以无法排序
        mResultAdapter.setNewData(mExamResultEntityList);

//这里是整个entity 
public class ResultSection extends SectionEntity<ResultEntity> {

    public ResultSection(boolean isHeader, String header) {
        super(isHeader, header);
    }

    public ResultSection(ResultEntity mResultEntity) {
        super(mResultEntity);
    }
}

`

**Comment by githubzaibao** [comment]
SectionEntity 是个抽象类，你可以扩展一个字段用来存储TopicNo，然后就可以根据TopicNo进行排序了
