### ISSUE TITLE
调用disableLoadMoreIfNotFullPage()后，在小米5上不能加载更多

### ISSUE THREAD

**Issue by lyn-wang** [CymChad/BaseRecyclerViewAdapterHelper#1184]
调用disableLoadMoreIfNotFullPage(RecyclerView recyclerView)后，在数据超过一个屏幕的情况下，在小米5上不能加载更多，在Android6.0版本的模拟器上有时能加载更多有时不能。
测了一下，下小米5上这个判断一直为false:
` if ((linearLayoutManager.findLastCompletelyVisibleItemPosition() + 1) != getItemCount()) {
           setEnableLoadMore(true);
      }`

**Comment by tysheng** [comment]
如果你是数据不够一个屏幕的话，是不会开启的

**Comment by lyn-wang** [comment]
数据超过一个屏幕的情况下，调用这个方法在小米5也不能加载更多

**Comment by tysheng** [comment]
把使用的代码发一下看看

**Comment by lyn-wang** [comment]
发现问题了，是disableLoadMoreIfNotFullPage(RecyclerView recyclerView)调用时机不对，我是在创建Adapter之后立马调用的，此时还没有数据。这个方法是50ms延迟后去判断数据是否足够一屏，手机用的 WiFi加载数据较慢，而模拟器网络是用的网线，加载数据较快，所以会出现在这个问题。我现在是在加载完数据后去调用这个方法，就没问题了。你看你们能否把这个方法优化下，哈哈，谢谢！

**Comment by tysheng** [comment]
我注释里已经写明了使用方法。。。。
