### ISSUE TITLE
intent传值到下一个activity里bean.getSubItems()为null

### ISSUE THREAD

**Issue by MonkeyMushroom** [CymChad/BaseRecyclerViewAdapterHelper#1185]
bean继承AbstractExpandableItem实现折叠，在intent传值到下一个activity里bean对象的getSubItems方法为null，版本号2.9.18

**Comment by githubzaibao** [comment]
你可以借助Gson，先用Gson转换成string，传递到下一个activity后，在从String序列化为bean

**Comment by githubzaibao** [comment]
原因应该是AbstractExpandableItem没有实现序列化接口

**Comment by MonkeyMushroom** [comment]
嗯嗯！可行
