### ISSUE TITLE
当RecyclerView嵌套在NestedScrollView里时无法显示item的进出动画

### ISSUE THREAD

**Issue by JiangShuLiang** [CymChad/BaseRecyclerViewAdapterHelper#1187]

**Comment by JiangShuLiang** [comment]
为了解决RecyclerView和ScrollView滑动冲突的问题，我是有调用这句：
recyclerview.setNestedScrollingEnabled(false);

**Comment by CymChad** [comment]
为什么要嵌套使用？

**Comment by liu-hailin** [comment]
老铁，当recyclerview放在scrollview中，listview的缓存、滑动加载这些特性就已经没有，你滑动只是在滑动recyclerview，简单来说，就是recyclerview已经全部都展开完了，和普通的N个view竖直排放没有大的区别了。建议看看addHaderView的方法，或者试试多布局来实现

**Comment by JiangShuLiang** [comment]
@CymChad 因为activity里不只有一个recyclerview啊，还有banner，spinner等view，所以肯定要在最外面套个scrollview的，让整体能一起滑动

**Comment by JiangShuLiang** [comment]
@liu-hailin 你是说把scrollview里的其他view设置成是recyclerview的headerview吗？

**Comment by CymChad** [comment]
是的
