### ISSUE TITLE
MultiItemQuickAdapter调用notifyDataSetChanged()第二级Item数据均重复加载

### ISSUE THREAD

**Issue by coolhades** [CymChad/BaseRecyclerViewAdapterHelper#1188]
在通过记录item选中状态后 调用notifyDataSetChanged() 再次展示Recyclerview发现所有二级Item重复加载了一次，数据源检查后没有问题~
有个细节：再次展示Recyclerview时 第一级Item属于expand状态 但是不显示第二级item

**Comment by CymChad** [comment]
可以提供demo吗？

**Comment by CymChad** [comment]
以及gif问题图

**Comment by coolhades** [comment]
![gif](https://cloud.githubusercontent.com/assets/17229567/26832964/aa0d7686-4b03-11e7-86de-bf9ec884ac21.gif)
点击item后刷新数据【根据数据源修改该item的状态如文字颜色】
刷新用的adapter.setNewData(generateData());

**Comment by coolhades** [comment]
解决了 是数据源引用问题
