### ISSUE TITLE
使用 BaseItemDraggableAdapter 快速拖拽时会发生UI更新卡顿

### ISSUE THREAD

**Issue by yezishu** [CymChad/BaseRecyclerViewAdapterHelper#1189]
版本 BaseRecyclerViewAdapterHelper:2.9.18
机型魅族MX5
android系统版本5.1
Flyme 6.0.1.0A
进行快速拖拽时会发现卡顿现象

经过测试另外一部华为荣耀机型也存在

**Comment by VectorWen** [comment]
@yezishu 你闪烁的界面能贴出来吗？我看看你界面的内容放了多少

**Comment by yezishu** [comment]
内容显示15条数据 我排查了一下
`if (from < to) {
            for (int i = from; i < to; i++) {
                Collections.swap(mData, i, i + 1);
            }
        } else {
            for (int i = from; i > to; i--) {
                Collections.swap(mData, i, i - 1);
            }
        }`
应该主要是这串代码，item在移动的时候会一直调用ItemTouchHelper.Callback.onMoved。
所以阻塞了UI主线程

**Comment by yezishu** [comment]
那串代码是 BaseItemDraggableAdapter 的onItemDragMoving方法

**Comment by tysheng** [comment]
可以把 onItemDragMoving 这个方法重写一下，换成先 remove 再 add, 看看会不会好点

**Comment by yezishu** [comment]
排查了一下 不是onItemDragMoving这个方法的问题 而是我另外加的ItemDecoration的性能问题。
