### ISSUE TITLE
应该提供方法回收emptyview以及errorview等

### ISSUE THREAD

**Issue by lpc904586134** [CymChad/BaseRecyclerViewAdapterHelper#1190]
应该提供方法回收emptyview以及errorview等

**Comment by CymChad** [comment]
请详细描述，没太明白

**Comment by CymChad** [comment]
目前是可以切换这两个种状态的

**Comment by lpc904586134** [comment]
某些情况下页面需要重建视图，重新构建recycleview layoutmanager，decorator以及适配器，加载监听，之前的emptyview以及errorview绑定到了内部一个framelayout无法手动回收，需要提供给外部一个销毁之前数据以及视图的方法，虽然用处不多

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
如果你重置了adapter，那么emptyview肯定是没有了，因为emptyview是跟着adapter走的。

**Comment by CymChad** [comment]
empty重新创建就好了，所有的都重新创建了，empty设置空就可以了
