### ISSUE TITLE
空数据有分割线问题

### ISSUE THREAD

**Issue by fuxianwen** [CymChad/BaseRecyclerViewAdapterHelper#1192]
我这边设置了矩形分割线，发现空数据底部是有分割线的，加载中 底部也有分割线，我代码中设置最后一条数据无分割线无效，是否是需要判断头部加底部数据...如何判断..

**Comment by fuxianwen** [comment]
发现item没有设置背景色分割线判断无效，加载中 能否设置一个背景色.

**Comment by 1109993488** [comment]
空数据和加载更多其实都是item，显示空数据的时候你可以移除分割线，加载更多你可以通过getLoadMoreViewCount()来判断是否有加载更多来处理是否显示

**Comment by fuxianwen** [comment]
我设置判断了的 ，但是item不设置背景色有分割线搞不懂，设置了背景色就没有..

**Comment by 1109993488** [comment]
ItemDecoration的onDrawOver方法不会被覆盖
