### ISSUE TITLE
加载更多不知道总条数咋办啊？

### ISSUE THREAD

**Issue by focus2846** [CymChad/BaseRecyclerViewAdapterHelper#120]
加载更多是不是要跟demo的写的方法一样？还有其他方式吗

**Comment by githubzaibao** [comment]
开启加载更多功能你不需要知道总条数，你只需要设计一个阀值，意思就是说，当recyclerView中的item数量达到这个阀值时，继续下拉，便会调用加载更多的回调方法。感谢你的关注与支持
