### ISSUE TITLE
刷新和加载更多的问题

### ISSUE THREAD

**Issue by phomel** [CymChad/BaseRecyclerViewAdapterHelper#1201]
你好,如果我用加载更多加载了两页,然后滑到第二页, 如果调用刷新方法,用adapter.setnewdata加载第一页, 就会自动加载第二页,如果设置重新加载第一页的时候不会自动触发加载更多的listener

**Comment by phomel** [comment]
你好,问题我解决了,看了挺久源码,控制好总页数和当前页,确定mNextLoadEnable和mLoadMoreEnable就好了

**Comment by phomel** [comment]
你好,不过compile的项目并不能像library那样,loadMoreView有多种状态,只有显示默认的加载条目loadingView,如果这部分想像library里展示的多种加载状态,有什么好的方法么?

**Comment by 1109993488** [comment]
自定义加载更多，你可以看下demo的CustomLoadMoreView

**Comment by phomel** [comment]
那我要写一个类继承basequcikadapter,然后写几个loadmorefailed和loadmoreend方法这样么?感觉有点难,我去试试,谢啦!

**Comment by phomel** [comment]
是在BaseQuickAdapter,让onCreateViewHolder方法中生成baseViewHolder的getLoadingView方法显示不同加载状态么,自动加载的addLoadMore方法是在onBindViewHolder中,在adapter添加一些加载状态变化的方法,在activity中控制loadingView变化可以么?这样的想法对么?

**Comment by 1109993488** [comment]
加载更多其实也是一个item，然后控制切换不同的状态

**Comment by 1109993488** [comment]
你想要什么样的效果？

**Comment by phomel** [comment]
多 加载完成 和 加载失败点击重新加载 的状态,我再好好想想

**Comment by cervy** [comment]
其实有时也可以考虑在"Z"轴上扩展状态UI， 库自带的是"X"/“Y"轴
