### ISSUE TITLE
多种item设计的不太好用吧。

### ISSUE THREAD

**Issue by q805699513** [CymChad/BaseRecyclerViewAdapterHelper#1203]
特别是分页加载的的时候添加数据，添加数据都去add new MultipleItem(...);吗

**Comment by CymChad** [comment]
不是呀,只要`implements MultiItemEntity`就可以了.

**Comment by LambertCoding** [comment]
我也觉得这里设计有一点不好， 只能通过数据实体来区分ItemType，不能关联position，如果要做一个固定position使用不同布局的就不行了；
我觉得还是在adapter里提供一个方法，把对应实体和position都回调出来返回item类型，这样好一点；

**Comment by CymChad** [comment]
如果大家觉得这种多布局方式有点由于耦合了实体类，还有支持另外一种多布局方式具体可查看更便捷的多布局, 为 BaseQuickAdapter 设置代理.   https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/968
