### ISSUE TITLE
数据不满一屏时，一直显示底部动画

### ISSUE THREAD

**Issue by PeanutZhang** [CymChad/BaseRecyclerViewAdapterHelper#1207]
当数据不满一个屏幕时，下面显示加载动画，调用了disableLoadMoreIFNotFullPage(),还是一直显示

**Comment by 1109993488** [comment]
你这个要在绑定数据还没刷新ui的时候调用，如果已经回掉加载更多了再掉就不起作用

**Comment by CoderAstro** [comment]
我调用的disableLoadMoreIFNotFullPage，也不好用，能在解释解释吗

**Comment by 1109993488** [comment]
数据为0的时候是没有加载更多的，比如设置1条数据(setNewData(list))，然后绘制界面如果绘制到加载更多就回调加载更多请求下一页，disableLoadMoreIFNotFullPage是在setNewData后禁用加载更多然后界面绘制完判断是否满一屏幕，再去开启加载更多，你们调disableLoadMoreIFNotFullPage后又调了setEnableLoadMore(true)吗？一直显示底部动画说明已经回调加载更多了

**Comment by Ayanokouji-Kenn** [comment]
他们的意思是 初始数据就一条的时候，这时第二条就是“加载更多”

**Comment by sitexa** [comment]
我也遇到这个问题，上拉时，后台已经 没有数据了，还是在显示正在加载的进度条，同时，后台不停地发送网络请求。不知道如何停止。

**Comment by 1109993488** [comment]
@sitexa 没有数据要调loadMoreEnd()
