### ISSUE TITLE
item点击事件延迟

### ISSUE THREAD

**Issue by Sumsear** [CymChad/BaseRecyclerViewAdapterHelper#1209]
华为P8 RecyclerView第一次加载完后会有很大几率出现点击事件响应延迟的问题：
mAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Intent intent = new Intent(getActivity(), GoodsDetailActivity.class);
                Goods.DataBean dataBean = (Goods.DataBean) adapter.getItem(position);
                intent.putExtra("goods_id", dataBean.getGoods_id());
                startActivity(intent);
            }
        });

**Comment by AllenCoder** [comment]
收到，你在onItemClick 回调函数的第一行加入log日志，看一下响应时间，然后贴上来，正常逻辑下，这里用的是系统的onClick回调，响应时间应该是由系统决定的，是否其他地方有耗时的延时代码导致？

**Comment by Sumsear** [comment]
您好！ 在第一行加日志怎样才能拿到响应时间呢？还有就是只有第一次会，很明显能看到点击了item后水波纹过了一会儿才显示！，然后才完成页面跳转，我看了一下在onItemClick方法内部只花了14毫秒，所以问题用该出现在点击屏幕到最后回调onItemClick方法的这个过程中出现的！




------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年6月13日(星期二) 上午10:30
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "309201338"<309201338@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] item点击事件延迟 (#1209)




收到，你在onItemClick 回调函数的第一行加入log日志，看一下响应时间，然后贴上来，正常逻辑下，这里用的是系统的onClick回调，响应时间应该是由系统决定的，是否其他地方有耗时的延时代码导致？

**Comment by AllenCoder** [comment]
你重写Actvity的dispatchTouchEvent 在那里的加入标记，标为起始时间，之后在响应处加入日志，看一下具体耗时多少时间 。 在布局正常情况系统的事件分发应该会很快，麻烦将复现的Demo和日志提供给我，以便追踪问题
