### ISSUE TITLE
改写ExpandableItem变为点击加载更多出现的BUG

### ISSUE THREAD

**Issue by mflk007** [CymChad/BaseRecyclerViewAdapterHelper#1211]
我利用ExpandableItem的DEMO，将其改为子项最后有一个加载更多项，点击加载更多addSubItem进入然后对整个adapter进行notifyDataSetChanged，还是一直显示之前的数据，只有重新折叠打开后才显示新的数据

**Comment by mflk007** [comment]
...我找到了暂时的解决方案。。。调用如下。。
adapter.collapse(1, false);
 adapter.expand(1, false);
先收起在开启。。。

**Comment by CymChad** [comment]
你可以add一个尾部
