### ISSUE TITLE
分级时候，需要把点击分级的按钮隐藏点，隐藏不了

### ISSUE THREAD

**Issue by yoyiyi** [CymChad/BaseRecyclerViewAdapterHelper#1214]
您好，分级时候，需要把点击分级的按钮隐藏点，但是隐藏不了
 holder.getView(R.id.fl_recent)
                        .setOnClickListener(view -> {
                            holder.setVisible(R.id.fl_recent, false);//隐藏不掉，不起作用
                            //view.setVisibility(View.GONE);//隐藏不掉，也不起作用
                            int pos = holder.getAdapterPosition();
                            expand(pos, false);
                        });

**Comment by CymChad** [comment]
这个应该是通过数据来隐藏，单独设置隐藏会有缓存问题。

**Comment by CymChad** [comment]
如果解决缓存问题，可以查看文档 http://www.jianshu.com/p/b343fcff51b0

**Comment by yoyiyi** [comment]
```
 holder.getView(R.id.fl_recent)
                        .setOnClickListener(view -> {
                            ViewGroup.LayoutParams params = view.getLayoutParams();
                            params.width = 0;
                            params.height = 0;
                            view.setLayoutParams(params);
                            int pos = holder.getAdapterPosition();
                            expand(pos, false);

                        });
```
但是我通过这种设置，需要点击两次才能隐藏，真是无语了，我设置标志位试试

**Comment by CymChad** [comment]
如果用数据更新的方式，可以解决你的问题。

**Comment by yoyiyi** [comment]
已经解决了 在MultiItemEntity实现类里面加一个标志位

**Comment by CymChad** [comment]
👍 @yoyiyi
