### ISSUE TITLE
类似贴吧里的 加载最新的评论怎么做

### ISSUE THREAD

**Issue by RookieExaminer** [CymChad/BaseRecyclerViewAdapterHelper#1215]
上拉加载 显示 “没有更多数据”。 然后我想再上拉请求数据或者是我想点击“没有更多数据” 再去服务器请求新数据 该怎么办 就是类似贴吧里的 加载最新的评论     谢谢

**Comment by 1109993488** [comment]
你可以看下#1206

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.20'

**Comment by jijiangrui** [comment]
点击加载更多时, 正在加载显示了, 而加载失败的提示没有隐藏

**Comment by FrankKwok** [comment]
@jijiangrui 是这样的，建议重新开个issue

**Comment by FrankKwok** [comment]
@1109993488

**Comment by 1109993488** [comment]
@jijiangrui 加载失败没有隐藏？麻烦你描述下出现的场景，效果

**Comment by sitexa** [comment]
我也遇到相同问题，加载失败的toast一直显示，退出应用后也没有关闭。“load more failed"
