### ISSUE TITLE
aide中绑定RecyclerView与QuickAdapter时错误（类问题？）

### ISSUE THREAD

**Issue by venssy** [CymChad/BaseRecyclerViewAdapterHelper#1216]
**android studio中没有问题，在aide(android x86)上出现错误无法绕过。**

adapter继承自BaseQuickAdapter
`public class QuickAdapter extends BaseQuickAdapter<String[], BaseViewHolder> { ... }`

绑定RecyclerView和QuickAdapter时提示错误：
`recyclerView.setAdapter(adapter);`

> Method 'android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView.Adapter)' in 'android.support.v7.widget.RecyclerView' can not be applied to '(package.QuickAdapter)'

`adapter.bindToRecyclerView(recyclerView);`

> Method 'com.chad.library.adapter.base.BaseQuickAdapter<T, K>.bindToRecyclerView(?)' in 'package.QuickAdapter' can not be applied to '(android.support.v7.widget.RecyclerView)'

`recyclerView.setAdapter((Adapter)adapter);`和`recyclerView.setAdapter((BaseQuickAdapter)adapter);`强制转换也不可以，can not be type of 'Adapter'

**Comment by FrankKwok** [comment]
能不能贴出更详细的报错信息

**Comment by venssy** [comment]
直接clone项目到gradle中，稍微修补了几个对象转换的小错误就可以用了，至于maven的问题没有办法，因为aide看不到编译过程，只有这两个错误提示，有可能是aide对派生类支持有限，在修补时就有个错误是View派生类无法识别，需要强制转化（在getView()时发生错误）：
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/b33fac78fa33372783d48d313135ff3f92678b35/library/src/main/java/com/chad/library/adapter/base/BaseViewHolder.java#L209-L233
