### ISSUE TITLE
ImageView 设置成invisible无法点击

### ISSUE THREAD

**Issue by montotone** [CymChad/BaseRecyclerViewAdapterHelper#1218]
//                if (item.isSelect) {
//                    Log.e(TAG, "convert: vi");
//                    ivIcon.setVisibility(View.VISIBLE);
//                } else {
//                    Log.e(TAG, "convert:invi");
//                    ivIcon.setVisibility(View.INVISIBLE);
//                }
                if (item.isSelect) {
                    ivIcon.setImageResource(R.drawable.iv_anchor_diamond);
                } else {
                    ivIcon.setImageResource(R.drawable.iv_dice);
                }

**Comment by montotone** [comment]
调用了notifyDataSetChanged().点击只会执行一次

**Comment by FrankKwok** [comment]
请详细描述问题

**Comment by montotone** [comment]
就是recycleView里面有选中和未选中状态,点击选中设置visible.未选中设置invisible.
不调用notifyDataSetChanged().可以正常点击回调.
调用了notifyDataSetChanged(),只能点击一次.第二次就没有反应了

**Comment by FrankKwok** [comment]
点击之后更改实体类的状态了吗

**Comment by AllenCoder** [comment]
1.. 当控件状态为invisble时 本身并不会消费掉touch事件， 只会将touch事件透传给parentView 。
2. 另外针对按钮状态的控制，一定是要在数据层有标记字段，不可用itemview本身来存储，会因为回收和复用机制，导致数据出错。。
