### ISSUE TITLE
how to implement swipe left or other direction on this library

### ISSUE THREAD

**Issue by navotera** [CymChad/BaseRecyclerViewAdapterHelper#122]
is it possible to add swipe that showed some view on recycler view using this library and how to setdirection on the swipe event... so user can swipe right or left based on the different listener method

thanks

**Comment by elfman** [comment]
if you just want to showed some text or bitmap on the side when swiping, you can overwrite the onChildDraw method in the ItemDragAndSwipeCallback.java, but will disappear after release. 
    
     @Overwrite
     public void onChildDraw(Canvas c, RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder, float dX, float dY, int actionState, boolean isCurrentlyActive) {
        super.onChildDraw(c, recyclerView, viewHolder, dX, dY, actionState, isCurrentlyActive);

        // Fade out the view as it is swiped out of the parent's bounds
        if (actionState == ItemTouchHelper.ACTION_STATE_SWIPE) {
            View itemView = viewHolder.itemView;

            Context context = recyclerView.getContext();
            Paint paint = new Paint();

            Bitmap icon;

            if (dX > 0) {

                icon = BitmapFactory.decodeResource(context.getResources(), R.drawable.temp);
                // Set color for right swipe
                paint.setColor(Color.YELLOW);

                // Draw Rect with varying right side, equal to displacement dX
                c.drawRect((float) itemView.getLeft(), (float) itemView.getTop(), dX,
                        (float) itemView.getBottom(), paint);

                // Set the image icon for right swipe
                c.drawBitmap(icon, (float) itemView.getLeft() + 25, (float) itemView.getTop() +
                        ((float) itemView.getBottom() - (float) itemView.getTop() - icon.getHeight()) / 2, paint);
            }
        }
    }

**Comment by navotera** [comment]
i guess it would be great if on the implementation of  OnItemSwipeListener interface there are method listener to know which direction is we need... 

by the way thanks a lot sir

**Comment by elfman** [comment]
If you want to set the direction on the swipe event, you can overwrite the getMovementFlags in ItemDragAndSwipeCallback.java, change the swipeFlag like this
     `int swipeFlags = ItemTouchHelper.START;`
I will add a public method to do this soon.

**Comment by navotera** [comment]
what if i need both direction ?

**Comment by elfman** [comment]
`int swipeFlags = ItemTouchHelper.START | ItemTouchHelper.END;`

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.6'
Enable change the drag and swipe movement direction and threshold by setters.

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.7'
Enable draw on the edge when swipe moving

**Comment by navotera** [comment]
pardon me, i cannot test it yet since i got another things to do, please dont close this issue yet

Thanks

**Comment by CymChad** [comment]
@navotera ok

**Comment by CymChad** [comment]
Still no test?When you have problems and open the issue

**Comment by navotera** [comment]
seems like your documentation on this github on how to use this lib need to update.. since when creating new object from class onItemSwipeListener need to implement another method (onItemSwipeMoving method). ....

i notice two feature on this update : 
-----------------------------------------------------
1. Enable change the drag and swipe movement direction and threshold by setters. 
2. Enable draw on the edge when swipe moving

sorry sir can u give us example on how to implement that two update.. 
anyway thanks for your kindly reply.....

**Comment by elfman** [comment]
You can find the usage in the demo [ItemDragAndSwipeUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemDragAndSwipeUseActivity.java)

**Comment by navotera** [comment]
thanks :+1:  :+1:  :+1: 
please close this issues (cannot find button **comment and close** on this issues)

**Comment by arscree** [comment]
What about swiping to the right?
@Overwrite
 public void onChildDraw(Canvas c, RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder, float dX, float dY, int actionState, boolean isCurrentlyActive) {
    super.onChildDraw(c, recyclerView, viewHolder, dX, dY, actionState, isCurrentlyActive);

    // Fade out the view as it is swiped out of the parent's bounds
    if (actionState == ItemTouchHelper.ACTION_STATE_SWIPE) {
        View itemView = viewHolder.itemView;

        Context context = recyclerView.getContext();
        Paint paint = new Paint();

        Bitmap icon;

        if (dX > 0) {

            icon = BitmapFactory.decodeResource(context.getResources(), R.drawable.temp);
            // Set color for right swipe
            paint.setColor(Color.YELLOW);

            // Draw Rect with varying right side, equal to displacement dX
            c.drawRect((float) itemView.getLeft(), (float) itemView.getTop(), dX,
                    (float) itemView.getBottom(), paint);

            // Set the image icon for right swipe
            c.drawBitmap(icon, (float) itemView.getLeft() + 25, (float) itemView.getTop() +
                    ((float) itemView.getBottom() - (float) itemView.getTop() - icon.getHeight()) / 2, paint);
        }
    }
}

**Comment by navotera** [comment]
Much Thank u sir
