### ISSUE TITLE
Recyclerview  item复用问题

### ISSUE THREAD

**Issue by comerssschen** [CymChad/BaseRecyclerViewAdapterHelper#1220]
大佬你好 我item里面有图片和加减按钮还有复选框，在第一次加载的时候图片有错位的情况，在item其他空间的点击也会出现这种情况，怎么解决这个复用问题的呢？

**Comment by FrankKwok** [comment]
请贴出相关代码

**Comment by MakeCodeFly** [comment]
我也碰到这个问题   其中的ImageView控件会复用第一个的数据  代码如下：
![image](https://user-images.githubusercontent.com/24836213/27326529-443310b0-55de-11e7-97bf-efd637ffe6e1.png)

![image](https://user-images.githubusercontent.com/24836213/27326586-71ec79e2-55de-11e7-8b50-3b2edf679761.png)

![image](https://user-images.githubusercontent.com/24836213/27326565-6290f6c6-55de-11e7-8f7a-352a64bdab16.png)

**Comment by FrankKwok** [comment]
现在不方便看图，所以不是很清楚错误原因，但是这种情况一般都是实体类没有保存状态引起的，就是说不要依赖view去保存状态，因为它们会被复用

**Comment by FrankKwok** [comment]
@MakeCodeFly 你这个convert方法没有全部发出来，model.getDongtai()==null的时候是怎么处理的？

**Comment by CymChad** [comment]
数据状态错乱
这个问题无论是RecyclerView还是ListView不做处理都会出现问题，这个本质上是由于布局重用机制导致的，解决办法是通过数据状态来控制控件的状态，一定要设置状态无论什么状态，if和else是少不了的，如下代码：
```java

  if（entity.isCheck）{
    checkBox.isChecked(true);
  } else {
    checkBox.isChecked(false);
  }
```
解决缓存问题案例：

处理文本框和单选的缓存问题  https://github.com/Pyuming/RecyclerViewEditTextDemo
实现三级伸缩，并解决多选框的复用  https://github.com/Sky0202/About_BRVAH

**Comment by zwping** [comment]
@CymChad 也遇到了一个图片错位的问题，项目中是item中嵌套recyclerView，child recyclerView展示图片，每个item中图片数量不一，在这里面无法使用
`if（entity.isCheck）{
    checkBox.isChecked(true);
  } else {
    checkBox.isChecked(false);
  }`
这个错位问题怎么解决呢？有什么解决思路嘛
