### ISSUE TITLE
添加headerView问题

### ISSUE THREAD

**Issue by xujianlafeng** [CymChad/BaseRecyclerViewAdapterHelper#1221]
大佬，我在一个RecyclerView里面添加了多个headerView，进这个页面的时候，页面总是会自动滑到最后添加的那个headerView那。有没有控制这个不要滑动的方法。

**Comment by Troll4it** [comment]
试试添加这句
   rv.getLayoutManager().scrollToPosition(0);
        rv.smoothScrollToPosition(0);

**Comment by xujianlafeng** [comment]
rv.getLayoutManager().scrollToPosition(0);
rv.smoothScrollToPosition(0);
这两句不管加在哪都不管用啊。

**Comment by CymChad** [comment]
可以提供demo吗？我这边测试如果headerView是rv的话，会因为焦点的问题，滑到最后一个headerView的地方，但是可以通过 @Troll4it 的答案解决。

**Comment by xujianlafeng** [comment]
是的，其中一个header就是RV。

**Comment by xujianlafeng** [comment]
@CymChad 我的最后一个headerView就是RV，请问一下这个问题如何解决啊，Troll4it的答案解决不了哦，rv.getLayoutManager().scrollToPosition(0);
rv.smoothScrollToPosition(0);
这两句加上了不管用额。

**Comment by xujianlafeng** [comment]
@CymChad 我写了个demo，怎么给你啊，有邮箱么？

**Comment by Troll4it** [comment]
@CymChad 我的问题是解决了，想了下，为什么又有时加头布局就不滑动，有时就滑动？？？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/984

**Comment by CymChad** [comment]
@xujianlafeng 邮件给我  it_chenyuming@163.com

**Comment by xujianlafeng** [comment]
@CymChad 感谢大佬，我这边找人帮忙解决了。

**Comment by CymChad** [comment]
ok 问题解决就好，你的解决方案是？说出来让大家以后遇到这个问题的时候，也可以快速解决 @xujianlafeng

**Comment by xujianlafeng** [comment]
@CymChad 额，我是曲线救国啊，我没有添加那个内部是RV的headerView了，我直接用了你的多种类型的Adapter。

**Comment by CymChad** [comment]
那也可以，实现一个功能有多种方式，其实你用headerview本质上也是多种类型。

**Comment by FanYimin** [comment]
我也遇到这样的问题。我headerview里面有imageview、textview和一个纵向recyclerview。headerview添加后总是滑动到headerview中的rv那里，而不是显示headerview顶部。我是这样解决的，在headerview顶部添加一个1dp高度的recyclerview，headerview添加之后再让这个1dp的recyclerview setAdapter。这样焦点就滑动到顶部了，虽然有点蛋疼，但是效果很好。
![135442394](https://user-images.githubusercontent.com/12930593/27616993-323b22cc-5be6-11e7-94b8-592d61c8e690.jpg)美女的脸看不见了，焦点在headerview里rv

**Comment by wanglianghai** [comment]
headView 的顶部加上个1dp的recycleview布局

**Comment by MarsToken** [comment]
> @CymChad 感谢大佬，我这边找人帮忙解决了。

![image](https://user-images.githubusercontent.com/16185910/100190693-c75f2c80-2f29-11eb-8beb-8a4fde59e3ee.png)
不应该，这个是源码。我也碰到这个问题了。我看那几种方案都不行。正在看源码。作者彻底解决了吗
