### ISSUE TITLE
添加了ClickableSpan的部分响应其点击事件其余部分响应item的点击事件

### ISSUE THREAD

**Issue by xiang23** [CymChad/BaseRecyclerViewAdapterHelper#1223]
试了几种方法，要么单独响应其一，要么同时两个都响应.试了一下其他issue的方法只能响应clickablespan的其他部分的text点击直接被屏蔽了

**Comment by AllenCoder** [comment]
切换点击事件为 

```java
adapter.setonItemClickListener(listener)

```

然后单独设置clickspan 具体代码demo里面有写到。

[adapter写法](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/PullToRefreshAdapter.java)

**Comment by xiang23** [comment]
试了下demo，同时这样触发了两个点击事件一个item的一个clickspan的，如果把这个textview  加上addOnClickListener的话除了加上clickspan的文字剩下的文字都不触发item的点击事件了。有没有什么好的解决方案？ 
测试机型：genymotion的 custom phone 
android版本:7.0
库版本：2.9.19

**Comment by xiang23** [comment]
不好意思没注意改成adapter的 setonItemClickListener,改完以后clickspan的点击事件正常但是其余文字不触发item的点击事件

**Comment by AllenCoder** [comment]
处理办法参考这篇博文 [http://blog.csdn.net/zhaizu/article/details/51038113](http://blog.csdn.net/zhaizu/article/details/51038113)

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.22'
