### ISSUE TITLE
关于加载更多的问题

### ISSUE THREAD

**Issue by shijiannihao** [CymChad/BaseRecyclerViewAdapterHelper#1225]
就是屏幕只显示一条数据的时候也会触发下拉加载更多，不是应该是滑动到屏幕最后下拉的时候才会触发加载更多吗，

**Comment by CymChad** [comment]
文档有写解决方案 [文档](http://www.jianshu.com/p/b343fcff51b0)。模式是进入回调的，你可以在回调中处理。如：不满足一屏就关闭监听。还可以调用`mQuickAdapter.disableLoadMoreIfNotFullPage();`

**Comment by shijiannihao** [comment]
数据不满一屏幕调用mQuickAdapter.disableLoadMoreIfNotFullPage();是可以解决的
