### ISSUE TITLE
能否增加addRightLayout的功能

### ISSUE THREAD

**Issue by yanjingming** [CymChad/BaseRecyclerViewAdapterHelper#1226]
之所以有这样的需求，源于在做联系人列表时，右侧会有一个用rv实现的sideBar，可是当联系人列表滑动反弹时，也想让sideBar一起滑动反弹，如果是基于rv增加的布局应该就可以跟着一起滑动反弹了。这只是一个小小的需求场景，应该还有其他类似的需求吧，求~~

**Comment by CymChad** [comment]
因为这个和更多的和自定义rv相关，adapter做起来就耦合了，所以不考虑支持。
