### ISSUE TITLE
多种item条目

### ISSUE THREAD

**Issue by lh414035210** [CymChad/BaseRecyclerViewAdapterHelper#1227]
![j b eud hp hoz is oyux](https://user-images.githubusercontent.com/24253339/27278550-49ad3518-5514-11e7-8d4a-a42f4e6204ae.jpg)
![ed w 6 _1j surey o6 5d](https://user-images.githubusercontent.com/24253339/27278559-4e0145be-5514-11e7-9954-49f84e27ef61.png)

**Comment by lh414035210** [comment]
不知道实体类是怎么获取itemType的,  求大神解答!  万分感谢

**Comment by FrankKwok** [comment]
不是已经获取了吗

**Comment by lh414035210** [comment]
这个IMG1, IMG2,IMG3,怎么就和itemType联系上了, 我需要根据  List<String> imgs中图片的数量获取itemType..

**Comment by FrankKwok** [comment]
是自己设定的啊

**Comment by lh414035210** [comment]
怎么设定,求指教.. 真心一点感觉都没有,谢谢

**Comment by FrankKwok** [comment]
不是很明白你的需求

**Comment by FrankKwok** [comment]
说的详细一点

**Comment by lh414035210** [comment]
根据json数据中的一个image集合中图片的数量,得到不同的itemType

**Comment by lh414035210** [comment]
json数据我已经贴出来了

**Comment by FrankKwok** [comment]
好的，容我吃个饭先

**Comment by lh414035210** [comment]
恩,谢了,记得回我哦,今晚做不出来,  我就跳楼了

**Comment by FrankKwok** [comment]
```
@Override
public getItemType() {
  if (imgs.size() == 1) {
    return 0;
  } else if ( imgs.size() == 2) {
    return 1;
  }
}
```
是这个意思吗

**Comment by lh414035210** [comment]
对对

**Comment by lh414035210** [comment]
我看文档上说要给每个数据设置itemType..   不懂什么意思

**Comment by FrankKwok** [comment]
这样就是设置了itemType了，MutipleItemAdapter会用到这个方法

**Comment by lh414035210** [comment]
@Override
            public int getItemType() {
                if (imgs.size() == 1) {
                    return IMG1;
                } else if ( imgs.size() == 2) {
                    return IMG2;
                }
               return IMG3;
            }

**Comment by FrankKwok** [comment]
主要是要看你的业务需求，这个itemType与布局相关联，在创建ViewHolder的时候，是根据实体类的itemType来使用对应的布局

**Comment by lh414035210** [comment]
万分感谢了大神..   已经出来了..  谢谢谢   你这一提醒,抵得上我一下午的时间
