### ISSUE TITLE
三级菜单的子菜单收缩bug

### ISSUE THREAD

**Issue by lxl970211** [CymChad/BaseRecyclerViewAdapterHelper#1228]
setSubItem()如果直接传入一个list,折叠 collpse()时 parentPosition 不正确，展开两个item,先折叠下面的会折叠上一个展开的菜单

## 具体数据添加格式如下

![qq 20170619175610](https://user-images.githubusercontent.com/16635123/27279902-aacdc0de-5518-11e7-9cf1-2ddee50df8c5.png)

## 使用以下方式去添加则没问题
![qq 20170619175748](https://user-images.githubusercontent.com/16635123/27279964-e1b68f5e-5518-11e7-8e2c-dd85527530dc.png)

gif图暂不方便上传
使用的是BRVAH 2.8.0版本  ，测试了在最新的版本中也存在此问题

**Comment by FrankKwok** [comment]
能不能贴出其它部分的代码
