### ISSUE TITLE
after calling setNewData, new list clicks still holds previous list values.

### ISSUE THREAD

**Issue by aalap03** [CymChad/BaseRecyclerViewAdapterHelper#1229]
I have 11 items in my list, I filter them by values added in searchbar and setup the list using filtered data using setNewData which works fine. But after clicking on filtered list, it still holds values of previous list position.

    searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                ArrayList<FileOrFolder> filteredList = new ArrayList<>();

                for(FileOrFolder oneItem : items){ //previous items where 11 and first items click opens screen 1
                    if(oneItem.getDocumentName().toLowerCase().contains(newText.toLowerCase()))
                        filteredList.add(oneItem);
                }

                adapter.setNewData(filteredList);
                //now I have new data and first new item click again goes to screen 1 but it should go to respective items screen
               // I tried notifyRangeInserted, notifyRangeRemoved methods etc.. with new count and start position values but doesnt make any difference.

                return false;
            }
        });

which methods to use after setNewData to hold same item values.. ???

**Comment by FrankKwok** [comment]
which search view, android or v7?

**Comment by aalap03** [comment]
v7

**Comment by FrankKwok** [comment]
I have wrote a demo, no recurrence the bug

**Comment by FrankKwok** [comment]
How you implement the click listener

**Comment by aalap03** [comment]
hey.. I observed that the clicklistener was not in the adapter and outside so it was holding the same values after the filtered list also, so I changed the click handle inside the adapter class and it worked fine.. thank u...

**Comment by FrankKwok** [comment]
🆗
