### ISSUE TITLE
setTextColor doesnot work

### ISSUE THREAD

**Issue by hiwhitley** [CymChad/BaseRecyclerViewAdapterHelper#123]
setTextColor doesnot work
I am doing like this， is any problems？？？？

  baseViewHolder.setText(R.id.tv_name, good.getGoodName())
                .setText(R.id.tv_descr, good.getDescr())
                .setText(R.id.tv_price, "￥ " + good.getPrice())
                .setTextColor(R.id.tv_price, R.color.font_pink);

**Comment by navotera** [comment]
what the error

**Comment by CymChad** [comment]
getView(resId) 获取到控件，然后就可以自己设置了

**Comment by wintercoder** [comment]
setTextColor()第二个参数是int类型，而R.color返回的是String，故你可以用

`
.setTextColor(R.id.tv_price, mContext.getResources().getColor(R.color.font_pink));
`

亲测可用 @hiwhitley

**Comment by IceWaterGuo** [comment]
> setTextColor()第二个参数是int类型，而R.color返回的是String，故你可以用
> 
> `.setTextColor(R.id.tv_price, mContext.getResources().getColor(R.color.font_pink));`
> 
> 亲测可用 @hiwhitley

请问你的上下文怎么拿到的？

**Comment by wintercoder** [comment]
> > setTextColor()第二个参数是int类型，而R.color返回的是String，故你可以用
> > `.setTextColor(R.id.tv_price, mContext.getResources().getColor(R.color.font_pink));`
> > 亲测可用 @hiwhitley
> 
> 请问你的上下文怎么拿到的？

我是fragment里设置，所以肯定能拿到..
