### ISSUE TITLE
有关多类型的奇葩问题

### ISSUE THREAD

**Issue by Troll4it** [CymChad/BaseRecyclerViewAdapterHelper#1230]
这个问题特别奇葩，想了好久都没想通，不好描述需要大佬的邮箱，看了效果才能讲述，求大佬邮箱

**Comment by FrankKwok** [comment]
我的邮箱行吗？ghlfrankkwok@gmail.com

**Comment by Troll4it** [comment]
@FrankKwok 您好，问题已发送  ，用的版本号2.9.20

**Comment by FrankKwok** [comment]
我需要你的item布局

**Comment by Troll4it** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:orientation="vertical">

    <ImageView
        android:id="@+id/sdv_one_img"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="fitXY"/>
</LinearLayout>

**Comment by Troll4it** [comment]
@FrankKwok <?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:orientation="vertical">

    <ImageView
        android:id="@+id/sdv_one_img"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="fitXY"/>
</LinearLayout>

**Comment by FrankKwok** [comment]
你的图片加载框架用的哪个库？

**Comment by Troll4it** [comment]
glide，以前用fresco，最近换成glide的

**Comment by FrankKwok** [comment]
我感觉是这个问题和图片有关

**Comment by Troll4it** [comment]
可是它确实多了很多的item，可以看图，我还特意开了视图的边界

**Comment by Troll4it** [comment]
就是这个，那个空白的不就是item吗

**Comment by FrankKwok** [comment]
这个OneImgRecyAdapter你是怎么写的

**Comment by Troll4it** [comment]
public class OneImgRecyAdapter extends BaseQuickAdapter<RxHomeContentBean, BaseViewHolder> {
    public OneImgRecyAdapter(int layoutResId, List<RxHomeContentBean> data) {
        super(layoutResId, data);
    }


    @Override   这个是我做适配用的
    protected View getItemView(int layoutResId, ViewGroup parent) {
        View view = mLayoutInflater.inflate(layoutResId, parent, false);
        AutoUtils.auto(view);
        return view;
    }

    @Override
    protected void convert(BaseViewHolder helper, RxHomeContentBean item) {
        if (StringUtil.isEmpty(item.getImg()))
        GlideUtils.loadImageView(mContext, item.getImg(), item.getWidth(), String.valueOf(MyApplication.widthPixels * Integer.valueOf(item.getHeight()) / Integer.valueOf(item.getWidth())), helper.getView(R.id.sdv_one_img));
    }
}

**Comment by FrankKwok** [comment]
我这边现在无法复现你这个问题

**Comment by Troll4it** [comment]
我自己也特意写了demo，也没有复现，就在项目中出现，这就头疼

**Comment by FrankKwok** [comment]
这就很难搞了

**Comment by Troll4it** [comment]
我在尝试下解析json数据写个demo，看有没有问题

**Comment by FrankKwok** [comment]
我就是解析json试的

**Comment by Troll4it** [comment]
@FrankKwok 自己狠心把项目的这个module扣出来写成demo，解释json,还是没有复现之前的效果，但是根据大佬你说的应该是图片加载问题，自己给图片设置定高，就没有问题，想想就是图片加载问题，谢谢你

**Comment by FrankKwok** [comment]
这就是不知道问题出在哪里，解决了问题。。。

**Comment by Troll4it** [comment]
图片定为定高，既然没有问题，那就说明不是这个库加载的问题，如果涉及到此库的问题，就需要大佬您的帮助，这个我还真是也是心有余而力不足。既然知道是图片加载的问题，就是自己写的图片加载有点问题，这个简单的也不好意思去麻烦大佬你，嘻嘻嘻        难道动态加载图片与库也有关系？？？

**Comment by Troll4it** [comment]
唯一的疑问就是中间的空白的item，是怎么来的，copy自己的module写成demo也重现不了

**Comment by FrankKwok** [comment]
图片这块我也掌握的一般啊，ImageView的属性挺多的，你可以看看这些scaleType的区别

**Comment by Troll4it** [comment]
好的，谢谢
