### ISSUE TITLE
与EasySwipeMenuLayout结合使用，item 点击事件失效

### ISSUE THREAD

**Issue by liqinghua188** [CymChad/BaseRecyclerViewAdapterHelper#1231]
Activity主要代码如下：

    List<Message> messageList;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_message_list);
        ButterKnife.bind(this);

        initToolBarBack(mToolbar, "消息");
        mRvMessages.setLayoutManager(new LinearLayoutManager(this));

        messageList = new ArrayList<Message>();
        messageList.add(new Message("1111", "1111111", 1));
        messageList.add(new Message("2222", "2222222", 2));
        messageList.add(new Message("3333", "3333333", 3));

        MessageAdapter messageAdapter = new MessageAdapter(R.layout.item_message_view, messageList);

        messageAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                DyToast.show(position + messageList.get(position).getTitle());
            }
        });

        mRvMessages.addItemDecoration(new DividerItemDecoration(MessageListActivity.this, DividerItemDecoration.VERTICAL_LIST));
        mRvMessages.setItemAnimator(new DefaultItemAnimator());
        mRvMessages.setAdapter(messageAdapter);

    }
    
        class MessageAdapter extends BaseQuickAdapter<Message, BaseViewHolder> {

	        public MessageAdapter(@LayoutRes int layoutResId, @Nullable List<Message> data) {
	            super(layoutResId, data);
	        }
	
	        @Override
	        protected void convert(BaseViewHolder helper, Message item) {
	            helper.setText(R.id.message_item_tv_mtitle, item.getTitle());
	            helper.setText(R.id.message_item_tv_subtitle, item.getSubContent());
	        }
	    }
    
    
    
    
item 布局如下：

    <com.guanaj.easyswipemenulibrary.EasySwipeMenuLayout
        android:id="@+id/es"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        app:contentView="@+id/content"
        app:leftMenuView="@+id/left"
        app:rightMenuView="@+id/right">

        <LinearLayout... />

        <LinearLayout... />

		
        <LinearLayout			
            android:id="@+id/right"
            android:layout_width="80dp"
            android:layout_height="match_parent"
            android:gravity="center"
            android:background="@android:color/holo_red_light">

            <TextView
                android:id="@+id/right_menu_2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="删除" />

        </LinearLayout>
    </com.guanaj.easyswipemenulibrary.EasySwipeMenuLayout>  
    
    
    
item点击无效，估计是和EasySwipeMenuLayout 事件机制有冲突

**Comment by AllenCoder** [comment]
EasySwipeMenuLayout  估计是消费掉了item的点击事件

**Comment by AllenCoder** [comment]
@anzaizai

**Comment by dotfeng** [comment]
我也碰到这个问题，按照下面处理的话，会跟侧滑冲突
adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                if(view.getId() == R.id.tv_text) {
                    openActivity();
                }
            }
        });

**Comment by dotfeng** [comment]
@AllenCoder @liqinghua188 EasySwipeMenuLayout 已经修复了这个问题

**Comment by byning2012** [comment]
@dotfeng 为什么我使用的时候还是不能点击？并没有修复这个问题啊

**Comment by AndroidMF** [comment]
有些机型会拦截掉，直接在setOnTouchListener方法里调用删除就OK了
