### ISSUE TITLE
addData();方法存在小bug

### ISSUE THREAD

**Issue by Fomovet** [CymChad/BaseRecyclerViewAdapterHelper#1232]
**版本：2.9.19
问题描述：**
**调用 mAdapter.addData(0, mList)，发现如果是数据插入的位置是第0条的话，需要上下滑动列表后才能看到插入的第0条数据，如果是插入的位置是从1开始mAdapter.addData(1, mList)那么就不会出现这个问题**

**Comment by FrankKwok** [comment]
这样的效果并没有什么问题，比如说现在显示的第一个位置是5，在位置0处添加新数据，难道还要滑动到顶部么，再比如，底部只显示到10，这个时候添加在位置11处添加数据，要不要滑动？如果需要滑动的话，可以自己调用scrollToPosition方法去实现滑动

**Comment by Fomovet** [comment]
@FrankKwok nice！
