### ISSUE TITLE
想把你的框架和阿里巴巴的vlayout结合加一个上滑加载更多的功能实现，不知道怎么搞，老大有思路吗？

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#1233]
想把你的框架和阿里巴巴的vlayout结合加一个上滑加载更多的功能实现，不知道怎么搞，老大有思路吗？

**Comment by FrankKwok** [comment]
这个库不是有这个功能了吗

**Comment by AcgnCodeMonkey** [comment]
刚刚才在看vlayout，不过感觉不行吧，vlayout本身就要使用继承了 他定义的adapter的适配器，和这个库冲突

**Comment by douya40** [comment]
就是发现有冲突，才不知道怎么搞，想完美结合使用，不知道怎么结合使用

**Comment by CymChad** [comment]
目前并没有针对vlayout做过兼容处理，上滑加载更多功能brvah可以独立完成。
