### ISSUE TITLE
上拉加载问题

### ISSUE THREAD

**Issue by ITskyIT** [CymChad/BaseRecyclerViewAdapterHelper#1235]
为什么请求数据后 会自动一直触发上拉加载onLoadMoreRequested()此方法

**Comment by AllenCoder** [comment]
参考 
1. [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1094](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1094)

2. [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/983](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/983)
