### ISSUE TITLE
几点疑惑

### ISSUE THREAD

**Issue by toutoumu** [CymChad/BaseRecyclerViewAdapterHelper#1238]
1. {@link BaseQuickAdapter.RequestLoadMoreListener#onLoadMoreRequested}这个方法能否添加一个参数,最好是int类型的,加载更多,和刷新的时候一般都是使用的同样的服务, 但是这个方法没有一个参数来标识,这次调用时刷新还是加载更多,Adapter中也没法知道,Adapter#isLoading这个感觉不太可靠,因此我在实现的时候都是自定义一个变量来作为刷新或者加载更多.
2. Adapter 中mData属性能否做成final类型: 我在使用的时候Fragment中想要保存一份Adapter中mData的引用,非final类型实现起来比较麻烦.每次都需要手动更新Fragment的引用,能否将Adapter.setNewData改成清空mData中数据,再把新数据添加进去,并且在构造函数就判断mData不能为空,而不是为空则创建.
3. 有这样一个需求,一开始进入页面没有数据,需要显示一个正在加载的loading.列表没有数据此时网络异常需要显示一个网络异常的View.空数据(已经有)没有判断是否已经设置过同样的view(布局文件)
希望优化这几个功能.

**Comment by AllenCoder** [comment]
1. 后续考虑加入优化任务项

2. setNewData的Api设计是为了替换一份全新的数据，如果是为了刷新数据，构造adapter时，应该传入一个final类型的数据的引用，刷新时，只需
```java
mData.clear()；
mData.addAll(list);
mAdapter.notifyDataSetChanged();
```

3. 这个应该属于recyclerview父层的任务，不建议耦合到recyclerView里面加入loading的view

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.21'
