### ISSUE TITLE
数据刷新及EmptyView的相关问题

### ISSUE THREAD

**Issue by JiayiHuang** [CymChad/BaseRecyclerViewAdapterHelper#1241]
当RecyclerView的数据不满一屏时，刷新数据会导致：
1. RecyclerView有稍长时间的空白闪烁。有时还会刷新加载数据失败，一直空白。
2. 如果之前有设置EmptyView，那么在这段空白时间内，就会显示之前所设置的EmptyView。

另外，Adapter刷新数据导致RecyclerView空白的问题是怎么产生的？
我禁用了RecyclerView加载的动画，并同时设置Item动画时长为0，都没有效果。应该不是这个问题。

**Comment by CymChad** [comment]
复现方式是？能录制一个gif，看看吗？

**Comment by JiayiHuang** [comment]
![1](https://user-images.githubusercontent.com/10696896/27521740-d8995200-5a52-11e7-909e-cc228b858023.gif)
开始加载失败的EmptyView，点击后展示加载的EmptyView，加载成功后，刷新数据，RecyclerView闪烁，偶尔会出现加载失败，一直空白。
在空白期间会显示之前设置的加载中的EmptyView（这个问题修改源码已经解决）。

**Comment by 1109993488** [comment]
你刷新数据怎么刷新的？能否贴下代码？

**Comment by JiayiHuang** [comment]
最开始是按照通常的方法：
mAdapter.notifyDataSetChanged();
发现有点问题后，有修改成Demo中的方法：
mAdapter.setNewData(this.missions);
不过后者的数据刷新最后也是调用的前者，所以并没有效果。
在数据很多的时候，没有出现这个空白闪烁，只有在数据不足一屏或刚好一屏的时候才有（当前我的情况）。

**Comment by 1109993488** [comment]
下拉刷新闪烁跟你显示加载中逻辑判断有关吗？

**Comment by JiayiHuang** [comment]
这个应该没有，同样的代码，在数据多的时候就没有闪烁的现象

**Comment by 1109993488** [comment]
你可以参考下demo的EmptyViewUseActivity，或者看在demo上能否复现

**Comment by JiayiHuang** [comment]
实在抱歉，我在Presenter中请求数据的时候，没有去掉模拟数据时的显示数据，导致它会刷新两遍数据。我一直都在检查Activity中View的逻辑。耽误你们的时间了。
