### ISSUE TITLE
当我的数据大小刚好为分页大小2倍时候，为什么不会调用onLoadMoreRequested方法了

### ISSUE THREAD

**Issue by chg2018** [CymChad/BaseRecyclerViewAdapterHelper#1243]
如题，我感觉很诡异，第二页滑动到底的时候一直在显示 正在加载中。。。，不再调用onLoadMoreRequested方法了

**Comment by CymChad** [comment]
版本，代码。请贴出

**Comment by chg2018** [comment]
2.9.22

**Comment by CymChad** [comment]
使用代码呢？

**Comment by 1109993488** [comment]
addData后要调用loadMoreComplete，否则一直显示正在加载中

**Comment by chg2018** [comment]
搞定了，@addData后要调用loadMoreComplete，否则一直显示正在加载中

**Comment by chg2018** [comment]
mSwipeRefreshLayout.setRefreshing(false);
        mCurPageIndex++;

        if (!CollectionUtils.isEmpty(result.data)) {
            LogUtil.d(TAG, result.data.size());

            if (result.data.size() < WenWenConst.PAGE_SIZE) {
                mAdapter.loadMoreEnd(mLoadMoreEndGone);
            }
            for (WenDouJiLuDTO mWenDouJiLuDTO : result.data) {
                mEntity = new WenDouJiLuItem(mWenDouJiLuDTO);
                mAdapter.addData(mEntity);
            }

            mAdapter.loadMoreComplete();

        } else {
            mAdapter.loadMoreEnd(mLoadMoreEndGone);
        }

        mSwipeRefreshLayout.setEnabled(true);

**Comment by chg2018** [comment]
@Override
    public void onLoadMoreRequested() {
        mSwipeRefreshLayout.setEnabled(false);

        if (mAdapter.getData().size() < WenWenConst.PAGE_SIZE) {
            mAdapter.loadMoreEnd(true);
            return;
        }

        getWenDouHistoryList(new QueryWenDouJiLuDTO(mCurPageIndex * WenWenConst.PAGE_SIZE));
    }
