### ISSUE TITLE
Multiple layouts (Grid and List)

### ISSUE THREAD

**Issue by dsdebastiani** [CymChad/BaseRecyclerViewAdapterHelper#1244]
Is it possible to create and unique adapter with dynamic layouts?
The propose is to change the recycleView layout manager from list to grid and vice versa, but changing the res layout file to same data list.

If the adapter is in mode LIST it will load list_item_layout;
If the adapter is in mode  GRIT it will load grid_item_layout;

**Comment by liu-hailin** [comment]
ok  ,  you can do it .

**Comment by dsdebastiani** [comment]
Ok, so... I can do it. But do you have any idea of how to do it?
The `BaseQuickAdapter` accepts only one `layout_id` in the constructor.

**Comment by CymChad** [comment]
Can `extends BaseMultiItemQuickAdapter` implementation

**Comment by CymChad** [comment]
Change the LayoutManager can change the type to realize the layout change
