### ISSUE TITLE
自定义view

### ISSUE THREAD

**Issue by a237112263** [CymChad/BaseRecyclerViewAdapterHelper#1246]
没发现item自定义view怎么用？

**Comment by FrankKwok** [comment]
什么意思？

**Comment by FrankKwok** [comment]
convert里面使用Holder的getView方法

**Comment by a237112263** [comment]
大神我在点击item里面的一个控件，获取亮一个控件时对象报空？





------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年6月26日(星期一) 下午4:14
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "‰∮飛∮￡"<371116959@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 自定义view (#1246)




Closed #1246.

**Comment by a237112263** [comment]
谢谢，已经找到方法了





------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年6月26日(星期一) 下午4:14
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "‰∮飛∮￡"<371116959@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 自定义view (#1246)




Closed #1246.

**Comment by a237112263** [comment]
大神BaseRecyclerViewAdapterHelperk可以实现图片瀑布流吗？




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年6月26日(星期一) 下午4:14
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "‰∮飛∮￡"<371116959@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 自定义view (#1246)




Closed #1246.

**Comment by FrankKwok** [comment]
@a237112263 使用StaggeredGridLayoutManager
