### ISSUE TITLE
BaseMultiItemQuickAdapter分组的形式一些问题

### ISSUE THREAD

**Issue by Anbinghui** [CymChad/BaseRecyclerViewAdapterHelper#1247]
我现在有一个需求是:一级item和二级item都能够上下移动.在移动一级的时候没有问题.下面是二级item移动时遇到的问题希望能够得到您的帮助:
改变二级item位置的时候使用Collections.swap和adapter.notifyItemMoved(position,position-1);但是在关闭一级item重新打开以后位置又重新回到原来的状态了.
二级item的position我怎么去判断他是属于哪个一级item.我看二级item的position是递增上去的.向上移动时能直接移动到另一个一级item里面.

**Comment by CymChad** [comment]
在你Moved的时候需要改变数据源数据。你是用的Expandable的方式吗？

**Comment by CymChad** [comment]
如果是的话你可以通过二级item的对象使用getParentPosition方法拿到第一级的position
