### ISSUE TITLE
这个 可以做侧拉删除吗

### ISSUE THREAD

**Issue by to686312** [CymChad/BaseRecyclerViewAdapterHelper#1248]

**Comment by CymChad** [comment]
可以，配合https://github.com/anzaizai/EasySwipeMenuLayout 使用

**Comment by to686312** [comment]
谢谢  大神  一直使用 baserecyclerviewhelp  感觉棒棒的  感谢大神的 贡献啊

**Comment by CymChad** [comment]
@to686312 感谢认可

**Comment by to686312** [comment]
能加个微信吗   大神  跟上大神的脚步   我微信：13881100969
