### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by aa6868226** [CymChad/BaseRecyclerViewAdapterHelper#1249]
ExpandRecyclerView向上滑动的时候怎么将能点击下拉的头部顶在顶部

**Comment by CymChad** [comment]
配置 https://github.com/oubowu/PinnedSectionItemDecoration  使用

**Comment by aa6868226** [comment]
谢谢 您发的这个有悬浮头部 但是不是ExpandRecyclerView 怎么实现ExpandRecyclerView那样点击悬浮头部可扩展收起

**Comment by CymChad** [comment]
原理一样的，可以配合使用。
