### ISSUE TITLE
在vivo X9手机上发生ClassCastException

### ISSUE THREAD

**Issue by MorganGeng** [CymChad/BaseRecyclerViewAdapterHelper#1250]
我使用BaseQuickAdapter展示了一个列表,自定义了ViewHolder继承自BaseViewHolder,然后在vivo x9上发生了crash.BaseViewHolder cannot cast to 自定义的Viewholder.
PS:有看到文档介绍自定义的viewholder使用外部类继承BaseViewHolder   但问题还是发生了,麻烦帮忙看一下原因

**Comment by FrankKwok** [comment]
异常信息以及版本？

**Comment by MorganGeng** [comment]
版本:compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.18'
异常信息:java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.xxx.xxx.ui.viewholder.TimerViewHolder

**Comment by FrankKwok** [comment]
@MorganGeng 你的Adapter怎么写的？

**Comment by MorganGeng** [comment]
@FrankKwok 就是最普通的adatper,特别之处就是我在自定义的ViewHolder中封装了计时器方法.

我现在怀疑是不是可能与混淆有关系,我在试.

**Comment by MorganGeng** [comment]
@FrankKwok   感谢回复! 问题已经解决.

我在混淆中添加了:
-keep class * extends com.chad.library.adapter.base.BaseViewHolder{
   *;
}
之后正常运行了.

**Comment by caldremch** [comment]
#添加以下混淆规则可解决
#保留继承于BaseViewHolder的内部类不被混淆
-keep class $ extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
(...);
}
