### ISSUE TITLE
NestedScrollView嵌套RecyclerView加载更多问题

### ISSUE THREAD

**Issue by Glgo** [CymChad/BaseRecyclerViewAdapterHelper#1251]
这种情况下会自动加载更多，内存会一直涨上去。就算设置mAdapter.setAutoLoadMoreSize(0);也不管用。请问作者这种情况下怎样才能跟正常状态下的上拉加载更多效果一样呢？

**Comment by FrankKwok** [comment]
#910

**Comment by Glgo** [comment]
可不可以换个方案：把原来RecycleView上面的部分，作为RecycleView的HeaderView这样就能解决滑动的问题了

**Comment by FrankKwok** [comment]
这样是可以的
