### ISSUE TITLE
在adapter中获取不到position,点击删除使用EasySwipeMenuLayout 时如何处理删除item

### ISSUE THREAD

**Issue by dotfeng** [CymChad/BaseRecyclerViewAdapterHelper#1252]
在adapter中获取不到position
helper.getView(R.id.tv_delete).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                remove(position);
            }
        });

**Comment by FrankKwok** [comment]
helper可以获取position

**Comment by FrankKwok** [comment]
有专门的ClickItem方法的

**Comment by dotfeng** [comment]
@FrankKwok 多谢，已经解决。`remove(helper.getAdapterPosition());`
不使用setOnItemChildClickListener主要是EasySwipeMenuLayout 需要helper获取布局
`EasySwipeMenuLayout easySwipeMenuLayout = helper.getView(R.id.es);
easySwipeMenuLayout.resetStatus();`

**Comment by FrankKwok** [comment]
🆗
