### ISSUE TITLE
最新可依赖的版本号是多少?

### ISSUE THREAD

**Issue by jiaqiangsheng** [CymChad/BaseRecyclerViewAdapterHelper#1254]
最新的2.9多的都试过了，都报错Not Found,我直接用的2.0.0，后面的可以版本那个还可以用

**Comment by CymChad** [comment]
你是不是版本号前面加了个v？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases  版本号看这里

**Comment by jiaqiangsheng** [comment]
ok，不加v就可以了。谢谢！
