### ISSUE TITLE
在item的点击事件回调中调用刷新会刷掉点击效果

### ISSUE THREAD

**Issue by ChineseCodeFarmer** [CymChad/BaseRecyclerViewAdapterHelper#1261]
我给item设置了ripple点击效果，在item的点击事件的回调中调用adapter.notifyDataSetChanged()，波纹效果会被刷掉，请问这个问题有什么好的解决办法吗？

**Comment by AllenCoder** [comment]
点击波纹效果开始时，立即就回调了adapter.notifyDataSetChanged()；会导致视图重绘刷新，波纹效果会被刷掉；
解决办法只有，在点击事件发生后，延时调用adapter.notifyDataSetChanged() 或者关闭波纹动画

**Comment by ChineseCodeFarmer** [comment]
我的item上有个CheckBox，延迟刷新体验会非常的差，肯定是不行的，而且我调用adapter.notifyItemChanged()单独刷新我点击的item的时候，波纹效果依然存在。

**Comment by AllenCoder** [comment]
针对这个issue ，我认为不是适配器的bug ，而是你的视图刷新和view的点击效果ripper冲突的原因 。

可参考该问题[https://stackoverflow.com/questions/34191427/recyclerview-item-not-showing-ripples-touch-feedback-when-the-item-has-a-checkbo](https://stackoverflow.com/questions/34191427/recyclerview-item-not-showing-ripples-touch-feedback-when-the-item-has-a-checkbo)
notifyDataSetChanged() will conflict with those default ripple effects.
![image](https://user-images.githubusercontent.com/8213915/27675241-c7b39776-5cdb-11e7-9a45-23ce338e1b8c.png)

可考虑改变需求方案，或者需求更好的解决方案
