### ISSUE TITLE
嵌套recycleview

### ISSUE THREAD

**Issue by stoneLee81** [CymChad/BaseRecyclerViewAdapterHelper#1262]
在使用DEMO中的嵌套RV做的列子，加载首屏幕嵌套RV没有数据，往下滚动到第二屏嵌套RV就有数据了，在网上滚动到首屏，首屏嵌套RV数据恢复

但如果这样使用
**helper.getView(tv_name).post(() -> {**
                    this.subRecyclerView(helper, helper.getView(recyclerview), helper.getView(tv_name), new ImageAdapter(item.getMItems(), helper.getView(tv_name).getWidth()));
                **});**

protected void subRecyclerView(BaseViewHolder helper, RecyclerView rv, TextView tv, BaseMultipleAdapter mAdapter) {
        rv.setLayoutManager(new GridLayoutManager(helper.itemView.getContext(), C.GRID_COL, GridLayoutManager.VERTICAL, false));
        rv.setHasFixedSize(true);
        mAdapter.setSpanSizeLookup((gridLayoutManager, position) -> mAdapter.getData().get(position).getSpanSize());
        rv.setAdapter(mAdapter);
    }
加载首屏嵌套RV就有数据

请问这个是BUG还是？

**Comment by CymChad** [comment]
请检查一些你的数据源，demo显示正常呀

**Comment by AllenCoder** [comment]
Demo的recyclerview嵌套recyclerView之前遇到每次进入会自动定位到嵌套的item的recyclerView 通过设置父item的recyclerView的焦点

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_item_click"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/bg"
    android:focusable="true"
    android:focusableInTouchMode="true"
    tools:context="com.chad.baserecyclerviewadapterhelper.ItemClickActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/list"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</RelativeLayout>

```
优先获取焦点

2. 尝试设置 父item 的RecyclerView 的minHeight 使其minHeight>0
