### ISSUE TITLE
convert方法只执行一次，但数据有多条，并且尾布局不显示？

### ISSUE THREAD

**Issue by DaiFalin** [CymChad/BaseRecyclerViewAdapterHelper#1265]
在AVD模拟器7.1.1上正常显示，在6.0的真机（乐视，小米手机）上convert()只会执行一次，添加的尾布局也不显示，使用的2.9.22。

**Comment by CymChad** [comment]
你的item是不是填充了一整个屏幕？

**Comment by DaiFalin** [comment]
android:layout_width="match_parent"
    android:layout_height="wrap_content"
最外层是这样的

**Comment by CymChad** [comment]
你在rv外层套了其他滚动控件吗？

**Comment by DaiFalin** [comment]
对的，最外层有ScrollView，但是我屏蔽了RecyclerView的滚动。

**Comment by CymChad** [comment]
如果去掉，你试试看是否显示正常？

**Comment by DaiFalin** [comment]
去掉了正常显示，因为这个界面有很多其他的布局，所以嵌套了ScrollView，当嵌套了ScrollView之后，helper.getLayoutPosition()方法只会返回一次0。

**Comment by CymChad** [comment]
其他布局是否可以用添加头部或者尾部的方式来处理？

**Comment by CymChad** [comment]
从这个问题上来看，不是adapter的问题，而是滚动布局和滚动布局之间的冲突问题。我在想是不是可以换种方式来实现你的需求更为合适。

**Comment by DaiFalin** [comment]
是的，滚动布局之间的冲突问题，目前只有考虑RecyclerView多布局或者动态计算RecyclerView高度。

**Comment by CymChad** [comment]
恩，我觉得可以用多布局来解决，并且你也可以轻松通过添加头部或者尾部的方式来实现你的需求。因为头部和尾部都是支持添加多个的。

**Comment by DaiFalin** [comment]
好的，谢谢指点！可以close issue 了
