### ISSUE TITLE
可展开的列表，一级页面添加点击时的背景颜色，列表的背景颜色错乱

### ISSUE THREAD

**Issue by flyzend** [CymChad/BaseRecyclerViewAdapterHelper#1267]
![image](https://user-images.githubusercontent.com/5538443/27677145-3309ea14-5ce3-11e7-95d4-ef9802642c04.png)
这是demo ，我就在点击一级按钮的时候，加了背景颜色，然后颜色显示就不正常了，非常乱

**Comment by CymChad** [comment]
如果当初的改变某个view的颜色，肯定会有错乱问题。这是缓存机制的问题。

**Comment by CymChad** [comment]
解决方案就是，通过改变数据来改变颜色。

**Comment by flyzend** [comment]
我猜也是缓存，改变数据来改变颜色怎么做？

**Comment by flyzend** [comment]
只是点击展开和收起需要改变一级列表的颜色，数据是没变的

**Comment by CymChad** [comment]
把第一级的状态存到第一级的实体类中，颜色的改变由改变数据实体的属性来控制view的改变。

**Comment by CymChad** [comment]
http://www.jianshu.com/p/b343fcff51b0 文档也有描述缓存问题的解决方案，以及案例。

**Comment by CymChad** [comment]
原理类似

**Comment by flyzend** [comment]
解决了，谢谢！
