### ISSUE TITLE
快速上拉加载更多，不触发loadMore

### ISSUE THREAD

**Issue by SephirothLT** [CymChad/BaseRecyclerViewAdapterHelper#1268]
数据整体是有多页的，但是在初始化完成之后快速滑动，只能加载两页的数据。在初始化完成后慢慢滑动才可以将全部页加载完，求解？

**Comment by 1109993488** [comment]
快速滑动不加载的时候加载更多显示加载中吗？，看下是否调用了loadMoreComplete，只有调了这个才会下一次请求

**Comment by SephirothLT** [comment]
@1109993488  没有显示加载中，调用了这个方法啊 。现在的问题是，滑动快，可能导致不进行加载更多。不是能不能加载更多的问题。

**Comment by 1109993488** [comment]
滑动回调跟滑动快慢没关系，你有调用setEnableLoadMore(false)或disableLoadMoreIfNotFullPage()？

**Comment by SephirothLT** [comment]
@1109993488 调用了啊 我也很郁闷啊。。。

**Comment by 1109993488** [comment]
调用了disableLoadMoreIfNotFullPage？如果调用了这个，快速滑动就有这个问题

**Comment by SephirothLT** [comment]
@1109993488 那有什么解决办法吗？

**Comment by 1109993488** [comment]
你可以不调disableLoadMoreIfNotFullPage，自己在下拉刷新的时候判断是否还有数据关闭加载更多

**Comment by SephirothLT** [comment]
@1109993488  我试试 不过这样的话  可能导致不满一屏的时候总是调用loadMore

**Comment by CymChad** [comment]
不会总是调用loadMore，调用loadMore后，就知道关闭回调。所以只会调用一次loadMore。
