### ISSUE TITLE
compile失败...

### ISSUE THREAD

**Issue by tromoLi** [CymChad/BaseRecyclerViewAdapterHelper#1269]
已经添加了 maven { url "https://jitpack.io" }
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://dl.bintray.com/thelasterstar/maven/" }
        maven { url "https://jitpack.io" }
    }
}
然后 Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.22

**Comment by FrankKwok** [comment]
感觉是其他问题引起的

**Comment by tromoLi** [comment]
今天又正常了，昨天as大姨妈了应该
