### ISSUE TITLE
GridLayoutManager布局时候上拉加载不回调

### ISSUE THREAD

**Issue by xicong** [CymChad/BaseRecyclerViewAdapterHelper#1274]
第一次初始化正常，然后手动下拉刷新一次，再滚动到底部不会回调下拉加载更多的方法

**Comment by 1109993488** [comment]
请参考demo，你这种情况下拉加载处于什么状态？，手动下拉刷新一次获取到数据如果调用setNewData后滑动到底部肯定会回调加载更多的
