### ISSUE TITLE
关于适配器中使用Edittext的问题,看了简书上的处理的疑问。

### ISSUE THREAD

**Issue by z332406259** [CymChad/BaseRecyclerViewAdapterHelper#1275]
简书上的处理是：让我参考RecyclerViewEditTextDemo-master这个项目。这个项目DemoListAdapter类的convert方法里面依旧是使用etAge.addTextChangedListener(new TextWatcher() {...});只是暴露一个接口监听OnItemEditTextChangedListener，这样的话，在条目很多的情况下。每个复用的edittext都会add大量的TextChangedListener。导致很多无用的监听。我想在edittext构造的时候处理,但是找不到相关的方法。除非自定义BaseViewHolder。所以想问问作者有没有相关的方法。

**Comment by Pyuming** [comment]
http://www.it1352.com/117863.html   可以看下这里面的方法

**Comment by z332406259** [comment]
看来需要自定义baseviewholder在构造里做处理了。感谢作者！
