### ISSUE TITLE
在多布局的时候使用addHeaderView之后，我使用adapter.notifyItemRemoved(position);会报错

### ISSUE THREAD

**Issue by Arthurshen98** [CymChad/BaseRecyclerViewAdapterHelper#1278]
在多布局的时候使用addHeaderView之后，我使用adapter.notifyItemRemoved(position);会报错删除某一个item会报错，如果我先删除的是item显示较少的那个A布局，再删除B布局不会报错，但是如果A布局不删除，先删除B布局类型，就报错。仅仅使用adapter.notifyDataSetChanged();没有问题，但是notifyItemRemoved()方法无法调用就没有删除动画。
![image](https://user-images.githubusercontent.com/15273559/27821913-7aa539c2-60d6-11e7-8b63-d6f59ffd726f.png)

**Comment by FrankKwok** [comment]
看不太懂，组织一下问题

**Comment by CymChad** [comment]
删除布局的同时你删除了数据吗？
