### ISSUE TITLE
Rv嵌套Rv时候 外部Rv点击事件失效。点击没有反应。

### ISSUE THREAD

**Issue by m511386374** [CymChad/BaseRecyclerViewAdapterHelper#1282]

**Comment by AllenCoder** [comment]
参考Demo ItemClickActivity的嵌套点击事件写法 
[`https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java`](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java)

**Comment by m511386374** [comment]
@Override
    public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
        Logger.d("嵌套RecycleView item 收到: " + "点击了第 " + position + " 一次");
        Toast.makeText(Utils.getContext(), "嵌套RecycleView item 收到: " + "点击了第 " + position + " 一次", Toast.LENGTH_SHORT).show();
    }

使用这个方法没有效果、、

**Comment by m511386374** [comment]
外层的reyclerView拦截点击事件一直都被内部reyclerView给消费了

**Comment by m511386374** [comment]
问题已经解决 我在布局里面加了这个属性，导致点击事件有问题。android:clickable="true"
 谢谢！
