### ISSUE TITLE
setEmptyView的问题

### ISSUE THREAD

**Issue by zhengliufeng** [CymChad/BaseRecyclerViewAdapterHelper#1289]
在使用了adapter.setNewData()后，再使用setEmptyView()无效，还是原来有数据的界面，没有变成空数据界面。

**Comment by FrankKwok** [comment]
用法错误

**Comment by FrankKwok** [comment]
#1105

**Comment by zhengliufeng** [comment]
我的和这个有点差别，我是两个按钮点击切换数据，但是用的是同一个recycleview，在page是1的时候没有数据的话设置空布局，在page>1时就是下面显示没有更多数据。现在是一个列表有数据，一个列表没有数据，两个切换的时候出的问题

**Comment by FrankKwok** [comment]
没明白，这样会引起什么问题？

**Comment by zhengliufeng** [comment]
![1](https://user-images.githubusercontent.com/19903583/27901140-7dbf2f8a-6263-11e7-98ab-a0380331d1f7.png)
![2](https://user-images.githubusercontent.com/19903583/27901156-86ef27ae-6263-11e7-9fe9-db643bc5397e.png)
![3](https://user-images.githubusercontent.com/19903583/27901166-8cb7b052-6263-11e7-8bed-9b1262f183f2.png)

就是这样切换后出问题了

**Comment by FrankKwok** [comment]
共享Adapter？

**Comment by zhengliufeng** [comment]
是的

**Comment by FrankKwok** [comment]
那你切换页面的时候要切换数据的，这里的代码是怎么做的？

**Comment by zhengliufeng** [comment]
initData（Boolean  isInit）；   true的话adapter.setNewData,  falsed的话adapter。addData。

**Comment by FrankKwok** [comment]
你这样我看不出来问题啊，我觉得是你切换的代码写得有误

**Comment by zhengliufeng** [comment]
好吧  我后面在setEmptyView前加了setnewData就行了
mVipSubjectAdapter.setNewData(new ArrayList<VideoListBean.BodyBean>());
mVipSubjectAdapter.setEmptyView(getEmptyView());

**Comment by FrankKwok** [comment]
如果所有页面的emptyView都一样，不用每次都setEmptyView的，一开始设置一次配置好就行了

**Comment by zhengliufeng** [comment]
这样的话如果分页加载时第二页没有数据会不会边成emptyview

**Comment by FrankKwok** [comment]
不会的，你可以试试

**Comment by zhengliufeng** [comment]
哦  好的   谢谢
