### ISSUE TITLE
空布局不显示

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#1290]
如题，我在第一次加载列表设置adapter.setEmptyView(R.layout.layout_emptyview, (ViewGroup) recyclerView.getParent());时空布局会加载出来，但是当我渲染了新的adapter后再去设置空布局就发现空布局不会再显示了，请问这是什么情况啊？

**Comment by zuoanguo** [comment]
我也是这样的情况，有解决这个问题吗？

**Comment by BugMen** [comment]
嗯，你只需要在initAdapter的时候设置一遍空布局就好了




------------------ 原始邮件 ------------------
发件人: "zuoanguo";<notifications@github.com>;
发送时间: 2017年7月28日(星期五) 下午4:17
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 空布局不显示 (#1290)




我也是这样的情况，有解决这个问题吗？
