### ISSUE TITLE
下拉加载出现问题  

### ISSUE THREAD

**Issue by 15121144267** [CymChad/BaseRecyclerViewAdapterHelper#1291]
进入页面直接回调下拉加载接口 disableLoadMoreIfNotFullPage()设置有效 但是就失去加载功能了

**Comment by 15121144267** [comment]
初始化：mShopDetailRecyclerView.setLayoutManager(new GridLayoutManager(this, 2));
        mAdapter = new ShopDetailAdapter(null, this);
        mShopDetailRecyclerView.setAdapter(mAdapter);
        mAdapter.setOnLoadMoreListener(this, mShopDetailRecyclerView);
这是我拿到list数据的方法
@Override
    public void transformShopGoodsListSuccess(List<ShopDetailResponse.ProductsBean> products) {
        mList = products;
        if (products.size() > 0) {
            mAdapter.addData(mList);
            mAdapter.loadMoreComplete();
        } else {
            mAdapter.loadMoreEnd();
        }
    }
这是下拉加载回调 进入页面第一次add数据的时候 直接走这里了  我在看asmple的时候并没有  其他项目也没有
@Override
    public void onLoadMoreRequested() {
        if (mList.size() < mPagerSize) {
            mAdapter.loadMoreEnd(true);
        } else {
            mPresenter.requestShopGoodsList(++mPagerNo, mPagerSize);
        }
    }

 myCompileSdkVersion = 25
    myBuildToolsVersion = "25.0.3"
  myDsign: "com.android.support:design:25.2.0",

**Comment by FrankKwok** [comment]
如果不满一页也要加载更多，你可以不调用`disableLoadMoreIfNotFullPage()`
