### ISSUE TITLE
添加空布局和添加头布局有冲突么

### ISSUE THREAD

**Issue by xdjm** [CymChad/BaseRecyclerViewAdapterHelper#1293]
为什么在同时有的情况下，只显示了头布局，而没显示空布局，总感觉空布局有点怪怪的

**Comment by CymChad** [comment]
没有冲突，默认是显示一个，如果想同时显示可以通过方法设置  具体查看文档 http://www.jianshu.com/p/b343fcff51b0

**Comment by chenkexu** [comment]
@CymChad ，如果想同时显示头布局和空布局怎么设置啊？

**Comment by chenkexu** [comment]
@Override
    public void getCollectShopList(List<ProductListEntity> projectListData) {
        //结束刷新
        setRefreshing(false);
        //没数据
        if (projectListData == null||projectListData.size()==0) {
            collectShopAdapter.setNewData(null);
//            空布局
            collectShopAdapter.setEmptyView(R.layout.layout_no_seach_cloth, (ViewGroup) myRecyclerView.getParent());
            collectShopAdapter.setHeaderAndEmpty(true);
        }else{
            collectShops = projectListData;
            setData(true, collectShops);
            collectShopAdapter.setEnableLoadMore(true);
        }
    }

这样设置还是不行啊，空布局显示不出来
