### ISSUE TITLE
header时一个viewPager是，滑动出现问题

### ISSUE THREAD

**Issue by qsxs** [CymChad/BaseRecyclerViewAdapterHelper#1295]
版本2.9.23，头部是一个viewPager,为这个viewPager  addOnPageChangeListener 后回出现viewPager滑动卡顿，viewPager  不能自动根据滑动距离选中原页或者下一页

**Comment by qsxs** [comment]
准确的说是在addOnPageChangeListener 中调用adapter.setNewData就不出现这种情况

**Comment by FrankKwok** [comment]
最好代码贴出来
