### ISSUE TITLE
能否实现多布局带头部的效果呢？

### ISSUE THREAD

**Issue by HeJingWei** [CymChad/BaseRecyclerViewAdapterHelper#1296]
能否实现多布局带头部的效果呢？

**Comment by FrankKwok** [comment]
多布局和头部不冲突的

**Comment by HeJingWei** [comment]
大神请教一个问题，我这边要实现一个多布局带头部的recyclerView.其中有一个布局中又是一个垂直并且带多布局的列表，这个垂直列表是不是就得用整个高度的recyclerView或listview了？这样就不能无限加载了吧，会卡

**Comment by FrankKwok** [comment]
把多布局变成很多item呢？

**Comment by HeJingWei** [comment]
就是其中一个item中又带了一个多布局的列表，貌似只能计算出全部高度显示完全了

**Comment by CymChad** [comment]
恩 是的 只能全部显示。添加头部本质上就是多添加了一种类型，所以和多布局不冲突。
