### ISSUE TITLE
remove(position) 批量删除，positon自动调整

### ISSUE THREAD

**Issue by stormlei** [CymChad/BaseRecyclerViewAdapterHelper#1297]
remove(position) 删除一个后，因为position自动调整，再删除该位置上的项，就会错误，这个该怎么处理？ @CymChad

**Comment by FrankKwok** [comment]
批量删除的position是随机的吗，还是连着的？

**Comment by CymChad** [comment]
http://blog.csdn.net/u010507199/article/details/46496187  原理都是一致的，先通过标注属性，然后在删除。

**Comment by stormlei** [comment]
@FrankKwok 随机的。通过标注属性确实可以解决，不过数据一般都是接口获取的，还要自己每个都加一个标记，不知有没有其他方法？

**Comment by FrankKwok** [comment]
因为复用机制的存在，只能在实体类里标记，不能根据view的状态判断

**Comment by jesse920524** [comment]
批量删除可以把position存放在一个list中,再使用Collections.sort()后Colletions.reverse()将数据先排序后反序.
最后遍历list执行adapter.remove(position)
这样删除时就是倒序删除了,不会出现position乱序的问题.
