### ISSUE TITLE
ExpandableAdapter

### ISSUE THREAD

**Issue by nuli1228588792** [CymChad/BaseRecyclerViewAdapterHelper#1298]
怎样才能只展开一项呢，我现在怎么写也不能只展开一项

**Comment by FrankKwok** [comment]
expand方法

**Comment by zhaoxiuyu** [comment]
@FrankKwok  展开 调用的这个 expand方法，当我点击其他项的时候也会展开。怎么设置 同时只能展开一项？ 点击另一项的时候，之前展开的自动关闭？
