### ISSUE TITLE
滑动删除时判空一下数组的长度

### ISSUE THREAD

**Issue by xdjm** [CymChad/BaseRecyclerViewAdapterHelper#1299]
版本2.9.23
在BaseItemDraggableAdapter.java中的246行中如下：
```
public void onItemSwiped(RecyclerView.ViewHolder viewHolder) {
        if (mOnItemSwipeListener != null && itemSwipeEnabled) {
            mOnItemSwipeListener.onItemSwiped(viewHolder, getViewHolderPosition(viewHolder));
        }

        int pos = getViewHolderPosition(viewHolder);

        mData.remove(pos);
        notifyItemRemoved(viewHolder.getAdapterPosition());
    }
```

判定一下mData的长度再进行remove，做一个项目时报错了 ，报错如下

`java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
at java.util.ArrayList.remove(ArrayList.java:405)
at com.chad.library.adapter.base.BaseItemDraggableAdapter.onItemSwiped(BaseItemDraggableAdapter.java:246`

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.24'
