### ISSUE TITLE
关于不走convert方法

### ISSUE THREAD

**Issue by nakisaren** [CymChad/BaseRecyclerViewAdapterHelper#13]
你好，今天用你的适配器，不走convert方法，请问是有什么细节我没注意到吗？
public class NurseToDoAdapter extends BaseQuickAdapter<NurseTodo.ResultBean> {

    public NurseToDoAdapter(Context context, NurseTodo nurseTodo) {
        super(context, R.layout.door_search_left, nurseTodo.getResult());

    }

    @Override
    protected void convert(BaseViewHolder baseViewHolder, NurseTodo.ResultBean resultBean) {
        String time = resultBean.getStartTime() + "-" + resultBean.getEndTime();
        Log.v("09",time+"aaa");
        if (resultBean.isSelect) {
            baseViewHolder.setText(R.id.tv_search_item, time).setText(R.id.tv_search_item_name, resultBean.getServiceItem())
                    .setTextColorRes(R.id.tv_search_item, R.color.white).setTextColorRes(R.id.tv_search_item_name, R.color.white)
                    .setBackgroundRes(R.id.ll_search_item, R.color.colorSelect);
        }else{
            baseViewHolder.setText(R.id.tv_search_item, time).setText(R.id.tv_search_item_name, resultBean.getServiceItem())
                    .setTextColorRes(R.id.tv_search_item, R.color.colorNonSelect).setTextColorRes(R.id.tv_search_item_name, R.color.colorSelect)
                    .setBackgroundRes(R.id.ll_search_item, R.color.colorSearchBg);
        }
    }
}

**Comment by CymChad** [comment]
urseTodo.getResult() 的size是？

**Comment by nakisaren** [comment]
这是我在activity中的初始化和调用adapter代码，
mNurseTodo = response.body();
                mNurseToDoAdapter = new NurseToDoAdapter(mContext,mNurseTodo);
                mNurseToDoAdapter.setOnRecyclerViewItemClickListener(mOnRecyclerViewItemClickListener);
                mRvSearchLeft.setAdapter(mNurseToDoAdapter);
然后debug模式下，mNurseToDoAdapter的数据大小是跟服务器上是一样的，所以很困惑，不知道哪边出了问题

**Comment by CymChad** [comment]
你先写死数据试一下，要不你加Q群558178792，QQ沟通方便一些
