### ISSUE TITLE
addOnItemTouchListener 的点击一次，返回键退出执行点击事件执行多次问题

### ISSUE THREAD

**Issue by tigersunboy** [CymChad/BaseRecyclerViewAdapterHelper#1301]
这个bug不是bixian必现的。有时候点击一次点击事件，进去详情页面。但是退出的时候能退多次，每次退出的效果是退出详情页，有进入详情页面吗，再进去的的数据有时候也会变。打印log发现，每一次的点击的时候，点击事件执行了四次，但是退出一次点击的效果执行一次，退出一次执行一次，像是有个队列等待着，setOnItemClickListener这个点击事件没有问题
addOnItemTouchListener 这个点击事件是在一个纵向rv的adapter中的一个横向rv的条目点击事件

![1](https://user-images.githubusercontent.com/20189106/28046845-1b313886-6619-11e7-99f2-6d113373d547.png)
![log](https://user-images.githubusercontent.com/20189106/28047183-0604668e-661b-11e7-8456-0e71c21f5f48.png)

**Comment by CymChad** [comment]
addOnItemTouchListener 会重复添加。你应该执行了多次，建议用set，不会累计添加。
