### ISSUE TITLE
怎么画一个带头部的gridview

### ISSUE THREAD

**Issue by wudaotiantian** [CymChad/BaseRecyclerViewAdapterHelper#1302]

**Comment by CymChad** [comment]
1.设置布局管理器为grid
2.设置addHeaderView

**Comment by AaronYang23** [comment]
可是这个添加的view不能是属于gridview的item里吧 。，我想在item添加一个类似书架添加按钮那样的

**Comment by FrankKwok** [comment]
@AaronYang23 可以自己在convert里做特殊的处理

**Comment by AaronYang23** [comment]
搞定了  adapterGrid.setFooterViewAsFlow(true);这个方法可以设置是否跟随
