### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Cornflower1991** [CymChad/BaseRecyclerViewAdapterHelper#1304]
调用adapter.getItem(position) 的时候 position=-1；

**Comment by FrankKwok** [comment]
版本，调用代码

**Comment by Cornflower1991** [comment]
2.9.18  代码 adapter.getItem(position)  是在adapter 的 onItemChildClick回调中 。 不知道是不是删除item之后引起的

**Comment by FrankKwok** [comment]
@Cornflower1991 有错误信息吗

**Comment by CymChad** [comment]
更新至最新版试试

**Comment by Cornflower1991** [comment]
好的。我出现了个新的问题。onLoadMoreRequested调用之后 服务器返回的数据为0，但是当前条数小于 服务器返回的总count 所以我就 调用了loadMoreComplete 。然后 又再次回调了onLoadMoreRequested

**Comment by CymChad** [comment]
loadMoreComplete的意思就是加载完成，还有下一页的意思，如果没有数据了你可以直接调用加载结束的方法

**Comment by Cornflower1991** [comment]
对 是我们服务器返回的数据有问题。  我是想问下 如果我调用onLoadMoreRequested了之后数据返回为0然后我调用notifyDataSetChanged，再调用loadMoreComplete。然后又会调用这个onLoadMoreRequested。

**Comment by CymChad** [comment]
loadMoreComplete 你可以把他理解成一个通知，通知有下一页的意思，所以还会调用onLoadMoreRequested

**Comment by Cornflower1991** [comment]
如果我notifyDataSetChanged 之前加入了一条数据。 就不会一直调用。

**Comment by FrankKwok** [comment]
不需要调用notifyDataSetChanged

**Comment by Cornflower1991** [comment]
我知道了 loadMoreComplete  已经调用了
