### ISSUE TITLE
有没有提供方法可以修改已加载全部的foot提示信息呢

### ISSUE THREAD

**Issue by maxiaoping** [CymChad/BaseRecyclerViewAdapterHelper#1307]
有没有提供方法可以修改已加载全部的foot提示信息呢

**Comment by FrankKwok** [comment]
你的意思是自定义LoadView？继承LoadMoreView就可以了

**Comment by CymChad** [comment]
可以自定义加载全部的布局 具体看见文档：http://www.jianshu.com/p/b343fcff51b0
以及demo源码。
