### ISSUE TITLE
addHeader 调用notifyItemRangeChanged 崩溃

### ISSUE THREAD

**Issue by ng2Kaming** [CymChad/BaseRecyclerViewAdapterHelper#1311]
addHeader 添加头部后。做切换布局（LayoutManager.setSpanCount）后，调用notifyItemRangeChanged()。
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder
解决办法是关闭掉切换动画。有办法不关闭动画 解决这个问题吗？

**Comment by 1109993488** [comment]
如果有头部 从1开始  没有就可以从0， 调用notifyDataSetChanged效果一样
