### ISSUE TITLE
recyclerview嵌套recyclerview上滑导致图片错位问题

### ISSUE THREAD

**Issue by zwping** [CymChad/BaseRecyclerViewAdapterHelper#1312]
项目中有做一个类似朋友圈的功能，每个item中显示数量不等的图片，当我从上往下看的时候图片没有任何异常，**但当我从下晚上快速滑动的时候**，每个item中图片显示就产生了错位

**Comment by CymChad** [comment]
你用的是什么图片加载框架？

**Comment by zwping** [comment]
glide

**Comment by CymChad** [comment]
如果不用这个adapter就不会错位吗？

**Comment by FrankKwok** [comment]
外层Adapter每次onBind的时候是如何处理的？

**Comment by CymChad** [comment]
@zwping 问题解决了吗？

**Comment by zwping** [comment]
@CymChad cymChad，不好意思，这两天在忙其它事，我先关掉，等等有空再使用其它adapter看看会不会出现这个问题

**Comment by zwping** [comment]
@FrankKwok 我是自定义写了一个9图组件，内外层使用的Adapter都是AdapterHelper框架

**Comment by FrankKwok** [comment]
@zwping 能不能看下你的代码呢？

**Comment by zwping** [comment]
@FrankKwok 问题解决了，我在内层recyclerView中使用了getViewTreeObserver方法，快速滑动就导致错位了
源码地址：https://github.com/zwping/RecyclerBugTest/blob/master/app/src/main/java/win/zwping/recyclerpicbugtest/CommNinePic.java
