### ISSUE TITLE
在adapter类中刷新的问题

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#1313]
我想问下，在Adapter类中可以调用什么方法达到刷新列表的效果呢？

**Comment by CymChad** [comment]
notifyDataSetChanged

**Comment by BugMen** [comment]
我的意思是在convert（）这个方法中刷新




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月14日(星期五) 下午2:03
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




notifyDataSetChanged

**Comment by CymChad** [comment]
convert 你要刷新？
convert本身就是一个赋值的过程呀。

**Comment by BugMen** [comment]
是这样，我把Adapter作为了一个外部类，然后我现在在convert()方法中做了一些点击事件，需要刷新下列表，所以我就想问这个刷新的功能该调用那个方法呢？


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月14日(星期五) 下午2:13
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




convert 你要刷新？
 convert本身就是一个赋值的过程呀。

**Comment by CymChad** [comment]
点击事件可以设置这个adapter. notifyDataSetChanged  呀

**Comment by BugMen** [comment]
这个item的点击事件也能拿到自己的adapter么？


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月14日(星期五) 下午2:21
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




点击事件可以设置这个adapter. notifyDataSetChanged  呀

**Comment by CymChad** [comment]
恩 可以

**Comment by BugMen** [comment]
怎么拿呢？是用BaseViewHolder里的setAdapter么？可是这个方法里的adapter参数要怎么获取啊




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月14日(星期五) 下午2:52
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




恩 可以

**Comment by BugMen** [comment]
请问从convert()中做刷新的方法是什么啊




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月14日(星期五) 下午2:52
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




恩 可以

**Comment by CymChad** [comment]
convert本身就是adapter里面，你直接notifyDataSetChanged就可以了呀

**Comment by CymChad** [comment]
还有一种方式你可以在外面设置点击事件呀，都有提供方法。具体看文档：http://www.jianshu.com/p/b343fcff51b0

**Comment by BugMen** [comment]
我是点击了列表后会弹出一个popupwindow，然后点击popupwindow里的条目后刷新列表，这样的操作也是用这样的方法么？




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 中午11:32
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




还有一种方式你可以在外面设置点击事件呀，都有提供方法。具体看文档：http://www.jianshu.com/p/b343fcff51b0

**Comment by CymChad** [comment]
恩，都可以的。

**Comment by BugMen** [comment]
我调用了，可是列表并没有刷新啊




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 下午3:17
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




恩，都可以的。

**Comment by CymChad** [comment]
你改变了数据吗？

**Comment by BugMen** [comment]
我做了删除操作




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 晚上9:33
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




你改变了数据吗？

**Comment by CymChad** [comment]
你删除就直接调用 remove方法就可以了呀

**Comment by BugMen** [comment]
notifyDataSetChanged()方法确实没有刷新数据，麻烦能给我个例子让我看看嘛？




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 晚上9:33
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




你改变了数据吗？

**Comment by BugMen** [comment]
好了，解决了，我看了下BaseQuickAdapter类，发现还有个remove方法，正好满足需求！谢谢你一直帮我！抱拳了老铁！




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月17日(星期一) 晚上9:33
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在adapter类中刷新的问题 (#1313)




你改变了数据吗？
