### ISSUE TITLE
 hotFanscircleAdapter.loadMoreFail()后布局里面没有显示相应的文字信息

### ISSUE THREAD

**Issue by xicong** [CymChad/BaseRecyclerViewAdapterHelper#1314]
![image](https://user-images.githubusercontent.com/11675597/28204953-a0e34a46-68b2-11e7-8ff5-af4cae1607d2.png)
如果设置 hotFanscircleAdapter.loadMoreFail();以后怎么下面显示空白啊，不是应该显示加载失败，点击重试吗，是需要设置什么吗

**Comment by FrankKwok** [comment]
是最新版本吗，hotFanscircleAdapter这里是如何设置loadMoreView的？

**Comment by xicong** [comment]
:2.9.22'是的最新版本，加载更多view没有做设置啊，应该会调用你默认的view啊，默认的也需要设置吗

**Comment by FrankKwok** [comment]
有没有调用setEnableLoadMore这个方法？

**Comment by xicong** [comment]
没有啊

**Comment by xicong** [comment]
调用了，设置的true

**Comment by FrankKwok** [comment]
需要调用setEnableLoadMore(true)开启加载更多功能

**Comment by xicong** [comment]
hotFanscircleAdapter.setLoadMoreView(new SimpleLoadMoreView());
        hotFanscircleAdapter.setEnableLoadMore(true);
        hotFanscircleAdapter.setOnLoadMoreListener(this, recycleview_home_tab_fanscircle_hot);

**Comment by xicong** [comment]
初始化的时候就调用了，我是加载更多的时候没有网络就设置了loadMoreFail，结果里面显示空白，但是点击重新加载的效果都是有的

**Comment by FrankKwok** [comment]
拿最新版本试了，不能重现这个问题

**Comment by xicong** [comment]
好吧，我再看看
