### ISSUE TITLE
onLoadMoreRequested总是在加载第三页时不被调用。

### ISSUE THREAD

**Issue by hanfeng1982** [CymChad/BaseRecyclerViewAdapterHelper#1317]
@Override
    public void onLoadMoreRequested() {
        Log.e(tag,"调用了onLoadMoreRequested");
        srlTasklist.setEnabled(false);
        rvTasklist.postDelayed(new Runnable() {
            @Override
            public void run() {
                Log.e(tag,"加载更多:"+curPage);
                queryData(curPage,STATE_MORE);
            }
        },delayMillis);
    }
第二页的时候调用了。再继续上拉加载第三页的时候，总显示“正在加载中”，然后实际上onLoadMoreRequested并没有被调用。请问咋配置呀？

    private void queryData(int page, final int actionType) {
        // 如果是加载更多
        if (actionType == STATE_MORE) {
            // 处理时间查询
            // 跳过之前页数并去掉重复数据
            query.setSkip(curPage * PAGE_SIZE + 1);
        } else {
            // 下拉刷新
            curPage = 0;
            query.setSkip(curPage);
        }
        // 设置每页数据个数
        query.setLimit(PAGE_SIZE);
        // 查找数据
        query.findObjects(new FindListener<TaskContentEntity>() {

            @Override
            public void done(List<TaskContentEntity> list, BmobException e) {
               srlTasklist.setEnabled(true);
                if(e == null){
                    if (list.size() > 0) {
                        // 将当前页码+1
                        curPage++;
                        if (actionType == STATE_REFRESH) {
                            taskListAdapter.setNewData(list);
                        }else {
                            taskListAdapter.addData(list);
                        }
                        taskListAdapter.setEnableLoadMore(true);
                       //taskListAdapter.loadMoreEnd(false);
                    } else if (actionType == STATE_MORE) {
                        //taskListAdapter.loadMoreEnd(true);
                        //taskListAdapter.loadMoreComplete();
                        
                    } else if (actionType == STATE_REFRESH) {
                       // taskListAdapter.loadMoreEnd(true);
                       // taskListAdapter.loadMoreComplete();
                        
                    }
                }else {
                    taskListAdapter.loadMoreFail();

                }

            }
        });

**Comment by FrankKwok** [comment]
你什么情况下都执行`curPage++;`让页数加一，处理的不对吧

**Comment by hanfeng1982** [comment]
嗯嗯，确实哈，还没有完善代码。我现在数据库里面有几十条数据，至少都要六七页后，才会结束刷新的，但是现在第三页开始就不调用取数据的方法了，感觉好奇怪呀

**Comment by FrankKwok** [comment]
正常来讲应该是不会有问题的，可以先debug看一下，如果还有问题，可以找以前的issues看看

**Comment by hanfeng1982** [comment]
好的，谢谢。我晚上回家再去看看以前的提问，再研究下

**Comment by hanfeng1982** [comment]
问题解决啦。哈哈
 if (actionType == STATE_REFRESH) {
                            taskListAdapter.setNewData(list);
                            srlTasklist.setRefreshing(false);
                            taskListAdapter.setEnableLoadMore(true);
                        }else {
                            taskListAdapter.addData(list);
                            taskListAdapter.loadMoreComplete();
                        }
我没有理解好，taskListAdapter.loadMoreComplete();和taskListAdapter.loadMoreEnd(true);的意思，呵呵，今天上班突然看了下文档，沉思了下就通了。谢谢了。

**Comment by lyq027** [comment]
@hanfeng1982 遇到与你一样问题，你是哪变更了呢？

**Comment by hanfeng1982** [comment]
taskListAdapter.loadMoreComplete();和taskListAdapter.loadMoreEnd(true);设置不正确导致的。看官方文档：taskListAdapter.loadMoreComplete();表示当次加载完毕。后面可能有数据taskListAdapter.loadMoreEnd(true);和taskListAdapter.loadMoreEnd(FALSE);表示后面没有数据了，最后一页。
