### ISSUE TITLE
对 RecyclerView 进行截图问题

### ISSUE THREAD

**Issue by chiemy** [CymChad/BaseRecyclerViewAdapterHelper#1318]
使用[此方式](https://stackoverflow.com/a/31017673/2744948)对 RecyclerView 进行截图，在 BaseQuickAdapter 的 onBindViewHolder 方法中，这行代码

`this.convert(holder, this.mData.get(holder.getLayoutPosition() - this.getHeaderLayoutCount()));`

会产生 `IndexOutOfBoundsException`。未添加头部，经调试 `holder.getLayoutPosition()` 为 -1，所以
`holder.getLayoutPosition() - this.getHeaderLayoutCount()` 结果为 -1。

这里为何使用` holder.getLayoutPosition()` 而不用 `positions` 参数？

或者你有更好的截图方案吗？

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.25'
