### ISSUE TITLE
setEmpty，加载完毕在GridLayoutManager情况下显示异常

### ISSUE THREAD

**Issue by xiangjava** [CymChad/BaseRecyclerViewAdapterHelper#132]
![default](https://cloud.githubusercontent.com/assets/6281188/16576770/d9c2ab24-42c3-11e6-8105-4cd610bd6114.jpg)
![grid](https://cloud.githubusercontent.com/assets/6281188/16576838/39052f80-42c4-11e6-8c2b-5ff72f5bffeb.png)

**Comment by CymChad** [comment]
请使用最新版本

**Comment by xiangjava** [comment]
更新到185，还是出现setEmprtView只显示一半的情况

**Comment by CymChad** [comment]
你的EmprtView的加载方式是？

**Comment by xiangjava** [comment]
mRecyclerView.setLayoutManager(gridManager);
mRecyclerView.setLayoutManager(listManager);
用到了网格列表切换，切换到网格视图就出现emptyView只显示一半，setEmptyView是在初始化Adapter的时候设置的

**Comment by xiangjava** [comment]
我看见V185更新下来的代码是这样：
@Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
        RecyclerView.LayoutManager manager = recyclerView.getLayoutManager();
        if (manager instanceof GridLayoutManager) {
            final GridLayoutManager gridManager = ((GridLayoutManager) manager);
            gridManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    int type = getItemViewType(position);
                    return (type == EMPTY_VIEW || type == HEADER_VIEW || type == FOOTER_VIEW || type == LOADING_VIEW) ? gridManager.getSpanCount() : 1;
                }
            });
        }
}

但是github代码显示
@Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
        RecyclerView.LayoutManager manager = recyclerView.getLayoutManager();
        if (manager instanceof GridLayoutManager) {
            final GridLayoutManager gridManager = ((GridLayoutManager) manager);
            gridManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    int type = getItemViewType(position);
                    return (type == EMPTY_VIEW || type == HEADER_VIEW || type == FOOTER_VIEW || type == LOADING_VIEW) ? gridManager.getSpanCount() : 1;
                }
            });
        }
}
是不是没更新到maven上面的原因

**Comment by xiangjava** [comment]
public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
        LayoutManager manager = recyclerView.getLayoutManager();
        if(manager instanceof GridLayoutManager) {
            final GridLayoutManager gridManager = (GridLayoutManager)manager;
            gridManager.setSpanSizeLookup(new SpanSizeLookup() {
                public int getSpanSize(int position) {
                    int type = BaseQuickAdapter.this.getItemViewType(position);
                    return type != 1365 && type != 273 && type != 819 && type != 546?1:gridManager.getSpanCount();
                }
            });
        }

    }

**Comment by CymChad** [comment]
我代码做过处理呀，你要不用用  1.8.8试试？

**Comment by CymChad** [comment]
还不行，你可以用StaggeredGridLayoutManager  也可以实现一样的效果

**Comment by xiangjava** [comment]
我刚测试了一下1.8.8也不行，跟了一下代码，发现重新设置setLayoutManager不会执行onAttachedToRecyclerView，导致无法执行GridLayoutManager的判断。最后跟踪代码发现在切换布局之后recyclerView执行swapAdapter(Adapter adapter, boolean removeAndRecycleExistingViews)方法就可以了，问题解决，谢谢。

**Comment by CymChad** [comment]
切换布局之后？

**Comment by LvWind** [comment]
@CymChad 
2.1.7 版本也出现相同情况，用的 GridLayoutManager
初始化 adapter 的时候 setEmprtView，最后居左显示一半。

 P.S.试过 StaggeredGridLayoutManager 了，空白页正常了但有数据的时候并不是我想要的 gridview 的效果。

**Comment by CymChad** [comment]
你从新开一个 issues把你想要的效果，和目前的效果，都贴出来，我这边好更加详细的去修改这个问题。

**Comment by Reanni** [comment]
同遇到这个问题标记一下。结论：要先setLayoutManager再setAdapter就能正常显示。如果反过来，onAttachedToRecyclerView()方法中manager的值就会为null导致下面的代码不会执行
