### ISSUE TITLE
没有走convert这个方法

### ISSUE THREAD

**Issue by 16fangougou** [CymChad/BaseRecyclerViewAdapterHelper#1322]
版本2.9.24.

设置adapter manager:
![image](https://user-images.githubusercontent.com/17920617/28357719-f461854e-6c9e-11e7-92d0-c4f55039e485.png)

adapter基本代码:
![image](https://user-images.githubusercontent.com/17920617/28357760-132cc9fc-6c9f-11e7-9361-f0fb5cdfed3e.png)

实体类和模拟数据:
![image](https://user-images.githubusercontent.com/17920617/28357855-4bb044c0-6c9f-11e7-90ff-115628350197.png)

我打印跟踪, 没有走conver这个方法. 
请教一下这是什么原因?

**Comment by FrankKwok** [comment]
有没有什么报错信息的？

**Comment by 16fangougou** [comment]
@FrankKwok 没有任何报错

**Comment by FrankKwok** [comment]
内容挺多的，能不能传个demo到GitHub？

**Comment by 16fangougou** [comment]
@FrankKwok 找到原因了, 我在rv外面,嵌套了一个swiperefreshlayout, 这种不能兼容么?

**Comment by FrankKwok** [comment]
@16fangougou 可以兼容的啊，demo里面用的有SwipeRefreshLayout啊

**Comment by 16fangougou** [comment]
@FrankKwok 我是自定义扩展了原生的, 重写了一下onMeasure就好了.谢谢, 可以关闭了.
