### ISSUE TITLE
BaseViewHolder 的setVisible能加入INVISIBLE么?

### ISSUE THREAD

**Issue by a48352433** [CymChad/BaseRecyclerViewAdapterHelper#1326]
`  public BaseViewHolder setVisible(int viewId, boolean visible) {

        View view = getView(viewId);

        view.setVisibility(visible ? View.VISIBLE : View.GONE);

        return this;

    }`
这个方法里能加入INVISIBLE么?

**Comment by a48352433** [comment]
算了.我还是自己集成BaseViewHolder 自己写吧!

**Comment by CymChad** [comment]
恩，感谢。
