### ISSUE TITLE
哈喽 在不 我在item里面加了自定义控件, 在convert(BaseViewHolder helper, MainRecyclerSectionModel item)函数实现里面, 自定义控件里面的view怎么都是null, 我怎么做才能获取自定义控件的子view

### ISSUE THREAD

**Issue by YanJerry97** [CymChad/BaseRecyclerViewAdapterHelper#1329]
哈喽 在不 我在item里面加了自定义控件, 在convert(BaseViewHolder helper, MainRecyclerSectionModel item)函数实现里面, 自定义控件里面的view怎么都是null, 我怎么做才能获取自定义控件的子view

**Comment by FrankKwok** [comment]
使用helper.getView(int id)获取自定义View

**Comment by YanJerry97** [comment]
恩 这个知道 但是自定义控件里面的ziview是null 很奇怪


                ItemImageView itemImageView = (ItemImageView)helper.getView(R.id.itemImageView);
                itemImageView.setTitleText(itemModel.title);

itemImageView.setTitleText函数里面的titleTv是null


    public ItemImageView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        LayoutInflater.from(context).inflate(R.layout.item_image_view, this);
        mContext = context;
        //初始化view
        titleTv = (TextView)findViewById(R.id.title_tv);
        sourceTv = (TextView)findViewById(R.id.source_tv);
        nineGridView = (NineGridView) findViewById(R.id.nine_grid_view);
    }

    public void setTitleText(String title) {
        if (!TextUtils.isEmpty(title)) {
            titleTv.setText(title);
        }
    }

**Comment by FrankKwok** [comment]
你每个构造方法都正确的初始化了吗？

**Comment by YanJerry97** [comment]
嘿嘿  谢谢 找到原因了 很强大的库

**Comment by CymChad** [comment]
感谢使用
