### ISSUE TITLE
改改亲

### ISSUE THREAD

**Issue by longlylong** [CymChad/BaseRecyclerViewAdapterHelper#133]
this.mData = data == null ? new ArrayList<T>() : data;
这样写会出bug的,引用会被改变的...每次我拉代码都要改成 this.mData = data;
还有每个子类的adapter都加个
public List<T> getData(){
    return mData;
}

**Comment by CymChad** [comment]
有提供getData方法。base类就有。

**Comment by CymChad** [comment]
或者你可以先new ArrayList

**Comment by longlylong** [comment]
你在base类里面返回的是List  不是List<T> 极度不方便 
即使你在base类里面改成了返回List<T>  子类还是要重写的..不然返回的还是List

还有一个不明白你为什么这么写的.被人喜欢传什么都是他们的事情,你为什么要加个三元进去呢?

**Comment by CymChad** [comment]
null的话，有问题呀

**Comment by longlylong** [comment]
null 你抛异常就好了...

**Comment by CymChad** [comment]
不太友好吧。。
