### ISSUE TITLE
item  位置 混乱

### ISSUE THREAD

**Issue by lhb11** [CymChad/BaseRecyclerViewAdapterHelper#1330]
加载的item 的位置是乱的 如何处理

**Comment by FrankKwok** [comment]
混乱一般都是开发者不理解复用机制引起的

**Comment by CymChad** [comment]
请阅读文档，有复用机制的解决方案  http://www.jianshu.com/p/b343fcff51b0

**Comment by lhb11** [comment]
![wechatimg3282](https://user-images.githubusercontent.com/15186545/28553077-4ea7937a-7124-11e7-98c2-9128ae2752cd.jpeg)
就是后面的switch，开关因为复用会混乱，第一个的开启 ，有的时候滚动就回跑到的别的item上开启

**Comment by CymChad** [comment]
文档里面有说明，有demo，本质问题都是一样的，要通过绑定属性到实体类上

**Comment by lhb11** [comment]
刚看到，复用是没有办法关闭的吗，我现在 也是 绑定到 module上的

**Comment by lhb11** [comment]
但是 绑定到module上还是有问题，滚动的时候就会 ，出现错乱

**Comment by FrankKwok** [comment]
你是如何处理的？

**Comment by lhb11** [comment]
在 实力类中设置 一个 ischecked 属性，分别给每个item的实例赋值

**Comment by FrankKwok** [comment]
@lhb11 你这个做法没问题的，我觉得最好贴下代码，这样才能知道问题在哪
