### ISSUE TITLE
BaseMultiItemQuickAdapter 如何删除父级（连同子级一起删除，并刷新界面）？

### ISSUE THREAD

**Issue by 287138531** [CymChad/BaseRecyclerViewAdapterHelper#1331]
private List<MultiItemEntity> data = new ArrayList<>();
折叠菜单实现的方法：感觉 postion很混乱。我不知道该操作哪个数据. 

实现类似于qq的分组。
我结合和一个SwipeDelMenuLayout侧滑组件，通过接口方法，在init  的时候设置删除方法，
删除成功再做下面操作：
1.删除父级并连同子级一起删除,刷新界面（折叠状态不会改变，就是原来是展开的不要变收缩）
2.删除子级的内容并刷新界面（折叠状态不会改变，就是原来是展开的不要变收缩）
3.菜单点开的时候刷新局部数据，然后局部更新。

刷新的时候，我clear  data，再添加一遍，这个时候调用Adater.notifyDataSetChanged();
子数据会错乱。（实际上数据没变化时候不会乱，数据少了就会）

**Comment by CymChad** [comment]
你删除的代码是？

**Comment by 287138531** [comment]
private List data = new ArrayList<>();
我clear data，再添加一遍，这个时候调用Adater.notifyDataSetChanged();

**Comment by 287138531** [comment]
其实我是需要在Adater外面做删除，而不是demo的convert里面，实际上 用，也是先请求接口删除，成功再删除list

**Comment by 287138531** [comment]
对了，实际上我是在子级的界面上有删除父级的入口。。这种情况下怎么删除？

**Comment by FrankKwok** [comment]
你可以持有父级对象引用

**Comment by FrankKwok** [comment]
这里要分两种情况，如果子级没有展开，直接在数据源里移除父级数据；若子级展开了，则需要先移除对应的所有子级数据，然后再移除父级数据

**Comment by CymChad** [comment]
@FrankKwok 正解
