### ISSUE TITLE
上拉加载更多,有时候没有回调有时候有

### ISSUE THREAD

**Issue by jyjiawohao** [CymChad/BaseRecyclerViewAdapterHelper#1332]
mAdapter.setPreLoadNumber(1);
mAdapter.disableLoadMoreIfNotFullPage();

因为初始化的时候调用了这俩就  所以在上拉加载的时候 有事可以上拉加载更多数据 有时候无法上拉加载
 
现在注释掉上面的两句,问题占时没有出现, 想请问下,是否是版本更新了,不需要设置了

**Comment by 1109993488** [comment]
disableLoadMoreIfNotFullPage不能再初始化的时候调用，这个是在setNewData后调的
