### ISSUE TITLE
Support for BaseViewHolder.setLayoutManager

### ISSUE THREAD

**Issue by bliveinhack** [CymChad/BaseRecyclerViewAdapterHelper#1334]
Great work folks.

it would be nice to have viewHolder method like `setLayoutManager` to set Layout Manager to inner `RecycleView`.

**Comment by CymChad** [comment]
There are two ways to：
 
1. Through `viewHolder.getView(R.id.iv)` access `RecycleView` set Layout Manager

2.Custom BaseViewHolder

**Comment by bliveinhack** [comment]
Yeah,

i'm already using `viewHolder.getView(R.id.iv)`. Though i think it may initialise layout manager every time.
