### ISSUE TITLE
RecyclerView嵌套RecyclerView显示不全，用这个框架怎么解决呢

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#1335]
RecyclerView嵌套RecyclerView显示不全，用这个框架怎么解决呢

**Comment by AllenCoder** [comment]
注意设置嵌套item的布局的高度和宽度，建议可以先设置minHeight 试试，能否正常展开嵌套的布局。demo的ItemCliclkActivity使用的就是嵌套布局，建议参考一下
