### ISSUE TITLE
加载完所有数据后，再刷新，加载更多就没用了

### ISSUE THREAD

**Issue by Hhcoco** [CymChad/BaseRecyclerViewAdapterHelper#1338]
数据页有3页，全部加载完以后，再下拉刷新，此时就只有第一页的数据了，这个时候再上拉，加载更多的view显示出来了，但是加载更多的方法没用调用。

**Comment by CymChad** [comment]
下拉刷新，调用setNewData方法来。则会重新开启上拉监听。

**Comment by Hhcoco** [comment]
这样直接crash了：java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{137c63 position=16 id=-1, oldPos=6, pLpos:6 scrap [attachedScrap] tmpDetached no parent}

**Comment by CymChad** [comment]
版本，使用代码

**Comment by Hhcoco** [comment]
2.9.12
//第一次的时候没有问题，但是下拉刷新后再调这句就crash了。
adapter.setNewData(list);
//如果我这样写,不会crash了，加载更多这个view一直出现，但是并没有调用方法。
list.clear;
//在有一个地方，我clear后马上notifyDataSetChanged一次，加载更多可以用了，但是在另外一个地方又
 // 不行。
list.addAll(data.getResults());
adapter.notifyDataSetChanged();

**Comment by Hhcoco** [comment]
我加载完所有分页数据后，再刷新重新设置新数据，感觉好像adapter的一些设置没用了？

**Comment by FrankKwok** [comment]
@Hhcoco 调用BaseQuickAdapter中的添加或删除数据的方法之后不需要再notifyDataSetChanged()

**Comment by CymChad** [comment]
下拉刷新你只需要调用adapter.setNewData(list);即可。你可以看下demo的案例。
