### ISSUE TITLE
发现新BaseMultiItemQuickAdapter 新bug一枚，折叠菜单必须全部展开才会显示

### ISSUE THREAD

**Issue by 287138531** [CymChad/BaseRecyclerViewAdapterHelper#1339]
只要不Adater.expandAll();
都是不显示，我的需求是默认收起的。
我试过先全部展开，再收起collapse所有的，只要一collapse，就不显示

**Comment by FrankKwok** [comment]
collapse之后当然就不显示了

**Comment by 287138531** [comment]
？我需要默认 是收起状态怎么做？

**Comment by FrankKwok** [comment]
默认就是收起的啊

**Comment by 287138531** [comment]
只要不做展开操作，就不显示

**Comment by FrankKwok** [comment]
你的这个收起和我理解的收起是一个意思吗？

**Comment by 287138531** [comment]
加个QQ聊可以？  折叠菜单  --不就是展开和收起吗？  只要不调用展开的方法，整个列表都不显示。
调用collapse 收起二级菜单就，整个列表都不显示

**Comment by FrankKwok** [comment]
我加你好了，你的QQ多少？

**Comment by 287138531** [comment]
287138531

**Comment by CymChad** [comment]
@287138531 问题解决的如何了？

**Comment by 287138531** [comment]
搞定了，我用了三级，应该展开二级内容，我搞错了，吧所有的折叠起来了

**Comment by CymChad** [comment]
经过与@FrankKwok 沟通反馈问题已解决，原因是使用者理解有误。
