### ISSUE TITLE
IndexOutOfBoundsException:cause by Calling adapter.notifyDataItemRemoved or notifyDataItemInserted

### ISSUE THREAD

**Issue by akindone** [CymChad/BaseRecyclerViewAdapterHelper#1340]
IndexOutOfBoundsException——cause by Calling adapter.notifyDataItemRemoved or notifyDataItemInserted after setEmptyView

因为调用notifyDataItemRemoved或notifyDataItemInserted导致刷新视图时，报异常。

目前我的解决办法：
在BaseQuickAdapter的子类里添加3个方法,在需要用到notifyDataItemRemoved的地方替换为notifyDataItemInserted
```
/**
     * notify adapter a new data has been inserted in to certain location
     */
    public void notifyDataItemInserted(@IntRange(from = 0) int position) {
        notifyItemInserted(position + getHeaderLayoutCount());
        compatibilityDataSizeChanged(1);
    }

    /**
     * notify adapter that a item has removed from the specified position of adapter
     */
    public void notifyDataItemRemoved(@IntRange(from = 0) int position) {
        int internalPosition = position + getHeaderLayoutCount();
        notifyItemRemoved(internalPosition);
        compatibilityDataSizeChanged(0);
        notifyItemRangeChanged(internalPosition, mData.size() - internalPosition);
    }

    /**
     * copy from BaseQuickAdapter because of the private modifier
     */
    private void compatibilityDataSizeChanged(int size) {
        final int dataSize = mData == null ? 0 : mData.size();
        if (dataSize == size) {
            notifyDataSetChanged();
        }
    }
```
理由
虽然BaseQuickAdapter已经提供了`addData(@IntRange(from = 0) int position, @NonNull T data)`,`remove(@IntRange(from = 0) int position)`, 但是方法却会修改mData。举个例子，我不想通过adapter去修改数据，而由专门的数据管理类去增删，仅需要通知视图去更新某个position的item的增删。

希望能够考虑这种需求，避免these ugly code in subClass

**Comment by FrankKwok** [comment]
这个专门的数据管理类是什么意思呢？

**Comment by akindone** [comment]
项目里在用mvp去解耦视图与业务逻辑，现在数据都放在presenter里管理，视图依赖presenter里的数据。

**Comment by FrankKwok** [comment]
你的意思是在Presenter层修改数据，然后再View层notifyData？

**Comment by akindone** [comment]
是的-_-

**Comment by CymChad** [comment]
满足你的例子
例子：“举个例子，我不想通过adapter去修改数据，而由专门的数据管理类去增删，仅需要通知视图去更新某个position的item的增删。”

有两种方案：
1、通过adapter.getData来修改数据，通过adapter原始的方法来通知更新。
2、在初始化adapter的时候new一个list给到adapter然后直接操作list，通过adapter原始的方法来通知更新。

**Comment by akindone** [comment]
感谢你的回复！但是，
你上面说的`adapter原始的方法`，指的是`notifyDataItemInserted`吗？我就是按照方案2做的，在设置了emptyView的情况下，调用notifyDataItemInserted方法的时候会报数组越界异常。

**Comment by FrankKwok** [comment]
setEmptyView是配置项，@see #1289 , #1280 , #1105
