### ISSUE TITLE
多层recyclerview复用问题

### ISSUE THREAD

**Issue by dsh923713** [CymChad/BaseRecyclerViewAdapterHelper#1344]
recyclerview子item中有上下两个recyclerview  点击上面的recyclerview将数据传到下面的recyclerview，同时上面的当条数据清除 ，滑动后 再返回去 会出现复用，数据又回到最开始的样子

**Comment by CymChad** [comment]
数据缓存的问题wiki有解释：http://www.jianshu.com/p/b343fcff51b0
