### ISSUE TITLE
当item高度超过一屏时,onpause->onresume后recyclerview内容会往上偏移一段距离

### ISSUE THREAD

**Issue by LambdaV5** [CymChad/BaseRecyclerViewAdapterHelper#1345]
![default](https://user-images.githubusercontent.com/17512402/28601857-46a34c54-71ed-11e7-920b-3c5400887db7.png)
![default](https://user-images.githubusercontent.com/17512402/28601880-63336200-71ed-11e7-8c44-a291a70f3ffa.png)

**Comment by CymChad** [comment]
你检查下你的item高度是不是没写死

**Comment by LambdaV5** [comment]
是的,高度自适应的

**Comment by CymChad** [comment]
你写死就好了，有人遇到同样的问题，通过写成固定高度就好了

**Comment by LambdaV5** [comment]
我们每个item的内容是不固定的

**Comment by CymChad** [comment]
那是有规则的吗？

**Comment by LambdaV5** [comment]
没有规则

**Comment by CymChad** [comment]
那你item里面的元素的高度是固定的吗？

**Comment by LambdaV5** [comment]
你是说自己算高度吗?

**Comment by LambdaV5** [comment]
item里面嵌套了recyclerview

**Comment by CymChad** [comment]
里面是rv应该没问题呀，demo里面就有嵌套rv的栗子

**Comment by CymChad** [comment]
你嵌套的rv里面的item的高度是否能够固定？

**Comment by LambdaV5** [comment]
高度没有超过最外层recyclerview高度的时候,一切正常,超过了就会出现这种情况,嵌套的item高度是固定的,不过有两种类型

**Comment by CymChad** [comment]
问题的出现的原因就是由于布局内容不固定导致的（之前有人遇到过同样的问题）。你可以看下demo中的案例看看，你有什么地方没设置好，我在demo中无法复现你的问题，我目前也只能猜测你有可能会发生问题的地方。

**Comment by CymChad** [comment]
adapter是不会自动修改item的高度的。

**Comment by LambdaV5** [comment]
好的,谢谢

**Comment by CymChad** [comment]
如果解决了，麻烦回复下，让后续遇到同样问题的老铁们，可以找到解决问题的方案，谢谢。

**Comment by LambdaV5** [comment]
好的,才开始看demo

**Comment by LambdaV5** [comment]
根据观察,rv所在界面第一次显示时,不论第一个item是否超过rv高度,显示均正常.
在打开其他界面或者按home键之后,再重新打开,此时rv的内容会往上滚动一段距离,下拉刷新结束后有此现象
因此我的解决思路是,在界面不可见时保存不可见的标识,并给rv设置滚动监听,在滚动的时候根据下拉状态或者不可见状态来滚动rv里面的内容,并重置不可见状态
代码如下
### 滚动监听
` rv.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                if (mRefreshView.isRefreshing() || isPaused() &&
                        ((LinearLayoutManager) recyclerView.getLayoutManager())
                                .findFirstVisibleItemPosition() == 0) {
                    recyclerView.scrollToPosition(0);
                    setPaused(false);
                    return;
                }
                super.onScrolled(recyclerView, dx, dy);
            }
        });

  private boolean isPaused() {
        return mIsInvisible || mIsPaused;
    }
`
### 不可见状态保存
` @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        if (!isVisibleToUser) {
            mIsInvisible = true;
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        mIsPaused = true;
    }`
### 不可见状态恢复
`   private void setPaused(boolean paused) {
        mIsInvisible = paused;
        mIsPaused = paused;
    }`

**Comment by CymChad** [comment]
👍 @LambdaV5

**Comment by lindan83** [comment]
> 根据观察,rv所在界面第一次显示时,不论第一个item是否超过rv高度,显示均正常.
> 在打开其他界面或者按home键之后,再重新打开,此时rv的内容会往上滚动一段距离,下拉刷新结束后有此现象
> 因此我的解决思路是,在界面不可见时保存不可见的标识,并给rv设置滚动监听,在滚动的时候根据下拉状态或者不可见状态来滚动rv里面的内容,并重置不可见状态
> 代码如下
> 
> ### 滚动监听
> `rv.addOnScrollListener(new RecyclerView.OnScrollListener() { @Override public void onScrolled(RecyclerView recyclerView, int dx, int dy) { if (mRefreshView.isRefreshing() || isPaused() && ((LinearLayoutManager) recyclerView.getLayoutManager()) .findFirstVisibleItemPosition() == 0) { recyclerView.scrollToPosition(0); setPaused(false); return; } super.onScrolled(recyclerView, dx, dy); } });`
> `private boolean isPaused() { return mIsInvisible || mIsPaused; }`
> 
> ### 不可见状态保存
> `
> @override
> public void setUserVisibleHint(boolean isVisibleToUser) {
> super.setUserVisibleHint(isVisibleToUser);
> if (!isVisibleToUser) {
> mIsInvisible = true;
> }
> }
> 
> ```
> @Override
> public void onPause() {
>     super.onPause();
>     mIsPaused = true;
> }`
> ```
> ### 不可见状态恢复
> `private void setPaused(boolean paused) { mIsInvisible = paused; mIsPaused = paused; }`

有效的办法，谢谢！
