### ISSUE TITLE
网络断开，加载更多失败，继续点击加载更多，加载中会与加载更多重叠

### ISSUE THREAD

**Issue by cwyrzz** [CymChad/BaseRecyclerViewAdapterHelper#1348]
网络断开，加载更多失败，继续点击加载更多，加载中会与加载更多重叠。
请问是否可以点击加载更多，显示加载中，隐藏加载更多

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/906

**Comment by CymChad** [comment]
你的问题可以在历史问题中查找到。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/838

**Comment by cwyrzz** [comment]
只能取消动画吗？没有其他解决方案？

**Comment by CymChad** [comment]
目前只能取消动画。因为重叠就是动画引起的。
