### ISSUE TITLE
 引入

### ISSUE THREAD

**Issue by yunquefly** [CymChad/BaseRecyclerViewAdapterHelper#135]
为啥我按照给出的方式引进项目会报错

**Comment by liu-hailin** [comment]
能给出具体错误吗？是recyclerview冲突了吗？

**Comment by yunquefly** [comment]
下面是报的错自动引入在项目中添加，
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.5'
maven { url "https://jitpack.io" }
源码demo中为啥还要关联一个material-spinner-1.0.5.aar

Error:(25, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.5
<a href="disable.gradle.offline.mode">Disable offline mode and Sync</a><br><a href="openFile:/Users/ex-guoshaotang001/AndroidStudioProjects/Demo/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by yunquefly** [comment]
只要我在项目的依赖里面添加
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.5'
就会报错，新建项目也是一样的效果

**Comment by CymChad** [comment]
@yunquefly 

Add it in your root build.gradle at the end of repositories:

allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
