### ISSUE TITLE
如何添加一个带有计时器效果的头部

### ISSUE THREAD

**Issue by RaylanXL** [CymChad/BaseRecyclerViewAdapterHelper#1354]
`mQuickAdapter.addHeaderView(getView());`
现在是添加一个头部后，其中包含有计时器，不过计时器并不会自己刷新时间，该怎么办

**Comment by tysheng** [comment]
数据是数据，视图是视图，视图只是用来显示控制器想让他显示的。

所以你只需要修改，相应位置的数据源就可以了。

类比多个有计时器的条目，需要多个计时器吗？一个就够了，利用一个计时器，对相应位置的数据进行变化，然后局部刷新。

**Comment by CymChad** [comment]
正解 通过数据改变view的变化。
