### ISSUE TITLE
上拉加载显示问题

### ISSUE THREAD

**Issue by LambdaV5** [CymChad/BaseRecyclerViewAdapterHelper#1355]
在上拉加载的过程中,如果继续往上拖动recyclerView(连续快速往上拉可重现),上拉加载完成后布局显示错乱
底部显示情况
![default](https://user-images.githubusercontent.com/17512402/28658551-7ad5ad22-72de-11e7-8cf0-28070ffac76d.png)
recyclerview底部被这个view遮盖,顶部也会被遮盖
顶部显示情况
![default](https://user-images.githubusercontent.com/17512402/28658680-128ffa64-72df-11e7-89f4-5308a1a803d4.png)

小车为下拉刷新布局

**Comment by CymChad** [comment]
收到

**Comment by 1109993488** [comment]
没看懂，能否截个gif？

**Comment by LambdaV5** [comment]
取货码:20这个item是最后一个item,正常显示应该是显示到下边蓝色这个地方,第二个图为第一个item,已经拉到顶了,但是它有一部分在rv界面外显示了

**Comment by 1109993488** [comment]
是否是RecyclerView外面的下拉刷新控件影响的？

**Comment by LambdaV5** [comment]
上拉加载用的是adapter的,我觉得可能是在快速上拉的过程中把前一次加载的view引用改变了,然后导致加载成功后之前的view没有被移除

**Comment by 1109993488** [comment]
能把上拉加载更新代码贴下吗

**Comment by LambdaV5** [comment]
`if (orders.size() > 0) {
                        mOrderAdapter.loadMoreComplete();
                        mOrderAdapter.addData(orders);
                    } else {
                        --mPageNum;
                        mOrderAdapter.loadMoreEnd();
                    }`

**Comment by 1109993488** [comment]
看代码没问题，是否是你用的ItemDecoration造成的？

**Comment by LambdaV5** [comment]
没有ItemDecoration

**Comment by LambdaV5** [comment]
确实是下拉框架的问题
