### ISSUE TITLE
大佬，有个问题我想问下。能不能实现gridview后面加一个添加的按钮？

### ISSUE THREAD

**Issue by AaronYang23** [CymChad/BaseRecyclerViewAdapterHelper#1356]

**Comment by CymChad** [comment]
可以实现，具体看文档http://www.jianshu.com/p/b343fcff51b0  有一个setFooterViewAsFlow方法可以设置成你想要的效果

**Comment by AaronYang23** [comment]
谢谢大佬

**Comment by AaronYang23** [comment]
谢谢


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年7月27日(星期四) 晚上6:07
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "杨先僧🏠"<1071757337@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 大佬，有个问题我想问下。能不能实现gridview后面加一个添加的按钮？ (#1356)




Closed #1356.
