### ISSUE TITLE
多类型使用BaseMultiItemQuickAdapter的时候，会自动向上或向下跳一段距离，顶部添加高高的bannderHeader,addHeaderView的时候不会，怎么解决跳的问题？？？急急急！！！ 

### ISSUE THREAD

**Issue by iosline** [CymChad/BaseRecyclerViewAdapterHelper#1357]

**Comment by iosline** [comment]
只有有个人，遇到了差不多类似的问题，但是没有解决

**Comment by iosline** [comment]
之前

**Comment by FrankKwok** [comment]
你说的是和 #1345 一样？

**Comment by iosline** [comment]
但是他这种方法并没有解决问题，还是会跳

**Comment by FrankKwok** [comment]
那你把问题和代码描述详细一点，只有相关信息多了，才有可能解决问题

**Comment by iosline** [comment]
[http://7xl32g.com1.z0.glb.clouddn.com/%E6%95%88%E6%9E%9C.gif](url) 效果是这样的，第一次进来的时候，调用了mRecyclerView.smoothScrollToPosition(0);才没有向上跳，切换回来的时候，跳了

**Comment by iosline** [comment]
`public class FoundListRecyclerAdapter extends BaseMultiItemQuickAdapter<FoundItemModel,BaseViewHolder> {


    private ItemClickListener itemClickListener;

    public FoundListRecyclerAdapter() {
        super(null);

        addItemType(FoundItemModel.ONE_IMAGE, R.layout.layout_item_found_one_image);
        addItemType(FoundItemModel.NINE_IMAGE, R.layout.layout_item_found_nine_image);

    }

    @Override
    protected void convert(final BaseViewHolder helper, final FoundItemModel item) {

        switch (helper.getItemViewType()) {
            case FoundItemModel.ONE_IMAGE:

                if (item.isVertical()){
                    helper.getView(R.id.image_horizontal).setVisibility(View.GONE);
                    helper.getView(R.id.image_vertical).setVisibility(View.VISIBLE);
                }else {
                    helper.getView(R.id.image_horizontal).setVisibility(View.VISIBLE);
                    helper.getView(R.id.image_vertical).setVisibility(View.GONE);
                }
                break;
            case FoundItemModel.NINE_IMAGE:
                RecyclerView imageRecycler = helper.getView(R.id.image_recycler);
                imageRecycler.setLayoutManager(new FullyGridLayoutManager(mContext,3));
                ImageAdapter imageAdapter=new ImageAdapter(R.layout.item_square_image);
                imageRecycler.setAdapter(imageAdapter);
                List<String> imgUrls=new ArrayList<>();
                for (int i = 0; i < 9; i++) {
                    imgUrls.add("http://img.taopic.com/uploads/allimg/140326/235113-1403260U22059.jpg");
                }
                
                imageAdapter.addData(imgUrls);
                break;
        }


        helper.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                itemClickListener.onItemClick(helper,v,item);
            }
        });
    }`

**Comment by iosline** [comment]
`
public class FoundTrendHotFragment extends BaseFragment implements BaseQuickAdapter.RequestLoadMoreListener, SwipeRefreshLayout.OnRefreshListener {

    @BindView(R.id.rv_list)
    RecyclerView mRecyclerView;
    @BindView(R.id.swipeLayout)
    SwipeRefreshLayout mSwipeRefreshLayout;
    private FoundListRecyclerAdapter adapter;

    @Override
    protected void initData() {

    }

    @Override
    protected void initViews() {
        mSwipeRefreshLayout.setRefreshing(true);
        mSwipeRefreshLayout.setOnRefreshListener(this);
        mSwipeRefreshLayout.setColorSchemeColors(Color.rgb(47, 223, 189));
        mRecyclerView.setLayoutManager(new LinearLayoutManager(mActivity));
        mRecyclerView.addItemDecoration(new DividerItemDecoration(mActivity,
                DividerItemDecoration.VERTICAL_LIST));
        initAdapter();



    }

    private void initAdapter() {
        adapter = new FoundListRecyclerAdapter();
        adapter.setOnLoadMoreListener(this, mRecyclerView);
        adapter.openLoadAnimation();
        mRecyclerView.setAdapter(adapter);

        adapter.setItemClickListener(new FoundListRecyclerAdapter.ItemClickListener() {
            @Override
            public void onItemClick(BaseViewHolder holder, View view, Object object) {

            }
        });


    }

    @Override
    protected int getLayoutRes() {
        return R.layout.fragment_found;
    }



    public static FoundTrendHotFragment newInstance(String title){
        FoundTrendHotFragment fragment = new FoundTrendHotFragment();
        Bundle arguments = new Bundle();
        arguments.putString("title", title);
        fragment.setArguments(arguments);
        return fragment;
    }

    @Override
    protected void fetchData() {
        mRecyclerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                mSwipeRefreshLayout.setRefreshing(false);
                List<FoundItemModel> list=new ArrayList<>();
                for (int i = 0; i < 10; i++) {
                    FoundItemModel user=new FoundItemModel();
                    if (i%2 == 0){
                        user.setType(0);
                        if (i % 4==0){
                            user.setVertical(true);
                        }else {
                            user.setVertical(false);
                        }
                    }else {
                        user.setType(1);
                        user.setVertical(false);
                    }

                    list.add(user);
                }
                LogUtil.d("====initdata====zoujici");
                adapter.addData(list);
                mRecyclerView.smoothScrollToPosition(0);
            }
        },2000);
    }

    @Override
    public void onRefresh() {
        mRecyclerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                mSwipeRefreshLayout.setRefreshing(false);
                List<FoundItemModel> list=new ArrayList<>();
                for (int i = 0; i < 10; i++) {
                    FoundItemModel user=new FoundItemModel();
                    if (i%2 == 0){
                        user.setType(0);
                        if (i % 4==0){
                            user.setVertical(true);
                        }else {
                            user.setVertical(false);
                        }

                    }else {
                        user.setType(1);
                        user.setVertical(false);
                    }
                    list.add(user);
                }
                LogUtil.d("===regresh=====zoujici");
                adapter.setNewData(list);
                mRecyclerView.smoothScrollToPosition(0);
            }
        },2000);
    }

    @Override
    public void onLoadMoreRequested() {
        mRecyclerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                adapter.loadMoreComplete();
                List<FoundItemModel> list=new ArrayList<>();
                for (int i = 0; i < 10; i++) {
                    FoundItemModel user=new FoundItemModel();
                    if (i%2 == 0){
                        user.setType(0);
                        if (i % 4==0){
                            user.setVertical(true);
                        }else {
                            user.setVertical(false);
                        }
                    }else {
                        user.setType(1);
                        user.setVertical(false);
                    }
                    list.add(user);
                }
                LogUtil.d("=====loadmore===zoujici");
                adapter.addData(list);
            }
        },2000);
    }

}`

**Comment by CymChad** [comment]
你rv的item高度写死了没？
你rv的item里面有嵌套rv没？

**Comment by CymChad** [comment]
你上传的gif看不了

**Comment by iosline** [comment]
gif 直接点击看不了，你把链接 复制出来，新开一个标签页打开

**Comment by iosline** [comment]
9张图的时候 嵌套了rv, 高度都没有写死，都是android 自己测量的，没有自己的代码

**Comment by 1109993488** [comment]
最外层RV加上
```
android:focusable="true"
android:focusableInTouchMode="true"
```

**Comment by iosline** [comment]
我去，竟然可以  不跳了 厉害了 @1109993488

**Comment by ironman6121** [comment]
android:focusable="true"
android:focusableInTouchMode="true" 
这个确实能解决
