### ISSUE TITLE
我先打开几个 ，然后关闭全部折叠后 ，再打开某项 这时候 就打开的不对

### ISSUE THREAD

**Issue by everyline** [CymChad/BaseRecyclerViewAdapterHelper#1359]

**Comment by CymChad** [comment]
怎么不对了？

**Comment by everyline** [comment]
我先打开一项  然后调用方法 关闭全部，  这时候在打开 新的一项 ， pos 还是以前展开的list总数   这时候打开的这项  就不对了

**Comment by everyline** [comment]
这时候 pos 就不对了  但是 怎么重新获取 pos

**Comment by lhl-012** [comment]
设置变量  记住上一个打开的位置  然后再点击下一个时候  判断这个位置是不是为空 不为空就关闭他  最核心的是要再获取一下pos
![1](https://user-images.githubusercontent.com/30283272/28706855-a784cce8-73a8-11e7-8a79-344da267759e.png)
![2](https://user-images.githubusercontent.com/30283272/28706860-aeb135ce-73a8-11e7-9ba1-b55f21c1d31c.png)

**Comment by edifangyi** [comment]
![image](https://user-images.githubusercontent.com/12421552/31759512-3b5eb704-b4e4-11e7-822c-99ff939764cd.png)


可以做到点击自己，不收缩

**Comment by msrlin** [comment]
这个方法里的  hasOpen变量可以不使用
