### ISSUE TITLE
Error:(27, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.5 <a href="openFile:/Users/ruanruan/Code/git/BasicCommonLib/LibCommon/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

### ISSUE THREAD

**Issue by HelloDearWorld** [CymChad/BaseRecyclerViewAdapterHelper#136]
Error:(27, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.5
<a href="openFile:/Users/ruanruan/Code/git/BasicCommonLib/LibCommon/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by yunquefly** [comment]
我也是报的这种错误

**Comment by liu-hailin** [comment]
你们是不是没有在总gradle里面添加东西？

**Comment by liu-hailin** [comment]
allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
