### ISSUE TITLE
如果我现在有3级列表  我想点击 第一级列表   就要把2 3 级一次性都展开 而不是点击第2级 展开第3级 这时候就会报错

### ISSUE THREAD

**Issue by everyline** [CymChad/BaseRecyclerViewAdapterHelper#1362]
![vjmvu 5lgkkex ne 4xjarv](https://user-images.githubusercontent.com/8476579/28715165-684a1c06-73c9-11e7-811d-4c79912d9d46.png)
![ljpw7 vyta l8k03_ an](https://user-images.githubusercontent.com/8476579/28715170-6f8ea3d8-73c9-11e7-962f-347fd8105a34.png)

**Comment by CymChad** [comment]
Cannot call this method while RecyclerView is computing a layout or scrolling  这个错误是在数据还没加载完的时候又去操作了数据源。

**Comment by CymChad** [comment]
你可以把第3级的数据放在第2级后加载之后

**Comment by CymChad** [comment]
可以放在mRecyclerView.post里面加载。

**Comment by CymChad** [comment]
为什么要在mRecyclerView.post 里面去做操作是因为要在mRecyclerView初始化布局计算完成之后才能在操作mRecyclerView的ui，否则会出现Cannot call this method while RecyclerView is computing a layout or scrolling

**Comment by everyline** [comment]
我 就是把 第3级的数据 放到第2级加载之后  自动展开的 才会这样

**Comment by CymChad** [comment]
恩，我的意识是你加载第三层级数据的时候操作太快了，第二级还没加载完毕就开始第三级加载了。你可以把第三级数据加载放在mRecyclerView.post 里面去加载试试看还会不会报错。
