### ISSUE TITLE
怎么给2级设置EmptyView呢

### ISSUE THREAD

**Issue by kcjian** [CymChad/BaseRecyclerViewAdapterHelper#1363]
多级Adapter继承BaseMultiItemQuickAdapter，怎么给2级设置EmptyView呢，就是展开一级没有数据，2级显示EmptyVIew

**Comment by CymChad** [comment]
暂时不支持这个功能。你可以通过判断第2级数据为空的时候让第2级新增一个空数据作为标示，然后通过这个标示去显示你自己定义的emptyview，本质上就是多加一个type来区分。
