### ISSUE TITLE
使用RecyclerView嵌套NestedScrollView时, 如何实现上拉加载更多的功能

### ISSUE THREAD

**Issue by hexianqiao3755** [CymChad/BaseRecyclerViewAdapterHelper#1368]

**Comment by Troll4it** [comment]
@hexianqiao3755  我就是平常怎么写上拉加载更多，在NestedScrollView也是怎么写的

**Comment by hexianqiao3755** [comment]
@Troll4it 可是我嵌套之后只能加载一页的数据, onLoadMoreRequested这个方法都不进去

**Comment by Troll4it** [comment]
不会吧。那就有可能你的代码有问题，看下你的代码，这个我自己写过，完全是没有问题的

**Comment by hexianqiao3755** [comment]
我昨天把scrollview去掉把recyclerview上面的内容加到头部来实现了, 就不会有问题了, 代码已经覆盖掉了,
你能把你的代码发出来我看下吗? 我看看是不是我写的有问题

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1251
