### ISSUE TITLE
开了拖拽就不能单击

### ISSUE THREAD

**Issue by longlylong** [CymChad/BaseRecyclerViewAdapterHelper#137]

**Comment by elfman** [comment]
你是怎么用的，我测试是没问题

**Comment by longlylong** [comment]
toggleViewId这个id如果和item的布局大小一样的话?那item的单击事件会被抢了?
我用 GestureDetector和RecyclerView.addOnItemTouchListener实现了单击了

**Comment by elfman** [comment]
建议在onBindViewHolder中给itemView绑定单击事件
