### ISSUE TITLE
使用过程中布局错位

### ISSUE THREAD

**Issue by decazuk** [CymChad/BaseRecyclerViewAdapterHelper#1370]
大神，我使用的是2.9.18版本  我的recyclerview偶尔会布局错位
我的结构是上面有一个header展示banner
![_spec](https://user-images.githubusercontent.com/2127779/28804387-6ae7b936-7695-11e7-8a6b-ba8a6271a978.png)
但是使用过程中会出现recyclerview下端会变短
![wechatimg985](https://user-images.githubusercontent.com/2127779/28804401-8653cb4c-7695-11e7-896b-5dac527e4a0f.png)

我布局的高度都是match_parent，看变短的高度像是banner的高度。只是偶尔会出现。这个有可能跟什么有关系呢

**Comment by FrankKwok** [comment]
这个banner的高度是写死的吗？

**Comment by RyanChouChina** [comment]
大概是因为这个：

数据状态错乱
这个问题无论是RecyclerView还是ListView不做处理都会出现问题，这个本质上是由于布局重用机制导致的，解决办法是通过数据状态来控制控件的状态，一定要设置状态无论什么状态，if和else是少不了的，如下代码：

  if（entity.isCheck）{
    checkBox.isChecked(true);
  } else {
    checkBox.isChecked(false);
  }
