### ISSUE TITLE
多布局时，如何保证其中的item不被删除

### ISSUE THREAD

**Issue by fengwei23** [CymChad/BaseRecyclerViewAdapterHelper#1372]
大神，请教一个问题，我使用多布局时，会有不同的itemviewType，但是我开启了拖拽和滑动删除，我希望其中一种itemviewType的布局是不能被拖拽和删除的，请问该库可以实现吗（我尝试了之后发现好像不行）

**Comment by elfman** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/756

**Comment by fengwei23** [comment]
按照您的方式实现了，谢谢
