### ISSUE TITLE
ExpandableAdapter展开

### ISSUE THREAD

**Issue by xmqapple** [CymChad/BaseRecyclerViewAdapterHelper#1373]
ExpandableAdapter展开列表时候，我只想点击的那个展开，其它的关闭，就是一次只展开一个，其余的都关闭，这个功能有没有方法做呢

**Comment by lhl-012** [comment]
![tim 20170802093432](https://user-images.githubusercontent.com/30283272/28853864-f70600c8-7765-11e7-9fc2-4d0eda8789cf.png)
![tim 20170802093500](https://user-images.githubusercontent.com/30283272/28853865-f7086980-7765-11e7-9ae7-edeffb7ef9ea.png)

**Comment by lhl-012** [comment]
设置2个变量，记录上次点击开的位置，下次打开时候先关闭上次的，要重新获取位置
