### ISSUE TITLE
Focus or bring the parent item after expanding to top!

### ISSUE THREAD

**Issue by khaledkhj** [CymChad/BaseRecyclerViewAdapterHelper#1378]
After clicking on item to expand it, it would be nicer to bring the parent item to top so that we can see the children right away!

This is a good practice in case we are expanding items on the bottom of the screen. 

Thank you in advance.

**Comment by lhl-012** [comment]
recyclerview have two method : scrollToPosition()  and   smoothScrollToPosition() .LayoutManager have a method : scrollToPositionWithOffset(pos, 0);   These 3 methods can scroll to the specified location (It's not on the screen) , but the location where you can click is already on the screen .  I am sorry, we have no way to make it sticky, maybe you can try another way
