### ISSUE TITLE
在ViewPager的Fragment中添加HeadView或者FooterView会出现“child already has a parent”异常

### ISSUE THREAD

**Issue by walkthehorizon** [CymChad/BaseRecyclerViewAdapterHelper#138]
具体是这样的，当我在在ViewPager的Fragment中的RecyclerView中添加头部后，初次加载一切都是正常的，但当滑倒其他位置在滑回该页面的时候，就出现了
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

个人解决办法，每次滑动回来的时候去除HeadView的父布局的所有子布局，
        if (storyAdapter != null){
            ViewGroup viewGroup = (ViewGroup) getHeadView(news).getRootView();
            viewGroup.removeAllViews();
            storyAdapter.addHeaderView(getHeadView(news));
        }

不知道你们怎么看这个问题，以及如何更好的解决

**Comment by liu-hailin** [comment]
这涉及到Fragment生命周期了吧？再进来添加会再添加一个，本身的那一个还被缓存的状态，肯定会报错已经有一个了，建议优化下自己代码，生命周期控制下
