### ISSUE TITLE
item绑定点击事件，点击出现多个选中状态

### ISSUE THREAD

**Issue by xueyaxuan** [CymChad/BaseRecyclerViewAdapterHelper#1380]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.9'
再给item绑定点击事件时，设置选中的背景颜色。出现点击第一个，第九个也有了背景色，数据量大的话以此类推每过九个就会选中一个

**Comment by FrankKwok** [comment]
建议更换最新版本

**Comment by xueyaxuan** [comment]
我试一下

**Comment by xueyaxuan** [comment]
已更新到最新版本 问题还是存在

**Comment by FrankKwok** [comment]
调用代码发一下

**Comment by xueyaxuan** [comment]
gomeRandAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {

                                    @Override
                                    public void onItemClick(BaseQuickAdapter adapter, View view, int position) {

                                        if (beforSelectView != null){
                                            beforSelectView.setBackgroundColor(Color.WHITE);
                                        }
                                        //选中的颜色置为黄色
                                        view.findViewById(R.id.ll_form).setBackgroundColor(Color.parseColor("#FFAA00"));
                                        //保存此次选中的对象
                                        beforSelectView  = (LinearLayout) view.findViewById(R.id.ll_form);
                                        mTvItemJdKp.setText(“”");
                                        mTvJdFlag.setText(listsBeans.getData().getList().get(position).getEnterpriseName()+"");
                                        //请求选中数据的信息
                                        getCompanyDetailDatas(listsBeans.getData().getList().get(position).getEnterpriseName());
                                    }
                                });

**Comment by FrankKwok** [comment]
不理解复用机制导致的问题，@see http://www.jianshu.com/p/b343fcff51b0

**Comment by FrankKwok** [comment]
看`数据状态错乱`的示例

**Comment by xinghang-shen** [comment]
查看了示例没看到解决的办法，我的情况是 一共12条数据，我的第一条数据状态为选中，第十条数据的状态同步问选中，第二条对应 第十一条，第三条对应第十二条，因为只有十二条数据，所以当第四条数据选中的时候，不会有其他选中的条目，因此缓存的规则为 从第十条开始缓存前面的一到九条。
