### ISSUE TITLE
调用LoadMoreEnd之后就无法回复LoadMoreRequest。

### ISSUE THREAD

**Issue by LaxusYlg** [CymChad/BaseRecyclerViewAdapterHelper#1383]
条件搜索界面，使用同一个Adapter，一旦某一个条件没更多数据，调用了LoadMoreEnd之后，查询其他条件，但是OnLoadMore没有再调用了。使用setEnableLoadMore+loadMoreComplete可以达到LoadMoreEnd的开启与关闭效果，我觉得如果能使用一个方法达到该效果是否比较好。

**Comment by FrankKwok** [comment]
新的条件需要重新配置

**Comment by CymChad** [comment]
如果需要重新开启上拉可以在重新加载数据的时候调用setNewData
