### ISSUE TITLE
disableLoadMoreIfNotFullPage()在该情况下无效

### ISSUE THREAD

**Issue by JeremyLam1** [CymChad/BaseRecyclerViewAdapterHelper#1384]
如MainActivity底部有两个可切换显示的tab，即fragment A与Fragment B，B页面是个（RecylcerView列表）。

     当进入B页面，执行代码显示下拉的loading获取数据：
```
           mSrlRefresh.setEnabled(true);
           mSrlRefresh.setRefreshing(true);
           mAdapter.setEnableLoadMore(false);
```

      开始获取数据时马上切换到A页面，等B页面获取数据结束之后，切换回B页面，就会发现上拉加载更多操作开始执行了（只有首次获取数据会出现）。如果是B页面首次获取数据时候，不切换到其他界面Fragment A，则正常（即不会出现上拉加载更多操作）。
      
     B页面获取数据后代码处理是：
```
          mAdapter.setNewData(list);
          mAdapter.disableLoadMoreIfNotFullPage();
          mSrlRefresh.setRefreshing(false);
          mAdapter.setEnableLoadMore(false);
```

**Comment by wxy520ll** [comment]
我也遇到一个关于disableLoadMoreIfNotFullPage() 的问题。。这个方法有点问题

**Comment by CymChad** [comment]
如果不调用这个方法，直接进入回调，在回调里面处理判断如果不满足一页就关闭上拉监听，你觉得这个方式会不会比调用disableLoadMoreIfNotFullPage好一些？

**Comment by tysheng** [comment]
对于这种快速操作，当前方法确实不能很好的工作，你只能监听滑动了
