### ISSUE TITLE
请问我连续调用了removeHeaderView和addHeaderView出现的问题

### ISSUE THREAD

**Issue by HeJingWei** [CymChad/BaseRecyclerViewAdapterHelper#1386]
我用动画作了一个平移，显示出的时候我把头部add进去，隐藏的时候remove了。现在有一个问题就是我remove了之后再add同一个view，view里的布局都不见。请问这是为什么呢

**Comment by FrankKwok** [comment]
调用代码与版本？

**Comment by HeJingWei** [comment]
解决了，不能和属性动画一起用，不知道为什么，我直接用remove和add也自带平移了
