### ISSUE TITLE
RecyclerView中的EditText、TextView时设置了长按选中时弹不出系统的复制/粘贴/全选等选择

### ISSUE THREAD

**Issue by xwtao** [CymChad/BaseRecyclerViewAdapterHelper#1387]
我给RecyclerView中的EditText、TextView时设置了长按弹出系统的复制/粘贴/全选等选择，但滑动了几个item后就长按弹不出来了，继承原生的适配器就可以（TextView设置长按选中的代码是这样的：
                android:enabled="true"
                android:focusable="true"
                android:longClickable="true"          
                android:textIsSelectable="true"）

**Comment by AllenCoder** [comment]
```
android:textIsSelectable="true" 
```
这个属性加上会弹不出 复制/粘贴/全选 

我这边去掉这个测试一下正常，我的代码和截图如下
```
<EditText
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:hint="测试粘贴"
    android:enabled="true"
    android:focusable="true"
    android:longClickable="true"
    android:textColor="@color/ksw_md_ripple_checked"
    android:layout_alignParentBottom="true"
    android:layout_centerHorizontal="true" />
```

点击事件使用的是  **adapter.setOnItemXX** 这种，不能用**mRecyclerView.addOnItemTouchListener** 会有冲突

![st 3i2nsa hf5x8 hubs 2](https://user-images.githubusercontent.com/8213915/28913960-731bf350-786c-11e7-9f10-5686709cb431.png)

**Comment by QiuSean** [comment]
这个问题我也遇到了，请问最终解决了么

**Comment by xwtao** [comment]
我最后是用代码通过长按复制到到剪切板的

**Comment by QiuSean** [comment]
场景太多，这么处理坑太多了，先紧急上了，有兴趣回头一起研究下，加个微信：SeanSuc

**Comment by chenyongda2018** [comment]
@QiuSean @xwtao 
重写adapter的onViewAttachedToWindow方法
`@Override
    public void onViewAttachedToWindow(RecyclerView.ViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        holder.textView.setEnabled(false);
        holder.textView.setEnabled(true);
    }`
