### ISSUE TITLE
请问有关item进入动画的问题

### ISSUE THREAD

**Issue by CKTim** [CymChad/BaseRecyclerViewAdapterHelper#1388]
现在我在做聊天界面，想让右边的item有进入动画，左边的没有，这个怎么处理？

**Comment by CKTim** [comment]
还有请问一下多类型item会导致动画失效是什么问题？

**Comment by CymChad** [comment]
动画设置目前只会在一种itemtype的情况下执行。

**Comment by CKTim** [comment]
请问如果是多item的时候呢？有没有解决思路




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月3日(星期四) 下午4:34
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "蔡晓坤"<471497226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问有关item进入动画的问题 (#1388)




动画设置目前只会在一种itemtype的情况下执行。

**Comment by CymChad** [comment]
我这边看下

**Comment by CKTim** [comment]
麻烦了 很需要这个功能
 




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月3日(星期四) 下午4:45
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "蔡晓坤"<471497226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问有关item进入动画的问题 (#1388)




我这边看下

**Comment by CymChad** [comment]
你的版本号是？

**Comment by CKTim** [comment]
2.9.24


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月3日(星期四) 下午4:47
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "蔡晓坤"<471497226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问有关item进入动画的问题 (#1388)




你的版本号是？

**Comment by CymChad** [comment]
我看了下源码，多类型是支持的

**Comment by CymChad** [comment]
刚才也跑了下代码，是支持的

**Comment by CKTim** [comment]
我这边在看一下  是不是我自己使用有问题




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月3日(星期四) 下午4:51
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "蔡晓坤"<471497226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问有关item进入动画的问题 (#1388)




我看了下源码，多类型是支持的

**Comment by CymChad** [comment]
![1](https://user-images.githubusercontent.com/7698209/28913942-5baba0ee-786c-11e7-80ee-d18df8e3fb0e.gif)

我就只是调用了`  multipleItemAdapter.openLoadAnimation();`

**Comment by CKTim** [comment]
可能我没说清楚，我是这样情况的，添加新的Item进去，有些不加载动画，例如发了张图片他可能加载动画了，但是发了段文字他就不加载动画了
 




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月3日(星期四) 下午4:54
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "蔡晓坤"<471497226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问有关item进入动画的问题 (#1388)





 
我就只是调用了multipleItemAdapter.openLoadAnimation();

**Comment by CymChad** [comment]
我这篇无法重现,从源码的角度来看只要不是特殊类型都会有动画的。
```java
  @Override
    public void onViewAttachedToWindow(K holder) {
        super.onViewAttachedToWindow(holder);
        int type = holder.getItemViewType();
        if (type == EMPTY_VIEW || type == HEADER_VIEW || type == FOOTER_VIEW || type == LOADING_VIEW) {
            setFullSpan(holder);
        } else {
            addAnimation(holder);
        }
    }
```
