### ISSUE TITLE
多item设置setEmptyView的问题

### ISSUE THREAD

**Issue by xuekaiqi** [CymChad/BaseRecyclerViewAdapterHelper#1389]
我设置多item布局后，然后设置setEmptyView后报数组越界
![image](https://user-images.githubusercontent.com/17778482/28909179-ec9dd120-7859-11e7-9ca6-8eb7e1e25843.png)
求大神指点

**Comment by FrankKwok** [comment]
是否是配置错误，@see #1289, #1280 , #1105

**Comment by CymChad** [comment]
重写`getItemViewType`肯定会出现问题，因为base类有很多处理，多item可以看文档用正确的方法配置即可。
