### ISSUE TITLE
MultiTypeDelegate

### ISSUE THREAD

**Issue by jbxkuang** [CymChad/BaseRecyclerViewAdapterHelper#1392]
public final int getLayoutId(int viewType) {
        return this.layouts.get(viewType, TYPE_NOT_FOUND);
}

当getLayoutId 为 TYPE_NOT_FOUND时, 因为TYPE_NOT_FOUND = -404,
导致Resources$NotFoundException
且该方法为final,无法覆写.

建议增加默认layoutId 的方法

**Comment by FrankKwok** [comment]
默认的layoutId意义何在？

**Comment by jbxkuang** [comment]
@FrankKwok 
type not found 时 return 的 layoutId,目前的写法遇到未注册的type会抛出Resources$NotFoundException

**Comment by FrankKwok** [comment]
未注册的type报异常有什么问题吗，这是代码逻辑写错了呀

**Comment by tysheng** [comment]
type 不是你自己设置的吗，你控制 bean 里的 type 就好了

**Comment by jbxkuang** [comment]
你们认为this.layouts.get(viewType, TYPE_NOT_FOUND);第二个参数的意义?
是返回404?:-D
