### ISSUE TITLE
LoadMoreView的状态对。加载更多的影响

### ISSUE THREAD

**Issue by wxy520ll** [CymChad/BaseRecyclerViewAdapterHelper#1394]
又发现 一个设计不好的地方。我再项目中把 上拉加载更多+下拉刷新 抽出来作为基类。。有这样的一个activity。 通过筛选条件，显示列表。。假设每页数据10条。筛选条件1。总共有12条。。筛选条件2  有4条。。筛选条件3  有0条。。。。因为每个条件最后都是对应不同的loadMore状态。导致，任意切换筛选条件，，在有些情况下。异常
```java
if (datalist.size()==0&&page==1){
			mlist.clear();
			stateLayout.showEmptyView();
			adapter.notifyDataSetChanged();
			return;
		}
		if (datalist.size() < 10) {
			adapter.loadMoreEnd();
		} else {
			adapter.loadMoreComplete();
		}
```
核心代码如上。多dataList.size()==0 && page==1 是调试新家上去的

**Comment by wxy520ll** [comment]
因为loadMore的状态 影响着代码的运行。所以。 导致有很多数据，但是第一页加载完成之后，就显示 “没有更多数据了”

**Comment by FrankKwok** [comment]
请详细描述你的问题

**Comment by wxy520ll** [comment]
简单说：一个界面可以选择三个筛选条件。。没选择一个筛选条件，那么recycleview的adapter将刷新一下。。 此开源项目的源码：
```java
  if (getLoadMoreViewCount() == 0) {
            return;
        }
        if (position < getItemCount() - mAutoLoadMoreSize) {
            return;
        }
        if (mLoadMoreView.getLoadMoreStatus() != LoadMoreView.STATUS_DEFAULT) {
            return;
        }
```
当mLoadMoreView.getLoadMoreStatus() != LoadMoreView.STATUS_DEFAULT  就会return。

所以会导致下面的情况：
我点击筛选条件一：假设加载失败loadview的状态时fail状态。这个时候 我紧接着有点击筛选条件2。。因为loadview 已经为fail状态了。所以点击筛选2。之后假设请求到数据，但是loadview显示  加载失败

**Comment by 1109993488** [comment]
筛选请求的数据调setNewData设置，然后再判断是否要关闭加载更多

**Comment by wxy520ll** [comment]
好的，多谢。。筛选条件之前：清空数据源，然后调用setNewData。然后就不会出现这个问题。。这个方法是必须要放在请求之前 调用吗
