### ISSUE TITLE
recycleView设置横向LinearLayoutManager.HORIZONTAL，在添加头部出现问题

### ISSUE THREAD

**Issue by Troll4it** [CymChad/BaseRecyclerViewAdapterHelper#1395]
这是下面的效果图![screenshot_2017-08-04-12-09-34](https://user-images.githubusercontent.com/27883219/28953882-da993050-790d-11e7-8830-3d9528fa1a92.png)

**Comment by FrankKwok** [comment]
问题是？

**Comment by Troll4it** [comment]
@FrankKwok 头部跟item,在一个同一水平线，而不是在顶部

**Comment by CymChad** [comment]
你可以这样，rv嵌套rv  外层的rv是VERTICAL的addhead，然后rv的item就是rv。

**Comment by CymChad** [comment]
源码是对不同方向做过处理，不过只是LayoutParams的处理。
 ```
public int addHeaderView(View header, int index, int orientation) {
        if (mHeaderLayout == null) {
            mHeaderLayout = new LinearLayout(header.getContext());
            if (orientation == LinearLayout.VERTICAL) {
                mHeaderLayout.setOrientation(LinearLayout.VERTICAL);
                mHeaderLayout.setLayoutParams(new LayoutParams(MATCH_PARENT, WRAP_CONTENT));
            } else {
                mHeaderLayout.setOrientation(LinearLayout.HORIZONTAL);
                mHeaderLayout.setLayoutParams(new LayoutParams(WRAP_CONTENT, MATCH_PARENT));
            }
        }
```

**Comment by CymChad** [comment]
因为LinearLayoutManager要么横要么竖。

**Comment by Troll4it** [comment]
谢谢，按照您的思维实现了想要的效果。。
后来我也看了下源码：这样去设置   adapter.addHeaderView(view,-1, LinearLayout.VERTICAL);也无效
想问下;
  if (orientation == LinearLayout.VERTICAL) {
               mHeaderLayout.setOrientation(LinearLayout.VERTICAL);
               mHeaderLayout.setLayoutParams(new LayoutParams(MATCH_PARENT, WRAP_CONTENT));
           } else {
               mHeaderLayout.setOrientation(LinearLayout.HORIZONTAL);
               mHeaderLayout.setLayoutParams(new LayoutParams(WRAP_CONTENT, MATCH_PARENT));
           }
这个应该是对方向进行处理，但是我也传递了方向这个值进去，没有效果，为什么？？谢谢

**Comment by CymChad** [comment]
他这个方法是为了填充宽度和高度，如果是竖的那么头部宽度要`MATCH_PARENT`，如果是横的那么头部高度要`MATCH_PARENT`。
