### ISSUE TITLE
关于下面这段代码，添加GridLayoutManager时添加自定义分割线的问题

### ISSUE THREAD

**Issue by mlzhang920802** [CymChad/BaseRecyclerViewAdapterHelper#1396]
mRecyclerView.setLayoutManager(new GridLayoutManager(mContext,2));
        addHeaderAdapter = new AddHeaderAdapter(anchorList);
        addHeaderAdapter.openLoadAnimation(BaseQuickAdapter.ALPHAIN);
        mRecyclerView.setAdapter(addHeaderAdapter);
        dividerGridItemDecoration = new DividerGridItemDecoration(mContext, PxDpUtil.dp2px(5),mContext.getResources().getColor(R.color.gray));
//        dividerItemDecoration = new DividerItemDecoration(mContext,DividerItemDecoration.VERTICAL_LIST,mContext.getResources().getDrawable(R.drawable.shape_vertical_split));
        mRecyclerView.addItemDecoration(dividerGridItemDecoration);
        View headerView = getLayoutInflater(saveInstance).inflate(R.layout.item_header, (ViewGroup) mRecyclerView.getParent(), false);
        addHeaderAdapter.addHeaderView(headerView, 0);
        mRecyclerView.setAdapter(addHeaderAdapter);

**Comment by CymChad** [comment]
出现了什么问题？

**Comment by CymChad** [comment]
DividerGridItemDecoration都是由开发来绘制的，你可以修改一下你的绘制代码。addHeaderView默认就是add一个item。
