### ISSUE TITLE
recycleView里面嵌套gridView，列表gridView的数据重复了

### ISSUE THREAD

**Issue by zhsiyi** [CymChad/BaseRecyclerViewAdapterHelper#1399]
是这样的，我在这个recycleView item里面是需要选择相册添加图片的，所以就是类似发表朋友圈里面的功能，但是我用来装相册的列表用的是gridView，这样出现了添加图片后下面的item也出现了一样的图片，类似缓存的。前面checkbox跟edittext的问题都解决了，但是这个recycleView嵌套gridView的缓存问题不知道从哪里下手，不知道能不能指示一下。

**Comment by CymChad** [comment]
0.打印一下图片路径，看是否数据导致。
1.你可以尝试吧gv缓存rv。
2.你可以换个图片缓存框架试试。

**Comment by zhsiyi** [comment]
老大，顺便问一下，您这个控件的上拉刷新怎么加进去啊，搞半天没搞懂。上下拉的




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月7日(星期一) 下午3:19
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "jusic&泗夷"<348510817@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] recycleView里面嵌套gridView，列表gridView的数据重复了 (#1399)




Closed #1399.
