### ISSUE TITLE
快速连续多次滑动删除item时bug

### ISSUE THREAD

**Issue by ssyijiu** [CymChad/BaseRecyclerViewAdapterHelper#140]
有些item已经变成了黄色但是没有删除，并且convertView复用，滑动的时候其他item也会变成黄色。

**Comment by elfman** [comment]
你是指用demo时出错？

**Comment by elfman** [comment]
你是不是没有重写clearView方法？
如果在start时修改了item的样式，不管最后有没有删除item，都要在clearView中将其还原，我在注释里写了

**Comment by ssyijiu** [comment]
是的，demo出错

**Comment by elfman** [comment]
已修改并提交pr

**Comment by CymChad** [comment]
已合成代码。  
请使用  
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.8'
