### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c

### ISSUE THREAD

**Issue by wmq389122157** [CymChad/BaseRecyclerViewAdapterHelper#1400]
多布局崩溃,  添加的itemType确认没有错误, 想问一下怎么解决

**Comment by CymChad** [comment]
版本，代码。
这种错误可能出现的错误有一下：
1. 你在adapter初始化的时候配置了没？
2.你在填充数据的时候getitemtype重写了没？
3.1和2的type类型是否一致了？

**Comment by wmq389122157** [comment]
已经解决了, 原因可能是我两个item类型 用的同一个自定义的BaseViewHolder,现在改成通用的BaseViewHolder了, 我想问一下, 是不是多种item类型不能用多个自定义的ViewHolder

**Comment by FrankKwok** [comment]
你Adapter的泛型是如何声明的？

**Comment by wmq389122157** [comment]
extends BaseMultiItemQuickAdapter<MemberBean, MyHolder>
如果多个item类型的话 会报错
我就换成了 extends BaseMultiItemQuickAdapter<MemberBean, BaseViewHolder> 这种
然后在convert里边只能通过框架的API 设置数据, 不能把baseViewHolder 强转成MyHolder

**Comment by FrankKwok** [comment]
BaseViewHolder有getView方法，一般是没有必要自定义holder的

**Comment by MapleDev** [comment]
其实还有一种可能：getItemType() 大于 addItemType的数量时就会报此错

**Comment by kamaelyoung** [comment]
> 其实还有一种可能：getItemType() 大于 addItemType的数量时就会报此错

😂 感谢
