### ISSUE TITLE
BaseMultiItemQuickAdapter使用问题

### ISSUE THREAD

**Issue by SuperXiaoda** [CymChad/BaseRecyclerViewAdapterHelper#1402]
我使用BaseMultiItemQuickAdapter，在给二级列表添加数据后，使用adnapter的replaceData()方法后整个列表的数据就没有了。小弟测试代码如下：
    Person person = (Person) mListData.get(0);
                person.getSubItems().add(new Like("搞笑"));
                mAdapter.replaceData(mListData);
望大神指点！

**Comment by elfman** [comment]
是整个列表都空了什么都没有显示吗？

**Comment by FrankKwok** [comment]
。。。，你这样使用是不太对

**Comment by FrankKwok** [comment]
这个方法是把老列表清空，新列表的数据都加入到老列表

**Comment by SuperXiaoda** [comment]
谢谢各位，是我自己使用的问题
