### ISSUE TITLE
子条目点击事件

### ISSUE THREAD

**Issue by chenkexu** [CymChad/BaseRecyclerViewAdapterHelper#1403]
如果子条目有一个SeekBar,如何获取拖动事件呢？？是在adapter里面获取View，再设置点击事件吗？

**Comment by CymChad** [comment]
恩是的 , holder.getview获取SeekBar。

**Comment by chenkexu** [comment]
如果我想在Activity里面获取SeekBar，该怎么获取呢？？？

**Comment by chenkexu** [comment]
@CymChad

**Comment by CymChad** [comment]
getviewbyposition

**Comment by chenkexu** [comment]
那就是说，只能在点击事件里面调用getviewbyposition了？？？@CymChad

**Comment by CymChad** [comment]
恩  这样就可以拿到其他布局，还有就是通过改变数据实体来控制其他布局
