### ISSUE TITLE
上拉加载onLoadMore无限回调

### ISSUE THREAD

**Issue by jesse920524** [CymChad/BaseRecyclerViewAdapterHelper#1407]
版本:compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.12'

activity部分代码:
 mAdapter.setOnLoadMoreListener(() -> {
            mRecyclerView.postDelayed((Runnable) () -> {
                mPresenter.requestData(mPresenter.getCurrPage());
            }, 1000);
        }, mRecyclerView);

presenter部分代码:
public void requestData(int page){
        dataService.getLiuchongList(page)
                .observeOn(AndroidSchedulers.mainThread()).subscribe(observer);
    }

observer部分代码:
private final class LiuchongListObserver implements Observer<LiuChongListEntity> {

        /**
         * Provides the Observer with the means of cancelling (disposing) the
         * connection (channel) with the Observable in both
         * synchronous (from within {@link #onNext(Object)}) and asynchronous manner.
         *
         * @param d the Disposable instance whose {@link Disposable#dispose()} can
         *          be called anytime to cancel the connection
         * @since 2.0
         */
        @Override
        public void onSubscribe(Disposable d) {

        }

        @Override
        public void onNext(LiuChongListEntity entity) {
            Log.d(TAG, "onNext: " + entity);
            currPage++;
            if (currPage == 1){
                mView.getAdapter().loadMoreComplete();
                loadData(entity.getSneakList());

            }else{
                mView.getAdapter().loadMoreComplete();
                loadDataMore(entity.getSneakList());

            }
        }

        @Override
        public void onError(Throwable e) {
            Log.d(TAG, "onError: " + e.toString());
            mView.loadDataEnd();
        }

        /**
         * Notifies the Observer that the {@link Observable} has finished sending push-based notifications.
         * <p>
         * The {@link Observable} will not call this method if it calls {@link #onError}.
         */
        @Override
        public void onComplete() {

        }
    }

弄了一晚上,还是没能好用.
还要麻烦宇明哥了,真是抱歉.

2017/08/06补充:
presenter#loadData()及presenter#loadDataMore()部分代码:

public void loadData(List<LiuChongListEntity.SneakListBean> beanList){
        mView.loadData(beanList);

    }

    public void loadDataMore(List<LiuChongListEntity.SneakListBean> beanList){
        mView.loadDataMore(beanList);

    }

view#loadData()及view#loadDataMore()

@Override
    public void loadData(List<LiuChongListEntity.SneakListBean> beanList) {
        mRecyclerView.post(new Runnable() {
            @Override
            public void run() {
                mAdapter.setNewData(beanList);
            }
        });
    }

    @Override
    public void loadDataMore(List<LiuChongListEntity.SneakListBean> beanList) {
        mRecyclerView.post(new Runnable() {
            @Override
            public void run() {
                mAdapter.addData(beanList);
            }
        });
    }

**Comment by 1109993488** [comment]
没有数据的时候需要调loadMoreEnd关闭加载更多，否则在底部会一直回调

**Comment by 1109993488** [comment]
如果不是数据问题，看是否嵌套了ScrollView造成的

**Comment by dengzhenyu** [comment]
如果嵌套了scrollview是不是没有解决办法，只能用swiperefreshlayout

**Comment by jesse920524** [comment]
我是这样解决的:
1.更新版本:compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.22'
2.在http response的回调中的代码:

@Override
        public void onNext(LiuChongListEntity entity) {

           //获取server返回的总页数,根据总页数判断加载多少页数据
            int totalPages = entity.getPages();
            if (currPage == 1) {
                mView.loadData(entity.getSneakList());
                mView.loadMoreComplete();
            }else {
               //当当前页数大于等于总页数时,不再请求更多数据.
                if (totalPages <= currPage) {
                    mView.loadMoreEnd();
                }else {
                   //当前页数小于总页数,说明还需要请求更多数据
                    mView.loadMoreComplete();
                }
                mView.loadDataMore(entity.getSneakList());
            }

            currPage++;
        }

mView#loadData()及loadDataMore()代码:
 @Override
    public void loadData(List<LiuChongListEntity.SneakListBean> beanList) {
        mListAdapter.getData().clear();
        mListAdapter.setNewData(beanList);
        mSwipeLayout.setRefreshing(false);
    }

   @Override
    public void loadDataMore(List<LiuChongListEntity.SneakListBean> beanList) {
        mRecyclerViewList.post(new Runnable() {
            @Override
            public void run() {
                mListAdapter.addData(beanList);
            }
        });
    }

mView#loadMore() 及mView#loadMoreEnd()代码:
 @Override
    public void loadMoreComplete() {
        mListAdapter.loadMoreComplete();
    }

    @Override
    public void loadMoreEnd() {
        mListAdapter.loadMoreEnd(true);//与以前不同,这次调用一个形参的方法.
    }

这样解决了上拉加载更多无限回调的问题.

仍然存在的问题:
mListAdapter.loadMoreEnd(false);//如果这样写,仍然会触发上拉无限回调.

这次集成新版本的BRVAH对我造成了非常大的困扰,大概超过12小时卡在了上拉无限回调的问题.
其根本原因是我没有阅读recyclerView源码以及BRVAH源码,惭愧.
最后感谢@1109993488 @dengzhenyu 的耐心解答,再次感谢宇明哥开源这么优秀的类库.

**Comment by vipheyue** [comment]
几百万条数据,几百万页 也要加载完???

**Comment by po1arbear** [comment]
这个解决bug很常见啊 ，从根本上解决了吗？  现在看到的解决方案都不够优雅：1、取消scrollview，用header+recyclerview  2、当页数大于一定数值时取消加载
