### ISSUE TITLE
找不到资源id，整个layout就一直有一个找不到id 

### ISSUE THREAD

**Issue by YY007H** [CymChad/BaseRecyclerViewAdapterHelper#1408]
![8r xhdzem8 u xahvaloza](https://user-images.githubusercontent.com/15188456/29052552-80226f7a-7c1d-11e7-8c55-4e6c5955335f.png)
把这行禁掉 就正常了 这是为什么？ 确定布局中的确有这个id

**Comment by FrankKwok** [comment]
这个`info.getTESTNO()`是int吧，要显式转成String，不然调用资源的重载方法`setText(int,int)`

**Comment by YY007H** [comment]
是int类型的，我的锅(┬＿┬)

**Comment by Jcfa** [comment]
请问可以进行dataBingding的绑定么

At 2017-08-08 18:17:18, "陈宇明" <notifications@github.com> wrote:


Closed #1408.
