### ISSUE TITLE
作者大大为什么你使用notifyItemRangeInserted()不会抛出异常？

### ISSUE THREAD

**Issue by pdog18** [CymChad/BaseRecyclerViewAdapterHelper#1411]
```
    /**
     * add new data to the end of mData
     *
     * @param newData the new data collection
     */
    public void addData(@NonNull Collection<? extends T> newData) {
        mData.addAll(newData);
        notifyItemRangeInserted(mData.size() - newData.size() + getHeaderLayoutCount(), newData.size());
        compatibilityDataSizeChanged(newData.size());
    }

```
您的代码里面 有用到`  notifyItemRangeInserted(mData.size() - newData.size() + getHeaderLayoutCount(), newData.size());`

其中这个`newData,size()`并不为0 ，而我仿照你这样写的话，很容易就出现这样的异常
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{7b483c2 position=7 id=-1, oldPos=-1, pLpos:-1 no parent} 
```
我debug发现是在`RecyclerView#ViewHolder#offsetPosition()`中修改了`ViewHolder`的`mPosition`导致了异常。

所以我在自己的类中将`notifyItemRangeInserted(mData.size() - newData.size() ,newData.size())`的后面一个参数直接修改为0，即直接改了`offsetposition()`中的接受的第二个`offset`的参数或者将`notifyItemRangeInserted()` 直接修改为`notifyDataSetChange()`才行，但是我看您的项目里，使用`notifyItemRangeInserted()`完全没有异常，想请教一下大家这个`offsetposition()`是不是有毒啊？

**Comment by CymChad** [comment]
没有深入研究过
