### ISSUE TITLE
 取消第一进来就加载更多，取消下拉刷新时也在加载更多要怎么做？

### ISSUE THREAD

**Issue by yliang11** [CymChad/BaseRecyclerViewAdapterHelper#1414]
mAdapter.disableLoadMoreIfNotFullPage(mRecyclerView);这句该在哪调用？怎么老是不起作用
 @Override
    public void onRefresh() {
        mAdapter.setEnableLoadMore(false);
        getData();
    }
下拉刷新时已关闭了加载更多，还是出现加载了更多数据

**Comment by 1109993488** [comment]
你一进来就有数据？一进来设置了加载更多并且有数据的时候会触发加载更多
