### ISSUE TITLE
请问一下:我数据更新了后调用adapter.notifyDataSetChanged()更新不了数据

### ISSUE THREAD

**Issue by azhengyongqin** [CymChad/BaseRecyclerViewAdapterHelper#1416]
请问一下:我数据更新了后调用adapter.notifyDataSetChanged()更新不了数据

**Comment by CymChad** [comment]
你检查下你更新的数据源是否adapter的数据源，你可以通过adapter.getdata 获取数据源然后你再尝试一下更新试一下是否有效。
