### ISSUE TITLE
关于网格布局最后一行的补全问题

### ISSUE THREAD

**Issue by Non-Name** [CymChad/BaseRecyclerViewAdapterHelper#1418]
如果是使用网格布局，那么当最后一行数据不够填满时，怎样设置填充控件呢

**Comment by CymChad** [comment]
自己可以添加一个空数据

**Comment by CymChad** [comment]
adapter只负责显示数据。

**Comment by keaitao0321** [comment]
GridLayoutManager layoutManager = (GridLayoutManager) mRecyclerView.getLayoutManager();
        layoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                //  int itemViewType = mBaseQuickAdapter.getItemViewType(position);
                int itemViewType = mRecyclerView.getAdapter().getItemViewType(position);
                if (itemViewType == 0) {
                    return 1;
                } else {
                    return 2;
                }
                // return 2;
            }
        });

不知道对你有用没
