### ISSUE TITLE
多类型item拖曳怎么做

### ISSUE THREAD

**Issue by huangchaoqingcheng** [CymChad/BaseRecyclerViewAdapterHelper#1419]
多类型item的且可以拖曳的怎么做？怎么让它同时拥有BaseItemDraggableAdapter和BaseMultiItemQuickAdapter的功能？

**Comment by huangchaoqingcheng** [comment]
我尝试把BaseItemDraggableAdapter加上MultiItem的效果了  但是拖曳的item只能在与它同类型的地方插入  请问该怎样改

**Comment by CymChad** [comment]
文档有答案 http://www.jianshu.com/p/b343fcff51b0

**Comment by CymChad** [comment]
默认不支持多个不同的 ViewType 之间进行拖拽，如果开发者有所需求：

重写ItemDragAndSwipeCallback里的onMove()方法，return true即可

**Comment by huangchaoqingcheng** [comment]
还有个体验的问题想请教一下  比如上面的item有很长，拖动item自动往上滚的时候托不上去，，，

**Comment by huangchaoqingcheng** [comment]
在OnItemDragListener的回调方法里怎么拿到触摸的x y坐标?
![image](https://user-images.githubusercontent.com/13914477/29301457-e3862d86-81ae-11e7-9eb3-e59b6ad4bd54.png)

**Comment by elfman** [comment]
@huangchaoqingcheng 在OnItemDragListener是获取不到坐标的，本库的拖拽功能是建立在ItemTouchHelper上，ItemTouchHelper也没有提供有接口获取坐标，你如果需要xy坐标的话需要重写ItemTouchHelper的`updateDxDy`方法，具体请看[https://stackoverflow.com/a/32788285/2444365](https://stackoverflow.com/a/32788285/2444365)

**Comment by huangchaoqingcheng** [comment]
长按拖曳后交换位置的时候怎么设置交换时的一个动画？
如下第一个图交换位置的时候感觉很平滑  第二个图没有设置任何效果，交换位置时候感觉很生硬，，怎么做到像第一个图那样的交换效果呢？

![true](https://user-images.githubusercontent.com/13914477/30573363-fb82141c-9d25-11e7-9b78-ff619e3b663a.gif)
![false](https://user-images.githubusercontent.com/13914477/30573372-058fb428-9d26-11e7-8da8-bb492dbd44ed.gif)

**Comment by xm2017** [comment]
> 默认不支持多个不同的 ViewType 之间进行拖拽，如果开发者有所需求：
> 
> 重写ItemDragAndSwipeCallback里的onMove()方法，return true即可

问下 4.0 版本中遇到这个问题，怎么解决？这个 api 貌似没了

**Comment by xm2017** [comment]
> > 默认不支持多个不同的 ViewType 之间进行拖拽，如果开发者有所需求：
> > 重写ItemDragAndSwipeCallback里的onMove()方法，return true即可
> 
> 问下 4.0 版本中遇到这个问题，怎么解决？这个 api 貌似没了

重写这个可以了
```
public class MutilTypeDragAndSwip extends QuickDragAndSwipe {
    @Override
    public boolean onMove(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder, @NonNull RecyclerView.ViewHolder target) {
        return true;
    }
}
```
