### ISSUE TITLE
emptyView下方会有个分隔线怎么去掉呢

### ISSUE THREAD

**Issue by Ayanokouji-Kenn** [CymChad/BaseRecyclerViewAdapterHelper#1420]
setEmptyView 其实就是在0的位置插入了一个itemView吧，
在我设置了recyclerview.addItemDecoration之后，emptyview下方会有一个自定义的分隔线，这玩意怎么去掉

**Comment by CymChad** [comment]
分割线是开发者自己设置的，emptyview本质上就是一个item。
