### ISSUE TITLE
HeaderAndFooterUseActivity

### ISSUE THREAD

**Issue by 121104115wyb** [CymChad/BaseRecyclerViewAdapterHelper#1423]
HeaderAndFooterUseActivity 中 headerAndFooterAdapter的点击事件为啥要设置新的数据，有什么我没想到的，还是大牛们，笔误

**Comment by CymChad** [comment]
这是测试是不是会出现问题，没有特殊含义。

**Comment by 121104115wyb** [comment]
今天登陆邮箱发现大神回复了，另外那个在简书中问同样问题的也是我，嘻嘻，现在明白了
