### ISSUE TITLE
某些情况下，使用rv.scrollTo()的，convert未调用

### ISSUE THREAD

**Issue by 16fangougou** [CymChad/BaseRecyclerViewAdapterHelper#1425]
例如：
数据和布局显示完毕后，我点击评论按钮滚动到评论列表（假如position为5），然后我点击当前顶部的title，滚动到页面最顶部（rv.scrollTo(0)），这个时候，position 0~4都为调用convert。稍微滑动一下下或者触摸一下屏幕才调用convert。
这个问题导致我界面显示异常。

请教一下是什么问题导致的？

目前暂时的解决办法是，滚动到顶部后，调用.notifyDataSetChanged()才正常显示。

**Comment by CymChad** [comment]
显示异常？convert本质就是onBindViewholder
