### ISSUE TITLE
[优化]BaseQuickAdapter.addData(List<T> newData)这个方法的实现里应该默认调用loadMoreComplete()

### ISSUE THREAD

**Issue by hexi** [CymChad/BaseRecyclerViewAdapterHelper#1426]
我开始以为客户端调用了这个方法之后addData(List<T> newData)，loading的状态默认会改为false，导致出现一个bug，就是调用过addData(List<T> newData)方法之后无法加载新的数据，所以建议addData(List<T> newData)这个方法的实现里应该默认调用loadMoreComplete()。

**Comment by CymChad** [comment]
loadMoreComplete方法是配合上拉使用的，但是如果不用上拉也使用addData那么其实就是多余的了，我觉得你的优化方案可以在新增一个方法就是专门给上拉使用的添加数据方法，然后在这个方法里面调用adddata和loadMoreComplete。
