### ISSUE TITLE
加载更多

### ISSUE THREAD

**Issue by cwyrzz** [CymChad/BaseRecyclerViewAdapterHelper#1429]
一页加载10条数据，当一看到第10条的item时就已经触发了加载更多，我希望的是显示加载更多的footview时才触发加载更多

**Comment by 1109993488** [comment]
如果不设置setPreLoadNumber就是在显示加载更多的时候回调加载更多

**Comment by cwyrzz** [comment]
我没有设置，也是这样，demo的PullToRefresh好像也这样，滑到第10条就弹出吐司了

**Comment by 1109993488** [comment]
现在的显示是加载更多在屏幕外面准备滑动到屏幕内时触发的

**Comment by cwyrzz** [comment]
这样子的话，如果item很高，根本看不到加载更多...

**Comment by cwyrzz** [comment]
能不能做下处理优化，让滑到加载更多再触发加载更多的事件啊？

**Comment by 1109993488** [comment]
目前还没好的解决办法，用户也不会在意没到底部就加载的

**Comment by cwyrzz** [comment]
提出的问题能不能解决一下再close




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月15日(星期二) 中午11:52
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "309107361"<309107361@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 加载更多 (#1429)




Closed #1429.

**Comment by 1109993488** [comment]
现在的做法没法做到滑动到底部，也就是加载更多底部显示回调，现在只能是加载更多头部要滑动进屏幕回调

**Comment by CymChad** [comment]
@cwyrzz  
1. 你的回复时长已经超过了5天。 
2. 你提的问题1109993488回复了你，不是所有提的新需求都会被开发的。
3. 如果你有新的问题可以重新开issues。

其实可以自己添加一个尾部，就显示加载更多，然后加载完毕后在rm掉这个尾部。
