### ISSUE TITLE
当为GridLayoutManager时header和footer不对

### ISSUE THREAD

**Issue by caiyoufei** [CymChad/BaseRecyclerViewAdapterHelper#143]
当RecyclerView设置为GridLayoutManager时，header和footer嵌入到item中去了，鸿洋哥今天发布的“Android 优雅的为RecyclerView添加HeaderView和FooterView”(http://blog.csdn.net/lmj623565791/article/details/51854533) 解决了这个问题，希望这个强大的RecyclerViewAdapter能参考一下，修复这个问题，谢谢

**Comment by CymChad** [comment]
你使用的是最新的版本吗？

**Comment by caiyoufei** [comment]
@CymChad v1.8.5 是最新的吧

**Comment by CymChad** [comment]
恩 是的

**Comment by caiyoufei** [comment]
@CymChad  我这边那样使用就会导致header和footer添加到item里面了，不会是我缺少了某个设置吧？

**Comment by CymChad** [comment]
我代码做过处理的。你要不用用  1.8.8 看看？

**Comment by CymChad** [comment]
还不行，你可以用StaggeredGridLayoutManager 也可以实现一样的效果

**Comment by caiyoufei** [comment]
嗯，StaggeredGridLayoutManager是没有问题的，就只有GridLayoutManager有那个问题

**Comment by CymChad** [comment]
我有写
 @Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
        RecyclerView.LayoutManager manager = recyclerView.getLayoutManager();
        if (manager instanceof GridLayoutManager) {
            final GridLayoutManager gridManager = ((GridLayoutManager) manager);
            gridManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    int type = getItemViewType(position);
                    return (type == EMPTY_VIEW || type == HEADER_VIEW || type == FOOTER_VIEW || type == LOADING_VIEW) ? gridManager.getSpanCount() : 1;
                }
            });
        }
    }

**Comment by CymChad** [comment]
你可以看看 #132
