### ISSUE TITLE
BaseMultiItemQuickAdapter问题

### ISSUE THREAD

**Issue by heyzhuyue** [CymChad/BaseRecyclerViewAdapterHelper#1432]
在item数据超过一屏时，onCreateDefViewHolder和convert方法只有在向下滑动时才会加载下面item，有没有方法设置一次性加载出来？

**Comment by FrankKwok** [comment]
没有显示是不会调用onBindViewHolder的

**Comment by CymChad** [comment]
这个是rv加载机制的问题。
