### ISSUE TITLE
setNotDoAnimationCount();

### ISSUE THREAD

**Issue by AIlll** [CymChad/BaseRecyclerViewAdapterHelper#1433]
为什么我设置这个没效果啊 ，想让前几个item不使用动画

**Comment by CymChad** [comment]
设置了isFirstOnly(false)？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1117

**Comment by AIlll** [comment]
没设置这个啊，设为true一样没用

**Comment by AIlll** [comment]
对，那就是了，刷新数据就失效了

**Comment by CymChad** [comment]
setNewData会重置标示，你在setNewData之后调用setNotDoAnimationCount就行了。

**Comment by dom4j1** [comment]
@CymChad  我就是在setNewData之後設置的setNotDoAnimationCount  還是不起作用啊

**Comment by wzgl5533** [comment]
应该可以的，我也这样设置的@dom4j1
