### ISSUE TITLE
多类型的问题

### ISSUE THREAD

**Issue by zhangzhikai** [CymChad/BaseRecyclerViewAdapterHelper#1434]
BaseMultiItemQuickAdapter 为什么要限制实体必须要实现MultiItemEntity？我看了源码里对于MultiItemEntity的作用就是区分不同的viewtype，getItemType()这个方法完全可以交给adapter的实现类去处理。我感觉MultiItemEntity增加了代码的耦合度，我的对象类非常不愿意去实现一个第三个的接口。因为，一般项目里的数据对象轻易不会改的，但是如果我更换了adapter，就得修改我的数据对象的实现接口，这样很不明智。以上。如有冒犯望海涵。

**Comment by CymChad** [comment]
没事，感谢你提出自己的想法。除了以上你说的做法我们还支持另外一种做法。https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/968
