### ISSUE TITLE
removeAllHeaderView();无效

### ISSUE THREAD

**Issue by zcl947694252** [CymChad/BaseRecyclerViewAdapterHelper#1435]
使用removeAllHeaderView()无法将头布局从父容器移除

**Comment by 1109993488** [comment]
请查看是否调了此方法，请具体描述，

**Comment by zcl947694252** [comment]
ProxyCommissionAdapter adapter = new ProxyCommissionAdapter(R.layout.item_proxy_commission, users);
            adapter.removeAllHeaderView( );
        adapter.addHeaderView(mHeadview);
调用 adapter.removeAllHeaderView( )后再次添加headView 仍然会报出
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by 1109993488** [comment]
如果removeAllHeader和addHeaderView一起用 需要加上notifyDataSetChanged
