### ISSUE TITLE
recyclerview 嵌套发生重叠

### ISSUE THREAD

**Issue by to686312** [CymChad/BaseRecyclerViewAdapterHelper#1440]
我是外面一个竖直的recyclerview  他的adapter（BaseQuickAdapter）,里面的子条目又有一个水平的recyclerview，并且在外面recyclerview的adapter中给里面的recyclerview设置adapter（BaseQuickAdapter）并且设置控件点击事件,我写回掉把子条目的控件点击监听写到activity中，我点击是 通过子recyclerview的adapter获取点击位置的bean对象，拍照赋值给这个bean对象，但是这个bean修改后，notifyDataSetChanged发现每个子recyclerview的数据都改了      比如我点击第一条子条目，修改bean发现其余的子条目数据都变成 我修改的bean对象    明明我只改了一个  但是显示是每个都改了

**Comment by CymChad** [comment]
你检查下数据源，adapter只是显示数据。你问题描述中提到的“明明我只改了一个 但是显示是每个都改了”，我猜测是不是数据源被你全部改了？因为我这边没有代码，只通过你的描述很难确定你的问题，只能猜测。你可以打日志调试一下。

**Comment by to686312** [comment]
我看 我在new adapter的时候传入一个集合（集合里bean对象是一个对象里面放一个集合和一个name），在外面的recyclerview的adapter中去bean对象取集合 并且设置子recyclerview的adapter作为数据，我在activity中处理子recyclerview的adapter的点击事件，拿到子adapter 通过getItem获取点击的bean对象 在修改bean   发现每个都改了

**Comment by to686312** [comment]
![_20170815122137](https://user-images.githubusercontent.com/15982492/29302160-630ed486-81b4-11e7-9b6b-450ab6e65acc.png)

![_20170815122235](https://user-images.githubusercontent.com/15982492/29302200-b1f9d7da-81b4-11e7-8ee9-25ca507d36c5.png)

![_20170815122308](https://user-images.githubusercontent.com/15982492/29302206-b6d7c8ac-81b4-11e7-8268-fd21b817690b.png)
![_20170815122354](https://user-images.githubusercontent.com/15982492/29302214-bbffe2f6-81b4-11e7-9464-1e50a15162b3.png)

**Comment by FrankKwok** [comment]
你把这部分抽取出来写个demo，上传到github，这样我们可以找到问题所在

**Comment by CymChad** [comment]
@to686312 问题解决了吗？

**Comment by to686312** [comment]
OK了   改了点东西  谢谢啊

**Comment by CymChad** [comment]
恩 搞定就好

**Comment by to686312** [comment]
谢谢啊
