### ISSUE TITLE
树形列表add了subitem后，调用notifyDataSetChanged没有更新

### ISSUE THREAD

**Issue by HeJingWei** [CymChad/BaseRecyclerViewAdapterHelper#1441]
for (int i = 0; i < detailModel.getDatalist().size(); i++) {
                                    monthModel.addSubItem(detailModel.getDatalist().get(i));
                                }
                                    mAdapter.notifyDataSetChanged();

以上代码，add进去了，但是界面没有加载进去，而是自己点了收起再展开才有新加入的数据

**Comment by CymChad** [comment]
操作数据源的同时要操作adapter的添加方法。

**Comment by HeJingWei** [comment]
没有懂，能不能代码解释一下 ：）

**Comment by HeJingWei** [comment]
adapter也需要add这个数据吗

**Comment by HeJingWei** [comment]
我用mAdapter.add进去数据源后   收起树形列表不会收回来了

**Comment by elfman** [comment]
@HeJingWei 在mAdapter里加的数据要与addSubItem里是同一个对象

**Comment by HeJingWei** [comment]
@elfman   我的确是在一个循环里去ADD的数据

**Comment by elfman** [comment]
@HeJingWei 这可能是你代码的原因了，因为有人展开后再动态加载是可以显示出来的

**Comment by HeJingWei** [comment]
我的代码就是拿到数据然后
for (int i = 0; i < detailModel.getDatalist().size(); i++) {
monthModel.addSubItem(detailModel.getDatalist().get(i));
}
mAdapter.notifyDataSetChanged();
但是界面上没有实时更新数据
如果我在for循环里把数据add到mAdapter里去，就会有多的数据和列表头在同一层

**Comment by FrankKwok** [comment]
`for (int i = 0; i < detailModel.getDatalist().size(); i++) {
monthModel.addSubItem(detailModel.getDatalist().get(i));
}
mAdapter.notifyDataSetChanged();`，数据是展开的话，这样调用是没有效果的

**Comment by xiaokun19931126** [comment]
这个可以notify某一个指定子层级的itemView吗，貌似没有这个api。我调用notifyDataSetChanged后，所有的层级都关闭了。
