### ISSUE TITLE
recyclerview 套recyclerview  adapter设置数据外面的adapter.getdata获取到的数据是原来的

### ISSUE THREAD

**Issue by to686312** [CymChad/BaseRecyclerViewAdapterHelper#1444]
里面的adapter.setdata方法设置数据   但是外面的adapter.getdata获取到的数据是原来的数据

**Comment by to686312** [comment]
在外面的recyclerview的adapter中 设置子recyclerview的adapter的setOnItemChildClickListener发现我点击其他条目获取的adapter还是上一个adapter

**Comment by FrankKwok** [comment]
你这个描述把我搞糊涂了

**Comment by to686312** [comment]
就是 外面的adapter里面初始化子adapter,同时给子adapter在convert里设置setOnItemChildClickListener监听,我自己写了一个接口 把setOnItemChildClickListener里的adapter带到外面去 (该adapter点击调用remove 发现去的条目的adapter的数据都跟着变了)

**Comment by to686312** [comment]
就是 外面的adapter里面初始化子adapter,同时给子adapter在convert里设置setOnItemChildClickListener监听,我自己写了一个接口 把setOnItemChildClickListener里的adapter带到外面去 (该adapter点击调用remove 发现其他条目的adapter的数据都跟着变了)

**Comment by CymChad** [comment]
你检查下你的数据源。每个adapter都有它自己的数据源。如果正确使用是不会出现你说的问题。
