### ISSUE TITLE
在头布局与多布局同时使用,调用adapter.remove()方法,布局出错

### ISSUE THREAD

**Issue by yangfeng1994** [CymChad/BaseRecyclerViewAdapterHelper#1445]
在头布局与多布局同时使用,调用adapter.remove()的方法去删除一种布局的item后,下面的数据会被另一种布局的item覆盖,只有再删除一条,才会出现被覆盖的那条.

**Comment by FrankKwok** [comment]
详细代码？

**Comment by CymChad** [comment]
有头部的情况下删除的时候注意position+1，头部本质上就是一个item。
