### ISSUE TITLE
报错 别人的项目就不报错

### ISSUE THREAD

**Issue by zhengxuanyi** [CymChad/BaseRecyclerViewAdapterHelper#1450]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/chad/library/adapter/base/BaseQuickAdapter;

**Comment by lhl-012** [comment]
Multiple dex files define Lcom/chad/library/adapter/base/BaseQuickAdapter;百度一下,别人的不报错因为人家只用一次，而你准备用多少次呢？2次不会有奖哦

**Comment by CymChad** [comment]
重复引用
