### ISSUE TITLE
recylerview 设置为横向时。footview 无法填充满高度

### ISSUE THREAD

**Issue by echozheng1** [CymChad/BaseRecyclerViewAdapterHelper#1451]
adapter.addFooterView(initDeptTOPfooter());//无效  
adapter.addFooterView(initDeptTOPfooter(),-1, LinearLayout.HORIZONTAL); // 同样无效

footview的布局。我无论是设置固定高度还是parent/content 都无效

**Comment by echozheng1** [comment]
View view = View.inflate(this, R.layout.footer_topdept, null); 我是这么加载尾部布局的

**Comment by echozheng1** [comment]
LayoutInflater.from(this).inflate(R.layout.footer_topdept, selectTOPrecy,false);换成这种加载布局。问题解决

**Comment by CymChad** [comment]
恩，这是开发者加载方式的问题。
