### ISSUE TITLE
已经不支持gradle了？

### ISSUE THREAD

**Issue by liuhw1988** [CymChad/BaseRecyclerViewAdapterHelper#1452]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.22' 这个版本之前还可以的，为啥现在取消掉了？

**Comment by liuhw1988** [comment]
好吧，我搞错了

**Comment by Cashdispenser** [comment]
glide怎么加载出来的，为什么我的加载不出来
SectionBean sectionBean = item.t;
String tid = sectionBean.getTid();
String preview = sectionBean.getPreview();
 Glide.with(SyxyApplication.getInstance()).load(preview).into((ImageView) helper.getView(R.id.iv_example_item));
helper.setText(R.id.tv_example_title, sectionBean.getTitle());

**Comment by Cashdispenser** [comment]
glide怎么加载出来的，为什么我的加载不出来
SectionBean sectionBean = item.t;
String tid = sectionBean.getTid();
String preview = sectionBean.getPreview();
Glide.with(mContext).load(preview).into((ImageView) helper.getView(R.id.iv_example_item));
helper.setText(R.id.tv_example_title, sectionBean.getTitle());
