### ISSUE TITLE
setNewData后为啥要强制开启loadmore

### ISSUE THREAD

**Issue by AvatarQing** [CymChad/BaseRecyclerViewAdapterHelper#1454]
我在添加过RequestLoadMoreListener后，然后setEnableLoadMore(false)了，setNewData后被强制开启了loadMore功能，能否不强制开启

**Comment by CymChad** [comment]
`setNewData`开启`loadmore`是这样的，上拉完毕后关闭`loadmore`这个时候配合下拉刷题调用`setNewData`就可以开启上拉了。
