### ISSUE TITLE
关于Scrollbar的问题，该怎么处理？

### ISSUE THREAD

**Issue by chuwe1** [CymChad/BaseRecyclerViewAdapterHelper#1455]
老哥，我添加了一个很长的Header之后当在header滑动的时候 scrollbar很短，当滑动到 下面的items的时候 scrollbar有恢复了正常 这个怎么破？

**Comment by CymChad** [comment]
有图吗？

**Comment by FrankKwok** [comment]
这个不是问题吧，微信有时候都这样
