### ISSUE TITLE
brvah，实现了像qq一样的侧侧滑删除了么？

### ISSUE THREAD

**Issue by MoreToMore** [CymChad/BaseRecyclerViewAdapterHelper#1456]
一开始这边是没有实现像qq那样的侧滑删除，但是收集的文章当中是有这份内容的，请问这中侧滑删除功能有实现么？

**Comment by Zorphling** [comment]
有侧滑啊  你下个demo看都有的

**Comment by CymChad** [comment]
有的，可以组合第三方实现，文档文末有地址。

**Comment by chinaTLJ** [comment]
> 有的，可以组合第三方实现，文档文末有地址。

没找到地址在哪里
