### ISSUE TITLE
列表倒序

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#1457]
我想让第一条数据显示到最后一个位置，就像聊天消息那样子，请问这个是对数据进行倒序呢还是怎么操作？

**Comment by guominfang** [comment]
对数组进行排序就可以了，

例子，实体Bean包含一个创建时间字段（时间戳）
```
private void sort(List<Bean> data) {
        //JDK 1.8 之前的做法
        Collections.sort(data, new Comparator<Bean>() {
            @Override
            public int compare(Bean o1, Bean o2) {
                if (o1.getCreateTime() < o2.getCreateTime())
                    return -1;
                if (o1.getCreateTime() == o2.getCreateTime())
                    return 0;
                return 1;
            }
        });
      JDK 1.8 的做法
      data.sort(new Comparator<Bean >() {
            @Override
            public int compare(Bean o1, Bean o2) {
                if (o1.getCreateTime() < o2.getCreateTime())
                    return -1;
                if (o1.getCreateTime() == o2.getCreateTime())
                    return 0;
                return 1;
            }
        });

    }
```

**Comment by BugMen** [comment]
好的，我试试，多谢！




------------------ 原始邮件 ------------------
发件人: "guominfang";<notifications@github.com>;
发送时间: 2017年8月17日(星期四) 晚上8:33
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 列表倒序 (#1457)




对数组进行排序就可以了，
 
例子，实体Bean包含一个创建时间字段（时间戳）
 private void sort(List<Bean> data) {         //JDK 1.8 之前的做法         Collections.sort(data, new Comparator<Bean>() {             @Override             public int compare(Bean o1, Bean o2) {                 if (o1.getCreateTime() < o2.getCreateTime())                     return -1;                 if (o1.getCreateTime() == o2.getCreateTime())                     return 0;                 return 1;             }         });       JDK 1.8 的做法       data.sort(new Comparator<Bean >() {             @Override             public int compare(Bean o1, Bean o2) {                 if (o1.getCreateTime() < o2.getCreateTime())                     return -1;                 if (o1.getCreateTime() == o2.getCreateTime())                     return 0;                 return 1;             }         });     }

**Comment by CymChad** [comment]
感谢 @guominfang

**Comment by Wangct23** [comment]
不是有 reverseLayout吗？

**Comment by Abvatous** [comment]
补充一下，在新的集合倒序之后，还需要调用setNewData,更新BaseQuickAdapter内部的数据源集合。
