### ISSUE TITLE
继承BaseViewHolder后,item点击事件不起作用

### ISSUE THREAD

**Issue by ParadiseHell** [CymChad/BaseRecyclerViewAdapterHelper#1459]

**Comment by ParadiseHell** [comment]
`BaseQuickAdapter.bindViewClickListener`这个方法应该变为**protected**,这样在自定义ViewHodlder后可以添加各种点击事件.
`BaseViewHolder.setAdapter`应该为**public**,源码中,`onCreateViewHolder`都执行了`setAdpater`方法.

**Comment by CymChad** [comment]
用`setOnItemClickListener`也不行？

**Comment by ParadiseHell** [comment]
肯定是设置了`setOnItemClickListener`，我因为item不是全部一样的，所以要继承`BaseViewHolder`,但是在`onCreateViewHolder`返回了不同的holder,但是这样就没法自动调用`bindViewClickListener`方法了，所以设置了也没用，最后我手动调用了这段代码才起作用的。

`if (getOnItemClickListener() != null) {
            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    getOnItemClickListener().onItemClick(BaseQuickAdapter.this, v, baseViewHolder.getLayoutPosition() - getHeaderLayoutCount());
                }
            });
        }
        if (getOnItemLongClickListener() != null) {
            view.setOnLongClickListener(new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    return getOnItemLongClickListener().onItemLongClick(BaseQuickAdapter.this, v, baseViewHolder.getLayoutPosition() - getHeaderLayoutCount());
                }
            });
        }`

**Comment by AllenCoder** [comment]
![image](https://user-images.githubusercontent.com/8213915/29502758-f0580ace-8664-11e7-93d7-f99642671171.png)
bindViewClickListener 的代码在不是特殊的布局，头布局和底部布局时都会自动默认绑定

但是绑定时会去检查用户是否设置了 listener 

![image](https://user-images.githubusercontent.com/8213915/29502797-3b7e71dc-8665-11e7-967b-7c589d12d8ec.png)
所以 demo里面的设置listener都是紧跟在adapter 之后就立即设置的 
![image](https://user-images.githubusercontent.com/8213915/29502829-6f5692a0-8665-11e7-9995-7746bfaf3342.png)

所以，检查一下，你的设置listener方法是否写在了耗时的获取数据之后，导致adapter检查是否设置listener时 还未及时设置listener

**Comment by CymChad** [comment]
1.自定义viewholder不需要你重写onCreateViewHolder。
2.如果你重写了onCreateViewHolder那么肯定会出问题的，因为base的onCreateViewHolder里面做了很多处理。
