### ISSUE TITLE
关于嵌套ScrollView，不响应loadmore事件

### ISSUE THREAD

**Issue by liulance** [CymChad/BaseRecyclerViewAdapterHelper#1460]
大佬，如题，我用ScrollView嵌套rv,adapter不能响应loadmore事件了，应该怎么处理呢？
谢谢

**Comment by BugMen** [comment]
不要用嵌套，因为会屏蔽RV的滑动事件

**Comment by liulance** [comment]
@BugMen 能怎么处理下么？

**Comment by BugMen** [comment]
就是尽量避免这两个控件的嵌套啊，官方也是不建议嵌套的，不过你可以试下用MD中的CoordinatorLayout + AppBarLayout + CollapsingToolbarLayout布局方式看看能不能解决




------------------ 原始邮件 ------------------
发件人: "liu";<notifications@github.com>;
发送时间: 2017年8月18日(星期五) 下午5:11
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 关于嵌套ScrollView，不响应loadmore事件 (#1460)




@BugMen 能怎么处理下么？

**Comment by FrankKwok** [comment]
@BugMen 正解,  @liulance 建议使用添加header或footer的方式把其他部分的页面嵌到RV中
