### ISSUE TITLE
BaseMultiItemQuickAdapter  多布局折叠问题

### ISSUE THREAD

**Issue by Songshuangpeng** [CymChad/BaseRecyclerViewAdapterHelper#1461]
大佬你好 我用BaseMultiItemQuickAdapter实现多布局时,先是请求接口得到父布局的数据,if (null != mGroupData) {
for (RWisdomGroup one : mGroupData) {
MultiItemEntity one1 = one;
if (null != mChildItemData) {
for (RTradeItem two : mChildItemData) {
one.addSubItem(two);
}
}
itemEntities.add(one1);
}
return itemEntities;
}
这时候mchildData数据是null，上面遍历完成后给adapter设置数据，父布局正确展示，当点击父布局时在请求子布局数据接口，得到数据后通过适配器的addData方法添加数据，子布局也正确展示，当再次点击相同的父布局时adapter的isExpanded方法仍然返回false，导致无法折叠

这个布局的折叠和展开功能 父布局和子布局的数据必须同时有值吗？

**Comment by CymChad** [comment]
子布局没有数据展开就关闭就没有意义。

**Comment by CymChad** [comment]
你可以参考下demo和测试一下demo。

**Comment by CymChad** [comment]
> 这个布局的折叠和展开功能 父布局和子布局的数据必须同时有值吗？

我刚才测试了一下是的，如果没有值点击不会改变状态。
