### ISSUE TITLE
列表很卡顿

### ISSUE THREAD

**Issue by wqandroid** [CymChad/BaseRecyclerViewAdapterHelper#1463]
我的列表有头像。图片。文字等一些东西。当加载100条数据之后，滑动卡顿很明显。后台一直有gc的log。但是之前用 listview，是没有任何问题的

**Comment by BugMen** [comment]
有没有在外层嵌套scrollview，还有，布局的层级也别太深，这些原因都会导致卡顿的

**Comment by wqandroid** [comment]
这些我肯定知道。布局也就三四层嵌套！你们没有做过这些测试吗？

**Comment by CymChad** [comment]
demo中有较复杂的嵌套rv，并没有什么问题。
