### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by niezhiyang** [CymChad/BaseRecyclerViewAdapterHelper#1467]
发现个bug 就是item里面有checkbox的时候,当在convert中拿到这个checkbox
并且设置setOnCheckedChangeListener这个的时候 ,会出现乱的数据,可能是item复用的问题吧

**Comment by FrankKwok** [comment]
想要实现怎样的效果，实现代码是怎样的，能发吗？

**Comment by niezhiyang** [comment]
CheckBox checkB = (CheckBox) baseViewHolder.getView(R.id.cb_item_music_all_issave);
        if (item.isChecked) {
            checkB.setChecked(true);
        }
        checkB.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
                if (b) {//如果选中就存起来
                } else {
                    //如果从选中到位选中 就删除
                } 
            }
        });

**Comment by CymChad** [comment]
你的isChecked的状态需要存放起来。在每一个entity里面。具体你可以看下http://www.jianshu.com/p/b343fcff51b0  文档 有相关的demo
