### ISSUE TITLE
给适配器添加自定义的空内容布局的问题

### ISSUE THREAD

**Issue by feer921** [CymChad/BaseRecyclerViewAdapterHelper#147]
给适配器添加自定义的空内容布局的问题后，再去请求网络并有数据返回，这时把数据设置进适配器，会报视图解析时的下标越界问题，具体Log信息再贴出来

**Comment by CymChad** [comment]
是最新的版本吗？

**Comment by CymChad** [comment]
最好能给出具体代码，和crash log。
