### ISSUE TITLE
分组收缩里嵌套recyclerview的点击事件不响应

### ISSUE THREAD

**Issue by CocoForAndroid** [CymChad/BaseRecyclerViewAdapterHelper#1470]
### 代码如下：
    ` protected void convert(final BaseViewHolder baseViewHolder, final MultiItemEntity multiItemEntity) {
        switch (baseViewHolder.getItemViewType()) {
            case TYPE_PARENT:
                final ParentItem item = (ParentItem) multiItemEntity;
                baseViewHolder.setText(R.id.parent_name_tv, item.getName());
                final ImageView iv = baseViewHolder.getView(R.id.parent_down_up_iv);
                final TextView tvTitle = baseViewHolder.getView(R.id.parent_name_tv);
                //点击展开收缩
                baseViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        int pos = baseViewHolder.getAdapterPosition();
                        if (item.isExpanded()) {
                            collapse(pos);
                        } else {
                            expand(pos);
                        }
                    }
                });
                if (item.isExpanded()) {
                    tvTitle.setTextColor(ContextCompat.getColor(mContext, R.color.bottom_press_color));
                    iv.setBackgroundResource(R.drawable.uparrow);
                } else {
                    tvTitle.setTextColor(ContextCompat.getColor(mContext, R.color.menuColor));
                    iv.setBackgroundResource(R.drawable.downarrow);
                }

                break;
            case TYPE_CHILD:
                final ChildItem childItem = (ChildItem) multiItemEntity;
                RecyclerView recyclerView = baseViewHolder.getView(R.id.child_rcv);
                recyclerView.setLayoutManager(new LinearLayoutManager(mContext));
                List<ChildLv0Item> childLv0Items = childItem.getChildLv0Items();
                ChildAdapter childAdapter = new ChildAdapter(R.layout.item_type_child0, childLv0Items);
                recyclerView.setHasFixedSize(true);
                recyclerView.setAdapter(childAdapter);

                baseViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        Log.d("child_view", "onClick: child click");
                    }
                });

                break;

        }
     private class ChildAdapter extends BaseQuickAdapter<ChildLv0Item, BaseViewHolder> {

        ChildAdapter(@LayoutRes int layoutResId, @Nullable List<ChildLv0Item> data) {
            super(layoutResId, data);
        }

        @Override
        protected void convert(BaseViewHolder baseViewHolder, ChildLv0Item childLv0Item) {
            baseViewHolder.setText(R.id.child_title_tv, childLv0Item.getTitle())
                    .setText(R.id.child_content_tv, childLv0Item.getContent());

        }
    }
    }`

**Comment by CymChad** [comment]
你应该用childAdapter设置点击事件吧？

**Comment by CymChad** [comment]
我看你的代码设置的点击事件只是item的，不是子item的。item是rv，子item才是被嵌套rv的item，所以你要设置childAdapter的点击事件。
