### ISSUE TITLE
recyclerView嵌套在NestedScrollView中，导致adapter自动调用loadMore

### ISSUE THREAD

**Issue by chengxiaorun** [CymChad/BaseRecyclerViewAdapterHelper#1472]
好像是recyclerView抢夺焦点引起，recyclerView没有滚动但是一直在加载数据，没显示的item图片也被加载了。然后还调用到了loadMore，无限刷新，直到最后一页，求解

**Comment by FreeLoopC** [comment]
@chengxiaorun 我也出现了这个问题, 你是怎么解决的
