### ISSUE TITLE
添加加载更多监听,会不停调用onLoadMoreRequested方法

### ISSUE THREAD

**Issue by itdais** [CymChad/BaseRecyclerViewAdapterHelper#1473]
adapter设置setOnLoadMoreListener,
当加载到底部后会不停调用BaseQuickAdapter.RequestLoadMoreListener的onLoadMoreRequested
是否应该是当调用loadMoreComplete()  loadMoreFail()或者loadMoreEnd()方法后再次拉起是调用

**Comment by CymChad** [comment]
加载数据成功后还有下一页调用`loadMoreComplete()`，加载结束调用`loadMoreEnd()`，加载失败调用 `loadMoreFail()`。具体使用你可以看demo代码和文档http://www.jianshu.com/p/b343fcff51b0
