### ISSUE TITLE
列表不满一页的时候 会重复多次执行onLoadMoreRequested

### ISSUE THREAD

**Issue by pricnehao** [CymChad/BaseRecyclerViewAdapterHelper#1476]
列表不满一页的时候  会重复多次执行onLoadMoreRequested    如何请求成功之后   不上拉不进行加载更多 ？ 
 而且碰到没有分页的列表 如果不满一页 会一直请求  请问如何解决？

**Comment by CymChad** [comment]
你可以在callback里面判断是否满足一样然后调用加载完毕的方法即可。
