### ISSUE TITLE
添加自定义header，包含viewpager为什么无法显示

### ISSUE THREAD

**Issue by hhcchhcc12** [CymChad/BaseRecyclerViewAdapterHelper#1477]
myAdapter.addHeaderView(headerView);
这样添加了一个header，headerView是一个viewpager，但是显示不出来。

**Comment by Rianney** [comment]
所以是为什么呢老哥 我的viewPager也显示不出来

**Comment by Jiawei1994** [comment]
你好，有没有什么方法可以解决，我现在是Item 里放入了一个Viewpager，第一个fragment显示没有问题，但是切换到第二页viewpager 就不显示了，没有找到是什么原因造成的。
