### ISSUE TITLE
BaseMultiItemQuickAdapter with Swipe functionality

### ISSUE THREAD

**Issue by carmas123** [CymChad/BaseRecyclerViewAdapterHelper#1481]
Hi all, how can I implement BaseMultiItemQuickAdapter with swipe functionality?
I see the example with BaseItemDraggableAdapter but it inherit from BaseQuickAdapter and not from BaseMultiItemQuickAdapter.

Regards

**Comment by CymChad** [comment]
Copy BaseItemDraggableAdapter code combination.

**Comment by carmas123** [comment]
I don't understand what I need?

**Comment by CymChad** [comment]
BaseItemDraggableAdapter copy to BaseMultiItemQuickAdapter derived classes

**Comment by carmas123** [comment]
But this intend that I need to create my custom class derived from BaseItemDraggableAdapter ?

**Comment by CymChad** [comment]
Don't need，Only copy BaseItemDraggableAdapter core code to your class.

**Comment by carmas123** [comment]
ok thank you I try it

**Comment by CymChad** [comment]
Thank you for your use
