### ISSUE TITLE
item里添加内容判断后, 滑动屏幕后, 出现内容错位的问题(已解决, 但是我不会撤销, 大神请忽略这个issue)

### ISSUE THREAD

**Issue by heavenyu4** [CymChad/BaseRecyclerViewAdapterHelper#1483]
前面的CardView 还有数据, 最后几项的CardView 没有数据, 再滑上来的时候, 前面有数据的都没了, 请问这个怎么办? 我说清楚了吗? 这个怎么上传截屏或视频呢?

**适配器如下**
public class DeviceListAdapter extends BaseQuickAdapter<DeviceListBean, BaseViewHolder> {
    Context context;

    public DeviceListAdapter(Context context, @Nullable List<DeviceListBean> data) {
        super(R.layout.item_device_list, data);
        this.context = context;
    }

    @Override
    protected void convert(BaseViewHolder helper, DeviceListBean item) {
        helper.setText(R.id.tv_name, item.getName());
        helper.setText(R.id.tv_section, item.getSection());
        helper.setText(R.id.tv_device_status, item.getDeviceStatusLabel());
        helper.setText(R.id.tv_fault_status, item.getFaultStatusLabel());

        CardView cardView_device_status = helper.getView(R.id.cardview_device_status);
        switch (item.getDeviceStatus()) {
            case "0":  
                cardView_device_status.setBackgroundColor(0xFF00796b);
                break;
            case "1":  
                cardView_device_status.setBackgroundColor(0xFFf6412d);
                break;
            case "2":
                cardView_device_status.setBackgroundColor(0xFFff9900);
                break;
            default:
                helper.setVisible(R.id.cardview_device_status, false);
                break;
        }
    

    }
}

**数据如下**
 for (int i = 0; i < 40; i++) {

            DeviceListBean bean = new DeviceListBean();
            bean.setName("test"+i);
            bean.setDeviceStatus(i%3+"");
            bean.setDeviceStatusLabel(i%3+"");
            data.add(bean);
        }
        for (int i = 0; i < 20; i++) {

            DeviceListBean bean = new DeviceListBean();
            bean.setName("test"+40+i);
            data.add(bean);
        }
        adapter = new DeviceListAdapter(this, data);
        recyclerView.setLayoutManager(new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false));
        recyclerView.setAdapter(adapter);

**layout**

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="60dp"
    android:background="@color/colorPrimary">

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_marginLeft="@dimen/padding_normal"
        android:layout_marginRight="@dimen/spacing_normal"
        android:gravity="center_vertical"
        android:orientation="vertical">

        <TextView
            android:id="@+id/tv_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:lines="1"
            android:maxLines="1"
            android:text=""
            android:textColor="@color/colorTextPrimary"
            android:textSize="@dimen/app_text_size_regular" />

        <TextView
            android:id="@+id/tv_section"
            style="@style/second_text"
            android:drawableLeft="@drawable/keshi_location"
            android:drawablePadding="4dp"
            android:text="" />

    </LinearLayout>

    <ImageView
        android:id="@+id/iv_arrow"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_centerVertical="true"
        android:layout_marginRight="@dimen/padding_normal"
        android:src="@drawable/item_arrow_right" />

    <LinearLayout
        android:id="@+id/ll_state"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_marginRight="15dp"
        android:gravity="center_vertical|right"
        android:orientation="vertical"
        android:layout_alignParentTop="true"
        android:layout_toLeftOf="@+id/iv_arrow"
        android:layout_toStartOf="@+id/iv_arrow"
        android:layout_marginEnd="15dp">

        <android.support.v7.widget.CardView
            android:id="@+id/cardview_device_status"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:cardBackgroundColor="#00796b"
            app:cardCornerRadius="2dp"
            app:cardElevation="0dp">

            <TextView
                android:id="@+id/tv_device_status"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:gravity="center"
                android:lines="1"
                android:maxLines="1"
                android:paddingLeft="5dp"
                android:paddingRight="5dp"
                android:text=""
                android:textColor="@color/white"
                android:textSize="12sp" />

        </android.support.v7.widget.CardView>

        <TextView
            android:id="@+id/tv_fault_status"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/spacing_micro"
            android:text=""
            android:lines="1"
            android:maxLines="1"
            android:textColor="@color/result_normal"
            android:textSize="@dimen/app_text_size_medium" />

    </LinearLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:layout_alignParentBottom="true"
        android:background="@color/colorTextSecondary" />

    <View
        android:layout_width="5dp"
        android:layout_height="match_parent"
        android:background="@color/item_index" />
</RelativeLayout>

**Comment by FrankKwok** [comment]
直接close这个issue就好了

**Comment by jingbolee** [comment]
请问下 @heavenyu4 , 滑动以后，有些数据显示为空白的问题，你是怎么处理的。

**Comment by heavenyu4** [comment]
@jingbolee 适配器里不是有这句吗？
 helper.setVisible(R.id.cardview_device_status, false);
等到滑上去的时候， viewholder不是缓存重复利用的嘛， 那这个不可见不就留下来了吗，我说明白了吗？
把这句去掉就可以了
