### ISSUE TITLE
关于加载更多问题

### ISSUE THREAD

**Issue by gyyak46** [CymChad/BaseRecyclerViewAdapterHelper#1484]
在adapter.setOnLoadMoreListener()外面调用 loadMoreEnd()这个方法  不起作用

**Comment by gyyak46** [comment]
使用的库是2.9.19

**Comment by CymChad** [comment]
调用玩loadMoreEnd之后你还调用了其他方法吗？如果你还调用了loadMoreComplete那就又会被开启，所以你先检查下调用玩loadMoreEnd只会是否还调用了其他方法。
