### ISSUE TITLE
建议加上防重复点击

### ISSUE THREAD

**Issue by XXiaoQing** [CymChad/BaseRecyclerViewAdapterHelper#1486]
item 的点击事件，如快速点击，会出现相同的 2 个界面，意见加上防止重复点击的功能

**Comment by Troll4it** [comment]
你的用的是rv引出的点击事件吧，你用adapter.setOnItemClickListener就不会，你可以试下

**Comment by CymChad** [comment]
正解，推荐使用setOnItemClickListener
