### ISSUE TITLE
BaseQuickAdapter的remove()方法报错

### ISSUE THREAD

**Issue by andy91310** [CymChad/BaseRecyclerViewAdapterHelper#1490]
![image](https://user-images.githubusercontent.com/10116442/29714200-ae811dc0-89d4-11e7-88ad-61ada49b1661.png)

**Comment by CymChad** [comment]
触发场景？

**Comment by FrankKwok** [comment]
这个是List的错误，你存放数据的List是哪种类型？

**Comment by andy91310** [comment]
String类型

**Comment by CymChad** [comment]
版本号是？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/641  我查了下历史issues，这个是旧版本的问题，你更新一下版本应该就好了，如果你还有问题可以重新开一个issues。

**Comment by andy91310** [comment]
2.9.28的版本呢。

**Comment by CymChad** [comment]
2.9.28？你有没有添加头部或者尾部之类的？

**Comment by CymChad** [comment]
我使用最新版本测试了4种情况都没有出现你说的问题
1.添加头部和尾部，删除所有。
2.添加头部，删除所有。
3.添加尾部，删除所有。
4.无添加，删除所有。

建议你检查下代码，你也可以修改demo上面的测试代码试试。
