### ISSUE TITLE
关于嵌套的问题.

### ISSUE THREAD

**Issue by eclipse4dk** [CymChad/BaseRecyclerViewAdapterHelper#1491]
我的布局时一个NestedScrollview里面有多个RecyclerView:
1.recyclerview设置高度wrap_content之后,里面的条目有的时候加载出一部分,有的时候全部可以加载出来,有的时候一条都不加载,我设置高度为一个较大的固定值之后,发现都显示出来了,应该是加载过程中,还没有完全算出recyclerview的高度就执行完毕了.因为数据的size是不固定的,所以高度必须wrap_content,不知该如何解决.
2.某一个recyclerview里面的子条目是上方一个Imageview,下方一个横向滚动的recyclerview,高度自适应也有问题.而且横向滚动的recyclerview里面的条目图片能够正常加载,但下面的两个textview无法加载出来.使用显示布局边界发现有展示两个textview,但数据没有加载.

**Comment by CymChad** [comment]
这个和adapter有什么关系？

**Comment by eclipse4dk** [comment]
不好意思,我关了.是我自己的原因.
