### ISSUE TITLE
setVisible的行为变了

### ISSUE THREAD

**Issue by pye52** [CymChad/BaseRecyclerViewAdapterHelper#1493]
从27升到28之后，发现布局变得诡异了，突然多了一块空白出来
看了一下发现有个PR，将setVisible修改为传入false时view设置为invisible
原来的api改名为setGone
这就很尴尬了…这个API在版本前后的行为不一致，如果要升级的话不少地方都需要修改过来
希望能谨慎修改api，例如这种情况下新增一个setInvisible的方法而不改动原有方法不是更好吗

**Comment by andy91310** [comment]
我也遇到这个问题，最后还是用了原生的

**Comment by CymChad** [comment]
恩，好的，我的疏忽，给你们带来了不便十分抱歉。我后续会改过来的。

**Comment by CymChad** [comment]
1.下次合并我会更加注意api的修改对现有用户的影响。
2.这次修改我新增了修改日志。

感谢提醒。
