### ISSUE TITLE
莫名其妙的会出来空指针

### ISSUE THREAD

**Issue by everyline** [CymChad/BaseRecyclerViewAdapterHelper#1494]
![default](https://user-images.githubusercontent.com/8476579/29767526-544c7c1c-8c15-11e7-95a0-0982ea08f327.png)

**Comment by FrankKwok** [comment]
版本？

**Comment by everyline** [comment]
2.9.25

**Comment by FrankKwok** [comment]
暂时从代码里看不到问题。。。

**Comment by FrankKwok** [comment]
换成最新版试试？

**Comment by everyline** [comment]
我先去试试吧   我也找不到具体报错的地方

**Comment by CymChad** [comment]
新版本已修复这个bug。
