### ISSUE TITLE
BaseMultiItemQuickAdapter 模仿expandablelistview 出现数据显示不完全

### ISSUE THREAD

**Issue by androidengineer** [CymChad/BaseRecyclerViewAdapterHelper#1496]
使用BaseMultiItemQuickAdapter时，使用handler每次发送一条数据，添加MultiItemEntity-->添加subItem循环的添加，但是每个总条目只会显示一条subItem。打印Log日志，数据正常添加，但是item数量始终为外层列表数量*2，也就是说每个数据源只添加了一个subItem。代码如下：
 private int groupPosition = 0, childPosition = -1;
if (groupPosition < blocks.size()) {
            //添加title
            if (childPosition == -1) {
                L.e("添加title" + groupPosition);
                mActivity.mLessonAdaper.getData().add(blocks.get(groupPosition));
                //有item才加一
                if (!CollectionUtil.collectionIsEmpty(blocks.get(groupPosition).getElements())) {
                    childPosition = 0;
                } else {
                    groupPosition += 1;
                }
            } else {
                //可以添加item
                blocks.get(groupPosition).addSubItem(blocks.get(groupPosition).getElements().get(
                        childPosition));
                if (childPosition == blocks.get(groupPosition).getElements().size() - 1) {
                    //最后一条
                    groupPosition += 1;
                    childPosition = -1;
                } else {
                    childPosition += 1;
                }
            }
          mActivity.mLessonAdaper.expandAll();
            mActivity.mLessonAdaper.notifyDataSetChanged();
            binding.elvList.smoothScrollToPosition(Integer.MAX_VALUE);
            BwApplication.getHandler().postDelayed(this, 500);
        } else {
            BwApplication.getHandler().removeCallbacks(this);
        }

**Comment by everyline** [comment]
你写的逻辑不对

**Comment by androidengineer** [comment]
@everyline 哪里不对？刷新UI还是数据加入？

**Comment by CymChad** [comment]
具体可参考demo源码

**Comment by CymChad** [comment]
demo中就有BaseMultiItemQuickAdapter写出来的expandablelistview效果。
