### ISSUE TITLE
关于多类型布局时的默认布局

### ISSUE THREAD

**Issue by wimvogt** [CymChad/BaseRecyclerViewAdapterHelper#1497]
你好，有个问题请教下，在继承BaseMultiItemQuickAdapter的adapter的初始化中，如何添加默认布局类型，比如说我添加了几种类型，1、2、3、4，但是数据类型有可能是5，6，7，8，那不支持的类型都使用默认布局

**Comment by CymChad** [comment]
那你可以在gettype里面重写的规则写死5，6，7，8，都是默认类型。

**Comment by CymChad** [comment]
本质上每一个布局的显示都是跟进type来绑定到layout的，那么其实你可以通过改变实体类的type来实现你的需求，如：1、2、3、4、都是对应的layout，这个没问题，那么你可以type等于5、6、7、8、时同时映射成一个默认布局的type假设他是10。这样就可以做到5、6、7、8、都指向10这个布局了。

**Comment by wimvogt** [comment]
这有点困难，因为不支持的个数是不确定的，这些类型是后台可以自定义的，能确定的是支持的类型和个数，其它的都是不支持的，数量太大了
