### ISSUE TITLE
MultiItemEntity 类结构变更

### ISSUE THREAD

**Issue by mavenjan** [CymChad/BaseRecyclerViewAdapterHelper#1498]
之前就有star该项目，当时没有采用。最近在学习别的demo的时候有用到v1.8.5版本的BRHV。其中MultiItemEntity类结构和BaseQuickAdapter的方法都有变更

int currentPosition = getViewHolderPosition(baseViewHolder);   该方法失效

channel.setItemType(Channel.TYPE_OTHER_CHANNEL);   //该方法失效
老版本的MultiItemEntity 实体类   
public abstract class MultiItemEntity {
    protected int itemType;
    public MultiItemEntity() {
    }
    public int getItemType() {
        return this.itemType;
    }
    public void setItemType(int itemType) {
        this.itemType = itemType;
    }
}
求大神指导意见，我应该怎么兼容最新的BHRV版本

**Comment by CymChad** [comment]
`public class MultipleItem implements MultiItemEntity {`
把继承改成实现，然后重写getItemType就好了。
如果你还要setItemType的话，你可以也自己写一个。
当前的position可以通过viewholder.getlayoutposition即可。

**Comment by mavenjan** [comment]
谢谢指导
