### ISSUE TITLE
加载失败，请点我重试

### ISSUE THREAD

**Issue by dumaokun** [CymChad/BaseRecyclerViewAdapterHelper#1499]
版本号：2.9.22
问题描述及复现：给的demo中，Pull ToRefresh Use这个模块中，第一次加载失败，底部会有“加载失败，请点我重试”，然后我点击时，出现“正在加载中...”但是会覆盖在“加载失败，请点我重试”之上
所用手机：红米NOTE 4X

不知道我的问题描述清楚没。

**Comment by 1109993488** [comment]
#838
