### ISSUE TITLE
 Caused by: java.lang.RuntimeException: please bind recyclerView first!

### ISSUE THREAD

**Issue by twimsos** [CymChad/BaseRecyclerViewAdapterHelper#1500]
quickAdapter = new QuickAdapter();
        quickAdapter.setEmptyView(R.layout.emptyview);//添加此行后。报错误
        quickAdapter.openLoadAnimation(BaseQuickAdapter.SCALEIN);
        quickAdapter.isFirstOnly(false);
        recyclerView.setAdapter(quickAdapter);
R.layout.emptyview：
`<?xml version="1.0" encoding="utf-8"?>
<TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:text="没有此类数据~~~"
    android:gravity="center"
    />`

当添加EmptyView时，报错信息： Caused by: java.lang.RuntimeException: please bind recyclerView first!
代码指向上面：quickAdapter.setEmptyView(R.layout.emptyview);
删除时的确不报错，请问我是哪里整错了？谢谢~~

**Comment by CymChad** [comment]
1.quickAdapter.setEmptyView(R.layout.emptyview); 需要你adapter.bindr....方法。
2.如果你不想bind那么可以用quickAdapter.setEmptyView(R.layout.emptyview，rv);这个重载方法。
