### ISSUE TITLE
item和item子控件的长按事件在抬起手时会多触发一次点击事件

### ISSUE THREAD

**Issue by sutingshuai** [CymChad/BaseRecyclerViewAdapterHelper#1501]
在设置
adapter中：
   @Override
    protected void convert(BaseViewHolder helper, Birds item) {
        helper.setText(R.id.tv_rv_BirdName, item.getName())
                .setText(R.id.tv_rv_BirdCountry, item.getName())
                .setText(R.id.tv_rv_BirdId, item.getId()+ "")
                .addOnLongClickListener(R.id.iv_rv_BirdImage)
                .addOnClickListener(R.id.iv_rv_BirdImage);
        Glide.with(mContext).load(item.getImageUrl()).apply(GlideRequestOptions.getDefaultRequestOptions().transform(new CircleCrop())).into((ImageView) helper.getView(R.id.iv_rv_BirdImage));
    }

MainActivity中：
  adapter2.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Log.e("MainActivity", "OnItemClickListener" + list.get(position) + "\nposition = " + position );
            }
        });
        adapter2.setOnItemLongClickListener(new BaseQuickAdapter.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(BaseQuickAdapter adapter, View view, int position) {
                Log.e("MainActivity", "OnItemLongClickListener" + list.get(position) + "\nposition = " + position );
                return false;
            }
        });
        adapter2.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                switch (view.getId()){
                    case R.id.iv_rv_BirdImage:
                        Log.e("MainActivity", "OnItemChildClickListener" + list.get(position).getImageUrl() + "\nposition = " + position );
                        break;
                }
            }
        });
        adapter2.setOnItemChildLongClickListener(new BaseQuickAdapter.OnItemChildLongClickListener() {
            @Override
            public boolean onItemChildLongClick(BaseQuickAdapter adapter, View view, int position) {
                switch (view.getId()){
                    case R.id.iv_rv_BirdImage:
                        Log.e("MainActivity", "OnItemChildLongClickListener" + list.get(position).getImageUrl() + "\nposition = " + position );
                        break;
                }
                return false;
            }
        });

大神我发现一个bug：版本号2.9.28，在使用时设置item和item的子控件的长按事件会触发一次长按事件后手抬起来时又触发一次点击事件。对于item和item的子控件都是这样。

版本号是：compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.28'

请修改一下这里的bug！我也在简书里评论了。

**Comment by AllenCoder** [comment]
```
adapter2.setOnItemChildLongClickListener(new BaseQuickAdapter.OnItemChildLongClickListener() {
@override
public boolean onItemChildLongClick(BaseQuickAdapter adapter, View view, int position) {
switch (view.getId()){
case R.id.iv_rv_BirdImage:
Log.e("MainActivity", "OnItemChildLongClickListener" + list.get(position).getImageUrl() + "\nposition = " + position );
break;
}
return true;
}
```
你的
return false; 修改为return true ; 
消费掉长按事件才会不继续分发点击事件

**Comment by dary123** [comment]
> ```
> adapter2.setOnItemChildLongClickListener(new BaseQuickAdapter.OnItemChildLongClickListener() {
> @override
> public boolean onItemChildLongClick(BaseQuickAdapter adapter, View view, int position) {
> switch (view.getId()){
> case R.id.iv_rv_BirdImage:
> Log.e("MainActivity", "OnItemChildLongClickListener" + list.get(position).getImageUrl() + "\nposition = " + position );
> break;
> }
> return true;
> }
> ```
> 
> 你的 setOnItemChildLongClickListener
> return false; 修改为return true ;
> 消费掉长按事件才会不继续分发点击事件

已经return true为啥还是不行
