### ISSUE TITLE
关于空布局

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#1503]
我想知道，空布局的设置除了可以设置数据为空的情况，还可以设置第一次加载以及网络错误的情况吗？

**Comment by CymChad** [comment]
你可以看下demo，有告诉你如何切换空布局的案例。

**Comment by BugMen** [comment]
哎呀，没好好看Demo我的错，谢谢！






------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年8月30日(星期三) 下午4:50
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 关于空布局 (#1503)




你可以看下demo，有告诉你如何切换空布局的案例。
