### ISSUE TITLE
数据不满一页底部显示问题

### ISSUE THREAD

**Issue by yangzhenqi** [CymChad/BaseRecyclerViewAdapterHelper#1504]
如果不满一页不需要加载更多，所以我使用了`disableLoadMoreIfNotFullPage()`。
但是当我在`onLoadMoreRequested()`外调用`loadMoreEnd()`，底部自定义的`LoadMoreView` 无更多数据 不显示

**Comment by 1109993488** [comment]
调用了disableLoadMoreIfNotFullPage这个，如果不满一屏幕的时候调loadMoreEnd会不起作用，建议不加disableLoadMoreIfNotFullPage，自己再下拉跟上拉里面判断数量是否够一页，不够一页就掉loadMoreEnd，如果够了就掉loadMoreComplete

**Comment by yangzhenqi** [comment]
我在进入界面的时候，第一次加载数据没有写在`onLoadMoreRequested()`里  所以才用了`disableLoadMoreIfNotFullPage()`。这样的话第一次加载数据是需要写在`onLoadMoreRequested()`里么

**Comment by 1109993488** [comment]
```
    public void onRefreshSuccess(List list){
        adapter.setNewData(list);
        checkLoadMore(list);
    }
    
    public void onLoadMoreSuccess(List list){
        adapter.addAllData(list);
        checkLoadMore(list);
    }
    
    public void checkLoadMore(List list){
        if(list<一页){
            adapter.loadMoreEnd();
        }else {
            adapter.loadMoreComplete();
        }
    }
```
