### ISSUE TITLE
多布局中删除子布局问题

### ISSUE THREAD

**Issue by wardenlzr** [CymChad/BaseRecyclerViewAdapterHelper#1505]
第一次删除时正常，第二次删除时protected void convert(final BaseViewHolder holder,final MultiItemEntity item)方法中返回的item 是第一次删除的item  因此报如下错：
java.lang.ArrayIndexOutOfBoundsException: length=21; index=-1
                                                                            at java.util.ArrayList.get(ArrayList.java:310)
                                                                            at com.tengdi.investigate.adapter.IssueAdapter$2$1.onClick(IssueAdapter.java:83)
                                                                            at android.view.View.performClick(View.java:4780)
                                                                            at android.view.View$PerformClick.run(View.java:19866)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

我的adapter代码如下：
public class IssueAdapter extends BaseMultiItemQuickAdapter<MultiItemEntity, BaseViewHolder> {

    public static final int TYPE_TITLE = 0;
    public static final int TYPE_CONTENT = 1;
    private BaseActivity mActivity;
    private List<String> removeIds = new ArrayList<>();//删除的问答的ID
    private WeDialog weDialog = null;

    public IssueAdapter(BaseActivity activity,@Nullable List<MultiItemEntity> data) {
        super(data);
        mActivity = activity;
        addItemType(TYPE_TITLE, R.layout.issue_title_item);
        addItemType(TYPE_CONTENT, R.layout.issue_item);
    }

    public List<String> getRemoveIds(){
        return removeIds;
    }
    @Override
    protected void convert(final BaseViewHolder holder,final MultiItemEntity item) {
        switch (holder.getItemViewType()) {
            case TYPE_TITLE:
                final IssueTitleBean titleBean = (IssueTitleBean) item;
                holder.setText(R.id.tv_item_title, ((IssueTitleBean) item).getTitle())
                        .addOnClickListener(R.id.tv_add);
                holder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        int pos = holder.getAdapterPosition();
                        if (titleBean.isExpanded()) {
                            collapse(pos);
                        } else {
                            expand(pos);
                        }
                    }
                });
                break;
            case TYPE_CONTENT:
//                int position = holder.getAdapterPosition();
                final IssueBean.MessageBean bean = (IssueBean.MessageBean) item;
                holder//.setText(R.id.tv_ask_number, position + ".问：")
                        .setText(R.id.et_ask, bean.getText())
                        .setText(R.id.et_answer, bean.getAnswer())
                        .setTypeface(R.id.tv_ask_number,mActivity.iconfont)
                        .setTypeface(R.id.tv_answer,mActivity.iconfont)
                        ;
                holder.itemView.setOnLongClickListener(new View.OnLongClickListener() {
                    @Override
                    public boolean onLongClick(View v) {
                        if (weDialog == null) {
                            weDialog = new WeDialog(mContext);
                        }
                        weDialog.setTitle("是否删除该问答？")
                                .setNegativeButton("点错了", null)
                                .setPositiveButton("确定", new View.OnClickListener() {
                                    @Override
                                    public void onClick(View view) {
                                        removeIds.add(bean.getId());
                                        int cp = getParentPosition(bean);
                                        ((IssueTitleBean)getData().get(cp)).removeSubItem(bean);
                                        getData().remove(holder.getLayoutPosition());
                                        notifyItemRemoved(holder.getLayoutPosition());
                                        weDialog.dismiss();
                                    }
                                }).setCanceledOnTouchOutside(true)
                                .show();
                        return false;
                    }
                });
//                position++;
                break;
        }
    }
}

传进来的参数如下：
private List<MultiItemEntity> getIssueList(List<IssueBean.MessageBean> list1, List<IssueBean.MessageBean> list2, List<IssueBean.MessageBean> list3) {
        ArrayList<MultiItemEntity> res = new ArrayList<>();
        for (int j = 0; j < 3; j++) {
            String title = "";
            IssueTitleBean titleBean1 = null;
            IssueTitleBean titleBean2 = null;
            IssueTitleBean titleBean3 = null;
            switch (j) {
                case 0:
                    title = "相关情节";
                    titleBean1 = new IssueTitleBean(title);
                    for (int k = 0; k < list1.size(); k++) {
                        titleBean1.addSubItem(list1.get(k));
                    }
                    break;
                case 1:
                    title = "违法情节";
                    titleBean2 = new IssueTitleBean(title);
                    for (int k = 0; k < list2.size(); k++) {
                        titleBean2.addSubItem(list2.get(k));
                    }
                    break;
                case 2:
                    title = "违法表现";
                    titleBean3 = new IssueTitleBean(title);
                    for (int k = 0; k < list3.size(); k++) {
                        titleBean3.addSubItem(list3.get(k));
                    }
                    break;
            }
            if (titleBean1 != null) {
                res.add(titleBean1);
            }
            if (titleBean2 != null) {
                res.add(titleBean2);
            }
            if (titleBean3 != null) {
                res.add(titleBean3);
            }
        }
        return res;
    }

**Comment by CymChad** [comment]
删除的话，demo有删除的案例，你可以看下，你这样贴的代码块没法看。

**Comment by wardenlzr** [comment]
大佬 可以发个谈论群号么？

**Comment by CymChad** [comment]
558178792
