### ISSUE TITLE
必现规律，第二次loading时，只显示加载圈，没有发送网络请求。

### ISSUE THREAD

**Issue by xuwenfa** [CymChad/BaseRecyclerViewAdapterHelper#1506]
结合刷新使用，刷新完数据后，第一次loading时没问题，第二次loading时，加载圈出现，然而没有发送网络请求，导致加载圈永不消失。

**Comment by CymChad** [comment]
是否进了回调？

**Comment by 1109993488** [comment]
第一次loading请求网络成功后需要调loadMoreComplete

**Comment by xuwenfa** [comment]
谢谢大伙，谢谢谢谢，我的失误，加载完之后没有调用loadMoreComplete，导致只是第一次加载成功发送数据请求，第二次只是loading，不发送网络请求。
忠实支持者。
