### ISSUE TITLE
添加item子控件的点击事件为什么要放在Adapter中呢？

### ISSUE THREAD

**Issue by MoonlightSW** [CymChad/BaseRecyclerViewAdapterHelper#1508]
我这边在操作列表的时候需要先关闭侧滑菜单然后去删除，否侧Viewholder复用的原因会导致下面的列表出现侧滑打开的情况，感觉这样直接标注ViewHolder中的setonclickListener弃用，还是不太科学啊，可能你是考虑值创建一个listener？

**Comment by CymChad** [comment]
通过不是删除操作应该在atc里面做吗？所以需要先在adapter里面绑定监听，然后在atc实现监听。具体你可以看 文档http://www.jianshu.com/p/b343fcff51b0 ，setonclickListener的弃用是应该在adapter直接设置并实现点击事情，没有在adapter里面绑定，在atc实现监听的方式好。

**Comment by MoonlightSW** [comment]
@CymChad OK 了解了
