### ISSUE TITLE
BaseAdapter 里的getView方法好像没什么作用啊，应该传递个强转类型吧？

### ISSUE THREAD

**Issue by MoonlightSW** [CymChad/BaseRecyclerViewAdapterHelper#1509]
@SuppressWarnings("unchecked")
    public <T extends View> T getView(@IdRes int viewId ,Class<T> tClass) {
        View view = views.get(viewId);
        if (view == null) {
            view = itemView.findViewById(viewId);
            views.put(viewId, view);
        }
        return (T) view;
    }

像这样~，不然还得自己强转，As不自动提示，略麻烦

**Comment by CymChad** [comment]
恩 多谢提醒。

**Comment by CymChad** [comment]
后续我们会改进

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/907
