### ISSUE TITLE
当adapter的item为button时，设置了setOnRecyclerViewItemClickListener 后点击不灵

### ISSUE THREAD

**Issue by petma** [CymChad/BaseRecyclerViewAdapterHelper#151]
将home_item_view.xml中的内容，替换为button之后，HomeActivity中点击按钮，不会跳到新的activity.
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center">

  <Button
      android:id="@+id/btn"
      android:layout_margin="5dp"
      android:layout_width="match_parent"
      android:layout_height="wrap_content" />
</LinearLayout>`

` @Override
    protected void convert(BaseViewHolder helper, HomeItem item) {
        helper.setText(R.id.btn, item.getTitle());

    }`

**Comment by CymChad** [comment]
你是想设置item的点击还是子布局的点击？

**Comment by CymChad** [comment]
？？？
