### ISSUE TITLE
Scrollview 嵌套RecyclerView addData() 加载数据不显示 

### ISSUE THREAD

**Issue by skemdddd** [CymChad/BaseRecyclerViewAdapterHelper#1510]

**Comment by skemdddd** [comment]
我感觉是代码冲突问题， 但是 不知道问题在哪 ，希望能看看我的demo

**Comment by skemdddd** [comment]
我感觉是代码冲突问题， 但是 不知道问题在哪 ，希望能看看我的demo

**Comment by skemdddd** [comment]
setHasFixedSize(true); 开了之后 不显示， 不开启可以显示 是什么原因？

**Comment by CymChad** [comment]
setHasFixedSize 这是系统api，你添加的item应该是不同类型的item，setHasFixedSize的作用是让固定类型的item更有优势。

**Comment by panhs** [comment]
请问解决了吗  我也遇到这个问题了
