### ISSUE TITLE
mRecyclerView notifyDataSetChanged 闪动

### ISSUE THREAD

**Issue by umeitime** [CymChad/BaseRecyclerViewAdapterHelper#1511]
mRecyclerView notifyDataSetChanged item会闪动

如果使用默认的addData的话，我在添加评论的时候，因为第一个item加了最新评论textview，除了第一个其他的都需要隐藏，当第一个item变成第二个就无法刷新了。

**Comment by CymChad** [comment]
这个不是adapter的问题，notifyDataSetChanged是原生的api。
