### ISSUE TITLE
OnItemClick Ripple Effect

### ISSUE THREAD

**Issue by jbxkuang** [CymChad/BaseRecyclerViewAdapterHelper#1513]
android:background="@android:color/white"
android:foreground="?attr/selectableItemBackground"

每次点击Item,Ripple Effect都是从正中间扩散,
没有响应到触摸位置,
看到sample用的drawable作为background,
想请教使用selectableItemBackground,如何让Ripple Effect随点击位置而变化.

**Comment by CymChad** [comment]
使用adapter的setitemclick方法。
