### ISSUE TITLE
多布局的点击事件

### ISSUE THREAD

**Issue by Troll4it** [CymChad/BaseRecyclerViewAdapterHelper#1515]
我现在在多布局中设置点击事件，给每个控件设置的，想改变下方式。。看了简书的文章，有看了demo都没有相关的介绍。。请问，有没有好的方法给每个不同的布局设置点击事件，谢谢诶

**Comment by CymChad** [comment]
用添加点击事件的api就可以添加呀。如果是子布局就先绑定后添加监听即可，用viewid来区分。
