### ISSUE TITLE
RecyclerView嵌套RecyclerView加载更多时的跳动问题

### ISSUE THREAD

**Issue by provswin** [CymChad/BaseRecyclerViewAdapterHelper#1516]
Hello，我在项目中使用了1个垂直的RecyclerView（记为R1），这个RecyclerView中的每一个item是一个横向的RecyclerView（记为R2）。

在R1中加载更多时，在成功获取数据调用loadMoreComplete之后，加载更多的视图会消失，但是R1的菜单会出现一个跳动的效果（即加载完成后，原有的内容会往下跳动）：如下图
![跳动的效果](https://github.com/provswin/-/blob/master/ezgif.com-video-to-gif.gif) 
但是，在正常不嵌套的情况下，是不会出现这个跳动，R1会很自然的加载出更多的数据。请问知道这个原因是什么吗？

**Comment by 1109993488** [comment]
在最外层设置焦点就行

**Comment by provswin** [comment]
@1109993488 谢谢，可以了。是按照你的方法，在最外层设置了
                android:focusable="true"
                android:focusableInTouchMode="true"
就可以了
