### ISSUE TITLE
BaseQuickAdapter的setOnRecyclerViewItemClickListener貌似不起作用？

### ISSUE THREAD

**Issue by MarcoPeng** [CymChad/BaseRecyclerViewAdapterHelper#152]
historyAdapter.setOnRecyclerViewItemChildClickListener(new BaseQuickAdapter.OnRecyclerViewItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                ToastUtil.showToast(context, "click" + view.getId());
                if (view.getId() == R.id.del_cb) {
                    adapter.remove(position);
                    history_list.remove(position);
                }
            }
        });

**Comment by CymChad** [comment]
你可以看下demo的使用方法。

**Comment by CymChad** [comment]
setOnRecyclerViewItemClickListener  是这样方法，你使用方法错误了。
