### ISSUE TITLE
Rv 嵌套 Rv 上拉加载问题

### ISSUE THREAD

**Issue by H-Zan** [CymChad/BaseRecyclerViewAdapterHelper#1521]
Rv1 嵌套 Rv2, Rv2进行上拉加载, 当点击上拉加载按钮后, 整个屏幕不能继续向下滚动, 就是说 Rv2 新加载的数据不能靠滚动显示出来.

**Comment by 1109993488** [comment]
rv2加载的数据你是怎么添加的？你这个点击上拉加载按钮是rv2天假的footer？

**Comment by H-Zan** [comment]
@1109993488 是的, 点击的 rv2 的 footer,

**Comment by H-Zan** [comment]
@1109993488  我修改demo 中点击示例的嵌套 rv 为加载更多模式, 也不能继续向下滑动,

**Comment by 1109993488** [comment]
rv2加载的数据你是怎么添加的？

**Comment by H-Zan** [comment]
@1109993488 按照 示例 demo 中添加的

**Comment by 1109993488** [comment]
我试了添加没问题，你可以在demo中加试试，或者你提供个有问题的demo

**Comment by H-Zan** [comment]
[Uploading BaseRecyclerViewAdapterHelper-master 1.zip…]()

在 itemClick 模块中

**Comment by H-Zan** [comment]
添加的代码在 ItemClick 模块中

[BaseRecyclerViewAdapterHelper-master 1.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/1280338/BaseRecyclerViewAdapterHelper-master.1.zip)

**Comment by H-Zan** [comment]
@1109993488 
添加的代码在 ItemClick 模块中
[BaseRecyclerViewAdapterHelper-master 1.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/1280345/BaseRecyclerViewAdapterHelper-master.1.zip)

**Comment by 1109993488** [comment]
不能滑动的原因是你设置了setHasFixedSize(true)属性，滑动事件是在最外层rv上
如果不设置这个属性会出现无限加载
建议换中做法，比如你的其他类型放到header里
