### ISSUE TITLE
设置emptyView显示有问题

### ISSUE THREAD

**Issue by Reginer** [CymChad/BaseRecyclerViewAdapterHelper#1522]
用
public void setEmptyView(int layoutResId) 
设置一个空布局，传进去的布局宽高都是match_parent，显示的时候，高就不是全屏了

**Comment by ALguojian** [comment]
布局贴一下

**Comment by Reginer** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:id="@+id/view_empty"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:gravity="center"
              android:orientation="vertical"
              android:padding="@dimen/dp20">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:drawablePadding="@dimen/dp20"
        android:drawableTop="@drawable/ic_content_null"
        android:gravity="center"
        android:text="@string/content_null"
        android:textSize="@dimen/sp20"/>
</LinearLayout>`

**Comment by Reginer** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:id="@+id/view_empty"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:gravity="center"
              android:orientation="vertical"
              android:padding="@dimen/dp20">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:drawablePadding="@dimen/dp20"
        android:drawableTop="@drawable/ic_content_null"
        android:gravity="center"
        android:text="@string/content_null"
        android:textSize="@dimen/sp20"/>
</LinearLayout>

**Comment by Reginer** [comment]
上面没显示全：

https://github.com/Reginer/AndroidLife/blob/master/app/src/main/res/layout/book/layout/view_content_null_layout.xml

**Comment by FrankKwok** [comment]
你RV是全屏吗

**Comment by Reginer** [comment]
wrap_content

**Comment by FrankKwok** [comment]
改成match_parent看看

**Comment by Reginer** [comment]
@FrankKwork，可以了，谢谢

**Comment by chengzhijun0706** [comment]
我的recyclerview是全屏的,但是空view还是高度不对
`<?xml version="1.0" encoding="utf-8"?>
<com.scwang.smartrefresh.layout.SmartRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:srlEnableAutoLoadmore="true">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/scrollView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#fff"
            android:orientation="vertical">

            <FrameLayout
                android:id="@+id/lyt_custom_head"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <TextView
                    android:id="@+id/tv_report_num"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:layout_marginTop="10dp"
                    android:textColor="#999"
                    android:textSize="16sp"
                    android:visibility="gone"
                    app:layout_scrollFlags="scroll"/>

                <FrameLayout
                    android:id="@+id/lyt_sort"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center_vertical"
                    android:paddingLeft="10dp"
                    android:paddingRight="10dp"
                    android:visibility="gone">

                    <ImageView
                        android:id="@+id/img_sort"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:src="@drawable/header_live_detail_sort_selector"/>

                    <TextView
                        android:id="@+id/tv_num"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="right|center_vertical"
                        android:gravity="center"
                        android:text="1条报道"
                        android:textColor="#999"
                        android:textSize="12sp"/>

                </FrameLayout>

            </FrameLayout>

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                tools:listitem="@android:layout/simple_list_item_2"/>

        </LinearLayout>

    </android.support.v4.widget.NestedScrollView>

</com.scwang.smartrefresh.layout.SmartRefreshLayout>
`
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:gravity="center"
        android:layout_gravity="center">

    <View
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/fragment_common_home_empty_view_head"/>

    <View
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/fragment_common_home_empty_view_foot"/>

    <View
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>

    </LinearLayout>

</RelativeLayout>`

**Comment by caoeryang** [comment]
我的rv是match_parent   空布局最外层也是match_parent    但是效果确是wrap_content

**Comment by Reginer** [comment]
外面嵌套ScrollView的会变成wrap_content的。可以设置rv的高度为一个固定值，比如100dp
