### ISSUE TITLE
addHeaderView and then setEmptyView crash

### ISSUE THREAD

**Issue by jacky1234** [CymChad/BaseRecyclerViewAdapterHelper#1523]
The crash log is:
`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{300f2ac1 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}`
 
First 
`setAdapter to RecyclerView` and then `addHeaderView` to it ,when the network is not available ,it 
crash ,here is the code:
```
override fun onError(t: Throwable) {
        mAdapter.emptyView = errorView
        swipeRefreshLayout?.isRefreshing = false
        swipeRefreshLayout.isEnabled = false
        swipeRefreshLayout?.setOnRefreshListener(null)

        if (mAdapter.isLoadMoreEnable) {
            mAdapter.setEnableLoadMore(false)   //不需要加载更多
        }
    }
``` 
when run into ` mAdapter.emptyView = errorView`  it crashes ,why?

**Comment by FrankKwok** [comment]
emptyView是配置项，参考#1280
