### ISSUE TITLE
Diffutil 结合adapter的使用方法

### ISSUE THREAD

**Issue by Lemniscate317** [CymChad/BaseRecyclerViewAdapterHelper#1525]
我的diffutil的demo是在这个链接上学的 结合这个link使用
http://blog.csdn.net/zxt0601/article/details/52562770

在这个link里面到了最后一步，会让你使用adapter.setData这个方法。但是baseTecyclerViewAdapterHelper是没有的，然后我们就自己写一个
!!!我这里项目需要 使用的是多item的adapter 
```
public class Adapter extends BaseMultiItemQuickAdapter<Item, BaseViewHolder> {
    

    public void setData(List<Item> lists) {
        getData().clear();
        getData().addAll(lists);
    }
}
```
然后我估摸着大家都是卡在这里，因为别的地方结合adapter一样能用 所以先到这里

**Comment by lhl-012** [comment]
dear sir,diffutil is good at data comparison, now we only use list.clean() and list.addAll() , So there's no need to use it,If you have special needs, you can manage the data yourself and refresh the data with adapter

**Comment by lhl-012** [comment]
翻译一下，Diffutil主要做的是进行数据比对操作，比如list里面数据内容发生变化，但是目前我们使用的是全增或者全删，没有必要使用，如果你有特殊需求，自己管理数据，用adapter.notifyItemRemoved等4个方法即可

**Comment by Lemniscate317** [comment]
我刚好有需要用到 看到有人提问不知道怎么结合使用 我就开个贴 方便讨论而已

**Comment by lhl-012** [comment]
Diffutil需要实体中有唯一性字段，添加对于数据维护过多，不合适，所以没做
