### ISSUE TITLE
列表项不足一屏时会不断loadmore

### ISSUE THREAD

**Issue by cxbiao** [CymChad/BaseRecyclerViewAdapterHelper#1526]
当列表项不足recyclerview的一屏时，会自动无限的去调用loadmore，实际上已经没有更多数据了！
但又不能设置loadmoreend，因为随时可能有新数据到来，这就非常尴尬了！
导致loadmore会一直存在，相信各位都有体验，不知作者如何解决这个问题？

**Comment by 1109993488** [comment]
有新数据了客户端也不知道，必须调下拉刷新才能更新数据

**Comment by 1109993488** [comment]
更新的时候调setNewData会重新开启加载更多

**Comment by Yzw92** [comment]
setNewData()要在loadMoreEnd()之前调用

**Comment by BruseDu** [comment]
是的setNewData会重新开启加载更多 这个问题一直存在希望作者尽快解决

**Comment by CymChad** [comment]
@BruseDu 如果你想关闭调用loadMoreEnd即可。

**Comment by addappcn** [comment]
现在的加载更多不如之前老版本 ，感觉现在代码越来越臃肿，复杂，不易用，真的 我开发几年了 也许我真的开发水平很低
