### ISSUE TITLE
同时使用GridLayoutManager和EmptyView会出现问题

### ISSUE THREAD

**Issue by kjsolo** [CymChad/BaseRecyclerViewAdapterHelper#1527]
如果RV设置GridLayoutManager的spanCount大于n，那么EmptyView的宽度显示只会显示1/n

**Comment by CymChad** [comment]
收到，我修复一下。

**Comment by CymChad** [comment]
你可以试一下，adapter.setSpanSizeLookup,不用GridLayoutManager的。
