### ISSUE TITLE
notifyDataSetChanged之后显示loadmoreview，但是并没有调用loadmore的方法.如何不让他显示loadmoreview

### ISSUE THREAD

**Issue by shaoshiwei** [CymChad/BaseRecyclerViewAdapterHelper#1529]
刚进入页面是一个空数据的recyclerview，这时候添加了一条数据并notifyDataSetChanged，这时候在底部就会显示loadmore，但是断点调试，并没有进入loadmore的方法。怎么做才能不让它显示？谢谢。

因为不支持直接上传视频，只能上传压缩包，所以麻烦下载才能看。

[录屏.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/1280616/default.zip)

**Comment by 1109993488** [comment]
不设置加载更多监听就不会开启加载更多，如果开启了加载更多并添加数据这时就应该判断是否还有更多数据，如果没有更多需要loadMoreEnd关闭加载更多
