### ISSUE TITLE
ExpandableUseActivity 伸缩性能问题

### ISSUE THREAD

**Issue by zuoyuan333** [CymChad/BaseRecyclerViewAdapterHelper#1530]
最近做一个类似360清理大师的微信清理功能.做相册预览( 聊天图片 )时发现当子item的量级达到几万的时候,点击headview条目收缩会卡顿,展开不会卡顿,在低端机上相当明显.高端机也有1秒钟左右的卡顿,而360的毛事木有.....请指出这个性能问题能不能在你这个helper里面优化, 如果不能请给我一个链接我看看要怎么写,感觉解决好了可以放到demo里面,,用相册替换原有的ExpandableUseActivity 会比较震撼

**Comment by CymChad** [comment]
可以看下这篇文章[源码分析](https://mp.weixin.qq.com/s?__biz=MzIwMzYwMTk1NA==&tempkey=OTIxX0h0aEVieTJqVkFTV2hUMzk2MVBzY0I3X09QVF9ONFllWXhHUXphYWVfTTZwbzZNRHdNRGMtVVVFNzVheDJSSmhmaF9iblJTcmRuMG9XVnlyYjdfMEFsSV9oSUVYb3F6M2F2eHVtcVBwUTNSMkZINk1sdmJDX0l1MUVZMGFnR1lYWllHbFRwZ3g5dmdrdFBpNDdha2kzVlhTZUdQMnQzMTFuTzVHZVF%2Bfg%3D%3D&chksm=16cda08021ba2996cae65d3a6bbc1fd1c1e0ce98623e4a8aca0da079e7b2234524c9ff7c4a4d#rd)，希望对你有帮助。
