### ISSUE TITLE
如果把RecyclerView直接嵌套在NestedScrollView里面，并且添加RequestLoadMoreListener，那么RequestLoadMoreListener会不断触发，直到数据加载完成

### ISSUE THREAD

**Issue by zhangliangbo** [CymChad/BaseRecyclerViewAdapterHelper#1532]
layout:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.rdrnss.common.activity.TestActivity">

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </android.support.v4.widget.NestedScrollView>

</LinearLayout>
activity:
public class TestActivity extends AutoBackActivity {

    @BindView(R.id.recycler)
    RecyclerView recyclerView;

    Cache<Item> cache = new Cache<>(20);
    Adapter adapter = new Adapter();

    @Override
    protected int getContentView() {
        return R.layout.activity_test;
    }

    @Override
    protected void initWidget() {
        adapter.setOnLoadMoreListener(new LoadMoreListener(), recyclerView);
        recyclerView.setAdapter(adapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(TestActivity.this));
        recyclerView.setNestedScrollingEnabled(false);
        super.initWidget();
        List<Item> list = new ArrayList<>();
        for (int i = 0; i < 1000; i++) {
            list.add(new Item());
        }
        cache.refresh(list);//缓冲数据
        adapter.getData().clear();
        requestLocal();
    }

    /**
     * 本地分页缓存
     *
     * @param <T>
     */
    protected class Cache<T> extends ArrayList<T> {
        private int curPage = 1;
        private int pageSize = 10;
        private int pageCount = 0;

        public Cache(int pageSize) {
            this.pageSize = pageSize;
        }

        public void refresh(List<T> list) {
            clear();
            curPage = 1;
            pageCount = list.size() / pageSize + 1;
            addAll(list);//加入数据
        }

        public boolean haveMore() {
            return curPage <= pageCount;
        }

        public List<T> fetchMore() {
            List<T> result = new ArrayList<>();
            if (curPage < pageCount) {
                for (int i = pageSize * (curPage - 1); i < pageSize * curPage; i++) {
                    result.add(get(i));
                }
            } else {
                for (int i = pageSize * (curPage - 1); i < size(); i++) {
                    result.add(get(i));
                }
            }
            curPage++;//索引转到下一页
            return result;
        }

        public int getPageSize() {
            return pageSize;
        }

        public int getCurPage() {
            return curPage;
        }
    }

    private void requestLocal() {
        Observable.just(0).delay(1, TimeUnit.SECONDS)
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<Integer>() {
                    @Override
                    public void accept(@NonNull Integer integer) throws Exception {
                        adapter.loadMoreComplete();
                        List<Item> itemList = cache.fetchMore();
                        for (Item item : itemList) {
                            adapter.addData(item);
                        }
                        adapter.notifyDataSetChanged();
                    }
                });
    }

    private class Item {

    }

    private class LoadMoreListener implements BaseQuickAdapter.RequestLoadMoreListener {

        @Override
        public void onLoadMoreRequested() 

> **该事件会被不停地触发，直到cache的数据全部请求完
嵌套在NestedScrollView的RecyclerView会出现这种问题**

            Logger.d("page: " + cache.getCurPage());
            if (cache.haveMore()) {
                requestLocal();
            } else {
                adapter.loadMoreEnd();
            }
        }
    }

    private class Adapter extends BaseQuickAdapter<Item, BaseViewHolder> {

        Adapter() {
            super(R.layout.item_object, new ArrayList<>());
        }

        @Override
        protected void convert(BaseViewHolder baseViewHolder, Item item) {

        }
    }

}

**Comment by CymChad** [comment]
机制上的冲突建议使用别的上拉控件来实现 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/204
