### ISSUE TITLE
删除操作时只移除了视图移除数据失败

### ISSUE THREAD

**Issue by zuoyuan333** [CymChad/BaseRecyclerViewAdapterHelper#1538]
2.9.28版本,  CleanWxExpandableItemAdapter

for (int i = 0; i < picLists.size(); i++) {
						if (picLists.get(i).getItemType()== CleanWxExpandableItemAdapter.TYPE_HEAD){
							CleanWxPicHeadInfo headInfo=(CleanWxPicHeadInfo)picLists.get(i);
							if (headInfo.isChecked()){
								if (headInfo.isChecked()){
									picLists.remove(i);
									mAdapter.notifyItemRemoved(i);
									i--;
								}
							}
						}else if(picLists.get(i).getItemType()== CleanWxExpandableItemAdapter.TYPE_PIC){
							CleanWxClearInfo itemInfo=(CleanWxClearInfo)picLists.get(i);
							if (itemInfo.isChecked()){
								picLists.remove(i);//这个和下面那就都移除无效
								boolean remove = picLists.remove(picLists.get(i));//(这个返回值为true)
								mAdapter.notifyItemRemoved(i);
								i--;
							}
						}
					}
在删除前后遍历list的size.发现删除无效,但是视图上对应的item确实删除了

**Comment by zuoyuan333** [comment]
如果只删除数据的话,又不能同时使用mAdapter.notifyItemRemoved(i);,所以我现在只能先遍历一次删除视图,再遍历一次删除数据...

**Comment by CymChad** [comment]
使用mAdapter. remove方法没有？我看你的代码使用的都是原生的api。

**Comment by zuoyuan333** [comment]
for (int i = 0; i < picLists.size(); i++) {
						if (picLists.get(i).getItemType()== CleanWxExpandableItemAdapter.TYPE_HEAD){
							CleanWxPicHeadInfo headInfo=(CleanWxPicHeadInfo)picLists.get(i);
							if (headInfo.isChecked()){
								if (headInfo.isChecked()){
									mAdapter.remove(i);
									picLists.remove(i);
									mAdapter.getData().remove(i);
									mAdapter.getData().remove(picLists.get(i));
									mAdapter.notifyItemRemoved(i);
									i--;
								}
							}
						}else if(picLists.get(i).getItemType()== CleanWxExpandableItemAdapter.TYPE_PIC){
							CleanWxClearInfo itemInfo=(CleanWxClearInfo)picLists.get(i);
							if (itemInfo.isChecked()){
								mAdapter.remove(i);
								picLists.remove(i);
								mAdapter.getData().remove(i);
								mAdapter.getData().remove(picLists.get(i));
								mAdapter.notifyItemRemoved(i);
								i--;
							}
						}
					}
还是删不掉

**Comment by CymChad** [comment]
可以给个demo看下吗？

**Comment by CymChad** [comment]
只需要mAdapter.remove(i);，其他的都不需要。

**Comment by zuoyuan333** [comment]
给不出来demo..我先这样处理着,后面写个demo出来

**Comment by CymChad** [comment]
恩 好的。

**Comment by CymChad** [comment]
我在demo测试 使用rm方法是可行的，后续给出demo我这边帮你调试看下。
