### ISSUE TITLE
麻烦作者考虑下向后兼容的事情

### ISSUE THREAD

**Issue by xiaobaDev** [CymChad/BaseRecyclerViewAdapterHelper#1539]
2.9.28
setVisible:Set a view visibility to VISIBLE (true) or INVISIBLE (false).
setGone: Set a view visibility to VISIBLE (true) or GONE (false).
这种改法，原先Gone的会变成INVISIBLE，导致UI显示错乱，项目里面如果大规模使用你这个库的话，查起来很麻烦

你可以把原先的声明废弃，再写个新的函数

**Comment by CymChad** [comment]
恩。谢谢，下次我一定会注意。这边是我这边考虑不周导致给你带来了麻烦，十分抱歉。
