### ISSUE TITLE
Animation not work in GridLayoutManager 

### ISSUE THREAD

**Issue by jasonni** [CymChad/BaseRecyclerViewAdapterHelper#154]
Hi @CymChad,
I just trying to change LinearLayoutManager to GridLayoutManager in AnimationUseActivity class,
and the animation not working

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/16791156/a4892f1a-48ee-11e6-917a-4c68d39554d2.png)
normal

**Comment by CymChad** [comment]
![1](https://cloud.githubusercontent.com/assets/7698209/16791173/ce0f975c-48ee-11e6-9057-0eb64a225493.gif)

**Comment by CymChad** [comment]
```java
switch (viewType) {
            case 0:
                convert((BaseViewHolder) holder, mData.get(holder.getLayoutPosition() - getHeaderViewsCount()));
                addAnimation(holder);
                break;
            case LOADING_VIEW:
                addLoadMore(holder);
                break;
            case HEADER_VIEW:
                break;
            case EMPTY_VIEW:
                break;
            case FOOTER_VIEW:
                break;
            default:
                convert((BaseViewHolder) holder, mData.get(holder.getLayoutPosition() - getHeaderViewsCount()));
                onBindDefViewHolder((BaseViewHolder) holder, mData.get(holder.getLayoutPosition() - getHeaderViewsCount()));
                break;
        }
```
You are the type of the custom?

**Comment by jasonni** [comment]
Hi @CymChad , sorry, my bad, it's working now. 
Thanks for your help :)

I have another question about SLIDEIN_BOTTOM animation when using GridLayoutManager,
the last item is not slide in,

![slidebottom](https://cloud.githubusercontent.com/assets/4085409/16792249/6581c740-48f9-11e6-8075-3709bb5ccf3c.gif)

I find the problem is the last item height is 0, any idea to fix it ?
