### ISSUE TITLE
在嵌套popupWindow使用时 view未刷新问题？

### ISSUE THREAD

**Issue by zk1393943039** [CymChad/BaseRecyclerViewAdapterHelper#1540]
使用的昨天项目内libary的版本

在嵌套popupWindow使用时 setNewData()
 设置空数据view未刷新   vegetableAdapter.getData().size()长度打印为0
有数据 显示正常
`    ArrayList<VegetableBean> vegetableBeanArray = new ArrayList<>();  vegetableAdapter.setNewData(vegetableBeanArray);`

**Comment by CymChad** [comment]
如果setNewData个null呢？

**Comment by zk1393943039** [comment]
setNewData(null) view亦未刷新 打他打印长度为0 
setOnItemClickListener点击无效 貌似是view未刷新的问题

**Comment by CymChad** [comment]
可以给个demo看下吗？我在demo里面无法复现你说的情况。

**Comment by zk1393943039** [comment]
`//商品名称模糊搜索
        RxTextView.textChanges(etCommodityName)
                .debounce(800, TimeUnit.MILLISECONDS) //800毫秒响应一次 输入监听
                .filter(charSequence -> { //过滤字符长度小于0的并且非item点击
                    if (isItemClick) {
                        isItemClick = false;
                        return false; //为item点击 终止发送
                    } else {
                        return charSequence.toString().trim().length() > 0;
                    }
                })
                .switchMap(new Function<CharSequence, ObservableSource<String>>() { //只监视最新发出的Observable 防止之前数据网络请求等待时间过长覆盖新数据
                    @Override
                    public ObservableSource<String> apply(@NonNull CharSequence charSequence) throws Exception {
                        return Observable.just(charSequence.toString());
                    }
                })
                .subscribe(charSequence -> {
                    mCommodityBean = null;
                    mPresenter.selectCommodity(charSequence.toString(), null);
                }); //发送网络请求`
`//Presenter 搜索实现
 @Override
    public void selectCommodity(String commodityName, String barCode) {

        if (commodityName != null) {//根据蔬菜名称搜素
            if (commodityName.equals("")) { //再次加载
                isLoadMore = true;
                pageNumber++;
            } else {
                pageNumber = 1;
                isLoadMore = false;
                mCommodityName = commodityName;
            }

        } else { //根据条码搜索
            if (barCode.equals("")) { //再次加载
                isLoadMore = true;
                pageNumber++;
            } else {
                pageNumber = 1;
                isLoadMore = false;
                mBarCode = barCode;
            }
        }


        Map<String, Object> paramsMap = new HashMap<>();
        paramsMap.put("USERID", MyApplication.myAppInstance.getUserBean().getUserId());
        paramsMap.put("pageSize", "10");
        paramsMap.put("pageNumber", String.valueOf(pageNumber));
        if (commodityName != null) {
            paramsMap.put("VEGETABLE_NAME", mCommodityName);
        } else {
            paramsMap.put("BAR_CODE", mBarCode);
        }


        BaseSubscriber<ResponseBody> subscriber = mRetrofitHelper.selectVegetable(RetrofitHelper.RequestBodyStructure(paramsMap))
                .compose(RxUtil.rxSchedulerHelper())
                .subscribeWith(new BaseSubscriber<ResponseBody>(mView) {
                    @Override
                    public void onRequestSuccess(JsonObject jsonObject) {
                        if (jsonObject.has("page")) {
                            jsonObject = jsonObject.getAsJsonObject("page");
                            if (jsonObject.has("list")) {
                                Gson gson = new Gson();
                                JsonArray VegetableArray = jsonObject.getAsJsonArray("list");
                                ArrayList<CommodityBean> commodityBeanArray = new ArrayList<>();
                                for (int i = 0; i < VegetableArray.size(); i++) {
                                    CommodityBean commodityBean = new CommodityBean();
                                    commodityBean = gson.fromJson(VegetableArray.get(i), CommodityBean.class);
                                    commodityBeanArray.add(commodityBean);
                                }
                                LogUtil.i("isLoadMore", "" + isLoadMore);
                                if (isLoadMore) { //判断是否加载更多
                                    if (commodityBeanArray.size() > 0) {
                                        vegetableAdapter.addData(commodityBeanArray);
                                        vegetableAdapter.loadMoreComplete();
                                    } else {
                                        vegetableAdapter.loadMoreEnd();
                                    }
                                } else { //正常搜素
                                    if (vegetableAdapter == null) { //判断是否需要第一次初始化
                                        fulladpater(commodityBeanArray);
                                    } else {
                                            vegetableAdapter.setNewData(commodityBeanArray);
                                        LogUtil.i("当前数据长度", "-" + vegetableAdapter.getData().size());
                                    }
                                }

                            }
                        }
                    }
                });
        addSubscribe(subscriber);
    }

    //填充数据
    private void fulladpater(ArrayList<CommodityBean> commodityBeanArray) {
        LogUtil.i("vegetableBeanList", commodityBeanArray.toString());

        vegetableAdapter = new BaseQuickAdapter<CommodityBean, BaseViewHolder>(R.layout.item_pop_vegetable, commodityBeanArray) {
            @Override
            protected void convert(BaseViewHolder baseViewHolder, CommodityBean vegetable) {
                TextView tv = baseViewHolder.getView(R.id.item_pop_tv);
                tv.setText(vegetable.getVEGETABLE_NAME());
            }
        };
        //item点击
        vegetableAdapter.setOnItemClickListener((adapter, view1, position) -> {

            CommodityBean commodityBean = (CommodityBean) adapter.getData().get(position);
            mView.dismissVegetableList(commodityBean);
            LogUtil.i("点击", commodityBean.toString());

        });
        mView.showVegetableList(vegetableAdapter);
    }`

`//展示蔬菜列表
    @Override
    public void showVegetableList(BaseQuickAdapter vegetableAdapter) {

        LayoutInflater inflater = getLayoutInflater();
        View view = inflater.inflate(R.layout.pop_jion_vegetable, (LinearLayout) findViewById(R.id.pop_jion_vegetable));
        popupWindow = new PopupWindow(view, ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        RecyclerView pop_rv_line = (RecyclerView) view.findViewById(R.id.pop_jion_vegetable_rv);
        pop_rv_line.setLayoutManager(new LinearLayoutManager(mContext, LinearLayoutManager.VERTICAL, false));

        //加载更多
        vegetableAdapter.setOnLoadMoreListener(() -> pop_rv_line.postDelayed(() -> mPresenter.selectCommodity("", null), 0), pop_rv_line);
        vegetableAdapter.disableLoadMoreIfNotFullPage();

        pop_rv_line.setAdapter(vegetableAdapter);

        popupWindow.setInputMethodMode(PopupWindow.INPUT_METHOD_NEEDED);
        popupWindow.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        popupWindow.showAsDropDown(etCommodityName);

    }`

**Comment by CymChad** [comment]
你这个代码我很难直接实现，我的意思是能不能给一个抽出来的小demo，我给你调试一下。

**Comment by zk1393943039** [comment]
自己的内容刷新代码错误了 跟项目库无关
抱歉耽误库主 时间了
