### ISSUE TITLE
adapter点击事件如何获取当前item的某一个控件？

### ISSUE THREAD

**Issue by Destiny01** [CymChad/BaseRecyclerViewAdapterHelper#1543]
mAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
              //这里如何获取item里面的某一个控件
            }
 }

**Comment by FrankKwok** [comment]
中间的view参数里去拿

**Comment by Destiny01** [comment]
view.findViewById((d)？

**Comment by CymChad** [comment]
getViewByPosition

**Comment by Destiny01** [comment]
mAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
        @Override
        public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                    
                    ImageView iv_anim = (ImageView) adapter.getViewByPosition(position, R.id.iv_anim);
                    iv_anim.setImageResource(R.drawable.animation1);
                    //播放动画
                    final AnimationDrawable animationDrawable = (AnimationDrawable) iv_anim.getDrawable();
                  //动画播放会错位，差3个位置
        }

**Comment by qianzhihe86** [comment]
请问要是在点击事件外呢？使用该方法adapter.getViewByPosition(position, R.id.iv_anim);获取的为null，怎么办？
