### ISSUE TITLE
2.9.28 ，setText()含有空格" "会被换行

### ISSUE THREAD

**Issue by Damon-L** [CymChad/BaseRecyclerViewAdapterHelper#1549]
继承BaseQuickAdapter重写convert( )，helper.setText(int resId , CharSequence value );
如果value含有空格，例如"11111 2222 3333"，空格会被转成换行
![image](https://user-images.githubusercontent.com/13973974/30363554-448f5008-9893-11e7-8955-55fec89dd1b8.png)
![image](https://user-images.githubusercontent.com/13973974/30363546-3b3b37ec-9893-11e7-8e00-08ddb2e7c77d.png)

**Comment by CymChad** [comment]
![image](https://user-images.githubusercontent.com/7698209/30366326-3b0a7a76-989d-11e7-8717-b4036373111b.png)
我刚才在demo上测试了一下，并没有发生你说的问题。
