### ISSUE TITLE
做类似朋友圈的界面卡顿特别明显

### ISSUE THREAD

**Issue by axkza** [CymChad/BaseRecyclerViewAdapterHelper#1550]
就是   垂直recyclerview   item是  网格recyclerview，类似朋友圈图片列表

普通的recyclerview没问题，用了这个就感觉卡了

**Comment by axkza** [comment]
有没有这种需求的例子？麻烦给一个参考一下

**Comment by axkza** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1052
发现跟这个问题一样，我下载你上面的demo看看

**Comment by CymChad** [comment]
我提供了demo，你可以看看，有问题在提。

**Comment by axkza** [comment]
用你的那个demo其实也会卡，可能图小卡顿不明显，后来我发现卡顿的原因是因为recyclerview嵌套的recyclerview的viewpool是不共享的，也就是每次滑动到新item都会去重新生成，导致的卡顿！

参考这里http://www.ctolib.com/topics-116825.html
RecyclerView:嵌套RecyclerViews    的优化（recyclerview版本必须5.1.0以上）

在外层recyclerview的adapter中添加一个全局的viewpool
RecyclerView.RecycledViewPool mSharedPool = new RecyclerView.RecycledViewPool();

然后在convert里面设置recyclerview.setRecycledViewPool(mSharedPool);
这样每个item的recyclerview都是共享viewpool，就可以解决卡顿的问题了！

建议做个例子，毕竟类似朋友圈的布局还是挺常见的

**Comment by CymChad** [comment]
好的，感谢。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1550

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1560

**Comment by kexingmo** [comment]
好像不行哦，recyclerview嵌套的子recyclerview，如果子recyclerview的item多的话（10~15个）感觉还是会有弹~弹的感觉，不是特别流畅，另外内存花费挺大的，滑动一屏2M多（可能跟图片大小有关）

最近就在弄朋友圈的功能，希望作者尽快出个demo，感激不尽！
