### ISSUE TITLE
PullToRefreshUseActivity上拉加载问题

### ISSUE THREAD

**Issue by jinguangyue** [CymChad/BaseRecyclerViewAdapterHelper#1551]
在demo里面的PullToRefreshUseActivity第一次上拉加载都会提示加载失败， 我在使用过程中遇到了， 然后看demo里面也是这个现象， 这情况应该不是正常现象吧， 不知道其他伙伴有没有遇到过

isErr 变量是false, 那每次的第一次加载更多都会提示， 不知道为什么要这样写呢

**Comment by CymChad** [comment]
这个只是演示可以使用这个功能而已。
