### ISSUE TITLE
关于Expandable点击展开某一项，其他项全部收缩的问题

### ISSUE THREAD

**Issue by magic0908** [CymChad/BaseRecyclerViewAdapterHelper#1552]
首先感谢作者提供这个库！我也一直在用，不过最近需要用到Expandable类型，遇到一些问题。
我们的需求是这样的，列表中第一个item默认展开，其他收缩；点击哪一个，哪一个就展开，其他的收缩，我就在demo设置了adapter.expand(0);
在adapter里写了个方法，点击最上层item遍历所有item，把方法写在item点击事件里
private void expandItem(int position){
        for(MultiItemEntity item : getData()){
           Level0Item lv0 = (Level0Item) item;
            if (lv0.isExpanded()) {
                collapse(position);
            } else {
                expand(position);
            }
        }
    }
但是问题来了，如果我点击第一个默认展开的item，会报异常java.util.ConcurrentModificationException
如果我点击其他item，会出现类型转换异常，java.lang.ClassCastException: com.chad.baserecyclerviewadapterhelper.entity.Level1Item cannot be cast to com.chad.baserecyclerviewadapterhelper.entity.Level0Item
想请教作者这个问题怎么处理好。

**Comment by lhl-012** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1359

**Comment by magic0908** [comment]
@lhl-012 已经解决了，感谢！
