### ISSUE TITLE
下拉刷新没有添加新的数据

### ISSUE THREAD

**Issue by sunshinewei** [CymChad/BaseRecyclerViewAdapterHelper#1555]
` mRefresh.setOnRefreshListener(new OnRefreshListener() {
            @Override
            public void onRefresh(RefreshLayout refreshlayout) {
                page = 1;
                mChuZhiAdapter.setNewData(mList);
                mRefresh.finishRefresh();
            }
        });
        mRefresh.setOnLoadmoreListener(new OnLoadmoreListener() {
            @Override
            public void onLoadmore(RefreshLayout refreshlayout) {
                page++;
                mChuZhiAdapter.addData(mList);
                mRefresh.finishLoadmore();
            }
        });`
能帮我看看吗，大神

**Comment by sunshinewei** [comment]
没有清空个旧数据

**Comment by CymChad** [comment]
setNewData 既可以清除旧数据以及装载新数据。
