### ISSUE TITLE
BaseMultiItemQuickAdapter的adapter点击事件问题

### ISSUE THREAD

**Issue by xqwgiser** [CymChad/BaseRecyclerViewAdapterHelper#156]
你好，我在项目中使用BaseMultiItemQuickAdapter时，对item设置点击事件时发现当item类型及数量较多时，点击的view位置与adapter记录的位置出现差别，例如我点击第5个item,改变其显示的文字，但却是第7个item文字内容改变，至今尚未发现问题所在:
```
case LayerField.TEXT://itemType标签，共5个
                baseViewHolder.setText(R.id.tv_fieldName, layerField.getCHINESENAME());
                if (layerField.getISNULLABLE() == 1) {
                    isNull = "必填";
                } else {
                    isNull = "非必填";
                }
                baseViewHolder.setOnClickListener(R.id.textField, new View.OnClickListener() {
                    @Override
                    public void onClick(final View v) {
                        Log.e("layerField",layerField.getCHINESENAME());//记录点击项
                        new MaterialDialog.Builder(context)//弹出赋值dialog
                                .title("文本")
                                .content(layerField.getCHINESENAME())
                                .inputType(InputType.TYPE_CLASS_TEXT)
                                .input(isNull, null, new MaterialDialog.InputCallback() {
                                    @Override
                                    public void onInput(MaterialDialog dialog, CharSequence input) {
                                        if (input.length() == 0) {
                                            new MaterialDialog.Builder(context)
                                                    .title("警告")
                                                    .content(layerField.getCHINESENAME() + "为必填项目")
                                                    .positiveText("确定")
                                                    .show();
                                        } else {
                                            
                                            TextView textView= (TextView) v.findViewById(R.id.tv_fieldContent);//保存输入内容
                                            textView.setText(input);
                                            
                                        }
                                    }
                                }).show();
                    }
                });
                break;
```

**Comment by CymChad** [comment]
你可以使用我提供的方法来设置点击事件

**Comment by xqwgiser** [comment]
对BaseMultiItemQuickAdapter设置的OnRecyclerViewItemChildClickListener好像无效。。。。

**Comment by CymChad** [comment]
看下你使用的代码

**Comment by xqwgiser** [comment]
adapter.setOnRecyclerViewItemChildClickListener(new BaseQuickAdapter.OnRecyclerViewItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                Log.e("click","success");
            }
        });
        dataList.setAdapter(adapter);

**Comment by CymChad** [comment]
在adapter里面你要给具体控件设置方法呀，
helper.setOnClickListener(R.id.tweetAvatar, new OnItemChildClickListener())

**Comment by verticalakash** [comment]
Hello xqwgiser!
i am stuck in a same situation like you and unfortunately i didn't get any perfect situation. please help me out. My code snippet is as follows:
`public class MultipleItemQuickAdapter extends BaseMultiItemQuickAdapter<PostListModel> {

    private FeedItemListener feedItemListener;


    FeedFileView attachmentRecyclerView;

    Context context;

    public MultipleItemQuickAdapter(Context context, List<PostListModel> data, FeedItemListener feedItemListener) {
        super( data);
        addItemType(PostListModel.TEXT, R.layout.normal_feed_row);
        addItemType(PostListModel.IMG, R.layout.item_feed_image_layout);
        addItemType(PostListModel.LINK, R.layout.item_feed_link_layout);
        addItemType(PostListModel.FILE, R.layout.item_feed_attachment_layout);

        this.context = context;

        this.feedItemListener = feedItemListener;
    }


    @Override
    protected void convert(BaseViewHolder helper, final PostListModel item) {
        switch (helper.getItemViewType()) {
            case PostListModel.TEXT:
                setTextTypeDetails(helper, item);
                break;
            case PostListModel.IMG:
                // set img data
                setImageTypeDetails(helper, item);
                break;
            case PostListModel.LINK:
                // set imgs data
                setLinkTypeDetails(helper, item);
                break;
            case PostListModel.FILE:
                // set imgs data
                setHeaderDetails(helper, item);
                attachmentRecyclerView = helper.getView(R.id.attachment_recyclerview);
                attachmentRecyclerView.addOnItemTouchListener(new SimpleClickListener() {
                    @Override public void onItemClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                        //PostListModel postListModel = (PostListModel) baseQuickAdapter.getItem(i);
                        Toast.makeText(context, i+1+" child clicked ", Toast.LENGTH_SHORT).show();

                        Intent intent = new Intent(context, PostDetailActivity.class);
                        intent.putExtra(PostListModel.class.getSimpleName(), Parcels.wrap(item));
                        intent.putExtra("position",Parcels.wrap(i));
                        context.startActivity(intent);
                    }

                    @Override
                    public void onItemLongClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {

                    }

                    @Override
                    public void onItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {

                    }

                    @Override
                    public void onItemChildLongClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {

                    }
                });
                attachmentRecyclerView.setAttachments(item.storyModel.attachments);
                helper.addOnClickListener(R.id.attachment_recyclerview);
                break;
        }

        setButtonBarListeners(helper, item);
    }`

When ever it goes to the third case of switch the respective Activity open 3 times on a screen that my problem.

**Comment by xqwgiser** [comment]
Hello,verticalakash:
I fixed my problem with `baseViewHolder.setIsRecyclable(false)`,because Android will recycle the itemview
regardless of it's status is changed or not,so I disabled it.
But,it's not recommend.You sholud set tag for your item to identify which needs recycle or not,you can find detail in [http://stackoverflow.com/questions/29055946/expanding-recyclerview-item](url);
[http://blog.csdn.net/fangchao3652/article/details/44103945](url).
Hope I could help.
