### ISSUE TITLE
新增demo案例

### ISSUE THREAD

**Issue by CymChad** [CymChad/BaseRecyclerViewAdapterHelper#1560]
新增demo案例

**Comment by CymChad** [comment]
用于记录新增demo案例模块。

**Comment by yuekong** [comment]
朋友圈demo 在哪里啊

**Comment by CymChad** [comment]
@yuekong 由于最近比较忙还没开发

**Comment by xlyasdasd** [comment]
类似的实现https://github.com/xlyasdasd/BRVAHCircleDemo有时间再优化😂

**Comment by xlyasdasd** [comment]
类似的实现，有时间再优化😂 https://github.com/xlyasdasd/BRVAHCircleDemo

**Comment by CymChad** [comment]
@yuekong 朋友圈案例 @xlyasdasd 已上传

**Comment by zmmzhaomaomao** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1560#issuecomment-336083991
 
哈喽，“朋友圈实现”的那个Demo并没有用RecycledViewPool进行优化，请问有优化的版本吗？ 因为我在使用过程中出现过点击事件错乱的情况。

**Comment by TrueloveSomeGIRl** [comment]
> @yuekong朋友圈案例@xlyasdasd已上传
333

**Comment by TrueloveSomeGIRl** [comment]
[错误](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1560#issuecomment-336334520)
