### ISSUE TITLE
添加了头部之后，item有多个点击控件，区别不出来

### ISSUE THREAD

**Issue by DebugZeng** [CymChad/BaseRecyclerViewAdapterHelper#1561]
添加了头部之后，item有多个点击控件，区别不出来，如果去掉头部就可以，请问怎么解决![image](https://user-images.githubusercontent.com/6902555/30518775-8176ad1c-9bb9-11e7-8774-3ab89d67914d.png)

**Comment by AllenCoder** [comment]
1. 头部的点击事件 默认不处理，交由开发者自行控制，在adapter.setOnItemClickListener里面是收不到header和footer的点击事件的。
2. 不应该这样判断childview是否属于同一个对象，因为会涉及到view的复用，应该用 

```java
   switch(view.getId()){
      case xxx:
     break
    }
```
处理判断，修正代码再测试一下

**Comment by DebugZeng** [comment]
好了，谢谢
