### ISSUE TITLE
mMultipleItemAdapter.setEmptyView(mNetErrView) 没有效果

### ISSUE THREAD

**Issue by 121493359** [CymChad/BaseRecyclerViewAdapterHelper#1565]
版本：2.9.22
使用的是demo里的这个MultipleItemQuickAdapter
adapter有添加两个header和一个footer
大概步骤
1.mMultipleItemAdapter.setHeaderFooterEmpty(true,true);
2.mMultipleItemAdapter.addHeaderView(bannerView);
mMultipleItemAdapter.addHeaderView(mViewTopNavigationbar);
3.mMultipleItemAdapter.addFooterView(mViewBottomNavigationbar);
4.mNetErrView = mInflater.inflate(R.layout.view_err_net, null, false);
5.mRecyclerView.setAdapter(mMultipleItemAdapter);
在刷新onRefresh中判断没有网络回去调用mMultipleItemAdapter.setEmptyView(mNetErrView);
调试有走到setEmptyView，但是没有效果。

**Comment by 121493359** [comment]
demo被我改成这样也是无效，是否我哪里是否错误

package com.chad.baserecyclerviewadapterhelper;

import android.os.Bundle;
import android.os.Handler;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.view.ViewGroup;

import com.chad.baserecyclerviewadapterhelper.adapter.MultipleItemQuickAdapter;
import com.chad.baserecyclerviewadapterhelper.base.BaseActivity;
import com.chad.baserecyclerviewadapterhelper.data.DataServer;
import com.chad.baserecyclerviewadapterhelper.entity.MultipleItem;
import com.chad.library.adapter.base.BaseQuickAdapter;

import java.util.List;

/**
 * https://github.com/CymChad/BaseRecyclerViewAdapterHelper
 * modify by AllenCoder
 */
public class MultipleItemUseActivity extends BaseActivity {
    private RecyclerView mRecyclerView;

    private View notDataView;
    private View errorView;
    MultipleItemQuickAdapter mMultipleItemAdapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_multiple_item_use);
        setTitle("MultipleItem Use");
        setBackBtn();
        mRecyclerView = (RecyclerView) findViewById(R.id.rv_list);
        notDataView = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) mRecyclerView.getParent(), false);
        notDataView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onRefresh();
            }
        });
        errorView = getLayoutInflater().inflate(R.layout.error_view, (ViewGroup) mRecyclerView.getParent(), false);
        errorView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onRefresh();
            }
        });
        final List<MultipleItem> data = DataServer.getMultipleItemData();
        mMultipleItemAdapter = new MultipleItemQuickAdapter(this, data);

        final GridLayoutManager manager = new GridLayoutManager(this, 4);
        mRecyclerView.setLayoutManager(manager);
        mMultipleItemAdapter.setSpanSizeLookup(new BaseQuickAdapter.SpanSizeLookup() {
            @Override
            public int getSpanSize(GridLayoutManager gridLayoutManager, int position) {
                return data.get(position).getSpanSize();
            }
        });
        onRefresh();
    }

    private boolean mError = true;
    private boolean mNoData = true;

    private void onRefresh() {
        mMultipleItemAdapter.setEmptyView(R.layout.loading_view, (ViewGroup) mRecyclerView.getParent());
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                if (mError) {
                    mMultipleItemAdapter.setEmptyView(errorView);
                    mError = false;
                } else {
                    if (mNoData) {
                        mMultipleItemAdapter.setEmptyView(notDataView);
                        mNoData = false;
                    } else {
                        mRecyclerView.setAdapter(mMultipleItemAdapter);
//                        mMultipleItemAdapter.setNewData(DataServer.getSampleData(10));
                    }
                }
            }
        }, 1000);
    }

}

**Comment by 1109993488** [comment]
请参考EmptyViewUseActivity，你的demo里data有数据，只有data为空的时候才会显示emptyView

**Comment by 121493359** [comment]
多谢回复，是我使用错误


------------------ 原始邮件 ------------------
发件人: "BlingBling";<notifications@github.com>;
发送时间: 2017年9月19日(星期二) 下午5:26
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "庸sú、 ゝ"<121493359@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] mMultipleItemAdapter.setEmptyView(mNetErrView) 没有效果 (#1565)




请参考EmptyViewUseActivity，你的demo里data有数据，只有data为空的时候才会显示emptyView
