### ISSUE TITLE
不能同时添加空布局和FootView吗? 

### ISSUE THREAD

**Issue by OpenSourceMIUI** [CymChad/BaseRecyclerViewAdapterHelper#1569]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{404be9d position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}

**Comment by CymChad** [comment]
可以，`setHeaderFooterEmpty`
