### ISSUE TITLE
使用SmartRefreshLayout刷新时，刷新后onItemSwipeListener中的clearView方法没有回调

### ISSUE THREAD

**Issue by LengM** [CymChad/BaseRecyclerViewAdapterHelper#1571]
https://github.com/scwang90/SmartRefreshLayout
使用SmartRefreshLayout刷新，刷新后拖拽可以正常使用；
滑动后会出现内容消失，但item还在页面上的问题
代码：
https://github.com/MingYngLee/MyApplication/blob/master/app/src/main/java/com/yng/ming/myapplication/ui/demo/BRVAHSwipeActivity.java

**Comment by MingYngLee** [comment]
正常情况下的回调：`09-21 14:00:40.109 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeStart ---------
09-21 14:00:40.113 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.128 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.147 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.165 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.193 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.205 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.224 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.242 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.261 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.279 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.297 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.316 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.317 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwiped ---------
09-21 14:00:40.358 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.374 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.389 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.408 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.426 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.445 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.463 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.482 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.502 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:00:40.519 3831-3831/com.yng.ming.myapplication I/logcat: --------- clearItemSwipe ---------
`

刷新后：`09-21 14:01:15.013 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeStart ---------
09-21 14:01:15.015 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.033 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.051 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.070 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.089 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.107 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.126 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.144 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.163 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.181 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.200 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwipeMoving ---------
09-21 14:01:15.201 3831-3831/com.yng.ming.myapplication I/logcat: --------- onItemSwiped ---------
`

**Comment by CymChad** [comment]
内容消失，但item还在页面上的问题?  没看明白，能给出具体效果吗？

**Comment by LengM** [comment]
https://pan.baidu.com/s/1mi3Mx9A

**Comment by elfman** [comment]
@LengM 能否将你的demo源码上传到github上？

**Comment by LengM** [comment]
https://github.com/LengM/MyApplication/blob/master/app/src/main/java/com/yng/ming/myapplication/ui/demo/BRVAHSwipeActivity.java
@elfman 
这里就是
https://github.com/LengM/MyApplication

**Comment by LengM** [comment]
https://github.com/LengM/SwipeBugDemo
@elfman

**Comment by elfman** [comment]
你在往rv添加一个新的itemTouchHelper前，需要先将之前的itemTouchHelper去掉，即执行
`itemTouchHelper.attachToRecyclerView(null);`，不然后续的操作扔会在之前的adapter中进行，我在你的代码上做了补丁，你可以apply到你项目看看[https://pan.baidu.com/s/1c2KrRqw](https://pan.baidu.com/s/1c2KrRqw)。
另外，refresh时最好的做法应该只更新数据，像你现在这样把整个adapter都替换掉并不是一个好的做法

**Comment by LengM** [comment]
@elfman 好的谢谢了，已经解决了
