### ISSUE TITLE
EmptyView 与 HeaderView 不能同时显示

### ISSUE THREAD

**Issue by jarylan** [CymChad/BaseRecyclerViewAdapterHelper#1573]
使用的是最新版本；
在 demo 的 EmptyViewUseActivity 展示类中，给 Adapter 添加 HeaderView（addHeaderView方法），EmptyView 与 HeaderView 不能同时显示 。 
有数据之后才会显示 HeaderView ； 
仔细想也是这么回事，没有数据的话 HeaderView 也不显示；但是有些产品设计头部一直存在，只在列表内容区域显示 EmptyView ；

**Comment by CymChad** [comment]
可以同时显示，具体可查文档有api可以设置同时显示的 http://www.jianshu.com/p/b343fcff51b0
