### ISSUE TITLE
2.9.30版本ExpandableItemAdapter使用setNewData()方法传入数据无效

### ISSUE THREAD

**Issue by sweet2o09** [CymChad/BaseRecyclerViewAdapterHelper#1574]
ExpandableItemAdapter初始化的时候要传入一个List<MultiItemEntity> data
我先传入一个空的List<MultiItemEntity> data
然后等网络请求回来后通过setNewData()方法传递进一个新的list,结果无法显示出来,只有当初始化的时候传递进去才能显示
成功代码:
ArrayList<MultiItemEntity> list = generateData();
        mAdatper = new RoomManageAdatper(list);
        mAdatper.removeAllFooterView();
        mAdatper.addFooterView(addFooterView());
        mAdatper.setFooterViewAsFlow(true);
        mRecyclerView.setAdapter(mAdatper);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(mContext));
        mAdatper.expandAll();
失败代码:
ArrayList<MultiItemEntity> list = generateData();
        mAdatper = new RoomManageAdatper(new ArrayList<MultiItemEntity>());
        mAdatper.removeAllFooterView();
        mAdatper.addFooterView(addFooterView());
        mAdatper.setFooterViewAsFlow(true);
        mRecyclerView.setAdapter(mAdatper);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(mContext));
        mAdatper.expandAll();
        mAdatper.setNewData(list);

**Comment by sweet2o09** [comment]
mRecyclerView.setLayoutManager(new LinearLayoutManager(mContext));的问题
使用Demo里面的就GridLayoutManager 就没问题了
final GridLayoutManager manager = new GridLayoutManager(this, 3);
        manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return adapter.getItemViewType(position) == ExpandableItemAdapter.TYPE_PERSON ? 1 : manager.getSpanCount();
            }
        });
mRecyclerView.setLayoutManager(manager);

**Comment by 1940913858** [comment]
@sweet2o09 额，请问你怎么解决的？

**Comment by 1940913858** [comment]
额，只是mAdapter.expandAll();无效而已。~~~要在后面再设置一次，对吧。
