### ISSUE TITLE
Expandable多级布局折叠再打开后获取位置出错

### ISSUE THREAD

**Issue by a191532696** [CymChad/BaseRecyclerViewAdapterHelper#1575]
多级布局当中的三级布局获取当前父级Position，折叠再打开后，获取到的位置会变化，并且获取的位置有错误。

**Comment by elfman** [comment]
@a191532696 你是指第二次获取的位置错误码？那第一次获取的位置是否正确？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1591  提问请看这个，如果还有问题再重新提一个issues。
