### ISSUE TITLE
分组下如何获取子item的所有节点位置

### ISSUE THREAD

**Issue by haoyuexiyu** [CymChad/BaseRecyclerViewAdapterHelper#1577]
比如点父节点后想把父节点下的所有item都做某些操作,想要获取该父节点下的位置,怎么获取

**Comment by CymChad** [comment]
数据结构上把子item的list的放在分组的对象里面。
点击你能拿到位置，通过位置你能拿到对象，拿到对象可以通过这个对象拿到下面的list。

**Comment by haoyuexiyu** [comment]
那么反过来怎么取父item的位置呀

**Comment by CymChad** [comment]
一样的，绑定父item的信息即可。
