### ISSUE TITLE
多布局不兼容的情况

### ISSUE THREAD

**Issue by 1940913858** [CymChad/BaseRecyclerViewAdapterHelper#1578]
有个特殊需求，比如数据源data.size() = 10,   然后排版成position = 0 的时候，data.get(0),data.get(1),data.get(2) ,会显示在一个布局里，放在position  = 0的item里；
其余的size 7 个，显示在position = 1-7里。
   然后就会出现问题了，这时候我们绑定的数据是10个，导致布局会显示10个。我就想着重写itemcount方法，改成data.size()-2.   这样可以实现界面，但是上啦刷新的底部效果就加不上来了，因为我们的count写死了。  
    请问有什么好的想法么？

**Comment by CymChad** [comment]
你可以通过改变数据结构来达到你的需求而不是改变适配器。
如：data.get(0),data.get(1),data.get(2) 都放在0里面。根据不同的type来做不同的设置值的规则。

**Comment by 1940913858** [comment]
还有我发现另外一个问题，我看你那边源码，实际上是有缓存view的，但是我这边有个类似横向progressbar的view ，原先比如下载进度是，5%，10% ，15%，20%这样子，我这个progressbar原先hashcode一直是一样的，所以进度的动画衔接的上；但是我使用了brvah后，发现现在会从0%--5%， 0%--10%，0%--15%，0--20%这样子跳，也就是，查了下hashcode ，发现每次都是不一样的。我找不出原因，你的源码我也看了，确实是有缓存，我实在找不出原因啦，求救

**Comment by 1940913858** [comment]
我绑定数据是跟原先普通recyclerview一样，请求完成后，list.addall()  ,然后adapter.notifydatasetchange这样子。

**Comment by CymChad** [comment]
能提供复现demo吗？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1581
