### ISSUE TITLE
建议更新文档中的混淆配置

### ISSUE THREAD

**Issue by lookingforwt** [CymChad/BaseRecyclerViewAdapterHelper#1580]
建议混淆配置加上
```proguard
-keepclassmembers  class **$** extends com.chad.library.adapter.base.BaseViewHolder {
     <init>(...);
}
```
不然ViewHolder为Adapter的内部类时, proguard会把ViewHolder的constructor干掉

**Comment by qq1728744610** [comment]
兄弟，帮了我大忙

**Comment by CymChad** [comment]
好的

**Comment by CymChad** [comment]
多谢@lookingforwt

**Comment by CymChad** [comment]
github主页以及简书都添加上了。

**Comment by sunnyamuren** [comment]
-keepclassmembers  class **$** extends com.chad.library.adapter.base.BaseViewHolder {
     <init>(...);
}加上这个 也没有效果，控件不显示 我主要用的 BaseMultiItemQuickAdapter
