### ISSUE TITLE
convert方法，对象不一致问题

### ISSUE THREAD

**Issue by 1940913858** [CymChad/BaseRecyclerViewAdapterHelper#1581]
还有我发现另外一个问题，我看你那边源码，实际上是有缓存view的，但是我这边有个类似横向progressbar的view ，原先比如下载进度是，5%，10% ，15%，20%这样子，我这个progressbar原先hashcode一直是一样的，所以进度的动画衔接的上；但是我使用了brvah后，发现现在会从0%--5%， 0%--10%，0%--15%，0--20%这样子跳，也就是，查了下hashcode ，发现每次都是不一样的。我找不出原因，你的源码我也看了，确实是有缓存，我实在找不出原因啦，求救，比如：
     
我绑定数据是跟原先普通recyclerview一样，请求完成后，list.addall() ,然后adapter.notifydatasetchange这样子。

**Comment by 1940913858** [comment]
DownLoadProgressButton downloadPrgBar = helper.getView(R.id
                .listitem_competitive_download_prgBar);
        if (position == 0) {
            Log.e(TAG, "downloadPrgBar >>> " + downloadPrgBar.hashCode());
        }
hashcode每次都是不一样的。求解

**Comment by 1940913858** [comment]
@Override
    protected void convert(BaseViewHolder helper, AppInfo info) {

        MeituMicaDownLoadProgressButton downloadPrgBar = helper.getView(R.id
                .listitem_competitive_download_prgBar);
        if (position == 0) {
            Log.e("senfa", "downloadPrgBar >>> " + downloadPrgBar.hashCode());
        }
}

**Comment by 1940913858** [comment]
@override
protected void convert(BaseViewHolder helper, AppInfo info) {
    DownLoadProgressButton downloadPrgBar = helper.getView(R.id
            .listitem_competitive_download_prgBar);
    if (position == 0) {
        Log.e("senfa", "downloadPrgBar >>> " + downloadPrgBar.hashCode());
    }
}

**Comment by 1940913858** [comment]
我在适配器里的构造方法，直接使用postdelay一直notify ，然后打出convert方法的downloadPrgBar对象的hashcode ，一直都不是一致的，怎么会这样

**Comment by 1940913858** [comment]
请问有这个限制么？

**Comment by 1940913858** [comment]
我突然发现~~~~recyclerview的item布局的父布局，android:layout_height=""   不能设置为warp_content ,不然每个view都会重新创建，我还没跟源码，不确定是为什么。这边只能设置为match_parent

**Comment by 1940913858** [comment]
我已经把demo抽出来做了，代码和你的demo完全一样，但是我这边还是一样，不一致，但是你的demo的hashcode是一致的，超级奇怪；
求解答

**Comment by 1940913858** [comment]
@CymChad

**Comment by 1940913858** [comment]
这边好像不能传文件吧。我这demo ，就是单独啦出你的上啦的那个activity做的。
如果可以，麻烦加下q ，1940913858 ，帮忙看下demo问题。谢谢作者了~~

**Comment by 1940913858** [comment]
[http://pan.baidu.com/s/1dFGlR7j](url)

**Comment by 1940913858** [comment]
麻烦作者帮忙看下， 这个demo只是拉取你其中一个activity做的。基本完全一样，可是tag =  senfa   ，这个hashcode就不一致。很多issues卡顿问题，我觉得可能是这个原因引起的

**Comment by 1940913858** [comment]
@Override
    protected void convert(BaseViewHolder helper, Status item) {
        TextView s = helper.getView(R.id.tweetText);
        if (helper.getLayoutPosition() == 2) {
            Log.e("senfa", "bug demo convert: " + s.hashCode());
        }
}
类似就是这样，hashcode会一直变

**Comment by 1940913858** [comment]
@CymChad 谢谢，demo就是上面的baidu盘的地址。

**Comment by 1940913858** [comment]
我研究了好几天，没找到解决方案以及原因。

**Comment by 1940913858** [comment]
这个问题实在是奇葩。~~~~

**Comment by CymChad** [comment]
你的demo 访问过去 404 ，已加你Q

**Comment by CymChad** [comment]
控件的显示是根据数据对象来的，而不是根据控件对象来了，m控制v的变化，而不是v控制m的变化，v的所有变化都通过m来展示的。
