### ISSUE TITLE
GridView 数据不满一屏的情况下 loadMore一直加载

### ISSUE THREAD

**Issue by SirZhao** [CymChad/BaseRecyclerViewAdapterHelper#1582]
当设置了loadmore 为true,  下拉刷新的时候setData，数据量不满一屏时，LoadMore就一直显示，gridView   findLastCompletedPosition得到不是最后一个，而是最后一个满一行的Position。因为我不清楚屏幕到底能显示多少Item，所以setData时会出现此异常，请问有没有好的解决方案

**Comment by Y-JH** [comment]
使用这种方法就解决了：
 //上拉加载更多功能
        mRecyclerView.addOnScrollListener(new RecyclerViewScrollListener() {

            @Override
            public void stopScrolling() {
            }

            @Override
            public void startScrolling() {
            }

            @Override
            public void requestMoreListener() {
                if (layoutLoadmore.getVisibility() == View.VISIBLE)
                    return;
                mPageIndex += 1;
//                startLoadingMore();
            }

            @Override
            public boolean isRefreshingOrLoadingCallback() {
                return (layoutLoadmore.getVisibility() == View.VISIBLE ? true : false);
            }

            @Override
            public boolean isLessThanNumber() {
                return listBean.size() < 1 ? true : false;
            }
        });

**Comment by CymChad** [comment]
可以在回调里面关闭上拉监听。  mQuickAdapter.loadMoreEnd();
