### ISSUE TITLE
默认的加载更多样式, 刚显示出来是靠左的,没有居中

### ISSUE THREAD

**Issue by shitb** [CymChad/BaseRecyclerViewAdapterHelper#1583]
图片穿不上来..
一个普通列表,带加载更多,每次加载1条数据,第一次显示 加载中... 的时候是居左的,后面又会显示到中间

**Comment by CymChad** [comment]
版本，代码，图片

**Comment by Troll4it** [comment]
@shitb  你看下你的  
      recyclerview.setLayoutManager();
        recyclerview.setAdapter();这两个方法的顺序，应该先设置setLayoutManager,在设置adapter，不同的顺序，在网格列表中，会出现你问题

**Comment by shitb** [comment]
版本:2.9.28
主要代码和效果展示:下图
布局文件
<img width="535" alt="ddd" src="https://user-images.githubusercontent.com/4415390/30791274-08ca0540-a1e4-11e7-9d49-972e9b31e146.png">

代码
<img width="526" alt="ccc" src="https://user-images.githubusercontent.com/4415390/30791263-e7a15a58-a1e3-11e7-9a2d-f91b7d043020.png">

界面
<img width="396" alt="aaa" src="https://user-images.githubusercontent.com/4415390/30791270-f2e1ab52-a1e3-11e7-9b8f-a62fd607e7a6.png">

@CymChad

**Comment by shitb** [comment]
找到问题了,recyclerview宽度写错了,手残了...
