### ISSUE TITLE
关于rv嵌套rv结构，数据刷新显示的问题

### ISSUE THREAD

**Issue by yuanjun52306** [CymChad/BaseRecyclerViewAdapterHelper#1585]
我是在外层rv的adapter里创建内层的rv和adapter并绑定数据的，数据都是存储在实体类里（实体类实现了MultiItemEntity），这些解析json得到的数据在存储以后就没有再更改过。现在需求是内部的每一个rv都有两份数据（每份数据有相同数量的item，内容不同），点击footerView会在这两份数据中互相切换（同一个内层rv中），调用的是外层adapter.notifyDataSetChanged()方法，然后在convert方法里对内层rv的adapter进行setNewData()。我把这两份数据放在外层rv的adapter数据源里面的一个DATA字段中存储，当需要刷新的时候，取出对应实体类的adpter（内层rv的，在首次可见时创建的，并存储在对应的实力类中），然后取出实体类DATA字段（类型是ArrayList<ArrayList<MulEntity>> data），比如之前取的是data.get(0)，这次就取data.get(1)，然后调用内层rv的adpter.setNewData(data.get(1))进行刷新。大致流程就是这样。
现在问题是，内层的每个rv在第一次显示的时候都是正常的（item数量和内容都正常），而且切换数据也正常。但只要这个rv超出屏幕外再回来，显示的内容和item数量都不对了（显示的是此时在屏幕外的某个rv应该显示的item），或者有时候干脆就没有刷新（调试发现内层rv的convert方法没有走，不知道为什么，但是走了内层adpter.setNewData(data.get(position))这个方法，期间我让position一直在0和1之间变化，所以传到内层adapter的数据是变化的），感觉应该是rv复用的问题，但adapter是对应实体类取出来的，数据也没有改过，也调用了setNewData()方法，还是找不出原因，希望能够给予解答，谢谢！
还有一点，我发现外层的rv的adapter调用notifyItemChanged(position)和notifyDataSetChanged()方法进行刷新，结果不一样（我只想刷新内层rv，不想全部刷新，而且这两个方法都会走到内层adapter的setNewData()方法），还有就是adapter的setNewData()和replaceData()结果也不一样，总归这几个方法两两组合没有一个能正确显示的。希望能抽空给予解答，谢谢！

![20170925070231](https://user-images.githubusercontent.com/12429604/30787640-2814495c-a1c0-11e7-8f66-b6bfdc61b93e.png)

![20170925070419](https://user-images.githubusercontent.com/12429604/30787641-28152264-a1c0-11e7-9646-b6317cd99d4c.png)

![20170925070542](https://user-images.githubusercontent.com/12429604/30787642-281b8f14-a1c0-11e7-96da-82b8509471e7.png)

**Comment by CymChad** [comment]
能否提供一个demo给我，我这边来调试看一下，我会怀疑是 数据没换过来。

**Comment by yuanjun52306** [comment]
你好，感谢百忙之中抽空帮我调试，我写了个demo放到附件里了，你看一下是哪里出了问题，谢谢！


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年9月25日(星期一) 下午5:37
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "有经验的开发人员"<384511594@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 关于rv嵌套rv结构，数据刷新显示的问题 (#1585)




能否提供一个demo给我，我这边来调试看一下，我会怀疑是 数据没换过来。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
         
  


从QQ邮箱发来的超大附件

Demo0925.zip (25.54M, 2017年10月25日 20:39 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=77326335f72903c65c1c88231162561701055000020152591b03010d054f500900004e0c560001155002020c555a010803510102376e647c535f0c050e5051164c5b13350a&code=62c57bd8

**Comment by yuanjun52306** [comment]
我还上传了一份到百度网盘
https://pan.baidu.com/s/1jIcMiwQ

**Comment by CymChad** [comment]
我看了下你的demo，你这边只是简单的还了当前的数据源并没有把主要的数据源换掉所以数据变化是正常的。

**Comment by CymChad** [comment]
举个例子，你遍历是一个list，然后你换一换是把list的其中一项给重新赋予的新的内容然后刷新，这个时候内容变了，但是你没有改变list里面内容所以滑动过来数据还是有问题的，为什么换一换内容就不变了，那是因为你通过tag来改变内容，将内容改变后tag的值你都没变，tag一直是一样的所以换一换也不会改变内容。

**Comment by CymChad** [comment]
解决办法
1. 改变数据的同时需要改变数据源list的内容，而不只是改变当前item的adapter内容。
2. 改变数据的同时需要改变数据源tag的标示，而不是不管tag。

**Comment by CymChad** [comment]
你可以参考下这个案例，这个案例就是改变item内容的同时改变了data的内容，所以做到了数据不错乱。
[实现三级伸缩，并解决多选框的复用](https://github.com/Sky0202/About_BRVAH)

**Comment by CymChad** [comment]
你的例子和这个例子很像，你只做了第一步，改变了控件本身的数据显示，而忽略了第二步，改变数据源的内容。

**Comment by yuanjun52306** [comment]
你好，首先我这个tag的值已经在[换一换]的点击事件里更改了，而且每个内层rv在第一次可见的时候都是可以正常切换数据的。其次我不太懂这个[数据源list的内容]和这个[当前item的adapter内容]有什么区别，adapter.setNewData()这个方法不是给adapter里的mData重新赋值吗，我都给adapter一个新的数据源了，就没必要更改数据源的内容了吧，而且所有数据都是解析json以后就没有再更改过，只是保存到是实体类里了，只有get没有set。你运行demo试一下，从内层第一个rv到内层最后一个rv，在他们第一次可见的时候点击[换一换]，都是正常的，如果tag值没有更改，或者数据源有问题，这里就不应该是正常的了。

关于数据结构，我举个例子，比如一般情况下，内层rv数据源是6个苹果(添加到1个list里)，现在我需要[换一换]功能，再加入6个梨，也就是2个list，而adapter要求数据源只能是一个list，我就把这2个list放到1个新的list里，也就是list套list，再把这个新的list存储到外层rv里实体类的DATA字段，用tag标识索引，每次点击[换一换]，我只需要从外层rv的list里取出相应的子list然后给到内层rv的adapter就可以了吧，没必要改变子list的内容，因为两个子list本来就不一样，我总不能把6个苹果再换成6个香蕉吧。

昨天我看到网上一篇帖子，也是rv嵌套rv结构，出现的问题和我一样，都是滑下来没问题，滑上去就乱了，他的解决方法是不嵌套，只使用一个rv，在数据结构上做处理的，但是他那个不需要局部刷新，和我的需求不一致。

我也试过上面这种方案，滑动数据显示完全没问题，就是没法加入[换一换]功能，感觉这个问题只出现在rv嵌套的结构中。有没有rv嵌套rv的demo可以看一下？或者能抽空简单做个嵌套结构的demo吗？

你说的那个三级树的demo我看了，他是根据bean的isChecked属性每次更新checkBox的状态以保证刷新数据的正确性，而我这个也同样根据bean的内容在更新状态，不管什么状态，if和else都有的。

**Comment by yuanjun52306** [comment]
我在给内层adapter设置新的数据源时，通过log打印这个新数据源list的size，发现size永远都是对的，可显示出来的item数量有的就不对了


![20170926163452](https://user-images.githubusercontent.com/12429604/30850647-b31aa744-a2d8-11e7-9247-090daf948dce.png)

**Comment by CymChad** [comment]
adapter.setNewData()这个方法是给当前item的rv赋值，这个赋值只是改变当前item的数据显示。
我说的给list赋值是指给最外层的rv的list赋值。

**Comment by CymChad** [comment]
嵌套rv在demo里面的itemclickatc里面有一个案例。

**Comment by CymChad** [comment]
其实你的数据错乱就是和缓存一样，你的rv数据好比状态，你只是改变了当前item的数据而并没有记录在最外层的数据源中，所以导致滑动之后又回到之前的状态。

**Comment by yuanjun52306** [comment]
我明白你的意思了，可是外层rv在itemType=RECYCLER_VIEW的实体类里只存放了内层rv的两个list和tag索引，这个位置的item状态只是根据tag值取出相应的list数据给内层rv，而tag值我也相应的修改了，而且是在外层rv相应的实体类改的，也就是[记录在最外层的数据源中]，[给最外层的rv的list赋值]，而且我一直改的都是外层rv的实体类，内层数据都是从外层取的。


![20170926170515](https://user-images.githubusercontent.com/12429604/30852312-f18cd722-a2dd-11e7-8462-4e0f365296a7.png)


![20170926171030](https://user-images.githubusercontent.com/12429604/30852315-f1c42740-a2dd-11e7-98dd-d4d9d02345d9.png)

**Comment by yuanjun52306** [comment]
谢谢你的帮助，我参考了你的那个demo里的itemClickAdapter关于嵌套rv的写法，问题解决了，数据刷新显示正常，滑动后也显示正常，原来不是数据状态的问题，是每次滑动到内层rv都需要在外层adapter的conver方法里重新调用内层rv的setAdapter方法，如果只是调用内层adapter.setNewData()就会出问题（因为我想的是把内层adapter缓存起来放到外层rv的实体类里，每次只需要set新的数据就可以了，但是貌似不行），至于内层rv和adapter的引用，缓存或重新new的显示结果都一样，你的demo里没有缓存rv和adapter，每次都是重新new一个新的Adapter，然后重新setAdapter，不知道这样做性能方面会不会有影响，但是显示是正确的。再次感谢大神的无私奉献！

**Comment by CymChad** [comment]
ok，问题解决就好，这个性能不影响，因为你的内容不会太多。

**Comment by roybill** [comment]
请问一下,我现在是一个垂直的RV,然后子item都是多布局,其中有两条item是水平的RV,但是水平的RV会数据错乱.比如水平的RV中有点击"关注"的按钮,点击后变为"已关注".这种问题应该怎么解决呢?这是水平RV的adapter代码:
  @Override
    public void convert(@NotNull BaseViewHolder helper, FocusBean.DataBean.ListBean listBean) {
        RecyclerView recyclerView = helper.getView(R.id.rv_home_focus_horizontal_list);
        List<FocusBean.DataBean.ListBean> data = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            FocusBean.DataBean.ListBean bean = new FocusBean.DataBean.ListBean();
            data.add(bean);
        }
        if (adapter == null) {
            LinearLayoutManager manager = new LinearLayoutManager(getContext());
            manager.setOrientation(LinearLayoutManager.HORIZONTAL);
            recyclerView.setLayoutManager(manager);
            adapter = new FocusHorizontalListAdapter(R.layout.multiple_item_focus_horizontal, data);
            LogUtils.d("0855   55555");
            recyclerView.setAdapter(adapter);
            adapter.addChildClickViewIds(R.id.tv_group_focus);
            adapter.setOnItemChildClickListener(new OnItemChildClickListener() {
                @Override
                public void onItemChildClick(@NonNull BaseQuickAdapter adapter, @NonNull View view, int position) {
                    Toast.makeText(getContext(), "点击了" + position, Toast.LENGTH_SHORT).show();
                    FocusBean.DataBean.ListBean listBean = data.get(position);
                    listBean.setFocused(listBean.isFocused() ? false : true);
                    adapter.notifyItemChanged(position);
                }
            });
//        }else{
//            recyclerView.setAdapter(adapter);
        }
    }

**Comment by LoveDoDo** [comment]
[每次滑动到内层rv都需要在外层adapter的conver方法里重新调用内层rv的setAdapter方法]，配合setNewData()试一试吧，我已经好久不写嵌套rv了，大神的新版本应该已经有了更简便的方法，多看看Demo，数据错乱就重新设置新数据，确保新设置的数据状态是正确的就一定不会错乱

**Comment by roybill** [comment]
水平RV的adapter我是这样设置的,但是不行,关于我这个写法有什么好的建议呢?
 @Override
    public void convert(@NotNull BaseViewHolder helper, FocusBean.DataBean.ListBean listBean) {
        RecyclerView recyclerView = helper.getView(R.id.rv_home_focus_horizontal_list);
        List<FocusBean.DataBean.ListBean> data = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            FocusBean.DataBean.ListBean bean = new FocusBean.DataBean.ListBean();
            data.add(bean);
        }
        if (adapter == null) {
            LinearLayoutManager manager = new LinearLayoutManager(getContext());
            manager.setOrientation(LinearLayoutManager.HORIZONTAL);
            recyclerView.setLayoutManager(manager);
            adapter = new FocusHorizontalListAdapter(R.layout.multiple_item_focus_horizontal, data);
            LogUtils.d("0855   55555");
            recyclerView.setAdapter(adapter);
            adapter.addChildClickViewIds(R.id.tv_group_focus);
            adapter.setOnItemChildClickListener(new OnItemChildClickListener() {
                @Override
                public void onItemChildClick(@NonNull BaseQuickAdapter adapter, @NonNull View view, int position) {
                    Toast.makeText(getContext(), "点击了" + position, Toast.LENGTH_SHORT).show();
                    FocusBean.DataBean.ListBean listBean = data.get(position);
                    listBean.setFocused(listBean.isFocused() ? false : true);
                    adapter.notifyItemChanged(position);
                }
            });
        }else{
            recyclerView.setAdapter(adapter);
        }
    }
