### ISSUE TITLE
树形列表添加header后，点击展开关闭recyclerview滚动问题

### ISSUE THREAD

**Issue by KingsleyCheng** [CymChad/BaseRecyclerViewAdapterHelper#1586]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/20455499/30791043-7995683e-a1e2-11e7-84ce-160edbbf2836.gif)
从“员工一览”往上为header，下面问树形列表recyclerview，进入页面，向下滑动到可展开item时，点击展开，关闭列表没有问题；但是，进入页面向下滑动到可展开item，完后再向上滑动一下，这时候点击展开，关闭列表，整个布局就会向下滚动，点击的那个item被滚动到屏幕下方外面，看不到了。

       //员工一览recyclerview
        RecyclerView mRecyclerView = (RecyclerView) findViewById(R.id.staff_list_rv);
        LinearLayoutManager layoutManager = new LinearLayoutManager(this);
        mAdapter = new MineCompanyStaffAdapter(null);
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());
        mRecyclerView.setLayoutManager(layoutManager);

        mAdapter.openLoadAnimation(BaseQuickAdapter.SCALEIN);
        mAdapter.isFirstOnly(true);
        mRecyclerView.setAdapter(mAdapter);
        mAdapter.setOnItemChildClickListener(this);

        //添加头（我的公司信息）
        View headerView = this.getLayoutInflater().inflate(R.layout.activity_mine_company_header, (ViewGroup) mRecyclerView.getParent(), false);
        mAdapter.addHeaderView(headerView);
        mCompanyNameEt = (EditText) headerView.findViewById(R.id.company_name_et);
        mEmailEt = (EditText) headerView.findViewById(R.id.email_tv);
        mTelEt = (EditText) headerView.findViewById(R.id.tel_et);
        mCompanyAddressEt = (EditText) headerView.findViewById(R.id.company_address_et);
        mIntroduceEt = (EditText) headerView.findViewById(R.id.introduce_et);
        mIntroduceEt.setOnTouchListener(this);
        mSelectBusinessType = (TextView) headerView.findViewById(R.id.select_business_type);
        mSelectBusinessTypeIv = (ImageView) headerView.findViewById(R.id.select_business_type_iv);
        mInviteTv = (TextView) headerView.findViewById(R.id.invite_tv);
        mInviteListView = (ListView) headerView.findViewById(R.id.invite_lv);
        setListViewHeightBasedOnChildren(mInviteListView);
        mStaffNumTv = (TextView) headerView.findViewById(R.id.staff_num_tv);

        mItemEntities.addAll(mInvitePersonLevelOnes);
        mAdapter.setNewData(mItemEntities);
        mAdapter.setType1Num(numOne1);
        mAdapter.setType2Num(numOne2);

**Comment by elfman** [comment]
@KingsleyCheng 能否给个GIF图演示一下？

**Comment by elfman** [comment]
@KingsleyCheng 你能否在demo上做修改复现出这个bug，再提交个commit到github上，以方便我们查找问题

**Comment by KingsleyCheng** [comment]
好的，我抽时间，做一下
