### ISSUE TITLE
建议封装下ItemAnimation

### ISSUE THREAD

**Issue by heyleon** [CymChad/BaseRecyclerViewAdapterHelper#1587]
用的是目前最新的代码,需要对item中的某个view做一些动画效果.自己改写的话直接在convert方法中设置的话不执行,需要刷新一次才执行

**Comment by CymChad** [comment]
ItemAnimation是通过rv设置的，这个和adapter貌似没什么关系。

**Comment by heyleon** [comment]
= =大神我仔细研究了一下发现重写onbindviewholer这个方法可以实现进入动画就加载
而在convert方法中则需要刷新一次动画才运行~

**Comment by CymChad** [comment]
convert方法其实就是onbindviewholer的封装呀
