### ISSUE TITLE
恢复网络连接后，没有上拉加载出新数据

### ISSUE THREAD

**Issue by SiXuManYan** [CymChad/BaseRecyclerViewAdapterHelper#1589]
作者您好，我在使用过程中发现了一个小疑惑，无意冒犯：

 测试时我手动干预了一下网络连接状态（断掉wifi和重新链接wifi），然后恢复网络连接后，没有自动加载出新数据，我猜测是没有回调onLoadMoreRequested（）；

步骤如下：
       先断网，然后进行上拉加载，BaseRecyclerViewAdapterHelper会根据我所设置的回调（如：loadMoreComplete，loadMoreEnd，loadMoreFail）在底部显示一层LoadingView。此时重新链接wifi,数据没有加载出来。

这是我使用上的问题吗？

版本：
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.28'

使用代码：

`
@EFragment(R.layout.yh_frgm_attention)
public class AttentionFragment extends BaseFragment implements SwipeRefreshLayout.OnRefreshListener, BaseQuickAdapter.RequestLoadMoreListener {

    @ViewById
    RecyclerView recyclerview;
    @ViewById
    SwipeRefreshLayout swipe_refresh;
    @Bean
    MyAttentionAdapter2 mAdapter;
    @Bean
    ConcernListPresenter concernListPresenter;
    @Bean
    AreaPrefUtil areaPrefUtil;

    private ImageLoader imageLoader;
    private int pageNumber = 0;
    private boolean last = false;

    @AfterViews
    void AfterView() {

        initPresenter();
        initView();
        getData(getYString(R.string.requesting));
    }

    protected void initView() {

        swipe_refresh.setOnRefreshListener(this);
        swipe_refresh.setColorSchemeResources(R.color.color_FFE6503D);
        imageLoader = ImageLoader.getInstance();

        mAdapter.init(imageLoader, OptionsUtil.getListOptions(), dc, dc.getContact());

        mAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                toast("onItemClick");
            }
        });

        mAdapter.setOnLoadMoreListener(this, recyclerview);
        mAdapter.disableLoadMoreIfNotFullPage(recyclerview);
        recyclerview.setAdapter(mAdapter);
    }

    protected void getData(String msg) {
        ConcernListRequestBean bean = ConcernListRequestBean_.getInstance_(getActivity());
        bean.pageNumber = pageNumber;
        concernListPresenter.doFragment(bean, msg, this, new OnCallBackListener<ConcernListResponseBean>() {
            @Override
            public void onSuccess(ConcernListResponseBean responseBean) {
                swipe_refresh.setRefreshing(false);

                dismissProgressDialog();

                String resultCode = responseBean.resultCode;
                switch (resultCode) {
                    case CommResultCode.CODE_1001:
                        if (responseBean.data == null) {
                            return;
                        }
                        if (responseBean.data.concernList.isEmpty()) {
                            if (pageNumber == 0) {
                                toast("show emptyView");
                            }
                            return;
                        }
                        last = responseBean.data.isLast;
                        if (pageNumber == 0) {
                            mAdapter.setNewData(responseBean.data.concernList);
                            mAdapter.setEnableLoadMore(!last);
                        } else {
                            mAdapter.addData(responseBean.data.concernList);
                            if (last) {
                                mAdapter.loadMoreEnd();  // 加载结束
                            } else {
                                mAdapter.loadMoreComplete(); // 加载完成
                            }
                        }
                        break;
                    default:
                        break;
                }
            }

            @Override
            public void onError(int errorCode) {
                dismissProgressDialog();
                toast(getYString(R.string.net_error) + errorCode);
                if (pageNumber != 0) {
                    // 加载失败
                    mAdapter.loadMoreComplete(); // 加载完成
                }
            }
        });

    }

    @Override
    public void initPresenter() {
        concernListPresenter.setOnHttpProgressDialogListener(this);
    }

    @Override
    public void onRefresh() {
        // 本页面不需要下拉刷新
        swipe_refresh.setRefreshing(false);
    }

    @Override
    public void onLoadMoreRequested() {
        pageNumber++;
        getData("");
    }
}`

**Comment by CymChad** [comment]
demo 有模拟网络不好的案例，你可以看看。

**Comment by CymChad** [comment]
当网络恢复了不会自动加载数据需要主动触发

**Comment by 1109993488** [comment]
onError需要调loadMoreFailed

**Comment by SiXuManYan** [comment]
我明白了，谢谢大家~
