### ISSUE TITLE
加载数据以后这个RecyclerView重新加载

### ISSUE THREAD

**Issue by wangmingqiang** [CymChad/BaseRecyclerViewAdapterHelper#1590]
大神我的适配器在setOnLoadMoreListener加载更多数据以后，给适配器设置了notifyDataSetChanged()不管用还是会从第一条开始显示
   小弟很菜    希望大神给个建议

**Comment by CymChad** [comment]
demo有案例，你可以看看。https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java
