### ISSUE TITLE
继承BaseMultiItemQuickAdapter，不走convert方法

### ISSUE THREAD

**Issue by ApeForProgram** [CymChad/BaseRecyclerViewAdapterHelper#1596]
版本：2.9.28
![3hkwqn 4z p4r j c_r t](https://user-images.githubusercontent.com/15900889/30848163-d24350a6-a2d0-11e7-92b4-bc85e826c17a.png)
![j al d2kkmwn 4 rwoq0](https://user-images.githubusercontent.com/15900889/30848285-4cc4ac62-a2d1-11e7-8e1c-402429a76a29.png)
![default](https://user-images.githubusercontent.com/15900889/30848502-e5af08f0-a2d1-11e7-866c-4ec3c97b630c.png)
convert的log不打印，方法也没走，这是为什么

**Comment by ApeForProgram** [comment]
请问作者可以给个方便的联系方式么，qq群什么的

**Comment by CymChad** [comment]
看下你rv的设置，是不是没有设置布局管理器？

**Comment by CymChad** [comment]
http://www.recyclerview.org/ 有qq群

**Comment by ApeForProgram** [comment]
@CymChad qq群我搜了，说没有符合要求的群

**Comment by ApeForProgram** [comment]
@CymChad 
![z9bnm ppr t 3z au o](https://user-images.githubusercontent.com/15900889/30849430-ed056d9e-a2d4-11e7-8586-4ee6c8834781.png)
用的v7默认的

**Comment by CymChad** [comment]
截图看下rv设置的代码

**Comment by ApeForProgram** [comment]
@CymChad 
![z9bnm ppr t 3z au o](https://user-images.githubusercontent.com/15900889/30849614-7cf1419e-a2d5-11e7-9377-d278ec9dbed6.png)

**Comment by CymChad** [comment]
能抽取出一个demo给我吗？我这边帮你调试一下。

**Comment by ApeForProgram** [comment]
@CymChad 怎么给到你

**Comment by ApeForProgram** [comment]
@CymChad 我再研究一下，感谢你。我看看根据你的方向再试试

**Comment by CymChad** [comment]
上传到网盘，或者放在git上面，给我连接就好了。
这种情况
1.没有设置布局管理器
2.数据源问题
3.item布局高度全屏了

**Comment by ApeForProgram** [comment]
@CymChad 好的好的，我先自己研究一下，看看我写的到底哪里出了问题。感谢感谢

**Comment by CymChad** [comment]
恩 好的。

**Comment by CymChad** [comment]
问题解决了吗？

**Comment by ApeForProgram** [comment]
@CymChad 解决了，我在继承了adapter之后，onbindviewholder也自动生成出来了，之前我都是把这个生成的代码删掉了，昨天写的时候忘了删除，里面没有调用super，所以就这样了。谢谢你啦，可以关了
