### ISSUE TITLE
改变HeaderView的高度布局总是向上扩展，怎么能让HeaderView变高是向下扩展

### ISSUE THREAD

**Issue by CodingHornet** [CymChad/BaseRecyclerViewAdapterHelper#1597]
我目的是想在HeaderView里用ExpandableLayout，结果发现ExpandableLayout每次展开都向上展开，后来我换成设置控件显隐测试也是这样的效果。

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

    <TextView
        android:id="@+id/toggle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="20dp"
        android:text="切换"/>

    <TextView
        android:id="@+id/two"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/holo_blue_light"
        android:padding="20dp"
        android:text="
    sample.sample.sample.sample.sample.sample.sample.sample.sample.sample.\n
    sample.sample.sample.sample.sample.sample.sample.sample.sample.sample.\n
    "
        android:textColor="@color/white"/>

</LinearLayout>

```
```
View headerView = getLayoutInflater().inflate(R.layout.header_negotiate_detail,
                (ViewGroup) mRecycler.getParent(), false);
        TextView toggle = (TextView) headerView.findViewById(R.id.toggle);
        final TextView two = (TextView) headerView.findViewById(R.id.two);
        toggle.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                two.setVisibility(two.getVisibility() == View.VISIBLE ? View.GONE : View.VISIBLE);
            }
        });

        mCommentAdapter.addHeaderView(headerView);`
```

**Comment by 1109993488** [comment]
你是如何改变HeaderView的高度的？

**Comment by CodingHornet** [comment]
@1109993488 直接设置HeaderView里子控件的显隐

**Comment by CodingHornet** [comment]
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

    <TextView
        android:id="@+id/toggle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="20dp"
        android:text="切换"/>

    <TextView
        android:id="@+id/two"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/holo_blue_light"
        android:padding="20dp"
        android:text="
    sample.sample.sample.sample.sample.sample.sample.sample.sample.sample.\n
    sample.sample.sample.sample.sample.sample.sample.sample.sample.sample.\n
    "
        android:textColor="@color/white"/>

</LinearLayout>`

`View headerView = getLayoutInflater().inflate(R.layout.header_negotiate_detail,
                (ViewGroup) mRecycler.getParent(), false);
        TextView toggle = (TextView) headerView.findViewById(R.id.toggle);
        final TextView two = (TextView) headerView.findViewById(R.id.two);
        toggle.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                two.setVisibility(two.getVisibility() == View.VISIBLE ? View.GONE : View.VISIBLE);
            }
        });

        mCommentAdapter.addHeaderView(headerView);`

**Comment by 1109993488** [comment]
我再demo里试的没问题，你的列表里有嵌套RecyclerView吗？

**Comment by CodingHornet** [comment]
@1109993488 没有，我的代码就像上面贴的，很简单

**Comment by 1109993488** [comment]
要显示的view顶部在外面就会上移，如果完全显示就不会有问题，RecyclerView本身就是这样的

**Comment by CodingHornet** [comment]
@1109993488 隐藏上移是我想要的，主要现在是view显示也是往上移

**Comment by 1109993488** [comment]
你在demo里加试试，或者提供个demo

**Comment by CodingHornet** [comment]
@1109993488 我用demo改的效果确实正常

**Comment by CymChad** [comment]
如果在demo里面是正常的，就请对比一下代码，如果还是没有发现任何问题，可以提供一个有问题的demo，便于我们这边快速查找解决。 @CodingHornet

**Comment by CodingHornet** [comment]
@CymChad 嗯，我打算再在正式项目里尝试一下

**Comment by CymChad** [comment]
ok，有问题随时联系。
