### ISSUE TITLE
树形列表 bug 连续两个数据打开树形列表。点击第二个打开的item关闭子item，会造成显示bug

### ISSUE THREAD

**Issue by PokerMman** [CymChad/BaseRecyclerViewAdapterHelper#1598]
树形列表 bug 连续两个数据打开树形列表。点击第二个打开的item关闭子item，会造成显示bug。
例如 我们打开了父item0，显示了   子item0。父item1，显示了   子item1。
点击父item1 会关闭子item1，但是子item0会跑到父item1下面

**Comment by elfman** [comment]
@PokerMman 能否给一个可复现的demo

**Comment by PokerMman** [comment]
稍等

**Comment by PokerMman** [comment]
demo 中的例子子item 数据 指向了同一个所以会发送这种错误
@elfman

**Comment by qinyang1018** [comment]
@PokerMman   请问下 这个问题你解决了吗？

**Comment by hellosuperX** [comment]
同问，如何解决的
