### ISSUE TITLE
2.1.6版本

### ISSUE THREAD

**Issue by DoomTeam** [CymChad/BaseRecyclerViewAdapterHelper#1599]
通过recycleView添加addOnItemTouchListener，再修改recycleView的适配器，会取不到修改的adapter，以及数据源，导致点击的数据源一直是第一个数据源。

**Comment by AllenCoder** [comment]
点击接口使用最新的 adapter.setOnItemClickListener(),
或者每次切换完adapter remove掉recyclerview的ItemTouch接口，重新添加
