### ISSUE TITLE
这样布局的时候，内容列表的RecyclerView只能显示一条数据，有解决方法不

### ISSUE THREAD

**Issue by cbfg5210** [CymChad/BaseRecyclerViewAdapterHelper#160]
这样布局的时候，内容列表的RecyclerView只能显示一条数据：
	<LinearLayout>
	<android.support.v7.widget.Toolbar>
	</android.support.v7.widget.Toolbar>

	<android.support.v4.widget.DrawerLayout>
	
	<android.support.v7.widget.RecyclerView>
	</android.support.v7.widget.RecyclerView>
	<!--侧滑菜单->
	<android.support.v7.widget.RecyclerView>
	</android.support.v7.widget.RecyclerView>
	</android.support.v4.widget.DrawerLayout>
	</LinearLayout>

**Comment by CymChad** [comment]
没有做过此类布局，所以无法提供解决方案，非常抱歉。
