### ISSUE TITLE
item  android:visibility="gone" 无效

### ISSUE THREAD

**Issue by KeqingLI** [CymChad/BaseRecyclerViewAdapterHelper#1600]
2.9.28 版本后  如果在item的布局文件中 其一子布局有android:visibility="gone" ，实际效果上item的高度会是 android:visibility="visibility" 时的高度

**Comment by KeqingLI** [comment]
2.9.27正常

**Comment by CymChad** [comment]
Change the method setVisible --> setGone
The new method setVisible

setVisible:Set a view visibility to VISIBLE (true) or INVISIBLE (false).
setGone: Set a view visibility to VISIBLE (true) or GONE (false).

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases

**Comment by CymChad** [comment]
2.9.28 版本更新了，更新日记，以及文档上都注明了。

**Comment by KeqingLI** [comment]
3Q
