### ISSUE TITLE
关于多级展开功能的一点建议

### ISSUE THREAD

**Issue by AcgnCodeMonkey** [CymChad/BaseRecyclerViewAdapterHelper#1603]
找了一下，貌似没人提，多级展开一般在项目中也都是以层级的形式存在的，但是目前来讲，本库必须要求平铺数据，这个在使用的时候真的很蛋疼，如果能有办法支持平级和层级数据的多级展开就完美了

**Comment by CymChad** [comment]
你是说数据结构吗？

**Comment by CymChad** [comment]
如果是数据结构可以由开发者来自己组合的

**Comment by CymChad** [comment]
只要实现IExpand这个接口就可以了，具体你可以看看demo源码。
