### ISSUE TITLE
你好，遇到一个这样的问题，就是和刷新控件嵌套使用的时候，只要一设置数据或者设置EmptyView，就会导致刷新手势失效，

### ISSUE THREAD

**Issue by xicong** [CymChad/BaseRecyclerViewAdapterHelper#1606]
刚发现好像是因为添加头部导致的，并且我的头部内容比较多

**Comment by xicong** [comment]
同样的写法，在activity却没有遇到类似的问题

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1605

**Comment by CymChad** [comment]
请提供案例，demo无法复现。

**Comment by xicong** [comment]
好的，发你邮箱吗？

**Comment by CymChad** [comment]
上传到github，给我个链接就好了。

**Comment by xicong** [comment]
已经通过qq发送给你了

**Comment by CymChad** [comment]
在吗？你qq在m我一下，我这边信息太多了。找不到你的信息了。

**Comment by CymChad** [comment]
由于无法正常运行你的demo，需要你上传一个github地址的demo上来并且重新开个issues ，我叫人帮你看下。

**Comment by xicong** [comment]
https://github.com/zhouoryou/GolfersIntelligence
