### ISSUE TITLE
使用Gradle build项目提示：Error:(200, 18) 错误: 编码GBK的不可映射字符

### ISSUE THREAD

**Issue by guominfang** [CymChad/BaseRecyclerViewAdapterHelper#1607]
![qq 20170929163413](https://user-images.githubusercontent.com/24568042/31007770-37383886-a534-11e7-8a74-1411e49cbfa7.png)

**Comment by guominfang** [comment]
点击这些错误会跳转到 
![_20170929163652](https://user-images.githubusercontent.com/24568042/31007846-74b509f0-a534-11e7-9bfa-d85584ce24b7.png)

**Comment by CymChad** [comment]
http://blog.csdn.net/sljjyy/article/details/11976099
