### ISSUE TITLE
调用ScrollBy报错

### ISSUE THREAD

**Issue by chuwe1** [CymChad/BaseRecyclerViewAdapterHelper#1608]
Added View has RecyclerView as parent but view is not a real child.
偶尔出现，已经是最新版的了

**Comment by CymChad** [comment]
复现场景是？

**Comment by chuwe1** [comment]
item有2个或者3个的时候 而且有个人很长的header 绝对超过屏幕高度 一调用 scrollby 或者scrollToPosition(0) 就出现这个错误

**Comment by chuwe1** [comment]
不是 100% 复现 要看脸的

**Comment by CymChad** [comment]
能不能抽出一个复现demo？我这边看下。
