### ISSUE TITLE
对加载脚布局显示的不解想法

### ISSUE THREAD

**Issue by rcjs** [CymChad/BaseRecyclerViewAdapterHelper#1609]
大佬好，我的对上拉加载的处理有些不同的想法。
我不懂为什么要setnewdata里去开启显示加载脚布局。我个人有些别的想法：
我认为的显示上拉加载布局的思路可以是：
第一次加载时，他处于的状态是配置adapter后的状态，这个时候，由于set监听,会使加载脚布局开启。但何不关闭，在第一次加载即setnewdata方法里，回调一个是否要开启加载脚布局的接口A。由用者去根据pagesize判断要不要显示脚布局。
第二次加载起，用adddata里，不需要回调这个接口A了。
下拉刷新，刷新成功后，用的还是setnewdata，那还是能回调接口A，由用者去根据pagesize判断要不要显示脚布局。
我在brvah群里，仁昌居士

**Comment by 1109993488** [comment]
你说的这种方法跟自己在setNewData或addData后判断是否还有更多来关闭加载更多是一样的，只是写法不一样。你说的用addData里，不需要回掉这个接口A了是什么意思？

**Comment by CymChad** [comment]
@1109993488 我和 @rcjs 聊过，他的意思是能不能一开始不显示加载布局。默认不开启上拉监，等setNewData（第一次加载数据）的时候在开启。这样就可以首次进入页面不显示正在加载的尾部了。

**Comment by CymChad** [comment]
我们现在的做法是一开始就显示加载布局，等数据来了之后然后隐藏加载布局，在等数据的过程中会显示加载中的布局。而 @rcjs 的想法是第一次能不能不显示这个加载中的布局。而是等第一次加载数据完毕后在去显示这个加载中的尾部布局。

**Comment by rcjs** [comment]
我的想法如下：
同@CymChad 所说的一样。
加载更多脚布局的一开始显示，我认为可以不需要，默认初始就是不显示脚布局的。

我个人在使用brvah的刷新写法时，是这么写的：
1、第一次加载和下拉刷新 setNewData
2、非第一次加载即上拉加载
   2.1 上拉加载成功，且有新数据，则addData添加新数据，且允许继续上拉加载功能
   2.2 上拉加载成功，但没有新数据，则显示“没有新数据”脚布局或者是“什么也不显示”，且不允许继续上拉加载功能
   2.3 上拉加载失败，显示“加载失败”脚布局，且允许重新加载。

然后，我对于开启是否能加载更多功能这个，抱有如下想法：
1.库里加一个接口：专门用来在填充完数据后，进行回调。假设这个接口叫A。
2.一个开关型方法：
   2.1 打开上拉加载功能，且显示上拉加载脚布局（里面还能改变显示的脚布局的内容，比如：“正在加载中”、“加载失败”）。
   2.2 关闭上拉加载功能，且
        2.2.1 根据需求，选择显示上拉加载脚布局，如“没有新数据”。
        2.2.2 根据需求，选择不显示上拉加载脚布局，如“没有新数据下什么也不显示”。

我们可以在这个接口里写是否要显示加载更多脚布局。
1、当我第一次加载和下拉刷新完后，setNewData后，回调了接口A，里面由使用者决定是否<=allRequestCount，是则打开上拉加载功能,且显示上拉加载脚布局；否，则关闭上拉加载功能,且不显示上拉加载脚布局。
2、当我非第一次加载即上拉加载时，
   2.1 上拉加载成功，且有新数据，则addData添加新数据后，回调了接口A，
且由使用者决定是否<=allRequestCount，是则不用操作什么（也可以再次重复进行打开上拉加载功能的操作）,且显示上拉加载脚布局；
否，则没有新数据，即关闭上拉加载功能,且显示“没有新数据”脚布局或者是“什么也不显示”，且不允许继续上拉加载功能
   2.3 上拉加载失败，显示“加载失败”脚布局，且允许重新加载。

这个想法是不考虑disableLoadMoreIfNotFullPage()、与setOnLoadMoreListener

**Comment by 1109993488** [comment]
setNewData开启加载更多是因为之前考虑到设置了RequestLoadMoreListener回调后就表示这个页面是分页请求的数据，就默认开启了加载更多，没有更多的时候就关闭就行
之前就有人提过有这个默认就是关闭的想法，但是考虑到如果修改后需要主动调方法开启加载更多会出兼容问题(除非增加新的方法替代setNewData）（或者增加个方法设置加载更多默认关闭的方式，但是这种使用的时候需要调一下，有点麻烦），这种就需要手动调方法开启
关于回调接口A这个回调完全可以写方法自己在加载更多后去调下这个方法判断开启关闭加载更多，回调判断也有局限（比如服务器返回的数据中有个是否还有更多数据，这时候回调就不好去取这个字段）当然可以提供这个回调，自己写方法或用回调都可以。
你看下我的理解对吗，再讨论下兼容问题

**Comment by rcjs** [comment]
首先，我的那个建议加个接口A，是在不删除其他几个接口的情况下，去加个接口A。也就代表了，不会影响老用户的写法。相当于他们在那个回调里什么都不写。甚至是不设置这个接口A的监听。继续按老的写法来。
其次，setNewData开启加载更多，这个如果得到的数据未满一页，然后我进行隐藏加载更多脚布局，就会出现，先显示后隐藏的动画效果，不是很好看。
设置了RequestLoadMoreListener回调确实是代表是分页请求，但请求的数据是会出现两种可能：一屏多和一屏未满，对于一屏未满而言，他不需要开启加载更多功能。仅一屏多时的情况下，的<allRequestCount才要开启加载更多功能。
这样，你不觉得使用库的开发者要考虑的角度就变多了吗？我是未满，要记得之前是开了，所以要关闭，满了m要记得之前是开了，所以不用操作。
假设是我说的一直有接口A监听。那我，接口里的方法传入参数就是这次填充的data，我再使用data.size，然后，我在接口方法里写的就是判断data.size和一次请求该返回的条数比大小。这个比较，和@CymChad 大佬他谈论过。那我就不需要考虑一开始是打开还是关闭了，只对此次的请求操作结果进行判断，小于一次请求该返回的条数就关闭，等于一次请求该返回的条数就打开。
至于你说的最后一个的问题，是根据字段来判断的那种情况。这个不是很蛋疼。 确实要字段的话，那我接口里传入的参数是data即可。是setNewData()和addData()能延伸出接口A，接口A里的方法参数为data的类型而不单单是data.size。
我说的改动并不会影响老代码，因为，我的设置监听接口A，和RequestLoadMoreListener这些没关系，假设我没写setListenerA，则还是老的写法。
我的建议是在改动用库方式时，的可优化。现在demo里的写法和上上条的不是一个思路。，且没有给出一个比较“规范”的模板，每个人都有一套自己的模板。这就很尴尬了。所以我是推崇，在以后的版本里，给出一个规范性的模板和以上的加载显示处理。让以后的用库者可以统一起来，问题也不会那么怪。

**Comment by CymChad** [comment]
@rcjs 你看看我理解你说的意思是不是这样

新增接口A

1.如果设置了这个接口A，默认就是关闭，然后在接口A里面返回一个boolean 值  ，从里面判断 data.size 是否大于 一页大小，然后如果大于就再去开启上拉加载。

2.如果不设置接口A，那么和现在是一样的。

**Comment by rcjs** [comment]
@CymChad 
对1：
在接口A里面返回一个boolean 值 ，做什么？
从里面判断 data.size 是否大于 一页大小，对，但这个是由用库者决定。我们提供的是接口A里重写方法的参数是data，不是data.size。这样就防止他是通过：（比如服务器返回的数据中有个是否还有更多数据，这时候回调就不好去取这个字段）这个来确定是否要加载。
对2：
对。

**Comment by 1109993488** [comment]
你现在要的是这样的效果吧？
```
public class BaseQuickAdapter<T> extends RecyclerView.Adapter {
    public interface OnLoadMoreListener {
        void checkLoadMore(boolean isRefresh, int pageSize);
    }

    List<T> mData;

    OnLoadMoreListener mListener;

    public void setNewData(List<T> data) {
        //1.xxx
        final int size = data == null ? 0 : data.size();
        mListener.checkLoadMore(true, size);
    }

    public void addData(List<T> data) {
        //2.xxx
        final int size = data == null ? 0 : data.size();
        mListener.checkLoadMore(false, size);
    }

    public void openLoadMore() {
        //开启加载更多，如果调了这个方法，加载更多会一直打开
        //如果想在一次请求中开启，需要在2.xxx中关闭
    }
}

class MainActivity {
    BaseQuickAdapter mAdapter;

    BaseQuickAdapter.OnLoadMoreListener onLoadMoreListener = new BaseQuickAdapter.OnLoadMoreListener() {
        @Override
        public void checkLoadMore(boolean isRefresh, int pageSize) {
            if (pageSize < 10) {
                mAdapter.loadMoreEnd(boolean);
            } else {
                mAdapter.openLoadMore();
            }
        }
    };

    //下拉刷新回调
    public void refreshSuccess(List data) {
        mAdapter.setNewData(data);
    }

    //加载更多获取数据成功回调
    public void loadMoreSuccess(List data) {
        mAdapter.addData(data);
    }

    //加载更多获取数据失败回调
    public void loadMoreFail(Exception e) {
        mAdapter.loadMoreFail();
    }

}
```

**Comment by rcjs** [comment]
我有空会自己去改一下，改好了再来讨论。假设的话，有些不好测试自己想法。

**Comment by CymChad** [comment]
恩，有新的想法在开一个issues讨论，我先关了这个issues。
