### ISSUE TITLE
Bug in SLIDEIN_BOTTOM animation when using GridLayoutManager

### ISSUE THREAD

**Issue by jasonni** [CymChad/BaseRecyclerViewAdapterHelper#161]
I have a question about SLIDEIN_BOTTOM animation when using GridLayoutManager,
the last item (here is item 5) not slide in,

![slidebottom](https://cloud.githubusercontent.com/assets/4085409/16792249/6581c740-48f9-11e6-8075-3709bb5ccf3c.gif)

I find the problem is the last item height is 0, any idea to fix it ?

**Comment by CymChad** [comment]
Not find out why

**Comment by jasonni** [comment]
I find the height of item 5 is 0, so it can't animate. 
Maybe it's too early to call animate?
I will help to find the problem.

**Comment by CymChad** [comment]
I've tested 12 data, also is the only article 5 not slide in，strange

**Comment by CymChad** [comment]
Find the problem The fifth didn't perform onViewBindHolder method

**Comment by CymChad** [comment]
Adapter is reuse mechanism lead to the problems

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.6'

**Comment by CymChad** [comment]
fix #161
