### ISSUE TITLE
HeaderView也是一个recyclerView的情况

### ISSUE THREAD

**Issue by pkxutao** [CymChad/BaseRecyclerViewAdapterHelper#1610]
请问 在HeaderView也是一个recyclerView的情况下 ， 怎么添加headerview的recyclerview的item点击事件？  我看了下demo好像没有这种情况

**Comment by Troll4it** [comment]
跟其他的点击事件是一样的。。

**Comment by CymChad** [comment]
在设置headerview的recyclerview的adapter的时候设置点击事件

**Comment by yudongyy** [comment]
我也遇到了写了不起作用，不知楼主怎么解决的

**Comment by pkxutao** [comment]
@yudongyy 起作用的，我后来发现是我的点击事件调用方法写错了
