### ISSUE TITLE
左滑删除的问题

### ISSUE THREAD

**Issue by duomaidragon** [CymChad/BaseRecyclerViewAdapterHelper#1611]
快速的滑动两个item,一定概率出现两个同时被划开，然后先划开的item的底层按钮点击第一次可以让后划开的收回，但是第二次点击的事件回调没有了，求更新解决~
![bug](https://user-images.githubusercontent.com/19400320/31044581-9f551f94-a604-11e7-8271-e34ee8bbf29a.png)

**Comment by elfman** [comment]
本库并不支持侧滑菜单，你是不是用了其它库了？

**Comment by duomaidragon** [comment]
sorry~确实是这样，adapter用的咱们的，滑动监听用了其他的库~问题关闭掉了哈
