### ISSUE TITLE
addItemDecoration作为一条分割线，上啦加载的时候，每个item间分割线会移动，然后又会复原的问题

### ISSUE THREAD

**Issue by Anayuta** [CymChad/BaseRecyclerViewAdapterHelper#1612]

**Comment by 1109993488** [comment]
是不是你的分割线有问题

**Comment by Anayuta** [comment]
@1109993488 分割线没有问题吧。
public class CommentDecoration extends RecyclerView.ItemDecoration {
    private Context mContext;
    private Drawable mDivider;
    private int mOrientation;

    public static final int HORIZONTAL_LIST = LinearLayoutManager.HORIZONTAL;
    public static final int VERTICAL_LIST = LinearLayoutManager.VERTICAL;

    //我们通过获取系统属性中的listDivider来添加，在系统中的AppTheme中设置
    public static final int[] ATRRS  = new int[]{
            android.R.attr.listDivider
    };

    public CommentDecoration(Context context, int orientation) {
        this.mContext = context;
        final TypedArray ta = context.obtainStyledAttributes(ATRRS);
        this.mDivider = ta.getDrawable(0);
        ta.recycle();
        setOrientation(orientation);
    }

    //设置屏幕的方向
    public void setOrientation(int orientation){
        if (orientation != HORIZONTAL_LIST && orientation != VERTICAL_LIST){
            throw new IllegalArgumentException("invalid orientation");
        }
        mOrientation = orientation;
    }

    @Override
    public void onDraw(Canvas c, RecyclerView parent, RecyclerView.State state) {
        if (mOrientation == HORIZONTAL_LIST){
            drawVerticalLine(c, parent, state);
        }else {
            drawHorizontalLine(c, parent, state);

        }
    }

    //画横线, 这里的parent其实是显示在屏幕显示的这部分
    public void drawHorizontalLine(Canvas c, RecyclerView parent, RecyclerView.State state){
        int left = parent.getPaddingLeft();
        int right = parent.getWidth() - parent.getPaddingRight();

        final int childCount = parent.getChildCount();
        for (int i = 0; i < childCount; i++){
            final View child = parent.getChildAt(i);

            //获得child的布局信息
            final RecyclerView.LayoutParams params = (RecyclerView.LayoutParams)child.getLayoutParams();
            final int top = child.getBottom() + params.bottomMargin;
            final int bottom = top + mDivider.getIntrinsicHeight();

            mDivider.setBounds(left, top, right, bottom);
            mDivider.draw(c);
        }
    }

    //画竖线
    public void drawVerticalLine(Canvas c, RecyclerView parent, RecyclerView.State state){
        int top = parent.getPaddingTop();
        int bottom = parent.getHeight() - parent.getPaddingBottom();

        final int childCount = parent.getChildCount();
        for (int i = 0; i < childCount; i++){
            final View child = parent.getChildAt(i);

            //获得child的布局信息
            final RecyclerView.LayoutParams params = (RecyclerView.LayoutParams)child.getLayoutParams();
            final int left = child.getRight() + params.rightMargin;
            final int right = left + mDivider.getIntrinsicWidth();

            mDivider.setBounds(left, top, right, bottom);
            mDivider.draw(c);
        }
    }

    @Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
        if(mOrientation == HORIZONTAL_LIST){
            //画横线，就是往下偏移一个分割线的高度
            outRect.set(0, 0, 0, mDivider.getIntrinsicHeight());
        }else {
            //画竖线，就是往右偏移一个分割线的宽度
            outRect.set(0, 0, mDivider.getIntrinsicWidth(), 0);
        }
//        outRect.set(0, 0, 0, mDivider.getIntrinsicWidth());
    }
}

**Comment by 1109993488** [comment]
分割线怎么移动的? 你在demo里加试试，

**Comment by Anayuta** [comment]
@1109993488      ~~! 之前发现这问题，赶进度就直接删了。

**Comment by 1109993488** [comment]
无法复现就不知道怎么造成的，如果还有问题最好提供复现方法方便解决

**Comment by Anayuta** [comment]
可以复现，改天我提供出来吧

**Comment by 1109993488** [comment]
ok

**Comment by Jessiqi** [comment]
遇到同样的问题

**Comment by Anayuta** [comment]
@Jessiqi  你看看你加载完成后数据添加，我的是因为loadMoreComplete后才设置enabled，把代码位置改了下就没那问题了。
 mSwipeRefreshLayout.setEnabled(true);
 mBaseRefreshAdapter.addData(data);
 mBaseRefreshAdapter.loadMoreComplete();

**Comment by Jessiqi** [comment]
@Anayuta 谢谢，解决了我的bug,我上午纠结了好久，非常感谢

**Comment by ericwangjp** [comment]
同样遇到recyclerview嵌套recyclerview刷新内层分割线变大的问题，目前无解

**Comment by ZevShiShi** [comment]
我用这个办法解决的
···kotlin
 // 添加分割线，增加判断防止分割线多次添加导致间隔变大
            if (rvItemImage.itemDecorationCount == 0) {
                rvItemImage.addItemDecoration(SpaceItemDecoration(ConvertUtils.dp2px(5f)))
            }
···
