### ISSUE TITLE
Horizontal  RecyclerView 添加FooterView，setFooterViewAsFlow（true）无效！

### ISSUE THREAD

**Issue by CoKoOne** [CymChad/BaseRecyclerViewAdapterHelper#1613]
当使用横向的RecyclerView 添加FooterView，无论使用LinearLayoutManager还是GridLayoutManager，setFooterViewAsFlow（true），FooterView仍占满一行！

**Comment by CymChad** [comment]
你使用一下瀑布流布局。

**Comment by CoKoOne** [comment]
试过了 还是不行。

**Comment by CoKoOne** [comment]
`   StaggeredGridLayoutManager staggeredGridLayoutManager = new StaggeredGridLayoutManager(1, StaggeredGridLayoutManager.HORIZONTAL);
            recyclerview.setLayoutManager(staggeredGridLayoutManager);

            MyAdapter adapter = new MyAdapter(list);
            View inflate = View.inflate(this, R.layout.item_footer, null);
            adapter.addFooterView(inflate);
            adapter.setFooterViewAsFlow(true);

            recyclerview.setAdapter(adapter);
            recyclerview.addItemDecoration(new RecyclerView.ItemDecoration() {
                public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {

                    int pos = parent.getChildAdapterPosition(view);
                    int i = parent.getAdapter().getItemCount() - 1;
                    if (pos != i) {
                        //int left, int top, int right, int bottom
                        outRect.set(dp2px(10), 0, 0, 0);
                    } else {
                        outRect.set(dp2px(10), 0, dp2px(10), 0);
                    }

                }
            });
`

**Comment by CymChad** [comment]
版本号是？

**Comment by CoKoOne** [comment]
2.9.31 @CymChad

**Comment by CymChad** [comment]
行，收到，我看下

**Comment by CymChad** [comment]
我在demo中的MultipleItemUseActivity测试了一下是有效的
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_multiple_item_use);
        setTitle("MultipleItem Use");
        setBackBtn();
        mRecyclerView = (RecyclerView) findViewById(R.id.rv_list);
        final List<MultipleItem> data = DataServer.getMultipleItemData();
        final MultipleItemQuickAdapter multipleItemAdapter = new MultipleItemQuickAdapter(this, data);
        final GridLayoutManager manager = new GridLayoutManager(this, 4);
        mRecyclerView.setLayoutManager(manager);
        multipleItemAdapter.setSpanSizeLookup(new BaseQuickAdapter.SpanSizeLookup() {
            @Override
            public int getSpanSize(GridLayoutManager gridLayoutManager, int position) {
                return data.get(position).getSpanSize();
            }
        });
        View view = getLayoutInflater().inflate(R.layout.footer_view, (ViewGroup) mRecyclerView.getParent(), false);
        multipleItemAdapter.addFooterView(view);
        multipleItemAdapter.setFooterViewAsFlow(true);
        mRecyclerView.setAdapter(multipleItemAdapter);
    }
```

**Comment by CymChad** [comment]
你自己可以在demo里面测试一下。

**Comment by CoKoOne** [comment]
你这个是竖向的Recyclerview？  横向的无效啊

**Comment by CymChad** [comment]
我去确认一下。

**Comment by CymChad** [comment]
没问题，横向的是横着看的。

竖向的Recyclerview，是并排，为不占满一行。
横向的Recyclerview，是并列，为不占满一行。

**Comment by CymChad** [comment]
SpanSize的原理是这样的，竖向的一行分成几等，横着排。而横向的一行分成几等份，竖着排。

**Comment by CoKoOne** [comment]
什么意思？没看明白  要不你放在Demo里吧  这样大家就懂了 @CymChad

**Comment by CymChad** [comment]
<img width="775" alt="11" src="https://user-images.githubusercontent.com/7698209/31601495-aa254fd0-b21f-11e7-8ba3-51c0f3d99f41.png">
上面的图分别是竖向和横向的setFooterViewAsFlow（true）效果。

**Comment by CoKoOne** [comment]
------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年10月16日(星期一) 下午4:12
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "上帝"<1689686109@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] Horizontal RecyclerView 添加FooterView，setFooterViewAsFlow（true）无效！ (#1613)





 上面的图分别是竖向和横向的setFooterViewAsFlow（true）效果。 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
         
  


从QQ邮箱发来的超大附件

bug.zip (204.3K, 2017年11月16日 23:53 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0f616137afab9e9d6ef1d7531765504d03515056025100041e5051550348565752004c550056004f525850525056045a570704013162620046064f4d5815625f&t=exs_ftn_download&code=3aa71ebb

**Comment by ljackChen001** [comment]
@CoKoOne 这个问你你解决了吗，我也遇到同样的问题

**Comment by CoKoOne** [comment]
没有啊，我试了作者说的方法，无效，可能是他没说详细，我也没理解透彻，准备换成多布局的形式，如果你解决了，希望能告知我一下，我解决会以邮件的方式告知你！




------------------ 原始邮件 ------------------
发件人: "ljackChen001";<notifications@github.com>;
发送时间: 2017年11月15日(星期三) 中午1:01
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "上帝"<1689686109@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] Horizontal RecyclerView 添加FooterView，setFooterViewAsFlow（true）无效！ (#1613)




@CoKoOne 这个问你你解决了吗，我也遇到同样的问题

**Comment by ljackChen001** [comment]
@CoKoOne  addFooterView(getFooterView(), 0, LinearLayoutManager.HORIZONTAL)重载这个方法

**Comment by CoKoOne** [comment]
哥们，非常谢谢，解决了！




------------------ 原始邮件 ------------------
发件人: "ljackChen001";<notifications@github.com>;
发送时间: 2017年11月15日(星期三) 下午2:23
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "上帝"<1689686109@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] Horizontal RecyclerView 添加FooterView，setFooterViewAsFlow（true）无效！ (#1613)




@CoKoOne  addFooterView(getFooterView(), 0, LinearLayoutManager.HORIZONTAL)重载这个方法
