### ISSUE TITLE
在低端机上卡顿

### ISSUE THREAD

**Issue by 1405553774** [CymChad/BaseRecyclerViewAdapterHelper#1618]
在低端机上卡顿挺厉害的，我在华为G700   ANDROID 4.2.1 上的，不知道有没有人遇过。 我的itemlayout布局也很简单

**Comment by CymChad** [comment]
你使用原始的adapter效果如何？

**Comment by CymChad** [comment]
你可以看下 关于卡顿的历史issues  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=%E5%8D%A1%E9%A1%BF

**Comment by CymChad** [comment]
如果还是卡顿，你可以提供一个demo。我这篇测试一下。

**Comment by 1405553774** [comment]
谢谢你，我已经修复了，因为我是拿你的adapter 源码 根据我的需求 进行改造的。你的代码没问题，是我的item里面的一个自定义图片空间过度绘制而导致的。 在低端测试机上会出现。 再次感谢

**Comment by CymChad** [comment]
恩 好的，感谢使用。
