### ISSUE TITLE
实现京东购物车的功能

### ISSUE THREAD

**Issue by fanfan1009** [CymChad/BaseRecyclerViewAdapterHelper#1619]
您好，我想实现京东购物车那样的功能点击head的选择框，下面子选择框自动全选。反过来一样。  现在就是不知道如何互相影响

**Comment by CymChad** [comment]
通过改变实体数据的属性来控制ui界面的显示。

**Comment by STGing** [comment]
把你的数据里面增加一个boolean属性，用于判断该条item是否被勾选。当设置全选的时候，遍历所有数据，将所有数据新加的这个属性设置为 true。在adapter中判断item的这个属性来设置checkbox是否勾选，最后刷新数据就可以了。

**Comment by BugMen** [comment]
@STGing 你好，
checkBoxAll.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                if (isChecked) {
                    for (Mode mode : ModeList) {
                        mode.isCheck = true;
                    }
                } else {
                    for (Mode mode : ModeList) {
                        mode.isCheck = false;
                    }
                }
                adapter.notifyDataSetChanged();
            }
        });
我这样设置了全选，然后
helper.setOnCheckedChangeListener(R.id.checkbox_invoice, new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                item.isCheck = isChecked;
            }
        });
        if (item.isCheck) {
            helper.setChecked(R.id.checkbox_invoice, true);
        } else {
            helper.setChecked(R.id.checkbox_invoice, false);
        }
这是我的Adapter，全选并没有展示，单选也出现了状态不能保存，可以帮我看下代码哪里有问题么？

**Comment by CymChad** [comment]
http://blog.csdn.net/guohaosir/article/details/72403724 你可以看下相关博客，以及查看下相关demo，读下源码

**Comment by fanfan1009** [comment]
感谢感谢，万分感谢 





------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年12月13日(星期三) 中午1:47
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "杨帆"<563254482@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 实现京东购物车的功能 (#1619)



http://blog.csdn.net/guohaosir/article/details/72403724 你可以看下相关博客，以及查看下相关demo，读下源码

**Comment by sun-wenming** [comment]
根据 STGing的描述，简单撸了一个商城购物车 [ShopCart](https://github.com/sun-wenming/ShopCart)
