### ISSUE TITLE
下拉刷新可以,但是上拉加载更多就不行了,代码如下,请大神指示! debug下,直接不走onLoadMoreRequested()这个方法!

### ISSUE THREAD

**Issue by OpenSourceMIUI** [CymChad/BaseRecyclerViewAdapterHelper#1620]
package com.ebuy.shop.ui.activity;

import android.graphics.Color;
import android.os.Bundle;
import android.os.Handler;
import android.support.annotation.Nullable;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import android.widget.Toast;

import com.chad.library.adapter.base.BaseQuickAdapter;
import com.ebuy.shop.R;
import com.ebuy.shop.model.dao.Manager;
import com.ebuy.shop.model.net.bean.MyOrderListsResponse;
import com.ebuy.shop.ui.adapter.PersonalMyOrderAdapter;
import com.ebuy.shop.utils.UiUtils;
import com.vondear.rxtools.view.RxToast;

import java.util.ArrayList;
import java.util.List;

import butterknife.InjectView;

/**
 * Created by Administrator on 2017/9/4.
 * 个人我的订单
 */

public class PersonalMyOrderActivity extends BaseActivity implements BaseQuickAdapter.RequestLoadMoreListener, SwipeRefreshLayout.OnRefreshListener {
    @InjectView(R.id.rv_my_order)
    RecyclerView rv_my_order;
    List<MyOrderListsResponse.MyOrder.Order> orders;
    @InjectView(R.id.swipeLayout)
    SwipeRefreshLayout swipeLayout;
    private String pageSize = "10";
    int page = 1;
    PersonalMyOrderAdapter personalMyOrderAdapter;
    View commentFoot;
    private View notDataView;
    private View errorView;
    TextView tvEmpty;
    private int delayMillis = 2000;
    private boolean isErr;
    private int pages;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SetContentLayout(R.layout.activity_personal_my_order);
        initView();
        initSwipeRefreshLayout();
        initData();
    }
    private void initSwipeRefreshLayout() {
        swipeLayout.setOnRefreshListener(this);
        swipeLayout.setColorSchemeColors(Color.rgb(47, 223, 189));
    }

    private void initData() {
        showLoading("");
        orderListsPresenter.getOrders(Manager.getUserToken(), page, pageSize);
    }

    private void initView() {
        tvTitle.setText("我的订单");
        LinearLayoutManager commentManager = new LinearLayoutManager(this);
        commentManager.setOrientation(LinearLayoutManager.VERTICAL);
        rv_my_order.setLayoutManager(commentManager);
        rv_my_order.setHasFixedSize(true);
        orders = new ArrayList();
        personalMyOrderAdapter = new PersonalMyOrderAdapter(R.layout.item_personal_my_order_complete, orders, PersonalMyOrderActivity.this);
        // 当列表滑动到倒数第N个Item的时候(默认是1)回调onLoadMoreRequested方法
        personalMyOrderAdapter.setPreLoadNumber(9);
        personalMyOrderAdapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_LEFT);
        rv_my_order.setAdapter(personalMyOrderAdapter);
        personalMyOrderAdapter.isFirstOnly(false);
        personalMyOrderAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                startActivity(PersonalMyOrderActivity.this, PersonalGoCommentActivity.class, false);
            }
        });
        commentFoot = getLayoutInflater().inflate(R.layout.footer_personal_business_fragment, (ViewGroup) rv_my_order.getParent(), false);
        notDataView = getLayoutInflater().inflate(R.layout.empty_no_data, (ViewGroup) rv_my_order.getParent(), false);
        tvEmpty = (TextView) notDataView.findViewById(R.id.tv_empty);
        tvEmpty.setText("暂无订单 /(ㄒoㄒ)/~~ ");
        errorView = getLayoutInflater().inflate(R.layout.error_no_net, (ViewGroup) rv_my_order.getParent(), false);
        errorView.findViewById(R.id.ll_refresh_net).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                initData();
            }
        });
//        boolean slideToBottom = UiUtils.isSlideToBottom(rv_my_order);
//        if (slideToBottom) {
//            personalMyOrderAdapter.addFooterView(commentFoot);
//        }
    }

    @Override
    public void success(Object o) {
        if (o != null) {
            MyOrderListsResponse orderResponse = (MyOrderListsResponse) o;
            if (orderResponse != null && orderResponse.getData() != null) {
                pages = orderResponse.getData().getPages();
                List<MyOrderListsResponse.MyOrder.Order> orderLists = orderResponse.getData().getList();
                if (orderLists.size() > 0) {
                    if (orderLists.size() < 3) {
                        personalMyOrderAdapter.removeFooterView(commentFoot);
                    }
                    orders.addAll(orderLists);
                    swipeLayout.setRefreshing(false);
                    personalMyOrderAdapter.notifyDataSetChanged();
                } else {
                    personalMyOrderAdapter.notifyDataSetChanged();
                    personalMyOrderAdapter.setEmptyView(notDataView);
                }
            } else {
                personalMyOrderAdapter.notifyDataSetChanged();
                personalMyOrderAdapter.setEmptyView(notDataView);
            }
        } else {
            personalMyOrderAdapter.notifyDataSetChanged();
            personalMyOrderAdapter.setEmptyView(notDataView);
        }
        hideLoading();
    }

    @Override
    public void failed(String msg) {
        RxToast.error(this, "获取订单列表失败 /(ㄒoㄒ)/~~", Toast.LENGTH_SHORT).show();
        hideLoading();
        swipeLayout.setRefreshing(false);
        orders.clear();
        personalMyOrderAdapter.notifyDataSetChanged();
        personalMyOrderAdapter.setEmptyView(errorView);
    }

    @Override
    public void onRefresh() {
        personalMyOrderAdapter.setEnableLoadMore(false);
        personalMyOrderAdapter.removeFooterView(commentFoot);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                orders.clear();
                orderListsPresenter.getOrders(Manager.getUserToken(), 1, "10");
                personalMyOrderAdapter.setNewData(orders);
                isErr = false;
                swipeLayout.setRefreshing(false);
                personalMyOrderAdapter.setEnableLoadMore(true);
            }
        }, delayMillis);
    }

    @Override
    public void onLoadMoreRequested() {
        swipeLayout.setEnabled(false);
        page++;
        if (pages < page) {
            personalMyOrderAdapter.loadMoreEnd(true);
        } else {
            if (isErr) {
                showLoading("");
                orderListsPresenter.getOrders(Manager.getUserToken(), page, "10");
                personalMyOrderAdapter.addData(orders);
                personalMyOrderAdapter.loadMoreComplete();
            } else {
                isErr = true;
                Toast.makeText(PersonalMyOrderActivity.this, "获取定期列表失败 /(ㄒoㄒ)/~~", Toast.LENGTH_LONG).show();
                personalMyOrderAdapter.loadMoreFail();
                hideLoading();
            }
        }
        swipeLayout.setEnabled(true);
    }
}

**Comment by 1109993488** [comment]
你调用setOnLoadMoreListener设置加载更多监听了吗？

**Comment by OpenSourceMIUI** [comment]
有啊, initSwipeRefreshLayout()里,注册了swipeLayout.setOnRefreshListener(this);

**Comment by CymChad** [comment]
是否可以提供一个可复现的demo？或者直接在官方demo里面修改一份复现代码，这边便于我们更快的找出问题 @OpenSourceMIUI

**Comment by 1109993488** [comment]
@OpenSourceMIUI setOnLoadMoreListener，不是setOnRefreshListener
