### ISSUE TITLE
设置disableLoadMoreIfNotFullPage() 没有用，初始化的时候还是回调onLoadMoreRequested（）

### ISSUE THREAD

**Issue by 317056658** [CymChad/BaseRecyclerViewAdapterHelper#1622]
public class KeyInformationBoxroomActivity extends AppCompatActivity implements BaseItemDraggableAdapter.RequestLoadMoreListener{
    private  TextView mBackData;
    //获得window装饰类
    private View mDecorView;
    private ProlificSerialDriver driver;
    private HashMap<String,String> languageMap;
    public  static final int  FLAG_FAVORITE=1001;  //收藏夹
    public  static final int  FLAG_CUT_HISTORY=1002;//切割记录\
    /**最多展示多少条数据*/
    private static final int TOTAL_COUNT = 20;
    /**已经获取到多少条数据了*/
    private  int mCurrentCounter = 0;
    private boolean isErr;
    private int flag;
    List dataSet;
    private LinearLayoutManager mLayoutManager;

    private RecyclerView  mRecyclerBoxroom;
    private MyDataAdapter mDataAdapter;
    private LinearLayout mLinearLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_favorites_and_history);
        this.getIntentData();
        initViews();
    }
    @Override
    protected void onStart() {
        super.onStart();
    }

    @Override
    protected void onResume() {
        super.onResume();
        Tools.hideBottomUIMenu(mDecorView);

    }  @Override
    protected void onPause() {
        super.onPause();
    }

    @Override
    protected void onStop() {
        super.onStop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
    }
    private void  initViews(){
        mDecorView = getWindow().getDecorView();
        mLinearLayout = (LinearLayout)findViewById(R.id.ll_layout);
       CardView cv= (CardView)findViewById(R.id.cardView);
        cv.setRadius(8);//设置图片圆角的半径大小

        cv.setCardElevation(100);//设置阴影部分大小

        cv.setContentPadding(10,10,10,10);//设置图片距离阴影大小
        TextView mTitle=(TextView)findViewById(R.id.tv_title);
         switch (flag){
             case FLAG_FAVORITE:
                 mTitle.setText("Favorite Key Blank");
                 break;
             case FLAG_CUT_HISTORY:
                 mTitle.setText("Cut History");
                 break;
         }
        mRecyclerBoxroom =(RecyclerView)findViewById(R.id.recycler_boxroom);
        mRecyclerBoxroom.setHasFixedSize(true);
        LinearLayoutManager  layoutManager=new LinearLayoutManager(this);
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        layoutManager.setReverseLayout(false);
        mRecyclerBoxroom.setLayoutManager(layoutManager);
        //准备数据源
        dataSet=new ArrayList<>();
        for (int i = 0; i <10 ; i++) {
           dataSet.add("我是内容"+i);
        }
        //item拖拽事件
        OnItemDragListener onItemDragListener =new OnItemDragListener() {
            @Override
            public void onItemDragStart(RecyclerView.ViewHolder viewHolder, int pos) {

            }

            @Override
            public void onItemDragMoving(RecyclerView.ViewHolder source, int from, RecyclerView.ViewHolder target, int to) {

            }

            @Override
            public void onItemDragEnd(RecyclerView.ViewHolder viewHolder, int pos) {

            }
        };
        //item侧滑事件
        OnItemSwipeListener onItemSwipeListener=new OnItemSwipeListener() {
            @Override
            public void onItemSwipeStart(RecyclerView.ViewHolder viewHolder, int pos) {

            }

            @Override
            public void clearView(RecyclerView.ViewHolder viewHolder, int pos) {

            }

            @Override
            public void onItemSwiped(RecyclerView.ViewHolder viewHolder, int pos) {

            }

            @Override
            public void onItemSwipeMoving(Canvas canvas, RecyclerView.ViewHolder viewHolder, float dX, float dY, boolean isCurrentlyActive) {

            }
        };
        mDataAdapter=new MyDataAdapter(dataSet);
        ItemDragAndSwipeCallback itemDragAndSwipeCallback=new ItemDragAndSwipeCallback(mDataAdapter);
        ItemTouchHelper itemTouchHelper = new ItemTouchHelper(itemDragAndSwipeCallback);
        itemTouchHelper.attachToRecyclerView(mRecyclerBoxroom);
        //开启拖拽
        mDataAdapter.enableDragItem(itemTouchHelper);
        mDataAdapter.setOnItemDragListener(onItemDragListener);
        // 开启滑动删除
        mDataAdapter.enableSwipeItem();
        mDataAdapter.setOnItemSwipeListener(onItemSwipeListener);
        mDataAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(KeyInformationBoxroomActivity.this, "onItemClick" + dataSet.get(position).toString(), Toast.LENGTH_SHORT).show();
            }
        });
        mDataAdapter.openLoadAnimation(BaseQuickAdapter.SCALEIN );  //开启动画效果
        mDataAdapter.isFirstOnly(false);

        mDataAdapter.setOnLoadMoreListener(this,mRecyclerBoxroom);
        mDataAdapter.disableLoadMoreIfNotFullPage();
        mRecyclerBoxroom.setAdapter(mDataAdapter);

    }

    /**
     * 启动当前Activity
     * @param context
     * @param languageMap
     */
    public  static  void  startFavoriteActivity(Context context, HashMap<String,String> languageMap,int flag){
        Intent intent=new Intent(context,KeyInformationBoxroomActivity.class);
        intent.putExtra("language",languageMap);
        intent.putExtra("flag",flag);
        context.startActivity(intent);
    }
    private  void  getIntentData(){
        Intent intent=getIntent();
        languageMap= (HashMap<String, String>) intent.getSerializableExtra("language");
         flag=intent.getIntExtra("flag",-1);
    }

    @Override
    public void onLoadMoreRequested() {
     mRecyclerBoxroom.postDelayed(new Runnable() {
         @Override
         public void run() {

                 if(mCurrentCounter>= TOTAL_COUNT){
                     //数据全部加载完毕
                     mDataAdapter.loadMoreEnd();
                     Log.d("加载完毕", "run: ");
                 }else {
                     List<String> list=new ArrayList();
                     for (int i = 10; i <20 ; i++) {
                         list.add("我是内容"+i);
                     }
                     Log.d("回调", "run: "+isErr);
                     mDataAdapter.addData(list);
                     mCurrentCounter=mDataAdapter.getData().size();
                     mDataAdapter.loadMoreComplete();  //加载完成
                     Log.d("是好多？", "run: "+mCurrentCounter);
                 }
         }
     },500);

    }

**Comment by CymChad** [comment]
那你在onLoadMoreRequested里面判断下是否小于一页的数量，如果小于就关闭上拉。

**Comment by 317056658** [comment]
我解决了 但是你这个方法disableLoadMoreIfNotFullPage()  根本就没有用啊  楼主，你的开源都做的这么优秀了。麻烦你修复下

**Comment by CymChad** [comment]
恩，好的，多谢建议。
