### ISSUE TITLE
在没网的状态下，下拉刷新这个为什么一直报空.Common1Adapter.setEnableLoadMore(boolean)'

### ISSUE THREAD

**Issue by 012ABC** [CymChad/BaseRecyclerViewAdapterHelper#1623]

**Comment by 1109993488** [comment]
你的意思是这一句报错了？你是不是刷新的时候调了setEnableLoadMore(false)，没网的时候又调了setEnableLoadMore(true)?这2句同时调就会有问题，后面的需要放到post里调

**Comment by 012ABC** [comment]
font{
        line-height: 1.7;
    }


    
恩，是的，谢谢



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年10月11日 14:15，BlingBling<notifications@github.com> 写道： 


你的意思是这一句报错了？你是不是刷新的时候调了setEnableLoadMore(false)，没网的时候又调了setEnableLoadMore(true)?这2句同时调就会有问题，后面的需要放到post里调
