### ISSUE TITLE
Demo中的SectionAdapter.setOnItemChildClickListener  并没有用

### ISSUE THREAD

**Issue by shengguan** [CymChad/BaseRecyclerViewAdapterHelper#1627]
Demo中的SectionAdapter.setOnItemChildClickListener  并没有用

```
 sectionAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                MySection mySection = mData.get(position);
                if (mySection.isHeader)
                    Toast.makeText(SectionUseActivity.this, mySection.header, Toast.LENGTH_LONG).show();
                else
                    Toast.makeText(SectionUseActivity.this, mySection.t.getName(), Toast.LENGTH_LONG).show();
            }
        });
        sectionAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(SectionUseActivity.this, "onItemChildClick" + position, Toast.LENGTH_LONG).show();
            }
            }
````

setOnItemChildClickListener里的Toast不会执行，只会执行setOnItemClickListener

**Comment by CymChad** [comment]
你在adapter绑定了子控件吗？

**Comment by CymChad** [comment]
首先在adapter的convert方法里面通过viewHolder.addOnClickListener绑定一下的控件id

 @Override
    protected void convert(BaseViewHolder viewHolder, Status item) {
        viewHolder.setText(R.id.tweetName, item.getUserName())
                .setText(R.id.tweetText, item.getText())
                .setText(R.id.tweetDate, item.getCreatedAt())
                .setVisible(R.id.tweetRT, item.isRetweet())
                .addOnClickListener(R.id.tweetAvatar)
                .addOnClickListener(R.id.tweetName)
                .linkify(R.id.tweetText);
       
    }
