### ISSUE TITLE
和刷新控件结合使用会冲突导致下拉不可用

### ISSUE THREAD

**Issue by xicong** [CymChad/BaseRecyclerViewAdapterHelper#1630]
https://github.com/zhouoryou/GolfersIntelligence      
这个是demo地址，结合刷新一起使用的时候，添加了头部view导致刷新手势触发不了，但是第一次设置自动刷新正常，注释掉添加头部代码也会显示正常

**Comment by 1109993488** [comment]
RecyclerView第一个item高度为0的时候会使SwipeRefreshLayout无法下拉刷新，你的header高度为0，解决办法：
1.用到header时再添加，不用的时候移除
2.给SwipeRefreshLayout设置setOnChildScrollUpCallback返回false

**Comment by xicong** [comment]
哦，懂了，谢了哦
