### ISSUE TITLE
helper.setText个别参数会报Resources$NotFoundException

### ISSUE THREAD

**Issue by swt930** [CymChad/BaseRecyclerViewAdapterHelper#1631]
![image](https://user-images.githubusercontent.com/10876333/31497800-b08347d6-af92-11e7-923b-60f978d01b8b.png)
![image](https://user-images.githubusercontent.com/10876333/31497822-c261ed40-af92-11e7-95c0-b58c11a8e2d6.png)
![image](https://user-images.githubusercontent.com/10876333/31497841-d0fbad6e-af92-11e7-82f5-a1b27c3f411b.png)

最新版本 2.9.31
id并没有错  也没有重复的

**Comment by CymChad** [comment]
这个是你的设置内容有问题，你这个设置的内容应该是 数字，然后系统会把他当做资源id去查找，你在内容后面+“”就可以了，这样就会把内容变成str类型。
