### ISSUE TITLE
RecyclerView中setNestedScrollingEnabled(false)，无法完全展示

### ISSUE THREAD

**Issue by duduzai** [CymChad/BaseRecyclerViewAdapterHelper#1632]
RecyclerView需要内嵌到NextScrollview，为了解决卡顿问题RecyclerView.setNestedScrollingEnabled(false)。所以在外部监听NextScrollview来实现加载更多，请求执行之后，item无法完全显示出来。 #342  看到讨论里dataAdded方法，不过没有找到调用。

**Comment by duduzai** [comment]
#1588

**Comment by CymChad** [comment]
不建议嵌套 Scrollview，如果嵌套 Scrollview 会导致 上拉失效。这样最好配合上拉控件来实现加载更多。

**Comment by CymChad** [comment]
还有无法完全展示也不是adapter的问题，我在网上找了下解决方案，你看看行不行  https://my.oschina.net/caomenglong/blog/747197

**Comment by duduzai** [comment]
恩，只是需求需要，为了复用，recyclerview被放在了Fragment里面，
![image](https://user-images.githubusercontent.com/5093381/31528159-56cd58cc-b004-11e7-828f-ab7d8879eb9c.png)
为了上滑 视差的效果不得已。上面提到的dataAdded方法，没有找到，或许我可以试一下

**Comment by CymChad** [comment]
之前老版本的dataAdded其实就是addData，追加数据

**Comment by duduzai** [comment]
感谢回复，我按上面的方法再去试试
