### ISSUE TITLE
结合粘性库stickyheadersrecyclerview后导致上拉加载无效

### ISSUE THREAD

**Issue by zofnk** [CymChad/BaseRecyclerViewAdapterHelper#1633]
原本你们的加载是在最后一个item的时候就开始自动加载,
结合了该库后会导致滑动到最后一个item后没有触发自动加载回调...
不知道是你们还是他的库的冲突...?

**Comment by zofnk** [comment]
你们在"下拉加载"的时候没有做headview , 没有出现问题, 在上拉加载的时候出现,不知道是不是因为上拉加载的FootView与该库对item创建的HeadView冲突的原因?

**Comment by zofnk** [comment]
另外再问下 , 下拉加载这个需求在对网络断开或者请求失败的情况下 怎么跟上拉加载一样有一个error的view来重新加载?

**Comment by zofnk** [comment]
第一个问题虽然可以把预加载的位置提前几个来规避,但是快速滑动下还是不行

**Comment by zofnk** [comment]
第一个问题虽然可以把预加载的位置提前几个来规避,但是如果快速滑动的话还是会出现问题,请问这样的issue可以解决吗?

**Comment by 1109993488** [comment]
1.最好提供demo
2.没看懂
3.可以下拉失败的时候清空data并设置EmptyView

**Comment by zofnk** [comment]
@1109993488  原本上拉加载是在最后一个item的时候触发onLoadMoreRequested的,因为结合了该库之后,无法主动触发 , 只能设置setPreLoadNumber来强制去让其触发.
demo 我找找接口看怎么弄个出来...

**Comment by 1109993488** [comment]
结合使用的时候加载更多布局应该不显示吧？如果显示了肯定会回调onLoadMoreRequested，你是否重写了getItemCount？

**Comment by zofnk** [comment]
@1109993488  刚刚试了一下 , 重写了getItemCount ,直接return mData.size() 的话好像是没问题了..不过那个那个加载完成的footview 就没有显示了...

**Comment by 1109993488** [comment]
getItemCount 最好不要重写，里面控制显示header、footer、加载更多

**Comment by zofnk** [comment]
@1109993488 (・(ｪ)・)...我以为是说需要重写 , 之前是没有重写会导致issue标题的问题 , 重写后请求正常情况是没问题, 如果出现错误或者网络断开 , 那个Error的点击加载更多就无法显示了吧?

**Comment by 1109993488** [comment]
如果重写了getItemCount 数量会有问题，可能不会显示加载更多， 加载更多出现的错误或没有网络可以调loadMoreFail显示加载失败的布局， 如果下拉刷新出现错误或无网 可以通过清空data数据并且设置EmptyView显示自定义的错误界面

**Comment by zofnk** [comment]
1.不是下拉刷新 我上面说的是下拉加载 就是UpFetch的情况下 如果下拉出现错误, 怎么跟上拉一样有个显示加载失败的布局?
2.那我现在是要重写getItemCount吗? 然后再针对网络异常的情况的时候,进行显示加载失败的布局么?

**Comment by 1109993488** [comment]
1.现在下拉加载没有加载状态这个功能
2.你可以把加载失败布局放到header里

**Comment by zofnk** [comment]
@1109993488 你好, https://github.com/zofnk/RecyclerViewLoadMoreTest 我弄了demo 你可以看下吗?就是还原了下场景会出现的问题

**Comment by 1109993488** [comment]
你这是滑动到底部就异常了
```
    @Override
    public long getHeaderId(int position) {
        final int dataPosition = position - getHeaderLayoutCount();
        if (dataPosition >= mData.size()) {
            return -1;
        }
        return mData.get(position).hashCode();
    }
```
这里应该控制下position，position可能会越界

**Comment by zofnk** [comment]
@1109993488  对呀 这个问题是要怎么解决...?Orz..

**Comment by 1109993488** [comment]
0.0上面不是给你列出了解决办法么

**Comment by zofnk** [comment]
喔喔...我还以为是问题出现的地方..今天找这个问题找得有点头痛...
非常感谢!!!!!~么么哒~
