### ISSUE TITLE
是的 又是我 上拉加载怎么主动触发?

### ISSUE THREAD

**Issue by zofnk** [CymChad/BaseRecyclerViewAdapterHelper#1635]
场景 : 从服务器请求了10条数据 , 显示没有更多数据, 上拉也被禁用了 。
这时服务器又添加了一些数据，这时需要去上拉再请求，是要怎么做？看了一遍ISSUE ，用的是enableLoadMoreEndClick这个方法吗？

  @Override
    public void onLoadMoreRequested() {
        mSwipeRefreshLayout.setEnabled(false);
        if (mNewsEntity.getData().isHasNext()) {
            page++;
            getDataList();
        } else {
            mNewsAdapter.loadMoreEnd();
        }
        mSwipeRefreshLayout.setEnabled(true);
    }

项目里对列表的上拉一般都是这样写的。。
@1109993488

**Comment by 1109993488** [comment]
设置enableLoadMoreEndClick(true)就可以，这样可以在没有更多的时候需要点击没有更多数据刷新

**Comment by zofnk** [comment]
@1109993488  有API来修改通过上拉去触发加载而不是通过点击没有更多数据来触发吗?

**Comment by 1109993488** [comment]
没有
