### ISSUE TITLE
onLoadMoreRequested adapter.addData()后  数据会自＋  

### ISSUE THREAD

**Issue by swt930** [CymChad/BaseRecyclerViewAdapterHelper#1637]
![image](https://user-images.githubusercontent.com/10876333/31548457-6dff745e-b05d-11e7-8ef4-96dd7010cc2a.png)
给的demo里同样  默认6条数据  加载一次应该是12条数据  而实际是18条数据

**Comment by 1109993488** [comment]
你的dataLists自己往里添加数据了，addData方法又加了一遍
