### ISSUE TITLE
用BRVAH写的图片选择器明显感到卡顿

### ISSUE THREAD

**Issue by GGjin** [CymChad/BaseRecyclerViewAdapterHelper#1638]
下面这个是测试的Demo  用BRVAH和 普通的adapter对比 其他都一样
https://github.com/GGjin/ImageDemo

**Comment by CymChad** [comment]
收到，我看看。

**Comment by CymChad** [comment]
<img width="1084" alt="1111" src="https://user-images.githubusercontent.com/7698209/31655797-a60b1daa-b2ef-11e7-92a0-721c2ee17817.png">
以上是原始adapter
<img width="1083" alt="2222" src="https://user-images.githubusercontent.com/7698209/31655798-a68b46b0-b2ef-11e7-95f4-ae5705d55eba.png">
以上是BRVAH

**Comment by GGjin** [comment]
应该是你的坚果pro 性能好一些所以 卡的不明显 我录制了视频 一个是带显示卡顿的那个条形图的一个是不带的 https://share.weiyun.com/c47654c37990e6d2a6bc34b99688f08d  （忽略里面的h图吧。。）

**Comment by CymChad** [comment]
恩，我看下你的视频，以及用一台差一点的手机试试看。我发图是想说明原始adapter和brvah的性能消耗和cup占用是几乎一样的。

**Comment by GGjin** [comment]
好吧 ，那我再研究一下具体的原因吧 这个issue 可以关了
