### ISSUE TITLE
不能用自己的加载和刷新控件吗?一定要用这个框架内置的么?

### ISSUE THREAD

**Issue by 282167361** [CymChad/BaseRecyclerViewAdapterHelper#1639]

**Comment by CymChad** [comment]
可以使用自己的，不设置上拉监听就行了。

**Comment by 282167361** [comment]
这个是默认关闭的吧?还有个问题就是,适配器中的mContext是怎么来的,为什么可以直接使用父类的变量?




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年10月16日(星期一) 下午4:00
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "伍晓焜"<282167361@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 不能用自己的加载和刷新控件吗?一定要用这个框架内置的么? (#1639)




可以使用自己的，不设置上拉监听就行了。

**Comment by CymChad** [comment]
```
   public K onCreateViewHolder(ViewGroup parent, int viewType) {
        K baseViewHolder = null;
        this.mContext = parent.getContext();
```

**Comment by 282167361** [comment]
那这个框架有添加分割线的功能方法吗?




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年10月16日(星期一) 下午5:11
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "伍晓焜"<282167361@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 不能用自己的加载和刷新控件吗?一定要用这个框架内置的么? (#1639)



   public K onCreateViewHolder(ViewGroup parent, int viewType) {         K baseViewHolder = null;         this.mContext = parent.getContext();

**Comment by CymChad** [comment]
没有

**Comment by 282167361** [comment]
那listview和GridView不能使用这个框架么?




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年10月26日(星期四) 中午11:18
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "伍晓焜"<282167361@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 不能用自己的加载和刷新控件吗?一定要用这个框架内置的么? (#1639)




没有

**Comment by CymChad** [comment]
恩 是的

**Comment by 282167361** [comment]
我数据能显示,但是会日志里面报:No adapter attached; skipping layout是怎么回事呢?


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年10月26日(星期四) 中午11:22
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "伍晓焜"<282167361@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 不能用自己的加载和刷新控件吗?一定要用这个框架内置的么? (#1639)




恩 是的

**Comment by 282167361** [comment]
你好,你上次说listview和gridview也适用这个框架,但是我这样写却报了这个错误
SelectStoreAdp selectStoreAdp = new SelectStoreAdp(R.layout.list_item_select_store, data);
lv_selectStore.setAdapter((ListAdapter) selectStoreAdp);     java.lang.ClassCastException: SelectStoreAdp cannot be cast to android.widget.ListAdapter      at .SelectStoreDialog.initData(SelectStoreDialog.java:41)




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年10月26日(星期四) 中午11:22
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "伍晓焜"<282167361@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 不能用自己的加载和刷新控件吗?一定要用这个框架内置的么? (#1639)




恩 是的
