### ISSUE TITLE
我AS跑这个demo  一直报错

### ISSUE THREAD

**Issue by 179098051** [CymChad/BaseRecyclerViewAdapterHelper#1645]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: .\build\buildCache\0092804781f53b79f150859e5e8dedad331e746c\output

**Comment by CymChad** [comment]
http://blog.csdn.net/doujiawei_1862391/article/details/51693074  
http://blog.csdn.net/lxk_1993/article/details/50511172
http://blog.csdn.net/shunzi1046/article/details/51279932
我这边都正常运行，你看看以上的解决方案是否可以解决你的问题。

**Comment by 179098051** [comment]
谢谢大佬
