### ISSUE TITLE
下标获取一直是-1

### ISSUE THREAD

**Issue by llol** [CymChad/BaseRecyclerViewAdapterHelper#1647]
我使用的是BaseMultiItemQuickAdapter，在convert中
@Override
    protected void convert(final BaseViewHolder holder, AudioViewEntry item) {
        switch (holder.getItemViewType()) {
            case AudioViewEntry.AUDIO_ITEM:
                int position = getParentPosition(item);
              

这样获取到的position一直是-1；
前提：我的实体实现了MultiItemEntity接口，并重写了getItemType（）方法；
        我的list是可以正常显示的，加载数据也正常，底部加载也可以

请问这是什么情况造成的

**Comment by CymChad** [comment]
这个getParentPosition是用于树形菜单，你要想获得当前position，可以通过holder.getlayoutposition
