### ISSUE TITLE
setNewData这个方法真是让我又爱又恨

### ISSUE THREAD

**Issue by kubiAye** [CymChad/BaseRecyclerViewAdapterHelper#1648]
这个方法总会帮我自动把一些状态复位了.尤其在一些我设置了loadMoreEnd时候

**Comment by shichaohui** [comment]
setNewData() 是更换全部数据的，load more 之后应该调用 addData() 追加新的数据到列表中。单个 Item 更新后可以调用 setData() 函数刷新 adapter。
