### ISSUE TITLE
adapter add header问题

### ISSUE THREAD

**Issue by YRInred** [CymChad/BaseRecyclerViewAdapterHelper#1652]
每次添加了头部之后 如果是长页面 每次打开的时候整个页面会自动往上移一小段距离 只有往下拉才能显示全面 是不是 头部添加的算法有些问题？

**Comment by Troll4it** [comment]
焦点问题
 给你的RV添加这个方法
rv.getLayoutManager().scrollToPosition(0);
                      rv.smoothScrollToPosition(0);

**Comment by YRInred** [comment]
header 大于1屏了 这个位移差的跟多了

**Comment by 1109993488** [comment]
焦点问题，历史有这个问题

**Comment by 1109993488** [comment]
#1357 #1516

**Comment by YRInred** [comment]
最外层RV加上

android:focusable="true"
android:focusableInTouchMode="true"

还是无效。。。有点懵逼

**Comment by YRInred** [comment]
感觉是你们内部adapter设置新值的时候 会寻找第一个recyclerview才会停下来 之前我头部的recyclerview超过一屏它就会滑动到我的第一个recyclerview的地方 现在我在头部的最上面加一个recyclerview就不会出现自动滑动了

**Comment by Troll4it** [comment]
descendantFocusability这个属性你可以试下

**Comment by Jessiqi** [comment]
目前项目中遇到这个问题：
外面布局SwipeRefreshLayout
在SwipeRefreshLayout里加以下代码问题解决
android:focusable="true"
android:focusableInTouchMode="true"

**Comment by tmac1999** [comment]
感觉是你们内部adapter设置新值的时候 会寻找第一个recyclerview才会停下来 之前我头部的recyclerview超过一屏它就会滑动到我的第一个recyclerview的地方 现在我在头部的最上面加一个recyclerview就不会出现自动滑动了
------------------
我也采用上面这个方式解决了

-----------------------
android:focusable="true"
android:focusableInTouchMode="true" 好像没用。
