### ISSUE TITLE
checkbox 在滚动的时候回出现错位

### ISSUE THREAD

**Issue by why2** [CymChad/BaseRecyclerViewAdapterHelper#1653]
checkbox 在滚动的时候回出现错位，数据集中的单个对象都有标记是否选中的flag，但是在滚动的时候还是会出现错位。

**Comment by 742340082** [comment]
同样问题

**Comment by hookbin** [comment]
convert中必须设置 helper.setChecked（viewId，true | false） 无论CheckBox是何种状态

**Comment by CymChad** [comment]
这是复用问题，需要通过相关属性判断 if else 来设置 true | false。文档也有说明。http://www.jianshu.com/p/b343fcff51b0
