### ISSUE TITLE
CoordinatorLayout嵌套viewpager这个recycleview无事件响应

### ISSUE THREAD

**Issue by yangshuai8318243** [CymChad/BaseRecyclerViewAdapterHelper#1654]
大佬好，BaseRecyclerViewAdapterHelper我使用了很久了，功能很好很方便，但是最近遇到一个项目中的问题，在使用CoordinatorLayout嵌套AppBarLayout嵌套CollapsingToolbarLayout之后外层使用viewpager内部使用BaseRecyclerViewAdapterHelper实现，这样发现使用BaseRecyclerViewAdapterHelper之后无法传递给父视图滚动事件，目前还没有查到问题具体点，但是使用原生的方式是可以的，所以可以确定是BaseRecyclerViewAdapterHelper的问题，我自己正在排查问题，如果大佬已经知道问题，希望可以提供帮助

**Comment by AllenCoder** [comment]
能否提供相关可复现Demo ，便于验证和修复Bug？

**Comment by yangshuai8318243** [comment]
例子如下，viewpager是嵌套Fragment里面只有一个recycleview，这样使用无法响应外部的折叠效果

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">

    <Button
        android:layout_width="match_parent"
        android:layout_height="50dp" />

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        android:orientation="vertical">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:orientation="vertical">

            <android.support.design.widget.CollapsingToolbarLayout
                android:id="@+id/collapsing_toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                app:layout_scrollFlags="scroll">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical">

                    <Button
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        android:background="@drawable/comment_gray" />


                    <HorizontalScrollView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginLeft="15dp"
                        android:layout_marginTop="10dp"
                        android:scrollbars="none"
                        app:layout_scrollFlags="scroll">

                        <LinearLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:orientation="horizontal">

                            <TextView
                                android:id="@+id/item_label1"
                                android:layout_width="130dp"
                                android:layout_height="50dp"
                                android:gravity="center"
                                android:text="小说精选"
                                android:textSize="15sp" />

                            <TextView
                                android:id="@+id/item_label2"
                                android:layout_width="130dp"
                                android:layout_height="50dp"
                                android:layout_marginLeft="5dp"
                                android:gravity="center"
                                android:text="摄影游记"
                                android:textSize="15sp" />

                            <TextView
                                android:id="@+id/item_label3"
                                android:layout_width="130dp"
                                android:layout_height="50dp"
                                android:layout_marginLeft="5dp"
                                android:gravity="center"
                                android:text="漫画手绘"
                                android:textSize="15sp" />

                            <TextView
                                android:id="@+id/item_label4"
                                android:layout_width="130dp"
                                android:layout_height="50dp"
                                android:layout_marginLeft="5dp"
                                android:gravity="center"
                                android:text="签约作者"
                                android:textSize="15sp" />
                        </LinearLayout>
                    </HorizontalScrollView>

                    <EditText
                        android:layout_width="match_parent"
                        android:layout_height="45dp"
                        android:layout_marginBottom="5dp"
                        android:layout_marginLeft="15dp"
                        android:layout_marginRight="15dp"
                        android:layout_marginTop="10dp"
                        android:gravity="center"
                        android:hint="搜索简书的内容和朋友" />

                    <View
                        android:id="@+id/line_divider"
                        android:layout_width="match_parent"
                        android:layout_height="1px"
                        android:layout_marginBottom="10dp"
                        android:background="@android:color/darker_gray"
                        android:visibility="gone" />

                </LinearLayout>
            </android.support.design.widget.CollapsingToolbarLayout>

            <TextView
                android:layout_width="match_parent"
                android:layout_height="50dp"
                android:layout_marginLeft="5dp"
                android:gravity="center"
                android:text="摄影游记"
                android:textSize="15sp" />
        </android.support.design.widget.AppBarLayout>



        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">


            <android.support.v4.view.ViewPager
                android:id="@+id/today_dynamic_viewpager"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </LinearLayout>

    </android.support.design.widget.CoordinatorLayout>


</LinearLayout>

**Comment by AllenCoder** [comment]
基于提供的xml，测试Ｄｅｍｏ的滚动事件和recyclerViwe的滚动事件 已经点击事件是可以的 ，请提供修改demo 的复现bug代码

**Comment by CymChad** [comment]
超过5天提问者没有回复开发者问题我先关闭，如还有问题提问者可以重新开一个issues，并给出相关信息便于开发者快速找到bug。
