### ISSUE TITLE
对一段代码有疑问

### ISSUE THREAD

**Issue by XiaoChongxc** [CymChad/BaseRecyclerViewAdapterHelper#1656]

**Comment by XiaoChongxc** [comment]
还有    int childSize = chidChilds.size();
        if (null != chidChilds && childSize > 0) {
            for (int i = 0; i < childSize; i++) {
                remove(parentPosition + 1);
            }
        }
这一段， 先获取到了 size， 在判断是不是null， 是不是迟了

**Comment by XiaoChongxc** [comment]
在demo上面测试了，ExpandableItem Activity 页面，remove level1 layout 有2个问题： 1  在展开情况下，remove 之后，关闭 在展开 level 0，只是removelevel1 的子类view,  2, 在 关闭情况下， remove之后，关闭 在展开 level 0，数据恢复

**Comment by CymChad** [comment]
最新的代码吗？

**Comment by XiaoChongxc** [comment]
前2天拉的最新代码，你拉一下，编译出来看看咯

**Comment by CymChad** [comment]
@GeekTR      恩 我看看

**Comment by GeekTR** [comment]
@CymChad  @XiaoChongxc  第一个item那里remove确实存在数据会恢复得问题，除了第一个都没有问题，我这边其实已经改好了，只是 忘了提交，我待会儿下班回家提交一下

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.33'
