### ISSUE TITLE
emptyView调用时机不对

### ISSUE THREAD

**Issue by yangkile** [CymChad/BaseRecyclerViewAdapterHelper#1657]
按正常使用逻辑应该是第一次加载完毕后,setNewdata 或者setdata 后emptyview才显示

然而目前在设置了emptyview后,默认状态下网络还没返回时就显示emptyview了

**Comment by CymChad** [comment]
看下你的初始化代码

**Comment by CymChad** [comment]
你可以看下demo的，有问题再给出你的代码

**Comment by lijunzz** [comment]
在ViewPager使用出现了这个情况，不清楚是不是ViewPager预加载导致的。
