### ISSUE TITLE
SwipeRefreshLayout  刷新问题

### ISSUE THREAD

**Issue by everyline** [CymChad/BaseRecyclerViewAdapterHelper#1659]
![default](https://user-images.githubusercontent.com/8476579/31814382-0a065bd4-b5bc-11e7-9f1c-fa462b73c159.png)
比如这样 他正在刷新  这时候我上啦加载 之后   然后在下拉刷新的时候   不能下拉了

**Comment by everyline** [comment]
是不是走error的时候 我写错代码了

**Comment by everyline** [comment]
当前列表数据为空，或者请求失败时  下拉就出不来了

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1641
