### ISSUE TITLE
HeaderView更新的问题

### ISSUE THREAD

**Issue by vihuela** [CymChad/BaseRecyclerViewAdapterHelper#166]
HeaderView是垂直的几个轮播图组成的，每次刷新数据调用adapter.addHeaderView(header);
里面代码有notify，但是新数据不生效。我现在做法是保存HeaderView的外部引用，然后外部去刷新它，貌似这种做法不恰当

还有个RecyclerView bug吧？就是item包含ViewPager，上下滑动复用后，Viewpager左右滑动会卡顿，估计什么被复用了。

**Comment by CymChad** [comment]
1.你可以用adapter原生的方法去单独刷新第一条。
2.这个就不太清楚了，因为没有做过item里面放入ViewPager。
