### ISSUE TITLE
BaseQuickAdapter都设置OnItemClick和OnItemLongClick,长按时itemClick也会调用

### ISSUE THREAD

**Issue by pananfly** [CymChad/BaseRecyclerViewAdapterHelper#1660]
应该是下面此段代码的处理问题了
private void bindViewClickListener(final BaseViewHolder baseViewHolder) {
        if (baseViewHolder == null) {
            return;
        }
        final View view = baseViewHolder.itemView;
        if (view == null) {
            return;
        }
        if (getOnItemClickListener() != null) {
            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    getOnItemClickListener().onItemClick(BaseQuickAdapter.this, v, baseViewHolder.getLayoutPosition() - getHeaderLayoutCount());
                }
            });
        }
        if (getOnItemLongClickListener() != null) {
            view.setOnLongClickListener(new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    return getOnItemLongClickListener().onItemLongClick(BaseQuickAdapter.this, v, baseViewHolder.getLayoutPosition() - getHeaderLayoutCount());
                }
            });
        }
    }

**Comment by pananfly** [comment]
使用代码如下：
public static void onQuickAdapterBindingCommand(final RecyclerView recyclerView,
                                               final BaseQuickAdapter adapter ,
                                               final ReplyCommand<Integer> loadMoreListener,
                                                    final ReplyCommand<Integer> itemClickCommand ,
                                                    final ReplyCommand<Integer> itemLongClickCommand) {
        if(adapter != null) {
            recyclerView.setAdapter(adapter);
            if(loadMoreListener != null){
                adapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
                    @Override
                    public void onLoadMoreRequested() {
                        if(loadMoreListener != null){
                            loadMoreListener.execute(adapter.getItemCount());
                        }
                    }
                }, recyclerView);
                adapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
                    @Override
                    public void onItemClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                        if(itemClickCommand != null){
                            itemClickCommand.execute(i);
                        }
                    }
                });

                adapter.setOnItemLongClickListener(new BaseQuickAdapter.OnItemLongClickListener() {
                    @Override
                    public boolean onItemLongClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                        if(itemLongClickCommand != null){
                            itemLongClickCommand.execute(i);
                        }
                        return true;
                    }
                });
            }
        }

    }

**Comment by foreverGoUp** [comment]
这个问题还没解决啊！！！2.9.34已测，依然有这个问题。 @pananfly 这个问题作者解决了吗？

**Comment by foreverGoUp** [comment]
已解决。原来不是框架问题，是android机制如此，在onItemLongClick回调中返回true，onItemLongClick处理了就不会再回调onItemClick
