### ISSUE TITLE
敬爱的开发组 如何设置拖拽超过一半生效 

### ISSUE THREAD

**Issue by hongyang51** [CymChad/BaseRecyclerViewAdapterHelper#1661]
如何设置拖拽超过一半生效

**Comment by elfman** [comment]
重写`ItemDragAndSwipeCallback`的`getSwipeThreshold `方法，返回`0.5`
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/HEAD/library/src/main/java/com/chad/library/adapter/base/callback/ItemDragAndSwipeCallback.java#L107

**Comment by hongyang51** [comment]
@elfman  谢谢 又学会一个技能

**Comment by hongyang51** [comment]
大大 不好用啊

**Comment by hongyang51** [comment]
@elfman @CymChad  
这样写之后 还是 需要拖动整整一行才会变换

 `  private class MyItemDragAndSwipeCallback extends ItemDragAndSwipeCallback{


        public MyItemDragAndSwipeCallback(BaseItemDraggableAdapter adapter) {
            super(adapter);
        }

        @Override
        public float getSwipeThreshold(RecyclerView.ViewHolder viewHolder) {
            return 0.4F;
        }
    }`

**Comment by hongyang51** [comment]
对了我说的是上下排序那种

**Comment by elfman** [comment]
@hongyang51 上下排序什么意思？请给个动态图演示下？

**Comment by hongyang51** [comment]
![device-2017-10-25-204131](https://user-images.githubusercontent.com/13972600/31999464-e8e03dd0-b958-11e7-90b3-b654c000ebc7.gif)
@elfman  需要这种拖动一半 的效果现在是 需要拖动整一行

**Comment by elfman** [comment]
@hongyang51 额，我理解错了，上面说的那个控制滑动删除的，控制拖拽的应该是重写`getMoveThreshold`函数。
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/HEAD/library/src/main/java/com/chad/library/adapter/base/callback/ItemDragAndSwipeCallback.java#L102

**Comment by hongyang51** [comment]
@elfman  比较尴尬的是 还是不生效 感觉改成任何值 效果都一样

**Comment by CymChad** [comment]
https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.Callback.html  这个是官方文档你可以参考一下。
