### ISSUE TITLE
三级展开 以及删除 或者刷新item的时候 还是有问题  比如删除某一个item的第三级的时候，下面的某个item第一级图片会变，还会报错

### ISSUE THREAD

**Issue by everyline** [CymChad/BaseRecyclerViewAdapterHelper#1662]
![default](https://user-images.githubusercontent.com/8476579/31871015-d67154f2-b7e3-11e7-9517-e0e3b05a4fa4.png)

**Comment by CymChad** [comment]
版本是？能够提供bug复现demo？

**Comment by everyline** [comment]
就是现在的版本  你点第三级   就能出现

**Comment by CymChad** [comment]
ok 我看看

**Comment by CymChad** [comment]
@GeekTR

**Comment by GeekTR** [comment]
@everyline 是demo里面ExpandableItem里面的Level1下面的item吗？我点击没有问题的啊

**Comment by GeekTR** [comment]
是Demo里面Level1下面的item吗？我这边点击似乎没有问题啊  @everyline

**Comment by GeekTR** [comment]
第一级的图片会变是因为Demo中的图片显示是根据当前实际所在位置显示的，并非真实数据，换成真实数据是不会有问题的，至于会报错奔溃我这边没有出现 @everyline

**Comment by everyline** [comment]
@GeekTR  稍微点快  真的会报错  就第三级的数据

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.33'
