### ISSUE TITLE
关于footView的显示问题！

### ISSUE THREAD

**Issue by STGing** [CymChad/BaseRecyclerViewAdapterHelper#1669]
1.当前使用的版本号 2.9.22
2.操作描述：
当前页面是购物页面，进入该页面之后：从后台请求数据，然后设置适配器（emptyView 和 footView都设置）。

![image](https://user-images.githubusercontent.com/28034901/31928816-1dabefb0-b8cc-11e7-89d0-b47976d200d5.png)

如上图所示，如果请求的有数据，就显示数据列表和footView，如果没有数据，就会显示emptyView。这里没有问题。

出现问题地方：
  在购物车中，删除商品数据之后，去其他页面添加商品到购物车，此时获取到数据，用adapter.setNewData();方法，然后adapter.notifyDataSetChanged(); 刷新数据。数据可以正常显示，但是footview就不会显示了？？？官方使用指南和demo中都没有看到这方面的问题，Issues记录里面也没找到，所以希望大佬要看到，帮忙指点一下，谢谢！

**Comment by STGing** [comment]
数据和footview正常显示的图片

![pic1](https://user-images.githubusercontent.com/28034901/31929304-1bae322a-b8ce-11e7-9af7-a38e1555198b.png)


删除原来数据，增加新数据之后，footView不正常显示的图片

![pic2](https://user-images.githubusercontent.com/28034901/31929383-643f49a2-b8ce-11e7-9a93-7a004df73714.png)

**Comment by 1109993488** [comment]
你是不是重写了getItemCount方法？

**Comment by STGing** [comment]
没有重写getItemCount方法，重写这个有什么用？？仅仅是重写联网获取数据，然后setNewData() ，然后刷新数据。其他都没有做！

**Comment by 1109993488** [comment]
getItemCount控制显示item的数量，重写后可能会造成不显示footer，按照你说的只是setNewData不会造成footer不显示
建议贴下adapter和操作代码，这样能快速查找错误

**Comment by STGing** [comment]
我发的第一张图片就是设置adapter的代码，下面是获取数据重写设置数据

```  
 if (code == 200) {
                                ShopCartGetDataBean.DataBean mData = getDataBean.getData();
                                List<ShopCartGetDataBean.DataBean.SkusBean> skuList1 = mData.getSkus();
                                if (skuList1.size() > 0) {
                                    //有数据
                                    skuList = skuList1;
                                    //设置所有商品状态为默认选中
                                    setAllGoodsStatus(skuList1);
                                    if (null != adapter) {
                                        adapter.setNewData(skuList1);
                                    
                                        //计算底部及footview里面的价格
                                        setGoodsAllPrice(skuList1);

                                        adapter.notifyDataSetChanged();
                                    }

                                }
                            }  
```

**Comment by 1109993488** [comment]
这段代码没看出什么问题，你看看能不能把代码贴全或提供个demo

**Comment by STGing** [comment]
已解决！把项目重新理了一遍，应该是逻辑某处有问题，哭。。。@1109993488感谢帮助！

**Comment by Jack-SunQi** [comment]
请问你是怎么解决的？我现在也遇到了相同的问题，找了很久都没找出原因
