### ISSUE TITLE
用的gradle，都没法同步，build.gradle里面加了依赖啊

### ISSUE THREAD

**Issue by ShallowMemory** [CymChad/BaseRecyclerViewAdapterHelper#167]
Error:Could not find com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.2.
Required by:
    CXReader:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by CymChad** [comment]
Add it in your root build.gradle at the end of repositories:

allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
