### ISSUE TITLE
有HeaderView在convert里面调用expand(position,false,false)出现崩溃

### ISSUE THREAD

**Issue by JiangSuyun** [CymChad/BaseRecyclerViewAdapterHelper#1670]
demo里加了一个按钮
![image](https://user-images.githubusercontent.com/10287693/31983632-ada0f898-b923-11e7-859f-30320d458612.png)
点击以后新增的数据并没有展开

2.9.32版本

**Comment by elfman** [comment]
请贴下log

**Comment by CymChad** [comment]
超过5天提问者没有回复开发者问题我先关闭，如还有问题提问者可以重新开一个issues，并给出相关信息便于开发者快速找到bug。
