### ISSUE TITLE
能否增加在RecyclerView的LongClick事件

### ISSUE THREAD

**Issue by samyhd** [CymChad/BaseRecyclerViewAdapterHelper#1673]
原生的mRecyclerView.setOnLongClickListener事件好似在加载数据后失效了。

能否扩展下加上LongClick事件的实现，有时一屏只有1、2项时，有长按事件的，那可以在RecyclerView空白地方长按弹出功能菜单。

**Comment by CymChad** [comment]
有长按事件的，http://www.jianshu.com/p/b343fcff51b0

**Comment by samyhd** [comment]
我指的不是Item或Item内子控件的长按事件呵，是RecyclerView内空白地方的长按，原生有此事件，但是显示数据后失效，以后修复此BUG把此事件另外公布出来。

**Comment by AllenCoder** [comment]
你的空白部分的点击实现是借助ItemTouchListener接口实现的？还是 填充空白的view实现点击事件的？

**Comment by AllenCoder** [comment]
正常不满一屏幕时，显示数据会创建新的viewholder，viewholder.setOnItemClickListener ,移除viewholder时，响应的空白部分点击事件也被移除了，所以不会有响应。
