### ISSUE TITLE
多布局setEmptyView是否无法全屏？

### ISSUE THREAD

**Issue by NanKerTDY** [CymChad/BaseRecyclerViewAdapterHelper#1675]
使用文档中BaseQuickAdapter 设置代理实现多布局setEmptyView显示没问题；
1.版本2.9.32
2.照着Demo写的，RecyclerView和View布局用的match_parent
3.尝试外面套一层也没用
4.目前还没找到问题原因

**Comment by CymChad** [comment]
看下代码，看下图

**Comment by NanKerTDY** [comment]
想死……前天调难了，无法解决。今天想着复现下，把之前代码放出来，然后，就没有然后了……好了。
当时如果重启或者clean下应该就解决了，不是第一次踩这坑了，擦。
