### ISSUE TITLE
树形添加数据问题

### ISSUE THREAD

**Issue by xiaokun19931126** [CymChad/BaseRecyclerViewAdapterHelper#1676]
![image](https://user-images.githubusercontent.com/18168000/32046161-c91e7db4-ba74-11e7-9487-aba913941033.png)
这是第一层级；
![image](https://user-images.githubusercontent.com/18168000/32046179-d89e27ee-ba74-11e7-9946-8f79e9edccae.png)
这是第二层级；现在是点击第二层级加载第三层级数据，adapter里面代码如下：

**Comment by xiaokun19931126** [comment]
![image](https://user-images.githubusercontent.com/18168000/32046330-55b99e2a-ba75-11e7-89c6-473dab111fbb.png)
回调接口到Activity中，更新数据，然后调用adapter.notifyDataSetChanged();
刷新完后，层级自动全部收缩，变成图一那个样子。

**Comment by xiaokun19931126** [comment]
属于动态添加第三层级数据，数据加上去了，但是那个notifyDataSetChanged一直就有问题。

**Comment by GeekTR** [comment]
@xiaokun19931126 插入数据的话可以试试notifyItemInserted方法局部刷新
