### ISSUE TITLE
BaseRecyclerViewAdapterHelper嵌套在ScrollView里面自动加载不正常

### ISSUE THREAD

**Issue by Nicesunqi** [CymChad/BaseRecyclerViewAdapterHelper#1678]
BaseRecyclerViewAdapterHelper嵌套在ScrollView里面自动加载不正常，一进页面它就开始自动加载了，总共有2000多条数据，直接出现了200多个请求，这个是什么问题呀

**Comment by Nicesunqi** [comment]
总共有2000多条数据，直接出现200多个请求

**Comment by CymChad** [comment]
这个rv和sv的滑动冲突。不建议嵌套使用。

**Comment by CymChad** [comment]
建议使用添加header或footer的方式把其他部分的页面嵌到RV中

**Comment by CymChad** [comment]
或者上拉不使用该库，组合第三方上拉下拉库使用。
