### ISSUE TITLE
在Android sudio3.0 中配置失败

### ISSUE THREAD

**Issue by llol** [CymChad/BaseRecyclerViewAdapterHelper#1680]
我把sudio升级到3.0后 依赖出错了，一直提示

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30. Open File Show Details
//我的配置如下
buildscript {
    repositories {
        jcenter()
       google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
       google()
        maven { url "https://jitpack.io" }
    }
}
//module中
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30'

我的gradle是4.1

**Comment by ZhangPeng0220** [comment]
试试这个。。我昨天搞了一晚上。
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        /*classpath'com.neenbedankt.gradle.plugins:android-apt:1.8'*/
    }
    repositories {
        google()
        jcenter {
            url "http://jcenter.bintray.com/"
        }
    }
}
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
    }
}

**Comment by AllenCoder** [comment]
新版本已经对Android studio 3.0 和gradle 4.1做了升级和兼容 

依赖方式变更不大

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

在 app的build.gradle 里面加入 
示例模板 
```

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.31'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
}
```
核心代码 只需要加入 
```
dependencies {
  
    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.31'
  
}
```

**Comment by llol** [comment]
好的，谢谢




------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年10月30日(星期一) 下午2:14
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "景占午"<714107186@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 在Android sudio3.0 中配置失败 (#1680)




新版本已经对Android studio 3.0 和gradle 4.1做了升级和兼容
 
依赖方式变更不大
 allprojects {     repositories {         google()         jcenter()         maven { url "https://jitpack.io" }     } }  
在 app的build.gradle 里面加入
 示例模板
  dependencies {     implementation fileTree(dir: 'libs', include: ['*.jar'])     implementation 'com.android.support:appcompat-v7:26.1.0'     implementation 'com.android.support.constraint:constraint-layout:1.0.2'     testImplementation 'junit:junit:4.12'     androidTestImplementation 'com.android.support.test:runner:1.0.1'     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'     implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.31'     implementation 'com.android.support:recyclerview-v7:26.1.0' }  
核心代码 只需要加入
 dependencies {        implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.31'    }

**Comment by ZhangPeng0220** [comment]
兵贵神速

**Comment by SomnusWu** [comment]
我也遇到这个问题，项目转为了kotlin的。
![tim 20171121165335](https://user-images.githubusercontent.com/7221064/33063137-87f3ebfe-cedc-11e7-9c2d-19f386683000.png)

![tim 20171121165240](https://user-images.githubusercontent.com/7221064/33063107-6fe6dee0-cedc-11e7-94ea-8526c9de03dd.png)
。

**Comment by SomnusWu** [comment]
![tim 20171121165407](https://user-images.githubusercontent.com/7221064/33063205-c4b9dcba-cedc-11e7-9550-32ea022e1af1.png)

**Comment by zlei123456** [comment]
BaseRecyclerViewAdapterHelper我把这个改成最新版本，就可以了。
