### ISSUE TITLE
在调用loadmoreend结束后,固定在这个位置,如果这个时候有新数据,调用setnewdata方法后上拉加载不可用

### ISSUE THREAD

**Issue by LambdaV5** [CymChad/BaseRecyclerViewAdapterHelper#1684]

**Comment by LambdaV5** [comment]
不会的,滚动位置固定了

**Comment by 1109993488** [comment]
setNewData调用后会重新开启加载更多，你看看setNewData后是否还做了什么操作

**Comment by 1109993488** [comment]
建议你不要用disableLoadMoreIfNotFullPage这个方法，自己判断如果是第一页大小不够一页的大小或小于一页的一半就调loadMoreEnd(true)关闭加载更多，这样不会显示没有更多数据
