### ISSUE TITLE
添加头部布局，使用Grid布局加间距时，每行的最后一个位置错误

### ISSUE THREAD

**Issue by HDJ999999** [CymChad/BaseRecyclerViewAdapterHelper#1685]
未使用头部布局时，底部间距位置计算正确，但使用添加头部布局后，底部间距位置计算错误
version 2.9.33
代码
 HomeFragmentAdapter adapter = new HomeFragmentAdapter(data);
        IndexOutGridLayoutManager manager = new IndexOutGridLayoutManager(getActivity(),5);
        bindingView.recyclerView.setLayoutManager(manager);
        GridOffsetsItemDecoration offsetsItemDecoration = new GridOffsetsItemDecoration(
                GridOffsetsItemDecoration.GRID_OFFSETS_VERTICAL);
        offsetsItemDecoration.setOffsetLast(false);
        offsetsItemDecoration.setOffsetEdge(false);
        offsetsItemDecoration.setVerticalItemOffsets((int) DisplayUtil.dip2px(getActivity(), 8));
        offsetsItemDecoration.setHorizontalItemOffsets((int) DisplayUtil.dip2px(getActivity(), 8));
        bindingView.recyclerView.addItemDecoration(offsetsItemDecoration);
        bindingView.recyclerView.setAdapter(adapter);

        adapter.addHeaderView(addHeadLayout());//不添加此行显示正常
![normal](https://user-images.githubusercontent.com/17296265/32269379-24aca84c-bf2d-11e7-891f-f689e817594d.png)
![abnormal](https://user-images.githubusercontent.com/17296265/32269380-24db36e4-bf2d-11e7-883d-956678bc2420.png)

![image](https://user-images.githubusercontent.com/17296265/32269773-4474d9a0-bf2e-11e7-9b5b-a6120691c0ef.png)

**Comment by CymChad** [comment]
头部也是一个item，只不过是不同类型的item，所以你可以在GridOffsetsItemDecoration里面根据这个规则做一下处理。

**Comment by HDJ999999** [comment]
已更改，谢谢！
