### ISSUE TITLE
建议收集箱

### ISSUE THREAD

**Issue by CymChad** [CymChad/BaseRecyclerViewAdapterHelper#1688]

**Comment by CymChad** [comment]
仅限于功能新增提议，使用过程中遇到的问题可以参考https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1591

历史建议

https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/907
#500
#77

**Comment by ITskyIT** [comment]
能加入自定义下拉刷新吗

**Comment by CymChad** [comment]
下拉刷新需要更改rv，由于这个库是adapter的定制库所以无法改变做到自定义下拉刷新 @ITskyIT

**Comment by gzxg1234** [comment]
建议convert加上payloads参数，想做局部刷新，发现实现的是没有payloads的onBindViewHolder

**Comment by zhaoxiuyu** [comment]
能做闪光效果吗？表示数据正在加载中。类似于这种。
![ij_227 zvf q pby s](https://user-images.githubusercontent.com/16554580/32822809-3d2b937c-ca15-11e7-8715-7b7393b15901.png)
有其他的库实现了这个，但是一起使用感觉有点多余，能集成进来吗

**Comment by xumengyin** [comment]
mOpenAnimationEnable 开启动画变量只能开启，能加入关闭的公共方法吗 自由的开关动画效果

**Comment by AutumnNight-SnowFingertips** [comment]
能增加侧滑删除类似的功能吗，就像你说的EasySwipeMenuLayout这个库的一个效果一样，不想再另外引一个库了，拜托

**Comment by congxiaoyao** [comment]
可以提供对databinding的支持吗 虽然可以自定义ViewHolder实现，但单独为databinding做支持的话内存和效率上都能更优化一步

**Comment by AllLuckly** [comment]
希望增加一个  组尾 的功能

**Comment by Android-KJY** [comment]
有木有配套使用的类似IOS，右滑关闭Activity的框架？

**Comment by lgwguang** [comment]
设置加载更多的监听后，首次进去会加载更多，下拉刷新也会加载更多，希望这个地方可以控制一下

**Comment by senjoeson** [comment]
能把你提供的官网的群号写对么?558178792这群能查到,我服你!

**Comment by RealMoMo** [comment]
能提供Jar架包？

**Comment by MariShunxiang** [comment]
BaseItemDraggableAdapter.java 能否增加 dragFixCount 属性，等于1的时候第一个item不可以拖动。等于2的时候第一个和第二个item不可以拖动。以此类推。

**Comment by wuzhgahj** [comment]
上拉加载可否加入 主动的上拉 不要自动的呢?

**Comment by XiongKe94** [comment]
提个建议 就是 多布局 类型 ，我的实体结构能不能继承那个接口MultiItemEntity，可以换成抽象的方法 让我们实现就行了 换成实体 还得封装 太麻烦了.

**Comment by CShawn** [comment]
onAttachedToRecyclerView方法中，将GridLayoutManager的HeaderView设置为了统一的独占一行，这是很不方便的，更多的情况下，GridLayoutManager的HeaderView是为了设置为一个Item，而不是独占一行，建议addHeaderView()改为可设置为Grid的Item或为当前项目中的独占一行效果。

**Comment by 15707901235** [comment]
能不能加个固定头部的功能。

**Comment by Zeroplucky** [comment]
可以加一些常用的ItemDecoration

**Comment by TheStar4Fate** [comment]
当集成IM组件时，由于第三方SDK的基础消息类无法修改，所以BaseMultiItemQuickAdapter也无法使用了，希望后续能修改下这种继承实现的模式

**Comment by parcool** [comment]
能添加一个defaultView吗？意思就是：adapter数据为空（在请求网络期间）设置一个空布局，这样也不会在用户等待刷新的时候一直看白屏。现在我用的是初始化的时候就setData(new ArrayList<>)，这样就会显示一个空布局，但是我希望第一次请求网络的时候是一个defaultView，没有数据才是另外的EmptyView。

**Comment by sweet2o09** [comment]
![image](https://user-images.githubusercontent.com/8555893/38549291-45b7ea88-3ce6-11e8-995a-d6605ed53748.png)
拖拽功能是否能提供个方法,有个这样的业务场景,就是item项上面有个上移或者下移的按钮,点击的话要实现Item切换,希望能实现拖拽的动效,如果拖拽功能能提供一个手动触发的方法的话那最好不过了

**Comment by wardenlzr** [comment]
悬浮吸顶
侧滑删除

**Comment by AnotherJack** [comment]
建议树形列表能增加悬浮吸顶的效果

**Comment by lifei1245** [comment]
建议在addData这个方法里进行类型的判断,当传入泛型的时候,传入的是一个集合,结果他添加的是一个Object对象进去,导致需要强转一次
```
```

**Comment by laohong** [comment]
建议加入吸顶效果

**Comment by codelishaohui** [comment]
作者有无考虑添加对[Paging library](https://developer.android.com/topic/libraries/architecture/paging/)的支持？

**Comment by AndroidJohnsonWang** [comment]
建议增加DiffUtil（AsyncListDiffer）配合使用，goolge推荐的做法，自己再配合ROOM使用真是爽

**Comment by Reginer** [comment]
增加对androidx中RecyclerView的支持。
https://android-developers.googleblog.com/2018/05/hello-world-androidx.html

**Comment by shaziln** [comment]
增加和删除都自带动画，建议替换某条数据时候也有动画，旧数据有退出动画，新数据有进入动画，最好还能够自定义。

**Comment by shaoniankehao** [comment]
使用该库的时候多次setEmptyView会报The specified child already has a parent. You must call removeView() on the child's parent first.
建议在setEmptyView方法内部加上下面的判断
`if (mEmptyView.getParent() != null && mEmptyView.getParent() instanceof ViewGroup) {
                ((ViewGroup) mEmptyView.getParent()).removeView(mEmptyView);
 }`

**Comment by aloe20** [comment]
建设增加头部悬浮吸顶效果

**Comment by axkza** [comment]
可以加一些常用的ItemDecoration，比如mutilItem这种，不同个数的item之间添加相同间距，如果没有ItemDecoration，完全不符合产品需求

**Comment by YanceyLin** [comment]
建议与希望可以添加一下头布局悬停和脚布局悬停的功能

**Comment by yangsanning** [comment]
树形展开收起布局高度缓动动画

**Comment by 86userused** [comment]
能加一个自定义的下拉刷新吗，说实话，现在系统的下拉刷新样式很少有产品经理看的上的。

**Comment by MissGongYi** [comment]
高版本不兼容低版本，使用1.6.7版本的老项目更新到2.9.30报错

**Comment by CymChad** [comment]
重新开一个模块来记录问题。

**Comment by helloworkcupid** [comment]
建议增加头部固定功能，尤其是headView 的固定，这样使用多
