### ISSUE TITLE
上拉后，不停调用onLoadMoreRequested，轻轻一拉可以拉出20-200页

### ISSUE THREAD

**Issue by tmxd09887** [CymChad/BaseRecyclerViewAdapterHelper#1694]
用的是2.9.33

用pageNum += 1;记录调用的次数

轻轻一拉可以拉出20-200页，实际recyclerview滚动只有几页

看文档里引用的版本是compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30',

2.9.33是不稳定吗？

**Comment by 1109993488** [comment]
1.是否设置了setPreLoadNumber
2.与嵌套ScrollView冲突

**Comment by tmxd09887** [comment]
1.2都不是

上拉loadmore出现无限回调，不知道是什么原因。

**Comment by 1109993488** [comment]
参考demo或贴出代码
你打印下onBindViewHolder的position看看设置100条数据不滑动的时候是不是position回掉到100，如果没有回掉到100就是写的有问题，如果到100了就属于ScrollView冲突

**Comment by tmxd09887** [comment]
adapter里的convert方法里输出了position，测试后发现，position滑到40,回调里的页数已经3-4页了。滑动过快了吗？无限回调是没有了。

以下是代码。

谢谢

`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        View rootView = inflater.inflate(R.layout.home_fragment, container, false);

        mRecyclerView = (RecyclerView) rootView.findViewById(R.id.recycler_view);
        mSwipeRefreshLayout = (SwipeRefreshLayout) rootView.findViewById(R.id.swipeLayout);

        GridLayoutManager layoutManager = new GridLayoutManager(context,4);
        mRecyclerView.setLayoutManager(layoutManager);

        initAdapter();
        initRefreshLayout();

        return rootView;
    }


    private void initAdapter() {
        mAdapter = new homeAdapter();

        mAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                mRecyclerView.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        pageNum += 1;
                        getP().loadData(pageNum,"MORE_DATA",mTitle);
                        XLog.d("this is pagenum",String.valueOf(pageNum));
                        mAdapter.notifyDataSetChanged();
                        mAdapter.loadMoreComplete();
                    }

                }, DELAY_TIME);
            }
        },mRecyclerView);

        mAdapter.setPreLoadNumber(3);

        mRecyclerView.setAdapter(mAdapter);
    }

    private void initRefreshLayout() {
        mSwipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                mAdapter.setEnableLoadMore(false);
                XLog.d("on refresh start");
                pageNum = 0;
                getP().loadData(1, "REFRESH_DATA", mTitle);
                mSwipeRefreshLayout.setRefreshing(false);
            }
        });
    }

`

**Comment by 1109993488** [comment]
你的一页有多少，一屏能显示多少条？现在还有问题吗

**Comment by tmxd09887** [comment]
一页40个。一屏30多个。问题没有解决。我用了其他控件代替。一直会关注BaseRecyclerViewAdapterHelper，谢谢。

**Comment by 1109993488** [comment]
没看到你是怎么处理数据的，如果滑动到底部没有数据了还继续调loadMoreComplete就会无限循环加载
具体你可以参考下demo
