### ISSUE TITLE
setOnItemChildClickListener事件获取view.getTop()一直为0

### ISSUE THREAD

**Issue by yxlku** [CymChad/BaseRecyclerViewAdapterHelper#1695]
请问为什么在setOnItemChildClickListener事件获取view.getTop()一直为0，但是在setOnItemClickListener中view.getTop()却能获取到值；

**Comment by minmei** [comment]
同问，也碰到这个问题了

**Comment by AllenCoder** [comment]
正确的获取view.getTop的方法应该是 这样

```
View view = recyclerview.getLayoutManager().findViewByPosition(postion);
view.getTop();

```

clickListener 接口返回的view 会存在视图复用的情况，导致获取的view位置不准确
