### ISSUE TITLE
头部问题

### ISSUE THREAD

**Issue by niezhiyang** [CymChad/BaseRecyclerViewAdapterHelper#1696]
当头部过于长的时候, 会出现首次漏不全,但是可以滑动

**Comment by 1109993488** [comment]
漏不全？header也是个item

**Comment by niezhiyang** [comment]
你添加一个比较长的头部试一试
每次启动的时候会把头部最上面的遮盖住
相当于往上已经滑了一会了
如果你往下滑动 还会漏出来

**Comment by niezhiyang** [comment]
<?xml version="1.0" encoding="utf-8"?>

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                  xmlns:app="http://schemas.android.com/apk/res-auto"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent"
                  android:orientation="vertical">
<LinearLayout
    android:background="#ff0"
    android:layout_width="match_parent"
    android:layout_height="100dp"></LinearLayout>
    <View
        android:layout_width="match_parent"
        android:layout_height="0.5dp"/>
        <View
            android:id="@+id/banner_head_index"
            android:layout_width="match_parent"
            android:layout_height="150dp"
            />

        
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="88dp"
            android:paddingBottom="10dp"
            android:paddingLeft="5dp"
            android:paddingRight="5dp"
            android:paddingTop="10dp">

            <LinearLayout
                android:id="@+id/ll_index_borrow"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="center"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                    />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="5dp"
                    android:textColor="@android:color/black"/>

            </LinearLayout>

            <LinearLayout
                android:id="@+id/ll_index_invest"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="center"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                   />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="5dp"
                    android:textColor="@android:color/black"/>

            </LinearLayout>

            <LinearLayout
                android:id="@+id/ll_index_haipay"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="center"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                   />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="5dp"
                    android:textColor="@android:color/black"/>

            </LinearLayout>

            <LinearLayout
                android:id="@+id/ll_index_shop"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="center"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                   />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="5dp"
                    android:textColor="@android:color/black"/>

            </LinearLayout>

            <LinearLayout
                android:id="@+id/ll_index_cardbag"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="center"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                    />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="5dp"
                    android:textColor="@android:color/black"/>

            </LinearLayout>

        </LinearLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="10dp"
           />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
              />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="5dp"
               />


            <View
                android:layout_width="0dp"
                android:layout_height="1dp"
                android:layout_weight="1"/>

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                />

            <TextView
                android:id="@+id/tv_index_all_repay"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginRight="10dp"
              />

        </LinearLayout>

        
        <LinearLayout
            android:id="@+id/ll_index_now_borrow"
            android:layout_width="match_parent"
            android:layout_height="200dp">

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_alignParentTop="true"
                android:layout_weight="1"
                android:gravity="center"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/tv_index_borrow_sum"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"

                    android:textSize="16sp"/>

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="10sp"/>


            </LinearLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_alignParentTop="true"
                android:layout_weight="1"
                android:gravity="center"
                android:orientation="vertical">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:textColor="#1e1c1c"
                        android:textSize="16sp"/>

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:textColor="#6c6b6b"
                        android:textSize="12sp"/>
                </LinearLayout>

                <TextView
                    android:layout_width="100dp"
                    android:layout_height="40dp"
                    android:layout_marginBottom="50dp"
                    android:gravity="center"
                    android:textColor="#F8F8F8"
                    android:textSize="16sp"/>

            </LinearLayout>

        </LinearLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="10dp"
           />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="10dp"
            android:layout_marginTop="10dp"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="5dp"
               />

            <View
                android:layout_width="0dp"
                android:layout_height="1dp"
                android:layout_weight="1"/>

            <TextView
                android:id="@+id/tv_index_invest_more"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
               />

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
               />

        </LinearLayout>

        <View
            android:id="@+id/rv_invest_ad"
            android:layout_width="match_parent"
            android:layout_height="100dp"/>

        <View
            android:layout_width="match_parent"
            android:layout_height="10dp"
          />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="10dp"
            android:layout_marginTop="10dp"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
               />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="5dp"
                />

            <View
                android:layout_width="0dp"
                android:layout_height="1dp"
                android:layout_weight="1"/>

            <TextView
                android:id="@+id/tv_index_shanfq_more_1"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
               />

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
               />

        </LinearLayout>
        <ImageView
            android:id="@+id/iv_shop"
            android:layout_marginTop="5dp"

            android:layout_width="match_parent"
            android:layout_height="100dp"></ImageView>
        <LinearLayout
            android:layout_marginTop="5dp"
            android:layout_width="match_parent"
            android:layout_height="180dp">
            <View
                android:id="@+id/banner_head_index_shop"
                android:layout_marginRight="2dp"
                android:layout_weight="1"
                android:layout_width="0dp"
                android:layout_height="match_parent"/>
            <LinearLayout
                android:layout_marginLeft="2dp"
                android:layout_weight="1"
                android:orientation="vertical"
                android:layout_width="0dp"
                android:layout_height="match_parent">
                <ImageView
                    android:id="@+id/iv_index_shop_top"
                  android:layout_marginBottom="1dp"
                    android:layout_weight="1"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"/>
                <ImageView
                    android:id="@+id/iv_index_shop_bottom"
                    android:layout_marginTop="1dp"
                    android:layout_weight="1"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"/>
            </LinearLayout>
        </LinearLayout>
        <View
            android:layout_width="match_parent"
            android:layout_height="10dp"
          />
    </LinearLayout>
你添加这么长的头部试一试

**Comment by niezhiyang** [comment]
我知道问题了 
是因为头部中有个reclerview,
大神,怎样解决呀

**Comment by 1109993488** [comment]
#1516

**Comment by niezhiyang** [comment]
不管用

**Comment by 1109993488** [comment]
你要在最外层RecyclerView根布局添加
