### ISSUE TITLE
建议：关于点击事件的解耦问题 ,希望再解耦点放出部分可供重写的方法

### ISSUE THREAD

**Issue by MirkoWu** [CymChad/BaseRecyclerViewAdapterHelper#1699]
//原代码  部分
private void bindViewClickListener(final BaseViewHolder baseViewHolder) {
        if (baseViewHolder == null) {
            return;
        }
        final View view = baseViewHolder.itemView;
        if (view == null) {
            return;
        }
        if (getOnItemClickListener() != null) {
            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    getOnItemClickListener().onItemClick(BaseQuickAdapter.this, v, baseViewHolder.getLayoutPosition() - getHeaderLayoutCount());
                }
            });
        }
        if (getOnItemLongClickListener() != null) {
            view.setOnLongClickListener(new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    return getOnItemLongClickListener().onItemLongClick(BaseQuickAdapter.this, v, baseViewHolder.getLayoutPosition() - getHeaderLayoutCount());
                }
            });
        }
    }
@ChadCym 关于item 的点击事件 ，希望能再细分下。现在有这样的场景，我要在adapter 中重写到item的点击事件，进行再封装，但偏偏拿不到当前的View ,所以能希望实现以下分解。这样修改对现有的使用者没有任何影响，但对以后的扩展有很大帮助,我们可以在自己的listener触发前统一做一些处理。
以下修改代码仅供参考：
    private void bindViewClickListener(final BaseViewHolder baseViewHolder) {
        if (baseViewHolder == null) {
            return;
        }
        final View view = baseViewHolder.itemView;
        if (view == null) {
            return;
        }
        if (getOnItemClickListener() != null) {
            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    int position = baseViewHolder.getLayoutPosition() - getHeaderLayoutCount();
                    setOnItemClick(v, position);
                }
            });
        }

        if (getOnItemLongClickListener() != null) {
            view.setOnLongClickListener(new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    int position = baseViewHolder.getLayoutPosition() - getHeaderLayoutCount();
                    return setOnItemLongClick(v, position);
                }
            });
        }
    }

    //点击事件 提取出来 以供复写
    protected void setOnItemClick(View v, int position) {
        //do something...
        getOnItemClickListener().onItemClick(BaseQuickAdapter.this, v, position);
    }

    //长按事件事件 提取出来 以供复写
    protected boolean setOnItemLongClick(View v, int position) {
        //do something...
        return getOnItemLongClickListener().onItemLongClick(BaseQuickAdapter.this, v, position);
    }

**Comment by CymChad** [comment]
已合成并发布版本

**Comment by MirkoWu** [comment]
thanks
