### ISSUE TITLE
不方便使用Data Binding功能

### ISSUE THREAD

**Issue by w420984** [CymChad/BaseRecyclerViewAdapterHelper#17]
构造函数只支持传itemview的布局id，这样不方便使用Data Binding功能，能加上构造函数传自定义view进去的功能么

**Comment by zpfang9008** [comment]
应该可以自己改一下就行吧，最近也在看google 那个TODO-DataBinding，还不太熟练。

**Comment by CymChad** [comment]
恩 是的，你可以把你需要使用的方式发我一下，我给你加个构造也可以

**Comment by CymChad** [comment]
你加一下Q群 558178792 Q聊方便一些

**Comment by CymChad** [comment]
已解决 compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.6.5'

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.0' 已经对baseviewholder支持扩展了，并且demo新增了databinding使用的案例
