### ISSUE TITLE
关于处理 edittext 的小问题。

### ISSUE THREAD

**Issue by iauhsil** [CymChad/BaseRecyclerViewAdapterHelper#1700]
由于我有多个布局  头布局+内容+尾部局
按照文档处理文本框的方法去处理 edittext 的问题。
  
    @Override
    public void onEditTextAfterTextChanged(Editable editable, int position) {

    在这个回调里面。返回的position 可能有头布局 和尾部局的 position 。所以不知道这个问题该怎么处理 。
}

**Comment by CymChad** [comment]
可以减去头部的数量,adapter有方法获取头部和尾部count的。  头部和尾部都可以看做一个item。
