### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by qinyang1018** [CymChad/BaseRecyclerViewAdapterHelper#1701]
版本2.9.30    使用BaseQuickAdapter实现自定义表单 通过继承BaseFormViewHolder 用多个不同viewholder控制。  给列表添加head后直接越界
![image](https://user-images.githubusercontent.com/15726024/32366489-483187ae-c04c-11e7-88a7-3cf4b4ed3993.png)
![image](https://user-images.githubusercontent.com/15726024/32366497-54c4e90c-c04c-11e7-8192-f4f2291a7fb2.png)
走了这句减成-1了

**Comment by 1109993488** [comment]
你是否重写了getItemViewType方法？

**Comment by qinyang1018** [comment]
是的  
![image](https://user-images.githubusercontent.com/15726024/32475374-0b5f340a-c337-11e7-819c-1a78e7b6d255.png)

**Comment by 1109993488** [comment]
不用重写这个方法就可以，如果非要重写可以重写getDefItemViewType这个方法

**Comment by qinyang1018** [comment]
我不重写getViewType会报错，  然后重写了getDefItemViewType，不添加head正常，添加head后报下面的错误
![image](https://user-images.githubusercontent.com/15726024/32475932-ff028204-c339-11e7-95cb-efcd1cf65388.png)

![image](https://user-images.githubusercontent.com/15726024/32475918-e6f7203e-c339-11e7-8fe2-445f87234db5.png)

**Comment by 1109993488** [comment]
你检查下你的onCreateViewHolder、onCreateDefViewHolder方法是否有问题，onCreateViewHolder返回空会报这个错

**Comment by qinyang1018** [comment]
![image](https://user-images.githubusercontent.com/15726024/32478929-f2ee94cc-c34c-11e7-9bfc-8e63d951c39b.png)
我这个得到的viewviewType是273.

**Comment by 1109993488** [comment]
不要重写onCreateViewHolder，你可以重写onCreateDefViewHolder

**Comment by qinyang1018** [comment]
可以了  谢谢
