### ISSUE TITLE
设置多布局的type类型只能是int类型,建议可以是其它类型.如String

### ISSUE THREAD

**Issue by keaitao0321** [CymChad/BaseRecyclerViewAdapterHelper#1703]
setMultiTypeDelegate(new MultiTypeDelegate<HomeInfo.ArrayBean>() {
            @Override
            protected int getItemType(HomeInfo.ArrayBean arrayBean) {
                return 0;
            }
        });

这里返回的只能是int类型,但是我的后台返回bean对象type是String类型的

**Comment by CymChad** [comment]
这个开发者可以将string装换成相对于的type。因为item的type最终肯定是int

**Comment by keaitao0321** [comment]
嗯,解决了,只是我的类型有很多,我不明白为什么只能是int类型

**Comment by CymChad** [comment]
adapter的type类型，原始的api规则就是int类型。

**Comment by keaitao0321** [comment]
好的,谢谢,没看源码啊 --
