### ISSUE TITLE
有header时,列表数据为空,设置emptyview能不能利用剩余的屏幕控件

### ISSUE THREAD

**Issue by yyzl0418** [CymChad/BaseRecyclerViewAdapterHelper#1708]
有header时,列表数据为空,设置emptyview能不能利用剩余的屏幕控件,不想超出屏幕显示emptyview,超出显示觉得有点奇怪

**Comment by CymChad** [comment]
收到，我看看如何优化。

**Comment by CymChad** [comment]
我看了下源码，这个你可以通过动态设置emptyview的layoutParams来做到不超出。

**Comment by yyzl0418** [comment]
我看了emptyview的layoutparams已经被写死成match parent了,应该怎么修改,求帮助
