### ISSUE TITLE
希望解决一下RecyclerView嵌套RecyclerView时数据显示不完的问题

### ISSUE THREAD

**Issue by hexianqiao3755** [CymChad/BaseRecyclerViewAdapterHelper#1709]
找到了类似的解决办法, 但是好像无法使用到BaseRecyclerViewAdapterHelper里去,
希望可以出一个解决方案
http://blog.csdn.net/codekxx/article/details/71218859

**Comment by CymChad** [comment]
RecyclerView和RecyclerView嵌套你可以看下demo的clickitem这个案例有这个
