### ISSUE TITLE
于新版本问题：addHeader

### ISSUE THREAD

**Issue by ybADMIN** [CymChad/BaseRecyclerViewAdapterHelper#171]
新版本问题：由于要监听recycleView滑动对头部进行放大缩小，新版本将头部视图添加到LinearLayout中后获取到Header的值一直是固定的，这个应该怎么弄呢，我通过反射获取到头部视图可这个头部视图的Bottom一直闪动的改变如：bottom=0-->bottom =120--->bottom=0--->bottom=125--->bottom=0
一直都是正常值与数值0交替出现

**Comment by shichaohui** [comment]
在添加Header的时候就已经有了Header View的引用了啊，不需要用反射获取，Header缩放直接缩放这个Header或者Header的背景图片就行了，不需要处理mHeaderLayout。

**Comment by ybADMIN** [comment]
这个问题我已经解决了谢谢你的回答，不过我的缩放使用的是SpringView来做的，因此需要获得Header的高度，最后我还是用反射获取到HeaderLayout高度的
