### ISSUE TITLE
滑动删除除了可以使用canvas绘制文字外，可以添加布局么？

### ISSUE THREAD

**Issue by jeesezh** [CymChad/BaseRecyclerViewAdapterHelper#1711]
![image](https://user-images.githubusercontent.com/19542480/32433238-4cfd0ef4-c315-11e7-851a-aa451d4ba2ac.png)
我在ItemDragAndSwipeCallback这个类里面没有找到合适的方法--

**Comment by jeesezh** [comment]
我用canvas画了布局
![image](https://user-images.githubusercontent.com/19542480/32436108-f18cd83e-c31d-11e7-8ad5-a20c01e91eb5.png)
![image](https://user-images.githubusercontent.com/19542480/32436113-f4521624-c31d-11e7-9d9c-9afd7b1c859f.png)
左滑的时候，绘制出的内容可以和滑动一起动，但是右滑出的就固定在那儿，
请问这个问题怎么解决呢

**Comment by elfman** [comment]
右滑时你要从Canvas的右边画，右对齐。

**Comment by elfman** [comment]
侧滑菜单需要使用其他库，推荐https://github.com/anzaizai/EasySwipeMenuLayout

**Comment by jeesezh** [comment]
使用右对齐解决了，谢谢
