### ISSUE TITLE
将RecyclerView放在ConstraintLayout中出现布局问题

### ISSUE THREAD

**Issue by Troll4it** [CymChad/BaseRecyclerViewAdapterHelper#1712]
您好。。宇明哥，这是我写的一个demo出现的问题，实现效果和录制的视频都在文件夹中，已经发你邮箱同时请看activity_main这个布局文件，里面有我的一点点说明，请教下这是这个问题如何引起的，谢谢!!!!!

**Comment by CymChad** [comment]
收到，我有空看看

**Comment by Troll4it** [comment]
@CymChad 此问题用原生的Adapter也测试过了，也出现同样的情况，不是BRVAH的问题。只要用ConstraintLayout包裹RV,item的Layout的高度固定就出现此情况，具体什么原因还的具体去研究下

**Comment by CymChad** [comment]
恩 好的 收到
