### ISSUE TITLE
release 版本 不显示问题

### ISSUE THREAD

**Issue by CcSimple** [CymChad/BaseRecyclerViewAdapterHelper#1714]
如标题. 
用的是com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.33.
debug模式正常显示.

**Comment by CymChad** [comment]
有复现demo吗？

**Comment by AllenCoder** [comment]
加入混淆规则试一下，你的数据类或者自定义viewholder 会被混淆掉，这里最容易出现问题

**Comment by AllenCoder** [comment]
可以debug模式下开启 混淆调试一下

**Comment by CcSimple** [comment]
感谢你的回复, 昨天已经找出原因了. 正是因为混淆导致的问题






------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年11月8日(星期三) 下午3:20
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: " "<840054486@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] release 版本 不显示问题 (#1714)




加入混淆规则试一下，你的数据类或者自定义viewholder 会被混淆掉，这里最容易出现问题

**Comment by CcSimple** [comment]
感谢你的回复, 昨天已经找出原因了. 因为混淆导致的问题







------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年11月8日(星期三) 下午3:20
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: " "<840054486@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] release 版本 不显示问题 (#1714)




有复现demo吗？

**Comment by sunnyamuren** [comment]
我也遇到了相同的问题 使用版本是 2.9.35，请问怎么解决呢？
