### ISSUE TITLE
adapter.getItem()   ClassCastException

### ISSUE THREAD

**Issue by BinarySatan** [CymChad/BaseRecyclerViewAdapterHelper#1715]
界面上有两个按钮， 对应两个不同的adapter 和不同的数据源，   当我通过 onSimpleItemClick获取数据源的时，会报异常。 类似下面的伪代码。

  
`  if (directory.isSelected()) {  

                   BookDirectoryEntity bookDirectoryEntity = (BookDirectoryEntity) adapter.getItem(position);
                   callback.onJumpDirectory(bookDirectoryEntity.chapterId);
                } else { 
                    BookMarkEntity bookMarkEntity = (BookMarkEntity) adapter.getItem(position);
                    callback.onJumpBookMark(bookMarkEntity.chapterNumber, bookMarkEntity.position);
                }`

看起来这样， 界面已经变了， 但是 getItem出来的数据源类型缺不是同一个，  非必现问题， 但是我来回点的话 也总会出现。
库版本是 2.9.31

--------------------------------

情况出现在， 如果我在 第一个按钮的adapter里 滑动的话， 在set新的adpter, 这时界面已经变了，但是点击item的时候，  adapter.getItem 的数据源类型 还是第一个按钮类型的。
还有onSimpleItemClick 不会调用， 除非position <=2 。 纳闷了。

**Comment by AllenCoder** [comment]
onSimpleItemClick 这个接口应该用的是 recyclerView.addItemTouchListener这个接口，建议把点击事件 切换到 adapter.setOnItemClickListener 针对不同的adapter采用不同的点击事件，方便区分数据源和视图
