### ISSUE TITLE
使用loadMoreEnd后,如何继续使用上拉加载更多功能.

### ISSUE THREAD

**Issue by MahatmaSun** [CymChad/BaseRecyclerViewAdapterHelper#1718]
使用了loadMoreEnd方法后, BaseQuickAdapter类里的mNextLoadEnable设置为了false,禁止使用上拉加载更多功能,但是我们的需求是想要可以无限上拉加载更多. 请问现在有对应的方法修改mNextLoadEnable的值吗?

**Comment by MahatmaSun** [comment]
另外想麻烦问一下 为什么官网的qq群搜不到. 说没有找到该群

**Comment by 1109993488** [comment]
目前这种方法没法做到关闭加载再触发回调
群号:558178792

**Comment by MahatmaSun** [comment]
![qq 20171108202722](https://user-images.githubusercontent.com/20633789/32549138-4ce4a5a8-c4c3-11e7-90ee-40e7cc9937c1.png)

@1109993488  好的,我知道了.那我再想想别的办法吧.  麻烦您看下截图.我搜索的就是这个群号,但是还是提示没有这个群.

**Comment by MahatmaSun** [comment]
另外,我可能对我想要的需求没有表述清楚. 我们是想要实现,在没有数据的情况下, 首先是显示加载过程的文字"正在加载...", 然后显示"没有更多数据了"字样,显示1秒钟后隐藏"没有更多数据了"字样.
我目前的实现方法是,当没有数据的时候 先调用loadMoreEnd(false); -----显示"没有更多数据了"字样.   然后1秒延迟后调用loadMoreEnd(true);-----隐藏"没有更多数据了"字样.
用户再向上拉动时 已久需要"正在加载"---显示"没有更多"--隐藏"没有更多". 
建议放开对mNextLoadEnable值的修改.谢谢

**Comment by 1109993488** [comment]
可以设置enableLoadMoreEndClick实现点击没有更多数据再次回调加载更多

**Comment by 1109993488** [comment]
再向上拉动只能自己监听滑动才行

**Comment by hezhipengzipp** [comment]
这个问题就解决了？
