### ISSUE TITLE
不给你点星，就不让加Q群，这种行为真丑陋

### ISSUE THREAD

**Issue by BunnyAndLiLy** [CymChad/BaseRecyclerViewAdapterHelper#172]

**Comment by CymChad** [comment]
入群门槛：star我的项目，为什么呢？

有门槛，都有人加入的话证明加入者求知欲强。
确定star了我的项目，肯定看过源码或者用过我的项目，这样入群后才有更深入技术的交流，群里面内容质量才能够得到保障。
选拔人才，从使用者中选择，让他们加入开发或维护，这样才能把这个东西做好做大。

**Comment by pexcn** [comment]
前排围观……
