### ISSUE TITLE
我做了一个侧滑删除菜单，并且整个列表是有分页上拉加载更多。当我删除后，调用remove方法，会触发onLoadMoreRequested

### ISSUE THREAD

**Issue by PantomZ** [CymChad/BaseRecyclerViewAdapterHelper#1720]
我觉得BaseQuickAdapter,是不是应该加个类似LoadMoreComplete的方法，阻止调用onLoadMoreRequested.

**Comment by CymChad** [comment]
onLoadMoreRequested 的触发机制是最后一个item可见的。 有自带的`loadMoreEnd`关闭加载方法。

**Comment by PantomZ** [comment]
我每一页加载10条数据，我第一页加载了10条，然后我删除了第一条，这个时候，onLoadMoreRequested 会被触发，总条数为9条，我调用notificationDataChanged后，遍历到最后一个position:9的，触发了onLoadMoreRequested,但是position:9不在当前屏幕
