### ISSUE TITLE
拖拽效果

### ISSUE THREAD

**Issue by 384516108** [CymChad/BaseRecyclerViewAdapterHelper#1724]
你好，我想实现一个功能  点击item  此时被点击的item滑动到列表顶部（滑动效果和拖拽效果一样）
这个功能 能扩展实现吗

**Comment by CymChad** [comment]
可以使用原始的替换位置方法来实现也是带动效的。

**Comment by 384516108** [comment]
好的 谢谢了

**Comment by sweet2o09** [comment]
@iKoonkoon 请问你是如何实现的?继承BaseItemDraggableAdapter中能实现么

**Comment by iKoonkoon** [comment]
最后我没有实现这个功能，需求改了
