### ISSUE TITLE
自动加载更多的问题

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#1725]
adapter.disableLoadMoreIfNotFullPage()这个方法不是当列表长度不足一页的时候就不会调用onLoadMoreRequested（）方法的嘛？为什么我的列表只有一项的时候还是在回调onLoadMoreRequested方法？

**Comment by CymChad** [comment]
建议你在onLoadMoreRequested里面判断如果list size不满足一页的时候关闭上拉加载。可以见demo
