### ISSUE TITLE
BaseMultiItemQuickAdapter能否通过setExpanded保留之前的状态

### ISSUE THREAD

**Issue by litforest** [CymChad/BaseRecyclerViewAdapterHelper#1726]
使用BaseMultiItemQuickAdapter，我希望在setNewData之后依然保有之前的expand/collapse状态，因此我保存了之前数据中各个Level0Item的isExpanded值，再对新的数据setExpanded，最后再setNewData。效果并没有保留之前的状态，请问能否通过这个方式实现，还是在setNewData后expand才可以。

**Comment by CymChad** [comment]
你可以根据全部打开方法的思路去做你的指定打开的方法。是可行的。

**Comment by Tracycuizh** [comment]
> 使用BaseMultiItemQuickAdapter，我希望在setNewData之后依然保有之前的expand/collapse状态，因此我保存了之前数据中各个Level0Item的isExpanded值，再对新的数据setExpanded，最后再setNewData。效果并没有保留之前的状态，请问能否通过这个方式实现，还是在setNewData后expand才可以。

请问楼主解决了吗？我这里有相同的问题
