### ISSUE TITLE
关于树形列表的加载更多

### ISSUE THREAD

**Issue by WayneLyn** [CymChad/BaseRecyclerViewAdapterHelper#1727]
使用BaseMultiItemQuickAdapter的时候？想咨询一下，由于我使用过程中，二级item是点击一级item中的某一条后进行网络请求再add进来的，但是这个地方二级菜单数据可能会很多，所以想在二级菜单做上拉加载更多。请问有没有好的办法区分一级菜单和二级菜单的上拉加载。

**Comment by CymChad** [comment]
暂不支持，只支持整个数据源加载。

**Comment by lianzigeng** [comment]
希望这个可以支持一下的,谢谢啦
