### ISSUE TITLE
关于ScrollView嵌套RecyclerView的问题。

### ISSUE THREAD

**Issue by weipeilong123** [CymChad/BaseRecyclerViewAdapterHelper#1734]
我在用到ScrollView嵌套RecyclerView时，出现了RecyclerView只显示10条数据的问题该如何解决？
我试过了用FullyLinearLayoutManager、recyclerView.setNestedScrollingEnabled(false)、ScrollView中的android:fillViewport="true"、以及重写ScrollView等方法都未能解决。所以到这里来请教。

**Comment by GillX** [comment]
请问你找到解决方法吗？
我也遇到这个问题

**Comment by AllenCoder** [comment]
1.单独不嵌套时测试recyclerview是否可以正常显示完所有的数据
2. recyclerview建议设置 android:minHeight ="xxxxxx"
3. ScrollView 的高度设置match_parent 
4. 在ScrollView 中加入 android:fillViewport="true"
5. 如果还是无法显示，换成NestScrollView 替换ScrollView测试

**Comment by weipeilong123** [comment]
问题已解决，我的方法是在RecyclerView外层套一个RelativeLayout，宽高设为wrap_content。

**Comment by tangchao0106** [comment]
6.0显示不完成，，重写onMeasure方法就好了。
