### ISSUE TITLE
点击水波纹效果不明显

### ISSUE THREAD

**Issue by ZhangPeng0220** [CymChad/BaseRecyclerViewAdapterHelper#1736]
在使用item点击的效果功能的时候，我按照要求加入代码
` multipleItemAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
               // Log.d(TAG, "onItemClick: ");
                Toast.makeText(getContext(), "onItemClick" + position, Toast.LENGTH_SHORT).show();
                Intent intent = new Intent();
                intent.setClass(getContext(),ArticalDetailActivity.class);
                getContext().startActivity(intent);
            }
        });`
但是没有见到水波纹效果，后边查看了issues，发现了
` android:foreground="?android:attr/selectableItemBackgroundBorderless">`
将他添加到了自己的cardview中，但是效果不如demo中的itemclickactivity里的效果那么明显，我也查看了demo中item_click_view中的代码，也没有发现相关属性，我想知道你们是如何添加水波纹效果的。

我查看了touch_bg，但是不解其意，能不能详细讲解一下，自己再添加touch_bg为后置效果的时候并不好用，我把drawable文件夹和drawable—v21下面的touch_bg都拿过来了，也没见效果

**Comment by ZhangPeng0220** [comment]
![image](https://user-images.githubusercontent.com/18100741/32716057-85def708-c88f-11e7-8373-e12c81fa22f5.png)
这是相关代码

**Comment by AllenCoder** [comment]
可能跟你的UI效果图的颜色搭配有关，关于水波纹设置没有什么特别的地方，建议提供相关可测试Demo ,以便排查我们的问题。

**Comment by ZhangPeng0220** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="5dp"
    android:layout_marginRight="5dp"
    android:layout_marginTop="5dp"
    app:cardCornerRadius="5dp"
    app:cardPreventCornerOverlap="false"
    app:cardUseCompatPadding="true"
    app:cardElevation="1dp"
   >
    

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="0dp"
        android:padding="5dp"
        android:orientation="horizontal"
        android:background="@drawable/touch_bg">

        <TextView
            android:id="@+id/story_title_tv"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:padding="5dp"
            android:layout_marginRight="5dp"
            android:textColor="@android:color/black"
            android:maxLines="3"
            android:textSize="20dp"
            android:text="在吐槽看不懂之前，先问：当代艺术需要被公众理解吗"/>

        <FrameLayout
            android:id="@+id/story_frame_iv"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:visibility="visible"
            tools:visibility="visible">

            <ImageView
                android:id="@+id/story_iv"
                android:layout_width="80dp"
                android:layout_height="80dp"
                android:scaleType="centerCrop"
                android:background="#0099FF"/>

            <ImageView
                android:id="@+id/multi_pic_iv"
                android:layout_width="40dp"
                android:layout_height="16dp"
                android:src="@drawable/home_pic"
                android:scaleType="centerCrop"
                android:layout_gravity="bottom|right"
                android:visibility="gone"
                />
        </FrameLayout>


    </LinearLayout>

</android.support.v7.widget.CardView>
`
我刚刚又尝试了一下，上面是我的布局文件，我刚开始把android:background="@drawable/touch_bg"这个属性放到了cardview里面不好用。后来放到了LinearLayout里面是可以用的，cardview的水波纹效果是不是只针对foreground那个属性才能用啊？？？

**Comment by AllenCoder** [comment]
是的 cardview的波纹效果针对的是 android:foreground  

API 11+:

Add android:foreground="?android:attr/selectableItemBackground" to your CardView element.

API 9+:

Add android:foreground="?selectableItemBackground" to your CardView element.
