### ISSUE TITLE
在使用多布局时，addHeader的问题

### ISSUE THREAD

**Issue by JackLiaoJH** [CymChad/BaseRecyclerViewAdapterHelper#174]
在使用多布局时,由于对于banner是经过addHeader进去的，但是没有的时候,我需要隐藏掉，刷新有了之后，我又需要显示出来，BaseMultiItemQuickAdapter似乎使用这个时无效？

**Comment by JackLiaoJH** [comment]
`public class MultipleItemUseActivity extends Activity implements SwipeRefreshLayout.OnRefreshListener {
    private RecyclerView mRecyclerView;
    SwipeRefreshLayout mSwipeRefreshLayout;

    View mHeadView;
    MultipleItemQuickAdapter mMultipleItemQuickAdapter;

    boolean mIsAddHead;

    Handler mHandler = new Handler();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_multiple_item_use);
        mRecyclerView = (RecyclerView) findViewById(R.id.rv_list);
        mSwipeRefreshLayout = (SwipeRefreshLayout) findViewById(R.id.swipeLayout);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mMultipleItemQuickAdapter = new MultipleItemQuickAdapter(this, DataServer.getMultipleItemData());
        mRecyclerView.setAdapter(mMultipleItemQuickAdapter);

        mHeadView = LayoutInflater.from(this).inflate(R.layout.head_view, null);
//        mMultipleItemQuickAdapter.addHeaderView(mHeadView,0);
        mSwipeRefreshLayout.setOnRefreshListener(this);
    }

    @Override
    public void onRefresh() {
        mHandler.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (mIsAddHead) {
                    mMultipleItemQuickAdapter.removeHeaderView(mHeadView);
                } else {
                    mMultipleItemQuickAdapter.addHeaderView(mHeadView,0);
                }
                mSwipeRefreshLayout.setRefreshing(false);
                mIsAddHead = !mIsAddHead;
            }
        },2000);

    }
}`

**Comment by CymChad** [comment]
收到，我看看

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.5' 已解决
