### ISSUE TITLE
RecyclerView设置成GridView  隐藏子条目

### ISSUE THREAD

**Issue by chenkexu** [CymChad/BaseRecyclerViewAdapterHelper#1740]
RecyclerView设置成GridView  隐藏某个子条目，字条目可以隐藏，但是还占据空间大小。
![image](https://user-images.githubusercontent.com/14785825/32817355-1ef6e982-c9f8-11e7-821e-fede6763c49c.png)

**Comment by CymChad** [comment]
隐藏会占位，你可以rm这个item就不占位了。

**Comment by chenkexu** [comment]
@CymChad rm是什么

**Comment by chenkexu** [comment]
@CymChad 是rn  RecyclerView吗？

**Comment by chenkexu** [comment]
remove

**Comment by CymChad** [comment]
是的  删除

**Comment by CymChad** [comment]
是adapter的原始方法
