### ISSUE TITLE
设置了BaseQuickAdapter的EmptyView后，可以再删除EmptyView吗

### ISSUE THREAD

**Issue by zgnckzn** [CymChad/BaseRecyclerViewAdapterHelper#1741]
有办法将设置的EmptyView动态去掉吗？是否有提供类似方法

**Comment by 1109993488** [comment]
@zgnckzn 你还需要吗？

**Comment by zgnckzn** [comment]
@1109993488 我通过做了一个假的EmptyView实现了动态去除EmptyView的效果。如果有更好的方式，麻烦教教我，多谢

**Comment by 1109993488** [comment]
你这样是RV列表为空，还不想显示空布局？那直接隐藏RV不就可以了？如果非要把空布局移除就需要增加新功能
