### ISSUE TITLE
hi, i hava a question.

### ISSUE THREAD

**Issue by YanxuLi** [CymChad/BaseRecyclerViewAdapterHelper#1743]
你好，我是用了RxGalleryFinal，但是在添加了新的照片后，list中的数据已经改变，我也调用了setNewData方法，不过列表没有刷新，只有滑动列表后，新的数据才会刷新出来，请问有什么解决的办法么？

                     list.remove("add");

                     image_list = imageMultipleResultEvent.getResult();

                        for (int i = 0; i < image_list.size(); i++) {

                            camera_number++;

                            list.add(image_list.get(i).getOriginalPath());

                        }

                        if (list.size() < 9) {

                            list.add("add");

                        }

                        image_list.clear();

                        Logger.e(list.toString());

                        adapter.setNewData(list);

                        adapter.notifyDataSetChanged();

**Comment by CymChad** [comment]
没用过 RxGalleryFinal，setNewData是包含了刷新和清空数据的代码的，只要列表内容改变只需要用setNewData就可以了，你可以看看demo。建议你可以换别的图片加载框架试试。

**Comment by YanxuLi** [comment]
RxGalleryFinal是一个照片选择和拍照的框架，我发现只从相册中选择没有问题，不过在第一次拍照之后，再拍照或者从相册选择，就会出现不滑动就不刷新的问题。

**Comment by YanxuLi** [comment]
![82b4a3f8d02f3f8d9c252d60b136db53_20171115154157](https://user-images.githubusercontent.com/17410522/32824550-62560e5a-ca1c-11e7-8306-5455f46a44b1.gif)

**Comment by YanxuLi** [comment]
![82b4a3f8d02f3f8d9c252d60b136db53_20171115154348](https://user-images.githubusercontent.com/17410522/32824642-aa8923d8-ca1c-11e7-8391-4502d7393e3c.gif)
拍完照就开始有问题

**Comment by 1109993488** [comment]
是不是选择图片有问题，确定拿的图片的路径是对的、？

**Comment by YanxuLi** [comment]
如果是路径有问题的话，稍微滑动后也不会显示，但是我的情况是轻微滑动后显示了

**Comment by CymChad** [comment]
如果使用原生的adapter效果是如何？
