### ISSUE TITLE
item点击子控件点击事件控制其他子控件显隐，导致响应重复

### ISSUE THREAD

**Issue by GodJiong** [CymChad/BaseRecyclerViewAdapterHelper#1746]
View view = recycleview.getLayoutManager().findViewByPosition(position);
view再去获取对应控件实现监听。分页加载用这个方法会导致每页的position都会自动响应点击事件

**Comment by GodJiong** [comment]
progressAdapter.setOnItemChildClickListener((adapter, view, position) -> {
            View item = rvProgress.getLayoutManager().findViewByPosition(position);
            TextView detail = (TextView) item.findViewById(R.id.tv_detail_item);
            LinearLayout linearLayout = (LinearLayout) item.findViewById(R.id.ll_update);

            switch (view.getId()) {
                case R.id.tv_detail_item:
                    detail.setVisibility(View.GONE);
                    linearLayout.setVisibility(View.VISIBLE);
                    break;
                case R.id.tv_toUpdate_item:
                    ActivityUtils.startActivity(this, MerManageActivity.class, true);
                    break;
                case R.id.iv_show_item:
                    detail.setVisibility(View.VISIBLE);
                    linearLayout.setVisibility(View.GONE);
                    break;
            }
        });

**Comment by AllenCoder** [comment]
子控件 点击的绑定不能这么绑定，因为adapter复用的，会导致重复绑定。
子控件只要在itemView 里面可以直接在convert方法里面 绑定 

```
 @Override
    protected void convert(BaseViewHolder viewHolder, Status item) {
        viewHolder.setText(R.id.tweetName, item.getUserName())
                .setText(R.id.tweetText, item.getText())
                .setText(R.id.tweetDate, item.getCreatedAt())
                .setVisible(R.id.tweetRT, item.isRetweet())
                .addOnClickListener(R.id.tweetAvatar)
                .addOnClickListener(R.id.tweetName)
                .linkify(R.id.tweetText);
       
    }
```
