### ISSUE TITLE
树形布局导致手机卡死

### ISSUE THREAD

**Issue by me-LittleDemo** [CymChad/BaseRecyclerViewAdapterHelper#1747]
使用树形布局，滑动非常不流畅，并且会使手机卡死（测试手机锤子M1，页面中只有一个RecyclerView，没有其他布局，所做的工作就是从从网络获取到数据展示在页面上，也没有其他复杂操作），卡死之后手机无法再进行其他任何操作，只能强制重启。我有看过内存使用情况，没有内存溢出的现象。
Android 版本6.0.1 smartisan os 3.7.7
谢谢你们的开源，希望尽快修复bug

**Comment by CymChad** [comment]
你的数据有多大？我也是锤子手机，坚果。demo上没有发现卡顿现象。
