### ISSUE TITLE
同时使用了headView和multitem和pulltorefresh在上拉加载更多，获取到数据加入adapter时报错

### ISSUE THREAD

**Issue by xubo5200** [CymChad/BaseRecyclerViewAdapterHelper#1749]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.tjx.tingdao, PID: 29825
                  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{17db288 position=11 id=-1, oldPos=-1, pLpos:-1 no parent} android.support.v7.widget.RecyclerView{7e02046 VFED..... ........ 0,0-1080,1420 #7f09006d app:id/first_item_rv_list}, adapter:com.tjx.tingdao.mvp.ui.adapter.HomeMultipleItemQuickAdapter@674207, layout:android.support.v7.widget.LinearLayoutManager@a7f6f34, context:com.tjx.tingdao.mvp.ui.activity.HomeActivity@a19d175
                      at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5421)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5603)
                      at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                      at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                      at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                      at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                      at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                      at android.os.Handler.handleCallback(Handler.java:761)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6577)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by xubo5200** [comment]
这是我的adapter
package com.tjx.tingdao.mvp.ui.adapter;

import android.content.Context;
import android.widget.ImageView;
import android.widget.TextView;

import com.chad.library.adapter.base.BaseMultiItemQuickAdapter;
import com.chad.library.adapter.base.BaseQuickAdapter;
import com.jess.arms.di.component.AppComponent;
import com.jess.arms.http.imageloader.ImageLoader;
import com.jess.arms.http.imageloader.glide.ImageConfigImpl;
import com.jess.arms.utils.ArmsUtils;
import com.tjx.tingdao.R;
import com.tjx.tingdao.mvp.model.api.Api;
import com.tjx.tingdao.mvp.model.entity.TabFirstItem;
import com.tjx.tingdao.mvp.model.entity.TabFirstItem.DataBean.BeanItem;
import com.tjx.tingdao.mvp.ui.activity.HomeActivity;
import com.tjx.tingdao.mvp.ui.holder.AutoBaseViewHolder;
import com.tjx.tingdao.mvp.ui.widget.GalleryRecyclerView;

import java.util.ArrayList;
import java.util.List;

/**
 * @author xubo
 */
public class HomeMultipleItemQuickAdapter extends BaseMultiItemQuickAdapter<TabFirstItem.DataBean.BeanItem, AutoBaseViewHolder> {
    private GalleryRecyclerView rvList;
    private BaseQuickAdapter rvAdatper;
    private List<TabFirstItem.DataBean.BeanItem> datas;
    private List<String> imgs = new ArrayList<>();
    private ImageLoader mImageLoader;
    private AppComponent mAppComponent;
    private final Context context;

    public HomeMultipleItemQuickAdapter(Context context, List<TabFirstItem.DataBean.BeanItem> data) {
        super(data);
        this.context = context;
        this.datas = data;
        this.mAppComponent = ArmsUtils.obtainAppComponentFromContext(context);
        this.mImageLoader = mAppComponent.imageLoader();
        this.addItemType(TabFirstItem.LABEL, R.layout.first_tab_item_label);
        this.addItemType(TabFirstItem.ITEM, R.layout.first_tab_item_item);
        this.addItemType(TabFirstItem.HOT, R.layout.first_tab_item_hot);
    }

    @Override
    public void convert(AutoBaseViewHolder helper, BeanItem item) {
        switch (helper.getItemViewType()) {
            case TabFirstItem.LABEL:
                TextView labelMore = helper.getView(R.id.label_more);
                TextView labelName = helper.getView(R.id.label_name);
                labelMore.setOnClickListener(view ->
                        ((HomeActivity) context).showMessage("功能正在开发中")
                );
                labelName.setText(item.getName());
                break;
            case TabFirstItem.HOT:
                if (rvList == null) {
                    rvList = helper.getView(R.id.hot_rv_list);
                    rvList.setCanAlpha(true);
                    rvList.setCanScale(true);
                    rvList.setBaseScale(0.4f);
                    rvList.setBaseAlpha(0.95f);
                    rvAdatper = new BaseQuickAdapter<TabFirstItem.DataBean.HotItem, AutoBaseViewHolder>(R.layout.hot_item, item.getHotItems()) {
                        @Override
                        protected void convert(AutoBaseViewHolder helper, TabFirstItem.DataBean.HotItem item) {
                            ImageView img = helper.getView(R.id.hot_iv);
                            mImageLoader.loadImage(context,
                                    ImageConfigImpl
                                            .builder()
                                            .url(Api.IMG_URL + item.getImg())
                                            .imageView(img)
                                            .build());
                        }
                    };
                    rvList.setAdapter(rvAdatper);
                }
                rvAdatper.notifyDataSetChanged();
                break;
            case TabFirstItem.ITEM:
                helper.setText(R.id.label_title, item.getTitle());
                helper.setText(R.id.label_content, item.getDescription());
                mImageLoader.loadImage(context,
                        ImageConfigImpl
                                .builder()
                                .url(Api.IMG_URL + item.getImg())
                                .imageView(helper.getView(R.id.label_icon))
                                .build());
//                    helper.setText(R.id.label_session, item.getCourse());
                break;
            default:
                break;
        }
    }


}

**Comment by xubo5200** [comment]
我使用demo中的multiitemadapter也同样报错
package com.chad.baserecyclerviewadapterhelper;

import android.os.Bundle;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;

import com.chad.baserecyclerviewadapterhelper.adapter.MultipleItemQuickAdapter;
import com.chad.baserecyclerviewadapterhelper.base.BaseActivity;
import com.chad.baserecyclerviewadapterhelper.data.DataServer;
import com.chad.baserecyclerviewadapterhelper.entity.MultipleItem;
import com.chad.library.adapter.base.BaseQuickAdapter;

import java.util.List;

/**
 * https://github.com/CymChad/BaseRecyclerViewAdapterHelper
 * modify by AllenCoder
 */
public class MultipleItemUseActivity extends BaseActivity {
    private RecyclerView mRecyclerView;
    private MultipleItemQuickAdapter multipleItemAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_multiple_item_use);
        setTitle("MultipleItem Use");
        setBackBtn();
        mRecyclerView = (RecyclerView) findViewById(R.id.rv_list);
        final List<MultipleItem> data = DataServer.getMultipleItemData();
        multipleItemAdapter = new MultipleItemQuickAdapter(this, data);
        final GridLayoutManager manager = new GridLayoutManager(this, 4);
        mRecyclerView.setLayoutManager(manager);
        multipleItemAdapter.setSpanSizeLookup(new BaseQuickAdapter.SpanSizeLookup() {
            @Override
            public int getSpanSize(GridLayoutManager gridLayoutManager, int position) {
                return data.get(position).getSpanSize();
            }
        });
        mRecyclerView.setAdapter(multipleItemAdapter);
        View headerView = getHeaderView(0, new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                multipleItemAdapter.addHeaderView(getHeaderView(1, getRemoveHeaderListener()), 0);
            }
        });
        multipleItemAdapter.addHeaderView(headerView);
        multipleItemAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                final List<MultipleItem> data = DataServer.getMultipleItemData();
                multipleItemAdapter.addData(data);
            }
        });
    }
    private View getHeaderView(int type, View.OnClickListener listener) {
        View view = getLayoutInflater().inflate(R.layout.head_view, (ViewGroup) mRecyclerView.getParent(), false);
        if (type == 1) {
            ImageView imageView = (ImageView) view.findViewById(R.id.iv);
            imageView.setImageResource(R.mipmap.rm_icon);
        }
        view.setOnClickListener(listener);
        return view;
    }
    private View.OnClickListener getRemoveHeaderListener() {
        return new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                multipleItemAdapter.removeHeaderView(v);
            }
        };
    }
}




下面是错误
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.chad.baserecyclerviewadapterhelper, PID: 32193
                  java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling android.support.v7.widget.RecyclerView{f697166 VFED..... .F...... 0,0-1080,1680 #7f080097 app:id/rv_list}, adapter:com.chad.baserecyclerviewadapterhelper.adapter.MultipleItemQuickAdapter@b568ca7, layout:android.support.v7.widget.GridLayoutManager@2def554, context:com.chad.baserecyclerviewadapterhelper.MultipleItemUseActivity@9f6e4f5
                      at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2663)
                      at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5074)
                      at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:11564)
                      at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6905)
                      at com.chad.library.adapter.base.BaseQuickAdapter.addData(BaseQuickAdapter.java:560)
                      at com.chad.baserecyclerviewadapterhelper.MultipleItemUseActivity$3.onLoadMoreRequested(MultipleItemUseActivity.java:55)
                      at com.chad.library.adapter.base.BaseQuickAdapter.autoLoadMore(BaseQuickAdapter.java:1455)
                      at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:922)
                      at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
                      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                      at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                      at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                      at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                      at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                      at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                      at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                      at android.os.Handler.handleCallback(Handler.java:761)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6577)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by 1109993488** [comment]
TabFirstItem.HOT 这种类型的item不是一个吧？你不应该判断rvList == null,你应该
```
RecyclerView rvList = helper.getView(R.id.hot_rv_list);
        BaseQuickAdapter rvAdatper = rvList.getAdapter();
        if (rvAdatper == null) {
            rvList.setCanAlpha(true);
            rvList.setCanScale(true);
            rvList.setBaseScale(0.4f);
            rvList.setBaseAlpha(0.95f);
            rvAdatper = new BaseQuickAdapter<TabFirstItem.DataBean.HotItem, AutoBaseViewHolder>(R.layout.hot_item, null) {
                @Override
                protected void convert(AutoBaseViewHolder helper, TabFirstItem.DataBean.HotItem item) {
                    ImageView img = helper.getView(R.id.hot_iv);
                    mImageLoader.loadImage(context,
                            ImageConfigImpl
                                    .builder()
                                    .url(Api.IMG_URL + item.getImg())
                                    .imageView(img)
                                    .build());
                }
            };
            rvList.setAdapter(rvAdatper);
        }
        rvAdatper.setNewData(item.getHotItems());
```

第二个问题是你应该在onLoadMoreRequested方法里不能直接notifyData，需要放到post里

**Comment by xubo5200** [comment]
@1109993488 TabFirstItem.HOT 这个是recyclerview1中 嵌套了（仅有的）一个横向的recyclervie2,所以我没有每次都去初使化RV,不过我第一个错误，跟这里没有关系，我按照你的写法改了，也还是报错

**Comment by 1109993488** [comment]
那你添加数据是怎么添加的

**Comment by xubo5200** [comment]
@1109993488 
`if (pullToRefresh) {
                            mRootView.updateBanner(tabFirstItem.getData().getAd1());
                            TabFirstItem.DataBean.BeanItem label = new TabFirstItem.DataBean.BeanItem();
                            label.setItemType(TabFirstItem.LABEL);
                            label.setName(tabFirstItem.getData().getTuijian1().get(0).getName());
                            mBeanItems.add(label);
                            for (TabFirstItem.DataBean.BeanItem beanItem : tabFirstItem.getData().getTuijian1()) {
                                beanItem.setItemType(TabFirstItem.ITEM);
                                mBeanItems.add(beanItem);
                            }
                            List<TabFirstItem.DataBean.HotItem> hotItems = new ArrayList<>();
                            for (TabFirstItem.DataBean.BeanItem beanItem : tabFirstItem.getData().getAd1()) {
                                hotItems.add(new TabFirstItem.DataBean.HotItem(beanItem.getId(), beanItem.getImg()));
                            }
                            TabFirstItem.DataBean.BeanItem hot = new TabFirstItem.DataBean.BeanItem();
                            hot.setItemType(TabFirstItem.HOT);
                            hot.setHotItems(hotItems);
                            mBeanItems.add(hot);

                            for (TabFirstItem.DataBean.BeanItem beanItem : tabFirstItem.getData().getTuijian2()) {
                                beanItem.setItemType(TabFirstItem.ITEM);
                                mBeanItems.add(beanItem);
                            }
//                            mAdapter.notifyDataSetChanged();
                            mAdapter.setNewData(mBeanItems);
                        } else {
                            for (TabFirstItem.DataBean.BeanItem beanItem : tabFirstItem.getData().getTuijian2()) {
                                beanItem.setItemType(TabFirstItem.ITEM);
                            }
                            mAdapter.addData(tabFirstItem.getData().getTuijian2());
//                            mAdapter.notifyDataSetChanged();
                            if(tabFirstItem.getData().getTuijian2().size()<5){
                                mAdapter.loadMoreEnd();
                            }else{
                                try {
                                    mAdapter.loadMoreComplete();
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }
//                            mAdapter.notifyItemRangeInserted(preEndIndex, tabFirstItem.getData().getTuijian2().size());
                        }`

**Comment by 1109993488** [comment]
addData会自动notifyItemRangeInserted，入股你也写了notifyItemRangeInserted就会异常，但是看你上面的代码有notifyDataSetChanged，就不会产生异常;
暂时没看出什么问题，建议给个demo可以快速找问题

**Comment by 1109993488** [comment]
你可以参考下demo加载更多
