### ISSUE TITLE
能结合SmartRefreshLayout的上拉加载？

### ISSUE THREAD

**Issue by zhongyuanwu** [CymChad/BaseRecyclerViewAdapterHelper#1752]
结合SmartRefreshLayout的上拉加载 必须要先设置BaseRecyclerViewAdapterHelper的上拉监听，否则没有效果，就想要上拉加载的时候有个越界回弹效果 ，好像BaseRecyclerViewAdapterHelper没有，

**Comment by CymChad** [comment]
SmartRefreshLayout的上拉和BaseRecyclerViewAdapterHelper是没有关联的。BaseRecyclerViewAdapterHelper的上拉原理是通过adapter检查滑动到item的position来做的，而SmartRefreshLayout是嵌套布局通过监听rv滑动做的。所以各不影响。
