### ISSUE TITLE
setLayoutManager 设置成GridLayoutManager后

### ISSUE THREAD

**Issue by yzjsbsb** [CymChad/BaseRecyclerViewAdapterHelper#1753]
setLayoutManager 设置成GridLayoutManager后，怎么在最后增加一个footview，
我调用mQuickAdapter.addFooterView(footerView);是在下一行增加的footview，而不是在item后面继续添加footview

**Comment by zhanzijian** [comment]
兄弟  你这个问题解决了么   可否告知   我也遇到同样问题 @yzjsbsb
