### ISSUE TITLE
SwipeMenuRecyclerView 添加setEmptyView出错

### ISSUE THREAD

**Issue by zhaoyouzhi** [CymChad/BaseRecyclerViewAdapterHelper#1755]
mAdapter.setEmptyView(R.layout.view_recycler_empty, (ViewGroup) mSmRecyclerView.getParent());
使用SwipeMenuRecyclerView 会出现把emptyView当成Item，会走onClick和侧滑事件

**Comment by zhaoyouzhi** [comment]
![image](https://user-images.githubusercontent.com/17698787/33053892-0b35fa6a-ceb1-11e7-9f84-bc82608de9ae.png)

**Comment by CymChad** [comment]
emptyView本质上就是一个item
