### ISSUE TITLE
在使用BaseSectionQuickAdapter这个Adapte不能隐藏Section的头

### ISSUE THREAD

**Issue by Troll4it** [CymChad/BaseRecyclerViewAdapterHelper#1756]
![6_r1y r7q wz d ne2ki9d](https://user-images.githubusercontent.com/27883219/33065546-20b73fc4-cee4-11e7-9619-815b14a8c2a0.png)
这是这个框架的demo我加了把Section的头部Gone,但是还是把空间留出来，同时使用helper.setGone(R.id.card_view,true);这个无效的

**Comment by CymChad** [comment]
控件是肯定会留的，因为你是一个item的存在，如果要隐藏可以直接rm这个item
