### ISSUE TITLE
Not showing load more in realm adapter

### ISSUE THREAD

**Issue by ranjitzade** [CymChad/BaseRecyclerViewAdapterHelper#1757]
I've extended realm adapters with BaseQuickAdapter, its not showing the load more custom view anymore now.
used [this](https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java) realm adapter
Any suggestions of what to do?

**Comment by 1109993488** [comment]
check getItemCount
