### ISSUE TITLE
ScrollView 嵌套RecyclerView中加载了全部的页数

### ISSUE THREAD

**Issue by weitto** [CymChad/BaseRecyclerViewAdapterHelper#1758]
ScrollView中上半部分是webView（占一个屏幕）,下半部是RecyclerView，recyclverView中有分页数据。我一进入界面就回调了加载更多事件，加载一页后，又加载下一页，直到全部加载完成，可是我都没滑动到底部。adapter中用得是databinding绑定数据的。哪里出问题了呢

**Comment by 1109993488** [comment]
不能和ScrollView嵌套使用，可以把webView放到header中

**Comment by weitto** [comment]
放入header中体验不太好，滑动会出现卡顿的情况。 有没有手动监听滑动到底部的方法呢？或者到底部显示“加载更多”，点击后才加载下一页数据...

**Comment by CymChad** [comment]
监听到底部只能通过rv来做。adapter无法监听。建议更换第三方的上拉库。
