### ISSUE TITLE
多布局实现出现问题

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#1762]
多布局实使用TabLayout+ViewPager,滑动页面怎么让TabLayout悬浮置顶

**Comment by CymChad** [comment]
这个和adapter无关

**Comment by douya40** [comment]
多布局更新MulEntity.ITEM_VIEW3，更新其中一个布局的数据怎么实现呢

**Comment by CymChad** [comment]
更新数据刷新adapter就好了。

**Comment by douya40** [comment]
adapter是整个刷新呀，我要局部更新的

**Comment by CymChad** [comment]
http://www.jianshu.com/p/a92955be0a3e  局部更新原生的也有提供方法的。
