### ISSUE TITLE
上拉加载更多时,获取到数据后,在添加数据的时候,加载动画停止了

### ISSUE THREAD

**Issue by MahatmaSun** [CymChad/BaseRecyclerViewAdapterHelper#1763]
上拉刷新后,获取到数据,调用adapter.addData方法 ,然后调用adapter.loadMoreComplete();
加载效果是,请求接口过程中,正在加载前面的圆圈一直在转.当数据返回后.按照上述方法添加数据时,会卡住1秒左右.圆圈不转了.卡在那不动.不知道怎么解决这个问题.能让数据加载的更流畅一些,不要看着卡在那了.谢谢

**Comment by MahatmaSun** [comment]
我又试了一下 不是动画停止, 而是确实是卡住了.
SwipeRefreshLayout 下拉刷新也会卡主.

**Comment by 1109993488** [comment]
请确认你请求数据没有耗时操作

**Comment by MahatmaSun** [comment]
我在adapter.setOnLoadMoreListener监听里使用okhttp异步请求了接口.在访问成功后做了基本处理. 如截图 并没有耗时操作
![image](https://user-images.githubusercontent.com/20633789/33247352-648416d2-d358-11e7-871a-093778b91cb2.png)

**Comment by MahatmaSun** [comment]
adapter里的代码也很简单. 就是几个textview赋值. 每次刷新展示10条数据.
![image](https://user-images.githubusercontent.com/20633789/33247428-0fc5d97c-d359-11e7-9841-5eb7d2f550cd.png)

**Comment by MahatmaSun** [comment]
@1109993488 麻烦帮忙看看 谢谢

**Comment by MahatmaSun** [comment]
是gson解析json时的耗时操作影响的? 可是肯定是需要解析数据的啊

**Comment by MahatmaSun** [comment]
我又进一步跟进了一下. 下拉刷新用的SwipeRefreshLayout.在刷新结束后.解析json为list. 并没有卡顿. 然后加上adapter.setNewData(data);就卡了. 不知道怎么回事. 我当时模拟分页的时候写了10条假数据 并没有卡.

**Comment by CymChad** [comment]
有gif吗？

**Comment by CymChad** [comment]
我想看下效果

**Comment by MahatmaSun** [comment]
@CymChad 不太会录制gif. 我去找找录制方法 然后录好了发上来. 谢谢   还有就是官网上的qq群(558178792)真的搜索不到 前段时间就反映过.  是群不在了. 还是禁止被搜索了  还是别的情况. 能否提供一个群. 这样遇到问题,大家也可以讨论讨论. 谢谢

**Comment by MahatmaSun** [comment]
@CymChad    gif链接    https://s9.aconvert.com/convert/p3r68-cdx67/kmptb-d0dmp.gif

**Comment by 1109993488** [comment]
你可以自己用handler postDelay，造个假数据加载试试，

**Comment by MahatmaSun** [comment]
@1109993488 如果不加载布局. 随便放一个String类型的list的话.  这样是不卡的.  可能是这个手机配置不高.华为P9的卡顿就不是很明显.

**Comment by CymChad** [comment]
你可以自定义上拉布局试试看

**Comment by MahatmaSun** [comment]
SwipeRefreshLayout 下拉刷新时也会卡一下, 把adapter.setNewData(data);注释了 就不卡了.自定义上拉布局结果应该也是一样的吧.
这个问题,影响不是很大,配置高点的手机,卡顿时间短,等有时间再处理.
但是我就好奇个事儿.为啥每次提到群 都避而不答呢.  我已经在不同的Issue问过至少3次了.  官网写的群(558178792) 搜索不到. 是群不在了. 还是禁止被搜索了 还是别的情况. 能否提供一个群. 这样遇到问题,大家也可以讨论讨论. 谢谢

**Comment by CymChad** [comment]
![image](https://user-images.githubusercontent.com/7698209/33643273-037f7fb6-da79-11e7-8685-bf614579082c.png)
群号就是558178792  你用电脑查找一下看看

**Comment by MahatmaSun** [comment]
@CymChad  我真的是找了好多次了 都没有 我让四个同事用他们的电脑搜索 也没有. 不知道为什么. 手机搜了也不行 按名称查找也不行/(ㄒoㄒ)/~~ 
![image](https://user-images.githubusercontent.com/20633789/33647143-56536904-da8e-11e7-8f18-cf763197b4c2.png)
![image](https://user-images.githubusercontent.com/20633789/33647151-5f6b621c-da8e-11e7-9b42-d1516d76e9b4.png)
![image](https://user-images.githubusercontent.com/20633789/33647138-51bb0f8c-da8e-11e7-804a-97810d8ae7f2.png)

**Comment by CymChad** [comment]
要不这样你加我qq我拉你入群  54050520  问题答案是 陈宇明

**Comment by MahatmaSun** [comment]
@CymChad 谢谢了. 昨天在一个微信群里 正好有人在你的群里面. 他把群分享给我  我加入进去了 谢谢!
