### ISSUE TITLE
recyclerview 嵌套recyclerview 

### ISSUE THREAD

**Issue by awpss** [CymChad/BaseRecyclerViewAdapterHelper#1765]
版本:2.8.7
外层recyclerview嵌套recyclerview,内层recyclerview中每个item中有多个editext（可能不满一屏），点击editext弹出键盘时,软键盘挡住内容,列表无法移动,已尝试设置清单属性,均无效，请大佬帮忙看下 适配器是否需要设置什么

**Comment by AllenCoder** [comment]
1. 参考解决办法 [http://www.jianshu.com/p/2f36c4886226](http://www.jianshu.com/p/2f36c4886226)
2. 列表无法移动多半是Touch事件被拦截消费掉，没有分发给外层的reyclerview用于滚动事件的处理
3. 可以在最外层的reyclerview [实现ItemTouch事件，自己处理滚动的事件，参照[(https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/library/src/main/java/com/chad/library/adapter/base/listener/SimpleClickListener.java)](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/library/src/main/java/com/chad/library/adapter/base/listener/SimpleClickListener.java)
