### ISSUE TITLE
下拉刷新会界面闪烁问题

### ISSUE THREAD

**Issue by 751496032** [CymChad/BaseRecyclerViewAdapterHelper#1767]
下拉刷新会界面闪烁，怎么处理，把动画关了也会，谢谢！

**Comment by CymChad** [comment]
版本号？原生的adapter不会？

**Comment by CymChad** [comment]
下拉刷新你用了什么方法？

**Comment by AllenCoder** [comment]
参考解决办法 如下:
1. [https://medium.com/@hanru.yeh/recyclerviews-views-are-blinking-when-notifydatasetchanged-c7b76d5149a2](https://medium.com/@hanru.yeh/recyclerviews-views-are-blinking-when-notifydatasetchanged-c7b76d5149a2)
2. [http://www.voidcn.com/article/p-pbyrwyxk-bcx.html](http://www.voidcn.com/article/p-pbyrwyxk-bcx.html)

**Comment by 751496032** [comment]
把.setDuration(0)就不会了
