### ISSUE TITLE
Can't see level 1 view after expand

### ISSUE THREAD

**Issue by kim24** [CymChad/BaseRecyclerViewAdapterHelper#1769]
Hi,
I followed every instruction about creating expandable items but the problem is that the code is executed there is no error at all but items of recyclerview are not expanded.
I checked logs it says that : "item expanded" but I don't see any change in the application.
Should I have some special attribute in xml file?!

**Comment by vishnyakov-aleks** [comment]
Have the same problem, resolved this by disable animation
try this
  ```
 expand(position, false, true);
   collapse(position, false, true);
```

**Comment by vishnyakov-aleks** [comment]
please, why are you closed it? with animation bugs occurred =(

**Comment by CymChad** [comment]
Is there a demo or GIF?

**Comment by vishnyakov-aleks** [comment]
![- 1](https://user-images.githubusercontent.com/17671328/33367105-72738096-d4fe-11e7-95d0-0293826c4866.gif)

**Comment by elfman** [comment]
please attach the relevant code and your android version
