### ISSUE TITLE
如果我要从网络获取数据,Adapter的构造器怎么写?

### ISSUE THREAD

**Issue by jesse920524** [CymChad/BaseRecyclerViewAdapterHelper#177]
demo中的代码是这样的:
 public QuickAdapter() {
        super( R.layout.tweet, DataServer.getSampleData(100));
    }

    public QuickAdapter(int dataSize) {
        super( R.layout.tweet, DataServer.getSampleData(dataSize));
    }

可是我要从网络获取数据,也就是说DataServer.getSampleData()的形参需要volley回调的List<Json>,而这个List在adapter是access不到的.
请教我该怎么写,才能从网络获取到数据,呈现到RecyclerView上.

**Comment by CymChad** [comment]
setNewData（）
