### ISSUE TITLE
LinearLayoutManager.HORIZONTAL，设置headerView，头部显示，列表不显示

### ISSUE THREAD

**Issue by yxyaxng** [CymChad/BaseRecyclerViewAdapterHelper#1770]
LinearLayoutManager.VERTICAL 显示正常，
![image](https://user-images.githubusercontent.com/24906252/33247124-9e5267c6-d356-11e7-9326-4d038d3af655.png)

**Comment by CymChad** [comment]
你在横向布局的时候添加headerView的方法选择添加一个方向属性即可。
