### ISSUE TITLE
高频率刷新，滑动卡顿

### ISSUE THREAD

**Issue by HappyImp** [CymChad/BaseRecyclerViewAdapterHelper#1771]
我这里得list几秒刷新一次，刷新是进行全部刷新的，在刷新过程中，我滑动列表是会卡顿的

**Comment by AllenCoder** [comment]
1. 全量高速刷新，代价是非常昂贵的（非常不建议）
2. 我在之前的项目中遇到和处理的解决办法是：使用官方的DiffUtil 作为刷新的工具类增量刷新需要刷新的部分
3. 自定义一个数据模型，通过Rxjava的filter 过滤出变动的数据集，通过变动数据集对应的model的postion去刷新对应的Ui 的item视图

**Comment by HappyImp** [comment]
@AllenCoder 我这里不单是item刷新，连item的顺序都是变化的，可以说基本都刷新了。。

**Comment by AllenCoder** [comment]
全量高速刷新 每次都涉及到recyclerview控件的高度计算，重新布局，渲染，绘制，所以，边高速刷新边滑动是必然会卡顿的，要不就是滑动过程中禁止刷新，刷新完成之后，再重新渲染布局，这个跟本身的适配器优化关系不大
