### ISSUE TITLE
下拉加载无限执行

### ISSUE THREAD

**Issue by jeesezh** [CymChad/BaseRecyclerViewAdapterHelper#1774]
版本号：2.9.34
layout：
![image](https://user-images.githubusercontent.com/19542480/33301829-05fed92c-d433-11e7-8c92-f031f0675b0f.png)

code：
![image](https://user-images.githubusercontent.com/19542480/33301845-1a0928f0-d433-11e7-8230-ca228bc30434.png)

![image](https://user-images.githubusercontent.com/19542480/33301834-0d604b1a-d433-11e7-8fed-1786c181bd22.png)
![image](https://user-images.githubusercontent.com/19542480/33301858-296b190c-d433-11e7-8bfc-3f12316ae731.png)

**Comment by kona5362** [comment]
我也遇到了这个问题

**Comment by kona5362** [comment]
我的好像是头布局引起的

**Comment by meijius** [comment]
我的也是，咋解决呢。

**Comment by meijius** [comment]
![tim 20171128180838](https://user-images.githubusercontent.com/21004705/33314017-55688358-d467-11e7-907b-af19e0b5d872.png)
无限加载更多

**Comment by CymChad** [comment]
有嵌套sv吗？

**Comment by tysheng** [comment]
你好, 我没有看到你"关闭"的代码, 也就是 setFetchEnable(false), so, 你自己应该能解决.

**Comment by caiguangzhao** [comment]
我嵌套了sv，然后就一直调用下拉加载了，怎么办？

**Comment by CymChad** [comment]
@caiguangzhao 嵌套有机制冲突，要么你取出嵌套把嵌套部分放在头部或者尾部，要么换其他第三方来做上拉
