### ISSUE TITLE
继承baseviewholder并有header时

### ISSUE THREAD

**Issue by renshaodong** [CymChad/BaseRecyclerViewAdapterHelper#1775]
这个header也会用成这个自己的viewholder，然后这个viewholder里是headerView.findview就会成空，虽然不会报错，但是一堆异常，强迫症有点难受

**Comment by AllenCoder** [comment]
headerview 不会走convert方法，对于headerview的控件id绑定，都是在setHeaderView之前绑定的，不需要再去convert方法里面绑定headerview的内部childview的id

**Comment by renshaodong** [comment]
额 我没说明白，不是convert里的，是这个new BaseViewHolder(headerView)在自定义ViewHolder时，headerView它也会执行行viewHolder构造里的findView，但其实并没用到，
