### ISSUE TITLE
数据较少的情况下,(一页能显示下),数据出来后会自动执行一次加载更多的动画.

### ISSUE THREAD

**Issue by MahatmaSun** [CymChad/BaseRecyclerViewAdapterHelper#1776]
数据较少的情况下,(一页能显示下),请求接口后,列表显示出来数据后,会自动执行一次上拉加载更多的动画,一闪即逝,(就是"正在加载中..."那个动画).不知道怎么能去掉.
如果数据一页显示不下的话,没有这个问题.不会自动加载.
我在onLoadMoreRequested中判断了 数据条数小于10条执行adapter.setEnableLoadMore(false);

**Comment by MahatmaSun** [comment]
我打debug跟了一下. 数据不足一页的时候 会自动进行一次上拉加载更多.   代码会走到onLoadMoreRequested监听里. 这个怎么能设置不让他加载.

**Comment by meijius** [comment]
无限加载更多，你的不会哈？

**Comment by MahatmaSun** [comment]
@meijius 我的不会无限加载更多. 我又仔细阅读了一遍作者的使用指南. 然后在第一次获取到数据, 调用adapter.setNewdata方法后 又调用了一遍adapter.disableLoadMoreIfNotFullPage(mRecycler);方法.
解决了我说的那个问题. 
作者有提供屏蔽第一次自动加载更多的方法. 
这个问题解决了.是我没仔细阅读文档.
文档里没具体说调用的位置,但是在demo里有对disableLoadMoreIfNotFullPage方法的说明.
![image](https://user-images.githubusercontent.com/20633789/33315614-25446638-d46c-11e7-82ec-2c1d8b32ab3f.png)

**Comment by meijius** [comment]
我使用了，可是还是会无限加载更多。要不就报错。

**Comment by meijius** [comment]
@MahatmaSun  代码能看下不。

**Comment by meijius** [comment]
setEnableLoadMore
setNewData
setOnLoadMoreListener
disableLoadMoreIfNotFullPage 
@MahatmaSun 
怎么排下来的，我哪个顺序都换了，还是无限加载更多。

**Comment by meijius** [comment]
@MahatmaSun  一进界面就自动加载更多 一直无限加的去 知道没有了
![tim 20171128191400](https://user-images.githubusercontent.com/21004705/33316846-5481650a-d470-11e7-899b-6bbfd9d1390b.png)

**Comment by MahatmaSun** [comment]
@meijius 
1.是不是你这个集合的问题啊.  你尝试一下 不要用成员变量里那个itemList  就是addData的时候用新的list.   然后你可以把数据再添加到itemList里.
2. 监听写在初始化的时候就行. 你这是写到加载第一次数据之后了?不知道这个有影响没.   
3.还有就是在监听里最好判断一下itemList的条目数. 如果小于一页要显示的条数. 就禁用加载更多.

**Comment by meijius** [comment]
怎么写都是无限加载更多，要不就不出现加载更多。 @MahatmaSun

**Comment by MahatmaSun** [comment]
@meijius  要不你出个demo 正好我需求刚做完 有点时间  我给你改一下. 肯定不会怎么写都无线加载更多的.

**Comment by meijius** [comment]
@MahatmaSun 稍等，加下QQ757221145

**Comment by CymChad** [comment]
@meijius 你提的issues 我回复你了。你是因为嵌套机制导致的。
