### ISSUE TITLE
关于checkbox：convert里做了if..else..处理，但是滑动后仍然会消失

### ISSUE THREAD

**Issue by JiangShuLiang** [CymChad/BaseRecyclerViewAdapterHelper#1778]
如下图，看了文档了，做了if..else的处理：
![image](https://user-images.githubusercontent.com/20485764/33367397-6c724c24-d529-11e7-89c6-8507a933866d.png)

但是往下滑动后再返回就会发现之前【选中】的checkbox会变成【没选中】

**Comment by CymChad** [comment]
你点击的时候对数据源进行的改变拉吗？
