### ISSUE TITLE
recyclerview快速滑动时.禁止加载更多失效.

### ISSUE THREAD

**Issue by MahatmaSun** [CymChad/BaseRecyclerViewAdapterHelper#1779]
正常情况下,第一次加载数据后,在itme数量不足一页的情况下,禁止加载更多.
现在出现的问题是
缓慢滑动recyclerview是正常的.但是如果快速滑动 也就是fly的时候.到达最后一条以后.会走回调,现象就是加载更多动画一闪即逝. 之后无论怎么fly都不会出现这种情况了. 只有第一次加载数据后有这个现象.
如果有解决方法烦请告知.如果没有的话,对我的项目也没什么太大的影响.作为优化建议,提供给作者 . 
谢谢!

**Comment by MahatmaSun** [comment]
补充一下 如果正常速度滑动到底部后.  再fly 也不会出现上述情况. 只有第一次加载数据后,快速fly.才会出现上述情况.

**Comment by CymChad** [comment]
收到，感谢你的建议，由于第一次要监测rv的数据，所以采用了延迟测量。一开始获取是无法获取到想要的数据的。所以目前暂时没有很好的解决办法，除非先调用关闭上拉方法然后第一次加载完成之后再开启上拉监听。

**Comment by CymChad** [comment]
收藏建议 #1688
