### ISSUE TITLE
v7包依赖方式

### ISSUE THREAD

**Issue by weinierfei** [CymChad/BaseRecyclerViewAdapterHelper#178]
嗨,陈总好!library中的compile 'com.android.support:recyclerview-v7:23.3.0'能变成provided不,因为项目中如果用了其他版本的support,就会报冲突

**Comment by CymChad** [comment]
可以

**Comment by weinierfei** [comment]
下个版本中应该能变过来哈,谢谢回复

**Comment by CymChad** [comment]
恩 ，可以的。

**Comment by weinierfei** [comment]
新版本中没修改,是不是忘了?

**Comment by CymChad** [comment]
还真忘了，是在不好意思，我这就改一下，几分钟。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.8'
