### ISSUE TITLE
树形结构为啥一定要List<MultiItemEntity>去add进去

### ISSUE THREAD

**Issue by zdxiang** [CymChad/BaseRecyclerViewAdapterHelper#1787]
List《MultiItemEntity》 res = new ArrayList<>();
                    for (int i = 0; i < level1.size(); i++) {
                        ContentList contentList = level1.get(i);
                        contentList.setSubItems(contentList.getList());
                    }
                    res.addAll(level1);
只是两级树形结构，
    public static final int TYPE_LEVEL_0 = 0;
    public static final int TYPE_LEVEL_1 = 1;
如果不用 List《MultiItemEntity》的话，holder.getItemViewType()都是返回0.

**Comment by CymChad** [comment]
因为需要重写getItemViewType返回type。
