### ISSUE TITLE
切换GridLayoutManager

### ISSUE THREAD

**Issue by ly469097645** [CymChad/BaseRecyclerViewAdapterHelper#1788]
使用setLayoutManager，切换LinearLayoutManager和GridLayoutManager的时候，在LinearLayoutManager设置好头布局的情况下切换至GridLayoutManager会出现头布局变成GridLayoutManager的第一条数据而不是头布局了，这种情况有什么比较好的解决方法吗，请大神指导下
![1111](https://user-images.githubusercontent.com/12133597/33534820-e886d262-d8e4-11e7-8da3-cbe6bf1b629c.png)
![222](https://user-images.githubusercontent.com/12133597/33534821-e9c73392-d8e4-11e7-9ec3-7e72a688c73f.png)

**Comment by Troll4it** [comment]
看下你这两个方法的顺序 :应该是先设置.setLayoutManager()，后设置setAdapter()

**Comment by CymChad** [comment]
经过测试setLayoutManager之后会有你说的问题，但是按照 @Troll4it 说的做就是没问题的了

**Comment by ly469097645** [comment]
第一次是没问题，就是app中有一个切换listview和gridview的功能，每次切换都执行了.setLayoutManager()来切换LinearLayoutManager和GridLayoutManager，这样每次切换都要重新setAdapter()吗

**Comment by CymChad** [comment]
嗯 是的，如果不setAdapter不会走对head的处理操作。

**Comment by RiceRichhonour** [comment]
你好，请问，切换LinearLayoutManager和GridLayoutManager的时候，布局并不相同，如何设置布局呢。
