### ISSUE TITLE
onLoadMoreRequested问题

### ISSUE THREAD

**Issue by jesse920524** [CymChad/BaseRecyclerViewAdapterHelper#179]
请问,我写的上滑加载更多为什么不能执行,以下是代码:

  /**加载更多监听*/
    @Override
    public void onLoadMoreRequested() {

        recyclerView.post(new Runnable() {
            @Override
            public void run() {
                Log.d("FirstActivity", "onLoadMoreRequested executed");
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        //请求更多数据方法getArticleMore();
                        adapter.notifyDataChangedAfterLoadMore(myList2, true);
                    }
                }, DELAYED_MILLIS);

            }
        });
    }

====================================================================================================================================
我在demo中把RecyclerView数据长度写死就能成功回调onLoadMoreRequested(),但网络请求却无法调用,求助!

**Comment by CymChad** [comment]
你的pagesize是？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/131  你可以参考下这里面的问题
