### ISSUE TITLE
shoppingcartRvlevel0item.getSubItems()返回的数据集有问题

### ISSUE THREAD

**Issue by 18300072348** [CymChad/BaseRecyclerViewAdapterHelper#1793]
返回的并不是当前组的子数据集而是当前最后可见的item的子数据集

**Comment by 18300072348** [comment]
从源码来看，    
public void addSubItem(int position, T subItem) {
        if (mSubItems != null && position >= 0 && position < mSubItems.size()) {
            mSubItems.add(position, subItem);
        } else {
            addSubItem(subItem);
        }
    }
    public void addSubItem(T subItem) {
        if (mSubItems == null) {
            mSubItems = new ArrayList<>();
        }
        mSubItems.add(subItem);
    }
    @Override
    public List<T> getSubItems() {
        return mSubItems;
    }
所有的子数据并不是分别添加到不同的集合里，而是一个集合里，返回的也是这个集合，这样根本找不到最初添加的是那些数据了

**Comment by 18300072348** [comment]
忘了说了我这是二级树形列表加载不同组布局，一种子布局有子项一种没有，没有的那种组布局需要从上一个有子布局的组里获取所有子项的数据显示

**Comment by 18300072348** [comment]
@Override
    public void setSubItems(List<ShoppingcartRvlevel1item> list) {
        mlist = list;
    }

    @Override
    public List<ShoppingcartRvlevel1item> getSubItems() {
        return mlist;
    }

    @Override
    public void addSubItem(ShoppingcartRvlevel1item subItem) {
        if(mlist==null){
            mlist=new ArrayList<>();
        }
        mlist.add(subItem);
    }
在子项的实体类里重写这几个方法可解决返回数据集问题，但总是会出现第一屏时第一个不可见的item数据错乱，且数据经常变，只有这一个是错的，这应该不是缓存问题，因为已经处理了数据在设置的。还有另外一个问题：看图吧
![meizu-m2 note-2017-12-05-11-51-33](https://user-images.githubusercontent.com/18573453/33589381-1cdcc688-d9b3-11e7-91f8-9dcbc379cb46.jpg)
折叠几次之后数据才会全部出来

**Comment by CymChad** [comment]
版本号？

**Comment by 18300072348** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.34'

**Comment by elfman** [comment]
@18300072348 `AbstractExpandableItem`本来就只会返回可见的item，你要获取新添加的元素的话应该自己添加一些方法来保存状态。

你后面说的那些问题不太看得懂，但感觉更像是你的代码问题
