### ISSUE TITLE
disableLoadMoreIfNotFullPage();设置后就不能再上拉加再啦

### ISSUE THREAD

**Issue by 2665867688** [CymChad/BaseRecyclerViewAdapterHelper#1794]
disableLoadMoreIfNotFullPage();设置后 好像是请求超过一定时间就不能上啦加载啦，但是不设置 第一次进入的时候又会回调 上拉加载的方法，handler.sendEmptyMessageDelayed(0, 3000);我设置请求三秒，然后上拉到底部的时候就不能上拉加载拉

**Comment by baakonn** [comment]
源码注释：
 这个方法是用来检查是否满一屏的，所以只推荐在 {@link #setNewData(List)} 之后使用
     * 原理很简单，先关闭 load more，检查完了再决定是否开启


最终只是控制setEnableLoadMore（true/false） 感觉不应该这样
