### ISSUE TITLE
发现了一个奇怪的bug

### ISSUE THREAD

**Issue by 2665867688** [CymChad/BaseRecyclerViewAdapterHelper#1795]
第一种情况:当disableLoadMoreIfNotFullPage设置后，第一次请求数据时超过一定时间 比如三秒，并且数据条数铺满全屏时，再次上拉加载 就不执行上拉加载的回调方法，而且也不显示上拉加载的底部，

第二种情况：当数据没有铺满全屏时，比如只有三条数据，当不设置disableLoadMoreIfNotFullPage第一次进入时会加载数据 显示上拉加载的底部并回调上拉监听方法，如果第一次进入时需求是请求数据并显示SwipeRefreshLayout的加载progressbar,而不是上拉底部的话需要设置disableLoadMoreIfNotFullPage，但设置了以后如果数据铺满屏幕又会发生第一种情况。

下面是我的代码 我分别改变了 一次 获取的条数 和请求时间进行的测试
package com.yue.rl;

import android.os.Handler;
import android.os.Message;
import android.support.annotation.Nullable;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.DividerItemDecoration;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.widget.ImageView;
import android.widget.Toast;

import com.bumptech.glide.Glide;
import com.chad.library.adapter.base.BaseQuickAdapter;
import com.chad.library.adapter.base.BaseViewHolder;
import com.scwang.smartrefresh.header.MaterialHeader;
import com.scwang.smartrefresh.layout.SmartRefreshLayout;
import com.scwang.smartrefresh.layout.listener.OnLoadmoreListener;
import com.yue.rl.contants.Contants;

import java.util.LinkedList;
import java.util.List;

public class Test02Activity extends AppCompatActivity implements BaseQuickAdapter.RequestLoadMoreListener, SwipeRefreshLayout.OnRefreshListener {
    private RecyclerView recyclerView;

    private Test02Activity.CheckAdapter checkAdapter;
    private List<String> list;
    private boolean isRefresh = true;

    private SwipeRefreshLayout refresh;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test02);
        initView();
    }

    private void initView(){
        recyclerView = findViewById(R.id.recycler_test02);
        refresh = findViewById(R.id.swiperefresh);

        recyclerView.addItemDecoration(new DividerItemDecoration(this, DividerItemDecoration.VERTICAL));
        LinearLayoutManager manager = new LinearLayoutManager(this);
        list = new LinkedList<>();
        checkAdapter = new Test02Activity.CheckAdapter(list);
        recyclerView.setLayoutManager(manager);
        recyclerView.setAdapter(checkAdapter);

        checkAdapter.setOnLoadMoreListener(this, recyclerView);
        checkAdapter.disableLoadMoreIfNotFullPage();
        refresh.setOnRefreshListener(this);
        refresh.setRefreshing(true);
        handler.sendEmptyMessageDelayed(0,3000);
    }

    @Override
    public void onLoadMoreRequested() {
        Toast.makeText(this, "加载数据", Toast.LENGTH_SHORT).show();
        isRefresh = false;
        handler.sendEmptyMessageDelayed(1,3000);
    }

    @Override
    public void onRefresh() {
        isRefresh = true;
        handler.sendEmptyMessageDelayed(0,3000);
    }

    class CheckAdapter extends BaseQuickAdapter<String, BaseViewHolder> {

        public CheckAdapter(@Nullable List<String> data) {
            super(R.layout.item_test01, data);
        }

        @Override
        protected void convert(BaseViewHolder helper, String item) {
            ImageView imageView = helper.getView(R.id.item_image);
            Glide.with(imageView.getContext())
                    .load(item)
                    .into(imageView)
            ;
        }
    }

    private void getData() {
        if (isRefresh){
            refresh.setRefreshing(false);
        }

        if (list.size() > 30) {
            checkAdapter.loadMoreEnd(false);
            return;
        }
        for (int i = 0; i < 10; i++) {

            list.add(Contants.imgs[i]);
        }
        checkAdapter.notifyDataSetChanged();
    }
    Handler handler = new Handler() {
        @Override
        public void handleMessage(Message msg) {
            switch (msg.what) {
                case 0:
                    getData();
                    break;
                case 1:
                    Toast.makeText(Test02Activity.this, "加载完成", Toast.LENGTH_SHORT).show();
                    getData();
                    break;
            }

        }
    };
}

**Comment by baakonn** [comment]
我也遇到了，测试的时候，不满一屏，会自定出发loadmore，disableLoadMoreIfNotFullPage 单纯的吧loarmore（true/false），不太好，不满一屏我也想加载更多啊（测试时，每次加载一条）
