### ISSUE TITLE
Item got cropped

### ISSUE THREAD

**Issue by Skullper** [CymChad/BaseRecyclerViewAdapterHelper#1799]
I'm using Expandable Item. My layout is ConstraintLayout with wrap_content height. Result:
https://drive.google.com/open?id=1J4mkwwGIHVXeXRzh8UJTSbeRHP4WL0lN

How can I fix that?

**Comment by CymChad** [comment]
android:minHeight="?actionBarSize

**Comment by Skullper** [comment]
@CymChad I have investigated this problem and found out that it was a problem with constraint layout

**Comment by CymChad** [comment]
Thank you for your investigation
