### ISSUE TITLE
disableLoadMoreIfNotFullPage的建议

### ISSUE THREAD

**Issue by 2665867688** [CymChad/BaseRecyclerViewAdapterHelper#1800]
如果有一个专门的禁止已进入就自动加载更多的方法就好了，disableLoadMoreIfNotFullPage并不怎末好使

**Comment by CymChad** [comment]
建议可以在加载更多的里面通过判断数据的size来关闭加载。

**Comment by 2665867688** [comment]
@Override
            public void onSuccess(String result) {
                Logger.d("CollectActivity", result);
                HashMap map = gson().fromJson(result, HashMap.class);
                if (isRefresh == true) {//刷新
                    mRefresh.setRefreshing(false);
                    List<PoiMerge02> list = gson().fromJson(gson().toJson(map.get("rows")), new TypeToken<ArrayList<PoiMerge02>>() {
                    }.getType());
                    mList.clear();
                    mList.addAll(list);
                    mAdapter.loadMoreComplete();
                } else {
                    List<PoiMerge02> list = gson().fromJson(gson().toJson(map.get("rows")), new TypeToken<ArrayList<PoiMerge02>>() {
                    }.getType());
                    if (list.size() != 0) {
                        mList.addAll(list);
                        mAdapter.notifyDataSetChanged();
                        mAdapter.loadMoreComplete();
                    } else {
                        mAdapter.loadMoreEnd(false);
                        return;
                    }
                }
                mAdapter.disableLoadMoreIfNotFullPage();
                Logger.d("ToiletAllCommentActivity", result);
                L.e(result);

            }
我在请求完  mAdapter.disableLoadMoreIfNotFullPage();这样就完美解决啦
