### ISSUE TITLE
上啦加载

### ISSUE THREAD

**Issue by SoulEaterVTT** [CymChad/BaseRecyclerViewAdapterHelper#1802]
只要把上啦加载的事件写上，默认就会加载更多一次，这不符合逻辑啊

**Comment by 1109993488** [comment]
你可以在第一次设置数据后判断是否有更多数据，没有可以关闭，就不会回调加载更多

**Comment by SparkChenZ** [comment]
这样不合理，这种情况是发生在item接近满屏的时候

**Comment by SparkChenZ** [comment]
看了源码，因为是通过适配器来实现的新数据的加载，一旦出现请求数据接近满屏item数量而不满屏的情况，就算修改了状态，停止了底部view的加载状态，那么加载机制也停止了，不会再重新启动加载回调。

**Comment by CymChad** [comment]
一开始无法得知一夜有多少条，所以默认加载了会进入一次回调，这个时候可以按照 @1109993488 的做法来处理。
