### ISSUE TITLE
我这里需要 根据重力感应去让recyclerview的每个item跟着屏幕方向旋转 

### ISSUE THREAD

**Issue by to686312** [CymChad/BaseRecyclerViewAdapterHelper#1803]
我在重力感应的监听里 通过adapter的getitemcout  for循环获取item布局 通过getViewByPosition  获取到这个布局给他设置旋转动画   在item可见的条目 动画旋转 是正常的  但是不可见的item 发现item并没有跟其他的item一样旋转  只有在他显示的时候才跟着旋转

**Comment by to686312** [comment]
为了让每个item  跟着重力感应 旋转  这个能支持 吗

**Comment by CymChad** [comment]
这个和adapter无关。
