### ISSUE TITLE
addHeaderView内包含webview，webview会定位到顶部

### ISSUE THREAD

**Issue by jiaok** [CymChad/BaseRecyclerViewAdapterHelper#1804]
addHeaderView布局上面是TextView下面是webview，加载完成后webview会跳动到顶部把上面的布局顶上去了，请问是什么原因？

**Comment by 1109993488** [comment]
#1357 #1516

**Comment by jiaok** [comment]
可以了，要把webview设置android:focusable="false"
        android:focusableInTouchMode="false"
