### ISSUE TITLE
CheckBox设置全局的疑问

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#1805]
checkBoxAll.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                if (isChecked) {
                   
                } else {
                    
                }
                adapter.notifyDataSetChanged();
            }
        });
我想问下，当我在activity层操作checkbox的时候怎么去改变整个mode里的判断值，好实现全选状态呢？
顺便提个小小的建议哈，关于CheckBox的问题好像也挺多的，建议作者在Demo里写个例子，好让我们可以直接去参考例子，嘻嘻

**Comment by CymChad** [comment]
全选你只要改变数据源就好了。把每一个mode的是否被选中的属性值改变就好了。你看下相关博客就明白了，http://blog.csdn.net/guohaosir/article/details/72403724
