### ISSUE TITLE
BaseSectionQuickAdapter 加载更多时，界面没有向下移动

### ISSUE THREAD

**Issue by Jessiqi** [CymChad/BaseRecyclerViewAdapterHelper#1807]
在BaseSectionQuickAdapter使用加载更多，加载数据完成后，当前页界面会向下移动，如果界面有分隔线 ，分隔线会错乱的闪一下，该如何解决？

**Comment by 1109993488** [comment]
#1689 这样描述问题，我们都不知什么问题，更不知怎么解决
