### ISSUE TITLE
可否禁用loadmoreview？

### ISSUE THREAD

**Issue by DanteAndroid** [CymChad/BaseRecyclerViewAdapterHelper#1809]
我使用loadmore功能，但是用SwipeRefresh来代替加载时的UI，所以想禁用loadmoreview。设为空会崩溃。

**Comment by 1109993488** [comment]
禁用还想用？用哪些功能？你可以试试footerView

**Comment by CymChad** [comment]
你是意思是第一次不想显示loadmoreview？你可以设置 setEnableLoadMore

**Comment by DanteAndroid** [comment]
什么第一次，我说的很明确了啊，使用loadmore功能但是不使用loadmoreview。即，列表拉到最下方会触发loadmore，但是不会显示任何loadmoreview（我自己会处理）

**Comment by 1109993488** [comment]
继承LoadMoreView，自定义加载中、加载失败、没有更多高度为0，你看看是不是要这种

**Comment by DanteAndroid** [comment]
@1109993488 听起来是这样。希望能提供官方的接口方便地禁用loadmoreview。。如果觉得这需求很少见或者不合理，也可无视。谢谢！

**Comment by CymChad** [comment]
可以考虑 #1688

**Comment by 1109993488** [comment]
@DanteAndroid 如果加载失败高度也是0的话那就没法再回调加载更多，现在加载失败的时候只有点击加载失败布局才能回调加载更多

**Comment by DanteAndroid** [comment]
@1109993488 嗯，
- 方案1：往上滑动再往下滑触发loadmore
- 方案2：给BRVAH添加一个`loadmore()`的方法（配合`disableLoadMoreView()`用）

**Comment by 1109993488** [comment]
用户不知道往上滑再往下滑会触发ladMore，我觉得你这样还不如自己监听RV滑动到底部自己处理
