### ISSUE TITLE
When I include the library an old RecyclerView draws wrong

### ISSUE THREAD

**Issue by cazador4** [CymChad/BaseRecyclerViewAdapterHelper#181]
Before include:
http://imgur.com/j3y3DnJ
After include:
http://imgur.com/xoKAjKE

I've only included in the build.gradle 
`compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.3'`

Do you know why the height of items in my old recyclerview are drawing bad ?

Do you override some class ?

**Comment by CymChad** [comment]
Should be your XML layout height problem，You can try
```xml
android:layout_height="wrap_content"
```

**Comment by CymChad** [comment]
loading layout code 
```java
mLayoutInflater.inflate(layoutResId, parent, false);
```
