### ISSUE TITLE
setOnClickListener  为什么Deprecated了 ？

### ISSUE THREAD

**Issue by pdog18** [CymChad/BaseRecyclerViewAdapterHelper#1812]
现在应该用哪个来给指定控件设置点击事件？

**Comment by lgwguang** [comment]
你说的给指定控件设置点击事件helper.getView(viewId).setOnClickListener()，不知道是不是这个

**Comment by CymChad** [comment]
你可以看下文档 http://www.jianshu.com/p/b343fcff51b0
