### ISSUE TITLE
adapter继承BaseQuickAdapter,viewholder继承BaseViewHolderHelper，会报转换异常

### ISSUE THREAD

**Issue by yxyaxng** [CymChad/BaseRecyclerViewAdapterHelper#1814]
![image](https://user-images.githubusercontent.com/24906252/33865974-207df146-df2f-11e7-92e7-563a32c9c7ba.png)

**Comment by CymChad** [comment]
版本

**Comment by yxyaxng** [comment]
@CymChad 2.9.33
