### ISSUE TITLE
关于adapter.notifyItemChanged(0);的必现Crash

### ISSUE THREAD

**Issue by MirkoWu** [CymChad/BaseRecyclerViewAdapterHelper#1816]
@ChadCym **发现了一个必现Crash,具体情况如下：**
新建一个adapter，
addHeaderView(）.只添加一个header(多个的没测，应该也有问题).
footer加不加都行,随便加数据，个数不限.
调用 adapter.notifyItemChanged(0); 时crash。
只是position==0会crash，其他的不会。
调用adapter.notifyDataSetChanged();时不会crash。

可以参考 demo里的 **HeaderAndFooterUseActivity** ，
点击事件里改成这样，点击第一个非header  item应该就可以复现。

> headerAndFooterAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
>             @Override
>             public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
>                 adapter.notifyItemChanged(position);
>             }
>         });
>

**Comment by CymChad** [comment]
版本是？

**Comment by MirkoWu** [comment]
2.9.34

**Comment by 1109993488** [comment]
header、footer位置不能notifyItemChanged
