### ISSUE TITLE
在适配器控制行布局子控件显隐藏，有问题

### ISSUE THREAD

**Issue by zhanhon** [CymChad/BaseRecyclerViewAdapterHelper#1817]
`//适配器
class StringAdapter extends BaseQuickAdapter<String,BaseViewHolder>{
        public StringAdapter(@Nullable List<String> data) {
            super(R.layout.layout_item, data);
        }
        @Override
        protected void convert(BaseViewHolder helper, String item) {
            final int position = helper.getLayoutPosition();
            TextView text = helper.getView(R.id.textView);
            text.setText(item);
            helper.addOnClickListener(R.id.textView);
            if (position > 0 && position % 6 == 0) {
                helper.setVisible(R.id.id_image, true);
            } else {
                helper.setVisible(R.id.id_image, false);
            }
        }
    }`
item 布局
![item](https://user-images.githubusercontent.com/18360628/33917898-ad7b7124-dfeb-11e7-835b-9f101013f917.png)

库版本：2.9.34
问题描述：item根布局是LinearLayout，达到条件隐藏的控件所在位置有空白；
要的预期效果应该是没有空白。

**Comment by CymChad** [comment]
Change the method setVisible --> setGone
The new method setVisible

setVisible:Set a view visibility to VISIBLE (true) or INVISIBLE (false).
setGone: Set a view visibility to VISIBLE (true) or GONE (false).

**Comment by zhanhon** [comment]
好的，谢谢。我粗心大意了
