### ISSUE TITLE
在使用BaseSectionQuickAdapter，addItemDecoration没有作用

### ISSUE THREAD

**Issue by scrat000** [CymChad/BaseRecyclerViewAdapterHelper#182]
代码如下：
`
 LinearLayoutManager linearLayoutManager=new LinearLayoutManager(this);
linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
musicplayRecyclerview.setLayoutManager(linearLayoutManager);
 musicplayRecyclerview.addItemDecoration(new RecycleViewDivider(
                this, LinearLayoutManager.VERTICAL
                , ScreenUtils.dpToPxInt(this, 10)
                , getResources().getColor(R.color.black)));
musicplayRecycler

view.setAdapter(adapter);
`
列表中并没有显示分割线

**Comment by CymChad** [comment]
此没有改变Decoration的源码。其他adapter有？
