### ISSUE TITLE
当时用分组模式时

### ISSUE THREAD

**Issue by EdwinShadow** [CymChad/BaseRecyclerViewAdapterHelper#1824]
使用分组模式时 recyclerView在setLayoutManage时应该用StaggeredGridLayoutManager，头部布局和分组的布局才会分开展示用GridLayoutManager不会分开。。。

**Comment by CymChad** [comment]
你的版本号是？

**Comment by EdwinShadow** [comment]
2.4.7 是因为没有更新最新版本吗？

**Comment by EdwinShadow** [comment]
更新最新版本后解决了。。。感谢老大
