### ISSUE TITLE
用适配器mAdapter.setNewData(dataList);后，第一次item会闪一下

### ISSUE THREAD

**Issue by qianzhihe86** [CymChad/BaseRecyclerViewAdapterHelper#1826]
加载数据后，item数据变化，对集合数据重新修改，然后放到集合后，用适配器mAdapter.setNewData(dataList);后，第一次item会闪一下。请问怎么解决？
代码：
//第一次初始化时，该dataList的size=0
 mAdapter=new CarRecyclerViewAdapter(R.layout.car_fragment_layout_item, dataList);
        recyclerView.setAdapter(mAdapter);

//获取数据后，操作item时。设置item上的状态刷新
   private void setItemIsAllSelected(boolean isAllSelected){
        if (dataList.size()<=0){
            ToastUtil.showToastMessage(mActivity,"暂无可选项！");
            return;
        }
        for (int i=0; i<dataList.size(); i++){
            CarItemBean carItemBean=dataList.get(i);
            carItemBean.isSelected=isAllSelected;
            dataList.remove(i);
            dataList.add(i, carItemBean);
        }
        mAdapter.setNewData(dataList);
    }

**Comment by qianzhihe86** [comment]
适配器里面item加载图片的：
 Glide.with(mContext)
                .load(url)
                .asBitmap()
                .thumbnail(0.3f)//设置缩略图支持
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .error(R.mipmap.ic_launcher)
                .into(imageView);

**Comment by qianzhihe86** [comment]
已经看了源码
使用这种方式notifyItemChanged(int position, Object payload)局部组件刷新无效

**Comment by qianzhihe86** [comment]
源码里面没有重写public void onBindViewHolder(final RecyclerView.ViewHolder holder, final int position,List payloads) 这个方法，没有做对应的操作。

**Comment by CymChad** [comment]
嗯，是的没有支持diff

**Comment by qianzhihe86** [comment]
那闪屏的话，请问怎么处理呢？

**Comment by CymChad** [comment]
图片闪屏？你可以试试这个 http://www.jianshu.com/p/654dac931667

**Comment by qianzhihe86** [comment]
是的，这个方法试过了。
加了一下代码：((SimpleItemAnimator)recyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
结果找不到SimpleItemAnimator类

**Comment by CymChad** [comment]
recyclerView.getItemAnimator().setChangeDuration(0)；  这个也不行吗？

**Comment by qianzhihe86** [comment]
是的，不管用

**Comment by qianzhihe86** [comment]
然后本来想用public void onBindViewHolder(final RecyclerView.ViewHolder holder, final int position,List payloads) 这个方法来处理的，结果发现框架源码里面没重写该方法，也没做进一步的处理过

**Comment by CymChad** [comment]
ok，了解了。明天我找找解决方案。

**Comment by Pyuming** [comment]
((DefaultItemAnimator) mRecyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
使用这个试一下。

**Comment by CymChad** [comment]
@qianzhihe86 使用 @Pyuming 的方法可以吗？

**Comment by qianzhihe86** [comment]
稍等，我试试呢

**Comment by qianzhihe86** [comment]
这个闪屏的问题无法处理么？

**Comment by AllenCoder** [comment]
加载数据后，item数据变化，对集合数据重新修改，然后放到集合后，应该只是修改了数据，而没有修改数据源的指向地址，（list没有被重新指向一个新的对象）此时不需要调用 setNewData()，只需要简单调用 
adapter.notifyDataSetChanged();

**Comment by CymChad** [comment]
这个闪屏并不是adapter的问题，我们只能提供可能解决的方案。
