### ISSUE TITLE
OnItemDragListener

### ISSUE THREAD

**Issue by justdoITlkq** [CymChad/BaseRecyclerViewAdapterHelper#1827]
陈大佬，您好。
我现在使用2.9.34的版本，我下载使用到 BaseItemDraggableAdapter的拖拽功能，我在大多数情况下，在onItemDragEnd()时会用到到的起始和结束位置用来保存更改后的位置，但是在OnItemDragListener的接口中的三个方法中只有onItemDragMoving()回调会提供from和end，如果moving时保存会保存多次。

**Comment by CymChad** [comment]
有点没懂，问题是？
