### ISSUE TITLE
多条目布局传入不同的entity，点击获取position问题

### ISSUE THREAD

**Issue by DCZLQR** [CymChad/BaseRecyclerViewAdapterHelper#1828]
首先版本是2.9.30，
下面我是添加数据的方法
`private ArrayList<BluetoothGroup> generateData() {
        List<String> groupName = getInstance().selectAllGroupName();
        final ArrayList<BluetoothGroup> list = new ArrayList<>();
        for (int i = 0; i < groupName.size(); i++) {
            final BluetoothGroup group = new BluetoothGroup();
            group.setGroupName(groupName.get(i));

            List<Long> mLong = BluetoothGroupHelper.getInstance().selectBluetoothByGroupNmae(groupName.get(i));
            for (Long l : mLong) {
                Bluetooth b;
                b = BluetoothHelper.getInstance().selectSingleByKey(l);
                group.addSubItem(b);
            }
            list.add(group);
        }
        return list;
    }`

其实就是把b   addSubItem 到group，然后list再add  group，和demo里面的不同，下面是demo添加数据的方法：
`private void initAdapter() {
        List<ClickEntity> data = new ArrayList<>();
        data.add(new ClickEntity(ClickEntity.CLICK_ITEM_VIEW));
        data.add(new ClickEntity(ClickEntity.CLICK_ITEM_CHILD_VIEW));
        data.add(new ClickEntity(ClickEntity.LONG_CLICK_ITEM_VIEW));
        data.add(new ClickEntity(ClickEntity.LONG_CLICK_ITEM_CHILD_VIEW));
        data.add(new ClickEntity(ClickEntity.NEST_CLICK_ITEM_CHILD_VIEW));
        adapter = new ItemClickAdapter(data);
        adapter.openLoadAnimation();
        mRecyclerView.setAdapter(adapter);
    }`
[不同的是demo是添加同一个entity,我是两个不同的，再看看实际效果
![test](https://user-images.githubusercontent.com/32856687/33940317-73569d1c-e049-11e7-8050-7dd21b4eff1a.jpg)

点击第二处画红线的地方，打印 item4，有没有办法获取的是item1

**Comment by DCZLQR** [comment]
忘了说，我的点击事件是写在fragment里面的，点击的是整个item的layout

**Comment by CymChad** [comment]
它的原理就是把子级和父级当作一级来看，具体要着相关数据，可以看demo的代码，写个监听传入

**Comment by DCZLQR** [comment]
已经搞定了，谢谢
