### ISSUE TITLE
onBindViewHolder 不执行问题

### ISSUE THREAD

**Issue by HpWens** [CymChad/BaseRecyclerViewAdapterHelper#183]
想问下  recyclerview 中 我来回滑动 onBindViewHolder 不执行问题 

`07-25 09:58:39.154 12347-12347/com.example.recyclerdemo E/---------------: ************5
07-25 09:58:39.314 12347-12347/com.example.recyclerdemo E/---------------: ************7
07-25 09:58:39.414 12347-12347/com.example.recyclerdemo E/---------------: ************8`

这里很明显 第6 没有执行  

`    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        Log.e("---------------","************"+position);`

我数据源集合大小为7

**Comment by CymChad** [comment]
我的项目应该没有暴露onBindViewHolder吧
