### ISSUE TITLE
快速删除

### ISSUE THREAD

**Issue by guyunke123** [CymChad/BaseRecyclerViewAdapterHelper#1830]
你好，用BaseQuickAdapter中快速点击item删除，位置不准确，这个怎么处理
 mAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Log.i(TAG,"onItemClick---position"+position);
                adapter.remove(position);
            }
        });

**Comment by AllenCoder** [comment]
1. 如果添加了headerview和footview ，这个position 对应的是 数据里面的position，默认是要被减去的，所以，需要根据自己添加headviewcount，改变位置
2. 情况2 ，快速点击，是否是足够的快，导致 adapter的渲染还未真正完成，点击的item还是上一次没有被adapter移除的view ，会导致记录的位置不正确

**Comment by guyunke123** [comment]
是情况2
请教
int position = holder.getAdapterPosition();   if (position > -1) {      listener.onItemChildClick(v, position);  }
这样子改行不行


------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年12月18日(星期一) 下午5:42
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "ky"<980277440@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 快速删除 (#1830)



 
如果添加了headerview和footview ，这个position 对应的是 数据里面的position，默认是要被减去的，所以，需要根据自己添加headviewcount，改变位置
 
情况2 ，快速点击，是否是足够的快，导致 adapter的渲染还未真正完成，点击的item还是上一次没有被adapter移除的view ，会导致记录的位置不正确

**Comment by AllenCoder** [comment]
postion = -1 说明，当前的view已经在adapter里面被移除了，你的点击回调到被移除，时间上这么快吗？还是哪里出现卡顿导致的？

**Comment by guyunke123** [comment]
看lib代码是holder.holder.getLayoutPosition()，快速点击（实现点击删除item，如最开始代码）,holder.getLayoutPosition()获得到的postion位置不准确，我是把ItemDragAndSwipeUseActivity的点击事件改成remove（）试试，发现快速点击位置会少1或者2

**Comment by AllenCoder** [comment]
我这边单独测试快速点击删除 没有发现未知错乱情况。

测试代码如下：

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setBackBtn();
        setTitle("ItemClickActivity Activity");
        setContentView(R.layout.activity_item_click);
        mRecyclerView = (RecyclerView) findViewById(R.id.list);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        initAdapter();
        adapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemClick: ");
                adapter.remove(position);
                Toast.makeText(ItemClickActivity.this, "onItemClick" + position, Toast.LENGTH_SHORT).show();
            }
        });
        adapter.setOnItemLongClickListener(new BaseQuickAdapter.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemLongClick: ");

                Toast.makeText(ItemClickActivity.this, "onItemLongClick" + position, Toast.LENGTH_SHORT).show();
                return true;
            }
        });
        adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemChildClick: ");
                Toast.makeText(ItemClickActivity.this, "onItemChildClick" + position, Toast.LENGTH_SHORT).show();
            }
        });
        adapter.setOnItemChildLongClickListener(new BaseQuickAdapter.OnItemChildLongClickListener() {
            @Override
            public boolean onItemChildLongClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemChildLongClick: ");
                Toast.makeText(ItemClickActivity.this, "onItemChildLongClick" + position, Toast.LENGTH_SHORT).show();
                return true;
            }
        });
}
```

postion是通过 
```
 public final int getLayoutPosition() {
            return mPreLayoutPosition == NO_POSITION ? mPosition : mPreLayoutPosition;
        }
```
这个方法获取到的，如果他返回的位置不正确，说明要么该view已经不存在当前的布局中，你说的快速点击是否涉及到删除之后，由于布局过于复杂，布局还未完成，又点击触发了，导致记录的touch位置不正确。。

**Comment by AllenCoder** [comment]
如果无法解决，请提供必现Demo 及相关Demo的操作必现步骤 。

**Comment by guyunke123** [comment]
重现很简单，demo的ItemDragAndSwipeUseActivity 的120行，改改就行了



 指着靠屏幕下方某一项（第5或6）连点







------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2018年1月2日(星期二) 晚上6:04
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "ky"<980277440@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 快速删除 (#1830)




如果无法解决，请提供必现Demo 及相关Demo的操作必现步骤 。
