### ISSUE TITLE
setOnItemChildClickListener与addHeaderView

### ISSUE THREAD

**Issue by JustinChiang123** [CymChad/BaseRecyclerViewAdapterHelper#1833]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.34'
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30'
两个版本都是一样的。
![image](https://user-images.githubusercontent.com/4392239/33984373-5d3826f0-e0f2-11e7-8c0a-1b79353f4d3d.png)
如上图，我添加了头部，然后在ChildClickListener里面出错了。位置错乱。data直接使用postion没问题，正确，可是获取view的时候，或获取到上面一个view。当头部没有我要获取的view的id时，就直接报错了NullPointerException(view是空)。

**Comment by JustinChiang123** [comment]
也就是说我是这样操作的。
![image](https://user-images.githubusercontent.com/4392239/33984684-7b550832-e0f3-11e7-9bbb-31c39e05401f.png)

**Comment by AllenCoder** [comment]
1. 因为源码里面 关于 postion做了转换处理，传入的data数据 会正确对应点击item的位置 ，
```
    private int getClickPosition() {
        if (getLayoutPosition()>=adapter.getHeaderLayoutCount()){
            return getLayoutPosition() - adapter.getHeaderLayoutCount();
        }
        return 0;
    }


```
你用adapter.getViewByPostion 是需要把headview的个数也叠加在内的

**Comment by JustinChiang123** [comment]
got
