### ISSUE TITLE
BaseQuickAdapter  removeAllHeaderView

### ISSUE THREAD

**Issue by afinaliu** [CymChad/BaseRecyclerViewAdapterHelper#184]
public void removeAllHeaderView() {
        if (mFooterLayout == null) return;

        mHeaderLayout.removeAllViews();
        mHeaderLayout = null;
    }    请确认当前是代码

**Comment by shichaohui** [comment]
这个问题已经确认了，下个版本会修复，敬请期待。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.7'
