### ISSUE TITLE
华为meta8、小米6   添加首屏item动画无效

### ISSUE THREAD

**Issue by zhouzhuo810** [CymChad/BaseRecyclerViewAdapterHelper#1840]
已重写该方法，其他手机没问题，目前已发现这两个手机会无效，系统都是7.0+。
@Override
    protected void startAnim(Animator anim, int index) {
        super.startAnim(anim, index);
        if (index < count)
        anim.setStartDelay(index * 150);
    }
用的SlidingRight动画。

**Comment by CymChad** [comment]
没有你说的机型无法测试。我可以去着一台7.0的试试

**Comment by zhouzhuo810** [comment]
好的~

**Comment by CymChad** [comment]
抱歉并没有发现你说的问题。

**Comment by zhouzhuo810** [comment]
好吧，就是延时无效，动画还是有，是整屏一起进来的，不是一条条进来。
