### ISSUE TITLE
向右滑动删除崩溃，请大神们指导一下

### ISSUE THREAD

**Issue by cwwei2005** [CymChad/BaseRecyclerViewAdapterHelper#1841]
原谅我还没拜读源码，直接使用了。项目中想用滑动删除功能，代码如下：

---adapter---
public class QuexianAddAdapter extends BaseItemDraggableAdapter<QuexianSaveInfo, BaseViewHolder> {
    public QuexianAddAdapter(int layoutResId, @Nullable List<QuexianSaveInfo> data) {
        super(layoutResId, data);
    }

    @Override
    protected void convert(BaseViewHolder helper, QuexianSaveInfo item) {
    }
}

---activity---
mQuexianAddAdapter = new QuexianAddAdapter(R.layout.main, list);
rv.setLayoutManager(new LinearLayoutManager(this));
rv.setAdapter(mQuexianAddAdapter);

//拖曳删除
ItemDragAndSwipeCallback callback = new ItemDragAndSwipeCallback(mQuexianAddAdapter);
ItemTouchHelper helper = new ItemTouchHelper(callback);
helper.attachToRecyclerView(rv_quexian);
mQuexianAddAdapter.enableSwipeItem();//enable

mQuexianAddAdapter.setOnItemSwipeListener(new OnItemSwipeListener() {
	@Override
	public void onItemSwipeStart(RecyclerView.ViewHolder viewHolder, int pos) {
		Log.d("tag","xx");
	}

	@Override
	public void clearView(RecyclerView.ViewHolder viewHolder, int pos) {
		Log.d("tag","xx");
	}

	@Override
	public void onItemSwiped(RecyclerView.ViewHolder viewHolder, int pos) {
		Log.d("tag","xx");
	}

	@Override
	public void onItemSwipeMoving(Canvas canvas, RecyclerView.ViewHolder viewHolder, float dX, float dY, boolean isCurrentlyActive) {
		Log.d("tag","xx");
	}
});

**Comment by CymChad** [comment]
错误日志是？

**Comment by cwwei2005** [comment]
在向右滑动删除时报错：
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NoClassDefFoundError: android.support.v7.widget.helper.ItemTouchHelper$3
debug时看到只进入回调的start方法，然后就崩溃了。

**Comment by AllenCoder** [comment]
是否添加的recylerview版本号 有问题，建议升级reyclerview版本试一下，demo测试没有问题

**Comment by cwwei2005** [comment]
恩，是的，升级了v7-26.1.0，暂时没发现其它问题。谢谢！！






------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年12月29日(星期五) 下午5:20
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "wei"<494545699@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 向右滑动删除崩溃，请大神们指导一下 (#1841)




是否添加的recylerview版本号 有问题，建议升级reyclerview版本试一下，demo测试没有问题
