### ISSUE TITLE
刷新时网络图片闪烁怎么办

### ISSUE THREAD

**Issue by dujingxue1997** [CymChad/BaseRecyclerViewAdapterHelper#1842]

**Comment by CymChad** [comment]
http://www.jianshu.com/p/654dac931667

**Comment by dujingxue1997** [comment]
这个我试了，没有用。。。。。

**Comment by CymChad** [comment]
收到，我明天试试

**Comment by dujingxue1997** [comment]
嗯嗯。网上的办法我基本都试过了。比如 设置mAdapter.setHasStableIds(true);这个，还有去掉动画，我都试过了。还是闪烁。我用的是拖拽的Adapter

**Comment by Pyuming** [comment]
((DefaultItemAnimator) mRecyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
使用这个试一下。

**Comment by KomoriWu** [comment]
方法都试了木用啊

**Comment by AllenCoder** [comment]
To use stable IDs, we need to

```
setHasStableIds(true)
```
In RecyclerView.Adapter, we need to set setHasStableIds(true); true means this adapter would publish a unique value as a key for item in data set. Adapter can use the key to indicate they are the same one or not after notifying data changed.
```
override getItemId(int position)

```
Then we must override getItemId(int position), to return identified long for the item at position. We need to make sure there is no different item data with the same returned id.
