### ISSUE TITLE
BaseQuickAdapter 的构造方法只能传入视图ID？

### ISSUE THREAD

**Issue by ming0101** [CymChad/BaseRecyclerViewAdapterHelper#1843]
我用的kotlin Anko构建的视图如何使用。也就是构造方法添加传入View？

**Comment by CymChad** [comment]
目前没有针对kotlin特别处理，只有一种方式。

**Comment by AllenCoder** [comment]
参考此链接 [https://github.com/Kotlin/anko/issues/194](https://github.com/Kotlin/anko/issues/194)
