### ISSUE TITLE
侧滑菜单和拖拽换位置不能实现

### ISSUE THREAD

**Issue by BatriderD** [CymChad/BaseRecyclerViewAdapterHelper#1846]
BaseItemDraggableAdapter 实现了拖拽功能  在此基础上想增加 侧滑菜单 时候引入了 官方推荐的EasySwipeMenuLayout  可以侧滑但是拖拽功能无效了

**Comment by githubzaibao** [comment]
你好，我是EasySwipeMenuLayout的作者，EasySwipeMenuLayout在设计之初是不考虑拖拽换位置的的，因为设计时实现的机制是拦截触摸式事件，如果你想要实现改效果，或许可以根据实际需求，找到一个点来判断是否拦截EasySwipeMenuLayout的响应来进行实现
