### ISSUE TITLE
官方demo能否做成moudle  被依赖，出现了Cannot resolve type for movie

### ISSUE THREAD

**Issue by helloworkcupid** [CymChad/BaseRecyclerViewAdapterHelper#1848]
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: Found data binding errors.
****/ data binding error ****msg:Cannot resolve type for movie
file:E:\AndroidProject\MultipleHost\MultipleVirtuaStand\src\main\res\layout\item_movie.xml
loc:36:71 - 36:75
****\ data binding error ****

请问这是什么情况呢？大神们，谁有做好的moudle ？

**Comment by CymChad** [comment]
http://blog.csdn.net/u014453811/article/details/54582426 你可以看看网上的一些解决方案。这个和项目本身无关。
