### ISSUE TITLE
通知数据更新问题

### ISSUE THREAD

**Issue by litianjiaodongjie** [CymChad/BaseRecyclerViewAdapterHelper#1853]
Item  里面有Rec ，数据变了，通知item里面的Rec的adapter数据更新不起作用。。然后我又去通知外层adapter更新当前item，起作用了，但会导致整个item的数据被替换成之前操作的item数据。

**Comment by CymChad** [comment]
看下你更新Item 里面有Rec ，数据的代码。你可以试试通过adapter.getdata然后获取adapter的数据源改改，我怀疑你没有改对数据源。

**Comment by litianjiaodongjie** [comment]
好的，谢谢了，现在已经换个思路解决了:-O！@CymChad
