### ISSUE TITLE
item点击事件中如何获取具体的view

### ISSUE THREAD

**Issue by TonyJason** [CymChad/BaseRecyclerViewAdapterHelper#1854]
您好, 我想在item点击事件中或者item子控件点击事件中获取具体的某一个view，应该如何操作，我尝试如下操作，可惜报空，也尝试用view.findViewById 也是报空。求指导，谢谢!
![image](https://user-images.githubusercontent.com/15902558/34245084-5e8109d4-e663-11e7-94e5-8cf7d8dc79e3.png)

**Comment by CymChad** [comment]
getViewByPosition

**Comment by TonyJason** [comment]
@CymChad 
![image](https://user-images.githubusercontent.com/15902558/34281298-adcc3b0e-e6f8-11e7-9786-c7fc468c2bde.png)

我用onItemChildClick(BaseQuickAdapter adapter, View view, int position)里面的adapter报这个错误，用HeaderAndFooterAdapter headerAndFooterAdapter的adapter.getViewByPosition也报这个错误。

**Comment by xiaochaodevelop** [comment]
你这个用getViewByPosition时参数需要使用三个参数的，也就是要把RecyclerView传进去，刚试了一下，ok了
