### ISSUE TITLE
不知道会不会解决，先提.加入addheadview 后 更改item的数据然后刷新实体奔溃

### ISSUE THREAD

**Issue by fujingxie** [CymChad/BaseRecyclerViewAdapterHelper#1855]
拿demo改的：
  private void initAdapter() {
        headerAndFooterAdapter = new HeaderAndFooterAdapter(R.layout.item_header_and_footer,list);
        headerAndFooterAdapter.openLoadAnimation();
        mRecyclerView.setAdapter(headerAndFooterAdapter);

        headerAndFooterAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                headerAndFooterAdapter.getData().get(0).setUserName("修改的数据");
                headerAndFooterAdapter.notifyItemChanged(0);
                Toast.makeText(HeaderAndFooterUseActivity.this, "" + Integer.toString(position), Toast.LENGTH_LONG).show();
            }
        });

    }
修改数据后 notifyItemChanged就奔溃了；报：java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder

**Comment by 1109993488** [comment]
#1816
