### ISSUE TITLE
StaggeredGridLayoutManager 一次上拉，触发多次RequestLoadMoreListener

### ISSUE THREAD

**Issue by ShshyDevooo** [CymChad/BaseRecyclerViewAdapterHelper#1859]
当前使用版本
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.34'
使用StaggeredGridLayoutManager 后出现上拉一次，触发多次RequestLoadMoreListener
具体初始化代码如下
```
getRecyclerView().setLayoutManager(new StaggeredGridLayoutManager(4,StaggeredGridLayoutManager.VERTICAL));
        mAdapter = getAdapter();
        mAdapter.setEnableLoadMore(true);
        getRecyclerView().setAdapter(mAdapter);
        mAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                loadMore();
            }
        }, getRecyclerView());
        mAdapter.setLoadMoreView(new RvLoadMoreView());
```

**Comment by ShshyDevooo** [comment]
下面是加载更多数据实现：
```
 final List<Integer> list = new ArrayList<>();
        for (int i = 0; i < 10; i++)
            list.add(i);
        Observable.create(new ObservableOnSubscribe<List<Integer>>() {
            @Override
            public void subscribe(ObservableEmitter<List<Integer>> observableEmitter) throws Exception {
                Random random = new Random();
                if (random.nextBoolean())
                    observableEmitter.onNext(list);
                else
                    observableEmitter.onError(new Throwable("load failed"));
            }
        })
                .subscribeOn(Schedulers.io())
                .delay(1000, TimeUnit.MILLISECONDS)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<List<Integer>>() {
                    @Override
                    public void accept(List<Integer> integer) throws Exception {
                        mView.updateData(integer);
                        mView.showLoadComplete();
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        throwable.printStackTrace();
                        mView.showLoadError();
                    }
                });
```
以下是加载结束，加载完成，加载失败回调处理：
```
@Override
    public void showLoadComplete() {
        mAdapter.loadMoreComplete();
    }

    @Override
    public void showLoadError() {
        mAdapter.loadMoreFail();
    }

    @Override
    public void showLoadEnd() {
        mAdapter.loadMoreEnd();
    }
```

**Comment by RahulSDeshpande** [comment]
@ShshyDevooo Hey hii..

I believe your ```RecyclerView``` layout is nested under ```NestedScrollView```.
or else you have set ```setNestedScrollingEnabled(true)``` to your ```RecyclerView```'s object.

Better way post your layout code here.

Please confirm this first :)

**Comment by ShshyDevooo** [comment]
@RahulSDeshpande hi
this is my layout file
<?xml version="1.0" encoding="utf-8"?>
```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.telemedicine_tv.widget.ScaleRecyclerView
        android:id="@+id/rv_doctors"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</LinearLayout>
```
and this is my custom widget code:
```
public class ScaleRecyclerView extends RecyclerView {

    private int mSelectedPosition = 0;

    public ScaleRecyclerView(Context context) {
        super(context);
        init();
    }

    public ScaleRecyclerView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    public ScaleRecyclerView(Context context, @Nullable AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init();
    }

    private void init() {
        //启用子视图排序功能
        setChildrenDrawingOrderEnabled(true);
    }

    @Override
    public void onDraw(Canvas c) {
        mSelectedPosition = getChildAdapterPosition(getFocusedChild());
        super.onDraw(c);
    }

    @Override
    protected int getChildDrawingOrder(int childCount, int i) {
        int position = mSelectedPosition;
        if (position < 0) {
            return i;
        } else {
            if (i == childCount - 1) {
                if (position > i) {
                    position = i;
                }
                return position;
            }
            if (i == position) {
                return childCount - 1;
            }
        }
        return i;
    }
}
```
emm .. I don't use `NestedScrollView `anywhere.
Any problem with my custom `RecyclerView`?

**Comment by ck-snow** [comment]
adapter.addData后及时调用adapter.loadMoreComplete;

**Comment by ShshyDevooo** [comment]
@ck-snow 你好。我在addData后马上调用了loadMoreComplete，我贴出来的代码就是这样写的啊

**Comment by RahulSDeshpande** [comment]
Hey @ShshyDevooo !!

I **assume** :) that your custom RecyclerView -> ScaleRecyclerView is
1) scaling your layout depending upon the items in the list
2) & measuring the height of the RecyclerView and not letting your BaseQuickAdapter listen to the callbacks of your RecyclerView's end-scrolls.

If my assumption is wrong, **can you please explain what is the special use of your ScaleRecyclerView widget** !?

Cheers 👍

**Comment by ck-snow** [comment]
是这样的，我觉得这个可能是baserecyclerviewadapterhelper的bug，当屏幕中最后可见的item是数据data的最后一条时，就会触发onLoadMoreRequested方法。上拉加载更多的footer占据屏幕的空间，当加载完成后，footer会隐藏，这时adapter发现最后一个可见的item还是数据data的最后一条，又触发了onLoadMoreRequested。
解决办法：增大item的高度

**Comment by ShshyDevooo** [comment]
@ck-snow 你好，现在的情况是：当最后可见的item不是data的最后一条时还是会触发onLoadMoreRequested。

**Comment by ShshyDevooo** [comment]
@RahulSDeshpande hi.
I use the custom widget in order to scale the focus item in the recyclerview and not covered by the other items. By default , the recyclerview in the support library draw item by the position of the item and that cause the focused item covered by the item draw late than it.So i use the custom widget to change the default behavior.
emm , sorry ,my english is poor .. Have i make it clear for you?

**Comment by RahulSDeshpande** [comment]
@ShshyDevooo
Yess, but that can be done by managing the list item's layout.
But its okay, that would be your app's specific requirement :)

So I suppose, that's the reason your BaseQuickAdapter is not able to get the scroll-to-end callback from the RecyclerView.

Just for the time being, try replacing your
```<com.telemedicine_tv.widget.ScaleRecyclerView .. />```
with
```<android.support.v7.widget.RecyclerView .. />```
& map the objects respectively in your Java files.

This issue is everywhere when you use custom RecyclerView or NestedScrollView with BRVAH :)

Let us know :+1: 
Cheers !!

**Comment by caineyang** [comment]
//加载更多
        adapter.setOnLoadMoreListener({
            val lastVisibleItem = gridLayoutManager.findLastVisibleItemPosition()
            if (lastVisibleItem == adapter.itemCount - 1 && adapter.itemCount < gallery.size) {
                worker.getPhotos(virginLoad,date)
            }
        },recycleView)
我也出现了相同的情况，一打开，根本没有滑动，最后一个item也不可见，就一直再往前加载数据，知道没有数据可供加载才停下

**Comment by wmgylc** [comment]
是这样的，在回调函数里加一个判断recyclerView是否滚动到底部的判断就能发现，第一次滚动到底部触发加载后，接下来判断函数将不断判定滚动到底部，因而回调函数将不断加载，直到所有加载内容结束。另外在这个过程中检测itemcount好像也始终保持最开始的个数。。。

xml文件是最普通的recyclerView。

**Comment by caineyang** [comment]
@wmgylc 问题是我一进入就开始加载啊，并没有滚动操作，滑动到底部，最后一个item并不可见

**Comment by ShshyDevooo** [comment]
@caineyang 我也还没解决呢

**Comment by 1109993488** [comment]
@caineyang 加载更多不能和NestedScrollView嵌套使用

**Comment by 1109993488** [comment]
@ShshyDevooo 最好提供个demo
不知道你说的`一次上拉，触发多次RequestLoadMoreListener`是怎么回事。`addData`后如果不调用`loadMoreComplete`是不会回调`RequestLoadMoreListener`的。`RequestLoadMoreListener`回调是在`LoadMoreView`将要显示的时候回调的，就是在屏幕内或将要进入屏幕内。

**Comment by caineyang** [comment]
@1109993488 问题是我必须用NestedScrollView啊，使用了CollapsingToolbarLayout，和toolbar，有交互有没有什么替代？？？

**Comment by 1109993488** [comment]
@caineyang 和`CollapsingToolbarLayout`一起使用不一定非要用`NestedScrollView`，`RecyclerView`直接和`CollapsingToolbarLayout`是没有问题的，如果还有别的布局你可以加到`RecyclerView`的头部。`NestedScrollView`和`RecyclerView`嵌套使用是有问题的

**Comment by caineyang** [comment]
@1109993488 放弃使用NestedScrollView了，可以用了 谢谢老铁
