### ISSUE TITLE
onItemChildClick()中,请问如何点击A更改B的状态

### ISSUE THREAD

**Issue by jesse920524** [CymChad/BaseRecyclerViewAdapterHelper#186]
宇明哥下午好:
A为ImageView,B为textView
我想实现点击A,发送http请求,在server返回的数据中解析出数据,设置给B
目前我的代码是这样的:
@Override
            public void onItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                switch (view.getId()) {
                    case R.id.iv_listitem_like:(A控件的id)
                             //想在这里b.setText("");

请问如何实现,多谢了!

**Comment by CymChad** [comment]
B 同一个item的是指其他的控件？还是说其他item的 某一个控件？

**Comment by jesse920524** [comment]
A和B都是RecyclerView的一项中的不同控件,也就是同一item的其他控件. @CymChad

**Comment by CymChad** [comment]
改变相应的数据源数据进行刷新

**Comment by jesse920524** [comment]
刷新的话会造成recyclerView闪烁,我是这样解决的:
((TextView)((LinearLayout)(view.getParent())).findViewById(R.id.tv_listitem_like_count)).setText(articleItem.getFavCount());
找到A的父容器,通过父容器的findViewById()找到子元素B,向下转型为TextView后,调用setText方法更新B元素的状态.

你写的类库真的很好用,谢谢你!

**Comment by CymChad** [comment]
非常感谢你的使用，如果觉得好用就推荐给其他人吧。
