### ISSUE TITLE
调用adapter.remove(position)方法，发现删除的item位置不对

### ISSUE THREAD

**Issue by zou-xian-liang** [CymChad/BaseRecyclerViewAdapterHelper#1860]
1.调用adapter.addHeaderView()方法添加headView;
2.调用adapter.remove(position)删除position处条目，发现删除的position位置的后一个item数据;

**Comment by AllenCoder** [comment]
针对单独添加的headview和footview ，为了不影响点击事件回调中postion对list影响，返回的position 都不包括headview和footview的size
