### ISSUE TITLE
怎么在Adapter里使用butterknife

### ISSUE THREAD

**Issue by OtherSun** [CymChad/BaseRecyclerViewAdapterHelper#1861]
不重写BaseQuickAdapter怎么使用butterknife在adapter里绑定控件

**Comment by AllenCoder** [comment]
自定义baseviewHodler ，在viewholder里面使用 butterknife  绑定 itemview

**Comment by xiaoxiaohua333** [comment]
这个与 setEmptyView 会造成冲突

**Comment by lyhsgit2015** [comment]
ButterKnife.bind(this,holder.itemView)
