### ISSUE TITLE
Pls make documented bindToRecyclerView method

### ISSUE THREAD

**Issue by theonlylies** [CymChad/BaseRecyclerViewAdapterHelper#1862]
getViewByPosition(int position,int idRes) throw RuntimeExeption and say thant i must bind recyclerView first but i already bind it!!!
BUT
if i use getViewByPosition(RecyclerView,int position,int idRes) all fine
i think that is bug with BaseQuickAdapter getRecyclerView() method...pls check this

**Comment by theonlylies** [comment]
pls make documented bindRecyclerView method for adapter!!!

**Comment by qianzhihe86** [comment]
把recyclerView.setAdapter(mAdapter);改成mAdapter.bindToRecyclerView(recyclerView);就可以了

**Comment by theonlylies** [comment]
ok, but why is available method getViewByPosition(int position,int idRes) if this doent work?
and pls add to wiki info about that

**Comment by CymChad** [comment]
ok
