### ISSUE TITLE
bug 使用DiffUtil 刷新数据，并且 设置了setEmptyView 导致崩溃

### ISSUE THREAD

**Issue by yingshirun** [CymChad/BaseRecyclerViewAdapterHelper#1863]
bug 使用DiffUtil 刷新数据，并且 设置了setEmptyView 导致崩溃
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{ad57cb8 position=22 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{ee2edf6 VFED..... ......I. 0,0-1440,2112 #7f0800e1 app:id/recycler}, adapter:meevii.daily.beatles.reminder.adapter.ReminderListAdapter@d6475f7, layout:android.support.v7.widget.LinearLayoutManager@3c1ac64, context:meevii.daily.beatles.reminder.activity.MainActivity@693bab5

**Comment by kennir** [comment]
对，我也碰到这个问题了

**Comment by 1109993488** [comment]
数据没有或变有的时候EmptyView会改变显示状态，DiffUtil并没有计算EmptyView的改变，所以会报错。如果数据从无到有或从有到无，可以调下notifyDataSetChanged();

**Comment by tudou152** [comment]
> 数据没有或变有的时候EmptyView会改变显示状态，DiffUtil并没有计算EmptyView的改变，所以会报错。如果数据从无到有或从有到无，可以调下notifyDataSetChanged();

从无到有的时候，如果再次调用 dataSetChanged() 岂不是又刷新一次，浪费性能？这个问题是否能从框架的内部解决呢，我今天也刚好遇到了这个问题，不过是从有到无的时候遇到的。暂时用你提供的方法解决了，多谢啦~
