### ISSUE TITLE
没有清空数据的功能吗？

### ISSUE THREAD

**Issue by Wing-Li** [CymChad/BaseRecyclerViewAdapterHelper#1865]
下拉刷新之前，页面先要清空之前的数据。

**Comment by zofnk** [comment]
Use Adapter.getData().clear() or Adapter.setNewData()

**Comment by Wing-Li** [comment]
`Adapter.getData().clear() `
只清空了数据，并没有更新UI；

`Adapter.setNewData() `
是拿到数据之后，才能覆盖以前的。
而我的需求是：下拉刷新时，立马将页面上显示的东西 清空，等拿到数据了，再给列表显示。

我目前的做法是：
`adapter.replaceData(new ArrayList<BtInfo>());`

**Comment by zofnk** [comment]
Adapter.getData().clear();
Adapter.notifyDataSetChanged(); ?

**Comment by Wing-Li** [comment]
这样也可以，效果是一样的。

但是两种做法都存在一个问题：
如果设置了数据为空时，显示某个页面。
那么这两种做法，都会先显示那个 空数据 的页面。

**Comment by AllenCoder** [comment]
当需求与提供的功能有不一致时，建议适当改造，可根据自己的业务场景，定制各种状态下的recyclerview的视图，下拉刷新时 立马将页面上显示的东西 清空；同时移除空布局，等拿到数据了，再给列表显示。同时设置空布局
