### ISSUE TITLE
OnItemClickListener点击事件问题

### ISSUE THREAD

**Issue by MisterBowie** [CymChad/BaseRecyclerViewAdapterHelper#1866]
我使用的RecyclerView做的grid布局, item布局中有一个button,button没有设置点击事件,
Adapter写法如下:
 helper.setText(R.id.recharge_rule_btn, item.getRechargeName());
        if (position == helper.getAdapterPosition()) {
            item.setSelect(true);
            helper.setTextColor(R.id.recharge_rule_btn, mContext.getResources().getColor(R.color.theme_color));
            helper.setBackgroundRes(R.id.recharge_rule_btn, R.drawable.drawable_feed_back_edit);
        } else {
            item.setSelect(false);
            helper.setTextColor(R.id.recharge_rule_btn, mContext.getResources().getColor(R.color.black));
            helper.setBackgroundRes(R.id.recharge_rule_btn, R.drawable.drawable_feed_back_black_edit);
        }

adapter设置监听代码如下:
adapter.setOnItemClickListener((baseAdapter, view, position) -> {
            adapter.setPosition(position);
            adapter.notifyDataSetChanged();
            rulesDesTv.setText(rechargeRules.get(position).getRechargeDes());
        });
这样只有点击button以外的区域才会有点击事件的回调, 点击button并不会是item的点击事件生效

**Comment by AllenCoder** [comment]
button 在 listview和recyclerView中 ，都会抢占焦点事件 ，无论是否设置了点击事件，可参考 https://stackoverflow.com/questions/30396075/click-through-recyclerview-empty-space

建议 将button 的id 设置为可点击的childview ,在childview里面处理 itemchild的点击事件 
```


adapter.setItemChildClickListener(// todo your thing)

```
