### ISSUE TITLE
长按与拖拽冲突

### ISSUE THREAD

**Issue by lhyocean** [CymChad/BaseRecyclerViewAdapterHelper#1870]
在长按事件中调用adapter.notifyDateChange  ，然后当前的拖拽排序就失效了，不能触发了，（我的需求是长按时出现一个删除按钮，所以需要调notify）
 版本，现在的最新版本（我直接clone 在demo 内改的）

**Comment by AllenCoder** [comment]
长按事件和拖拽事件都需要消费touch事件，两个接口目前是独立开来的，如果同时消费，必然会导致，先触发的消费后，后面的接口消费不到，

可以把 长按的业务逻辑 放在 

```
 @Override
            public void onItemDragStart(RecyclerView.ViewHolder viewHolder, int pos) {
                Log.d(TAG, "drag start");
                BaseViewHolder holder = ((BaseViewHolder) viewHolder);
//                holder.setTextColor(R.id.tv, Color.WHITE);
            }

```

**Comment by NewHuLe** [comment]
我也遇见这类问题，发现只要长按的时候调用notifyDataSetChanged（）来刷新适配器显示删除按钮，设置的拖动就会失效，需要再长按一次才能拖动，在onItemDragStart（）中也无法处理这个问题，请问这需要如何解决呢 @lhyocean @CymChad

**Comment by alguojian** [comment]
我也有这个需求，开启拖拽的时候，每个item会多显示删除按钮，我再onItemDragStart中调用了notifyDataSetChanged（），后拖拽失效了，请问针对这个需求我改如何处理呢？
