### ISSUE TITLE
博客需要更新了

### ISSUE THREAD

**Issue by ZhangPeng0220** [CymChad/BaseRecyclerViewAdapterHelper#1871]
最近看你们简书博客源码分析，由于你们版本升级代码封装有了变化，建议调整一下。
比如https://www.jianshu.com/p/fa3f97c19263，还有其他的，我也遇到了

**Comment by CymChad** [comment]
好的多谢提醒，我下周更新最近这几周都很忙。下周统一统计下内容一并更新
