### ISSUE TITLE
BaseSectionQuickAdapter 数据多的时候渲染慢，卡

### ISSUE THREAD

**Issue by lanshifu** [CymChad/BaseRecyclerViewAdapterHelper#1874]
项目中需要搜索功能，两种数据源，所以使用了分组BaseSectionQuickAdapter 。
联系人有1500条，在输入1的时候，子线程查询，然后主线程调用 mAdapter.replaceData(list);

结果：界面卡顿无法操作，1秒之后才显示数据。当数据比较少的时候就不卡，比如10条。
结论：数据多的时候调用BaseSectionQuickAdapter.replaceData()，界面卡。
作者看下能不能优化。

**Comment by CymChad** [comment]
收到

**Comment by 1109993488** [comment]
界面卡肯定不是replaceData这句话造成的，请检查你筛选数据是在子线程中执行的
