### ISSUE TITLE
使用BaseQuickAdapter导致高度无法自适应，会保持一定最小高度，使用基础类RecyclerView.Adapter无此问题

### ISSUE THREAD

**Issue by KnightGuard** [CymChad/BaseRecyclerViewAdapterHelper#1875]
item里面是两个text.setText(Html.fromHtml(result, mUrlImageGetter, null));

**Comment by KnightGuard** [comment]
找到原因，版本：2.9.28
Change the method setVisible --> setGone
The new method setVisible
还在用旧方法导致占据空间

**Comment by CymChad** [comment]
嗯，以及更新方法了
