### ISSUE TITLE
请问Section能别的布局结合使用吗?

### ISSUE THREAD

**Issue by zofnk** [CymChad/BaseRecyclerViewAdapterHelper#1878]
如果有这样一个设计稿:
如图:![tim 20171228113947](https://user-images.githubusercontent.com/17997544/34399619-e7517dce-ebc3-11e7-8e66-ef7dc0eed583.png)

最外层是Section , 每个Section中又嵌套好几种各不相同的多种行布局列表,而且Section数量不定,需要根据后台返回的数据来的. 这样的列表在该库中需要怎么去实现?

**Comment by cai784921129** [comment]
有个开源库可以实现，类似这种用法
![image](https://user-images.githubusercontent.com/20353284/34472570-f7b20d48-ef9f-11e7-97f0-c44caf57d533.png)

**Comment by zofnk** [comment]
@cai784921129 兄呆 库叫啥...你截图的这3个列表中 , 最下面那个List能实现上拉加载吗? 而不是一个固定的size?

**Comment by cai784921129** [comment]
https://github.com/luizgrp/SectionedRecyclerViewAdapter
上拉加载你用 https://github.com/cai784921129/PullToRefreshView 可以实现

**Comment by zofnk** [comment]
@cai784921129 我看了下 是可以实现 只是想为了实现这一个列表而去多了2个库 冗余了挺多 , 那用这个BaseRecyclerViewAdapterHelper库里是怎么去实现这种需求的List?

**Comment by cai784921129** [comment]
我不是开发者，只是最近在使用BaseRecyclerViewAdapterHelper，具体能不能实现，还要请开发者解答

**Comment by CymChad** [comment]
可以使用多布局实现

**Comment by zenchen3331** [comment]
「可以使用多布局实现」
大佬 如何结合使用呢？
Adapter 继承了 BaseSectionQuickAdapter ，Entity 继承了 SectionEntity，
这样可以分组。
让后自己做多布局实现吗？
还是说可以结合 BaseMultiItemQuickAdapter 使用，
如何结合呢？
