### ISSUE TITLE
多布局时需要清空数据，item布局清空了，title布局没有清空

### ISSUE THREAD

**Issue by Vegen** [CymChad/BaseRecyclerViewAdapterHelper#1881]
mAdapter.getData().clear();
if (dataList.size() > 0) mAdapter.getData().addAll(dataList);
mAdapter.notifyDataSetChanged();

dataList初次有数据时size > 0的时候无误，但是无数据的时候会保留着上一次的title，item的布局确实清空了，请问怎样才可以彻底清空连带title

**Comment by Vegen** [comment]
多布局还是无法完全清空啊，麻烦修复一下这个bug

**Comment by CymChad** [comment]
使用setNewData
