### ISSUE TITLE
mAdapter.getViewByPosition获取组件时得到null。

### ISSUE THREAD

**Issue by qianzhihe86** [CymChad/BaseRecyclerViewAdapterHelper#1885]
获取列表数据成功后，展示数据完毕。然后在任意地方使用mAdapter.getViewByPosition获取组件时得到null。

**Comment by qianzhihe86** [comment]
在setOnItemChildClickListener外部调用的

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1876

**Comment by richfuns** [comment]
我也遇到这个问题了，请问怎么解决的？谢谢
