### ISSUE TITLE
ExpandableUseActivity收缩性能问题

### ISSUE THREAD

**Issue by zuoyuan333** [CymChad/BaseRecyclerViewAdapterHelper#1889]
demo中的ExpandableUseActivity 的获取数据部分
generateData()改成如下
private ArrayList<MultiItemEntity> generateData() {
        int lv0Count = 1;
        int lv1Count = 100000;

        String[] nameList = {"Bob", "Andy", "Lily", "Brown", "Bruce"};
        Random random = new Random();

        ArrayList<MultiItemEntity> res = new ArrayList<>();
        for (int i = 0; i < lv0Count; i++) {
            Level0Item lv0 = new Level0Item("This is " + i + "th item in Level 0", "subtitle of " + i);
            for (int j = 0; j < lv1Count; j++) {
                Level1Item lv1 = new Level1Item("Level 1 item: " + j, "(no animation)");
                lv0.addSubItem(lv1);
            }
            res.add(lv0);
        }
        return res;
    }
点击收缩的时候卡很久很久然后anr,.....360清理大师的微信清理的图片也有很多,点击收缩就不会有任何卡顿

**Comment by CymChad** [comment]
这个和rv的容器有关。使用的都是rv的原生方法
