### ISSUE TITLE
有关拖拽的疑问

### ISSUE THREAD

**Issue by xj999** [CymChad/BaseRecyclerViewAdapterHelper#1890]
我在多类型的adapter内想实现部分type可拖拽的功能,请问在源码内哪个位置修改可以实现,我试了下重写ItemDragAndSwipeCallback的onMove方法,但是拖拽1个item他就开始疯狂闪烁了

**Comment by CymChad** [comment]
默认是支持的

**Comment by MariShunxiang** [comment]
我也有这个需求。不过是单类型的adapter

**Comment by MariShunxiang** [comment]
请问调用哪个方法可以实现部分item可拖拽？

**Comment by shichaohui** [comment]
参考 #2740 #2202 #370 #1419
