### ISSUE TITLE
disableLoadMoreIfNotFullPage 设置无效

### ISSUE THREAD

**Issue by WuGang128** [CymChad/BaseRecyclerViewAdapterHelper#1893]
disableLoadMoreIfNotFullPage 设置了 第一次默认还是会加载更多

**Comment by CymChad** [comment]
建议按demo的方式来处理

**Comment by WuGang128** [comment]
按demo 的方式还是会出现加载更多View  闪以下 。可不可以在触发加载更多的时候直接判断 和pageSize

**Comment by 1109993488** [comment]
第一次设置数据的时候就可以判断是否还有更多数据，没有的话可以调用loadMoreEnd(boolean)方法关闭加载更多，这样就不会出现闪一下

**Comment by WuGang128** [comment]
我这么尝试过还是会闪一下

**Comment by 1109993488** [comment]
怎么闪一下?`RecyclerView`自带的动画？关闭试试`RecyclerView.setItemAnimator(null);`

**Comment by WuGang128** [comment]
会出现加载更多的view 但是很快就 变成没有更多数据了

**Comment by 1109993488** [comment]
最好贴下代码，要不参考demo；
最开始列表没有数据的时候是不会显示加载更多的，在设置`setNewData`后判断是否有更多数据没有调`loadMoreEnd(boolean)`关闭加载更多，这时候界面绘制完成是不会显示加载更多的。如果只有几条数据，你没有关闭加载更多，是会显示加载更多的，这个时候回调`onLoadMoreRequested`会再次请求数据，如果请求很快并且没有数据再关闭就会出现你说的闪一下

**Comment by WuGang128** [comment]
非常感谢问题解决了
