### ISSUE TITLE
上拉加载有问题

### ISSUE THREAD

**Issue by ZHANG111** [CymChad/BaseRecyclerViewAdapterHelper#190]
当数据不满一屏时，刚进来会自动上拉加载更多，这个操作是不应该的。
把PullToRefreshUseActivity里面的PAGE_SIZE由6改为2再运行一下，就可以看到bug了

**Comment by CymChad** [comment]
这个是你可以控制的，通过pageSize，除非这个方法是又pageSize来判断的。因为我无法得知你一页的数量，所以需要你告诉我你一页有多少个。如果你告诉我你一页有2个，那么我当到达了2个就帮你加载更多。

**Comment by ZHANG111** [comment]
给这个问题配了个图：http://blog.csdn.net/ZhangLiChunZuoYa/article/details/52053644。你看看

**Comment by CymChad** [comment]
数据如果一页的数量都不满足，还会有下一页的数据吗？

**Comment by CymChad** [comment]
>当初始数据不满一屏时（数据从服务器获取，数目不确定，有可能是6个，也有可能是2个。。。。）刚进来就会执行上拉加载更多。 
你上拉加载的判断（mCurrentCounter >= TOTAL_COUNTER）个人感觉不是很合理。

如果数据不瞒住一屏，那么还会有下一页吗？
mCurrentCounter >= TOTAL_COUNTER 这个判断不是固定的，可以由开发者自定义，你如果有页数的话可以通过页数判断。

**Comment by ZHANG111** [comment]
明白你的意思了。
但是还有个问题，有的大屏幕手机一屏可以放6个条目，小屏手机只能放4个条目，这样的话，pageSize到底是选6还是选4？

**Comment by CymChad** [comment]
6

**Comment by CymChad** [comment]
你们服务器应该有定每页显示多少个吧。
