### ISSUE TITLE
有多个Head时，为RcyclerView设置的ItemDecoration在多个Head之间无效

### ISSUE THREAD

**Issue by TheStar4Fate** [CymChad/BaseRecyclerViewAdapterHelper#1901]
我使用的ItemDecoration是com.yqritc:recyclerview-flexibledivider:1.4.0
Adapter是com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.33
RecyclerView版本是27.0.2
![_20180104204808](https://user-images.githubusercontent.com/7358871/34564180-a292136a-f190-11e7-8f4c-7bfdfdbe0730.jpg)
具体情况如图所示，第一条数据与head之间有ItemDecoration效果，但是Head与Head之间没有

**Comment by 1109993488** [comment]
目前header整体是一个item

**Comment by TheStar4Fate** [comment]
明白了，我试下其他方法
