### ISSUE TITLE
特殊情况下loadMoreEnd()调用失败，导致重复数据

### ISSUE THREAD

**Issue by zhyihui** [CymChad/BaseRecyclerViewAdapterHelper#1902]
查看了一些issue没有发现我遇到的问题；
当数据量正好填满一页，最后一条数据显示一部分的时候，可以加载更多，但其实数据已经加载完了，没有更多数据了。
如下图所示，其实数据总共7条，“百岁山”下面露一部分的是最后一条了，但这时还是可以加载更多，此时page=2，但服务器返回的还是第一页7条数据（重复加载），但是继续往下拉就不会再次加载了。
<img width="343" alt="qq20180104-234049 2x" src="https://user-images.githubusercontent.com/4401837/34571176-c9c41754-f1a8-11e7-9b57-b7096e9d5f4d.png">

从下面两个图片中可以看到，一共只有7条数据
<img width="345" alt="qq20180104-234757 2x" src="https://user-images.githubusercontent.com/4401837/34571560-cbc9a496-f1a9-11e7-97b4-0d1040c11e4f.png">
<img width="341" alt="qq20180104-234813 2x" src="https://user-images.githubusercontent.com/4401837/34571575-d411cf34-f1a9-11e7-9f31-0705b910e3e0.png">

数据更多或者数据不满一页都不会出现这种情况，不知道是我哪里用的不对么？下面是我的部分代码：

```java
Api.instance.order(mapOf("smiId" to uid, "soStatus" to mType, "pageNum" to mPage.toString()))
        .compose(bindToLifecycle())
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe { resp ->
            mBinding.swipeRefreshLayout.isRefreshing = false
            if (!resp.isOk()) {
                toast(resp.desc())
                return@subscribe
            }
            mAdapter.loadMoreComplete()
            if (!resp.hasMore()) mAdapter.loadMoreEnd()
            if (mPage == 1) {
                mAdapter.setNewData(resp.data.list)
                mAdapter.disableLoadMoreIfNotFullPage()
            } else {
                mAdapter.addData(resp.data.list)
            }
        }
```

在上面描述的情况下，`resp.hasMore()`反回的是false（没有更多数据），满足`loadMoreEnd()`方法调用条件，但这个方法调用无效。

经过跟踪，发现是 `if (!resp.hasMore()) mAdapter.loadMoreEnd()`这行代码没有执行下去，因为`loadMoreEnd()`方法中有下面这个判断
```java
if (getLoadMoreViewCount() == 0) {
    return;
}
```
此时正好满足这个条件，`getLoadMoreViewCount ()` 返回的是0，而这个方法
```java
public int getLoadMoreViewCount() {
        if (mRequestLoadMoreListener == null || !mLoadMoreEnable) {
            return 0;
        }
        if (!mNextLoadEnable && mLoadMoreView.isLoadEndMoreGone()) {
            return 0;
        }
        if (mData.size() == 0) {
            return 0;
        }
        return 1;
    }
```
返回0是因为`mLoadMoreEnable `为false，虽然找到原因，但不知道为什么以及怎样解决。

请问这是怎么回事呢？是我做的不对吗？谢谢....

**Comment by 1109993488** [comment]
`mLoadMoreEnable`属性会在`setOnLoadMoreListener(RequestLoadMoreListener)`后设置为true，只有`setEnableLoadMore(false)`才会置为false

应该按下面的来处理
```
mBinding.swipeRefreshLayout.isRefreshing = false
if (!resp.isOk()) {
    toast(resp.desc())
    return@subscribe
}

if (mPage == 1) {
    mAdapter.setNewData(resp.data.list)
} else {
    mAdapter.addData(resp.data.list)
}
if (resp.hasMore()) {
    mAdapter.loadMoreComplete()
} else {
    mAdapter.loadMoreEnd()
}
```

**Comment by zhyihui** [comment]
@1109993488 非常感谢你的解答，我马上试一下，我看你说了一句“只有setEnableLoadMore(false)才会置为false”，那么在上述情况下，是哪里导致`setEnableLoadMore(false)`被调用了呢？
另外，按你的做法，`mAdapter.disableLoadMoreIfNotFullPage()`这行代码应该在哪里调用呢？
再次感谢！

**Comment by zhyihui** [comment]
@1109993488 你说的方式并不能解决问题
在我最初的代码中，`mAdapter.loadMoreEnd()`调用之前并没有`setEnableLoadMore(false)`方法的调用机会呢

**Comment by 1109993488** [comment]
`mAdapter.disableLoadMoreIfNotFullPage()`内部也会调用`setEnableLoadMore(false)`，最好是用没有更多数据去关闭加载更多，而不用`mAdapter.disableLoadMoreIfNotFullPage()`来管理不满足一屏的情况下关闭加载更多

**Comment by zhyihui** [comment]
可是在我最初的代码中，调用`loadMoreEnd()`之前并没有调用过`disableLoadMoreIfNotFullPage()`，`disableLoadMoreIfNotFullPage ()`是之后调用的，所以我还不是很明白为什么会出现上面的情况。
最初代码：
```java
     mAdapter.loadMoreComplete()
     if (!resp.hasMore()) mAdapter.loadMoreEnd()
     if (mPage == 1) {
          mAdapter.setNewData(resp.data.list)
          mAdapter.disableLoadMoreIfNotFullPage()
     } else {
         mAdapter.addData(resp.data.list)
     }
```
而我确实是用`if (!resp.hasMore()) mAdapter.loadMoreEnd()`来关闭加载更多的，请问这有没有可能是Bug呢！我的用法哪里有问题吗？
谢谢！

**Comment by zhyihui** [comment]
@1109993488 另外，更多数据或更少数据并不会出现这种问题；用你上面的代码不能解决问题，所以应该不是`disableLoadMoreIfNotFullPage ()`方法的原因。
麻烦了，谢谢

**Comment by 1109993488** [comment]
请参考demo，最好提供出问题的demo，这样能快速找到问题，你可以在demo中试试
