### ISSUE TITLE
分割线有问题

### ISSUE THREAD

**Issue by zouzhenglu** [CymChad/BaseRecyclerViewAdapterHelper#1906]
添加了空界面后，如果有分割线，下面还会有分割线，
添加了foot跟header 也是，有类似的问题

**Comment by 1109993488** [comment]
`EmptyView`、`Header`、`Footer`都是Item，所以需要自己处理不显示分割线
`getEmptyViewCount()`、`getHeaderLayoutCount()`、`getFooterLayoutCount()`、`getLoadMoreViewCount()`
