### ISSUE TITLE
平常在手机debug测试的时候可以使用，但是在项目正式签名打包上线之后，BaseRecyclerViewAdapterHelper就不能使用了

### ISSUE THREAD

**Issue by WinnerLi** [CymChad/BaseRecyclerViewAdapterHelper#1908]
你好，我也出现了debug时可以正常使用，但是在正式签名之后出现问题，添加了混淆不能使用，取消混淆之后就可以正常使用。
build.gradle文件:
release { minifyEnabled true shrinkResources true proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' } debug { minifyEnabled false proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' }
混淆代码：
-keep class com.chad.library.adapter.** { *; } -keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter -keep public class * extends com.chad.library.adapter.base.BaseViewHolder -keepclassmembers public class * extends com.chad.library.adapter.base.BaseViewHolder { <init>(android.view.View); }

**Comment by WinnerLi** [comment]
发现只是有没有混淆的区别，添加了混淆就不能使用，没有添加混淆就可以使用。和是否正式签名没有关系

**Comment by jwdtommy** [comment]
-keep class com.chad.library.adapter.** {
*;
}
-keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter{*;}
-keep public class * extends com.chad.library.adapter.base.BaseViewHolder{*;}
-keepclassmembers  class **$** extends com.chad.library.adapter.base.BaseViewHolder {
     <init>(...);
}

**Comment by alen252** [comment]
> 添加混淆规则 proguard-rules.pro
> 
> ```
> 
> -keep class com.chad.library.adapter.** {
> *;
> }
> -keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter
> -keep public class * extends com.chad.library.adapter.base.BaseViewHolder
> -keepclassmembers  class **$** extends com.chad.library.adapter.base.BaseViewHolder {
>      <init>(...);
> }
> ```

没有用。。
