### ISSUE TITLE
请问调用哪个方法可以实现部分item可拖拽？

### ISSUE THREAD

**Issue by MariShunxiang** [CymChad/BaseRecyclerViewAdapterHelper#1911]
请问调用哪个方法可以实现部分item可拖拽？

**Comment by CymChad** [comment]
目前框架没有实现你说的那个需求。
但是我看到网上资料可以
```
@Override
 public void onItemLongClick(RecyclerView.ViewHolder vh) {
     //判断被拖拽的是否是前两个，如果不是则执行拖拽
     if (vh.getLayoutPosition() != 0 && vh.getLayoutPosition() != 1) {
         mItemTouchHelper.startDrag(vh);
 
     }
 }
```
来源：https://www.cnblogs.com/wjtaigwh/p/6543354.html

**Comment by MariShunxiang** [comment]
好的，多谢大佬~

**Comment by sinkkin** [comment]
> 好的，多谢大佬~

请问一下，你按这个写了有用吗，为什么这样写还是可以拖拽啊

**Comment by gaojian89** [comment]
> > 好的，多谢大佬~
> 
> 请问一下，你按这个写了有用吗，为什么这样写还是可以拖拽啊

继承BaseItemDraggableAdapter重写setToggleDragOnLongPress()和onItemDragMoving()也可以实现。
![qq 20181221095815](https://user-images.githubusercontent.com/7867727/50320369-05b26c80-0507-11e9-9a25-9c148ecafd66.png)
![qq 20181221095815](https://user-images.githubusercontent.com/7867727/50320380-0e0aa780-0507-11e9-8d60-cab2d35e4128.png)

**Comment by daxiong--** [comment]
static class DoubleItemDragAndSwipeCallback extends  ItemDragAndSwipeCallback{

        private WeakReference<List<AppFuncCommonVo>> dataWeakReference;
        public DoubleItemDragAndSwipeCallback(BaseItemDraggableAdapter adapter,List<AppFuncCommonVo> data) {
            super(adapter);
            dataWeakReference = new WeakReference<>(data);
        }

        @Override
        public int getMovementFlags(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder) {

            if (dataWeakReference.get().get(viewHolder.getAdapterPosition()).getIsLock()){
                return super.makeMovementFlags(0,0);
            }else{
                return super.getMovementFlags(recyclerView, viewHolder);
            }

        }



        @Override
        public void onMoved(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder source, int fromPos, @NonNull RecyclerView.ViewHolder target, int toPos, int x, int y) {
            if (!dataWeakReference.get().get(toPos).getIsLock()){
                super.onMoved(recyclerView, source, fromPos, target, toPos, x, y);
            }
        }

    }

**Comment by daxiong--** [comment]
直接继承该库的ItemDragAndSwipeCallbac,实现了部分按钮不可以拖拽，而且该部分按钮不能其他拖拽替代
static class DoubleItemDragAndSwipeCallback extends  ItemDragAndSwipeCallback{

        private WeakReference<List<AppFuncCommonVo>> dataWeakReference;
        public DoubleItemDragAndSwipeCallback(BaseItemDraggableAdapter adapter,List<AppFuncCommonVo> data) {
            super(adapter);
            dataWeakReference = new WeakReference<>(data);
        }

        @Override
        public int getMovementFlags(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder) {

            if (dataWeakReference.get().get(viewHolder.getAdapterPosition()).getIsLock()){
                return super.makeMovementFlags(0,0);
            }else{
                return super.getMovementFlags(recyclerView, viewHolder);
            }

        }



        @Override
        public void onMoved(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder source, int fromPos, @NonNull RecyclerView.ViewHolder target, int toPos, int x, int y) {
            if (!dataWeakReference.get().get(toPos).getIsLock()){
                super.onMoved(recyclerView, source, fromPos, target, toPos, x, y);
            }
        }

    }
