### ISSUE TITLE
BaseMultiItemQuickAdapter 折叠展开问题

### ISSUE THREAD

**Issue by a7891749** [CymChad/BaseRecyclerViewAdapterHelper#1914]
部分代码
![代码截图](https://user-images.githubusercontent.com/24807345/34759217-5c61cae6-f615-11e7-9696-2180f30a5071.png)

**Comment by a7891749** [comment]
![s80110-14401803](https://user-images.githubusercontent.com/24807345/34759338-108e762c-f616-11e7-9d49-4911fd22669f.gif)

**Comment by CymChad** [comment]
请检查你的数据源。

**Comment by a7891749** [comment]
我因为重写了equals 所以才会出现这个问题。
解决办法
 
![rofg 2uj 8k4 j pw a0t](https://user-images.githubusercontent.com/24807345/35033813-000937a6-fba7-11e7-80ca-4c1b969f12eb.png)
