### ISSUE TITLE
RecyclerView嵌套recyclerview ，滑动到网格recyclerview 时，会在网格recyclerview开始位置卡顿一下。（垂直recyclerview item是 网格recyclerview）

### ISSUE THREAD

**Issue by qianzhihe86** [CymChad/BaseRecyclerViewAdapterHelper#1916]
RecyclerView嵌套recyclerview ，滑动到网格recyclerview 时，会在网格recyclerview开始位置卡顿一下。（垂直recyclerview item是 网格recyclerview）。
1、在外部适配器里面加上 
RecyclerView.RecycledViewPool mSharedPool = new RecyclerView.RecycledViewPool();后
在其convert方法加上outRecyclerView.setRecycledViewPool(mSharedPool);也未能解决。
2、在外部适配器的convert方法里面，网格recyclerview地方加上：
  GuessLikeAdapter guessLikeAdapter = (GuessLikeAdapter) guessYouLikeRecyclerView.getAdapter();
                if (guessLikeAdapter == null) {
                    guessLikeAdapter = new GuessLikeAdapter(R.layout.guess_like_item);//智能推荐item
                    guessYouLikeRecyclerView.setAdapter(guessLikeAdapter);
                }
                guessLikeAdapter.setNewData(guessYouLikeList);也不能解决问题

**Comment by qianzhihe86** [comment]
网格recyclerview 数据有96条，也就是说这96条数据为外部recyclerview 的一个item

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1618  这个一般都是item复杂或者图片加载过大导致，建议你可以优化下你都item或者优化下你都图片加载方式。

**Comment by qianzhihe86** [comment]
好的。#1905里面的方法试过了，还是不管用。后台一次性返回90+的数据作为一个item，没法优化，我换了一个办法解决了。谢谢

**Comment by zofnk** [comment]
@qianzhihe86 请问下是怎么解决的?

**Comment by qianzhihe86** [comment]
我换成2个RecyclerView了，没有嵌套了。

**Comment by waitingFat** [comment]
我自己用了BaseMultiItemQuickAdapter 和 google原生的holder写法两种情况对比，  发现确实是像楼主说的前者在多条目且子view有recycleview的时候 特别卡 ，而原生的写法表现非常流畅

**Comment by FightTigher** [comment]
@waitingFat 为什么我用原生的表现也很卡顿？可以看下代码吗

**Comment by zhangqifan1** [comment]
嘤嘤嘤,请问这个解决了么..版本是2.9.46

**Comment by fengjuan** [comment]
碰到同样的问题

**Comment by haegyeong** [comment]
有解决方案吗？我也碰到这个问题了，头痛
