### ISSUE TITLE
当我添加一个自定义的viewgroup去作为emptyview的时候，该怎么正确的设置点击事件

### ISSUE THREAD

**Issue by Colaman0** [CymChad/BaseRecyclerViewAdapterHelper#1918]
如题，我想写一个布局作为emptyview，然后点击的时候进行刷新，但是我发现，setEmptyView这个方法，要么传一个view，要么传布局文件进去，但是传布局文件的话我没法设置点击

**Comment by Abvatous** [comment]
请问 2.X，3.x  现在有添加点击事件api嘛？我现在传入一个view动态布局添加点击事件。插个眼吧
