### ISSUE TITLE
添加头部的问题

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#192]
请问下， 添加头部，能不能在头部实现一个图片轮播的效果

**Comment by CymChad** [comment]
头部的内容是随开发者自定义的。

**Comment by wuzhaohui026** [comment]
已经解决了，问题处在我是用的Fragment，然后addHeaderView(getView());getView()这个方法和Fragment的方法重叠了，所以导致加载不出来
