### ISSUE TITLE
可以设置组头悬停到顶部吗?

### ISSUE THREAD

**Issue by keaitao0321** [CymChad/BaseRecyclerViewAdapterHelper#1920]
我的需求是对数据进行分组,但是在上滑的时候组头要停留在顶部,下滑的时候又自动下滑

**Comment by cai784921129** [comment]
自己根据BaseRecyclerViewAdapterHelper写的例子，里面有悬停头部用法 https://github.com/cai784921129/BaseRecyclerViewAdapterHelper

**Comment by keaitao0321** [comment]
谢谢
