### ISSUE TITLE
自定义ViewHolder

### ISSUE THREAD

**Issue by SrDino** [CymChad/BaseRecyclerViewAdapterHelper#1923]
大佬，谢谢你写这个框架，方便我们的使用，但是在使用的过程中，出现了一个问题，怎么样在自定义ViewHolder的构造方法形参，传入除了View的其他的参数，还有，如何获取ViewHolder里面的adapter,没有找到getAdapter的方法，

**Comment by CymChad** [comment]
ViewHolder 是基于 Adapter 的，你可以直接写成内部类就可以拿到adapter到内部属性了。

**Comment by SrDino** [comment]
大佬，你好，首先谢谢能回复我，后来我想了想，已经这样实现了，我想问下，这个框架为什么要这样设计，有setAdapter，却没有getAdapter，是不是有什么原因的？望解答，谢谢。




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2018年1月17日(星期三) 下午5:08
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "546861506"<546861506@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 自定义ViewHolder (#1923)




ViewHolder 是基于 Adapter 的，你可以直接写成内部类就可以拿到adapter到内部属性了。

**Comment by CymChad** [comment]
setAdapter 是给item为rv的设置的，getAdapter应该是从rv对象获得的。因为adapter是基于rv的

**Comment by SrDino** [comment]
不是很懂，不过还是谢谢了。


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2018年1月17日(星期三) 下午5:21
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "546861506"<546861506@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 自定义ViewHolder (#1923)




setAdapter 是给item为rv的设置的，getAdapter应该是从rv对象获得的。因为adapter是基于rv的
