### ISSUE TITLE
setOnItemSwipeListener#onItemSwiped is called before the data is changed

### ISSUE THREAD

**Issue by humazed** [CymChad/BaseRecyclerViewAdapterHelper#1928]
when using `setOnItemSwipeListener#onItemSwiped` as in sample application I noticed that `onItemSwiped` is called before the swiped item is deleted from the data list.

looking at library code it turns out the that in `BaseItemDraggableAdapteronItemSwiped#onItemSwiped` is called before remove `mData.remove(pos);`

which make the callback mostly useless if you want to make anything with the updated data.

I'm suggesting moving onItemSwiped at the end of the method.

I have tried it and every this seems to be working fine.
I can make a pull request for it if you want.

**Comment by CymChad** [comment]
Thank you for your request
