### ISSUE TITLE
加载更多时，如何手动关闭

### ISSUE THREAD

**Issue by xueyaolive** [CymChad/BaseRecyclerViewAdapterHelper#193]
如果调用notifyDataChangedAfterLoadMore(false);问题是下次再拉到底部就不会触发了

**Comment by CymChad** [comment]
你要做什么样的需求？

**Comment by xueyaolive** [comment]
我已经加载了几页数据，后面还有数据，网络断了，自然就返回了error，我在error里是要关闭加载更多的转圈图标，如果此时我又联网了，重新滑动到底部是不是应该重新加载更多，由于调用了notifyDataChangedAfterLoadMore(false)方法，下次滑动到底部就不触发了，总不能让其重新刷新一次，再滑到底部触发吧，就是有什么方法就是直接关闭加载更多，下次滑动到底部依然可以触发加载更多，不知作者有没有听明白我的意思！

**Comment by CymChad** [comment]
自定义的加载失败尾部errorFooterView添加如下代码：
errorFooterView.setOnClickListener(view -> {
adapter.removeFooterView(errorFooterView);
adapter.openLoadMore(true);
});
在请求失败的回调函数调用adapter.addFooterView(errorFooterView).

**Comment by wjehovah** [comment]
> 在请求失败的回调函数调用adapter.addFooterView(errorFooterView).
 可以不传 footer 直接stop 么

**Comment by CymChad** [comment]
@wjehovah  notifyDataChangedAfterLoadMore(false)  这样之后就是stop，不可以在上拉了。

**Comment by wjehovah** [comment]
@CymChad 但是我还想 上拉。希望公开一个方法。
```java
  /**
   * 关闭下拉和上拉刷新 view
   */
  private void stopRefresh() {
    if (swipeLayout == null || adapter == null) {
      return;
    }
    if (swipeLayout.isRefreshing()) {
      Logger.e("restUi");
      swipeLayout.setRefreshing(false);
    }
  }
```

还想owner 公开一个 判断是否 正在加载状态 的方法。像`SwipeRefreshLayout` 那样

**Comment by CymChad** [comment]
通常不是加载完了就关闭了吗？加载时间是你来控制的。

**Comment by wjehovah** [comment]
@CymChad 您好 我是请求完毕后，自动回调 关闭 刷新或者加载 view 的。这样就省去每次 手动调用了

**Comment by wjehovah** [comment]
> 自定义的加载失败尾部errorFooterView添加如下代码：
errorFooterView.setOnClickListener(view -> {
adapter.removeFooterView(errorFooterView);
adapter.openLoadMore(true);
});
在请求失败的回调函数调用adapter.addFooterView(errorFooterView).


@ChadCym 这样再次下拉刷新，之后 loadMore 会一直卡在loading

**Comment by CymChad** [comment]
@wjehovah 首先触发加载更多的函数的时候就【显示正在加载】请求后自动回调，只有两种结果一是有更多数据二是没有数据了，这个时候你都要调用notifyDataChangedAfterLoadMore方法呀，调用这个方法就是【关闭了正在加载】了呀。

**Comment by CymChad** [comment]
@wjehovah 你的版本号是？

**Comment by CymChad** [comment]
下拉刷新的时候，你设置数据是用的setNewData吗？

**Comment by shichaohui** [comment]
@wjehovah 下拉刷新后footerView添加或者删除失败的问题在1.9.7版本已经解决了，请更新版本。

**Comment by shichaohui** [comment]
@wjehovah sorry，上面的回复解决的不是一直loading的问题，我刚刚也遇到了一直loading的问题，解决方法是在添加errorFooterView的时候调用notifyDataChangedAfterLoadMore(false);这句代码。因为不调用这句代码的话，adapter中会一直维持着loading状态，导致下次进入的时候不会执行加载的监听。

**Comment by wjehovah** [comment]
@shichaohui 嗯谢谢，我也是这样解决的。

**Comment by sjw903** [comment]
是啊，而且再次加载的时候，这个也不会消失，这个如果能放出来，供大家调用就好了！
