### ISSUE TITLE
请问如何使用pull to refresh?

### ISSUE THREAD

**Issue by ohpoloha** [CymChad/BaseRecyclerViewAdapterHelper#1931]
你好, 程式码还有文档裡面我都找不到如何使用pull to refresh. 根据讨论区看起来像是支援的, 就是SwipeRefreshLayout的效果, 可是请问要如何使用呢? 根据[这边的例子](https://github.com/AllenCoder/BRVAH_kotlin/blob/159de4ffe9eab8d11ab645e29876b4268b48cf65/app/src/main/java/com/allen/kotlinapp/PullToRefreshUseActivity.kt)看起来像是要自己写?

**Comment by AllenCoder** [comment]
下拉刷新，需要自己配合第三方的下拉刷新框架或者自己扩展实现，本库没有耦合下拉部分的功能

**Comment by ohpoloha** [comment]
了解, 这样我就放心了, 谢谢
