### ISSUE TITLE
重写了onCreateViewHolder方法后，源码BaseViewHolder里面的adapter为空

### ISSUE THREAD

**Issue by DebugZeng** [CymChad/BaseRecyclerViewAdapterHelper#1937]
重写了onCreateViewHolder方法后，我自己定义了ViewHolder，没有走super.onCreateViewHolder(parent, viewType)，然后当我调用了adapter.setOnItemChildClickListener，然后报错了BaseViewHolder里面的adapter为空

**Comment by CymChad** [comment]
嗯 是的，因为super.onCreateViewHolder(parent, viewType)里面写了绑定点击事件的方法

**Comment by DebugZeng** [comment]
这样的话那我只能通过其他方法设置点击事件，，就没法在activity里面adapter.setOnItemChildClickListener这样使用了呢，这个问题以后会解决吗
