### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.addAll(java.util.Collection)' on a null object reference

### ISSUE THREAD

**Issue by HardyHaclke** [CymChad/BaseRecyclerViewAdapterHelper#194]
![Uploading 4CX51N)BTI_1C9T~IQ[@$YF.png…]()
在fragment中下拉加载更多，显示正在加载中，然后点击button返回activity会出现这样的错误

**Comment by xueyaolive** [comment]
请问你是在回调过程中，没有进行isAdd()判断，如果此时fragment已经被destryView了，你又去找这个fragment的子view赋值什么的，自然就NullPointerException了

**Comment by HardyHaclke** [comment]
感谢大神指教，在下新人一枚
