### ISSUE TITLE
在Viewpager 中 Fragment 使用时，如果Fragment 被重建后，状态的保存问题

### ISSUE THREAD

**Issue by kuanMingLi** [CymChad/BaseRecyclerViewAdapterHelper#1940]
在ViewPager 中，Fragment view被销毁，然后重建的时候，有bug。如下面的代码

```
 private CourseItemAdapter mAdapter;

```

在 onCreate()中初始化

```
if(mAdapter == null){
  mAdapter = new CourseItemAdapter ();
}
```
在onViewCreated（）中使用

```
  mAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                mPresenter.loadMore(index,PAGE_SIZE);
            }
        }, recyclerView);
////其它代码
```
上面导致，滑动到底部的时候，显示的是 处于“加载中状态..”，不能够下拉加载更多

如果在
在onViewCreated（）中这样使用

```
 mAdapter = new CourseItemAdapter ();
  mAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                mPresenter.loadMore(index,PAGE_SIZE);
            }
        }, recyclerView);

////其它代码

```
那么就是正常的。

上面的问题该如何解决？

**Comment by kuanMingLi** [comment]
我发现，在下面的方法中，并没有考虑 到 Fragment  view 多次重建的情形。
 public void setOnLoadMoreListener(RequestLoadMoreListener requestLoadMoreListener, RecyclerView recyclerView) {
        openLoadMore(requestLoadMoreListener);
        _**if (getRecyclerView() == null) {
            setRecyclerView(recyclerView);
        }**_
    }
如果使用
````
  @Deprecated
    public void setOnLoadMoreListener(RequestLoadMoreListener requestLoadMoreListener) {
        openLoadMore(requestLoadMoreListener);
    }
`````
不会出现问题

**Comment by CymChad** [comment]
Fragment 缓冲问题。adapter是在Fragment之下的。

**Comment by kuanMingLi** [comment]
在Fragment 的多次销毁，重建中，View 会被销毁，重建，但是为了 性能或其它考虑，Adapter 则会保留，到时Adapter 中 的RecycleView  对象改变了。这种情况有没有考虑

**Comment by Angelina-Y** [comment]
在Viewpager 中 Fragment 使用时，如果Fragment 被重建后，状态的保存问题
这个问题是Fragment中有对应的List<String> data;数据重复问题
目前已经解决，这个准备做给Demo进行验证
