### ISSUE TITLE
空布局高度

### ISSUE THREAD

**Issue by AIlll** [CymChad/BaseRecyclerViewAdapterHelper#1941]
设置空布局高度失效，没有全屏。rv和空布局都是match_parent

**Comment by AllenCoder** [comment]
设置EmptyView的布局参数  

```
final LayoutParams layoutParams = new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
     
           
mEmptyLayout.setLayoutParams(layoutParams);
```

**Comment by AIlll** [comment]
@AllenCoder 在什么时候设置布局参数，我设置了还是没有用

**Comment by AllenCoder** [comment]
正常模式下，如果emptyView的布局参数设置了 
```
        android:layout_width="match_parent"
        android:layout_height="match_parent"
```
就不需要任何处理了，建议参考demo  的EmptyViewUseActivity

**Comment by AIlll** [comment]
@AllenCoder 我看了demo也没有什么特别的，全都设置了match_parent啊，可就是不行

**Comment by 2318423730** [comment]
我也遇到了，用了其他人封装的RecycleView来做滑动删除，空布局高度没有充满

**Comment by AllenCoder** [comment]
第三方封装的recyclerview可能有些计算高度第三方开发者处理的，如有需要，可向第三方recyclerview开发者反馈

**Comment by LiHexiang** [comment]
我用原生的为什么也不行啊

**Comment by slimvan** [comment]
@LiHexiang 看看你RecyclerView的高度是不是写的wrap_content
