### ISSUE TITLE
请问我怎么点击一个item改变其他item

### ISSUE THREAD

**Issue by watermelonJun** [CymChad/BaseRecyclerViewAdapterHelper#1943]
比如 有6个数据 我点了2 就会有一个勾  我再点3  怎么把其他的item的勾去掉

**Comment by AllenCoder** [comment]
点击触发之后，保存点击的position ，然后修改数据层model ,model 存储item的选中和未选中的状态，然后通知适配器刷新

**Comment by watermelonJun** [comment]
我是用的循环解决的  请问跟你说的方法比起来缺点是什么 求教
int layoutPosition = helper.getLayoutPosition();
                    for (int i = 0; i < obj.size(); i++) {
                        if (i == layoutPosition) {
                            ImageView iv = (ImageView) getViewByPosition(familyMemberList, layoutPosition, R.id.iv_check_yes);
                            int visibility = iv.getVisibility();
                            if (visibility == View.VISIBLE) {
                                iv.setVisibility(View.GONE);
                            } else {
                                iv.setVisibility(View.VISIBLE);
                            }
                        } else {
                            ImageView iv = (ImageView) getViewByPosition(familyMemberList, i, R.id.iv_check_yes);
                            iv.setVisibility(View.GONE);
                        }
                    }

**Comment by AllenCoder** [comment]
原理上差不多，都是通过循环更新标记当前的state ，然后通知视图刷新显示对应的state 。
