### ISSUE TITLE
想问下关于点击子控件的方法

### ISSUE THREAD

**Issue by guoxinxin** [CymChad/BaseRecyclerViewAdapterHelper#1946]
使用新版本，不过处理子空间的点击事件的时候遇到错误，没有看到文档中写的那个方法，能否更新下文档？感觉文档中写的方法，在使用的版本中没有，谢谢（使用的版本是2.9.30）

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister)
