### ISSUE TITLE
可以针对不同的itemType 使用不同的动画吗？

### ISSUE THREAD

**Issue by pdog18** [CymChad/BaseRecyclerViewAdapterHelper#1948]
现在有三种`type`
* left 
* middle
* right  

我期望
`left` --> `SLIDEIN_LEFT`动画
`middle` -->`SCALEIN`动画
`right` --> `SLIDEIN_RIGHT`动画

**Comment by AllenCoder** [comment]
可以通过自定义 item的viewholder 控制 item的动画播放规则
