### ISSUE TITLE
HeaderView 和 EmptyView同时显示，EmptyView无法设置占据屏幕剩余全部高度

### ISSUE THREAD

**Issue by wangyeming** [CymChad/BaseRecyclerViewAdapterHelper#195]
谢谢你的开源项目，我在使用中有一个问题，首先我的LayoutManager是最普通的LinearLayoutManager，比如我希望数据为空时，HeaderView和EmptyView同时显示，EmptyView的高度应该占据屏幕剩余全部高度，即layout_weight = 1，HeaderView高度自适应。

然而我很难实现这种布局，如果EmptyView的高度设置为match_parent的话，HeaderView + EmptyView的高度之和超过了一屏，虽然我可以通过把HeaderView写在EmptyView内部这样实现，但是代码冗余。

P.S. 我想到了一种不优雅的实现方式，将EmptyView写在HeaderView内部，有数据时hide，无数据时show，不过希望BaseQuickAdapter能提供一个接口方法，指定EmptyView和HeaderView/FooterView同时展示时，高度为屏幕剩余全部高度，谢谢～

**Comment by CymChad** [comment]
收到，验证后给你回复

**Comment by AllenCoder** [comment]
headView 和 emptView 同时显示 ，只需要重写BaseQuickAdapter 的 setEmptView 即可 
      @Override
    public void setEmptyView(View emptyView) {
        super.setEmptyView(true,true,emptyView);
    }

**Comment by CymChad** [comment]
我的建议是你可以通过获取屏幕的高度减去header的高度然后设置EmptView的高度。
