### ISSUE TITLE
多级联动模式下 ,设置reverseLayout为true,item挂载异常

### ISSUE THREAD

**Issue by mudao** [CymChad/BaseRecyclerViewAdapterHelper#1950]
多级联动模式下 ,RecyclerView设置setLayoutManager的reverseLayout为true,item挂载异常.代码如下
` mRecyclerView.setLayoutManager(new LinearLayoutManager(getContext(),LinearLayoutManager.VERTICAL,true));`
按照我的意思只是根item倒序显示,子item依旧挂载在根item下.而现在显示的就错乱了.

**Comment by elfman** [comment]
能否给个demo或图片展示下是怎样错乱的？
