### ISSUE TITLE
请问一下,RecyclerView嵌套RecyclerView,快速滑动报错是怎么回事?

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#1951]
报这个异常: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
我也在百度搜索过,还没有解决.item的RecyclerView设置的是水平滑动的RecyclerView,当我水平滑动第一个item的时候正常,当我滑动再次滑动其他item的RecyclerView就报这个异常了,请问怎么解决?多谢解答!

**Comment by elfman** [comment]
@roybill 这个应该是你代码问题，与本库无关，请检查你的代码。你要我们帮忙解决请贴下你的代码，以及你尝试过的解决方法。

你这错误可以参考下[这个下面问题的答案](https://stackoverflow.com/questions/28071349/the-specified-child-already-has-a-parent-you-must-call-removeview-on-the-chil)
