### ISSUE TITLE
setNewData 后 调用 expandAll 无效，使用的BaseMultiItemQuickAdapter

### ISSUE THREAD

**Issue by xinyangcuncun** [CymChad/BaseRecyclerViewAdapterHelper#1952]

**Comment by elfman** [comment]
能否贴下你的代码？

**Comment by xinyangcuncun** [comment]
adapter.setNewData(data);
            adapter.notifyDataSetChanged();
            adapter.expandAll();

原本展开的，走到上面的代码会闭合，这里的Adapter 加了一个头。

**Comment by elfman** [comment]
我这里测试并没有出现你描述的问题，替换后列表已经展开了

**Comment by Bleach1** [comment]
出现同样问题
