### ISSUE TITLE
请教一个RecyclerView嵌套的问题

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#1953]
父RecyclerView是垂直滑动的,item中嵌套了水平滑动的RecyclerView,当我水平滑动父RecyclerView的第一条item的RecyclerView时正常,但是此时我迅速水平滑动第二条item的RecyclerView时就报错了:java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.,我百度找了也还没解决,知道的麻烦提供一下思路,谢谢!

**Comment by AllenCoder** [comment]
```
adapter的 
view 试下这种办法 

View view = LayoutInflater.from(context).inflate(R.layout.rv_detail, parent,false);
```

**Comment by roybill** [comment]
谢谢!我试过这个方法,不行哦,我现在把item的RecyclerView的点击事件放到父RecyclerView的Adapter内就解决了,但是这样感觉很不雅,应该还有更好的解决方法



roybill@163.com
 
发件人： Allen
发送时间： 2018-01-23 18:12
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： roybill; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请教一个RecyclerView嵌套的问题 (#1953)
adapter的 
view 试下这种办法 
View view = LayoutInflater.from(context).inflate(R.layout.rv_detail, parent,false);

**Comment by 1109993488** [comment]
最好提供demo或代码
