### ISSUE TITLE
碰到一个RecycleView嵌套RecycleView，内部RecycleView只显示一条数据的问题

### ISSUE THREAD

**Issue by Arms-merchants** [CymChad/BaseRecyclerViewAdapterHelper#1956]
当前项目使用的版本号是2.9.12，这个展示是正常的，但是更新到28以上的版本后，嵌套显示就会出现问题

**Comment by AllenCoder** [comment]
测试一下 最新版本 2.9.34

另外。28 指的是 sdk 28? 还是 targetVersion  = 28 ?提供详细出错配置及复现Demo
