### ISSUE TITLE
RecyclerView刷新数据闪屏问题

### ISSUE THREAD

**Issue by VincentYD** [CymChad/BaseRecyclerViewAdapterHelper#1957]
![a](https://user-images.githubusercontent.com/31061813/35314883-0fadcb2e-0104-11e8-9f10-2ff4374ce055.png)
点击TabLayout标签请求网络后通过adapter.setNewData()刷新整个列表数据,
当底部LinearLayout 一直VISIBILE 的时候,点击tab设置数据不会出现闪屏问题
如果在mTabLayout.addOnTabSelectedListener中设置点击标签隐藏LinearLayout (GONE),然后请求网络后设置adapter.setNewData()刷新列表数据,后设置LinearLayout (VISIBILE )就会出现闪屏的情况

targetSdkVersion 22
compileSdkVersion 26
minSdkVersion 16
helper版本 2.9.30

**Comment by 1109993488** [comment]
你可以在demo中试下，如果还出现闪屏的话最好提供个demo方便我们解决，这种情况一般都是别的原因造成的
