### ISSUE TITLE
.isExpanded()；当有三级菜单的时候  三级菜单为空的时候  这个值也是在true   在历史版本是false.

### ISSUE THREAD

**Issue by AngelBo** [CymChad/BaseRecyclerViewAdapterHelper#1959]

**Comment by elfman** [comment]
@AngelBo 相关部分代码近期都没有做过修改，你指的是哪个版本？你确定是本库的问题？

**Comment by AngelBo** [comment]
是的  最新版的问题   我又改回到2.9.13版本去了

**Comment by AngelBo** [comment]
我有三级菜单 一开始三级菜单都是空的   expandall 把三级菜单的isExpanded()设置为true了，其实我三级菜单都是没有任何对象的 完全为null  只有点击二级菜单按钮时候去加载 ，导致需要点击三次  在历史版本就不会

**Comment by AngelBo** [comment]
![image](https://user-images.githubusercontent.com/13344413/35367073-7732586a-01b7-11e8-8020-e7a5a06bcc3a.png)

**Comment by elfman** [comment]
查了下log，是在这个commit https://github.com/CymChad/BaseRecyclerViewAdapterHelper/commit/08935fe29eb7696ca7e102b0707972e48d404479 里修改的，是为了修复bug，当没有子项时，调用`expandAll`依然会将其设置为`expanded`

**Comment by AngelBo** [comment]
但是那样不合乎逻辑呀  这个问题的话  没有子布局 那子布局怎么可以是展开的呢？

**Comment by elfman** [comment]
它是一个实现`Expandable`接口的对象，不管有没有子项，它都是可以展开的，我是这样理解的，至于展开后是什么样，我不管。

**Comment by AngelBo** [comment]
好的 那这样的话就像相当于模拟一个对象进去了
