### ISSUE TITLE
section headers这种方式加载更多的时候数量怎么控制???

### ISSUE THREAD

**Issue by bobingxin** [CymChad/BaseRecyclerViewAdapterHelper#196]
一般是根据header的量来加载更多了，不知道怎么解决？

**Comment by CymChad** [comment]
通过pagesize来判断是否加载更多的，如果当前数据量超过pageSize的话就加载更多了

**Comment by jituijiaqiezi** [comment]
我做的时候，因为有些数据是必须将获取的数据先删除的，所以我每次都要主动设置大小，否则会无法再次加载

**Comment by CymChad** [comment]
原理和普通的一样。
