### ISSUE TITLE
示例代码可以加上MultipleItem，RecyclerView嵌套RecyclerView的情况吗？

### ISSUE THREAD

**Issue by MariShunxiang** [CymChad/BaseRecyclerViewAdapterHelper#1961]
示例代码可以加上MultipleItem，RecyclerView嵌套RecyclerView的情况吗？

**Comment by elfman** [comment]
@MariShunxiang RecyclerView互相嵌套的情况并不属于本库的内容，并不打算专门添加这种样例，网上很多关于recyclerview嵌套的文章，请自行查找学习
