### ISSUE TITLE
三级折叠目录，怎么在Activity点击事件外拿到第三级的控件

### ISSUE THREAD

**Issue by wapchief** [CymChad/BaseRecyclerViewAdapterHelper#1962]
有这样一个需求，类似慕课网的课程目录那样，
只有子目录才可以点击播放视频，
点击之后字体会变成正在播放的颜色，同时其它颜色置成默认。

现在的思路是在Activity中监听播放状态，当播放完成发送广播，自动播放下一个课程，同时上一个item颜色置为默认，当前item自动更改颜色。

我尝试用下面的方法获取，并没有获取到，position是我在遍历数据的时候保存的。
`        TextView textView = (TextView) mAdapter.getViewByPosition(mClassListRv,i, R.id.item_fragment_class2_title);
`
但是获取到的控件是null，请问有其它实现的方法或者思路吗

**Comment by elfman** [comment]
View的position不建议保存，当用户展开或折叠view时，position是会发生变化的。建议保存对应的item，在需要时再通过item获取position，再获取对应的view
