### ISSUE TITLE
数组角标越界异常

### ISSUE THREAD

**Issue by yy-Kevin** [CymChad/BaseRecyclerViewAdapterHelper#1965]
BaseMultiItemQuickAdapter 从一级列表 打开二级列表  偶尔报，数组角标越界异常，方法如下：
int pos = holder.getAdapterPosition();
collapse(pos);

**Comment by elfman** [comment]
请贴下具体Log，是库中哪一行出错

**Comment by yy-Kevin** [comment]
我上传图片失败，具体到(BaseQuickAdapter.java:611)，(BaseQuickAdapter.java:1817)，(BaseQuickAdapter.java:1762)，(BaseQuickAdapter.java:1787)

**Comment by elfman** [comment]
请贴原始的Log

**Comment by yy-Kevin** [comment]
![error](https://user-images.githubusercontent.com/23628394/35375659-d091cc4e-01e2-11e8-978b-97da0d2dafc9.png)

**Comment by elfman** [comment]
这个你应该考虑下你为啥传了个`-1`过去
