### ISSUE TITLE
请教一个用BRVAH获取到IjkVideoView后在RecyclerView的item播放的问题

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#1967]
我点击RecyclerView任意一个item的播放按钮,始终都是第一个item播放,请问这个该怎么解决?视频播放用的是IjkPlayer,Adapter用的是BRVAH.
以下是继承BaseQuickAdapter的类:
public class HomeAdapter extends BaseQuickAdapter<HomeListBean, BaseViewHolder> {

    private Context mContext;

    public HomeAdapter(int layoutResId, @Nullable List<HomeListBean> data, Context context) {
        super(layoutResId, data);
        this.mContext = context;
    }

    @Override
    protected void convert(BaseViewHolder helper, HomeListBean item) {
        helper.setText(R.id.tv_home_item_title, item.getTvHomeItemTitle())
                .setText(R.id.btn_game_type, item.getBtnGameType())
                .setText(R.id.tv_type, item.getTvType())
                .setText(R.id.tv_year_type, item.getTvYearType())
                .setText(R.id.tv_video_count, item.getTvVideoCount())
                .addOnClickListener(R.id.play_icon)
                .getView(R.id.video_view);//为自定义View的情况或ViewGroup的情况
        IjkVideoView ijkVideoView = helper.getView(R.id.video_view);//视频播放的View
        Glide.with(mContext).load(item.getImgUrl()).crossFade().placeholder(R.mipmap.temp_channel_item_image).into((ImageView) helper.getView(R.id.iv_trumb));
    }

}

**Comment by CymChad** [comment]
1.点击事件里面去获取具体的控件而不是convert。
2.通过实体类的属性来控制视频的播放。
