### ISSUE TITLE
Expandable item not collapse previous one

### ISSUE THREAD

**Issue by AravinthSri** [CymChad/BaseRecyclerViewAdapterHelper#1969]
i used one variable to store last clicked position when click new expandable item  try to close previous one but when new expandable appear means entier adapter position changed 

[No Expand Means]  Adapter Position

Header Item 1 -------------------------> 0
Header Item 2 -------------------------> 1
Header Item 3 -------------------------> 2
Header Item 4 -------------------------> 3
Header Item 5 -------------------------> 4

Expandable Adapter Position 

Once Expand Means Entire Adapter Position Changed Like This

Header Item 1 -------------------------> 0
Header Item 2 -------------------------> 1
--H1 Sub Item1  -----------------> 2
--H1 Sub Item2  -----------------> 3
--H1 Sub Item3  -----------------> 4
Header Item 3 -------------------------> 5
Header Item 4 -------------------------> 6
Header Item 5 -------------------------> 7

so adapter position changed entirely so what can i do kindly help me to get....

**Comment by elfman** [comment]
I have told you to store the clicked item instead of its position in [this issue](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1924#issuecomment-360689532), why do you insist on using the position?
