### ISSUE TITLE
adapter添加header和empty，设置显示empty时不显示header，数据为空却显示header不显示empty

### ISSUE THREAD

**Issue by wangyeming** [CymChad/BaseRecyclerViewAdapterHelper#197]
如题
![2016-07-30 21-52-50](https://cloud.githubusercontent.com/assets/8231644/17270885/fd610130-569f-11e6-8c29-b5c8945473e0.png)
这是demo的代码，我添加一行 addHeaderView，结果显示异常，如下图
![245730425](https://cloud.githubusercontent.com/assets/8231644/17270905/43d1e224-56a0-11e6-90a5-97e1d14f92dc.jpg)
只显示header，却不显示EmptyView

**Comment by CymChad** [comment]
收到，验证后给你回复

**Comment by AllenCoder** [comment]
应该重写BaseQuickAdapter 的 
    @Override
    public void setEmptyView(View emptyView) {
        super.setEmptyView(true,true,emptyView);
    },
你是否处理过呢？

**Comment by wangyeming** [comment]
@AllenCoder  然而你代码的含义你确定理解了吗？setEmptyView(true,true,emptyView) 表示同时展示header，empty，footer，然而我只希望展示empty

**Comment by CymChad** [comment]
你可以不添加header view

**Comment by CymChad** [comment]
根据数据size来判断加不加head。

**Comment by wangyeming** [comment]
......好吧，既然你关了，我也无话可说，但问题依然存在，虽然我可以手动removeHeader，但这不是个优雅的解决方式

**Comment by CymChad** [comment]
内部代码原理是，有header就显示header，有header不会被认为是空，所以不会显示EmptyView。

**Comment by Puppy-Love** [comment]
@wangyeming 嗯 正解，设置true 就可以empty 和footer 或者head都显示了
