### ISSUE TITLE
item动画依次执行，按照简书上的例子有兼容问题，测试7.1无效，5.1有效

### ISSUE THREAD

**Issue by 287138531** [CymChad/BaseRecyclerViewAdapterHelper#1970]
但是如果需要依次执行动画可以重写startAnim让第一个屏幕的item动画延迟执行即可。

@Override
    protected void startAnim(Animator anim, int index) {
        super.startAnim(anim, index);
        if (index < count)
        anim.setStartDelay(index * 150);
    }

**Comment by AllenCoder** [comment]
确认是动画bug ,暂时猜测跟系统有关，正在寻找解决方案

**Comment by fddlpz** [comment]
不知道有解决方案没有

**Comment by AllenCoder** [comment]
暂时解决办法是手动定义anim,根据不同版本调整anim的属性和加载方案
