### ISSUE TITLE
setNewData出现闪屏

### ISSUE THREAD

**Issue by wlmxj** [CymChad/BaseRecyclerViewAdapterHelper#1972]
不设置动画就出现，设置了openLoadAnimation 就没有了，感觉是动画这的问题，自己写的apdater没出现闪屏，不知道怎么搞了

**Comment by CymChad** [comment]
你把rv的自带动画设置null试试。

**Comment by playscforever** [comment]
@CymChad @wlmxj 自带的设置为null也没用好像
