### ISSUE TITLE
两个手指同时点击两个item，会多次响应

### ISSUE THREAD

**Issue by yhzhan1002** [CymChad/BaseRecyclerViewAdapterHelper#1974]
在SectionUseActivity界面两个手指同时点击item，会相应响应两次；同时点击多个item时，会相应响应多次。
个人认为应该只响应一次

**Comment by AllenCoder** [comment]
事件响应是基于 view的OnClickListener接口的回调完成的，如果觉得响应过快，可在onClickListener的回调里面做 消抖处理，对于多次的回调，只触发一次  Rxjava 的.throttleFirst(1, TimeUnit.SECONDS) 操作符 ，‘
或者自己判断拦截 重复的响应
