### ISSUE TITLE
[树形列表] 怎么样刷新数据的同时保持展开的状态

### ISSUE THREAD

**Issue by NutBear** [CymChad/BaseRecyclerViewAdapterHelper#1975]
有解决思路吗 因为树形列表使用的是MultiItemEntity

**Comment by NutBear** [comment]
@CymChad 可以写个例子吗 我需要保存状态并刷新数据 卡主了

**Comment by NutBear** [comment]
@CymChad 可以写个例子吗 我需要保存状态并刷新数据 思路卡住了

**Comment by shenbengit** [comment]
怎么可以快速解决这个问题？手动设置setExpanded(true)无效啊？

**Comment by gemgao** [comment]
@NutBear 解决了吗，同样的需求

**Comment by benben1** [comment]
这个问题目前有解吗？
