### ISSUE TITLE
初始化后加载数据问题

### ISSUE THREAD

**Issue by yedajiang44** [CymChad/BaseRecyclerViewAdapterHelper#1976]
看简书上看到如下说明
![image](https://user-images.githubusercontent.com/25813145/35471275-d39adbea-0392-11e8-8f5c-8b4b8c0adf8e.png)
那为什么我初始化后没有执行onLoadMoreRequested方法？
下面是我初始化的代码
![qq 20180127184946](https://user-images.githubusercontent.com/25813145/35471285-faaa7d8a-0392-11e8-8fce-713f52a71bf7.png)
目前必须要下拉刷新后才能用上拉加载，难道是我的姿势不对吗？

**Comment by CymChad** [comment]
只要set了监听默认就会进入毁掉，下拉刷新后会重新开启监听。具体你可以看看demo。你是不是调用了额外的方法。你可以单独写一个demo出来。

**Comment by yedajiang44** [comment]
@CymChad 我是用了依赖注入，会不会跟这个有关系？

**Comment by CymChad** [comment]
我没有试过依赖注入，你可以试试，用排除法找到最终问题所在。
