### ISSUE TITLE
关于设置空布局的问题。

### ISSUE THREAD

**Issue by nevermorever** [CymChad/BaseRecyclerViewAdapterHelper#1985]
请问setEmptyView方法是否 是在adapter没有数据的时候才生效呢？ 我这边测试的是只有adapter无数据，才会显示设置的空布局

相关代码：

 @BindView(R.id.recycler)
 RecyclerView mRecycler;

// retrofit的网络请求中
@Override
 public void onError(Throwable e) {
        mAdapter.setEmptyView(R.layout.error_view);
 }

**Comment by CymChad** [comment]
嗯 是的 没有数据才生效。如果你要显示错误布局，可以先把data设置为空
