### ISSUE TITLE
上拉刷新，一直显示正在加载中，不断调用刷新数据，调用loadMoreComplete无效

### ISSUE THREAD

**Issue by yigepang** [CymChad/BaseRecyclerViewAdapterHelper#1986]
不知是否是databinding的缘故，树形布局，expandall也无效，以下是我请求网络的数据，
  /**
     * 获取邀请列表
     *
     * @param
     */
    public void getInvitte(int mypage) {
        //todo 记得换token
        addDisposable(RetrofitManager.getInstance().create(HttpService.class).inviteList("b77be2dccc57d06a0124f3b348550b6a", String.valueOf(mypage))
                        .compose(RxSchedulers.<Result<InviteModel>>io_main(WorkListActivity.this)).
                                subscribeWith(new BaseSubscriber<InviteModel>() {
                                    @Override
                                    public void handlerSuccess(Result result, InviteModel info) {
                                        inviteModel = info;
                                        showContentView();
                                        //TODO 本地数据 记得装换
//                                        inviteModel = gson.fromJson(DebugUtil.getTestJson("test/invite", WorkListActivity.this), InviteModel.class);
                                        if (inviteModel.getList().size() == 0) {
                                            ToastUtils.showShort(WorkListActivity.this, "已无更多数据");
                                            endPage = page;
                                        } else {
                                            invitelist.addAll(inviteModel.getList());
                                            invateAdapter.notifyDataSetChanged();
                                            page++;
                                        }
                                        invateAdapter.loadMoreComplete();
                                        DebugUtil.error("显示", "" + invateAdapter.isLoading());
                                    }

                                    @Override
                                    public void handlerError(Result result, InviteModel info) {
                                        super.handlerError(result, info);
                                        ToastUtils.showShort(WorkListActivity.this, result.getMsg());
                                    }

                                    @Override
                                    public void onComplete() {
                                        super.onComplete();
                                        invateAdapter.loadMoreComplete();
                                    }

                                    @Override
                                    public void onError(Throwable t) {
                                        super.onError(t);
                                        ToastUtils.showShort(WorkListActivity.this, "网络错误");

                                    }
                                })
        );
    }
然后我再刷新监听中调用这个方法
 invateAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                bindingView.recyclview.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        getInvitte(page);
                        if (page == endPage) {
                            invateAdapter.loadMoreComplete();

                        } else {
                            getInvitte(page);
                        }
                    }
                }, 500);

            }
        }, bindingView.recyclview);
我并未嵌套scrollview什么的嵌套,父容器是linealayout,数据显示一直是在加载中，调用loadMoreComplete无效，我使用的是databinding

**Comment by 1109993488** [comment]
没有更多数据时调用的是`loadMoreEnd`

**Comment by yigepang** [comment]
loadMoreEnd调用后就无法再上拉，loadMoreComplete调用时结束本次上拉加载，我的情况是往上拉一次，数据就不断加载，上拉框一直显示加载中，无法回弹

**Comment by helloworld10010** [comment]
> loadMoreEnd调用后就无法再上拉，loadMoreComplete调用时结束本次上拉加载，我的情况是往上拉一次，数据就不断加载，上拉框一直显示加载中，无法回弹

我也这样。你弄好了吗

**Comment by helloworld10010** [comment]
数据因为未知原因 达不到total，请求也没数据了，奇怪
