### ISSUE TITLE
滑动显示删除等更多按钮

### ISSUE THREAD

**Issue by jituijiaqiezi** [CymChad/BaseRecyclerViewAdapterHelper#199]
现在滑动有删除的效果，但是要实现各种操作按钮怎么实现呢

**Comment by elfman** [comment]
这个不是adpater应该做的事，建议使用另一个开源项目[AndroidSwipeLayout](https://github.com/daimajia/AndroidSwipeLayout)

**Comment by jituijiaqiezi** [comment]
@elfman 谢谢
