### ISSUE TITLE
提一个建议，

### ISSUE THREAD

**Issue by liguangze** [CymChad/BaseRecyclerViewAdapterHelper#1992]
Demo每一个activity都是一个新的adapter，假如我既想刷新，又想动画，还有空的呢，这个怎么处理，这里有涉及到了3个adapter,我感觉万能的应该是一个adapter,然后用adapter来处理添加头，动画，刷新，等等，个人想法，不知道怎么样

**Comment by AllenCoder** [comment]
这些分散功能都是可以叠加使用的，分散成每个adapter是为了降低使用者首次使用门槛，可以很方便的实现自己想要的功能
