### ISSUE TITLE
瀑布流 删除数据的问题

### ISSUE THREAD

**Issue by xiaoyu0828** [CymChad/BaseRecyclerViewAdapterHelper#1993]
我用的瀑布流,3列,首先我在最前边插入了三个item,其实插入的这三个并没有展示出来,删掉第二个不可见的item,,发现列表抖动了一下,布局并没有变化,我觉得布局应该重新排列,不会传图

**Comment by AllenCoder** [comment]
没显示出来，有很多原因
1. 数据删除成功了，没有正常通知视图刷新
2.修改的数据和adapter绑定的数据不是同一个引用地址
3.layoutmanger设置使用不正确
