### ISSUE TITLE
版本：2.9.34，上拉加载时加载失败，提示“加载失败，点我重试”的问题

### ISSUE THREAD

**Issue by wcglws** [CymChad/BaseRecyclerViewAdapterHelper#1994]
demo中，上拉加载更多时，出现“加载失败，点我重试”，点击后，数据加载成功，这个点击事件是库中写好的么？能不能自己定义？

**Comment by AllenCoder** [comment]
点我重试是底部的view ,完全可以根据需求自定义

**Comment by wcglws** [comment]
demo是写了个类继承LoadMoreView，没看到点击事件如何加个底部view的
