### ISSUE TITLE
文档说的和代码不符呀 浪费时间 我都自己能整出一个了

### ISSUE THREAD

**Issue by Tanglonglong** [CymChad/BaseRecyclerViewAdapterHelper#1995]
文档说的和代码不符呀 浪费时间 我都自己能整出一个了  楼主先学学写文档吧！
我用的是多分组  问题是也不难 本来想你已经分装好了  用起来应该很快 结果让人很失望 
你文档说一下你的封装思路 看的也快 直接就贴个代码又和文档不符 太浪费时间了

**Comment by linsir6** [comment]
这只是一个开源项目，你又没付费，没理由要求那么多的。 你可以选择不用呀。

**Comment by linsir6** [comment]
当你发现 开源项目有问题的时候，你可以选择不用，或者提pr，而不是 在这里抱怨

**Comment by AllenCoder** [comment]
简书上的文档可能更新不及时，请以github 最新Demo 代码为准

**Comment by Tanglonglong** [comment]
我的问题 我用错类了  看错类名了  一直没发现！  不过文档写好一点 还是很有必要的
