### ISSUE TITLE
多布局问题

### ISSUE THREAD

**Issue by xlyasdasd** [CymChad/BaseRecyclerViewAdapterHelper#1996]
多布局可以使用不同的model嘛？几个model的数据都很庞大，并且没有相同点，如果耦合成一个model使用会使一个model变得特别难维护

**Comment by AutumnNight-SnowFingertips** [comment]
我也想问这个问题呢

**Comment by tangnuo** [comment]
多布局推荐使用：https://github.com/drakeet/MultiType
