### ISSUE TITLE
请问一下,如果convert方法内的第二个参数,比如HomeListBean item数据bean类里面有集合或者更多层级,该怎么获取层级内的数据呢?我这样拿会为空,比如item.getData();这样拿到的对象为空

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#1998]
@Override
    protected void convert(BaseViewHolder helper, HomeListBean item) {
        List<HomeListBean.DataBean> data = item.getData();//这里data为空

**Comment by AllenCoder** [comment]
检查你构造方法传入的数据结构， 应该是你传入的MultipleItem 本身没有处理好，才会导致 
List<HomeListBean.DataBean> data = item.getData();//这里data为空
