### ISSUE TITLE
添加Footer,点击失效

### ISSUE THREAD

**Issue by hezhipengzipp** [CymChad/BaseRecyclerViewAdapterHelper#1999]
mFooterView = LayoutInflater.from(mContext).inflate(R.layout.item_add_newaddress,null);
        mKlineTradeTypeAdapter = new WithDrawBTCAdapter(R.layout.item_btc_coin,coinUserAddressBeanList);
        mKlineTradeTypeAdapter.addFooterView(mFooterView);

**Comment by AllenCoder** [comment]
mFooterView 的点击事件是自己实现控制的。。

```
mFooterView .setOnClickListener(listener ->{// todo})
```
