### ISSUE TITLE
1.6.8有个app_name字符串资源的冲突问题

### ISSUE THREAD

**Issue by tsunamilx** [CymChad/BaseRecyclerViewAdapterHelper#20]
看截图
![image](https://cloud.githubusercontent.com/assets/6290337/15316143/3378abb0-1c4e-11e6-9419-2122a7508ca0.png)

在编译后生成的代码里有个 values-en 目录，里面的 values-en.xml 有个 app_name = Library
结果就是这个 app_name 把我原本的 app_name 给覆盖了，原因应该是他显式的指定了英语的values资源，优先级高于默认的英语资源（没有指定语言的资源）？

所以我 app 的名字就变成了 Library 。。。哭死。。。

我之前用的 1.6.1，没有这个问题，确认没有这个 values-en 目录，切回 1.6.8 就有了。
我没有去试 1.6.1 - 1.6.8 之间的版本。

**Comment by CymChad** [comment]
恩，好的，收到，我这就去把英文的那个app_name去除掉。

**Comment by CymChad** [comment]
改好了，我会和你说一下

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/15317164/e5127c44-1c52-11e6-942e-872f6d51a0fa.png)
你看一下这样配置一下会不会出现你那种情况

**Comment by tsunamilx** [comment]
还是会。
我试了下 1.6.7，没有这个问题。

**Comment by CymChad** [comment]
我重现了，因为你没有配置英文的，但是你的手机是在英文环境下，所以默认它就去找子工程的英文配置了。我这边把英文的名字删除掉吧。稍等几分钟

**Comment by tsunamilx** [comment]
没错，我手机是英文环境

**Comment by CymChad** [comment]
ok，那我删除掉那个英文的name，在给你打个版本。稍等片刻，真不好意思。

**Comment by tsunamilx** [comment]
哈哈效率好高

**Comment by CymChad** [comment]
必须的，为人民服务，如果你觉得好用的话，分享给其他人使用，帮助更多人~！

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.6.9'

**Comment by CymChad** [comment]
改好了，你先试试，好了和我说一下，我好 close 这个 issues

**Comment by tsunamilx** [comment]
app_name 是没有了，但是还有`<string name="loading">Loading...</string>`, 顺便都去掉呗

**Comment by CymChad** [comment]
英文系统也显示中文？我特意做的国际化。。。

**Comment by tsunamilx** [comment]
我觉得你的国际化方式不反对，一般默认都是英文的，然后添加其他语言，感觉你默认是中文，然后添加英语

**Comment by CymChad** [comment]
不是默认中文，这个是手机系统自适应的。

**Comment by tsunamilx** [comment]
不是，手机是根据系统语言自动去寻找对应的字符串资源，如果找不到，就加载默认的，也就是不带任何语言后缀的values目录。你要做国际化的话，一般都是默认的是英语，然后在添加zh的values-zh目录来支持中文。

**Comment by CymChad** [comment]
行，你方便提个pr吗？

**Comment by tsunamilx** [comment]
好，我看看先，不过可能要到这周末，最近在赶项目...

**Comment by CymChad** [comment]
恩 可以的，谢谢。
