### ISSUE TITLE
请问一个问题？

### ISSUE THREAD

**Issue by qzqs** [CymChad/BaseRecyclerViewAdapterHelper#2000]
为什么我加载网络失败的布局和空布局调用setEmptyView()方法都显示不出来？不知道该如何解决了，代码如下：
   errorView = inflater.inflate(R.layout.view_network_error, container, false);
  if (mAdapter.getItemCount() == 0) {//只有在第一次获取数据或者是刷新的时候调用
            mAdapter.setEmptyView(errorView );
}
但是就是显示不出来我的网络错误布局，太奇怪了。

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1503 

请详细参考Demo

**Comment by qzqs** [comment]
我是按照Demo来写的呀，作者能点一下思路么？实在是找不到解决方法了，才来提问的

**Comment by qzqs** [comment]
我是按照Demo来写的呀，作者能点一下思路么？实在是找不到解决方法了，才来提问的

**Comment by qzqs** [comment]
我是按照Demo来写的呀，作者能点一下思路么？实在是找不到解决方法了，才来提问的

**Comment by qzqs** [comment]
我是按照Demo来写的呀，作者能点一下思路么？实在是找不到解决方法了，才来提问的

**Comment by qzqs** [comment]
我是按照Demo来写的呀，作者能点一下思路么？实在是找不到解决方法了，才来提问的

**Comment by qzqs** [comment]
我是按照Demo来写的呀，作者能点一下思路么？实在是找不到解决方法了，才来提问的

**Comment by qzqs** [comment]
我是按照Demo来写的呀，作者能点一下思路么？实在是找不到解决方法了，才来提问的

**Comment by qzqs** [comment]
网络卡了..提交了那么多次...
