### ISSUE TITLE
AnimatorCompatHelper高版本不存在兼容

### ISSUE THREAD

**Issue by bill95** [CymChad/BaseRecyclerViewAdapterHelper#2006]
1 BaseRecyclerViewAdapterHelper:2.9.35
2 加载数据时默认加载动画
3 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support4/animation/AnimatorCompatHelper;
4 在低版本的v4包中包含AnimatorCompatHelper，但在26的高版本中被移除 
对高版本做一个兼容的新包

**Comment by Jibinghao** [comment]
同遇到这个问题@CymChad

**Comment by suliyea** [comment]
app  gradle增加配置, 亲测有效. 

    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                // Skip multidex because it follows a different versioning pattern.
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '26.1.0'
                }
            }
        }
    }
