### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by shuwenyouxi** [CymChad/BaseRecyclerViewAdapterHelper#2008]
BaseSectionQuickAdapter所对应的multitype应该用哪个Adapter<br>需求是多type的下拉刷新

**Comment by AllenCoder** [comment]
使用 BaseMultiItemQuickAdapter
参考[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java)
