### ISSUE TITLE
上拉加载的问题

### ISSUE THREAD

**Issue by wcglws** [CymChad/BaseRecyclerViewAdapterHelper#2010]
数据不满一页，会自动执行一次加载更多的动画，怎么解决？demo中也有这个问题，

**Comment by AllenCoder** [comment]
参考 
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1476](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1476)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1207](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1207)
