### ISSUE TITLE
getLayoutId()是如何使用的

### ISSUE THREAD

**Issue by idealcn** [CymChad/BaseRecyclerViewAdapterHelper#2011]
LoadMoreView.java这个类中的方法getLayoutId()是在哪里使用的

**Comment by AllenCoder** [comment]
自定义loadMoreView的布局 可以参考Demo [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/loadmore/CustomLoadMoreView.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/loadmore/CustomLoadMoreView.java)
