### ISSUE TITLE
使用Expandable 展开列表之后，再使用layoutManager的findViewByPosition返回空 #1977

### ISSUE THREAD

**Issue by wangqingnan** [CymChad/BaseRecyclerViewAdapterHelper#2016]

**Comment by elfman** [comment]
请贴出你的代码，最好给出个可复现的demo，仅凭这一句话描述无法知道是否是本库问题

**Comment by wangqingnan** [comment]
你好，我看了下你们出的demo试了下是没有问题的，我是在点击列表某一项，请求网络获取里面的subitem，调用 mAdapter.notifyDataSetChanged()刷新数据后才，再使用ayoutManager的findViewByPosition返回空的情况，我这边再看看是否是我这边的问题

**Comment by wangqingnan** [comment]
你好，我对demo的ExpandableActivity进行了改造重现了标题所述的情况

地址：https://github.com/wangqingnan/DemoTestNull/tree/master/app/src/main/java/com/allen/kotlinapp

全在ExpandableActivity里，另外，我怀疑是添加了head和foot导致的情况，不知道是不是这样

操作步骤：打开app，进入ExpandableActivity，点击第一个标题(This is 0th item in Level0)展开列表,然后下拉列表至最下方，点击叫test的button按钮，监听事件如下

 btnNext.setOnClickListener {
            // 这边item会返回null
            val item = manager.findViewByPosition(1)
            println(item)
}
