### ISSUE TITLE
横向的RecyclerView添加头部和尾部回出现独占一整行的情况

### ISSUE THREAD

**Issue by QiWenLV** [CymChad/BaseRecyclerViewAdapterHelper#2019]
![we_906xipy 3 q23h5sa](https://user-images.githubusercontent.com/25661932/36112557-0b68da0c-1065-11e8-9cce-555204431d44.png)
![9t95 2plo5 d q i 1g7 q](https://user-images.githubusercontent.com/25661932/36112558-0baa962c-1065-11e8-8f9c-b9d727c881b1.png)
![mddg 4_8zw2ww7ke4gfid q](https://user-images.githubusercontent.com/25661932/36112559-0c5fc09c-1065-11e8-9a01-cc811bf495df.png)

布局中的宽度均为wrap_content，头部和尾部都出现了独占一行的情况。
```
baseActorsAdapter.addFooterView(footer);
 rvActors.setLayoutManager(new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false));
```

**Comment by originzyf** [comment]
你解决了吗 我也遇到这个问题了

**Comment by Puppy-Love** [comment]
我也出现了这个问题，footer view 设置marginleft marginRight 没有做都是一行占满了

**Comment by originzyf** [comment]
你用多itemtype就可以了

**Comment by song234876** [comment]
你在横向布局的时候添加headerView的方法选择添加一个方向属性即可,默认是添加的竖向。同时设置头部局不独占一行。adapter.isHeaderViewAsFlow = true;   adapter.addHeaderView(headerView, 0, RecyclerView.HORIZONTAL)
