### ISSUE TITLE
加载更多

### ISSUE THREAD

**Issue by HardyHaclke** [CymChad/BaseRecyclerViewAdapterHelper#202]
求教：fragment中使用了RecyclerView加载更多的功能，所有item都加载完后，滑动RecyclerView，在滑动中点击button返回Activity，崩溃。错误如下图：
![error](https://cloud.githubusercontent.com/assets/17586147/17315769/03691fce-58a1-11e6-95c1-6ae0fe7d3417.png)

**Comment by elfman** [comment]
你是不是在这个过程中把Adapter里面的数据设置为null了？如果想清空数据，传一个空的List进去，现在版本传null会出错

**Comment by HardyHaclke** [comment]
恩，确实是设置为null了。
非常感谢！
