### ISSUE TITLE
click on one item , changes drawable in multiple item

### ISSUE THREAD

**Issue by gokrish6670** [CymChad/BaseRecyclerViewAdapterHelper#2020]
private void initAdapter() {
        List<String> list = Arrays.asList(skills);
        RegisterSkillAdapter aAdapter = new RegisterSkillAdapter(this, list);
        LinearLayoutManager linear = new LinearLayoutManager(this);
        linear.setOrientation(LinearLayoutManager.VERTICAL);
        topic_Recycler.setHasFixedSize(true);
        topic_Recycler.setLayoutManager(linear);
        topic_Recycler.setAdapter(aAdapter);
        aAdapter.setOnItemChildClickListener((baseQuickAdapter, view, i) -> {
            switch (view.getId()) {
                case R.id.skills:
                    TextView textSkills = (TextView) view;
                    if(!textSkills.isSelected()) {
                        textSkills.setSelected(true);
                        selectedString.add(list.get(i));
                        textSkills.setCompoundDrawablesWithIntrinsicBounds(0, 0, R.drawable.ic_check_black, 0);
                    } else {
                        textSkills.setSelected(false);
                        selectedString.remove(list.get(i));
                        textSkills.setCompoundDrawablesWithIntrinsicBounds(0, 0, R.drawable.ic_add_black, 0);
                    }
                    break;
                default:
                    break;
        }});
    }

public class RegisterSkillAdapter extends BaseQuickAdapter<String , BaseViewHolder> {
    public RegisterSkillAdapter(Context context, List<String> data) {
        super(R.layout.item_register_skills, data);
    }
    @Override
    protected void convert(BaseViewHolder helper, String result) {
        helper.setText(R.id.skills, result).addOnClickListener(R.id.skills);
    }
}

![ezgif com-optimize](https://user-images.githubusercontent.com/22348175/36533226-e744af58-17e8-11e8-9afe-c38396b8f2f9.gif)

**Comment by AllenCoder** [comment]
1. You should check your code .

2You should change like this. 
```

adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
               for(int i =0;i<list;i++){
                   if(i==position){
                       list.get(position).isSelected=true;
                   }else{
                         list.get(position).isSelected=false;
                   }
                    adapter.notifyDataSetChanged();
               }
            }
        });


@override
protected void convert(BaseViewHolder helper, Bean bean) {
    helper.setText(R.id.skills, bean.result).addOnClickListener(R.id.skills);
    if(!bean.isSelected()) {
        textSkills.setSelected(true);
        selectedString.add(list.get(i));
        textSkills.setCompoundDrawablesWithIntrinsicBounds(0, 0, R.drawable.ic_check_black, 0);
     } else {
        textSkills.setSelected(false);
        selectedString.remove(list.get(i));
        textSkills.setCompoundDrawablesWithIntrinsicBounds(0, 0, R.drawable.ic_add_black, 0);
    }

}
```
