### ISSUE TITLE
multiitem+databinding

### ISSUE THREAD

**Issue by shi1hh** [CymChad/BaseRecyclerViewAdapterHelper#2021]
有没有好的实践啊？？？没有找到例子

**Comment by AllenCoder** [comment]
结合demo两个  DataBindingUseAdapter和MultipleItemQuickAdapter

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DataBindingUseAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DataBindingUseAdapter.java)
