### ISSUE TITLE
设置gridmanager在没有数据的时候怎么才能显示一个默认的布局 

### ISSUE THREAD

**Issue by gaoxu19930112** [CymChad/BaseRecyclerViewAdapterHelper#2022]
当没有数据的时候显示一个添加照片的图片,有数据的时候就把这个添加照片的图片替换成对应数据的图片,并再该图片之后又加一个添加照片的图片,类似微信朋友圈发照片的功能,我重写了getitemcount方法,数据量+1,但是现在在没有数据还是不会走convert方法,无法显示添加照片的图标

**Comment by AllenCoder** [comment]
数据为空时，不会执行convert方法。可以采用空布局，空布局显示的内容就是你希望显示的默认内容。
