### ISSUE TITLE
NestedScrollView嵌套RecyclerView情况下onLoadMoreRequested会立即执行

### ISSUE THREAD

**Issue by xwc010** [CymChad/BaseRecyclerViewAdapterHelper#2023]
NestedScrollView嵌套RecyclerView情况下，创建BaseMultiItemQuickAdapter并赋值给RecyclerView时BaseMultiItemQuickAdapter设置的RequestLoadMoreListener 中的onLoadMoreRequested会被立即自动执行而不是等到滑动到底部，同时底部不显示loadmore提示语，显示的是Item布局的一部分

**Comment by xwc010** [comment]
feedAdapter = new YJLFeedAdapter(getActivity(), mFeeds);
        // 设置adapter
        mRecyclerView.setAdapter(feedAdapter);
        feedAdapter.setOnItemClickListener(createOnItemClickListener());
        feedAdapter.setOnItemChildClickListener(createOnItemChildClickListener());

        feedAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                getNextPageFeeds();
            }
        }, mRecyclerView);

**Comment by admingalery** [comment]
我也发现这个问题

**Comment by AllenCoder** [comment]
NestedScrollView 嵌套recyclerview会导致recylerview 一进来就默认全展开，就会执行加载更多的操作，一直加载完成所有数据，直至数据加载完毕
