### ISSUE TITLE
请教一个使用BRVAH,RecyclerView嵌套RecyclerView的问题

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2025]
能否直接在父RecyclerView的Adapter中设置子RecyclerView的Adapter?子RecyclerView的List数据如何添加呢?
父Adapter布局:
`public class ChannelAdapter extends BaseQuickAdapter<ChannelListBean, BaseViewHolder> implements BaseQuickAdapter.OnItemChildClickListener {
    private Context mContext;
    private ChannelItemAdapter itemAdapter;
    public ChannelAdapter(int layoutResId, @Nullable List<ChannelListBean> data, Context context) {
        super(layoutResId, data);
        mContext = context;
    }
    @Override
    protected void convert(BaseViewHolder helper, ChannelListBean item) {
        //可链式调用赋值
        helper.setText(R.id.tv_channel_item_title, item.getTitle())
                .setText(R.id.tv_game_video_count,item.getVideoCount())
                .addOnClickListener(R.id.tv_channel_item_title)
                .addOnClickListener(R.id.item_channel_recyclerview);//item内子控件需要点击事件,必须在父容器添加声明;
        RecyclerView itemRecyclerView = helper.getView(R.id.item_channel_recyclerview);
        itemRecyclerView.setLayoutManager(new GridLayoutManager(mContext, 2));
        //子item水平滚动
//        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(mContext);
//        linearLayoutManager.setOrientation(LinearLayoutManager.HORIZONTAL);
//        itemRecyclerView.setLayoutManager(linearLayoutManager);
        itemAdapter = new ChannelItemAdapter(R.layout.item_channel_items, getData());//TODO  子RecyclerView的Adapter
        itemRecyclerView.setAdapter(itemAdapter);//直接通过BaseQuickAdapter封装的getData获取数据
//        itemAdapter.addFooterView(View.inflate(mContext, R.layout.temp_footerview, null));//添加FooterView
        //获取当前条目position
        int position = helper.getLayoutPosition();
        //TODO:待优化,是否不应该写在这里
//        itemAdapter.setOnItemClickListener(this);
        this.setOnItemChildClickListener(this);
    }`

其他类中获取JSON数据:
` private void setSortGameData(String json) {
        //处于子线程
        Gson gson = new Gson();
        ChannelListBean channelListBean = gson.fromJson(json, ChannelListBean.class);
        List<ChannelListBean.DataBean> data = channelListBean.getData();
//        //RecyclerView的临时数据
        mDatas = new ArrayList<>();
        ChannelListBean bean;
        ChannelListBean.DataBean dataBean = null;
        for (int i = 0; i < data.size(); i++) {
            dataBean = data.get(i);
            String typeName = dataBean.getTypename();//item大标题
            int vtotal = dataBean.getVtotal();//item视频总个数
            bean = new ChannelListBean();
            bean.setTitle(typeName);
            bean.setVideoCount(vtotal + "");
            bean.setContent("1725年德玛西亚");
//            List<ChannelListBean.DataBean.ListBean> list = dataBean.getList();
            mDatas.add(bean);
        }

//        listDatas = dataBean.getList();//这样无法添加子RecyclerView的数据
//        ChannelListBean.DataBean.ListBean listBean;
//        for (int i = 0; i < listDatas.size(); i++) {
//            listBean=new ChannelListBean.DataBean.ListBean();
//            List<ChannelListBean.DataBean.ListBean.QualityBean> quality = listBean.getQuality();
//            listDatas.add(listBean);
//            mDatas.addAll();
//        }
        Message obtain = Message.obtain();
        obtain.what = SHOW_SUCCESS;
        mHandler.sendMessage(obtain);
    }`

**Comment by AllenCoder** [comment]
请参考Demo最新示例代码
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java)
```
package com.chad.baserecyclerviewadapterhelper.adapter; 
 
import android.support.v7.widget.LinearLayoutManager; 
import android.support.v7.widget.RecyclerView; 
import android.view.View;
import android.widget.Toast;
 
import com.chad.baserecyclerviewadapterhelper.R; 
import com.chad.baserecyclerviewadapterhelper.entity.ClickEntity; 
import com.chad.baserecyclerviewadapterhelper.util.Utils; 
import com.chad.library.adapter.base.BaseMultiItemQuickAdapter; 
import com.chad.library.adapter.base.BaseQuickAdapter; 
import com.chad.library.adapter.base.BaseViewHolder; 
import com.orhanobut.logger.Logger; 
 
import java.util.List;
 
/** 
 * 
 */ 
public class ItemClickAdapter extends BaseMultiItemQuickAdapter<ClickEntity, BaseViewHolder> implements BaseQuickAdapter.OnItemClickListener, BaseQuickAdapter.OnItemChildClickListener { 
    NestAdapter nestAdapter;
 
    public ItemClickAdapter(List<ClickEntity> data) {
        super(data);
        addItemType(ClickEntity.CLICK_ITEM_VIEW, R.layout.item_click_view);
        addItemType(ClickEntity.CLICK_ITEM_CHILD_VIEW, R.layout.item_click_childview);
        addItemType(ClickEntity.LONG_CLICK_ITEM_VIEW, R.layout.item_long_click_view);
        addItemType(ClickEntity.LONG_CLICK_ITEM_CHILD_VIEW, R.layout.item_long_click_childview);
        addItemType(ClickEntity.NEST_CLICK_ITEM_CHILD_VIEW, R.layout.item_nest_click);
 
    } 
 
 
    @Override 
    protected void convert(final BaseViewHolder helper, final ClickEntity item) {
        switch (helper.getItemViewType()) {
            case ClickEntity.CLICK_ITEM_VIEW: 
                helper.addOnClickListener(R.id.btn);
                break; 
            case ClickEntity.CLICK_ITEM_CHILD_VIEW: 
                helper.addOnClickListener(R.id.iv_num_reduce).addOnClickListener(R.id.iv_num_add)
                        .addOnLongClickListener(R.id.iv_num_reduce).addOnLongClickListener(R.id.iv_num_add);
                // set img data 
                break; 
            case ClickEntity.LONG_CLICK_ITEM_VIEW: 
                helper.addOnLongClickListener(R.id.btn);
                break; 
            case ClickEntity.LONG_CLICK_ITEM_CHILD_VIEW: 
                helper.addOnLongClickListener(R.id.iv_num_reduce).addOnLongClickListener(R.id.iv_num_add)
                        .addOnClickListener(R.id.iv_num_reduce).addOnClickListener(R.id.iv_num_add);
                break; 
            case ClickEntity.NEST_CLICK_ITEM_CHILD_VIEW: 
                helper.setNestView(R.id.item_click); // u can set nestview id
                final RecyclerView recyclerView = helper.getView(R.id.nest_list);
                recyclerView.setLayoutManager(new LinearLayoutManager(helper.itemView.getContext(), LinearLayoutManager.VERTICAL, false));
                recyclerView.setHasFixedSize(true);
 
                nestAdapter = new NestAdapter();
                nestAdapter.setOnItemClickListener(this);
                nestAdapter.setOnItemChildClickListener(this);
                recyclerView.setAdapter(nestAdapter);
                break; 
        } 
    } 
 
    @Override 
    public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
        Toast.makeText(Utils.getContext(), "childView click", Toast.LENGTH_SHORT).show();
    } 
 
    @Override 
    public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
        Logger.d("嵌套RecycleView item 收到: " + "点击了第 " + position + " 一次");
        Toast.makeText(Utils.getContext(), "嵌套RecycleView item 收到: " + "点击了第 " + position + " 一次", Toast.LENGTH_SHORT).show();
    } 
} 
```
