### ISSUE TITLE
请问为什么这样设置空布局不起作用呢?

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2026]
discoveryAdapter = new DiscoveryAdapter(R.layout.item_discovery, mDatas);
 View view = View.inflate(getActivity(), R.layout.empty_view, null);
  discoveryAdapter.setEmptyView(view);

**Comment by AllenCoder** [comment]
空布局只有在设置绑定的data为空时才会展示 。具体用法参考 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/EmptyViewUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/EmptyViewUseActivity.java)
