### ISSUE TITLE
请问使用BRVAH时,RecyclerView嵌套RecyclerView,子RecyclerView数据不对应怎么解决?

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2029]
//这里就一个类
public class ChannelAdapter extends BaseQuickAdapter<ChannelListBean, BaseViewHolder> implements BaseQuickAdapter.OnItemChildClickListener {

    private Context mContext;
    private ChannelItemAdapter itemAdapter;
    private static final String TAG = "ChannelAdapter";
    private List<ChannelListBean.DataBean.ListBean> mChannelItemData;

    public ChannelAdapter(int layoutResId, @Nullable List<ChannelListBean> data, Context context) {
        super(layoutResId, data);
        mContext = context;
    }

    @Override
    protected void convert(BaseViewHolder helper, ChannelListBean item) {
        //可链式调用赋值
        helper.setText(R.id.tv_channel_item_title, item.getTitle())
                .setText(R.id.tv_game_video_count, item.getVideoCount())
                .addOnClickListener(R.id.tv_channel_item_title)
                .addOnClickListener(R.id.item_channel_recyclerview);//item内子控件需要点击事件,必须在父容器添加声明;
        RecyclerView itemRecyclerView = helper.getView(R.id.item_channel_recyclerview);
        itemRecyclerView.setLayoutManager(new GridLayoutManager(mContext, 2));

        mChannelItemData = new ArrayList<>();
        List<ChannelListBean> data = getData();//直接通过BaseQuickAdapter封装的getData获取数据
        List<ChannelListBean.DataBean.ListBean> list = null;
        for (int i = 0; i < data.size(); i++) {
            ChannelListBean bean = data.get(i);
            List<ChannelListBean.DataBean> beanData = bean.getData();
            for (int j = 0; j < beanData.size(); j++) {
                ChannelListBean.DataBean dataBean = beanData.get(j);
                list = dataBean.getList();
//                for (int k = 0; k < list.size(); k++) {
//                    ChannelListBean.DataBean.ListBean listBean = list.get(k);
//                    String lenght = listBean.getLenght();
//                    listBean.setLenght(lenght);
//                    Log.d(TAG, "1741=   " + lenght);
//                    mChannelItemData.add(listBean);
//                }
                itemAdapter = new ChannelItemAdapter(R.layout.item_channel_items, list, mContext);//TODO  子RecyclerView的Adapter
                itemRecyclerView.setAdapter(itemAdapter);
            }
        }

//        for (int j = 0; j < list.size(); j++) {
//            ChannelListBean.DataBean.ListBean listBean = list.get(j);
//            String lenght = listBean.getLenght();
//            Log.d(TAG, "1739=   "+lenght);
//        }

//        for (int i = 0; i < list.size(); i++) {
//            ChannelListBean.DataBean.ListBean listBean = list.get(i);
//            String img = listBean.getImg();
//            listBean.setImg(img);
//            mChannelItemData.add(listBean);
//            itemAdapter = new ChannelItemAdapter(R.layout.item_channel_items, list, mContext);//TODO  子RecyclerView的Adapter
//            itemRecyclerView.setAdapter(itemAdapter);
//        }

        this.setOnItemChildClickListener(this);
    }

//    @Override//子item中RecyclerView的点击事件
//    public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
//        Intent toPlay = new Intent(mContext, VideoPlayActivity.class);
//        mContext.startActivity(toPlay);
//    }

    @Override//子item中标题和更多视频的点击事件
    public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
        if (view.getId() == R.id.tv_channel_item_title) {
            Intent toTopicPlay = new Intent(mContext, TopicPlayActivity.class);
            mContext.startActivity(toTopicPlay);
        }
    }
}

**Comment by AllenCoder** [comment]
数据不对应？是指position对应的位置不正确吗？ 
嵌套recyclerview感觉你的数据赋值有问题
```
    for (int i = 0; i < data.size(); i++) {
        ChannelListBean bean = data.get(i);
        List<ChannelListBean.DataBean> beanData = bean.getData();
        for (int j = 0; j < beanData.size(); j++) {
            ChannelListBean.DataBean dataBean = beanData.get(j);
            list = dataBean.getList();
```
请检查对应item的recyclerview的adapter的数据是否正确
可参考Demo  [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java)
