### ISSUE TITLE
加载更多

### ISSUE THREAD

**Issue by Ludejin** [CymChad/BaseRecyclerViewAdapterHelper#203]
设置15条数据一页（mAdapter.openLoadMore(Const.PAGE_SIZE, true);），加载2页但数据未完全加载，如果中途删除一条或多条，调用adapter的remove方法，然后再拉到底，不执行加载更多方法，不知道是不是当前不够15条数据了。

**Comment by CymChad** [comment]
看下你具体的使用代码

**Comment by CymChad** [comment]
你更新数据的方式是这样吗？adapter.notifyDataChangedAfterLoadMore(data,true);

**Comment by Ludejin** [comment]
是的，其他情况是正常的，就是删除后就出现了不能加载更多的情况，代码实现：
![image](https://cloud.githubusercontent.com/assets/10751355/17350703/74571276-595b-11e6-8a78-769dc613116b.png)

**Comment by CymChad** [comment]
你删除后是不是就走到了notifyDataChangedAfterLoadMoer（false）？

**Comment by Ludejin** [comment]
删除后没走那里，仅仅是调用adapter的remove 方法，具体实现：
![image](https://cloud.githubusercontent.com/assets/10751355/17350846/a52618d8-595c-11e6-9a7f-98a4ee7fe600.png)
![image](https://cloud.githubusercontent.com/assets/10751355/17350852/aff67168-595c-11e6-8fa6-befad942ae8b.png)

**Comment by CymChad** [comment]
最后一条就会调用上拉的回调。
private boolean isLoadMore() {
return mNextLoadEnable && pageSize != -1 && mRequestLoadMoreListener != null && mData.size() >= pageSize;
}

**Comment by Ludejin** [comment]
就是这里的问题了
![image](https://cloud.githubusercontent.com/assets/10751355/17351170/e977a04a-595e-11e6-97ea-8e2045b41dff.png)
因为我删除后，this.mData.size() >= this.pageSize;这个条件不成立，所以这算是个bug吧？

**Comment by CymChad** [comment]
但是这个只是限制第一页。后续你的data会累计，这个判断就不会影响了。

**Comment by Ludejin** [comment]
不，第n(n > 1)页也会的，因为可能删掉( (n - 1) * pageSize + 1) 条数据，这样还是会出现这种情况

**Comment by CymChad** [comment]
哦，对，我想想。

**Comment by CymChad** [comment]
我的设计的时候是这样思考的，不满一个屏幕还会有下一页吗？我把pageSize看做一页的数量。不知道你是否有好的建议？

**Comment by Ludejin** [comment]
不满一屏幕有可能会有下一页，暂时没有
用取模的方式， 余数大于0就true，如果删空了，就应该下拉刷新来重新加载数据
![image](https://cloud.githubusercontent.com/assets/10751355/17351329/2036f6b6-5960-11e6-969a-153feafe6a83.png)
因为我们这里可以自己设置了mNextLoadEnable，但是考虑考虑，这样也不算太合理

**Comment by Ludejin** [comment]
可不可以不满一屏幕就自动去加载更多的实现，
![image](https://cloud.githubusercontent.com/assets/10751355/17351480/79effcc4-5961-11e6-84f3-1dc05e97265f.png)
你还有这个条件，而我们一般如果是加载完所有数据都会：
![image](https://cloud.githubusercontent.com/assets/10751355/17351490/9d114442-5961-11e6-9d91-947dbc632c29.png)
将mNextLoadEnable设为false了，这样挺合理的。不知道有没有考虑不周的地方

**Comment by CymChad** [comment]
恩 我觉得只能价格按钮去触发重新开启上拉，pageSize设置成0，因为我考虑到，假设你第一页显示10条数据，你有下一页数据，但是你删除了8条数据，只有两条数据了，那么理论上是无法除非上拉的，就算能够让你触发上拉也是不合理的，因为没有一个应用不满足一屏幕的情况下还可以上拉加载更多的，所以就是加一个加载更多的按钮，按钮的事件就是开启加载更多吧pageSize改成0，这样就可以触发上拉加载更多的方法了，你觉得呢？

**Comment by CymChad** [comment]
这样也可以，你再调用一下设置pagesize的方法。

**Comment by Ludejin** [comment]
明哥，我刚刚clone下你的Demo测试了一下，可以直接去掉最后一个条件就可以了，我们也不需要重新设置pageSize，
当我们删到刚好一屏时，会调用
![image](https://cloud.githubusercontent.com/assets/10751355/17351626/e36831de-5962-11e6-8da5-40ee29b37c61.png)
而后在onBindViewHolder里也直接执行了加载更多，所以我觉得去掉最后一个条件就好了，如果数据不满一页，我们已经自己处理了mNextLoadEnable

**Comment by CymChad** [comment]
去掉肯定是可以的，那么PageSize就没用了，并且会出现一进来就会调用加载更多的监听，现在正在使用的开发者会出现问题的，因为通常都是滑到最后一条才去加载更多的，我想了一下可以加个标示去做这个判断。不改变现在的流程，支持你需要的效果，这样就两全其美了。

**Comment by CymChad** [comment]
我的改动要考虑到所有的开发者的体验，所以不能轻易改动现有的流程。

**Comment by Ludejin** [comment]
考虑到所有的开发者的体验这个是肯定要的，但是我调试过程中一进来是不会调用加载更多的监听的，只有到底部才会执行的，有可能是我忽略了你的某些实现，我再了解了解

**Comment by Ludejin** [comment]
你说的flag我觉得是不是可以用dataCount或者pageCount，现在一般的分页接口都会返回这两个参数之一，除非一些不好的接口，而且每次加载更多的时候我们都有在回调里面判断了，所以这个flag其实很多情况也是不需要的，你的Demo中TOTAL_COUNTER是写死的，有些出入，所以考虑多了点，我们删除数据库成功后，界面更新删除，再加载更多时，我们返回的dataCount或者pageCount也是会变的。

**Comment by CymChad** [comment]
在回调里面的判断我只是写了一个场景而已，具体的判断还是由开发者来判断的，比如你可以通过页数来判断，也可以通过一个flag来判断是否有没有下一页都可以，只不过是我demo的目的就是让大家明白notifyDataChangedAfterLoadMoer的用法

**Comment by CymChad** [comment]
我想到一个办法了，就是一开始你就把pagesize设置成0

**Comment by Ludejin** [comment]
那样其实pageSize在你的库内意义也是没有的，不过是在我这样实现的方式下没用，其他的没试过也不知道，这样我这个场景能够实现（说白了，在我的场景，跟删除最后一个条件是一样的）

**Comment by Ludejin** [comment]
![image](https://cloud.githubusercontent.com/assets/10751355/17388059/f226da6c-5a2b-11e6-9840-abfb7edf80de.png)
您这个第一个函数好像是没有意义的，要么应该在第一个加上this.pageSize = pageSize;

**Comment by CymChad** [comment]
恩，这是很早写的函数。我后续改一下，多谢提醒。

**Comment by CymChad** [comment]
pageSize设置成0就没含义了，对了，因为其他人不会设置成0，所以对其他人有含义，但是设置成0对你应该可以实现你要的作用。

**Comment by Ludejin** [comment]
这个我知道，我说的就是我的场景是没有意义的。您最近添加Expandable功能？

**Comment by CymChad** [comment]
还在研发中
