### ISSUE TITLE
请问为什么我这样设置空布局不起作用呢?

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2030]
//                    Toast.makeText(getActivity(), "加载失败布局...", Toast.LENGTH_SHORT).show();//TODO,空布局不起作用
//                    discoveryAdapter = new DiscoveryAdapter(R.layout.item_discovery, mDatas);
//                    View view = View.inflate(getActivity(), R.layout.empty_view, null);
//                    discoveryAdapter.setEmptyView(view);

**Comment by AllenCoder** [comment]
参考Demo示例代码
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/EmptyViewUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/EmptyViewUseActivity.java)
