### ISSUE TITLE
databinding怎么使用

### ISSUE THREAD

**Issue by gsw3430** [CymChad/BaseRecyclerViewAdapterHelper#2031]
这个adapter怎么用databinding

**Comment by AllenCoder** [comment]
参考 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DataBindingUseAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DataBindingUseAdapter.java)
