### ISSUE TITLE
请教一个使用BRVAH,RecyclerView嵌套RecyclerView的 分页加载问题

### ISSUE THREAD

**Issue by yangchaojiang** [CymChad/BaseRecyclerViewAdapterHelper#2032]
嵌套RecyclerView的 adadpeer分页加载，没有屏幕底部。
触发无限分页加载问题
怎么解决吗？

**Comment by AllenCoder** [comment]
加载更多情形很多，但基本上都有相应的解决方案 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2023](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2023)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1984](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1984)

查看问题列表
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A+](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A+)
