### ISSUE TITLE
请教两个关于BRVAH加载更多的问题

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2034]
比如我列表刚开始是展示10条数据,加载更多后再获取10条数据,总共展示了20条数据
1.没加载更多之前点击item获取item数据是正常的,比如我点击item9是正常的,当我点击item11就报数组下标越界了.
@Override
    public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
        if (view.getId() == R.id.play_icon) {//播放图标
            HomeListBean homeListBean = mDatas.get(position);
            List<HomeListBean.DataBean> data = homeListBean.getData();
            Toast.makeText(mContext, "119=  "+data.size(), Toast.LENGTH_SHORT).show();
//            if(data.size()!=0&&data!=null){}
            HomeListBean.DataBean dataBean = data.get(position);//这里越界
            String titleName = dataBean.getName();
            String subName = dataBean.getSubname();
            String coverImg = dataBean.getImg();
            int vid = dataBean.getVid();
            HomeListBean.DataBean.ChannelBean channel = dataBean.getChannel();
2.加载更多示例这个TOTAL_COUNTER是肯定不能写死的,是直接获取后台的总条数吗?但是后台说没有提供

**Comment by AllenCoder** [comment]
下标越界，检测一下你的数据引用地址是否正确。加载更多的是需要及时修改数据原始数据源，关于这块应该检测你的加载完成后的处理逻辑
