### ISSUE TITLE
第一次加载onLoadMoreRequested不回调

### ISSUE THREAD

**Issue by iRoxas** [CymChad/BaseRecyclerViewAdapterHelper#2040]
设置onLoadMoreRequested后，希望列表在刚显示的时候自动加载数据。但是看了autoLoadMore代码
private void autoLoadMore(int position) {
        **if (getLoadMoreViewCount() == 0) {
            return;
        }**
        if (position < getItemCount() - mPreLoadNumber) {
            return;
        }
        if (mLoadMoreView.getLoadMoreStatus() != LoadMoreView.STATUS_DEFAULT) {
            return;
        }
        mLoadMoreView.setLoadMoreStatus(LoadMoreView.STATUS_LOADING);
        if (!mLoading) {
            mLoading = true;
            if (getRecyclerView() != null) {
                getRecyclerView().post(new Runnable() {
                    @Override
                    public void run() {
                        mRequestLoadMoreListener.onLoadMoreRequested();
                    }
                });
            } else {
                mRequestLoadMoreListener.onLoadMoreRequested();
            }
        }
    }
public int getLoadMoreViewCount() {
        if (mRequestLoadMoreListener == null || !mLoadMoreEnable) {
            return 0;
        }
        if (!mNextLoadEnable && mLoadMoreView.isLoadEndMoreGone()) {
            return 0;
        }
        **if (mData.size() == 0) {
            return 0;
        }**
        return 1;
    }
mData.size() == 0就不能autoLoadmore了，但是列表一开始本来就没有数据。
请问是需要手动addData一次，还是我理解错了？

**Comment by AllenCoder** [comment]
加载更多，从字面意思理解就是已经有过一些数据，才会触发加载更多，一开始没有数据是不会触发加载更多的，需要有一次数据之后，滑动到底部才会触发加载更多
