### ISSUE TITLE
最新版本在上拉加载时,只有第一次能正常上啦数据插入,后面列表会停在最下面,无限触发上拉加载更多

### ISSUE THREAD

**Issue by SlimEx** [CymChad/BaseRecyclerViewAdapterHelper#2044]
如果上啦加载更多时候数据源很快更新的话.调用adddata之后,列表惯性滚动让列表无限触发上拉

**Comment by AllenCoder** [comment]
参考 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1407](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1407)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1346](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1346)
