### ISSUE TITLE
能配合使用纯代码写的布局而不使用IdRes吗？比如配合Anko Layout

### ISSUE THREAD

**Issue by spkingr** [CymChad/BaseRecyclerViewAdapterHelper#2046]
能否配合 Anko 使用呢？因为构造函数只支持 @IdRes 的参数传入，而不能直接传入 View ，使用 Anko Layout 的时候没办法使用吗？
感谢回复！

**Comment by AllenCoder** [comment]
暂时还不支持，后续如有机会考虑接入

**Comment by kangqiao** [comment]
Anko代码中使用的BaseQuickAdapte.
`
abstract class AKBaseQuickAdapter<T> : BaseQuickAdapter<T, AKViewHolder<T>>(-1) {

    /**
     * 在Anko的RecyclerView中使用AkBaseQuickAdapter时, 仅需要为每个Item指定创建AkItemView实例即可.
     */
    abstract fun onCreateItemView(): AKItemViewUI<T>

    override fun createBaseViewHolder(parent: ViewGroup, layoutResId: Int): AKViewHolder<T> {
        return if (layoutResId > 0) {
            super.createBaseViewHolder(parent, layoutResId)
        } else {
            val akContext = AnkoContext.create(parent.context, parent)
            val akItemView = onCreateItemView()
            val view = akItemView.createView(akContext)
            AKViewHolder(akItemView, view)
        }
    }

    override fun convert(helper: AKViewHolder<T>, item: T) {
        helper.bind(item)
    }
}
`
`
akAdapter = object : AKBaseQuickAdapter<Article>() {
    override fun onCreateItemView() = ArticleAKItemViewUI()
}

class ArticleAKItemViewUI : AKItemViewUI<Article> {
    override fun bind(akViewHolder: AKViewHolder<Article>, item: Article) {
......
`
https://github.com/kangqiao182/ComponentForAndroid/blob/93574428e674503ca1158ce7e03945e31a59263a/modules/home/src/main/java/com/zp/android/home/ui/HomeFragmentUI.kt#L71
