### ISSUE TITLE
多布局每一种布局都是一个接口没看明白数据怎么加载

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#2047]
MyBaseModel info = JSON.parseObject(response.get().toString(), MyBaseModel.class);
                if (info.getState() == Constants.SUCCEED) {
                    AllOrder acty = JSON.parseObject(response.get().toString(), AllOrder.class);
                    List<MulEntity>  mulEntityList=new ArrayList<>();
                    MulEntity mulEntity=new MulEntity(4);

                    mulEntityList.add(mulEntity);
                    multitleAdapter.setNewData(mulEntityList);
                } else {
                    ToastUtils.show(info.getData());
                }

怎么给其中布局给数据呢

**Comment by AllenCoder** [comment]
参考最新示例代码  [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java)
