### ISSUE TITLE
多布局问题，实际应用

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#2048]
在不，我用你的框架，实现多布局，我是四个接口对应四个布局，实现在一个页面，感觉用那个你的布局实现不了，怎么搞呢

**Comment by AllenCoder** [comment]
可参考Demo最新示例 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/MultipleItemUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/MultipleItemUseActivity.java)

**Comment by douya40** [comment]
我看了这个是一个是他加载数据的，目前我有四个接口，异步请求，就会有四个实体加载不同的布局

**Comment by tangnuo** [comment]
Demo太理想化了，实际情况异常复杂；
只有一个BaseViewHolder，通过findViewById来展示数据特别难受

**Comment by AllenCoder** [comment]
Demo在设计之初，也无法全面考虑到所有的应用场景，针对复杂的场景，还是需要自己自定义多布局，自定义实体类的实现，需要适当改造。

**Comment by Kunsan16** [comment]
@douya40 我自己的一种做法如下：
四个接口使用rxjava的concatArray按顺序请求，然后用一个list来保存这四个接口请求的response
时间过去蛮久了，不知你使用的是什么方法
