### ISSUE TITLE
刷新调用setNewData方法的问题

### ISSUE THREAD

**Issue by sososeen09** [CymChad/BaseRecyclerViewAdapterHelper#205]
在以前的版本中setNewData中把FooterView置为null，新版本中不是这样，而是手动调用removeAllFooters方法，这么设计是有什么特别的目的吗？

**Comment by CymChad** [comment]
这样让使用者更加清晰

**Comment by CymChad** [comment]
并且新的版本可以添加多个头部和尾部

**Comment by CymChad** [comment]
Demo刷新的时候也是用的setNewData方法

**Comment by shichaohui** [comment]
1. 之前只能一个footer，所以setNewData()方法中把footerView重置为null是可以达到removeAllFooterVIew的目的，从而解决刷新后旧的footerView仍存在的问题。
2. 新版本使用一个LinearLayout维护所有footerView，如果刷新后仍设置footerLayout为null会导致刷新后footerLayout显示不出来。
3. 刷新后仍显示之前添加的footerView是因为没有调用removeFooterView/removeAllFooterView方法移除旧的footerView， demo中没有问题是因为demo中setNewData之后调用了removeAllFooterView()。
4. 开发者手动移除footerView更加灵活，可以在刷新时自由控制任意footerView的移除。
