### ISSUE TITLE
setOnItemClickListener点击失效问题

### ISSUE THREAD

**Issue by zcl947694252** [CymChad/BaseRecyclerViewAdapterHelper#2050]
下载的demo在小米6上运行点击跳转DragAndSwipe跳转进入界面，点击item三次后setOnItemClickListener就不在响应点击事件

**Comment by AllenCoder** [comment]
ItemDragAndSwipeUseActivity 这个Activity自身又实现了OnItemDragListener，当部分点击有少许的滑动距离时，会触发滑动的监听，导致itemview的State一直没有释放。所以下一次的点击就不会触发，滑动释放后，重新点击又可以了，点击和滑动事件同时触发的冲突需要处理一下
