### ISSUE TITLE
Expanable功能单独expand有问题

### ISSUE THREAD

**Issue by wilson123** [CymChad/BaseRecyclerViewAdapterHelper#2051]
假如布局默认是收起来的，第一个父节点有3个子节点，第二个父节点有2个子节点，还有其他父节点，我现在要单独展开第一个和第二个父节点，调用expand（0）后再expand（1）就出问题了；
expand（0）展开后position就乱了，第二个父节点的position变成了4，要改成expand（4）而不是expand（1）来展开第二个父节点；
在Expandable功能中，getAdapterPosition（）无法正常去使用获取当前是第几个父节点，第几个子节点

**Comment by ImAlipay** [comment]
我也遇到了这个问题，不知道怎么解决了

**Comment by ImAlipay** [comment]
判断type类型就可以了
