### ISSUE TITLE
多布局问题和viewholder

### ISSUE THREAD

**Issue by tangnuo** [CymChad/BaseRecyclerViewAdapterHelper#2052]
多布局问题：
1、多个接口返回数据，返回的顺序不确定的情况下，数据组装困难；
2、多种数据结构，并且结构不一致的时候，如果将各种数据类型统一放入一个集合中，非常臃肿。

viewHolder:
1、Adapter中展示数据，只有BaseViewHolder，并且是通过findViewById的形式来获取控件，页面复杂的时候极其复杂（为什么不支持butterknife）。

**Comment by AllenCoder** [comment]
多布局参考最新 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DemoMultipleItemRvAdapter.java
