### ISSUE TITLE
setNewData不刷新页面

### ISSUE THREAD

**Issue by wimvogt** [CymChad/BaseRecyclerViewAdapterHelper#2053]
给adapter设置list1，再次刷新时调用setNewData(list2)，页面展示的还是list1数据

**Comment by zhEdward** [comment]
`setNewData(list2)`改为`setNewData(null)`数据可以正常清空吗？

**Comment by wimvogt** [comment]
@zhEdward 可以，现在是这么清空的

**Comment by AllenCoder** [comment]
检查一下 list1 和list 2 确认数据不同吗？如果数据发生改变肯定是会刷新视图的

**Comment by caoeryang** [comment]
list1和list2 数据一样 ,造成数据重复怎么解决啊?
