### ISSUE TITLE
Expandable列表加载完之后，都没有展开，请问怎么设置呢？

### ISSUE THREAD

**Issue by richfuns** [CymChad/BaseRecyclerViewAdapterHelper#2057]
我是参照官方例子写的，基本一模一样，但是Item全部没有展开啊？

现在只能通过mAdapter.expand(pos);一个一个设置

请指教，谢谢

**Comment by shkwy** [comment]
在activity里adapter.expandAll();

**Comment by richfuns** [comment]
@shkwy 现在用的就是这个方法

**Comment by LiWeiQiangAndroid** [comment]
fragment 中设置adapter.expandAll();无效，设置后laodData加载数据还是折叠状态

**Comment by shichaohui** [comment]
@LiWeiQiangAndroid 查看源码你就会发现 `expandAll()` 是实时对数据进行操作，所以要在数据加载完后才能使用。

**Comment by fengshenzhu** [comment]
所有相关issue都没有解决问题就关闭了😿
贴一个我这边有效的解决方法：
```java
private void expandAll() {
    for (int i = 0; i < mAdapter.getData().size(); i++) {
        mAdapter.collapse(i, false, false);
    }
    mAdapter.expandAll();
    mAdapter.notifyDataSetChanged();
}
```
