### ISSUE TITLE
请问V7包RecyclerView.ViewHolder的getAdapterPosition()方法用BRVAH是用哪个api获取?

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2058]

**Comment by roybill** [comment]
我试了helper.getLayoutPosition()这个方法好像拿的不对呀.
V7包的代码:
` @Override
    public void onBindViewHolder(final ViewHolder holder, final int position) {
        final MyLiveBean myLive = mMyLiveList.get(holder.getAdapterPosition());
//        holder.mTvTitle.setText(myLive.getTitle());
//        holder.mTvSource.setText(myLive.getSource());
        if (mEditMode == MYLIVE_MODE_CHECK) {
            holder.mCheckBox.setVisibility(View.GONE);
        } else {
            holder.mCheckBox.setVisibility(View.VISIBLE);

            if (myLive.isSelect()) {
                holder.mCheckBox.setImageResource(R.mipmap.ic_checked);
            } else {
                holder.mCheckBox.setImageResource(R.mipmap.ic_uncheck);
            }
        }
        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mOnItemClickListener.onItemClickListener(holder.getAdapterPosition(), mMyLiveList);
            }
        });
    }`

自定义点击接口回调;
` public interface OnItemClickListener {
        void onItemClickListener(int pos, List<CollectedBean> myLiveList);
    }`
BRVAH的代码:
` @Override
    public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
        //选择删除按钮不可见时点击item播放视频,可见时点击选择删除
        if (checkBox.getVisibility() == View.VISIBLE) {
            Toast.makeText(mContext, "点击删除" + position, Toast.LENGTH_SHORT).show();
            //回调点击接口
//            mOnItemClickListener.onItemClickListener(position, mMyLiveList);
            mOnItemClickListener.onItemClickListener(这里该怎么拿holder.getAdapterPosition()这个方法的数据, mMyLiveList);
        }`

**Comment by AllenCoder** [comment]
```
  private int getClickPosition() {
        if (getLayoutPosition()>=adapter.getHeaderLayoutCount()){
            return getLayoutPosition() - adapter.getHeaderLayoutCount();
        }
        return 0;
    }
```
点击位置需要减去headview的数量
