### ISSUE TITLE
关于布局复用 重复加载的问题反馈

### ISSUE THREAD

**Issue by wincentytg** [CymChad/BaseRecyclerViewAdapterHelper#206]
@Override
    protected void convert(final BaseViewHolder helper,final Status item,final int position) {
        helper.setText(R.id.tweetName, item.getUserName())
                .setText(R.id.tweetText, item.getText())
                .setText(R.id.tweetDate, item.getCreatedAt())
                .setVisible(R.id.tweetRT, item.isRetweet())
                .setOnClickListener(R.id.tweetAvatar, new OnItemChildClickListener())
                .setOnClickListener(R.id.tweetName, new OnItemChildClickListener())
                .linkify(R.id.tweetText);
        Log.i("URI",position+"");
        helper.getView(R.id.tweetDate).setOnClickListener(new View.OnClickListener(){

            @Override
            public void onClick(View v) {

                item.setUserName("cefede");
                notifyItemChanged(position,item);
            }
        });
        Glide.with(mContext).load(item.getUserAvatar()).crossFade().placeholder(R.mipmap.def_head).transform(new GlideCircleTransform(mContext)).into((ImageView) helper.getView(R.id.tweetAvatar));
    }

现在假如第1条数据和第6条数据复用布局，当我操作第1条的点击事件的时候执行  item.setUserName("cefede");
                notifyItemChanged(position,item);，Log.i("URI",position+"");会打印出1 和 6 ，也就是说 第一条数据和第六条数据 会同时刷新，现在能不能操作第一条的时候只刷新 第一条的数据，跟第一条公用布局的不刷新？  谢谢

**Comment by CymChad** [comment]
你可以使用我提供的方法来设置点击事件
Use it item chlid click
Adapter
```java
protected void convert(BaseViewHolder helper, Status item) {
    helper.setOnClickListener(R.id.tweetAvatar, new OnItemChildClickListener())
        .setOnClickListener(R.id.tweetName, new OnItemChildClickListener());
}
```
Activity
```java
mQuickAdapter.setOnRecyclerViewItemChildClickListener(new BaseQuickAdapter.OnRecyclerViewItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                String content = null;
                Status status = (Status) adapter.getItem(position);
                switch (view.getId()) {
                    case R.id.tweetAvatar:
                        content = "img:" + status.getUserAvatar();
                        break;
                    case R.id.tweetName:
                        content = "name:" + status.getUserName();
                        break;
                }
                Toast.makeText(AnimationUseActivity.this, content, Toast.LENGTH_LONG).show();
            }
        });
```

**Comment by wincentytg** [comment]
还是不行 这是调用您提供的方法

我点击第一条数据的时候 Log.i("URI",position+"");log打印的position 提示的是5，而且第一条对应的Username也没改成我设置的"cefede"。界面上还是显示原来的。


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年8月3日(星期三) 上午10:12
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "六月的战士"<995278340@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 关于布局复用 重复加载的问题反馈 (#206)




你可以使用我提供的方法来设置点击事件
 Use it item chlid click
 Adapter
 protected void convert(BaseViewHolder helper, Status item) {     helper.setOnClickListener(R.id.tweetAvatar, new OnItemChildClickListener())         .setOnClickListener(R.id.tweetName, new OnItemChildClickListener()); }
 
Activity
 mQuickAdapter.setOnRecyclerViewItemChildClickListener(new BaseQuickAdapter.OnRecyclerViewItemChildClickListener() {             @Override             public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {                 String content = null;                 Status status = (Status) adapter.getItem(position);                 switch (view.getId()) {                     case R.id.tweetAvatar:                         content = "img:" + status.getUserAvatar();                         break;                     case R.id.tweetName:                         content = "name:" + status.getUserName();                         break;                 }                 Toast.makeText(AnimationUseActivity.this, content, Toast.LENGTH_LONG).show();             }         });

**Comment by wincentytg** [comment]
为啥用您提供的方法 就ok了  用我自己写的单击监听事件 就会出现复用的问题呢？谢谢

**Comment by CymChad** [comment]
你的postion是动态的，我的postion是通过viewholder.getLayoutPostion获取的。RecyclerView源码做了处理。

**Comment by wincentytg** [comment]
我刚才 又试了几遍 你写的方法 也有问题 也会出现复用刷新的问题，你多上下滑动几次列表然后再点击某一个试试 看看效果就知道了

**Comment by CymChad** [comment]
恩 好的。你是说postion还是有问题对吧

**Comment by wincentytg** [comment]
是的 可能位置的记录有问题

**Comment by CymChad** [comment]
行，我查查。

**Comment by CymChad** [comment]
没遇到，position错位的情况。。

**Comment by CymChad** [comment]
位置记录都是通过ViewHolder获取的。

**Comment by wincentytg** [comment]
我在这个方法 加了个position
protected abstract void convert(BaseViewHolder helper, T item,int position);
实现的方法里 穿进去position
 @Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder, int positions) {
        int viewType = holder.getItemViewType();

        switch (viewType) {
            case 0:
                convert((BaseViewHolder) holder, mData.get(holder.getLayoutPosition() - getHeaderLayoutCount()),positions);
                break;

然后在自己的adapter里打印log @Override
    protected void convert(final BaseViewHolder helper,final Status item,final int position) {
        Log.i("URI",position+"");

这样改的话有问题吗?

这样 就导致 我上下多滑动几次列表  点击某一个单击的时候这里打印的position就会出现跟当前点击item布局复用的所有position

**Comment by wincentytg** [comment]
就会刷新除了 本次单击之外的item  这样 就不是 改哪个 刷新哪个了 只是把别的不相干的布局也刷新了下  数据没变  即使这样 也不会影响使用，就是性能感觉不好了

**Comment by CymChad** [comment]
你可以通过 viewHolder.getLayoutPosition拿到这个position

**Comment by wincentytg** [comment]
现在不是position的问题 position 没问题啊 是刷新的问题 我单击了 第一条执行了 notify这个方法 为啥第六条个会刷新？convert 这个方法 在position为1和6 的时候执行了

**Comment by wincentytg** [comment]
上下滑动多次之后执行这个方法**notifyItemChanged(position+1,status);** convert 这个方法会执行两次

**Comment by engglea** [comment]
convert会执行两次
