### ISSUE TITLE
RecyclerView嵌套RecyclerView

### ISSUE THREAD

**Issue by zcychinese** [CymChad/BaseRecyclerViewAdapterHelper#2060]
RecyclerView嵌套RecyclerView时，子Recycler的子控件不能撑满的问题。

**Comment by AllenCoder** [comment]
参考Demo的ItemClickActivity的布局和逻辑写法
[https://github.com/AllenCoder/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java](https://github.com/AllenCoder/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/ItemClickAdapter.java)
