### ISSUE TITLE
请问用BRVAH加载更多我这样写是不是多余了?而且点击加载更多的item会数据错乱

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2061]
但是我用官方这个  //成功获取更多数据
                                mQuickAdapter.addData(DataServer.getSampleData(PAGE_SIZE));数据不展示.我是这样写的,麻烦帮我纠正一下,谢谢!

`  private void setLoadMoreData(String json) {
        //处于子线程
        Gson gson = new Gson();
        final CollectedBean collectedBean = gson.fromJson(json, CollectedBean.class);
        final List<CollectedBean.DataBean> data = collectedBean.getData();
        mDatas = new ArrayList<>();
        Log.d(TAG, "1111curr="+mCurrentCounter+"    ,data="+data.size());
        final int totalCount = mCurrentCounter + data.size();//视频总条数
//        Log.d(TAG, "1110=   "+totalCount);
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (mCurrentCounter >= totalCount) {
                    //数据全部加载完毕
                    mAdapter.loadMoreEnd();
                } else {
                    if (isErr) {
                        for (int i = 0; i < data.size(); i++) {
                            CollectedBean.DataBean dataBean = data.get(i);
                            CollectedBean bean = new CollectedBean();
                            String title = dataBean.getName();
                            int watchCount = dataBean.getClick();
                            String img = dataBean.getImg();
                            String totalTime = dataBean.getLenght();
                            bean.setTitle(title);//标题
                            Log.d(TAG, "1121=   "+title);
                            bean.setWatchCont(watchCount + "");//观看数
                            bean.setImgUrl(img);//封面
                            bean.setTotalTime(totalTime);//视频时长
                            bean.setData(data);
//                            collectedBean.setData(data);
                            mAdapter.addData(bean);
                            mDatas.add(bean);
                        }
                        //加载更多后position总数需要添加为和totalCount相同数目,否则会下标越界
                        for (int i = 0; i < totalCount; i++) {
                            CollectedBean.DataBean dataBean = data.get(i);
                            data.add(dataBean);
                        }
                        mCurrentCounter = mAdapter.getData().size();
                        //主动调用加载完成，停止加载
                        mAdapter.loadMoreComplete();
                    } else {
                        //获取更多数据失败
                        isErr = true;
                        //同理，加载失败也要主动调用加载失败来停止加载（而且该方法会提示加载失败）
                        mAdapter.loadMoreFail();
                    }
                }
            }
        });
    }`

**Comment by AllenCoder** [comment]
请重新提交一下你的代码，代码使用markdown语法格式化一下，这样更能准确排查问题
