### ISSUE TITLE
当header过长时打开界面，整个界面会自动往上移动header的高度

### ISSUE THREAD

**Issue by yzjsbsb** [CymChad/BaseRecyclerViewAdapterHelper#2063]
必须手动下拉才行。
外部套用SwipeRefreshLayout并添加
        android:focusable="true"
        android:focusableInTouchMode="true"
并没有效果。。。

**Comment by AllenCoder** [comment]
headerview内部是否有类似EditText的控件，这类控件会优先获取焦点，导致headview上移，使其完全展示出来，可在recyclerview布局中设置优先获取焦点
```
<android.support.v7.widget.RecyclerView
        android:id="@+id/rv_list"
        android:layout_width="match_parent"
        android:descendantFocusability="beforeDescendants"
        android:layout_height="match_parent"/>
```
如果这种方案不行，可在view显示之后，手动调用代码使其滚动到（0.0）位置
