### ISSUE TITLE
Add footview and headview

### ISSUE THREAD

**Issue by amloser** [CymChad/BaseRecyclerViewAdapterHelper#2065]
如果RecyclerView没有铺满全屏 只占屏幕的一部分 比如屏幕的一半。添加头部或者尾部 虽然已经挤出去了 但是还是无法滑动 必须当布局填满整个屏幕后（这时候已经有一半看不见了其实）才能滑动 应该是默认就是获取屏幕高度 这个怎么解决

**Comment by amloser** [comment]
这边 我给定RecyclerView高度就可以了 内容包裹就不行。。

**Comment by AllenCoder** [comment]
搞定就好，多尝试
