### ISSUE TITLE
多布局报错

### ISSUE THREAD

**Issue by Yanqilong** [CymChad/BaseRecyclerViewAdapterHelper#2066]
当列表内存在多个布局，但不确定列表会返回哪些数据类型，所以适配器内设置了所有的布局后报错了，

错误如下：
```ruby 
android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c 
```
请问这种情况怎么解决？

**Comment by AllenCoder** [comment]
资源未找到。可以参考Demo的多布局写法

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/MultipleItemQuickAdapter.java)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/MultipleItemUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/MultipleItemUseActivity.java)
