### ISSUE TITLE
上拉加载更多的问题,请大神解决下

### ISSUE THREAD

**Issue by yyzl0418** [CymChad/BaseRecyclerViewAdapterHelper#2073]
调用loadMoreEnd(true)后在当前页面就无法再使用加载更多,请帮忙解决下

**Comment by zhEdward** [comment]
这api 本意就是 当 服务器给的“分页”数据全部都加载完 就不能在允许加载了。
按照demo里的 如果不是“最后一页”的数据  都是调用`mAdapter.loadMoreComplete()`的
