### ISSUE TITLE
Horizontal Recyclerview inside Vertical Recyclerview

### ISSUE THREAD

**Issue by mobilegeekkk** [CymChad/BaseRecyclerViewAdapterHelper#2076]
I want to create a dynamic loading view that contains horizontal recyclerview inside vertical recyclerview and vertical recyclerview should be inside Scrollview as the main view contains some more views components. So my dynamic hierarchy is as following:-

Scrollview [
  | Viewpager --
  | AdView --
  | Vertical Items - Recyclerview {
       1) [Horizontal Recyclerview {1.1, 1.2, 1.3} [Lazy Loading of Items]]
       2) [Horizontal Recyclerview {2.1, 2.2, 2.3} [Lazy Loading of Items]]
       3) [Horizontal Recyclerview {3.1, 3.2, 3.3} [Lazy Loading of Items]]
       4) [Horizontal Recyclerview {4.1, 4.2, 4.3} [Lazy Loading of Items]]
       .
       .
       .
    [Lazy Loading of Items in Vertical Direction also]
       }
   | Some Another View --
          ]

Is this horizontal recyclerview inside vertical recylerview possible from Bravah ?
Would scroll behavior of Scrollview be smooth ? 
 Please suggest me.

**Comment by AllenCoder** [comment]
horizontal recyclerview inside vertical recylerview could not fluent, you can Adjust the layout, or Use multiple layouts

**Comment by mobilegeekkk** [comment]
@AllenCoder  Hey buddy, can you tell me how can I adjust my layout ? 
like I want a dynamically recyclerview type of section adapter and inside that list I want nested horizontal dynamic items. This view is basically same as google play store view.
How can i get this approach ?
