### ISSUE TITLE
设置入场动画后不能取消

### ISSUE THREAD

**Issue by scsfwgy** [CymChad/BaseRecyclerViewAdapterHelper#2077]
简直抓狂，有这种需求：我刚进入后要入场动画，后面需要取消掉，但是这个设置是一个私有的属性，无法更改。另外，为什么刷新之后需要重新设置.setNewData()？大佬的做法不理解啊（我是铁杆）。

**Comment by scsfwgy** [comment]
@CymChad

**Comment by AllenCoder** [comment]
新版本已经加入closeLoadAnimation
