### ISSUE TITLE
请问用BRVAH滑动后数据错乱该怎么解决?

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2078]
我看了官方是拿checkBox做数据错乱的示例,但是我用的是TextView,我尝试用官方的做法但是没有做出来,请问该怎么解决呢?这是我的item点击代码:
`public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
        //TODO:有bug,复用后状态错乱.需要点击对应item的关注改变状态
        TextView tvNotFocus = view.findViewById(R.id.tv_related_theme_recommended_focus);//默认未关注
        String focus = tvNotFocus.getText().toString();
        List<TopicRelatedRecommendedBean> data = getData();
        TopicRelatedRecommendedBean topicRelatedRecommendedBean = data.get(position);
        boolean select = topicRelatedRecommendedBean.isSelect();

        if (view.getId() == R.id.tv_related_theme_recommended_focus) {
            if (focus.equals("关注")) {
//                Toast.makeText(mContext, "已关注", Toast.LENGTH_SHORT).show();
                tvNotFocus.setText("已关注");
                tvNotFocus.setBackgroundResource(R.drawable.topic_already_focus_shape);
            } else if (focus.equals("已关注")) {
//                Toast.makeText(mContext, "取消关注", Toast.LENGTH_SHORT).show();
                tvNotFocus.setText("关注");
                tvNotFocus.setBackgroundResource(R.drawable.release_button_shape);
            }
        }
        if (select) {
            Toast.makeText(mContext, "取消关注", Toast.LENGTH_SHORT).show();
            tvNotFocus.setText("关注");
            tvNotFocus.setBackgroundResource(R.drawable.release_button_shape);
            topicRelatedRecommendedBean.setSelect(false);
        } else {
            Toast.makeText(mContext, "关注", Toast.LENGTH_SHORT).show();
            tvNotFocus.setText("已关注");
            tvNotFocus.setBackgroundResource(R.drawable.topic_already_focus_shape);
            topicRelatedRecommendedBean.setSelect(true);
        }
    }`

**Comment by AllenCoder** [comment]
数据错乱是你的数据状态保存不对，应该用数据层Model的字段来标记不同的状态，而不能通过view来存储，view会因为复用导致状态错乱
