### ISSUE TITLE
setEmpty的问题

### ISSUE THREAD

**Issue by liuyong1993** [CymChad/BaseRecyclerViewAdapterHelper#2079]
没有数据的时候设置了setEmpty   ,但是当有了数量 ，调用adapter的notifyDataSetChanged()方法并没有让空布局消失，必须要调用adapter.addNewData()才可以，这是为什么

**Comment by zhEdward** [comment]
![image](https://user-images.githubusercontent.com/12438329/37776187-b9ef925a-2e1f-11e8-9315-9f9f2c738fbf.png)
看它源码得出的，  前面的代码段 就是拿来控制（error view，empty view）之类显示/隐藏状态的，最后才使用`adapter.notifyDataSetChanged()`来装填新数据

**Comment by AllenCoder** [comment]
@
