### ISSUE TITLE
使用setOnItemClickListener时，view复用的问题

### ISSUE THREAD

**Issue by yy-Kevin** [CymChad/BaseRecyclerViewAdapterHelper#2084]
mAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                ToggleButton viewById = (ToggleButton) view.findViewById(R.id.tb_check_personal);
}
想请教一个问题，使用adapter的点击事件时，view会出现复用的问题，也就是第一个，第十一个，第二十一个可能是同一个对象，请问这种问题该怎么解决，谢谢。

**Comment by AllenCoder** [comment]
view的复用正是recyclerView的机制，所以要把状态的保存存放在Model的字段内，通过更新Model来达到不同位置的view显示不一样的效果
