### ISSUE TITLE
FooterLayout的setLayoutParams问题

### ISSUE THREAD

**Issue by OtherSun** [CymChad/BaseRecyclerViewAdapterHelper#2086]
如何设置FooterLayout的LayoutParams宽高都为WRAP_CONTENT呢，原因是嵌套在listview的单行水平列表滑动时footerview总有宽或高满屏，例如：如果宽是MATCH_PARENT，第二屏出现footerview就是满屏，如果高是MATCH_PARENT，那footerview也会满屏，我觉得可以重载这个方法，增加两个参数可以自己设置；
如下是源码：

public int addFooterView(View footer, int index, int orientation) {
        if (mFooterLayout == null) {
            mFooterLayout = new LinearLayout(footer.getContext());
            if (orientation == LinearLayout.VERTICAL) {
                mFooterLayout.setOrientation(LinearLayout.VERTICAL);
                mFooterLayout.setLayoutParams(new LayoutParams(MATCH_PARENT, WRAP_CONTENT));
            } else {
                mFooterLayout.setOrientation(LinearLayout.HORIZONTAL);
                mFooterLayout.setLayoutParams(new LayoutParams(WRAP_CONTENT, MATCH_PARENT));
            }
        }
        final int childCount = mFooterLayout.getChildCount();
        if (index < 0 || index > childCount) {
            index = childCount;
        }
        mFooterLayout.addView(footer, index);
        if (mFooterLayout.getChildCount() == 1) {
            int position = getFooterViewPosition();
            if (position != -1) {
                notifyItemInserted(position);
            }
        }
        return index;
    }

**Comment by AllenCoder** [comment]
可以根据需要重载这个方法，改.setLayoutParams(new LayoutParams(WRAP_CONTENT, WRAP_CONTENT));
