### ISSUE TITLE
点击item不太灵敏可能是因为什么啊？

### ISSUE THREAD

**Issue by Martin-zhq** [CymChad/BaseRecyclerViewAdapterHelper#2087]
整个布局中没有给子控件添加点击事件，只给item添加了点击事件。。但是点击item的时候，有时候会点个两三次还不响应，主要是点击item中的空白部分时它最可能出现不响应的情况，这可能是因为什么啊老哥？

**Comment by AllenCoder** [comment]
参考demo 写法 
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister)

不灵敏是否跟你的布局触控面积太小有关，建议放大布局的可点击响应面积试一下

**Comment by Martin-zhq** [comment]
老哥，我写的是仿照微信里边的动态详情界面，然后外边是个ScrollView，在评论列表里用的是RecyclerView，然后用的这个库的方法：adapter.setOnItemClickListener给添加的点击事件。然后它就点击不灵敏，而且整个item最低高度是60多dp啊，这跟触控面积应该没关系吧，所以我怀疑是不是跟ScrollView的事件冲突什么的有关，所以才想来问问的。。
