### ISSUE TITLE
单选失效

### ISSUE THREAD

**Issue by LiangLuDev** [CymChad/BaseRecyclerViewAdapterHelper#2089]
if (!beanList.get(position).isSelected()) {
                    for (SubscribeDateInfo.DataBean bean : beanList) {
                        bean.setSelected(false);
                    }
                    beanList.get(position).setSelected(true);
                    mAdapterSubscribeDate.notifyDataSetChanged();
                }

这段代码放在setOnItemClickListener，实现单选达不到单选效果，换成原生RecyclerView就行，不知道是不是我操作问题  求解答

**Comment by LiangLuDev** [comment]
@AllenCoder 没有header等其他布局，因为已经换了原生的，能不能提供一下代码。

**Comment by AllenCoder** [comment]
我没有代码，这个操作很容易实现的，数据层Model 增加一个isSelete字段 。绑定bean的单选状态字段，控制bean的单选状态，通知视图刷新

**Comment by zidanpiaoguo** [comment]
哦，搞定了。
  @Override
            public void onClick(View v) {

                for (int i = 0; i < mData.size(); i++) {
                    mData.get(i).setSelect(false);
                }
                mData.get(helper.getLayoutPosition()).setSelect(true);
                notifyDataSetChanged();

                EventBus.getDefault().post(new MessageEvent(2));
            }

**Comment by zidanpiaoguo** [comment]
convert 中是获取不到position 的吧。我重写的convert 方法，他源码都没有传position这个字段 。

**Comment by JQLewis** [comment]
@zidanpiaoguo 是的，convert()里如果能把position传过来就不用去遍历mData了，我的列表item比较多，最终还是用回了原生的Adapter
