### ISSUE TITLE
BaseMultiItemQuickAdapter 滑动卡顿

### ISSUE THREAD

**Issue by GCZeng** [CymChad/BaseRecyclerViewAdapterHelper#2090]
使用BaseMultiItemQuickAdapter写了一个多布局列表，一共3个类型，自动加载到一定数量的时候，然后往回滚动列表，每显示一行item的时候就会卡一下。

设置了setSpanSizeLookup
int spanSize = 6;
mHomeItemAdapter.setSpanSizeLookup((gridLayoutManager, position) -> {
                if (mData.get(position).getData() instanceof HomeMenuBean) {
                    return 2;
                } else if (mData.get(position).getData() instanceof HomeListBean) {
                    return 3;
                } else {
                    return spanSize;
                } 
});
调试发现上述方法return spanSize的时候不会卡顿，请问题个是什么原因？

**Comment by AllenCoder** [comment]
滑动卡顿可能有很多因素，如果你的recyclerview外层包裹有scrollView或者频繁刷新布局，触发重绘，是会感觉到卡顿的，另外不能在convert 方法里面处理任何耗时的操作

**Comment by GCZeng** [comment]
1. 外面没有ScrollView包裹的；
2. 我把BaseMultiItemQuickAdapter换成RecyclerView.Adapter就不会卡顿了；
3. convert方法里面是没有耗时操作的，数据是在本地生成的，图片使用Glide加载网络图片。

我调试过很多次了，觉得可能是框架的问题，望解决。

**Comment by AllenCoder** [comment]
多布局新版本提供了一个新的实现方法，可尝试接入测试一下 
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2102](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2102)
