### ISSUE TITLE
请教一个加载后刷新数据的问题

### ISSUE THREAD

**Issue by songsongtao** [CymChad/BaseRecyclerViewAdapterHelper#2092]
1. 
`mAdapter.getData().addAll(data);`
` mAdapter.loadMoreComplete()`
2. 
`mAdapter.addData(data);`
` mAdapter.loadMoreComplete()`
我之前使用你的库的时候一直用的是1.的方式加载更多后来添加数据（data是请求更多的数据集合）
后来我发现应该用2.的方式来添加更新数据。
我想问下为什么第一种方式也没有问题

**Comment by roybill** [comment]
你好!请问一下为什么我这样加载更多不行呢?
`
    /**
     * 显示加载更多成功数据
     */
    private void showLoadMoreSuccess() {
        final int totalCount = mCurrentCounter + mLoadMoreData.size();//视频总条数
        if (mCurrentCounter >= totalCount) {
            //数据全部加载完毕
            mAdapter.loadMoreEnd();
        } else {
            if (isErr) {
                for (int i = 0; i < mLoadMoreData.size(); i++) {
                    SearchResultBean.DataBean dataBean = mLoadMoreData.get(i);
                    SearchResultBean bean = new SearchResultBean();
                    String title = dataBean.getName();//标题
                    int watchCount = dataBean.getClick();//观看数
                    String updateTime = dataBean.getUpdateTime();//更新时间
                    String img = dataBean.getImg();//封面
                    String length = dataBean.getLenght();//视频总时长
                    bean.setTitle(title);
                    bean.setWatchCont(watchCount + "");
                    bean.setDate(updateTime);
                    bean.setImgUrl(img);
                    bean.setTotalTime(length);
                    bean.setData(mLoadMoreData);
                    mAdapter.addData(bean);
                    mDatas.add(bean);
                }
                //加载更多数据后必须添加加载出来的dataBean,否则会下标越界!
                for (int i = 0; i < totalCount; i++) {
                    SearchResultBean.DataBean dataBean = mLoadMoreData.get(i);
                    mLoadMoreData.add(dataBean);
                }
                mCurrentCounter = mAdapter.getData().size();
                //主动调用加载完成，停止加载
                mAdapter.loadMoreComplete();
            } else {
                //获取更多数据失败
                isErr = true;
                //同理，加载失败也要主动调用加载失败来停止加载（而且该方法会提示加载失败）
                mAdapter.loadMoreFail();
            }
        }
    }`

**Comment by AllenCoder** [comment]
格式太乱，无法排除问题
