### ISSUE TITLE
请问我使用BRVAH加载更多的时候这样是不是会重复加载了?偶尔还会下标越界

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2093]
重点是在setLoadMoreData(String json)这个方法.下面是一整个类来的,可能我没格式化好
类代码:
`public class SearchResultController extends TabController implements BaseQuickAdapter.RequestLoadMoreListener {

    @BindView(R.id.rv_have_result)
    RecyclerView mRecyclerView;
    @BindView(R.id.rl_search_loading)
    RelativeLayout mLoading;
    @BindView(R.id.rl_no_search_result)
    RelativeLayout mNoResult;

    private static final String TAG = "SearchResultController";
    private static final int NO_SEARCH_RESULT = 0;
    private static final int SHOW_SEARCH_SUCCESS = 1;
    private static final int SHOW_SEARCH_FAIL = 2;
    private static final int SHOW_LOAD_MORE_SUCCESS = 3;
    private static final int SHOW_LOAD_MORE_FAIL = 4;
    private Context mContext;
    private String searchKeywords;
    private List<SearchResultBean> mDatas = new ArrayList<>();
    private SearchResultHandler mHandler = new SearchResultHandler();
    private SearchResultAdapter mAdapter;
    private int mSize = 1;
    private int mCurrentCounter;
    private boolean isErr = true;
    private int totalCount;
    private List<SearchResultBean.DataBean> mLoadMoreData;
    private List<SearchResultBean.DataBean> mInitJsonData;

    public SearchResultController(Context context) {
        super(context);
        this.mContext = context;
    }

    @Override
    protected View initContentView(Context context) {
        View view = View.inflate(context, R.layout.controller_search_result, null);
        ButterKnife.bind(this, view);
        return view;
    }

    @Override
    public void initData() {
        searchKeywords = (String) BaseApplication.getApplication().getMap().get("searchTitle");
        Log.d(TAG, "1811=   "+searchKeywords);
        searchGame();
    }

    private void searchGame() {
        Gson gson=new Gson();
        String localJson = gson.toJson(new SearchObject());
        Log.d(TAG, "1812=   "+localJson);
        mLoading.setVisibility(View.VISIBLE);
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Response response = NetWorkRequestUtils.postRequest(ConstantsUtils.HEAD_URL + "/video/search", new SearchObject());
                    if (response.isSuccessful()) {
                        String json = response.body().string();
                        Log.d(TAG, "手动搜索成功=" + json);
                        setSearchData(json);//设置手动搜索结果数据
                    } else {
                        Log.d(TAG, "手动搜索失败1111111111111");
                        Message obtain = Message.obtain();
                        obtain.what = SHOW_SEARCH_FAIL;
                        mHandler.sendMessage(obtain);
                    }
                } catch (Exception e) {
                    Log.d(TAG, "手动搜索失败22222222222");
                    Message obtain = Message.obtain();
                    obtain.what = SHOW_SEARCH_FAIL;
                    mHandler.sendMessage(obtain);
                    e.printStackTrace();
                }
            }
        }).start();
    }

    /**
     * 设置手动搜索结果数据
     */
    private void setSearchData(String json) {
        Gson gson = new Gson();
        SearchResultBean searchResultBean = gson.fromJson(json, SearchResultBean.class);
//        List<SearchResultBean.DataBean> data = searchResultBean.getData();
        mInitJsonData = searchResultBean.getData();
//        mSize = mInitJsonData.size();//用于请求加载更多数据
//        mCurrentCounter = mSize;
        if (mInitJsonData.isEmpty()) {
            //搜索无结果,显示暂无搜索结果
            Message obtain = Message.obtain();
            obtain.what = NO_SEARCH_RESULT;
            mHandler.sendMessage(obtain);
            return;
        }
        SearchResultBean bean;
        for (int i = 0; i < mInitJsonData.size(); i++) {
            bean = new SearchResultBean();
            SearchResultBean.DataBean dataBean = mInitJsonData.get(i);
            String title = dataBean.getName();//标题
            int watchCount = dataBean.getClick();//观看数
            String updateTime = dataBean.getUpdateTime();//更新时间
            String img = dataBean.getImg();//封面
            String length = dataBean.getLenght();//视频总时长
            bean.setTitle(title);
            bean.setWatchCont(watchCount + "");
            bean.setDate(updateTime);
            bean.setImgUrl(img);
            bean.setTotalTime(length);
            bean.setData(mInitJsonData);
            mDatas.add(bean);
        }
        Message obtain = Message.obtain();
        obtain.what = SHOW_SEARCH_SUCCESS;
        mHandler.sendMessage(obtain);
//        Log.d(TAG, "search1013="+mInitJsonData.size());
    }

    private class SearchResultHandler extends Handler {
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            switch (msg.what) {
                case NO_SEARCH_RESULT://没有搜索结果
                    mLoading.setVisibility(View.GONE);
                    mNoResult.setVisibility(View.VISIBLE);
                    break;
                case SHOW_SEARCH_SUCCESS:
                    mLoading.setVisibility(View.GONE);
                    //创建布局管理
                    LinearLayoutManager layoutManager = new LinearLayoutManager(mContext);
                    layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
                    mRecyclerView.setLayoutManager(layoutManager);
                    mRecyclerView.addItemDecoration(new DividerItemDecoration(mContext,1));
                    mAdapter = new SearchResultAdapter(R.layout.item_search_have_result, mDatas, mContext);
                    mRecyclerView.setAdapter(mAdapter);
                    int size = mInitJsonData.size();
                    //初始化列表数据大于等于10条才去加载更多
                    if (size >= 10) {
                        mAdapter.setOnLoadMoreListener(SearchResultController.this);//加载更多
                    }
                    break;
                case SHOW_SEARCH_FAIL:
                    mLoading.setVisibility(View.GONE);
                    Toast.makeText(mContext, "搜索失败,请稍后重试", Toast.LENGTH_SHORT).show();
                    break;
                case SHOW_LOAD_MORE_SUCCESS:
                    showLoadMoreSuccess();//显示加载更多成功数据
                    break;
                case SHOW_LOAD_MORE_FAIL:
                    Toast.makeText(mContext, "加载更多失败", Toast.LENGTH_SHORT).show();
                    break;
                default:
                    break;
            }
        }
    }

    @Override
    public void onLoadMoreRequested() {
        mRecyclerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                getLoadMoreData();//联网获取加载更多数据
            }
        }, 1000);
    }

    /**
     * 联网获取加载更多数据
     */
    private void getLoadMoreData() {
        mSize = mSize + 1;
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Response response = NetWorkRequestUtils.postRequest(ConstantsUtils.HEAD_URL + "/video/search", new LoadMoreDataObject());
                    if (response.isSuccessful()) {
                        String json = response.body().string();
                        Log.d(TAG, "加载更多数据成功=   " + json);
                        setLoadMoreData(json);
                    } else {
                        Log.d(TAG, "加载更多数据失败11111111111");
                        Message obtain = Message.obtain();
                        obtain.what = SHOW_SEARCH_FAIL;
                        mHandler.sendMessage(obtain);
                    }
                } catch (Exception e) {
                    Log.d(TAG, "加载更多数据失败2222222222");
                    Message obtain = Message.obtain();
                    obtain.what = SHOW_SEARCH_FAIL;
                    mHandler.sendMessage(obtain);
                    e.printStackTrace();
                }
            }
        }).start();
    }

    /**
     * 设置加载更多数据
     */
    private void setLoadMoreData(String json) {
        //处于子线程
        Gson gson = new Gson();
        SearchResultBean searchResultBean = gson.fromJson(json, SearchResultBean.class);
        mLoadMoreData = searchResultBean.getData();
//        mSize += mLoadMoreData.size();
        //视频总条数
//        totalCount = mSize;
        mDatas = new ArrayList<>();
        Message obtain = Message.obtain();
        obtain.what = SHOW_LOAD_MORE_SUCCESS;
        mHandler.sendMessage(obtain);
//        Log.d(TAG, "1015="+mLoadMoreData.size());
    }

    /**
     * 显示加载更多成功数据
     */
    private void showLoadMoreSuccess() {
        final int totalCount = mCurrentCounter + mLoadMoreData.size();//视频总条数
        if (mCurrentCounter >= totalCount) {
            //数据全部加载完毕
            mAdapter.loadMoreEnd();
        } else {
            if (isErr) {
                for (int i = 0; i < mLoadMoreData.size(); i++) {
                    SearchResultBean.DataBean dataBean = mLoadMoreData.get(i);
                    SearchResultBean bean = new SearchResultBean();
                    String title = dataBean.getName();//标题
                    int watchCount = dataBean.getClick();//观看数
                    String updateTime = dataBean.getUpdateTime();//更新时间
                    String img = dataBean.getImg();//封面
                    String length = dataBean.getLenght();//视频总时长
                    bean.setTitle(title);
                    bean.setWatchCont(watchCount + "");
                    bean.setDate(updateTime);
                    bean.setImgUrl(img);
                    bean.setTotalTime(length);
                    bean.setData(mLoadMoreData);
                    mAdapter.addData(bean);
                    mDatas.add(bean);
                }
                //加载更多数据后必须添加加载出来的dataBean,否则会下标越界!
                for (int i = 0; i < totalCount; i++) {
                    SearchResultBean.DataBean dataBean = mLoadMoreData.get(i);
                    mLoadMoreData.add(dataBean);
                }
                mCurrentCounter = mAdapter.getData().size();
                //主动调用加载完成，停止加载
                mAdapter.loadMoreComplete();
            } else {
                //获取更多数据失败
                isErr = true;
                //同理，加载失败也要主动调用加载失败来停止加载（而且该方法会提示加载失败）
                mAdapter.loadMoreFail();
            }
        }
    }

    /**
     * 封装手动搜索数据的对象
     */
    private class SearchObject {
        //        String action = "search";
        String word = searchKeywords;
        int p = 1;//p默认为1(表示第1页数据),首次加载更多为2,依次累加
    }

    /**
     * 封装加载更多数据的对象
     */
    private class LoadMoreDataObject {
        //        String action = "search";
        String word = searchKeywords;
        int p = mSize;//p默认为1(表示第1页数据),首次加载更多为2,依次累加
    }
}`

**Comment by AllenCoder** [comment]
格式有点乱，看的不是很清晰。加载更多Demo 写有参考示例，参考Demo 调整一下代码试试
