### ISSUE TITLE
BaseQuickAdapter.RequestLoadMoreListener with nested scroll causing pagination problems

### ISSUE THREAD

**Issue by RicardoSnow** [CymChad/BaseRecyclerViewAdapterHelper#2094]
I've been passing through problems when it try to use the BaseQuickAdapter.RequestLoadMoreListener for pagination, but I'm using a recycler view inside a nested scroll.

Can you guys give me a help?
Thanks

**Comment by AllenCoder** [comment]
Nested scrolling is very cumbersome，I suggest you remove the nested layout, if you can not nest, try listening nested, modify the callback method
