### ISSUE TITLE
Footer布局在GridLayoutManager下只在最后一行

### ISSUE THREAD

**Issue by sicelex** [CymChad/BaseRecyclerViewAdapterHelper#2095]
![布局图片](http://i2.bvimg.com/638397/f4b17bb43c32c527.png)
我想把FooterView放在图片的右边该如何实现

`mRecyclerView.setLayoutManager(new GridLayoutManager(mContext, 3));
        mAdapter = new UploadImageAdapter(R.layout.item_add_pic, mList);
        mRecyclerView.setAdapter(mAdapter);
        mAdapter.addFooterView(getFooterView(mRecyclerView, 0, new View.OnClickListener() {
            @Override
            public void onClick(View view) {}
        }));

        private View getFooterView(RecyclerView recyclerView, int type, View.OnClickListener listener) {
            View view = getLayoutInflater().inflate(R.layout.item_default_add_pic, (ViewGroup) recyclerView.getParent(), false);
            view.setOnClickListener(listener);
            return view;
        }`

**Comment by AllenCoder** [comment]
这种布局不适合addFootView,建议用多布局的形式，判断position时显示footView的布局
