### ISSUE TITLE
请问使用多条目adapter，如何实现只刷新数据，不刷新整个视图？

### ISSUE THREAD

**Issue by tjpulord** [CymChad/BaseRecyclerViewAdapterHelper#2096]
在使用BaseMultiItemQuickAdapter时，使用addItemType添加了大概10个左右的布局，页面还有每秒刷新页面功能，但在刷新数据时分别使用了setNewData方法和notifyDataSetChanged方法，页面有闪屏现象，请问使用哪个方法能只刷新数据而不用刷新view，或是怎么解决页面闪屏的现象？

**Comment by AllenCoder** [comment]
通知刷新单条item 用下列api都可以实现
![image](https://user-images.githubusercontent.com/8213915/38067162-d74e06ce-333d-11e8-82fe-242ed5b32848.png)

至于闪屏，可参考，recyclerview刷新闪烁解决方案
