### ISSUE TITLE
convert 方法重复调用问题

### ISSUE THREAD

**Issue by canglen** [CymChad/BaseRecyclerViewAdapterHelper#2098]
recyclerview结合了PagerSnapHelper 使用 设置  LinearLayoutManager.HORIZONTAL
activity 暴露给adapter smoothScrollToPosition(position);方法。
adapter 继承 BaseQuickAdapter
然后在  
convert 里面进行操作后 调用
position 分别 使用了
 helper.getAdapterPosition();
helper.getLayoutPosition();
helper.getPosition();
均有几率出现 convert  调用2次  然后position 出现类似于 9 11这样的跳动，然后 smoothScrollToPosition(position) 就会多滑动位置。
更换继承 RecyclerView.Adapter 后 问题解决 。
新手，不知道问题所在，还请大佬检查解决。

**Comment by AllenCoder** [comment]
convert 方法是被Recyclerview的onBindViewHolder方法的回调的，所以在刷新布局时会多次调用。你的
smoothScrollToPosition(position) 方法应该放在Activity内处理。

**Comment by crossdoit** [comment]
getAdapterPosition:86
getAdapterPosition:87
getAdapterPosition:88
getAdapterPosition:89
getAdapterPosition:87
getAdapterPosition:88
getAdapterPosition:89
getAdapterPosition:90
getAdapterPosition:86
getAdapterPosition:91

确实convert 这里存在问题，一直上滑，位置回乱跳

**Comment by AllenCoder** [comment]
mAdapter.notifyDataSetChanged()会触发全局刷新加载的，可以使用adapter的局部刷新功能

**Comment by canglen** [comment]
为什么更换继承 RecyclerView.Adapter 后 问题就不存在了，其他调用代码完全一致。
另外没有调用adapter.notifyDataSetChanged()
就是recyclerview 结合了PagerSnapHelper  滑动的时候 一次是一页的
但是会出现有几率出现 convert 方法调用2次。

**Comment by AllenCoder** [comment]
```
  @Override
    public void onBindViewHolder(K holder, int position) {
        //Add up fetch logic, almost like load more, but simpler.
        autoUpFetch(position);
        //Do not move position, need to change before LoadMoreView binding
        autoLoadMore(position);
        int viewType = holder.getItemViewType();

        switch (viewType) {
            case 0:
                convert(holder, getItem(position - getHeaderLayoutCount()));
                break;
            case LOADING_VIEW:
                mLoadMoreView.convert(holder);
                break;
            case HEADER_VIEW:
                break;
            case EMPTY_VIEW:
                break;
            case FOOTER_VIEW:
                break;
            default:
                convert(holder, getItem(position - getHeaderLayoutCount()));
                break;
        }
    }
```
convert方法的调用只会发生在recyclerview的onBindViewHolder里面。如果场景相同，理论上调用次数也是一样的

**Comment by WDevaloper** [comment]
目前页遇到这个问题
