### ISSUE TITLE
头部问题

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#210]
请问我在头部放了个banner，实现轮播哦的效果，但是每次刷新，轮播的图片总会再增加，有没有方法可以解决下。

**Comment by Ludejin** [comment]
@wuzhaohui026 这个你可以自己控制banner的图片Item，刷新成功完全能自己清空本来banner的图片，然后再add进去不就行了？

**Comment by wuzhaohui026** [comment]
@Ludejin 我的banner用的也是开源的，我试试可不可以吧，谢谢啊
