### ISSUE TITLE
上拉加载更多问题

### ISSUE THREAD

**Issue by zyxzhangyuxia** [CymChad/BaseRecyclerViewAdapterHelper#2100]
1.第一次进入的时候，customerView总是显示“加载失败，请点我重试”。此时网络状态良好，再次点击的时候也能加载的出来。
2.服务器端的分页加载，通常情况下不知道 TOTAT_COUNT，这个时候做分页加载，怎么做？

求大神指点一下。

**Comment by AllenCoder** [comment]
1 。加载更多要根据具体场景具体设计， 如果不知道Total_count只能不断尝试加载。另外可以参考demo的加载更多
