### ISSUE TITLE
我是MultipleItemRvAdapter的开发者

### ISSUE THREAD

**Issue by chaychan** [CymChad/BaseRecyclerViewAdapterHelper#2103]
已经将代码贡献，也完善了demo，请review，若没有问题请整合，有问题的话，请提出，我可以修改后再提交

**Comment by zhangshaobo87** [comment]
顶

**Comment by AllenCoder** [comment]
相关代码已经合并，有时间补充一下wiki

**Comment by chaychan** [comment]
@AllenCoder wiki我已经写好，只是不知道要怎么提交

**Comment by JGNS** [comment]
你好，能帮看一下2104的问题吗，第二级列表条目会错乱么？

**Comment by AllenCoder** [comment]
@chaychan   查看issue [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2118](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2118)

wiki 需要编辑权限。 你在你的项目里面写好，我到时候直接拷贝过来吧

**Comment by chaychan** [comment]
@AllenCoder 好了，已经在我的项目里写了wiki, README我之前有Pull Request

**Comment by zhaize1115** [comment]
MultipleItemRvAdapter目前不支持拓展ViewHolder，只能使用BaseViewHolder
