### ISSUE TITLE
Remove setEmptyView 

### ISSUE THREAD

**Issue by gokrish6670** [CymChad/BaseRecyclerViewAdapterHelper#2106]
is there any way to remove emptyview?...
i want to remove emptyview when i click the emptyview

errorView = getLayoutInflater().inflate(R.layout.error_view, (ViewGroup) mRecyclerView.getParent(), false);
        errorView.setOnClickListener(view -> {
            onRefresh();
        });
        TextView errorData = errorView.findViewById(R.id.error_view_text);
        errorData.setText("Can't Connect right now");

**Comment by AllenCoder** [comment]
Emptyview does not need to be removed. When there is data, it is not empty and it will automatically disappear.

**Comment by dbacinski** [comment]
If you really have to do it then there is a hack:
`(adapter.emptyView as? FrameLayout)?.removeAllViews()`
