### ISSUE TITLE
adapter中setOnItemClickListener，position为0不执行

### ISSUE THREAD

**Issue by Payaml** [CymChad/BaseRecyclerViewAdapterHelper#2108]
以下是convert方法中的代码
`  //FindView
        ImageView mIvIcon = holder.getView(R.id.item_about_icon);
        TextView mTvText = holder.getView(R.id.item_about_text);

        //setValues
        mIvIcon.setImageResource(bean.getImageResId());
        mTvText.setText(bean.getTextStr());

        //ClickEvent
        setOnItemClickListener((adapter, view, position) -> {
            //此处position为0时不执行
        });`

**Comment by Payaml** [comment]
holder.itemView.setOnClickListener(v -> {
            //这样写的话是都会正常执行的
        });
我不知道这个问题是bug还是我的写法有问题

**Comment by AllenCoder** [comment]
position为0不执行？如果是单独添加的headView 的点击事件是不会在adapter的itemclick里面触发回调的。你是哪种情况？

**Comment by AllenCoder** [comment]
可具体参考demo的[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java)

**Comment by Payaml** [comment]
不是headView，而且headView 的点击事件也不是这样调用的。就是正常的itemView点击事件

**Comment by AllenCoder** [comment]
提供复现demo测试一下

**Comment by Spikoss** [comment]
我也遇到题主一样的问题，而且传值会错乱
 @Override
    protected void convert(BaseViewHolder helper, final OneClickModel.DataBean item) {
        helper.setText(R.id.tv_jiaoyiAmount, String.valueOf(item.getJiaoyiAmount()));
        adapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Intent intent = new Intent();
                intent.setClass(context, OneClickPayDetailActivity.class);
                intent.putExtra("jiaoyiAmount",String.valueOf(item.getJiaoyiAmount()));
                startActivity(intent);
            }
        });}`

**Comment by AllenCoder** [comment]
你把点击事件写在convert方法里面，怎么能正确，请查看demo的点击事件写法，应该写在activity页面
