### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by laizhouyingdixiaoma** [CymChad/BaseRecyclerViewAdapterHelper#2111]
看了所有的相关上拉加载更多问题，但是还是没有搞明白，现在框架里面上拉有两个监听（建议用哪种？），一个是过期的也是demo中用的，但是下拉监听中请求回来然后再请求回调设置loadcomplete无效。另外一个上拉监听是需要传RecycleVIew的，这个里面主要是处理什么逻辑呢？adapter设置数据以及设置收起的操作必须放在这里面吗？另外recycleview起一个Handler定时监听是什么作用呢？真心求解，谢谢。

**Comment by laizhouyingdixiaoma** [comment]
看了所有的相关上拉加载更多问题，但是还是没有搞明白，现在框架里面上拉有两个监听（建议用哪种？），一个是过期的也是demo中用的，但是下拉监听中请求回来然后再请求回调设置loadcomplete无效。另外一个上拉监听是需要传RecycleVIew的，这个里面主要是处理什么逻辑呢？adapter设置数据以及设置收起的操作必须放在这里面吗？另外recycleview起一个Handler定时监听是什么作用呢？真心求解，谢谢。

**Comment by AllenCoder** [comment]
很抱歉这么晚了，才回复你，加载更多请看 https://www.jianshu.com/p/b343fcff51b0。
如果不是很明白，建议直接看源码
