### ISSUE TITLE
滑动删除出现报错

### ISSUE THREAD

**Issue by a598501880** [CymChad/BaseRecyclerViewAdapterHelper#2112]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dd4a815 position=1 id=-1, oldPos=2, pLpos:2 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{a4da01e VFED..... .F....I. 0,1039-1080,1692 #7f080122 app:id/recycler_view_message_list}, adapter:com.jw.android.smartlamp.jwcloud.Adapter.MessageAdapter@4d18bf6, layout:android.support.v7.widget.LinearLayoutManager@c21bbf7, context:com.jw.android.smartlamp.jwcloud.View.MainActivity@12499e6

**Comment by AllenCoder** [comment]
数组索引越界？是Demo报错吗？

**Comment by yedajiang44** [comment]
@AllenCoder 我也出现这问题，不是demo

**Comment by yedajiang44** [comment]
@a598501880 哥们！你解决了吗？

**Comment by a598501880** [comment]
删除之后notifyDataSetChanged一下就好 @yedajiang44
