### ISSUE TITLE
自动加载怎么处理？

### ISSUE THREAD

**Issue by langxing** [CymChad/BaseRecyclerViewAdapterHelper#2116]
设置加载监听之后，会默认加载下一页。所以也就等于初始化的时候，会加载2页数据，但实际上，我们是不需要这个需求的，请问怎么解决？

**Comment by xinyangmaojian** [comment]
同问，我也有这个问题

**Comment by tengya** [comment]
设置这个mQuickAdapter.disableLoadMoreIfNotFullPage(RecyclerView);
有个bug，外层布局是NestedScrollView并且设置recyclerview.setNestedScrollingEnabled(false)后，那个方法会关闭上拉加载，而且不自动打开。不设置我这会无限加载下一页

**Comment by Toasss** [comment]
+1

**Comment by vipheyue** [comment]
注释掉这行就可以了

https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/b209c89b4d1c966997ef088be7b4a050348481ce/library/src/main/java/com/chad/library/adapter/base/BaseQuickAdapter.java#L929
