### ISSUE TITLE
短时间内频繁调用notifyDataSetChanged, setOnItemClickListener点击事件会几率失效

### ISSUE THREAD

**Issue by huangliqiang** [CymChad/BaseRecyclerViewAdapterHelper#2122]
因为我的列表需要实时更新数据，有时候一秒内会有多次刷新数据，调用notifyDataSetChanged。 
然后我设置的setOnItemClickListener 功能主要是给布局setVisible或者setGone， 导致会出现有时候点击失效。（如果去掉实时刷新数据功能，点击事件正常）

**Comment by AllenCoder** [comment]
实时刷新列表这种需求我遇到过，可以说我刷新的场景更严格，10ms数据会更新过来，立即刷新界面，但是后面优化处理，数据过来不是无脑式全量刷新，而是要对比数据差异部分，无论是通过Rxjava的filter还是自定义diffutil要找出数据中的变动部分，然后调用 如下这几个api
![image](https://user-images.githubusercontent.com/8213915/38502786-ea8aad6a-3c42-11e8-8e34-e80fc3d9a410.png)
另外，基于我原来的场景我的点击事件有两套写法的，

```
mRecyclerView.addOnItemTouchListener(new OnItemLongClickListener( ) {
            @Override
            public void onSimpleItemLongClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(RecyclerClickItemActivity.this, "" + Integer.toString(position), Toast.LENGTH_SHORT).show();

            }
        });
```
参考写法
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister)
这种写法对点击的响应不会丢失，但写法上，稍微繁琐

**Comment by AllenCoder** [comment]
局部刷新需要自己处理payloads目前框架没有扩展此功能

**Comment by JasonBtc** [comment]
@huangliqiang  怎么解决的？ 我这边现在也是 实时刷新价格 ，setOnItemChildClickListener的点击事件也会失效

**Comment by JasonBtc** [comment]
@AllenCoder  请问怎么解决这个频繁刷新 点击失效呢？item的局部按钮也是这样，上面那个链接跳不进去了
