### ISSUE TITLE
ExpandableItem如何能实现在item上面伸展/收缩

### ISSUE THREAD

**Issue by zhaize1115** [CymChad/BaseRecyclerViewAdapterHelper#2123]
现在ExpandableItem都是向下的伸展出列表，没有向上的
类似这种场景：列表底部有一个item--“显示更多”，点击后在该item之上呈现“子列表”，再次点击后“子列表”收起来。

**Comment by AllenCoder** [comment]
目前没有过多的精力开发新功能，如果有场景需求，可以酌情自定义adapter
