### ISSUE TITLE
LinearLayoutManager 的 findLastCompletelyVisibleItemPosition一直返回-1

### ISSUE THREAD

**Issue by JeremyHwc** [CymChad/BaseRecyclerViewAdapterHelper#2124]
Issues里面没找到这个问题，就决定提出来了。

现在我这里有一个需求是，RecyclerView竖向装载数据，当RecyclerView 不需要滑动的时候（比如数据只有1条时），我不需要在RecyclerView后面添加FooterView，这个时候我就想到用LinearLayoutManager的findLastCompletelyVisibleItemPosition来和我集合mDatas里面的数据条数作对比，就是
if(linearLayoutManager.findLastCompletelyVisibleItemPosition()<mDatas.size()){
    mAdapter.addFooterView(mFooterView);
}

但是我通过log打印出来linearLayoutManager.findLastCompletelyVisibleItemPosition()返回的结果一直是-1。

想问问这个需求可以用什么方式来实现呀？

**Comment by AllenCoder** [comment]
可以参考如下解决方案 
[https://stackoverflow.com/questions/41054375/why-findlastcompletelyvisibleitemposition-is-returning-1](https://stackoverflow.com/questions/41054375/why-findlastcompletelyvisibleitemposition-is-returning-1)
