### ISSUE TITLE
GridLayoutManager布局中添加头部

### ISSUE THREAD

**Issue by HoneyWorld** [CymChad/BaseRecyclerViewAdapterHelper#2125]
使用recycleview做网格布局时，一排显示两个view，添加头部后，会让我设置的分割线变错乱

**Comment by AllenCoder** [comment]
请看addHeadView源码，添加头部适用于LinearLayoutManager这种情况，GridLayoutManager建议适用多布局

**Comment by HoneyWorld** [comment]
谢谢了，没注意看源码
