### ISSUE TITLE
目前无法支持在多个RecyclerView中共享RecycledViewPool

### ISSUE THREAD

**Issue by DroidWorkerLYF** [CymChad/BaseRecyclerViewAdapterHelper#2128]
如果在多个`RecyclerView`间共享`RecycleViewPool`，目前有bug，比如点击事件只在onCreateViewholder的时候setAdapter，但是点击回调时，holder已经被复用到了另一个RV中，这时候，就全错了，我在convert的时候再次调用了setAdapter方法进行修正，还有像自己添加的footer也有可能因为这样，状态不对

**Comment by AllenCoder** [comment]
目前点击事件不支持多个RecyclerView共享RecycledViewPool的复用，这种情况下，需要自定义点击事件到view绑定
