### ISSUE TITLE
Proguard Issue

### ISSUE THREAD

**Issue by mehrdad1990** [CymChad/BaseRecyclerViewAdapterHelper#2129]
Hi,
I have problem when I obfuscate my application with your library added... I already inserted your proguard settings but still I have this problem.
the problem is that the adapter is not showing anything in recyclerview... basically recyclerview not showing anything while it is actually filled...
what should I do ???

**Comment by mehrdad1990** [comment]
@AllenCoder

**Comment by mehrdad1990** [comment]
the problem is not happening when I disable minify or proguard...it works ok

**Comment by AllenCoder** [comment]
paste your log
