### ISSUE TITLE
 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{3778fee position=4 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}

### ISSUE THREAD

**Issue by lijore** [CymChad/BaseRecyclerViewAdapterHelper#2132]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{3778fee position=4 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
滑动列表出现这异常

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/982](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/982)

**Comment by Jay-ch** [comment]
多半是使用了   mAdapter.data.clear()，一定要在后面加上mAdapter.notifyDataSetChanged()；
mAdapter.data.clear()
mAdapter.notifyDataSetChanged()

**Comment by 0toN** [comment]
> 多半是使用了 mAdapter.data.clear()，一定要在后面加上mAdapter.notifyDataSetChanged()； mAdapter.data.clear() mAdapter.notifyDataSetChanged()
没有用mAdapter.data.clear()，也会这样
