### ISSUE TITLE
BaseMultiItemQuickAdapter 二级列表如何刷新局部

### ISSUE THREAD

**Issue by JGNS** [CymChad/BaseRecyclerViewAdapterHelper#2133]
第二级条目中有个控件的值（下载进度）是动态改变的，来源是下载回调监听。如何刷新？求大佬方案。50RMB酬谢 qq982607522

**Comment by AllenCoder** [comment]
在javabean字段中绑定下载进度字段，当回调发生改变时，找出对应位置改变的bean,刷新单条item即可

**Comment by JGNS** [comment]
多谢回复，我现在做的是在回调中重新给字段赋值，然后直接notifyDataSetChanged，这样效果是实现了；但是您说的刷新单条item的操作在二级列表中没见过，查看了方法有add 和remove，没有直接update的
