### ISSUE TITLE
MultipleItemRvAdapter-bindClick和BaseQuickAdapter-bindViewClickListener冲突了

### ISSUE THREAD

**Issue by zhaize1115** [CymChad/BaseRecyclerViewAdapterHelper#2134]
1.MultipleItemRvAdapter-bindClick在onBind中执行，BaseQuickAdapter-bindViewClickListener在onCreate中执行，所以无论bindViewClickListener中set什么监听，bindClick会把bindViewClickListener中设置的监听器给冲掉。所以使用MultipleItemRvAdapter的话setOnItemClickListener是失效的。
2.bindClick是一定会执行，这点感觉不妥，应该开放出接口来让使用者自己控制bindClick，如果不设置则不setListener，从而就不会出现setOnItemClickListener的问题了。
@chaychan

**Comment by zhaize1115** [comment]
@chaychan

**Comment by chaychan** [comment]
@zhaize1115 我在MultipleItemRvAdapter项目中就有解决这个问题，忘记把更新的代码提交了
