### ISSUE TITLE
setOnItemSwipeListener执行后报IndexOutOfBoundsException

### ISSUE THREAD

**Issue by yedajiang44** [CymChad/BaseRecyclerViewAdapterHelper#2143]
数据源只有一个item的情况下滑动删除执行后RecyclerView的validateViewHolderForOffsetPosition(ViewHolder holder) 抛出异常
```java
if (holder.mPosition < 0 || holder.mPosition >= mAdapter.getItemCount()) {
        throw new IndexOutOfBoundsException("Inconsistency detected. Invalid view holder "
       + "adapter position" + holder + exceptionLabel());
}
```
滑动删除的代码，什么都没做
![qq 20180412114357](https://user-images.githubusercontent.com/25813145/38655364-c0569f9e-3e46-11e8-833d-70f8493d1b20.png)

下面这个是抛异常的地方
![zc w _3 kt 02 vn9p7txw](https://user-images.githubusercontent.com/25813145/38651600-c11391c4-3e34-11e8-82a0-0dd696d40eb5.png)

原因是

```java
if (holder.mPosition < 0 || holder.mPosition >= mAdapter.getItemCount())
```

中
`mAdapter.getItemCount()`
返回0，也就是BaseQuickAdapter的getItemCount()返回0
```java
    public int getItemCount() {
        int count;
        if (getEmptyViewCount() == 1) {
            count = 1;
            if (mHeadAndEmptyEnable && getHeaderLayoutCount() != 0) {
                count++;
            }
            if (mFootAndEmptyEnable && getFooterLayoutCount() != 0) {
                count++;
            }
        } else {
//此处的count为0
            count = getHeaderLayoutCount() + mData.size() + getFooterLayoutCount() + getLoadMoreViewCount();
        }
        return count;
    }
```

**Comment by AllenCoder** [comment]
应该是我们的bug，滑动删除推荐用 [https://github.com/anzaizai/EasySwipeMenuLayout](https://github.com/anzaizai/EasySwipeMenuLayout)
