### ISSUE TITLE
getViewByPosition这个方法不能获取不在屏幕上的item如何解决？

### ISSUE THREAD

**Issue by OathkeeperDL7** [CymChad/BaseRecyclerViewAdapterHelper#2145]
如何获取包括不可见得条目view？

**Comment by lhl-012** [comment]
不知道你使用的场景是什么？这是recyclerview的一个方法
 public ViewHolder findViewHolderForLayoutPosition(int position) {
        return findViewHolderForPosition(position, false);
    }
可能是false的原因   但是findViewHolderForPosition(position, false);是私有的

**Comment by lhl-012** [comment]
如果需要扩展  自己看代码修改

**Comment by OathkeeperDL7** [comment]
@lhl-012 我是动态添加一个item，然后里面有editText，全部输入之后点击保存，获取所有的item里的数据，但是不可见的item用getViewByPosition获取里面的editText会报空指针

**Comment by lhl-012** [comment]
@OathkeeperDL7    第三条 那是recycler的方法   自己去修改实现吧
