### ISSUE TITLE
实体类集成  SectionEntity 后 fastjson报错问题

### ISSUE THREAD

**Issue by canglen** [CymChad/BaseRecyclerViewAdapterHelper#2146]
com.alibaba.fastjson.JSONException: default constructor not found. 
说没有默认构造函数。
但是继承SectionEntity  后是没办法添加不带参数的默认构造函数的。。
不知道如何解决，有处理过的大佬还请指点。

**Comment by canglen** [comment]
换成使用GSON 来解析后可以了，可能是 fastjson 的特殊性吧。
他们应该都是通过反射来解析的吧？但是不知道为什么会有这个区别。

**Comment by lhl-012** [comment]
public abstract class SectionEntity<T> implements Serializable {
    public boolean isHeader;
    public T t;
    public String header;

    public SectionEntity(boolean isHeader, String header) {
        this.isHeader = isHeader;
        this.header = header;
        this.t = null;
    }

    public SectionEntity(T t) {
        this.isHeader = false;
        this.header = null;
        this.t = t;
    }
}
三个参数2个可以去掉，但是连T，就是真实的数据都去掉，应该是不合理的吧。

**Comment by canglen** [comment]
继承SectionEntity 后  好像添加不上空构造方法的。

**Comment by wenshuo001** [comment]
我的也是这样
