### ISSUE TITLE
怎样设置HeaderView的高度？

### ISSUE THREAD

**Issue by zhangshuliang** [CymChad/BaseRecyclerViewAdapterHelper#2148]
@CymChad   你好，想问下比如我的RecyclerView的item的高度70dp,我要给这个RecyclerView添加一个高200dp的header（其实就是一张图片），但是我添加后，发现HeaderView的高度并不是200dp，而是和我的item的高度一样的。求解，谢谢

**Comment by 490965536** [comment]
我也遇到这个问题了... 你解决了么...

**Comment by zhangshuliang** [comment]
已经解决，是我自己写的HeaderView的布局的问题，布局要嵌套一层，如果直接在跟布局设置高度，不起作用
