### ISSUE TITLE
条目不能完全隐藏

### ISSUE THREAD

**Issue by jestar719** [CymChad/BaseRecyclerViewAdapterHelper#215]
通过getConvertView.setVisible(View.GONE)来隐藏条目.但是条目虽然隐藏了,但仍占了位置.

**Comment by CymChad** [comment]
这样隐藏item，为什么不直接rm？

**Comment by CymChad** [comment]
这样我觉得和它的机制有关，如果是的话，那么用原始的adapter应该也是一样的效果。

**Comment by CymChad** [comment]
我测试过了，原始的adapter也是一样的，我的理解是这样的，因为adapter他遍历出来的时候就计算好高度了，你只是setVisible(View.GONE)的话只会隐藏item，但是不会重新绘制整个RV。

**Comment by CymChad** [comment]
除非你rm某一个条目
