### ISSUE TITLE
分组布局如何实现拖拽？

### ISSUE THREAD

**Issue by parcool** [CymChad/BaseRecyclerViewAdapterHelper#2152]
看了所有Issues，好像没人提到过这个问题？
需求是：一个分组里的Item只能在当前Item之间拖动，但是父级的item之间需要带上自己的子级们一起拖动换顺序。如何实现呢？

**Comment by AllenCoder** [comment]
自定 ItemTouchHelper.Callback

**Comment by inke3c** [comment]
> 看了所有Issues，好像没人提到过这个问题？
> 需求是：一个分组里的Item只能在当前Item之间拖动，但是父级的item之间需要带上自己的子级们一起拖动换顺序。如何实现呢？

分组如何拖动？拖拽必须要继承BaseItemDraggableAdapter，分组必须要继承BaseSectionQuickAdapter，只能单继承呀
