### ISSUE TITLE
空布局显示有问题,没有全屏,

### ISSUE THREAD

**Issue by caoeryang** [CymChad/BaseRecyclerViewAdapterHelper#2154]
<android.support.v7.widget.RecyclerView
            android:id="@+id/recycleView_free"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/shape_corner_10_white"
            android:nestedScrollingEnabled="false"
            android:overScrollMode="never"
            android:paddingBottom="15dp"
            android:paddingLeft="15dp"
            android:paddingRight="15dp"
            />

空布局如下:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
<ImageView
    android:src="@mipmap/ic_launcher"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
</LinearLayout>

**Comment by caoeryang** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
<ImageView
    android:src="@mipmap/ic_launcher"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
</LinearLayout>

**Comment by caoeryang** [comment]
空布局的最外层也是match_parent

**Comment by LiHexiang** [comment]
解决了吗

**Comment by AllenCoder** [comment]
空布局的全屏是match_parent，是撑满你的recyclerview的包裹区域，你全屏要设置你的Activity

**Comment by LiHexiang** [comment]
“你全屏要设置你的Activity”这句话怎么理解，怎么设置Activity？
