### ISSUE TITLE
addOnItemTouchListener获取到错误的position

### ISSUE THREAD

**Issue by huangliqiang** [CymChad/BaseRecyclerViewAdapterHelper#2155]
version 2.9.38 
 ` recycle.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                L.e("test", "position = "+ i);    
            }
        });`

有时候获取到的position不正确，获取到错误的position。不知道是不是因为adapter.notifyDataSetChanged() 刷新频率太快，实时更新数据一秒会调用多次刷新，跟这个有关系吗

**Comment by AllenCoder** [comment]
刷新过快，会有这个问题，实时刷新，不应该整个界面的全部刷新，应该使用局部刷新

**Comment by huangliqiang** [comment]
@AllenCoder 局部刷新是指刷新部分item整个view还是item的某些view刷新呢？此库貌似没有提供局部刷新的方法吧？

**Comment by AllenCoder** [comment]
局部刷新item
