### ISSUE TITLE
adapter.addHeaderView后，没有下拉刷新

### ISSUE THREAD

**Issue by xiaoxing1992** [CymChad/BaseRecyclerViewAdapterHelper#2156]
使用的是SwipeRefreshLayout+Recyclerview 
-----adapter.addHeaderView后，点击消息通知隐藏，，然后就没有下拉刷新了，而且添加头布局默认还不能隐藏 ，只要一隐藏就没下拉刷新  ，上啦加载没问题

**Comment by AllenCoder** [comment]
添加的头布局不需要了，需要调用adapter.removeHeadrView
