### ISSUE TITLE
调用notifyItemChanged更新单个item报错

### ISSUE THREAD

**Issue by adminLiu-s** [CymChad/BaseRecyclerViewAdapterHelper#2157]
![image](https://user-images.githubusercontent.com/11938143/38797988-df3a852a-4192-11e8-9b3d-b891d6dad57e.png)

**Comment by franklee315** [comment]
怎么解决的？

**Comment by luyun181** [comment]
解决了吗？

**Comment by ggyg123** [comment]
我也遇到了

**Comment by 957919019** [comment]
似乎是因为刷新的时候Item没有显示在界面造成的，或者是你添加了header造成的

**Comment by shichaohui** [comment]
position 传错了吧。传入的 position 的值要包含 headView 的数量。
`int postion = mData.indexOf(item) + mAdapter.getHeaderLayoutCount()`

**Comment by 957919019** [comment]
谢谢，没想到框架异常好用，直接用mData保存数据就可以了，我是用这个refreshNotifyItemChanged(i);调用的，谢谢
