### ISSUE TITLE
设置空布局没效果，跟实例一样的呢 苦恼

### ISSUE THREAD

**Issue by minmei** [CymChad/BaseRecyclerViewAdapterHelper#2159]
viewEmpty = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) recyclerView.getParent(), false);

mAdapter.setEmptyView(viewNetError);

设置数据的时候确定列表已经为空了，不知道为什么就是不显示

**Comment by VincentYD** [comment]
下面加上mAdapter.setNewData(null);

**Comment by minmei** [comment]
已经加了  mAdapter.setNewData(new ArrayList());也试过了  真的是醉了

**Comment by AllenCoder** [comment]
参照demo的EmptyView调试一下你的代码试下效果

**Comment by minmei** [comment]
谢谢回复，不过还是不行，感觉这个地方有bug呢

**Comment by ihewro** [comment]
我也是这样，不过最后通过多次排查问题（花了好长时间哈哈哈），发现的问题所在，我的adpater里面有这样一段代码：

```
@Override
    public int getItemCount() {
        return moduleList.size();
    }
```

是以前用普通adapter遗留的，就没删，发现删掉了就可以了！！不知道能否给楼主帮助

也想问下是为什么呢？@AllenCoder  @minmei

**Comment by AllenCoder** [comment]
空布局会去调用list.size会和系统的空布局处理机制冲突，不能重写
