### ISSUE TITLE
addData和setNewData区别

### ISSUE THREAD

**Issue by cjcj125125** [CymChad/BaseRecyclerViewAdapterHelper#2162]
刚才碰到个奇怪的问题，看到大佬的文档中写的是当加载更多后再调刷新时候要用setNewData来填充数据，但是我发现他们里面的参数类型不一样，这就导致我再不同类型的item的时候，刷新调用setNewData的时候提示不能强制转换类型，但是addData就可以，因为addData的类型是Collection<? extends T> newData 
而setNewData是List<T> data  ，希望大佬指点，谢谢
![qq 20180417230304](https://user-images.githubusercontent.com/20206579/38878431-84b30bca-4293-11e8-9f25-cf0a994edce5.png)

**Comment by AllenCoder** [comment]
addData有三个重载函数，其中的一个是添加一个数据集
```
  @Deprecated
    public void add(@IntRange(from = 0) int position, @NonNull T item) {
        addData(position, item);
    }

    /**
     * add one new data in to certain location
     *
     * @param position
     */
    public void addData(@IntRange(from = 0) int position, @NonNull T data) {
        mData.add(position, data);
        notifyItemInserted(position + getHeaderLayoutCount());
        compatibilityDataSizeChanged(1);
    }

    /**
     * add one new data
     */
    public void addData(@NonNull T data) {
        mData.add(data);
        notifyItemInserted(mData.size() + getHeaderLayoutCount());
        compatibilityDataSizeChanged(1);
    }
```
setNewData的意思是重新设置一个新的数据源，所以要求数据源是一个List<T>的类型
如果你的adapter传入的数据就是List<com.tgyx.bbs.entity.Record> 需要你重新包装数据

**Comment by cjcj125125** [comment]
为了避免麻烦，我还是用addData好了，我在addData之前先clean所有数据，然后再notifyDataSetChanged，好像是可以的
