### ISSUE TITLE
在我的项目里面或者在你们的demo里面，animation界面里面recylerview子条目设置水波纹效果无效啊  

### ISSUE THREAD

**Issue by Blizzard-liu** [CymChad/BaseRecyclerViewAdapterHelper#2163]

**Comment by AllenCoder** [comment]
demo的运行也不正常吗？资源设置要放在v21文件下，另外水波纹效果是从5.1之后才系统支持的？

**Comment by Blizzard-liu** [comment]
demo里面 就animation模块设置了也不显示  其他模块都有的

**Comment by Blizzard-liu** [comment]
百思不得骑姐

**Comment by AllenCoder** [comment]
点击事件用的是哪个？

**Comment by Blizzard-liu** [comment]
还没设置点击事件呢

**Comment by Blizzard-liu** [comment]
adapter.setOnItemChildClickListener（） 设置了一个条目子控件的点击事件

**Comment by AllenCoder** [comment]
demo的animation是设置了其他动画效果所以没有水波纹，
ItemClick界面的item支持水波纹效果 ，看实验demo查看

**Comment by Blizzard-liu** [comment]
那就是设置了动画就没有水波纹了是吗 两者不能共存？

**Comment by Blizzard-liu** [comment]
ItemClick界面也开启了动画 但是有水波纹 为啥animation没有  我的项目里面现在也搞不出来水波纹了

**Comment by Blizzard-liu** [comment]
pulltorefresh界面和animation界面共用一套布局的 pulltorefresh就有水波纹 而且有动画

**Comment by AllenCoder** [comment]
不是不能共存，是没有特殊设置，itemClick的背景设置了水波纹效果

**Comment by Blizzard-liu** [comment]
请问找到原因了吗

**Comment by AllenCoder** [comment]
不是bug,是两个点击事件的原理不一样。ItemClick界面的水波纹是使用adapter.setOnItemClick，波纹效果是系统原生实现的，而pulltorefresh界面的点击事件是
```
mRecyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(final BaseQuickAdapter adapter, final View view, final int position) {
                Toast.makeText(PullToRefreshUseActivity.this, Integer.toString(position), Toast.LENGTH_LONG).show();
            }
        });
```
水波纹是开发者代码控制的水波纹效果，在动画效果上跟系统有出入，点击系统没有特殊的场景需求建议直接用 adapter.setOnItemClickListener

**Comment by Blizzard-liu** [comment]
谢谢
