### ISSUE TITLE
BaseQuickAdapter<HashMap<String, String>>

### ISSUE THREAD

**Issue by iagocanalejas** [CymChad/BaseRecyclerViewAdapterHelper#217]
I don't know if this is a bug or it's me missing something but i will try to splain it simplifying my code.

I am using an adapter extending `BaseQuickAdapter<HashMap<String, String>>`, and my convert function is like:

`@Override`
`    protected void convert(BaseViewHolder holder, HashMap<String, String> item) {`
`       Log.d(TAG, "convert: " + item);`
`       View v = holder.itemView.findViewWithTag("postalCode");`
`       holder.setText(v.getId(), item.get("postalCode"));`
`   }`

Here comes the problem. When my List<HashMap<String,String> have length 1 like:

`hash1.put("postalCode", "1");`
`array.add(hash1);`
`adapter = new AdapterTasksDetails(itemView, a);`

My log output is correct:
> D/BaseQuickAdapter: convert: {postalCode=1}

When my  List<HashMap<String,String> grows the problem appears. Having length = 2:

`hash1.put("postalCode", "1");`
`hash2.put("postalCode", "2");`
`array.add(hash1);`
`array.add(hash2);`
`adapter = new AdapterTasksDetails(itemView, a);`

My log output become:
> D/BaseQuickAdapter: convert: {postalCode=1}
> D/BaseQuickAdapter: convert: {postalCode=2}
> D/BaseQuickAdapter: convert: {postalCode=1}
> D/BaseQuickAdapter: convert: {postalCode=2}
> D/BaseQuickAdapter: convert: {postalCode=1}

And having length = 3:

`hash1.put("postalCode", "1");`
`hash2.put("postalCode", "2");`
`hash3.put("postalCode", "3");`
`array.add(hash1);`
`array.add(hash2);`
`array.add(hash3);`
`adapter = new AdapterTasksDetails(itemView, a);`

My log output become:
> D/BaseQuickAdapter: convert: {postalCode=1}
> D/BaseQuickAdapter: convert: {postalCode=2}
> D/BaseQuickAdapter: convert: {postalCode=3}
> D/BaseQuickAdapter: convert: {postalCode=2}
> D/BaseQuickAdapter: convert: {postalCode=1}
> D/BaseQuickAdapter: convert: {postalCode=2}
> D/BaseQuickAdapter: convert: {postalCode=3}
> D/BaseQuickAdapter: convert: {postalCode=2}
> D/BaseQuickAdapter: convert: {postalCode=1}

In all cases just the last element is showed in the view. Thank you for your time.

**Comment by CymChad** [comment]
Please post all of the code

**Comment by CymChad** [comment]
You can check your data structure

**Comment by iagocanalejas** [comment]
This is the main activity:

`
public class ActivityTaskDetails extends AppCompatActivity {

    private static final String TAG = "ActivityTaskDetails";

    public static final String EXTRA_TASK = "task";

    private AdapterTasksDetails adapter = null;
    private Task selectedTask = null;

    @BindView(R.id.recyclerDetails)
    RecyclerView recyclerView;
    @BindView(R.id.btn_submit)
    ActionProcessButton submitButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_task_details);
        ButterKnife.bind(this);

        selectedTask = getIntent().getExtras().getParcelable(EXTRA_TASK);

        try {
            JSONObject jsonView = new JSONObject(selectedTask.getAndroidView().toString());
            Log.d(TAG, "onCreate: " + jsonView);
            Log.d(TAG, "onCreate: " + selectedTask.getData());
            View itemView = DynamicView.createView(this, jsonView, ViewHolder.class);
            adapter = new AdapterTasksDetails(itemView, selectedTask.getData());
            recyclerView.setAdapter(adapter);
            recyclerView.setHasFixedSize(false);
            recyclerView.setLayoutManager(new LinearLayoutManager(this));
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }


    public static class ViewHolder{

    }
`

Adapter code:

`
public class AdapterTasksDetails extends BaseQuickAdapter<HashMap<String, String>> {

    View view;
    AdapterTasksDetails adapter;
    int pc, name;

    public AdapterTasksDetails(View contentView, List<HashMap<String, String>> data) {
        super(contentView, data);
        this.view = contentView;
        adapter = this;
        name = view.findViewWithTag("name").getId();
        pc = view.findViewWithTag("postalCode").getId();
    }

    @Override
    protected void convert(BaseViewHolder holder, HashMap<String, String> item) {
        holder.setText(name, item.get("name"))
                .setText(pc, item.get("postalCode"));
        Log.d(TAG, "convert: " + item);
    }
}
`

Task entity
`
public class Task implements Parcelable {
    private long id;
    private String description;
    private float latitude;
    private float longitude;
    private TaskType taskType;
    private Date limitDate;
    private float prize;
    private List<HashMap<String,String>> data;
    private JsonObject androidView;

    private Task(Parcel in) {
        id = in.readLong();
        description = in.readString();
        latitude = in.readFloat();
        longitude = in.readFloat();
        taskType = (TaskType) in.readSerializable();
        limitDate = (Date) in.readSerializable();
        prize = in.readFloat();

        data = new ArrayList<>();
        in.readList(data, List.class.getClassLoader());
        androidView = new JsonParser().parse(in.readString()).getAsJsonObject();
    }

    //Getter Setter

    @Override
        public int describeContents() {
            return 0;
        }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(id);
        parcel.writeString(description);
        parcel.writeFloat(latitude);
        parcel.writeFloat(longitude);
        parcel.writeSerializable(taskType);
        parcel.writeSerializable(limitDate);
        parcel.writeFloat(prize);
        parcel.writeList(data);
        parcel.writeString(androidView.toString());
    }

    public static final Parcelable.Creator<Task> CREATOR
            = new Parcelable.Creator<Task>() {
        public Task createFromParcel(Parcel in) {
            return new Task(in);
        }

        public Task[] newArray(int size) {
            return new Task[size];
        }
    };
`

**Comment by CymChad** [comment]
You print the dataSzie
```
Log.d(TAG, "convert: " + item + "dataSize" + mData.size());
```

**Comment by iagocanalejas** [comment]
Size is correct for all examples i have

**Comment by CymChad** [comment]
I tested the normal

**Comment by CymChad** [comment]
MyData
```java
public static List<HashMap<String, String>> getData() {
        List list = new ArrayList<String>();
        for (int i = 0; i < 3; i++) {
            HashMap has = new HashMap<String, String>();
            has.put("data" + i,"data" + i);
            list.add(has);
        }
        return list;
    }
```
MainActivity
```java
 recyclerView = (RecyclerView) findViewById(R.id.rv);
recyclerView.setLayoutManager(new LinearLayoutManager(this));
QuickAdapter adapter = new QuickAdapter(MyData.getData());
recyclerView.setAdapter(adapter);
```
Adapter
```java
public class QuickAdapter extends BaseQuickAdapter<HashMap<String, String>> {
    public QuickAdapter(List<HashMap<String, String>> data) {
        super(R.layout.item_view, data);
    }

    @Override
    protected void convert(BaseViewHolder baseViewHolder, HashMap<String, String> s) {
        //    baseViewHolder.getLayoutPosition();
        Log.e("x", "" + s);
//        baseViewHolder.setText(R.id.tv, s.get("da"))
//                .setOnClickListener(R.id.tv, new OnItemChildClickListener())
//                .setOnClickListener(R.id.iv, new OnItemChildClickListener());

    }
}

```
