### ISSUE TITLE
BaseMultiItemQuickAdapter二级列表时，在convert方法里默认展开某些布局时，出现常见的错误

### ISSUE THREAD

**Issue by xiaschina** [CymChad/BaseRecyclerViewAdapterHelper#2174]
cannot call this method while recyclerview is computing a layout or scrolling

**Comment by AllenCoder** [comment]
参考处理办法
1. [https://stackoverflow.com/questions/27070220/android-recyclerview-notifydatasetchanged-illegalstateexception](https://stackoverflow.com/questions/27070220/android-recyclerview-notifydatasetchanged-illegalstateexception)
2. [https://www.jianshu.com/p/353d401fbd99](https://www.jianshu.com/p/353d401fbd99)
