### ISSUE TITLE
新版本2.9.38中新增的多布局的BaseItemProvide缺少两个重要方法

### ISSUE THREAD

**Issue by lhj1079947827** [CymChad/BaseRecyclerViewAdapterHelper#2176]
在新增的多布局改进的新版本2.9.38 中的BaseItemProvide缺少两个重要方法，分别是viewType()和layout()方法，子类继承它和没有重写这个两个方法的，不能实现多布局问题。
![1](https://user-images.githubusercontent.com/20966610/39164817-0789e1d4-47b4-11e8-97ea-95fc9c00152e.png)
![2](https://user-images.githubusercontent.com/20966610/39164819-0b909b42-47b4-11e8-8a0e-119557141731.png)

**Comment by Jsonjia** [comment]
![qq 20180424133813](https://user-images.githubusercontent.com/11712648/39168045-ef1a49ca-47c4-11e8-8d3d-fc9d6d423dfa.png)
![qq 20180424133823](https://user-images.githubusercontent.com/11712648/39168059-fa5879a6-47c4-11e8-9571-a467515ffa53.png)
新版本2.9.38中缺少viewType()和layout()，但是下载的demo有这2个方法

**Comment by lhl-012** [comment]
已确认   等待回复

**Comment by AllenCoder** [comment]
已发布新版
