### ISSUE TITLE
瀑布流的一点疑问

### ISSUE THREAD

**Issue by yzjsbsb** [CymChad/BaseRecyclerViewAdapterHelper#2177]
想做一个两列的瀑布流，左列的item是一种样式A(20*20的正方形)，右列的item是样式B(16*16的正方形)
但是做出来的均是左右交错的。请问怎么实现比较好

**Comment by lhl-012** [comment]
瀑布流是grid模式的    需求与adapter无关   可以尝试看看阿里开源的那个vlayout   @AllenCoder   close
