### ISSUE TITLE
convert debug进不去

### ISSUE THREAD

**Issue by zhujiabin** [CymChad/BaseRecyclerViewAdapterHelper#2178]
convert debug进不去，也不知道为啥？

**Comment by lhl-012** [comment]
尝试打log   as可能有bug  我也遇到过  但是这不是代码的问题

**Comment by lhl-012** [comment]
@AllenCoder   close

**Comment by wosika** [comment]
我也遇到了，小米手机上不运行convert方法。华为、安卓模拟器没有问题。不知道为什么找了很久

**Comment by AllenCoder** [comment]
想debug代码，可以直接拉源代码依赖调试，gradle拉下来的aar调试时跳转顺序可能不一致
