### ISSUE TITLE
正式打包的时候出现异常  java.util.zip.ZipException: duplicate entry: com/chad/library/BuildConfig.class

### ISSUE THREAD

**Issue by WinnerLi** [CymChad/BaseRecyclerViewAdapterHelper#2179]
![image](https://user-images.githubusercontent.com/18546315/39221247-66ea4f2e-4868-11e8-8cf6-93759addce57.png)

![image](https://user-images.githubusercontent.com/18546315/39221268-89d4da7c-4868-11e8-9032-24384cdad418.png)

**Comment by lhl-012** [comment]
https://blog.csdn.net/hexingen/article/details/74065796
上面图中发现你并未引用BaseRecyclerViewAdapterHelper
