### ISSUE TITLE
如果设置了HeaderView，再动态设置setEmptyView会崩，怎么去处理正在加载时不让他显示空布局？

### ISSUE THREAD

**Issue by qinxianyuzou** [CymChad/BaseRecyclerViewAdapterHelper#2180]
如果设置了HeaderView，再动态设置setEmptyView，在遇到只有HeaderView没有其他数据的时候会崩，不设置HeaderView则不会崩，如果说setEmptyView不能动态去处理，那么怎么去处理正在加载时不让他显示空布局？我首次进入这个页面第一次加载数据时必然不能显示空布局，但是如果不动态设置，那么一进来就会直接显示，直到数据加载完成刷新数据，这样的体验是很不好的。

**Comment by lhl-012** [comment]
贴出你的关键代码和相应报错日志
