### ISSUE TITLE
BaseMultiItemQuickAdapter这个Adapter 可以取消展开子项时的动画吗，策划说太卡求帮忙

### ISSUE THREAD

**Issue by liuhang12138** [CymChad/BaseRecyclerViewAdapterHelper#2185]

**Comment by lance1992kun** [comment]
使用这个方法  默认position的方法是带动画的  你传入false就没动画了
/**
     * Expand an expandable item
     *
     * @param position position of the item, which includes the header layout count.
     * @param animate  expand items with animation
     * @return the number of items that have been added.
     */
    public int expand(@IntRange(from = 0) int position, boolean animate) {
        return expand(position, animate, true);
    }

**Comment by liuhang12138** [comment]
抱歉，前几天比较忙，忘了回复了，已找到此方法，感谢作者分享
