### ISSUE TITLE
使用BaseMultiItemQuickAdapter做伸缩控件

### ISSUE THREAD

**Issue by zhangyong5566** [CymChad/BaseRecyclerViewAdapterHelper#2187]
使用BaseMultiItemQuickAdapter做伸缩控件，层级只有2级（一个主一个子），子布局放spinner有时候收缩不隐藏，缩回去了，但是那个三角还在原来的地方必须点击其他条目伸缩才会刷新消失。。这是不是框架的bug？

**Comment by AllenCoder** [comment]
检查数据层model 的隐藏控制是否正确
