### ISSUE TITLE
ScrollView嵌套RecyclerView，一进页面就一直在回调onLoadMoreRequested这个方法，有什么方法可以解决么？

### ISSUE THREAD

**Issue by lijingxin888** [CymChad/BaseRecyclerViewAdapterHelper#2190]

**Comment by DancingSnowInFingertips** [comment]
如果你要加载更多的话，我现在就找到一种方法，就是直接监听NestedScrollView的滑动监听
 scrollView.setOnScrollChangeListener(new NestedScrollView.OnScrollChangeListener() {
            @Override
            public void onScrollChange(NestedScrollView v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {
                if (scrollY == (v.getChildAt(0).getMeasuredHeight() - v.getMeasuredHeight())) {
                    new Handler().postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            //数据刷新
                        }
                    }, 1500);
                }
            }
        });

**Comment by lijingxin888** [comment]
我现在就是用这种方法解决了

**Comment by lijingxin888** [comment]
但是我看它已经修复了源码这个问题，但是拉下来最新的代码BaseQuickAdapter里面的方法并没有改动，作者是还没有提交代码，更新代码么？

**Comment by lijingxin888** [comment]
<img width="1290" alt="2018-05-08 5 38 54" src="https://user-images.githubusercontent.com/20985414/39751887-4617c270-52ec-11e8-98ee-7a1bf9441865.png">
这是修改代码的截图。

**Comment by AllenCoder** [comment]
已更新，暂未发布
