### ISSUE TITLE
header和footer有margin 但是添加了没有

### ISSUE THREAD

**Issue by simplepeng** [CymChad/BaseRecyclerViewAdapterHelper#2195]
public int addHeaderView(View header, int index, int orientation) {
        if (mHeaderLayout == null) {
            mHeaderLayout = new LinearLayout(header.getContext());
            if (orientation == LinearLayout.VERTICAL) {
                mHeaderLayout.setOrientation(LinearLayout.VERTICAL);
                mHeaderLayout.setLayoutParams(new LayoutParams(MATCH_PARENT, WRAP_CONTENT));
            } else {
                mHeaderLayout.setOrientation(LinearLayout.HORIZONTAL);
                mHeaderLayout.setLayoutParams(new LayoutParams(WRAP_CONTENT, MATCH_PARENT));
            }
        }

确定这个不改成header的layoutParams吗？

**Comment by AllenCoder** [comment]
header或者footer最终都是添加到一个大的LinearLayout，margin应该添加在headview上面
