### ISSUE TITLE
extends BaseMultiItemQuickAdapter 实现局部刷新可以出个demo吗？或者哪个大佬实现了，请指教。

### ISSUE THREAD

**Issue by bingdu0** [CymChad/BaseRecyclerViewAdapterHelper#2198]
extends BaseMultiItemQuickAdapter 局部刷新可以出个demo吗？或者哪个大佬实现了，请指教。

**Comment by bingdu0** [comment]
@supperyan  extends BaseMultiItemQuickAdapter 后，有好多种布局样式，最后的一种样式是评论的样式，现在发表新评论，新评论内容我要怎么刷新出来？也就是说，我只想刷新 评论的样式的布局。
![comment](https://user-images.githubusercontent.com/13532640/39557764-89b7f7fe-4ebc-11e8-8ebc-ce032c999efa.jpg)
没有找到什么方法，忘指教！

**Comment by supperyan** [comment]
使用的时候你应该是按照type来判断使用哪个布局的，既然你type已经定义好对应的布局了，新添加的评论你只需要给type写成自己想要的布局对应的type就行了啊。
添加成功以后，直接adapter.addData()。

**Comment by bingdu0** [comment]
@supperyan @liuhang12138  adapter.addData() 是添加数据，我现在的问题是，我点了发表按钮之后，评论接口返回最新的三条数据，我调用addData的话，就成了6条数据了。DiffUtil 是将全部数据传进去比较才可以更新吧？
