### ISSUE TITLE
当用StaggeredGridLayoutManager时用使用emptyview时不能占整行

### ISSUE THREAD

**Issue by xionghao1991** [CymChad/BaseRecyclerViewAdapterHelper#22]
setEmptyView 没有考虑StaggeredGridLayoutManager或者GridLayoutManager的情况可以考虑在重写onViewAttachedToWindow

` 

        if (holder.getItemViewType() == EMPTY_VIEW) {
            if (holder.itemView.getLayoutParams() instanceof StaggeredGridLayoutManager.LayoutParams) {
                StaggeredGridLayoutManager.LayoutParams params = (StaggeredGridLayoutManager.LayoutParams) holder.itemView.getLayoutParams();
                params.setFullSpan(true);
            }
        }
    
`

**Comment by CymChad** [comment]
收到，你提个pr我合并一下？

**Comment by CymChad** [comment]
今天我加一下吧

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.7.0'
	}

bug 已修复

**Comment by YooTrepeat** [comment]
我遇到的EmptyView和ErrorView类似问题，LinearLayoutManager,如果RecyclerView设置了ItemDecoration,且第一个item设置了top或者所有item底部都设置了bottom，那么EmptyView或者ErrorView也会有top、bottom，不能占满recyclerview区域
