### ISSUE TITLE
多itemtype的时候可以做成面向接口编程。

### ISSUE THREAD

**Issue by ZippoZeng** [CymChad/BaseRecyclerViewAdapterHelper#220]
MultiItemEntity 这个是个抽象类，java中只能继承一个类，如果自己项目里面逻辑有集成一个basemodel的话，这个MultiItemEntity就不能继承了，所以可以考虑改成面向接口编程，可能效果会好一点。

**Comment by CymChad** [comment]
恩，可以的。

**Comment by CymChad** [comment]
多谢建议。
