### ISSUE TITLE
侧滑如何做成类似QQ的效果呀

### ISSUE THREAD

**Issue by piaosan6** [CymChad/BaseRecyclerViewAdapterHelper#2201]
这个侧滑如何做成类似QQ的效果呀，我看demo是直接就删除了，一般都要出个选项啥的吧

**Comment by AllenCoder** [comment]
侧滑本身是第三方功能，可以根据demo提供的侧滑思路深度定制或者结合 [https://github.com/anzaizai/EasySwipeMenuLayout](https://github.com/anzaizai/EasySwipeMenuLayout)
