### ISSUE TITLE
如何对固定position禁止拖拽

### ISSUE THREAD

**Issue by Whatgbc** [CymChad/BaseRecyclerViewAdapterHelper#2202]
如题，想要把最后一项固定住不能随便拖拽。

**Comment by Whatgbc** [comment]
ItemDragAndSwipeCallback callback=new ItemDragAndSwipeCallback(menuAdapter){
            @Override
            public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder source, RecyclerView.ViewHolder target) {
                if(source.getLayoutPosition()==8||target.getLayoutPosition()==8){
                    return false;
                }
                return super.onMove(recyclerView, source, target);
            }
        };

大概这样，但是仍可以做拖拽动作。。

**Comment by gaojian89** [comment]
> ItemDragAndSwipeCallback callback=new ItemDragAndSwipeCallback(menuAdapter){
> @override
> public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder source, RecyclerView.ViewHolder target) {
> if(source.getLayoutPosition()==8||target.getLayoutPosition()==8){
> return false;
> }
> return super.onMove(recyclerView, source, target);
> }
> };
> 
> 大概这样，但是仍可以做拖拽动作。。

还需要在setToggleDragOnLongPress（）中写类似的逻辑
@Override
    public void setToggleDragOnLongPress(boolean longPress) {
        mDragOnLongPress = longPress;
        if (mDragOnLongPress) {
            mOnToggleViewTouchListener = null;
            mOnToggleViewLongClickListener = new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    if (mItemTouchHelper != null && itemDragEnabled) {
                        if(getViewHolderPosition((RecyclerView.ViewHolder) v.getTag(com.chad.library.R.id.BaseQuickAdapter_viewholder_support)） == 8) {
                            mItemTouchHelper.startDrag((RecyclerView.ViewHolder) v.getTag(com.chad.library.R.id.BaseQuickAdapter_viewholder_support));
                        }

                    }
                    return true;
                }
            };
        } else {
            mOnToggleViewTouchListener = new View.OnTouchListener() {
                @Override
                public boolean onTouch(View v, MotionEvent event) {
                    if (MotionEventCompat.getActionMasked(event) == MotionEvent.ACTION_DOWN
                            && !mDragOnLongPress) {
                        if (mItemTouchHelper != null && itemDragEnabled) {
                            if(getViewHolderPosition((RecyclerView.ViewHolder) v.getTag(com.chad.library.R.id.BaseQuickAdapter_viewholder_support)） == 8) {
                                mItemTouchHelper.startDrag((RecyclerView.ViewHolder) v.getTag(com.chad.library.R.id.BaseQuickAdapter_viewholder_support));
                            }
                        }
                        return true;
                    } else {
                        return false;
                    }
                }
            };
            mOnToggleViewLongClickListener = null;
        }
    }
