### ISSUE TITLE
 onLoadMoreRequested() 有的时候不执行

### ISSUE THREAD

**Issue by caoeryang** [CymChad/BaseRecyclerViewAdapterHelper#2205]
public void onSuccess(Response<BaseBean<List<LocationBean>>> response) {
                        List<LocationBean> data = response.body().getData();
                        Integer totalSize = Integer.valueOf(response.body().getCountSize());
                        if (totalSize > 0) {
                            mTvResult.setVisibility(View.VISIBLE);
                            mTvResult.setText("共找到" + totalSize + "个接种点");
                        } else {
                            mTvResult.setVisibility(View.GONE);
                        }
                        if (mCurrentSize >= totalSize) {
                            mAdapter.loadMoreEnd(true);
                        } else {
                            mAdapter.addData(data);
                            mAdapter.notifyDataSetChanged();
                            mCurrentSize = mAdapter.getData().size();
                            if (data.size() < 10) {
                                mAdapter.loadMoreEnd(true);
                            } else {
                                mAdapter.loadMoreComplete();
                                pageNo++;
                            }
                        }
                    }

**Comment by caoeryang** [comment]
pageNo++ 之后      上拉没反应了

**Comment by caoeryang** [comment]
这个应该是个bug,loadMoreEnd这个方法没有执行,loadmore应该不会被终止,但是我把.loadMoreEnd(true)方法中形参boolean值去掉后,load就正常了

**Comment by SunJenry** [comment]
我这是执行一次之后就再也不回调onLoadMoreRequested() 方法了，完全找不到头绪

**Comment by AllenCoder** [comment]
loadMoreEnd(true) 是加载完成不会再次执行加载更多，如果想要再次回调，应该调用 mAdapter.loadMoreComplete();
      

```

    private void setData(boolean isRefresh, List data) {
        mNextRequestPage++;
        final int size = data == null ? 0 : data.size();
        if (isRefresh) {
            mAdapter.setNewData(data);
        } else {
            if (size > 0) {
                mAdapter.addData(data);
            }
        }
        if (size < PAGE_SIZE) {
            //第一页如果不够一页就不显示没有更多数据布局
            mAdapter.loadMoreEnd(isRefresh);
            Toast.makeText(this, "no more data", Toast.LENGTH_SHORT).show();
        } else {
            mAdapter.loadMoreComplete();
        }
    }
```

**Comment by RahulSDeshpande** [comment]
@AllenCoder AS per your comment I tried adding ```mAdapter.loadMoreComplete()``` to get the callback to the ```onLoadMoreRequested(){ .. }```, but couldn't.

Can you please help me with this ?
