### ISSUE TITLE
设置空布局时，布局match_parent失效

### ISSUE THREAD

**Issue by sasying** [CymChad/BaseRecyclerViewAdapterHelper#2207]
使用SwipeRefreshLayout嵌套RecyclerView，设置的空布局为LinearLayout，空布局LinearLayout的大小只能跟空布局内容的大小一致。什么原因导致的？

**Comment by sasying** [comment]
setEmptyView（）用的是FrameLayout，是这个原因导致布局一致显示在左上角的吗？各种方法都无效.....LinearLayout的weight都无效.........

**Comment by AllenCoder** [comment]
自定义EmptView参数
