### ISSUE TITLE
能否当显示出最后一条或倒数几条item时，才调用自动加载,？

### ISSUE THREAD

**Issue by MirkoWu** [CymChad/BaseRecyclerViewAdapterHelper#2208]
版本 2.9.34 
场景:adapter每页加载10条数据，但是每个item高度比较小，10个item确实不满一屏，但当adapter添加有header的时候 或者recyclerview上边有其他的控件已经占据一部分空间时，recyclerview的10个item就不能一屏显示完了，此时会自动调用下拉刷新，搞得每次已进入页面就要加载二次。所以，能否在逻辑上判断下，确认最后一个item已经显示，或者说倒数第几个item显示时再开始加载更多？

**Comment by AllenCoder** [comment]
可以完全自己控制加载更多逻辑，每次加载的数据设置大于10条以上，或者，当请求完成后，根据逻辑判断是否已经进入页面，是否需要执行加载更多逻辑，demo的加载更多，模拟了这种情况，可以参考具体业务代码改善
