### ISSUE TITLE
BaseMultiItemQuickAdapter获取条目位置问题

### ISSUE THREAD

**Issue by liuhang12138** [CymChad/BaseRecyclerViewAdapterHelper#2212]
请问我现在有3个分组 一个下面有2个子条目，当列表全部展开的时候，记录所有条目位置，当条目收缩的时候，获取的position却是收缩后排序的位置，比如我第三组  全部展开列表返回的是6位置  但是列表全部收缩的时候，返回的是3位置。。我怎么还能取到位于全部数据的6位置呢，我需要记录每一个条目的位于全部数据中的位置和一些其他属性，有什么方法吗？多谢指导

**Comment by AllenCoder** [comment]
position返回的基于当前展示的位置，如果要记录展开后的位置，需要自己在model层加字段保存展开后的expandPostion，然后收缩后，取值
