### ISSUE TITLE
BaseMultiItemQuickAdapter holder.setText(id,string);找不到资源

### ISSUE THREAD

**Issue by wangsanpiao** [CymChad/BaseRecyclerViewAdapterHelper#2214]
@Override
    protected void convert(final BaseViewHolder helper, MultiItemEntity item) {
        switch (helper.getItemViewType()) {
            case TYPE_LEVEL_0:
                final OrderLevel0 orderLevel0 = (OrderLevel0) item;
                //在这里用helper.setText会找不到资源id，换成下面的方法就可以了
                //helper.setText(R.id.ordertype ,orderLevel0.getItemType());
                TextView view = (TextView) helper.itemView.findViewById(R.id.ordertype);
                view.setText(orderLevel0.getOrderType());
                helper.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        int pos = helper.getAdapterPosition();
                        Log.d(TAG, "Level 1 item pos: " + pos);
                        if (orderLevel0.isExpanded()) {
                            collapse(pos, false);
                        } else {
                            expand(pos, false);
                        }
                    }
                });
                break;
            case TYPE_LEVEL_1:
                final OrderLevel1 orderLevel1 = (OrderLevel1) item;
                helper.setText(R.id.food_name, orderLevel1.getFoodName())
                        .setText(R.id.quantity, "数量：" + orderLevel1.getQuantity())
                        .setText(R.id.unit_price,"单价：" + orderLevel1.getUnitPrice());

                break;
        }
    }

**Comment by AllenCoder** [comment]
资源id和布局不对应，检查demo的代码
