### ISSUE TITLE
为什么修复了数据满一屏的bug，源码是最新拉下来的，但是为什么不是修改后的代码，作者还没有更新么？

### ISSUE THREAD

**Issue by lijingxin888** [CymChad/BaseRecyclerViewAdapterHelper#2216]
<img width="1290" alt="2018-05-08 5 38 54" src="https://user-images.githubusercontent.com/20985414/39752044-d4f949a0-52ec-11e8-8f65-df2b2e18e035.png">
这一块的代码，why？

**Comment by AllenCoder** [comment]
已合并

**Comment by lijingxin888** [comment]
好的，我看看，谢谢🙏

**Comment by lijingxin888** [comment]
![2018-05-09 10 11 59](https://user-images.githubusercontent.com/20985414/39792083-8861ecf2-5371-11e8-9029-344171f20720.png)
<img width="934" alt="2018-05-09 10 12 14" src="https://user-images.githubusercontent.com/20985414/39792088-8dffaa14-5371-11e8-9afa-6efc0558d9ac.png">
下载最新的包还是没有代码，查询阿里云的代码管理路径是3.9.94的，这是什么原因呢？

**Comment by lijingxin888** [comment]
是上传库的路径地址不对么？劳烦各位大神求解。

**Comment by lijingxin888** [comment]
谢谢，辛苦了🙏
