### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zhaoxiuyu** [CymChad/BaseRecyclerViewAdapterHelper#222]
/**
         *  功能都挺好的，唯一美中不足就是  刷新和加载，太过单调和难看，不知道项目是否还在更新，能否多提供几种刷新和加载的样式，或者提供拉动过程中的状态，让我们可以自己写效果。
         *  还有就是直接从上面下载的APK 安装后 竟然打开就直接闪退。为毛...
         */

**Comment by CymChad** [comment]
下拉刷新是配合第三方的，所以开发者任意选择，上拉加载，可以设置自定义布局。你的版本需要在4.1以上。

**Comment by zhaoxiuyu** [comment]
666 。  刚刚配合第三房的刷新试过 ， 不错哦。这是我目前用过最牛逼的adapter了。

**Comment by CymChad** [comment]
多谢，好用的话可以推荐给其他开发，我们会持续更新的，谢谢使用。
