### ISSUE TITLE
一级列表折叠后，遍历集合无法改变已经折叠的list数据

### ISSUE THREAD

**Issue by Dhaojie6688** [CymChad/BaseRecyclerViewAdapterHelper#2222]
implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.40'

需求：一级列表显示标题，二级列表显示CheckBox，主界面有一个全选按钮
当全选或者全不选 遍历list更改所有二级列表的CheckBox状态然后刷新适配器

问题：
当list有5条数据的时候
LEVEL_0 为第一条数据
LEVEL_1  为第二条、第三条数据
LEVEL_0 为第四条数据
LEVEL_1 为第五条数据
结构如下：
![error](https://user-images.githubusercontent.com/34852138/39846790-30f27a6c-5430-11e8-93e2-19027c5e406c.gif)

当一级列表折叠的时候，遍历list更改所有二级列表的状态时，获取不到已经折叠的二级列表数据了。
点击全选的时候所有一级列表都展开，此时获取list大小为5
折叠第一个一级列表，然后点击取消全选，此时获取list大小为3

**Comment by haoweizero** [comment]
@Dhaojie6688 请问您的问题解决了吗？
