### ISSUE TITLE
上拉加载后会自动滑翔

### ISSUE THREAD

**Issue by adminLiu-s** [CymChad/BaseRecyclerViewAdapterHelper#2223]
使用的就是普通下拉刷新控件嵌套recyclerview，但有时上拉加载后会自动滑到底部，这问题如何解决

**Comment by AllenCoder** [comment]
上拉加载更多会有数据添加到底部，如果此时调用adapter.notifyDataChange()会有滑动情况，如果感觉不好，可以在下拉刷新时，关闭加载更多，等数据加载完成后，再次开启加载更多的功能
