### ISSUE TITLE
拖拽与点击事件冲突

### ISSUE THREAD

**Issue by spd-heshuip** [CymChad/BaseRecyclerViewAdapterHelper#2224]
对item中的某个view同时设置了点击事件和拖动（非长按）拖拽事件，两个事件发生冲突，点击事件无法响应；

**Comment by AllenCoder** [comment]
点击事件使用adapter.setOntemClcik ，就好了。同时拖拽事件的Demo正好有点击和拖动结合的实现

**Comment by parcool** [comment]
@AllenCoder  我是不是眼瞎了，demo中并没有看到点击与拖动的结合。demo中的点击只是itemView的点击，别人问的是itemView中的某个View同时设置了点击。比如：adapter.setOnItemChildClickListener
