### ISSUE TITLE
headerview 添加宽度问题受到recyclerView 宽度影响

### ISSUE THREAD

**Issue by sqc0720** [CymChad/BaseRecyclerViewAdapterHelper#2228]
recyclerView 的布局是有paddingleft 和paddingright 的。 通过addHeaderView 添加的header的宽度也有了padding. 这个应该如何处理。希望给出相应的代码，3q

**Comment by AllenCoder** [comment]
recyclerView是父容器加padding值肯定会影响item的显示内容的
处理办法有两个
1 . 移除recyclerVIew的padding值只在item里面添加
2. 针对headview设置padding的值为负数，同时设置recyclerview的clicpChild =false
