### ISSUE TITLE
UpFetch功能加loading

### ISSUE THREAD

**Issue by easyrose** [CymChad/BaseRecyclerViewAdapterHelper#2232]
聊天需求的下拉加载历史数据如何在头部添加小菊花进度

**Comment by AllenCoder** [comment]
UpFetch 上拉加载更多，本身可以自定义loadingView

下拉刷新可以参考或者引入第三方库实现

**Comment by 123skywengboy123** [comment]
下拉加载等多 类似 聊天页面

**Comment by 123skywengboy123** [comment]
下拉加载等多 类似 聊天页面  不是上拉加载  不是上拉加载   不是上拉加载   下拉加载的时候能都有 能有loding 怎么实现

**Comment by dtboy1995** [comment]
+1
