### ISSUE TITLE
recyclerview嵌套recyclerview 共享RecycledViewPool出错

### ISSUE THREAD

**Issue by timmy008** [CymChad/BaseRecyclerViewAdapterHelper#2240]
1.外层：
       manager.setRecycleChildrenOnDetach(true);
        recyclerView.setLayoutManager(manager);
        recyclerView.setNestedScrollingEnabled(false);
        recycledViewPool = recyclerView.getRecycledViewPool();
2.在外出RecyclerView的Adapter的convert方法中设置recycledViewPool
        RecyclerView recyclerView = helper.getView(R.id.recyclerView);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(mContext, LinearLayoutManager.HORIZONTAL, false);
            recyclerView.setLayoutManager(linearLayoutManager);
            recyclerView.setRecycledViewPool(pool);  // 通过构造方法传递的，就是recycledViewPool

3.在水平水平方向Adapter的convert方法中使用时报错，为空指针
          helper
                .setText(R.id.tv_money, mContext.getString(R.string.shopping_cart_goods_price, item.getMemberPrice()))

     这里发现mContext为null

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int, java.lang.Object[])' on a null object reference

**Comment by AllenCoder** [comment]
mContext 为空，应该检查你的context是否引用正确

**Comment by itljw** [comment]
解决了吗？我也遇到了...使用RecyclerViewPool后复用的时候，mContext就为空了

**Comment by CSnowStack** [comment]
只是我直接 view.getContext
