### ISSUE TITLE
recyclerView嵌套，如何从内层的adapter中拿到外层的position

### ISSUE THREAD

**Issue by zhaoren** [CymChad/BaseRecyclerViewAdapterHelper#2241]
recyclerView嵌套，如何从内层的adapter中拿到外层的position

**Comment by AllenCoder** [comment]
内层的adapter在构造方法中传入外层的position

**Comment by jasonSuzhow** [comment]
> 内层的adapter在构造方法中传入外层的position

![image](https://user-images.githubusercontent.com/13963143/54912033-ab241480-4f2a-11e9-88b8-68e030c1a0c9.png)
我加了一个position, 应该怎么是修改啊

**Comment by jasonSuzhow** [comment]
> recyclerView嵌套，如何从内层的adapter中拿到外层的position

请问一下怎么解决的
