### ISSUE TITLE
Called attach on a child which is not detached: ViewHolder

### ISSUE THREAD

**Issue by jacky1234** [CymChad/BaseRecyclerViewAdapterHelper#2244]
@CymChad 滑动列表中最后一项，加上footerview，然后删除最后一项数据，就会报这个错误。请问这个是什么原因？

java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{68aa657 position=466 id=466, oldPos=-1, pLpos:-1}

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=Called+attach+on+a+child+which+is+not+detached%3A](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=Called+attach+on+a+child+which+is+not+detached%3A)
