### ISSUE TITLE
setOnItemClickListener的问题

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#2248]
![2sw igtier 6g9 _ twivg](https://user-images.githubusercontent.com/15857673/40337865-8eadb680-5da4-11e8-817c-e26d89165041.png)
在setOnItemClickListener( )方法里取adapter的值用((JavaBean) adapter.getItem(position))总会提示有个潜在的空指针异常，该怎样正确取值避免空指针呢

**Comment by AllenCoder** [comment]
作为编码规范，肯定会提示你进行空指针检查的，本身这种在可回收复用组件里面获取的view方式就会出现可能为空。你应该获取adapter.getItem（position）后，作为一个变量判断不为空之后，再进行后续的操作
