### ISSUE TITLE
2.9.40版本关于上拉加载的bug

### ISSUE THREAD

**Issue by Lyang166** [CymChad/BaseRecyclerViewAdapterHelper#2249]
正常进入页面 先刷新调用onRefresh( )方法加载第一页数据 ，然后上拉加载正常调用onLoadMoreRequested( )方法加载第二页数据，然后再上拉加载，就会出现一直显示“正在加载中footer布局”，不调用onLoadMoreRequested( )方法。然而数据是不止3页的

**Comment by YouLe2016** [comment]
简书中有说明这个问题

**Comment by YouLe2016** [comment]
注意：如果上拉结束后，下拉刷新需要再次开启上拉监听，需要使用setNewData方法填充数据。
