### ISSUE TITLE
结合CheckBox数据显示错乱问题

### ISSUE THREAD

**Issue by liuyu0823** [CymChad/BaseRecyclerViewAdapterHelper#2250]
选择某一子项CheckBox，滑动界面，数据出现错乱，未被选中的也被选中啦

**Comment by AllenCoder** [comment]
view复用问题，需要在数据层标记checkbox的选中属性

**Comment by w4mxl** [comment]
@AllenCoder 我遇到的是item 中的Textview滑动界面出现错乱。简单描述一下，我的item里面有Button“-”，Botton“+”，和一个显示数目的Textview（数目>0才显示）。根据button改变textview的数字。我是onItemChildClick里修改数据data，然后notifyItemChanged。convert里，Textview是根据数据来判断是否显示及显示多少。请问这样还有啥问题吗？
