### ISSUE TITLE
addHeaderView出现的问题

### ISSUE THREAD

**Issue by chaychan** [CymChad/BaseRecyclerViewAdapterHelper#2253]
调用adapter的addHeaderView后，有添加头部，显示没问题，头部的点击事件也没问题，就是第一个条目点击后报错：

Called attach on a child which is not detached: ViewHolder{32206bb position=0 id=-1, oldPos=-1, pLpos:-1}

其他条目点击后没问题，请问这是什么情况，如何解决？

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/479](urhttps://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/479l)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1315](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1315)
