### ISSUE TITLE
setEmptyView不显示了

### ISSUE THREAD

**Issue by xue12311** [CymChad/BaseRecyclerViewAdapterHelper#2254]
您好，请问
我在setEmptyView（）这个方法中添加了一个加载界面，希望每次网络请求时显示这个加载界面，
现在我进行这个方法setNewData（），然后在重新加载数据后，setEmptyView就显示不出来了，列表还是我通过setNewData（）这个方法的数据。
我需要在加载数据时显示加载界面，应该怎么修改

**Comment by AllenCoder** [comment]
EmptView只有在数据为空时才会显示，加载状态图请设置其他View

**Comment by wangtao2855** [comment]
![image](https://user-images.githubusercontent.com/34060120/55973101-71d3fe80-5cb7-11e9-9909-109644a2845b.png)
R.layout.....必须更换一个新的嘛?

**Comment by CAnonymous8** [comment]
mAdapter.setRecyclerView(recyclerView);
mAdapter.setEmptyView(R.layout.item_empty);

设置空布局前，先绑定下recyclerView
