### ISSUE TITLE
添加头布局后下标问题

### ISSUE THREAD

**Issue by chen-krolser** [CymChad/BaseRecyclerViewAdapterHelper#2256]
添加头布局后，helper.getLayoutPosition()得到的下标都会下移一位，getAdapterPosition()跟弃用的getPosition()方法得到的下标也是一样 会下移一位，用的BaseQuickAdapter

**Comment by AllenCoder** [comment]
请阅读源码，每一个headview是会占用一个postion的，所以会在数据处理时，智能减去了headView的个数
