### ISSUE TITLE
希望可以加入一个清除复用View的方法

### ISSUE THREAD

**Issue by BCheney** [CymChad/BaseRecyclerViewAdapterHelper#2257]
public <T extends View> T getView(@IdRes int viewId) {
        View view = views.get(viewId);
        if (view == null) {
            view = itemView.findViewById(viewId);
            views.put(viewId, view);
        }
        return (T) view;
    }

以上是BaseViewHolder的方法，BaseViewHolder中有很多方法都调用了此方法，比如说 setText、setTextColor。。。
当我在调用过以上这些方法的时候，会把我更改过后的View也存起来，所以我修改item的一些状态时，不得不用if去进行判断，这无形中就导致了增加了许多冗余代码，所以希望增加可以removeViews()类似这样的方法，确保每个itemView的状态是最原始的状态

**Comment by AllenCoder** [comment]
暫不打算支持此功能
