### ISSUE TITLE
自动加载更多

### ISSUE THREAD

**Issue by HoneyWorld** [CymChad/BaseRecyclerViewAdapterHelper#2259]
设置setOnLoadMoreListener后，一直在调用该接口，这个问题不解决，好像没发用了

**Comment by afkT** [comment]
是会有这种情况，因为自动加载，没满屏幕就会一直触发 OnLoadMoreListener

**Comment by XiaoQiWen** [comment]
同样遇到这个问题
setEnableLoadMore
disableLoadMoreIfNotFullPage
都不管用

**Comment by AllenCoder** [comment]
参考 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2190](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2190)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2167](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2167)

**Comment by ruanbaojun1105** [comment]
@AllenCoder 并没有任何作用
setEnableLoadMore
disableLoadMoreIfNotFullPage
都不管用

**Comment by zhupengxiang** [comment]
@ruanbaojun1105 @AllenCoder  解决了么  不满一屏 加载更多
![qq 20180808183634](https://user-images.githubusercontent.com/17894209/43832465-19e0fed8-9b3a-11e8-9f88-348c2f420806.png)

**Comment by zhupengxiang** [comment]
我这样调用还是不生效啊  以前是没问题的

**Comment by ruanbaojun1105** [comment]
@zhupengxiang 我这边是在调用加载更多的时候判断一下是否在加载刷新，基本勉强能用，主要是下拉刷新的控件放在CoordinatorLayout里面就会有这问题，其他的没遇到

**Comment by zhupengxiang** [comment]
@ruanbaojun1105 这跟不满一屏触发loadmore没有关系啊

**Comment by ruanbaojun1105** [comment]
这是我遇到的，可能跟你的问题不同

**Comment by LeeDuo** [comment]
我遇到的问题是，不满一屏，自动调用了加载更多，导致界面上数据重复。
我是在第一次加载数据的同时，设置了加载更多的监听
![image](https://user-images.githubusercontent.com/18297605/49647163-9182be00-fa5c-11e8-905c-f630c9a15e12.png)
因为获取数据是在子线程，所以判断第一次的数据是否需要加载更多的时候，其实onLoadMoreRequested()已经在同时回调了，不知道为什么会这样
试了很多方法，开启关闭loadMore都不行，除非不设置onLoadMore监听
最后的解决办法是，把设置监听放到第一次加载数据判断的时候
![image](https://user-images.githubusercontent.com/18297605/49647820-b6783080-fa5e-11e8-880c-54a2e07001b7.png)
好歹是解决了- -！

**Comment by v1ncent9527** [comment]
private static final int PAGE_SIZE = 10；
PAGE_SIZE设置成接口每次的返回数量就可以了
