### ISSUE TITLE
scrollView或者NestedScrollView嵌套recyclerView时 会不断的加载更多

### ISSUE THREAD

**Issue by millerzhu** [CymChad/BaseRecyclerViewAdapterHelper#2262]

**Comment by millerzhu** [comment]
昨天遇到的，不断的加载导致崩溃，我也不知道什么原因这样嵌套会引起不停的加载更多，换了布局就ok

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1777](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1777)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1251](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1251)
