### ISSUE TITLE
上拉加载第一次进入一直回调

### ISSUE THREAD

**Issue by Olove0** [CymChad/BaseRecyclerViewAdapterHelper#2268]
设置了加载更多的监听
mAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                doLoadMore();
            }
        },mRvPending);
mAdapter.disableLoadMoreIfNotFullPage();
第一次进入一直回调，设置了disableLoadMoreIfNotFullPage 也不起作用

**Comment by AllenCoder** [comment]
加载更多参考Demo写法，另外recyclerView外层不能包裹scrollView或者NestScrollView否则会一直加载更多

**Comment by shenjiabing** [comment]
recyclerView外层包裹scrollView或者NestScrollView会一直加载更多这个问题修复了吗？有没有解决办法？
