### ISSUE TITLE
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

### ISSUE THREAD

**Issue by hl5130** [CymChad/BaseRecyclerViewAdapterHelper#2270]
情况：ViewPager+Fragment，每一个Fragment中有RecyclerView。
操作步骤：点击“Home”，返回桌面，再次打开应用程序，出现了此错误。请问这个如何解决？

**Comment by a451492549** [comment]
版本号: 2.9.40
ViewPager + Fragment + RecyclerView 设置emptyView，左右切换时报这个错误。

**Comment by Bertkiing** [comment]
me too ...

**Comment by usernamemwl** [comment]
我用addHeader()添加了个头布局，然后每次点击第一条时报这个错误

**Comment by 2318423730** [comment]
怎么解决的？

**Comment by Blizzard-liu** [comment]
+1

**Comment by aloe20** [comment]
+1

**Comment by wanxiangxin** [comment]
ViewPager + Fragment + RecyclerView 设置emptyView，左右切换时报这个错误，请问作者怎么解决？？？？

**Comment by AllenCoder** [comment]
1 .检查是否fragment的创建时机
2. 执行setEmptyView时fragment的rootview是否已经被回收异常
3. fragment的根视图跟随activity的会在滑动过程中，被回收处理

**Comment by 0kman** [comment]
试试viewPager.setOffscreenPageLimit(mFragments.size() - 1);

**Comment by cugkuan** [comment]
我也是，搞的只能是缓存整个View
