### ISSUE TITLE
ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

### ISSUE THREAD

**Issue by ZhangXinmin528** [CymChad/BaseRecyclerViewAdapterHelper#2271]
能否在一个UI界面内使用两个RecyclerView,这样的话就需要创建两个Adapter,然后就会报这个异常？实在不行我就要该实现方案了。

**Comment by AllenCoder** [comment]
没有明白你的需求，可以针对不同的UI采用多类型布局

**Comment by ZhangXinmin528** [comment]
不是的，我们使用了360的replugin开发，我感觉有可能是框架的原因吧。就是在同一个Activity中有两个列表的情况，那天编译一直提示这种错误。

**Comment by a451492549** [comment]
Viewpager + fragment + recyclerView 设置emptyView，左右切换时报这个错误。

**Comment by AllenCoder** [comment]
Viewpager + fragment + recyclerView 设置emptyView，左右切换时,fragment如果没有设置，会重复创建rootView ，和detachRootView ,造成view的引用为空或者view的parentView不为空，重复添加会报错导致。
主要原因是视图缓存和重建引起的

**Comment by ddyos** [comment]
> Viewpager + fragment + recyclerView 设置emptyView，左右切换时,fragment如果没有设置，会重复创建rootView ，和detachRootView ,造成view的引用为空或者view的parentView不为空，重复添加会报错导致。
> 主要原因是视图缓存和重建引起的

所以有解决方案吗？

**Comment by Panxiaoan1993** [comment]
> Viewpager + fragment + recyclerView 设置emptyView，左右切换时,fragment如果没有设置，会重复创建rootView ，和detachRootView ,造成view的引用为空或者view的parentView不为空，重复添加会报错导致。
> 主要原因是视图缓存和重建引起的

请问可以具体解释一下吗？我的项目也遇到了这个问题，也是viewpager+fragment+recycleview，我用的也是多布局，多布局中包含另一个recycleview。

**Comment by zxm1243** [comment]
解决办法吗？

**Comment by zxm1243** [comment]
解决方案呢？

**Comment by darylsze** [comment]
@zxm1243 found that custom extends `BaseViewHolder` solved this problem.
My example:
```kotlin
class MyPmVH(view: View): BaseViewHolder(view)
```

**Comment by darylsze** [comment]
@zxm1243 found that custom extends `BaseViewHolder` solved this problem.
My example:
```kotlin
class MyXXViewHolder(view: View): BaseViewHolder(view)
```
then use in adapter as usual
```kotlin
class MyXXAdapter : BaseQuickAdapter<XX, MyXXViewHolder>(R.layout.mylayout) {
```
