### ISSUE TITLE
大佬，使用CoordinatorLayout+AppBarLayout+RecyclerView组合时，recycleView上啦加载时，使用Adapter的上啦加载方式时，会一直惯性滑动，无限加载好几页数据，希望大佬抽空看下

### ISSUE THREAD

**Issue by Asmewill** [CymChad/BaseRecyclerViewAdapterHelper#2275]
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/id_coordinatorlayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    >
    <android.support.design.widget.AppBarLayout
        android:id="@+id/id_appbarlayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:elevation="0dp"
        >
        <TextView
            app:layout_scrollFlags="scroll|enterAlways"
            android:layout_width="match_parent"
            android:gravity="center"
            android:layout_height="50dp"
            android:text="使用CoordinatorLayout+AppBarLayout包裹的可以滑动的TExtView"
            android:textColor="#e95c63"
            android:background="@color/colorPrimary"/>
    </android.support.design.widget.AppBarLayout>

<LinearLayout
    style="@style/bg"
    app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/swipeLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        >

        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:descendantFocusability="afterDescendants"
            />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

</LinearLayout>

</android.support.design.widget.CoordinatorLayout>

**Comment by Asmewill** [comment]
![](https://github.com/Asmewill/BaseRecyclerViewAdapterHelper/blob/master/GIF.gif)|

**Comment by AllenCoder** [comment]
CoordinatorLayout布局内会一直触发recyclerview的多次measure，无法加载完成，可以手动控制加载一屏幕时关闭加载更多，待布局完成后，再次开启加载更多，demo里面的加载更多可以参考一下

**Comment by fuguiniao** [comment]
找到解决办法了，试过可以用
https://github.com/shaopx/RecyclerView66996774Workaround
