### ISSUE TITLE
关于默认选中

### ISSUE THREAD

**Issue by yzjsbsb** [CymChad/BaseRecyclerViewAdapterHelper#2278]
你好，我想默认选中第一个item。貌似没有直接可以使用的方法。请问要怎么做

**Comment by AllenCoder** [comment]
默认选中，处理办法，待recyclerview绘制完毕，手动处理数据model，标记第一个item的选中状态，然后通知适配器刷新

**Comment by yzjsbsb** [comment]
手动处理数据model，标记第一个item的选中状态是指自己添加字段用来标记吗？如果是的话，标记完之后刷新适配器，适配器里应该手动掉用选中的方法，不过我好像没有找到选中item的方法

**Comment by AllenCoder** [comment]
选中的字段应该是包含在设计的状态 state 的model里面的，api不提供，这是基础功能

**Comment by yzjsbsb** [comment]
好的，谢谢了
