### ISSUE TITLE
onItemChildClick 怎么判断是哪个子控件点击的

### ISSUE THREAD

**Issue by 617450941** [CymChad/BaseRecyclerViewAdapterHelper#2281]
item有多个子控件  onItemChildClick 里怎么区分是哪个子控件点击的

**Comment by spynokia** [comment]
switch(view.getId())
case R.id.xxx

**Comment by leejay001** [comment]
> switch(view.getId())
> case R.id.xxx

如果在moudle中不能用R.id.xxx怎么办

**Comment by leejay001** [comment]
解决了，用if可以，不能switch，因为library中不是final常量
