### ISSUE TITLE
How to refer to each element of the list?

### ISSUE THREAD

**Issue by bsodKeks** [CymChad/BaseRecyclerViewAdapterHelper#2282]
For example, when I click on an item, I make a visible picture, and thus it is necessary that in all other elements this picture becomes invisible. How can this be realized?

**Comment by fandeus** [comment]
you can do it like this in yourAdapter at this method `convert` find your view  View yourView = help.getView(R.id.your_view_id);   if(item.getIsHidden()){yourView.setVisibility(View.VISIBLE or View.GONE)}

**Comment by bsodKeks** [comment]
if I do so, then every 13 list items will become visible. 0, 13, 26 etc

**Comment by AllenCoder** [comment]
You can add a field marker view to show and hide the data layer
