### ISSUE TITLE
How to call loadmore manually?

### ISSUE THREAD

**Issue by tamtom** [CymChad/BaseRecyclerViewAdapterHelper#2283]
I want to call loadmore when the scrolls in the middle of the results 
so for example, if the results are 20 and the user scrolled to the item 10 I need to request loadmore 
how is that can be achieved

**Comment by AllenCoder** [comment]
you can refer this [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)
