### ISSUE TITLE
下载下来的项目无法打开

### ISSUE THREAD

**Issue by CaiJingFu** [CymChad/BaseRecyclerViewAdapterHelper#2284]
先是提示Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.

然后我将gradle改成4.4后，就提示
`Failed to resolve: runtime <a href ="OpenFile:D:/GitHub/ BaseRecyclerViewAdapterHelper-master/app/buidle-gradle">Open file</a>`

请问如何解决？

**Comment by CaiJingFu** [comment]
打开先是提示Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.
然后我将gradle改成4.4后，就提示
Failed to resolve: runtime <a href ="OpenFile:D:/GitHub/ BaseRecyclerViewAdapterHelper-master/app/buidle-gradle">Open file</a>

**Comment by CaiJingFu** [comment]
Failed to resolve: runtime <a href ="OpenFile:D:/GitHub/ BaseRecyclerViewAdapterHelper-master/app/buidle-gradle">Open file</a>

**Comment by CaiJingFu** [comment]
（Failed to resolve: runtime <a href ="OpenFile:D:/GitHub/ BaseRecyclerViewAdapterHelper-master/app/buidle-gradle">Open file</a>）

**Comment by CaiJingFu** [comment]
`Failed to resolve: runtime <a href ="OpenFile:D:/GitHub/ BaseRecyclerViewAdapterHelper-master/app/buidle-gradle">Open file</a>`

**Comment by AllenCoder** [comment]
目前项目推荐的依赖配置都有写好，CI集成测试这边是可以正常运行的，建议根据demo项目写法，翻墙联网更新本地的gradle版本和android  build tools plugin 版本

**Comment by AllenCoder** [comment]
[https://circleci.com/gh/CymChad/BaseRecyclerViewAdapterHelper/75](https://circleci.com/gh/CymChad/BaseRecyclerViewAdapterHelper/75)

**Comment by CaiJingFu** [comment]
解决了，谢谢

**Comment by hellohanyu** [comment]
@CaiJingFu 请问怎么解决的
