### ISSUE TITLE
不知道怎么实现？

### ISSUE THREAD

**Issue by ylmyg** [CymChad/BaseRecyclerViewAdapterHelper#2285]
我想做分布局，已经
    实体类是 WeatherData
    public class WeatherData implements Serializable,MultiItemEntity{
        private List<HoursForecastEntity> hoursForecast;
        private List<DailyForecastEntity> dailyForecast;
        private List<LifeIndexEntity> lifeIndex;
        private List<AlarmsEntity> alarms;
    }
我想在适配器中传入WeatherData  然后分布局再使用里面的list集合赋值
但是mWeatherFragmentAdapter.setNewData(mWeatherData)；
必须传入mWeatherData是list的，不能直接传入对象。我是不是需要构造呢？

**Comment by AllenCoder** [comment]
你做实体类的转换，简单的把数据合并为一个一个集合即可
