### ISSUE TITLE
how to remove an item in using section

### ISSUE THREAD

**Issue by alouanemed** [CymChad/BaseRecyclerViewAdapterHelper#2288]
How Can I remove an item from sections items let's say when on loadmore is clicked ?
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/749371b75edda1da0eab98e7726a833d87ff7729/app/src/main/java/com/chad/baserecyclerviewadapterhelper/SectionUseActivity.java

**Comment by AllenCoder** [comment]
you can remove section data and then call adapter.notifyDataChange
