### ISSUE TITLE
BaseQuickAdapter 第一个items点击事件无效

### ISSUE THREAD

**Issue by dyalexamor** [CymChad/BaseRecyclerViewAdapterHelper#2289]
自定义一个adapter
public class MyAdapter extends BaseQuickAdapter<Data, BaseViewHolder> implements BaseQuickAdapter.OnItemClickListener{
   @Override
    protected void convert(BaseViewHolder helper, Data item) {
        helper.setImageResource(R.id.iv_operation, item.getLogo())
                .setText(R.id.tv_operation, item.getShowMessage());

        this.setOnItemClickListener(this);
    }

    @Override
    public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
       Log.e("Data===>", "" + this.getData().size());
        Log.e("position===>", "" + position);
    }

如上所示： data的值有4个，如果在Activity中实现BaseQuickAdapter.OnItemClickListener，items点击事件无问题，点击后position分别打印0，1，2，3  为什么在MyAdapter设置BaseQuickAdapter.OnItemClickListener时，点击第一个items无反应，点击其他items正常，position只打印了1，2，3？

**Comment by Panxiaoan1993** [comment]
是不是加了header？

**Comment by dyalexamor** [comment]
加了header跟items的点击事件没有关系吧？

**Comment by dyalexamor** [comment]
@

**Comment by dyalexamor** [comment]
@Panxiaoan1993 确实有加了header，如果是因为加了header那么在adapter设置Itemclick点击第一个items无效，在activity中设置Itemclick又是好的呢
