### ISSUE TITLE
滑到第15条自动触发checkbox事件，什么原因？

### ISSUE THREAD

**Issue by strugglelin** [CymChad/BaseRecyclerViewAdapterHelper#2293]
滑到第15条自动触发checkbox事件，什么原因？
convert（）方法如下：
helper.setOnCheckedChangeListener(R.id.cb_choose, new CompoundButton.OnCheckedChangeListener() {
@Override
public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
if(isChecked){

helper.setTextColor(R.id.cb_choose, Color.parseColor("#357ffa"));
concern(item.getCurrency_trade_id(),helper);
}else{

helper.setTextColor(R.id.cb_choose, Color.parseColor("#aaaaaa"));
cancelConcern(item.getCurrency_trade_id(),helper);
}
}
});

**Comment by JavaBoyHW** [comment]
你提供的信息不是太全，但根据我对你问题的理解：是ViewHolder机制触发了checkbox事件。你应该是想解决checkbox错乱问题。可以参考如下链接：[RecyclerView中使用CheckBox勾选混乱问题](https://blog.csdn.net/ww897532167/article/details/77529605)
