### ISSUE TITLE
RecyclerView嵌套RecyclerView每刷新一次内层RecyclerView的ItemDecoration增大一倍

### ISSUE THREAD

**Issue by ericwangjp** [CymChad/BaseRecyclerViewAdapterHelper#2294]
无论是setNewData()还是notifyItemChanged(position)最终列表刷新一次后内层RecyclerView的ItemDecoration间距都会增加一次，目测增大一倍的样子

**Comment by AllenCoder** [comment]
是否是使用嵌套的方式不对，频繁刷新应该不会有这个问题。

**Comment by ericwangjp** [comment]
目前发现加载更多，即使不嵌套RecyclerView，页数过多也会这样，加载一页，页面的ItemDecoration增大一次，很容易重现，你的demo中根本没有添加ItemDecoration，所以没问题，你加上自己试试就知道

**Comment by 574085757** [comment]
设置item为warpcontent

**Comment by YooTrepeat** [comment]
这个我也遇到过，我尝试过重写CreateViewHolder等解决方案，都没用。所以当时我弃用了ItemDecoration。在item布局中加的margin

**Comment by yaoxin2017** [comment]
刷新时内嵌的recyclerview 会重复执行 addItemDec... ，如果在add前 先删除 ItemDec...应该就没问题了吧

**Comment by AnJiuZhe** [comment]
这是因为复用的问题吧，每次recyclerview都会添加ItemDecoration，所以应该判断这个recyclerview是否复用过，我的解决思路是把嵌套的recyclerview加入到一个集合中，每次判断recyclerview是否包含在集合中，如果不包含就添加ItemDecoration并加入到集合中。感觉这样性能有影响，item过多的话，不知道各位有没有更好的解决思路！！

**Comment by AnJiuZhe** [comment]
找到比较好的方法了。
 /**
         * 判断recyclerview是否存在ItemDecoration,若存在则不必重复添加
         */
        RecyclerView.ItemDecoration itemDecoration = recyclerView.getItemDecorationAt(0);
        if (itemDecoration == null) {
            recyclerView.addItemDecoration(new GridSpacingItemDecoration(DpPxUtils.dip2px(mContext, 17)));
        }

**Comment by saanl** [comment]
> 找到比较好的方法了。
> /**
> * 判断recyclerview是否存在ItemDecoration,若存在则不必重复添加
> */
> if (recyclerView.getItemDecorationCount() == 0) {
> recyclerView.addItemDecoration(new ItemDecoration(mContext));
> }

我就说怎么点击一次 变小一次 原来是复用的时候还会添加item decoration
