### ISSUE TITLE
多布局同类型不定高的item复用卡顿

### ISSUE THREAD

**Issue by easyrose** [CymChad/BaseRecyclerViewAdapterHelper#2298]
多布局RecyclerView相同item不定高，复用时都重新计算高度导致ui卡顿

**Comment by AllenCoder** [comment]
不定高，如果一屏幕里面这种item非常多，计算起来会卡顿，因为需要不断的测量，重绘，本库和原生adapter在性能上没什么出入，都是基于原adapter封装了api,性能优化很多方案，可以尝试其他解决方案
