### ISSUE TITLE
获取某个item的view

### ISSUE THREAD

**Issue by weavey** [CymChad/BaseRecyclerViewAdapterHelper#23]
使用过程中遇到这样的需求，点击某个item改变它的背景颜色，类似选中效果，再点击另外一个item，之前选中的item要变回原来的颜色，所以想要根据item的position拿到它的view，希望作者能加多这个方法，感激不尽。

**Comment by CymChad** [comment]
helder.getView(resId) 有这个方法的

**Comment by CymChad** [comment]
恩，我看看

**Comment by CymChad** [comment]
通常做法就是全部刷新一遍列表，然后在给当前view颜色，不需要知道之前的view吧？

**Comment by weavey** [comment]
额  这样也是可以 但是 当我的列表数据很多的时候 这样会很耗性能的吧   建议最好是有一个根据position拿到item的view的方法  可能以后还会有其他情况需要\(^o^)/

**Comment by CymChad** [comment]
notifyItemChanged(); 你可以使用这个方法改变postion的数据，通过数据属性去决定item的bg颜色，这样就是单独改一个，因为我看了下recycleView的源码，他没有把View的集合给暴露，如果自己去存View的话，感觉不太好，所以尽量用原始的方法。

**Comment by weavey** [comment]
嗯 recyclerview没有这样方法就没办法了  主要问题在于我数据的实体类里面 没有一个属性是可以用来判断改变view的背景   这样的话我要重新打包数据或者记录每个item的标志   最近一直在用你的这个万能Adapter  感觉非常不错！强！

**Comment by CymChad** [comment]
感谢使用，有什么问题可以继续提出
