### ISSUE TITLE
 在Fragment中监听不到LoadMore

### ISSUE THREAD

**Issue by SilentWeek** [CymChad/BaseRecyclerViewAdapterHelper#230]
如果是在Fragment中使用LoadMore会监听不到，我在Fragment中 mAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
@Override
public void onLoadMoreRequested() {
mRecyclerView.post(new Runnable() {
@Override
public void run() {
if (mCurrentCount >= totalCount) {
notMore();
} else {
page++;
requestBuildingList();
}
}
});
}
});

这样 ，回调的方法一直都进不去

**Comment by CymChad** [comment]
#131 你可以看下

**Comment by SilentWeek** [comment]
我另写了个Demo发现在Fragment里面是可以监听到的，应该是我自己项目里代码出了其他的问题，抱歉···

**Comment by CymChad** [comment]
恩 没事，从源码中找到答案。
