### ISSUE TITLE
setEmptyView()没有起作用

### ISSUE THREAD

**Issue by waterpotter** [CymChad/BaseRecyclerViewAdapterHelper#2301]
你好,感谢作者的开源,对我帮助很大.在今天的使用中,首先,进页面后,第一次请求数据,rv进行数据列表加载显示,然后,再根据筛选条件重新请求数据,当请求下来的新数据为空时,加载emptyview,可是emptyview不显示,列表上还是原先的第一次请求数据,这是为什么?

**Comment by waterpotter** [comment]
问题解决了:使用setEmptyView()之前的将之前的数据setNewData(null)

**Comment by wangtao2855** [comment]
还是不成啊 虽然数据清除了,但是setEmpty的布局还是没有显示啊

**Comment by pumatus** [comment]
我也是，而且在fragment中

**Comment by wangtao2855** [comment]
> 我也是，而且在fragment中

我解决了 忘记是咋解决的 就记得是自己的问题 你是不是用了今日头条适配了

**Comment by pumatus** [comment]
View view = getActivity().getLayoutInflater().inflate(R.layout.default_no_data, null);
					myVoteAdapter = new MyVoteAdapter(nodeAssemblyData, voteListListener);
					myVoteAdapter.setNewData(null);
					myVoteAdapter.setEmptyView(view);
					recyclerView.setAdapter(myVoteAdapter);
没有用别的，就这几行代码，是在fragment中

**Comment by wangtao2855** [comment]
> View view = getActivity().getLayoutInflater().inflate(R.layout.default_no_data, null);
> myVoteAdapter = new MyVoteAdapter(nodeAssemblyData, voteListListener);
> myVoteAdapter.setNewData(null);
> myVoteAdapter.setEmptyView(view);
> recyclerView.setAdapter(myVoteAdapter);
> 没有用别的，就这几行代码，是在fragment中

setAdapter 肯定需要放在SetNewData(null) 之前啊

**Comment by pumatus** [comment]
不行

**Comment by pumatus** [comment]
代码是没问题，是我在rxjava中进行了飞主线程更新UI, 这个崩溃被try catch了

**Comment by sdgSnow** [comment]
请问这个问题有解决吗
NationAdapter nationAdapter = new NationAdapter(nationList, context);
        recyclerView.setLayoutManager(new GridLayoutManager(context, 1, GridLayoutManager.VERTICAL, false));
        nationAdapter.setNewData(null);
        View view = LayoutInflater.from(context).inflate(R.layout.empty_build_list, null);
        nationAdapter.setEmptyView(view);
        recyclerView.setAdapter(nationAdapter);
我这样setNewData为null了也不行
