### ISSUE TITLE
现有的Header/Footer形式对decoration太不友好了

### ISSUE THREAD

**Issue by jeonhei** [CymChad/BaseRecyclerViewAdapterHelper#2303]
如果业务需要用到多Header且中间需要有间隔的话现在的做法是只能在Header布局里添加一个空的view然后设定大小和背景色 这样做太不灵活了 希望可以改成每个Header对应一个Item

**Comment by AllenCoder** [comment]
多header最终被添加到同一个LinearLayout作为一个item放入适配器中，暂时不支持ItemDecoration在多个headView中
