### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Cannot change whether this adapter has stable IDs while the adapter has registered observers.

### ISSUE THREAD

**Issue by xwtao** [CymChad/BaseRecyclerViewAdapterHelper#2306]
使用setHasStableIds报Caused by: java.lang.IllegalStateException: Cannot change whether this adapter has stable IDs while the adapter has registered observers.错误
代码如下： protected void convert(BaseViewHolder baseViewHolder, Dynamic dynamic) {
        setHasStableIds(true);
......
}

 @Override
    public long getItemId(int position) {
        return position;
    }

**Comment by AllenCoder** [comment]
```

public void setHasStableIds(boolean hasStableIds) {

   if (hasObservers()) {
  throw new IllegalStateException("Cannot change whether this adapter has " +
  "stable IDs while the adapter has registered observers.");
   }
   mHasStableIds = true;
   }




public final boolean hasObservers() {
  return mObservable.hasObservers();
  }
 


```

**Comment by xwtao** [comment]
通过源码发现setHasStableIds(true);要在setAdapter之前调用就不会报错了，不过就是还是没达到我想要的效果

**Comment by yanftch** [comment]
> 通过源码发现setHasStableIds(true);要在setAdapter之前调用就不会报错了，不过就是还是没达到我想要的效果

其实不然，就算是在 setAdapter() 之前调用，也是会报错的。
