### ISSUE TITLE
第一个items点击无效

### ISSUE THREAD

**Issue by dyalexamor** [CymChad/BaseRecyclerViewAdapterHelper#2307]
public class MyAdapter extends BaseQuickAdapter<Data, BaseViewHolder>implements BaseQuickAdapter.OnItemClickListener{

public MyAdapter (@Nullable List<Data> data) {
    super(R.layout.recyclerview_items_, data);
}

@Override
protected void convert(BaseViewHolder helper, Data item) {
    this.setOnItemClickListener(this);
}

@Override
public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
   
    Log.e("position===>", "" + position);
}
Data数据有4个，在Activity中实现OnItemClickListener分别点击items position输出0，1，2，3. 但是如上程序所示：在MyAdapter实现OnItemClickListener分别点击items postion输出1，2，3. 第一个items点击事件无效，为什么？

**Comment by AllenCoder** [comment]
请参考 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java)

**Comment by ihewro** [comment]
@AllenCoder  如果写在adapter里面为什么第一个项点击无效呢？

因为这个事件是和adapter绑定的，如果写在activity里面就会重复代码，因为多个activity都会有这个点击事件
