### ISSUE TITLE
remove item 操作的BUG问题

### ISSUE THREAD

**Issue by xiaosong520** [CymChad/BaseRecyclerViewAdapterHelper#231]
现项目有一个历史记录的列表，item布局的右方是个删除记录的控件。在onItemChildClick 监听事件 处理 item 的 remove 操作，发现如果用户连续点击太快，某个item触发了不止一次remove，引起错误（比如删除第一个item，结果不小心连续点击了第一个item的删除键两次，程序就会崩溃）

**Comment by CymChad** [comment]
这个需要开发者来处理，因为如果删除的话肯定要请求，请求是需要时间的，如果在请求还没回调的时候你又点击了重复的item rm 那么肯定会出问题的。
