### ISSUE TITLE
多样式条目列表重复刷新几次后，同样内容的同一个条目会多次显示

### ISSUE THREAD

**Issue by hymbo** [CymChad/BaseRecyclerViewAdapterHelper#2313]
自己的adapter不管继承BaseMultiItemQuickAdapter还是BaseQuickAdapter进行多中条目数据开发，多次刷新后下拉查看，三种不同的item会重复显示，比如类型1的显示了1条，类型2的显示了3条，类型3的显示了2条（类型1、2内部也是一个列表数据），看了历史的issue没有相关问题，请问下是否可提供一些解决建议？

**Comment by CymChad** [comment]
能否提供可运行的demo？

**Comment by shuzhili** [comment]
这重复条目我这样出现了，请问怎么解决的呢
