### ISSUE TITLE
实现BaseQuickAdapter<T,BaseViewHolder>,数据可不可以设置成通用的

### ISSUE THREAD

**Issue by androidmoyan** [CymChad/BaseRecyclerViewAdapterHelper#2316]
比如有三种或者更多的对象格式,但是 item内的 控件都一样, 数据返回后咱们用不同的对象解析,会得到三种或者是更多的对象格式 比如 一个item 内有 TextView 和 ImageView ,但是 T 是两三种 ,如 LoginResponseData,MainResponseData ........等, 这种情况下想用同一个 Adapter,根据 构造函数传入不同的类型进行区分对象, 这种有办法么?

**Comment by cervy** [comment]
建议构造通用JavaBean

**Comment by androidmoyan** [comment]
那如果没有通用的javabean 就不能通用了么? ,这个可以考虑添加一下

**Comment by joefei** [comment]
既然item一样,为什么javabean会有两三种?

**Comment by androidmoyan** [comment]
数据格式是嵌套的,有的时候后台返回的数据解析不一样的
