### ISSUE TITLE
快速上拉加载更多有问题

### ISSUE THREAD

**Issue by SlimEx** [CymChad/BaseRecyclerViewAdapterHelper#2317]
快速上拉时拉到底部从网络读取数据之后,如果耗时很短,新加载出来的数据会弹出来,然后列表会继续滚动,直到停下,如果上拉的速度够快的话,列表又会滚动到底部触发加载更多.

我用单独的recyclerview测试了,也有这个问题,应该不是scroollView包裹的问题,真的不知道怎么解决了.
我感觉应该是检测加载更多的方法有问题

**Comment by xiaoanzi** [comment]
我也遇到这个问题，我是这样解决的。在网络请求完成之后，调用 RecyclerView 的 stopScroll() 方法即可解决这个问题。

**Comment by qianzui** [comment]
这个问题有什么解决办法吗？我也遇到了

**Comment by huadabing** [comment]
各位大佬有没有遇到在NestedScrollView中，它都是自动加载全部数据的情况？

**Comment by sorgs** [comment]
可以尝试调用下
recyclerView.stopScroll();

**Comment by yu893145181** [comment]
发现这个问题只会出现在recyclerView设置网格布局之后有的。解决办法就是数据请求成功之后recyclerView.stopScroll(),有用

**Comment by gogooing** [comment]
我这都问题是sdk27版本的recyclerview会出现，28的就不会这样

**Comment by CymChad** [comment]
感谢大家的回复
