### ISSUE TITLE
setOnLoadMoreListener，自动执行，怎么让他刚开始加载时不执行

### ISSUE THREAD

**Issue by wangxp423** [CymChad/BaseRecyclerViewAdapterHelper#2319]
`blogAdapter.run {
            isMyLike = true
            bindToRecyclerView(blog_include_rv)
            setOnLoadMoreListener({
                pageIndex++
                blogPresenter.loadMoreDataList(pageIndex)
            }, blog_include_rv)
            setEmptyView(R.layout.recycle_list_empty)
            onItemClickListener = this
            onItemChildClickListener = this
        }`

这是我在Activity中，关于adapter默认配置的代码，其中setOnLoadMoreListener中的代码不会执行，但是同样的代码我放在Fragment的onActivityCreated的时候，每次刚进入页面setOnLoadMoreListener中的代码就会执行，这个是什么情况啊？求指教

**Comment by wangxp423** [comment]
补充一下，fragment中没有调用bindToRecyclerView(blog_include_rv)，因为调用的话 来回滑动会报异常。

**Comment by wangxp423** [comment]
找到问题原因了，是因为如果页面数据不满一屏幕，而且没有掉用loadMoreEnd就会自动执行到loadMoreListener里面。

**Comment by xiaocaini** [comment]
我也遇到了这个问题。一进来就自动调用了setOnLoadMoreListener()这个方法。数据已经占满屏了，但是会连续请求分页。直到加载完分页。请问怎么回事

**Comment by wangxp423** [comment]
result?.data?.datas?.let {
            blogAdapter.run {
                addData(it)
                if (result.data.over) {
                    loadMoreEnd()
                    setEnableLoadMore(false)
                } else {
                    pageIndex++
                    loadMoreComplete()
                    setEnableLoadMore(true)
                }
            }
        }

这是我的代码，我昨天调试了很长时间，然后发现了 我提问的那个问题，今天我又试了下是可以。你在请求完成以后 调用一下 自带的三个方法 就是我 if else 里面的三个 组合一下试试。

**Comment by wangxp423** [comment]
最后在补充一下，虽然我上面说的可以暂时解决自动调用loadMoreListener这个问题。但是如果是在Activity中，如果不是满屏的情况下一样不会自动调用loadMoreListener，但是如果在Fragment中却会自动调用，而且因为我的是跟TabLayout结合使用的，我调用了loadMoreEnd以后，是会出现底部的"没有更多数据"底部View的，但是如果我来回切换Fragment的时候，就又自动调用loadMoreListener了，我必须调用loadMoreEnd和setEnableLoadMore(false)，这两个方法，才会在来回切换的时候，不自动调用loadMoreListener。我觉得这是代码有问题。首先Activity没有问题，其次，loadMoreEnd说明已经到底了，显示底部View,如果在调用setEnableLoadMore(false)就不会显示底部View了，这两个明显冲突了。但是在Fragment中却必须这么做。当然也有其他解决办法，比如到底了以后，如果再走loadMoreListener，加一个判断直接return就可以，但是既然楼主给了这么多的状态，但是状态间有一些问题，还望知晓。

**Comment by AllenCoder** [comment]
加载更多的异常，设计之初没有完全考虑，但通过目前已有的api组合可以处理问题，也希望有能力的同学，贡献自己的优秀代码优化加载更多。使RRVAH更好

**Comment by xwaitalonec** [comment]
> 我也遇到了这个问题。一进来就自动调用了setOnLoadMoreListener()这个方法。数据已经占满屏了，但是会连续请求分页。直到加载完分页。请问怎么回事

**Comment by KnightOneAdmin** [comment]
我也遇到这个问题， 怎么解决的？
