### ISSUE TITLE
是不是根布局要LinearLayout，加载更多才有效果？

### ISSUE THREAD

**Issue by awu515** [CymChad/BaseRecyclerViewAdapterHelper#232]
如题。。刚开始根布局用了RelativeLayout，发现加载更多监听没执行。mRecyclerView.setLayoutManager(new LinearLayoutManager(this)); 看了这句话，感觉根布局要LinearLayout。。

**Comment by CymChad** [comment]
不是呀，看你的设置。pageSize多少？

**Comment by awu515** [comment]
好吧。犯了低级错误。没留意这个size。谢谢解答。

**Comment by CymChad** [comment]
没事，感谢使用。
