### ISSUE TITLE
使用拖拉适配器(BaseItemDraggableAdapter)配合google的FlexboxLayoutManager出现崩溃

### ISSUE THREAD

**Issue by azhansy** [CymChad/BaseRecyclerViewAdapterHelper#2320]
需求是类似标签控件，多个标签显示不下会自动换行显示，
当第一行只有一个textview，就是第一行只有一个item，
移除第一个item然后第二行的数据就会变成第一行，此时就崩溃了，
（使用原生的recyclerView适配器正常，所以怀疑拖拉适配器跟FlexboxLayoutManager是不是不能共存，麻烦帮忙排查下，笔芯！）
` constructor(context: Context, attributeSet: AttributeSet?, defStyle: Int) : super(context, attributeSet, defStyle) {
        //初始化recyclerView数据
        adapter = TagAdapter()
        setAdapter(adapter)
        val manager = FlexboxLayoutManager()
        addItemDecoration(CustomItemDecoration(DisplayUtil.dip2px(getContext(), 10f)))
        layoutManager = manager

        //设置点击item事件
        adapter.setOnItemClickListener { adapter, view, position ->
            val tagView = adapter.getItem(position)
            if (tagView != null && tagView is ITagView) {
                mOnItemClickListener?.onItemClick(tagView, view, position)
            }
        }

    }

    class TagAdapter : BaseItemDraggableAdapter<ITagView, BaseViewHolder>(R.layout.tag_recycler_item, null) {

        override fun convert(helper: BaseViewHolder, tagView: ITagView?) {
            tagView?.let {
                val tagTextView = helper.getView<RoundedButton>(R.id.tv_tag)
                tagTextView.text = tagView.getName()
            }
        }
    }`
崩溃日志如下：
java.lang.IllegalStateException: Two different ViewHolders have the same change ID. This might happen due to inconsistent Adapter update events or if the LayoutManager lays out the same View multiple times.
                                                                              ViewHolder 1:ViewHolder{1f673e5 position=0 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)} 
                                                                              View Holder 2:ViewHolder{493616b position=0 id=-1, oldPos=-1, pLpos:-1}
                                                                                 at android.support.v7.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:3441)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3373)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3135)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                                 at android.view.View.layout(View.java:17529)

**Comment by AllenCoder** [comment]
猜测可能是这个原因
[https://www.jianshu.com/p/69b880bc24ad](https://www.jianshu.com/p/69b880bc24ad)

**Comment by Danniel-yan** [comment]
> 猜测可能是这个原因
> https://www.jianshu.com/p/69b880bc24ad

FlexboxLayoutManager adapter实现DraggableModule 怎么解 谢谢 ♥️

**Comment by Danniel-yan** [comment]
> > 猜测可能是这个原因
> > https://www.jianshu.com/p/69b880bc24ad
> 
> FlexboxLayoutManager adapter实现DraggableModule 条目无法实现拖拽怎么解 谢谢 ♥️
