### ISSUE TITLE
addOnClickListener 优化建议

### ISSUE THREAD

**Issue by heiniuniu** [CymChad/BaseRecyclerViewAdapterHelper#2322]
目前，addOnClickListener 的操作 需要放到convert中执行，convert会执行很多次，但是个人觉得，添加点击事件的操作只需要执行一次即可。建议在BaseQuickAdapter onCreateViewHolder 执行结束时，通知子类。 新增一个抽象方法onCreateViewHolderAfter   。    可以解决频繁的 new View.OnClickListener

**Comment by AllenCoder** [comment]
addOnClickListener只是针对itemChild的点击事件的绑定，因为在onCreateViewHolder时无法预知itemchild是否存在于当前的itemview中，因为此时它也无法处理， 不知道那个子控件需要响应点击。 
所以交由开发者控制在某个时机去绑定itemchild的点击事件
新增一个抽象方法onCreateViewHolderAfter这个想法很好，应该可以改进实现，
如有好的解决方案和idea，欢迎贡献代码，帮助我们更好的改进和优化BRVAH
