### ISSUE TITLE
嵌套复用问题

### ISSUE THREAD

**Issue by Chenayi** [CymChad/BaseRecyclerViewAdapterHelper#2324]
recyclerview 嵌套 横向的recyclerview 或者viewpager 划出后再划回来，横向的recyclerview 或者viewpager会被重置到第一个item，请问有好的解决方法吗

**Comment by Chenayi** [comment]
就是划上去再划回来viewpager 或者横向recyclerview 会复位，而不是上次的位置

**Comment by AllenCoder** [comment]
在数据model层标记viewpager的位置，在convert方法里面通过model标记的状态字段重新设置viewpager的位置
