### ISSUE TITLE
加载更多时出现 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first. 

### ISSUE THREAD

**Issue by wsparse** [CymChad/BaseRecyclerViewAdapterHelper#2325]
大神，我在将项目移植到本地使用时，设置每页加载条数足够少(3条)，在执行加载OnRequestDataListener中的onLoadMore()方法时，初始应该就是要连续两次执行加载更多的方法加载的数据才能够满屏使得BaseQuickAdapter中的mLoadingView不可见。但此时就会抛标题所述的异常。并且具体也没有在log日志中显示是哪行代码出这个异常。我猜想可能是由于mLoadingView导致出现这个异常。我本想在拷贝下的你的项目中来修改INCREASE_PAGE = 3;来重现一下，但page* INCREASE_PAGE来得到的数据我理解为本次请求的条数和你的项目中@get("nc/article/{type}/{id}/{startPage}-20.html")的startPage的意思好像有点不同，因此没能重现。另外若我设置每页加载5条在我的程序中就只需一次加载更多就能使数据满屏，此时就不会抛这个异常。希望能帮忙看看这是怎么回事。

**Comment by AllenCoder** [comment]
相同问题解决方案可能有如下情形导致请自查代码
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=+java.lang.IllegalStateException%3A+The+specified+child+already+has+a+parent.+You+must+call+removeView%28%29+on+the+child%27s+parent+first.](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=+java.lang.IllegalStateException%3A+The+specified+child+already+has+a+parent.+You+must+call+removeView%28%29+on+the+child%27s+parent+first.)


[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/569](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/569)
