### ISSUE TITLE
removeDataFromParent(T child) 空指针异常

### ISSUE THREAD

**Issue by yingka** [CymChad/BaseRecyclerViewAdapterHelper#2326]
BaseMultiItemQuickAdapter 中的方法removeDataFromParent(T child)代码段 parent.getSubItems().remove(child);空指针异常，建议做非空判断
List subItems = parent.getSubItems();
            if (subItems != null) {
                subItems.remove(child);
            }

**Comment by CymChad** [comment]
收到你的建议
