### ISSUE TITLE
建议：在混淆配置中增加内部类相关配置

### ISSUE THREAD

**Issue by alwaystest** [CymChad/BaseRecyclerViewAdapterHelper#2327]
```
-keepattributes InnerClasses
```

使用版本2.9.40

自定义ViewHolder，发现在Release版本反射生成ViewHolder失败。进一步追查原因的时候发现是BaseQuickAdapter尝试生成非静态内部类的ViewHolder的时候，`class.isMemberClass()`返回了false。
然后发现只要ProguardRules里面没有指定`-keepattributes InnerClasses`，混淆过后判断就失效了。

`getDefaultProguardFile('proguard-android-optimize.txt')` 获取的Default Rules里面是有这条的，但是如果有用户直接使用自己指定的ProguardRule，不使用`getDefaultProguardFile`的话，就会出现上面的问题。

所以建议Readme里面的ProguardRule把这条规则也加上。

**Comment by CymChad** [comment]
已修改，谢谢你的建议。
