### ISSUE TITLE
在初始化适配器，setAdapter绑定Recyleview后，调用disableLoadMoreIfNotFullPage，结果报错:please bind recyclerView first! 

### ISSUE THREAD

**Issue by dary123** [CymChad/BaseRecyclerViewAdapterHelper#2331]
在初始化适配器，setAdapter绑定Recyleview后，调用disableLoadMoreIfNotFullPage，结果报错:please bind recyclerView first!

**Comment by NateRobinson** [comment]
我也遇到这个问题了，这个方法貌似放哪都有问题，求解答～

**Comment by xiaolongwuhpu** [comment]
+1

**Comment by SoySauce1024** [comment]
放在设置 loadmore 监听方法「adapter.setOnLoadMoreListener(listener,recyclerview) 」 之后不会报错，我一直是这么处理的

**Comment by oksimple** [comment]
+1

**Comment by XiFanYin** [comment]
> 放在设置 loadmore 监听方法「adapter.setOnLoadMoreListener(listener,recyclerview) 」 之后不会报错，我一直是这么处理的

好像这样还是会每次触发加载更多执行
