### ISSUE TITLE
setEmptyView()是对数据集合进行监听了吗?清空数据集合emptyview就会显示

### ISSUE THREAD

**Issue by AnJiuZhe** [CymChad/BaseRecyclerViewAdapterHelper#2335]
实现搜索功能的时候,第一次搜索出来的结果不为空,添加进集合,更换搜索词时清空数据集合,emptyview显示了,此时还未调用adapter.notifyDataSetChanged()方法,请求到数据后添加进集合,emptyview隐藏,这样就导致了emptyview一闪而过.需要怎么解决呢?谢谢

**Comment by liupeng826** [comment]
请问你解决这个问题了吗？

**Comment by AnJiuZhe** [comment]
@liupeng826 恩，解决了。如果你要刷新数据的话，在请求数据之前不要清空数据源，请求拿到数据之后调用adapter.setNewData()就可以了。

**Comment by liupeng826** [comment]
多谢
