### ISSUE TITLE
question not bug

### ISSUE THREAD

**Issue by JarvisBuop** [CymChad/BaseRecyclerViewAdapterHelper#2338]
![default](https://user-images.githubusercontent.com/17249566/42488627-0f2775fc-8439-11e8-9f99-06ba0b4bbd04.png)
问题(不是bug):
 BaseMultiItemQuickAdapter-convert(...) 方法中
RecyclerViewHolder h = multiTypeViewHolders.get(viewType).get(key);
        if (h == null) {
            // build
            try {
                Class<? extends RecyclerViewHolder> cls = holderClasses.get(viewType);
                Constructor c = cls.getDeclaredConstructors()[0]; // 第一个显式的构造函数
                c.setAccessible(true);
                h = (RecyclerViewHolder) c.newInstance(new Object[]{this});
                multiTypeViewHolders.get(viewType).put(key, h);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
RecyclerViewholder 的子类为何不能为内部类 ,会报参数数目异常?
如果是静态内部类就没问题;

**Comment by 1109993488** [comment]
https://blog.csdn.net/qq_26287435/article/details/81809708
