### ISSUE TITLE
scrollview嵌套recyclerview

### ISSUE THREAD

**Issue by strangecontries** [CymChad/BaseRecyclerViewAdapterHelper#2341]
版本号：2.9.30
scrollview嵌套recyclerview，使用上滑加载的时候，recyclerview底部判断不准确，一直会回调onLoadMoreRequested方法，请问这个问题怎么解决呢？

**Comment by Panxiaoan1993** [comment]
> 我也是同样的问题



> 版本号：2.9.30
> scrollview嵌套recyclerview，使用上滑加载的时候，recyclerview底部判断不准确，一直会回调onLoadMoreRequested方法，请问这个问题怎么解决呢？

换方案，scrollview嵌套recyclerview无非就是想把不同布局放到一起滑动，如果布局不复杂，建议采用addHeaderView的方式，如果复杂，建议采用Material Design

**Comment by CymChad** [comment]
@Panxiaoan1993 感谢你的回答

**Comment by weixiao666** [comment]
> @Panxiaoan1993 感谢你的回答



> > 我也是同样的问题
> 
> > 版本号：2.9.30
> > scrollview嵌套recyclerview，使用上滑加载的时候，recyclerview底部判断不准确，一直会回调onLoadMoreRequested方法，请问这个问题怎么解决呢？
> 
> 换方案，scrollview嵌套recyclerview无非就是想把不同布局放到一起滑动，如果布局不复杂，建议采用addHeaderView的方式，如果复杂，建议采用Material Design
我们现在需求是往上滑动的时候，顶部的搜索栏颜色根据滑动的距离渐变，然后搜索框固定在顶部，所以需要用scrollview来判断滑动的距离，如果不用scrollview有别的什么好的方法判断滑动了多少吗
