### ISSUE TITLE
recyclerview嵌套gridlayout的recyclerview，点击gridlayout的recyclerview条目,如何获取外层recyclerview位置

### ISSUE THREAD

**Issue by chao9267** [CymChad/BaseRecyclerViewAdapterHelper#2343]
recyclerview嵌套gridlayout布局的recyclerview,
gridlayout布局的recyclerview里面是图片（0-9张）,点击gridlayout布局的图片的时候  如何获取被点击的是外层recyclerview的哪一条数据？

**Comment by AnJiuZhe** [comment]
我也遇到类似的问题了。点击子recyclerview不知道怎么获取父Recyclerview的position，请问你解决了这个问题没？

**Comment by TongGuHermint** [comment]
同问，点击的明明是第一个item的第一个子item，打印出来确是第二个item的第一个子item了

**Comment by CymChad** [comment]
收到
