### ISSUE TITLE
item 隐藏部分控件导致留空白

### ISSUE THREAD

**Issue by helloworkcupid** [CymChad/BaseRecyclerViewAdapterHelper#2345]
if(!TextUtils.isEmpty(item.image)){

            helper.setGone(R.id.card_view,true);
            helper.setGone(R.id.bgImageView,true);

            Glide.with(mContext).load(item.image).crossFade().into((ImageView) helper.getView(R.id.bgImageView));

        }else {
//             helper.getView(R.id.card_view).setVisibility(View.GONE);
            helper.setGone(R.id.card_view,false);
            helper.setGone(R.id.bgImageView,true);
        }

adapter 种使用这个方法，得到的结果是，布局隐藏的地方，出现了空白

**Comment by helloworkcupid** [comment]
提问之前我看过了解决方案，我的用的compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.40'版本，仍然没有解决，请提供帮助，谢谢

**Comment by helloworkcupid** [comment]
已解决

**Comment by mzhkby** [comment]
@helloworkcupid 怎么解决的？

**Comment by ludoven** [comment]
怎么解决的

**Comment by winter20lee** [comment]
去调整数据源，而不是去控制显示/隐藏，高度已经算进去了
