### ISSUE TITLE
RecyclerView A嵌套Recyclerview B，设置A的setOnItemClickListener，在点击到B的区域A的setOnItemClickListener无响应，要怎么解决

### ISSUE THREAD

**Issue by CodingHornet** [CymChad/BaseRecyclerViewAdapterHelper#2346]
RecyclerView A嵌套Recyclerview B，设置A的setOnItemClickListener，在点击到B的区域A的setOnItemClickListener无响应，要怎么解决

**Comment by CymChad** [comment]
收到

**Comment by AllenCoder** [comment]
设置 itemview的 子布局的焦点获取顺序
或者 设置父布局的事件分发顺序 
http://www.yanglajiao.com/article/huangxin112/79415079
