### ISSUE TITLE
headView添加了一个viewpager，viewpager不能滑动了

### ISSUE THREAD

**Issue by dcbinn** [CymChad/BaseRecyclerViewAdapterHelper#2347]
headView添加了一个viewpager，viewpager不能滑动了，viewpager是取消了预加载的，然后用了一个定时器然他轮播，但是手动切换viewpager是失效的  是不是有滑动冲突

**Comment by CymChad** [comment]
收到

**Comment by franticn** [comment]
同样的问题，我这边可以滑动 滑动后会导致ANR,还在排查原因

**Comment by limuyang2** [comment]
此问题不属于本库的问题，在项目中没有出现过此问题。headView里的viewpager并不会影响滑动

**Comment by limuyang2** [comment]
> 同样的问题，我这边可以滑动 滑动后会导致ANR,还在排查原因

此问题，线上项目也曾遇到过，由于RV本身的回收复用机制，需要自定义viewpager，重写相关的方法。

**Comment by franticn** [comment]
> 此问题，线上项目也曾遇到过，由于RV本身的回收复用机制，垂直滑动时，headView被滑出了屏幕，viewpager可能就会崩溃。需要自定义viewpager，重写相关的方法。

左右滑动，并不是上下滑动。此时Header的position就在0的位置。
