### ISSUE TITLE
MultiTypeDelegate继承问题

### ISSUE THREAD

**Issue by hcg2011** [CymChad/BaseRecyclerViewAdapterHelper#2349]
public abstract class MultiTypeDelegate<T> {

    private static final int DEFAULT_VIEW_TYPE = -0xff;
    private SparseIntArray layouts;
    private boolean autoMode, selfMode;

    public MultiTypeDelegate(SparseIntArray layouts) {
        this.layouts = layouts;
    }

其中 DEFAULT_VIEW_TYPE  和 layouts 可以修改为protected的吗？子类继承了该方法用于实现多item的时候，发现不能调用layouts。扩展性欠缺

**Comment by CymChad** [comment]
收到，可以提个建议到 #2806

**Comment by limuyang2** [comment]
提个建议到 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2806
