### ISSUE TITLE
setNewData的问题

### ISSUE THREAD

**Issue by BestSingerInSiHui** [CymChad/BaseRecyclerViewAdapterHelper#235]
我之前用1.8.5的时候没有问题的，后来看到更新到1.9.7之后我更新了一下

**Comment by BestSingerInSiHui** [comment]
之前我在new Adapter的时候只放一个空list，到后面获取数据之后再setNewData进去，是没有问题的

现在1.9.7发现使用 setNewData这个方法之后，报ViewRootImpl$CalledFromWrongThreadException，
虽然我用activity.runOnUiThread，再在Runnable里面setNewData()解决了问题，但总感觉别扭

**Comment by CymChad** [comment]
setNewData() 这个方法一直没改过。
