### ISSUE TITLE
当使用nestscrollview + recyclerview 时 setOnLoadMoreListener 会一直不停的回调

### ISSUE THREAD

**Issue by xiaoyaomimi** [CymChad/BaseRecyclerViewAdapterHelper#2353]

**Comment by harmongao** [comment]
有解决方案吗

**Comment by xilingit** [comment]
我也遇到这个问题了，求作者解答

**Comment by 1322739583** [comment]
确实存在这个问题啊  正常使用下拉加载功能  只要在布局外面加一层nestscrollview就会出现这个问题 网上有人分析了具体原因https://www.jianshu.com/p/23e979f06a4d  给出方案是用addheaderview。有没有别的解决方案？

**Comment by Panxiaoan1993** [comment]
这个问题是一直都存在的，也不是这个库的问题，我做项目的时候，由于结构是SwipeRefreshLayout+banner+横向recyclerView+纵向recyclerView，在这个问题上栽了很多跟头，这里给一些建议吧：
1. 如果非要使用nestedScrollView，可以给adapter设置OnLoadMoreListener，但是回调里面什么也不做，然后给NestedScrollView设置OnScrollChangeListener，根据NestedScrollView是否滑动到底部，来做加载更多的操作，但是这样做有一个致命缺点，就是recyclerView的item不会复用，性能极差，不推荐使用；

2. 用BaseMultiItemQuickAdapter，把每一种View当成一个recyclerview的一个item，可滑动区域就只有一个recyclerview，优点：所有的view事件分发都会交由recyclerView完成，没有滑动冲突；  缺点：view的状态更新、数据操作非常不方便；

3. 采用addHeaderView，通过添加头部的方式来解决这个问题，这个方案在除了recyclerview的其它view不复杂的情况下比较好用，如果headerView太复杂，也不好管理；

4. 采用Material Design，这也是我的项目中改了几次后，最终采用的方法，采用这个方案的原因主要是前面几种方案的缺点都刚好在我这里体现的淋漓尽致，再加上UI改版需要用到动画效果，所以才开始使用Material Design，我的做法是把banner、横向recyclerView和其它view都包裹在appbarLayout里面，最后的纵向recyclerview作为滚动target；优点：view分开管理，数据更新、删除、显示隐藏非常方便，可以根据需求定制滑动时各个view的动画效果，优雅的同时代码也好管理；当然也是有缺点的，缺点：需要处理一些滑动冲突，比如banner采用的是viewpager，viewpager跟SwipeRefreshLayout的手势上有一些冲突，还有AppbarLayout跟纵向recyclerView有滑动冲突，当然这几个都非常非常容易解决，所以还是觉得这种方案最合适。

**Comment by CymChad** [comment]
@Panxiaoan1993 感谢你的回复
