### ISSUE TITLE
如何设置adpter 不自动上拉加载更多。

### ISSUE THREAD

**Issue by cwgsmart** [CymChad/BaseRecyclerViewAdapterHelper#2354]
1.我的项目中使用了BaseMultiItemQuickAdapter 实现了两层可收缩展开的RecyclerView 效果
我设置的pageSize 为30 。
当我点击上层的title 时显示或隐藏 子Item的view效果。
但是当我点击title 调用 adapter 的 expand(pos) 方法时。这时adapter 自动加载了下一页。这不是我想要的效果。我只是想把这30个子Item 收缩起来。并不想加载更多。
请问如何处理。

**Comment by CymChad** [comment]
通过判断调用关闭上拉加载的函数
