### ISSUE TITLE
emptyView无法居中的问题

### ISSUE THREAD

**Issue by taotaodai** [CymChad/BaseRecyclerViewAdapterHelper#2357]
使用setHeaderAndEmpty(true)以后，由于headerView占了一部分高度，导致emptyView中的内容无法居中。
![2 tsimh zyu z ujmg l3s](https://user-images.githubusercontent.com/13148199/42874690-4dcb5d1a-8ab4-11e8-841f-a88fc7275690.png)

![screenshot_20180718-175219](https://user-images.githubusercontent.com/13148199/42874702-5564abd0-8ab4-11e8-97eb-99cda88c7056.jpg)

**Comment by stiflerfang** [comment]
你要把你的emptyview的布局设置成全屏的，然后内容居中，你可以看下源码里面，其实是新建了一个全屏的layout来存放你的emptyview，所以你自己的emptyview要想办法弄成居中的。
