### ISSUE TITLE
在小米4.4版本上出现的 适配器 数据错误（ui不更新）问题

### ISSUE THREAD

**Issue by yinlliang** [CymChad/BaseRecyclerViewAdapterHelper#2359]
使用适配器做下拉刷新，以及条件筛选功能时，数据源应该是动态的改变的，但是在xiaomi4.4机型上会出现筛选之后 界面错乱的问题，主要是进度条的进度值出现错乱，实际数据是正确的，当往下拉动列表然后再拉回来时会恢复正常，刷新时也会这样，请问这是为什么？我有尝试解决，比如加载新的数据之前将 lendAdapter.setNewData(null);这样会解决上面描述的情况，但是会出现一个新的问题，就是在更新数据时会出现闪屏，先闪一下再出现数据，这样的体验还是有点别扭。
 private void initData() {
        pagerNumber=1;
        map.put("pageNumber",pagerNumber);
        if(lendAdapter!=null){
            lendAdapter.setEnableLoadMore(false);//这里的作用是防止下拉刷新的时候还可以上拉加载
        }
        //获取标的列表数据
        RxRetrofitManager.getHttpRequestService()
                .listFinance(map)
                .subscribeOn(Schedulers.io())
                .compose(this.<SubjectBean>bindToLifecycle())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new BasicObserver<SubjectBean>() {
                    @Override
                    public void onSuccess(SubjectBean response) {
                        srlInvest.setRefreshing(false);
                        subjectBean=response;
                        if(lendAdapter!=null){
                            lendAdapter.setEnableLoadMore(true);//这里的作用是防止下拉刷新的时候还可以上拉加载
                        }
                        subjectList.addAll(response.getList());
                        setData(true,response.getList());
                    }

                    @Override
                    public void onError(Throwable e) {
                        super.onError(e);
                        if(lendAdapter!=null){
                            lendAdapter.setEnableLoadMore(true);//这里的作用是防止下拉刷新的时候还可以上拉加载
                        }
                        srlInvest.setRefreshing(false);
                    }
                });

    }
private void setData(boolean isRefresh, List<SubjectBean.ListBean> data) {
        final int size = data == null ? 0 : data.size();
        if (isRefresh) {
            //加载新数据
            if(size==0){
                //如果没有数据则显示 无数据
                rvStanderpower.setHasFixedSize(true);
                //初始化无数据布局
                notDataView =mActivity.getLayoutInflater().inflate(R.layout.empty, (ViewGroup) rvStanderpower.getParent(), false);
                //将无数据布局设置到适配器中
                lendAdapter.setEmptyView(notDataView);
            }else{
                lendAdapter.setNewData(data);
            }
        } else {
            //加载更多
            if (size > 0) {
                lendAdapter.addData(data);
            }
        }
        if (size < pagerSize) {
            //第一页如果不够一页就不显示没有更多数据布局
            lendAdapter.loadMoreEnd(isRefresh);
        } else {
            lendAdapter.loadMoreComplete();
        }
    }
   private void initAdapter(){
        rvStanderpower.setLayoutManager(layout);//竖直放置
        lendAdapter = new LendAdapter(subjectList, mActivity);
        lendAdapter.setPreLoadNumber(0);//取消预加载
        lendAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                loadMore();
            }
        },rvStanderpower);
        rvStanderpower.setAdapter(lendAdapter);
        lendAdapter.notifyDataSetChanged();
    }

这是主要的代码，刷选时会重新调用initData（）
,麻烦帮忙看下，谢谢!

**Comment by AllenCoder** [comment]
1. 进度条的值需要跟model中的字段对应绑定
2. 刷新闪屏应尽量避免使用setNewData()

**Comment by yinlliang** [comment]
您好，感谢您的回答，进度条的值是已经和model中的字段进行了绑定的，而且这种现象在版本高的机型之上并不会出现，
