### ISSUE TITLE
树形列表删除bug

### ISSUE THREAD

**Issue by shenbengit** [CymChad/BaseRecyclerViewAdapterHelper#2361]
![image](https://user-images.githubusercontent.com/24364422/43033030-5aa7a424-8cf5-11e8-81b6-5db85d9c3dfd.png)
在树形列表中，如果一级目录下没有子目录时，在调用BaseMultiItemQuickAdapter中remove(int position),删除，会导致程序崩溃。你使用你写的列子也是这样。
![image](https://user-images.githubusercontent.com/24364422/43033085-3bf98064-8cf6-11e8-864e-ef230a14fd64.png)
![image](https://user-images.githubusercontent.com/24364422/43033093-4f3d20c2-8cf6-11e8-9d5b-f07f14625c58.png)

**Comment by CymChad** [comment]
收到
