### ISSUE TITLE
九宫格数据不足一平，会一直刷新

### ISSUE THREAD

**Issue by cuiyt123** [CymChad/BaseRecyclerViewAdapterHelper#2363]
后台一次返回十条数据，我用的是九宫格的布局，一列是四个，三列不满足一屏，有刷新事件，会一直刷新直到最后一页，怎么处理呢，如果增加loadMoreEnd方法那就没法下拉刷新了，做了判断也不行

**Comment by AllenCoder** [comment]
参考加载更多的demo写法 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)
