### ISSUE TITLE
关闭动画后在调用notifyItemChanged时会触发动画效果SLIDEIN_BOTTOM

### ISSUE THREAD

**Issue by GoAheadComeOn** [CymChad/BaseRecyclerViewAdapterHelper#2365]
在初始化adapter的时候调用mAdapter.closeLoadAnimation()，然后在刷新某一项数据时调用mAdapter.notifyItemChanged(position)，这个时候会有一个从底部滑动的效果。

**Comment by 17770843708** [comment]
遇到同样的问题 很别扭 mAdapter.closeLoadAnimation()后执行mAdapter.notifyItemChanged()还是会有默认的渐显动画 求解

**Comment by CymChad** [comment]
收到

**Comment by limuyang2** [comment]
在recyclerview中关闭动画后再次尝试。
如果还有问题，请提供demo，并参照 
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues 提交问题
