### ISSUE TITLE
getViewByPosition方法为什么有时候会返回null

### ISSUE THREAD

**Issue by Holyn** [CymChad/BaseRecyclerViewAdapterHelper#2366]
调用BaseQuickAdapter里的getViewByPosition方法去获取适配器里面的某个view，有时会出现null。比如列表有100条，当打开列表滑动到底部，那么使用getViewByPosition获取列表第一条的view就会null。有什么方法可以避免这个问题？

**Comment by AllenCoder** [comment]
当第一条view 被回收时就会返回null ,需要做非空判断。
2. 关闭回收机制，不建议这么做

**Comment by DevelopWb** [comment]
> 我必须要拿到每个view上面的数据，那怎么办，每个view都会由用户输入数据

解决了 吗
