### ISSUE TITLE
recycler使用动画问题？

### ISSUE THREAD

**Issue by XiongKe94** [CymChad/BaseRecyclerViewAdapterHelper#2368]
如何使用BaseRecyclerViewAdapterHelper和recyclerview-animators这个库
https://github.com/wasabeef/recyclerview-animators
代码:
   mRecyclerView!!.itemAnimator = LandingAnimator(OvershootInterpolator(1f))
怎么都没有效果

**Comment by CymChad** [comment]
可以直接使用本库的动画方法，本库也支持自定义动画。
