### ISSUE TITLE
在ItemProvider中如何处理子View的点击事件呢？

### ISSUE THREAD

**Issue by aloe20** [CymChad/BaseRecyclerViewAdapterHelper#2370]
ItemProvider有onClick和onLongClick方法，如何处理子View的点击事件呢？

**Comment by ImportEffort** [comment]
我现在也有这个疑问，如果addClickListener 只能在adapter中去拿点击事件，造成逻辑耦合了，既然ItemProvider的出发点是逻辑解耦 那么这个的确需要处理一下

**Comment by AllenCoder** [comment]
ItemProvider是后面的一个多布局的实现方案，跟我们之前的部分功能重叠了，可以忽略

**Comment by ImportEffort** [comment]
为撒忽略，我觉得该方案还可以呀，对于多种复杂条目的可以很好的进行逻辑分离，既然接受的pr我觉得还是有必要维护下去。
