### ISSUE TITLE
关于BaseItemProvider的问题

### ISSUE THREAD

**Issue by jeonhei** [CymChad/BaseRecyclerViewAdapterHelper#2371]
能不能为BaseItemProvider提供构造ViewHolder时的回调事件 现在的BaseItemProvider并不能完全的做到业务独立 例如我以往可以在ViewHolder的构造方法里一次性的为TextView添加TextWatcher 现在只能在ItemProvider的convert方法里创建TextWatcher并付值为ItemProvider的成员变量 然后addTextWatcher之前检测成员mTextWachter是否为空 如果不为就先执行removeTextChangedListener方法然后再创建一个新的TextWahter成员去付值 有点恶心...希望作者可以改进一下

**Comment by CymChad** [comment]
收到 可以提一个建议到 #2806
