### ISSUE TITLE
setOnLoadMoreListener没有任何响应，该设置的都设置过了

### ISSUE THREAD

**Issue by gsn516** [CymChad/BaseRecyclerViewAdapterHelper#2372]
mRecyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
        mRightAdapter = new ShopDataAdapter(getContext());
        mRightAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                pageIndex = pageIndex + 1;
                getPresenter().queryMaterialDatailmore(typeId, pageIndex, pageSize);
            }
        });
        mRightAdapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_LEFT);
        mRecyclerView.setAdapter(mRightAdapter);
        mSwipeRefreshLayout.setColorSchemeResources(R.color.gray);
        mSwipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                refresh();
            }
        });

**Comment by gsn516** [comment]
没有效果，我绑定过了onLoadMoreRequested里面方法没有回调

**Comment by gsn516** [comment]
我对照过demo了，没有缺少什么，是哪边出了问题了呢？

**Comment by yedajiang44** [comment]
一样。。。不知道怎么回事，我用的kotlin，只有第一次上啦的时候有用，第二次就嗝屁了

**Comment by CymChad** [comment]
请对照检查你的使用步骤是否缺少。
