### ISSUE TITLE
在使用loadMore的时候出现的问题

### ISSUE THREAD

**Issue by Cloudant-android** [CymChad/BaseRecyclerViewAdapterHelper#2374]
`if (adapter.getData().size() >= total){
            adapter.loadMoreEnd(true);
        } else if (adapter.getData().size() < total){
            adapter.setEnableLoadMore(true);       
        } else {
            adapter.loadMoreFail();
        }`
这部分代码在表示adapter能加载更多的时候并且数据不够分页的数量的时候，它不会加载，求回答是我的用法错误开始怎么回事？

**Comment by qianshengta** [comment]
loadMoreComplete()//本次加载结束，但是服务器还有更多数据，还会触发加载更多
loadMoreFail()//本次加载失败，还会触发加载更多
loadMoreEnd()//加载结束，服务器没有更多数据了，不会在触发加载更多了

**Comment by CymChad** [comment]
@qianshengta  感谢你的回复
