### ISSUE TITLE
BaseMultiItemQuickAdapter的问题

### ISSUE THREAD

**Issue by aojiaoqiang** [CymChad/BaseRecyclerViewAdapterHelper#2377]
在菜单展开的时候 去清理菜单下面的所有的item 会导致item一直在菜单下面 无法折叠
getSubItems().clear();

**Comment by CymChad** [comment]
收到

**Comment by shichaohui** [comment]
`getSubItems().clear()` 只是删除了数据，没有更新 UI。
可以使用 `Adapter#remove()` 的方式删除数据（自动更新 UI）。
在之后的版本中，我们会新增删除所有 subItem 的函数。
