### ISSUE TITLE
添加一条headerView后，scrollToPosition（0）无法返回顶部，需要手动向下划一下

### ISSUE THREAD

**Issue by SiXuManYan** [CymChad/BaseRecyclerViewAdapterHelper#2382]
列表setData后，根据具体需求add了一条headerView( 就是一个高度为40的textView )，手动调用了以代码

```
               recyclerView.getLayoutManager().scrollToPosition(0);
               recyclerView.smoothScrollToPosition(0);
```
列表无法滚动到顶部,，需要手动向下滑动一下才能滑动到顶部
查了其他issues，没有得到解决方案

**Comment by ApolloXiao** [comment]
我也有同样的问题，求解决方案。。

**Comment by AllenCoder** [comment]
参考解决方案 [https://github.com/AllenCoder/Recyclerview](https://github.com/AllenCoder/Recyclerview)
