### ISSUE TITLE
使用BaseMultiItemQuickAdapter出现getViewType()=0 导致程序崩溃

### ISSUE THREAD

**Issue by hy20160705** [CymChad/BaseRecyclerViewAdapterHelper#2383]
主要问题是这样子的  我的RecycleView中是有多布局展示  我的数据获取需要调用两个后台服务接口（调用第一个接口 再根据第一个接口里面的数据 调用第二个接口 ）mData中的数据是两个接口的数据合并起来的
Important：我调用第一个接口之后  还未调用notify函数  就触发了数据更新操作 调用getViewType（）=0，导致程序崩溃 
以下是我的代码：
[MultilStrogeDataAdapter .txt](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/2260020/MultilStrogeDataAdapter.txt)
[StorageDataFargment .txt](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/2260019/StorageDataFargment.txt)

**Comment by AllenCoder** [comment]
提供更多崩溃日志，以便排查问题
