### ISSUE TITLE
请教一个加载多布局的问题

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#2384]
后台返回10条列表数据,为什么我这样设置了多布局后只显示9条了?
`  HomeBean homeBean = getArguments().getParcelable(AppExtra.HOME_DATA);
        List<HomeBean.FocusEventBean> focusEventBeans = homeBean.getFocus_event();//获取比赛数据
        List<HomeBean.ArticleInfoBean> articleInfoBean = homeBean.getArticleInfo();//首页资讯列表(布局一)
        mAdapter = new HeadlineAdapter(R.layout.item_home_page, articleInfoBean, homeBean);
        //添加首页headerview
        view = View.inflate(getActivity(), R.layout.home_header_view, null);
        mViewPager = view.findViewById(R.id.vp_home_header);
        mViewPager.addOnPageChangeListener(this);
        mPageList = new ArrayList<>();
        for (int i = 0; i < focusEventBeans.size(); i++) {
            //动态生成顶部比赛页面
            HomeBean.FocusEventBean gameBean = focusEventBeans.get(i);
            HomeGameFragment homeGameFragment = HomeGameFragment.newInstance(gameBean);
            FragmentPage fragmentPage = new FragmentPage(homeGameFragment, "");
            mPageList.add(fragmentPage);
        }
        BaseFragmentPagerAdapter adapter = new BaseFragmentPagerAdapter(getChildFragmentManager(), mPageList);
        initHeader();//ViewPager为第一页的数据展示
        mViewPager.setAdapter(adapter);
        mAdapter.addHeaderView(view);
        mAdapter.setOnItemClickListener(this);

        //加载多布局
        for (int i = 0; i < articleInfoBean.size(); i++) {
            HomeBean.ArticleInfoBean bean = articleInfoBean.get(i);
            if (i == 3) {
                bean.setLayoutType(HomeBean.ArticleInfoBean.SECOND_TYPE); //在第四条item设置第二种布局
            } else {
                bean.setLayoutType(HomeBean.ArticleInfoBean.NORMAL_TYPE);//默认第一种布局
            }
        }
        //TODO:布局一数据少了一条
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getActivity());
        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        DividerItemDecoration mDividerItemDecoration = new DividerItemDecoration(getActivity(), linearLayoutManager.getOrientation());
        mRecyclerView.addItemDecoration(mDividerItemDecoration);
        mRecyclerView.setLayoutManager(linearLayoutManager);
        mRecyclerView.setAdapter(mAdapter);//   设置文章列表数据
//        mAdapter.notifyItemChanged(2,articleInfoBean.size());
//        mAdapter.notifyItemChanged(2,2);
//        mAdapter.notifyItemRangeChanged(2,articleInfoBean.size());`

**Comment by AllenCoder** [comment]
检查你的数据结构
