### ISSUE TITLE
使用GridLayoutManager 时候 loadMoreView的宽度显示不正常。

### ISSUE THREAD

**Issue by LucasDevelop** [CymChad/BaseRecyclerViewAdapterHelper#2388]
loadMoreView是以item的方式加入的，所以他的宽度是以一个item的宽度显示的。

**Comment by pengfeigao** [comment]
+1，我的是添加header后导致整个RecyclerView整体右边有大约2dp的间距

**Comment by 7hundeR** [comment]
> loadMoreView是以项目的方式加入的，所以他的宽度是以一个项目的宽度显示的。

能跟footerView一样设置setFooterViewAsFlow()吗

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
![image](https://user-images.githubusercontent.com/7698209/61641180-4195f600-acd1-11e9-856b-e620ef87e7e1.png)
我这边使用demo使用了GridLayoutManager，loadMoreView显示正常，如果还有问题可以提供复现demo。

**Comment by yingka** [comment]
![youdu图片20191126182828](https://user-images.githubusercontent.com/20808020/69621858-d3947d80-107a-11ea-843c-1e194bca2c7d.png)
试试在recyclerView先设置LinearLayoutManager，再绑定adapter，再次设置GridLayoutManager
可以复现
