### ISSUE TITLE
意外发现加载更多出现死循环自动请求与回调，情况代码如下

### ISSUE THREAD

**Issue by xueyaolive** [CymChad/BaseRecyclerViewAdapterHelper#239]
执行如下代码加载更多，分页15条，此时18条数据
@Override public void onLoadMoreRequested() {
        isUpLoad = 1;
        int number = pageNumber + 1;
        initData(number);//异步请求网络数据
    }
成功返回数据
   @Override
    public void collectSuccess(PageActiveRsponse rsponse) {
        pageActiveRsponse = rsponse;
        if (pageActiveRsponse == null) {
            return;
        }
        activeListResponses = pageActiveRsponse.getActivitys();
        if (isUpLoad == 0) {
//刷新的数据
            mSwipeRefreshLayout.setRefreshing(false);
            myCollectActiveAdapter.setNewData(activeListResponses);
        } else {
//加载更多数据
            pageNumber = pageNumber + 1;
            myCollectActiveAdapter.notifyDataChangedAfterLoadMore(activeListResponses, true);
        }
//判断是否还可以加载更多，当返回18数据是正常的，
//意外: 第一页已经加了15条，原本还有3条，在第二页加载，如果此时却返回了2条数据
//  if (dataSize > 0 && dataSize >= pageActiveRsponse.getTotalCount())自然这个方法没有进入就出现死循环自动请求与回调，如果是返回3条就进入这个方法就不会出问题
pageActiveRsponse.getTotalCount() ＝＝ 17，
        int dataSize = myCollectActiveAdapter.getData().size();
        if (dataSize > 0 && dataSize >= pageActiveRsponse.getTotalCount()) {
            myCollectActiveAdapter.notifyDataChangedAfterLoadMore(false);
            View view = getLayoutInflater().inflate(R.layout.view_load_done, (ViewGroup) mRecyclerView.getParent(), false);
            myCollectActiveAdapter.addFooterView(view);
        }
    }
//我认为以上是一个bug，大神可以试试这种情况

**Comment by CymChad** [comment]
你的pageSize是？

**Comment by CymChad** [comment]
private boolean isLoadMore() {
return mNextLoadEnable && pageSize != -1 && mRequestLoadMoreListener != null && mData.size() >= pageSize;
}
这是是否加载更多的判断，你可以看下。

**Comment by CymChad** [comment]
为什么这个没有进入？ if (dataSize > 0 && dataSize >= pageActiveRsponse.getTotalCount())，这是外面判断的问题，而不是方法本身的问题。

**Comment by CymChad** [comment]
因为如果你的数据没有加载完，所以会不断的加载，逻辑上这是正常的，如果你的数据加载完了调用了myCollectActiveAdapter.notifyDataChangedAfterLoadMore(false); 也就不会调用回调了。

**Comment by CymChad** [comment]
这属于后台返回数据有误，总数量18数据，意外: 第一页已经加了15条，原本还有3条，在第二页加载，如果此时却返回了2条数据，那么就是不满足18，那么就不会进入if，就不会结束回调。因为你没有通知adapter数据加载完了，所以会一直加载。

**Comment by xueyaolive** [comment]
我知道是后台的原因，但却说明了另一个问题：我始终先调用了myCollectActiveAdapter.notifyDataChangedAfterLoadMore(activeListResponses, true);这个方法，而这个判断if (dataSize > 0 && dataSize >= pageActiveRsponse.getTotalCount())是为了添加一个尾部（并不是一定都要进入这个方法，只是最后一页进入），就是显示没有“更加数据加载了”（这个if当没有加载完18条数据是不会进入的），否则继续滑到底部可以加载更多！
假设：同样代码逻辑，当pageSize=15,共33条数据，也就是可以分3页，后台返回正常（就是返回来第三页有3条数据），也就是这个时候进入if (dataSize > 0 && dataSize >= pageActiveRsponse.getTotalCount())，前面两页不会进入，一切就会正常（未出现死循环自动请求与回调），
2.如果后台返回第三页是2条（原本要返回3条数据），前面两页还是会进入myCollectActiveAdapter.notifyDataChangedAfterLoadMore(activeListResponses, true);，与正常现象同理，不会进入if (dataSize > 0 && dataSize >= pageActiveRsponse.getTotalCount())，到了加载第3页，就出现  死循环自动请求与回调
总结：同样有时没有进入if (dataSize > 0 && dataSize >= pageActiveRsponse.getTotalCount())这个方法是正常的，进入这个方法只是为了不让触发加载更多，到最后一页进入

**Comment by CymChad** [comment]
如果没有更多数据了你调用一下  notifyDataChangedAfterLoadMore(false);   就不会加载更多了，至于你什么时候调用，这是你的逻辑控制的。adapter无法知道你的逻辑。
