### ISSUE TITLE
adapter.setOnItemChildClickListener无效的问题

### ISSUE THREAD

**Issue by Ccixyj** [CymChad/BaseRecyclerViewAdapterHelper#2391]
adapter.setOnItemChildClickListener 点击事件第一次有效，但是刷新后就无效了。

因为当前使用的是 `View.generateViewId()` 来生成id，且刷新列表时把 `ViewGroup` 清空并重新生成子 view 。debug发现在 `addOnClickListener(view.id)`  里 ，`BaseViewHolder` 的 `getView()` 还是原来的view，（因为新生成的view 和 原来的view id是一致的 ）。

另外，如果用 `RecyclerView.addOnItemTouchListener(OnItemChildClickListener)` 则无此问题

**Comment by baakonn** [comment]
adapter.setOnItemChildClickListener第一次点击无效
我也有遇到，但是只是第一次点击无效，之后就没问题了，改为recycleview.addOnItemTouchListener(new OnItemChildClickListener() {
 没有这个问题

**Comment by limuyang2** [comment]
请提供demo，并参照
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues 提交问题
