### ISSUE TITLE
一级列表折叠后，无法改变已经折叠的list数据

### ISSUE THREAD

**Issue by haoweizero** [CymChad/BaseRecyclerViewAdapterHelper#2396]
#2222 
我这个问题在#2222由问题提问者自己关闭了，但是我联系不到提问者，只好自己再重新开一个问题了。

**Comment by HarkBen** [comment]
是view的状态还是对应的data中的子集合状态呢？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
