### ISSUE TITLE
GridLayoutManager header和Load more的问题

### ISSUE THREAD

**Issue by niq2003** [CymChad/BaseRecyclerViewAdapterHelper#24]
当使用GridLayoutManager的时候，addHeaderView占的spansize应该是整个宽度，可以通过一下设置解决问题
 manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                if (position == 0) {
                    return 2;
                }
                return 1;
            }
        });
但是loadmore view占地spansize不是整个宽度，看了下代码，loadmore处理了StaggeredGridLayoutManager的情况，但是StaggeredGridLayoutManager的时候addHeaderView的spansize不知道如何处理

**Comment by CymChad** [comment]
那你直接使用StaggeredGridLayoutManager就可以了呀

**Comment by niq2003** [comment]
StaggeredGridLayoutManager addHeaderView header占的宽度不能通过setSpanSizeLookup设置

**Comment by CymChad** [comment]
哦，我知道了你就是想头部也占据一行对吧，我这边改一下就可以了

**Comment by niq2003** [comment]
对的，一般使用StaggeredGridLayoutManager 或GridLayoutManager 的时候headerview和footerview的需求大部分都是占一行吧

**Comment by CymChad** [comment]
恩 是的，我这边改一下，然后你在试试，稍等5分钟

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.7.1'  你试一下

**Comment by niq2003** [comment]
试了一下这个问题已经解决，谢谢～

**Comment by CymChad** [comment]
没事，有问题再提哦
