### ISSUE TITLE
setEnableLoadMore 设置问题

### ISSUE THREAD

**Issue by ruan7k** [CymChad/BaseRecyclerViewAdapterHelper#2400]
PullToRefreshUseActivity 页面  场景描述： 
1. 数据集合共2页   滑动到底部将所有数据加载完成。
2.断掉网络,下拉刷新数据 此时数据mNextRequestPage 被重置为1 ,mAdapter.setEnableLoadMore(true);
3 连接网络 用户滑动到底部触发  onLoadMoreRequested 方法  isRefresh 为false ，mNextRequestPage=1 ，数据完成加载后  mAdapter.addData(data); 方法 ，造成界面数据的重复。

**Comment by AllenCoder** [comment]
已修复demo的bug
