### ISSUE TITLE
二级菜单添加数据之后调用 调用adapter.setNewData(list); adapter.expandAll();并没有刷新新添加的数据

### ISSUE THREAD

**Issue by zoubihai** [CymChad/BaseRecyclerViewAdapterHelper#2401]
使用BaseMultiItemQuickAdapter,在原数据基础上的二级菜单添加新的数据level0Item.addSubItem();然后去调用adapter.setNewData(list); adapter.expandAll();list里面的一级菜单已经饱和新添加数据但是并没有刷新新添加的数据;

**Comment by gaofeng7777** [comment]
你好，我也遇到了这这问题，请问解决了吗？

**Comment by gaofeng7777** [comment]
@zoubihai 你好，我也遇到了这这问题，请问解决了吗？

**Comment by Clance** [comment]
同问题，真坑人，数据debug看到已经添加进去乐，刷新不展示

**Comment by zzm123456** [comment]
我也遇到了。。有解决方案吗

**Comment by zzm123456** [comment]
同问，我也遇到这种问题 有解决方案吗

**Comment by lianzigeng** [comment]
我也是的,不知道该怎么解决了,真的烦,二级目录展开的时候添加数据没反应,

**Comment by CymChad** [comment]
收到
