### ISSUE TITLE
树形菜单的一级菜单View没有复用

### ISSUE THREAD

**Issue by zjhcode** [CymChad/BaseRecyclerViewAdapterHelper#2402]
在二级菜单展开后，发现一级菜单的itemView没有复用，重新创建了一个View
我用原生API对比了一下，原生的一级菜单的View是复用的，这也符合原理，因为树形菜单
只是在一级菜单下面了添加了二级的item，而一级菜单始终在屏幕上，应该是可以复用的。

**Comment by CymChad** [comment]
感谢你的建议
