### ISSUE TITLE
用瀑布流layout  RecyclerView.scrollToPosition出现错位

### ISSUE THREAD

**Issue by longlylong** [CymChad/BaseRecyclerViewAdapterHelper#241]
RecyclerView.scrollToPosition

**Comment by CymChad** [comment]
这个框架是adapter的框架，和RecyclerView不耦合的。

**Comment by longlylong** [comment]
那这个是adapter还是RecyclerView的bug呢?
用girdlayout就不会出现错位

**Comment by CymChad** [comment]
scrollToPosition 这个属于系统方法。你是通过RecyclerView点出来的就是RecyclerView的方法。
