### ISSUE TITLE
需求是多个标题加item 

### ISSUE THREAD

**Issue by watermelonJun** [CymChad/BaseRecyclerViewAdapterHelper#2414]
标题使用的适配器   item用的gridview    现在可能有五个标题 然后每个标题都有item  item里面有imageview和一个textview   现在就算我不用网络加载图片   滑动也会很卡

 public class LabelAdapter extends BaseQuickAdapter<ClassificationBean.DataBean.ListDataBean, BaseViewHolder> {

        public LabelAdapter(List<ClassificationBean.DataBean.ListDataBean> subCategoriesList) {
            super(R.layout.classification_level2, subCategoriesList);
        }

        @Override
        protected void convert(final BaseViewHolder helper, ClassificationBean.DataBean.ListDataBean item) {
            helper.setText(R.id.tv_title1, item.getCateName());

            final List<ClassificationBean.DataBean.ListDataBean> subCategoriesList = item.getSubCategoriesList();

//            RecyclerView recycler = helper.getView(R.id.rcList);
//            recycler.setLayoutManager(new GridLayoutManager(getActivity(), 3));
//            recycler.setNestedScrollingEnabled(false);
//            recycler.setAdapter(new ItemAdapter(subCategoriesList));
            ExpandableGridView gridview = helper.getView(R.id.gridview);

            ImageListAdapter ImageListAdapter = new ImageListAdapter(getActivity(), subCategoriesList);

            // 设置GridView的adapter。GridView继承于AbsListView。
            gridview.setAdapter(ImageListAdapter);
            gridview.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> adapterView, View view, int position, long rowid) {
                    LogUtils.e(subCategoriesList.get(position).getCateMobileName());
                    Bundle bundle = new Bundle();
                    bundle.putSerializable("subCategoriesList", (Serializable) subCategoriesList);
                    Intent intent = new Intent(getActivity(), ListOfGoodsActivity.class);
                    intent.putExtras(bundle);
                    intent.putExtra("flag", position);
                    startActivity(intent);
                }
            });

        }
    }

public class ImageListAdapter extends ArrayAdapter {
    private Context context;
    private LayoutInflater inflater;

    private List<ClassificationBean.DataBean.ListDataBean> imageUrls;
    private ImageView iv;
    private TextView itemText;

    public ImageListAdapter(Context context, List<ClassificationBean.DataBean.ListDataBean> imageUrls) {
        super(context, R.layout.grid_view_item, imageUrls);

        this.context = context;
        this.imageUrls = imageUrls;

        inflater = LayoutInflater.from(context);
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        if (null == convertView) {
            convertView = inflater.inflate(R.layout.grid_view_item, parent, false);
            iv = convertView.findViewById(R.id.itemImage);
            itemText = convertView.findViewById(R.id.itemText);
            itemText.setMaxEms(7);
            itemText.setSingleLine(true);
            itemText.setEllipsize(TextUtils.TruncateAt.END);
        }
//        ImageLoader.loadRoundImage(context, NetConfig.BASE_IMG_URL + imageUrls.get(position).getCateImg(), iv, 0, 0);
        itemText.setText(imageUrls.get(position).getCateMobileName());
        return convertView;
    }
}

**Comment by AllenCoder** [comment]
你应该排查一下卡顿原因:
1.是否在convert里面有耗时操作，
2.是否是外层包裹了scrollView
