### ISSUE TITLE
可折叠适配器ExpandableItemAdapter的状态问题

### ISSUE THREAD

**Issue by TkkSoCool** [CymChad/BaseRecyclerViewAdapterHelper#2417]
父级AbstractExpandableItem对象设置setExpanded(true)为展开状态，实际上子项并不会展开，而父级的状态却为展开，回引起状态混乱 ，如父级item箭头状态错乱

**Comment by chenxiaoci** [comment]
有这个错误

**Comment by CymChad** [comment]
收到

**Comment by shichaohui** [comment]
`AbstractExpandableItem#setExpanded(true)` 仅仅是修改对象中的属性，并不会刷新视图，展开和收起需要使用 `Adapter#collapse()` 和 `Adapter#expand()` `Adapter#expandAll()`。
