### ISSUE TITLE
Row item position has change on scroll

### ISSUE THREAD

**Issue by iman2420** [CymChad/BaseRecyclerViewAdapterHelper#2418]
I use this code as Adapter for questions list :
The problem is that when I scroll the list, all the rows are shaped and the list is unordered. Please check where the code was wrong?

      `public class QuestionsListAdapter extends BaseMultiItemQuickAdapter<MultiItemEntity, BaseViewHolder> {
    private final Context mContext;
    private final boolean mAdminMode;
    protected String TAG = QuestionsListAdapter.class.getSimpleName();

    private static final int ACCEPTED = 1;
    private static final int REJECTED = 2;
    public static final int PENDING = 0;

    public static final int TYPE_HEADER = 5;
    public static final int TYPE_QUESTION = 6;

    public QuestionsListAdapter(Context context, List<MultiItemEntity> data, boolean adminMode) {
        super(data);
        addItemType(TYPE_HEADER, R.layout.item_question_list_header);
        addItemType(TYPE_QUESTION, R.layout.item_question_list);
        this.mContext = context;
        this.mAdminMode = adminMode;
    }

    @Override
    protected void convert(final  BaseViewHolder holder,final  MultiItemEntity item) {
        switch (holder.getItemViewType()) {
            case TYPE_HEADER: {
                final QuestionsHeader questionsHeader = (QuestionsHeader) item;
                holder.setText(R.id.header_title, questionsHeader.title).setText(R.id.header_subtitle, questionsHeader.subTitle);
                switch (questionsHeader.getStatus()) {
                    case ACCEPTED: {
                        holder.setBackgroundColor(R.id.header_root, mContext.getResources().getColor(R.color.green_500));
                        break;
                    }
                    case PENDING: {
                        holder.setBackgroundColor(R.id.header_root, mContext.getResources().getColor(R.color.yellow_500));
                        break;
                    }
                    case REJECTED: {
                        holder.setBackgroundColor(R.id.header_root, mContext.getResources().getColor(R.color.red_500));
                        break;
                    }
                }

                holder.getView(R.id.expand_button).setOnClickListener(v -> {
                    int pos = holder.getAdapterPosition();
                    if (questionsHeader.isExpanded()) {
                        collapse(pos, true, true);
                    } else {
                        expand(pos, true, true);
                    }
                });
                break;
            }
            case TYPE_QUESTION: {
                final Question question = (Question) item;
                holder.setText(R.id.txt_question, question.getQuestionText());
                holder.setText(R.id.txt_choice_1, question.getChoice1());
                holder.setText(R.id.txt_choice_2, question.getChoice2());
                holder.setText(R.id.txt_choice_3, question.getChoice3());
                holder.setText(R.id.txt_choice_4, question.getChoice4());
                holder.getView(R.id.lyt_action).setVisibility(View.GONE);
                holder.getView(R.id.txt_accept).setVisibility(mAdminMode ? View.VISIBLE : View.GONE);

                EditText txtQuestion = holder.getView(R.id.txt_question);
                EditText txtChoice1 = holder.getView(R.id.txt_choice_1);
                txtChoice1.setCompoundDrawablesWithIntrinsicBounds(0, 0, 0, 0);
                EditText txtChoice2 = holder.getView(R.id.txt_choice_2);
                txtChoice2.setCompoundDrawablesWithIntrinsicBounds(0, 0, 0, 0);
                EditText txtChoice3 = holder.getView(R.id.txt_choice_3);
                txtChoice3.setCompoundDrawablesWithIntrinsicBounds(0, 0, 0, 0);
                EditText txtChoice4 = holder.getView(R.id.txt_choice_4);
                txtChoice4.setCompoundDrawablesWithIntrinsicBounds(0, 0, 0, 0);
                addTextChangedListener(txtQuestion, question);
                addTextChangedListener(txtChoice1, question);
                addTextChangedListener(txtChoice2, question);
                addTextChangedListener(txtChoice3, question);
                addTextChangedListener(txtChoice4, question);

                switch (question.getCorrectAnswer()) {
                    case CHOICE_1: {
                        txtChoice1.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_check, 0, 0, 0);
                        break;
                    }
                    case CHOICE_2: {
                        txtChoice2.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_check, 0, 0, 0);
                        break;
                    }
                    case CHOICE_3: {
                        txtChoice3.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_check, 0, 0, 0);
                        break;
                    }
                    case CHOICE_4: {
                        txtChoice4.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_check, 0, 0, 0);
                        break;
                    }
                }
                switch (question.getStatus()) {
                    case ACCEPTED: {
                        holder.setBackgroundColor(R.id.root_lyt, mContext.getResources().getColor(R.color.green_200));
                        break;
                    }
                    case REJECTED: {
                        holder.setBackgroundColor(R.id.root_lyt, mContext.getResources().getColor(R.color.yellow_200));
                        holder.getView(R.id.txt_edit).setBackgroundColor(mContext.getResources().getColor(R.color.blue_300));
                        holder.getView(R.id.lyt_action).setVisibility(View.VISIBLE);
                        holder.setText(R.id.txt_edit, mContext.getString(R.string.edit));
                        break;
                    }
                    case PENDING: {
                        holder.setBackgroundColor(R.id.root_lyt, mContext.getResources().getColor(R.color.red_200));
                        holder.getView(R.id.txt_edit).setBackgroundColor(mContext.getResources().getColor(R.color.blue_300));
                        holder.getView(R.id.lyt_action).setVisibility(View.VISIBLE);
                        holder.setText(R.id.txt_edit, mContext.getString(R.string.edit));
                        break;
                    }
                }

                holder.getView(R.id.txt_delete).setOnClickListener(view -> {
                    if (mAdminMode) {
                        showRejectQuestionDialog( holder.getAdapterPosition(), question);
                    } else {
                        showDeleteQuestionDialog(question.getQuestion_unique_id(),  holder.getAdapterPosition(), question);
                    }
                });
                holder.getView(R.id.txt_accept).setOnClickListener(view -> showAcceptQuestionDialog( holder.getAdapterPosition(), question));
                holder.getView(R.id.txt_accept).setOnLongClickListener(view -> { searchGoogle(txtQuestion.getText().toString());return true; });
                //noinspection deprecation
                holder.getView(R.id.txt_edit).setOnClickListener(view -> enableEditText(holder.getConvertView(), holder.getAdapterPosition(), question));
                break;
            }
        }
    } 
     ....`

**Comment by AllenCoder** [comment]
you can refer to this [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Expandable-Item](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Expandable-Item)

**Comment by iman2420** [comment]
@AllenCoder As you can see in the code, I worked as a sample, but the problem is still not resolved. 
When I scroll the list, the order of the rows falls.
