### ISSUE TITLE
emptyview干扰拖动

### ISSUE THREAD

**Issue by kennir** [CymChad/BaseRecyclerViewAdapterHelper#2422]
如果item上有可以拖动的组件，例如视频的进度条，EmptyView会干扰第一个item上的组件的拖动时间

测试下来和emptyview无关，就是第一个item上的拖动会经常变成拖动viewpager或者滑动rv

**Comment by AllenCoder** [comment]
拖动手势冲突需要自己处理一下

**Comment by kennir** [comment]
但是很奇怪，第二个item就不受干扰，我需要怎么处理？
