### ISSUE TITLE
上滑加载更多无限循环

### ISSUE THREAD

**Issue by wanxiangxin** [CymChad/BaseRecyclerViewAdapterHelper#2424]
我的页面最外层是ScrollView，然后一个垂直的线性布局，顶部的View已经超过一屏，然后接着是RecycleView，也就是刚开始RecycleView是在一屏之外的，然后上滑加载更多无限调用

**Comment by AllenCoder** [comment]
相同问题 解决方案 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1704](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1704)
