### ISSUE TITLE
 错误：java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling android.support.v7.widget.RecyclerView

### ISSUE THREAD

**Issue by 1226362423** [CymChad/BaseRecyclerViewAdapterHelper#2427]
在Adapter convert 方法当中做出 notifyDataSetChanged()操作 就出现如下错误 ：请教大神怎么解决

java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling android.support.v7.widget.RecyclerView{cbdcf76 VFED..... ......ID 0,91-660,727 #7f0801b4 app:id/rlv_order_time}, adapter.************:@2a6c4a9, layout:android.support.v7.widget.LinearLayoutManager

**Comment by 1226362423** [comment]
最新版本

**Comment by 1226362423** [comment]
下面是Adapter代码
```
public class OrderTimeRlvAdapter extends BaseQuickAdapter<OrderExpandRlvModel,BaseViewHolder> {

    private List<OrderExpandRlvModel> modelList;

    private int position;

    public OrderTimeRlvAdapter(int layoutResId, @Nullable List<OrderExpandRlvModel> data) {
        super(layoutResId, data);
        modelList=data;
    }

    @Override
    protected void convert(BaseViewHolder helper, OrderExpandRlvModel item) {

        position=helper.getAdapterPosition();

        RadioButton radioBtnTime=helper.getView(R.id.radio_item_order_time);
        radioBtnTime.setText(item.getName());

        TextView tvPersonNumber=helper.getView(R.id.tv_person_number);

        if(item.isChecked()){
           tvPersonNumber.setTextColor(Utils.getColor(R.color.class_tab_def));
           radioBtnTime.setChecked(true);
        }else{
           tvPersonNumber.setTextColor(Utils.getColor(R.color.black));
           radioBtnTime.setChecked(false);
        }

        radioBtnTime.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                modelList.get(position).setChecked(true);
                if(modelList.get(position).isChecked()){
                     for(int i=0;i<modelList.size();i++){
                            if(i!=position){
                                 modelList.get(i).setChecked(false);
                            }
                     }
                }
                notifyDataSetChanged();
            }
        });
    }
}

```

**Comment by 1226362423** [comment]
这样子写也是报错
`  protected void convert(BaseViewHolder helper, OrderExpandRlvModel item) {


        position = helper.getLayoutPosition();//获取当前item的position

        RadioButton radioBtnTime = helper.getView(R.id.radio_item_order_time);
        radioBtnTime.setText(item.getName());

        TextView tvPersonNumber = helper.getView(R.id.tv_person_number);

        if (item.isChecked()) {
            tvPersonNumber.setTextColor(Utils.getColor(R.color.class_tab_def));
//          radioBtnTime.setChecked(true);
            helper.setChecked(R.id.radio_item_order_time,true);
        } else {
            tvPersonNumber.setTextColor(Utils.getColor(R.color.black));
//          radioBtnTime.setChecked(false);
            helper.setChecked(R.id.radio_item_order_time,false);
        }


        helper.setOnCheckedChangeListener(R.id.radio_item_order_time, new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                modelList.get(position).setChecked(true);
                if (modelList.get(position).isChecked()) {
                    for (int i = 0; i < modelList.size(); i++) {
                        if (i != position) {
                            modelList.get(i).setChecked(false);
                        }
                    }
                }
                setNewData(modelList);
            }
        });`

**Comment by lxd85194181** [comment]
和你一样的逻辑 解决了吗
