### ISSUE TITLE
我现在有三级目录，我想一进来只展开一级和二级目录，三级目录点击才会展示这个怎么做？

### ISSUE THREAD

**Issue by lu79931748** [CymChad/BaseRecyclerViewAdapterHelper#2432]
`int pos = holder.getAdapterPosition();expand(pos);`我这样报错了，然后我 `adapter.expand(0)`只会展开第一个一级目录。这个应该怎么做啊？

**Comment by gucuncun** [comment]
你现在这个实现了没有，我也有这个需求

**Comment by lu79931748** [comment]
> 你现在这个实现了没有，我也有这个需求

我最后没用这个。。。最后还是用rv嵌套rv使用的
