### ISSUE TITLE
同向RecyclerView滑动冲突，内部RecyclerView无法滑动

### ISSUE THREAD

**Issue by playscforever** [CymChad/BaseRecyclerViewAdapterHelper#2437]
垂直的RecyclerView中添加一个header，header里面有一个垂直但是高度固定的RecyclerViewInner,目前的情况是RecyclerViewInner无法滑动，每次滑动都是滑动的外层RecyclerView。

**Comment by playscforever** [comment]
@AllenCoder hi~ 麻烦帮忙看看，

**Comment by playscforever** [comment]
额。目前好像只能处理外层的onInterceptTouchEvent，谁有更好的方案？

**Comment by Danniel-yan** [comment]
+1

**Comment by AllenCoder** [comment]
你可以参考NestScrollView对嵌套触摸事件的处理，外层不拦截，分发到内层recyclerview，消费完再返回给外层
