### ISSUE TITLE
使用BaseMultiItemQuickAdapter实现多布局，局部更新时在onBindViewHolder()中获取view 报空指针

### ISSUE THREAD

**Issue by liuyaoting** [CymChad/BaseRecyclerViewAdapterHelper#2438]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference

**Comment by liuyaoting** [comment]
onBindViewHolder 代码
 if (payloads.isEmpty()) {
            onBindViewHolder(holder, position);
        } else {
            DiscoverHotspot discoverHotspot = getItem(position);
            if (discoverHotspot == null) {
                return;
            }
            int itemType = getDefItemViewType(position);
            if (DiscoverHotspot.UPLOAD == itemType) {
                LogUtils.e("onBindViewHolder " + mData.get(position).getProgress());
                ProgressBar progressBar = holder.getView(R.id.pb_upload_mask);
                progressBar.setVisibility(View.VISIBLE);
                setAnimationProgress(progressBar, discoverHotspot.getProgress());
            }
        }

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2355
