### ISSUE TITLE
可以默认（第一次进入RecyclerView）时多加载几个item吗？

### ISSUE THREAD

**Issue by JiangShuLiang** [CymChad/BaseRecyclerViewAdapterHelper#2439]
作者你好，很喜欢你这个adapterHelper，真心好用得不要不要的！
我有个需求就是默认（第一次进入RV）想多加载几个item，我这儿一个item里就一张长图，看了日志默认是加载两个，滑动到第二个可见的时候才加载第三个。我希望第一次进入RecyclerView的时候能多加载几个。不知道要如何实现，希望作者能解疑一下，提前感谢了！！！！

这是需求背景（如果你有空的话希望可以看下）：
最近手头有个漫画阅读的项目，我用了你这个adapter去做。每个item里就一张长图，但由于图片比较长，所以加载比较慢，但业主又要求不能让用户看到空白的（其实是还没加载完成的）item。所以我就想默认（第一次进入RV）时多加载几个item，然后setPreloadNumber设置多一些，来实现尽量多的预加载，尽量让用户在滑动阅读的时候看不到还没加载完成的item。

**Comment by CymChad** [comment]
你可以提到 #2806 ，采纳后会被排期开发

**Comment by limuyang2** [comment]
可以尝试使用 `Glide` 提供的RecyclerView的预加载功能。
官方文档：https://muyangmin.github.io/glide-docs-cn/int/recyclerview.html
