### ISSUE TITLE
何时增加对androidx的支持

### ISSUE THREAD

**Issue by candyguy242** [CymChad/BaseRecyclerViewAdapterHelper#2441]
Google要把支持库的包名换掉，导致采用新支持库的项目不能正常编译，请及早做出支持，谢谢~

**Comment by ebnbin** [comment]
@CymChad 
https://github.com/grandcentrix/ThirtyInch/issues/148
看看这个能不能解决，目前 recyclerview-v7 用的是 compileOnly 导致迁移 androidX 后包找不到，用 api 应该能解决问题的
