### ISSUE TITLE
跪求刷新闪屏问题指教

### ISSUE THREAD

**Issue by OblivioU** [CymChad/BaseRecyclerViewAdapterHelper#2443]
纵向RecyckerView多布局adapter，有banner，跑马灯，横向RecylerView，纵向RecyclerView
试了notify刷新的所有api，刷新还是会闪屏
代码中加了以下代码了，刷新还是会闪屏((DefaultItemAnimator)mRecyclerView.getItemAnimator()).setSupportsChangeAnimations(false);

if(!ObjectUtils.isEmpty(item.getIconFile())){
            if(!item.getIconFile().getUrl().equals(imgIcon.getTag(R.id.item_apk_icon))){
                GlideUtils.loadApkIcon(mContext, item.getIconFile().getUrl(), imgIcon);
                imgIcon.setTag(R.id.item_apk_icon, item.getIconFile().getUrl());
            }
        }

**Comment by CymChad** [comment]
收到

**Comment by limuyang2** [comment]
请尝试`recyclerView.setItemAnimator(null)`

**Comment by MicroSummer** [comment]
Glide的Option用了吗，如果用了话最好不要在convert里创建，否则造成图片闪烁
