### ISSUE TITLE
使用树形列表时 点击item会出现闪烁的现象

### ISSUE THREAD

**Issue by Power-Android** [CymChad/BaseRecyclerViewAdapterHelper#2444]
使用树形列表时 点击item会出现闪烁的现象，文章中的gif也是存在的，尤其在暗背景下闪烁更明显，有办法解决么？

**Comment by AllenCoder** [comment]
刷新数据源时，不要更改数据源地址，而是要在原来的数据源做diff变动

**Comment by Bruce8hou** [comment]
能不能具体说一下怎么操作呢

**Comment by hyb1234hi** [comment]
我这里也出现点击item会出现闪烁的现象，没有更改数据源地址
