### ISSUE TITLE
点击水波纹效果，怎么去掉

### ISSUE THREAD

**Issue by shoushuai** [CymChad/BaseRecyclerViewAdapterHelper#2445]
item没加selectableItemBackground

**Comment by HarkBen** [comment]
item随便给个背景


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by shoushuai** [comment]
@HarkBen 我不用这个库，就没有。item看需要添加forebackground。用这个库，背景就有了
