### ISSUE TITLE
局部更新问题

### ISSUE THREAD

**Issue by onlycyndi** [CymChad/BaseRecyclerViewAdapterHelper#2446]
需求需要一个二级折叠的样式，二级子项根据外部按钮状态可以切换①树形列表，②一个饼状图。功能实现了，现在遇到问题是①条目过多超出可显示高度后，切换到②状态会出现②布局从下往上跳动，我想的是①的高度在切换到②的时候没有换算过来。我把折叠关闭再打开的时候②布局又正常了，目前没有找到如何解决这个高度的问题，请问下大佬有没有什么解决思路。

**Comment by AllenCoder** [comment]
布局较复杂而且高度变化较大时，可能会出现较大可能性的跳动，建议增加动画或者交换，去缓解高度跳动的影响

**Comment by onlycyndi** [comment]
我后来的解决方案是加一个与一级项平级的底部，在切换的时候，隐藏掉二级项，展开一级底部项就没有这个问题了。

**Comment by onlycyndi** [comment]
我后来的解决方案是加一个与一级项平级的底部装入②饼状图，在切换的时候，隐藏掉二级项的①树形列表，展开一级底部项的②饼状图就没有这个问题了。
