### ISSUE TITLE
BaseQuick Adapter not updating 

### ISSUE THREAD

**Issue by AravinthSri** [CymChad/BaseRecyclerViewAdapterHelper#2447]
[ (BaseQuickAdapter) adapter.setNewData(list) ] adapter not updating properly when using setNewData.. when keyboard is appear then only adapter changes reflect or not reflect kindly help me to fix this issue.

**Comment by AllenCoder** [comment]
you can refer this [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)
