### ISSUE TITLE
使用FlexboxLayoutManager ,无法设置EmptyView

### ISSUE THREAD

**Issue by caosiqiao4000** [CymChad/BaseRecyclerViewAdapterHelper#2449]
经过测试 使用FlexboxLayoutManager运行到
setEmptyView()

报出如下错误
RecyclerView$LayoutParams cannot be cast to com.google.android.flexbox.FlexItem

**Comment by AllenCoder** [comment]
提示是类型转换异常。

**Comment by feaoes** [comment]
利用反射将BaseQuickAdapter中的mFrameLayout 设置成特定LayoutParams可以解决
`
        FrameLayout frameLayout = new FrameLayout(getContext());
        frameLayout.setLayoutParams(new FlexboxLayoutManager.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        ReflectUtils.reflect(mainClassListAdapter).field("mEmptyLayout",frameLayout);//反射注入参数为FlexboxLayoutManager.LayoutParams的FrameLayout
        mainClassListAdapter.setEmptyView(R.layout.layout_empty_list);
`

**Comment by caosiqiao4000** [comment]
好是

**Comment by caosiqiao4000** [comment]
好是
