### ISSUE TITLE
BaseSectionMultiItemQuickAdapter这个适配器问题

### ISSUE THREAD

**Issue by wcglws** [CymChad/BaseRecyclerViewAdapterHelper#2453]
最新版本的库。。。RecyclerView嵌套使用BaseSectionMultiItemQuickAdapter这个适配器，可以么？试了下，header显示出来了，也就是这个回调了 protected void convertHead(BaseViewHolder helper, TabItem item) {}，但是protected void convert(BaseViewHolder helper, TabItem item) {}这个回调方法没走。。

**Comment by AllenCoder** [comment]
使用方法参考demo教程 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/SectionMultipleItemAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/SectionMultipleItemAdapter.java)
