### ISSUE TITLE
这个库支持databinding吗?

### ISSUE THREAD

**Issue by MinghaoCao** [CymChad/BaseRecyclerViewAdapterHelper#2454]
怎么用啊

**Comment by AllenCoder** [comment]
支持 ，请看Demo 的[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DataBindingUseAdapter.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DataBindingUseAdapter.java)
