### ISSUE TITLE
重复请求

### ISSUE THREAD

**Issue by yishangfei** [CymChad/BaseRecyclerViewAdapterHelper#2455]
2秒请求一次网络接口
![image](https://user-images.githubusercontent.com/15099278/45202253-f9353b80-b2aa-11e8-8bb9-926176abe1d9.png)
成功后设置适配器   
http://images.yishangfei.xyz/Screenrecorder-2018-09-06-17-10-00-549.mp4
滑动到底部 等待刷新重新adapter时导致adapter回到顶部

尝试过setNewData可是只能传一个实体类    这个adapter使用了两个实体类  
想问碰到这种情况该如何处理

**Comment by liufangmeng** [comment]
干嘛要重新设置adapter啊。直接setNewData就行。

**Comment by yishangfei** [comment]
@liufangmeng 
![image](https://user-images.githubusercontent.com/15099278/45205773-c17fc100-b2b5-11e8-9115-a08bd6cc0634.png)  
![image](https://user-images.githubusercontent.com/15099278/45205798-d78d8180-b2b5-11e8-9ed6-2c67666e27d3.png)
setNewData只能穿一个啊

**Comment by liufangmeng** [comment]
自定义adapter 当个临时list
