### ISSUE TITLE
convert方法调用时机有异常

### ISSUE THREAD

**Issue by JiangShuLiang** [CymChad/BaseRecyclerViewAdapterHelper#2456]
是这样的：
适配器里用picasso加载图片，然后：

如果有设置placeholder，则rv是逐个加载的，就是等到某个item可见了，才加载这个item的内容，此时convert方法就逐次调用的。

而如果没设置placeholder，则rv会一下子把所有item都加载好。此时convert方法就一下子调用了十几次

**Comment by AllenCoder** [comment]
convert的调用时机是recyclerview布局展开的时机，跟adapter无关，有可能是placeholder未设置，会让recyclerview全展开
