### ISSUE TITLE
项目遇到一个稍微奇怪的问题（数据部分丢失），不知作者有无相关的思路或经验

### ISSUE THREAD

**Issue by henu3540** [CymChad/BaseRecyclerViewAdapterHelper#2457]
在从本地数据库中取出数据列表时，使用brvah加载数据会出现部分数据丢失。比方说，传入的list中有六条数据，而adapter中的getData()却只得到三条数据。我用原生的adapter测试时六条数据是全部加载出来的。

**Comment by AllenCoder** [comment]
数据丢失，是否跟你数据源引用地址不一致有关，或者数据源被其他地方修改过

**Comment by easyandroid** [comment]
> 在从本地数据库中取出数据列表时，使用brvah加载数据会出现部分数据丢失。比方说，传入的list中有六条数据，而adapter中的getData()却只得到三条数据。我用原生的adapter测试时六条数据是全部加载出来的。

我也出现了 请问怎么修改了？
