### ISSUE TITLE
BaseRecyclerViewAdapterHelper嵌套adapter 会不会很影响性能？

### ISSUE THREAD

**Issue by MinchinWang** [CymChad/BaseRecyclerViewAdapterHelper#2459]
BaseRecyclerViewAdapterHelper嵌套adapter 会不会很影响性能？

**Comment by MagnifierSun** [comment]
嵌套的adapter没法复用视图啊

**Comment by AllenCoder** [comment]
嵌套优化参考这篇文章
[https://proandroiddev.com/optimizing-nested-recyclerview-a9b7830a4ba7](https://proandroiddev.com/optimizing-nested-recyclerview-a9b7830a4ba7)
