### ISSUE TITLE
似乎不支持DataBinding

### ISSUE THREAD

**Issue by EthanCo** [CymChad/BaseRecyclerViewAdapterHelper#246]
似乎不支持DataBinding，DataBinding是大势所趋，希望可以对DataBinding进行适配优化。

**Comment by CymChad** [comment]
恩，后续会支持，好了通知你。

**Comment by EthanCo** [comment]
好的，期待 !

**Comment by hzqjyyx** [comment]
同样希望有DataBinding的支持

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.0' 已经对baseviewholder支持扩展了，并且demo新增了databinding使用的案例

**Comment by EthanCo** [comment]
首先，表示惊喜，终于可以用DataBinding了 ! 
但是，我在使用过程中似乎遇到一个问题，我将PullToRefreshUseActivity 改为用DataBinding方式实现，在加载更多时会报错。 具体定位，发现是在  

DataBindingAdapter#getItemView()      

> @Override
>     protected View getItemView(int layoutResId, ViewGroup parent) {
>            ViewDataBinding binding = DataBindingUtil.inflate(mLayoutInflater, layoutResId, parent, false);
>            View view = binding.getRoot();
>            view.setTag(R.id.BaseQuickAdapter_databinding_support, binding);
>            return view;
>     }  

打印日志发现，layoutResId 正常时候的ID和报错时候的ID不一致，应该是Item类型不同所造成的，可能需要进行类型的判断

上传的文件是修改后的PullToRefreshUseActivity

**Comment by elfman** [comment]
你弄错了一个地方，`DataBindingAdapter`并不是库里的类，是我展示的demo里演示用的

**Comment by elfman** [comment]
错误的原因是BaseSectionQuickAdapter里调用了getItemView传来mSectionHeadResId，而mSectionHeadResId的layout并没有使用databinding，所以inflate返回了null。
但DataBindingAdapter并不是库里的方法，只是在demo里演示用的，不需要考虑用在BaseSectionQuickAdapter的情况。可能名字让你混淆了吧，DataBinding继承BaseQuickAdapter就行了

**Comment by EthanCo** [comment]
我应该没用过BaseSectionQuickAdapter，在PullToRefreshUseActivity里，我只将  

`mQuickAdapter = new QuickAdapter(PAGE_SIZE);`  

改为了  

`mQuickAdapter = new DataBindingAdapter(R.layout.item_movie, genData(0));  `

将 

 `DataServer.getSampleData(PAGE_SIZE)`

改为了

```
public static List<Movie> genData(int index) {
        int start = index * PAGE_SIZE;
        int end = (index + 1) * PAGE_SIZE;
        ArrayList<Movie> list = new ArrayList<>();
        Random random = new Random();
        for (int i = start; i < end; i++) {
            String name = "Movie " + i;
            int price = random.nextInt(10) + 10;
            int len = random.nextInt(80) + 60;
            Movie movie = new Movie(name, len, price);
            list.add(movie);
        }
        return list;
    }
```

我查看代码中的引用，BaseSectionQuickAdapter 只被 SectionAdapter 继承，而SectionAdapter 只在SectionUseActivity中被使用。  应该是没有用过SectionUseActivity的。  

具体定位错误，是在
BaseQuickAdapter#onCreateViewHolder()  

```
@Override
    public K onCreateViewHolder(ViewGroup parent, int viewType) {
        K baseViewHolder = null;
        this.mContext = parent.getContext();
        this.mLayoutInflater = LayoutInflater.from(mContext);
        switch (viewType) {
            case LOADING_VIEW:
                baseViewHolder = getLoadingView(parent);
                break;
            case HEADER_VIEW:
                baseViewHolder = createBaseViewHolder(mHeaderLayout);
                break;
            case EMPTY_VIEW:
                baseViewHolder = createBaseViewHolder(mEmptyView == mCopyEmptyLayout ? mCopyEmptyLayout : mEmptyView);
                break;
            case FOOTER_VIEW:
                baseViewHolder = createBaseViewHolder(mFooterLayout);
                break;
            default:
                baseViewHolder = onCreateDefViewHolder(parent, viewType);
        }
        return baseViewHolder;
    }
```

其中，在使用DataBinding正常情况下是加载 `baseViewHolder = onCreateDefViewHolder(parent, viewType);`，而在出现错误时，加载的是`baseViewHolder = getLoadingView(parent);`，是这个`getLoadingView()`没有使用DataBinding所造成的。

故将def_loading.xml添加一层`<layout></layout>`，错误解决。  

同时考虑到不使用DataBinding的童鞋的使用，故复制def_loading.xml到demo里，再代码中自定义设置  

`mQuickAdapter.setLoadingView(getLayoutInflater().inflate(R.layout.databinding_loading, (ViewGroup) mRecyclerView.getParent(), false));`

相关代码已pull request

**Comment by elfman** [comment]
我昨晚看错Log了，是`createBaseViewHolder`里调用了`getItemView`，导致的出错，但这并不是关键。
你还是理解错我的意思了，实际这个错误只需要在DataBindingAdapter里的`getItemView()`加一句`if (binding == null) {  return super.getItemView(layoutResId, parent);  }`就能解决了。
我不想修复是因为DataBindingAdapter只是在Demo里使用，也仅仅是用于`DataBindingUseActivity`，你将它用在`PullToRefreshUseActivity`是错误的行为。

**Comment by EthanCo** [comment]
前面的确实是一种好的方法。但是在使用DataBinding的情况下，也可能需要使用加载更多和上拉加载不是吗，我觉得Demo中需要有关于DataBinding的加载更多和上拉加载使用示例会好些

**Comment by elfman** [comment]
加载更多和上拉加载是更新adapter的方式，对DataBinding来说并没有什么区别，DataBinding只负责创建View，这View之后怎么用的跟它无关。
Demo应该是突出重点，即如何写DataBinding，所以我觉得不需要再专门写针对加载更多和上拉加载的Demo，因为是一样的。
但我还是改一下那个Adapter的名字吧，那句判断null也加上去好了，免得其它人也理解错误了。

**Comment by EthanCo** [comment]
恩，好的。

**Comment by elfman** [comment]
多谢你的建议。
我想你那个pull request应该可以取消了吧？

**Comment by EthanCo** [comment]
恩，取消了 ~

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.3' 
Change the name of  DataBindingAdapter in demo in case of confusion

**Comment by EthanCo** [comment]
好的
