### ISSUE TITLE
求安慰

### ISSUE THREAD

**Issue by HayDar-Android** [CymChad/BaseRecyclerViewAdapterHelper#2462]
```
   
    public BaseViewHolder setGone(@IdRes int viewId, boolean visible) {
        View view = getView(viewId);
        view.setVisibility(visible ? View.VISIBLE : View.GONE);
        return this;
    }
```
这个代码是不是有点反人类，setGone()，还得false才有效，大神你是不是忘了写感叹号了。因为这个bug,导致我们损失了1000万用户，现在我和测试正在海投简历

**Comment by msdx** [comment]
blame了一下，修改来自于此：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/commit/aa4a3d01baf5d946d6b5c5c7a05e95a2efcb7963

**Comment by daiwenbo88** [comment]
早知道 就不该更新  setGone(false)和setGone(true) 真的很费解

**Comment by leaderliang** [comment]
看了下，确实不舒服~
