### ISSUE TITLE
调用 loadmoreEnd 后怎么再次开启上拉加载更多的功能

### ISSUE THREAD

**Issue by Likeyong** [CymChad/BaseRecyclerViewAdapterHelper#2465]
我遇到的问题是，目前使用了本库的上拉加载更多，用了另外一个库的下拉刷新。
1. 上拉加载数所有数据加载完毕的时候调用了loadmoreEnd。
2. 调用了下拉刷新这时候从网络上从新获取了数据，然后需要继续使用上拉加载更多。
但是这时候 不管怎么拉 都是显示加载完毕了。
我没有找到修改这个状态的接口。
麻烦大神能指点一下，谢谢了

**Comment by AllenCoder** [comment]
详细用法参考Demo [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)
