### ISSUE TITLE
请问什么时候支持AndroidX

### ISSUE THREAD

**Issue by Anzhi-Meiying** [CymChad/BaseRecyclerViewAdapterHelper#2467]
疯狂报错好无奈...

**Comment by AllenCoder** [comment]
考虑升级方案中，先别急着上AndroidX啊

**Comment by Anzhi-Meiying** [comment]
因为有好几个库都是Androidx，然后现在全部都升级成Androidx了...

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/tree/androidx](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/tree/androidx) 
目前代码不稳定，只作为暂时androidX分支提交，后续可能会有大规模变动。目前可以给你提供alpha版的依赖库依赖

**Comment by AllenCoder** [comment]
```
dependencies {
	        implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.43-alpha1'
	}
```

**Comment by Anzhi-Meiying** [comment]
非常感谢
