### ISSUE TITLE
NestedScrollView嵌套RecyclerView加载更多BUG

### ISSUE THREAD

**Issue by logney** [CymChad/BaseRecyclerViewAdapterHelper#2468]
当Adapter.setEnableLoadMore(true)时就会触发加载更多

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1777](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1777)
