### ISSUE TITLE
上啦加载更多bug

### ISSUE THREAD

**Issue by aii1991** [CymChad/BaseRecyclerViewAdapterHelper#247]
1.当数据量不足已填满一页时,进行下来刷新会触发加载更多回调.
2.recyclerview滑动到底部后就自动触发了加载更多回调,是否能像pulltorefresh一样滑动到底部后再往上拉拉一定距离再触发加载更多回调.

**Comment by CymChad** [comment]
1.你的版本是？
2.不能，因为监听原理就是到最后一个item触发的。

**Comment by CymChad** [comment]
你的pageSzie是？

**Comment by CymChad** [comment]
pageSize 是一页的数量 。

**Comment by aii1991** [comment]
@CymChad pageSize设置的是10

**Comment by aii1991** [comment]
@CymChad 不好意思呀 是第一页数据不足填满一屏时  那里表达错了

**Comment by CymChad** [comment]
那么你的数据满足了10条吗？

**Comment by CymChad** [comment]
只要你的数据超过了你的pageSize那么就会调用加载鞥多的回调

**Comment by CymChad** [comment]
2.0你可以不用设置pageSize

**Comment by aii1991** [comment]
@CymChad 能否让我通过QQ群 我截图给你看下

**Comment by CymChad** [comment]
好了
