### ISSUE TITLE
取消自动加载更多。

### ISSUE THREAD

**Issue by meijius** [CymChad/BaseRecyclerViewAdapterHelper#2470]
set方法 没找到 en也没有。

**Comment by AllenCoder** [comment]
参考demo使用示例 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)

**Comment by Jameshuihui** [comment]
mQuickAdapter.disableLoadMoreIfNotFullPage();调用好像没有作用，只能采用示例这种方式吗？
