### ISSUE TITLE
如何立即更新所有ItemView，包括不可见部分的View

### ISSUE THREAD

**Issue by Dkaishu** [CymChad/BaseRecyclerViewAdapterHelper#2473]
我的需求是这样的：每一个Item项有一个Switch，于是我在dataList项中持有了一个OnCheckedChangeListener，并在adapter中的convert方法中``` Switch.setOnCheckedChangeListener(item.listener) ```,现在我添加一个总Switch，控制列表中的所有Switch，但是发现只有可见部分的ItemView执行了回调，请问有什么解决方法？

**Comment by AllenCoder** [comment]
不可见的itemview还没attachWindow ,不会触发covert方法，如果非得这么处理，可以在外层裹一层scrollView让recyclerView全展开，但是这样在数据量不大的情况下没有问题，数据量太大会造成滑动和布局卡顿，请慎用
