### ISSUE TITLE
RecyclerView外层使用权重布局导致setOnLoadMoreListener 多次执行

### ISSUE THREAD

**Issue by YaDongHouse** [CymChad/BaseRecyclerViewAdapterHelper#2474]
RecyclerView外层使用权重布局导致setOnLoadMoreListener 多次执行 一直到数据全部加载完

**Comment by 1510766316** [comment]
在使用最新的版本里，每次刷新都会调用到setOnLoadMoreListener，这很让人恼火，在刷新时，禁止加载更多都没用

**Comment by 1510766316** [comment]
我这边RecyclerView外层没有使用权重布局

**Comment by YaDongHouse** [comment]
关键是新开一个项目怎么用都是正常的，就是在原来项目中会一直调用，一直到数据全部加载完，应该不是权重问题

**Comment by YaDongHouse** [comment]
找到问题了，RecycleView的父布局不能使用水平方向的权重布局。
例如：使用如下布局，只要设置了加载更多，就一直会调用。
<LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@color/colorAccent"
                    android:gravity="center"
                    android:text="左侧"
                    android:textSize="25sp" />
            </LinearLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="5">

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/dividend_list"
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="5"
                    android:paddingLeft="2dp"
                    android:paddingRight="2dp" />

            </LinearLayout>

        </LinearLayout>
