### ISSUE TITLE
2.9.43-alpha1  运行报错，更换到低版本就又好了，

### ISSUE THREAD

**Issue by Pawnwangluo123** [CymChad/BaseRecyclerViewAdapterHelper#2475]
![image](https://user-images.githubusercontent.com/19551936/45744055-1adddd80-bc30-11e8-83c8-41b6f64a93c3.png)
![image](https://user-images.githubusercontent.com/19551936/45744073-26c99f80-bc30-11e8-8b9c-bf148dcf50fb.png)

**Comment by AllenCoder** [comment]
2.9.43-alpha1 是针对已经升级AndroidX的兼容适配版本，未升级AndroidX的请勿升级使用

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2467#issuecomment-422261485
