### ISSUE TITLE
依次加载动画，会先显示出Item, 然后再动画，不流畅

### ISSUE THREAD

**Issue by wcquan2008** [CymChad/BaseRecyclerViewAdapterHelper#2476]
@Override
    protected void startAnim(Animator anim, int index) {
        if (index < 5)
           anim.setStartDelay(index * 150);
        super.startAnim(anim, index);
    }
依次加载动画，是这样处理的。动画是依次加载了，但是由于ListView中先显示出Item，然后再进行的动画。整体不流畅，可以处理吗

**Comment by AllenCoder** [comment]
可以重新item的anim，根据需求定制自己的动画

**Comment by chenyy0708** [comment]
最近也碰到这个需求，需要首屏也逐个显示动画，我的做法是把item根布局的透明度android:alpha="0"，然后重写Adapter的startAnim
@Override
    protected void startAnim(Animator anim, int index) {
        if (index < 首屏item个数) {
            anim.setStartDelay(index * 50);
        }
        mData.get(index).setAnimation(true);
        super.startAnim(anim, index);
    }


自定义动画SlideLeftAnimation里面增加一个alpha属性动画，例如
public class SlideLeftAnimation implements BaseAnimation {
    @Override
    public Animator[] getAnimators(View view) {
        return new Animator[]{
                ObjectAnimator.ofFloat(view, "translationX", -view.getRootView().getWidth(), 0),
                ObjectAnimator.ofFloat(view, "alpha", 0, 1f)
        };
    }
}


在item bean对象里增加一个字段
    public AdapterBean{
    
   .........

    /**
     * 是否执行过动画
     */
    private boolean isAnimation = false;
}

最后在convert方法中判断显示
protected void convert(BaseViewHolder helper, AdapterBean item) {
        ........
        // 执行过动画直接显示
        if (item.isAnimation()) {
            helper.getView(R.id.ll_content).setAlpha(1f);
        }
}

**Comment by chenyy0708** [comment]
基本可以完美显示

**Comment by wcquan2008** [comment]
嗯，我也变相的处理了这个问题，谢谢
