### ISSUE TITLE
删除掉一个item后列表就显示错位

### ISSUE THREAD

**Issue by ruanbaojun1105** [CymChad/BaseRecyclerViewAdapterHelper#2477]
并不是一定出现，当内存较高时就必现
![1ffa7ba253c0a0b7531fac8dbfc409f5](https://user-images.githubusercontent.com/7459297/45865479-3ec82d00-bdb0-11e8-8dbd-577ae85f42d8.jpg)

**Comment by AllenCoder** [comment]
recyclerview的复用机制很完善，请检查数据源是否同步，操作删除时，是否影响了内部数据源的顺序
