### ISSUE TITLE
recyclerview嵌套，内层setEmptyView不显示

### ISSUE THREAD

**Issue by po1arbear** [CymChad/BaseRecyclerViewAdapterHelper#2479]
class DrawingLotteryAdapter(list: List<LuckyListData.Lucky>) : BaseQuickAdapter<LuckyListData.Lucky, BaseViewHolder>(R.layout.item_list_drawing_lottery, list) {
    override fun convert(helper: BaseViewHolder?, item: LuckyListData.Lucky?) {
        try {
            helper?.setText(R.id.tv_lucky_number, item?.award_info?.number)
                    ?.setText(R.id.tv_luck_time, formatToDay(item?.award_info?.end_time!! * 1000))
                    ?.setText(R.id.tv_block_height, item.award_info.block_height)
                    ?.setText(R.id.tv_block_time, formatToSecond(item.award_info.end_time))
                    ?.setText(R.id.tv_block_hash, insertChangeLine(item.award_info.block_hash))
                    ?.getView<View>(R.id.tv_query_address)?.setOnClickListener {
                        ARouter.getInstance().build(AppRouterUri.INNERBROWSER_ACTIVITY)
                                .withString("url", AppConstant.BLOCK_QUERY_URL)
                                .navigation()
                    }
            val mWinnerAdapter = WinnerAdapter(item?.winners)
            val recyclerView = helper?.getView<RecyclerView>(R.id.recycler_view)
            recyclerView!!.layoutManager = LinearLayoutManager(mContext, LinearLayoutManager.VERTICAL, false)
            recyclerView.adapter = mWinnerAdapter
            mWinnerAdapter.bindToRecyclerView(recyclerView)
            mWinnerAdapter.setEmptyView(R.layout.winner_empty_layout)
        } catch (e: Exception) {
            Logger.d(e)
        }
    }
}

**Comment by AllenCoder** [comment]
内层EmptyView不显示，请检查内层数据源是否正确， 内层recyclerView布局参数是否正确
