### ISSUE TITLE
滑动删除 如何Undo

### ISSUE THREAD

**Issue by blackbbc** [CymChad/BaseRecyclerViewAdapterHelper#248]
您好，这个库很棒！
但是在生产环境中，我有这样一个需求，在滑动删除的时候，弹出一个dialog让用户选择是否确认删除，但是目前的对于这个库来说，一旦滑动了，item也从adapter里删除掉了，有没有这样一个方法使得滑动后item从adapter里不删除，同时返回原样呢

**Comment by elfman** [comment]
你这个需求实际我更推荐你使用另一个库[AndroidSwipeLayout](https://github.com/daimajia/AndroidSwipeLayout)
