### ISSUE TITLE
当列表数据为空时，headivew不显示 

### ISSUE THREAD

**Issue by shuaimango** [CymChad/BaseRecyclerViewAdapterHelper#2483]
当列表数据为空时，headivew不显示

**Comment by shuaimango** [comment]
补充一下，同时设置了空布局。当列表数据为空，优先显示空布局，应该是优先显示headivew，如果headivew没设置，才显示空布局

**Comment by Jayshanx** [comment]
madapter.setHeaderAndEmpty(true);

**Comment by CymChad** [comment]
@Jayshanx 感谢你的回答
