### ISSUE TITLE
快速滑出item出现重复的item

### ISSUE THREAD

**Issue by Mystrawberry** [CymChad/BaseRecyclerViewAdapterHelper#2484]
1. versionCode 5  ，versionName "2.1"

2. 没有改任何代码

3. 快速滑出去任意(我滑的是第一个item)一个item，其他的item往上移动的时候就能看见

4.  `            @Override
            public void onItemSwipeStart(RecyclerView.ViewHolder viewHolder, int pos) {
               //出现这种情况时，pos = -1，并且不会走 clearView（）
                Log.d(TAG, "view swiped start: " + pos);
            }`

![error](https://user-images.githubusercontent.com/10387048/46240271-54a0a800-c3d7-11e8-8528-7ec7ec7fa2c9.gif)

**Comment by liweiGe** [comment]
> 1. versionCode 5  ，versionName "2.1"
> 2. 没有改任何代码
> 3. 快速滑出去任意(我滑的是第一个item)一个item，其他的item往上移动的时候就能看见
> 4. `            @Override public void onItemSwipeStart(RecyclerView.ViewHolder viewHolder, int pos) { //出现这种情况时，pos = -1，并且不会走 clearView（） Log.d(TAG, "view swiped start: " + pos); }`
> 
> ![error](https://user-images.githubusercontent.com/10387048/46240271-54a0a800-c3d7-11e8-8528-7ec7ec7fa2c9.gif)

我也遇到写这个问题了，你解决了吗？求指教

**Comment by Mystrawberry** [comment]
@Override
 public void onItemSwipeStart(RecyclerView.ViewHolder viewHolder, int pos) 
{
            if (pos == -1) 
            {
                adapter.notifyDataSetChanged();
            }
  }

目前是这样改的，你有更好的方法吗？

**Comment by CymChad** [comment]
收到
