### ISSUE TITLE
多布局情况下，二级列表调用adapter.expandAll()只能打开最后一个

### ISSUE THREAD

**Issue by Jameshuihui** [CymChad/BaseRecyclerViewAdapterHelper#2487]
多布局情况下，有各种其他布局，二级列表调用adapter.expandAll()只能打开最后一个，用点击打开时，会先关闭先打开的，然后再点一次才能打开想要打开的列表，望回复

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
二级列表？没太明白你的意思。

**Comment by CymChad** [comment]
如果还有问题，你可以提供复现demo，这样便于我们更快速的定位问题。
