### ISSUE TITLE
添加较复杂的header时，滑动过程中会抖动

### ISSUE THREAD

**Issue by XuQK** [CymChad/BaseRecyclerViewAdapterHelper#2488]
我header是个快2屏高的稍微复杂点的view。然后滑到这个header的时候整个list就会抖一下。。。请问有办法解决吗。不想NestScrollview套RV，这样没法回收复用。
场景1：比如header是一个webview和若干textview
场景2：header是一个banner，一个4column 2row的recyclerview，一个banner，一个视频播放器
PS：听说listView这样弄不会抖，我等会就去试一下。不过能用RV的话还是想尽量RV，感谢解答

**Comment by mzhkby** [comment]
问题解决了吗？遇到了相同的问题

**Comment by CAnonymous8** [comment]
如果你 关联的是AppBarLayou 可以在 RecyclerView 布局中添加锚点解决 ：app:layout_anchor="@id/appBar"
app:layout_anchorGravity="bottom"
