### ISSUE TITLE
recyclerview嵌套recyclerview，子recyclerview的点击事件中如何获取父recyclerview的下标？

### ISSUE THREAD

**Issue by AnJiuZhe** [CymChad/BaseRecyclerViewAdapterHelper#2489]
有没有啥思路这个，不好获取。。

**Comment by AllenCoder** [comment]
通过父层绑定子adapter时将父层item的position传入进去

**Comment by cdcdec** [comment]
子adapter.setFatherPosition(helper.getAdapterPosition());
 子adapter中增加一个方法，将父adapter的position传进入
