### ISSUE TITLE
首页RecyclerView+头布局，adapter用的 brvah，偶尔出现进首页之后没有列表只有头布局的问题

### ISSUE THREAD

**Issue by Payphone7** [CymChad/BaseRecyclerViewAdapterHelper#2490]
偶尔出现没有列表只有头布局的情况，不太确定什么原因，列表和头布局的数据是分别请求的数据，列表adapter用的是brvah，刷新用的是SmartRefreshLayout，两边我都提了issue，希望大佬有时间帮看看，非常感谢

**Comment by AllenCoder** [comment]
头布局是否是adapter的headerView？

**Comment by CymChad** [comment]
长时间无回复，所以将关闭这个问题
