### ISSUE TITLE
添加第一条数据成功后，adapter.getData().size()=0？？？

### ISSUE THREAD

**Issue by liuyaoting** [CymChad/BaseRecyclerViewAdapterHelper#2491]
if (mAdapter.getData().size() > 0) {
            DiscoverHotspot hotspot = mAdapter.getItem(0);
            if (DiscoverHotspot.UPLOAD != hotspot.getStatus()) {
                mAdapter.addData(0, discoverHotspot);
            } else {
                uploadProgress(progress);
            }
        } else {
            mAdapter.addData(0, discoverHotspot);//添加第一条数据
        }

在添加第一条数据成功并记录完成进度，当进度有更新时再次进入这个方法mAdapter.getData().size()显示为0？？

**Comment by liuyaoting** [comment]
adapter.getData()不为空时，使用addData()会将原始数据的第一条数据替换掉

**Comment by AllenCoder** [comment]
请看Api源码
