### ISSUE TITLE
helper获取view，setTextSize不生效，

### ISSUE THREAD

**Issue by zxy007963** [CymChad/BaseRecyclerViewAdapterHelper#2493]
第一种：
int dimen = mContext.getResources().getDimensionPixelSize(R.dimen.text_size_48);
TextView tv = helper.getView(R.id.tx_item_hand_over_out_date);
 tv.setTextSize(COMPLEX_UNIT_PX, dimen);
第二种
TextView tv = helper.getView(R.id.tx_item_hand_over_out_date);
 tv.setTextSize(100);
第三种
DisplayMetrics dm =mContext.getResources().getDisplayMetrics();
float value = dm.scaledDensity;
TextView textView = helper.getView(R.id.tx_item_hand_over_out_date);
textView.setTextSize(10/value);

都不生效，字体大小无变化

**Comment by AllenCoder** [comment]
字体不生效，请检查是否是绑定了错误的view
