### ISSUE TITLE
弱弱问一下，如何一行显示多个item？

### ISSUE THREAD

**Issue by zj2050** [CymChad/BaseRecyclerViewAdapterHelper#2494]
我希望在横屏状态下一行显示多个item，如何做？谢谢

final GridLayoutManager manager = new GridLayoutManager(this, 4);
后面这个 4 是每行 item的 个数吗？

**Comment by yaoxin2017** [comment]
监听屏幕旋转，设置新的布局管理就可以了

**Comment by zj2050** [comment]
> 监听屏幕旋转，设置新的布局管理就可以了

@yaoxin2017 就是希望了解怎么布局成2 个， 缺省就横屏的
