### ISSUE TITLE
BaseMultiItemQuickAdapter配合GridLayoutManager的时候，loadMoreView不会占满一行

### ISSUE THREAD

**Issue by 7hundeR** [CymChad/BaseRecyclerViewAdapterHelper#2495]
BaseQuickAdapter没有这个问题

**Comment by 7hundeR** [comment]
解决了，是设置adapter跟设置layoutManager先后的问题

**Comment by protectedMan** [comment]
文档里有提到这一块
![image](https://user-images.githubusercontent.com/17565737/54890420-48a82580-4ee4-11e9-96c9-1ad09f4ad2f3.png)
