### ISSUE TITLE
实现电商首页这种复杂布局的数据处理问题

### ISSUE THREAD

**Issue by clearloveforyou** [CymChad/BaseRecyclerViewAdapterHelper#2496]
**Describe the bug**
电商首页用MultipleItemRvAdapter确实不错，但是数据还是得整理成一个List!假如首页有4个接口，那么就得把这四个接口的数据整理到一个List里面。那么问题就来了：1.必须得四个接口都请求完毕，才能处理数据，毕竟list的每个元素排放的位置就是我们显示的顺序 2.为什么不可以像Vlayout那样先确定下来排放顺序，然后在网络请求刷新对应模块？3.如果不整理成一个list，是不是就降低了item的复用性？

**Comment by AllenCoder** [comment]
两套框架的布局思路不一致，vlayout 是基于LayoutManager 做扩展改造的，MultipleItemRvAdapter是基于Adapter改造的。针对电商场景，vlayout的布局思路更优秀 。两套框架可以在一定程度上实现融合，但是需要两边都要改造

**Comment by Limy1992** [comment]
是不是也可以使用添加头布局的方式来做。

**Comment by AllenCoder** [comment]
可以。电商布局更推荐用vlayout，比较场景更复杂，处理的逻辑更多
