### ISSUE TITLE
adapter.notifyDataSetChanged()崩溃异常

### ISSUE THREAD

**Issue by lucky-you** [CymChad/BaseRecyclerViewAdapterHelper#2497]
在adaptera中调用adapter.notifyDataSetChanged()方法之后报异常。
![image](https://user-images.githubusercontent.com/22268878/46936069-b3c91280-d08f-11e8-8795-7173d76429c4.png)

**Comment by lucky-you** [comment]
渲染完之后，checkBox改变状态，调用notifyDataSetChanged()就会出现这个异常

**Comment by Guangxingtianxia** [comment]
holder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        int pos = holder.getAdapterPosition();
                        
                        if (headerItem.isExpanded()) {

                            // 关闭
                            collapse(pos, false);

                            // 1: 显示某view

                        } else {
                            // 开启
                            expand(pos, false);

                              // 2: 隐藏某view
                    
                        }

                        notifyDataSetChanged();
                    }
                });




为什么这样的代码，无法控制某一view 的显示与隐藏？

**Comment by AllenCoder** [comment]
要通过数据层字段绑定view的状态。
