### ISSUE TITLE
求助：RecyclerView + BRVAH

### ISSUE THREAD

**Issue by OblivioU** [CymChad/BaseRecyclerViewAdapterHelper#2498]
RecyclerView + BRVAH 多布局刷新界面闪烁
多布局Item包括 Banner， Marquee , HorizontalRecyclerView 多个
已尝试去除动画，setTag防止图片重复加载，都无功而返

求正确使用姿势，谢谢！

**Comment by AllenCoder** [comment]
1. 刷新策略改为局部刷新
2. 布局参数尽量指定，不要动态计算
3. 嵌套布局最好不要有
4. adapter的convert方法尽量不要有任何计算耗时任务

**Comment by OblivioU** [comment]
1. 2. 3. 4. 都符合了，也是不行，能否发下代码到邮箱帮我看下呢？
