### ISSUE TITLE
migrate to AndroidX

### ISSUE THREAD

**Issue by lwj1994** [CymChad/BaseRecyclerViewAdapterHelper#2499]
when to migrate to AndroidX?

**Comment by YZune** [comment]
hope to migrate to AndroidX soon.

**Comment by AllenCoder** [comment]
Android x migration completed [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.9.43-alpha1](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.9.43-alpha1)
