### ISSUE TITLE
为什么初始化列表就调用addLoadMore方法

### ISSUE THREAD

**Issue by zhujunjun** [CymChad/BaseRecyclerViewAdapterHelper#250]
为什么我初始化列表的时候，就调用以下方法呢？难道一定要传入pageSize值？刚开始加载的时候没有调用刷新方法，而去调用了onLoadMoreRequested()方法？求解
private void addLoadMore(RecyclerView.ViewHolder holder) {
        if (isLoadMore() && !mLoadingMoreEnable) {
            mLoadingMoreEnable = true;
            mRequestLoadMoreListener.onLoadMoreRequested();
        }
    }

**Comment by CymChad** [comment]
恩，你先传入，一个pageSize，我这边在检查一下。

**Comment by CymChad** [comment]
你说的是2.0对吧？

**Comment by zhujunjun** [comment]
是的~

**Comment by CymChad** [comment]
恩，那你就先传入pageSize，我这边看看先。

**Comment by zhujunjun** [comment]
传了pageSize也没用，比较奇怪的就是我请求的数据都还没回来，就调用了如下代码段的addLoadMore方法。这个onBindViewHolder是需要有数据了才会调用。
 @Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder, int positions) {
        int viewType = holder.getItemViewType();

        switch (viewType) {
            case 0:
                convert((BaseViewHolder) holder, mData.get(holder.getLayoutPosition() - getHeaderLayoutCount()));
                break;
            case LOADING_VIEW:
                addLoadMore(holder);
                break;
            case HEADER_VIEW:
                break;
            case EMPTY_VIEW:
                break;
            case FOOTER_VIEW:
                break;
            default:
                convert((BaseViewHolder) holder, mData.get(holder.getLayoutPosition() - getHeaderLayoutCount()));
                onBindDefViewHolder((BaseViewHolder) holder, mData.get(holder.getLayoutPosition() - getHeaderLayoutCount()));
                break;
        }

    }

**Comment by tq01m4m** [comment]
我也是这个bug，mark下

**Comment by CymChad** [comment]
看下你的代码，你确定设置了？

**Comment by zhujunjun** [comment]
这是我初始化adapter代码：
  mySelfRedPackageAdapter = new MySelfRedPackageNewAdapter (null);
        mySelfRedPackageAdapter.openLoadAnimation();
        mySelfRedPackageAdapter.openLoadMore(PAGE_SIZE);
        xListView.setAdapter(mySelfRedPackageAdapter);
        swipeLayout.setRefreshing(true);
        mySelfRedPackageAdapter.setOnLoadMoreListener(this);
这是数据请求回来设置adapter代码：
if (page == 1) {
                    mCurrentCounter=vo.size();
                   // mySelfRedPackageAdapter.openLoadMore(PAGE_SIZE);
                    mySelfRedPackageAdapter.setNewData (vo);
                    mySelfRedPackageAdapter.removeAllFooterView();
                } else {
                    mySelfRedPackageAdapter.addData(vo);
                }

**Comment by CymChad** [comment]
你的PageSize是多少？

**Comment by zhujunjun** [comment]
设置的20

**Comment by CymChad** [comment]
你一页显示多个？

**Comment by zhujunjun** [comment]
一页显示20个

**Comment by CymChad** [comment]
看下你的界面。

**Comment by zhujunjun** [comment]
这段代码是定义的适配器：
   public class MySelfRedPackageNewAdapter extends BaseQuickAdapter<CouponUserNewFilter>{


        public MySelfRedPackageNewAdapter(int layoutResId, List<CouponUserNewFilter> data) {
            super(layoutResId, data);
        }

        public MySelfRedPackageNewAdapter(List<CouponUserNewFilter> data) {
            super(data);
        }

        public MySelfRedPackageNewAdapter(View contentView, List<CouponUserNewFilter> data) {
            super(contentView, data);
        }

        @Override
        public BaseViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            View redPackageItemView = new MySelfRedPackageItemView (MySelfRedPackageActivity.this, null);
            return new RedViewHolder(redPackageItemView);
        }


        @Override
        protected void convert(BaseViewHolder helper, CouponUserNewFilter item) {
            ((MySelfRedPackageItemView) helper.getConvertView()).setData(item);
        }
    }

    public class RedViewHolder extends BaseViewHolder{

        protected RedViewHolder(View view) {
            super(view);
        }
    }

**Comment by CymChad** [comment]
你重写了onCreateViewHolder？

**Comment by zhujunjun** [comment]
![device-2016-08-23-175523](https://cloud.githubusercontent.com/assets/17331613/17887899/1116ac84-695b-11e6-964e-f02fb0397281.png)
是的！因为我把这个item布局封装成一个组件了！数据处理交给组件内部设置

**Comment by zhujunjun** [comment]
不知道为什么最后一项还有一块没有数据的item

**Comment by CymChad** [comment]
因为你重写了onCreateViewHolder，他应该是要显示加载中的布局的。

**Comment by zhujunjun** [comment]
那我自定义的组件怎么处理？

**Comment by CymChad** [comment]
你写在布局里面，convert方法里面，通过helper.getView拿到你的自定义布局,不要重写onCreateViewHolder。

**Comment by CymChad** [comment]
你设置了pageSize的话，是不会一进来就调用onLoadMoreRequested的。我测试过了。因为它不满足加载更多的条件
```java
private boolean isLoadMore() {
        return mNextLoadEnable && pageSize != -1 && mRequestLoadMoreListener != null && mData.size() >= pageSize;
    }
```

**Comment by zhujunjun** [comment]
你好，按照你的要求我把我的adapter重改了一次如下：
    public class MySelfRedPackageNewAdapter extends BaseQuickAdapter<CouponUserNewFilter>{

        public MySelfRedPackageNewAdapter(){
            super(R.layout.u_red_item_layout,null);
        }

        @Override
        protected void convert(BaseViewHolder helper, CouponUserNewFilter item) {
            ((MySelfRedPackageItemView) helper.getConvertView()).setData(item);
        }
    }
为什么第一次加载的时候还是去调用了public void onBindViewHolder(final RecyclerView.ViewHolder holder, int positions)方法？

**Comment by zhujunjun** [comment]
ok ~非常感谢！@CymChad
