### ISSUE TITLE
Expansion Issue in ExpandableItemAdapter and also want to know how can i use Custom Holder?

### ISSUE THREAD

**Issue by kushanshah11** [CymChad/BaseRecyclerViewAdapterHelper#2503]
**Describe the bug**
1 .when i expand two or more Item from level 1 and collapse anyone of them it will collapse first item of expanded.
**i have attached GIF of issue so you get better idea.**

used latest version of  implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.42'

2. i want to use my custom view holder how can i do this?

3. i want to get radiobutton value change with position and switch value to fragment how can i do this? 

Code =================

 private fun generateData(): ArrayList<MultiItemEntity> {

        val res = ArrayList<MultiItemEntity>()

        for (i in mainList) {

            val detailInfo = detailsList.find { info -> info.moduleEnumId.equals(i.moduleEnumId) }

            if (detailInfo == null) {
                detailInfo!!.value = 0
            }

            val lv0 = Level0Item(i.moduleName, detailInfo.value)

            for (j in i.featureList) {

                val detailInfo1 = detailsList.find { info -> info.moduleEnumId.equals(j.moduleEnumId) }

                if (detailInfo1 == null) {
                    detailInfo1!!.value = 0
                }

                val lv1 = Level1Item(j.featureName, detailInfo1.value)

                for ((k,value) in j.featureOptionList.withIndex()) {
                    //featurelist size is greater 2 add subItem else not
                    if (j.featureOptionList.size > 2){

                   //     val detailInfo2 = detailsList.find { info -> info.moduleEnumId.equals(detailInfo.moduleEnumId) }

                        val detailInfo2 =  detailInfo1!!.featureList.find { info->info!!.featureEnumId.equals(j.featureEnumId) }

                        if (detailInfo2 == null) {
                            detailInfo2!!.value = 0
                        }

                        if(value.featureOptionValue.equals(detailInfo2.value))
                        {
                            lv1.addSubItem(Person(value.featureOptionName, detailInfo2.value))
                        }else{
                            lv1.addSubItem(Person(value.featureOptionName, 0))
                        }

                    }

                }

                lv0.addSubItem(lv1)
            }
            res.add(lv0)
        }

        return res
    }

=============================================

 override fun convert(holder: BaseViewHolder, item: MultiItemEntity) {
        when (holder.itemViewType) {
            TYPE_LEVEL_0 -> {

                val lv0 = item as Level0Item

                holder.setText(R.id.tvMainModuleName, lv0.title)
                        .setChecked(R.id.scMainModule, lv0.switchValue != 0)

                holder.itemView.setOnClickListener {

                    val pos = holder.adapterPosition
                    Log.d(TAG, "Level 0 item pos: " + pos)
                    if (lv0.isExpanded) {
                        collapse(pos)
                    } else {
                        //                            if (pos % 3 == 0) {
                        //                                expandAll(pos, false);
                        //                            } else {
                        expand(pos)
                        //                            }
                    }
                }
            }
            TYPE_LEVEL_1 -> {

                val lv1 = item as Level1Item

                if(lv1.hasSubItem()){
                    holder.setVisible(R.id.scSubModule,false)
                }else{
                    holder.setVisible(R.id.scSubModule,true)
                }

                holder.setText(R.id.tvModuleSubName, lv1.title)
                        .setChecked(R.id.scSubModule,lv1.switchValue != 0)

                holder.itemView.setOnClickListener {

                    val pos = holder.adapterPosition
                    Log.d(TAG, "Level 1 item pos: " + pos)
                    if (lv1.isExpanded) {
                        collapse(pos)
                    } else {
                        expand(pos)
                    }

                }
            }
            TYPE_PERSON -> {

                val person = item as Person

                holder.setText(R.id.tvChildModule, person.name)
                        .setChecked(R.id.rbModule,person.switchValue != 0)

                holder.itemView.setOnClickListener {
                    /*val cp = getParentPosition(person)
                    (data[cp] as Level1Item).removeSubItem(person)
                    data.removeAt(holder.layoutPosition)
                    notifyItemRemoved(holder.layoutPosition)*/
                }
            }
        }
    }

end code ====================

**To Reproduce**

**Expected behavior**
i want to collapse all item if one of same level is expanded?

**Screenshots**

![2kb5sa](https://user-images.githubusercontent.com/18567763/47090802-3c3ae500-d241-11e8-9762-eeccaf48004f.gif)

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
1. [Use Custom BaseViewHolder](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Use-Custom-BaseViewHolder)
2.Update the latest version Please
3.You can get radiobutton value changes through data
