### ISSUE TITLE
请问有办法多加一个InitLoadingView之类的吗?

### ISSUE THREAD

**Issue by ohpoloha** [CymChad/BaseRecyclerViewAdapterHelper#2504]
库裡面有包含了EmptyView, 这个用于资料加载结束之后确定没有资料的时候很好用
可是我想要多一个InitLoadingView, 用于第一次资料还正在加载, 可以预设就显示该view直到setNewData被呼叫

**Comment by AllenCoder** [comment]
可以用状态布局 做为父布局，包含 loadView emptyView,netErrorView
