### ISSUE TITLE
findLastVisibleItemPosition not working

### ISSUE THREAD

**Issue by callmecaoye** [CymChad/BaseRecyclerViewAdapterHelper#2506]
**Describe the bug**
RecyclerView within GridLayoutManager
when call findLastVisibleItemPosition, the return always the last item in the list

**Comment by AllenCoder** [comment]
[https://stackoverflow.com/questions/24989218/get-visible-items-in-recyclerview ](https://stackoverflow.com/questions/24989218/get-visible-items-in-recyclerview)
