### ISSUE TITLE
版本号: 2.9.40

### ISSUE THREAD

**Issue by wanxiangxin** [CymChad/BaseRecyclerViewAdapterHelper#2508]
ViewPager + Fragment + RecyclerView 设置emptyView，左右切换时报这个错误。

_Originally posted by @a451492549 in https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2270#issuecomment-395285473_

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2270#issuecomment-395285473
