### ISSUE TITLE
Up to androidx library

### ISSUE THREAD

**Issue by johnzheng00** [CymChad/BaseRecyclerViewAdapterHelper#2509]
Note: With the release of Android 9.0 (API level 28) there is a new version of the support library called AndroidX which is part of Jetpack. The AndroidX library contains the existing support library and also includes the latest Jetpack components. 

You can continue to use the support library. Historical artifacts (those versioned 27 and earlier, and packaged as android.support.*) will remain available on Google Maven. However, all new library development will occur in the AndroidX library. 

We recommend using the AndroidX libraries in all new projects. You should also consider migrating existing projects to AndroidX as well.

**Comment by AllenCoder** [comment]
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.9.43-alpha1](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.9.43-alpha1)
Androidx migration work has been completed

**Comment by johnzheng00** [comment]
Thanks
