### ISSUE TITLE
树形列表点击出现闪烁

### ISSUE THREAD

**Issue by Bruce8hou** [CymChad/BaseRecyclerViewAdapterHelper#2513]
树形列表在点击的时候出现闪烁，数据是提前准备好了的，有没有什么办法解决呢

**Comment by GreenhairTurtle** [comment]
闪烁是因为出现了默认动画，把动画禁用就好了
···java
//防止频繁刷新闪屏
    ((SimpleItemAnimator) recyclerView.getItemAnimator())
        .setSupportsChangeAnimations(false);
···

**Comment by DanteAndroid** [comment]
@GreenhairTurtle 大佬，设置了以后，顶级列表不闪烁了。但是展开后的次级列表里的 item 还是会闪烁请问为什么

**Comment by GreenhairTurtle** [comment]
@DanteAndroid 是点击闪烁吗？还是展开动画？

**Comment by DanteAndroid** [comment]
> @DanteAndroid 是点击闪烁吗？还是展开动画？

展开的时候闪烁。像是动画，但是我记得 recyclerView 增加 item 时候的动画是很自然的插♂入，没有什么闪烁啊

**Comment by GreenhairTurtle** [comment]
@DanteAndroid 
```java
 setSupportsChangeAnimations(false)
```
只是itemChanged的动画不显示了

展开动画调用的是recyclerView默认动画，如果要改变，网上很多资料的

**Comment by DanteAndroid** [comment]
@GreenhairTurtle 非常感谢

**Comment by asyncHyj** [comment]
@Bruce8hou 大佬，解决了，不给出解决方案的吗？

**Comment by Bruce8hou** [comment]
> @Bruce8hou 大佬，解决了，不给出解决方案的吗？

//防止频繁刷新闪屏
    ((SimpleItemAnimator) recyclerView.getItemAnimator())
        .setSupportsChangeAnimations(false);

**Comment by zhaoxiuyu** [comment]
@Bruce8hou  @asyncHyj  @GreenhairTurtle  三级菜单知道怎么设置 同时只能展开一项吗？

**Comment by Bruce8hou** [comment]
> @Bruce8hou @asyncHyj @GreenhairTurtle 三级菜单知道怎么设置 同时只能展开一项吗？

目前还没有用过三级菜单，

**Comment by CymChad** [comment]
同时展开一项的思路可以在展开的时候先关闭所有项，然后在打开点击的这一项。
