### ISSUE TITLE
多布局时，在 convert() 函数里动态控制 view的显示与隐藏，不起作用， notifyItemChanged(pos);

### ISSUE THREAD

**Issue by Guangxingtianxia** [CymChad/BaseRecyclerViewAdapterHelper#2514]
holder.itemView.setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
int pos = holder.getAdapterPosition();

                    if (headerItem.isExpanded()) {

                        // 关闭
                        collapse(pos, false);

                        // 1: 显示某view

                    } else {
                        // 开启
                        expand(pos, false);

                          // 2: 隐藏某view
                
                    }

                    notifyDataSetChanged();
                }
            });
为什么这样的代码，无法控制某一view 的显示与隐藏？

**Comment by TomGarden** [comment]
通过 position +1 得到了解决
暂未详究原因
希望有更合理的解决方式

**Comment by CymChad** [comment]
收到

**Comment by shichaohui** [comment]
未能重现该问题，因此先行关闭。
如果您已经解决该问题，可以在下方回复解决方案。
如果您还有遇到此问题，请参考 #2807 重新提交 Issue 。
