### ISSUE TITLE
Recyclerview 嵌套时, item点击事件处理,子Recyclerview不响应父Recyclerview的点击

### ISSUE THREAD

**Issue by 18810867174** [CymChad/BaseRecyclerViewAdapterHelper#2516]
helper.addOnClickListener(R.id.recycler_view);// adapter 里面设置子Recyclerview为子控件点击
     helper.addOnClickListener(R.id.btn2);

//Activity里面的监听  
orderListAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                switch (view.getId()){
                    case R.id.recycler_view://不走
                        Log.e("--11111111111--->>",position+"");
                        break;
                   case R.id.btn2://走
                        Log.e("--22222222222--->>",position+"");
                        break;
                }
            }

**Comment by AllenCoder** [comment]
嵌套点击事件参考  Demo写法 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java)

**Comment by cdcdec** [comment]
我也遇到这个问题  ，我认为这个demo里面的写法  解决不了这个问题

**Comment by plain-dev** [comment]
@18810867174 你好，问题解决了吗

**Comment by 18810867174** [comment]
你好! 因为工作原因,已经离开当时的公司了,项目代码没有,拷到现在所在的公司环境里,晚上下班后看看代码才知道,等我晚上回复你.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Plain"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 上午10:50
收件人:&nbsp;"CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;;
抄送:&nbsp;"小十三"<894670253@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [CymChad/BaseRecyclerViewAdapterHelper] Recyclerview 嵌套时, item点击事件处理,子Recyclerview不响应父Recyclerview的点击 (#2516)





 
@18810867174 你好，问题解决了吗

**Comment by plain-dev** [comment]
@18810867174 谢谢，期待你的好消息

**Comment by 18810867174** [comment]
你好!不好意思,这两天事情较多一直没时间查看之前的代码,&nbsp;刚刚看来之前写的代码,&nbsp;是这么处理的,没有使用一级RecyclerView的&nbsp;子控件点击监听,而是在二级RecyclerView&nbsp;里面直接使用item点击监听实现的.因为这份代码是2018年的了,不知道现在有没有好的解决方法.

**Comment by plain-dev** [comment]
@18810867174 

我遇到的情况是这样的，内部的`RecyclerView`是一个图片的列表，网格布局的，一行7个。

然后内部`RecyclerView`的每个item有个点击事件，查看大图的。

当我为外层的`RecyclerView`设置item的点击事件后，内部`RecyclerView`空白的地方，无法响应点击。

针对这个问题，我最后是这么处理的。

```java
childAdapter.setOnItemClickListener((adapter, view, position) -> {
	// 查看大图
}
});

// 将子RecyclerView的点击事件传给外层itemView进行处理
childRV.setOnTouchListener((v, event) -> itemView.onTouchEvent(event));
```

🙏 最后感谢你的回复 ❤️
