### ISSUE TITLE
headerView 高度问题。

### ISSUE THREAD

**Issue by guoleifei** [CymChad/BaseRecyclerViewAdapterHelper#2518]
val view=      LayoutInflater.from(this).inflate(R.layout.roster_info_name, null) 
使用这种方式加载的时候获取不到第二个参数 因为没有地方能获取到mHeaderLayout 并且此时不一定初始化了这个父级布局。所以带入不了 布局文件的高度属性。
能否添加一个方法设置这个headerview 的高度？

**Comment by AllenCoder** [comment]
可以直接对headerView是一个inflate的view,可以人为指定宽度和高度
