### ISSUE TITLE
请问加载更多的view能全局设置吗

### ISSUE THREAD

**Issue by Jibinghao** [CymChad/BaseRecyclerViewAdapterHelper#2519]
不想每次都动态设置一遍加载更多的view，有没有什么办法在全局设置？

**Comment by wimvogt** [comment]
可以创建一个与原有加载更多布局名称一样的布局，app会覆盖原有布局。
注意：1、如果更新版本，需要查看源码，名称可以会变
           2、控件id需要与引用版本库中的布局中的控件id一样
