### ISSUE TITLE
语音播放时滑动问题

### ISSUE THREAD

**Issue by flyinggor** [CymChad/BaseRecyclerViewAdapterHelper#2520]
类似聊天界面，语音播放时上拉加载数据是否可以让语音不停止

**Comment by parcool** [comment]
兄弟，你应该是整一个播放的service，点击列表的选项就是调那个service播放而已(service播放需要的url根据点击的position从data里拿)，需要停止的时候自己手动去调那个service的方法。。。当然，你也可以直接放到Activity/Fragment里。
这种跟列表毛关系没有。
