### ISSUE TITLE
BaseMultiItemQuickAdapter Header

### ISSUE THREAD

**Issue by ChristingLi** [CymChad/BaseRecyclerViewAdapterHelper#2524]
2.9.43

在多类型Adapter中addHeader 导致列表的Position少1
![image](https://user-images.githubusercontent.com/32630546/48395477-5984a580-e752-11e8-9bf3-825204646a52.png)
position + 1时 取出的数据才是正确的

**Comment by wuxuebai** [comment]
谢谢 我也遇到这个问题了

**Comment by wuxuebai** [comment]
但是原理还不是太懂！
