### ISSUE TITLE
webview作为header，当header完全不可见时，往上拉动 当到达header 跟 recyclerview 分界出 会有明显的卡顿感

### ISSUE THREAD

**Issue by lrain-lv** [CymChad/BaseRecyclerViewAdapterHelper#2525]
webview作为header，当header完全不可见时，往上拉动 当到达header 跟 recyclerview 分界出 会有明显的卡顿感

**Comment by lrain-lv** [comment]
发现了，不是adapter的问题 是x5webview的问题

**Comment by TrebleZ** [comment]
我也是用的x5webview,想问下最后你怎么优化这个卡顿了

**Comment by TrebleZ** [comment]
> 发现了，不是adapter的问题 是x5webview的问题

我也是用的x5webview,想问下最后你怎么优化这个卡顿了 @lrain-lv
