### ISSUE TITLE
按照教程写，子级列表的布局不符合预期

### ISSUE THREAD

**Issue by DanteAndroid** [CymChad/BaseRecyclerViewAdapterHelper#2527]
教程：
 ![image](https://user-images.githubusercontent.com/10005563/48534690-c5e2de80-e8e3-11e8-8674-13264fc5692c.png)
实际效果：
![image](https://user-images.githubusercontent.com/10005563/48534733-f0cd3280-e8e3-11e8-830f-8e5a328aebe6.png)
预期效果：子级的菜单像教程图片那样，横向排列。而不是每行只有一个 item

**Comment by GreenhairTurtle** [comment]
你用的是LinearLayoutManager吧
```java
 final GridLayoutManager manager = new GridLayoutManager(this, 3);
        manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return adapter.getItemViewType(position) == ExpandableItemAdapter.TYPE_PERSON ? 1 : manager.getSpanCount();
            }
        });
```
Demo用的是GridLayoutManager

**Comment by DanteAndroid** [comment]
@GreenhairTurtle 感谢。一开始用的是 BRVAH 自带的 setSpanSizeLookup 方法，没有效果。改为系统的 GridLayoutManager 去设置就好了。

**Comment by DanteAndroid** [comment]
@GreenhairTurtle 老哥再問你一個問題：如何获取某个**次级菜单中item**的顶级菜单的item（或者其position）？

**Comment by GreenhairTurtle** [comment]
@DanteAndroid getParentPosition
