### ISSUE TITLE
recyclerview嵌套reyclerview,点击二级recyclerview无法获取被点击的二级recyclerview在一级recyclerview中的position

### ISSUE THREAD

**Issue by chao9267** [CymChad/BaseRecyclerViewAdapterHelper#2528]

**Comment by AllenCoder** [comment]
参考demo的 嵌套点击事件写法 
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java)

**Comment by chao9267** [comment]
我的是类似评论的那种嵌套  外层recyclerviewA是文章评论   在onBindViewHolder中初始化RecyclerviewB显示每条文章评论的下面的回复   不管是recyclerviewA 还是recyclerviewB都有对内容的点击事件和点赞按钮  不知道适用不

**Comment by cdcdec** [comment]
这种怎么解决呀
