### ISSUE TITLE
When the pull to refresh is combined with onloadmore with load fail, it crashes

### ISSUE THREAD

**Issue by marvinmosa** [CymChad/BaseRecyclerViewAdapterHelper#253]
Having an issue regarding the slowLoadMoreFailedView when i am trying both on load more and pull to refresh at the same time
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup)' on a null object reference
                                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.showLoadMoreFailedView(BaseQuickAdapter.java:725)`

**Comment by marvinmosa** [comment]
Although if i put your `mListAdapter.removeAllFooterView();` on the `onRefresh()` method it works.

**Comment by CymChad** [comment]
Problem has been received and is looking for problems, back to you later

**Comment by CymChad** [comment]
Please give your code

**Comment by shichaohui** [comment]
I think that when you call the showLoadMoreFailedView() method, the adapter is no data. At this time the object named layoutInflater is not initialized, so, you got NullPointerException. If you need prompt when load failed and adapter is no data, you can use emptyView. You can refer to [the demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/tree/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper).
