### ISSUE TITLE
关于BaseMultiItemQuickAdapter单个item间距问题

### ISSUE THREAD

**Issue by 1060680253** [CymChad/BaseRecyclerViewAdapterHelper#2533]
![27be399b-4259-4bd6-993f-d46239d27055](https://user-images.githubusercontent.com/15134794/48826475-58ccbe80-eda5-11e8-93f1-821636a1d4f3.png)
作者你好，关于上图有个问题，关于这样的recycleview的布局，当我用BaseMultiItemQuickAdapter的时候，我给recycleview设置griblayout为4的layoutmanager，但是第三行的蓝色标注的额外间距就是无法设置，请问有什么好的方法吗？

**Comment by CymChad** [comment]
这个是adapter的分配比例机制问题

**Comment by OilLyu** [comment]
> 这个是adapter的分配比例机制问题

请问这个问题要如何解决？我也在项目中遇到了。。着急
