### ISSUE TITLE
 android.view.InflateException: Binary XML file line #15 在Library 使用的时候报错

### ISSUE THREAD

**Issue by Terry999555** [CymChad/BaseRecyclerViewAdapterHelper#2536]
我在Library 中使用 Adapter的 setOnLoadMoreListener () 方法的时候,出现奔溃,我的Library引用的是 另一个Library中的依赖库.  每次加载的时候就会奔溃, 提示 android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class widget.RefreshView

**Comment by AllenCoder** [comment]
加载更多自定义view的设置建议参考demo写法
