### ISSUE TITLE
对Android TV开发  焦点事件的支持

### ISSUE THREAD

**Issue by kimonic** [CymChad/BaseRecyclerViewAdapterHelper#2537]
作者能够添加一下对Android TV开发中焦点相关操作的支持么???

**Comment by AllenCoder** [comment]
android 焦点开发的支持目前涉及到的工作量还在评估，但短时间内开发组成员的业余时间都不是很多，支持和跟进会很慢，如有能力可自己开发和贡献相关功能的pr
