### ISSUE TITLE
recyclerviewA嵌套recyclerviewB，给recyclerviewA的adapter设置OnItemclicklisten，点击recyclerviewB区域recyclerviewA的adapter点击事件无响应

### ISSUE THREAD

**Issue by chao9267** [CymChad/BaseRecyclerViewAdapterHelper#2539]
recyclerviewA嵌套recyclerviewB，给recyclerviewA的adapter设置onItemclicklisten，点击recyclerviewB区域recyclerviewA的adapter点击事件无响应

**Comment by AllenCoder** [comment]
参考demo的嵌套事件写法   [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java)

**Comment by kimljx** [comment]
> 参考demo的嵌套事件写法 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java
提醒一下链接404了
