### ISSUE TITLE
Possibilty of adding data to certain location

### ISSUE THREAD

**Issue by marvinmosa** [CymChad/BaseRecyclerViewAdapterHelper#254]
Hello Again, I was wondering if you can overload addData function to add data to certain location so that it will be more flexible.

**Comment by CymChad** [comment]
Thank you for your advice, later I will to improve it.

**Comment by CymChad** [comment]
Inform you after the modification of good

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.6'
