### ISSUE TITLE
网格布局设置空视图不能显示吗？

### ISSUE THREAD

**Issue by JhoBor** [CymChad/BaseRecyclerViewAdapterHelper#2540]
在fragment中设置网格布局，DevicesInRoomAdapter 继承BaseQuickAdapter，此时的mDevicesInRoomMap.get(room.getId())为null，然后设置空视图，不显示：

deviceRcv.setLayoutManager(new GridLayoutManager(getContext(),2));
DevicesInRoomAdapter adapter = new DevicesInRoomAdapter(mDevicesInRoomMap.get(room.getId()));
adapter.setEmptyView(R.layout.page_no_device,deviceRcv);
deviceRcv.setAdapter(adapter);

**Comment by AllenCoder** [comment]
能显示，但此时需要注意emptyView是作为一个itemview加进去的，会因为gridlayoutmanger控制显示不一定符合你的需求，网格布局建议当数据为空时调整  GridLayoutManager的每格显示个数，或者结合第三方的stateLayout搭配recyclerview来使用控制空布局的显示和隐藏

**Comment by getglory** [comment]
GridLayoutManager空布局无法全屏，需要使用StaggeredGridLayoutManager
