### ISSUE TITLE
树形列表item折叠时，ItemDecoration的getItemOffsets方法报下标越界错误

### ISSUE THREAD

**Issue by huang-yongTech** [CymChad/BaseRecyclerViewAdapterHelper#2544]
界面有一个树形列表，我要根据每一级设置列表左侧的缩进，类似目录那样，设置缩进我使用的是继承ItemDecoration覆写getItemOffsets方法，如下图所示：
![qq 20181127190708](https://user-images.githubusercontent.com/19563382/49078203-57553780-f278-11e8-8a3b-fca013a50bd8.png)
列表在展开的时候都是正常的，但是在折叠的时候红框标记的地方就会提示下标越界这个错误。请问这个要怎么处理？

**Comment by AllenCoder** [comment]
检查你传入数据
