### ISSUE TITLE
连续快速点击会调用两次 OnItemClickListener

### ISSUE THREAD

**Issue by lw254605953** [CymChad/BaseRecyclerViewAdapterHelper#2546]
**Describe the bug**
最基本的用法，而且在demo上也复现了，比如在demo首页，快速点击Animation的itemview（很快的那种，抽筋速度点。。），就会加载两次新页面

按照 #1486 的理解，框架是支持防止重复点击的，不知道我理解的是否有误，还是本身这块就需要开发者自行开发，望指教，谢谢

1. 当前使用的版本号   2.9.34
2. 如上
3. 使用代码
BaseQuickAdapter adapter......
adapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(final BaseQuickAdapter adapter, final View view, final int position) {
                Logger.e("1111111111");
            }
        });

**Comment by AllenCoder** [comment]
快速重复点击 响应 ，本身就符合功能需求，如果跟你们的产品需求不符，可以做消抖处理

**Comment by lw254605953** [comment]
说实话不是很理解为什么这个回事符合功能的需求，连续点击会打开两个相同的页面，什么样的需求会需要载入两个相同的页面？最后还是感谢回答，感谢开源，谢谢

**Comment by lw254605953** [comment]
> 快速重复点击 响应 ，本身就符合功能需求，如果跟你们的产品需求不符，可以做消抖处理

说实话不是很理解为什么这个回事符合功能的需求，连续点击会打开两个相同的页面，什么样的需求会需要载入两个相同的页面？最后还是感谢回答，感谢开源，谢谢

**Comment by helloworld10010** [comment]
怎么消抖的

**Comment by Allen0828** [comment]
初学者也遇到了!!! 临时解决方法 目前能用.
在Main获取tools中定义方法
```kotlin
inline fun View.setOnSingleClickListener(crossinline onClick: () -> Unit) {
    this.setOnClickListener {
        this.isClickable = false
        onClick()
        this.postDelayed({
            this.isClickable = true
        }, 1000)
    }
}
```
在使用View点击事件的方法中 替换onClick
```kotlin
headerView.setOnSingleClickListener {
        val intent = Intent(this.requireContext(), AudioActivity::class.java)
        startActivity(intent)
 }
```
在RecyclerView.Adapter中
```kotlin
override fun onBindViewHolder(holder: ExampleViewHolder, position: Int) {
        val currentItem = exampleList[position]
        holder.imageView.setImageResource(currentItem.imageResuorce)

        holder.itemView.setOnSingleClickListener {
            itemClickListener!!.onItemClickListener(position)
        }
        holder.textView1.text = currentItem.text1
        holder.textView2.text = "currentItem.text2"
        holder.titleLa.text = "i am title"
    }
```

**Comment by cdcde** [comment]
第一次不起作用
