### ISSUE TITLE
2.0版本 点击事件的按压效果无效

### ISSUE THREAD

**Issue by nEdAy** [CymChad/BaseRecyclerViewAdapterHelper#255]
Item的点击事件的按压效果无效 cardview的效果没有了
Item子控件的点击事件的按压效果设置background 的state_pressed state_focused 无效

**Comment by AllenCoder** [comment]
已收到反馈，正在排查问题。

**Comment by AllenCoder** [comment]
按照RecyclerView的设计，RecyclerView负责控制/框架，LayoutManager负责计算布局，假设将ItemClickListener放到RecyclerView上，如果要实现点击事件，首先需要确定每一个item的点击区域。但是RecyclerView无法知道每一个item的点击区域，因为LayoutManager是可以由开发者来实现的，也就是说两个View的区域是允许重叠的。如果点了A和B重叠区域到底是触发A还是B，又必须要由LayoutManager来决定。所以还不如直接放到LayoutManager中，但如果放到LayoutManager中的话需要给RecyclerView添加OnTouchListener，看上去又很别扭（要是外部给RecyclerView设置OnTouchListener会覆盖掉这个导致ItemClickListener失效）

所以google干脆就不干了，至少还能保持源码的整洁－。－（ListView中有一个很复杂的状态机就是用来维护Click点击态的）


(转自知乎)链接：https://www.zhihu.com/question/30336190/answer/47765575

从目前来看，这个 click 确实不容易维护和区分。目前的 bug 出现在手势消费掉了 click 的事件，造成背景 selector 无法正常切换,正在寻求更合理的解决办法

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.1' bug已修复

**Comment by i25net** [comment]
修改速度真的好快啊
