### ISSUE TITLE
androidstudio3.2.1 无法添加引用

### ISSUE THREAD

**Issue by shenchen1987** [CymChad/BaseRecyclerViewAdapterHelper#2552]
按照说明引入：
  allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
---------------------------------------------------
  dependencies {
            compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.40'
    }
结果编译时报错：
Could not GET 'https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.42/BaseRecyclerViewAdapterHelper-2.9.42.pom'. Received status code 400 from server: Bad Request

尝试过开启蓝灯，重启stuido。
还有啥方法可试试？？

**Comment by AllenCoder** [comment]
检查代理网络

**Comment by shenchen1987** [comment]
> 检查代理网络

把compile改成api和implementation 也不行，你说的检查代理网络是androidstudio的设置吗？
