### ISSUE TITLE
线性布局点击事件混乱

### ISSUE THREAD

**Issue by susan007** [CymChad/BaseRecyclerViewAdapterHelper#256]
将RecyclerView布局设置为LinearLayoutManager后，item点击事件混乱。比如点击了第一个按钮但第十个（不确定是第几个）按钮也会自动被点击。

**Comment by CymChad** [comment]
2.0版本吗？

**Comment by AllenCoder** [comment]
贴点击代码 及 使用版本？

**Comment by AllenCoder** [comment]
经排查，是 recyclerview 缓存 bug，其实这里有一个更好的处理思路，你可以在数据层  List 里面增加一个字段 用来判断区分 imageview 的显示和隐藏 ，例如 boolean  isClick =false;在 SimpleOnItemChildClick 判断 isClick 的值 ，然后刷新对应列表 image 的显示和隐藏，可以很好的处理和避免了上面的 bug 和满足需求
