### ISSUE TITLE
关于多布局刷新的问题

### ISSUE THREAD

**Issue by whmain** [CymChad/BaseRecyclerViewAdapterHelper#2563]
我的实体实现了MultiItemEntity，我在向list中添加数据后，使用 mAdapter.notifyDataSetChanged()方法刷新，RecyclerView上没有看到增加的那一项，需要滑动一下才会出现新增的那一项，请问下这怎么解决呀

**Comment by LI5426629** [comment]
请教大佬，这个问题你是怎么解决的？？？

**Comment by AllenCoder** [comment]
多布局刷新和普通适配器刷新没有本质上的区别，调用刷新的方法可能不符合你们的效果
