### ISSUE TITLE
俺想问下 以后是不是考虑拓展个悬停的条目...

### ISSUE THREAD

**Issue by wangzixu5678** [CymChad/BaseRecyclerViewAdapterHelper#2568]
RT  就像VLayout里那样咩 俺就是弱弱的问一下 顺便膜拜下大神咩.

**Comment by downtail** [comment]
https://github.com/downtail/ItemDecorationPlus自己写的参考一下

**Comment by CymChad** [comment]
https://github.com/downtail/ItemDecorationPlus  @downtail  非常感谢
