### ISSUE TITLE
2.0 emptyview 我设置的空布局 结果显示错误布局  来回切换emptyview  就混乱了

### ISSUE THREAD

**Issue by addappcn** [CymChad/BaseRecyclerViewAdapterHelper#257]

**Comment by CymChad** [comment]
贴代码

**Comment by CymChad** [comment]
你切换的时候，可以用  mQuickAdapter.notifyItemChanged(0);

**Comment by addappcn** [comment]
View  view = null;
        if (type==0){
            view = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) root.getParent(), false);
            view.setBackgroundResource(R.color.pub_bg_color);
            TextView txtRefresh = (TextView) view.findViewById(R.id.txt_refresh);
            TextView txtEmpty = (TextView) view.findViewById(R.id.txt_empty);
            ImageView imgEmpty = (ImageView) view.findViewById(R.id.img_empty);
            if (onlyFont){
                txtEmpty.setText(showMsg);
                imgEmpty.setVisibility(View.GONE);
                txtRefresh.setVisibility(View.GONE);
            } else{
                imgEmpty.setVisibility(View.VISIBLE);
                txtRefresh.setVisibility(View.VISIBLE);
                txtRefresh.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        if(null!=listener)
                            listener.onRefresh();
                    }
                });
            }
        } else {
            view = getLayoutInflater().inflate(R.layout.error_view, (ViewGroup) root.getParent(), false);
            view.setBackgroundResource(R.color.pub_bg_color);
            TextView txtRefresh = (TextView) view.findViewById(R.id.txt_refresh);
            TextView txtEmpty = (TextView) view.findViewById(R.id.txt_empty);
            ImageView imgEmpty = (ImageView) view.findViewById(R.id.img_empty);
            if (onlyFont){
                txtEmpty.setText(showMsg);
                imgEmpty.setVisibility(View.GONE);
                txtRefresh.setVisibility(View.GONE);
            } else{
                imgEmpty.setVisibility(View.VISIBLE);
                txtRefresh.setVisibility(View.VISIBLE);
                txtRefresh.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        if(null!=listener)
                            listener.onRefresh();
                    }
                });
            }
        }
//        root.removeView(view);
        ((BaseQuickAdapter)root.getAdapter()).setEmptyView(view);
        root.getAdapter().notifyItemChanged(0);


就上面两个layout来回切换就乱了

**Comment by CymChad** [comment]
恩，我看看。

**Comment by CymChad** [comment]
你在这个 if  esle 里面都加一个  root.getAdapter().notifyItemChanged(0); 看看 
```java
if (onlyFont){
txtEmpty.setText(showMsg);
imgEmpty.setVisibility(View.GONE);
txtRefresh.setVisibility(View.GONE);
root.getAdapter().notifyItemChanged(0);
} else{
imgEmpty.setVisibility(View.VISIBLE);
txtRefresh.setVisibility(View.VISIBLE);
root.getAdapter().notifyItemChanged(0);
txtRefresh.setOnClickListener(new View.OnClickListener() {
@Override
public void onClick(View v) {
if(null!=listener)
listener.onRefresh();
}
});
}
```

**Comment by addappcn** [comment]
ok，我试试

**Comment by CymChad** [comment]
恩，记得告诉我结果

**Comment by addappcn** [comment]
嗯，好

**Comment by addappcn** [comment]
还是一样，不行

**Comment by addappcn** [comment]
还是会错乱 你那边可以吗？

**Comment by CymChad** [comment]
我这边是，两个不同的布局每次切换的时候用一下代码，没有共用一个布局。
```java
((BaseQuickAdapter)root.getAdapter()).setEmptyView(view);
root.getAdapter().notifyItemChanged(0);
```

**Comment by CymChad** [comment]
你试试？

**Comment by addappcn** [comment]
ok我把布局稍微改下

**Comment by addappcn** [comment]
还是不可以，布局里控件名称改了也不行
我操作的流程是 进入一个列表  没有数据显示空的view  然后  断网  刷新 显示错误view   然后再刷新显示空的view  再刷新 显示错误view  就这样交替着

**Comment by CymChad** [comment]
我这边看看

**Comment by addappcn** [comment]
嗯，谢谢

**Comment by CymChad** [comment]
我试了试一下，是缓存的问题，需要重新new adapter，然后在setEmptyView

**Comment by addappcn** [comment]
不能再设置setEmptyView的地方去清楚缓存吗？如果重新new  感觉不太合理

**Comment by CymChad** [comment]
目前还没有找到就好的解决方案。我到时候在看看。

**Comment by addappcn** [comment]
ok，谢谢，辛苦了。

**Comment by CymChad** [comment]
你可以在 #77 提个新需求，就说新增全屏异常布局显示。因为之前没考虑到这个问题，只考虑到了空的情况。

**Comment by addappcn** [comment]
嗯
