### ISSUE TITLE
BaseMultiItemQuickAdapter在存在header的情况下，addSubItem失效

### ISSUE THREAD

**Issue by zdxiang** [CymChad/BaseRecyclerViewAdapterHelper#2575]
1当前使用的版本号：2.9.40
重点：我在历史问题中已经找过，并没有存在跟我一样的情况。

问题描述：
关于在adapter存在header的情况下，addSubItem，刷新数据无效的问题。

//这是我进行addSubItem的方法，有效，没有问题的。
 findViewById(R.id.btn_add).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                List<MultiItemEntity> list = mAdapter.getData();
                for (int i = 0; i < list.size(); i++) {
                    if (list.get(i) instanceof GroupEntity) {
                        if (i == 1) {
                            GroupEntity.ChildEntity fuckyou = new GroupEntity.ChildEntity("fuckyou");
                            ((GroupEntity) list.get(i)).addSubItem(fuckyou);
                            mAdapter.collapse(i, false);
                            mAdapter.expandAll();
                        }
                    }
                }
            }
        });

但是，如果adapter.addHeader()。之后，上述方法失效，刷新不了数据。
作者可以自己实践检验下。

**Comment by CymChad** [comment]
收到

**Comment by shichaohui** [comment]
`Adapter#collapse()` 相关源码，position 参数必须包含头布局的数量。
```
/**
 * Collapse an expandable item that has been expanded..
 *
 * @param position the position of the item, which includes the header layout count.
 * @return the number of subItems collapsed.
 */
public int collapse(@IntRange(from = 0) int position, boolean animate) {
    return collapse(position, animate, true);
}
```
直接遍历 data 获取的索引 i，不能直接传递给 collapse，需要加上头布局的数量。
因此正确的 position 不是 i，而是 `i + adapter.getHeaderLayoutCount()` 。
