### ISSUE TITLE
添加二级菜单的指定位置addSubItem(position, subItem);

### ISSUE THREAD

**Issue by easyandroid** [CymChad/BaseRecyclerViewAdapterHelper#2583]
分组拖动，移除后添加 
   int position = holder.getAdapterPosition();
   int parentPosition = getParentPosition(getItem(position));
   Level1Item subItem = new Level1Item("新添加" + position, "");
   ((Level0Item) getData().get(parentPosition)).addSubItem(position, subItem);
   ((Level0Item) getData().get(parentPosition)).getSubItems();
   addData(position + 1, subItem);
position 应该怎么算插入的位置。
在AbstractExpandableItem 里面
    public void addSubItem(int position, T subItem) {
          if (mSubItems != null && position >= 0 && position < mSubItems.size()) {
            mSubItems.add(position, subItem);
          } else {
            addSubItem(subItem);
         }
   }

**Comment by CymChad** [comment]
收到

**Comment by shichaohui** [comment]
由于这个问题提出的比较久了，而且描述的不是很清楚，因此先行关闭。
如果您已经解决该问题，可以在下方回复解决方案。
如果您还有遇到此问题，请参考 #2807 重新提交 Issue 。
