### ISSUE TITLE
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.44.

### ISSUE THREAD

**Issue by weiquanbin** [CymChad/BaseRecyclerViewAdapterHelper#2586]
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.44

**Comment by yangfeng1994** [comment]
兄弟，是不是你的网的问题，或者是你gradle 没有配置好，没办法拉去远程仓库的代码
