### ISSUE TITLE
section布局可不可以在需要的时候动态向一个head添加一个item数据？？

### ISSUE THREAD

**Issue by zhangjf88888** [CymChad/BaseRecyclerViewAdapterHelper#2588]
如题

**Comment by shichaohui** [comment]
分组布局的头 Item 和 内容 Item 保存在一个 List 中，在数据结构上是同级别的，因此如果想要向某一组中添加数据需要知道头 Item 的位置，然后将新的数据添加到头 Item 的后面，下一个头 Item 之间即可。
比如有如下分组：[头1, 内容1, 内容2, 内容3, 头2, 内容4, 内容5]
现在要向分组1的最后添加一条数据（内容6），那么通过遍历找到分组1的最后一个位置插入内容6即可。
[头1, 内容1, 内容2, 内容3, 内容6, 头2, 内容4, 内容5]
