### ISSUE TITLE
对于那种复杂布局穿插显示怎么搞啊，比如五种布局，页面要求显示效果是（顺序为垂直布局）A布局(3个item),B布局（1个item）,A布局（5个），C布局（3个），A(2个)，D（1个），B(2个)，A(5个)，D(2个)，类似复杂布局穿插显示，

### ISSUE THREAD

**Issue by kyriej** [CymChad/BaseRecyclerViewAdapterHelper#2590]
对于那种复杂布局穿插显示怎么搞啊，比如五种布局，页面要求显示效果是（顺序为垂直布局）A布局(3个item),B布局（1个item）,A布局（5个），C布局（3个），A(2个)，D（1个），B(2个)，A(5个)，D(2个)，类似复杂布局穿插显示，

**Comment by AllenCoder** [comment]
1. 可以采用BaseMultiItemQuickAdapter 实现
2. 复杂的电商布局可以参考vlayout 或者 [https://github.com/alibaba/Tangram-Android](https://github.com/alibaba/Tangram-Android)
