### ISSUE TITLE
上拉加载数据时加载的动画不显示

### ISSUE THREAD

**Issue by LazyPangda** [CymChad/BaseRecyclerViewAdapterHelper#2591]
上拉加载功能也都实现了，就是没有加载的loadmoreview，默认不是展示加载动画和加载完毕时的view么。我尝试手动调用了setLoadMoreView(new SimpleLoadMoreView())，还是没有生效。请问一般是什么原因导致呢？

**Comment by YYwishp** [comment]
你是不是重写了下面的这个方法
override fun getItemCount(): Int = data.size

**Comment by YYwishp** [comment]
重写了就有问题

**Comment by CymChad** [comment]
@YYwishp 谢谢你的回答
