### ISSUE TITLE
EmptyView displays error when I invoke 'recyclerView.addItemDecoration()'

### ISSUE THREAD

**Issue by ZMCurry** [CymChad/BaseRecyclerViewAdapterHelper#2594]
@Override
        public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
            super.getItemOffsets(outRect, view, parent, state);
            //itemCount == 1 when I set emptyView on the recyclerView, so emptyView will be influenced by 
            the following statement.
            int itemCount = parent.getAdapter().getItemCount();
            if (parent.getChildLayoutPosition(view) == 0) {
                outRect.left = 5;
            }
            outRect.right = 5;
        }

**Comment by CymChad** [comment]
你可以判断如果是EmptyView就不去addItemDecoration
