### ISSUE TITLE
多级目录展开收起时出现异常

### ISSUE THREAD

**Issue by Marksss** [CymChad/BaseRecyclerViewAdapterHelper#2596]
我写的是3级目录，当第3级目录有相同数据的item且这些item在分布不同的第2级目录下时，收起其中一个2级目录时另一个2级目录中的相同数据的item就漂移，如下图所示：
![gif](https://user-images.githubusercontent.com/8924834/50534293-86134600-0b75-11e9-8b41-f13102d73f1a.gif)
如果没有相同数据的item时则一切正常

**Comment by zhaoxiuyu** [comment]
@Marksss  知道怎么设置 同时只能展开一项吗？

**Comment by AllenCoder** [comment]
已收到pr，review之后已合并
