### ISSUE TITLE
希望能将getRecyclerView设置为public，并且新增removeRecyclerView方法

### ISSUE THREAD

**Issue by q876625596** [CymChad/BaseRecyclerViewAdapterHelper#2598]
因为在某些情况需要复用adapter，但是调用adapter.bindingRecyclerView()方法的时候如果已绑定过recyclerView，那么此时会抛出重复绑定的异常，我无法getRecyclerView()来判断是否已绑定过，也没有解绑recyclerView的方法

**Comment by CymChad** [comment]
收到，你可以添加到我们到需求列表中  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2806 我们会排期修改

**Comment by CymChad** [comment]
重新new 一个adapter也可以
