### ISSUE TITLE
二级列表 怎么设置只能同时展开一项？

### ISSUE THREAD

**Issue by zhaoxiuyu** [CymChad/BaseRecyclerViewAdapterHelper#2599]
用了这个 BaseMultiItemQuickAdapter 分组伸缩栏
展开 调用的这个 expand方法，当我点击其他项的时候也会展开。怎么设置 同时只能展开一项？ 点击另一项的时候，之前展开的自动关闭？

**Comment by huangqiqiang** [comment]
同问   我现在是在外面去控制点击 展开 显示
