### ISSUE TITLE
HeaderView或者FooterView、EmptyView共存情况

### ISSUE THREAD

**Issue by lvtanxi** [CymChad/BaseRecyclerViewAdapterHelper#26]
不知道作者遇见HeaderView与EmptyView或者FooterView与EmptyView或者HeaderView+FooterView与EmptyView共存的情况没有？

**Comment by CymChad** [comment]
没有，你遇到了？可以说一下你的使用场景吗？我好来修改

**Comment by lvtanxi** [comment]
我解决了。但是我还是说一下吧(可能范围比较小)。比如说有一个界面我添加了一个HeaderView但是我的item确实0，这时候需要显示一个EmptyView.这个时候只显示了HeaderView。

**Comment by CymChad** [comment]
当初设计的时候有考虑过这个问题，就是有HeaderView要不要显示EmptyView，这个问题，后来采用了不用显示EmptyView这种做法，你的需求是要这样吗？

**Comment by CymChad** [comment]
如果你有这样的需求，我可以写个重载方法，在设置EmptyView的是否设置一个表示，就是是否与headView共存，你觉得如何？

**Comment by CymChad** [comment]
因为你的需求也同时是大家的需求。

**Comment by lvtanxi** [comment]
也可以。因为我觉得这种情况还是有的吧

**Comment by CymChad** [comment]
今天事有点多，明天给你修改好，改好了，我和你说一下。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.7.2'  新增了我说的那个方法。
