### ISSUE TITLE
快速删除是有问题

### ISSUE THREAD

**Issue by NewHuLe** [CymChad/BaseRecyclerViewAdapterHelper#2602]
使用库版本号：com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.44
使用的布局：ConstraintLayout为根布局，里面就是一个AppCompatTextView与AppCompatImageButton
描述：列表快速点击删除时候有几率造成崩溃，onItemClick中的position有几率返回-1，特别是一直点击第一条postion=0的时候几率会大一点
截图：
![image](https://user-images.githubusercontent.com/6002150/50579711-95023d00-0e82-11e9-91a7-7d0d0ddf0b44.png)

**Comment by CymChad** [comment]
收到，我们验证一下

**Comment by CymChad** [comment]
已修复 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2810
