### ISSUE TITLE
自动加载更多出问题

### ISSUE THREAD

**Issue by wqjuser** [CymChad/BaseRecyclerViewAdapterHelper#2611]
页面类似抖音的首页，每个页面只有一个item，但是每次都会加载10个，滑动到最后一个也没有回调requestLoadMoreListener方法，还是原先的10个造成了数组越界。代码如下
`hotAdapter!!.setEnableLoadMore(true)
        hotAdapter!!.setOnLoadMoreListener({
            mRecyclerHot.postDelayed(kotlinx.coroutines.experimental.Runnable {
                pageNum++
                getDatas()
            }, 1000)

        }, mRecyclerHot)

 @SuppressLint("CheckResult")
    private fun getDatas() {
        operationNo = System.currentTimeMillis().toString()
        NetModule.getInstance().sApi.getIssueListNew(operationNo, null, null, pageNum, 10)
                .compose(RxUtils.io_mainLifeCycleObservable(this))
                .subscribe({
                    if (it.code == 200) {
                        if (it.data!!.isNotEmpty()) {
                            issues.addAll(it.data!!)
                            if (pageNum == 1) {
                                GlobalParams.itemType = issues[0].type
                                GlobalParams.issueId = issues[0].id
                                GlobalParams.pathUrl = issues[0].pathUrl
                            } else {
                                GlobalParams.itemType = issues[hotSmoothScrollToPosition].type
                                GlobalParams.issueId = issues[hotSmoothScrollToPosition].id
                                GlobalParams.pathUrl = issues[hotSmoothScrollToPosition].pathUrl
                            }
                        }
                        if (pageNum == 1) {
                            if (issues.isNotEmpty()) {
                                targetPositionId = issues[0].id
                            }
                            hotAdapter!!.notifyDataSetChanged()
                        } else {
                            hotAdapter!!.notifyItemChanged(issues.size)
                        }

                    } else {
                        toast(it.msg!!)
                    }
//                    if (mSmartRefresh.state == RefreshState.Refreshing) {
//                        mSmartRefresh.finishRefresh()
//                    } else if (mSmartRefresh.state == RefreshState.Loading) {
//                        mSmartRefresh.finishLoadMore()
//                    }
                }, {
                    //                    if (mSmartRefresh.state == RefreshState.Refreshing) {
//                        mSmartRefresh.finishRefresh()
//                    } else if (mSmartRefresh.state == RefreshState.Loading) {
//                        mSmartRefresh.finishLoadMore()
//                    }
                })
    }
`

**Comment by AllenCoder** [comment]
相同问题 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2374](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2374)

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A)

**Comment by o199666** [comment]
解决了没 同问！！！
