### ISSUE TITLE
哥们，你封装的adapter能使用DiffUtis和payload吗？实现局部刷新

### ISSUE THREAD

**Issue by gaoleicoding** [CymChad/BaseRecyclerViewAdapterHelper#2618]
哥们，你封装的adapter能使用DiffUtis和payload吗？实现局部刷新

**Comment by yangfeng1994** [comment]
这个已经开始在做了，可以在issues #2806 里先提一下需求。

**Comment by limuyang2** [comment]
已完成，请等待新版本发布
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2808
