### ISSUE TITLE
盼望加入payload和diffutils的使用，向开源者致敬！

### ISSUE THREAD

**Issue by gaoleicoding** [CymChad/BaseRecyclerViewAdapterHelper#2620]
盼望加入payload和diffutils的使用，向开源者致敬！

**Comment by yangfeng1994** [comment]
这个已经开始在做了，可以在issues #2806 里先提一下需求。

**Comment by limuyang2** [comment]
已完成，请等待新版本发布
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2808
