### ISSUE TITLE
addData bug?

### ISSUE THREAD

**Issue by XiongKe94** [CymChad/BaseRecyclerViewAdapterHelper#2621]
最新版本
当adapter数据为空时，addData()一条数据会自动触发onLoadMoreRequested();
addData()已经设置加载结束了；
能不能不触发呢？

**Comment by XiongKe94** [comment]
只有调用了 setEnableLoadMore(false);才不会触发 ，调用loadMoreEnd(true); 无效

**Comment by XiongKe94** [comment]
查看源码发现是bindViewHolder里面重写加载数据导致 有没有解决方法呢

**Comment by limuyang2** [comment]
addData() 之后马上调用 loadMoreEnd()。
如果问题依然存在，请提供demo。并参照 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2807 提问
