### ISSUE TITLE
分组多布局一点建议

### ISSUE THREAD

**Issue by ZevShiShi** [CymChad/BaseRecyclerViewAdapterHelper#2624]
SectionMultiEntity分组多布局希望组与主item数据可以相互关联，有些应用场景不好使用，比如购物车的正选反选，主体item和组中的选中状态不好控制，也不好扩展

**Comment by ZevShiShi** [comment]
已解决，thks，就是麻烦点

**Comment by QiaoYang0923** [comment]
> 已解决，thks，就是麻烦点

请问您的解决思路是什么
