### ISSUE TITLE
每个section都有header，能否每个section加footer

### ISSUE THREAD

**Issue by kyriej** [CymChad/BaseRecyclerViewAdapterHelper#2629]

**Comment by Yn1025** [comment]
这个有办法解决了吗

**Comment by wotoutengleha** [comment]
同问

**Comment by yangfeng1994** [comment]
你可以在issues #2806  里面提一个需求

**Comment by shichaohui** [comment]
添加新类型的数据到每个 section 的最后就行了。
可以参考多布局分组示例 [SectionMultipleItemUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/SectionMultipleItemUseActivity.java) 实现该功能。
