### ISSUE TITLE
2.0版本,设置点击的背景状态选择无效果

### ISSUE THREAD

**Issue by i25net** [CymChad/BaseRecyclerViewAdapterHelper#263]
我设置了某个Item根据点击变化背景,看不到效果,看了源码,是直接调用了RecyclerView.OnItemTouchListener 

看到
 if (isHeaderOrFooterPosition(vh.getLayoutPosition())) {
                    return false;
                }

那就是没有劫持点击时间呢,但是点击无效果

**Comment by CymChad** [comment]
更新到v2.0.1 即可
