### ISSUE TITLE
Called attach on a child which is not detached

### ISSUE THREAD

**Issue by wystyle1** [CymChad/BaseRecyclerViewAdapterHelper#2634]
复现：你们的官方demo中，将树形Demo ExpandableUseActivity类中构造模拟属性数据generateData方法中增加if (i == 0) continue;必崩。
具体异常：java.lang.IllegalArgumentException: Called attach on a child which is not detached。
修复必要性：树形level=0第一组时候，恰好第一个组没有组员，是很多业务场景。很多业务都是接口配置数据。
临时修复：我也可以通过禁用recycleView的默认动画修复。但是还是希望这个库避免出现这种异常情况

**Comment by CymChad** [comment]
收到，我们验证一下

**Comment by CymChad** [comment]
不知道你说的版本号是多少？
我拉的最新的代码，按照你的方式并没有崩。
![image](https://user-images.githubusercontent.com/7698209/61728783-71fc9380-ada8-11e9-9a71-7a7a45f1daf4.png)
