### ISSUE TITLE
clipChildren 这个属性在这有些问题

### ISSUE THREAD

**Issue by leocreater** [CymChad/BaseRecyclerViewAdapterHelper#2635]
使用的最新版本，46的，配合用的是https://github.com/icetea0822/MessageBubbleView
这个仿qq粘性删除,上面加载的item无法在下面item上使用cliochildren,动画加载不到下面item上，直接穿透了，下面的item反而可以在上面item上自如动画

**Comment by shichaohui** [comment]
这个问题不太好理解啊，过了时间也挺久了。如果您已经解决该问题，可以在下方回复解决方案。如果您还有遇到此问题，请参考 #2807 重新提交 Issue 。

**Comment by shichaohui** [comment]
试了一下这个粘性标签库，确实有问题（拖出当前 Item 就看不到了）。
用 [DragDeleteTextView](https://github.com/shichaohui/DragDeleteTextView) 吧，我试了这个没问题。
