### ISSUE TITLE
IndexOutOfBoundsException(Inconsistency detected. Invalid view holder adapter position)

### ISSUE THREAD

**Issue by qianshengta** [CymChad/BaseRecyclerViewAdapterHelper#2636]
版本是2.9.44。
在加载更多页数据，重新请求数据，并且新的数据条数与原有的不同(主要是新数据比原来的少)，在数组(List)clear之后，添加新数据并且调用loadMoreComplete()刷新会直接奔溃，并且报
**IndexOutOfBoundsException(Inconsistency detected. Invalid view holder adapter position)**
```
  list.clear();
        if (!ListUtils.isEmpty(visitOrderLists))
            list.addAll(visitOrderLists);
        visitOrderAdapter.loadMoreComplete();
```
百度之后得到的信息是，在数组改变后没有及时调用notifyDataSetChanged()，导致外部数组和RecyclerView内部数组不一致了，所以在loadMoreComplete()方法中有调notifyItemChanged(getLoadMoreViewPosition());
去更新数据是就会因为上面说的外部数组和RecyclerView内部数组不一致了直接奔溃。
百度给出的解决方法是在loadMoreComplete()之前调用notifyDataSetChanged()更新内部数组。这个方法是有效的。但是随之而来的问题是，加载动画时界面顶部也会偶尔同时出现动画效果 #2610。这个问题我之前也提过，就是接连调用notifyDataSetChanged()和loadMoreComplete()中的notifyDataSetChanged()会导致加载动画复用的问题，之前这个问题给出的解决方案是去掉notifyDataSetChanged()，但是现在去掉后就会出现现在的问题。

**Comment by qianshengta** [comment]
补充一点。比如说我一页是10条数据，请求完第一页后，加载更多时去请求下一页。但我当前列表里有20条数据，列表下滑到第11条数据可见的时候，这时候用新的10条数据去更新原来的20条数据，就会直接数组溢出奔溃。 
```
//新的十条代替之前的20条
list.clear();
        if (!ListUtils.isEmpty(visitOrderLists))
            list.addAll(visitOrderLists);
        visitOrderAdapter.loadMoreComplete();
```
但是奇怪的是，不管我当前列表里有多少条数据，只要第10条以后的数据不显示在屏幕上，也就是说11条之后的数据(包括11条)还处于屏幕下方不可见，就不会数组溢出奔溃，但是哪怕第11条数据就漏出了个头，你更新数据并且与之前的数组大小不一样就会直接数组溢出奔溃。而这里所说的10条的安全数据，也该是跟我请求过来的数据数组大小有关的。

**Comment by qianshengta** [comment]
@AllenCoder

**Comment by yangfeng1994** [comment]
如果你想把请求来的数据，，替换成新的数据，可以使用setNewData方法，或者replaceData方法

**Comment by qianshengta** [comment]
@yangfeng1994    @CymChad
如果使用setNewData   会在动画上出现问题，比如说我在加载更多的时候会有一个刷新的动画，导致界面会闪烁。在比如说，之前我提过的一个bug是在有动画的情况下，会在界面顶部有一个重复的动画

**Comment by CymChad** [comment]
关于动画问题你可以参考 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2513
