### ISSUE TITLE
NestedScrollView嵌套RecyclerView无法显示上拉加载动画 

### ISSUE THREAD

**Issue by Spikoss** [CymChad/BaseRecyclerViewAdapterHelper#2638]
`   mCarListRv.setLayoutManager(new LinearLayoutManager(this, RecyclerView.VERTICAL, false));
        adapter = new CarListAdapter(null);
        mCarListRv.setAdapter(adapter);
        srCarList.setOnRefreshListener(this);
        mCarListRv.setNestedScrollingEnabled(false);
        adapter.setOnLoadMoreListener(() -> {
        }, mCarListRv);

        scrollView.setOnScrollChangeListener((NestedScrollView.OnScrollChangeListener) (v, scrollX, scrollY, oldScrollX, oldScrollY) -> {
            if (scrollY == (v.getChildAt(0).getMeasuredHeight() - v.getMeasuredHeight())) {
                if(enableLoadMore) {
                    mPresenter.getMoreData(state, vehicleCode);
                }
            }
        });`

`  @Override
    public void getRefreshDataSuccess(List<VehicleListBean> data) {
        adapter.setNewData(data);
        adapter.disableLoadMoreIfNotFullPage();
    }

    @Override
    public void getMoreDataSuccess(List<VehicleListBean> data) {
        enableLoadMore = false;
        if (data.size() != 0) {
            adapter.addData(data);
            adapter.loadMoreComplete();
            enableLoadMore = true;
        } else {
            LogUtil.i("CarListActivity","loadMoreEnd()");
            adapter.loadMoreEnd();
        }
    }`

`     <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/sr_car_list"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <androidx.core.widget.NestedScrollView
        android:id="@+id/scrollView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
 <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:descendantFocusability="blocksDescendants">
            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_car_list"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="5dp" />
            </RelativeLayout>
        </LinearLayout>
    </androidx.core.widget.NestedScrollView>
    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>`

**Comment by Spikoss** [comment]
解决了#2608

**Comment by s8cm** [comment]
NestedScrollView嵌套RecyclerView 无法生效mAnimationAdapter.openLoadAnimation(),
请问如何解决？？
