### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#264]
是不是可以考虑增加一个移除EmptyView的方法。还是有其他方法可以让EmptyView消失

**Comment by CymChad** [comment]
你有什么需求需要这样做？

**Comment by wuzhaohui026** [comment]
我在做搜索页面的时候如果没数据就显示个空布局，有数据就显示数据，但是在换新的搜索条件，清空上一次的搜索结果的时候发现那个空布局还是存在。
另外刚才尝试判断底部是否为空，如果为空就加载底部视图，就出问题了。
if (response.getRes_message().size() == 0) {
                                mAdapter.notifyDataChangedAfterLoadMore(false);
                                if (view ==null) {
                                    view = getActivity().getLayoutInflater().inflate(R.layout.end_loading,
                                            (ViewGroup) recyclerView.getParent(), false);
                                }
                                mAdapter.addFooterView(view);

**Comment by wuzhaohui026** [comment]
对哦，我是在没数据的时候显示的来着。。。就不可能移除掉啊。。哈哈哈。

**Comment by CymChad** [comment]
你有数据就自动没了。。你如果不要你就不设置就好了。
