### ISSUE TITLE
如何删除多条条目?

### ISSUE THREAD

**Issue by liz821** [CymChad/BaseRecyclerViewAdapterHelper#2640]
一次只能删除一个条目吗?
一次删除几个数据集的子条目 notify会报错
通过adapter 循环remove也会报错    不会没考虑多条目删除吧?我注意到有removeRange这个api但是似乎也不是来做条目删除的

**Comment by bananaCaptain** [comment]
同问这个问题，应该怎样解决？谢谢

**Comment by 1109993488** [comment]
1.自己通过删除数据然后notifyDataSetChanged
2.倒序循环remove
以上两种都可实现, 还有问题的话请贴出代码
