### ISSUE TITLE
ERROR: Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46 

### ISSUE THREAD

**Issue by EdminhPeng** [CymChad/BaseRecyclerViewAdapterHelper#2641]
Android Studio在一个library的Module中，引用库，build.gradle文件代码如下
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'

    implementation 'androidx.appcompat:appcompat:1.0.2'

    api 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46'
}
```
在根目录下build.gradle文件中配置：
```
buildscript {
    
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        
    }
}
```
无论如何都gralde一直报错

ERROR: Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46
降低版本也是如此，不引用该BaseRecyclerViewAdapterHelper，就成功了，也参照了其他Issue，还是无法解决

**Comment by AllenCoder** [comment]
参照如下方法使用 [https://jitpack.io/#CymChad/BaseRecyclerViewAdapterHelper/2.9.46](https://jitpack.io/#CymChad/BaseRecyclerViewAdapterHelper/2.9.46)

如果还是拉不下来，检查一下你的本地网络问题

**Comment by getglory** [comment]
需要把maven { url "https://jitpack.io" }这句添加在
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

**Comment by 20074021207** [comment]
> 参照如下方法使用 https://jitpack.io/#CymChad/BaseRecyclerViewAdapterHelper/2.9.46
> 
> 如果还是拉不下来，检查一下你的本地网络问题

改成 https://www.jitpack.io 神奇的就可以
