### ISSUE TITLE
怎么做Banner的无限滚动效果

### ISSUE THREAD

**Issue by oreo** [CymChad/BaseRecyclerViewAdapterHelper#2642]
比如我这样设置，override fun getItemCount()=  Int.MAX_VALUE

convert方法只回调mData.size()次,超出的就不回调了 请问怎么解决啊

**Comment by zijinzhiyun** [comment]
还要重写getItem()和getItemViewType()方法

**Comment by pokerfaceCmy** [comment]
4.+ 版本如何重写getItem方法
