### ISSUE TITLE
调用 Adapter.addHeaderView(stockHeader);后 adapter.getItemViewType(position)获取类型不对

### ISSUE THREAD

**Issue by WFCN** [CymChad/BaseRecyclerViewAdapterHelper#2644]
首先调用  mAdapter.addHeaderView(stockHeader);

在public void onItemChildClick(BaseQuickAdapter adapter, View view, int position){
 adapter.getItemViewType(position) 
}
获取到的类型不正确   需要把position+1  再次获取才对

**Comment by yangfeng1994** [comment]
这个的实现头布局，就相当于多加了一条item，是需要这样获取的

**Comment by yangfeng1994** [comment]
这个的实现头布局，就相当于多加了一种类型的item，position+getHeaderLayoutCount()就行了
