### ISSUE TITLE
单独设置addOnClickListener后第一项和最后一项重复

### ISSUE THREAD

**Issue by gdchnly** [CymChad/BaseRecyclerViewAdapterHelper#2645]
`  @Override`
`protected void convert(BaseViewHolder helper, Item item) {`
`        if (helper.getLayoutPosition() == 0) {`
`            helper.setTextColor(R.id.value, Color.BLUE).addOnClickListener(R.id.value);`
 `       } `
 `       helper.setText(R.id.title, item.title).setText(R.id.value, item.value);`
 `   }`

代码入上所示，结果会使第一项和最后一项字体都变BLUE，并同时都有Click事件。
以上。
求解

**Comment by liz821** [comment]
你这是标准的复用问题啊, 在列标准你设置一个属性的同时都要回置其状态 如你这里
`if (helper.getLayoutPosition() == 0) {`
` helper.setTextColor(R.id.value, Color.BLUE).addOnClickListener(R.id.value);`
` }`
就要写上
else{
helper.setTextColor(R.id.value, Color.BLACK)；
}
