### ISSUE TITLE
貌似从2.9.40以后setOnItemSwipeListener 后onItemSwiped回调pos不对

### ISSUE THREAD

**Issue by ymh8416** [CymChad/BaseRecyclerViewAdapterHelper#2646]
貌似从2.9.40以后setOnItemSwipeListener 后onItemSwiped回调pos不对一直是－1
比如了下区别，之前的版本是先回调pos再通知adapter删除数据，
2.9.40之后都是先通知删除再回调给上层，导致获取的pos不对

**Comment by JasonQS** [comment]
我这也一直是 pos = -1

**Comment by chengkaikk** [comment]
-1

**Comment by xuhaoyang** [comment]
不知道为什么要这么改
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/commit/330346fdfb9eee3284adf107c0ef205bd7a0035b
我觉得这个想法是错的吧
