### ISSUE TITLE
item能否增加一个直接传view的方法？

### ISSUE THREAD

**Issue by isMeiying** [CymChad/BaseRecyclerViewAdapterHelper#2648]
有时候一些需求直接传layoutResId不太能行...望采纳，谢谢

如

>  super(View layoutView, List data);

**Comment by Anzhi-Meiying** [comment]
@AllenCoder

**Comment by Anzhi-Meiying** [comment]
@CymChad 传view会出现 Scrapped or attached views may not be recycled

**Comment by yangfeng1994** [comment]
不太懂，你在adapter的构造方法里可以直接传view   
![image](https://user-images.githubusercontent.com/23312254/61170626-7520a400-a59e-11e9-8984-56126043c7b8.png)

**Comment by isMeiying** [comment]
> 不太懂，你在adapter的构造方法里可以直接传view
> ![image](https://user-images.githubusercontent.com/23312254/61170626-7520a400-a59e-11e9-8984-56126043c7b8.png)

额，好像不可以传 view 类型吧，就是我是通过代码创建的布局然后将他传入 BRVAH 中
