### ISSUE TITLE
recycleview 嵌套recycleview  更改子recycleview  addData  滑动报错

### ISSUE THREAD

**Issue by liang979zhang** [CymChad/BaseRecyclerViewAdapterHelper#2649]
package com.yema.mytestlibrary.adapter

import android.util.Log
import android.widget.LinearLayout
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.chad.library.adapter.base.BaseQuickAdapter
import com.chad.library.adapter.base.BaseViewHolder
import com.yema.mytestlibrary.R
import com.yema.mytestlibrary.weight.ItemInPutClick

/**
 * 回复内容
 */
class CommentAdapter() : BaseQuickAdapter<CommentData, BaseViewHolder>(R.layout.item_comment_mian_layout) {

    lateinit var itemInPutClick: ItemInPutClick
    override fun convert(helper: BaseViewHolder?, item: CommentData?) {
        var replayAdapter = ReplayAdapter()
        var rl_content = helper!!.getView<RecyclerView>(R.id.rl_content)
        rl_content.tag = helper.adapterPosition
        rl_content.layoutManager = LinearLayoutManager(mContext)
        if (rl_content.tag == helper.adapterPosition) {
            rl_content.adapter = replayAdapter
        }

        replayAdapter.setNewData(item!!.getStrings().subList(0, 3))
        if (replayAdapter.data.size > 2) {
            helper!!.setVisible(R.id.ll_replay_show, true)
            helper!!.setVisible(R.id.ll_contene_hint, true)

        } else {
            helper!!.setVisible(R.id.ll_replay_show, false)
        }

        replayAdapter.setOnItemClickListener { adapter, view, position ->

            Log.e("tag", "")

//            itemInPutClick.itemClick(adapter)

            adapter.addData(2,ReplayMultipleItem(2, "asdasdasdasd是大大说", "我", "他"))

        }

        helper.getView<LinearLayout>(R.id.ll_replay_show).setOnClickListener {
            item.isIsshow = !item.isshow
            if (item.isshow) {
                helper.setVisible(R.id.ll_contene_hint, item.isshow)
                helper!!.setVisible(R.id.ll_replay_show, !item.isIsshow)

                if (rl_content.tag == helper.adapterPosition) {
                    replayAdapter.setNewData(item!!.getStrings())
                }

            }

        }
        helper.getView<LinearLayout>(R.id.ll_contene_hint).setOnClickListener {
            if (item.isshow) {
                helper!!.setVisible(R.id.ll_replay_show, item.isIsshow)
                helper.setVisible(R.id.ll_contene_hint, !item.isshow)
                if (rl_content.tag == helper.adapterPosition) {
                    replayAdapter.setNewData(item!!.getStrings().subList(0, 3))
                }

            }

        }
        helper.setVisible(R.id.ll_contene_hint, item.isshow)
    }

    fun setInputClick(itemInPutClick: ItemInPutClick) {
        this.itemInPutClick = itemInPutClick
    }
}

package com.yema.mytestlibrary.adapter

import com.chad.library.adapter.base.BaseMultiItemQuickAdapter
import com.chad.library.adapter.base.BaseViewHolder
import com.yema.mytestlibrary.MySpannableString
import com.yema.mytestlibrary.R

/**
 * 回复adapter
 */
class ReplayAdapter : BaseMultiItemQuickAdapter<ReplayMultipleItem, BaseViewHolder> {
    override fun convert(helper: BaseViewHolder?, item: ReplayMultipleItem?) {
        when (helper!!.itemViewType) {
            ReplayMultipleItem.NORME -> {
                val content1 = MySpannableString(mContext, "${item!!.responde}:  ${item.content}")
                        .first("${item.responde}:").size2(28).textColor(R.color.colorAccent)
                        .first(item.content).size2(28).textColor(R.color.blue)
                helper.setText(R.id.tv_repla_nor, content1)

            }
            ReplayMultipleItem.TOMMAIN -> {
                val content1 = MySpannableString(mContext, "${item!!.responde} 回复${item.replied}:  ${item.content}")
                        .first(item.responde).size2(28).textColor(R.color.colorAccent)
                        .first("回复").size2(28).textColor(R.color.c606060)
                        .first(item.replied).size2(28).textColor(R.color.colorPrimary)
                        .first(item.content).size2(28).textColor(R.color.blue)
                helper.setText(R.id.tv_repla_to, content1)
            }
        }
    }

    constructor() : super(null) {
        addItemType(ReplayMultipleItem.NORME, R.layout.itme_replay_layout)
        addItemType(ReplayMultipleItem.TOMMAIN, R.layout.itme_a_replay_b_layout)
    }

}

在  adapter.addData(2,ReplayMultipleItem(2, "asdasdasdasd是大大说", "我", "他"))  时滑动时报:
      java.util.ConcurrentModificationException
        at java.util.AbstractList$SubAbstractList.size(AbstractList.java:360)
        at com.chad.library.adapter.base.BaseQuickAdapter.getItemCount(BaseQuickAdapter.java:700)
        at androidx.recyclerview.widget.GapWorker$LayoutPrefetchRegistryImpl.collectPrefetchPositionsFromView(GapWorker.java:90)
        at androidx.recyclerview.widget.GapWorker.prefetchInnerRecyclerViewWithDeadline(GapWorker.java:323)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:349)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5564)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by Git-lyz** [comment]
这个问题解决吗

**Comment by animus198656** [comment]
这问题怎么解决的？

**Comment by royorange** [comment]
注意不要随意增加删除内部recyclerview的list内数据，否则会在遍历时出错。
内部可以新建list引用

**Comment by VliceZ** [comment]
@lyzqw @animus198656 请问有解决吗

**Comment by lichenchenisapuppy** [comment]
> @lyzqw @animus198656 请问有解决吗
 
我用的版本是2.9.50   setNewData可以
