### ISSUE TITLE
setNewData should not control loadMore action

### ISSUE THREAD

**Issue by jasonni** [CymChad/BaseRecyclerViewAdapterHelper#265]
LoadMore enable here just a little strange if I call **loadMoreComplete** befor **setNewData**,
It's hard to control loadMore action by myself. 

I think these methods should not be disturb by each of them.

[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/library/src/main/java/com/chad/library/adapter/base/BaseQuickAdapter.java#L214](url)

**Comment by CymChad** [comment]
Received your proposal, the subsequent will improve, thank you
