### ISSUE TITLE
使用需要翻墙么？为什么提示找不到这个版本？

### ISSUE THREAD

**Issue by yangqi1993** [CymChad/BaseRecyclerViewAdapterHelper#266]
Error:(92, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.8
<a href="openFile:E:/Apk_Bag/265g/265g_warehouse/zs265g_svn_temp/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by githubzaibao** [comment]
Do you have to add the configuration information jitpack warehouse in build.gradle profile?
先在 build.gradle(Project:XXXX) 的 repositories 添加:

    allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
