### ISSUE TITLE
实现拖拽功能时，其中一个条目是recyclerview，这个条目就不能拖拽了

### ISSUE THREAD

**Issue by yangshibai** [CymChad/BaseRecyclerViewAdapterHelper#2662]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by shichaohui** [comment]
不要直接用 RecyclerView 作为 ItemView，用其他的 ViewGroup 包裹 RecyclerView ，如 FrameLayout 。

**Comment by lhj1079947827** [comment]
请问你解决了这个问题了吗，就是Itemview中有RecyclerView点击内层RecyclerView不能拖拽的问题

**Comment by yangshibai** [comment]
> 请问你解决了这个问题了吗，就是Itemview中有RecyclerView点击内层RecyclerView不能拖拽的问题

我后面没有嵌套recyclerView了，我这个条目改成动态加载布局了，可以实现拖拽。上面说的 （不要直接用 RecyclerView 作为 ItemView，用其他的 ViewGroup 包裹 RecyclerView ，如 FrameLayout ） 这个方案后面我没有试过，你可以试下。

**Comment by lhj1079947827** [comment]
使用了他说的在RecyclerView在外层加一个ViewGroup 包裹也是不管用，点击了内层的RecyclerView也是不能拖拽

**Comment by yangshibai** [comment]
> 使用了他说的在RecyclerView在外层加一个ViewGroup 包裹也是不管用，点击了内层的RecyclerView也是不能拖拽

那你可以尝试下我的方法，这个条目动态加载布局，我这边用这种方式是可以拖拽的

**Comment by lhj1079947827** [comment]
怎么个动态方法？能放出关键代码来看下吗？

**Comment by yangshibai** [comment]
> 怎么个动态方法？能放出关键代码来看下吗？

最外层就是一个普通的ViewGroup，如LinearLayout，然后再调用addView()方法就可以了，这个应该是比较基础的内容吧，可以找些文章博客啥的看下，应该很多的。

**Comment by lhj1079947827** [comment]
不会造成卡顿吗？复用的时候?每次复用都是自动去生成？

**Comment by lhj1079947827** [comment]
你的只是一个是嘛？我的情况是多个，可能复用的时候每次都是去自动生成可能会造成卡顿了

**Comment by yangshibai** [comment]
> 你的只是一个是嘛？我的情况是多个，可能复用的时候每次都是去自动生成可能会造成卡顿了

addView()之前需要先调用removeAllViews()方法，我的肯定也是多个啊，一个还需要嵌套RecyclerView干啥啊，我这七八个吧，没有卡顿。

**Comment by lhj1079947827** [comment]
谢谢了啊

**Comment by yangshibai** [comment]
> 谢谢了啊

应该的，多多交流

**Comment by shichaohui** [comment]
这个问题的原因是触摸事件被子 RecyclerView 拦截了。
处理方式有很多种，这是其中一种：

@Override
protected void convert(@NonNull final BaseViewHolder helper, String item) {
    ...
    RecyclerView rcv = helper.getView(R.id.rcv);
    rcv.setOnTouchListener(new View.OnTouchListener() {
        @Override
        public boolean onTouch(View v, MotionEvent event) {
            // 把触摸事件交给父 RecyclerView 的 Item 处理
            return helper.itemView.onTouchEvent(event);
        }
    });
    rcv.setLayoutManager(new LinearLayoutManager(rcv.getContext()));
    rcv.setAdapter(childAdapter);
}

**Comment by yangshibai** [comment]
> 这个问题的原因是触摸事件被子 RecyclerView 拦截了。
> 处理方式有很多种，这是其中一种：
> 
> ```java
> @Override
> protected void convert(@NonNull final BaseViewHolder helper, String item) {
>     ...
>     RecyclerView rcv = helper.getView(R.id.rcv);
>     rcv.setOnTouchListener(new View.OnTouchListener() {
>         @Override
>         public boolean onTouch(View v, MotionEvent event) {
>             // 把触摸事件交给父 RecyclerView 的 Item 处理
>             return helper.itemView.onTouchEvent(event);
>         }
>     });
>     rcv.setLayoutManager(new LinearLayoutManager(rcv.getContext()));
>     rcv.setAdapter(childAdapter);
> }
> ```

是的，如果不需要考虑子RecyclerView的点击事件响应的话这样是可以的，我的需求是因为又有拖拽又需要响应子Item的点击事件所以没用到这种方式了

**Comment by shichaohui** [comment]
@yangshibai 嗯，这是 Adapter 的一个 bug，后面的版本会修复。
