### ISSUE TITLE
recyclerview横向布局的时候添加headview，设置固定宽度的headview,运行起来却是占满一屏。

### ISSUE THREAD

**Issue by chao9267** [CymChad/BaseRecyclerViewAdapterHelper#2667]
recyclerview横向布局的时候添加headview，设置固定宽度的headview,运行起来却是占满一屏。

设置横向布局 recyclerview设置match_parent,
mRecyclerviewPhoto.setLayoutManager(new LinearLayoutManager(getApplicationContext(), LinearLayoutManager.HORIZONTAL, false));
 
自定义的headerview我设置90dp的宽度
   myPhotoAdapter.addHeaderView(View.inflate(getApplicationContext(), R.layout.header_vperson_photo, null));

运行起来   headerview却是match_parent

**Comment by songsongtao** [comment]
和你一样的问题，我看了库的代码，重写了layoutparam导致的原本的宽高设置无效

**Comment by chao9267** [comment]
> 和你一样的问题，我看了库的代码，重写了layoutparam导致的原本的宽高设置无效

你解决了没有？

**Comment by chao9267** [comment]
mAdapter.addFooterView(view,-1,LinearLayout.HORIZONTAL);   
 addfooterview有一个重载方法，要设置footerview的方向为horizontal才会使wrap_content生效

**Comment by Rianney** [comment]
我试过一个TextView没有ViewGroup会导致铺满, 但为TextView设置ViewGroup之后就不会了

**Comment by xilost** [comment]
@chao9267 正解

**Comment by hugang1122** [comment]
holder.recyclerview.adapter = OrderImageAdapter( image,  ordernumber).apply {
            addFooterView(View(mContext),-1,LinearLayout.HORIZONTAL)
            addFooterView(LayoutInflater.from(mContext).inflate(R.layout.item_order_image,null))
        }
@chao9267 正解

**Comment by CLZ666** [comment]
@chao9267 对的，点赞
