### ISSUE TITLE
分组树形列表，初次加载时能展开指定的分组吗？

### ISSUE THREAD

**Issue by lihuiqiang123** [CymChad/BaseRecyclerViewAdapterHelper#2668]
分组树形列表，初次加载时能展开指定的分组吗？

**Comment by shichaohui** [comment]
使用 adapter.expand(position) 即可展开指定分组。
但是要注意，当展开一个分组后， 该分组后面的 Item 的 position 会发生变化（因为分组展开和收缩是基于添加和删除数据的）。
