### ISSUE TITLE
使用BaseQuickAdapter添加头布局如果列表数据为空,导致头布局不显示

### ISSUE THREAD

**Issue by feisher** [CymChad/BaseRecyclerViewAdapterHelper#2670]
使用BaseQuickAdapter添加头布局如果列表数据为空,导致头布局不显示，，暂时使用BaseMultiItemQuickAdapter解决的，但是无法处理列表无数据的显示

**Comment by gfeng567** [comment]
adapter.setHeaderAndEmpty(true);

**Comment by CymChad** [comment]
@gfeng567 感谢你的回复
