### ISSUE TITLE
加载更多和没有更多数据，分割线问题

### ISSUE THREAD

**Issue by songsongtao** [CymChad/BaseRecyclerViewAdapterHelper#2672]
1. 当前使用的版本号
2.9.46
 mRv.addItemDecoration(new android.support.v7.widget.DividerItemDecoration(this,LinearLayoutManager.VERTICAL));
2. 复现操作描述
添加了分割线上拉刷新，显示正在加载会有分割线，很丑

**Comment by imgod1** [comment]
同样遇到这个问题...但是看来没人理睬啊...

**Comment by songsongtao** [comment]
自定义分割线,最后一个childView不绘制分割线来规避这个问题
我也是这样处理了的，但是没用正在加载，切换到没有更多数据之间还是又分割线，然后显示没有更多又消失掉

**Comment by songsongtao** [comment]
@Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
        if (dividerDrawable == null) {
            return;
        }

        if (parent.getChildLayoutPosition(view) < 1) {
            return;
        }
已解决

**Comment by songsongtao** [comment]
//再这个方法中绘制
 public void onDrawOver(Canvas c, RecyclerView parent, RecyclerView.State state) {
}
