### ISSUE TITLE
分组问题

### ISSUE THREAD

**Issue by CPLASF1925** [CymChad/BaseRecyclerViewAdapterHelper#2673]
如何实现分组加载更多，类似支付宝账单那样，刷新得到的数据可能是上一个分组的，也可能是新的分组，数据该如何处理？

**Comment by yangfeng1994** [comment]
你可以在issues #2806 提个需求

**Comment by shichaohui** [comment]
分组的数据是一个 List，头和内容平级，根本不需要考虑加载到的新数据是否是一个新的分组，直接添加就行，其关键在与你的数据，与 Adapter 没什么关系。
比如：
现有数据 [头1, 2, 3, 4, 头2, 5, 6]
加载得到新数据 [7, 8, 头3, 9, 10]
直接将新数据添加到现有数据列表就行，得到 [头1, 2, 3, 4, 头2, 5, 6, 7, 8, 头3, 9, 10]
再次加载新数据 [头4, 11, 12, 13]
新数据添加到现有数据列表得到 [头1, 2, 3, 4, 头2, 5, 6, 7, 8, 头3, 9, 10, 头4, 11, 12, 13]
