### ISSUE TITLE
BaseMultiItemQuickAdapter子View点击事件无效？

### ISSUE THREAD

**Issue by RockyQu** [CymChad/BaseRecyclerViewAdapterHelper#2674]
public class MainAdapter extends BaseMultiItemQuickAdapter<MainType, BaseViewHolder> {

    private Context context;

    public MainAdapter(Context context, List<MainType> data) {
        super(data);

        this.context = context;

        addItemType(MainType.INTRODUCTION, R.layout.item_main_introduction);
        addItemType(MainType.MUSEUM, R.layout.item_main_museum);
    }

    @Override
    protected void convert(BaseViewHolder helper, MainType item) {
        switch (helper.getItemViewType()) {
            case MainType.INTRODUCTION:
                helper.addOnClickListener(R.id.item_introduction_museum);
                helper.addOnClickListener(R.id.item_introduction_traffic);
                helper.addOnClickListener(R.id.item_introduction_time);
                helper.addOnClickListener(R.id.item_introduction_contact);
                helper.addOnClickListener(R.id.item_introduction_reservation);
                helper.addOnClickListener(R.id.item_introduction_notice);
                break;
            case MainType.MUSEUM:

                break;
        }
    }
}

mainAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {

            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                int itemType = adapter.getItemViewType(position);
                Logg.e("itemType "+itemType);
                switch (itemType) {
                    case MainType.INTRODUCTION:
                        switch (view.getId()) {
                            case 11:// 场馆介绍
                                Logg.e("1");
                                break;
                            case 12:
                                Logg.e("2");
                                break;
                            case R.id.item_introduction_time:

                                break;
                            case R.id.item_introduction_contact:

                                break;
                            case R.id.item_introduction_reservation:

                                break;
                            case R.id.item_introduction_notice:

                                break;
                        }
                        break;
                    case MainType.MUSEUM:

                        break;
                }
            }
        });

**Comment by RockyQu** [comment]
点击子View会返回onItemChildClick 方法，但是log itemType 273 是为什么

**Comment by RockyQu** [comment]
MainType 代码如下

class MainType implements MultiItemEntity {

    public static final int INTRODUCTION = 1;
    public static final int MUSEUM = 2;

    private int mainType;

    public MainType(int mainType) {
        this.mainType = mainType;
    }

    @Override
    public int getItemType() {
        return mainType;
    }
}

**Comment by RockyQu** [comment]
发现去掉 addHeaderView 就没问题了这是什么？

**Comment by kris-liutao** [comment]
@RockyQu 你好   我遇到和你这个一样的问题  多布局的item的子view点击事件无效  你是怎么解决的呢

**Comment by RockyQu** [comment]
@kris-liutao 添加 addHeaderView 后 adapter.getItemViewType(position) 要加1，也就是 adapter.getItemViewType(position+1) 可正确了

**Comment by RockyQu** [comment]
@kris-liutao 添加 addHeaderView 后 adapter.getItemViewType(position) 要加1，也就是 adapter.getItemViewType(position+1) 就正确了

**Comment by kris-liutao** [comment]
@RockyQu   好的呢  万分感谢
