### ISSUE TITLE
二次事件绑定第一次不响应，第二次绑定后才响应

### ISSUE THREAD

**Issue by zuojianjian** [CymChad/BaseRecyclerViewAdapterHelper#2675]
事件绑定如下图：
![微信截图_20190312181511](https://user-images.githubusercontent.com/20851340/54193425-00a4fe00-44f5-11e9-8cb2-fdf105a02fc0.png)
![微信截图_20190312181601](https://user-images.githubusercontent.com/20851340/54193435-0a2e6600-44f5-11e9-823a-2205f2854499.png)
表现如下：第一次点击togglebutton不响应事件监听，第二次点击响应！原因是第一次点击的时候事件还没绑定吗？该如何避免这种情况出现

**Comment by 972223177** [comment]
我也是这样。大哥你解决了吗

**Comment by Bleach1** [comment]
同问

**Comment by CymChad** [comment]
无法复现，请参考demo
