### ISSUE TITLE
这个框架太多过度绘制了吧

### ISSUE THREAD

**Issue by luoyincheng** [CymChad/BaseRecyclerViewAdapterHelper#2676]
![Screenshot_20190313-104820](https://user-images.githubusercontent.com/37969236/54250251-f67b1200-457d-11e9-8431-b2111caa1aa7.jpg)

**Comment by luoyincheng** [comment]
![Screenshot_20190313-104820](https://user-images.githubusercontent.com/37969236/54250279-1ca0b200-457e-11e9-87e5-2d10ccff2dd1.jpg)

**Comment by liangxiwei** [comment]
你这是怎么做得到的。。。请上代码

**Comment by luoyincheng** [comment]
@liangxiwei 没做别的  只是把activity和根布局的背景去掉，再手机里打开开发者模式里面的查看过度绘制而已

**Comment by CSnowStack** [comment]
@luoyincheng ,这不是框架的问题,你布局的问题

**Comment by luoyincheng** [comment]
@CSnowStack 我去掉了所有可能的过度绘制表现就是这样,这是性能最好的布局方式了,没问题的

**Comment by CSnowStack** [comment]
@luoyincheng 你随便留一个activity或根布局的背景，再看一下布局层级

**Comment by luoyincheng** [comment]
为什么留背景？我用其他的控件，同样不留背景，就不会有这个过度绘制，这个怎么回事？

**Comment by CSnowStack** [comment]
只要acitivty没有背景,没设置透明主题,布局有空隙,能和之前的activity重合,就会出现这种情况

**Comment by amosxb** [comment]
很明显  是你自己写的代码有问题嘛，自己找问题啊，实在不行再提issue。  感觉你就是一出这问题就来提issue

**Comment by ningning21** [comment]
这个issue把大火都逗乐了

**Comment by AllenCoder** [comment]
框架没有在布局上做任何黑箱操作，布局过度绘制，请检查你的itemview和activity的layout是否存在过度布局
