### ISSUE TITLE
用这个适配器实现2级列表存在BUG

### ISSUE THREAD

**Issue by nickyhuang2607** [CymChad/BaseRecyclerViewAdapterHelper#2677]
如果数据中存在重复ID的数据，那么收缩会出现BUG 具体是在recursiveCollapse(int)这个函数内部的位置获取getItemPosition()  例如A组内有一个数据a1 ，B组内也有一个数据a1，那么收缩B组，此时找到的位置是A组中的a1,从而造成数据错乱

**Comment by franticn** [comment]
同样的问题，今天也发现了

**Comment by dengpan20** [comment]
我也是出现了

**Comment by nickyhuang2607** [comment]
> 我也是出现了

其实想解决也容易，在childItem的实体类里加入groupId,然后重写它的equals方法即可

**Comment by MagicKim** [comment]
> > 我也是出现了
> 
> 其实想解决也容易，在childItem的实体类里加入groupId,然后重写它的equals方法即可

帮忙贴一下解决的代码，到时候遇到这个问题就好解决了。
