### ISSUE TITLE
截图产生的问题

### ISSUE THREAD

**Issue by RXlung** [CymChad/BaseRecyclerViewAdapterHelper#2678]
查找到了#1318 的 相关问题，但是没有尝试出解决方法；
我尝试了使用2.9.25版本，也没有解决
问题：RecyclerView截图 关于位置的全是-1；
![image](https://user-images.githubusercontent.com/21995371/54257661-ffc6a780-459a-11e9-8ef6-22dcf004bfc9.png)
手机上显示是正常的序号。

**Comment by TylerWang1110** [comment]
你好, 请问你这个问题解决了么?

**Comment by TylerWang1110** [comment]
> 查找到了#1318 的 相关问题，但是没有尝试出解决方法；
> 我尝试了使用2.9.25版本，也没有解决
> 问题：RecyclerView截图 关于位置的全是-1；
> ![image](https://user-images.githubusercontent.com/21995371/54257661-ffc6a780-459a-11e9-8ef6-22dcf004bfc9.png)
> 手机上显示是正常的序号。

你好, 请问你这个问题解决了么?

**Comment by RXlung** [comment]
没有解决，因为我的item不多，最后直接生成item的bitmap拼接做的。

**Comment by TylerWang1110** [comment]
> 没有解决，因为我的item不多，最后直接生成item的bitmap拼接做的。

我使用最新版2.9.46 可以了, 我的item太多了
