### ISSUE TITLE
onLoadMoreRequested接口为什么会默认就执行？

### ISSUE THREAD

**Issue by 13588823551** [CymChad/BaseRecyclerViewAdapterHelper#268]
PullToRefreshUserActivity类中onLoadMoreRequest的方法改为如下，当activity启动时默认就会调用这个方法，怎么样能让他不默认执行？
`@Override
    public void onLoadMoreRequested() {
        mRecyclerView.post(new Runnable() {
            @Override
            public void run() {
                if (mCurrentCounter >= TOTAL_COUNTER) {
                    mQuickAdapter.loadComplete();
                    if (notLoadingView == null) {
                        notLoadingView = getLayoutInflater().inflate(R.layout.not_loading, (ViewGroup) mRecyclerView.getParent(), false);
                    }
                    mQuickAdapter.addFooterView(notLoadingView);
                } else {
            
                        new Handler().postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                mQuickAdapter.addData(DataServer.getSampleData(PAGE_SIZE));
                                mCurrentCounter = mQuickAdapter.getData().size();
                            }
                        }, delayMillis);
                    
                }
            }

        });
    }`

**Comment by CymChad** [comment]
设置pageSize 一个屏幕的数量   使用  openLoadMore方法来设置

**Comment by 13588823551** [comment]
openLoadMore  这个方法需要什么时候调用呢？ 我是想让列表滑到最下面才执行加载

**Comment by CymChad** [comment]
一开始就设置就好了。

**Comment by CymChad** [comment]
设置监听的时候设置，设置一个页的数量，这样滑到这个数量就会调用onLoadMoreRequested

**Comment by 13588823551** [comment]
那我在获取数据之后，openLoadMore(data.size())  这样是不行的对吧？
