### ISSUE TITLE
BaseMultiItemQuickAdapter使用的时候，二级布局的内容一致的问题

### ISSUE THREAD

**Issue by liuyifang1121** [CymChad/BaseRecyclerViewAdapterHelper#2680]
1. 当前使用的版本号：2.9.46
2. 复现操作描述：数据按照一二级数据要求继承，最后出现在使用adapter.expandAll()展开全部方法时，二级数据不同的item数据拼装后数据变成一致的问题。跟踪断点发现BaseQuickAdapter类中如下代码：
```
if (!expandable.isExpanded()) {
            List list = expandable.getSubItems();
            mData.addAll(position + 1, list);
            subItemCount += recursiveExpand(position + 1, list);

            expandable.setExpanded(true);
//            subItemCount += list.size();
        }
```
，此处代码的 List list = expandable.getSubItems()返回的list中的元素数据相同，而expandable中的subitems数据是正确的。谢谢

不知道是不是数据结构的原因，以下是我的数据：
```
class YyglOneBean extends AbstractExpandableItem<YyglOneItemBean> implements MultiItemEntity {

    private String patron_id;
    private String patron_name;
    private String photo;
    private int yu_num;
    private List<YyglOneItemBean> yu_info;
}
```

**Comment by liuyifang1121** [comment]
> 1. 当前使用的版本号：2.9.46
> 2. 复现操作描述：数据按照一二级数据要求继承，最后出现在使用adapter.expandAll()展开全部方法时，二级数据不同的item数据拼装后数据变成一致的问题。跟踪断点发现BaseQuickAdapter类中如下代码：
```
>    `if (!expandable.isExpanded()) {
>    List list = expandable.getSubItems();
>    mData.addAll(position + 1, list);
>    subItemCount += recursiveExpand(position + 1, list);
>    ```
>         expandable.setExpanded(true);
>    ```
> 
> // subItemCount += list.size();
> }`
```，此处代码的 List list = expandable.getSubItems()返回的list中的元素数据相同，而expandable中的subitems数据是正确的。谢谢

**Comment by liuyifang1121** [comment]
> > 1. 当前使用的版本号：2.9.46
> > 2. 复现操作描述：数据按照一二级数据要求继承，最后出现在使用adapter.expandAll()展开全部方法时，二级数据不同的item数据拼装后数据变成一致的问题。跟踪断点发现BaseQuickAdapter类中如下代码：
if (!expandable.isExpanded()) {
    List list = expandable.getSubItems();
    mData.addAll(position + 1, list);
    subItemCount += recursiveExpand(position + 1, list);
    expandable.setExpanded(true);
 // subItemCount += list.size();
 }
，此处代码的 List list = expandable.getSubItems()返回的list中的元素数据相同，而expandable中的subitems数据是正确的。谢谢
> ```

**Comment by liuyifang1121** [comment]
抱歉打扰了，是我一个地方写错了。😭

**Comment by MagicKim** [comment]
> 抱歉打扰了，是我一个地方写错了。😭

问一下，在多布局里面可以加入可以折叠的布局吗？
