### ISSUE TITLE
父节点位置

### ISSUE THREAD

**Issue by jobscolin** [CymChad/BaseRecyclerViewAdapterHelper#2684]
需求：通过子节点同时获取父节点的位置(父节点不是相对于总列表的位置)
BaseMultiItemQuickAdapter下只看到2个方法获取父节点的位置，getParentPositionInAll和getParentPosition这两个方法只能获取到父节点位于suo'y

**Comment by LiQinglin007** [comment]
除了自己计算，有没有比较好的方式能拿到父类的pos和子类的pos?
