### ISSUE TITLE
树状列表的一个问题

### ISSUE THREAD

**Issue by jobscolin** [CymChad/BaseRecyclerViewAdapterHelper#2685]
现在获取的父节点是相对于总量的位置，如何获取父节点相对于父节点的排序（既父节点是0，1，2这样的排序）

**Comment by shichaohui** [comment]
方法 1. 遍历 Adapter 中的数据计算位置。
方法 2. 自行保存列表的备份，使用 list.indexOf() 获取位置。
若有更好的方法请在下方回复。
