### ISSUE TITLE
ClassCastException 使用的版本是2.9.46 release包报错

### ISSUE THREAD

**Issue by 13715001591** [CymChad/BaseRecyclerViewAdapterHelper#2688]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.hqcd.adapter.MyBaseViewHolder
报错的话就是ClassCastException 我debug没有一点问题 release包就疯狂报错 关闭混淆就没有问题了
混淆的代码是这个
`-keep class com.chad.library.adapter.** {
*;
}
-keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter
-keep public class * extends com.chad.library.adapter.base.BaseViewHolder
-keepclassmembers  class **$** extends com.chad.library.adapter.base.BaseViewHolder {
     <init>(...);
}
`
这是MyBaseViewHolder  的代码
`public class MyBaseViewHolder extends BaseViewHolder {

    public MyBaseViewHolder(View view) {
        super(view);
    }

    public MyBaseViewHolder setImageByUrl(@IdRes int viewId, String url) {
        ImageView view = getView(viewId);
        if (TextUtils.isEmpty(url)) url = "";
        if (!url.startsWith(Const.PICTURE_URL)) url = Const.PICTURE_URL + url;
        Glide.with(view.getContext()).load(url)
                .placeholder(R.drawable.default_error)
                .error(R.drawable.default_error)
                .skipMemoryCache(false)
                .dontAnimate()
                .into(view);
        return this;
    }

    public MyBaseViewHolder setLocalImage(@IdRes int viewId, String path) {
        ImageView view = getView(viewId);
        if (TextUtils.isEmpty(path)) path = "";
        Glide.with(view.getContext()).load(new File(path)).error(R.drawable.default_error)
                .into(view);
        return this;
    }

    public MyBaseViewHolder setHeadByUrl(@IdRes int viewId, String url) {
        ImageView view = getView(viewId);
        if (TextUtils.isEmpty(url)) url = "";
        if (!url.startsWith(Const.PICTURE_URL)) url = Const.PICTURE_URL + url;
        Glide.with(view.getContext()).load(url)
                .placeholder(R.drawable.default_head)
                .error(R.drawable.default_head)
                .skipMemoryCache(false)
                .dontAnimate()
                .into(view);
        return this;
    }
    public MyBaseViewHolder setText(@IdRes int viewId, CharSequence value) {
        TextView view = getView(viewId);
        view.setText(value);
        return this;
    }
    public MyBaseViewHolder setGone(@IdRes int viewId, boolean visible) {
        View view = getView(viewId);
        view.setVisibility(visible ? View.VISIBLE : View.GONE);
        return this;
    }

    /**
     * Set a view visibility to VISIBLE (true) or INVISIBLE (false).
     *
     * @param viewId  The view id.
     * @param visible True for VISIBLE, false for INVISIBLE.
     * @return The BaseViewHolder for chaining.
     */
    public MyBaseViewHolder setVisible(@IdRes int viewId, boolean visible) {
        View view = getView(viewId);
        view.setVisibility(visible ? View.VISIBLE : View.INVISIBLE);
        return this;
    }

}`

这里是adapter的代码

`public class ExhibitionAdapter extends BaseQuickAdapter<ExhibitionEntity,MyBaseViewHolder> {
    public ExhibitionAdapter(int layoutResId, @Nullable List<ExhibitionEntity> data) {
        super(layoutResId, data);
    }

    @Override
    protected void convert(MyBaseViewHolder helper, ExhibitionEntity item) {
        helper.setImageByUrl(R.id.iv_my_pub,  item.getPicture())
                .setText(R.id.tv_item_my_pub_2, item.getCreateTime())
                .setText(R.id.tv_my_pub_1, item.getTitle())
                .setText(R.id.tv_my_pub_comment_num, item.getCommentCount() + "")
                .setText(R.id.tv_my_pub_browse, item.getReadCount() + "");
    }
}
`

**Comment by shuaisong** [comment]
同样遇到这个问题
 java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.qybm.zhy.adapter.QuickViewHolder 
请大哥分享下混淆设置

**Comment by shuaisong** [comment]
问题解决

-keep class com.chad.library.adapter.** {
*;
}
-keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter
-keep public class * extends com.chad.library.adapter.base.BaseViewHolder
-keepclassmembers  class **$** extends com.chad.library.adapter.base.BaseViewHolder {
     <init>(...);
}
-keepclassmembers class * extends com.chad.library.adapter.base.BaseViewHolder { <init>(...); }

**Comment by tongruijun8** [comment]
同样的问题，混淆后就报这个错误了（java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to ……），求解？

**Comment by CymChad** [comment]
![](https://user-images.githubusercontent.com/7698209/61293330-047bc080-a806-11e9-9b72-1e6cc00691f2.png)
@tongruijun8 你试一下z这个方法
