### ISSUE TITLE
在使用diffutils局部更新数据时，mData更新但不需要notifyDataSetChanged

### ISSUE THREAD

**Issue by wanghl2015** [CymChad/BaseRecyclerViewAdapterHelper#2690]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by limuyang2** [comment]
自行在adapter中添加个方法就像了，例如：
`fun setDiffList(list: List<UserActModel>) {
        if (emptyViewCount == 1) {
            // 如果当前显示的是空视图，则不进行diff，直接设置新数据
            setNewData(list)
            return
        }
        val diffResult = DiffUtil.calculateDiff(MineDiffCallBack( mData, list))
        diffResult.dispatchUpdatesTo(this)
        mData = list
    }
`
然后外面，直接调用这个这个方法去设置数据就行了

**Comment by bakonMa** [comment]
我今天在看DiffUtil 想集合本库 用一下，但是发现：
构建adapter 的list 和 修改的数据是同一个list对象 使用xxxDiffCallBack  比较出来始终是相同的怎么解决，需要每次修改前clone 一份List，再做修改，在xxxDiffCallBack吗？感觉好烦，有其他解决办法吗？

**Comment by bakonMa** [comment]
> 自行在adapter中添加个方法就行了，例如：
> 
> ```
> fun setDiffList(list: List<UserActModel>) {
>         if (emptyViewCount == 1) {
>             // 如果当前显示的是空视图，则不进行diff，直接设置新数据
>             setNewData(list)
>             return
>         }
>         val diffResult = DiffUtil.calculateDiff(MineDiffCallBack( mData, list))
>         diffResult.dispatchUpdatesTo(this)
>         mData = list
> }
> ```
> 
> 然后外面，直接调用这个这个方法去设置数据就行了

我今天在看DiffUtil 想集合本库 用一下，但是发现：
构建adapter 的list 和 修改的数据是同一个list对象 使用xxxDiffCallBack 比较出来始终是相同的怎么解决，需要每次修改前clone 一份List，再做修改，在xxxDiffCallBack吗？感觉好烦，有其他解决办法吗？

**Comment by yangfeng1994** [comment]
这个功能，已经在做了。你可以添加作者陈宇明老师的微信chad_cym，进行沟通。

**Comment by limuyang2** [comment]
> > 自行在adapter中添加个方法就行了，例如：
> > ```
> > fun setDiffList(list: List<UserActModel>) {
> >         if (emptyViewCount == 1) {
> >             // 如果当前显示的是空视图，则不进行diff，直接设置新数据
> >             setNewData(list)
> >             return
> >         }
> >         val diffResult = DiffUtil.calculateDiff(MineDiffCallBack( mData, list))
> >         diffResult.dispatchUpdatesTo(this)
> >         mData = list
> > }
> > ```
> > 
> > 
> > 然后外面，直接调用这个这个方法去设置数据就行了
> 
> 我今天在看DiffUtil 想集合本库 用一下，但是发现：
> 构建adapter 的list 和 修改的数据是同一个list对象 使用xxxDiffCallBack 比较出来始终是相同的怎么解决，需要每次修改前clone 一份List，再做修改，在xxxDiffCallBack吗？感觉好烦，有其他解决办法吗？
> QQ：762713299

对同一个list进行修改，只能对list进行一次深拷贝，注意：不是浅拷贝，浅拷贝内存指针依然没有变化。

**Comment by limuyang2** [comment]
Diff已完成，请等待新版本发布
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2808
