### ISSUE TITLE
多布局之间拖动

### ISSUE THREAD

**Issue by wangyuan0217** [CymChad/BaseRecyclerViewAdapterHelper#2692]
看了下wiki 
多布局extends BaseMultiItemQuickAdapter 
拖动extends BaseItemDraggableAdapter
 这两个功能怎么样能共存啊，
类似于聊天页面不同消息（消息类型不一）上下拖动

**Comment by wangyuan0217** [comment]
发现多布局的另外一种代理写法，setMultiTypeDelegate/getMultiTypeDelegate的这个  然后adapter继承BaseItemDraggableAdapter 来实现多布局拖拽， 可是写完发现选中的消息类型只能在这个消息之间拖拽，无法在不同布局之间拖拽啊。

**Comment by MachKanh** [comment]
I have the same issue...
How can I implement item swipe/drag functionality in a BaseMultiItemQuickAdapter?

**Comment by wangyuan0217** [comment]
最终找了个ListView的了。。

**Comment by yangfeng1994** [comment]
你可以在issues #2806 里面提一个需求

**Comment by com13117340768** [comment]
我也是遇到同样的问题，要是能合并真是太好了

**Comment by xuyingke** [comment]
这个已经支持了。

**Comment by wangyuan0217** [comment]
> 这个已经支持了。

支持了？我没看到有更新啊 @xuyingke

**Comment by xuyingke** [comment]
最新版才会有，或者你直接用原生 ItemTouchHelper 似乎也没什么问题。
