### ISSUE TITLE
每次上拉加载后都会返回到顶部

### ISSUE THREAD

**Issue by li-wen-qi** [CymChad/BaseRecyclerViewAdapterHelper#2693]
感觉代码没什么问题，还有人有这种情况吗

**Comment by diswy** [comment]
同样遇到这问题，不知道怎么解决。。

**Comment by diswy** [comment]
目前定位问题是adapter.addData后会返回到顶部。我使用的是androidx下的rv，印象中以前使用无问题。不知道你跟我情况一样不 @li-wen-qi

**Comment by CymChad** [comment]
收到

**Comment by limuyang2** [comment]
请提供demo，方便我们测试。
参照 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2807 提问

**Comment by JohnsCui** [comment]
不要在setLoadDataResult之后使用setAdapter方法
