### ISSUE TITLE
为什么一直滚，直到没有数据为止？

### ISSUE THREAD

**Issue by AndyLeeBlue** [CymChad/BaseRecyclerViewAdapterHelper#2699]
按demo写的上拉加载，一旦到最后一行就一直加载直到服务器没有数据为止，没用nestscrollview，有人说用addhead的方式，对我来说改动太大了，这是怎么回事？该怎么解决呢？

**Comment by wanglianghai** [comment]
上拉加载布局不能嵌套在滚动布局中

**Comment by AndyLeeBlue** [comment]
并没有嵌套scroll中

**Comment by yangfeng1994** [comment]
能把你调用的代码贴出来吗？

**Comment by shichaohui** [comment]
新的数据加载完成后，是否调用了 `mAdapter.addData()` 函数添新数据加到 Adapter ？
如果仅仅调用 `mAdapter.loadMoreComplete()` 而没有添加新数据，会导致再次触发 `onLoadMoreRequested()` 函数加载数据。因为一直处于列表底部，所有会一直触发，直到数据加载完毕调用 `loadMoreEnd()` 结束加载。
