### ISSUE TITLE
断网后，加载更多然后addFooterView是报错

### ISSUE THREAD

**Issue by liujie007** [CymChad/BaseRecyclerViewAdapterHelper#270]
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling

**Comment by CymChad** [comment]
你是不是在没加载完item的时候就addFooterView了？

**Comment by CymChad** [comment]
需要在  mRecyclerView.post(这里面处理加载更多的代码);

**Comment by CymChad** [comment]
demo和文档里面有写

**Comment by liujie007** [comment]
1.触发加载更多onLoadMoreRequested后，然后addFooterView 报错，这个时候，没有加载数据

**Comment by liujie007** [comment]
好的， 我试试看。灰常感谢。

**Comment by CymChad** [comment]
恩，有问题再提
