### ISSUE TITLE
IndexOutOfBoundsException in use BaseMultiItemQuickAdapter

### ISSUE THREAD

**Issue by dengpan20** [CymChad/BaseRecyclerViewAdapterHelper#2700]
**Describe the bug**
连续展开多条item `展开到第八第九或者第十的时候会崩溃`

![image](https://user-images.githubusercontent.com/10458610/55785310-c70be680-5ae4-11e9-8d98-d2dc612010e6.png)

**Comment by CymChad** [comment]
收到，我们验证一下

**Comment by CymChad** [comment]
![image](https://user-images.githubusercontent.com/7698209/61642430-7014d080-acd3-11e9-9a53-2dd39f19c973.png)
我连续张开了12条，并没有复现出你说的问题。如果还有问题请提供demo
