### ISSUE TITLE
rv嵌套rv

### ISSUE THREAD

**Issue by z530703792** [CymChad/BaseRecyclerViewAdapterHelper#2704]
recyclerView嵌套recyclerView   二级列表中重写了onChildItemClickListener();希望能在该方法中返回点击事件条目所在一级recyclerView的位置   点击事件被消耗  无法获取

**Comment by AllenCoder** [comment]
目前的点击事件公开api是通用的api设计，无法针对嵌套的点击进行特殊处理，这种嵌套情形可以在数据层增加一个父级数据增加一个字段的标识id，在子级事件点击时获取父级的数据id即可，改造成本不是太大

**Comment by WangMiaoGit** [comment]
> recyclerView嵌入recyclerView二级列表中重建了onChildItemClickListener（）;希望能在该方法中返回单击事件所在的一级recyclerView的位置单击事件被消耗无法获取

你好，想问下，我的recyclerView嵌入recyclerView二级列，是在前一级的adapter中设置二级的onChildItemClickListener（）吗？我设定了，但是点击没效果
