### ISSUE TITLE
如何设置被选中的item的图标和颜色改变为选中状态，未被选中的item图标和颜色还是未选中状态

### ISSUE THREAD

**Issue by guogailee** [CymChad/BaseRecyclerViewAdapterHelper#271]
类似这样的
![s60829-164107](https://cloud.githubusercontent.com/assets/12292895/18045826/6a78ba32-6e07-11e6-86de-8538f90b6953.jpg)

**Comment by CymChad** [comment]
缓存问题，你在adapter里面对状态 if else 判断设置一下。

**Comment by CymChad** [comment]
根据一个数据属性来控制是否被选中，这样可以解决你的缓存问题。

**Comment by guogailee** [comment]
我试试看

**Comment by CymChad** [comment]
恩，好的，有问题随时说
