### ISSUE TITLE
//拖拽item，有时候长按之后，手机一直在震动，拖拽响应失败

### ISSUE THREAD

**Issue by Ye83** [CymChad/BaseRecyclerViewAdapterHelper#2712]
跟着demo 写拖拽，有时候可以拖，有时候拖的时候手机就会一直震动，停不下来。项目组要是看到的话，麻烦看看，要提供代码的话，可以提供。谢谢，麻烦了。谢谢你们整理出那么好用的轮子

**Comment by Ye83** [comment]
下载了demo apk，发现demo 里面的也是会有一样的情况。拖了几次之后，上下滑动，再拖动就出现震动了

**Comment by CymChad** [comment]
收到，我们验证一下

**Comment by CymChad** [comment]
经 @yangfeng1994  验证没有出现你说的问题，如果还有问题可以提供复现demo
