### ISSUE TITLE
树形菜单- 如何获取当前父类一共有多少个子项

### ISSUE THREAD

**Issue by xiaojidonggong** [CymChad/BaseRecyclerViewAdapterHelper#2716]
我的需求是，当子项是最后一个时，要展示不同的UI。
我现在能拿到当前子项的位置，我想获取子项一共多少个，这样就可以比较相等，得出是最后一个子项，设置不同UI。

**Comment by tpnet** [comment]
getSubItems().size

**Comment by CymChad** [comment]
@tpnet 感谢你的回复
