### ISSUE TITLE
设置重复执行动画分割线会丢失一部分

### ISSUE THREAD

**Issue by kangqin** [CymChad/BaseRecyclerViewAdapterHelper#2718]
我设置recyclerview条目点击时，条目滚动到中间，并且设置动画重复执行，但是滚动的时候中间以上的分割线会丢失

**Comment by shichaohui** [comment]
@kangqin 请问是否已解决了这个问题？
BRVAH 本身没有分割线的，是否是你的分割线绘制（ItemDecoration）有问题呢？如果可以的话，请提供一个 Demo 协助解决这个问题。
