### ISSUE TITLE
使用expandableItem,展开时组头高度会比收缩时的要大

### ISSUE THREAD

**Issue by nicelyjust** [CymChad/BaseRecyclerViewAdapterHelper#2719]
引用版本:com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46;
compileSdkVersion:28;
机型:pixel2 android P;

**Comment by nicelyjust** [comment]
![image](https://user-images.githubusercontent.com/20015907/57191328-dd2b8c00-6f56-11e9-897e-c6bf5ee337e0.png)

**Comment by CymChad** [comment]
收到，我们验证一下

**Comment by CymChad** [comment]
请检查你的布局
![image](https://user-images.githubusercontent.com/7698209/61642655-ed404580-acd3-11e9-8f39-60c91edfaf7f.png)
我从demo中并没有影响

**Comment by nicelyjust** [comment]
你好，出问题的机型是：谷歌pixel 2 os 9.0


| |
李增
|
|
邮箱：nicely_email@yeah.net
|

签名由 网易邮箱大师 定制

在2019年07月22日 22:57，陈宇明 写道：

Closed #2719.

**Comment by CymChad** [comment]
好的，我开个谷歌pixel 2 os 9.0的虚拟机检查一下。

**Comment by CymChad** [comment]
用了你说的同样的模拟器，测试demo效果还是一样。
![image](https://user-images.githubusercontent.com/7698209/61725742-ee8c7380-ada2-11e9-9238-1facb4776c80.png)
如果还有问题，你可以提供下复现的demo。
