### ISSUE TITLE
上拉加载更多结束，添加footerView提示用户没有更多了出现问题

### ISSUE THREAD

**Issue by weavey** [CymChad/BaseRecyclerViewAdapterHelper#272]
如题，这是很多上拉加载都会做的一个对用户的友好提示，我试过自己手动添加footerView，但效果不太好，第一：添加footerView，默认为gone，在notifyDataChangedAfterLoadMore(list,false)将footerView设为visibility，会和你的loadingView交替出现闪一下的问题，很突兀；第二，当第一页只有1条数据，数据没铺满屏幕，notifyDataChangedAfterLoadMore(list,false)后，也会有这个footerView，不太美观；所以希望作者能否在loadingView上做点优化，是否可以在notifyDataChangedAfterLoadMore(list,false)，将loadingView替换为提示“没有更多”等，最好可支持自定义样式。

**Comment by CymChad** [comment]
支持自定义的。setLoadingView

**Comment by CymChad** [comment]
我的demo有你这种场景吧。

**Comment by weavey** [comment]
就是不断手动的去更新loadingView？

**Comment by CymChad** [comment]
如果你觉得样式不要看设置setLoadingView可以改变样式，等到最后没有更多数据的时候你add FooterView提示“没有更多”，不就好了吗？

**Comment by weavey** [comment]
额  我上面已经说过这样用会出现的问题了  第一种情况 = =

**Comment by weavey** [comment]
改loadingView也不行吧  notifyDataChangedAfterLoadMore(list,false)之后 loadingView已经被隐藏了  替换了也看不到 = =

**Comment by CymChad** [comment]
我知道了，你的意思是让用户手动点击加载更多对吧？

**Comment by CymChad** [comment]
这样就要交替显示footerView和loadingView

**Comment by CymChad** [comment]
我这边试试，稍等

**Comment by weavey** [comment]
不是不是  不是要手动点击加载更多 上拉加载就够了= =

**Comment by weavey** [comment]
就是  上拉加载 没有更多的时候  能有个footerView给用户一个提示  没有更多了

**Comment by weavey** [comment]
没有更多数据的时候 添加footerView提示“没有更多”是可行的  就是会有一个闪一下的效果   主要是这个问题

**Comment by weavey** [comment]
初始化adapter：  
      footerView = getView();  //没有更多
        footerView.setVisibility(View.GONE);
        adapter.addFooterView(footerView);
更新数据的时候：

    @Override
    public void setRecycleView(List<HosAssessBean> list,
                               boolean bool) {

        adapter.notifyDataChangedAfterLoadMore(list,bool);
        if (!bool) {
            adapter.setLoadingView();
          footerView.setVisibility(View.VISIBLE);
        }
    }

给你看代码直观一点

**Comment by weavey** [comment]
这样是可以 就是呈现出来的效果不太好  会闪

**Comment by CymChad** [comment]
行，我看看，你主要还是说闪烁的问题对吧。我demo里面有代码，是在判断没有更多数据的时候直接addFooterView的，不需要先添加footerView，控制起来比较麻烦。

**Comment by CymChad** [comment]
```java
 if (mCurrentCounter >= TOTAL_COUNTER) {
                    mQuickAdapter.loadComplete();
                    if (notLoadingView == null) {
                        notLoadingView = getLayoutInflater().inflate(R.layout.not_loading, (ViewGroup) mRecyclerView.getParent(), false);
                    }
                    mQuickAdapter.addFooterView(notLoadingView);
                } 
```

**Comment by weavey** [comment]
这样也会有问题，每次都添加footerView，有一种情况，我执行下拉刷新，数据会清空，再次从第一页开始加载数据，到最后没有更多的时候 又添加了一个footerView ，那就会显示两个footerView了

**Comment by CymChad** [comment]
下拉要清空，demo源码有写处理代码
```java
@Override
    public void onRefresh() {
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mQuickAdapter.setNewData(DataServer.getSampleData(PAGE_SIZE));
                mQuickAdapter.openLoadMore(PAGE_SIZE);
                mQuickAdapter.removeAllFooterView();
                mCurrentCounter = PAGE_SIZE;
                mSwipeRefreshLayout.setRefreshing(false);
                isErr = false;
            }
        }, delayMillis);
    }

```

**Comment by weavey** [comment]
额  我用你这个万能adapter很久了  之前没这个问题 昨天更新到1.9.8 才出现这个问题，是不是之前你自动帮我们调了removeAllFooterView()这个方法？我个人建议，既然有 adapter.notifyDataChangedAfterLoadMore(list,bool)这个方法，ture和false我都传给你了，这些比较细节的处理，是不是可以不交由用户来做？让这个adapter更简便一些

**Comment by CymChad** [comment]
恩，是的，以前不支持多个footer，现在支持了。

**Comment by weavey** [comment]
那现在是要怎么解决呢  还是我去添加footerView吗  那那个闪一下的问题不解决了？= =

**Comment by CymChad** [comment]
还是按demo这种方式来。

**Comment by weavey** [comment]
额  那还是回到我开头提的那两点了 ，闪一下还能忍受，但是数据没填满屏幕，还是会有一个“没有更多”   这样的话  我还是不要给提示了  = =

**Comment by CymChad** [comment]
恩，是的。不要给提示。

**Comment by CymChad** [comment]
不满一屏幕不会进加载更多的回调的。也不会加“没有更多”的提示。

**Comment by weavey** [comment]
@Override
    public void onRefresh() {
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mQuickAdapter.setNewData(DataServer.getSampleData(PAGE_SIZE));
                mQuickAdapter.openLoadMore(PAGE_SIZE);
                mQuickAdapter.removeAllFooterView();
                mCurrentCounter = PAGE_SIZE;
                mSwipeRefreshLayout.setRefreshing(false);
                isErr = false;
            }
        }, delayMillis);
    }
是啊，但是超出屏幕，很多app是会提示没有更多的，但如果按这种写法，不管满不满屏都会出现“没有更多”的提示，如果相关用户提示的话

**Comment by CymChad** [comment]
你说的交替互换闪一下，也只会出现最后一次，我看过一些app，他们也是这样的。

**Comment by CymChad** [comment]
因为如果不请求网络，客户端也无法得知是否有下一页，所以会先出现加载中的状态，然后返回数据了得到了没有数据的状态，于是就替换成“没有更多”了。

**Comment by weavey** [comment]
不会吧 我看了掘金简书好几个app  “没有更多”的提示是很平滑的， 主要原因不是你说的这个，而是因为，loadingView和“没有更多”的footerView是在两个不同的位置上，才会出现闪一下的效果，如果是用framelayout包住这两个东西，让它们在一个位置上，用gone和visibility去控制 是不会这样的

**Comment by CymChad** [comment]
我这个loadingView和footerView都是adapter的一个item

**Comment by weavey** [comment]
是的   如果不用footerView来做提示“没有更多”，你这样做是正确的，如果要提示"没有更多"，就不太适用了

**Comment by weavey** [comment]
主要考虑到用户体验的问题，开了上拉加载后，用户滑着滑着突然就不能滑了，又没有任何提示，会让人家感到很奇怪，毕竟不是所有用户都是程序员，只有我们知道发生了什么事

**Comment by CymChad** [comment]
行，了解了，我考虑一下怎么做更多。

**Comment by CymChad** [comment]
你说得对，闪烁确实会影响体验

**Comment by weavey** [comment]
嗯嗯  又给你活干了  真不好意思  难怪你的版本更新的这么频繁= =

**Comment by CymChad** [comment]
恩，没事，多多提建议，用户多，需求也多，小步快跑。

**Comment by CymChad** [comment]
如果要平滑，那就应该，把最后一次的加载更多，内容直接变成“加载完成”。我先自己尝试一下，如果这样，看会不会了其他的bug。

**Comment by weavey** [comment]
对  我的思路也是这样

**Comment by weavey** [comment]
而且也能解决   数据没铺满屏幕的时候  会有“没有更多”的提示

**Comment by CymChad** [comment]
行，我先试试，好了告诉你。你可以再 #77 里面，提一下。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.7' 你试一下，看感觉如何？

**Comment by CymChad** [comment]
代码不变，你看下效果是否平滑。

**Comment by weavey** [comment]
爆炸了   我前面用的是1.9.7    2.0的你删了一些方法  项目太多地方用了  改不过来 = =

**Comment by CymChad** [comment]
.... 那等你有时间在换吧。2.0改动确实有点多，特别是点击事件那一块。

**Comment by CymChad** [comment]
换了之后，给我一个结果的答复就行了。

**Comment by weavey** [comment]
嗯 只能有时间再改了
