### ISSUE TITLE
复用同一个fragment切换时，recyclerview出现问题

### ISSUE THREAD

**Issue by 18856914956** [CymChad/BaseRecyclerViewAdapterHelper#2720]
**Describe the bug**
viewpager + tablayout , 使用同一个fragment多次切换，会出现
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
使用版本com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by limuyang2** [comment]
[参考此Issues，可以解决](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2796)
