### ISSUE TITLE
fragment里面添加emptyview不显示

### ISSUE THREAD

**Issue by zouqingliang** [CymChad/BaseRecyclerViewAdapterHelper#2723]
使用版本com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46
使用场景是这样的 我用tablayout+viewpager实现的fragment切换，然而很奇怪的问题出现了，设置emptyview后就第一次显示了下，后面重新安装APP，刷新布局都没有再次显示过，同样的方式在activity里面是正常显示
以下是代码：
public View getEmptyView(ViewGroup parent) {
        View view = getLayoutInflater().inflate(R.layout.view_no_data, parent,false);
        ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        layoutParams.width = parent.getWidth();
        layoutParams.height = parent.getHeight();
        view.setLayoutParams(layoutParams);
        return view;
    }
adapter.setEmptyView(getEmptyView((ViewGroup) rvList.getParent()));

**Comment by YellowStars1993** [comment]
我好像也遇到这个问题了，不知道楼主解决没有。。。

**Comment by YellowStars1993** [comment]
> 使用版本com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46
> 使用场景是这样的 我用tablayout+viewpager实现的fragment切换，然而很奇怪的问题出现了，设置emptyview后就第一次显示了下，后面重新安装APP，刷新布局都没有再次显示过，同样的方式在activity里面是正常显示
> 以下是代码：
> public View getEmptyView(ViewGroup parent) {
> View view = getLayoutInflater().inflate(R.layout.view_no_data, parent,false);
> ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
> layoutParams.width = parent.getWidth();
> layoutParams.height = parent.getHeight();
> view.setLayoutParams(layoutParams);
> return view;
> }
> adapter.setEmptyView(getEmptyView((ViewGroup) rvList.getParent()));

我好像也遇到这个问题了，不知道楼主解决没有
