### ISSUE TITLE
*** removeAllHeaderView ***

### ISSUE THREAD

**Issue by Alireza-Milani** [CymChad/BaseRecyclerViewAdapterHelper#2724]
Hello,
we've noticed an issue on method removeAllHeaderView and removeAllFooterView. The problem is that this method removes all children views inside the viewgroup which is a LinearLayout but keeping the parent which is the LinearLayout. it is better to remove the parent LinearLayout because the following error appears:
***

> ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

    public void removeAllHeaderView() {
        if (getHeaderLayoutCount() == 0) {
            return;
        }

        // mHeaderLayout.removeAllViews();

        // adding this solves the problem
        mHeaderLayout = null;
        int position = getHeaderViewPosition();
        if (position != -1) {
            notifyItemRemoved(position);
        }
    }

the suggestion is that if you remove the Linearlayout or null the parameter as mentioned in the description of the method itself the problem would be solved.
Best regards,
Alireza

**Comment by TpOut** [comment]
hey bro, why closed and reopen ?

**Comment by CymChad** [comment]
thanks your suggestion
