### ISSUE TITLE
树形二级列表里面有EditText问题

### ISSUE THREAD

**Issue by DingMr** [CymChad/BaseRecyclerViewAdapterHelper#2725]
当在二级或多级条目的布局中有EditText时，我出现了如下问题：
①数据错乱
②数据消失

**Comment by limuyang2** [comment]
由于没有相关代码及demo，仅根据描述，此问题并不属于本库的问题。
recyclerView本身具有复用机制，item的view视图都是复用的，
例如item0 上输入了“123”，那么当item5复用item0的时候，自然也会有“123”，就误以为数据错落或者消失。
此处应该自行对EditText中对数据进行保存和恢复重设。
建议多了解recyclerView复用机制。
