### ISSUE TITLE
ExpandableItemAdapt 发现的bug 在demo中可复现

### ISSUE THREAD

**Issue by she246** [CymChad/BaseRecyclerViewAdapterHelper#2728]
/**
 * https://github.com/CymChad/BaseRecyclerViewAdapterHelper
 */
public class ExpandableUseActivity extends BaseActivity {
    private RecyclerView mRecyclerView;
    private ExpandableItemAdapter adapter;
    private ArrayList<MultiItemEntity> list;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setBackBtn();
        setTitle("ExpandableItem Activity");
        setContentView(R.layout.activity_expandable_item_use);

        mRecyclerView = (RecyclerView) findViewById(R.id.rv);

        list = generateData();
        adapter = new ExpandableItemAdapter(list);

        final GridLayoutManager manager = new GridLayoutManager(this, 3);
        manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return adapter.getItemViewType(position) == ExpandableItemAdapter.TYPE_PERSON ? 1 : manager.getSpanCount();
            }
        });

        mRecyclerView.setAdapter(adapter);
        // important! setLayoutManager should be called after setAdapter
        mRecyclerView.setLayoutManager(manager);
        //adapter.expandAll();
    }

这是demo中ExpandableUseActivity 的主要代码，我想默认全部折叠隐藏，所以注释掉了 //adapter.expandAll();，运行demo，发现最后一个条目有时无法正常折叠隐藏/显示，求助大家

**Comment by 972223177** [comment]
我的情况是展开前几项中的一条，然后点列后几项的出现位置错乱的情况。末尾的甚至无法展开。请问你的解决了吗

**Comment by CymChad** [comment]
收到，我们验证一下

**Comment by CymChad** [comment]
运行demo测试了10次，并没有发现无法正常折叠隐藏/显示。

**Comment by kyriej** [comment]
有问题，多次折叠展开，就有条目无法正常展开收缩了
