### ISSUE TITLE
recyclerview未满一屏添加footerview满一屏可以固定在下方布局吗

### ISSUE THREAD

**Issue by wangfufu** [CymChad/BaseRecyclerViewAdapterHelper#2730]
recyclerview未满一屏添加footerview满一屏可以固定在下方布局吗

**Comment by yangfeng1994** [comment]
设置setLoadMoreView ,在你的自定义moreView里设置footView要显示的东西，在setNewData之前，调用disableLoadMoreIfNotFullPage 。
