### ISSUE TITLE
有关GridSectionAverageGapItemDecoration中的间距设置问题

### ISSUE THREAD

**Issue by jojoEcho** [CymChad/BaseRecyclerViewAdapterHelper#2732]
demo中GridSectionAverageGapItemDecoration中，设置sectionStartItemPos的方式，只有position首次出现时确定的sectionStartItemPos 是有效的，当sectionEdgeHPaddingDp和gapHorizontalDp数据差值较大时，超出一屏数据，再次滑回第一页时，就会出现item混乱的问题，可以只记录position首次出现时的记录值，比如是否是firstColumn、或者lastColumn，以及content的Rect的left和right的值，就可解决item混乱的问题

**Comment by candyguy242** [comment]
@jojoEcho 这个问题已经解决了，目前还没有合并过来，可以先用这个

https://github.com/candyguy242/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/decoration/GridSectionAverageGapItemDecoration.java

**Comment by Leu-Z** [comment]
给力

**Comment by AllenCoder** [comment]
已合并 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2765](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2765)
