### ISSUE TITLE
怎么实现更新部分控件，比如一个列表里的item有图片和倒计时控件，每秒只更新倒计时的Textview？

### ISSUE THREAD

**Issue by WarriorYu** [CymChad/BaseRecyclerViewAdapterHelper#2733]
怎么实现更新部分控件，比如一个列表里的item有图片和倒计时TextView，每秒只更新倒计时的Textview。使用onBindViewHolder(holder, position, payloads)这个方法可以实现，但是这个库没这个方法。我通过在convert(...)方法里自己保存viewholder到一个List,然后每秒钟去遍历viewholder，从而更新倒计时的TextView。因为业务还有场景复杂，这种方法不完美，请问有更好的建议吗？

**Comment by yangfeng1994** [comment]
获取item相应的itemView，然后再通过相应的itemView找到itemView中TextVIew对应的id，再对TextView进行倒计时的操作，当item划出屏幕时，一定要停止倒计时不然会造成内存泄漏

**Comment by limuyang2** [comment]
已添加Diff功能。请更新最新版
