### ISSUE TITLE
自定义LoadMoreView，如何添加监听

### ISSUE THREAD

**Issue by wimvogt** [CymChad/BaseRecyclerViewAdapterHelper#2736]
自定义LoadMoreView，里面实现了自己的view，如果对view添加点击事件？

**Comment by AllenCoder** [comment]
直接获取 loadMoreView
然后 loadMoreView.setOnClickListenter

**Comment by wimvogt** [comment]
不是整个view，LoadMoreView中可能有多个button，对button设置点击事件
