### ISSUE TITLE
重写getItemCount()无效

### ISSUE THREAD

**Issue by zybooo1** [CymChad/BaseRecyclerViewAdapterHelper#2738]
`    @Override
    public int getItemCount() {
        return mData.size() + 1;
    }`

**Comment by 103945089** [comment]
我也是

**Comment by zybooo1** [comment]
等有时间再来研究，我现在的解决方法是在数据源+1，也可以加一个Footer

**Comment by Roben1016** [comment]
> 等有时间再来研究，我现在的解决方法是在数据源+1，也可以加一个Footer

我是想实现添加本地相册图片的功能, 最后边会有一个+按钮, 加个footer没用, 只能在数据源上处理了

**Comment by GreenhairTurtle** [comment]
也许你应该试试
```java
public int getItemCount() { return super.getItemCount() + 1; }
```

**Comment by Roben1016** [comment]
> 也许你应该试试
> 
> ```java
> public int getItemCount() { return super.getItemCount() + 1; }
> ```

试过

**Comment by tmac1999** [comment]
问题都没解决为什么Close了？

**Comment by 1226362423** [comment]
我也遇到了

**Comment by 1226362423** [comment]
+++++1

**Comment by 1226362423** [comment]
public int getItemCount() { return super.getItemCount() + 1; } 没用
