### ISSUE TITLE
swapAdapter 切换适配器以后getItem 获取的数据不对

### ISSUE THREAD

**Issue by guoleifei** [CymChad/BaseRecyclerViewAdapterHelper#2739]
我有2个adapter 
mLeftAdapter,mRightAdapter 名字同但是是相同的adapter
其中的初始化的点击事件
init {
        setOnItemClickListener { _, view, position ->
            getItem(position)
        }
    }
当我使用 swapAdapter  切换适配器以后 从mLeftAdapter切换到 mRightAdapter 后
UI显示正确，但是getItem 获取的数据时mLeftAdapter 中的内容 而且 mdatas 中的数据也是和
mLeftAdapter 中的数据

**Comment by shichaohui** [comment]
未能重现该问题，感觉是你的用法不太对，是否能提供一个 Demo ？

**Comment by CymChad** [comment]
请根据规范提问 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2807
