### ISSUE TITLE
BaseItemDraggableAdapter

### ISSUE THREAD

**Issue by Theoneee** [CymChad/BaseRecyclerViewAdapterHelper#2740]
有没有办法控制拖动范围呢。
比如有十条数据，我只想2-10条数据之间可以拖动。1是保持不变的。

**Comment by shichaohui** [comment]
重写 `ItemDragAndSwipeCallback#getMovementFlags()` 函数自定义 Item 是否可被拖动或者滑动。
重写 `ItemDragAndSwipeCallback#onMove()` 函数自定义两个 Item 是否可以交换位置。
```
new ItemDragAndSwipeCallback(mAdapter) {
    @Override
    public int getMovementFlags(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder) {
        if (viewHolder.getAdapterPosition() == 0) {
            // 不可拖动，不可滑动
            return makeMovementFlags(0, 0);
        }
        return super.getMovementFlags(recyclerView, viewHolder);
    }

    @Override
    public boolean onMove(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder source, @NonNull RecyclerView.ViewHolder target) {
        // 不可拖动其他 Item 与 target Item 交换位置
        if (target.getAdapterPosition() == 0) {
            return false;
        }
        return super.onMove(recyclerView, source, target);
    }
};
```

**Comment by Danniel-yan** [comment]
> 重写 `ItemDragAndSwipeCallback#getMovementFlags()` 函数自定义 Item 是否可被拖动或者滑动。 重写 `ItemDragAndSwipeCallback#onMove()` 函数自定义两个 Item 是否可以交换位置。
> 
> ```
> new ItemDragAndSwipeCallback(mAdapter) {
>     @Override
>     public int getMovementFlags(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder) {
>         if (viewHolder.getAdapterPosition() == 0) {
>             // 不可拖动，不可滑动
>             return makeMovementFlags(0, 0);
>         }
>         return super.getMovementFlags(recyclerView, viewHolder);
>     }
> 
>     @Override
>     public boolean onMove(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder source, @NonNull RecyclerView.ViewHolder target) {
>         // 不可拖动其他 Item 与 target Item 交换位置
>         if (target.getAdapterPosition() == 0) {
>             return false;
>         }
>         return super.onMove(recyclerView, source, target);
>     }
> };
> ```

没有效果呢
