### ISSUE TITLE
onItemSwiped 中 pos 错误

### ISSUE THREAD

**Issue by happyhappyYang** [CymChad/BaseRecyclerViewAdapterHelper#2741]
@Override
            public void onItemSwiped(RecyclerView.ViewHolder viewHolder, int pos) {
                Log.d(TAG, "View Swiped: " + pos);
            }

这个方法返回的pos=-1

**Comment by AllenCoder** [comment]
1. 检查是否是最新版本
2.使用demo在你的环境下运行检查是否还是同样的问题。
