### ISSUE TITLE
mRequestLoadMoreListener 为null

### ISSUE THREAD

**Issue by parade0393** [CymChad/BaseRecyclerViewAdapterHelper#2742]
设置了loadMoreListener
`  newsListAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                if (isLast){
                    adapter.loadMoreEnd(false);
                }else {
                    getNewsListFromNet(currentPage+1);
                }
            }
        }, recy_jrxx);`
并且在适配器也接收到了
![13](https://user-images.githubusercontent.com/46487578/57584212-438e4c80-750b-11e9-8d50-be070906a7d5.jpg)
但是在antoLoadMore方法中判断 `getLoadMoreViewCount`时，却提示mRequestLoadMoreListener为null
![32](https://user-images.githubusercontent.com/46487578/57584270-b26ba580-750b-11e9-96f8-9e7a25ed6946.jpg)

**Comment by shichaohui** [comment]
@parade0393 请问这个问题你解决了吗？
`mRequestLoadMoreListener` 是强引用的，无缘无故不会为 null，可能是不小心调用`setOnLoadMoreListener()` 传了 null 进来了。
