### ISSUE TITLE
OnItemSwipeListener回调中pos问题

### ISSUE THREAD

**Issue by w-g-b** [CymChad/BaseRecyclerViewAdapterHelper#2745]
通过打印日志，发现如果只是滑动，没有删除item，那回调方法的pos为正数，会调用clearView()方法。
如果删除了某个元素的话，那pos为负数。但是删除第一个元素的时候，pos为-1，删除第二个数的时候pos也为-1。在clearView()做处理的时候无法分辨删除了那个元素。

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
已修复 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2811
