### ISSUE TITLE
头布局和空布局如何同时存在？？

### ISSUE THREAD

**Issue by chenkexu** [CymChad/BaseRecyclerViewAdapterHelper#2747]
怎么同时设置空布局和头布局啊？
  public void getCollectShopList(List<ProductListEntity> projectListData) {
        //结束刷新
        setRefreshing(false);
        //没数据
        if (projectListData == null||projectListData.size()==0) {
            collectShopAdapter.setNewData(null);
//            空布局
            collectShopAdapter.setEmptyView(R.layout.layout_no_seach_cloth, (ViewGroup) myRecyclerView.getParent());
            collectShopAdapter.setHeaderAndEmpty(true);
        }else{
            collectShops = projectListData;
            setData(true, collectShops);
            collectShopAdapter.setEnableLoadMore(true);
        }
    }

无效，只显示头布局，不显示空布局。

**Comment by AllenCoder** [comment]
可以的，检查你的设置顺序  参考demo写法 
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/HeaderAndFooterUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/HeaderAndFooterUseActivity.java)

**Comment by chenkexu** [comment]
@AllenCoder 大佬，你给的Demo中没有找到设置空布局setEmptyView的地方啊？？？

**Comment by chenkexu** [comment]
@AllenCoder 解决了。感谢大佬！

**Comment by lijunzz** [comment]
Demo 中未找到关键代码，参考  #2483 当列表数据为空时，headivew不显示 ，设置`madapter.setHeaderAndEmpty(true);`解决了这个问题。
