### ISSUE TITLE
这样一个用gson解析的类   怎么设置并区分做多布局？

### ISSUE THREAD

**Issue by wangjianfengw** [CymChad/BaseRecyclerViewAdapterHelper#2749]
package com.wuhanzihai.zyx.bean;

import com.chad.library.adapter.base.entity.MultiItemEntity;

import java.util.List;

/**
 * author : W
 * date   : 2019/5/1614:16
 * desc   :
 */
public class HomeBean implements MultiItemEntity {

    /**
     * code : 200
     * jifen :
     * message : 成功
     * data : {"xiaohua":[{"title":"喵起来吧～撸猫避免挨揍的正确开撸方式！","content":"喵星人性格傲娇，体态优美，毛色美丽、圆脸肉爪确实很容易俘获众人之心。猫咖啡馆深受年轻人的喜爱， 故宫猫、观复猫还成为了文化代言人。那么作为一个猫奴，你撸猫的姿势正确吗？下面我们就来说说猫奴的自我修养\u2014\u2014拍猫。很多时候，你就这样和谐的和猫主子这样坐着只是轻轻反复抚摸，也没做什么对吧然而人家却嫌弃的走了。为什么呢？原来这不是猫咪情绪失控，而是它的生理反应，反复抚摸会让他们赶紧想气球一样不断膨胀，涨着涨着就炸了，所以如何解决这个问题呢？第一点：仔细观察，确认猫咪生气的临界点。撸着撸着你可能会看到猫的尾尖开始轻微抽动，然后摆动幅度会升级，这就表示你快要挨揍了！","click":2613,"pic":"/uploadfile/xiaohua/20190104/295f4a2ef569cb9a7cc6cf6fd655c8ec.jpg","aid":59,"add_time":"2018-11-30 10:48","comment_num":1},{"title":"全球TOP4极光旅行地推荐 享受这份人间仙境","content":"精致的猪猪女孩们是否都有一个看极光的梦想？而看极光最好的地方全都在北欧，如果你刚好计划有北欧之行，不妨抽出时间去某地人间仙境看看极光美景。这份感受大概可以回味一生吧！住的地方固然重要，北欧适合看极光，也适合拍照的貌美酒店推荐给大家，不要错过哦~Top4 冰岛 · 雷克雅未克交通建议：中国没有直飞冰岛的航班，需从欧洲其他城市转机前往。从国内出发，最方便实惠的选择是芬兰航空、北欧航空（斯堪的纳维亚航空）的联程机票，国航、海航等也有飞往冰岛的航班。Top3 瑞典 · 尤卡斯亚维位于瑞典Kiruna的尤卡斯亚维村是瑞典第一家冰雪酒店的所在地哦~！在尤卡斯亚维村看见的极光都像是落在地平线上一样，非常美丽，而且还可以顺便去Esrange航天中心看看。推荐交通线路：芬兰航空、卡塔尔航空、中国国航。只有国航可以直达瑞典，其余航空都需要转机才可以到瑞典斯德哥摩尔机场。飞到斯德哥尔摩，然后再转机或者自驾或者乘火车抵达Kiruna地区。酒店推荐： ICEHOTLETop2 芬兰 · 卡克斯劳塔宁芬兰每年八月~次年四月，只要是晴朗的天气，都有可能看到极光。更重要的是，这里的酒店多数都为玻璃屋酒店，让大家躺着不受冻的欣赏极光美景！路线交通：中国航空和芬兰航空直飞航班可以到赫尔辛基的万塔机场。从北京前往赫尔辛基的直飞航程约8小时20分左右。淡季往返最便宜六七千左右。推荐酒店：卡克斯劳塔纳西村冰屋酒店Top1 挪威 · 斯瓦尔巴群岛每年11月到次年2月期间，都可以看到极光。斯瓦尔巴特群岛位于北冰洋之，这座挪威海岛是世界上纬度最高的地方，因此看极光再好不过了。交通线路：北欧航空和挪威航空。朗伊尔城与北极点的直线距离1333公里。如果你是计划北欧之行的话，除了搭乘游轮，还可以从挪威奥斯陆或是特罗姆瑟直接飞到朗伊尔城。","click":2527,"pic":"/uploadfile/xiaohua/20190104/75a97d13b8582f4b6fb19159f0ac91c8.jpg","aid":60,"add_time":"2018-11-30 10:48","comment_num":2},{"title":"决定你上限的，不是智商，而是自律","content":"决定人生成败的因素有很多，最早的时候，很多人都秉持着\u201c智商决定论\u201d，但随着我们人生阅历的增加，我们会越来越发现：　　人生如苦旅，有时候决定我们上限的，不是智商，而是自律。　　1　　我身边就有一个这样的朋友，自律到近乎\u201c强迫症\u201d。　　他是毕业于哈佛的名企高管。在一次座谈时谈及人生经验，他自我介绍说自己有着严重的\u201c强迫症\u201d和\u201c完美主义\u201d，做事讲究\u201c计划性\u201d。　　每天为自己制定计划，并会严格执行。　　大学的时候，逼自己每天背50个单词，不背完绝不睡觉的决绝，让他的英语水平鹤立鸡群，计划出国前，雅思考了高分。　　现在工作后，要求自己每天坚持学习1小时，并写出3个纬度的总结，锻炼自己的思考能力。　　他让我切实地感受到，人一旦拥有高度的自律，便能有足够的能力去掌控自己的人生。　　没有一份优秀是无缘无故的，它的背后往往是无数个日夜的坚持和付出，才能收获高超的技艺水平。　　2　　坊间一直有个说法\u201c你的身材，反映了你的实力\u201d，其实说的就是这个理儿。　　生活中的我们，要想拥有好身材，就需要做到\u201c管住嘴，迈开腿\u201d，如果缺乏自律，很难想象人不会在各种诱惑面前妥协。　　我有一个朋友，从小就在吃和运动这方面不考究，所以越来越胖，到了上大学的时候，170的个头，体重一度飙升到250多斤。　　直到有一次，因为表白受挫，于是痛定思痛，才下决心减肥。　　接下来，他在网上查详资料后，便开始给自己定下了减肥食谱和运动计划。再馋再饿，也坚持管住嘴。　　半年后，掉了近45公斤的肉。人一瘦下来，感觉世界都开阔了。之后，他还把这种\u201c减肥\u201d精神践行到学习的方方面面，人生一路绿灯。　　现在的他，活得通透又淡然，优秀耀眼。　　他告诉我，每当生活中遇到难事自己想要妥协的时候，就会翻翻看当初记录的减肥日记，想想自己当初是如何坚持下来的\u2026\u2026　　当你对自己足够\u201c狠\u201d，世间没有什么事能够难倒你的。　　人，就是要在这样一次次的自律中，一点点塑造出更为优秀的自己的。","click":2208,"pic":"/uploadfile/xiaohua/20190104/5dc35749cff70f2d5a9f3445d84e17fd.jpg","aid":58,"add_time":"2018-11-30 10:47","comment_num":4},{"title":"你所不知道的9个日本传统文化","content":"大家去日本旅行的时候，对日本文化会不会有很多疑问？例如为什么餐厅总是给冰水、街上为什么没有垃圾桶、筷子为什么要横放？原来看似理所当然的事情，在背后总是藏着有趣的原因，以下9条问题，你又有没有问过呢？【日本文化01】 为什么日本乌鸦特别多？在日本最大的感想，就是无论去到哪里，乌鸦都很多！为什么？乌鸦本来是在森林栖息的雀鸟，但由于城市发展令森林的数量减少，加上都市生活为乌鸦提供大量食物（=垃圾，乌鸦是杂食动物），自然繁殖得更多。据说乌鸦的智慧仅次于猿猴，加上近年物质丰盛，连乌鸦都变得愈来愈聪明，翻垃圾的能力就更上一层楼了。不过，即使日本要修改收集垃圾的方法，相信也需要一段时间，所以大概人们还要被乌鸦骚扰多一阵子吧！【日本文化02】 为什么富士山不属于日本政府？富士山山顶的部分（3,360米以上）其实是私有地，真正的地主是（鼓声）⋯⋯浅间神社！一直以来，富士山被视作灵山，并用作祭神之用，仪式由浅间神社负责，到德川家康年代，德川家康就将富士山的地权干脆赐予浅间神社。1871年明治维新及太平洋战争后，政府回收所有土地的地权，唯独富士山山顶部分除外。","click":2166,"pic":"/uploadfile/xiaohua/20190104/534d20e59c84fbf03a074c109f7e835f.jpg","aid":56,"add_time":"2018-11-30 10:14","comment_num":1},{"title":"《了不起的盖茨比》这部电影你真的看懂了吗？","content":"电影画面很美，如油画一般色彩浓重艳丽，场面宏大奢华，服装造型非常精致，是一场时尚的狂欢，很能吸引女性观众的眼光。盖茨比为对婚姻失望的黛西营造了一场唯美梦幻的宴会，像童话中的王子与公主，久经磨砺，终于在一起，轻易戳动少女心。然而现实终究是现实，穷小子逆袭的盖茨比终究斗不过老谋深算的上流社会人物汤姆，理想的爱情像是一个巨大而美丽的泡泡，一戳就破，唯留繁华过后的满地苍凉。而黛西，经过短暂的偷情经历，终归还是选择回到上流社会做一只华美的金丝雀。电影通过旁观者尼克的独白讲述了整个故事，刻画了上流社会的自私、冷漠与虚伪。和原著本身相比，电影更注重场景的刻画和描述，少了小说中深刻的剖析与批判，以及对人性的探讨，缺乏力度。在最好的年华、最美的季节里，Gatsby预见了美丽的Daisy。爱情来得理所当然，化作人生最美好的时刻。可是，现实将贫穷的Gatsby与Daisy分开，Gatsby远赴战场，Daisy苦苦等待。在对这爱情的坚守中，两人都曾努力过，可最终坚持到底的却只有Gatsby。仅仅凭借着对岸微弱的希望之光，Gatsby始终坚持着，默默为Daisy做任何事。终于，他重新俘获了爱情，可这爱却始终不能坦坦荡荡，爱人总是在丈夫与爱人间摇摆。一次的情绪失控，竟然让爱再次死去。可他依然不肯认输，存着一点点渺茫的希望，期盼那个女人的回心转意。现实是残酷的，他死了，她却没有来。","click":225,"pic":"/uploadfile/xiaohua/20190104/0325e4eebcece044fd9e8492ce257ec6.jpg","aid":57,"add_time":"2018-11-30 10:44","comment_num":1}],"black":[{"aid":30,"title":"兔子要吃窝边草 二手货物少不了","url":"http://vhost1035.zihaiweb.cn/index.php/api/index/news"},{"aid":1,"title":"快来了解下快兔社团吧！！","url":"http://vhost1035.zihaiweb.cn/index.php/api/index/news"}],"banner":[{"title":"啊啊","url":"http://vhost1035.zihaiweb.cn/index.php/api/index/news","pic":"/uploadfile/xiaohua/20181130/f94334567a8ed804c2bf6e44e1ace753.jpg","aid":42,"is_outside":2},{"title":"首页顶部Banner-2","url":"http://vhost1035.zihaiweb.cn/index.php/api/index/news","pic":"/uploadfile/xiaohua/20190104/e1940239160d3cd4fd1c8d0204003dc4.png","aid":43,"is_outside":2},{"title":"首页顶部Banner-1","url":"http://vhost1035.zihaiweb.cn/index.php/api/index/news","pic":"/uploadfile/xiaohua/20181130/dadf2c03141c82d0db364be4aec99c5d.jpg","aid":44,"is_outside":2},{"title":"校友圈","url":"http://vhost1035.zihaiweb.cn/index.php/api/index/news","pic":"/uploadfile/xiaohua/20181130/94a6678da4756743babfd09943d5cfcb.jpg","aid":72,"is_outside":2}],"ad":[{"title":"网易云课堂","url":"https://open.163.com/special/discount_pc/","pic":"/uploadfile/xiaohua/20190104/39dbe182a75c687ee2dc6c98cc32ee52.png","aid":48,"is_outside":2}]}
     */
    @Override
    public int getItemType() {
        return 0;
    }

    private int code;
    private String jifen;
    private String message;
    private DataBean data;

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getJifen() {
        return jifen;
    }

    public void setJifen(String jifen) {
        this.jifen = jifen;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public DataBean getData() {
        return data;
    }

    public void setData(DataBean data) {
        this.data = data;
    }

    public static class DataBean implements MultiItemEntity {

        public static final int ONE = 1;

        public static final int TWO = 2;

        public static final int THREE = 3;

        public static final int FOUR = 4;

        public static final int FIVE = 5;

        public static final int SIX = 6;

        public static final int SEVEN = 7;

        private int itemType;

        @Override
        public int getItemType() {
            return itemType;
        }

        public void setItemType(int itemType) {
            this.itemType = itemType;
        }

        private List<XiaohuaBean> xiaohua;
        private List<BlackBean> black;
        private List<BannerBean> banner;
        private List<AdBean> ad;

        public List<XiaohuaBean> getXiaohua() {
            return xiaohua;
        }

        public void setXiaohua(List<XiaohuaBean> xiaohua) {
            this.xiaohua = xiaohua;
        }

        public List<BlackBean> getBlack() {
            return black;
        }

        public void setBlack(List<BlackBean> black) {
            this.black = black;
        }

        public List<BannerBean> getBanner() {
            return banner;
        }

        public void setBanner(List<BannerBean> banner) {
            this.banner = banner;
        }

        public List<AdBean> getAd() {
            return ad;
        }

        public void setAd(List<AdBean> ad) {
            this.ad = ad;
        }

        public static class XiaohuaBean extends DataBean {
            /**
             * title : 喵起来吧～撸猫避免挨揍的正确开撸方式！
             * content : 喵星人性格傲娇，体态优美，毛色美丽、圆脸肉爪确实很容易俘获众人之心。猫咖啡馆深受年轻人的喜爱， 故宫猫、观复猫还成为了文化代言人。那么作为一个猫奴，你撸猫的姿势正确吗？下面我们就来说说猫奴的自我修养——拍猫。很多时候，你就这样和谐的和猫主子这样坐着只是轻轻反复抚摸，也没做什么对吧然而人家却嫌弃的走了。为什么呢？原来这不是猫咪情绪失控，而是它的生理反应，反复抚摸会让他们赶紧想气球一样不断膨胀，涨着涨着就炸了，所以如何解决这个问题呢？第一点：仔细观察，确认猫咪生气的临界点。撸着撸着你可能会看到猫的尾尖开始轻微抽动，然后摆动幅度会升级，这就表示你快要挨揍了！
             * click : 2613
             * pic : /uploadfile/xiaohua/20190104/295f4a2ef569cb9a7cc6cf6fd655c8ec.jpg
             * aid : 59
             * add_time : 2018-11-30 10:48
             * comment_num : 1
             */
            public XiaohuaBean() {
                setItemType(DataBean.FOUR);
            }

            private String title;
            private String content;
            private int click;
            private String pic;
            private int aid;
            private String add_time;
            private int comment_num;

            public String getTitle() {
                return title;
            }

            public void setTitle(String title) {
                this.title = title;
            }

            public String getContent() {
                return content;
            }

            public void setContent(String content) {
                this.content = content;
            }

            public int getClick() {
                return click;
            }

            public void setClick(int click) {
                this.click = click;
            }

            public String getPic() {
                return pic;
            }

            public void setPic(String pic) {
                this.pic = pic;
            }

            public int getAid() {
                return aid;
            }

            public void setAid(int aid) {
                this.aid = aid;
            }

            public String getAdd_time() {
                return add_time;
            }

            public void setAdd_time(String add_time) {
                this.add_time = add_time;
            }

            public int getComment_num() {
                return comment_num;
            }

            public void setComment_num(int comment_num) {
                this.comment_num = comment_num;
            }
        }

        public static class BlackBean extends DataBean {
            /**
             * aid : 30
             * title : 兔子要吃窝边草 二手货物少不了
             * url : http://vhost1035.zihaiweb.cn/index.php/api/index/news
             */
            public BlackBean() {
                setItemType(DataBean.TWO);
            }

            private int aid;
            private String title;
            private String url;

            public int getAid() {
                return aid;
            }

            public void setAid(int aid) {
                this.aid = aid;
            }

            public String getTitle() {
                return title;
            }

            public void setTitle(String title) {
                this.title = title;
            }

            public String getUrl() {
                return url;
            }

            public void setUrl(String url) {
                this.url = url;
            }
        }

        public static class BannerBean extends DataBean {

            public BannerBean() {
                setItemType(DataBean.ONE);
            }

            /**
             * title : 啊啊
             * url : http://vhost1035.zihaiweb.cn/index.php/api/index/news
             * pic : /uploadfile/xiaohua/20181130/f94334567a8ed804c2bf6e44e1ace753.jpg
             * aid : 42
             * is_outside : 2
             */

            private String title;
            private String url;
            private String pic;
            private int aid;
            private int is_outside;

            public String getTitle() {
                return title;
            }

            public void setTitle(String title) {
                this.title = title;
            }

            public String getUrl() {
                return url;
            }

            public void setUrl(String url) {
                this.url = url;
            }

            public String getPic() {
                return pic;
            }

            public void setPic(String pic) {
                this.pic = pic;
            }

            public int getAid() {
                return aid;
            }

            public void setAid(int aid) {
                this.aid = aid;
            }

            public int getIs_outside() {
                return is_outside;
            }

            public void setIs_outside(int is_outside) {
                this.is_outside = is_outside;
            }
        }

        public static class AdBean extends DataBean {
            /**
             * title : 网易云课堂
             * url : https://open.163.com/special/discount_pc/
             * pic : /uploadfile/xiaohua/20190104/39dbe182a75c687ee2dc6c98cc32ee52.png
             * aid : 48
             * is_outside : 2
             */
            public AdBean() {
                setItemType(DataBean.THREE);
            }

            private String title;
            private String url;
            private String pic;
            private int aid;
            private int is_outside;

            public String getTitle() {
                return title;
            }

            public void setTitle(String title) {
                this.title = title;
            }

            public String getUrl() {
                return url;
            }

            public void setUrl(String url) {
                this.url = url;
            }

            public String getPic() {
                return pic;
            }

            public void setPic(String pic) {
                this.pic = pic;
            }

            public int getAid() {
                return aid;
            }

            public void setAid(int aid) {
                this.aid = aid;
            }

            public int getIs_outside() {
                return is_outside;
            }

            public void setIs_outside(int is_outside) {
                this.is_outside = is_outside;
            }
        }
    }
}

**Comment by AllenCoder** [comment]
通过一个数据转换方法，将你的数据结构转换为对应多类型数据结构

**Comment by wangjianfengw** [comment]
> 通过一个数据转换方法，将你的数据结构转换为对应多类型数据结构

什么数据转换方法？

**Comment by 86userused** [comment]
@wangjianfengw  同问
