### ISSUE TITLE
BaseMultiItemQuickAdapter类中的mData为List<Object>

### ISSUE THREAD

**Issue by softrice** [CymChad/BaseRecyclerViewAdapterHelper#275]
描述下我的问题吧.
在使用BaseMultiItemQuickAdapter的时候想得到mData里的某个元素
`this.mData.get(i)`
发现得到的是Object类型.
发现bug出在
![image](https://cloud.githubusercontent.com/assets/10737613/18075180/233dca56-6ea5-11e6-8eb7-c217760d8a1f.png)
改成这样应该就可以了
![image](https://cloud.githubusercontent.com/assets/10737613/18075201/455bec58-6ea5-11e6-9cd0-660f1b8b02c5.png)

**Comment by CymChad** [comment]
![1](https://cloud.githubusercontent.com/assets/7698209/18078081/33850d5e-6ebc-11e6-91b5-6ee675f84e2a.png)

目前源码

**Comment by softrice** [comment]
看来你没明白我的意思 
`public abstract class BaseMultiItemQuickAdapter<T extends MultiItemEntity> extends BaseQuickAdapter {`
这样的写法是等价于
`public abstract class BaseMultiItemQuickAdapter<T extends MultiItemEntity> extends BaseQuickAdapter<Object> {`
所以你上面那个T就是Object
改成
`public abstract class BaseMultiItemQuickAdapter<T extends MultiItemEntity> extends BaseQuickAdapter<T> {`

**Comment by CymChad** [comment]
哦，明白了。

**Comment by CymChad** [comment]
我刚才试了一下，demo的代码，只要继承BaseMultiItemQuickAdapter，写了泛型
![1](https://cloud.githubusercontent.com/assets/7698209/18078883/77cc3d62-6ec0-11e6-815b-2f053fe9f6b9.png)
拿到的data就是你的泛型类型，不会出现拿到obj类型
![2](https://cloud.githubusercontent.com/assets/7698209/18078884/77ccf0e0-6ec0-11e6-8dea-ae80a4dd3cc8.png)

**Comment by softrice** [comment]
我再次确定了下,是拿到Object 
你用的jdk是什么
![27294404-f195-4b3c-93a1-65e6f9192ca1](https://cloud.githubusercontent.com/assets/10737613/18079643/6cd48fb4-6ec4-11e6-8665-0c155b76e89e.png)

**Comment by CymChad** [comment]
1.8

**Comment by softrice** [comment]
我也是1.8 
讲道理 如果是没改过来 不应该可以的

**Comment by CymChad** [comment]
你看下demo，里面的返回。

**Comment by CymChad** [comment]
我这边的问题，貌似我本地改了。

**Comment by CymChad** [comment]
稍等，马上代码上传。打包。

**Comment by softrice** [comment]
嗯嗯

**Comment by CymChad** [comment]
是在不好意思。

**Comment by softrice** [comment]
没事
把这个开源给我节省了很多时间,本来还想自己写一个的.

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.3' 你试一下

**Comment by softrice** [comment]
恩 ok了

**Comment by CymChad** [comment]
感谢你的使用，欢迎多多提好的建议。
