### ISSUE TITLE
多布局下,LayoutId找不到报Resources$NotFoundException: Resource ID #0xfffffe6c 异常. 

### ISSUE THREAD

**Issue by OutlookStarrySky** [CymChad/BaseRecyclerViewAdapterHelper#2750]
你好，关于这个问题 ，

    protected K createBaseViewHolder(ViewGroup parent, int layoutResId) {
        return createBaseViewHolder(getItemView(layoutResId, parent));
    }
   protected View getItemView(@LayoutRes int layoutResId, ViewGroup parent) {
        return mLayoutInflater.inflate(layoutResId, parent, false);
    }

 private int getLayoutId(int viewType) {
        return layouts.get(viewType, TYPE_NOT_FOUND);
    }
我发现出现异常本质上是getItemView（）方法中  mLayoutInflater.inflate（）,如果没有匹配资源ID，就会读取TYPE_NOT_FOUND字段 ，进而出现Resources$NotFoundException异常。我认为是 一个Bug,期望修复。
应该保证即便外界调用没有匹配的资源类型字段，也不至于异常导致应用崩溃。
建议：1.提供try{}catch{}；
           2.或者throwable给调用者处理；
           3.或者 提供外部一个异常的资源id处理方法，比如
            public void onNoMatchingResId(@IdRes int layoutResId){  
                    addItemType(TYPE_NOT_FOUND, layoutResId);
           }
           private int getLayoutId(int viewType) {
              return layouts.get(viewType,layouts.get(TYPE_NOT_FOUND));
         }
希望查看到 及时回复或者修复，谢谢！!!

**Comment by AllenCoder** [comment]
针对这个问题
1. 没有匹配资源ID ,开发期就应该就错误暴露出来，而不应该期望库给你做兜底工作，将错误吃掉，后续的问题更难排查
2. 针对多类型情况，肯定要一一对应资源而不是传入一个错误资源，前期不要做防御性编程才能保证后续的系统的稳健和强壮

**Comment by OutlookStarrySky** [comment]
首先谢谢你提出的思想意见。 
1.我意思不是需要 SDK 做兜底工作，是 希望暴露一个异常处理接口，调用方自己做异常降级处理的。之前架构的话 ，SDK 和客户端都无法处理异常。
2.针对资源错误 ，也不是 非要传入一个错误资源ID ，资源只是一个代名词嘛。

**Comment by LeoCheung0221** [comment]
我觉得这不是我们的问题啊，为啥我的异常跟这位哥们的一模一样，之前都是好的，现在升级了as就有问题，全局都搜索不到这个ID
