### ISSUE TITLE
关于Databinding双向绑定

### ISSUE THREAD

**Issue by qinglok** [CymChad/BaseRecyclerViewAdapterHelper#2751]
假设RecyclerView里的每一项都各自包含一个EditText，
使用Databinding后，因为ViewHolder的机制，只能实现单向的从数据到View，
而不能实现从View到数据（adapter中的数据跟随EditText的值而改变）。
该如何正确地获取？

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
conver再绑定一下
