### ISSUE TITLE
BaseMultiItemQuickAdapter 添加子项数据时，调用setnewdata 页面不刷新

### ISSUE THREAD

**Issue by zzm123456** [CymChad/BaseRecyclerViewAdapterHelper#2752]
BaseMultiItemQuickAdapter 添加子项数据时，调用setnewdata 页面不刷新，手动点击对应的父项才会刷新

**Comment by zzm123456** [comment]
我现在的解决方案是...找到对应的父的position 然后进行collapse和expand 这样能实现刷新 但是感觉有点蠢.....

**Comment by dendrocyte** [comment]
我也是同樣的狀況 需要再對adapter.notifyDataSetChange() 才行

**Comment by xuxh6** [comment]
if (volumeBean.isExpanded()){
                            adapter.collapse(position);
                        }
                        adapter.expand(position,false,true);

可以这样
