### ISSUE TITLE
切换GridLayoutManager，切换列表和网格布局，类似于淘宝，如何做的呢

### ISSUE THREAD

**Issue by RiceRichhonour** [CymChad/BaseRecyclerViewAdapterHelper#2754]
用bravh代码减少了很多，但是切换LinearLayoutManager和GridLayoutManager的时候，布局并不相同，如何设置布局呢。

难道每次都要new新的adapter么，我的adapter有header的

**Comment by AllenCoder** [comment]
建议用多类型 替代吧，通过修改type类型，切换为新的布局样式

**Comment by yishangfei** [comment]
@RiceRichhonour 哥你怎么做的

**Comment by RiceRichhonour** [comment]
> @RiceRichhonour 哥你怎么做的

我同时new了LinearLayoutManager和GridLayoutManager，切换的时候，切换layoutmanager数据切换一下就好了。

**Comment by yishangfei** [comment]
@RiceRichhonour  两个adapter 吗

**Comment by RiceRichhonour** [comment]
> @RiceRichhonour 两个adapter 吗

不需要啊，layoutManager绑定的是recyclerview，adapter继承BaseMultiItemQuickAdapter，切换状态时候，设置数据时候设置不同的itemtype，就可以调用不同的布局。

**Comment by yishangfei** [comment]
@RiceRichhonour  哥方便加个联系方式吗。。。 我尝试了一下还是没写出来

**Comment by yishangfei** [comment]
@RiceRichhonour 哥  会了~

**Comment by HuangJAndroid** [comment]
@RiceRichhonour 那你修改itemtype的值是去遍历数据一一修改吗

**Comment by RiceRichhonour** [comment]
> @RiceRichhonour 那你修改itemtype的值是去遍历数据一一修改吗
是的，遍历一下设置

**Comment by HuangJAndroid** [comment]
那数据多了不会有影响吗

**Comment by HuangJAndroid** [comment]
@RiceRichhonour 那数据多了不会有影响吗

**Comment by RiceRichhonour** [comment]
> @RiceRichhonour 那数据多了不会有影响吗

数据不会很多啊，有翻页，一页也就那么点数据而已，没有影响的。而且全局标记一下itemtype，获取到数据时候就判断设置上。

**Comment by HuangJAndroid** [comment]
@RiceRichhonour 数据多了切换好慢，你又这现象吗

**Comment by RiceRichhonour** [comment]
> @RiceRichhonour 数据多了切换好慢，你又这现象吗

不会，你不分页吗，一页20条，切换无感的，这样吧，我这段代码贴给你

        if (isLiner){
            ry_good.layoutManager =  LinearLayoutManager(activity)

            mList?.let {
                    for (good:GoodBean in it){
                        good.itemType=1
                    }
            }
        }else{
            ry_good.layoutManager =  GridLayoutManager(activity,2)
            mList?.let {
                for (good:GoodBean in it){
                    good.itemType=2
                }
            }
        }

**Comment by HuangJAndroid** [comment]
@RiceRichhonour 现在我翻页加起来列表200条数据，现在要切换，是不是直接改变adapter的全局变量itemtype
