### ISSUE TITLE
使用BaseMultiItemQuickAdapter作为头布局的适配器，第一次加载数据使用setNewData没问题，但是要刷新数据时再次调用setNewData布局没用更新

### ISSUE THREAD

**Issue by chen-krolser** [CymChad/BaseRecyclerViewAdapterHelper#2755]
版本号是2.9.30，
在头布局里面使用BaseMultiItemQuickAdapter，第一次加载数据没问题，当需要跟换数据时再次调用setNewData无效，进不到convert方法里面；
跟新数据使用方法
data.clear();
data.addAll(newdata);
mMultipeAdapter.setData(data);
试过用notifyDataSetChanged()也无效

**Comment by CymChad** [comment]
替换头部呢？

**Comment by CymChad** [comment]
如果是放在头部的rv，再次更新需要获取到rv的空间重新setNewData才行。
