### ISSUE TITLE
我在购物车中使用了这个adapter  下面还有一个和 购物车无关的列表 所以我使用了BaseMultiItemQuickAdapter，购物车头部和商品两种 所以我使用了BaseSectionQuickAdapter ，使用完之后发现对item进行点击跳转，多点几次跳转就有明显的卡顿

### ISSUE THREAD

**Issue by sweeterHoney** [CymChad/BaseRecyclerViewAdapterHelper#2756]
public class ShopCartProAdapter extends BaseMultiItemQuickAdapter<MultipleShopCartBean, BaseViewHolder> {}

public class ShopCartHeadAdapter extends BaseSectionQuickAdapter<SingleShopCartBean, BaseViewHolder> {

一个页面 第一个adapter里面的redcycle使用了下面的那个adapter

**Comment by AllenCoder** [comment]
用分析工具检查一下代码的耗时，不要在convert方法里面做计算和io的任务

**Comment by LiQinglin007** [comment]
除了自己计算，有没有比较好的方式能拿到父类的pos和子类的pos?

**Comment by sweeterHoney** [comment]
不是有个adapter.getxxposition 我记得是这个样子的呢
.......


------------------ 原始邮件 ------------------
发件人: "liqinglin"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 中午1:55
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "空口无凭。"<1621059932@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 我在购物车中使用了这个adapter  下面还有一个和 购物车无关的列表 所以我使用了BaseMultiItemQuickAdapter，购物车头部和商品两种 所以我使用了BaseSectionQuickAdapter ，使用完之后发现对item进行点击跳转，多点几次跳转就有明显的卡顿 (#2756)




除了自己计算，有没有比较好的方式能拿到父类的pos和子类的pos?
