### ISSUE TITLE
Scrollview ，以及NestedScrollview嵌套recyclerview

### ISSUE THREAD

**Issue by qiangzengli** [CymChad/BaseRecyclerViewAdapterHelper#2758]
在scrollview中嵌套recyclerview ，使用树形结构，导致recyclerview高度不能动态改变（即，只能显示到第一项有的高度，展开子菜单不能继续往下滑动）
在nestedScrollview中嵌套，会导致滚动后只有点击第二次才能相应点击事件（初步判断是滚动后recyclerview失去了焦点）

**Comment by shichaohui** [comment]
NestedScrollview 滚动后首次点击事件可能无效，这个貌似是 NestedScrollview 的 bug。
