### ISSUE TITLE
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by kamaelyoung** [CymChad/BaseRecyclerViewAdapterHelper#2760]
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true

**Comment by 1109993488** [comment]
数据更新后没有及时调用`notifyDataSetChanged()`
如果还有疑问请详细描述你的问题再次打开
