### ISSUE TITLE
Holder width and height setting dynamically

### ISSUE THREAD

**Issue by dendrocyte** [CymChad/BaseRecyclerViewAdapterHelper#2762]
若使用原生的Recyclerview.Adapter 可以達成設定holder 的高度 是整個recyclerview的1/3
```
public Holder onCreateViewHolder(@NonNull ViewGroup viewGroup, int viewtype) {
     //set the holder height or width here
   View view = getLayoutInflater().inflate(R.layout.title, viewGroup,false);
   view.getLayoutParams().height = (viewGroup.getHeight()) / 3;
   return new Holder(view);
}
```

但若使用BaseQuickAdapter 該如何達成這個需求？
純粹去override onCreateViewHolder() 會出現
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean)' on a null object reference`

**Comment by yangfeng1994** [comment]
在 item的convert方法里，对item进行高度的操作。
  ViewGroup.LayoutParams layoutParams = helper.itemView.getLayoutParams();
                layoutParams.height= layoutParams.height / 3;

或者将 item的布局设置为match_parent ，然后在 item的convert方法里，对item进行高度的操作。
  ViewGroup.LayoutParams layoutParams = helper.itemView.getLayoutParams();
                layoutParams.height =屏幕高度/ 3;
