### ISSUE TITLE
loadMoreEnd时遇到的问题，希望重视

### ISSUE THREAD

**Issue by WanMMao** [CymChad/BaseRecyclerViewAdapterHelper#2767]
当我上拉加载一直到没有更多数据的时候调用loadMoreEnd方法，这时将没有更多数据显示出来，然后我再次下拉刷新完成后调用loadMoreComplete 或者loadMoreEnd(true)都不生效，没有更多数据还是显示在那，并且setEnableLoadMore(true)也无法生效。但是我尝试new Handler().postDeloy()延迟一秒执行loadMoreComplete，setEnableLoadMore(true)这几个方法显示就正常了。请问这是什么问题，能否探讨一下呢

**Comment by AllenCoder** [comment]
参考一下demo的上拉加载试试  [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/UpFetchUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/UpFetchUseActivity.java)

**Comment by conghuahuadan** [comment]
我找到可能触发此问题的原因，楼主是不是先loadMoreXXX，然后再addData和notifyDataSetChanged，把顺序调换下就可以了
