### ISSUE TITLE
load a lot of data into adapter

### ISSUE THREAD

**Issue by dendrocyte** [CymChad/BaseRecyclerViewAdapterHelper#2768]
目前有一個需求是要將資料放入recyclerview. adapter
但從網路抓資料含圖 有200多筆
抓到的資料會放進recycler view
但這樣會有嚴重delay狀況

目前google 推出 paging的架構
需要改動到adapter
但已經使用了BaseQuickAdapter
很喜歡BaseQuickAdapter的封裝 clean code
不知道是否有考慮推出一個一次要load很多資料的 adapter ?

**Comment by CymChad** [comment]
收到 ，如果是bug请你根据规范提问 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2807 我们将快速处理。
如果是新需求请提交到 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2806 我们会排期迭代。
