### ISSUE TITLE
onItemChildClick点击事件问题

### ISSUE THREAD

**Issue by guyunke123** [CymChad/BaseRecyclerViewAdapterHelper#2769]
onItemChildClick 方法
在item remove的过程中任然可以点击 getLayoutPosition() = -1，所以getClickPosition() =0 位置不对
会出现点击错误，建议getLayoutPosition()这种获取位置的方法加上大于0判断

bindViewClickListener调用OnItemClickListener的时候也有这个问题，只是可以重写setOnItemClick方法，
加载了getLayoutPosition()>0判断

**Comment by AllenCoder** [comment]
嗯，建议不错，请问一下，复现情形，remove的过程中，同时点击？是在移动中，同时点击吗？

**Comment by guyunke123** [comment]
remove有个自带的动画，动画过程是可以点击item的。

还有，建议多一个viewHolder创建成功的回调方法，这样子子类复写，添加点击事件的listener就可以在这个方法中绑定一次，而不用covnert方法中每次new onClickListener创建对象

**Comment by passin95** [comment]
我这边也遇到了类似的问题，它可能导致更不好的结果，当移除或添加的操作存在的情况下，在快速点击的情况下，会响应多次（一般是2次）点击事件，且 position 是不一样的。
例如我点击 position 为 1 的子 item，它的代码是移除自己。如果我快速点击2次，会回调 adapter 的 OnItemChildClickListener 2次，第一次的 position 为 1（正常的），第二次的 position 为 0（不正常的）。我的建议是要不要在 adapter 加一个禁止快速点击的重写方法，默认情况下是禁止快速点击的。

**Comment by AllenCoder** [comment]
快速点击事件的消抖，应该在业务层处理，框架层如果过滤掉了，会影响其他使用者快速点击的情形

**Comment by passin95** [comment]
但我觉得快速点击造成的结果，可以理解为 BUG，从某种意义上讲，框架层面返回了一个错误的 position（快速点击中得到的position 并不正确，View 理论上已经从recyclerView 移除，却因快速点击返回了view 前一个位置的 position），并且我觉得绝大部分情况，使用者都希望返回一个正确的结果。
