### ISSUE TITLE
Viewpager+fragment，懒加载报错：java.lang.IllegalStateException：The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by userPeng** [CymChad/BaseRecyclerViewAdapterHelper#277]
# java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

fragmentA在使用BaseRecyclerViewAdapterHelper加载数据结束时调用方法`mAdapter.addFooterView(view_nodatas);
                        mAdapter.loadComplete();`     之后切换到其他界面销毁掉fragmentA，再进入fragmentA的时候出现以上报错信息，之后查情况调用方法`mAdapter.removeAllFooterView();`  但是还是会有以上信息

**Comment by shichaohui** [comment]
切到其他界面就销毁掉的话，应该不会存在旧的view和adapter，建议贴上代码看看。

**Comment by userPeng** [comment]
FragmentA--onCrete():
`           mSwipeRefreshLayout.setRefreshing(true);
            isFirst = true;
            mRecyclerView.setLayoutManager(new LinearLayoutManager(MyApplication.getContext()));
            mAdapter = new RecordAdapter(R.layout.record_recycleview_item, mAllDatas);
            mAdapter.removeAllFooterView();
            mRecyclerView.setAdapter(mAdapter);
            LoadData(0, 1);`


`private void LoadData(int type, final int page) {
‘’‘在加载完数据的地方'''
                        mAdapter.removeAllFooterView();
                        mAdapter.addFooterView(view_nodatas);
                        mAdapter.loadComplete();
                        pageNum = 1;
‘’‘’’
}
`

**Comment by userPeng** [comment]
基本代码都是按照demo写的,但是在销毁之后重新加载到`mAdapter.addFooterView(view_nodatas);`就会出现奔溃，奔溃信息如标题

**Comment by shichaohui** [comment]
你的问题应该是根#261一样的，建议你看一下我写的那串代码。

**Comment by userPeng** [comment]
一样奔溃了

**Comment by shichaohui** [comment]
你是怎么切换Fragment的？切换的时候做了什么操作？为什么你销毁了Fragment之后还有持有旧的view和adapter呢？

**Comment by lijunguan** [comment]
应该是和我遇到的一样，ViewPager 管理 并没有销毁Fragment， 生命周期是从onCreateView ()到destoryView()  没有执行onCraate() 和 onDestory() ,  我是定义的基类，在onCreate()方法  初始化了headerView footView loadingView 等。 就会出现这个问题， 不知道算不算是这个 项目的bug。   想要不出问题，就必须让Adapter的创建   inflate headerView footView 等在  onCreateView()方法或其他生命周期方法中（就是要做ViewPager 切换 恢复时 会执行的一个生命周期方法中）@userPeng @shichaohui

**Comment by shichaohui** [comment]
就必须让Adapter的创建 inflate headerView footView 等在 onCreateView()方法或其他生命周期方法中就相当于重新创建这些对象了，肯定不会有错。
现在分析一下这个异常的产生：切换前初始化footerView并调用addFooterView()方法添加到adapter，此时footerView已经有parent。然后切换页面再切换回来，切换后footerView没有任何改变（即和切换前是同一个对象），然后又添加这个footerView到adapter，结果导致上述异常。
解决方案：正常情况下parent.removeView()就能解决问题了，removeAllFooterView()方法中已经封装了该方法，但是 @userPeng 提出removeAllFooterView()无效，即footerView并没有被从parent中删除，我认为产生这种情况的原因只有一个，那就是你们的adapter已经不是原来的adapter对象了，所以remove才是无效的。

**Comment by userPeng** [comment]
首先，我先声明我在的程序是在onCreateView()中执行，并且之前说的销毁是有走onDestory()方法的； @lijunguan 
之后我按照 @shichaohui 的情况测试了一下mAdapter：
                        `//没有更多数据`
                        `System.out.println("前：" + mAdapter.getFooterLayoutCount() + "   " + mAdapter);`
                        `mAdapter.removeAllFooterView();`
                        `mAdapter.addFooterView(view_nodatas);`
                        `System.out.println("后：" + mAdapter.getFooterLayoutCount() + "   " + mAdapter);`
                        `Toast.makeText(MainActivity.context, "没有更多数据", Toast.LENGTH_SHORT).show();`
                        `mAdapter.loadComplete();`
控制台：
System.out: 前：0   com.ignite.funmoney.adapter.RecordAdapter@41c71920
System.out: 后：1   com.ignite.funmoney.adapter.RecordAdapter@41c71920
切换出去之后切换回来
System.out: 前：0   com.ignite.funmoney.adapter.RecordAdapter@4229ca10
奔溃。。。

打印出来的Log信息，说明在切换回来后Adapter是新建出来的对象，并且他的FooterView已经为0了，但是报错信息是讲我之前已经添加过一次，现在我该怎么fix该问题？

**Comment by shichaohui** [comment]
@userPeng 旧的footerView已经添加到旧的adapter中了，所以不管Adapter是不是新的都会报错。
现在有两种解决方案：
1. ((ViewGroup) footerView.getParent()).removeView(footerView);
    只重用footerView，不重用adapter的话，可以用这种方式把footerView从其parent中移除。
2. 如果footerView和adapter都要重用，可以使用adapter.removeFooterView()方法，但是要保证adapter对象没有改变，可以用判断对象是否为null的方式防止多次初始化，可参考 #261 。

**Comment by userPeng** [comment]
其实我跟偏向嗲用方法removeAllFooterView()  来解决这个bug，不过以上2个解决方案确实行得通，感谢 @shichaohui 细心解答
`if (footerView.getParent() != null) {
                            ((ViewGroup) footerView.getParent()).removeView(footerView);
                        }`
star+++

**Comment by zkq49099** [comment]
卧室在onDestroyView方法中
     if (mAdapter != null) {
            mAdapter.removeAllHeaderView();
            mAdapter = null;
        }
就可以了，谢谢各位帮助 @shichaohui
