### ISSUE TITLE
怎么去除header,footer等item的DividerItemDecoration

### ISSUE THREAD

**Issue by wy7217** [CymChad/BaseRecyclerViewAdapterHelper#2770]
版本号 2.9.45-androidx
添加DividerItemDecoration后 我在getItemOffsets中判断当前view的itemViewType是 BaseQuickAdapter.FOOTER_VIEW或者BaseQuickAdapter.HEADER_VIEW后调用 outRect.set(0, 0, 0, 0) 并return；
HEADER_VIEW下方的分割线成功去除了 但是FOOTER_VIEW下方的分割线始终存在 
请问有什么解决方案吗？
谢谢

**Comment by AllenCoder** [comment]
两种分案
1 .通过判断footview的位置，当postion 为最后一个view时 ，不设置分割线。
2. 直接在每个itemview上设置分割线的样式

**Comment by shenjiabing** [comment]
版本号 2.9.40
添加DividerItemDecoration的时候
public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state){
       int itemView=parent.getChildLayoutPosition(view);
    LogUtil.e("GridSpacingItemDecoration","============"+itemView);
 }
 我在getItemOffsets中，打印itemView，如果加了头部布局  会有2个0，出现，如果没有头部布局，就只有一个0，导致我做瀑布流的计算有问题，有没有办法判断，哪一个是头部布局
