### ISSUE TITLE
适配一下 ListAdapter，带DiffUtil的

### ISSUE THREAD

**Issue by Lans** [CymChad/BaseRecyclerViewAdapterHelper#2771]
package androidx.recyclerview.widget;
 
* Advanced users that wish for more control over adapter behavior, or to provide a specific base
 * class should refer to {@link AsyncListDiffer}, which provides custom mapping from diff events
 * to adapter positions.
 *
 * @param <T> Type of the Lists this Adapter will receive.
 * @param <VH> A class that extends ViewHolder that will be used by the adapter.
 */
public abstract class ListAdapter<T, VH extends RecyclerView.ViewHolder>
        extends RecyclerView.Adapter<VH> {
    private final AsyncListDiffer<T> mHelper;

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/DiffUtil#diffutil

**Comment by limuyang2** [comment]
已完成，请等待新版本发布
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pull/2808
