### ISSUE TITLE
ExpandableAdapter.expandAll() , expanded but now show in UI

### ISSUE THREAD

**Issue by tantai24495** [CymChad/BaseRecyclerViewAdapterHelper#2774]
**Describe the bug**
My adapter is extend from BaseMultiItemQuickAdapter
Click fragment A -> fragment B.
Fragment B, i run these code below:

      `expandAdapter = ExpandAdapter(listMultiItem) (listMultiItem surely have data)
      recycler_view.adapter = expandAdapter
      recycler_view.layoutManager = LinearLayoutManager(context)
      expandAdapter.expandAll()`

Everything worked fine, every items expanded as i want.

Back to fragment A then go back to fragment B.
**expandAdapter.expandAll()** don't show the expanded item on UI, it only show the header of the item.
If i click that header 2 times, it will expand

Please help, I'm appreciate a lot , i'm stuck with this for almost 3 days :((

**Expected behavior**
Expand item

**Comment by tantai24495** [comment]
I found an answer.
I used adapter.collapse(position) before expand and everything worked again.
Note: Should collapse position from backward, and expand from backward to forward

**Comment by CymChad** [comment]
thanks your answer

**Comment by OilLyu** [comment]
> I found an answer.
> I used adapter.collapse(position) before expand and everything worked again.
> Note: Should collapse position from backward, and expand from backward to forward

thanks your anser
