### ISSUE TITLE
头部轮播图滚动

### ISSUE THREAD

**Issue by bananaskin2019** [CymChad/BaseRecyclerViewAdapterHelper#2775]
首先感谢作者提供这个库
我这里的问题是：
banner作为recyclerview的头布局
当banner从不可见到可见时，
第一次自动切换图片是没有滚动动画，而是直接替换，
然后第二次切换图片才有滚动动画。
ps:不知道算不算问题

**Comment by yangfeng1994** [comment]
是不是你的RecyclerView抢占了焦点，你在父布局添加     android:focusable="true"  
        android:focusableInTouchMode="true" 试试，应该是焦点抢占的原因，或者在你的动画监听里面，看看有没有走相应的方法
