### ISSUE TITLE
请问大神  继承BaseQuickAdapter之后的根据条件来显示或者隐藏item的问题

### ISSUE THREAD

**Issue by wcglws** [CymChad/BaseRecyclerViewAdapterHelper#278]
public class ConsultHomeAdapter extends BaseQuickAdapter<ConsultHomeBean.DataBean.ArticlesBean> {
    public ConsultHomeAdapter(List<ConsultHomeBean.DataBean.ArticlesBean> dataBeanArticles) {
        super(R.layout.stock_news_item, dataBeanArticles);
    }

    @Override
    protected void convert(BaseViewHolder baseViewHolder, ConsultHomeBean.DataBean.ArticlesBean articlesBean) {
        //在这能不能根据item的位置来显示或者隐藏相应item中的子view（比如position==0的时候，让R.id.tv_people这个view隐藏）；如果不能的话，这个需求在哪可以实现呢？
        baseViewHolder.setText(R.id.tv_time, string2Date(articlesBean.getCreated_at()))
                .setText(R.id.tv_people, articlesBean.getSource())
                .setText(R.id.tv_message, articlesBean.getTitle());

    }

**Comment by CymChad** [comment]
baseViewHolder.getLayoutPosition拿到当前position。建议你最好不要这样，有可能出现缓存问题。你可以通过实体类的一个属性来控制是否隐藏显示。写个if else
