### ISSUE TITLE
添加Header为自动轮播时，getItemType一直调用，把header去掉就没事了

### ISSUE THREAD

**Issue by csaj** [CymChad/BaseRecyclerViewAdapterHelper#2780]
在adapter 添加head为banner 自动播放时，getItemType会一直调用

**Comment by AllenCoder** [comment]
轮播图自动播放时，是否一直频繁调用了adapter.notifyDataSetChanged()?

**Comment by csaj** [comment]
> 轮播图自动播放时，是否一直频繁调用了adapter.notifyDataSetChanged()?

没有，是每次自动获取焦点时，就会调用，没有调用notifyDataSetChanged()

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2807

**Comment by AttackPangHu** [comment]
> > 轮播图自动播放时，是否一直频繁调用了adapter.notifyDataSetChanged()?
> 
> 没有，是每次自动获取焦点时，就会调用，没有调用notifyDataSetChanged()

你問題解決了嗎？我也有同樣的問題
