### ISSUE TITLE
一个局部刷新的功能多久了还没有？

### ISSUE THREAD

**Issue by Eveninger** [CymChad/BaseRecyclerViewAdapterHelper#2781]
好多人提了这个需求，已经一年多了，还不愿意加进来。又不是很复杂的功能，为什么不能封装到库里，通过统一的形式提供使用。有人做了这个功能，提交了PR也不接受，做这个库的目的不就是提升开发效率，节约开发时间吗？为什么还要用的人自己去手动在做这件事呢？

**Comment by helloworkcupid** [comment]
臣附议。。。局部刷新也是经常用的

**Comment by RuoYuHoney** [comment]
额。。。不是可以吗。。。。。。。是你不会用吧。

**Comment by AllenCoder** [comment]
局部刷新指的是recyclerview的diffutil吗？如果是的话，之前的两个pr确实没有被合并，
(https://github.com/CymChad/BaseRecyclerViewAdapterHelper/pulls?utf8=%E2%9C%93&q=%E5%B1%80%E9%83%A8%E5%88%B7%E6%96%B0)
[原因有两个]
1. 提交的pr格式不规范，导致大量的代码变动，无法正常review代码，无法确认是否有重大bug
2. 提交的pr没有相关的sample用法，导致新特性无法确认使用方法

在此，也非常抱歉，由于工作变动，自己的空闲时间被压缩的极少，bug性问题，会紧急跟进修复，新特性功能的开发，时间会延后，也非常期待能有优秀的pr提交

**Comment by limuyang2** [comment]
```kotlin
/**
     * 局部数据更新
     * @param diffCallback
     */
    public void setDiffData(BaseDiffCallback<T> diffCallback) {
        if (getEmptyViewCount() == 1) {
            setNewData(diffCallback.newData);
            return;
        }
        DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(diffCallback);
        diffResult.dispatchUpdatesTo(this);
        mData = diffCallback.newData;
    }
```

这是我修改源码，简单封装的

**Comment by gaohequan** [comment]
臣附议

**Comment by protectedMan** [comment]
俺也一样

**Comment by AllenCoder** [comment]
新特性已经开发完成，即将发布

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/DiffUtil#diffutil
