### ISSUE TITLE
关于懒加载，加载过的fragment切换后会空白

### ISSUE THREAD

**Issue by Lee380822516** [CymChad/BaseRecyclerViewAdapterHelper#2783]
我最原始的方法构建Adapter，没有任务问题
用该库的BaseQuickAdapter就会出现加载过的fragment，切换（现在A切换到B，B切换到C，A就空白了，A切换到B，B到A，是正常的）后空白

**Comment by AllenCoder** [comment]
加载过的fragment被回收导致空白，BaseQuickAdapter没有对view的加载做过特殊处理，建议查看是否是recyclerview复用或者内存不足回收了fragment导致的空白，进一步排查问题

**Comment by limuyang2** [comment]
可否提供一份你的demo

**Comment by CymChad** [comment]
请根据规范提问 #2807
