### ISSUE TITLE
When init adapter,refersh recycleView

### ISSUE THREAD

**Issue by sjw903** [CymChad/BaseRecyclerViewAdapterHelper#279]
When I set setOnLoadMoreListener on InitAdapter, It will call listener
how can I set it when I init it, do not refersh recycleview

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Pull-up-to-loadMore

**Comment by sjw903** [comment]
我的意思是说,我在初始化的时候,不想让它触发刷新的动作,在我需要的时候再开始刷新

**Comment by sjw903** [comment]
这个问题在１.９.８版本上没有这个问题

**Comment by CymChad** [comment]
你是意思是，一进来就调用了setOnLoadMoreListener？如果是这样的话，你通过openLoad More设置一下pageSize。

**Comment by sjw903** [comment]
对啊,在初始化的时候,就设置了setOnLoadMoreListener,但是那个BaseQuickAdapter的构造函数那个第二个参数(List<T> data),我设置的是null,因为刚开始的时候没有数据,需要触发才能不断的加载数据!这个是用来加载下一页的数据来的!感谢你的回答!

**Comment by CymChad** [comment]
问题解决没？

**Comment by sjw903** [comment]
新版本有这个问题,在1.9.8这个版本没有,还存在！

**Comment by CymChad** [comment]
贴一下你的代码

**Comment by sjw903** [comment]
mQuickWithdrawListAdapter = new QuickWithdrawListAdapter(null);
        mQuickWithdrawListAdapter.openLoadAnimation(2);
        mWithdrawRecyclerView.setAdapter(mQuickWithdrawListAdapter);
        mQuickWithdrawListAdapter.setOnLoadMoreListener(() -> mWithdrawRecyclerView.post(() -> {
            int currentCount = mQuickWithdrawListAdapter.getItemCount();
            if (currentCount >= mWithdrawTotalCount) {
                if (null == mNotWithdrawLoadingView) {
                    mNotWithdrawLoadingView = LayoutInflater.from(getContext()).inflate(R.layout.layout_not_loading, (ViewGroup) mWithdrawRecyclerView.getParent(), false);
                }
                mQuickWithdrawListAdapter.addFooterView(mNotWithdrawLoadingView);
                mQuickWithdrawListAdapter.notifyDataChangedAfterLoadMore(false);
            } else {
                String beginTime = mBeginText.getText().toString();
                String endTime = mEndText.getText().toString();
                if (!TextUtils.isEmpty(beginTime) && !TextUtils.isEmpty(endTime)) {
                    QueryTime queryTime = CommonUtil.getQueryTime(beginTime, endTime);
                    withdrawRecordRequest(queryTime, false);
                }
            }
        }));


public class QuickWithdrawListAdapter extends BaseQuickAdapter<WithdrawInfo> {
    public QuickWithdrawListAdapter(List<WithdrawInfo> data) {
        super(R.layout.withdraw_list_item, data);
    }

    @Override
    protected void convert(BaseViewHolder baseViewHolder, WithdrawInfo withdrawInfo) {
        baseViewHolder.setText(R.id.tv_serialnumber, withdrawInfo.getSerialnumber());
        baseViewHolder.setText(R.id.tv_money, withdrawInfo.getMoney());
        baseViewHolder.setText(R.id.tv_pay_time, withdrawInfo.getTime());
        baseViewHolder.setText(R.id.tv_state, withdrawInfo.getState());
    }
    @Override
    public BaseViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        BaseViewHolder baseViewHolder = super.onCreateViewHolder(parent, viewType);
        AutoUtils.autoSize(baseViewHolder.getConvertView());
        return baseViewHolder;
    }
}

**Comment by CymChad** [comment]
需要设置一下 mQuickAdapter.openLoadMore(PAGE_SIZE);

**Comment by CymChad** [comment]
PAGE_SIZE 为每页显示的数量。只要超过这个数量才会触发setOnLoadMoreListener

**Comment by sjw903** [comment]
我开始不想用,需要设置0么?



sjw903@sohu.com
 
From: 陈宇明
Date: 2016-08-31 10:03
To: CymChad/BaseRecyclerViewAdapterHelper
CC: sjw903; Author
Subject: Re: [CymChad/BaseRecyclerViewAdapterHelper] When init adapter,refersh recycleView (#279)
需要设置一下 mQuickAdapter.openLoadMore(PAGE_SIZE);

**Comment by CymChad** [comment]
默认是0，0的话一进来就会调用setOnLoadMoreListener，如果不想一进来就调用的话，就设置一个数量，因为调用规则，是通过这个数值来进行判断的。通常设置一页的数量，超过一页的数量后就会调用setOnLoadMoreListener。

**Comment by sjw903** [comment]
不想在初始化的时候,就让它刷新,我可以在调用的地方去设置setOnLoadMoreListener,但是这个就总会被设置,如果这个接口能可以调用的话,就好了,就可以判断它为不为空,就可以不用每次都设置它了!
还有,我想问下,那个底部的玩命加载中...的那个view,可以让用户去调用就好了,因为在刷新的过程中,如果网络不好,这个提示就会一直存在!

**Comment by CymChad** [comment]
openLoadMore 这个只需要设置一次就好了。网络异常可以调用showLoadMoreFailedView();，具体更多方法的使用你可以查看https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD

**Comment by CymChad** [comment]
demo都有具体使用代码，你可以参考一下 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java

**Comment by CymChad** [comment]
还有其他的问题吗？

**Comment by sjw903** [comment]
有一个问题,那个正在加载中...的那个view,我们控制它消失的时间么?因为有的时候,在网络不可访问的时候,这个提示会一直存在!

**Comment by CymChad** [comment]
1.9.8  你通知为false就自动消失了，2.0 你通知它加载完毕就消失了，这样就无法上拉刷新的。如果你要提示后可以点击再次上拉刷新你可以showLoadMoreFailedView

**Comment by sjw903** [comment]
谢谢！
