### ISSUE TITLE
onLoadMoreRequested只回调了一次

### ISSUE THREAD

**Issue by wangyuan0217** [CymChad/BaseRecyclerViewAdapterHelper#2791]
项目中遇到这个问题，后单独写了测试项目验证。设置了加载更多，App进入首先加载10条数据，上滑这个时候回回调onLoadMoreRequested并开始加载第二页数据，继续上滑到最下面一直显示加载更多的loading也不走onLoadMoreRequested的回调。

以下是新项目测试部分代码
![image](https://user-images.githubusercontent.com/12730214/59753821-820be980-92b7-11e9-87f8-f5ccee7671f9.png)
![image](https://user-images.githubusercontent.com/12730214/59753862-994ad700-92b7-11e9-825d-9dc1001a57d2.png)
`import android.os.Bundle
import android.os.Handler
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import com.chad.library.adapter.base.BaseQuickAdapter
import com.chad.library.adapter.base.BaseViewHolder
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    private var adapter: ThisAdapter? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        adapter = ThisAdapter()
        adapter?.setEnableLoadMore(true)
        adapter?.setOnLoadMoreListener({
            Handler().postDelayed({ adapter?.addData(mock()) }, 1000)
        }, recyclerview)

        recyclerview.layoutManager = LinearLayoutManager(this)
        recyclerview.adapter = adapter

        adapter?.setNewData(mock())
    }

    private fun mock(): ArrayList<String> {
        return arrayListOf("", "", "", "", "", "", "", "", "", "")
    }

    inner class ThisAdapter : BaseQuickAdapter<String, BaseViewHolder>(
        R.layout.item,
        ArrayList<String>()) {

        override fun convert(helper: BaseViewHolder, item: String) {
            helper.setText(R.id.text, helper.adapterPosition.toString())
        }
    }
}`

**Comment by AllenCoder** [comment]
加载更多参考 demo写法 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)

**Comment by TylerWang1110** [comment]
loadMore完成后需要调用loadMoreComplete()
