### ISSUE TITLE
使用BaseMultiItemQuickAdapter做二级列表条目显示错乱

### ISSUE THREAD

**Issue by YuPf1989** [CymChad/BaseRecyclerViewAdapterHelper#2792]
lib_version：2.9.44 
是这样，做一个类似于qq分组的二级列表，一共有三个分组，分别打开第一个和第二个分组，此时关闭第二个分组数据，发现第二个分组title跑到第一个分组子条目上边了，始终找不到原因，求助大神。。。

**Comment by MagicKim** [comment]
数据出现问题了?你对着demo里面的例子看看.

**Comment by YuPf1989** [comment]
一开始我数据源是没问题的啊，只有按那种操作才会出问题，同时打开分组一和分组二，这时关闭分组二，分组二的title pos就发生了变化，实际是不应该发生变化的，只是分组二及其下边的title发生了展开或者折叠

**Comment by YuPf1989** [comment]
`fun getAddressBookData(): List<MultiItemEntity> {
        val lv0Count = 5
        val personCount = 5
        val data = ArrayList<ExpandableAddressBook>()
        for (i in 1..lv0Count) {
            val expandableData = ExpandableAddressBook("组织处$i")
            for (j in 1..personCount) {
                expandableData.addSubItem(AddressBookPerson("user$j"))
            }
            data.add(expandableData)
        }
        return data
    }`

`data class ExpandableAddressBook(
    val title: String
) : AbstractExpandableItem<AddressBookPerson>(), MultiItemEntity {
    override fun getItemType(): Int {
        return ExpandableAddressBookAdapter.TYPE_LEVEL_0
    }

    override fun getLevel(): Int {
        return ExpandableAddressBookAdapter.TYPE_LEVEL_0
    }

}`

`data class AddressBookPerson(
    val userName: String,
    val userIcon:String = "",
    val userIconId:Int = R.mipmap.ic_launcher_round
) : MultiItemEntity {
    override fun getItemType(): Int {
        return ExpandableAddressBookAdapter.TYPE_PERSON
    }
}`

这哪里存在问题吗？

**Comment by MagicKim** [comment]
@YuPf1989 额,对kt语法不了解,我的项目现在在用折叠列表,没有出现你说的这种情况

**Comment by YuPf1989** [comment]
没办法，后来我用expandablelistview做了，没出现问题，就是麻烦点……

**Comment by woyoudianhuai** [comment]
我也是同样的问题，望排查一下
