### ISSUE TITLE
SectionMultipleItemAdapter有办法获取item在section中的position吗？

### ISSUE THREAD

**Issue by wxyjevol** [CymChad/BaseRecyclerViewAdapterHelper#2793]
RT

**Comment by AllenCoder** [comment]
参考示例  [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/MultipleItemRvAdapterUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/MultipleItemRvAdapterUseActivity.java)
