### ISSUE TITLE
How to use CompoundDrawablePadding()

### ISSUE THREAD

**Issue by 957919019** [CymChad/BaseRecyclerViewAdapterHelper#2798]
How to use CompoundDrawablePadding()?
Here is a TextView i must add a drawable to it right,how shoule i do?

我需要在一个TextView右侧加一张图，希望调用CompoundDrawablePadding()来设置，但是似乎没有找到对应的方法，请指教

**Comment by yangfeng1994** [comment]
You can directly get the TextView object, and then operate on the TextView.
你直接获取TextView的对象，然后对TextView进行操作就行了
