### ISSUE TITLE
分组布局的用法时，如何能快速取到这一组下面的所有child数据呢？

### ISSUE THREAD

**Issue by Lsy1992** [CymChad/BaseRecyclerViewAdapterHelper#2799]
例如A B C 三个分组，如何通过一个简单的方法获取A分组内的所有子数据，而不是自己在根据组名称遍历？ 谢谢

**Comment by 1109993488** [comment]
AbstractExpandableItem<Object> item = (AbstractExpandableItem<Object>) getItem(position);
List<Object> subItems = item.getSubItems();
你想要的是这样的吗?

**Comment by QiaoYang0923** [comment]
> 例如A B C 三个分组，如何通过一个简单的方法获取A分组内的所有子数据，而不是自己在根据组名称遍历？ 谢谢

找到解决方法了吗
