### ISSUE TITLE
一次性加载三千多条数据，很慢，如何优化或者回调个加载进度百分比也行

### ISSUE THREAD

**Issue by dary123** [CymChad/BaseRecyclerViewAdapterHelper#2800]
一次性加载三千多条数据，很慢，如何优化或者回调个加载进度百分比也行

**Comment by zhengyi0049** [comment]
这么多数据 该加分页了 不是可以优化就能处理的

**Comment by dary123** [comment]
那能不能给个进度百分比

**Comment by dary123** [comment]
因为这边要做联系人，必须一次性加载这么多，公司要求显示个百分比

**Comment by dary123** [comment]
> 这么多数据 该加分页了 不是可以优化就能处理的

那能不能获取到进度百分比

**Comment by dary123** [comment]
> 这么多数据 该加分页了 不是可以优化就能处理的

因为这边要做联系人，必须一次性加载这么多，公司要求显示个百分比

**Comment by AllenCoder** [comment]
1. 加载3000多条，跟你的布局设计有关，如果recyclerview就是父层级，每次只会渲染当前屏幕区域的内容，加载速度应该是非常快的，你的数据量大小影响不会太大
2. 如果recyclerview 还有一个父布局，且父布局是类似于scrollview 这种父布局，就会导致recyclerView无法准确测量出布局高度，会导致一次性加载完毕，这种是非常不可取的，如果强行这么做，只需要判断 conver方法内部的回调position即可知道加载进度

**Comment by AllenCoder** [comment]
获取3000条数据，这个应该是一个耗时的任务吧，应该通过异步方式，可以分批次获取，然后加载recyclerview的视图

**Comment by dary123** [comment]
> 获取3000条数据，这个应该是一个耗时的任务吧，应该通过异步方式，可以分批次获取，然后加载recyclerview的视图

异步的方式不可行，因为这边涉及到类似微信联系人那样的字母索引，分批次会导致排序问题，目前recyleview外层没有scrollview这样的布局，外层只有个LinearLayout，再外层就是SwipeRefreshLayout，你说的conver方法我加了Log日志打印，发现只会打印屏幕可见范围类的item，不可见的item convert不会回调，往下滑动才会回调，跟recyleview的复用缓存机制有关

**Comment by dary123** [comment]
> 1. 加载3000多条，跟你的布局设计有关，如果recyclerview就是父层级，每次只会渲染当前屏幕区域的内容，加载速度应该是非常快的，你的数据量大小影响不会太大
> 2. 如果recyclerview 还有一个父布局，且父布局是类似于scrollview 这种父布局，就会导致recyclerView无法准确测量出布局高度，会导致一次性加载完毕，这种是非常不可取的，如果强行这么做，只需要判断 conver方法内部的回调position即可知道加载进度

不知道为啥会这么慢，Collection.sort方法都执行的非常快，一开始以为是这个方法比较耗时，后来发现不是，就是setAdapter方法加载视图耗时

**Comment by MagicKim** [comment]
设置这个试试**recyclerView.setHasFixedSize(true)**

**Comment by limuyang2** [comment]
感觉应该是你recyclerview使用上的问题，正常来说，如果只是联系人数据，那么这应该也是很简单的item类型。3000条数据理应是很快的

**Comment by dary123** [comment]
> 感觉应该是你recyclerview使用上的问题，正常来说，如果只是联系人数据，那么这应该也是很简单的item类型。3000条数据理应是很快的

我将item加载的方法都去掉了，就是单纯的加载空的item，还是很慢，感觉跟item的加载没有关系

**Comment by dary123** [comment]
> 感觉应该是你recyclerview使用上的问题，正常来说，如果只是联系人数据，那么这应该也是很简单的item类型。3000条数据理应是很快的

其实也不是特别慢，但是在我认为10秒已经算是慢的了，虽然其中有1~2秒是耗时在排序算法上的

**Comment by dary123** [comment]
> 设置这个试试**recyclerView.setHasFixedSize(true)**

试了，速度上基本没什么变化

**Comment by dary123** [comment]
> 感觉应该是你recyclerview使用上的问题，正常来说，如果只是联系人数据，那么这应该也是很简单的item类型。3000条数据理应是很快的

其实我们的产品对慢不慢已经不介意了，现在只要能获取到进度，显示个进度条 ，让用户感觉舒心一点，不会焦急的漫无目的等待

**Comment by dary123** [comment]
> 设置这个试试**recyclerView.setHasFixedSize(true)**

其实我们的产品对慢不慢已经不介意了，现在只要能获取到进度，显示个进度条 ，让用户感觉舒心一点，不会焦急的漫无目的等待

**Comment by dary123** [comment]
> 感觉应该是你recyclerview使用上的问题，正常来说，如果只是联系人数据，那么这应该也是很简单的item类型。3000条数据理应是很快的

有办法获取到当前加载进度么

**Comment by dary123** [comment]
> 设置这个试试**recyclerView.setHasFixedSize(true)**

有办法获取到当前加载进度么

**Comment by Weightang** [comment]
自己做个假进度条吧

**Comment by Weightang** [comment]
做个假进度条？

**Comment by Weightang** [comment]
做个假进度条？

**Comment by CymChad** [comment]
网络加载进度肯定获取不到，这个和网速有关，可以做个加载圈，一定要进度条只能做个假的了
