### ISSUE TITLE
item如何添加滑动删除按钮功能

### ISSUE THREAD

**Issue by pangli** [CymChad/BaseRecyclerViewAdapterHelper#2801]
![image](https://user-images.githubusercontent.com/7498978/60852807-d9a0d380-a22b-11e9-98fe-1daadbd4d957.png)

**Comment by yangfeng1994** [comment]
你可以去收集箱里提个需求[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2806](url)

**Comment by limuyang2** [comment]
我觉得这属于业务上的需求问题，不属于框架范围。这个需要自定义item的控件，网上有很多教程
