### ISSUE TITLE
2.9.46版本多条目类型子条目嵌套RecyclerView 滑动卡顿

### ISSUE THREAD

**Issue by zhangqifan1** [CymChad/BaseRecyclerViewAdapterHelper#2802]
多条目类型子条目嵌套RecyclerView 滑动卡顿.子条目不复杂,只有textview.滑动快了就会有明显的一个小卡顿.缓慢滑动到了某一个条目也会有一个小卡顿...

**Comment by limuyang2** [comment]
可否上一段demo，
以及告知一下机型

**Comment by zhangqifan1** [comment]
华为P10
public class MyAdapter extends BaseMultiItemQuickAdapter<MutliBean, BaseViewHolder> {
    /**
     * Same as QuickAdapter#QuickAdapter(Context,int) but with
     * some initialization data.
     *
     * @param data A new list is created out of this one to avoid mutable list
     */
    public MyAdapter(List<MutliBean> data) {
        super(data);
        addItemType(MutliBean.TYPE0,R.layout.item_title);
        addItemType(MutliBean.TYPE1,R.layout.item_content);
    }

    @Override
    protected void convert(BaseViewHolder helper, MutliBean item) {
        switch (item.getItemType()){
                    case  MutliBean.TYPE0:

                        break;
                    case  MutliBean.TYPE1:
                        RecyclerView view = helper.getView(R.id.item_rv);
                        ItemAdapter itemAdapter = new ItemAdapter(R.layout.item_title, item.getType1strs());
                        LinearLayoutManager ll=new LinearLayoutManager(mContext,LinearLayoutManager.VERTICAL,false);
                        view.setLayoutManager(ll);
                        view.setAdapter(itemAdapter);
                        break;
                    default:
                        break;
                }
    }
}
条目里没有图片,,只有一个String 的条目.
慢慢滑动/或者快速滑动到了某一个条目,就会有明显的 一个停顿,然后又接着滑

**Comment by limuyang2** [comment]
根据你的demo未能看出异常。初步判断应该是item性能问题所致。
被嵌套的`RecyclerView`，不应该重复设置`adapter`和`LayoutManager`，
将代码修改为以下，然后再次尝试：
```java
……
case  MutliBean.TYPE1:
        RecyclerView view = helper.getView(R.id.item_rv);

        if (view.getLayoutManager() == null) {
            LinearLayoutManager ll=new LinearLayoutManager(mContext,LinearLayoutManager.VERTICAL,false);
            view.setLayoutManager(ll);
        }

        if (view.getAdapter() == null) {
             ItemAdapter itemAdapter = new ItemAdapter(R.layout.item_title, item.getType1strs());
             view.setAdapter(itemAdapter);
        } else {
             ((ItemAdapter)view.getAdapter()).setNewData(item.getType1strs());
        }
       
        break;
……
```
希望能解决你的问题

**Comment by zhangqifan1** [comment]
解决了.谢谢.
