### ISSUE TITLE
嵌套RecyclerView如何让内层的RecyclerView失去点击事件，就是点击内层的item时候实际上点击的是外层的item？

### ISSUE THREAD

**Issue by lhholylight** [CymChad/BaseRecyclerViewAdapterHelper#2803]
我内层recyclerview并没有设置点击事件，同时也将内层recyclerview添加的点击事件      helper.addOnClickListener(R.id.xxx)(内层recyclerview id);,同时也设置了 helper.setNestView(R.id.xxx);(该id为整个item最外层id)

**Comment by yangfeng1994** [comment]
直接给外层的item设置点击事件，然后再调用adapter的地方使用        mRecyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(BaseQuickAdapter adapter, View view, int position) {
                
            }
        });

不需要对内部的RecyclerView进行点击事件的处理。

**Comment by AnyLifeZLB** [comment]
这个最后是怎么解决的？并没有看见解决方法啊

**Comment by helloworld10010** [comment]
> 这个最后是怎么解决的？并没有看见解决方法啊

就是直接用`recyclerView.addOnItemTouchListener`，不用`adapter?.setOnItemClickListener`了

**Comment by zhangguannan** [comment]
//解决嵌套RecyclerView子条目占用点击事件
        view.setOnTouchListener((v, event) -> {
            if (event.getAction() == MotionEvent.ACTION_UP) {
                helper.itemView.performClick();
            }
            return false;
        });
