### ISSUE TITLE
绝望了，一直调用加载更多的方法，找不出是什么问题

### ISSUE THREAD

**Issue by qzqs** [CymChad/BaseRecyclerViewAdapterHelper#2804]
布局是这样
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.SwipeRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/swipe_refresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#F2F2F2"
        android:orientation="vertical">

        <include layout="@layout/view_techtoolbar" />

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:scrollbars="none"
            android:overScrollMode="never"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            tools:listitem="@layout/item_detail"
            />

    </LinearLayout>
</android.support.v4.widget.SwipeRefreshLayout>
进到页面的时候一直调用onLoadMoreRequested()
完全不知道怎么去解决？

**Comment by qzqs** [comment]
第一页数据只有几个数据，没有把屏幕沾满，这样是不是会导致这个无限加载的问题？

**Comment by Wing-Li** [comment]
2019年了，这个问题还是这样。

**Comment by CymChad** [comment]
请参考 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1704

**Comment by limuyang2** [comment]
可以关闭此功能，请多看demo或者源码

**Comment by YxmCute** [comment]
> 第一页数据只有几个数据，没有把屏幕沾满，这样是不是会导致这个无限加载的问题？

我也遇到了,是在用弹窗的时候
