### ISSUE TITLE
如何传递两个bean

### ISSUE THREAD

**Issue by 1031900805** [CymChad/BaseRecyclerViewAdapterHelper#2805]
BaseQuickAdapter<LoginBean.HzListBean, BaseViewHolder>
我需要传入两个不同的bean

**Comment by yangfeng1994** [comment]
你是想用多布局吗？如果两个bean的话，可以考虑多布局

**Comment by yangfeng1994** [comment]
或者你对你的bean类进行整合一下，写一个类，里面包含这两个类。
