### ISSUE TITLE
2019-提问前必看

### ISSUE THREAD

**Issue by CymChad** [CymChad/BaseRecyclerViewAdapterHelper#2807]
大家好，我回来了。
由于有一段时间个人原因没有维护，今天重新开始维护。
今天整理下过滤了下所有的Issues，我们会排期开发解决。
跟进问题提出的复现路径先找到问题，然后解决问题，如果无法复现或描述不清晰的无法解决请大家理解。

请大家提问时一定要看下面的内容，否则你的问题无法快速被解决。

一定要看！！
一定要看！！
一定要看！！

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

超过3天提问者没有回复开发者问题自动关闭。
因为提问题者不配合开发者给出相关信息开发者也是无法解决问题。
如还有问题提问者可以重新开一个issues，并给出相关信息便于开发者快速找到bug。

如果有新的需求可以进入 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2806 提出你的需求

有想法一起贡献BRVAH的开发者可以加我微信（chad_cym）沟通，记得添加时备注：BRVAH。
BRVAH  开源技术交流 QQ 群号:558178792。

**Comment by inshyma** [comment]
老哥  实现使用expandAll展开二级的Item  怎么让二级的Item在上面显示  然后再显示一级的item

**Comment by wmjwmj828** [comment]
能在BaseQuickAdapter的onCreateViewHolder中新增一个绑定itemView其他事件的方法吗，现在监听其他事件只能在onBindViewHolder里面监听

**Comment by com13117340768** [comment]
boolean java.lang.String.equals(java.lang.Object)

**Comment by zlc921022** [comment]
您好，当添加了头部布局，列表数据为空的时候，设置了显示头部的方法，能显示头部布局，但是列表不会显示空布局了。

**Comment by wuxiangpeng** [comment]
配合SmartRefreshLayout下拉刷新框架，每次刷新都会闪屏。

**Comment by HoHoWhereAreYou** [comment]
BaseMultiItemQuickAdapter。想要修改列表中所有数据的一个值，例如isCheck，怎么修改

**Comment by zs1973** [comment]
> 列表

解决了吗》？

**Comment by mm46468648** [comment]
这库还维护么，往前加载更多啥时候支持？

**Comment by zxj0211** [comment]
UpFetchAdapter不是抽象的, 并且未覆盖UpFetchModule中的抽象方法addUpFetchModule(BaseQuickAdapter<?,?>)

**Comment by cjcj125125** [comment]
导入项目报错未实现接口，运行不起来master分支

**Comment by cjcj125125** [comment]
国内下载地址  打开的页面少儿不宜

**Comment by kystudio** [comment]
Java代码中, 在adapter里 helper.itemView.setOnClickListener,这里的itemView找不到, 在kotlin里是可以的,请问是什么情况?

**Comment by cailidz** [comment]
版本用的3.0.4，headerView有个ContentLoadingProgressBar，数据刷新频率较高，loading圈转得很快，与UI动画不一致，用setNewInstance()方法设置的数据，该方法会刷新全部数据，能否加一个只刷新数据，不刷新header的方法？类似notifyDataChangedWithoutHeader()方法。 @limuyang2
