### ISSUE TITLE
expandList

### ISSUE THREAD

**Issue by qiangzengli** [CymChad/BaseRecyclerViewAdapterHelper#2812]
请问在使用  二级菜单的时候，设置 
adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {

            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {}}）；

这段代码中的  position  随着 列表的展开  ，除了第一项 ，   其他项的position都是动态改变的。
比如  ，我有3个一级列表，每个一级列表中有3个条目，那么  在没有展开的状态下，一级列表的position分别是 0,1,2  如果展开了第一项  ，那个  第二个一级列表的position就变成了4，但是我需要根据item的位置进入到不同的界面，请问我该怎么做啊？

**Comment by shichaohui** [comment]
可以通过 `adapter.getData()` 获取数据，根据数据执行相应操作即可，不用关心 position 的值。
```
adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
    @Override
    public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
        Object obj = adapter.getData().get(position);
        if (obj instanceof Level0Item) {
            Level0Item item = (Level0Item) obj;
            // do something
        } else if (obj instanceof Level1Item) {
            Level1Item item = (Level1Item) obj;
            // do something
        }
    }
});
```
你可以看看源码中列表展开和收缩的原理（简单说就是调整列表的结构，将不同级别的列表混合到一起），只要理解了原理，相信你会有更合适的解决方案。
