### ISSUE TITLE
使用NestedScrollView嵌套RecyclerView后post addData() 分批次填充数据

### ISSUE THREAD

**Issue by lugenggeng** [CymChad/BaseRecyclerViewAdapterHelper#2813]
for (int i = 0; ; i += 10) {
                        List<MTHotelDetailResult.ResultBean.HotelDetailsBean.GoodsBean> goods = null;
                        if (i + 10 < allGoods.size()) {
                            goods = allGoods.subList(i, i + 10);
                        } else {
                            goods = allGoods.subList(i, allGoods.size() - 1);
                        }
                        List<MTHotelDetailResult.ResultBean.HotelDetailsBean.GoodsBean> finalGoods = goods;
                        tvAddress.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                mGoodAdapter.addData(finalGoods);
                            }
                        }, 1000);
                        if (i + 10 >= allGoods.size()) {
                            break;
                        }
                    }
大概代码是这样， 报 ConcurrentModificationException 异常。
使用CopyOnWriteArrayList和ArrayList都不行

**Comment by shichaohui** [comment]
你的代码逻辑有问题，你的 for 循环几毫秒就执行完了，导致多个 postDelayed(runnable, 1000) 基本同时启动，导致 adapter.addData() 同时执行多次，addData() 内部执行 List#addAll() ，addAll() 同时执行多次导致 ConcurrentModificationException 异常。
你应该去了解一下 ConcurrentModificationException 这个异常。

**Comment by lugenggeng** [comment]
是的呢，好的，我更换下循环的逻辑，把延时放在子线程里面
