### ISSUE TITLE
关于数据源的类型

### ISSUE THREAD

**Issue by 1031900805** [CymChad/BaseRecyclerViewAdapterHelper#2816]
public Adapter(int layoutResId, @Nullable List<Bean> data) {
        super(layoutResId, data);
   }
假如我想传一个SparseArray的数据类型 而不是 list 怎么做

**Comment by shichaohui** [comment]
目前只能传递 List，您可以到 #2806 中提需求，我们评估后安排开发。
您暂时可以吧 SparseArray 转成 List 使用。
