### ISSUE TITLE
addHeaderView的问题

### ISSUE THREAD

**Issue by 1479HuangDa** [CymChad/BaseRecyclerViewAdapterHelper#2817]
当添加了HeaderView 无法触发上拉加载更多的item了

**Comment by shichaohui** [comment]
请参考 Demo 中的 [PullToRefreshUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)，若还有问题，请参考 #2807 重新提交 Issue。

**Comment by censhengde** [comment]
头布局随着滑动会隐藏，能否固定头布局？

**Comment by shichaohui** [comment]
@censhengde 
直接用 LinearLayout 包着头部和 RecyclerView 不就行了。
