### ISSUE TITLE
recyclerview嵌套recyclerview，外部的adapter只能显示第一条数据

### ISSUE THREAD

**Issue by huguoyan1989** [CymChad/BaseRecyclerViewAdapterHelper#2818]
当前使用版本2.9.46
@Override
    protected void convert(BaseViewHolder helper, HotProductModel item) {
        RecyclerView hotProductItemRecyclerView = helper.getView(R.id.home_hot_product_grid_item_rv);
        GridLayoutManager gridLayoutManager = new GridLayoutManager(mContext, 2);
        hotProductItemRecyclerView.setLayoutManager(gridLayoutManager);
        HotProductItemAdapter hotProductItemAdapter = new HotProductItemAdapter(R.layout.home_hot_product_item, item.getProductList());
        hotProductItemRecyclerView.setAdapter(hotProductItemAdapter);
    }
第一个recyclerview只能显示第一条数据，第二个recyclerview正常循环显示完成后，第一个recyclerview就不会继续执行convert方法了

**Comment by android-taoge** [comment]
兄弟，我也遇到这个问题了 。。你解决了没有？  怎么解决的？救命！！！

**Comment by android-taoge** [comment]
@huguoyan1989  刚刚发现是最里层item布局高度设置为match_parent的原因。。 改为wrap_content就可以了。。。都是自己不细心啊！！！ 希望能帮到你

**Comment by huguoyan1989** [comment]
> @huguoyan1989 刚刚发现是最里层item布局高度设置为match_parent的原因。。 改为wrap_content就可以了。。。都是自己不细心啊！！！ 希望能帮到你

我也是傻了，我这一屏刚好显示完第一条数据，第二条数据往上滑一下就显示出来了
