### ISSUE TITLE
使用这个库后每次gradle build都很满啊？

### ISSUE THREAD

**Issue by yangqi1993** [CymChad/BaseRecyclerViewAdapterHelper#282]
不加这个库build 很快，基本10秒左右，加了这个库后，10几分钟都还没完成，特别是必须要加
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}这个，用意是什么？能不能就加compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.8'

**Comment by CymChad** [comment]
JitPack实际上是一个自定义的Maven仓库，发布非常方便和快速。使用jCenter和MavenCentral的一般流程是，注册、登陆、配置参数、Build、Push、等待验证（审核比较耗时），最后才能通过，发布过程繁杂冗长。

**Comment by yangqi1993** [comment]
那也就是说必须要加，但是项目gradle加载慢是需要翻墙么？基本每次都要build 14分钟都还不过

**Comment by CymChad** [comment]
恩，是的，这个主要看网速，翻墙可以提升速度。

**Comment by AndyLeeBlue** [comment]
build太慢了，慢到无法忍受，用了这么多库就数这个慢，功能再强大也只能弃用了......
