### ISSUE TITLE
调用setData() 后界面item不刷新

### ISSUE THREAD

**Issue by wuhongsheng** [CymChad/BaseRecyclerViewAdapterHelper#2820]
调用setData() 后界面item不刷新

**To Reproduce**
1.NestedScrollView 嵌套RecyclerView
2. 第一次setData界面可以刷新走convert方法
3. 第二次setData 不走convert方法界面不刷新
4.当RecyclerView滚动时界面会刷新

![WechatIMG184](https://user-images.githubusercontent.com/10295461/61674855-61a4d400-ad28-11e9-935f-883bcd203883.jpeg)

**Comment by CymChad** [comment]
使用`setNewData`呢？

**Comment by wuhongsheng** [comment]
也不走convert

**Comment by wuhongsheng** [comment]
> 使用`setNewData`呢？

也不走convert
当键盘弹出或RecyclerView 滚动时会走convert
第一次setData convert走了两次

**Comment by CymChad** [comment]
你去掉嵌套的NestedScrollView呢？

**Comment by AllenCoder** [comment]
提供最小可复现 demo 源码，以便于我们排查问题

**Comment by wuhongsheng** [comment]
> 提供最小可复现 demo 源码，以便于我们排查问题
写demo发现和constraintLayoutVersion
使用 constraintLayoutVersion = '2.0.0-beta2' 有问题
改成 constraintLayoutVersion = '1.1.3'修复此问题
