### ISSUE TITLE
BaseItemDraggableAdapter  的子布局使用 wrap_content 时的问题

### ISSUE THREAD

**Issue by protectedMan** [CymChad/BaseRecyclerViewAdapterHelper#2821]
使用最新demo修改，使用gridview实现一个3列的列表，当子布局高度为wrap_content时，会出现动态图所示的bug(列表在快速拖动时每个item的高度会变大）,如果子布局高度是**固定值**则不会出现这种情况。
子布局代码以及问题动态图演示如下：
![QQ20190723-111154](https://user-images.githubusercontent.com/17565737/61680033-c9fcb100-ad3a-11e9-9039-06d9904a1b14.gif)

![image](https://user-images.githubusercontent.com/17565737/61680259-835b8680-ad3b-11e9-98e8-6b3c7f91563f.png)

**Comment by protectedMan** [comment]
每次高度的变化量跟ItemDecoration时设置的分割线高度有关，
![image](https://user-images.githubusercontent.com/17565737/61681012-56f53980-ad3e-11e9-9dac-9cdea3c0bee0.png)

**Comment by CymChad** [comment]
嗯，多谢指出demo问题，我们这边会进行修改。
这个问题是属于布局层面的问题和adapter无关，样式是由开发者决策的。
