### ISSUE TITLE
数据刷新成功之后不会自动回到顶部

### ISSUE THREAD

**Issue by jyrwm** [CymChad/BaseRecyclerViewAdapterHelper#2822]
已加载数据的列表，滑动到底部，调用setNewData方法刷新数据，数据刷新成功之后不会自动回到顶部

**Comment by shichaohui** [comment]
您可以在调用 `adapter.setNewData()` 后调用 `mRecyclerView.scrollToPosition(0)` 滚动到顶部。

**Comment by jyrwm** [comment]
感谢 但是我想知道作者为什么要设计成这样

**Comment by shichaohui** [comment]
这里并没有做特别的设计，仅仅修改数据源并通知 Adapter 刷新。如果强制滚动到顶部的话，灵活性差，并不是所有人都想回到顶部。
```
public void setNewData(@Nullable List<T> data) {
    this.mData = data == null ? new ArrayList<T>() : data;
    ...
    notifyDataSetChanged();
}
```

**Comment by easyandroid** [comment]
解决了吗  现在的需求是不滚动回顶部 删除数据满一屏幕的时候 现在自动滚回顶部了。

**Comment by ggyg123** [comment]
@easyandroid 哥们 你的问题解决了么

**Comment by yishangfei** [comment]
@easyandroid  @ggyg123 哥 你们的问题解决了么
