### ISSUE TITLE
brvah怎么用filter

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#2824]
brvah怎么用filter

**Comment by limuyang2** [comment]
`Adapter` 实现 `Filterable`接口，重写`getFilter()`方法。
可参考 https://www.jianshu.com/p/04a2e42a732e

**Comment by douya40** [comment]
BaseMultiItemQuickAdapter  怎么用filter   获取子节点的数据，父节点的数据也要返回
