### ISSUE TITLE
setNewDiffData里的DiffUtil操作耗时

### ISSUE THREAD

**Issue by JasonTian23** [CymChad/BaseRecyclerViewAdapterHelper#2825]
![image](https://user-images.githubusercontent.com/17329673/61695773-b1a28b80-ad66-11e9-9a23-a3dcf5753fca.png)
从博客[](https://blog.csdn.net/zxt0601/article/details/52562770 )看到数据量多时耗时不少，建议放到工作线程

**Comment by JasonTian23** [comment]
https://blog.csdn.net/zxt0601/article/details/52562770

**Comment by JasonTian23** [comment]
![remove](https://user-images.githubusercontent.com/17329673/61700388-35607600-ad6f-11e9-8e47-ff3fbf2f11d2.png)
另外，remove方法可以添加个回调么，用来监听动画执行完毕

**Comment by limuyang2** [comment]
谢谢你的建议，目前来看，diff的耗时都在可接受范围内。此遍博文发布于2016年，限今的手机设备性能都能足以支撑。
考虑到极限情况下，会后续加入异步版本的Diff

**Comment by limuyang2** [comment]
功能已添加 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/commit/338b2bcfeaa6d8fabef7bed41c6deaba37855d35

**Comment by limuyang2** [comment]
> ![remove](https://user-images.githubusercontent.com/17329673/61700388-35607600-ad6f-11e9-8e47-ff3fbf2f11d2.png)
> 另外，remove方法可以添加个回调么，用来监听动画执行完毕

删除动画是系统自带的，系统也并未提供动画监听毁掉，抱歉

**Comment by JasonTian23** [comment]
速度真快 '赞'，另动画监听的问题已自行解决
