### ISSUE TITLE
树形结构 问题

### ISSUE THREAD

**Issue by jasonSuzhow** [CymChad/BaseRecyclerViewAdapterHelper#2827]
![image](https://user-images.githubusercontent.com/13963143/61763205-1ca39f00-ae07-11e9-806d-85e5038e7bd8.png)
如果一开始就是返回这样的数据, 那是不是用这个生成一个bean类 , 每个是数组的内部类都extends AbstractExpandableItem<LevelxxxItem> implements MultiItemEntity

**Comment by jasonSuzhow** [comment]
还要不要特地生成三个bean类... 求帮助

**Comment by jasonSuzhow** [comment]
必须用这种数据加载方式是么
![image](https://user-images.githubusercontent.com/13963143/61770578-30a7ca80-ae20-11e9-904d-0f99cb9e29c7.png)

**Comment by shichaohui** [comment]
参考 Demo [ExpandableUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ExpandableUseActivity.java) 就行了，数据结构都是一样的。
