### ISSUE TITLE
按照demo实现的扩展adapter  数据 只显示列  或者两种类型显示到一行去了

### ISSUE THREAD

**Issue by addappcn** [CymChad/BaseRecyclerViewAdapterHelper#2829]
GroupHistoryItemAdapter adapter = new GroupHistoryItemAdapter(viewModel.getList());
        final GridLayoutManager manager = new GridLayoutManager(this, 2);
        manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                KLog.d("why:",adapter.getItemViewType(position));
                return adapter.getItemViewType(position) == GroupHistoryItemAdapter.TEXT ? 1 : manager.getSpanCount();
            }
        });

binding.rvHistory.setAdapter(adapter);
        binding.rvHistory.setLayoutManager(manager);
        adapter.expandAll();

分组的entity  里面返回0
public int getLevel() {
        return 0;
    }
每个组下面的数据没有返回level  按照demo走的  返回对应的  getItemType

下面的adapter  的代码

 public GroupHistoryItemAdapter(List<MultiItemEntity> data) {
        super(data);
        addItemType(TEXT, R.layout.item_history_group_view);
        addItemType(IMG_TEXT, R.layout.item_history_child_view);
    }

    @Override
    protected void convert(final BaseViewHolder helper, final MultiItemEntity item) {
        // deal with multiple type items viewHolder
//        helper.addOnClickListener(R.id.card_view);
        switch (helper.getItemViewType()) {
            case TEXT:
                HistoryGroupItem item1 = (HistoryGroupItem)item;
                helper.setText(R.id.tv_date, item1.getDate());
                break;
            case IMG_TEXT:
                HistoryChildItem item2 = (HistoryChildItem)item;
                helper.setText(R.id.tv_name, item2.getMerchant().getName());
                helper.setText(R.id.tv_unit_price, item2.getMerchant().getUnitPrice());
                helper.setImageResource(R.id.iv_merchant,R.mipmap.item_img_place);
                break;
            default:
                break;
        }
    }

请大佬指点下

**Comment by addappcn** [comment]
最新版本 不是androidx版

**Comment by shichaohui** [comment]
无法复现，请仔细检查代码，如果还有问题，请提供可复现的 Demo。

**Comment by jiqianwen** [comment]
setAdapter挪到GridLayoutManager 之前有奇效~

**Comment by addappcn** [comment]
我试了两种方案都不行 最后只能改嵌套

**Comment by jiqianwen** [comment]
我昨天也是跟你一样的问题，然后尝试这两行代码换了下上下顺序，完美结局~

**Comment by addappcn** [comment]
不行 没有换行啊 ，两个类型item  都一行显示了

**Comment by jiqianwen** [comment]
diagnosisDiseaseAdapter = new DiagnosisDiseaseAdapter(dataList);
        diagnosisDiseaseAdapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_LEFT);
        mRecyclerview.setAdapter(diagnosisDiseaseAdapter);

        GridLayoutManager manager = new GridLayoutManager(this, 4);
        manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return diagnosisDiseaseAdapter.getItemViewType(position) == DiagnosisDiseaseAdapter.TYPE_LEVEL_CONTENT ? 1 : manager.getSpanCount();
            }
        });

        mRecyclerview.setLayoutManager(manager);
这是我的代码，你参考看看

**Comment by addappcn** [comment]
算了 还是不行  先不研究了

**Comment by jiqianwen** [comment]
扎心了，我就是这个问题，改了顺序就好了= =

**Comment by addappcn** [comment]
不知道您是否可以把相关的代码截个图  或发下关键部分  我对比下 看哪有问题

**Comment by jiqianwen** [comment]
就是上面我发的代码，其他没什么了

**Comment by addappcn** [comment]
那个连个数据entity  你是按照demo走的吗

**Comment by jiqianwen** [comment]
是的  跟demo一模一样的，就是这边改了下代码顺序

**Comment by addappcn** [comment]
这个是分组的 

public class HistoryGroupItem extends AbstractExpandableItem<HistoryChildItem> implements MultiItemEntity {

    public String getDate() {
        return date;
    }
    public void setDate(String date) {
        this.date = date;
    }
    private String date;
    public HistoryGroupItem(String date) {
        this.date = date;
    }
    @Override
    public int getItemType() {
        return GroupHistoryItemAdapter.TEXT;
    }
    @Override
    public int getLevel() {
        return 0;
    }
}

**Comment by addappcn** [comment]
那就奇怪了

**Comment by jiqianwen** [comment]
AbstractExpandableItem<Bean> 你要继承这个尖括号里面是你要包裹的下一级的内容的实体类

**Comment by jiqianwen** [comment]
你看demo里面实体类的继承做法，最新版本的demo里面

**Comment by addappcn** [comment]
有的 啊 不知道复制显示到这；就没有了

**Comment by jiqianwen** [comment]
那我也不清楚了。。。

**Comment by addappcn** [comment]
嗯，谢谢 不想浪费时间在这 了 有空再研究。
