### ISSUE TITLE
列表下方正在加载无法去掉

### ISSUE THREAD

**Issue by LoveNewSweetheart** [CymChad/BaseRecyclerViewAdapterHelper#2832]
如果没有添加Header是正常的。只要添加了Header，列表下方的正在加载样式就去不掉，即使调用了Adapter的notifyDataChangedAfterLoadMore（false）也是不行，我用的版本v1.9.8。这是为什么？

**Comment by darkbluexy** [comment]
调用loadMoreEnd(true)试试

**Comment by LoveNewSweetheart** [comment]
> 
> 
> 



> 
> 
> 调用loadMoreEnd(true)试试

已解决  是我调用的顺序导致的  。之前出现了这个原因是因为调用notifyDataChangedAfterLoadMore(false)之后又调用了setNewData()。所以出现了上述的问题。当我调用了setNewData之后再调用notifyDataChangedAfterLoadMore(false)就没问题了   谢谢
