### ISSUE TITLE
无法添加依赖

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#2833]
![21564385144_ pic](https://user-images.githubusercontent.com/15857673/62029615-ac858680-b215-11e9-85f9-f3d0a2c5a9ce.jpg)

**Comment by limuyang2** [comment]
请确认 `repositories` 已添加:
```
	allprojects {
		repositories {
			...
			maven { url "https://jitpack.io" }
		}
	}
```

其次，检查网络链接

**Comment by BugMen** [comment]
阔以了，谢谢！
