### ISSUE TITLE
每次上拉加载完成之后Recyclerview都会回到最上面！！！

### ISSUE THREAD

**Issue by jiqianwen** [CymChad/BaseRecyclerViewAdapterHelper#2834]
看到有人提过这个问题，但是并没有给出解决方案，确实印象中之前没有这个问题，看了他人的描述，好像确实是androidX版本的rv有这个问题？

**Comment by yangfeng1994** [comment]
您好，请把您的调用代码贴出来，我们给您具体分析，我用的也是androidx，暂时没有出现问题。

**Comment by jiqianwen** [comment]
mSwipeRefreshLayout.setColorSchemeColors(ContextCompat.getColor(getContext(),R.color.c_2fdcb5));
        mSwipeRefreshLayout.setOnRefreshListener(this);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(getContext(),RecyclerView.VERTICAL,false));
        doctorAdapter.addHeaderView(getAdapterHeadview());
        doctorAdapter.addFooterView(getRereshFootview());
        doctorAdapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_LEFT);
        mRecyclerView.setAdapter(doctorAdapter);

        showSkeleton(mRecyclerView,doctorAdapter,R.layout.item_skeleton_doctororder,true);

        doctorAdapter.setOnItemChildClickListener(this);
        doctorAdapter.setOnLoadMoreListener(this,mRecyclerView);

**Comment by jiqianwen** [comment]
我也是了你们官方demo迁移到AndroidX的版本，确实没出现这个问题，这是我的代码，哪里有问题吗。。。

**Comment by jiqianwen** [comment]
我找到问题了，是我使用的skeleton框架的问题

**Comment by diswy** [comment]
@jiqianwen  感谢指点，另外请教一下这个骨架屏有冲突的话，你怎么解决这个问题，不使用骨架屏这个框架了么？

**Comment by jiqianwen** [comment]
> @jiqianwen 感谢指点，另外请教一下这个骨架屏有冲突的话，你怎么解决这个问题，不使用骨架屏这个框架了么？

是啊，放弃了，用adapter设置了emptyview来代替了，刷新数据的时候，显示空布局

**Comment by diswy** [comment]
> > @jiqianwen 感谢指点，另外请教一下这个骨架屏有冲突的话，你怎么解决这个问题，不使用骨架屏这个框架了么？
> 
> 是啊，放弃了，用adapter设置了emptyview来代替了，刷新数据的时候，显示空布局


可以不用放弃，你只用第一页HIDE就可以，然后就不影响了
