### ISSUE TITLE
2.9.49和2.9.48版本下，三级列表展示问题

### ISSUE THREAD

**Issue by Jerry930326** [CymChad/BaseRecyclerViewAdapterHelper#2838]
【前置条件】
三级列表，多个item

【复现步骤】
展开第一个item所有层级，然后点击第二个层级，此时后面所有的item都会跟随第一个item的第三层级同时消失。
点击第一个层级则不会出现问题。
将版本改为2.9.40不会出现问题。

**Comment by shichaohui** [comment]
48 49 版本确实有这个问题，已经在 dev 分支修复，暂时还没有发新版本。如果你不需要 diff 版本的话，可以先用 47 版本，稍后发了新版本再更新就行了。
