### ISSUE TITLE
MultipleItemRvAdapter 重写convertPayloads 方法问题

### ISSUE THREAD

**Issue by bingdu0** [CymChad/BaseRecyclerViewAdapterHelper#2839]
如果 继承 MultipleItemRvAdapter 这个类，然后重写convertPayloads 方法，怎么局部更新 某个Provider 。例如demo中的

![qq](https://user-images.githubusercontent.com/13532640/62345465-1e671400-b525-11e9-98d1-2ac19e013434.png)

DemoMultipleItemRvAdapter extends MultipleItemRvAdapter 然后重写convertPayloads  怎么局部 更新TextItemProvider。 调用了 notifyItemChanged 之后 ，TextItemProvider 这个类里面的数据怎么更新，控件的数据怎么设置？

**Comment by limuyang2** [comment]
谢谢反馈，已经补上此功能。
在`TextItemProvider `中重写 `convertPayloads()`方法即可。

请等下个版本更新。你也可以下载`dev`分支体验。

**Comment by bingdu0** [comment]
> 谢谢反馈，已经补上此功能。
> 在`TextItemProvider `中重写 `convertPayloads()`方法即可。
> 
> 请等下个版本更新。你也可以下载`dev`分支体验。

您好，release 版什么时候发布？
