### ISSUE TITLE
What this library do when load more?

### ISSUE THREAD

**Issue by cuong292** [CymChad/BaseRecyclerViewAdapterHelper#2840]
I create the recycler view.the item inside it have 1 textview which have maxWidth = "200dp".After that,when a job done,the text inside that textview change but the view is not resize to fit the text by itself (still use the viewholder of previous view)  .but when loadmore,it resize to fit the text.So how does it really work?.Cause if both did notifyDataChange it will be the same result

**Comment by cuong292** [comment]
btw,this library is really awsome for everyone.thanks for sharing it <3

**Comment by CymChad** [comment]
use loadmore look [PullToRefreshUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)

library `addData` code:

```java
  public void addData(@IntRange(from = 0) int position, @NonNull Collection<? extends T> newData) {
        mData.addAll(position, newData);
        notifyItemRangeInserted(position + getHeaderLayoutCount(), newData.size());
        compatibilityDataSizeChanged(newData.size());
    }
```
