### ISSUE TITLE
刷新数据无效

### ISSUE THREAD

**Issue by adonis-lsh** [CymChad/BaseRecyclerViewAdapterHelper#2841]
在initVIew()方面里面设置
mAppointmentsBeanList = new ArrayList<>();
 mHistoryListAdapter = new AppointmentHistoryListAdapter(mAppointmentsBeanList);
 mHistoryListAdapter.openLoadAnimation();
 mHistoryListAdapter.bindToRecyclerView(mRecyclerView);

再initData()的网络请求里面调用
mAppointmentsBeanList = 请求结果
mHistoryListAdapter.notifyDataSetChanged();
没有效果

如果在网络请求结果里面调用
 mHistoryListAdapter = new AppointmentHistoryListAdapter(mAppointmentsBeanList);
 mHistoryListAdapter.openLoadAnimation();
 mHistoryListAdapter.bindToRecyclerView(mRecyclerView);

展示正常

找到问题了,必须使用replaceData,因为mAppointmentsBeanList地址变了

**Comment by CymChad** [comment]
👌
