### ISSUE TITLE
GridSectionAverageGapItemDecoration 在AndroidX位置错乱

### ISSUE THREAD

**Issue by HaleyHong** [CymChad/BaseRecyclerViewAdapterHelper#2842]
使用的版本：2.9.45-androidx
'androidx.appcompat:appcompat:1.0.2'
按照demo在BaseSectionQuickAdapter加上GridSectionAverageGapItemDecoration分割线位置错乱

**Comment by AllenCoder** [comment]
基于 最新 demo 和lib版本 2.9.49-androidx 测试没有发现对应问题

请升级新版本测试，或者提供最新可复现demo

**Comment by HaleyHong** [comment]
> 基于 最新 demo 和lib版本 2.9.49-androidx 测试没有发现对应问题
> 
> 请升级新版本测试，或者提供最新可复现demo

发现是addHeaderView会导致位置错位，在官方demo里的SectionUseActivity添加一个HeadView会重现问题

LinearLayout headView=new LinearLayout(this);
        headView.setLayoutParams(new ViewGroup.MarginLayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,200));
        sectionAdapter.addHeaderView(headView);

**Comment by shichaohui** [comment]
[commit 36e7ba4](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/commit/36e7ba4623ff4bc97f8444a119fcec9c14f642c8) 添加了 GridSectionAverageGapItemDecoration 对头部的处理。
这个是分割线绘制的问题，与 Adapter 没什么关系。你可以使用任何有效的分割线。
