### ISSUE TITLE
ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)  android.support.v7.widget.RecyclerView$Adapter.createViewHolder(Unknown Source:23)

### ISSUE THREAD

**Issue by fadedHYC** [CymChad/BaseRecyclerViewAdapterHelper#2843]
ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
android.support.v7.widget.RecyclerView$Adapter.createViewHolder(Unknown Source:23)

**Comment by fadedHYC** [comment]
![image](https://user-images.githubusercontent.com/22925521/62451467-ebc94f80-b7a0-11e9-9f32-5ddb909b8fdd.png)

**Comment by limuyang2** [comment]
请告知版本，并贴上使用示例

**Comment by fadedHYC** [comment]
版本 2.9.40  
代码：
![image](https://user-images.githubusercontent.com/22925521/62463328-47ed9d00-b7bc-11e9-943c-776a9b5ea3ab.png)
![image](https://user-images.githubusercontent.com/22925521/62463355-60f64e00-b7bc-11e9-9d2d-341b3e0c1add.png)
![image](https://user-images.githubusercontent.com/22925521/62463363-681d5c00-b7bc-11e9-8798-0eb00e28594e.png)
![image](https://user-images.githubusercontent.com/22925521/62463373-6f446a00-b7bc-11e9-9976-fa79d7817572.png)

**Comment by 1109993488** [comment]
估计是下面这段代码造成的问题, 更新最新版试试,新版对这种情况做了处理
![image](https://user-images.githubusercontent.com/4213541/62751843-ce91cb00-ba97-11e9-8ca0-d8a9eb97189e.png)

**Comment by fadedHYC** [comment]
最新的版本是2.9.47吗？

**Comment by fadedHYC** [comment]
最新的稳定版本是2.9.47吗？

**Comment by 1109993488** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.9.49

**Comment by yys730** [comment]
同样的情况，2.9.49仍然报错了，不管是headerview还是footview，重新添加都会报这个错

**Comment by 1109993488** [comment]
@yys730 @fadedHYC 请更新到 V2.9.50

**Comment by pye52** [comment]
androidx能发布一下50版本么？

**Comment by yys730** [comment]
好的感谢，上面的问题，上回在仔细阅读你们的说明文档后，添加empty时，用此方法
val emptyView = LayoutInflater.from(context).inflate(viewId, recycleview.parent as ViewGroup, false)
来添加，可以避免问题的出现。

**Comment by RealMoMo** [comment]
viewpager+fragment onviewcreate 中addheaderview 即使ondestroyview中removeheaderview，滑动回来依旧存在此问题
