### ISSUE TITLE
使用addData加载更多会出现界面闪烁

### ISSUE THREAD

**Issue by protectedMan** [CymChad/BaseRecyclerViewAdapterHelper#2846]
![QQ20190808-092528](https://user-images.githubusercontent.com/17565737/62668677-51932280-b9bf-11e9-8a5c-14a9dc3369ea.gif)

上拉加载更多加载数据出现界面闪烁，convert方法里是空的。也没有调用其他刷新方法， 仅仅是addData

**Comment by 1109993488** [comment]
闪烁的问题应该是调用了notifyDataSetChanged, 请检查下是否是自己调用了或者是某种情况下造成的调用
