### ISSUE TITLE
refreshNotifyItemChanged 没有带payloads的重载实现

### ISSUE THREAD

**Issue by 4dcity** [CymChad/BaseRecyclerViewAdapterHelper#2847]
如果直接使用  notifyItemChanged(position, payloads) 方法，在有header的时候容易出现下标错位。而refreshNotifyItemChanged没有提供带payloads的重载实现，希望可以支持一下

**Comment by shichaohui** [comment]
暂时先使用 `notifyItemChanged(position + getHeaderLayoutCount(), payloads);` 
后续版本将加入 `refreshNotifyItemChanged(positon, payloads)` 重载函数。
