### ISSUE TITLE
 helper.getAdapterPosition() 返回-1

### ISSUE THREAD

**Issue by suziqiang** [CymChad/BaseRecyclerViewAdapterHelper#2848]
protected void convert(BaseViewHolder helper, MultiItemEntity item) {
        switch (helper.getItemViewType()) {
            case TYPE_LEVEL_1:
                MenuOneItem item1 = (MenuOneItem) item;
                helper.setText(R.id.tv_cp_name_one, item1.cpName);
                CheckBox view = helper.getView(R.id.checkbox_soucang_one);
                view.setChecked(true);
                int pos = helper.getAdapterPosition();
                view.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
                    @Override
                    public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
                        if (!b) {
                            //先收起来在移除
                            if (item1.isExpanded()) {
                                collapse(pos, false);
                            }
                            LogUtils.debugInfo("点击的位置 pos=" + pos);
                            ObjectAnimator objectAnimator = ObjectAnimator.ofFloat(helper.itemView,"rotationX",0,-360);
                            objectAnimator.setDuration(5000);
                            objectAnimator.start();
                            objectAnimator.addListener(new AnimatorListenerAdapter() {
                                @Override
                                public void onAnimationEnd(Animator animation) {
                                    super.onAnimationEnd(animation);
                                    int pos111 = helper.getAdapterPosition();
                                    LogUtils.debugInfo("移除的位置 pos=" + pos111+"  dfd= "+helper.getAdapterPosition());
                                    remove(pos111);

                                }
                            });
                            Toast.makeText(mContext, "b=" + b, Toast.LENGTH_SHORT).show();
                        }
                    }
                });
                TextView view2 = helper.getView(R.id.tv_cp_name_one);
                view2.setOnLongClickListener(new View.OnLongClickListener() {
                    @Override
                    public boolean onLongClick(View view) {
                        if (!item1.isExpanded()) {
                            expand(pos, false);
                        } else {
                            collapse(pos, false);
                        }
                        return true;
                    }
                });
                break;

当我快速点击 移除的时候 就会返回-1  如何能返回正确的位置  问题出现在 动画加载完毕 候

**Comment by suziqiang** [comment]
> protected void convert(BaseViewHolder helper, MultiItemEntity item) {
> switch (helper.getItemViewType()) {
> case TYPE_LEVEL_1:
> MenuOneItem item1 = (MenuOneItem) item;
> helper.setText(R.id.tv_cp_name_one, item1.cpName);
> CheckBox view = helper.getView(R.id.checkbox_soucang_one);
> view.setChecked(true);
> int pos = helper.getAdapterPosition();
> view.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
> @override
> public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
> if (!b) {
> //先收起来在移除
> if (item1.isExpanded()) {
> collapse(pos, false);
> }
> LogUtils.debugInfo("点击的位置 pos=" + pos);
> ObjectAnimator objectAnimator = ObjectAnimator.ofFloat(helper.itemView,"rotationX",0,-360);
> objectAnimator.setDuration(5000);
> objectAnimator.start();
> objectAnimator.addListener(new AnimatorListenerAdapter() {
> @override
> public void onAnimationEnd(Animator animation) {
> super.onAnimationEnd(animation);
> int pos111 = helper.getAdapterPosition();
> LogUtils.debugInfo("移除的位置 pos=" + pos111+" dfd= "+helper.getAdapterPosition());
> remove(pos111);
> 
> ```
>                             }
>                         });
>                         Toast.makeText(mContext, "b=" + b, Toast.LENGTH_SHORT).show();
>                     }
>                 }
>             });
>             TextView view2 = helper.getView(R.id.tv_cp_name_one);
>             view2.setOnLongClickListener(new View.OnLongClickListener() {
>                 @Override
>                 public boolean onLongClick(View view) {
>                     if (!item1.isExpanded()) {
>                         expand(pos, false);
>                     } else {
>                         collapse(pos, false);
>                     }
>                     return true;
>                 }
>             });
>             break;
> ```
> 
> 当我快速点击 移除的时候 就会返回-1 如何能返回正确的位置 问题出现在 动画加载完毕  remove(pos111);
我要实现的功能 是 点击后 item 作旋转动画,动画完成候删除 ，我让动画持续时间5s 快速点击所有item 数据就乱了  我不明白 每次删除前 我都是重新获取位置的 为什么会返回-1呢  求指教

**Comment by 1109993488** [comment]
重复点击动画回调多次时item已经移除了,所以会返回-1

**Comment by suziqiang** [comment]
有什么思路吗 我的需求是 比如有10item 点击每一个item 做几秒的反转动画 然后移除，现在是各种问题 要不报错 要不删除的不是当前的 要不 就是删除了一个item 下一个item 反转了，有什么好的建议吗

**Comment by suziqiang** [comment]
我能根据对象地址删除item吗

**Comment by 1109993488** [comment]
你用的那个版本? 更新版本试试, 动画问题你可以让它只执行一次

**Comment by CymChad** [comment]
请更新版本以及调整动画执行次数。
