### ISSUE TITLE
如何实现网格布局 点击向下展开一个网格布局

### ISSUE THREAD

**Issue by suziqiang** [CymChad/BaseRecyclerViewAdapterHelper#2853]

**Comment by shichaohui** [comment]
参考 [ExpandableUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ExpandableUseActivity.java)，如果不行，请详细描述你的需求。

**Comment by suziqiang** [comment]
我试了不行  
我从网上请求一个list<classBean> 集合,  每一个classBean对象 里面又有一个 list<StudentBean>的集合。
 list<classBean> 集合请求成功后 我用网格布局展示classbean 里面的数据，每一行展示三个item, 点击其中的一个item,就会向下展示，把classbean里面的StudentBean集合 在用网格布局展示出来 一行五个item,

**Comment by suziqiang** [comment]
我试了不行 
联网请求list<ClassBean>对象集合，每一个ClassBean对象里面又有一个list<student>对象集合
我用网格布局展示classBean对象集合，一行展示3个item, 点击其中的一个item  向下展开 并用网格布局展示每一个student对象，一行五个student item.

**Comment by suziqiang** [comment]
我试了不行 
联网请求list<ClassBean>对象集合，每一个ClassBean对象里面又有一个list<student>对象集合
我用网格布局展示classBean对象集合，一行展示3个item, 点击其中的一个item  向下展开 并用网格布局展示每一个student对象，一行五个student item.

**Comment by suziqiang** [comment]
我试了不行 
联网请求list ClassBean 对象集合，每一个ClassBean对象里面又有一个list student 对象集合
我用网格布局展示classBean对象集合，一行展示3个item, 点击其中的一个item  向下展开 并用网格布局展示每一个student对象，一行五个student item.

**Comment by shichaohui** [comment]
Adapter 暂时不支持这样的功能，RecyclerView 嵌套应该能做，你也可以试试阿里开源的 [vLayout](https://github.com/alibaba/vlayout)。

**Comment by suziqiang** [comment]
谢谢 知道了 不好意思 有提了一遍
