### ISSUE TITLE
如何实现点击网格布局item 对应展开一个网格布局

### ISSUE THREAD

**Issue by suziqiang** [CymChad/BaseRecyclerViewAdapterHelper#2855]
你好 怎么实现下面的需求 我吧demo看了一遍 还是没有找到 
联网请求list ClassBean 对象集合，每一个ClassBean对象里面又有一个list student 对象集合
我用网格布局展示classBean对象集合，一行展示3个item, 点击其中的一个item 向下展开 并用网格布局展示student对象集合，一行五个student item.

**Comment by shichaohui** [comment]
Duplicate of #2853
