### ISSUE TITLE
想请问一下，convert的调用时机

### ISSUE THREAD

**Issue by lpslpsl** [CymChad/BaseRecyclerViewAdapterHelper#2857]
是这样的，我发现我再ActivityA 中有fragment+viewpager结构，里面是有recyclerView。然后跳转到B。在B进行了一些操作，通过发送eventbus，进行更新一些数据源。也调用了notifyDataSetChanged，但是这个时候并没有走conver方法，也没有走ViewHolder的这些。然后当我从B返回的时候。调用到了conver方法，为什么没有notifyDataSetChanged后立马调用呢

**Comment by CymChad** [comment]
这个是 fragment+viewpager 渲染机制的问题。你可以重新setAdapter试一下。
