### ISSUE TITLE
item里面自己加setOnClickListener，要点击两次才触发

### ISSUE THREAD

**Issue by LiuDongCai** [CymChad/BaseRecyclerViewAdapterHelper#2859]
item里面自己加setOnClickListener，要点击两次才触发点击事件，这是为什么呢
ps:没有设置adapter?.setOnItemClickListener

**Comment by LiuDongCai** [comment]
最新：发现快速滚动后点击，需要点击两次触发，如果快速滑动后等一会再点击是一次就可以触发了

**Comment by AdminQQZ** [comment]
我也遇见了~

**Comment by benyq** [comment]
我遇见的是EditText要点击两次

**Comment by dalong982242260** [comment]
我也遇到这个问题，不知道解决了没

**Comment by AdminQQZ** [comment]
后来排查，是自己的写的有问题~有些控件第一次点击是初始化，第二次才生效

**Comment by dalong982242260** [comment]
就是复用的时候才会出现

**Comment by AdminQQZ** [comment]
我的的列表上是一个关注按钮，点击后转圈关注,在适配器里面初始化好了。然后在activity里面的adapter.onItemClick 在把控件查找出来点击。就在这时候，出现了问题。
第一次点击的时候,是去查找了控件，关注按钮的onclick并没有执行，第二次在执行。后来我直接在实体类加了一个字段。isSelect=false，外界点击就设置true，在刷新列表就可以了。

**Comment by 1109993488** [comment]
快速滑动没有停止的时候点击是触发停止滑动
和CoordinatorLayout一起使用时快速滑动到头部或底部时RecyclerView的滑动状态变为`SCROLL_STATE_IDLE`会有延迟
https://blog.csdn.net/tianshuai4317618/article/details/92788747
