### ISSUE TITLE
设置isFirstOnly 加载更多后闪烁

### ISSUE THREAD

**Issue by zhujunjun** [CymChad/BaseRecyclerViewAdapterHelper#286]
如果代码里面设置了isFirstOnly为false ，当加载更多的数据后，会造成整个item闪烁。

**Comment by CymChad** [comment]
收到，后续会优化。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.7' 你试一下。
