### ISSUE TITLE
列表同时存在头部布局和空布局问题

### ISSUE THREAD

**Issue by zlc921022** [CymChad/BaseRecyclerViewAdapterHelper#2860]
您好，当添加了头部布局，列表数据为空的时候，设置了setHeaderAndEmpty(true);，能正确显示头部布局，但是列表不会显示自定义空布局的文字了。

**Comment by zlc921022** [comment]
您好 刚刚写错了，是这样的问题，同时存在头部布局和列表的时候，列表为空，setHeaderAndEmpty(true)之后能正常显示头部布局，但是列表显示空布局还能再滑动，而不是剩余的部分文字居中

**Comment by CymChad** [comment]
这样需要开发者自己去动态改变空布局的高度。

**Comment by zlc921022** [comment]
明白了，就是存在头部的时候。需要开发者自己去改变一下空布局高度，谢谢您了




| |
zlc921022
邮箱：zlc921022@163.com
|

签名由 网易邮箱大师 定制

在2019年08月19日 14:46，陈宇明 写道：

这样需要开发者自己去动态改变空布局的高度。
