### ISSUE TITLE
自定义多布局问题，保留setMultiTypeDelegate方法

### ISSUE THREAD

**Issue by shenjiabing** [CymChad/BaseRecyclerViewAdapterHelper#2862]
希望BaseQuickAdapter基类里面继承保留setMultiTypeDelegate方法自定义设置多布局，在2.9.49版本有这个方法，最新版2.9.50，把这个方法给去掉了。
有一些场景是需要自己写多布局，而bean对象是sdk里面的bean对象，所以无法去bean对象继承MultiItemEntity对象。

**Comment by limuyang2** [comment]
嗯，谢谢反馈。
多类型的Item有两种选择：
`MultipleItemRvAdapter` 
`BaseMultiItemQuickAdapter`（需要bean对象继承MultiItemEntity）

`setMultiTypeDelegate`方法现存在于`MultipleItemRvAdapter`  中，请继承此类，再次尝试
