### ISSUE TITLE
局部刷新问题

### ISSUE THREAD

**Issue by shenjiabing** [CymChad/BaseRecyclerViewAdapterHelper#2863]
使用的是2.9.49与2.9.50版本都存局部刷新问题，场景是列表里面只修改了某一条内容，但是按demo的方法，进行局部刷新的时候，还是走了convert()方法，导致刷新了整个view。我的方法是以下截图：
![a](https://user-images.githubusercontent.com/45984638/63222755-69984c80-c1de-11e9-969a-c2196f99e9d2.png)
在适配器里面重写这个方法
![b](https://user-images.githubusercontent.com/45984638/63222757-6dc46a00-c1de-11e9-80bd-9609af6b1b71.png)
![c](https://user-images.githubusercontent.com/45984638/63222759-70bf5a80-c1de-11e9-92ff-645b04241bf9.png)

**Comment by limuyang2** [comment]
demo测试没有问题。你的代码截图看起来也是正确的。
可否上传一个包含此问题的代码

**Comment by limuyang2** [comment]
为了再次确认，我进行了各版本测试。
测试均在一个独立的新工程中进行，分别导入了 `2.9.47` `2.9.48``2.9.49` `2.9.50`版本。
每个版本测试前，均进行了彻底的项目`clean`，并删除手机上已安装app，避免额外的可能影响。

上述四个版本中，表现一致，局部刷新功能正常。无法复现你所述情况。

请你再次进行测试确认，如有必要，可提供一份测试代码

**Comment by shenjiabing** [comment]
刚刚我写了一个demo，发现只有第一次点击的时候，还是走了convert()方法，之后再点击的时候，就不会再走流量

**Comment by shenjiabing** [comment]
这个是我写的demo，当你点击的时候，先清空日志，会发现只有第一次的时候会调用，convert()方法，后面在点击的时候就不会再调用了
![微信11111](https://user-images.githubusercontent.com/45984638/63481622-97281300-c4c8-11e9-8460-744961508dec.png)
![适配器](https://user-images.githubusercontent.com/45984638/63481674-c9d20b80-c4c8-11e9-9e51-141b3787729b.png)
![activity](https://user-images.githubusercontent.com/45984638/63481684-cfc7ec80-c4c8-11e9-943c-176288b84fc8.png)

**Comment by shenjiabing** [comment]
[Brvah.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/3528118/Brvah.zip)

**Comment by limuyang2** [comment]
> [Brvah.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/3528118/Brvah.zip)

好的，我再测试一下

**Comment by shenjiabing** [comment]
好的

**Comment by limuyang2** [comment]
> 这个是我写的demo，当你点击的时候，先清空日志，会发现只有第一次的时候会调用，convert()方法，后面在点击的时候就不会再调用了
> ![微信11111](https://user-images.githubusercontent.com/45984638/63481622-97281300-c4c8-11e9-8460-744961508dec.png)
> ![适配器](https://user-images.githubusercontent.com/45984638/63481674-c9d20b80-c4c8-11e9-9e51-141b3787729b.png)
> ![activity](https://user-images.githubusercontent.com/45984638/63481684-cfc7ec80-c4c8-11e9-943c-176288b84fc8.png)

您好，我使用你的demo再次进行了测试。依然无法复现失效的问题。所有功能为正常。

针对你图一的问题。经过测试，并不是`convert`和`convertPayloads`同时执行。
如果手机上显示的最后一个item是7，那么第一次点击可见布局的item进行局部刷新，那么由于`recyclerView`的预加载机制，会预加载第8个，所以导致`convert`执行（注意：这里是item 8的`convert`第一次执行！并不是刷新你所点击的item），同时所点击的item执行`convertPayloads`方法进行刷新。也就出现了如图所示的日志。

**Comment by limuyang2** [comment]
额外的代码建议：
点击事件里，这两句代码是多余的，可以去掉：
`mAdapter.getData().set(position,mAdapter.getData().get(position));`

因为你是直接对原数据进行的修改，并没有修改内存指针的引用，不必重新`set`

**Comment by limuyang2** [comment]
如果问题已解决，请关闭issues

**Comment by yexseven** [comment]
异步刷新 notifyItemChanged(position + counthead, 1);  有时候会调用convert 之后再调convertPayloads

**Comment by limuyang2** [comment]
> 异步刷新 notifyItemChanged(position + counthead, 1); 有时候会调用convert 之后再调convertPayloads

可否详细说明下

**Comment by wudifamo** [comment]
我也遇到了类似问题,请问作者是否有在5.0设备上测试过?同样的demo,我在6.0+设备运行只刷新指定item,但是在6.0以下会重绘所有item

**Comment by YunniWeng** [comment]
怎么解决？
