### ISSUE TITLE
kotlin 用的2.9.49，但是不让绑定androidx 包下的recyclerview

### ISSUE THREAD

**Issue by awoxsheng** [CymChad/BaseRecyclerViewAdapterHelper#2864]
![image](https://user-images.githubusercontent.com/28776970/63243172-52b03380-c28c-11e9-8ae1-95e70bfe6201.png)

**Comment by limuyang2** [comment]
请导入kotlin版本的本库。
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases

**Comment by limuyang2** [comment]
长时间未回复，先关闭此问题。如过还有问题，请新开issues
