### ISSUE TITLE
字体颜色问题

### ISSUE THREAD

**Issue by IceWaterGuo** [CymChad/BaseRecyclerViewAdapterHelper#2866]
adapter中字体颜色使用不了colors中的颜色值啊，只能使用Color的颜色值才有效果！！！

**Comment by shichaohui** [comment]
`setBackgroundColor()` `setTextColor()` 仅支持 `@ColorInt` 类型的值，`@ColorRes` 需要自行转换。
你可以到 #2806 中提一个支持 `@ColorRes` 的需求，我们稍后安排时间开发。
