### ISSUE TITLE
item使用include标签

### ISSUE THREAD

**Issue by heyangJob** [CymChad/BaseRecyclerViewAdapterHelper#2867]
版本  2.9.47

使用多布局

 <?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="12dp"
    android:layout_marginRight="12dp"
    android:orientation="horizontal">

    <include
        android:id="@+id/video_matrix_left"
        layout="@layout/view_section_videoofchannel_item"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_weight="1" />

    <include
        android:id="@+id/video_matrix_right"
        layout="@layout/view_section_videoofchannel_item"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_marginLeft="8dp"
        android:layout_weight="1" />

</LinearLayout>

查找控件
 View left = helper.getView(R.id.video_matrix_left);
 View right = helper.getView(R.id.video_matrix_right);

 ImageView ivVideoPosterLeft = left.findViewById(R.id.iv_video_poster);
 ImageView ivVideoPosterRight = right.findViewById(R.id.iv_video_poster);

 TextView tvVideoNameLeft = left.findViewById(R.id.tv_video_name);
 TextView tvVideoNameRight = right.findViewById(R.id.tv_video_name);

是不是要使用一个SparseArray<View> views缓存一下;

**Comment by shichaohui** [comment]
可以自定义 ViewHolder，ViewHolder 初始化时获取 View 并缓存，之后绑定数据的时候直接使用缓存即可。
