### ISSUE TITLE
DrawerLayout抽屉中添加使用RecyclerView绑定Item点击事件无响应

### ISSUE THREAD

**Issue by pangli** [CymChad/BaseRecyclerViewAdapterHelper#2868]
使用版本 com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.44

activity布局
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawer"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?actionBarSize"
            android:background="@color/White"
            app:contentInsetStart="0dp">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <ImageView
                    android:id="@+id/iv_left"
                    style="@style/SelectableStyle"
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:paddingStart="@dimen/dp_14"
                    android:paddingEnd="@dimen/dp_14"
                    android:src="@mipmap/img_black_back" />

                <TextView
                    android:id="@+id/tv_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:text="港险订单"
                    android:textColor="@color/color_333333"
                    android:textSize="@dimen/sp_18"
                    android:textStyle="bold" />

                <ImageView
                    android:id="@+id/iv_search"
                    style="@style/SelectableStyle"
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:layout_toStartOf="@id/iv_filter"
                    android:paddingStart="@dimen/dp_14"
                    android:paddingEnd="@dimen/dp_14"
                    android:src="@mipmap/sousuo" />

                <ImageView
                    android:id="@+id/iv_filter"
                    style="@style/SelectableStyle"
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:layout_alignParentEnd="true"
                    android:paddingStart="@dimen/dp_14"
                    android:paddingEnd="@dimen/dp_14"
                    android:src="@mipmap/shaixuan" />
            </RelativeLayout>
        </android.support.v7.widget.Toolbar>

        <android.support.design.widget.TabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_45"
            app:tabBackground="@color/white"
            app:tabGravity="fill"
            app:tabIndicatorColor="@color/color_10b2ff"
            app:tabIndicatorHeight="@dimen/dp_2"
            app:tabMode="fixed"
            app:tabSelectedTextColor="@color/color_10b2ff"
            app:tabTextColor="@color/color_666666" />

        <android.support.v4.view.ViewPager
            android:id="@+id/vp_fragment"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1" />
    </LinearLayout>

    <include layout="@layout/drawer_right_filter" />
</android.support.v4.widget.DrawerLayout>`

drawer_right_filter.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/many_lines_recyclerView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="end"
    android:layout_marginStart="-30dp"
    android:background="@color/white"
    android:orientation="vertical">

    <com.edaili.kotlin.baselibs.widget.ItemViewWithImage
        android:id="@+id/item_view"
        style="@style/ViewPressedStyle"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_45"
        android:layout_marginTop="@dimen/dp_40"
        app:leftText="渠道经理"
        app:showLine="false" />

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/dp_15"
                android:text="订单状态"
                android:textColor="@color/color_333333"
                android:textSize="@dimen/sp_14"
                android:textStyle="bold" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerView_order_status"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:paddingTop="@dimen/dp_10"
                android:paddingBottom="@dimen/dp_10"
                app:layoutManager="android.support.v7.widget.GridLayoutManager"
                app:spanCount="3"
                tools:itemCount="15"
                tools:listitem="@layout/item_filter" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/dp_15"
                android:text="日期类型"
                android:textColor="@color/color_333333"
                android:textSize="@dimen/sp_14"
                android:textStyle="bold" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerView_date_type"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:paddingTop="@dimen/dp_10"
                android:paddingBottom="@dimen/dp_10"
                app:layoutManager="android.support.v7.widget.GridLayoutManager"
                app:spanCount="3"
                tools:itemCount="5"
                tools:listitem="@layout/item_filter" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/dp_15"
                android:text="日期范围"
                android:textColor="@color/color_333333"
                android:textSize="@dimen/sp_14"
                android:textStyle="bold" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerView_date_range"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:paddingTop="@dimen/dp_10"
                android:paddingBottom="@dimen/dp_10"
                app:layoutManager="android.support.v7.widget.GridLayoutManager"
                app:spanCount="3"
                tools:itemCount="4"
                tools:listitem="@layout/item_filter" />
        </LinearLayout>

    </android.support.v4.widget.NestedScrollView>

    <android.support.constraint.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_49">

        <TextView
            android:id="@+id/tv_reset"
            style="@style/SelectableStyle"
            android:layout_width="@dimen/dp_0"
            android:layout_height="match_parent"
            android:background="@color/white"
            android:gravity="center"
            android:text="重置"
            android:textColor="@color/selector_approval_button_text_color"
            android:textSize="@dimen/sp_16"
            android:textStyle="bold"
            app:layout_constrainedWidth="true"
            app:layout_constraintEnd_toStartOf="@+id/tv_confirm"
            app:layout_constraintHorizontal_weight="1"
            app:layout_constraintStart_toStartOf="parent" />

        <TextView
            android:id="@+id/tv_confirm"
            style="@style/SelectableStyle"
            android:layout_width="@dimen/dp_0"
            android:layout_height="match_parent"
            android:background="@drawable/shape_approval_cancel_button_bg"
            android:gravity="center"
            android:text="确认"
            android:textColor="@color/white"
            android:textSize="@dimen/sp_16"
            android:textStyle="bold"
            app:layout_constrainedWidth="true"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_weight="2"
            app:layout_constraintStart_toEndOf="@+id/tv_reset" />

        <View
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_1"
            android:background="@color/color_f4f6f8"
            app:layout_constraintTop_toTopOf="parent" />
    </android.support.constraint.ConstraintLayout>
</LinearLayout>`

item_filter.xml
`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="@dimen/dp_5"
    android:layout_marginBottom="@dimen/dp_5">

    <TextView
        android:id="@+id/textView"
        style="@style/SelectableStyle"
        android:layout_width="97dp"
        android:layout_height="30dp"
        android:layout_gravity="center"
        android:background="@drawable/selected_insurance_button_bg"
        android:gravity="center"
        android:text="已签部分付款"
        android:textColor="@color/selector_insurance_button_text_color"
        android:textSize="@dimen/sp_12" />

</FrameLayout>`

adapter代码
`class FilterAdapter :
    BaseQuickAdapter<FilterItem, BaseViewHolder>(R.layout.item_filter) {

    /**
     * Normal list that does not indicate choices
     */
    internal val CHOICE_MODE_NONE = 0

    /**
     * The list allows up to one choice
     */
    internal val CHOICE_MODE_SINGLE = 1
    /**
     * The list allows multiple choices
     */
    internal val CHOICE_MODE_MULTIPLE = 2
    private var mChoiceMode = CHOICE_MODE_NONE
    /**
     * Running state of which positions are currently checked
     */
    private var mCheckStates: SparseBooleanArray? = null
    private var mCheckPosition: SparseIntArray? = null

    fun changerSelectedStatus(position: Int) {
        if (mChoiceMode == CHOICE_MODE_MULTIPLE) {
            val checked = mCheckStates?.get(position, false) ?: false
            if (checked) {
                mCheckStates?.put(position, false)
                mCheckPosition?.delete(position)
                notifyItemChanged(position)
            } else {
                mCheckStates?.put(position, true)
                mCheckPosition?.put(position, position)
                notifyItemChanged(position)
            }
        } else if (mChoiceMode == CHOICE_MODE_SINGLE) {
            val checked = mCheckStates?.get(position, false) ?: false
            if (checked) {
                mCheckStates?.clear()
                mCheckPosition?.clear()
                notifyItemChanged(position)
            } else {
                val oldPosition = getCheckedItemPosition()
                mCheckStates?.clear()
                mCheckPosition?.clear()
                if (oldPosition != -1) {
                    notifyItemChanged(oldPosition!!)
                }
                mCheckStates?.put(position, true)
                mCheckPosition?.put(position, position)
                notifyItemChanged(position)
            }
        }
    }

    fun setChoiceMode(choiceMode: Int) {
        mChoiceMode = choiceMode
        if (mChoiceMode != CHOICE_MODE_NONE) {
            if (mCheckStates == null) {
                mCheckStates = SparseBooleanArray(0)
            }
            if (mCheckPosition == null) {
                mCheckPosition = SparseIntArray(0)
            }
        }
    }

    private fun getCheckedItemPosition(): Int? {
        return if (mChoiceMode == CHOICE_MODE_SINGLE && mCheckStates != null && mCheckStates?.size() == 1) {
            mCheckStates?.keyAt(0)
        } else -1
    }

    override fun convert(helper: BaseViewHolder?, item: FilterItem?) {
        helper ?: return
        item ?: return
        val checked = mCheckStates?.get(helper.layoutPosition, false) ?: false
        val textView = helper.getView<TextView>(R.id.textView)
        textView.text = item.name
        textView.isSelected = checked
//        textView.setOnClickListener {
//            changerSelectedStatus(helper.layoutPosition)
//        }
    }
}`

点击事件设置
`   drawer.openDrawer(Gravity.END)
                orderStatusFilterAdapter?.setOnItemClickListener { baseQuickAdapter, view, i ->
                    orderStatusFilterAdapter?.changerSelectedStatus(i)
                }`

效果图：
![image](https://user-images.githubusercontent.com/7498978/63327679-421dbd00-c361-11e9-88cd-c053c535f41c.png)
设置点击事件无效

**Comment by CymChad** [comment]
请给一个完整可复现的demo

**Comment by pangli** [comment]
问题已解决
写demo的时候发现我给Item布局添加了按下效果导致
item布局
`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="@dimen/dp_5"
    android:layout_marginBottom="@dimen/dp_5">

    <TextView
        android:id="@+id/textView"
        style="@style/ViewPressedStyle" 
        android:layout_width="97dp"
        android:layout_height="30dp"
        android:layout_gravity="center"
        android:background="@drawable/selected_insurance_button_bg"
        android:gravity="center"
        android:text="已签部分付款"
        android:textColor="@color/selector_insurance_button_text_color"
        android:textSize="@dimen/sp_12" />


</FrameLayout>`

style：

` <style name="ViewPressedStyle">
        <item name="android:clickable">true</item>
        <item name="android:focusable">true</item>
        <item name="android:foreground">?attr/selectableItemBackground</item>
    </style>`
导致设置item点击事件无效
