### ISSUE TITLE
在使用“分组的伸缩栏”功能时展开分组。分组条目闪现

### ISSUE THREAD

**Issue by KarnaughK** [CymChad/BaseRecyclerViewAdapterHelper#287]
手机是小米4，MIUI8  ，下载的demo就没事。。。求解

**Comment by CymChad** [comment]
你设置了动画？

**Comment by CymChad** [comment]
你可以对比一下，你与demo代码的区别。

**Comment by KarnaughK** [comment]
是使用BaseMultiItemQuickAdapter的的时候添加了HeadView，导致分组条目闪现

**Comment by elfman** [comment]
改过来了，你试下还有没有问题

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.6'

**Comment by tudou152** [comment]
您好,打扰一下.我这里也遇到了这个问题.不过我的情况是,RecyclerView中嵌套 了RecyclerView,外层的RecyclerView是使用的adapter是继承BaseSectionQuickAdapter的,内层RecyclerView的adapter是继承自BaseMultiItemQuickAdapter的. 也就是说外层是一个分组的adapter,内层是一个二级展开和折叠的adapter.

   问题是,当我点击第一级的item,来折叠该item的子项的动画完成之后,这个item的下一个item里面的显示的内容会有一个从底部平移到中间的动画效果.(这种情况仅仅会发生在下一个item处于折叠状态的时候,如果他是展开的,那么就没有这个问题)
  请问,是bug还是我哪里配置出了问题ne ?
