### ISSUE TITLE
遇到一个问题，辛苦给解答一下。

### ISSUE THREAD

**Issue by weiweiForAndroid** [CymChad/BaseRecyclerViewAdapterHelper#2871]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{a353b6c position=2 id=-1, oldPos=2, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{f98a1d2 VFED..... .F....I. 0,0-1080,1615 #7f0800a9 app:id/recycler_view}, adapter:com.learning.chinese.source.list.SourceListAct$MySourceAdapter@fb712a3, layout:android.support.v7.widget.GridLayoutManager@5b2c9a0, context:com.learning.chinese.source.list.SourceListAct@64b5b7b

**Comment by weiweiForAndroid** [comment]
![image](https://user-images.githubusercontent.com/7279815/63559847-37903d00-c586-11e9-98c5-ee639ab39b4a.png)

**Comment by weiweiForAndroid** [comment]
![image](https://user-images.githubusercontent.com/7279815/63559909-64dceb00-c586-11e9-9041-7e1746f19077.png)
折叠的时候报错

**Comment by shengye102** [comment]
你这是下标越界了，检查下，你生成的数据是否正确。

**Comment by weiweiForAndroid** [comment]
@shengye102  好的，我检查下。
