### ISSUE TITLE
你好，使用ItemTouchHelper允许长按拖拽，长按时可能会触发OnItemClickListener（长按时间非常短时触发），请问如何解决？

### ISSUE THREAD

**Issue by zybooo1** [CymChad/BaseRecyclerViewAdapterHelper#2872]
**Describe the bug**
你好，使用ItemTouchHelper允许长按拖拽，长按时可能会触发OnItemClickListener（长按时间非常短时触发），请问如何解决？

**Comment by CymChad** [comment]
你做一个检验，本质上长按就是根据时间来判断分发的
