### ISSUE TITLE
多数据List怎么使用

### ISSUE THREAD

**Issue by zijinzhiyun** [CymChad/BaseRecyclerViewAdapterHelper#2874]
有数据源A、B、C、D四个List数据源，那应该怎么使用呢？setNewData之类的方法只能传一种类型

**Comment by limuyang2** [comment]
请使用泛型

**Comment by zijinzhiyun** [comment]
@limuyang2 ,adapter只接受一种泛型，四个List分别有不同的泛型，具体怎么使用？四个不同泛型的List要展示在一个RecyclerView中

**Comment by limuyang2** [comment]
```java
public class TAdapter<T> extends BaseQuickAdapter<T, BaseViewHolder> {

    public TAdapter(@Nullable List<T> data) {
        super(R.layout.layout_animation, data);
    }

    @Override
    protected void convert(@NonNull BaseViewHolder helper, T item) {
        if (item instanceof String) {

        } else if (item instanceof Integer) {

        } else if (item instanceof Integer) {
            
        }
    }
}
```

**Comment by MagicKim** [comment]
不同的集合是有不同的JavaBean吧.每个JavaBean实现一个接口,就像官方实现多布局那样implements MultiItemEntity  然后把所有的实体类一块加入到一个集合里面

```java

    private ArrayList<MultiItemEntity> generateData() {
        int lv0Count = 9;
        int lv1Count = 3;
        int personCount = 5;

        String[] nameList = {"Bob", "Andy", "Lily", "Brown", "Bruce"};
        Random random = new Random();

        ArrayList<MultiItemEntity> res = new ArrayList<>();
        for (int i = 0; i < lv0Count; i++) {
            Level0Item lv0 = new Level0Item("This is " + i + "th item in Level 0", "subtitle of " + i);
            for (int j = 0; j < lv1Count; j++) {
                Level1Item lv1 = new Level1Item("Level 1 item: " + j, "(no animation)");
                for (int k = 0; k < personCount; k++) {
                    lv1.addSubItem(new Person(nameList[k], random.nextInt(40)));
                }
                lv0.addSubItem(lv1);
            }
            res.add(lv0);
        }

        return res;
    }

```

**Comment by limuyang2** [comment]
> 不同的集合是有不同的JavaBean吧.每个JavaBean实现一个接口,就像官方实现多布局那样implements MultiItemEntity 然后把所有的实体类一块加入到一个集合里面.用的时候instanceof取出来.我是这样想的.
> 
> ```java
>     private ArrayList<MultiItemEntity> generateData() {
>         int lv0Count = 9;
>         int lv1Count = 3;
>         int personCount = 5;
> 
>         String[] nameList = {"Bob", "Andy", "Lily", "Brown", "Bruce"};
>         Random random = new Random();
> 
>         ArrayList<MultiItemEntity> res = new ArrayList<>();
>         for (int i = 0; i < lv0Count; i++) {
>             Level0Item lv0 = new Level0Item("This is " + i + "th item in Level 0", "subtitle of " + i);
>             for (int j = 0; j < lv1Count; j++) {
>                 Level1Item lv1 = new Level1Item("Level 1 item: " + j, "(no animation)");
>                 for (int k = 0; k < personCount; k++) {
>                     lv1.addSubItem(new Person(nameList[k], random.nextInt(40)));
>                 }
>                 lv0.addSubItem(lv1);
>             }
>             res.add(lv0);
>         }
> 
>         return res;
>     }
> ```

直接使用`List<Object> data`，将所有类型放进去。最后用`instanceof `取出
