### ISSUE TITLE
RV嵌套RV，内层RV添加数据后导致外层RV的item被挤出

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#2882]
我的场景是RecyclerView嵌套RecyclerView，开始的时候里层和外层的RecyclerView都是有数据的，然后向里层的adapter添加数据，之后外层RecyclerView的item被挤出界面了，这个问题要怎么解决？

**Comment by limuyang2** [comment]
这个应该是你布局问题。我们这看不到你的代码，无能为力了

**Comment by BugMen** [comment]
两个Rv的布局都是wrap_content啊

**Comment by CymChad** [comment]
提问可以根据要求来进行提问，这样便于快速定位问题
