### ISSUE TITLE
Androidx 

### ISSUE THREAD

**Issue by kingslou** [CymChad/BaseRecyclerViewAdapterHelper#2883]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/431

这个issues是16年的 看楼主回复说 
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.3.3' 已发布 loadComplete改成了notifyDataSetChanged，addData注释了notifyItemRangeInserted，因为notifyItemRangeInserted会引发 #414

然后我在 loadMoreComplete 遇到了一个问题 
报错Log
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:6).state:26 androidx.recyclerview.widget.RecyclerView{8ceb14b VFED...L. ........ 0,0-1080,1960 #7f090168 app:id/searchRecycleView}, adapter:geen.lou.gifmaker.adapter.SearchAdapter@c536a87, layout:androidx.recyclerview.widget.StaggeredGridLayoutManager@563adb4, context:geen.lou.gifmaker.gifmake.MainActivity@7bc7c9b
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6109)

**Comment by lgengsy** [comment]
就这样关了 ？？
