### ISSUE TITLE
2.9.50-androidx ?

### ISSUE THREAD

**Issue by Misakisogiou** [CymChad/BaseRecyclerViewAdapterHelper#2886]
2.9.50 的 androidx 版本呢?

**Comment by ColorDesert** [comment]
同问

**Comment by diefferson** [comment]
I implemented 2.9.50 without problems in an AndroidX project.

**Comment by diefferson** [comment]
Maybe androidx version is not necessary anymore

**Comment by diefferson** [comment]
I found the answer, like the current version of BaseRecyclerViewAdapterHelper uses RecyclerView version 28, if you use `android.enableJetifier=true`in your project you won't have problems.

**Comment by CymChad** [comment]
thanks
