### ISSUE TITLE
notifyItemRangeChanged方法失效

### ISSUE THREAD

**Issue by NewHuLe** [CymChad/BaseRecyclerViewAdapterHelper#2888]
你好，新版的notifyItemRangeChanged方法不知道做了何种改变，会引起局部刷新失效，描述如下：
1.问题版本号 baseRecyclerviewVersion = "2.9.50"
2.问题代码
 // 刷新item，显示删除按钮
  notifyItemRangeChanged(0, getItemCount(), true);
3.发现跟机型无关
4.目前还原baseRecyclerviewVersion = "2.9.46"暂无此问题，我们调用此方法是为实现长按拖动并显示删除按钮的功能，希望定位一下问题原因，谢谢！

**Comment by CymChad** [comment]
收到

**Comment by limuyang2** [comment]
是否有添加头布局？

**Comment by limuyang2** [comment]
是否有添加头布局？

**Comment by limuyang2** [comment]
我这里测试`notifyItemRangeChanged(0, getItemCount(), payLoad);`是正常的。
`notifyItemRangeChanged()`为系统方法，理应不会出现bug

**Comment by com13117340768** [comment]
屏幕可见部分有刷新，不可见的item没有变化。

**Comment by RUDNI** [comment]
我也碰到和他一样的问题

**Comment by everyline** [comment]
我也是在这样的问题  notifyItemRangeChanged 失效了 
![图片](https://user-images.githubusercontent.com/8476579/66536846-fe6d5580-eb50-11e9-8869-452255e6565b.png)

**Comment by limuyang2** [comment]
> 我也是在这样的问题 notifyItemRangeChanged 失效了
> ![图片](https://user-images.githubusercontent.com/8476579/66536846-fe6d5580-eb50-11e9-8869-452255e6565b.png)

可否重新上传下图片，或者提供demo

**Comment by limuyang2** [comment]
长时间未回复，先关闭issue，如有问题，请新开issue

**Comment by yefl2064** [comment]
2.9.50 androidx 也遇到这个问题
