### ISSUE TITLE
关于BaseQuickAdapter，使用GridLayoutManager,水平方向，使用加载更多的请教

### ISSUE THREAD

**Issue by pudao2010** [CymChad/BaseRecyclerViewAdapterHelper#2889]
代码示例如下：
GridLayoutManager gridLayoutManager = new GridLayoutManager(this, 3,
                GridLayoutManager.HORIZONTAL, false);
 mRecyclerView.setLayoutManager(gridLayoutManager);
需求是设置水平方向的Grid布局，spanCount=3，加载更多时，使用默认的LoadMoreView，发现单独占据一整屏，adapter的数量不是3的倍数，那么存在剩余的布局空间。请问有方法可以让LoadMoreView显示在最后的item上吗

**Comment by pudao2010** [comment]
![TIM截图20190903171342](https://user-images.githubusercontent.com/22054178/64160639-dbbf9100-ce6e-11e9-8477-317e59ea1943.png)

**Comment by CymChad** [comment]
暂不支持

**Comment by underwes** [comment]
好像可以先设置LinearLayoutManager，再设置GridLayoutManager  就是你想要的效果了
