### ISSUE TITLE
Expandable问题: 1.无法递归折叠 2.如何将header或footer增加到任意级别菜单

### ISSUE THREAD

**Issue by wcodebird** [CymChad/BaseRecyclerViewAdapterHelper#2893]
前置条件:
1.前几天刚下载的应该是最新版本
2.已经搜索过所有问答未发现

问题:
1.无法递归折叠菜单
   如下图，level 0 级菜单展开，再把 level 1级菜单展开，这时折叠level 0，然后再打开，发现level 1的菜单是展开的，而不是随着上级菜单折叠而同时折叠，
查看源代码发现一个方法 recursiveCollapse 此方法实现不完美
![image](https://user-images.githubusercontent.com/26832866/64398398-42bf8e80-d097-11e9-9c16-a7469c187a07.png)
解决方法:
让person也实现 IExpandable 接口或者继承 AbstractExpandableItem (主要目的也是为了实现接口IExpandable),然后按照下图修改方法 recursiveCollapse 
![image](https://user-images.githubusercontent.com/26832866/64407595-48c56780-d0b7-11e9-9cc7-f0ad82cfdeae.png)
上面解决方法也不完美,必须所有层级都实现接口 IExpandable，暂时解决，作为开发组的一个参考吧

2.如何将header或footer增加到任意级别菜单
按照例子中有3级菜单，假如如果想在第二级菜单中增加一个header或者footer，试了一下基本无法达成，或很难达成，目前增加header或者footer，使用 addHeaderView(View header, int index) ，如果在初始化Adapter的时候增加，index值无法确定，且只能在最外层增加，只有触动条目或者条目内动作监听时才能获取position，从而确定index，做了一下测试，这么做会导致条目和监听混乱，可能是刚刚接触BRVAH，没有深入研究，能否请教一下，想在二级或则三级菜单，或者任意级菜单中增加header或者footer，应该怎么做，有什么具体例子么？

**Comment by CymChad** [comment]
暂不支持

**Comment by wcodebird** [comment]
哦，原来如此,已找到方法，多谢！

**Comment by hhyy1986** [comment]
> 哦，原来如此,已找到方法，多谢！

什么方法，能分享下吗

**Comment by limuyang2** [comment]
在即将发布的`3.x`版本中，对折叠展开布局进行重写了，新增了`BaseNodeAdapter`。
子节点跟随父节点展开关闭；
可以对任意节点添加`Footer`；
满足你所提出对两点需求
