### ISSUE TITLE
绑定Item子控件的点击事件后，点击切换item的背景图片现象不正确

### ISSUE THREAD

**Issue by Pixel4396** [CymChad/BaseRecyclerViewAdapterHelper#2894]
绑定Item子控件的点击事件后，点击切换item的背景图片，点击第一个item切换背景图片的时候第十二个item的背景图片也切换了，点第二个item切换背景图片，第十三个也切换了，以此类推。
![Gif_20190907_105552](https://user-images.githubusercontent.com/43428107/64469063-a95baf80-d15e-11e9-9498-5841070ddff4.gif)
![QQ图片20190907105744](https://user-images.githubusercontent.com/43428107/64469064-b5477180-d15e-11e9-98bd-87f6790d2c9a.png)
![QQ图片20190907105759](https://user-images.githubusercontent.com/43428107/64469065-b5477180-d15e-11e9-8eed-cd9af1eca249.png)

**Comment by CymChad** [comment]
这个是缓存问题，数据状态错乱。
这个问题无论是RecyclerView还是ListView不做处理都会出现问题，这个本质上是由于布局重用机制导致的，解决办法是通过数据状态来控制控件的状态，一定要设置状态无论什么状态，if和else是少不了的，如下代码：
```
  if（entity.isCheck）{
    checkBox.isChecked(true);
  } else {
    checkBox.isChecked(false);
  }
```
