### ISSUE TITLE
想问下怎么可以做到addFoot的时候重复添加而不顶到最后

### ISSUE THREAD

**Issue by yuwoquan** [CymChad/BaseRecyclerViewAdapterHelper#2895]
想每次下拉加载更多时在底部添加广告内容。但是使用addFooterView之后加载完成footerview会顶到最下面，怎么才可以让他添加到数据的中间位置不断插入进去

**Comment by CymChad** [comment]
这个可以通过实现多样式布局来进行实现。把广告内容看作是一种新的布局。
