### ISSUE TITLE
adapter.remove(int pos) 方法删除某条item数据，item布局重叠，错乱

### ISSUE THREAD

**Issue by payencai** [CymChad/BaseRecyclerViewAdapterHelper#2896]
删除的用法能不能加在demo里面。我测试多个版本，直接调用remove方法，都会有问题。item布局重叠，错乱。

**Comment by weichongchong** [comment]
codeAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                if (view.getId() == R.id.tv_del) {
                    adapter.getData().remove(position);
                }
            }
        });
这个remove之后，界面显示的数据不对

**Comment by shichaohui** [comment]
`adapter.getData().remove(position);` 只是把数据从 List 中删除，并没有刷新 UI 。
