### ISSUE TITLE
添加多个header，可以通过 recyView.smoothScrollToPosition(position)方法，滑动到指定的header的位置吗？

### ISSUE THREAD

**Issue by WarriorYu** [CymChad/BaseRecyclerViewAdapterHelper#2899]
adapter.removeAllHeaderView();
adapter.removeAllFooterView();
adapter.addHeaderView(header,0);
adapter.addHeaderView(header2,1);
adapter.addFooterView(footer);
添加多个header，可以通过 recyView.smoothScrollToPosition(position)方法，滑动到指定的header的位置吗？

**Comment by shichaohui** [comment]
目前是不可以的，因为所有的 header 都在 position 为 1 的位置。如果要滚动到指定 header ，需要自行计算坐标。
