### ISSUE TITLE
获取position

### ISSUE THREAD

**Issue by weavey** [CymChad/BaseRecyclerViewAdapterHelper#29]
@Override
 public void onBindViewHolder(ViewHolder holder, final int position) {

}
官方的onBindViewHolder是会返回position的，能否在你的convert方法也给回呢
@Override
    protected void convert(BaseViewHolder baseViewHolder, Bean bean) {

       

    }
某些情况下我只需要根据一个position去判断执行一些操作,而不是bean中的某个字段去判断

**Comment by CymChad** [comment]
可以通过baseViewHolder.getLayoutPosition()，拿到当前的position

**Comment by weavey** [comment]
哦  翻了几遍源码 没发现还有这个方法 不好意思 = =
