### ISSUE TITLE
新手问下，如何onItemChildClick里面获取RecyclerView里面各个item的View

### ISSUE THREAD

**Issue by a237112263** [CymChad/BaseRecyclerViewAdapterHelper#2900]
新手问下，如何onItemChildClick里面获取RecyclerView里面各个item的View

**Comment by shichaohui** [comment]
[OnItemChildClickListener](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/library/src/main/java/com/chad/library/adapter/base/listener/OnItemChildClickListener.java) 的回调函数的参数里已经存在对应的 View 了。

**Comment by a237112263** [comment]
我需要获取的是别的item的view，比如我点击第二个item。我需要获取第一个Item的view怎么获取?




------------------ 原始邮件 ------------------
发件人: "陈宇明"<notifications@github.com>; 
发送时间: 2019年9月19日(星期四) 下午2:34
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "‰∮飛∮￡"<371116959@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 新手问下，如何onItemChildClick里面获取RecyclerView里面各个item的View (#2900)




OnItemChildClickListener 的回调函数的参数里已经存在对应的 View 了。

**Comment by shichaohui** [comment]
RecyclerView 本身就有函数可以获取
```java
mRecyclerView.findViewHolderForAdapterPosition(positon)

mRecyclerView.findViewHolderForLayoutPosition(positon)
```
