### ISSUE TITLE
emptyView和headView 同时显示时,出现的逻辑漏洞

### ISSUE THREAD

**Issue by Likeyong** [CymChad/BaseRecyclerViewAdapterHelper#2901]
不是bug,只是觉得设计不合理.
当设置了headView ,并且设置了headView和empty同时显示功能.
假设手机分辨率为1080 *1920 . headView高度为920px;
然后添加了headView, 我看源码里面会用一个matchParent的FrameLayout包裹内容.
也就是emptyView 的高度为 1920px .  那么这时候整个recyclerview的内容总高度为1920 +920个像素. 也就是说 这个时候的recyclerview是可以上下滑动的.  空页面可以上下滑动....不敢想象

**Comment by Likeyong** [comment]
希望能得到回复

**Comment by shichaohui** [comment]
2.x 版本不会改这个了，你到 #2806 提个需求吧，后续在 3.x 版本处理。
