### ISSUE TITLE
使用andriox+ConstraintLayout布局，无加载更多效果，自定义也无效果

### ISSUE THREAD

**Issue by huanglppp** [CymChad/BaseRecyclerViewAdapterHelper#2904]
使用andriox+ConstraintLayout布局，下拉加载更多的时候,无加载更多效果，自定义也无效果：
![image](https://user-images.githubusercontent.com/5566857/65381961-7b659600-dd2e-11e9-8764-c5034e5aed59.png)

**Comment by huanglppp** [comment]
没有出现，如图所示的这个效果，我的效果是这样的：
![image](https://user-images.githubusercontent.com/5566857/65381968-a8b24400-dd2e-11e9-8ccb-37e5333da126.png)

**Comment by hushibin** [comment]
老哥，你调用setOnLoadMoreListener会无限调用吗

**Comment by huanglppp** [comment]
> 老哥，你调用setOnLoadMoreListener会无限调用吗

不会，都是正常的

**Comment by longertime** [comment]
> 老哥，你调用setOnLoadMoreListener会无限调用吗

我这里也会出现这种现象？请问你解决了吗？当返回数据为空而又不调用loadmoreend()的时候就会出现这种情况
