### ISSUE TITLE
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder

### ISSUE THREAD

**Issue by EdminhPeng** [CymChad/BaseRecyclerViewAdapterHelper#2907]
查看了历史解决方式，并没有找到解决方式。

使用版本："com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.45-androidx"
1、使用BaseQuickAdapter，提前addHeaderView；
2、配合使用SmartRefreshLayout，加载网络数据列表，网络数据回调中，第一页调用BaseQuickAdapter.setNewData方法，后续加载的分页数据使用addData，并没有对列表做任何的增删；
偶发崩溃：java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder；而没有addHeaderView的列表页中并没有出现过该异常。

![image](https://user-images.githubusercontent.com/21301463/65496797-b660f880-deeb-11e9-9a47-4b5e31652030.png)

**Comment by AIlll** [comment]
item的position要加上headerView的数量

**Comment by EdminhPeng** [comment]
> item的position要加上headerView的数量

直接BaseQuickAdapter.setNewData或者BaseQuickAdapter.addData，里面做了position的兼容啊

**Comment by LiuDongCai** [comment]
@EdminhPeng 请问这个问题解决了吗，是怎么解决的

**Comment by minzbox** [comment]
> @EdminhPeng 请问这个问题解决了吗，是怎么解决的

do you call adapter.notifyItemChanged(position), if yes, replace by adapter.notifyItemChanged(position + getHeaderLayoutCount())

**Comment by liusunmiao** [comment]
> > item的position要加上headerView的数量
> 
> 直接BaseQuickAdapter.setNewData或者BaseQuickAdapter.addData，里面做了position的兼容啊

就是调用的setNewData和addData bugly上面还是记录一些错误

**Comment by Qiang11** [comment]
recyclerView默认动画导致的，禁用默认动画
