### ISSUE TITLE
不同布局的BaseMultiItemQuickAdapter中，要刷新某一项数据。怎么做？

### ISSUE THREAD

**Issue by ziyougang** [CymChad/BaseRecyclerViewAdapterHelper#2908]
不同布局的BaseMultiItemQuickAdapter中，要刷新某一项数据。怎么做？
我目前是获取到数据以后BaseMultiItemQuickAdapter..setNewData(taskList);
没起作用。

**Comment by shichaohui** [comment]
所有 Adapter 刷新数据都一样，与布局无关，直接调用 adapter.notifyXxx() 函数刷新就行。
