### ISSUE TITLE
天啊！点击事件不见了

### ISSUE THREAD

**Issue by BestSingerInSiHui** [CymChad/BaseRecyclerViewAdapterHelper#291]
天啊

**Comment by CymChad** [comment]
你是从2.0之前的版本切换到2.0的对吗？

**Comment by CymChad** [comment]
如果是这样的话，那么点击事件的设置方法已经改变了，具体你可以看下：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister

**Comment by BestSingerInSiHui** [comment]
可以，我还是爱你的
