### ISSUE TITLE
关于水平方向得适配器添加头部问题

### ISSUE THREAD

**Issue by PostLiu** [CymChad/BaseRecyclerViewAdapterHelper#2912]
`LinearLayoutManager llm = new LinearLayoutManager(this);
        llm.setOrientation(LinearLayoutManager.HORIZONTAL);
        recyclerView.setLayoutManager(llm);
        View headerView = getLayoutInflater().inflate(R.layout.js_recyclerview_header, (ViewGroup) recyclerView.getParent(),false);
        headerView.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.WRAP_CONTENT,
                ViewGroup.LayoutParams.WRAP_CONTENT));
        courseDetailsJSAdapter.addHeaderView(headerView);
        recyclerView.setAdapter(courseDetailsJSAdapter);`

头部的图片大小都是写死的,
运行的效果是头部充满了整个recyclerview,然后滑动才会显示数据

**Comment by shichaohui** [comment]
使用这个 API 试试，有什么不明白的可以看看源码。
```java
/**
 * @param header 头视图
 * @param index 要添加到的位置，-1 表示末尾
 * @param orientation 垂直排列：LinearLayout.VERTICAL，水平排列：LinearLayout.HORIZONTAL
 */
public int addHeaderView(View header, final int index, int orientation)
```

**Comment by PostLiu** [comment]
> 使用这个API试试，有什么不明白的可以看看原始码。
> 
> ```java
> / **
>  * @param标头头视图
> * @param index要添加到的位置，-1表示末尾
> * @param orientation垂直分配：LinearLayout.VERTICAL，水平分布：LinearLayout.HORIZONTAL 
> * / public int addHeaderView（ View header， final int索引， int方向） 
>   
> ```

OK,没有注意这个方法还可以设置其他参数,添加了索引跟方向能够正常显示头部尾部了

**Comment by hxkdidi** [comment]
一，说说我的具体场景：BaseNodeAdapter 添加头部 (版本 3.0.4)

二，我的recycleView布局：
      <?xml version="1.0" encoding="utf-8"?>
      <com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
       android:id="@+id/refreshLayout"
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:background="@color/windowBackground"
       android:fitsSystemWindows="false">

     <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:background="@color/white"
        tools:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
        tools:listitem="@layout/item_list" />

</com.scwang.smartrefresh.layout.SmartRefreshLayout>

三，我的headerView布局：

   <?xml version="1.0" encoding="utf-8"?>
   <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tool="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="14dp
    android:layout_marginRight="14dp"
    android:layout_marginBottom="20dp"
    android:background="@drawable/xy_card"
    android:paddingLeft="16dp"
    android:paddingTop="28dp"
    android:paddingRight="16dp"
    android:paddingBottom="28dp">

    <TextView
        android:id="@+id/tv_name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_marginEnd="14dp"
        android:layout_toStartOf="@+id/tv_discover_teacher_name"
        android:gravity="left"
        android:lineSpacingMultiplier="1.2"
        android:textColor="#ffffff"
        android:textSize="16sp"
        android:textStyle="bold"
        tool:text="MMKV——基于 mmap 的高性能通用 key-value 组件" />

    <TextView
        android:id="@+id/tv_value_1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/tv_name"
        android:layout_marginTop="16dp"
        android:textColor="#cccccc"
        android:textSize="12sp"
        tool:text="MMKV" />

    <TextView
        android:id="@+id/tv_value_2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/tv_name"
        android:layout_alignParentEnd="true"
        android:layout_marginTop="16dp"
        android:textColor="#ffffff"
        android:textSize="16sp"
        android:textStyle="bold"
        tool:text="MMKV" />

</RelativeLayout>

四，首先这个方法不生效：

       int addHeaderView（ View header， final int索引， int方向） 这个方法不行

五，解决方案：代码执行顺序 1->3->4

      1，headerView=LayoutInflater.from(AppData.getContext()).inflate(layoutId, null);

      **2，headerView= LayoutInflater.from(AppData.getContext()).inflate(layoutId, parent, false);（这个获取view的方法在高版本可以避免headerview的外边距失效问题，高版本（android 11 / api 30）上第3点可以不需要执行，否则会和布局的外间距叠加，但是这个方案在低版本（android 5.0 / api 22）不起作用）。**

     3，LinearLayout headerLayout = adapter.getHeaderLayout();
            if (headerLayout != null) {
                headerLayout.setPadding(DisplayUtils.dp2px(14), DisplayUtils.dp2px(20), DisplayUtils.dp2px(14), DisplayUtils.dp2px(20));
            }
    4，recycleView.setAdapter(adapter);
