### ISSUE TITLE
addFooterView不显示布局

### ISSUE THREAD

**Issue by songsongtao** [CymChad/BaseRecyclerViewAdapterHelper#2915]
当mAdapter.setNewData(null);
mAdapter.addFooterView(footerView);
不显示FooterView

**Comment by songsongtao** [comment]
![image](https://user-images.githubusercontent.com/20622787/66447817-06aa8f80-ea82-11e9-92e8-8210f99ad80b.png)

**Comment by songsongtao** [comment]
看了源码已经解决问题，作者判断了再有空布局的时候且无数据的时候，不能添加底部布局

**Comment by HeyBean-X** [comment]
那有办法解决空布局时也能显示footerView的办法吗
