### ISSUE TITLE
建议：MultipleItemRvAdapter

### ISSUE THREAD

**Issue by shoushuai** [CymChad/BaseRecyclerViewAdapterHelper#2918]
一个模型对应一个ItemProvider，当一个模型有两种布局（数据处理基本一致），搁以前都是在convert处理，现在怎么在同一个ItemProvider处理，就是说怎么根据模型中的参数设置layout。希望public abstract int layout();可以返回对应layout。

**Comment by shoushuai** [comment]
比如说列表中有广告模型，有多种布局。要么在它的ItemProvider中设置对应layout，要么再新建一个广告适配器，放在ItemProvider中的convert()中。但是像新闻列表有单图和多图俩布局，怎么弄的

**Comment by shoushuai** [comment]
我结合自己项目中用到的一个类似库，觉得上面不可行。
不过可以在MultipleItemRvAdapter继承类中的registerItemProvider()方法中，mProviderDelegate.registerProvider(new NewsListProvider());时，支持根据数据的参数返回对应ItemProvider。

**Comment by shoushuai** [comment]
就是实现一个Class可对应多个ItemProvider，demo没看到，不知道有没有这个

**Comment by shoushuai** [comment]
我自己项目中用到的一个库。
ItemProvider支持多个layout，可以有小图、大图、多图布局。
还有一种情况是，建议实现一个Class可对应多个ItemProvider，可以在MultipleItemRvAdapter继承类中的registerItemProvider()方法中，mProviderDelegate.registerProvider(new NewsListProvider());时，支持根据数据的参数返回对应ItemProvider。

**Comment by shoushuai** [comment]
我自己项目中用到的一个库。
ItemProvider支持多个layout，可以有小图、大图、多图布局。
还有一种情况是，建议实现一个Class可对应多个ItemProvider，可以在MultipleItemRvAdapter继承类中的registerItemProvider()方法中，mProviderDelegate.registerProvider(new NewsListProvider());时，支持根据数据的参数返回对应ItemProvider。
就是想在ItemProvider中根据数据设置返回不同layout

**Comment by bingdu0** [comment]
什么意思？ 就在ItemProvider 中返回不同layout？比如说 图文的ItemProvider  ， 然后在图文的ItemProvider 中返回  大图图文 三图图文，小图图文这样的吗？

**Comment by bingdu0** [comment]
> 我自己项目中用到的一个库。
> ItemProvider支持多个layout，可以有小图、大图、多图布局。
> 还有一种情况是，建议实现一个Class可对应多个ItemProvider，可以在MultipleItemRvAdapter继承类中的registerItemProvider()方法中，mProviderDelegate.registerProvider(new NewsListProvider());时，支持根据数据的参数返回对应ItemProvider。
> 就是想在ItemProvider中根据数据设置返回不同layout

什么意思？就比如说 图文的ItemProvider ， 然后在这个图文的ItemProvider  在返回  大图图文、小图图文 、多图图文？
