### ISSUE TITLE
Androidx中adapter的notifyDataSetChanged和notifyItemRangeChanged方法失效

### ISSUE THREAD

**Issue by Cedar-byte** [CymChad/BaseRecyclerViewAdapterHelper#2919]
1. 当前使用的版本号： 2.9.47-androidx
2. 复现操作描述：列表删除一行之后，调用刷新单条数据的方法或者刷新全部的方法都不行，始终显示的是原来的数据，就跟adapter有缓存一样。list数据debug确认remove后确实少了一条，但是界面显示的还是删除之前的数据。（我将adapter换成官方原生的之后就没有问题）
3. 使用代码： 
 `list.remove(position); 
  adapter.notifyItemRemoved(position);
  adapter.notifyItemRangeChanged(position, list.size() - position);`
或者  
`list.remove(position);
adapter.notifyDataSetChanged();`

**Comment by shichaohui** [comment]
有没有添加 Header ？notifyItemRemoved 需要加上 Header 的数量。BRVAH 提供了 remove 函数删除数据。

**Comment by GongXiaoYun** [comment]
> 有没有添加 Header ？notifyItemRemoved 需要加上 Header 的数量。BRVAH 提供了 remove 函数删除数据。

没有添加header呢。
