### ISSUE TITLE
一个关于Item间距的问题

### ISSUE THREAD

**Issue by sweet2o09** [CymChad/BaseRecyclerViewAdapterHelper#292]
我没有找到addItemDecoration()相关的代码,请问你是如何设置这个Item间距的?

**Comment by CymChad** [comment]
Item间距的问题是RecyclerView的，不是adapter的。

**Comment by CymChad** [comment]
mRecyclerView.addItemDecoration

**Comment by sweet2o09** [comment]
是的,这个我知道,我只是好奇,我看你的Demo里面并没有设置addItemDecoration,但是你出来的效果却是有间距的,就拿HomeActivity来说吧,我没看到相关设置,但是在效果上,每个Item中间都有间距,请问这是为什么呢

**Comment by CymChad** [comment]
![1](https://cloud.githubusercontent.com/assets/7698209/18236545/c70b9736-7359-11e6-80a6-32ae4649a045.png)
这是item的布局，我把最外面的LinearLayout设置成黑色了，你可以明显的看出。

**Comment by sweet2o09** [comment]
`<android.support.v7.widget.CardView
        android:id="@+id/card_view"
        android:layout_width="match_parent"
        android:layout_height="120dp"
        android:layout_gravity="center"
        card_view:cardCornerRadius="8dp"
        card_view:cardElevation="4dp"
        card_view:cardUseCompatPadding="true">`
我发现是因为card_view:cardElevation="4dp"  card_view:cardUseCompatPadding="true"这两个参数造成了有间距的视觉效果
