### ISSUE TITLE
BaseMultiItemQuickAdapter 情况无法数据更新

### ISSUE THREAD

**Issue by KeQian** [CymChad/BaseRecyclerViewAdapterHelper#2927]
除了首次加载数据正常  后续无法新增数据 比如 

mAdapter?.addData(recycleViewData as ArrayList<MultiItemEntity>)
新增子项
notifyDataSetChanged 
就像这样
        val response = Gson().fromJson<Level0>(jsonStr, Level0::class.java)

        var recycleViewData =  response.datas

        recycleViewData?.forEachIndexed { index, Level0 ->

            Level0.replys?.forEachIndexed { index, Level1 ->

                Level0.addSubItem(Level1)
            }

        }
        mAdapter?.addData(recycleViewData as ArrayList<MultiItemEntity>)
        mAdapter?.notifyDataSetChanged()

这些操作只会显示一级数据其他的均不显示

**Comment by bukeCN** [comment]
我也遇到了这样的问题，添加了二级数据，调用 notifyDataSetChanged() 无法立即刷新数据，需要收起在展开之后才能显示。
