### ISSUE TITLE
provider 不能使用自定义viewholder,出现ClassCastException

### ISSUE THREAD

**Issue by AreYReady** [CymChad/BaseRecyclerViewAdapterHelper#2928]
![image](https://user-images.githubusercontent.com/13625746/67736709-899c8580-fa43-11e9-8761-49f6cdf6eb58.png)
![image](https://user-images.githubusercontent.com/13625746/67736760-b6e93380-fa43-11e9-92b4-ba1fbbedf5c5.png)

- 更新当前最新版本2.9.50,
- 使用外部类,内部类加public static 的方式都不行,
- 更改成baseviewholder 正常

**Comment by limuyang2** [comment]
provider 中的 `viewHolder`要和`adapter`中定义的一样

**Comment by limuyang2** [comment]
在即将发布的`3.x`版本中，`ViewHolder`类型不再要求统一。每个`provider `可以拥有自己类型的`ViewHolder`，提高自由程度

**Comment by pntcwz** [comment]
> 在即将发布的`3.x`版本中，`ViewHolder`类型不再要求统一。每个`provider `可以拥有自己类型的`ViewHolder`，提高自由程度

请问有例子能参考吗?
