### ISSUE TITLE
一直触发BaseQuickAdapter.RequestLoadMoreListener

### ISSUE THREAD

**Issue by INTKILOW** [CymChad/BaseRecyclerViewAdapterHelper#2934]
一直触发BaseQuickAdapter.RequestLoadMoreListener

AppBarLayout + CollapsingToolbarLayout  + NestedScrollView + SmartRefreshLayout

**Comment by qingweiSun** [comment]
不满一屏就会，

**Comment by INTKILOW** [comment]
好像嵌套NestedScrollView 有这个问题

**Comment by INTKILOW** [comment]
NestedScrollView嵌套RecyclerView滑动冲突导致上拉加载更多失效

**Comment by dawnhope** [comment]
确实是一直在触发加载更多

**Comment by limuyang2** [comment]
NestedScrollView 嵌套 RecyclerView 会导致 RecyclerView的高度测算失效，然后就会一次性加载所有item。
这不是本库的bug

**Comment by greadking** [comment]
建议使用Adapter.addHeaderView 或 addFooterView， 将相关布局添加头脚上 去除NestedScrollView 应该可以解决相关问题
