### ISSUE TITLE
使用adapter 添加了头view 后使用adapter.notifyItemChanged(position);无效

### ISSUE THREAD

**Issue by lidiwo** [CymChad/BaseRecyclerViewAdapterHelper#2936]
使用adapter 添加了头view 后，

在setOnItemLongClickListener 的监听方法中使用adapter.notifyItemChanged(position) 崩溃
在setOnItemChildClickListener 的监听方法中使用adapter.notifyItemChanged(position) 无效

**Comment by shichaohui** [comment]
position 要加上头布局的数量

**Comment by getglory** [comment]
使用BaseRecyclerViewAdapterHelper自己的方法，不要使用RecyclerView.Adapter的方法。refreshNotifyItemChanged或者setData(int, Object);都可以。另外要注意helper.getAdapterPosition()也需要减去getHeaderLayoutCount()才是真实的position
