### ISSUE TITLE
关于SpanSize

### ISSUE THREAD

**Issue by realchen** [CymChad/BaseRecyclerViewAdapterHelper#2937]
当前使用的版本号 2.9.47
这边的值我想动态的变，比如再最内层时，列表只要一条数据的时候就占满一行
如果多条数据再平分，这个可以实现吗
`public int getSpanSize(int position) {
                //如果等于最内层,分别设置为1,就是每行3个;如果不是最内层,就设置每行的总个数,也就是一个item占满一行
                return qualityInspectAdapter.getItemViewType(position) == QualityInspectAdapter.TYPE_LEVEL_2 ? 1 : manager.getSpanCount();
            }`

**Comment by shichaohui** [comment]
adapter.setSpanSizeLookup()
gridLayoutManager.setSpanSizeLookup()

**Comment by realchen** [comment]
//设置整体的layoutmanager
        final GridLayoutManager manager = new GridLayoutManager(this, 3);
        //如果内外层的layoutmanager不一样呢? 需要设置setSpanSizeLookup
        manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                //如果等于最内层,分别设置为1,就是每行3个;如果不是最内层,就设置每行的总个数,也就是一个item占满一行
                return qualityInspectAdapter.getItemViewType(position) == QualityInspectAdapter.TYPE_LEVEL_2 ? 1 : manager.getSpanCount();
            }
        });


我现在想让最内层的时候，根据某一种条件来判断显示几个
现在的话，只要是最内层 就都是三等分这样布局 宽度很有限
