### ISSUE TITLE
多级列表嵌套 BaseMultiItemQuickAdapter

### ISSUE THREAD

**Issue by realchen** [CymChad/BaseRecyclerViewAdapterHelper#2939]
当前列表一共分为3级
一级和二级都是简单的标题
三级里会有多种类型的布局
我现在想实现这种需求，如果是单选框时，当点击某个按钮后
我遍历当前三级菜单同级的，把其他的置为未选中
请问下你这边有什么方法吗？主要是不知道怎么获取跟当前item同级的所有布局

**Comment by KaraShok** [comment]
你可以看一下demo里的那个分级的那个页面，那个可以满足你的需求。
