### ISSUE TITLE
emptyview 为什么不显示出来 

### ISSUE THREAD

**Issue by EdisonRXG** [CymChad/BaseRecyclerViewAdapterHelper#2941]
rec.setHasFixedSize(true);
        rec.setFocusableInTouchMode(false);
        rec.setNestedScrollingEnabled(true);
        LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
        mAdapter = new LogAdapter();
        notDataView = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) rec.getParent(), false);
        rec.setLayoutManager(layoutManager);
        rec.setAdapter(mAdapter);

设置布局的时候
 if (respons.getData().getLog().size() > 0) {
                mAdapter.setNewData(respons.getData().getLog());
            } else {
                mAdapter.setEmptyView(notDataView);
            }

这里的空视图一直不显示....怎么回事呢

**Comment by shichaohui** [comment]
检查是否执行到了 setEmptyView() 这个函数，检查是否是在主线程执行的，检查 notDataView 本身有没有问题。

**Comment by EdisonRXG** [comment]
是这!!  这个emptyview 在使用的时候  
rec.setHasFixedSize(true);
rec.setFocusableInTouchMode(false);
rec.setNestedScrollingEnabled(true);
LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
mAdapter = new LogAdapter();
notDataView = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) rec.getParent(), false);
rec.setLayoutManager(layoutManager);
rec.setAdapter(mAdapter);

**mAdapter.setEmptyView(notDataView);**
这个需要提前先使用一次~~~~~~ 才能显示出来  不知道是不是BUG

**Comment by EpicWang** [comment]
救了命了
数据置空的时候，空视图加载不出来，需要设置一下，才能显示
`mAdapter.setEmptyView(myView);`
