### ISSUE TITLE
在rv的头部使用banner自动轮播时候出现banner错位问题。

### ISSUE THREAD

**Issue by WangMiaoGit** [CymChad/BaseRecyclerViewAdapterHelper#2944]
![20191107_095025](https://user-images.githubusercontent.com/22518556/68353723-652c6180-0145-11ea-9a71-b268eb21b849.gif)
  上面 那个banner，是在rv外面，下面的banner是  添加到 rv 的头部。
在自动播放的时候发生的banner图 错误问题。
banner用的是开源的 https://github.com/youth5201314/banner 。

**Comment by BoxuanJia** [comment]
这个问题，是banner库的问题。
参考:https://github.com/youth5201314/banner/issues/733
那边的小伙伴给了解决方案，在recylerview的上级视图中，添加下面两句话试试。
android:focusable="true"
android:focusableInTouchMode="true"
