### ISSUE TITLE
继承BaseMultiItemQuickAdapter 怎么使用databinding？

### ISSUE THREAD

**Issue by bingdu0** [CymChad/BaseRecyclerViewAdapterHelper#2948]
继承 BaseQuickAdapter 实现了databining，如果继承BaseMultiItemQuickAdapter 实现多布局 怎么使用databinding？求大佬指教！

**Comment by limuyang2** [comment]
建议使用 3.x 版本

**Comment by bingdu0** [comment]
> 建议使用 3.x 版本

您好，3x 中有BaseMultiItemQuickAdapter databinding 的demo吗？

**Comment by bingdu0** [comment]
> 建议使用 3.x 版本

您好，3.x 能否提供一个BaseMultiItemQuickAdapter databinding 的demo
