### ISSUE TITLE
Item加上selector每次点击刷新Adapter.replaceData(dataList)或者notifyDataSetChanged，selector效果就不会显示

### ISSUE THREAD

**Issue by CaoXiLin** [CymChad/BaseRecyclerViewAdapterHelper#2949]
mRoomDeviceAdapter = new RoomDeviceAdapter(R.layout.room_device_item, 
        PFKApplication.mDeviceBeans);
        mRvView.setLayoutManager(new LinearLayoutManager(this));
        mRoomDeviceAdapter.openLoadAnimation(BaseQuickAdapter.ALPHAIN);
        mRvView.setAdapter(mRoomDeviceAdapter);
        mRoomDeviceAdapter.bindToRecyclerView(mRvView);
        mRoomDeviceAdapter.setEmptyView(R.layout.data_null);

        mRvView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(BaseQuickAdapter adapter, View view, int position) {
                List<DeviceBean> dataList = mRoomDeviceAdapter.getData();
                DeviceBean deviceBean = dataList.get(position);
                boolean select = deviceBean.isSelect();
                if (!select) {
                    deviceBean.setSelect(true);
                } else {
                    deviceBean.setSelect(false);
                    deviceBean.setChebox(false);
                }
                mRoomDeviceAdapter.replaceData(dataList);
            }

        });
          xml
      <LinearLayout
            android:background="@drawable/room_item_selector"
            android:gravity="center_horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
        >
         <TextView
                android:id="@+id/tv_name"
                android:gravity="center"
                android:text="客厅"
                android:textColor="@color/black"
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="80dp"/>
        </LinearLayout>

![image](https://user-images.githubusercontent.com/27336949/68821707-f9f50900-06c9-11ea-87c8-0b7cc621128c.gif)

**Comment by limuyang2** [comment]
请使用 `setOnItemClickListener()`
