### ISSUE TITLE
调用notifyItemChanged(int position, Object payload)

### ISSUE THREAD

**Issue by facexxyz** [CymChad/BaseRecyclerViewAdapterHelper#295]
RecyclerView局部数据刷新.

问题:调用notifyItemChanged(int position, Object payload)方法后,如何在Adapter中获取到payload数据?

**Comment by CymChad** [comment]
目前没有通过payload数据，后续可以优化。

**Comment by facexxyz** [comment]
@CymChad 谢谢

**Comment by Destiny01** [comment]
那如何解决notifyItemChanged(position)布局闪动问题呢？

**Comment by hexianqiao3755** [comment]
@Destiny01 哥们 我的也会闪动 请问你解决了吗
