### ISSUE TITLE
重新setAdapter导致，OnItemClickListener点击失效问题！

### ISSUE THREAD

**Issue by daqiang5566** [CymChad/BaseRecyclerViewAdapterHelper#2950]
1.当前版本号 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30'
2.
    (1) recyclyView.setAdapter(),当前data的数量是 1
    (2) 再次recyclyView.setAdapter() ,单签data的数量 是10
  （3）导致postition > 1 的item后面的 OnItemClickListener 不能正常点击，毕现。
3.问题代码，由于OnItemClickListener new 的时候已经绑定之前的adater,重新复用之前的OnItemClickListener 导致的，必须重新 new OnItemClickListener才可以解决问题。

**Comment by limuyang2** [comment]
Adapter 设置给了多个recyclerview？

**Comment by limuyang2** [comment]
长时间未回复，先关闭issus
