### ISSUE TITLE
mRequestLoadMoreListener.onLoadMoreRequested()空指针

### ISSUE THREAD

**Issue by guoshaoxinabc** [CymChad/BaseRecyclerViewAdapterHelper#2952]
BaseQuickAdapter里：
getRecyclerView().post(new Runnable() {
                    @Override
                    public void run() {
                        mRequestLoadMoreListener.onLoadMoreRequested();
                    }
                });
这里希望加上if(null!=mRequestLoadMoreListener)判断

**Comment by limuyang2** [comment]
1de0b76458147ea3a80cd34113c0c748cddacf9e
