### ISSUE TITLE
setNewData使用

### ISSUE THREAD

**Issue by BaiMingxu** [CymChad/BaseRecyclerViewAdapterHelper#2954]
您好，我在瀑布流刷新使用setNewData() 但是图片会闪烁，好像是因为notifyDataSetChanged();有没有方法是notifyItemRangeInserted刷新的

**Comment by zhizhi1hao** [comment]
我也遇到了 请问事怎么解决的呢

**Comment by benxin123** [comment]
我也遇到了 请问事怎么解决的呢
