### ISSUE TITLE
自定义多布局问题，保留setMultiTypeDelegate方法

### ISSUE THREAD

**Issue by xiaobaDev** [CymChad/BaseRecyclerViewAdapterHelper#2955]
我们项目只用到了BaseQuickAdapter进行了封装，这个类能用setMultiTypeDelegate
但最新的50版本里面，BaseQuickAdapter删除了这个方法，导致项目报错了。

建议保留BaseQuickAdapter的setMultiTypeDelegate。你可以声明过期，但不能直接删除掉啊

**Comment by limuyang2** [comment]
主要是考虑到`setMultiTypeDelegate`从功能属性上来说，不属于`BaseQuickAdapter `
理应属于`MultipleItemRvAdapter`中到方法

**Comment by xiaobaDev** [comment]
那我这种情况有什么建议吗？
全局只基于BaseQuickAdapter封装了一个类，新版本要用setMultiTypeDelegate，只能再开一个类了吗》？

**Comment by Alexxiaopang** [comment]
我也是这个问题，新版本并没有找到MultipleItemRvAdapter

**Comment by GuoAxiang** [comment]
同问题
