### ISSUE TITLE
2.9.46->2.9.47局部刷新问题

### ISSUE THREAD

**Issue by mallxiaodoudou** [CymChad/BaseRecyclerViewAdapterHelper#2957]
**Describe the bug**

mNewsFeedAdapter.notifyItemChanged(position, "a");

以前可以局部刷新item中的一个小视图，升级到2.9.47之后无法生效了，非得用
mNewsFeedAdapter.notifyItemChanged(position);

但是会刷新闪动，还是用回了2.9.46，希望修复，只是觉得2.9.47中的Diff刷新好用。点赞

**Comment by Alexxiaopang** [comment]
我用diffutil也是闪动，请问有什么办法？
