### ISSUE TITLE
headerView 或 footerView 滑动问题

### ISSUE THREAD

**Issue by Dpuntu** [CymChad/BaseRecyclerViewAdapterHelper#2958]
你好，当使用 CoordinatorLayout 配合 Recyclerview（rw1） ，并且  BaseRecyclerViewAdapterHelper 添加 headerView 或者 footerView  也是一个 Recyclerview （rw2）的时候，出现滑动 rw2时，会提前把rw1滑动隐藏，而CoordinatorLayout 还未收缩，只有触摸滑动非headerView 或者 footerView 的区域的时候，滑动才是正常的，问下如何解决？

布局代码：

  <android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:tag="swipe_target" >

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:fadingEdge="none"
            app:elevation="0dp"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

            <android.support.design.widget.CollapsingToolbarLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:expandedTitleMarginEnd="64dp"
                app:expandedTitleMarginStart="48dp"
                app:layout_scrollFlags="scroll|snap|exitUntilCollapsed|enterAlwaysCollapsed">

                <FrameLayout
                    android:id="@+id/mine_content"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:scaleType="centerCrop"
                    app:layout_collapseMode="parallax"
                    app:layout_collapseParallaxMultiplier="0.3" />
            </android.support.design.widget.CollapsingToolbarLayout>

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="44dp"
                android:layout_alignParentBottom="true">

                <android.support.design.widget.TabLayout
                    android:id="@+id/mine_tab"
                    android:layout_width="156dp"
                    android:layout_height="30dp"
                    android:layout_gravity="center"
                    android:background="@drawable/round_button_bg_grey"
                    app:tabIndicatorColor="@android:color/transparent"
                    app:tabIndicatorHeight="0dp"
                    app:tabGravity="center"
                    app:tabPaddingBottom="-1dp"
                    app:tabPaddingEnd="-1dp"
                    app:tabPaddingStart="-1dp"
                    app:tabPaddingTop="-1dp"
                    app:tabMode="fixed" />
            </FrameLayout>
        </android.support.design.widget.AppBarLayout>

        <android.support.v4.view.ViewPager
            android:id="@+id/mine_view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />

    </android.support.design.widget.CoordinatorLayout>

**Comment by limuyang2** [comment]
`headerView` `footerView`中不建议使用滑动布局

**Comment by limuyang2** [comment]
长时间未回复，先关闭issue，如有问题，请新开issue
