### ISSUE TITLE
setOnItemClickListener 快速点击的时候会打开2个页面

### ISSUE THREAD

**Issue by lovemianhuatang** [CymChad/BaseRecyclerViewAdapterHelper#2960]
![image](https://user-images.githubusercontent.com/41498415/69598386-20a92d00-1044-11ea-8ff0-103e791f24c5.png)

我直接点击demo Multipleltem 里的2个模块  快速点击也会出现2个页面 （2只手指点击不同地方）

**Comment by luoyexk** [comment]
启动模式singleTop应该可以解决。

**Comment by limuyang2** [comment]
自己做双击拦截。此功能不属于本库范畴
