### ISSUE TITLE
GridLayoutManager  添加的footer只占一列

### ISSUE THREAD

**Issue by yingka** [CymChad/BaseRecyclerViewAdapterHelper#2961]
![youdu图片20191126182828](https://user-images.githubusercontent.com/20808020/69622165-66cdb300-107b-11ea-85a2-d8b6cee32fbf.png)

recyclerView先设置LinearLayoutManager，再绑定adapter，再次设置GridLayoutManager

**Comment by limuyang2** [comment]
为何会有这种需求呢？

**Comment by lhj1079947827** [comment]
recyclerView设置GridLayoutManager如果数据不满一屏幕的时候显示出来的“没有更多数据”view只占了一列，没有铺满整列[
![image](https://user-images.githubusercontent.com/20966610/71467087-ad3e3b00-27fc-11ea-91d1-c5a7843309c8.png)
](url)
