### ISSUE TITLE
大神  3.x 的版本准备什么时候发布嘞

### ISSUE THREAD

**Issue by yuehongjie** [CymChad/BaseRecyclerViewAdapterHelper#2965]
大神  3.x 的版本准备什么时候发布嘞

**Comment by limuyang2** [comment]
您好，3.x依然还在重写中。预计本月会出alpha预览版本

**Comment by limuyang2** [comment]
`alpha`已经发布，可以提前尝鲜，欢迎反馈`BUG`。
[](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/README-cn.md)

**Comment by CasparXL** [comment]
> `alpha`已经发布，可以提前尝鲜，欢迎反馈`BUG`。
> [README](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/README-cn.md)

大佬，3.x-alpha-0.5-g85084eb-1这个版本拉不下来，报错了，请问是啥原因嘞，还是说要单独引用下来

**Comment by limuyang2** [comment]
> > `alpha`已经发布，可以提前尝鲜，欢迎反馈`BUG`。
> > [README](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/README-cn.md)
> 
> 大佬，3.x-alpha-0.5-g85084eb-1这个版本拉不下来，报错了，请问是啥原因嘞，还是说要单独下载下来

现在3.x 已发布beta版本，请前往主页查看
