### ISSUE TITLE
这文档写的跟屎一样

### ISSUE THREAD

**Issue by dlgchg** [CymChad/BaseRecyclerViewAdapterHelper#2968]
这文档写的跟屎一样

**Comment by SawDouma** [comment]
我怎么觉得文档写的很好，我用的很爽？  你问题不说清楚，只会抱怨，就会一直菜下去。

**Comment by liujia95** [comment]
用人家开源的东西戾气还这么大，看来还是缺少社会的毒打

**Comment by dlgchg** [comment]
可惜,我有钱

**Comment by zhaoxiuyu** [comment]
我也觉得文档写的不怎么样。点击 Wiki 是英文的，底部有 中文 连接，点击跳转简书了，2017年的。

https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/首页 这个连接是中文说明 还是我很久以前收藏下来的，现在找不到了，但是可以访问，也没更新内容了。

首页的中文1还可以看看，但是为什么是裂图。
这个库还是非常给力的，一直在用。

**Comment by q88qaz** [comment]
你怎么可以侮辱屎呢？

**Comment by cc365774016** [comment]
你有钱可以给他10W，20W的，让他给你独家更新一份

**Comment by limuyang2** [comment]
您好，现有文档足够使用了。新版文档会在3.x发布之后，全新重写
