### ISSUE TITLE
upfetch不满一页的时候 会不停加载

### ISSUE THREAD

**Issue by onism0106** [CymChad/BaseRecyclerViewAdapterHelper#2969]
如上，只有一个方法是设置上拉加载 的，disableLoadMoreIfNotFullPage
但是下拉加载的没有设置 方法，这是个bug？

**Comment by limuyang2** [comment]
您好，我稍后进行测试

**Comment by limuyang2** [comment]
确实是有这样的问题。但是不属于bug，upfetch本身只是一个简单实现，没有loadmore的那么多功能。
如果数据过少，upfetch设置为关闭就可以了
