### ISSUE TITLE
滑动删除怎么恢复

### ISSUE THREAD

**Issue by jituijiaqiezi** [CymChad/BaseRecyclerViewAdapterHelper#297]
BaseItemDraggableAdapter滑动删除的时候，我添加了一个dialog去确定是否删除，点击取消，那么列表中的项就变成一片空白，不知道是否可以告知恢复列表内容的方法呢？代码如下

    public class StageNameAdapter extends BaseItemDraggableAdapter<String> {

    public StageNameAdapter(List<String> data){
        super(R.layout.item_stage_name,data);
    }
    @Override
    protected void convert(BaseViewHolder holder, String name) {
        holder.setText(R.id.text_name,name);
    }

    @Override
    public void onItemSwiped(RecyclerView.ViewHolder viewHolder) {
        UIUtil.showDialog(mContext, "确定移除项目阶段:" + mData.get(viewHolder.getLayoutPosition()) + "?", (dialogInterface, i) -> {
            StageNameAdapter.super.onItemSwiped(viewHolder);
        });
    }
    }

只有在点击确定之后才会执行父类的onItemSwiped，但是点击取消，item没有删除，但是那一行就变成了空白，不知道有没有什么解决办法。因为同时也需要用到这个adapter的移动改变item的排列，所以使用swipeLayout有点难度。跪求大神提供点思路

**Comment by elfman** [comment]
调用`adapter.notifyItemChanged(position)`就能恢复原状了，同时你需要重写adapter中的`onItemSwiped`方法，阻止数据被删除

**Comment by jituijiaqiezi** [comment]
@elfman 谢谢了

**Comment by fWX228941** [comment]
@jituijiaqiezi @elfman  求两位看看，同样的问题，如何阻止数据被删除。	 OnItemSwipeListener onItemSwipeListener = new OnItemSwipeListener() {
            @Override
            public void onItemSwipeStart(RecyclerView.ViewHolder viewHolder, int pos) {


            }

            @Override
            public void clearView(RecyclerView.ViewHolder viewHolder, int pos) {

            }

            @Override
            public void onItemSwiped(RecyclerView.ViewHolder viewHolder, int pos) {
                mAdapter.notifyItemChanged(pos);
            }

            @Override
            public void onItemSwipeMoving(Canvas canvas, RecyclerView.ViewHolder viewHolder, float dX, float dY, boolean isCurrentlyActive) {

            }
        };

**Comment by fWX228941** [comment]
@jituijiaqiezi @elfman  public class ItemDragAdapter extends BaseItemDraggableAdapter<String> {

    boolean isdelted = false;
    public ItemDragAdapter(List data) {
        super(R.layout.item_draggable_view, data);
    }

    @Override
    protected void convert(BaseViewHolder helper, String item) {
        helper.setText(R.id.tv, item);
    }

    @Override
    public void onItemSwiped(final RecyclerView.ViewHolder viewHolder) {

        new SweetAlertDialog(mContext, SweetAlertDialog.WARNING_TYPE)
                .setTitleText("确定要删除吗？")
                .setConfirmText("删除")
                .setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                    @Override
                    public void onClick(SweetAlertDialog sDialog) {
                        ItemDragAdapter.super.onItemSwiped(viewHolder);
                        sDialog.dismissWithAnimation();
                    }
                })
                .setCancelText("取消")
                .setCancelClickListener(new SweetAlertDialog.OnSweetClickListener() {
                    @Override
                    public void onClick(SweetAlertDialog sDialog) {
                        sDialog.cancel();
                    }
                })
                .show();

    }

**Comment by fWX228941** [comment]
@CymChad  大神帮忙看看

**Comment by elfman** [comment]
`notifyItemChanged`应该放在`cancelClickListener`里，`confirmClickListener`里不要执行父类的`onItemSwiped`，自己手动把数据删除，具体参考源码。重写了Adapter的`onItemSwiped`后，`Callback`的`onItemSwiped`也不会再被调用了，就不要把代码放到里面去了

**Comment by fWX228941** [comment]
谢谢，测试了下，把notifyItemChanged 替换成  notifyDataSetChanged(); 未删除的数据就能恢复原状了。

**Comment by fWX228941** [comment]
两种方式都是可以的。
方式一：
  	   OnItemSwipeListener onItemSwipeListener = new OnItemSwipeListener() {
            @Override
            public void onItemSwipeStart(final RecyclerView.ViewHolder viewHolder, final int pos) {

                  new SweetAlertDialog(ItemDragAndSwipeUseActivity.this, SweetAlertDialog.WARNING_TYPE);
						.setTitleText("确定要删除吗？")
                        .setConfirmText("删除")
                        .setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                            @Override
                            public void onClick(SweetAlertDialog sDialog) {
                                sDialog.dismissWithAnimation();
                                mAdapter.remove(pos);
                            }
                        })
                        .setCancelText("取消")
                        .setCancelClickListener(new SweetAlertDialog.OnSweetClickListener() {
                            @Override
                            public void onClick(SweetAlertDialog sDialog) {
                                sDialog.cancel();
                                mAdapter.notifyDataSetChanged();
                            }
                        })
                        .show();
            }



@Override
public void onItemSwiped(final RecyclerView.ViewHolder viewHolder) {
}

**Comment by fWX228941** [comment]
方式二：
 @Override
    public void onItemSwiped(final RecyclerView.ViewHolder viewHolder) {
            pDialog = new SweetAlertDialog(mContext, SweetAlertDialog.WARNING_TYPE);
            pDialog.setTitleText("确定要删除吗？")
                    .setConfirmText("删除")
                    .setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                        @Override
                        public void onClick(SweetAlertDialog sDialog) {
                                sDialog.dismissWithAnimation();
                                ItemDragAdapter.super.onItemSwiped(viewHolder);
                         
                        }
                    })
                    .setCancelText("取消")
                    .setCancelClickListener(new SweetAlertDialog.OnSweetClickListener() {
                        @Override
                        public void onClick(SweetAlertDialog sDialog) {
                            sDialog.cancel();
                        }
                    })

                    .show();
            pDialog.setOnDismissListener(new DialogInterface.OnDismissListener() {
                @Override
                public void onDismiss(DialogInterface dialog) {
                    notifyDataSetChanged();
                    pDialog.dismissWithAnimation();
                }
            });
   }

OnItemSwipeListener onItemSwipeListener = new OnItemSwipeListener() {
            @Override
            public void onItemSwipeStart(final RecyclerView.ViewHolder viewHolder, final int pos) {

            }

            @Override
            public void clearView(RecyclerView.ViewHolder viewHolder, int pos) {



            }

            @Override
            public void onItemSwiped(RecyclerView.ViewHolder viewHolder, int pos) {


            }

            @Override
            public void onItemSwipeMoving(Canvas canvas, RecyclerView.ViewHolder viewHolder, float dX, float dY, boolean isCurrentlyActive) {

            }
        };

**Comment by elfman** [comment]
`notifyItemChanged`我试过是没问题的啊，你看下是不是position不对，应该对应的是显示时的位置，跟数据集里的位置不一定对应。
`notifyDataSetChanged`会重绘整个RecyclerView，但这里实际只需重绘一个item就行了，所以我是喜欢用`notifyItemChanged`，虽然对现在的手机来说这点花销不值一提

**Comment by Tiannuo** [comment]
notifyItemChanged这个方法确实不能显示那个滑动删除的选项，作者源码怎么写的可以发看看吗？

**Comment by Ervinnn** [comment]
如果是要通过后台网络数据的错误结果，来对滑动删除进行拦截呢？要怎么实现？
