### ISSUE TITLE
你好博主，之前我把项目切换到 androidx的模式之后，各种报错。什么时候能出个兼容androidx的版本

### ISSUE THREAD

**Issue by z244370114** [CymChad/BaseRecyclerViewAdapterHelper#2970]
你好，之前我把项目切换到 androidx的模式之后，各种报错。什么时候能出个兼容androidx的版本

**Comment by Ayagikei** [comment]
README有写[androidX stable Version](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.9.45-androidx)

**Comment by limuyang2** [comment]
请更新使用3.0 版本

**Comment by xiaojidonggong** [comment]
@limuyang2 我切换到AndroidX 使用 2.9.30版本，没有报错。
