### ISSUE TITLE
BaseMultiItemQuickAdapter多类型问题

### ISSUE THREAD

**Issue by maxrco** [CymChad/BaseRecyclerViewAdapterHelper#2977]
项目中多类型是有包含横向滑动的item如何解决?看了DEMO只有包含列表和宫格布局的,目前BaseMultiItemQuickAdapter无法满足需求,暂时我只能通过RecyclerView嵌套RecyclerView去解决,但是Google官方是不推荐这种写法的,对复用和性能都是非常不好的

**Comment by limuyang2** [comment]
纵向包含横向的，只能嵌套RecyclerView。只是嵌套的RecyclerView注意一下写法，就不会有什么性能问题。

官方的viewPager2就是用RecyclerView实现的，横向viewPager2里放RecyclerView列表，也不会有性能问题。官方用法也是如此，所以并不存在“Google官方是不推荐的”这种说法

**Comment by maxrco** [comment]
老大谢谢你的解答,我想请问下使用BaseMultiItemQuickAdapter如何给不同的item添加不同的addItemDecoration.目前加addItemDecoration是给整个RecyclerView所有的item,老大麻烦问下有没有好的解决方案

**Comment by lantee** [comment]
按照文档说明 自定义了动画 
deviceAdapter.openLoadAnimation(view -> new Animator[]{ObjectAnimator.ofFloat(view, "scaleY", 0, 1),
					ObjectAnimator.ofFloat(view, "scaleX", 0, 1),
					ObjectAnimator.ofFloat(view, "alpha", 0, 1)});
也重写了startAnim方法（如下） 但是延时并不起作用
@Override
    protected void startAnim(Animator anim, int index) {
        super.startAnim(anim, index);
        anim.setStartDelay(index * 150);
    }
有修改了一下重写的方法 这样写虽然动画有延时效果了
但是具体效果表现是已经刷新出列表了 再去播放每一个item的动画
@Override
    protected void startAnim(Animator anim, int index) {
        anim.setStartDelay(index * 150);
        super.startAnim(anim, index);
    }
请问是哪里出了问题吗
