### ISSUE TITLE
添加动画延时效果问题

### ISSUE THREAD

**Issue by lantee** [CymChad/BaseRecyclerViewAdapterHelper#2979]
按照文档说明 自定义了动画
deviceAdapter.openLoadAnimation(view -> new Animator[]{ObjectAnimator.ofFloat(view, "scaleY", 0, 1),
ObjectAnimator.ofFloat(view, "scaleX", 0, 1),
ObjectAnimator.ofFloat(view, "alpha", 0, 1)});
也重写了startAnim方法（如下） 但是延时并不起作用
@override
protected void startAnim(Animator anim, int index) {
super.startAnim(anim, index);
anim.setStartDelay(index * 150);
}
有修改了一下重写的方法 这样写虽然动画有延时效果了
但是具体效果表现是已经刷新出列表了 再去播放每一个item的动画
@override
protected void startAnim(Animator anim, int index) {
anim.setStartDelay(index * 150);
super.startAnim(anim, index);
}
请问是哪里出了问题吗

**Comment by limuyang2** [comment]
你可以使用`android:layoutAnimation`
参考：[使用RecyclerView和LayoutAnimation给列表添加进入动画](https://majing.io/posts/10000006531155)
