### ISSUE TITLE
为什么树形结构的时候返回是pos会错位

### ISSUE THREAD

**Issue by qzqs** [CymChad/BaseRecyclerViewAdapterHelper#2980]
当前使用的版本号 2.9.12
复现操作描述 展开子列表的时候返回pos是错误的
使用代码
--->构造父节点和子节点
 ArrayList<MultiItemEntity> res = new ArrayList<>();
            for (int i = 0; i < getAddItemExtensionList.getData().size(); i++) {
                GetAddItemExtensionList.DataBean dataBean = getAddItemExtensionList.getData().get(i);
                if (dataBean.getReasons().size() > 0) {
                    /**
                     * 应该是每个大项包含几个伸展出来的小项
                     */
                    for (int j = 0; j < dataBean.getReasons().size(); j++) {
                        reasonsBean = dataBean.getReasons().get(j);
                        reasonsBean.setSkuid(dataBean.getSkuid());
                    }
                    dataBean.addSubItem(reasonsBean);
                }
                res.add(dataBean);
            }
            adapter = new ZengxiangbukuanItemAdapter(res,ZengxiangbukuanActivity.this,orderAddItemsHashMap);
recyclerView.setAdapter(adapter);
----->适配器里面代码
 case TYPE_LEVEL_0:
                lv0 = (GetAddItemExtensionList.DataBean) item;
                if (!getAddItemExtensionList.contains(lv0)) {
                    getAddItemExtensionList.add(lv0);
                }
                if (!orderAddItemsHashMap.containsKey(lv0.getSkuid())) {
                    orderAddItemss = new SetAddItemExtensionPay.OrderAddItems();
                    orderAddItemsHashMap.put(lv0.getSkuid(), orderAddItemss);
                    orderAddItemsHashMap.get(lv0.getSkuid()).setSKUID(lv0.getSkuid());
                }
                holder.setText(R.id.title, lv0.getProductName())
                        .setText(R.id.tv_zhuangtai, lv0.isExpanded()
                                ? "收起" : "展开")
                        .setImageResource(R.id.iv, lv0.isExpanded()
                                ? R.drawable.xiangshang : R.drawable.xiangxia);
                holder.itemView.setOnClickListener(v -> {
                    int pos = holder.getLayoutPosition();
                    if (lv0.isExpanded()) {
                        collapse(pos);
                    } else {
                        if (getAddItemExtensionList.get(pos).getReasons().size() == 0) {
                            ToastUtils.showRoundRectToast("商品未配置增项费用");
                        } else {
                            expand(pos);
                        }
                    }
                });
  break;
crash日志
没有报错，就是 int pos = holder.getLayoutPosition();
有时候本来只有两项0和1 但是有时候点击展开的时候pos会返回2，就是返回pos是错误的，不清楚什么去解决

**Comment by qzqs** [comment]
特别是当展开有子项的情况下，再去展开其他的子项，获取pos 就错位的..

**Comment by qzqs** [comment]
而且为什么有时候子项都展开了，点击的时候返回的状态又是关闭状态，pos错位，展开和关闭的状态也是错乱的。

**Comment by limuyang2** [comment]
请尝试3.x版本的`BaseNodeAdapter`
