### ISSUE TITLE
ViewPager2 推出了 能不能尽快适配一下

### ISSUE THREAD

**Issue by 24kpk** [CymChad/BaseRecyclerViewAdapterHelper#2981]
#  ViewPager2 推出了 能不能尽快适配一下
ViewPager2 来源

```
dependencies {
    implementation "androidx.viewpager2:viewpager2:1.0.0"
}
```

适配需求

```
ViewPager2基于RecyclerView实现  适配器ViewHolder需要继承PagerViewHolder 还请尽快适配一下
```

**Comment by limuyang2** [comment]
`ViewPager2`中并未限定`Adapter`类型、`ViewHolder`类型，所以不存在适配的说法。本库可以直接使用。
同时`ViewPager2`源码中也并不包含`PagerViewHolder `这个东西。

请阅读`ViewPager2`源码
