### ISSUE TITLE
局部刷新有时有效有时无效

### ISSUE THREAD

**Issue by yanlianhanlin** [CymChad/BaseRecyclerViewAdapterHelper#2982]
使用BaseQuickDiffCallback时，获取数据刷新更改状态时有时正常刷新更改状态有时不会，当滚动recycleview后再滚动到需要刷新的item时状态已经改变，不知道是因为哪方面导致的这个问题

**Comment by Djangoogle** [comment]
我这边是**addHeaderView**以后出现了问题，部分item无法局部刷新，划出屏幕后再滑回来就好了

**Comment by limuyang2** [comment]
`mAdapter.notifyItemChanged(pos + mAdapter.getHeaderLayoutCount(),  payload);`

位置要加上`getHeaderLayoutCount()`

**Comment by limuyang2** [comment]
> 我这边是**addHeaderView**以后出现了问题，部分item无法局部刷新，划出屏幕后再滑回来就好了

mAdapter.notifyItemChanged(pos + mAdapter.getHeaderLayoutCount(), payload);

位置要加上getHeaderLayoutCount()

**Comment by Djangoogle** [comment]
@limuyang2 已解决，多谢提醒
