### ISSUE TITLE
2.9.50 GridLayoutManager BUG

### ISSUE THREAD

**Issue by wojiaojay123** [CymChad/BaseRecyclerViewAdapterHelper#2983]
从2.9.30升级到2.9.50，当列表数据增加时(减少没问题)，手动刷新页面的时候，GridLayoutManager 最后一个item布局会单独占一行，view变大，撑满整个屏幕，2.9.30没有这个bug

**Comment by limuyang2** [comment]
可否给个示例？

**Comment by limuyang2** [comment]
长时间未回复，先关闭issue，如有问题，请新开issue

**Comment by GodFan4** [comment]
我也遇到了类似的问题，设置显示两列
如果加载过一次单数的情况后就会异常
有时候从第二个开始就变成一行只显示一个，有时候是从后几个。
@limuyang2
