### ISSUE TITLE
使用mAdapter.loadMoreComplete();会触发setOnLoadMoreListener然后一直循环load

### ISSUE THREAD

**Issue by XuYinShuang** [CymChad/BaseRecyclerViewAdapterHelper#2985]
mAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
//            @Override
//            public void onLoadMoreRequested() {
//                page++;
//                getProjectUserList();
//            }
//        }, mRecycleView);

//这是获取数据之后 掉用loadMoreComplete()还是会触发 setOnLoadMoreListener
if (newDescBeans.data.page == newDescBeans.data.allPage) {
//                //第一页如果不够一页就不显示没有更多数据布局
//                mAdapter.loadMoreEnd();
//            } else {
//                mAdapter.loadMoreComplete();
//            }

**Comment by limuyang2** [comment]
先`addData`，再`mAdapter.loadMoreComplete()`

**Comment by XuYinShuang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mumu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 中午12:44
收件人:&nbsp;"CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;;
抄送:&nbsp;"徐银双"<1427195044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CymChad/BaseRecyclerViewAdapterHelper] 使用mAdapter.loadMoreComplete();会触发setOnLoadMoreListener然后一直循环load (#2985)




先addData，再mAdapter.loadMoreComplete()

**Comment by XuYinShuang** [comment]
我使用的是androidX版本的 1427195044 邮箱：1427195044@qq.com 签名由 网易邮箱大师 定制 在2019年12月19日 12:45，徐银双 写道： ------------------ 原始邮件 ------------------ 发件人: "mumu"<notifications@github.com>; 发送时间: 2019年12月19日(星期四) 中午12:44 收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 抄送: "徐银双"<1427195044@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 使用mAdapter.loadMoreComplete();会触发setOnLoadMoreListener然后一直循环load (#2985) 先addData，再mAdapter.loadMoreComplete() — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Zane1024** [comment]
看下你的RecyclerView是否被NestedScrollView包裹着、我今天就是给这个坑了

**Comment by XuYinShuang** [comment]
用了swipeRefreshLayout




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zane1024"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 下午3:52
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;; 
抄送: "徐银双"<1427195044@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 使用mAdapter.loadMoreComplete();会触发setOnLoadMoreListener然后一直循环load (#2985)




看下你的RecyclerView是否被NestedScrollView包裹着、我今天就是给这个坑了

**Comment by yihu5566** [comment]
我的也是会一直加载...怎么解决的?

**Comment by XuYinShuang** [comment]
还没解决😂😂 1427195044 邮箱：1427195044@qq.com 签名由 网易邮箱大师 定制 在2019年12月23日 14:21，shark fly 写道： 我的也是会一直加载...怎么解决的? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gh2571527745** [comment]
我的也是，androidX的，同样的问题

**Comment by runfengai** [comment]
搞死了。。。。同样的问题，看这样子难道只能自己加了么。嵌套了NestedScrollView

**Comment by XuYinShuang** [comment]
我已经放弃了这个上拉加载，用了自己定义得，你也可以用smartRefreshLayout得，这个不会冲突




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jarry"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 下午3:39
收件人:&nbsp;"CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;;
抄送:&nbsp;"徐银双"<1427195044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CymChad/BaseRecyclerViewAdapterHelper] 使用mAdapter.loadMoreComplete();会触发setOnLoadMoreListener然后一直循环load (#2985)




搞死了。。。。同样的问题，看这样子难道只能自己加了么。嵌套了NestedScrollView

**Comment by jack-smith** [comment]
> 搞死了。。。。同样的问题，看这样子难道只能自己加了么。嵌套了NestedScrollView

说一下间接的处理方法：
1、使用添加headerView的方式，这样就不需要外面嵌套ScrollView（多Item的处理方式也可以）；
2、对于添加headerView，但是为空时需要显示的，可以多放一个重复布局，用于数据为空时，headerView也显示的备用显示布局

**Comment by qq764215676** [comment]
我也是这个问题，用了NestedScrollView

**Comment by LentoLee** [comment]
对于CoordinatorLayout、NestedScrollView 这种造成的 onLoadMoreRequested() 多次调用问题，
提供一个简单的规避方法：在 onLoadMoreRequested() 回调时，先执行 recyclerView.stopScroll()，然后再做去请求，就不会发生多次调用的问题了。

**Comment by Natanic** [comment]
> 我也是这个问题，用了NestedScrollView
> getLoadMoreModule().setEnableLoadMoreIfNotFullPage(false)可以解决这个问题，但是调用后只能手动点击加载更多
> 或者改成ScrollView
> 或者不用NestedScrollView、ScrollView，把其他视图以HeaderView、FootView的方式设置到RecyclerView中(相当于整个页面只有一个RecyclerView)

新版本可以第一种方式
