### ISSUE TITLE
BaseMultiItemQuickAdapter中调用setData刷新数据会自动跳转到第一个位置

### ISSUE THREAD

**Issue by lhjgege** [CymChad/BaseRecyclerViewAdapterHelper#2986]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
版本号2.9.50
2. 复现操作描述
在adpter.setOnItemChildClickListener中调用adpter.setData（）刷新数据会自动跳到第一个位置
3. 使用代码
[
![问](https://user-images.githubusercontent.com/20966610/71157155-65f3ff80-227c-11ea-81f6-cc03c3eb8424.png)
](url)
3. crash日志
4. gif复现效果
[
![GIF](https://user-images.githubusercontent.com/20966610/71157165-6ab8b380-227c-11ea-985c-3f00d87c83c4.gif)
](url)

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by limuyang2** [comment]
可否给一个demo

**Comment by lhj1079947827** [comment]
我下一个demo看看是我的问题还是你的问题哈，等等哈

**Comment by ggyg123** [comment]
@limuyang2  我的也是这种情况，  列表添加了两个headerView,在headerView下方有个刷新数据的按钮，点击刷新按钮，数据刷新然后滚动到列表顶部，我用了BaseMultiItemQuickAdapter和上拉加载，请问有什么办法刷新不要滚动到列表顶部
