### ISSUE TITLE
empty view not show when loading

### ISSUE THREAD

**Issue by PascalTang** [CymChad/BaseRecyclerViewAdapterHelper#2987]
爬文找不到

我希望在第一次加載時

empty view會顯示出來

程式碼很短

`
  rv_video.layoutManager = GridLayoutManager(activity, 1)

        val rankAdapter = SearchAdapter(R.layout.item_search)

        rankAdapter.emptyView = LayoutInflater.from(activity).inflate(R.layout.item_empty_view, null, false)

        rankAdapter.onItemClickListener = BaseQuickAdapter.OnItemClickListener { adapter, view, position ->

        }

        rv_video.adapter = rankAdapter
`

但他沒有出現empty view

只有set data是空的才會

但我其他的頁面差不多形式

卻會顯示 我找不出差異

麻煩給我個指引

感謝

**Comment by PascalTang** [comment]
沒有答案嗎

**Comment by limuyang2** [comment]
```kotlin
val emptyView = layoutInflater.inflate(R.layout.empty_view, recyclerView, false)
adapter.setEmptyView(emptyView)
recyclerView.adapter = adapter
```
此写法没有问题，请参考

**Comment by dendrocyte** [comment]
`val emptyView = layoutInflater.inflate(R.layout.empty_view, recyclerView, false)
adapter.setEmptyView(emptyView)`
**===> still crash**

but @limuyang2 it works! Thanks!
