### ISSUE TITLE
BaseQuickAdapter as Anonymous class Click Listener 

### ISSUE THREAD

**Issue by omkar-tenkale** [CymChad/BaseRecyclerViewAdapterHelper#2989]
I struggled a lot here implementing click listener for itemchild
```

 adapter = new BaseQuickAdapter<Product, BaseViewHolder>(R.layout.item_catalog, products) {

            {
                Logger.d("setting click listener for child");
                setOnItemChildClickListener(new OnItemChildClickListener() {
                    @Override
                    public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                        switch (view.getId()){
                            case R.id.tvSchemeIndicator:
                                Logger.d("CLicked item at  "+position);
                                Toast.makeText(mContext, "onItemClick of anon class"+view.getId(), Toast.LENGTH_SHORT).show();
                                break;
                        }
                    }
                });
            }
            @Override
            protected void convert(BaseViewHolder helper, Product item) {
                helper.setText(R.id.tvProductName, item.getString("name"));
                helper.addOnClickListener(R.id.tvSchemeIndicator);
            }
        };
        adapter.bindToRecyclerView(rvCatalog);
```

**Why does the helper have this method** 
`"addOnClickListener(R.id)"
`
**shouldn't this be the adapter method?**
for example
`adapter.addOnClickListener(R.id.tvSchemeIndicator);
`
instead of 

`helper.addOnClickListener(R.id.tvSchemeIndicator);
`

As there will be repeated calls to this method on every convert of an item when clickable views should be only set once as they are not changing later.

**Comment by omkar-tenkale** [comment]
The example posted above is working.
My concern is about the repetitive calls from convert method when same can be done while adapter initialization.with a similar or same method.

**Comment by limuyang2** [comment]
In the 2.x version, the click event does indeed repeat `convert`. This situation will be modified in version 3.x

**Comment by limuyang2** [comment]
Long time no reply, close first
