### ISSUE TITLE
关于BaseNodeAdapter二级列表，展开点击的一个然后收起其他全部展开的

### ISSUE THREAD

**Issue by houyinyu** [CymChad/BaseRecyclerViewAdapterHelper#2991]
当前使用的版本号：在Github上面下载的Demo里面修改运行；
复现操作描述：
有这样一个需求，请求数据后默认展开第一个group，其他的收起，点击其他group后收起已经展开的group,我这边在 FirstProvider 的onClick监听里面做的循环：
![VRNLF_PE3G0 2%OF4@ AU~E](https://user-images.githubusercontent.com/20554445/71304288-9dd78000-23ff-11ea-9030-8b3a1f359c76.png)
出现一个问题
展开的position高于点击的position 的时候正常打开点击的，关闭已展开的（正常）；
展开的position低于点击的position 的时候，已展开的是已经关闭了，但是点击的没有打开。

**Comment by houyinyu** [comment]
图片好像打开太慢了--
在FirstProvider里面的onClick：
`  @Override
    public void onClick(@NotNull BaseViewHolder helper, @NotNull View view, BaseNode data, int position) {

        FirstNode node = (FirstNode) data;
        //        if (node.isExpanded()) {
//            getAdapter().collapse(position);
//        } else {
        if (!node.isExpanded()) {
            getAdapter().expand(position);
        }
        for (int i = 0; i < getAdapter().getItemCount(); i++) {
            if (position != i) {
                getAdapter().collapse(i);
            }
        }

    }`

**Comment by houyinyu** [comment]
图片好像打开太慢了--
在FirstProvider里面的onClick：
`    public void onClick(@NotNull BaseViewHolder helper, @NotNull View view, BaseNode data, int position) {

        FirstNode node = (FirstNode) data;
        //        if (node.isExpanded()) {
//            getAdapter().collapse(position);
//        } else {
        if (!node.isExpanded()) {
            getAdapter().expand(position);
        }
        for (int i = 0; i < getAdapter().getItemCount(); i++) {
            if (position != i) {
                getAdapter().collapse(i);
            }
        }

    }`

**Comment by houyinyu** [comment]
`  public void onClick(@NotNull BaseViewHolder helper, @NotNull View view, BaseNode data, int position) {

        FirstNode node = (FirstNode) data;
        //        if (node.isExpanded()) {
//            getAdapter().collapse(position);
//        } else {
        if (!node.isExpanded()) {
            getAdapter().expand(position);
        }
        for (int i = 0; i < getAdapter().getItemCount(); i++) {
            if (position != i) {
                getAdapter().collapse(i);
            }
        }

    } `

**Comment by houyinyu** [comment]
图片有点卡
在FirstProvider的onClick里面：

`public void onClick(@NotNull BaseViewHolder helper, @NotNull View view, BaseNode data, int position) {
         if (!node.isExpanded()) {
             getAdapter().expand(position);
         }
         for (int i = 0; i < getAdapter().getItemCount(); i++) {
             if (position != i) {
                 getAdapter().collapse(i);
             }
         }
     }
     `

**Comment by houyinyu** [comment]
图片有点卡，在FirstProvider的onClick里面：
	  
     if (!node.isExpanded()) {
            getAdapter().expand(position);
        }
        for (int i = 0; i < getAdapter().getItemCount(); i++) {
            if (position != i) {
                getAdapter().collapse(i);
            }
        }

    }

**Comment by limuyang2** [comment]
谢谢反馈，会后续跟进修改

**Comment by limuyang2** [comment]
beta 2已经发布，新增'expandAndCollapseOther()' 方法。
根据测试，数据迭代方法没有问题。出现如你所述问题的原因如下：
当一个node 折叠以后，`position `多对应的位置就会变化，所以不能简单的使用for循环处理，为了方便使用，新增了方法。具体逻辑可以查看源码了解
