### ISSUE TITLE
3.0.0-beta1 混淆打包出错，can't find referenced method 'void setContext(android.content.Context)

### ISSUE THREAD

**Issue by ixingzhi** [CymChad/BaseRecyclerViewAdapterHelper#2992]
can't find referenced method 'void setContext(android.content.Context)

**Comment by limuyang2** [comment]
经测试，没有发生此问题，请检查你主项目的其他混淆配置

**Comment by ixingzhi** [comment]
经过测试，我看了下作者Demo中，只有HomeAdapter用了Kotlin代码（没有引用BaseQuickAdapter中的context）；现在初步判断，原因是：Kotlin写的Adapter中，只要引用BaseQuickAdapter中的context，打包就会有问题。

**Comment by limuyang2** [comment]
```java
override fun convert(helper: BaseViewHolder, item: HomeEntity?) {
    Toast.makeText(context,"",Toast.LENGTH_SHORT).show()
}
```
`Adapter`中使用`context`
经过打包测试没有问题，请检查你项目的其他配置。

我也新建了一个测试项目，倒入了库，使用contenxt，然后打包、安装、反编译，都没问题。

**Comment by limuyang2** [comment]
根据源代码，`context`的定义如下：
```java
protected lateinit var context: Context
    private set
```
赋值为私有，对外暴露的只有`getContext()`。

根据我反编译查看，`BaseQuickAdapter`类中根本不存在`setContext()`方法，只存在`getContext()`。
由于赋值为私有，所以代码就没必备生成`setContext()`方法，`Adapter`内部对`context`赋值是直接进行的等号赋值：`this.context = con`。
由此可见，混淆后的编译生成的代码是符合源码定义逻辑的。

如果还有疑问，请新建项目再进行测试。
