### ISSUE TITLE
helper.getView  能否返回null，而不抛出异常呢。。我记得之前的版本可以的。。3.0版本不行了

### ISSUE THREAD

**Issue by huanghaoming** [CymChad/BaseRecyclerViewAdapterHelper#2993]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by limuyang2** [comment]
是有什么特殊需求么？
主要是最初考虑到在kotlin中返回null，写起来不太好看

**Comment by huanghaoming** [comment]
其实是这样的。。。我是想在多布局的情况下，在Adapter中写一些公共函数。。。有些view有些布局有，有些布局是没有的。。。本来呢是可以通过if else判断一下布局的type。。但是嫌麻烦，，有10几个布局。。没办法的话，我就用try catch盖住了

**Comment by huanghaoming** [comment]
再问一下，请问新版本能继承BaseViewHolder吗，我想自己实现一下，但是你们是不是写的不太好扩展了？

**Comment by huanghaoming** [comment]
再问一下，BaseProviderMultiAdapter下，请问新版本能继承BaseViewHolder吗，我想自己实现一下，但是你们是不是写的不太好扩展了？

**Comment by limuyang2** [comment]
1、下个版本会增加一个`getViewOrNull()`的方法
2、`BaseProviderMultiAdapter `的`BaseViewHolder `可以继承，实现自己的vh，可自定义程度是高于之前的版本的

**Comment by limuyang2** [comment]
查看此处的[MD](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/readme/4-%E5%A4%9A%E5%B8%83%E5%B1%80.md#BaseProviderMultiAdapter)
每一个Provider都可以有自己的VH类型，不再局限了

**Comment by huanghaoming** [comment]
BaseItemProvider和BaseProviderMultiAdapter我并没看到哪里可以自定义BaseViewholder啊。。大哥可以具体教我一下吗。。。我看了一下BaseDelegateMultiAdapter和MultipleItemQuickAdapter都有的

**Comment by huanghaoming** [comment]
好像明白了。。是在BaseItemProvider重写viewholder是吧。。。呃。。在BaseProviderMultiAdapter里可以定义吗

**Comment by limuyang2** [comment]
> BaseItemProvider和BaseProviderMultiAdapter我并没看到哪里可以自定义BaseViewholder啊。。大哥可以具体教我一下吗。。。我看了一下BaseDelegateMultiAdapter和MultipleItemQuickAdapter都有的

在`Provider`中重写`onCreateViewHolder `方法，就能返回自己的VH了

**Comment by limuyang2** [comment]
`BaseProviderMultiAdapter `里想要全部一次性定义的话，重写`onCreateDefViewHolder`方法。

**Comment by limuyang2** [comment]
不过不太建议`BaseProviderMultiAdapter`里重写定义

**Comment by huanghaoming** [comment]
好的。那我知道了。。谢谢

**Comment by limuyang2** [comment]
beta 2已经发布

**Comment by huanghaoming** [comment]
nice。。已用上
