### ISSUE TITLE
树形结构能否隐藏中间级，直接打开下级结构

### ISSUE THREAD

**Issue by bonjourss** [CymChad/BaseRecyclerViewAdapterHelper#2994]
情景：这边有个四级的结构，，第一级是必须展示的，第二个可以选择展示，如果第二级不展示的话，不展示的第二级子集展开，然后不影响所有第四级打开

**Comment by bonjourss** [comment]
我看每次collapse，expand都把整个结构刷新了一次，，我们能否之刷新当前的item

**Comment by limuyang2** [comment]
请问你用的版本是多少？

**Comment by bonjourss** [comment]
> 请问你用的版本是多少？

2.9.46

**Comment by limuyang2** [comment]
BaseNodeAdapter 应该可以满足你的情况

**Comment by bonjourss** [comment]
这个版本好像没有这个adapter  是不是需要升级，，我们项目还没有用到Androidx那需要升级到哪个版本

**Comment by limuyang2** [comment]
如果不是`Androidx`，那只能用2.9的版本了。从数据层级逻辑上来说，节点是一个跟一个的，如果第二级节点不存在，那么第三级节点就不存在。
如果第二级不存在，要展示第三级节点，那第三级节点就应该上移，属于第二级节点。

所以说你的这种数据结构是不严谨的
