### ISSUE TITLE
3.0 beta2，添加一个头部和一个底部的时候，2个都添加到头部去了

### ISSUE THREAD

**Issue by CordyHo** [CymChad/BaseRecyclerViewAdapterHelper#2997]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by limuyang2** [comment]
经过检测源码，和demo测试，并未出现问题。请给出你的测试样例

**Comment by CordyHo** [comment]
> 经过检测源码，和demo测试，并未出现问题。请给出你的测试样例

Adapter里实例化
 init {
        headerWithEmptyEnable = true
        footerWithEmptyEnable = true
    }

**Comment by ixingzhi** [comment]
3.0.0-beta2打包混淆，可以成功吗？

**Comment by limuyang2** [comment]
> 3.0.0-beta2打包混淆，可以成功吗？

demo打包混淆没有问题

**Comment by limuyang2** [comment]
> > 经过检测源码，和demo测试，并未出现问题。请给出你的测试样例
> 
> Adapter里实例化
> init {
> headerWithEmptyEnable = true
> footerWithEmptyEnable = true
> }
> 之后设置
> mRv.adapter = adapter
> adapter.setHeaderView(context.layoutInflater.inflate(R.layout.layout_quoted_price_header, null))
> adapter.setFooterView(context.layoutInflater.inflate(R.layout.layout_quoted_price_footer, null))
> 就这样，出现两个头部了
> ..
> adapter.setNewData(data)

那是因为你中间没有数据，header和footer连在了一起，仿佛是两个头部。
header 和 footer 都是item

**Comment by CordyHo** [comment]
> > > 经过检测源码，和demo测试，并未出现问题。请给出你的测试样例
> > 
> > 
> > Adapter里实例化
> > init {
> > headerWithEmptyEnable = true
> > footerWithEmptyEnable = true
> > }
> > 之后设置
> > mRv.adapter = adapter
> > adapter.setHeaderView(context.layoutInflater.inflate(R.layout.layout_quoted_price_header, null))
> > adapter.setFooterView(context.layoutInflater.inflate(R.layout.layout_quoted_price_footer, null))
> > 就这样，出现两个头部了
> > ..
> > adapter.setNewData(data)
> 
> 那是因为你中间没有数据，header和footer连在了一起，仿佛是两个头部。
> header 和 footer 都是item

有数据啊，最后 adapter.setNewData(data)了，RV的layoutManager是GridLayoutManager(context, 2)

**Comment by CordyHo** [comment]
用回2.9.50是正常的，其他代码不变，除了Adapter里实例化用回下面的
init {
        setHeaderFooterEmpty(true,true)
    }

**Comment by limuyang2** [comment]
可否给一个完整demo，供我测试

**Comment by CordyHo** [comment]
> 可否给一个完整demo，供我测试

https://pan.baidu.com/s/1tBUr0nYCAGNAdLk1sf93Dg

**Comment by ixingzhi** [comment]
> > 3.0.0-beta2打包混淆，可以成功吗？
> 
> demo打包混淆没有问题

经过测试，我看了下作者Demo中，只有HomeAdapter用了Kotlin代码（没有引用BaseQuickAdapter中的context）；现在初步判断，原因是：Kotlin写的Adapter中，只要引用BaseQuickAdapter中的context，打包就会有问题。

**Comment by limuyang2** [comment]
> > > 3.0.0-beta2打包混淆，可以成功吗？
> > 
> > 
> > demo打包混淆没有问题
> 
> 经过测试，我看了下作者Demo中，只有HomeAdapter用了Kotlin代码（没有引用BaseQuickAdapter中的context）；现在初步判断，原因是：Kotlin写的Adapter中，只要引用BaseQuickAdapter中的context，打包就会有问题。

如有疑问，请新开issue，请勿在别人的issue下讨论不相关问题。互相尊重

**Comment by limuyang2** [comment]
请更新 3.0 beta3
