### ISSUE TITLE
3.0 BETA2 viewpager+fragment 一个显示没有更多,所有的fragment都显示没有更多

### ISSUE THREAD

**Issue by walle9** [CymChad/BaseRecyclerViewAdapterHelper#2998]
如题

**Comment by limuyang2** [comment]
你是所有fragment都用的一个adapter？

**Comment by walle9** [comment]
> 你是所有fragment都用的一个适配器？

肯定不是了

**Comment by limuyang2** [comment]
给一个你的demo

**Comment by hotnewJ** [comment]
同样遇到这个问题，请问这个问题解决了吗？？每个fragment都是不同adapter，一个fragment下的loadMoreStatus会影响到其他fragment的loadMoreStatus状态
