### ISSUE TITLE
setloadingview效果有问题

### ISSUE THREAD

**Issue by matchparent** [CymChad/BaseRecyclerViewAdapterHelper#300]
默认的还好，但是如果自定义了一个会靠左显示，但通常需要居中显示，哪怕把默认的那个XML找出来一样贴上去也不能居中。另外高度被写死无法更改，希望添加入口。

**Comment by CymChad** [comment]
看下你的设置代码。

**Comment by matchparent** [comment]
adapter.setLoadingView(View.inflate(getActivity(), R.layout.header_main, null));

xml内容和layout.def_loading一样

**Comment by CymChad** [comment]
getLayoutInflater().inflate(R.layout.custom_loading, (ViewGroup) mRecyclerView.getParent(), false); 你这样加载一下。

**Comment by matchparent** [comment]
行了可以了，大神你好棒
