### ISSUE TITLE
分组布局下面的子布局是流式布局，该怎么实现？

### ISSUE THREAD

**Issue by guozhiqiang123** [CymChad/BaseRecyclerViewAdapterHelper#3000]
如图片上的这种布局
![QQ截图20191225164232](https://user-images.githubusercontent.com/20378988/71439711-a5679380-2735-11ea-98d5-bfbdddaef957.png)

**Comment by limuyang2** [comment]
垂直`LinearLayout` + `FlexboxLayout`就可以了，更简单，不用RV也可以实现

**Comment by limuyang2** [comment]
如果要使用本库实现，可以使用`BaseSectionQuickAdapter`。
配合google的[flexbox-layout](https://github.com/google/flexbox-layout)，
然后重写adapter中的`setFullSpan()`方法，
```kotlin
    override fun setFullSpan(holder: RecyclerView.ViewHolder) {
        super.setFullSpan(holder)
        val layoutParams = holder.itemView.layoutParams
        if (layoutParams is FlexboxLayoutManager.LayoutParams) {
            // 设置为铺满状态
        }
    }
```

**Comment by guozhiqiang123** [comment]
谢谢回复！我已经通过recyclervie嵌套的方式实现这种效果了

**Comment by Danniel-yan** [comment]
> 如果要使用本库实现，可以使用`BaseSectionQuickAdapter`。 配合google的[flexbox-layout](https://github.com/google/flexbox-layout)， 然后重写adapter中的`setFullSpan()`方法，
> 
> ```kotlin
>     override fun setFullSpan(holder: RecyclerView.ViewHolder) {
>         super.setFullSpan(holder)
>         val layoutParams = holder.itemView.layoutParams
>         if (layoutParams is FlexboxLayoutManager.LayoutParams) {
>             // 设置为铺满状态
>         }
>     }
> ```

FlexboxLayoutManager adapter实现DraggableModule 怎么解 谢谢 ♥️
