### ISSUE TITLE
3.0.0-beta2 混淆打包出错，can't find referenced method 'void setContext(android.content.Context)

### ISSUE THREAD

**Issue by ixingzhi** [CymChad/BaseRecyclerViewAdapterHelper#3002]
经过测试，我看了作者的Demo，只有HomeAdapter用了Kotlin代码（没有引用BaseQuickAdapter中的context）；现在初步判断，原因是：Kotlin写的Adapter中，只要引用BaseQuickAdapter中的context，打包就会出现此问题。

**Comment by limuyang2** [comment]
```java
override fun convert(helper: BaseViewHolder, item: HomeEntity?) {
    Toast.makeText(context,"",Toast.LENGTH_SHORT).show()
}
```
`Adapter`中使用`context`
经过打包测试没有问题，请检查你项目的其他配置。

我也新建了一个测试项目，倒入了库，使用contenxt，然后打包、安装、反编译，都没问题。

**Comment by limuyang2** [comment]
根据源代码，`context`的定义如下：
```java
protected lateinit var context: Context
    private set
```
赋值为私有，对外暴露的只有`getContext()`。

根据我反编译查看，`BaseQuickAdapter`类中根本不存在`setContext()`方法，只存在`getContext()`。
由于赋值为私有，所以编译器就没必要生成`setContext()`方法，`Adapter`内部对`context`赋值是直接进行的等号赋值：`this.context = con`。
由此可见，混淆后的编译生成的代码是符合源码定义逻辑的。

如果还有疑问，请新建项目再进行测试。

**Comment by ixingzhi** [comment]
新建项目测试没问题；我现在项目中的问题是这样：比如有100个Adapter，混淆打包会有15个Adapter报警告can't find referenced method 'void setContext(android.content.Context)，打包不成功；目前解决的办法是，报错的Adapter中context的引用换成 helper.itemView.context，混淆打包就不会报警告，会打包成功。

问题也有点奇怪，后续我持续跟进找原因。
问下作者，3.0正式版本大概什么时候能发布？

**Comment by limuyang2** [comment]
3.0还有些bug需要修复，会尽快发布正式版的
