### ISSUE TITLE
求助setAdapter编译无法通过。

### ISSUE THREAD

**Issue by fxsankdang** [CymChad/BaseRecyclerViewAdapterHelper#3003]
不知道为什么 RecyclerView调用setAdapter报错。显示cannt applied。第一步就卡住了，也不知道哪里有问题。实在难受，小弟不才，求助各位大佬。
Adapter就是这种写法
public class DemoAdapter extends BaseQuickAdapter<String, BaseViewHolder> {

    /**
     * 构造方法，此示例中，在实例化Adapter时就传入了一个List。
     * 如果后期设置数据，不需要传入初始List，直接调用 super(layoutResId); 即可
     */
    public DemoAdapter(list List<String>) {
        super(R.layout.layout_demo, list);
    }

    /**
     * 在此方法中设置item数据
     */
    @Override
    protected void convert(@NotNull BaseViewHolder helper, @Nullable String item) {
        helper.setText(R.id.tweetName, "This is an Item, pos: " + (helper.getAdapterPosition() - getHeaderLayoutCount()));
    }
}

**Comment by limuyang2** [comment]
版本号是多少呢？

**Comment by zhangshaobo87** [comment]
你构造函数里边是不是写反了 
应该是这样的
public DemoAdapter(List<String> list ) {
    super(R.layout.layout_demo, list);
}

**Comment by limuyang2** [comment]
你使用代码发出来看一看呢
