### ISSUE TITLE
demo中的BaseNodeAdapter折叠展开问题

### ISSUE THREAD

**Issue by jiwushi66** [CymChad/BaseRecyclerViewAdapterHelper#3004]
版本:3.0.0-beta3

demo中BaseNodeAdapter的First Node 7 展开后再次点击无法折叠
点击其他First Node也无法折叠First Node 7
demo里调用的方法是expandAndCollapseOther(position)
![device-2019-12-26-125644](https://user-images.githubusercontent.com/58125980/71458771-56763880-27df-11ea-8de4-e46167e16130.png)

**Comment by jiwushi66** [comment]
我希望默认展开第一项, 在FirstProvider里面设置了
entity.setExpanded(helper.getAdapterPosition() == 0);
运行后第一项并有展开, 点击也无法展开
此时点击其他FirstNode, 展开的数据会乱掉.
不知是否我使用的方式有误?

**Comment by limuyang2** [comment]
已经修复，请尝试 3.0 beta4

**Comment by limuyang2** [comment]
> 我希望默认展开第一项, 在FirstProvider里面设置了
> entity.setExpanded(helper.getAdapterPosition() == 0);
> 运行后第一项并没有展开, 点击也无法展开
> 此时点击其他FirstNode, 展开的数据会乱掉.
> 不知是否我使用的方式有误?

demo我已经更新，你可以下载新的demo查看
