### ISSUE TITLE
关于loadMoreView 默认使用全局静态变量的问题

### ISSUE THREAD

**Issue by nic562** [CymChad/BaseRecyclerViewAdapterHelper#3009]
版本： 3.0.0-beta4
问题：全局静态的 loadMoreView 包含的 loadMoreStatus， isLoadEndMoreGone 在全局中共享状态，造成不重启App的话，是无法复位状态，则RecyclerView不能触发加载更多。如果一个App中有多个不同的RecyclerView 使用BaseQuickAdapter，但所有BaseQuickAdapter 都共用这个静态 loadMoreView . 则共享使用了 loadMore 的状态了。这应该是有问题的。

1. 为何需要这样一个静态变量？
2. 如果这是必须的，因为 loadMoreStatus， isLoadEndMoreGone 均为 internal set 变量，那么在不自定义loadMoreView的情况下，我该如何重置其状态？

无法通过 isEnableLoadMore 重置其状态
`adapter.loadMoreModule.isEnableLoadMore = true`

无法通过直接该其属性
`adapter.loadMoreModule!!.loadMoreView.isLoadEndMoreGone = false`

有疑问的地方在 BaseLoadMoreModule 中第43行
>/** 设置加载更多布局 */
    var loadMoreView = LoadMoreModuleConfig.defLoadMoreView

和第22行

> object LoadMoreModuleConfig {
    /**
     * 设置全局的LodeMoreView
     */
    @JvmStatic
    var defLoadMoreView: BaseLoadMoreView = SimpleLoadMoreView()
}

**Comment by limuyang2** [comment]
由于此bug带来的问题表示抱歉，我会尽快修复
