### ISSUE TITLE
emptyview  怎么样才能居中？

### ISSUE THREAD

**Issue by Ccixyj** [CymChad/BaseRecyclerViewAdapterHelper#301]
我在设置了emptyview 后发现emptyview在recycle的 顶部，无法居中，该怎么设置呢？
```java
        EmptyLayout emptyLayout = EmptyLayout.getEmptyLayout(EmptyLayout.NODATA);
        emptyLayout.setOnLayoutClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mBasePresenter.loadData4Page(1);
            }
        });
        plantAdapter.setEmptyView(true,true,emptyLayout);//空view;
```
![image](https://cloud.githubusercontent.com/assets/6183506/18302155/adaef25a-7508-11e6-8e6c-1bc611cd2f56.png)

 我想让emptyview 居中， 需要设置什么？

**Comment by CymChad** [comment]
getLayoutInflater().inflate(R.layout. emptyview, (ViewGroup) mRecyclerView.getParent(), false); 试试

**Comment by Ccixyj** [comment]
可是这个view是一个自定义的view，怎么设置呢？

**Comment by CymChad** [comment]
那你用代码设置一下宽高，或者在外面套一层。
