### ISSUE TITLE
addChildClickViewIds()添加子View点击事件，列表中第一个Item中的子View点击事件无效。

### ISSUE THREAD

**Issue by ixingzhi** [CymChad/BaseRecyclerViewAdapterHelper#3011]

**Comment by limuyang2** [comment]
你的代码使用方式是什么样子的呢？

**Comment by ixingzhi** [comment]
写了一个Demo测试了下：

Adapter中的代码：
addChildClickViewIds(R.id.mBtnClick)

Activity中的代码：
mAdMain.setOnItemChildClickListener { _, view, _ ->
       if (view.id == R.id.mBtnClick) {
           Toast.makeText(this@MainActivity, "test", Toast.LENGTH_LONG).show()
       }
}

**Comment by limuyang2** [comment]
我测试了是有效的，没发现问题。你发一个你的demo过来呢

**Comment by zhouzhiguang** [comment]
我也碰到了这么解决的

**Comment by limuyang2** [comment]
> 我也碰到了这么解决的

可否给一个你们的demo呢，我这么没有复现出来

**Comment by zhouzhiguang** [comment]
我也遇到了是代码设置的问题一定要在构造函数里面设置不要在convert 里面设置

**Comment by limuyang2** [comment]
> 我也遇到了是代码设置的问题一定要在构造函数里面设置不要在convert 里面设置

是的呢，3.0版本做出了修改，不再在convert 里面设置了，因为`convert`会不断的设置数据，在里面重复设置点击事件不太合适，现在只需要在外部一次设置就行了。`convert`就只做设置数据的操作

**Comment by ixingzhi** [comment]
OK，再适配下代码，3.0确实改动挺大的。

**Comment by KisCode** [comment]
如果在XXXAdapter.convert方法addChildClickViewIds 设置会造成第一个item内指定childView点击无效，需要在外部具体Activity/Fragment初始化adapter后 通过adapter.addChildClickViewIds 方法设置childView点击事件 问题可以解决；

但是从代码上来看adapter.addChildClickViewIds 方法在Activity/Fragment调用总感觉怪怪的，layout_item.xml中所有的view的相关处理应在adapter内部统一处理，外部Activity/Fragment应该只管setAdapter

**Comment by bigc2001** [comment]
我也碰到这个问题，原因也是把addChildClickViewIds写在convert里面了，把它拿出来写在外面就可以了。

**Comment by AngelBo** [comment]
我也碰到了哦  要放到外面 这个建议修改一下
