### ISSUE TITLE
setOnLoadMoreListener 一直显示加载中

### ISSUE THREAD

**Issue by gh2571527745** [CymChad/BaseRecyclerViewAdapterHelper#3018]
如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2.9.50
2. 复现操作描述
在调用loadmorelistener的时候，拉上加载已经显示了正在加载中...，但是并没有触发Loadmore操作
3. gif复现效果

4,关键代码
`pageLists.let {
                    mKnowledgeListAdapter.run {
                        if (isRefresh) {
                            isRefresh = false
                            replaceData(pageLists)
                        } else {
                            addData(pageLists)
                        }
                        if (data.size == bean.data?.dataCount) {
                            loadMoreEnd()
                        } else {
                            loadMoreComplete()
                        }
                    }
                }

  mKnowledgeListAdapter.run {
            closeLoadAnimation()
            setOnLoadMoreListener(object : BaseQuickAdapter.RequestLoadMoreListener {
                override fun onLoadMoreRequested() {
                    loadMore()
                }
            }, rv_fragment_knowledge_child)
        }
![QQ视频20200102184658](https://user-images.githubusercontent.com/20102767/71663659-096f0500-2d91-11ea-9be4-40c268e3741a.gif)
`

**Comment by limuyang2** [comment]
先参考 2.x 的 demo

**Comment by zabio** [comment]
无限调用onloadmoreListener ，手写逻辑控制调用，但是一直无法手动结束complete
