### ISSUE TITLE
加载更多的一点疑问

### ISSUE THREAD

**Issue by EoniJJ** [CymChad/BaseRecyclerViewAdapterHelper#302]
加载更多不能实现往上拉取多少范围就触发加载更多吗
现在的逻辑好像是只要触底了就会触发加载更多？

**Comment by CymChad** [comment]
恩 是的。

**Comment by EoniJJ** [comment]
能否实现上拉一定范围再触发加载更多？

**Comment by CymChad** [comment]
目前无法实现。目前的原理是判断是否拉到底部最后一个item才出发加载更多的回调的。
