### ISSUE TITLE
BaseViewHolder 的 setXxx 方法有的返回 BaseViewHolder 有的返回 BaseViewHolder?

### ISSUE THREAD

**Issue by yinxtno1** [CymChad/BaseRecyclerViewAdapterHelper#3021]
![image](https://user-images.githubusercontent.com/19941667/71714529-37b01b80-2e49-11ea-99f2-65a11e94fdd9.png)

既然都是返回的 this ，这样做是不是有点不太合理

版本 3.0.0-bate6

**Comment by limuyang2** [comment]
抱歉，这是一个疏忽，下个版本会修复

**Comment by yinxtno1** [comment]
不用抱歉，不是什么大问题😂

**Comment by yinxtno1** [comment]
这里面提供的方法不如 2.x 版本多，只有 11个方法，2.x 版本除标记为过时的方法外有 30个方法

**Comment by limuyang2** [comment]
> 这里面提供的方法不如 2.x 版本多，只有 11个方法，2.x 版本除标记为过时的方法外有 30个方法

主要是不想加太多的东西进去。kt的话，后面会用扩展的方式

**Comment by limuyang2** [comment]
**3.0-beta8**
