### ISSUE TITLE
BaseNode 实现问题

### ISSUE THREAD

**Issue by inshyma** [CymChad/BaseRecyclerViewAdapterHelper#3025]
class  BaseNode  的属性 childNode 可不可以传BaseNode的子类  

目前 childNode 只接受BaseNode

**Comment by limuyang2** [comment]
你的意思是用泛型么？

**Comment by inshyma** [comment]
对  因为创建对象的时候需要转成BaseNode ,convert时候再强转回来   很累

**Comment by limuyang2** [comment]
泛型会有很大的限制。
假定一个node下，有多种类型子node。
例如类`A`、`B`都是继承于`BaseNode`。
```java
List<BaseNode> child = new ArrayList();
child.add(A);
child.add(B);
```
上面这种是没问题的。


如果用泛型`T`
假如定义了`T`是`A`类型，那么就变成了下面这种
```java
// 定义数组List<T> ，由于T是A类型，所以为List<A>
List<A> child = new ArrayList();
child.add(A);
child.add(B); // 错误！！
```
`B`这个类型就无法添加进去

**Comment by limuyang2** [comment]
我换了个角度思考，或许是应该可以用泛型的，我再尝试一下。
由于这是一个新增Adapter类型，会有些问题磨合期，请见谅

**Comment by liompei** [comment]
可以支持子node状态选中吗?比如我在父nodeA下选中一个子node1,当我再选中nodeA下子node3时,可以自行对node1状态和node3状态做处理,最好同时支持跨父node处理.这种侧边栏的应用场景还挺多 @limuyang2

**Comment by limuyang2** [comment]
这里用泛型，会有较多问题
