### ISSUE TITLE
无法触发上拉加载

### ISSUE THREAD

**Issue by Eveninger** [CymChad/BaseRecyclerViewAdapterHelper#303]
只在最开始初始化的时候调用了上拉加载，之后都没有触发。

**Comment by solomon2** [comment]
我也一直无法触发上拉加载，各种尝试都不行，默认的 和自定义的，都不行。还有请问adapter.openLoadMore(PAGE_SIZE);  这个方法具体是什么意思啊

**Comment by Eveninger** [comment]
已解决，是我自己代码的问题，加载一次完成后就调用loadComplete()，导致无法再次加载。

**Comment by CymChad** [comment]
@solomon2 你可以看下demo。pageSize为每页显示的数量，超过该数量才会调用加载更多的回调。

**Comment by liuyuttkx** [comment]
请问什么时候使用loadComplete()方法?
调用loadComplete()方法之后 ,如何让Adapter恢复可以上拉加载.
是否有禁用上拉加载, 主动调用上拉加载,等API.

我出现的问题和一楼一样. 
谢谢!!!

**Comment by CymChad** [comment]
有文档https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki，有案例。
