### ISSUE TITLE
adapter是在不可访问的类或接口中定义的

### ISSUE THREAD

**Issue by onism0106** [CymChad/BaseRecyclerViewAdapterHelper#3031]
在抽象类中定义了一个adapter，子类中无法访问adapter中的任何方法

**Comment by limuyang2** [comment]
贴一下你的代码

**Comment by agonytyh** [comment]
我是把一个加载数据类封装在一个Activity里面，里面定义了一个Adapter，定义大概 如下：
public abstract class BaseLoadDataActivity<T, U> extends BaseActivity {
           protected LoadDataAdapter adapter;
             class LoadDataAdapter extends BaseQuickAdapter<U, BaseViewHolder> implements LoadMoreModule {

        public LoadDataAdapter() {
            super(getItemView());
        }

        @Override
        protected void convert(@NotNull BaseViewHolder helper, @Nullable U item) {
            convertItemView(helper, item);
        }
    }
}
然后在子类中访问adapter就会报上面的错误，现在我只能在子类中，再定义一个BaseAdapter，然后让其等于父类的adapter，才能进行操作
