### ISSUE TITLE
GridSectionMultiAvgGapItemDecoration

### ISSUE THREAD

**Issue by ls3936252** [CymChad/BaseRecyclerViewAdapterHelper#3033]
我在一个多type的      RecyclerView中这样设置间距没有效果  我使用的方式对吗
GridSectionMultiAvgGapItemDecoration gs = new GridSectionMultiAvgGapItemDecoration();
        GridSectionMultiAvgGapItemDecoration.SectionDecoration s = new GridSectionMultiAvgGapItemDecoration.SectionDecoration(30,30,30,30);
        gs.addSectionDecoration(1, s);
        gs.setLastSectionBottomMarginDp(100);
        mRecyclerView.addItemDecoration(gs);

**Comment by limuyang2** [comment]
设置分割线，确实是调用系统方法`addItemDecoration `。至于为何无效，检查一下你的`GridSectionMultiAvgGapItemDecoration`的写法。
我这里也帮不上太多的忙
