### ISSUE TITLE
setDiffNewData这个方法会导致recyclerview闪烁一下

### ISSUE THREAD

**Issue by Alexxiaopang** [CymChad/BaseRecyclerViewAdapterHelper#3034]
如题，当使用这个方法时候，就算数据没有更新，但是列表还是会闪烁一下！
还有就是，多布局没有那个RVde 继承，必须修改数据bean返回type，但是使用的是第三方的bean

**Comment by limuyang2** [comment]
我使用demo测试，再次设置同样的数据，并不会闪烁

**Comment by limuyang2** [comment]
多布局有三个版本，其中有两个版本不需要继承。`BaseProviderMultiAdapter`是可以随意使用自己的bean的，不需要继承。可以查看文档

**Comment by Alexxiaopang** [comment]
我用的是分类布局，因为每个typeItem的背景和主背景都有差异，刷新的时候就会有闪烁
我在另外demo不是多布局也没有闪烁




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mumu"<notifications@github.com&gt;; 
发送时间: 2020年1月13日(星期一) 下午2:01
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;; 
抄送: "仰望半夜的月"<610611029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] setDiffNewData这个方法会导致recyclerview闪烁一下 (#3034)




我使用demo测试，再次设置同样的数据，并不会闪烁

**Comment by limuyang2** [comment]
闪烁是因为item发生了变化，数据判断为不一致导致的。检查你的itemCallback里的判断

**Comment by Alexxiaopang** [comment]
好的，我再看看，再问一个问题，如果使用BaseNode再使用diffutil，这个的callback需要怎么编写？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mumu"<notifications@github.com&gt;; 
发送时间: 2020年1月13日(星期一) 下午2:38
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;; 
抄送: "仰望半夜的月"<610611029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] setDiffNewData这个方法会导致recyclerview闪烁一下 (#3034)




闪烁是因为item发生了变化，数据判断为不一致导致的。检查你的itemCallback里的判断

**Comment by limuyang2** [comment]
> 好的，我再看看，再问一个问题，如果使用BaseNode再使用diffutil，这个的callback需要怎么编写？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mumu"<notifications@github.com&gt;; 发送时间: 2020年1月13日(星期一) 下午2:38 收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;; 抄送: "仰望半夜的月"<610611029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] setDiffNewData这个方法会导致recyclerview闪烁一下 (#3034) 闪烁是因为item发生了变化，数据判断为不一致导致的。检查你的itemCallback里的判断 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

编写方法一样的
