### ISSUE TITLE
3.0.0-beta7 设置新数据源setNewData的问题

### ISSUE THREAD

**Issue by Power-Android** [CymChad/BaseRecyclerViewAdapterHelper#3038]
/**
     * setting up a new instance to data;
     * 设置新的数据实例
     *
     * @param data
     */
    open fun setNewData(data: MutableList<T>?) {
        if (data == this.data) {
            return
        }
        this.data = data ?: arrayListOf()
        loadMoreModule?.reset()
        mLastPosition = -1
        notifyDataSetChanged()
        loadMoreModule?.checkDisableLoadMoreIfNotFullPage()
    }

如果第一次请求10条数据，加筛选条件后第二次请求剩7条数据，会直接return掉，需要手动notifyDataSetChanged()；如果不手动刷新，滑动时就会数组越界导致崩溃。

mViewModel.getList(mNodesBean.getId(), mNodesBean.getDir(), mNodesBean.getTag());
mViewModel.mLiveData.observe(this, myCloudLists -> {
            mMyCloudAdapter.setNewData(myCloudLists);
            mMyCloudAdapter.notifyDataSetChanged();
        });

**Comment by limuyang2** [comment]
`setNewData()`的注释说的很清楚了，这是设置新的数据实例，如果List的内存引用一样，就不会设置。
