### ISSUE TITLE
列表没有数据不能显示 HeaderView 

### ISSUE THREAD

**Issue by RockyQu** [CymChad/BaseRecyclerViewAdapterHelper#3039]
在没有数据的列表添加 addHeaderView ，HeaderView 显示不出来是为什么？

**Comment by limuyang2** [comment]
可否贴一下你的代码

**Comment by limuyang2** [comment]
我经过测试，功能正常，没有复现你所述的情况

**Comment by yangzhenqi** [comment]
我也遇到这个问题，是设置了空布局（setEmptyView），只显示了空布局HeaderView就不显示了，这个有什么办法解决吗

**Comment by yangzhenqi** [comment]
我也遇到这个问题，是设置了空布局（setEmptyView），当列表没有数据的时候只显示了空布局HeaderView就不显示了，这个有什么办法解决吗？ @limuyang2

**Comment by limuyang2** [comment]
> 我也遇到这个问题，是设置了空布局（setEmptyView），当列表没有数据的时候只显示了空布局HeaderView就不显示了，这个有什么办法解决吗？ @limuyang2

我测试了没有问题，请检查是否添加了`mAdapter.setHeaderWithEmptyEnable(true)`配置项

**Comment by yangzhenqi** [comment]
> > 我也遇到这个问题，是设置了空布局（setEmptyView），当列表没有数据的时候只显示了空布局HeaderView就不显示了，这个有什么办法解决吗？ @limuyang2
> 
> 我测试了没有问题，请检查是否添加了`mAdapter.setHeaderWithEmptyEnable(true)`配置项

我的可以了，谢谢你。

**Comment by RockyQu** [comment]
找到了，设置一下 setHeaderAndEmpty 为 true 就可以了
