### ISSUE TITLE
手指快速划一下页面，会停留在最后一个item那，没有继续往下显示footerView

### ISSUE THREAD

**Issue by woniu0936** [CymChad/BaseRecyclerViewAdapterHelper#304]
好比说我滑动一下屏幕，会filing到最底部自己停止，但是这里的最底部却是item的最底部，而不是之后的footerView

**Comment by woniu0936** [comment]
用的包是最新的2.1.0

**Comment by CymChad** [comment]
“没有更多”的footerView需要自己代码添加，demo都有代码。

**Comment by woniu0936** [comment]
可能你没理解我的意思，我同时加了headerView和footerView就没问题，但是不加HeaderView，只加footerView就会出现上述的问题
