### ISSUE TITLE
有没有办法 刷新数据后不滚动到顶部

### ISSUE THREAD

**Issue by ggyg123** [CymChad/BaseRecyclerViewAdapterHelper#3040]
**版本号：2.9.46**
列表添加了两个headerView,在headerView下方有个刷新数据的按钮，点击刷新按钮，数据刷新然后会滚动到列表顶部，我用了BaseMultiItemQuickAdapter和上拉加载，请问有什么办法不要滚动到列表顶部

**Comment by limuyang2** [comment]
你检查下是不是焦点的问题

**Comment by ggyg123** [comment]
我整个页面就是列表构成的，不会是焦点的问题吧

**Comment by bingdu0** [comment]
应该是焦点的问题

**Comment by Citrussss** [comment]
如果是焦点问题，把RecycleView的过度动画关闭即可解决焦点自动跑到第一个控件的问题
