### ISSUE TITLE
setEmptyView显示不正确

### ISSUE THREAD

**Issue by 1161853339** [CymChad/BaseRecyclerViewAdapterHelper#3044]
version:2.9.50
issue: 
recyclerView.setLayoutManager(new GridLayoutManager(this, 2)); 如果使用这个布局，
setEmptyView显示的时候也是按照了GridLayoutManager 来分成两列显示，导致显示只显示在第一个单元格

**Comment by kokod21** [comment]
请问你这个问题找到解决办法了吗？我现在也遇到了

**Comment by ZakAnun** [comment]
可以检查一下是否设置了 SpanSizeLookup，如果是的话需要自己判断 EmptyView 类型，然后返回相应的 spanCount @1161853339  @kokod21

**Comment by lain37** [comment]
`layoutManager.spanSizeLookup = object : GridLayoutManager.SpanSizeLookup() {
            override fun getSpanSize(position: Int): Int {
                return if (mMeetingAdapter.getItemViewType(position) == EMPTY_VIEW) {
                    2 //横向item数
                } else {
                    1
                }
            }
        }`
