### ISSUE TITLE
getItem（）获取数据 编译报错

### ISSUE THREAD

**Issue by JinLike** [CymChad/BaseRecyclerViewAdapterHelper#3047]
使用 kotlin 开发
Type mismatch: inferred type is Any? but MainModule?（自定义类名） was expected
代码 如下 ：
class MainModule : BaseData {
    var moduleName: String = ""
    var iconUrl: String = ""
    var isOpen: Boolean = false

    constructor(id: Int, moduleName: String, iconUrl: String) {
        this.moduleName = moduleName
        this.iconUrl = iconUrl
        this.id = id

    }

    constructor(moduleName: String, iconUrl: String, isOpen: Boolean) : super() {
        this.moduleName = moduleName
        this.iconUrl = iconUrl
        this.isOpen = isOpen
    }

}
class MainModuleAdapter(list: MutableList<MainModule>) :
    BaseQuickAdapter<MainModule, BaseViewHolder>(R.layout.item_main_module,list){

//    constructor(list: MutableList<MainModule?>) : this() {
//
//    }

    override fun convert(helper: BaseViewHolder, item: MainModule?) {
        helper.getView<TextView>(R.id.module_name).setText(item?.moduleName)
        //helper.getView<ImageView>(R.id.module_icon).loadImage(item?.iconUrl)
       // if (!item?.isOpen!!) ToastUtil.showErrorToast(context, "在未开放${item?.moduleName}功能")

    }

}
   var mainModules: ArrayList<MainModule> = ArrayList()
  moduleAdapter.setOnItemClickListener { adapter, view, position ->
            val module:MainModule? = adapter.getItem(position)
           when(module?.moduleName){
             

            }

        }
直接在  val module:MainModule? = mainModules.get(position)  取数据 没有问题  调用
  val module:MainModule? = adapter.getItem(position) 报 Type mismatch: inferred type is Any? but MainModule? was expected  泛型也写了

**Comment by limuyang2** [comment]
`adapter ` 是 `BaseQuickAdapter<*, *>`类型，需要强转类型
