### ISSUE TITLE
3.0 beta11    BaseItemProvider   addItemProvider() 泛型问题

### ISSUE THREAD

**Issue by zhangchi4126066** [CymChad/BaseRecyclerViewAdapterHelper#3048]
如果adapter数据泛型为Object
public class XXXProviderMultiAdapter extends BaseProviderMultiAdapter<Object>{}，
添加的ItemProvider也要写成Object
public class RecordPercentItemProvider extends BaseItemProvider<Object>,
conver()里面每次都要加上类型转换
 @Override
 public void convert(@NotNull BaseViewHolder helper, @Nullable Object data) {
        if(data instanceof RecordPercentGroupBean ){
            RecordPercentGroupBean item = (RecordPercentGroupBean) data;
            //...
        }
  }

**Comment by limuyang2** [comment]
没有看出什么问题呢，请问你想说明什么问题呢？

**Comment by scsfwgy** [comment]
借楼提个问题，从2.x切换到3.0 beta11后
开启加载更多功能，页面首次加载数据后会自动滑动到底部什么问题？之前是首次加载数据是默认在顶部的。

**Comment by qiangzengli** [comment]
我也遇到了这个问题，就是说，这个参数只允许传入BaseItemProvider<T> 这个类型，如果传入一个BaseItemProvider<T>的子类 会提示类型不匹配，这个参数可以通过类型上限来限制吗，我是菜鸡，表达有误请谅解

**Comment by wangbinbin0516** [comment]
我也遇到了 同样的问题  请问怎么解决的？
