### ISSUE TITLE
展开子项过多时，列表会滚动

### ISSUE THREAD

**Issue by 18702953620** [CymChad/BaseRecyclerViewAdapterHelper#3049]
展开子项过多时，列表会滚动到展开项的第一个，期望的效果是列表不滚动，在该项下面展开子项
使用的是`expand(position)`
gif如下
https://github.com/18702953620/ViewPager2Demo/blob/master/png/20200121_114425.gif

**Comment by 354420603** [comment]
我已出现了这个问题，item过多的时候，在添加数据，会自动滑动到第一个item从新开始滑动

**Comment by limuyang2** [comment]
是哪一个版本？
