### ISSUE TITLE
求助，无法进入onLoadMoreRequested方法

### ISSUE THREAD

**Issue by solomon2** [CymChad/BaseRecyclerViewAdapterHelper#305]
各种尝试都无法上拉刷新，默认OnLoadMore和自定义setLoadingView都不行。
        adapter.openLoadMore(dataList.size()+10);
        adapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                Logger.e("onLoadMoreRequested============");
                // 一定要在mRecyclerView.post里面更新数据。
                recycler_view.post(new Runnable() {
                    @Override
                    public void run() {
                        Logger.e("onLoadMoreRequested");
                    }
                });
            }
        });
        recycler_view.setAdapter(adapter);

还请问 adapter.openLoadMore(size);  这个方法传参含义

**Comment by solomon2** [comment]
自定义setLoadingView 也用的 demo里面的方法
customLoading = inflater.inflate(R.layout.custom_loading, (ViewGroup) recycler_view.getParent(), false);
adapter.setLoadingView(customLoading);

**Comment by CymChad** [comment]
openLoadMore（size）为pageSize 每页的大小，这个数字觉得了，当数据量到达多少的时候才调用onLoadMoreRequested

**Comment by CymChad** [comment]
具体你可以看看demo

**Comment by solomon2** [comment]
1
