### ISSUE TITLE
3.0版本 helper.setNestView

### ISSUE THREAD

**Issue by protectedMan** [CymChad/BaseRecyclerViewAdapterHelper#3054]
升级到3.0版本 helper.setNestView 没有了，如何替代。

**Comment by JingweiWang** [comment]
来看这个文档：
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/readme/1-BaseQuickAdapter.md#item-%E5%86%85%E5%AD%90view%E7%9A%84%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6

**Comment by protectedMan** [comment]
3.0的brvah的文档没有说这一块， 
我看helper.setNestView方法在2.x版本的实现是：
`/**
     * set nestview id
     *
     * @param viewIds add the child views id   can support childview click
     * @return
     */
    public BaseViewHolder setNestView(@IdRes int ... viewIds) {
        for (int viewId : viewIds) {
            nestViews.add(viewId);
        }
        addOnClickListener(viewIds);
        addOnLongClickListener(viewIds);
        return this;
    }`
本质上是添加给view两个点击事件。
