### ISSUE TITLE
原来是三级树形结构，改为四级树形结构之后，点击新增的那一级折叠会报错

### ISSUE THREAD

**Issue by ydldtec** [CymChad/BaseRecyclerViewAdapterHelper#3058]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 15(offset:7).state:35 androidx.recyclerview.widget.RecyclerView{1e29c45 VFED..... .F....ID 0,0-1080,1425 #7f09026a app:id/list_rv}

**Comment by limuyang2** [comment]
贴一下你的代码

**Comment by ydldtec** [comment]
@Override
    public void onClick(BaseViewHolder helper, View view, BaseNode data, int position) {
        getAdapter().notifyDataSetChanged();
        super.onClick(helper, view, data, position);
        getAdapter().expandOrCollapse(position, true, true, 110);
    }根据该异常已经异常出现位置，在这个位置添加了getAdapter().notifyDataSetChanged();就解决了。
