### ISSUE TITLE
Unresolved reference: databinding

### ISSUE THREAD

**Issue by qzqs** [CymChad/BaseRecyclerViewAdapterHelper#3059]
总是生成不了databinding，按照网上的改了也不行，不知道怎么去解决了？
import androidx.databinding.DataBindingUtil
import androidx.databinding.ViewDataBinding
一直找不到这两个类

**Comment by limuyang2** [comment]
`gradle`中配置：
```dataBinding {
        enabled = true
    }
```

**Comment by qzqs** [comment]
我是下载demo运行的，里面已经加上了配置了。主要是总是生成不了。
