### ISSUE TITLE
很奇怪，参照事例代码写的，报错。

### ISSUE THREAD

**Issue by MaskEgo** [CymChad/BaseRecyclerViewAdapterHelper#306]
![image](https://cloud.githubusercontent.com/assets/17177471/18321732/e4537002-7561-11e6-9833-033f6db8da6d.png)

**Comment by MaskEgo** [comment]
代码在这：
![image](https://cloud.githubusercontent.com/assets/17177471/18321769/088d0d66-7562-11e6-8ced-b6a8730974ae.png)

**Comment by CymChad** [comment]
贴出详细代码。以及报错触发流程。
