### ISSUE TITLE
setGone api变更

### ISSUE THREAD

**Issue by Reginer** [CymChad/BaseRecyclerViewAdapterHelper#3062]
![2JL3P{ZRNCB5U`(NFVUHEW5](https://user-images.githubusercontent.com/12568257/75420093-31827b00-5972-11ea-8a6d-4af1a331dfcb.png)

![{YY~7K9AUS T$)4}D`)(~2](https://user-images.githubusercontent.com/12568257/75420098-33e4d500-5972-11ea-9b60-b61c6e101de1.png)

kt版本的是3.x，java是2.x。

3.x的版本就以这个为准了么

**Comment by limuyang2** [comment]
是的，2.x的在使用上是具有歧义的，表达不准确
