### ISSUE TITLE
BaseNodeAdapter java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by shangjin-Li** [CymChad/BaseRecyclerViewAdapterHelper#3064]
![2020-03-03_122652](https://user-images.githubusercontent.com/15276396/75742996-729bd600-5d4a-11ea-8f1b-e84de69f313e.png)
如图，没有脚布局会导致数组越界。同时建议出BaseNodeAdapter子节点集合删除，单个遍历删除会触发java.util.ConcurrentModificationException问题

**Comment by shangjin-Li** [comment]
3.01版本

**Comment by HiDuke** [comment]
3.01版本 node动态增删节点会出现数组越界

**Comment by HiDuke** [comment]
public class NodeTreeAdapter extends BaseNodeAdapter {

    public NodeTreeAdapter() {
        super();
        addNodeProvider(new FirstProvider());
        addNodeProvider(new SecondProvider());
    }

    @Override
    protected int getItemType(@NotNull List<? extends BaseNode> data, int position) {
        BaseNode node = data.get(position);
        if (node instanceof FirstNode) {
            return 1;
        } else if (node instanceof SecondNode) {
            return 2;
        }
        return -1;
    }

    public static final int EXPAND_COLLAPSE_PAYLOAD = 110;
}


public class FirstProvider extends BaseNodeProvider {

    @Override
    public int getItemViewType() {
        return 1;
    }

    @Override
    public int getLayoutId() {
        return R.layout.item_node_first;
    }

    @Override
    public void convert(@NotNull BaseViewHolder helper, @NotNull BaseNode data) {
        FirstNode entity = (FirstNode) data;
        helper.setText(R.id.title, entity.getTitle());
    }

    @Override
    public void convert(@NotNull BaseViewHolder helper, @NotNull BaseNode data, @NotNull List<?> payloads) {
        for (Object payload : payloads) {
            if (payload instanceof Integer && (int) payload == NodeTreeAdapter.EXPAND_COLLAPSE_PAYLOAD) {
            }
        }
    }

    @Override
    public void onClick(@NotNull BaseViewHolder helper, @NotNull View view, BaseNode data, int position) {
        getAdapter().nodeAddData(data,new SecondNode("p:"+position));
        getAdapter().notifyDataSetChanged();
    }
}

public class SecondProvider extends BaseNodeProvider {

    @Override
    public int getItemViewType() {
        return 2;
    }

    @Override
    public int getLayoutId() {
        return R.layout.item_node_second;
    }

    @Override
    public void convert(@NotNull BaseViewHolder helper, @NotNull BaseNode data) {
        SecondNode entity = (SecondNode) data;
        helper.setText(R.id.title, entity.getTitle());
    }

    @Override
    public void onClick(@NotNull BaseViewHolder helper, @NotNull View view, BaseNode data, int position) {
        getAdapter().getData().remove(position);
        getAdapter().notifyItemRemoved(position);
    }
}

**Comment by MrShenPH** [comment]
在父节点中添加脚布局，删除父节点时脚布局没有被删除掉

**Comment by TxcA** [comment]
+1，目前自己判断位置刷新。

**Comment by Hiboboo** [comment]
同样没理解这段代码的逻辑，不知道为什么`removeCount += 1`？
```java
/**
     * 从数组中移除
     * @param position Int
     * @return Int 被移除的数量
     */
    private fun removeNodesAt(position: Int): Int {
        if (position >= data.size) {
            return 0
        }
        // 记录被移除的item数量
        var removeCount = 0

        // 先移除子项
        removeCount = removeChildAt(position)

        // 移除node自己
        this.data.removeAt(position)
        removeCount += 1 // 这里既然把所有Child和Node自己都移除完了，那为什么还要+=1呢？

        val node = this.data[position] // 因为+=1，这里下标越界了
        // 移除脚部
        if (node is NodeFooterImp && node.footerNode != null) {
            this.data.removeAt(position)
            removeCount += 1
        }
        return removeCount
    }
```

**Comment by ZakAnun** [comment]
> ![2020-03-03_122652](https://user-images.githubusercontent.com/15276396/75742996-729bd600-5d4a-11ea-8f1b-e84de69f313e.png)
> 如图，没有脚布局会导致数组越界。同时建议出BaseNodeAdapter子节点集合删除，单个遍历删除会触发java.util.ConcurrentModificationException问题

遍历的过程中，不应更新数据，不然会出现 java.util.ConcurrentModificationException
