### ISSUE TITLE
3.0.1版本 expandAndCollapseOther这个方法会报错

### ISSUE THREAD

**Issue by fansangg** [CymChad/BaseRecyclerViewAdapterHelper#3065]
**java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 16(offset:16).state:18 androidx.recyclerview.widget.RecyclerView{ec44142 VFED..... ......I. 0,0-1080,1520 #7f0904c5 app:id/recyclerView}**

**测试的过程中发现不仅expandAndCollapseOther 报错，expandOrCollapse 这个方法也会报下面的错误
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{f35b1f8 position=6 id=-1, oldPos=12, pLpos:12 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{23c5ac1 VFED..... ......I. 0,0-1080,1520 #7f0904c5 app:id/recyclerView}**

**但是demo里我反复试了都没有复现，麻烦帮忙看看是什么原因导致的**

代码

```
class PickSecondProvider(override val itemViewType: Int = 2, override val layoutId: Int = R.layout.item_exercise_choose_sencond) : BaseNodeProvider() {

    override fun convert(helper: BaseViewHolder, data: BaseNode) {
        val dataBean = (data as ExerciseNodeBean)

        helper.setText(R.id.title, dataBean.title)


        helper.setGone(R.id.dot, !dataBean.childNode.isNullOrEmpty())
        helper.setGone(R.id.expend, dataBean.childNode.isNullOrEmpty())

        helper.setImageResource(R.id.expend, if (!dataBean.isExpanded) R.drawable.icon_expand else R.drawable.icon_collapse)


    }

    override fun onClick(helper: BaseViewHolder, view: View, data: BaseNode, position: Int) {
        val dataBean = data as ExerciseNodeBean
        if (!dataBean.childNode.isNullOrEmpty()) {
            if (dataBean.isExpanded) {
                getAdapter()?.collapse(position)
            } else {
                getAdapter()?.expandAndCollapseOther(position)
            }
        }
    }
}
```

```
class PickFirstProvider(override val itemViewType: Int = 1, override val layoutId: Int = R.layout.item_exercise_choose_first) : BaseNodeProvider() {

    override fun convert(helper: BaseViewHolder, data: BaseNode) {
        val dataBean = (data as ExerciseNodeBean)

        helper.setText(R.id.title, dataBean.title)

        helper.setImageResource(R.id.expend, if (dataBean.isExpanded) R.drawable.icon_collapse else R.drawable.icon_expand)

    }

    override fun onClick(helper: BaseViewHolder, view: View, data: BaseNode, position: Int) {
        getAdapter()?.expandOrCollapse(position)
    }
}
```

**adapter**

```
class ExercisePickAdapter : BaseNodeAdapter() {

    init {
        addNodeProvider(PickFirstProvider())
        addNodeProvider(PickSecondProvider())
        addNodeProvider(PickThirdProvider())
    }

    override fun getItemType(data: List<BaseNode>, position: Int): Int {
        val baseNode = data[position] as ExerciseNodeBean
        return baseNode.type
    }


}
```

**Comment by fansangg** [comment]
如果我animate传false，那就不会报错

**Comment by fansangg** [comment]
试了很多次，我发现如果我继承BaseExpandNode的类用的是data class，就会出现以上错误

想请教一下原因是什么？

**Comment by wuyingtong** [comment]
可以设置expandOrCollapseq全部吗

**Comment by FlyMantou** [comment]
果然跟data class有关，但是原理是什么。。。

**Comment by qq1148120042** [comment]
@fansangg  老哥 这个咋解决的 ...

**Comment by fansangg** [comment]
> @fansangg 老哥 这个咋解决的 ...

不是说了data class的原因吗

**Comment by qq1148120042** [comment]
@fansangg   

public class CircleFirstNode extends BaseExpandNode {

    private List<BaseNode> childNode;
    private CircleListResult.RecordsBean data;

    public CircleFirstNode(List<BaseNode> childNode, CircleListResult.RecordsBean data) {
        this.childNode = childNode;
        this.data = data;

        setExpanded(false);
    }

    public CircleListResult.RecordsBean getData() {
        return data;
    }

    @Override
    public List<BaseNode> getChildNode() {
        return childNode;
    }
}

额 不是kotlin

**Comment by Jerrychurui** [comment]
我用的java写的也出现这个问题了，怎么解决呢

**Comment by li-yu** [comment]
不止新版本，老版本也可能会遇到同样的问题，但需要指出：这不是这个库的 BUG。

### 直接原因：
BaseNodeAdapter.kt 中涉及折叠逻辑的 ` this.data.removeAll(items)` 方法导致 data 中实际删除的数量比 items 个数多，接着又只是进行的局部刷新，最终导致 data 数据源与当前实际界面是不一致的，提示 “Inconsistency detected” 错误。

### 核心原因：
在调用 Java/Kotlin 集合的 `removeAll` 方法时会调用元素的  **`equals`** 方法进行判断，如果元素相等才执行移除操作。所以我们在定义实体对象时一定要留意其 `equals` 方法是否能准确比较。而 kotlin 的 data class 是根据 **主构造** 函数里的参数自动生成的 `equals` 方法，如果 data class 主构造定义不规范，就会导致在 `removeAll` 时会多删除”其他节点“的元素。  
举个例子，一个 ”错误的“ data class 实体类：  
```kotlin
data class User(var name: String) {
    // 用户 ID
    var id: String? = null
    // 分组的名字
    var group: String? = null
}
// 反编译看下，这里自动生成的 equals 只会对 name 进行比较
public boolean equals(@Nullable Object var1) {
      if (this != var1) {
         if (var1 instanceof User) {
            User var2 = (User)var1;
            if (Intrinsics.areEqual(this.name, var2.name)) {
               return true;
            }
         }

         return false;
      } else {
         return true;
      }
   }
```
所以当多个展开的分组都存在一个仅名字相同的 `User(”张三“)` 时，折叠其中一个分组时，就会导致其他分组的 ”张三“ 也会被临时删掉，导致报错。  
楼上说的去掉 data class 就能解决问题，那是因为 kotlin 默认的 class 的 `equals` 方法比较的是对象的引用地址，当然没问题了。
```java
public boolean equals(Object obj) {
    return (this == obj);
}
```
### 解决方法：
- 按需求重新定义实体类 data class 的主构造函数，例如:
  ```kotlin
  data class User(var name: String, var id: String, var group: String)
  ```
- 重写实体类 `equals` 方法。

**Comment by zengx1998** [comment]
大佬 我还是遇到这个问题啦 我重写了equals
