### ISSUE TITLE
使用BaseQuickAdapter,第一次滑动有卡顿,第二次上拉加载完数据后再次滑动不会卡顿了

### ISSUE THREAD

**Issue by ggyg123** [CymChad/BaseRecyclerViewAdapterHelper#3075]
使用BaseQuickAdapter,第一次滑动有卡顿,第二次上拉加载完数据后再次滑动不会卡顿,我还使用了SmartRefreshLayout库下拉刷新,能知道我遇到了什么问题么,

**Comment by CasparXL** [comment]
老哥，我估计不是这个库的问题，我也用的BaseQuickAdapter和SmartRefreshLayout库，没卡顿，你检查一下是不是xml文件里有啥没配置好。这个问题我以前貌似在哪里见过，就是想不起来了，好像是代码哪里没设置好

**Comment by ggyg123** [comment]
@CasparXL 在配置不错的机器上不会卡顿   配置低的会卡顿,但是配置低的其他应用列表没有卡顿,我现在其中的一个列表页面没有请求数据,直接加载的上个界面传的数据,第一次滑动也会卡顿 ,不得其解

**Comment by ggyg123** [comment]
待我下个库的demo 在手机上运行一行吧

**Comment by songsongtao** [comment]
> 待我下个库的demo 在手机上运行一行吧

解决了嘛

**Comment by m839336369** [comment]
我也是，我怀疑是加载的view组件太复杂的造成的加载卡顿，同一款软件，同一种加载手段，但是一些简单的布局加载的时候不会有卡顿产生，
