### ISSUE TITLE
3.0.1版本，setDiffNewData方法，无法满足直接对旧数据源修改的更新

### ISSUE THREAD

**Issue by Suguiqiang** [CymChad/BaseRecyclerViewAdapterHelper#3077]
**问题：3.0.1版本，setDiffNewData方法，无法满足直接对旧数据源修改的更新**
setDiffNewData内部对旧数据源和新数据源做了==的判断，这导致了更新数据，必须用一个新的对象。

**复现步骤**
1、定位到Demo中DiffUtilActivity类
2、修改itemChangeBtn的监听事件，如下：
```
    List<DiffUtilDemoEntity> newData=  mAdapter.getData();
    newData.get(0).setTitle("😊Item " + 0);
    mAdapter.setDiffNewData(newData);
```
3、运行代码，先点击notifyChangeBtn，再点击itemChangeBtn，无法更新数据。

**期望效果**
支持对旧数据源修改的更新。因为如果每次更新都需要对数据源进行一次深拷贝很麻烦。
希望作者考虑一下这个问题，感谢。

**Comment by limuyang2** [comment]
抱歉，为了数据安全性，不可设置相同实例。拷贝数据再修改即可，并不麻烦，示例如下：
```java
// 先拷贝出数据
List<Object> data = new ArrayList<>(adapter.getData());

// 修改数据
data.add(0, new ImageEntity());
...
...

// 使用 diif 刷新数据
adapter.setDiffNewData(data);
```
