### ISSUE TITLE
下拉刷新触发了加载更多

### ISSUE THREAD

**Issue by yihuajia** [CymChad/BaseRecyclerViewAdapterHelper#3079]
pageSize为30，刚好只有11条数据，此时满足不了以下条件，从而调用了加载更多的方法
position最后一个为11，baseQuickAdapter.itemCount 为12,preLoadNumber为1
if (position < baseQuickAdapter.itemCount - preLoadNumber) {
            return
}

**Comment by limuyang2** [comment]
检查一下你的业务代码逻辑
