### ISSUE TITLE
Status这个类去哪了?用最新的发现没有这个文件了.

### ISSUE THREAD

**Issue by lifetin** [CymChad/BaseRecyclerViewAdapterHelper#308]
没事了.我搞错了.问题关闭
另外说一下,这东西非常好.哈哈
麻烦把问题关闭吧.谢谢了!

**Comment by lifetin** [comment]
不好意思,我是新手,不太熟,没有详细的说明.网上找了也没看到.

**Comment by CymChad** [comment]
感谢使用，觉得好用的话可以推荐给其他人使用。

**Comment by lifetin** [comment]
还是希望能有个更详细点的教程.呵呵,像我们新手看是看的懂,可是理解起来有点吃力.要慢慢查源码.
