### ISSUE TITLE
3.0.1版本setNewData设置值相同但引用不同数据，也会被判断为同一数据而无法起效

### ISSUE THREAD

**Issue by qianshengta** [CymChad/BaseRecyclerViewAdapterHelper#3082]
先说我遇到的问题。现在我一个界面中有两个列表如图，一个类型列表，一个重量区间列表。两个列表的数据结构如下。重量区间列表的数据是从类型列表数据中取得，根据选择的类型获取重量区间(大部分重量区间的值是相同的)，然后通过setNewData更新重量区间列表，点击重量区间列表来选择重量区间，修改isSelect的值来做判断是否选择。
现在我这里出现的bug就是，在重量区间列表的数据值相同的情况下(都没有选择重量，或者选择的重量值都相同)，选择另外的类型，他的重量区间的数据还是没变得，对重量区间做出修改的化，修改的还是上一个类型的值，因为setNewData没有将类型对应的重量区间数据设置进去。我看了源码发现了这段代码， if (data == this.data) {return },这里用的"=="判断，那么他就只判断数据的值是否相同，如果值相同，即使他的引用是不同的，他也会被return。我在想是否应该使用"==="判断他们的引用来源来判断他们是否为同一个数据来的合适？
```
data class AppointmentCategoryType(val id: Long?, val name: String?,
                                   val children: MutableList<AppointmentCategoryWeight>?)

data class AppointmentCategoryWeight(val id: Long?, val weight: String?,var isSelect: Boolean = false)
```

![i](https://user-images.githubusercontent.com/29747624/76924171-803b8900-6910-11ea-90cf-8d283175cbcf.jpg)

**Comment by limuyang2** [comment]
谢谢你的建议，此处疏忽了，感谢指出

**Comment by scsfwgy** [comment]
同样有这个问题，因为我是统一页面定义了一个mDataList,有这个判断会有各种问题。移除这个判断是否会有问题？
![image](https://user-images.githubusercontent.com/16045179/77619001-4999ea00-6f72-11ea-9cf5-129e700ca612.png)

**Comment by scsfwgy** [comment]
@limuyang2 如果可以请尽快修复这个问题，项目要上线，谢谢。目前用的：3.0.1

**Comment by scsfwgy** [comment]
我看最新的提交是这样的，感觉和原有逻辑一样。我这里用  `setNewData(data: MutableList<T>?)`主要是为了在刷新后重置加载更多的状态，不知道是否是理解有问题。
![image](https://user-images.githubusercontent.com/16045179/77619589-7dc1da80-6f73-11ea-850e-7febf125c9b8.png)

**Comment by protectedMan** [comment]
我看问题已经修复了，但是没有发布新版本，望速迭代3.0.2

**Comment by limuyang2** [comment]
> 我看问题已经修复了，但是没有发布新版本，望速迭代3.0.2
> @limuyang2

已经发布`3.0.2` 修复了此 bug
