### ISSUE TITLE
可以不使用自带的混淆规则吗？

### ISSUE THREAD

**Issue by naturs** [CymChad/BaseRecyclerViewAdapterHelper#3084]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/library/proguard-rules.pro

这里的混淆规则保留了所有的androidx类，可以只保留BaseQuickAdapter和BaseViewHolder的规则吗？

或者我自己有办法控制不使用自带的规则吗？

**Comment by limuyang2** [comment]
请尝试`3.0.2`版本，如有问题，欢迎及时反馈

**Comment by naturs** [comment]
> 请尝试`3.0.2`版本，如有问题，欢迎及时反馈

验证已经可以混淆androidx下的包了，感谢
