### ISSUE TITLE
使用BaseMultiItemQuickAdapter，二级菜单item 的布局太长的话，底部的布局就无法全部显示

### ISSUE THREAD

**Issue by yanyonghua** [CymChad/BaseRecyclerViewAdapterHelper#3085]
我在现有问题上面去搜索，找了半天没找到。
所以就想新建一个issue ，是这样的：

有个树形结构的数据需要展示，

第一级就一行，第二级的有的很长，

有的短。短的呢能够全部显示。长的就部分不显示或者只显示一半。

经过反复的查看，我发现主要是超过手机屏幕的布局不显示了。或者显示一半，请问有什么方法能够解决吗?我用scrollview 来 ，好像scrollview的监听被拦截了

**Comment by yanyonghua** [comment]
异常情况：

![image](https://user-images.githubusercontent.com/22539945/77221945-a029b180-6b89-11ea-9b78-9b39db0fa228.png)
正常情况
![image](https://user-images.githubusercontent.com/22539945/77221953-b33c8180-6b89-11ea-90f3-061346fc3d85.png)
比对
![image](https://user-images.githubusercontent.com/22539945/77221959-bcc5e980-6b89-11ea-82c2-fd35f4ba988a.png)

**Comment by limuyang2** [comment]
可否给个demo，方便测试

**Comment by yanyonghua** [comment]
> 可否给个demo，方便测试

可以，我这边因为着急我就取了个巧。多出来的部分用分级的方式解决了。但是超过了还是看不了的。
[brvah.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/4496351/brvah.zip)

你可以看看。谢谢
