### ISSUE TITLE
关于上拉加载更多，loading不消失的问题

### ISSUE THREAD

**Issue by liuyangbajin** [CymChad/BaseRecyclerViewAdapterHelper#3086]
除了 adapter.loadMoreEnd(); 之外，上拉加载更多的loading还有其他的方式能让它隐藏吗？

比如下拉了7屏的内容，突然因为网络原因下一屏幕加载失败了，那么这个loading就一直存在了，如果使用 adapter.loadMoreEnd(); 的确能让loading消失，但是也无法继续拉取下一屏幕的内容了，因为可能网络又恢复了，希望是能够继续接着下拉的。

所以有什么方法能够使得上拉的loading隐藏？

**Comment by yingka** [comment]
mAdapter.loadMoreFail();试试？

**Comment by limuyang2** [comment]
`adapter.loadMoreFail()` 无法满足你的需求么？

**Comment by limuyang2** [comment]
长时间无人回复，先关闭此问题

**Comment by longertime** [comment]
loadmorefaile()会增加一个失败的footer，怎么在不影响下次加载更多的情况下去掉这个footer呢？

**Comment by longertime** [comment]
我还发现一个问题，当加载更多调用后，如果返回数据为空，如果不调用loadmoreend()而是调用loadmorecomplete()希望还能继续加载的话，会一直回调loadmorelistener
