### ISSUE TITLE
关于滑动删除和拖拽得问题。

### ISSUE THREAD

**Issue by HelloAnyu** [CymChad/BaseRecyclerViewAdapterHelper#3088]
您好：
       首先感谢您提供这么强大得库来让我们使用，我在使用滑动BaseItemDraggableAdapter中，遇到了一个问题。item可以往右滑动删除  但是左滑就不行，版本2.9.30。麻烦作者看到回复一下，感谢

**Comment by yangjiechina** [comment]
itemDragAndSwipeCallback.setSwipeMoveFlags(ItemTouchHelper.START);
