### ISSUE TITLE
BaseItemDraggableAdapter

### ISSUE THREAD

**Issue by wuhongsheng** [CymChad/BaseRecyclerViewAdapterHelper#3091]
请问下2.x版本中的BaseItemDraggableAdapter 在3.x中有替代方法吗

**Comment by LJW123** [comment]
注意：从2.x升级到3.x为不完全兼容升级！

加载更多、向上加载、拖拽为模块，并不集成在某一个Adapter中，根据需要集成即可。


/**
 * 需要【拖拽】功能的，[BaseQuickAdapter]继承此接口
 */
interface DraggableModule

其他功能同理
