### ISSUE TITLE
BaseSectionQuickAdapter怎么使用databinding

### ISSUE THREAD

**Issue by qq570026938** [CymChad/BaseRecyclerViewAdapterHelper#3096]
BaseSectionQuickAdapter怎么使用databinding 求解

**Comment by limuyang2** [comment]
请更新`3.0.2`，使用`BaseBinderAdapter`，具体用法参考demo

**Comment by qq570026938** [comment]
BaseBinderAdapter 在kotlin中怎么初始化

**Comment by qq570026938** [comment]
谢谢

**Comment by patelakshay13890** [comment]
I also sir have same question so please give some sample code for that will help me out sir...
