### ISSUE TITLE
BaseMultiItemQuickAdapter 怎么用databing

### ISSUE THREAD

**Issue by qq570026938** [CymChad/BaseRecyclerViewAdapterHelper#3102]
一个list集合中的实体类有一个类型来判断用不同布局，用BaseMultiItemQuickAdapter实现比较方便，但是这个BaseMultiItemQuickAdapter怎么用 databinding，其实用BaseProviderMultiAdapter这个databing也能实现，但是不推荐使用了，那么用BaseBinderAdapter怎么实现

**Comment by qq570026938** [comment]
一个list集合中的实体类有一个类型来判断用不同布局，用BaseMultiItemQuickAdapter实现比较方便，但是这个BaseMultiItemQuickAdapter怎么用 databinding

**Comment by limuyang2** [comment]
`BaseMultiItemQuickAdapter ` 中使用 `BaseDataBindingHolder`.
`BaseBinderAdapter` 中请参考demo

**Comment by Fubiven** [comment]
那 BaseDataBindingHolder 的泛型如何填写呢
