### ISSUE TITLE
fun onBindViewHolder(holder: VH, position: Int, payloads: MutableList<Any>) 重写问题

### ISSUE THREAD

**Issue by Reginer** [CymChad/BaseRecyclerViewAdapterHelper#3104]
现在版本3.0.2

fun onBindViewHolder(holder: VH, position: Int, payloads: MutableList<Any>) 
方法是不是有哪里逻辑不对？
```
notifyItemChanged(int position, @Nullable Object payload)
```
不能刷新对应的itm。

之前版本2.9.45-androidx可以刷新

**Comment by limuyang2** [comment]
给个示例代码

**Comment by Reginer** [comment]
[RV.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/4468116/RV.zip)

点那个卸载按钮，MainActivity#onItemChildClick里有小段注释

**Comment by geekxiaolong** [comment]
解决了没有

**Comment by Reginer** [comment]
没有，没用这个局部刷新了
