### ISSUE TITLE
adapter显示数据和setList设置的数据不一致

### ISSUE THREAD

**Issue by Reginer** [CymChad/BaseRecyclerViewAdapterHelper#3105]
使用版本3.0.2
setList之前打印了数据，其中一个数据为
![image](https://user-images.githubusercontent.com/12568257/78207248-b4e43e80-74d3-11ea-8d2d-f380cb6fc602.png)

![image](https://user-images.githubusercontent.com/12568257/78207212-99793380-74d3-11ea-8bfc-6fae74d2983d.png)

可是等到在adapter里的时候，在convert里打印却变了。
![image](https://user-images.githubusercontent.com/12568257/78207290-d8a78480-74d3-11ea-8a3e-b34c617d22dc.png)
变成了
![image](https://user-images.githubusercontent.com/12568257/78207316-e9f09100-74d3-11ea-8c0f-69e15c5b8a61.png)

显示成了右边fragment应该显示的内容了，按钮id一样。

**Comment by Reginer** [comment]
这个可能更直观
![image](https://user-images.githubusercontent.com/12568257/78208026-e8c06380-74d5-11ea-9d5b-c314ed0894ae.png)
![image](https://user-images.githubusercontent.com/12568257/78208152-3d63de80-74d6-11ea-94b2-63a4f5dafcb4.png)

**Comment by RubinTry** [comment]
同问，目前我用setNewInstance()临时代替了一下，希望早点能出解决方案

**Comment by Reginer** [comment]
@limuyang2  是在哪个版本上修复的 ？
