### ISSUE TITLE
List数据本来是10个，但是想显示11个，重写getDefItemCount返回data+1之后出现错误。

### ISSUE THREAD

**Issue by LoveNewSweetheart** [CymChad/BaseRecyclerViewAdapterHelper#3106]
List数据本来是10个，我的需求是显示11个。会有这样的开发需求存在。建议作者在这段代码上不要写死。
![aa](https://user-images.githubusercontent.com/18026908/78210895-2628ef00-74de-11ea-8625-97c678543b5f.png)

另外还请教一下，如果要实现添加footer，添加的是item的footer，而不是Adapter的footer怎么实现呢？

**Comment by xuyingke** [comment]
1、作者那么写似乎没啥问题。你 10 条数据，想要显示 11 个，就多加一条空数据就可以了。
2、item footer 是说二级吗 ？不是的话，你 itemView 自己加 view 就好了呀。

**Comment by limuyang2** [comment]
重写 `getDefItemCount()` 方法就行了

**Comment by zhupengxiang** [comment]
我重写这个方法 返回return super.getDefItemCount() + 1 怎么还是崩溃  别的地方还需要处理吗 @limuyang2

**Comment by zhujunhua2012** [comment]
@limuyang2 只重写`getDefItemCount()`还是不行的， 多的1个被解析成 laodMore 的view了。
应该是 `BaseQuickAdapter#getItemViewType` 这个， 在题主标注的那块， 把`val dataSize = data.size` 换成 `val dataSize = getDefItemCount()`吧？
