### ISSUE TITLE
setOnItemChildClickListener 点击第一个item 无效果

### ISSUE THREAD

**Issue by Binyy** [CymChad/BaseRecyclerViewAdapterHelper#3108]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by jw10041229** [comment]
在构造函数里addChildClickViewIds(),不要在convert()里

**Comment by limuyang2** [comment]
请看README，不要在convert方法里注册控件id

**Comment by Ccixyj** [comment]
我这里是通过convert时动态添加的某些按钮及View.generateViewId()生成的id，再addChildClickViewIds（...）后手动调用一次bindViewClickListener(holder , holder.itemViewType)就可以绑定。

**Comment by fishballzzz** [comment]
> 
> 
> 我这里是通过convert时动态添加的某些按钮及View.generateViewId()生成的id，再addChildClickViewIds（...）后手动调用一次bindViewClickListener(holder , holder.itemViewType)就可以绑定。

@Ccixyj 我看了你的留言也做了类似的代码，而且第一次点击也有反应，不过还是有点担心，请问你这样做有碰到什么问题吗？

**Comment by Ccixyj** [comment]
> > 我这里是通过convert时动态添加的某些按钮及View.generateViewId()生成的id，再addChildClickViewIds（...）后手动调用一次bindViewClickListener(holder , holder.itemViewType)就可以绑定。
> 
> @Ccixyj 我看了你的留言也做了类似的代码，而且第一次点击也有反应，不过还是有点担心，请问你这样做有碰到什么问题吗？

目前没有问题。bindViewClickListener 只是做事件绑定，就是每次convert是都会比原来多调用一次

**Comment by Binyy** [comment]
发了问题，然后在README文档找到原因了，

**Comment by a472385519** [comment]
> 发了问题，然后在README文档找到原因了，

#3252
