### ISSUE TITLE
建议去掉版本号里的'v'

### ISSUE THREAD

**Issue by basefas** [CymChad/BaseRecyclerViewAdapterHelper#311]
即把
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.1.1'
改成
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.1'

这样比较符合常规使用方法

**Comment by CymChad** [comment]
好的，多谢建议。下个版本就更改过来。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.3' 最新的版本已经去掉。
