### ISSUE TITLE
setNewData 与 replaceData

### ISSUE THREAD

**Issue by zhongzhibin617** [CymChad/BaseRecyclerViewAdapterHelper#3111]
我是用新版本kotlin的base , 其中setNewData 里面 data == this.data 在kotlin中比较的值，而不是对象地址，按照你的使用说明上
<img width="920" alt="截屏2020-04-03 上午11 22 12" src="https://user-images.githubusercontent.com/48230974/78320973-5f746400-759d-11ea-9e73-b94536e0767e.png">
我重新创建list再次setNewData并没有替换数据源
<img width="704" alt="截屏2020-04-03 上午11 19 41" src="https://user-images.githubusercontent.com/48230974/78321058-89c62180-759d-11ea-90fa-6c373700d62a.png">
所有只能用replaceData替换setNewData的效果

**Comment by limuyang2** [comment]
在`3.0.2`中已经修复过了，请用新版
