### ISSUE TITLE
BaseBinderAdapter 不能完全替代 BaseProviderMultiAdapter

### ISSUE THREAD

**Issue by liompei** [CymChad/BaseRecyclerViewAdapterHelper#3112]
1.
BaseProviderMultiAdapter 可以在相同 entity 中根据type区分。
BaseBinderAdapter 适用于不同entity的布局，类似于MultiTypeAdapter

希望可以在 BaseBinderAdapter 增加相同 entity 的 binder 区分。

2.

同一个 Binder 只能 add 一次，多次会crash，因此在会重走生命周期的 fragment 里通过创建对象时apply 或 by lazy 方式来用。不知道是不是故意这样做的。

**Comment by limuyang2** [comment]
谢谢你的反馈

**Comment by limuyang2** [comment]
3.0.3 中已经恢复
