### ISSUE TITLE
remove

### ISSUE THREAD

**Issue by yangyang9** [CymChad/BaseRecyclerViewAdapterHelper#3113]
open fun remove(@IntRange(from = 0) position: Int) {
        if (position >= data.size) {
            return
        }
        this.data.removeAt(position)
        val internalPosition = position + headerLayoutCount
        notifyItemRemoved(internalPosition)
        compatibilityDataSizeChanged(0)
        notifyItemRangeChanged(internalPosition, this.data.size - internalPosition)
    }

    open fun remove(data: T) {
        val index = this.data.indexOf(data)
        if (index == -1) {
            return
        }
        remove(index)
    }
两个remove方法，kotlin中使用编译器无法区分使用的是哪一个方法

**Comment by limuyang2** [comment]
两个`remove`参数不一样，kt中可以区分

**Comment by yyzl0418** [comment]
> 两个`remove`参数不一样，kt中可以区分

你可以试试传int型参数就会提示你不知道使用哪个方法,一个是泛型,可能是int类型,编译器无法区分

**Comment by limuyang2** [comment]
谢谢反馈

**Comment by limuyang2** [comment]
please use 3.0.3
