### ISSUE TITLE
3.x版本不能做到兼容2.x版本吗？

### ISSUE THREAD

**Issue by fantasybei** [CymChad/BaseRecyclerViewAdapterHelper#3114]
3.x版本的不少使用方式发生了改变，现在不能兼容老版本的话，升级后需要改一些东西，修改后的代码还得重新测试一遍。能不能做成兼容，3.x版本包名都改一下，2.x版本的代码也保留着。这样可以等有时间了把老代码慢慢改成用3.x版本的。

**Comment by chengzhijun0706** [comment]
同问，项目直接更改涉及的内容太多，现在项目是Java和kotlin混合，改起来更是难受，可以像RxJava一样改包名么

**Comment by limuyang2** [comment]
暂不兼容

**Comment by wystyle1** [comment]
希望作者考虑此建议，让使用2.x和3.x可以同时使用，解决兼容问题
