### ISSUE TITLE
NestedScrollView嵌套RecyclerView的问题

### ISSUE THREAD

**Issue by harryhasai** [CymChad/BaseRecyclerViewAdapterHelper#3116]
无法触发自动加载更多, 必须手动才可以
有没有什么方法可以设置?
感谢大佬

**Comment by harryhasai** [comment]
现在暂时能想到的修改方法就是把RecyclerView之上的布局全部添加到头布局里, 这样应该是可以自动触发加载更多, 
不知道各位大佬有没有其他的解决办法

**Comment by limuyang2** [comment]
NestedScrollView嵌套RecyclerView，会导致`RecyclerView`的复用机制失效，这是系统本身设计如此。所以，并不建议相同滑动方向上的NestedScrollView嵌套RecyclerView

**Comment by harryhasai** [comment]
> NestedScrollView嵌套RecyclerView，会导致`RecyclerView`的复用机制失效，这是系统本身设计如此。所以，并不建议相同滑动方向上的NestedScrollView嵌套RecyclerView

感谢大佬!!!!!!

**Comment by greadking** [comment]
建议你使用Adapter.addHeaderView 或 addFooterView， 将相关布局添加头脚上 去除NestedScrollView 应该可以解决相关问题
