### ISSUE TITLE
当使用GridLayoutManager.SpanSizeLookup和addHeaderView时出现数组越界

### ISSUE THREAD

**Issue by changpeku** [CymChad/BaseRecyclerViewAdapterHelper#3118]
如标题所述，我是直接使用的设置系统的GridLayoutManager.SpanSizeLookup，没有使用BaseQuickAdapter.setGridSpanSizeLookup这个方法
我使用的版本是3.0.2
原因我看了**BaseQuickAdapter**源码大概找到了
`override fun onAttachedToRecyclerView(recyclerView: RecyclerView){
      ···
return if (mSpanSizeLookup == null) {
                        if (isFixedViewType(type)) manager.spanCount else defSpanSizeLookup.getSpanSize(position)//这里的position是不是应该是position - headerLayoutCount
      ···
}`
原因我注释在代码里面了，不知道是程序的设计上的原因还是单纯的bug，另外我在github上是第一次提issue，如果在提问的细节上有什么不对的地方还请指正，谢谢

**Comment by limuyang2** [comment]
可否给一个你的demo

**Comment by Apeku** [comment]
> 可否给一个你的demo

怎么给demo，我是直接贴代码吗，直接贴代码的话只能贴关键代码，新手不太懂，见谅，下面是关键代码
`
recyclerView=findViewById(R.id.rv);
        initData();
final GridLayoutManager gridLayoutManager=new GridLayoutManager(this,6);
        gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return datas.get(position).getSpanZize(gridLayoutManager.getSpanCount());
            }
        });
        recyclerView.setLayoutManager(gridLayoutManager);
        recyclerView.addItemDecoration(new GridDividerItemDecoration(this,GridLayoutManager.VERTICAL));
        mQuickAdapter=new MQuickAdapter(datas);
        TextView header=new TextView(this);
        header.setText("peku的header");
        mQuickAdapter.addHeaderView(header);
        recyclerView.setAdapter(mQuickAdapter);

    }

    private void initData() {

        Random random=new Random();
        for(int i=0;i<30;i++){

            BaseSpanData data=null;
            int type=i%3+1;
            switch (type){

                case 1:
                    data=new SpanData1();
                    break;
                case 2:
                    data=new SpanData2();
                    break;
                case 3:
                    data=new SpanData3();
                    break;
                default:
                    break;
            }
            datas.add(data);
        }
    }
class MQuickAdapter extends BaseQuickAdapter<BaseSpanData, com.chad.library.adapter.base.viewholder.BaseViewHolder>{


        public MQuickAdapter(List<BaseSpanData> data) {
            super(R.layout.item_main, data);
        }

        @Override
        protected void convert(com.chad.library.adapter.base.viewholder.BaseViewHolder baseViewHolder, BaseSpanData baseSpanData) {


        }
    }
`
