### ISSUE TITLE
DragAdapter 在拥有不同的 ViewType 的时候，不同 ViewType 的拖拽排序失败

### ISSUE THREAD

**Issue by loshine** [CymChad/BaseRecyclerViewAdapterHelper#312]
如题所述，比如拥有3个 ViewType，那么相同 ViewType 的项目之间可以拖拽排序，不同 ViewType 之间的拖拽排序失效。

**Comment by elfman** [comment]
因为我觉得不同ViewType之间互换位置不太合适，所以我设置不允许不同ViewType之间的拖拽排序，如果你需要这样的话可以重写`ItemDragAndSwipeCallback`里的`onMove()`方法

**Comment by loshine** [comment]
@elfman 个人觉得应该让使用者自行选择，在文档中写明比较合适。还有谢谢解决问题 :)

**Comment by CymChad** [comment]
@loshine 可以，已加入文档。https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0%E6%8B%96%E6%8B%BD%E3%80%81%E6%BB%91%E5%8A%A8%E5%88%A0%E9%99%A4
