### ISSUE TITLE
如何在BaseQuickAdapter中使用viewBinding

### ISSUE THREAD

**Issue by cdcdec** [CymChad/BaseRecyclerViewAdapterHelper#3138]
如何在BaseQuickAdapter中使用viewBinding

**Comment by esmark-developer** [comment]
同问ヽ(゜Q。)ノ？

**Comment by liangfeng093** [comment]
+1，使用viewBinding后引用的都是对象。控件id命名的时候就不怕重复了。希望能添加对viewBinding

**Comment by Zengyonghao** [comment]
使用纯view的方式  传入binding的root对象就好了

**Comment by liangfeng093** [comment]
> 使用纯view的方式预先绑定的root对象就好了
> 
> `open class BaseBindingAdapter<ITEM,BD:ViewBinding>(val binding: BD): BaseQuickAdapter<ITEM, BaseViewHolder>(0) { override fun convert(holder: BaseViewHolder, item: ITEM) { } override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): BaseViewHolder { return createBaseViewHolder(binding.root) } }`

```kotlin
//直接使用binding设置控件属性，无法触发viewHolder的复用逻辑
binding.itemTwoHeadLeft.rootView1.visibility = View.VISIBLE
binding.itemTwoHeadLeft.tvTitleItemTwoHeadLeft.text = entity.leftTitle
//helper设置控件属性的时候只支持传入id，不支持传入对象。那传入binding就失去了意义，用binding我得点好几下才能把id点出来。那为啥不直接用R.id.rootView1呢？
helper.setVisible(binding.itemTwoHeadLeft.rootView1.id, true)
helper.setText(binding.itemTwoHeadLeft.tvTitleItemTwoHeadLeft.id, entity.leftTitle)
```
所以我觉得还是需要库对ViewBinding进行适配，helper设置控件属性的时候支持直接传入viewBinding对象

**Comment by xayo69** [comment]
BaseQuickAdapter中使用viewBinding是不支持吗？

**Comment by tanranran** [comment]
希望作者完善这一块

**Comment by xayo69** [comment]
纯view方式怎么使用呢？

**Comment by Zengyonghao** [comment]
> > 使用纯view的方式预先绑定的root对象就好了
> > `open class BaseBindingAdapter<ITEM,BD:ViewBinding>(val binding: BD): BaseQuickAdapter<ITEM, BaseViewHolder>(0) { override fun convert(holder: BaseViewHolder, item: ITEM) { } override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): BaseViewHolder { return createBaseViewHolder(binding.root) } }`
> 
> ```kotlin
> //直接使用binding设置控件属性，无法触发viewHolder的复用逻辑
> binding.itemTwoHeadLeft.rootView1.visibility = View.VISIBLE
> binding.itemTwoHeadLeft.tvTitleItemTwoHeadLeft.text = entity.leftTitle
> //helper设置控件属性的时候只支持传入id，不支持传入对象。那传入binding就失去了意义，用binding我得点好几下才能把id点出来。那为啥不直接用R.id.rootView1呢？
> helper.setVisible(binding.itemTwoHeadLeft.rootView1.id, true)
> helper.setText(binding.itemTwoHeadLeft.tvTitleItemTwoHeadLeft.id, entity.leftTitle)
> ```
> 
> 所以我觉得还是需要库对ViewBinding进行适配，helper设置控件属性的时候支持直接传入viewBinding对象

我是自定义了ViewHolder<BD> 构造方法传入了binding对象  在covert中取出binding就好了 onCreateViewHolder中每次会构建新的binding对象 应该不存在触发不了复用逻辑的问题

**Comment by Zengyonghao** [comment]
> 纯view方式怎么使用呢？

构造方法中的LayoutId填0

**Comment by Zengyonghao** [comment]
abstract class BaseBindingAdapter<ITEM,BD:ViewBinding> :
    BaseQuickAdapter<ITEM, BaseBindingAdapter.BindingViewHolder<BD>>(0) {
    abstract fun createBinding(parent: ViewGroup,viewType: Int):BD
    abstract fun convertPayloads(bd: BD,item: ITEM,payloads: Bundle)
    abstract fun convert(bd: BD,holder: BaseViewHolder,item: ITEM)

    override fun convert(holder: BindingViewHolder<BD>, item: ITEM) {
        convert(holder.bd,holder,item)
    }

    override fun convert(holder: BindingViewHolder<BD>, item: ITEM, payloads: List<Any>) {
        if (payloads.isNotEmpty())
        convertPayloads(holder.bd,item,payloads[0] as Bundle)

    }


    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int): BindingViewHolder<BD> {
        return createBaseViewHolder(createBinding(parent,viewType))
    }
    private fun createBaseViewHolder(bd:BD):BindingViewHolder<BD>{
        return BindingViewHolder(bd)
    }


    class BindingViewHolder<BD:ViewBinding>(val bd:BD): BaseViewHolder(bd.root)}

@xayo69 @tanranran @liangfeng093 liang

**Comment by zwping** [comment]
根据文档[纯view的使用方法](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/readme/1-BaseQuickAdapter.md#2%E7%BA%AFview%E5%88%9B%E5%BB%BAitem), 稍加改造一下即可, 没有过多的学习成本
```kotlin
abstract class BaseBindingAdapter<T, VB : ViewBinding>(data: MutableList<T>? = null) : BaseQuickAdapter<T, BaseViewHolder>(0, data) {

    abstract fun createViewBinding(inflater: LayoutInflater, parent: ViewGroup): VB

    abstract fun convert(holder: BaseViewHolder, vb: VB, item: T)

    lateinit var viewBinding: VB

    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int): BaseViewHolder {
        viewBinding = createViewBinding(LayoutInflater.from(parent.context), parent)
        return createBaseViewHolder(viewBinding.root)
    }

    override fun convert(holder: BaseViewHolder, item: T) {
        convert(holder, viewBinding, item)
    }

}
```
使用方法
```kotlin
val adapter = object : BaseBindingAdapter<String, ItemTestBinding>() {
                override fun createViewBinding(inflater: LayoutInflater, parent: ViewGroup): ItemTestBinding {
                    return ItemTestBinding.inflate(inflater, parent, false)
                }

                override fun convert(holder: BaseViewHolder, vb: ItemTestBinding, item: String) {
                    // holder.setText(R.id.tv_title,item)
                    vb.tvTitle.text = "$item"
                }
            }
```

**Comment by lx36301766** [comment]
https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650253904&idx=1&sn=172ba86cb5ce3bda68b7933672e870db&chksm=88635b3fbf14d22941fc2a24715d8e6aa9881881f0ca152532fe5adf41febe1548e19c0f2647&&xtrack=1&scene=90&subscene=93&sessionid=1610673603&clicktime=1610674599&enterid=1610674599#rd

参考这篇文章改造一下使用更方便：

implementation 'com.dylanc:viewbinding-ktx:1.0.1'

`abstract class BaseBindingAdapter<T, VB : ViewBinding>(data: MutableList<T>? = null)
    : BaseQuickAdapter<T, BindingViewHolder<VB>>(0, data) {

    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int) = newBindingViewHolderWithGeneric<VB>(parent)

}

inline fun <reified VB : ViewBinding> newBindingViewHolder(parent: ViewGroup): BindingViewHolder<VB> =
    BindingViewHolder.create(VB::class.java, parent)

fun <VB : ViewBinding> Any.newBindingViewHolderWithGeneric(parent: ViewGroup): BindingViewHolder<VB> =
    BindingViewHolder.createWithGeneric(this, parent)

class BindingViewHolder<VB : ViewBinding>(val binding: VB) : BaseViewHolder(binding.root) {
    companion object {
        @JvmStatic
        fun <VB : ViewBinding> create(clazz: Class<VB>, parent: ViewGroup) =
            BindingViewHolder(inflateBinding(clazz, LayoutInflater.from(parent.context), parent, false))

        @JvmStatic
        fun <VB : ViewBinding> createWithGeneric(any: Any, parent: ViewGroup) =
            BindingViewHolder<VB>(any.inflateBindingWithGeneric(LayoutInflater.from(parent.context), parent, false))
    }
}
`

使用方式：
`class XXXListAdapter(
    val dataList: MutableList<XXXBean>? = null
) : BaseBindingAdapter<XXXBean, XXXListitemBinding>(dataList) {

    override fun convert(holder: BindingViewHolder<XXXListitemBinding>, item: XXXBean) {
        holder.binding.name.text = item.name
    }

}
`

**Comment by lx36301766** [comment]
https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650253904&idx=1&sn=172ba86cb5ce3bda68b7933672e870db&chksm=88635b3fbf14d22941fc2a24715d8e6aa9881881f0ca152532fe5adf41febe1548e19c0f2647&&xtrack=1&scene=90&subscene=93&sessionid=1610673603&clicktime=1610674599&enterid=1610674599#rd

参考这篇文章改造一下使用更方便：

先把库导进来：implementation 'com.dylanc:viewbinding-ktx:1.0.1' （此库代码量很少）

然后创建 BaseBindingAdapter.kt
```kotlin
abstract class BaseBindingAdapter<T, VB : ViewBinding>(data: MutableList<T>? = null)
    : BaseQuickAdapter<T, BindingViewHolder<VB>>(0, data) {

    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int) = newBindingViewHolderWithGeneric<VB>(parent)

}


inline fun <reified VB : ViewBinding> newBindingViewHolder(parent: ViewGroup): BindingViewHolder<VB> =
    BindingViewHolder.create(VB::class.java, parent)

fun <VB : ViewBinding> Any.newBindingViewHolderWithGeneric(parent: ViewGroup): BindingViewHolder<VB> =
    BindingViewHolder.createWithGeneric(this, parent)

class BindingViewHolder<VB : ViewBinding>(val binding: VB) : BaseViewHolder(binding.root) {
    companion object {
        @JvmStatic
        fun <VB : ViewBinding> create(clazz: Class<VB>, parent: ViewGroup) =
            BindingViewHolder(inflateBinding(clazz, LayoutInflater.from(parent.context), parent, false))

        @JvmStatic
        fun <VB : ViewBinding> createWithGeneric(any: Any, parent: ViewGroup) =
            BindingViewHolder<VB>(any.inflateBindingWithGeneric(LayoutInflater.from(parent.context), parent, false))
    }
}

```

使用姿势：
```kotlin
class XXXListAdapter(
    val dataList: MutableList<XXXBean>? = null
) : BaseBindingAdapter<XXXBean, XXXListitemBinding>(dataList) {

    override fun convert(holder: BindingViewHolder<XXXListitemBinding>, item: XXXBean) {
        holder.binding.name.text = item.name
    }

}
```

**Comment by hc79879** [comment]
`
abstract class BaseVBQuickAdapter<VB : ViewBinding,T>(data: MutableList<T>? = null)
    : BaseQuickAdapter<T, BaseVBViewHolder<VB>>(0, data) {

    @Suppress("UNCHECKED_CAST")
    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int): BaseVBViewHolder<VB> {
        val type = javaClass.genericSuperclass
        //反射type.actualTypeArguments index=0 ->VB泛型ViewBinding;
        val clazz = (type as ParameterizedType).actualTypeArguments.first() as Class<VB>
        val method = clazz.getMethod("inflate", LayoutInflater::class.java,ViewGroup::class.java,Boolean::class.java)
        val binding = method.invoke(null, LayoutInflater.from(parent.context), parent,false) as VB
        return BaseVBViewHolder(binding)
    }
}

class BaseVBViewHolder<VB : ViewBinding>(val binding: VB) : BaseViewHolder(binding.root)
`

**Comment by hc79879** [comment]
`abstract class BaseVBQuickAdapter<VB : ViewBinding,T>(data: MutableList<T>? = null)
    : BaseQuickAdapter<T, BaseVBViewHolder<VB>>(0, data) {

    @Suppress("UNCHECKED_CAST")
    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int): BaseVBViewHolder<VB> {
        val type = javaClass.genericSuperclass
        //反射type.actualTypeArguments index=0 ->VB泛型ViewBinding;
        val clazz = (type as ParameterizedType).actualTypeArguments.first() as Class<VB>
        val method = clazz.getMethod("inflate", LayoutInflater::class.java,ViewGroup::class.java,Boolean::class.java)
        val binding = method.invoke(null, LayoutInflater.from(parent.context), parent,false) as VB
        return BaseVBViewHolder(binding)
    }
}

class BaseVBViewHolder<VB : ViewBinding>(val binding: VB) : BaseViewHolder(binding.root)`

**Comment by hc79879** [comment]
abstract class BaseVBQuickAdapter<VB : ViewBinding,T>(data: MutableList<T>? = null)
    : BaseQuickAdapter<T, BaseVBViewHolder<VB>>(0, data) {

    @Suppress("UNCHECKED_CAST")
    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int): BaseVBViewHolder<VB> {
        val type = javaClass.genericSuperclass
        //反射type.actualTypeArguments index=0 ->VB泛型ViewBinding;
        val clazz = (type as ParameterizedType).actualTypeArguments.first() as Class<VB>
        val method = clazz.getMethod("inflate", LayoutInflater::class.java,ViewGroup::class.java,Boolean::class.java)
        val binding = method.invoke(null, LayoutInflater.from(parent.context), parent,false) as VB
        return BaseVBViewHolder(binding)
    }
}

class BaseVBViewHolder<VB : ViewBinding>(val binding: VB) : BaseViewHolder(binding.root)

**Comment by hc79879** [comment]
```
abstract class BaseVBQuickAdapter<VB : ViewBinding,T>(data: MutableList<T>? = null)
    : BaseQuickAdapter<T, BaseVBViewHolder<VB>>(0, data) {

    @Suppress("UNCHECKED_CAST")
    override fun onCreateDefViewHolder(parent: ViewGroup, viewType: Int): BaseVBViewHolder<VB> {
        val type = javaClass.genericSuperclass
        //反射type.actualTypeArguments index=0 ->VB泛型ViewBinding;
        val clazz = (type as ParameterizedType).actualTypeArguments.first() as Class<VB>
        val method = clazz.getMethod("inflate", LayoutInflater::class.java,ViewGroup::class.java,Boolean::class.java)
        val binding = method.invoke(null, LayoutInflater.from(parent.context), parent,false) as VB
        return BaseVBViewHolder(binding)
    }
}

class BaseVBViewHolder<VB : ViewBinding>(val binding: VB) : BaseViewHolder(binding.root)
```

**Comment by kokod21** [comment]
class MyAdapter : BaseQuickAdapter<String, BaseViewHolder>(R.layout.item_layout) {
    override fun convert(holder: BaseViewHolder, item: String) { 
        val binding = ItemLayoutBinding.bind(holder.itemView)
        binding.tvXX = item
    }
}

这种方式可行？

**Comment by juniniho** [comment]
> class MyAdapter : BaseQuickAdapter<String, BaseViewHolder>(R.layout.item_layout) {
> override fun convert(holder: BaseViewHolder, item: String) {
> val binding = ItemLayoutBinding.bind(holder.itemView)
> binding.tvXX = item
> }
> }
> 
> 这种方式可行？
在创建ViewHolder的时候bind一次就行了。
`private lateinit var binding : ListItemBinding
override fun onViewHolderCreated(viewHolder: BaseViewHolder, viewType: Int) {
        binding = ListItemBinding.bind(viewHolder.itemView)
    }`

**Comment by peng093** [comment]
> > class MyAdapter : BaseQuickAdapter<String, BaseViewHolder>(R.layout.item_layout) {
> > override fun convert(holder: BaseViewHolder, item: String) {
> > val binding = ItemLayoutBinding.bind(holder.itemView)
> > binding.tvXX = item
> > }
> > }
> > 这种方式可行？
> > 在创建ViewHolder的时候bind一次就行了。
> 
> ```
> private lateinit var binding : ListItemBinding
> override fun onViewHolderCreated(viewHolder: BaseViewHolder, viewType: Int) {
>         binding = ListItemBinding.bind(viewHolder.itemView)
> }
> ```
6666，看来多那么多，还是你这个最简单 哈哈

**Comment by peng093** [comment]
> > class MyAdapter : BaseQuickAdapter<String, BaseViewHolder>(R.layout.item_layout) {
> > override fun convert(holder: BaseViewHolder, item: String) {
> > val binding = ItemLayoutBinding.bind(holder.itemView)
> > binding.tvXX = item
> > }
> > }
> > 这种方式可行？
> > 在创建ViewHolder的时候bind一次就行了。
> 
> ```
> private lateinit var binding : ListItemBinding
> override fun onViewHolderCreated(viewHolder: BaseViewHolder, viewType: Int) {
>         binding = ListItemBinding.bind(viewHolder.itemView)
> }
> ```

这样还是比较麻烦，每一个适配器都要声明binding ，我是重写了一个基类
基类
```
public abstract class BaseBindingAdapter<T,VB extends ViewBinding> extends BaseQuickAdapter<T, BaseViewHolder> {
    public VB bd;

    public BaseBindingAdapter(int subView, @Nullable List<T> data) {
        super(subView,data);
    }

    @Override
    protected void onItemViewHolderCreated(@NotNull BaseViewHolder viewHolder, int viewType) {
        super.onItemViewHolderCreated(viewHolder, viewType);
        Type superclass = getClass().getGenericSuperclass();
        Class<?> aClass = (Class<?>) ((ParameterizedType) superclass).getActualTypeArguments()[1];
        try {
            Method method = aClass.getDeclaredMethod("bind", View.class);
            bd = (VB) method.invoke(null, viewHolder.itemView);
        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
            e.printStackTrace();
        }
    }
}
```
使用
```
public class ViewBindingAdapter extends BaseBindingAdapter<TextBean, ItemViewBinding> {

    public ViewBindingAdapter(@Nullable List<TextBean> data) {
        super(R.layout.item_view, data);
    }

    @Override
    protected void convert(BaseViewHolder helper, TextBean item) {
        bd.titleTextview.setText("重写基类");
        bd.typeTextview.setText("测试");
    }
}
```

**Comment by nullkk** [comment]
> > > class MyAdapter : BaseQuickAdapter<String, BaseViewHolder>(R.layout.item_layout) {
> > > override fun convert(holder: BaseViewHolder, item: String) {
> > > val binding = ItemLayoutBinding.bind(holder.itemView)
> > > binding.tvXX = item
> > > }
> > > }
> > > 这种方式可行？
> > > 在创建ViewHolder的时候bind一次就行了。
> > 
> > 
> > ```
> > private lateinit var binding : ListItemBinding
> > override fun onViewHolderCreated(viewHolder: BaseViewHolder, viewType: Int) {
> >         binding = ListItemBinding.bind(viewHolder.itemView)
> > }
> > ```
> 
> 这样还是比较麻烦，每一个适配器都要声明binding ，我是重写了一个基类
> 基类
> 
> ```
> public abstract class BaseBindingAdapter<T,VB extends ViewBinding> extends BaseQuickAdapter<T, BaseViewHolder> {
>     public VB bd;
> 
>     public BaseBindingAdapter(int subView, @Nullable List<T> data) {
>         super(subView,data);
>     }
> 
>     @Override
>     protected void onItemViewHolderCreated(@NotNull BaseViewHolder viewHolder, int viewType) {
>         super.onItemViewHolderCreated(viewHolder, viewType);
>         Type superclass = getClass().getGenericSuperclass();
>         Class<?> aClass = (Class<?>) ((ParameterizedType) superclass).getActualTypeArguments()[1];
>         try {
>             Method method = aClass.getDeclaredMethod("bind", View.class);
>             bd = (VB) method.invoke(null, viewHolder.itemView);
>         } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
>             e.printStackTrace();
>         }
>     }
> }
> ```
> 
> 使用
> 
> ```
> public class ViewBindingAdapter extends BaseBindingAdapter<TextBean, ItemViewBinding> {
> 
>     public ViewBindingAdapter(@Nullable List<TextBean> data) {
>         super(R.layout.item_view, data);
>     }
> 
>     @Override
>     protected void convert(BaseViewHolder helper, TextBean item) {
>         bd.titleTextview.setText("重写基类");
>         bd.typeTextview.setText("测试");
>     }
> }
> ```

反射是不是有点影响性能了。。。

**Comment by juniniho** [comment]
onViewHolderCreated里面bind不行，会有复用的bug，绑定数据都错位了。我后来干脆改用原生的adapter。
发自我的iPad

**Comment by peng093** [comment]
> onViewHolderCreated里面bind不行，会有复用的bug，绑定数据都错位了。我后来干脆改用原生的adapter。 发自我的iPad
> […](#)
> 在 2021年6月28日，09:05，peng ***@***.***> 写道： ﻿ class MyAdapter : BaseQuickAdapter<String, BaseViewHolder>(R.layout.item_layout) { override fun convert(holder: BaseViewHolder, item: String) { val binding = ItemLayoutBinding.bind(holder.itemView) binding.tvXX = item } } 这种方式可行？ 在创建ViewHolder的时候bind一次就行了。 private lateinit var binding : ListItemBinding override fun onViewHolderCreated(viewHolder: BaseViewHolder, viewType: Int) { binding = ListItemBinding.bind(viewHolder.itemView) } 6666，看来多那么多，还是你这个最简单 哈哈 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
在 onViewHolderCreated里面bind，确实是有bug，bd被互相覆盖，导致位置错乱，以下在issue看到 有人使用新的基类实现的
```
public abstract class BaseBindingAdapter<T,VB extends ViewBinding> extends BaseQuickAdapter<T, BaseBindingAdapter.BaseVBViewHolder<VB>> {
    private Class<?> vbClass;

    // public VB bd;

    public BaseBindingAdapter(int subView, @Nullable List<T> data) {
        super(subView,data);
        initVBClass();
    }

    private void initVBClass(){
        Type superclass = getClass().getGenericSuperclass();
        Type[] typeArr = ((ParameterizedType) superclass).getActualTypeArguments();
        for (Type type:typeArr){
            Class<?> aClass = (Class<?>) type;
            if (ViewBinding.class.isAssignableFrom(aClass)){
                vbClass = aClass;
                return;
            }
        }
        throw new RuntimeException("你的适配器需要提供一个ViewBinding的泛型才能进行视图绑定");
    }

    @NotNull
    @Override
    protected BaseVBViewHolder<VB> onCreateDefViewHolder(@NotNull ViewGroup parent, int viewType) {
        return new BaseVBViewHolder<VB>(getViewBinding(LayoutInflater.from(parent.getContext()),parent));
    }

    @SuppressWarnings("unchecked")
    protected VB getViewBinding(LayoutInflater from, ViewGroup parent) {
        VB binding = null;
        try {
            Method method = vbClass.getDeclaredMethod("inflate", LayoutInflater.class,ViewGroup.class,boolean.class);
            binding = (VB) method.invoke(null, from,parent,false);
        } catch (NoSuchMethodException | IllegalAccessException| InvocationTargetException e) {
            e.printStackTrace();
        }
        return binding;
    }

    @SuppressWarnings("unchecked")
    public static class BaseVBViewHolder<VB> extends BaseViewHolder {
        public VB bd;

        public <B extends ViewBinding>BaseVBViewHolder(B binding) {
            super(binding.getRoot());
            this.bd = (VB) binding;
        }

    }
```
使用
```
public class ListDiglogAdapter extends BaseBindingAdapter<ListDiglogBean, AdapterDiglogItemBinding> {

        public ListDiglogAdapter(@Nullable List<ListDiglogBean> data) {
            super(R.layout.adapter_diglog_item, data);
        }


        @Override
        protected void convert(@NotNull BaseVBViewHolder<AdapterDiglogItemBinding> helper, ListDiglogBean item) {
            helper.bd.icIcon.setImageResource(item.getBgIcon());
            helper.bd.tvName.setText(item.getTitle());
        }
    }
```

**Comment by liweiGe** [comment]
从此再也不用写adapter，这是我研究的写法，有些人会说反射影响性能，不要闻风色变，就这点反射跟你自己的代码相比微不足道，至少代码写死来舒服

<img width="947" alt="image" src="https://user-images.githubusercontent.com/25901728/194837057-6b503c60-926c-4911-8524-d49a8b983e4d.png">
