### ISSUE TITLE
BaseMultiItemQuickAdapter 同一个Position 通过helper.getView 获取的view地址不一样

### ISSUE THREAD

**Issue by markliu009** [CymChad/BaseRecyclerViewAdapterHelper#3139]
**Describe the bug**
继承BaseMultiItemQuickAdapter 当调用notifyItemChanged(position)方法后(压测，猛调用)同一个Position 通过helper.getView 获取的view地址不一样

**To Reproduce**
1. 继承BaseMultiItemQuickAdapter
2. 频繁调用notifyItemChanged(position)方法  
3. 通过helper.getView  获取view 目的：通过网络请求来改变view的地址不相同

**Comment by BigKarel** [comment]
我也遇到了这个问题，有解决办法吗

**Comment by BigKarel** [comment]
只要notifyItemChanged(position)，helper.getView获取对象就不是同一个
