### ISSUE TITLE
BaseSectionQuickAdapter 获取不到view的id，即 helper.setText()方法报No view found with id 2131296560

### ISSUE THREAD

**Issue by WarriorYu** [CymChad/BaseRecyclerViewAdapterHelper#3142]

**Comment by sanhou** [comment]
你用的什么版本，我在convertHead里面也是找不到view

**Comment by PostLiu** [comment]
你这是解决了???我也遇到了这个问题

**Comment by bsodKeks** [comment]
Hi guys. Faced the same problem. Changed the order of layouts in the adapter constructor, and everything worked
