### ISSUE TITLE
在4.4.4的版本中，渲染很慢，大概慢 2 3秒才显示数据！

### ISSUE THREAD

**Issue by 6cwong** [CymChad/BaseRecyclerViewAdapterHelper#3144]
由于内部APK需要在4.4.4的版本中运行，发现渲染很慢，大概慢3秒左右列表才显示数据！列表数据不多才20条左右，请问各位大佬有啥解决方案？

**Comment by limuyang2** [comment]
请确认你的使用方法

**Comment by 6cwong** [comment]
> 请确认你的使用方法

我用的是完全正确的方法，在自己的手机9.0和模拟器5.1测试获取到数据之后就列表就秒显示出来，在一部4.4的手机上需要等个3秒左右才显示出列表数据。

**Comment by qgreat** [comment]
我也出现这个问题了，4.4.2的平板上，请问解决了吗？

**Comment by qgreat** [comment]
> 我也出现这个问题了，4.4.2的平板上，请问解决了吗？

问题找到了，是item layout里面只要有Checkbox就会inflate很耗时。
