### ISSUE TITLE
Provider 如何判斷已經回收

### ISSUE THREAD

**Issue by PascalTang** [CymChad/BaseRecyclerViewAdapterHelper#3145]
請問Provider有辦法判斷adapter當前item是否被回收嗎

就是可視範圍以外的資料
想要做處理
但我override沒看到相關的

**Comment by iso88591** [comment]
override fun onViewDetachedFromWindow(holder: MyBaseViewHolder) {
        super.onViewDetachedFromWindow(holder)
    }

    override fun onViewAttachedToWindow(holder: MyBaseViewHolder) {
        super.onViewAttachedToWindow(holder)
    }
複寫adapter的這個方法

**Comment by limuyang2** [comment]
`BaseItemProvider`中，已经添加`onViewAttachedToWindow`和`onViewDetachedFromWindow`方法
