### ISSUE TITLE
在adapter设置条目长按事件后,发生内存泄漏!  3.0.3

### ISSUE THREAD

**Issue by tangchuanyong** [CymChad/BaseRecyclerViewAdapterHelper#3146]
@Override
    protected void initView() {
        super.initView();
        initAdapter();
    }

    private void initAdapter() {
        rvList.getRecyclerView().setHasFixedSize(true);
        rvList.getRecyclerView().setLayoutManager(new LinearLayoutManager(this));
        comAdapter = new ComAdapter<AlarmHelpMessageBean>(R.layout.item_device_alarm_message, new ArrayList<>()) {
            @Override
            protected void convert(@NotNull BaseViewHolder helper, AlarmHelpMessageBean item) {
          
            }
        };
        rvList.setAdapter(comAdapter);
    }

@Override
    protected void initListener() {
        super.initListener();
        comAdapter.setOnItemLongClickListener(new OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(@NonNull BaseQuickAdapter adapter, @NonNull View view, int position) {
               L.e("长按事件随便长按几个条目,必定发生内存泄漏");
           
                return true;
           }
        });
    }

**Comment by tangchuanyong** [comment]
写不写setOnItemLongClickListener回调事件都会发生.只要长按就会内存泄漏

**Comment by tangchuanyong** [comment]
我切换回2+版本一样还是有泄漏发生,在Demo中LoadMore模块可测!必定发生内存泄漏!

**Comment by tangchuanyong** [comment]
这都没人测一下这个问题吗？

**Comment by iztou** [comment]
他这个框架有个根本性的错误，就是adapter持有了RecyclerView 的引用，这样子必然会报内存泄漏的
