### ISSUE TITLE
RV中的ImageView使用Databinding的方式加载图片会报类型转换失败

### ISSUE THREAD

**Issue by CordyHo** [CymChad/BaseRecyclerViewAdapterHelper#3148]
报错信息：java.lang.ClassCastException: com.chad.library.adapter.base.viewholder.BaseViewHolder cannot be cast to com.chad.library.adapter.base.viewholder.BaseDataBindingHolder
        at com.noahsolutions.goods2go.module.main.adapter.RvExpressAdapter.convert(RvExpressAdapter.kt:12)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:362)

RV item layout xml：
```
<ImageView
                    android:id="@+id/iv_logo"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_gravity="center"
                    android:scaleType="fitCenter"
                    android:src="@mipmap/ic_launcher"
                    app:imgNoBaseUrl="@{express.logo}"
                    tools:ignore="ContentDescription" />
```

RV Adapter代码：
class RvExpressAdapter(private val iExpressSelectCallBack: IExpressSelectCallBack)
    : BaseQuickAdapter<ViewModelExpressSelect.DataBean, BaseDataBindingHolder<ItemRvExpressBinding>>(R.layout.item_rv_express) {

    override fun convert(holder: BaseDataBindingHolder<ItemRvExpressBinding>, item: ViewModelExpressSelect.DataBean) {
        holder.dataBinding?.express = item
        holder.dataBinding?.tvBook?.setOnClickListener {
            iExpressSelectCallBack.onExpressSelect()
            PackageInfoModel.expressBean.set(item)  // 给静态类变量赋值，表示选择哪家快递公司
        }
    }
}

Glide代码：
@BindingAdapter("imgNoBaseUrl")
    fun setImageFromUrlNoBaseUrl(iv_image: ImageView, url: String?) {
        val options = RequestOptions()
                .error(R.mipmap.ic_launcher)
                .placeholder(R.mipmap.ic_launcher)
                .dontAnimate()
                .fitCenter()
        Goods2GoApplication.application?.let {
            Glide.with(it)
                    .load(url)
                    .apply(options)
                    .into(iv_image)
        }
    }

**Comment by CordyHo** [comment]
kotlin的话，除了 @BindingAdapter("imgNoBaseUrl") 注解之外还要加上 @JvmStatic

**Comment by CalmCenter** [comment]
在哪里加 @JvmStatic ？ 我也遇到了同样的情况
