### ISSUE TITLE
getView找不到View会直接崩溃，不会返回null

### ISSUE THREAD

**Issue by Moster1h** [CymChad/BaseRecyclerViewAdapterHelper#3152]
1. 当前使用的版本号
3.0.3
2. 复现操作描述
getView找不到View会直接崩溃，不会返回null。能不能getView默认使用getViewOrNull，不要搞成两个方法，这样做有必要吗？什么设计呀！
3. 使用代码
```
            View rl_pause = helper.getView(R.id.rl_pause);
            ProgressBar progressBar = helper.getView(R.id.progressBar);
```
4. crash日志
```
 java.lang.IllegalStateException: No view found with id 2131231349
        at com.chad.library.adapter.base.viewholder.BaseViewHolder.getView(BaseViewHolder.kt:37)
```

**Comment by Moster1h** [comment]
还有getItem也是，真心想不通了，很多多余的方法，用一个通用的就行了呀！

**Comment by ekibun** [comment]
附议，现在自带的SimpleLoadMoreView里没有load_more_load_complete_view，在调用getLoadComplete的时候直接炸了。

**Comment by Moster1h** [comment]
真心建议把不带OrNull的同名方法删除掉，只保留带OrNull，不然从2.0版本升级到3.0版本坑的要死。

**Comment by limuyang2** [comment]
请参考`kotlin`官方的API设计，例如：
`list.getOrNull()`
`list.getOrElse()`

在`kotlin`中，是null安全的语言。严格意义区分null与非null。

此接口设计并无问题，符合官方定义

**Comment by limuyang2** [comment]
还有，文档已经说明，3.0采用`kotlin`编写，加上api改动，属于不兼容升级

**Comment by Moster1h** [comment]
把不带OrNull的方法，内部实现用带OrNull的方法有那么难吗？，这样切换就兼容了。

**Comment by Moster1h** [comment]
而且继承你的BaseViewHolder，getView是final方法不能重写。想自己重写getView内部换成getViewOrNull都不行

**Comment by Moster1h** [comment]
Adapter的`getItem`不是final方法所以可以重写，内部使用`getItemOrNull`
```
   @Override
    public T getItem(int position) {
        return getItemOrNull(position);
    }
```

**Comment by limuyang2** [comment]
> 把不带OrNull的方法，内部实现用带OrNull的方法有那么难吗？，这样切换就兼容了。

这并非是难不难的问题，而是是否符合语意的问题

**Comment by Moster1h** [comment]
那你至少开放一下，让我们可以重写吧！

**Comment by limuyang2** [comment]
已经开放为open方法，可以复写了。请更新`3.0.4`

**Comment by Moster1h** [comment]
Ok,谢谢了❤️
