### ISSUE TITLE
条目中的图形会被绘制到title上面

### ISSUE THREAD

**Issue by WanMMao** [CymChad/BaseRecyclerViewAdapterHelper#3154]
![image](https://user-images.githubusercontent.com/28594366/80359222-18357680-88b0-11ea-9606-3fc8ed4dbe5f.png)
item中两个空间采用shape作为背景，控件1 背景为一个矩形框边框为蓝色，控件2背景是红色矩形框，滑动几次之后位于RecyclerView之上的title下面就会多了两条横线，颜色分别和这两个控件的颜色相对应，这个bug在我多个项目中都有出现

**Comment by limuyang2** [comment]
此库并不涉及view的渲染，检查下你的shape
