### ISSUE TITLE
BaseMultiItemQuickAdapter 多布局嵌套子RecyclerView显示不全

### ISSUE THREAD

**Issue by zYoungTang** [CymChad/BaseRecyclerViewAdapterHelper#3156]
原因:
由于嵌套 RecyclerView 的时候会导致 子RV 的条目 width 变小,
导致:
如果其中一个 item 嵌套了一个子 RecyclerView ,且不停在 data 中去掉这个 item 再加上去,这个条目的宽度会越变越小;

**Comment by xiaolunan** [comment]
我也遇到了，RecyclerView嵌套RecyclerView，子RecyclerView中数据过多的直接显示很高一段空白，数据少的能正常显示，请问怎么解决
