### ISSUE TITLE
最新版2.0没有notifyDataChangedAfterLoadMore(false)这个方法了么?

### ISSUE THREAD

**Issue by lifetin** [CymChad/BaseRecyclerViewAdapterHelper#316]

**Comment by lifetin** [comment]
![55](https://cloud.githubusercontent.com/assets/10474968/18409694/5aa9849c-7780-11e6-938a-80d4a5641370.png)
我这返回数据为空.想把这个移除掉.但是用了adapter.removeAllFooterView(); 还是不管用?
要怎么样把这个删掉呢?

**Comment by CymChad** [comment]
API改了，具体使用你可以看demo和文档，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD
