### ISSUE TITLE
都没发现加载更多失败后，点击重试要很准才有反应

### ISSUE THREAD

**Issue by abc784990536** [CymChad/BaseRecyclerViewAdapterHelper#317]
demo也会这样，就是加载更多失败后显示重试的footview，点击就会重新加载，但是这个点击事件似乎点的要非常果断精准才有反应，否则点多少下都没放应，是否点击事件被拦截

**Comment by abc784990536** [comment]
还有头部的点击事件也是，希望改善，不然用户点了都没反应

**Comment by CymChad** [comment]
恩 好的已经收到了。

**Comment by CymChad** [comment]
刚才用真机测试了，没有发现这个问题，看了下事件拦截代码对footview 和 headview 的点击没有拦截，抛给自己处理的。
