### ISSUE TITLE
helper.getLayoutPosition()=-1

### ISSUE THREAD

**Issue by steaywengwu** [CymChad/BaseRecyclerViewAdapterHelper#3170]
版本2.9.46
下标越界问题，导致闪退
问题描述：总共12条数据，快速滑动底部时（网络请求完成，数据有了，我就直接滑到底了，没停留），老是报下标越界问题，闪退，发现快速滑动到底部时helper.getLayoutPosition()=-1，

**Comment by limuyang2** [comment]
请更新版本尝试解决
