### ISSUE TITLE
子按钮的点击状态

### ISSUE THREAD

**Issue by bobingxin** [CymChad/BaseRecyclerViewAdapterHelper#318]
当点击一个子按钮的时候，另外一个子按钮也出现按压状态。

**Comment by AllenCoder** [comment]
按钮的点击状态问题，请查阅 wiki 详细操作步骤

**Comment by coolfire2015** [comment]
非常抱歉,该问题我这边也出现了,wiki中没有发现解决办法

**Comment by AllenCoder** [comment]
你好，目前 itemview的 selector 触发是基于 itemview 设计的，所以点击同一个 itemview 的任意一个 childview 都会触发 itemview 的 selector，下周版本更新会着重修复掉这个 bug,感谢你的反馈，

**Comment by bobingxin** [comment]
在textview增加一个clickable为true就不会出现这个问题，我目前是这么解决的。

**Comment by coolfire2015** [comment]
@bobingxin 好的,谢谢
