### ISSUE TITLE
BaseBinderAdapter 怎么使用上拉加载布局

### ISSUE THREAD

**Issue by qq570026938** [CymChad/BaseRecyclerViewAdapterHelper#3183]
BaseBinderAdapter 使用上拉加载更多，在page大于1时使用adapter.addData(list)数据重复

**Comment by qq570026938** [comment]
后开始依次重复，在上拉加载还是前5次的数据，后台传来的数据是正常的，打印发现，不在走绑定的QuickDataBindingItemBinder中的列表方法了
![image](https://user-images.githubusercontent.com/28619076/82188490-881fa580-9920-11ea-9c20-4d752eb75fb9.png)

**Comment by benxin123** [comment]
BaseBinderAdapter 怎么 implements 上拉加载？

**Comment by kidc1412** [comment]
> BaseBinderAdapter 怎么 implements 上拉加载？

可以自己新建一个Adapter然后继承BaseBinderAdapter然后再实现LoadMoreModule
