### ISSUE TITLE
使用ViewPager2

### ISSUE THREAD

**Issue by 330676687** [CymChad/BaseRecyclerViewAdapterHelper#3190]
使用ViewPager2报错
 java.lang.IllegalStateException: Pages must fill the whole ViewPager2 (use match_parent)
BaseDataBindingHolder没做适配吗

**Comment by minzbox** [comment]
Hi, how do you solve this issue? I encounter this when call load more.

**Comment by minzbox** [comment]
Hi, how do you solve this issue? I encounter this when call load more.

**Comment by ZhanRu** [comment]
同问

**Comment by 932707629** [comment]
是因为用了LoadMoreModule  看这个 https://www.jianshu.com/p/64940080f8fa
