### ISSUE TITLE
使用basequickadapter列表初始状态不滑动，点击事件失效

### ISSUE THREAD

**Issue by CCCCoder** [CymChad/BaseRecyclerViewAdapterHelper#3195]
版本：3.0.4
情况：初始化列表情况下，使用加载更多模块，不滑动列表，点击事件失效。只要滑动列表，点击事件有效。又遇到这种情况的么？

**Comment by CCCCoder** [comment]
非此库问题。

**Comment by YaakovHuang** [comment]
> 版本：3.0.4
> 情况：初始化列表情况下，使用加载更多模块，不滑动列表，点击事件失效。只要滑动列表，点击事件有效。又遇到这种情况的么？

我遇到了 我的情况是 ConstraintLayout + TabLayout + ViewPager2， ViewPager2里面的 Fragment 里面是 RecyclerView ，解决办法就是将  ConstraintLayout 改成 LinearLayout。

**Comment by KleinerFrosch** [comment]
> 非此库问题。

我遇到相同问题，请问你是怎么解决的
