### ISSUE TITLE
RecyclerView滚动监听并改变item

### ISSUE THREAD

**Issue by solomon2** [CymChad/BaseRecyclerViewAdapterHelper#320]
老大您好： 
       我想在RecyclerView滚动中监听并改变item内容。实体类使用并继承MultiItemEntity，按照您DEMO和参考源码，我尝试了几天无法实现，现在遇到的问题是要么无法更新，要么会刷新整个list界面，能否优化下实现这个功能。

```
        recycler_view.setOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                int firstVisibleItem = linearLayoutManager.findFirstCompletelyVisibleItemPosition();
                if (newState == 0) {
                    if (null != recycler_view.getChildAt(0)) {
                        adapter.getItem(firstVisibleItem).setItemType(TabViewNewAdapter.TYPE_2);
                        adapter.notifyDataSetChanged();
                    }
                }
            }
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) { }
        });
```

Adapter:
```
    @Override
    protected void convert(BaseViewHolder baseViewHolder, final ScenicListData tabViewObj) {
        int type = baseViewHolder.getItemViewType();
        final VrPanoramaView panoWidgetView =  baseViewHolder.getView(R.id.pano_view);
        final ImageView imageView = baseViewHolder.getView(R.id.imageView);
        if (type == TYPE_2) {
            imageView.setVisibility(View.GONE);
            panoWidgetView.setVisibility(View.VISIBLE);
            .....
```

**Comment by CymChad** [comment]
你有什么需求，需要这么做吗？

**Comment by solomon2** [comment]
是的 VrPanoramaView 的RecyclerView， 在滑动中只显示一个VrPanoramaView，其他item显示image

**Comment by solomon2** [comment]
RecyclerView , List 显示VrPanoramaView ，就像显示一批小视频一样， 性能、流程度 或者用户体验等原因，屏幕呈现出几个item，只展现第一个滑动出来完整的item ，其他的item用图标展示。

**Comment by solomon2** [comment]
本来我是重写Adapter的 getItemViewType  ，但由于还需要用到LoadMore， 重写了的话就和LoadMore冲突 。 所以 ~ 老大 求助~

**Comment by CymChad** [comment]
没用过VrPanoramaView，能有gif图吗？我理解的是，需要一个view置顶对吗？

**Comment by CymChad** [comment]
悬浮

**Comment by solomon2** [comment]
https://cloud.githubusercontent.com/assets/2686355/12434458/6f677ae4-bf0f-11e5-8fa9-b3d3b8a30165.gif

类似这个VideoPlayerManager框架实现的效果，不过他这个是播放视频 ，我有试过他的框架，还是和各种加载更多有冲突。

就是list在上下滑动时， 播放(特殊处理)第一个完整显示item， 其他的item用另外一个方式显示(只显示image)

**Comment by CymChad** [comment]
你可以试下 notifyItemRangeChanged刷新当个item的这个api试试。

**Comment by solomon2** [comment]
但是 只用adapter.getItem(firstVisibleItem).setItemType(TabViewNewAdapter.TYPE_2); 

无法更新 Data里面的ItemType
只有把DataList传入Adapter然后更新Adapter里面的DatLista数据，convert的时候再调用设置的DataList数据，这样又无法用convert里面的obj数据

**Comment by CymChad** [comment]
这样又无法用convert里面的obj数据？

**Comment by solomon2** [comment]
protected void convert(Holder holder , Obj obj) 

就是这个item的数据，只能用dataList.get(i).....来使用

还有notifyItemRangeChanged我刚试了 好像还是有问题，  他会更新我指定的，第一个完整显示的item和这个item下面显示出的的几个item

**Comment by CymChad** [comment]
notifyItemRangeChanged 有重载函数，你可以设置更新范围。

**Comment by solomon2** [comment]
老大我尝试后这样监听并更新的方式可以实现，不过每次item更新的时候都会有明显的闪烁一下，是不是layout的重新加载造成的喃？

```
    public TabViewNewAdapter(List<ScenicListData> data) {
        super(  data );
        addItemType(ScenicListData.TYPE_1, R.layout.list_item_card_main);
        addItemType(ScenicListData.TYPE_2, R.layout.list_item_card_main);
        panoOptions = new VrPanoramaView.Options();
        panoOptions.inputType = VrPanoramaView.Options.TYPE_MONO;
    }

```

我看了代码addItemType好像没有设置 只加载一个layout的方法

**Comment by CymChad** [comment]
恩 是的 更新会闪烁一下。我觉得你是不是可以把两个布局放在一个item里面，这样显示隐藏切换应该不会闪烁。

**Comment by solomon2** [comment]
是的，我加载2个相同layout， 就是切换显示和隐藏控件，还是会闪烁， 能不能只加载一个layout喃。

**Comment by CymChad** [comment]
这是没有找到对应的resId

**Comment by solomon2** [comment]
是的，就是不能只加载一个layout

**Comment by CymChad** [comment]
闪烁问题是Recycler自带的问题，不是这个框架所导致的。

**Comment by solomon2** [comment]
如果BaseMultiItemQuickAdapter 只加载一个layout可以解决不喃，我看了源码不知道怎么改。

**Comment by CymChad** [comment]
只加载一个layout，就没必要用BaseMultiItemQuickAdapter

**Comment by solomon2** [comment]
我用普通RecyclerView  的方式，滚动时更新， 是不会有闪烁的。

**Comment by CymChad** [comment]
你开启了动画吗？

**Comment by solomon2** [comment]
但是要多个ItemViewType区分的嘛。 框架内没法重写Adapter的 getItemViewType。

开启了的。只加载一次。

**Comment by CymChad** [comment]
你关掉动画看一下，有没有闪烁。

**Comment by CymChad** [comment]
因为notifyItemRangeChanged这个函数他是系统自带的API所以我们无法改变它的行为。

**Comment by solomon2** [comment]
关掉了，试试了下， 还是会闪烁

**Comment by CymChad** [comment]
你用原生的改变itemtype切换布局，局部刷新不会闪烁？

**Comment by solomon2** [comment]
是的， 原生或者BaseQuickAdapter 都行，都是Adapter里面重写getItemViewType来判断分类，然后滚动时监听设置分类，Adapter里面通过显示和隐藏来更改布局。

只是BaseQuickAdapter里面重写了getItemViewType  就不能使用loadmore

**Comment by CymChad** [comment]
如果你用BaseQuickAdapter你可以重写getDefItemViewType 在这里面加你的类型，这样就可以有loadmore和其他的功能。

**Comment by solomon2** [comment]
太棒了，这样可以，我怎么就没想到。 绕了好大弯路！
感谢老大。

**Comment by CymChad** [comment]
感谢使用，如果你觉得这个库还不错，你可以分享给你身边的开发者朋友们。

**Comment by solomon2** [comment]
好的 好的，感谢您的分享。
