### ISSUE TITLE
BaseNodeProvider在展开缩放会卡

### ISSUE THREAD

**Issue by hlzIrving** [CymChad/BaseRecyclerViewAdapterHelper#3205]
getAdapter().expandOrCollapse(position, true, true, NodeTreeAdapter.EXPAND_COLLAPSE_PAYLOAD);
出现卡在展开缩放

**Comment by kcjian** [comment]
getAdapter().expandOrCollapse(position, true)
我的展开不会卡，收起会卡

**Comment by hlzIrving** [comment]
> 版本3.0.2
> getAdapter().expandOrCollapse(position, true)
> 我的展开不会卡，收起会卡

好吧~~~我还以为就我一个人

**Comment by kcjian** [comment]
版本3.0.4
getAdapter().expandOrCollapse(position, true)
收起闪退
`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBaseViewHolder{e3e7543 position=2 id=-1, oldPos=2, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} `

**Comment by hlzIrving** [comment]
> 版本3.0.4
> getAdapter().expandOrCollapse(position, true)
> 收起闪退
> `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBaseViewHolder{e3e7543 position=2 id=-1, oldPos=2, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} `

尤其是小米的手机 其他厂都是ok的

**Comment by hlzIrving** [comment]
> 版本3.0.4
> getAdapter().expandOrCollapse(position, true)
> 收起闪退
> `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBaseViewHolder{e3e7543 position=2 id=-1, oldPos=2, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} `

你是数组越界了 大兄弟

**Comment by kcjian** [comment]
`public class FirstNodeProvider extends BaseNodeProvider {

    @Override
    public int getItemViewType() {
        return 0;
    }

    @Override
    public int getLayoutId() {
        return R.layout.list_item_faq_1;
    }

    @Override
    public void convert(@NotNull BaseViewHolder helper, @NotNull BaseNode data) {
        FirstNode entity = (FirstNode) data;
        helper.setText(R.id.name, entity.getTitle())
            .setImageResource(R.id.ivOpenClose,entity.isExpanded()?R.drawable.ic_up:R.drawable.ic_down);
    }

    @Override
    public void onClick(@NotNull BaseViewHolder helper, @NotNull View view, BaseNode data, int position) {
        Objects.requireNonNull(getAdapter()).expandOrCollapse(position,true);
    }
}`
我没有去控制这个啊，就是`expandOrCollapse(position,true)`了一下，3.0.2收起卡，3.0.4直接闪退了

**Comment by hlzIrving** [comment]
> getItemViewType

getItemViewType这个玩意你要设置下  你先看看demo··

**Comment by kcjian** [comment]
这个设置了，是我数据的问题，一级item都加了同一个二级list

用了`expandOrCollapse(position, true, true, NodeAdapter.EXPAND_COLLAPSE_PAYLOAD);`

但是还是会闪烁，

我总共两个一级item，当他们都展开时，收起第一个不会闪烁，

当第二个为收起状态，收起第一个会闪烁

**Comment by fail572872916** [comment]
> 这个设置了，是我数据的问题，一级item都加了同一个二级list
> 
> 用了`expandOrCollapse(position, true, true, NodeAdapter.EXPAND_COLLAPSE_PAYLOAD);`
> 
> 但是还是会闪烁，
> 
> 我总共两个一级item，当他们都展开时，收起第一个不会闪烁，
> 
> 当第二个为收起状态，收起第一个会闪烁
> 
> 而且没有触发这个
> @override
> public void convert(@NotNull BaseViewHolder helper, @NotNull BaseNode data) {
> FirstNode entity = (FirstNode) data;
> helper.setText(R.id.name, entity.getTitle())
> .setImageResource(R.id.ivOpenClose,entity.isExpanded()?R.drawable.ic_up:R.drawable.ic_down);
> }
> 用来改变展开收起的小图标
的确是同一个数据的问题，我搞了一上午，快怀疑人生了

**Comment by Jerrychurui** [comment]
老哥，怎么解决的
