### ISSUE TITLE
Custom ViewHolder

### ISSUE THREAD

**Issue by jeanpimentel** [CymChad/BaseRecyclerViewAdapterHelper#321]
How can I use my custom ViewHolder class?

I have many things to do, with many types, so doing all the things in convert method in adapter would be very bad, with many lines.

Instead of addItemType(int type, @LayoutRes int layoutResId), can I do a method like addItemType(int type, <T extends BaseViewHolder> myCustomClass)? How?

Is there an example?

**Comment by CymChad** [comment]
I'm sorry don't support that at present.
