### ISSUE TITLE
helper.setText(R.id.tv_title,R.string.xxx)返回是?类型

### ISSUE THREAD

**Issue by JamesLi2013** [CymChad/BaseRecyclerViewAdapterHelper#3216]
3.0.4版本
看了源代码 BaseViewHolder
open fun setText(@IdRes viewId: Int, @StringRes strId: Int): BaseViewHolder? {
        getView<TextView>(viewId).setText(strId)
        return this
    }

helper.setText(R.id.tv_title,R.string.xxx)返回是?类型,导致连续写的时候,后面都要带?或者!!才能解决了
这里不应该返回?类型,应去掉

**Comment by jianwuch** [comment]
看来不建议使用这个方法，可以使用这个方法setText(@IdRes viewId: Int, value: CharSequence?)

**Comment by jianwuch** [comment]
3年了，你终于关了，你知道这三年我是怎么过来的吗？哈哈
