### ISSUE TITLE
关于BaseViewHolder的问题

### ISSUE THREAD

**Issue by ChenZiqiang** [CymChad/BaseRecyclerViewAdapterHelper#3217]
自定义了一个viewholder并继承了  com.chad.library.adapter.base.viewholder.BaseViewHolder，
public class CollectionHolder extends BaseViewHolder
之后自定义了adapt并使用
 public class CollectionAdapter extends BaseQuickAdapter<CollectBean, CollectionHolder>
然后崩溃了 java.lang.ClassCastException: com.chad.library.adapter.base.viewholder.BaseViewHolder cannot be cast to com.wlwl.food.business.CollectRecordsActivity$CollectionHolder
同样的写法其他模块可以用，就这个类会崩溃。
现在是一脸懵逼中，求解答。

**Comment by aids61517** [comment]
繼承 BaseViewHolder 的 class 不能被混肴，在 proguard-rules.pro 加上這行
-keep class ** extends com.chad.library.adapter.base.BaseViewHolder { *; }

**Comment by yuanzaiyuanfang** [comment]
楼上正解
