### ISSUE TITLE
rv嵌套rv   使用的是多布局的方式实现

### ISSUE THREAD

**Issue by zhaichuankai** [CymChad/BaseRecyclerViewAdapterHelper#3218]
问题：每次刷新最外层的多布局适配器，里面的列表item的高度都会变高，我高度写死了的

**Comment by FYSong** [comment]
item相关布局代码列一下出来？

**Comment by zhaichuankai** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <com.flyco.roundview.RoundTextView
        android:id="@+id/tv_tag"
        android:layout_width="wrap_content"
        android:layout_height="18dp"
        android:ellipsize="end"
        android:gravity="center"
        android:maxLength="3"
        android:paddingLeft="8dp"
        android:paddingRight="8dp"
        android:text="单人播"
        android:textColor="#ff999999"
        android:textSize="12sp"
        app:rv_backgroundColor="#F1F1F1"
        app:rv_cornerRadius="5dp" />

</LinearLayout>
