### ISSUE TITLE
使用MultiItem 加 头部的时候，点击事件有一些使用上有些问题。

### ISSUE THREAD

**Issue by lijunguan** [CymChad/BaseRecyclerViewAdapterHelper#322]
需求中要使用粘性头部，所以使用了PinnedSectionItemDecoration，（TYPE_HEADER，TYPE_DATA两个type），   并且添加了一个头部，然后点击事件中根据下标得到type类型，发现了错乱问题。   看源码发现了问题，是因为添加了头部导致的，简单修改后暂时没有问题了，代码如下。  觉得这点可以优化， 不然使用很容易出错，还没有更深入研究，不知道在更复杂的情况下，我这样写会有问题不会。

 getRecyclerView().addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void SimpleOnItemClick(BaseQuickAdapter holder, View view, int index) {
                //点击事件的 index 已经减去了头部的数量,但是getItemViewType(int position)，的position默认是带有头部的
                //所以如果adpter添加例如头部， 在点击事件中 直接使用holder.getItemViewType(index) 会导致获取的type异常
                int itemType = holder.getItemViewType(index + holder.getHeaderLayoutCount());
                if (itemType == SettlementAdapter.TYPE_DATA) {
                    SettlementEntity item = mAdapter.getItem(index);
                    RunningOrderDetailActivity.startAction(mActivity, item.getData().getOrderID());
                }
            }
        });

**Comment by CymChad** [comment]
恩，好的，谢谢提醒。

**Comment by CymChad** [comment]
恩 是的，getItemViewType(int position) 无法处理原始API的postion

**Comment by CymChad** [comment]
headView也是一个item。所以需要开发者处理。

**Comment by gfeng567** [comment]
添加头部后的列表刷新某个位置的item也是需要position加上头部的数量。
