### ISSUE TITLE
BaseItemBinder中的onChildClick 监听不到 添加的第一条数据

### ISSUE THREAD

**Issue by xnc916** [CymChad/BaseRecyclerViewAdapterHelper#3223]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by 1046964106** [comment]
我也是无法的点击第一个

**Comment by aj2722465** [comment]
+1我也是无法的点击第一个

**Comment by troyccc** [comment]
+1

**Comment by troyccc** [comment]
知道什么原因了吗 大家

**Comment by zimq** [comment]
> 知道什么原因了吗 大家

add child listener不要写在covert里，这样写只有第一个covert后监听才会生效

**Comment by troyccc** [comment]
> > 知道什么原因了吗 大家
> 
> add child listener不要写在covert里，这样写只有第一个covert后监听才会生效

谢谢 解决啦！

**Comment by wangzhankai** [comment]
> > > 知道什么原因了吗大家
> > 
> > 
> > 添加子听众不要写在covert里，这样写只有第一个covert后监听才会发挥
> 
> 谢谢解决啦！

>不在covert中监听，要在哪监听呀？用的新版本addChildClickViewIds方法

**Comment by troyccc** [comment]
> > > > 知道什么原因了吗大家
> > > 
> > > 
> > > 添加子听众不要写在covert里，这样写只有第一个covert后监听才会发挥
> > 
> > 
> > 谢谢解决啦！
> 
> > 不在covert中监听，要在哪监听呀？用的新版本addChildClickViewIds方法

写在构造方法里，给的demo也是这样的

**Comment by wangzhankai** [comment]
改好了，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CymChad/BaseRecyclerViewAdapterHelper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月14日(星期二) 上午9:13
收件人:&nbsp;"CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;;
抄送:&nbsp;"飘渺星云"<1139130828@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [CymChad/BaseRecyclerViewAdapterHelper] BaseItemBinder中的onChildClick 监听不到 添加的第一条数据 (#3223)





     
知道什么原因了吗大家
  
添加子听众不要写在covert里，这样写只有第一个covert后监听才会发挥
  
谢谢解决啦！
   
不在covert中监听，要在哪监听呀？用的新版本addChildClickViewIds方法
   
写在构造方法里，给的demo也是这样的
