### ISSUE TITLE
First item (position 0) item child click is not listening.

### ISSUE THREAD

**Issue by jbrathod1312** [CymChad/BaseRecyclerViewAdapterHelper#3227]
I have added in adapter addChildClickViewIds(R.id.plusbtn,R.id.minusbtn,R.id.prodqty); 
.
The first item child clicks not working on position 0 item. when i click on any child of position 0 ite does nothing. rest position child working properly.

**Comment by SheepYang1993** [comment]
i have same problem too

**Comment by SheepYang1993** [comment]
fix in #3108

**Comment by jbrathod1312** [comment]
i solved by moving   addChildClickViewIds(); to adapter constructor instead of convet method.
