### ISSUE TITLE
关于结合第三方下拉刷新库

### ISSUE THREAD

**Issue by 13588823551** [CymChad/BaseRecyclerViewAdapterHelper#323]
你好，请问可以结合https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh 这个库写一个demo吗？
我在刷新完成时调用mAdapter.notifyItemChanged(0);方法，会报错
 java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{b7eeb1 position=0 id=-1, oldPos=-1, pLpos:-1}

代码如下
@Override
    public void refreshSuccess(final List<Data> data) {
        mRecyclerView.post(new Runnable() {
            @Override
            public void run() {
                    // 测试setEmptyView，清空数据
                    data.clear();
             
                if (data.size() == 0) {
                    if(mNoDataView == null) {
                        mNoDataView = getActivity().getLayoutInflater().inflate(R.layout.list_no_data, (ViewGroup) mRecyclerView.getParent(), false);
                        mAdapter.setEmptyView(mNoDataView);
                    } else {
                        mAdapter.notifyItemChanged(0);
                    }
                } else {
                    mAdapter.setNewData(data);
                }
                mAdapter.removeAllFooterView();
                ptrClassicFrameLayout.refreshComplete();
            }

        });

    }

**Comment by CymChad** [comment]
mAdapter.notifyItemChanged(0);为了什么？

**Comment by 13588823551** [comment]
为了让emptyView和普通的adapter界面切换。
需求是这样的：一开始加载数据没有加载到，mAdapter.setEmptyView(nodataView);  这个nodataView界面上有个重新加载的按钮，然后再次加载时有数据了，mAdapter.setNewData(data); 
然后在某次刷新后又没有数据，我要再次显示emptyView，所以我做了mAdapter.notifyItemChanged(0);这个操作。




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年9月13日(星期二) 中午1:45
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "Stars"<231885251@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 关于结合第三方下拉刷新库 (#323)




mAdapter.notifyItemChanged(0);为了什么？

**Comment by 13588823551** [comment]
为了让emptyView和普通的adapter界面切换。
需求是这样的：一开始加载数据没有加载到，mAdapter.setEmptyView(nodataView);  这个nodataView界面上有个重新加载的按钮，然后再次加载时有数据了，mAdapter.setNewData(data);
然后在某次刷新后又没有数据，我要再次显示emptyView，所以我做了mAdapter.notifyItemChanged(0);这个操作。

**Comment by CymChad** [comment]
不需要，如果没有数据就会自动显示emptyView，不需要重复set和刷新。

**Comment by 13588823551** [comment]
谢谢

**Comment by CymChad** [comment]
感谢你的使用，如果觉得这个库还不错，可以分享给其他开发者使用。

**Comment by 13588823551** [comment]
有个新问题，我使用粘性标签，PinnedSectionItemDecoration这个库，然后setEmptyView()后，顶部的标签还在，adapter.removeAllHeaderView()也没有用

**Comment by CymChad** [comment]
我帮你联系一下，PinnedSectionItemDecoration这个库的作者

**Comment by 13588823551** [comment]
其实我也联系了，但他好像在忙，那我再等等看

**Comment by 23hp** [comment]
我的项目也有下拉刷新的需求
