### ISSUE TITLE
RecyclerView嵌套的的时候，内层Adapter点击事件怎么提高到Activity里面去？

### ISSUE THREAD

**Issue by wjbd** [CymChad/BaseRecyclerViewAdapterHelper#3230]
任务列表里面嵌套了订单列表。订单列表的点击事件，怎么能提高到Activity里面去呢？
目前实现的方式是两层RecyclerView嵌套实现的

**Comment by wjbd** [comment]
目前我使用了
`
adapter.addChildClickViewIds(R.id.btn_item_order_delivery)
adapter.setOnItemChildClickListener(object : OnItemChildClickListener {}
`
这种方式获取不到点击事件

**Comment by wjbd** [comment]
R.id.btn_item_order_delivery是订单列表的提交按钮，怎么获取点击事件呢？

**Comment by jdhdevelop** [comment]
套了两层？一层可以。两层还不知道呢。

**Comment by GitHubKlod** [comment]
同问

**Comment by wjbd** [comment]
> 同问

越写越多以后，就不会这么写了，嵌套两层是能够达成效果，但是不够优雅，框架也达不到相应的需求。
目前来说我是通过多布局adapter来完善这个需求。
同时不建议使用嵌套多个recyclerview。
