### ISSUE TITLE
给作者2.x升级3.x兼容建议

### ISSUE THREAD

**Issue by wystyle1** [CymChad/BaseRecyclerViewAdapterHelper#3231]
原因：
1、2.x版本使用面广，2.x的api和实现思路有的较3.x差距较大
2、如果2.x直接升级3.x，势必会造成开发者做大量的代码调整，升级代价太大
3、3.x的很多方式可以理解为新的实现思路，包括部分api的改动

建议：
建议作者，修改包名，算作两个库，能够使2.x与3.x包共存，这样开发者在升级过程中几乎2.x老的代码不会影响，新的功能使用3.x库的api, 这样对开发者来说是友好的

**Comment by zhuangzeqin** [comment]
楼上的建议是非常好的； 赞同！出现大面积的改动也是不敢升级的

**Comment by Munccccc** [comment]
用的28.0没升级androidx又想用databing就要down下来改

**Comment by lhj1079947827** [comment]
非常好的建议，我的也是2x不敢升级3x升级太大了，改动太多

**Comment by Joslyn-Chen** [comment]
非常好的建议，改动太大了

**Comment by axepudding** [comment]
试着升级到3x，但是发现改动太大，目前项目又赶。。所以还是放弃升级

**Comment by liyujiang-gzu** [comment]
> 试着升级到3x，但是发现改动太大，目前项目又赶。。所以还是放弃升级

的确，我也试着升级到3.x，改了一会发现改动的地方太多了，果断放弃升级。

**Comment by zjxuzhj** [comment]
改了好久。。还不能用。。

**Comment by z-chu** [comment]
升级3.0 ，LoadMore不好统一封装，换回原来的了，很多地方可以做兼容2.0的地方硬改了，比如setGone、mContext这些。对比2.0没实质提升，不推荐升级，没有必要给自己找坑踩。

**Comment by liyujiang-gzu** [comment]
> 对比2.0没实质提升

是怎么对比的？既然是改了主版本号，说明重构很大。

**Comment by itsnicerdx** [comment]
赞同此建议

**Comment by kingslou** [comment]
> 试着升级到3x，但是发现改动太大，目前项目又赶。。所以还是放弃升级

为啥要升级呢 2.x 其实蛮稳定的了，就算你项目用kt 这个用java库也没有什么影响，而且我看3.x的一些 代替2.x使用方法跟达成的效果是不一致的，替换升级要谨慎

**Comment by lan2000** [comment]
赞同此建议

**Comment by Tiannuo** [comment]
+1

**Comment by Xabws** [comment]
改了一半放弃用最新版了，项目用recycleview的地方太多了，要改的话需要耗费大量的时间，开发者升级时也要考虑兼容问题

**Comment by TomGarden** [comment]
注意到作者没有将新版本用新包名
关于这个问题可想到的操作是(我现在就是在瞎说哈 , 我没有做过尝试)
1. 自己将 2.x 的分支fork 下然后做包名的修正
    - 这需要在自己的项目中将 import 包名做全部做一个修正
    - 改包名相对简单 replaseAll 即可
2. 将 3.x 引入

上述操作可能造成的问题是资源文件重名, 可能会需要花时间重命名下 , 这个是个力气活儿

**再次 : 我没有针对本库做过上述操作 , 但是对其他的库做过**
