### ISSUE TITLE
expandable all 

### ISSUE THREAD

**Issue by JakeWang123** [CymChad/BaseRecyclerViewAdapterHelper#324]
使用ExpandableItemAdapter 默认可以全部展开嘛？

**Comment by elfman** [comment]
目前不行，你可以使用`public int expand(int position, boolean animate, boolean shouldNotify)`这个方法逐个展开子项，然后调用`notifyItemRangeInserted`来插入所有子项。
或者等我加个expandAll方法

**Comment by JakeWang123** [comment]
notifyItemRangeInserted不可以在protected void convert(final BaseViewHolder baseViewHolder, MultiItemEntity multiItemEntity)这个方法里面调用的

**Comment by elfman** [comment]
出现了什么错误

**Comment by JakeWang123** [comment]
ava.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling

**Comment by elfman** [comment]
你这是还处于初始化阶段吧，即RecyclerView还没在屏幕上显示，那就不需要调用`notifyItemRangeInserted`，这个是刷新数据用的

**Comment by JakeWang123** [comment]
我现在想在setNewData后自动展开，这个该怎么做

**Comment by elfman** [comment]
`setNewData`后对需要展开的项调用`expand(position, false, false)`

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.4'

**Comment by CymChad** [comment]
Add expandAll method 具体使用方式，看demo。
