### ISSUE TITLE
进入界面时有网,进入界面后下拉加载更多时如果调用mQuickAdapter.loadComplete();则除非刷新下否则不能加载;

### ISSUE THREAD

**Issue by asdf19910719** [CymChad/BaseRecyclerViewAdapterHelper#325]
这算一点用户体验吧,想问下大神你关闭下拉记载更多效果只有loadComplete方法么,找半天没找到其他的只关闭效果但是可以下次继续下拉的方法...可以给个提示么...标题没说清楚,进入界面时有网,ui出来了,然后没网,再下拉的话,只能永久关闭下拉

**Comment by CymChad** [comment]
有准备的错误尾部方法，封装了开启的代码，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD

**Comment by CymChad** [comment]
showLoadMoreFailedView

**Comment by asdf19910719** [comment]
感谢大神啦
