### ISSUE TITLE
在多布局中使用databinding是这样获取吗？

### ISSUE THREAD

**Issue by fansangg** [CymChad/BaseRecyclerViewAdapterHelper#3255]
```
class CommunityAdapter : BaseMultiItemQuickAdapter<CommunityBean, BaseViewHolder>() {

    init {
        addItemType(CommunityBean.MOMENTS, R.layout.item_discover_post)
        addItemType(CommunityBean.ARTICLE, R.layout.item_discover_article)
    }

    override fun convert(holder: BaseViewHolder, item: CommunityBean) {
        if (item.itemType == CommunityBean.ARTICLE) {
            val articleBinding = DataBindingUtil.bind<ItemDiscoverArticleBinding>(holder.itemView)
            articleBinding?.viewmodel = item
            articleBinding?.executePendingBindings()
        } else {
            val postBinding = DataBindingUtil.bind<ItemDiscoverPostBinding>(holder.itemView)
            postBinding?.viewmodel = item
            postBinding?.executePendingBindings()
        }
    }

}
```

这样可以，但不知道是否为正确食用方式，demo中好像没找到多布局使用databinding的地方

**Comment by RDSunhy** [comment]
请问 最后您是怎么在BaseMultiItemQuickAdapter中使用databinding的?

**Comment by fansangg** [comment]
> 请问 最后您是怎么在BaseMultiItemQuickAdapter中使用databinding的?

val articleBinding = DataBindingUtil.bind<ItemDiscoverArticleBinding>(holder.itemView) 就是这样获取的

**Comment by RDSunhy** [comment]
> > 请问 最后您是怎么在BaseMultiItemQuickAdapter中使用databinding的?
> 
> val articleBinding = DataBindingUtil.bind(holder.itemView) 就是这样获取的

多谢指教!

**Comment by xiaoxing1992** [comment]
> > > 请问 最后您是怎么在BaseMultiItemQuickAdapter中使用databinding的?
> > 
> > 
> > val articleBinding = DataBindingUtil.bind(holder.itemView) 就是这样获取的
> 
> 多谢指教!

class KaiyanRecommendAdapter  : BaseMultiItemQuickAdapter<VideItem, BaseDataBindingHolder<*>>() {

    init {
        addItemType(1, R.layout.item_kz_header_home)
        addItemType(2, R.layout.item_kz_home)
    }

    override fun convert(holder: BaseDataBindingHolder<*>, item: VideItem) {
        when(holder.itemViewType){
            1->{
                var myholder  = holder.dataBinding as ItemKzHeaderHomeBinding

                myholder.executePendingBindings()
            }
            2->{
                var myholder  = holder.dataBinding as ItemKzHomeBinding
                myholder.videItem = item
                myholder.executePendingBindings()
            }
        }
    }
}
我是这么理解的
