### ISSUE TITLE
adapter item只有一个子view设置addChildClickViewIds的bug

### ISSUE THREAD

**Issue by wangshaolei** [CymChad/BaseRecyclerViewAdapterHelper#3258]
adapter item 只有一个子view设置addChildClickViewIds时，
如：
addChildClickViewIds(R.id.tv_do_rent)

第一个item 没有绑定上事件，点击事件view无响应。第二个及以后view正常。

**Comment by DaveBoy** [comment]
我也遇到了  我一直以为是我的点击范围没点准呢。。。我的天

**Comment by DaveBoy** [comment]
> adapter item 只有一个子view设置addChildClickViewIds时，
> 如：
> addChildClickViewIds(R.id.tv_do_rent)
> 
> 第一个item 没有绑定上事件，点击事件view无响应。第二个及以后view正常。

https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/3108 这里有解决方案

**Comment by wangshaolei** [comment]
> > adapter item 只有一个子view设置addChildClickViewIds时，
> > 如：
> > addChildClickViewIds(R.id.tv_do_rent)
> > 第一个item 没有绑定上事件，点击事件view无响应。第二个及以后view正常。
> 
> #3108 这里有解决方案

@DaveBoy thanks
