### ISSUE TITLE
adapter.getItem()和adapte.getData()问题

### ISSUE THREAD

**Issue by patrickning** [CymChad/BaseRecyclerViewAdapterHelper#3266]
2.x版本里，这两个方法可以返回自己指定的实体类T，现在3.x版本不行了，返回是Object和没有泛型的List，需要强转。我使用Java语言。

**Comment by long216** [comment]
addHeaderView
addFooterView
不能与
setEmptyView
共存
怎么解决?

**Comment by patrickning** [comment]
这个问题找到了，应该用自己定义的Adapter对象的getItem，这样返回是T，不要使用lamda表达式里的adapter
