### ISSUE TITLE
Expandable相关功能

### ISSUE THREAD

**Issue by JakeWang123** [CymChad/BaseRecyclerViewAdapterHelper#327]
1.Expandable如何添加ItemClick 事件；

2.ExpandableItemAdapter adapter = new ExpandableItemAdapter(list);

        View headerView = getView();
        adapter.addHeaderView(headerView);

        View footerView = getView();
        adapter.addFooterView(footerView);

        mRecyclerView.setAdapter(adapter);

        adapter.expandAll(3, true);这里的参数3是什么意思

**Comment by elfman** [comment]
1. 参考我在demo里的代码，在bind view时绑定
2. 参数3是指我想让列表的第四项在初始化时就展开，仅作示范

**Comment by JakeWang123** [comment]
在两级列表中，以及列表中如果有两项，如果以及列表的第二项没有子项的话，expand所有函数就不起作用

**Comment by JakeWang123** [comment]
List<MultiItemEntity> multiItemEntityList = new ArrayList<>();
        MultiJobLevel0Entity multiJobLevel0Entity = new MultiJobLevel0Entity();
        Resources resources =presenterView.context().getResources();
        multiJobLevel0Entity.setTitle(resources.getString(R.string.job_serving));
        MultiJobLevel1Entity multiJobLevel1Entity;
        if(servingList!=null && servingList.size()>0){
            for(JobListItem jobListItem:servingList){
                multiJobLevel1Entity = new MultiJobLevel1Entity();
                multiJobLevel1Entity.setJobListItem(jobListItem);
                multiJobLevel0Entity.addSubItem(multiJobLevel1Entity);
            }

        }
        multiItemEntityList.add(multiJobLevel0Entity);
        multiJobLevel0Entity = new MultiJobLevel0Entity();
        multiJobLevel0Entity.setTitle(resources.getString(R.string.job_queuing));
        if(queueList!=null && queueList.size()>0){
            int pos=0;
            for(JobListItem jobListItem:queueList){
                jobListItem.setPosition(pos++);
                multiJobLevel1Entity = new MultiJobLevel1Entity();
                multiJobLevel1Entity.setJobListItem(jobListItem);
                multiJobLevel0Entity.addSubItem(multiJobLevel1Entity);
            }

        }
        multiItemEntityList.add(multiJobLevel0Entity);


如果上面的queueList为空那么在一级列表中任何一项调用expand不起作用

**Comment by elfman** [comment]
1. 你说的“expand所有”是指“expandAll”？
2. 我看不出你的“queueList”从哪里来的，起什么作用
PS：你这代码排版能不能弄好点，我看着很吃力
