### ISSUE TITLE
3.0.4版本kotlin 如何为item子view添加点击事件

### ISSUE THREAD

**Issue by tytreal** [CymChad/BaseRecyclerViewAdapterHelper#3270]
实现OnItemChildClickListener中的方法时，总是报下面的错误
override fun onItemChildClick(adapter: BaseQuickAdapter<[ERROR: Unresolved java class

**Comment by plain-dev** [comment]
Sample code

```kotlin
adapter.apply {
	addChildClickViewIds(R.id.title)
	setOnItemChildClickListener { _, v, p ->
		when (v.id) {
			R.id.title -> {
				// do something
			}
		}
	}
}
```

**Comment by tytreal** [comment]
> Sample code
> 
> ```kotlin
> adapter.apply {
> 	addChildClickViewIds(R.id.title)
> 	setOnItemChildClickListener { _, v, p ->
> 		when (v.id) {
> 			R.id.title -> {
> 				// do something
> 			}
> 		}
> 	}
> }
> ```

请问哪里有brvah新版本的文档吗，一直找不到

**Comment by plain-dev** [comment]
就在 [README](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/readme/0-BaseRecyclerViewAdapterHelper.md) 中

**Comment by tytreal** [comment]
> 就在 [README](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/readme/0-BaseRecyclerViewAdapterHelper.md) 中
但是没有kotlin版本的，是还没补全吗

**Comment by fansangg** [comment]
> Sample code
> 
> ```kotlin
> adapter.apply {
> 	addChildClickViewIds(R.id.title)
> 	setOnItemChildClickListener { _, v, p ->
> 		when (v.id) {
> 			R.id.title -> {
> 				// do something
> 			}
> 		}
> 	}
> }
> ```


我这边 v.id 一直是 -1 求解？

**Comment by DaveBoy** [comment]
> > Sample code
> > ```kotlin
> > adapter.apply {
> > 	addChildClickViewIds(R.id.title)
> > 	setOnItemChildClickListener { _, v, p ->
> > 		when (v.id) {
> > 			R.id.title -> {
> > 				// do something
> > 			}
> > 		}
> > 	}
> > }
> > ```
> 
> 我这边 v.id 一直是 -1 求解？

你debug看一下呢。。。

**Comment by plain-dev** [comment]
@tytreal 貌似没有kt版本，不过不影响

**Comment by fansangg** [comment]
> > > Sample code
> > > ```kotlin
> > > adapter.apply {
> > > 	addChildClickViewIds(R.id.title)
> > > 	setOnItemChildClickListener { _, v, p ->
> > > 		when (v.id) {
> > > 			R.id.title -> {
> > > 				// do something
> > > 			}
> > > 		}
> > > 	}
> > > }
> > > ```
> > 
> > 
> > 我这边 v.id 一直是 -1 求解？
> 
> 你debug看一下呢。。。

嗯，是我防止快速二次点击的拓展函数写成了onitemclick

**Comment by tytreal** [comment]
@plain-dev 好的，感谢
