### ISSUE TITLE
设置addChildClickViewIds()后，第一项的点击事件不起作用，其他项时好的

### ISSUE THREAD

**Issue by vavaJ** [CymChad/BaseRecyclerViewAdapterHelper#3274]
class MenuFiveProvider : BaseItemProvider<HomeProviderBean>() {
    override val itemViewType: Int
        get() = HomeMultiItemAdapter.MENU_FIVE
    override val layoutId: Int
        get() = R.layout.item_home_five_menu

    override fun convert(helper: BaseViewHolder, item: HomeProviderBean) {
        addChildClickViewIds(R.id.tv_first)
    }

    override fun onClick(
        helper: BaseViewHolder,
        view: View,
        data: HomeProviderBean,
        position: Int
    ) {
        ToastUtil.instance.showShortToast("Click: $position")
    }

    override fun onChildClick(
        helper: BaseViewHolder,
        view: View,
        data: HomeProviderBean,
        position: Int
    ) {
        when (view.id) {
            R.id.tv_first -> {
                ToastUtil.instance.showShortToast("onChildClick: $position")
            }
        }
    }
}

**Comment by vavaJ** [comment]
addChildClickViewIds()注册在创建的时候

**Comment by Mrliandroid** [comment]
那这个到底是怎么解决的
