### ISSUE TITLE
nodeRemoveData数组越界问题

### ISSUE THREAD

**Issue by Anonywp** [CymChad/BaseRecyclerViewAdapterHelper#3277]
在BaseNodeAdapter的removeNodesAt中
在没有footer 的情况下，如果要删除的node是最后一个元素，那么再去取footer会越界

        // 移除node自己
        this.data.removeAt(position)
        removeCount += 1
        // 这里会越界
        val node = this.data[position]
        // 移除脚部
        if (node is NodeFooterImp && node.footerNode != null) {
            this.data.removeAt(position)
            removeCount += 1
        }

**Comment by 932707629** [comment]
同上  我也遇到了这种情况

**Comment by Anonywp** [comment]
自己修改源码打包吧，加个判断即可

**Comment by JiayuanChan** [comment]
同上 我也遇到了这种情况

**Comment by limuyang2** [comment]
更新最新版
