### ISSUE TITLE
第一次加载数据错误问题

### ISSUE THREAD

**Issue by romantiskt** [CymChad/BaseRecyclerViewAdapterHelper#329]
当我第一次加载数据错误,调起showLoadMoreFailedView()是报如下错误

`java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup)' on a null object reference
                                                                         at com.chad.library.adapter.base.BaseQuickAdapter.showLoadMoreFailedView(BaseQuickAdapter.java:744)`

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/253

**Comment by CymChad** [comment]
和上面的问题一样，你可以查看一下。
