### ISSUE TITLE
mAdapter.addData(list);之后展示出来的item的下标是乱的

### ISSUE THREAD

**Issue by woniu0936** [CymChad/BaseRecyclerViewAdapterHelper#330]
我的情况是：一页20条数据，做了一个三列的展示（用的StaggeredGridLayoutManager），然后到底之后加载下一页，这时候发现添加在后面的item的下标顺序不对（下标获取holder.getAdapterPosition()）,展示的结果是18，19，21，22，20，23.。。。。（我把holder.getAdapterPosition()的值显示在了每个item上面看的）

**Comment by woniu0936** [comment]
![wechatimg1](https://cloud.githubusercontent.com/assets/7264285/18510055/92358efc-7aae-11e6-8df4-df8240fc9376.png)

**Comment by CymChad** [comment]
收到

**Comment by woniu0936** [comment]
谢谢，麻烦了

**Comment by CymChad** [comment]
没事，应该的，感谢你的使用。

**Comment by CymChad** [comment]
我按照你的描述测试过demo，没发现你说的的问题。有个疑问
![image](https://cloud.githubusercontent.com/assets/7698209/18559245/fdb04f78-7ba8-11e6-85c1-7a9da27b76b0.png)
为什么这张图的19，21，22 这块没有分割线？

**Comment by CymChad** [comment]
贴一下代码。

**Comment by woniu0936** [comment]
public class FindVideoAdapter extends BaseQuickAdapter<Feed> {

    private RelativeLayout.LayoutParams mLayoutParams;
    private Context mContext;

    public FindVideoAdapter(Context context) {
        super(R.layout.item_find_video, null);
        mLayoutParams = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
//        mLayoutParams.setMargins(DisplayUtil.dip2px(context, 1), DisplayUtil.dip2px(context, 1), DisplayUtil.dip2px(context, 1), 0);
        mContext = context;
    }

    @Override
    protected void convert(BaseViewHolder holder, Feed feed) {

        LogUtil.d("----position-----" + holder.getAdapterPosition() + "----" + (2 == holder.getAdapterPosition() % 3));

        if (2 == holder.getAdapterPosition() % 3) {
            mLayoutParams.setMargins(DisplayUtil.dip2px(mContext, 1), DisplayUtil.dip2px(mContext, 1), DisplayUtil.dip2px(mContext, 1), 0);
        } else {
            mLayoutParams.setMargins(0, DisplayUtil.dip2px(mContext, 1), 0, 0);
        }
        holder.getConvertView().setLayoutParams(mLayoutParams);

        SimpleDraweeView sdvVideoImg = holder.getView(R.id.sdv_video_img);
        SimpleDraweeView sdvAuthorPortrait = holder.getView(R.id.sdv_author_portrait);
        RelativeLayout rlContent = holder.getView(R.id.rl_content);


        holder.setText(R.id.tv_item, String.valueOf(holder.getAdapterPosition()));

//        holder.setText(R.id.tv_nick_name, feed.getUser().getNickName())
//                .setText(R.id.tv_like_count, String.valueOf(feed.getLikeCount()))
//                .setText(R.id.tv_comment_count, String.valueOf(holder.getAdapterPosition()))
//                .setBackgroundColor(R.id.rl_item_bg, ViewUtil.getRadomColor());

    }
}

**Comment by woniu0936** [comment]
public class FindVideoFragment extends BaseFragment {

    @Bind(R.id.rlv_find_video)
    RecyclerView mRecyclerView;

    private FindVideoAdapter mAdapter;
    private StaggeredGridLayoutManager mLayoutManager;

    private LoadingFooter loadingFooter;
    private Paginator mPaginator;
    private View headerView;
    private boolean isLoading = false;
    //用来控制滑动状态的变化的¬,例如上滑(true)和下滑(false)之间的变化
    private boolean slideChange = false;
    private int[] lastVisibleItemPosition;

    private SimpleDraweeView sdvBanner;
    private TextView tvJoinCount;
    private TextView tvHotTitle;
    private TextView tvHotSubTitle;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mPaginator = new Paginator();
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_find_video, container, false);
        ButterKnife.bind(this, view);
        initView();
        getBannerData();
        getFeedList(mPaginator.toFirstPage());
        return view;
    }

    /**
     * 初始化view
     */
    private void initView() {
        loadingFooter = new LoadingFooter(mActivity);
        mLayoutManager = new StaggeredGridLayoutManager(3, StaggeredGridLayoutManager.VERTICAL);
        mRecyclerView.setLayoutManager(mLayoutManager);
        mAdapter = new FindVideoAdapter(mActivity);
        mAdapter.addFooterView(loadingFooter);
        mAdapter.addHeaderView(getHeaderView());
        mRecyclerView.setAdapter(mAdapter);

        RxRecyclerView.scrollEvents(mRecyclerView)
                .compose(this.<RecyclerViewScrollEvent>bindUntilEvent(FragmentEvent.DESTROY_VIEW))
                .filter(new Func1<RecyclerViewScrollEvent, Boolean>() {
                    @Override
                    public Boolean call(RecyclerViewScrollEvent event) {
                        if (event.dy() > 0 && !slideChange) {
                            slideChange = true;
                            //上滑 显示底部menu
                            RxBus.getDefault().post(new MainAcEvent(true));
                        } else if (event.dy() < 0 && slideChange) {
                            slideChange = false;
                            //下滑 隐藏底部menu
                            RxBus.getDefault().post(new MainAcEvent(false));
                        }
                        if (null == lastVisibleItemPosition) {
                            lastVisibleItemPosition = new int[mLayoutManager.getSpanCount()];
                        }
                        mLayoutManager.findLastVisibleItemPositions(lastVisibleItemPosition);
                        int lastPosition = findMax(lastVisibleItemPosition);
                        return (lastPosition >= mAdapter.getData().size()) && !isLoading;
                    }
                })
                .subscribe(new Action1<RecyclerViewScrollEvent>() {
                    @Override
                    public void call(RecyclerViewScrollEvent event) {

                        if (mPaginator.isLastPage()) {
                            loadingFooter.setState(LoadingFooter.State.TheEnd);
                        } else {
                            loadingFooter.setState(LoadingFooter.State.Loading);
                            getFeedList(mPaginator.toNextPage());
                            isLoading = true;
                        }

                    }
                });


    }

    /**
     * 初始化banner
     *
     * @return
     */
    public View getHeaderView() {
        View view = LayoutInflater.from(mActivity).inflate(R.layout.item_find_video_header, null);
        sdvBanner = (SimpleDraweeView) view.findViewById(R.id.sdv_banner);
        tvJoinCount = (TextView) view.findViewById(R.id.tv_join_count);
        tvHotTitle = (TextView) view.findViewById(R.id.tv_hot_title);

        tvHotSubTitle = (TextView) view.findViewById(R.id.tv_hot_sub_title);

        return view;
    }

    /**
     * banner赋值
     */
    private void setHeaderView(Subject subject) {
//        SayApplacation.frescoImageLoader.loadImage(sdvBanner, subject.getCoverImg(), false);
        sdvBanner.setImageURI(Uri.parse("http://img2.gouhuoapp.com/1614362694.jpg"));
        tvJoinCount.setText(String.format("%d%s", subject.getAnswerCount(), mActivity.getString(R.string.find_video_hot_join)));
        tvHotTitle.setText(subject.getTitle());
        tvHotTitle.getPaint().setFakeBoldText(true);
        tvHotSubTitle.setText(subject.getSubTitle());
    }

    private void getBannerData() {
        Api.creatApiString(Url.API_URL_GET_SUBJECT_HOTS, Api.ApiMethod.GET)
                .map(new Func1<String, String>() {
                    @Override
                    public String call(String s) {
                        //banner为啥要做分页??
//                        try {
//                            JSONObject obj = new JSONObject(s);
//                            String pageStr = obj.getJSONObject("paginator").toString();
//                            mPaginator = JSONUtils.fromJson(pageStr, Paginator.class);
//                        } catch (JSONException e) {
//                            e.printStackTrace();
//                        }
                        return s;
                    }
                })
                .flatMap(new Func1<String, Observable<Subject>>() {
                    @Override
                    public Observable<Subject> call(String s) {
                        Subject subject = null;
                        try {
                            JSONObject obj = new JSONObject(s);
                            JSONObject responseObj = obj.getJSONObject("response");
                            if (HttpConstant.RESPONSE_SUCCESS == responseObj.getInt("status_code")) {
                                String subjectStr = obj.getJSONArray("subjects").get(0).toString();
                                subject = JSONUtils.fromJson(subjectStr, Subject.class);
                            }
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }

                        return Observable.just(subject);
                    }
                })
                .subscribe(new RxSubscriber<Subject>() {
                    @Override
                    public void doOnCompleted() {

                    }

                    @Override
                    public void doOnError(Throwable e) {

                    }

                    @Override
                    public void doOnNext(Subject subject) {
                        if (null != subject) {
                            setHeaderView(subject);
                        }
                    }

                });

        RxRecyclerView.scrollStateChanges(mRecyclerView)
                .compose(this.<Integer>bindUntilEvent(FragmentEvent.DESTROY_VIEW))
                .subscribe(new Action1<Integer>() {
                    @Override
                    public void call(Integer integer) {
                        if (integer == RecyclerView.SCROLL_STATE_IDLE) {
                            SayApplacation.frescoImageLoader.resume();
                        } else {
                            SayApplacation.frescoImageLoader.pause();
                        }
                    }
                });
    }

    /**
     * 获取feed流分页数据
     *
     * @param pageNo
     */
    private void getFeedList(final int pageNo) {
        RequestParams params = new RequestParams();
        params.put("page", pageNo);

        Api.creatApiString(Url.API_URL_GET_INDEX_FEEDS, Api.ApiMethod.GET, params)
                .map(new Func1<String, String>() {
                    @Override
                    public String call(String s) {
                        try {
                            JSONObject obj = new JSONObject(s);
                            String pageStr = obj.getJSONObject("paginator").toString();
                            mPaginator = JSONUtils.fromJson(pageStr, Paginator.class);
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }
                        return s;
                    }
                })
                .flatMap(new Func1<String, Observable<List<Feed>>>() {
                    @Override
                    public Observable<List<Feed>> call(String s) {
                        List<Feed> list = null;
                        try {
                            JSONObject obj = new JSONObject(s);
                            String feedStr = obj.getJSONArray("results").toString();
                            list = JSONUtils.fromJsonArray(feedStr, new TypeToken<List<Feed>>() {
                            });
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }
                        return Observable.just(list);
                    }
                })
                .observeOn(AndroidSchedulers.mainThread())
                .compose(this.<List<Feed>>bindToLifecycle())
                .subscribe(new RxSubscriber<List<Feed>>() {
                    @Override
                    public void doOnCompleted() {
                        isLoading = false;

                        //        "paginator": {
                        //            "total": 7660,   总条目数
                        //                    "num_pages": 383   //总页数
                        //        },
//                        "results": [
//                        {
//                            "thumb": {
//                            "s": "video2.gouhuoapp.com/3126852410483696979?vframe/jpg/offset/0/w/300/h/300/",
//                                    "m": "video2.gouhuoapp.com/3126852410483696979?vframe/jpg/offset/0/w/900/h/900/",
//                                    "l": "video2.gouhuoapp.com/3126852410483696979?vframe/jpg/offset/0/w/2700/h/2700/"
//                        },
//                            "author": {
//                            "avatar_url": "",
//                                    "nickname": "呵呵✨",
//                                    "id": 4284
//                        },
//                            "video_key": "3126852410483696979",
//                                "ext_params": {
//                            "color": "",
//                                    "h": 1280,
//                                    "w": 720
//                        },
//                            "Question": {
//                            "content": "如果警察对你暴力逼供，有什么好的应对方法？",
//                                    "id": 769
//                        },
//                            "like_count": 0,
//                                "answer_id": 17170
//                        ;},
                    }

                    @Override
                    public void doOnError(Throwable e) {
                        isLoading = false;
                    }

                    @Override
                    public void doOnNext(List<Feed> list) {
                        LogUtil.d("lise.size() = " + list.size());
                        if (1 == pageNo) {
                            mAdapter.setNewData(list);
                        } else {
                            mAdapter.addData(list);
                        }

                    }
                });

    }

    /**
     * 获取数组最大值
     *
     * @param lastPositions
     * @return
     */
    private int findMax(int[] lastPositions) {
        int max = lastPositions[0];
        for (int value : lastPositions) {
            if (value > max) {
                max = value;
            }
        }
        return max;
    }

    /**
     * 对RxBus的post的订阅和处理
     */
    private void rxBusSub() {
        RxBus.getDefault().toObserverable(SayVideoFgEvent.class)
                .subscribeOn(Schedulers.io())
                .compose(this.<SayVideoFgEvent>bindUntilEvent(FragmentEvent.DESTROY_VIEW))
                .subscribe(new RxBusSubscriber<SayVideoFgEvent>() {
                    @Override
                    public void doOnError(Throwable e) {

                    }

                    @Override
                    public void doOnNext(SayVideoFgEvent event) {
//                        if (-1 != onClickPosition) {
//                            //更新对应feed的观看数
//                            mAdapter.updateWatchCountByPosition(event.getWatchCount(), onClickPosition);
//                        }
                    }
                });
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        ButterKnife.unbind(this);
    }
}

**Comment by woniu0936** [comment]
if (2 == holder.getAdapterPosition() % 3) {
        mLayoutParams.setMargins(DisplayUtil.dip2px(mContext, 1), DisplayUtil.dip2px(mContext, 1), DisplayUtil.dip2px(mContext, 1), 0);
    } else {
        mLayoutParams.setMargins(0, DisplayUtil.dip2px(mContext, 1), 0, 0);
    }
这段代码控制每一列的中间item，分别在左上右方向margin 1dp，两边两列只做marginTop=1dp；这里19，21，22这里没有分割线是因为分割线在20那里，要是下标不乱的话，就没这个问题了

**Comment by woniu0936** [comment]
我用的版本是2.1.0

**Comment by woniu0936** [comment]
@CymChad 升级到2.1.4之后，就没有乱序问题了，非常感谢

**Comment by parcool** [comment]
最新版本仍然有这个问题。用`StaggeredGridLayoutManager`就会位置错乱，我这里的实际情况是分2列，第0、1条数据正常，但是本来是第2条数据变成第3条了（也就是第2行的顺序反了），后面的数据也是乱来。。。我换成`GridLayoutManager`正常。当然，为了需求，我用原生的Adapter后再用`StaggeredGridLayoutManager`也正常。调了很久（没看你源码），才发现这个现象。目前使用原生adapter中，原因未知。。。。
