### ISSUE TITLE
3.0.4版本子View点击事件无法响应

### ISSUE THREAD

**Issue by zion223** [CymChad/BaseRecyclerViewAdapterHelper#3304]
```
public MultipleSectionGedanCommentAdapter(String commentId, int type, Context context, List<PlayListCommentEntity> data) {
        super(R.layout.item_gedan_comment_header, R.layout.item_gedan_detail_comment, data);
        setNormalLayout(R.layout.item_gedan_detail_comment);
        addChildClickViewIds(R.id.iv_item_gedan_comment_avatar_img, R.id.tv_item_gedan_comment_avatar_name);
        setOnItemClickListener((adapter, view, position) -> {
            switch (view.getId()) {
                case R.id.iv_item_gedan_comment_avatar_img:
                case R.id.tv_item_gedan_comment_avatar_name:
                    //点击进入用户详情
                    UserDetailActivity.startActivity(context, data.get(position).getComment().getUser().getUserId());
                    break;
                case R.id.iv_item_gedan_comment_zan:
                    //点赞
                    break;
                default:
                    break;

            }
        });
    }

```

**Comment by zion223** [comment]
点击回调会触发,打log发现view.getId() 值一直是-1

**Comment by Anonywp** [comment]
> > setOnItemChildClickListener
> 
> 没看明白您说的是啥意思

你写的是setOnItemClickListener，应该用setOnItemChildClickListener

**Comment by zion223** [comment]
> > > setOnItemChildClickListener
> > 
> > 
> > 没看明白您说的是啥意思
> 
> 你写的是setOnItemClickListener，应该用setOnItemChildClickListener

感谢 感谢

**Comment by yu893145181** [comment]
哈哈，习惯了，为啥这两种注册会有这么大的区别

**Comment by jesse920524** [comment]
> Item 内子View的点击事件：
> 注意，请不要在convert方法里注册控件id
> 
> // **_先注册需要点击的子控件id（注意，请不要写在convert方法里）_**
> adapter.addChildClickViewIds(R.id.btn, R.id.iv_num_add, R.id.item_click);
> // 设置子控件点击监听
> adapter.setOnItemChildClickListener(new OnItemChildClickListener() {
> @override
> public void onItemChildClick(@nonnull BaseQuickAdapter adapter, @nonnull View view, int position) {
> if (view.getId() == R.id.btn) {
> Tips.show("onItemChildClick " + position);
> }
> }
> });
> 
> 这样注册则没问题
> recyclerView.adapter = adapter
> adapter.addChildClickViewIds(R.id.tvUnBind)
> adapter.setOnItemChildClickListener { _, _, position ->
> var dialog = UnbindDeviceFragmentDialog()
> dialog.show(fragmentManager!!,null)
> }

谢谢亲测有效. 
但是这api封装的也太烂了, 体验极差

**Comment by miaoweixia** [comment]
class fourFragment : Fragment(), OnItemClickListener {

    lateinit var binding: FragmentFourBinding
    private var datas: MutableList<homeItem>? = null
    private var adapter: myadapter1? = null

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentFourBinding.inflate(layoutInflater)
        //初始化RecyclerView
        //模拟的数据（实际开发中一般是从网络获取的）
        datas = ArrayList()
        var model: homeItem
        for (i in 0..14) {
            model = homeItem(
                "name+" + i, "tltle+" + i,
                "https://dfzximg01.dftoutiao.com/news/20220118/20220118145048_e83d05f274fc573216bf6924d83dd0cf_1.jpeg"
            )
            datas!!.add(model)
        }


        var layoutManager = LinearLayoutManager(context)

        //创建布局管理
//        val layoutManager = LinearLayoutManager(context)
        layoutManager.orientation = LinearLayoutManager.VERTICAL
        binding.recyclerViewFour!!.layoutManager = layoutManager

        //创建适配器
        adapter = myadapter1(R.layout.recycleview_item, datas as ArrayList<homeItem>)

        //给RecyclerView设置适配器
        binding.recyclerViewFour!!.adapter = adapter
        return binding.root

        adapter!!.addChildClickViewIds(R.id.bottom)
        adapter!!.setOnItemClickListener(this)


    }
        override fun onItemClick(adapter: BaseQuickAdapter<*, *>, view: View, position: Int) {
            when (view.id) {
                R.id.textView7 ->
                    Toast.makeText(activity, "你点击了" + position, Toast.LENGTH_SHORT).show()
            }
        }
    }

这样写有问题吗 各位 点击无效果
