### ISSUE TITLE
star项目才能进群？无耻

### ISSUE THREAD

**Issue by hackware1993** [CymChad/BaseRecyclerViewAdapterHelper#331]

**Comment by elfman** [comment]
你觉得这项目不值得你star的话，还进群干嘛？

**Comment by hackware1993** [comment]
光看readme和介绍不足以确定你这个项目是不是有我想要的特性，能不能帮上我，所以先不急着给star，又不想给你提issue，就进群问问支不支持某种特性？如果支持，给star也不晚啊，你这是什么逻辑！

**Comment by elfman** [comment]
star了觉得不满意也可以取消，没人强迫你要加。
所有issue不管有没有star基本都在一天内回答，群里一群人嘈杂，反而不方便交流，提issue比加群要有效率。
连issue也不想提你也可以发邮件，作者邮箱都写在主页

**Comment by hackware1993** [comment]
发邮件太低效，如果仅仅是问题而非bug，不建议提issue，提太多问题类的issue会让人觉得框架不稳定，所以还是加群最直接。

**Comment by 86085185** [comment]
讲道理，issue不是bug的意思，是问题的意思，你有疑问或者bug都可以提出来，我觉得这样的好处就是可以记录下来，我遇到过一些问题都是在issue记录里面找到的，如果每个人都在群里面问问题那么会出现重复问题，你觉得这样效率高吗？

**Comment by 86085185** [comment]
我没有加群，但是我star了，因为这个库帮助了我，而且并不是一定要加群才能提问题，如果一定要加群才能提问题，那么为什么有这么多issue记录？

**Comment by elfman** [comment]
要免费用别人的东西，还请尊重下作者的要求，而这要求对你来说也不是难事。
退群unstar也没人惦记你的一颗星。
群里现在490人，项目现在star数3689，所以你也别觉得这个条件为了骗star

**Comment by 86085185** [comment]
支持作者！

**Comment by LiuTangLei** [comment]
爱用不用，弱智

**Comment by hackware1993** [comment]
@LiuTangLei sb

**Comment by hackware1993** [comment]
@LiuTangLei 傻逼

**Comment by Luogjy** [comment]
上来就骂人非常不妥，而且你star了之后可以取消的，觉得不公平可以无视这个项目，为什么要攻击呢？

**Comment by hackware1993** [comment]
不吵了，太low了
