### ISSUE TITLE
BaseMultiItemQuickAdapter的使用问题

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#334]
请问下我使用多布局，后台的返回数据里有布局类型，我改怎么使用啊？看了Demo写了没成功。

**Comment by CymChad** [comment]
在绑定数据的时候需要给每一条数据设置itemType，然后在adapter的构造里面绑定itemType和layout的关系，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8D%E5%90%8C%E7%9A%84item%E7%B1%BB%E5%9E%8B

**Comment by wuzhaohui026** [comment]
itemType在返回的JSON数据里已经有了。。。已经晕了。。。

**Comment by CymChad** [comment]
你set到itemType里面。

**Comment by wuzhaohui026** [comment]
![image](https://cloud.githubusercontent.com/assets/7565399/18617246/c10f4fd6-7dfd-11e6-9e98-42e569a2d7fc.png)
这样吗？

**Comment by CymChad** [comment]
恩 ，是的。

**Comment by wuzhaohui026** [comment]
那我的list怎么绑定数据，我之前是用resList.addAll(response.getRes_message());

**Comment by CymChad** [comment]
把你处理过的数据，和往常一样的设置就好了。

**Comment by wuzhaohui026** [comment]
![image](https://cloud.githubusercontent.com/assets/7565399/18621307/bd9fa8cc-7e53-11e6-8942-1cb76aaa98c7.png)
我这样写的，然后程序就崩了，
![image](https://cloud.githubusercontent.com/assets/7565399/18621310/d51b94a2-7e53-11e6-87ff-fbb4812840c7.png)

**Comment by wuzhaohui026** [comment]
好像已经号了，不过有个疑问，我一开始设定2个类型
![image](https://cloud.githubusercontent.com/assets/7565399/18621649/2494e952-7e59-11e6-834d-2211c7374071.png)
然后注释掉第三个，
![image](https://cloud.githubusercontent.com/assets/7565399/18621653/3bda50d4-7e59-11e6-8573-d4ed6d63809e.png)
程序就出现上面的情况，
然后我取消第三个注释
就可以运行了

**Comment by CymChad** [comment]
你的类型都保持一致的吗？

**Comment by CymChad** [comment]
报错的原因是因为通过这个typeId没有获得到layoutId

**Comment by wuzhaohui026** [comment]
soga,那就知道怎么回事了。现在已经可以正常使用了，谢谢
