### ISSUE TITLE
使用BaseDataBindingHolder混淆后闪退

### ISSUE THREAD

**Issue by qinyang1018** [CymChad/BaseRecyclerViewAdapterHelper#3345]
```
 java.lang.ClassCastException: com.chad.library.adapter.base.viewholder.BaseViewHolder cannot be cast to com.chad.library.adapter.base.viewholder.BaseDataBindingHolder
```
![image](https://user-images.githubusercontent.com/15726024/96208069-4b271000-0f9f-11eb-9aa1-47818f524738.png)
![image](https://user-images.githubusercontent.com/15726024/96208099-609c3a00-0f9f-11eb-856a-d19d611acf11.png)

混淆后闪退

**Comment by qinyang1018** [comment]
混淆配置规则错误
添加
-keep class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {*;}

**Comment by KAICW** [comment]
Android studio 4.0 无效一样报错
