### ISSUE TITLE
OnItemChildClickListener not Registered for first item in Adapter

### ISSUE THREAD

**Issue by JosephSanjaya** [CymChad/BaseRecyclerViewAdapterHelper#3347]
**Describe the bug**
When setup OnItemChildClickListener the first item in adapter did not register the click action, the second and the rest of data working fine with the click. Only The first one

**To Reproduce**
1. Register Child Id
2. Setup Child Ids for click
3. Run
4. See error on first item

**Expected behavior**
OnItemChildClickListener should work on all position, in java version 2.9 its working fine without issue

**Comment by o0o0oo00** [comment]
> **Describe the bug**
> When setup OnItemChildClickListener the first item in adapter did not register the click action, the second and the rest of data working fine with the click. Only The first one
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Register Child Id
> 2. Setup Child Ids for click
> 3. Run
> 4. See error on first item
> 
> **Expected behavior**
> OnItemChildClickListener should work on all position, in java version 2.9 its working fine without issue

how to solve it
