### ISSUE TITLE
BaseMultiItemQuickAdapter  里嵌套了RecyclerView滑动会卡顿

### ISSUE THREAD

**Issue by DarkerWanglei** [CymChad/BaseRecyclerViewAdapterHelper#3348]
我用的是2.9.44版本，一个三种类型的布局，每个类型里都嵌套了RecyclerView，  
                case MultipleItem.TEXT:
                RecyclerView recyclerView = helper.getView(R.id.rv_special);
                if (recyclerView.getLayoutManager() == null) {
                    recyclerView.setLayoutManager(new GridLayoutManager(mContext, 4));
                }

                if (recyclerView.getAdapter() == null) {
                    SpecialAdapter adapter = new SpecialAdapter(list);
                    recyclerView.setAdapter(adapter);
                } else {
                    ((SpecialAdapter) recyclerView.getAdapter()).setNewData(list);
                }
                break;
这么写的，滑动会卡顿，我也下载了您2.9.44的demo，把demo里的布局替换成我的，demo滑动也会卡顿，加载的图片数量也不大，图片就是网上随便找的个url，两个不同类型的布局之间卡顿会明显一点,希望能有点帮助。

**Comment by RDSunhy** [comment]
您好。请问这个问题解决了吗？分享下吧

**Comment by DarkerWanglei** [comment]
我卡顿的原因不是因为这个adapter，是我用了一个圆角图片的控件， 是因为这个控件导致的卡顿，你看从这方面能不能找找原因&nbsp;

郁闷
 &nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "the Sun."<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 上午10:17
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com&gt;; 
抄送: "不知觉"<912436316@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] BaseMultiItemQuickAdapter  里嵌套了RecyclerView滑动会卡顿 (#3348)



您好。请问这个问题解决了吗？分享下吧
