### ISSUE TITLE
doc seem a small mistake

### ISSUE THREAD

**Issue by JamesLi2013** [CymChad/BaseRecyclerViewAdapterHelper#335]
Wiki->Optimization adapter to reduce code->Getting started->(ImageView) helper.getView(R.id.iv)  , replace helper  by viewHolder,maybe better.

**Comment by CymChad** [comment]
Thank you

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Optimization-adapter-to-reduce-code
