### ISSUE TITLE
expand点击最后一个item，展开的时候奔溃

### ISSUE THREAD

**Issue by beiliubei** [CymChad/BaseRecyclerViewAdapterHelper#336]
使用 BaseMultiItemQuickAdapter<MultiItemEntity>

组织了三级目录（其中第二级没有点击事件），所以当点击第一级时，调用了expandAll(pos, false);方法，展开了所有。

现在有数据
    head（1个）
    item（如下结构）
     - section
        - folder
           - child
           - child
           - child
    - section
        - folder
           - child
           - child
           - child
    - section
        - folder
           - child
           - child
           - child
        - folder
           - child
           - child
           - child

点击展开第一和第二个section没问题，点击第三个section时，数组越界了

**Comment by beiliubei** [comment]
![image](https://cloud.githubusercontent.com/assets/1127875/18621259/152b93d6-7e53-11e6-8fa8-d8a506a531f4.png)
![image](https://cloud.githubusercontent.com/assets/1127875/18621264/2661d58e-7e53-11e6-84ed-26e7229bb5d9.png)
![image](https://cloud.githubusercontent.com/assets/1127875/18621265/32b2462a-7e53-11e6-8613-643e27504e4d.png)
![image](https://cloud.githubusercontent.com/assets/1127875/18621269/4869e1d0-7e53-11e6-87c6-e3cf0137b39b.png)

![image](https://cloud.githubusercontent.com/assets/1127875/18621279/65837b28-7e53-11e6-988f-685d18a3dc3c.png)

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.5'

**Comment by CymChad** [comment]
感谢贡献代码。
