### ISSUE TITLE
headview和footview随机性出现不能点击的情况

### ISSUE THREAD

**Issue by linjiangye** [CymChad/BaseRecyclerViewAdapterHelper#337]
尝试了官方的demo也有这样的情况，
随机性的，多尝试几次的时候可能会出现，添加了touch listener发现似乎根本没有响应到touch事件

**Comment by CymChad** [comment]
请给出具体操作步骤这样更容易让我们定位问题所在，目前我们这边测试都一切正常。

**Comment by linjiangye** [comment]
升级到2.14之后问题似乎消失了，那应该是我本地的问题吧

**Comment by CymChad** [comment]
恩，好的，感谢使用。
