### ISSUE TITLE
BaseSectionQuickAdapter 复用倒计时会乱跳

### ISSUE THREAD

**Issue by byjjack** [CymChad/BaseRecyclerViewAdapterHelper#3382]
在这个分组 adapter 里每个 item 使用了 CountDownTimer 实现倒计时 每个item数字会乱跳

public class BSAdapter extends BaseSectionQuickAdapter<BsResult, BaseViewHolder> {

    /**
     * Same as QuickAdapter#QuickAdapter(Context,int) but with
     * some initialization data.
     *
     * @param layoutResId      The layout resource id of each item.
     * @param sectionHeadResId The section head layout id for each item
     * @param data             A new list is created out of this one to avoid mutable list
     */
    public BSAdapter(int layoutResId, int sectionHeadResId, List<BsResult> data) {
        super(layoutResId, sectionHeadResId, data);
    }

    @Override
    protected void convertHead(BaseViewHolder helper, BsResult item) {

    }

    private CountDownTimer downTimer;

    private String rsState;// 1 是发送 2 是接收

    public void setRsState(String rsState) {
        this.rsState = rsState;
    }

    @Override
    protected void convert(BaseViewHolder helper, BsResult item) {

        if (item.t.getName().length() > 5) {
            helper.setText(R.id.tv_name, item.t.getName().substring(0, 5) + "...");

        } else {
            helper.setText(R.id.tv_name, item.t.getName());

        }

        helper.setText(R.id.tv_job, item.t.getJob_name());
        helper.setText(R.id.tv_day, item.t.getCreate_time());
        ImageView view = helper.getView(R.id.iv_cover);
        DrawableUtil.toRidius(100, item.t.getHead_img(), view, R.drawable.one_icon);

        //小红点
        boolean equals = item.t.getRead_time().equals("0");
        if (equals) {
            helper.getView(R.id.red_dot).setVisibility(View.VISIBLE);
        } else {
            helper.getView(R.id.red_dot).setVisibility(View.GONE);
        }

        long surplus_time = item.t.getSurplus_time();

        TextView status = helper.getView(R.id.tv_status);
        helper.getView(R.id.tv_time).setVisibility(View.GONE);
        helper.getView(R.id.tv_min).setVisibility(View.GONE);
        helper.getView(R.id.tv_sencend).setVisibility(View.GONE);

        helper.getView(R.id.tv_ms_time).setVisibility(View.GONE);
        helper.getView(R.id.tv_ms_num).setVisibility(View.GONE);

        if (TextUtils.isEmpty(item.t.getMy_job_name())) {
            helper.getView(R.id.tv_msname).setVisibility(View.INVISIBLE);
            helper.getView(R.id.msgw).setVisibility(View.INVISIBLE);
        } else {
            helper.getView(R.id.tv_msname).setVisibility(View.VISIBLE);
            helper.getView(R.id.msgw).setVisibility(View.VISIBLE);
            helper.setText(R.id.tv_msname, item.t.getMy_job_name());
        }

        switch (item.t.getStatus()) {
            case "0":

                helper.getView(R.id.tv_time).setVisibility(View.VISIBLE);
                helper.getView(R.id.tv_min).setVisibility(View.VISIBLE);
                helper.getView(R.id.tv_sencend).setVisibility(View.VISIBLE);

                if (rsState.equals("1")) {
                    helper.getView(R.id.tv_ms_time).setVisibility(View.GONE);
                    helper.getView(R.id.tv_ms_num).setVisibility(View.GONE);
                } else {
                    helper.getView(R.id.tv_ms_time).setVisibility(View.VISIBLE);
                    helper.getView(R.id.tv_ms_num).setVisibility(View.VISIBLE);
                }

                DrawableUtil.toDrable(R.drawable.notify_waite_pg, 0, 0, 30, 30, status, 1);
                helper.setText(R.id.tv_status, "等待");
                helper.itemView.setBackgroundResource(R.drawable.notify_waite);

                //计时器
                downTimer = new CountDownTimer(surplus_time * 1000, 1000) {
                    @Override
                    public void onTick(long millisUntilFinished) {
                        long timeSeconds = millisUntilFinished / 1000;
                        int strTime = caclTimeSec((int) timeSeconds);
                        int secnd = caclTimeSecs((int) timeSeconds);
                        int min = caclTimeSecss((int) timeSeconds);

                        String hour = (strTime >= 10) ? strTime + "" : "0" + strTime;
                        String senced = (secnd >= 10) ? secnd + "" : "0" + secnd;
                        String mintent = (min >= 10) ? min + "" : "0" + min;

                        helper.setText(R.id.tv_time, hour + ":");
                        helper.setText(R.id.tv_sencend, senced);
                        helper.setText(R.id.tv_min, mintent);
                    }

                    @Override
                    public void onFinish() {
                        int strTime = caclTimeSec(0);
                        helper.setText(R.id.tv_time, "");
                        helper.setText(R.id.tv_sencend, "");
                        helper.setText(R.id.tv_min, "");
                    }
                };
                downTimer.start();

                break;

**Comment by byjjack** [comment]
每个 item 里的倒计时就会显示其他item里的倒计时，一会展示一会不展示，知道这个是recyclerview 复用的原因，一开始解决办法是在 CountDownTimer 在 new 的时候先判断是否为空，不为空就先 cancel 然后再把他变成 null 最后再给他 new 一下，但是这个方案写完后 整个列表 的倒计时就都停止了

**Comment by Sky0202** [comment]
你这样写，相当于复用了同一个CountDownTimer，所以会出现错乱，我之前这种情况的解决方式是将每个new出来的CountDownTimer 存到一个list中，使用时去list中取，就可以避免错乱，防止复用

**Comment by com13117340768** [comment]
map<position,CountDownTimer 实例>

**Comment by byjjack** [comment]
谢谢楼上的两位的介意，正在尝试

**Comment by byjjack** [comment]
谢谢楼上两位的建议，正在尝试
