### ISSUE TITLE
setNewData 引起的 NullPointerException

### ISSUE THREAD

**Issue by Andrew-Shi** [CymChad/BaseRecyclerViewAdapterHelper#339]
BaseQuickAdapter 的构造方法中data传null，程序有非空判断，mData不会为空，但是初始化之后调用setNewData 是data传null，mData被赋值为空，getItemCount()被调用时程序崩溃，建议setNewData方法中加入非空判断

**Comment by CymChad** [comment]
恩 好的，多谢提醒

**Comment by CymChad** [comment]
下个版本，加上通知你。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.6'
