### ISSUE TITLE
An question about the method "convert"

### ISSUE THREAD

**Issue by shineM** [CymChad/BaseRecyclerViewAdapterHelper#34]
How to use image loading library like Glide  when bind view holder ?

**Comment by CymChad** [comment]
? 解决了？

**Comment by shineM** [comment]
没有，正在寻求其他方案，可以直接用getConvertView()这个方法得到的View自己绑定吗？

**Comment by shineM** [comment]
已解决，通过getConvertView可以自定义绑定，感谢！

**Comment by CymChad** [comment]
恩，你如果只是想改变加载图片的加载方式的话，可以通过holder.getView(resId),获取img对象。默认setImageUrl就是通过Glide加载图片。

**Comment by shineM** [comment]
嗯，还有个问题想问下，notifyDataChangedAfterLoadMore的datas参数只能同步请求数据吗

**Comment by CymChad** [comment]
同步请求数据？这个datas是追加数据

**Comment by shineM** [comment]
解决了，thanks！
