### ISSUE TITLE
BaseSectionQuickAdapter如何为每个分组设置背景？

### ISSUE THREAD

**Issue by Imfondof** [CymChad/BaseRecyclerViewAdapterHelper#3405]
**Describe the bug**
BaseSectionQuickAdapter可以实现多分组，那么如何实现为每个分组设置相应的背景呢？（功能效果类似于 支付宝--我的 页面）

version：2.9.40
目前的效果BaseSectionQuickAdapter只能设置item的背景，但是item对应的一组没有可以设置背景的地方。

**Comment by Imfondof** [comment]
解决方案：可以在BaseSectionQuickAdapter的实现类里的convert方法里为每个item设置布局。

比如一个分组里有三个，那么我们为第一个设置左上、右上的圆角，第二个不设置圆角，第三个设置左下、右下的圆角，那么效果上我们就实现了这个分组整体的圆角。

**Comment by skyyanyujiangnan** [comment]
如果一行显示三列数据   只有两条数据的时候如何显示最后一个圆角
