### ISSUE TITLE
BaseSectionQuickAdapter多布局展示问题

### ISSUE THREAD

**Issue by fanggege** [CymChad/BaseRecyclerViewAdapterHelper#3421]
集成了JSectionEntity 并重写了getItemType() 成功实现了多布局，
但是界面展示的效果和预期有所差别：
  第一个item  头部是标题（占用一行）
  第二个item  图片内容（三张图片占用一行）
  第三个item  评论内容（需要一个评论占用一行，但是这里却跟着图片的展示方式一致了 ，三个评论占用一行，这里我需要一条评论占用一行需要怎么操作？）

RecyclerView使用的 :setLayoutManager(new StaggeredGridLayoutManager(3, RecyclerView.VERTICAL));
adapter使用的：BaseSectionQuickAdapter
版本为：3.0.4

**Comment by fanggege** [comment]
找到原因了

**Comment by q88qaz** [comment]
分享出来
