### ISSUE TITLE
2.0.3版本上拉加载到最后一页数据报错

### ISSUE THREAD

**Issue by candebbs** [CymChad/BaseRecyclerViewAdapterHelper#344]
2.0.3版本上拉加载到最后一页数据时报错：java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling，但看demo没有问题。
代码是：
`
if (mCurrentPage >= totalPage) { // 加载所有的数据了
            try {
                wangHongListBaseQuickAdapter.loadComplete();
            }catch (Exception e){
                isErr = false;
            }
            if (notLoadingView == null) {
                notLoadingView = getActivity().getLayoutInflater().inflate(R.layout.not_loading, (ViewGroup) main_fragment_wongHongList_rv.getParent(), false);
            }
            try {
                wangHongListBaseQuickAdapter.addFooterView(notLoadingView);
            }catch (Exception e){
                isErr = false;
            }
        }
`
.loadComplete();和.addFooterView报的

**Comment by CymChad** [comment]
RecyclerView is computing a layout or scrolling  是因为要在加载数据的时候
```java
 mRecyclerView.post(new Runnable() {
// 在这里面操作
});
```

**Comment by CymChad** [comment]
原因是因为，RecyclerView的item还没加载完毕你就通过`addFooterView`新增了一个item，所以出现了Cannot call this method while RecyclerView is computing a layout or scrolling
