### ISSUE TITLE
addOnItemTouchListener BUG

### ISSUE THREAD

**Issue by jiongjiongxia** [CymChad/BaseRecyclerViewAdapterHelper#346]
SectionUseActivity 的 SectionAdapter 在 R.layout.def_section_head 里 如果去掉 android:id="@+id/more"的TextView  点击会报错。

**Comment by CymChad** [comment]
请贴出具体错误

**Comment by CymChad** [comment]
因为demo里面有应用到了@+id/more，所以你去掉肯定有问题。
