### ISSUE TITLE
fragment中使用问题

### ISSUE THREAD

**Issue by Heigedu** [CymChad/BaseRecyclerViewAdapterHelper#347]
在fragment中使用recyclerView会遇到 The specified child already has a parent. You must call removeView()的问题。 adapter中的mContext 是否应通过构造器传入

**Comment by Ludejin** [comment]
这是你代码的问题，贴代码

**Comment by Ludejin** [comment]
这是你代码的问题，贴代码

**Comment by CymChad** [comment]
#277
