### ISSUE TITLE
添加FootView时如果列表是横向的，footviewLayout会占满一整行的空间

### ISSUE THREAD

**Issue by YimasoftLiuGuanJun** [CymChad/BaseRecyclerViewAdapterHelper#3484]
添加FootView时如果列表是横向的，footviewLayout会占满一整行的空间，导致在添加数据后看到的总是最后一列的FootView，很迷惑， 解决方法可以获取这个FootViewLayout然后在手动设置宽度为实际控价的宽度。

1. 当前使用的版本号： 3.0.4
2. 复现操作描述： 添加footView，并且列表为横向列表

**Comment by Mrliandroid** [comment]
建议使用多布局，他这个添加footview不是同一种类型的

**Comment by YimasoftLiuGuanJun** [comment]
> 建议使用多布局，他这个添加footview不是同一种类型的

好吧，我只是想让别的人遇到这个issue然后能快速定位到这里，毕竟一开始这个问题让我很迷惑，最后才想起来测试footviewlayout的宽度。
