### ISSUE TITLE
树形结构删除最后一条数据会报索引越界

### ISSUE THREAD

**Issue by 1226362423** [CymChad/BaseRecyclerViewAdapterHelper#3487]
树形结构删除最后一条数据会报索引越界

**Comment by hejingzhou** [comment]
我这也复现了

**Comment by jqorz** [comment]
fork一下，修改BaseNodeAdapter#removeNodesAt中为val node = this.data.getOrNull(position)即可。
大家可以使用我改过的依赖 'com.github.jqorz:BaseRecyclerViewAdapterHelper:3.0.6.1'

**Comment by 1226362423** [comment]
把依赖引入到项目了 是因为没有加尾部 可以把尾部注释掉
