### ISSUE TITLE
headerView的显隐问题

### ISSUE THREAD

**Issue by woniu0936** [CymChad/BaseRecyclerViewAdapterHelper#349]
使用如下代码：
//隐藏header
LinearLayout headerViewLayout = mAdapter.getHeaderLayout();
headerViewLayout.setVisibility(View.GONE);
这时候headerView是隐藏了，但是还占着位置

**Comment by woniu0936** [comment]
![wechatimg1](https://cloud.githubusercontent.com/assets/7264285/18707756/0840241a-802a-11e6-8852-483476968466.jpeg)
![wechatimg2](https://cloud.githubusercontent.com/assets/7264285/18707757/084546b6-802a-11e6-8dd6-ff49694fa538.jpeg)

**Comment by CymChad** [comment]
setVisibility  是肯定会占位置的，他是一个item，不是一个整体的布局，除非你rm这个headView

**Comment by woniu0936** [comment]
@CymChad 除过remove之外，有什么其他好的建议吗？因为这个headerView是动态显隐的

**Comment by CymChad** [comment]
rm和add，这就可以动态显示或隐藏。

**Comment by woniu0936** [comment]
谢谢

**Comment by yanxinmiao** [comment]
添加两个headview后， 第一次删除时（无论删除哪个） 没有动画过渡，而是很生硬的隐藏，有没有什么好办法 。

问题应该是在这，第一次删除时 走不进第二个if语句 。
```
public void removeHeaderView(View header) {
        if (getHeaderLayoutCount() == 0) return;

        mHeaderLayout.removeView(header);
        if (mHeaderLayout.getChildCount() == 0) {
            int position = getHeaderViewPosition();
            if (position != -1) {
                notifyItemRemoved(position);
            }
        }
    }

```

**Comment by CymChad** [comment]
因为他的原理是无论多少个头部都是加载一个布局里面。 @yanxinmiao
