### ISSUE TITLE
setlist后无法刷新item

### ISSUE THREAD

**Issue by shuiming11** [CymChad/BaseRecyclerViewAdapterHelper#3498]
setlist后无法刷新item,使用全局刷新和局部刷新或者重新setlist都不能刷新item

**Comment by LaoXiZi** [comment]
同问
adapter.removeAt(position)
adapter.setNewInstance(list)
adapter.notifyDataSetChanged()
notifyItemChanged(position)都没刷新

**Comment by fly263** [comment]
有点坑，使用setList()

**Comment by SakurajimaMaii** [comment]
这个问题解决了吗？
