### ISSUE TITLE
BaseQuickAdapter.removeAt() BaseQuickAdapter.remove()，当getData()只有一条数据时，删除该条数据报错

### ISSUE THREAD

**Issue by fadedHYC** [CymChad/BaseRecyclerViewAdapterHelper#3505]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: BaseViewHolder{593d592 position=0 id=0, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{bf09b63 V.ED..... ......ID 0,0-1080,2119 #7f080271 app:id/recycler_view}, adapter:com.tuoluo.civi.adapter.BlackAdapter@65c8360, layout:androidx.recyclerview.widget.LinearLayoutManager@1ab6019, context:com.tuoluo.civi.view.activity.BlackActivity@84f87b1

**Comment by Hynsn** [comment]
你好 我也遇到这个问题了。请问你怎么解决的，急！！我这边需求数据全添加到head中刷新
