### ISSUE TITLE
请问下分组的伸缩栏的数据处理问题

### ISSUE THREAD

**Issue by candebbs** [CymChad/BaseRecyclerViewAdapterHelper#351]
我有一个需求是：是两级分组菜单的。我设置数据源时，有几个属性是判断一级的item或者两级的item是否选中之类的，但是
我点击了一级的item，可以知道影响到一级的item下面子菜单的这几个属性，但点击二级的item的，无法影响到其上一级的item数据属性，请问是怎样做，分级组的item可以互相影响到数据源？或者点击二级的item，就知道他所在的一级item的position?

**Comment by CymChad** [comment]
收到，正在跟进中，稍等。

**Comment by candebbs** [comment]
我希望在adapter中的protected void convert(BaseViewHolder baseViewHolder, WHListData.SearchList item)，再添加一个方法convert，这个convert方法多返回当前item的索引position。有时开发中使用到的，不要用holder.getAdapterPosition()来拿到

**Comment by CymChad** [comment]
错误的？

**Comment by elfman** [comment]
1. 你这个需求可以通过在AbstractExpandableItem里多加一个level表示层级来实现，需要获取parent时通过往前遍历level较小来获取。
2. getAdapterPosition是包含有RecyclerView自带的方法，返回的position是会包含有header layout，跟你的数据集里面的位置可能会不一样
