### ISSUE TITLE
分组问题

### ISSUE THREAD

**Issue by JacksenLaw** [CymChad/BaseRecyclerViewAdapterHelper#3510]
分组中布局可以实现 recyclerview 的 GridLayoutManager 的效果吗？

**Comment by liangjingkanji** [comment]
你说的这种效果么

<img src="https://i.imgur.com/OJUv7w7.png" width="20%"/>

https://github.com/liangjingkanji/BRV/

**Comment by JacksenLaw** [comment]
是的，就是这种效果，  demo得效果是 子分组是列表形式，我不太清楚是否能实现这种效果。  不过我用嵌套recyclerview实现了这种效果，虽然不太想用这种方式😔

发自我的iPhone

**Comment by EndeRHoshI** [comment]
1. 首先设置 GridLayoutManager
```
binding.recyclerView.layoutManager = GridLayoutManager(context, 4)
binding.recyclerView.adapter = adapter
```
2. 然后在 BaseNodeAdapter 将你想要显示一整行的 Provider 用 addFullSpanNodeProvider 设置
```
init {
    addFullSpanNodeProvider(TitleProvider()) // 占据一整行的 item，标题 item
    addNodeProvider(EntranceProvider()) // 普通的一行四个的 item
}
```
