### ISSUE TITLE
提个bug，item控件 点击事件的bug

### ISSUE THREAD

**Issue by JacksenLaw** [CymChad/BaseRecyclerViewAdapterHelper#3517]
在 继承 BaseQuickAdapter  的子类中，重写 onItemViewHolderCreated 方法，使用 addChildClickViewIds 方法绑定item控件的事件，发现第一个item 中所有绑定的事件不生效，但在构造方法中使用却没有问题。

**Comment by aikongmeng** [comment]
这个BUG 已经存在一年有余

**Comment by lhhseraph** [comment]
我也遇到同样问题
