### ISSUE TITLE
最新版api

### ISSUE THREAD

**Issue by adminLiu-s** [CymChad/BaseRecyclerViewAdapterHelper#352]
我现在用的是2.1.6的，请问下点击事件是改了吗   适配器都没这些方法了
setOnRecyclerViewItemChildClickListener
setOnRecyclerViewItemClickListener
setOnRecyclerViewItemChildLongClickListener
setOnRecyclerViewItemLongClickListener
继承的是BaseQuickAdapter

**Comment by CymChad** [comment]
恩是的具体使用你可以看文档。https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki
