### ISSUE TITLE
setEmptyView 只能维持前两个

### ISSUE THREAD

**Issue by chenwulue** [CymChad/BaseRecyclerViewAdapterHelper#353]
我有三种EmptyView的情况，但是发现切换时，只能在前两个切换，第三个设置无效，用的是sample中的EmptyViewUseActivity里面的方法，以下是代码
`package com.chad.baserecyclerviewadapterhelper;

import android.app.Activity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import com.chad.baserecyclerviewadapterhelper.adapter.QuickAdapter;

public class EmptyViewUseActivity extends Activity implements View.OnClickListener {
    private RecyclerView mRecyclerView;
    private QuickAdapter mQuickAdapter;
    private boolean isNotData = true;
    private View errorView;
    private View notDataView;
    private View errorView2;
    int number;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_empty_view_use);
        mRecyclerView = (RecyclerView) findViewById(R.id.rv_list);
        Button btnSwuich = (Button) findViewById(R.id.btn_switch);
        Button btnSetError = (Button) findViewById(R.id.btn_set_error);
        mRecyclerView.setHasFixedSize(true);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        initAdapter();
        btnSwuich.setOnClickListener(this);
        notDataView = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) mRecyclerView.getParent(), false);
        errorView = getLayoutInflater().inflate(R.layout.error_view, (ViewGroup) mRecyclerView.getParent(), false);
        errorView2 = getLayoutInflater().inflate(R.layout.error22_view, (ViewGroup) mRecyclerView.getParent(), false);
        btnSetError.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                isNotData = true;
            }
        });
    }

    private void initAdapter() {
        mQuickAdapter = new QuickAdapter(0);
        View emptyView = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) mRecyclerView.getParent(), false);
        mQuickAdapter.setEmptyView(emptyView);

        mRecyclerView.setAdapter(mQuickAdapter);
    }

    @Override
    public void onClick(View v) {

        int position = number % 3;
        Log.e("onClick position",position+"");
        if (position == 0) {
            if (isEmptyView(errorView))
                changedView(errorView);
        } else if (position == 1) {
            if (isEmptyView(errorView2))
                changedView(errorView2);
        } else if (position == 2) {
            if (isEmptyView(notDataView))
                changedView(notDataView);
        }
        number++;

/*

        View view;
        if (!isNotData) {
            isNotData = true;
            if (isEmptyView(notDataView))
                changedView(notDataView);
        } else {
            isNotData = false;
            if (isEmptyView(errorView))
                changedView(errorView);
        }
*/

    }

    private boolean isEmptyView(View view) {
        return mQuickAdapter.getEmptyView() != view;
    }

    private void changedView(View view) {
        Log.e("changedView","changedView");
        mQuickAdapter.setEmptyView(view);
        mQuickAdapter.notifyItemChanged(0);
    }
}
`
上面的errorView2设置无效

**Comment by CymChad** [comment]
恩，RecyclerView的Item缓存问题。

**Comment by CymChad** [comment]
目前最多只能做到两个。
