### ISSUE TITLE
有关item控件的 holder.setVisible方法

### ISSUE THREAD

**Issue by candebbs** [CymChad/BaseRecyclerViewAdapterHelper#355]
在开发中，item的控件会有三种状态：gone、invisible、visible
 不能只使用holder.setVisible(R.id....., false);来控制控件显示和隐藏，我觉得增加一个方法直接传view.invisible,view.visible,view.gone比较好。

**Comment by CymChad** [comment]
恩，你可以通过getView获取控件然后设置状态，这个状态确实没有考虑到，多谢建议。
