### ISSUE TITLE
大佬，请问能出一个简易版的kotlin的demo吗？我是一个安卓菜鸟

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [CymChad/BaseRecyclerViewAdapterHelper#3561]
原来公司java开发时用过您的这个BaseRecyclerViewAdapterHelper，觉得很好用，但是苦于当时帮助文档看不懂外加刚学安卓，只能复制粘贴公司原来的代码，现在比当初的能力强了些，又自学了kotlin，想在以后的项目中再使用您的这个框架，但是刚才下下来代码demo跑不起来，好像有几个地方缺少了方法，看了之前别人提的问题和回答找到了解决办法，重写那几个方法或者降级使用，还有重写绑定事件时也会突然崩溃，获取位置的方法变了要升级recyclerView依赖的版本，搞这些弄了几个小时，现在终于把原生的recyclerView替换成了您的框架，也从帮助文档中知道了不能在convert实现里写控件点击事件的绑定，原来一直都在实现方法里绑定的点击事件😂不知道后续使用还有多少困难在等着我，如果大佬能出个简单详细的kotlin使用的demo就好了，我技术太菜，您的demo对我来说阅读还是有些困难，我目前是一边对照您的文档一边看原来java项目中使用的一边用kotlin重写😢

**Comment by songdehuai** [comment]
这是我在用的样子，应该能帮助到你

**业务adapter**

``` kotlin
class TestAdapter : BaseListAdapter<UserBean>(R.layout.item_xxxxx) {

    override fun convert(holder: BaseViewHolder, item: UserBean) {
        //holder.setText(R.id.xxx,"")
        //holder.setImageResource(R.id.xxx,R.drawable.xxx)
        //todo 

    }
}

```
**BaseListAdapter**
``` kotlin
import androidx.annotation.LayoutRes
import com.chad.library.adapter.base.BaseQuickAdapter
import com.chad.library.adapter.base.viewholder.BaseViewHolder

abstract class BaseListAdapter<T>(@LayoutRes private val layoutResId: Int, data: MutableList<T>? = null) : BaseQuickAdapter<T, BaseViewHolder>(layoutResId, data) 

```

**BaseLoadMoreListAdapter**
``` kotlin
import androidx.annotation.LayoutRes
import com.chad.library.adapter.base.module.LoadMoreModule

abstract class BaseLoadMoreListAdapter<T>(@LayoutRes private val layoutResId: Int, data: MutableList<T>? = null) : BaseListAdapter<T>(layoutResId, data), LoadMoreModule 
```

**BaseBindingListAdapter**
``` kotlin
import androidx.annotation.LayoutRes
import androidx.databinding.ViewDataBinding
import com.chad.library.adapter.base.BaseQuickAdapter
import com.chad.library.adapter.base.viewholder.BaseDataBindingHolder

abstract class BaseBindingListAdapter<T, Binding : ViewDataBinding>(@LayoutRes private val layoutResId: Int, data: MutableList<T>? = null) : BaseQuickAdapter<T, BaseDataBindingHolder<Binding>>(layoutResId, data)

```

**Comment by SaltedFish-Extreme** [comment]
> 

啊，非常感谢，一目了然，还有一个问题想问下，点击事件的监听你是写在哪的，也在adapter类里还是在activity里😊

**Comment by SaltedFish-Extreme** [comment]
> 这是我在用的道理，应该能帮到你
> 
> **业务适配器**
> 
> ```kotlin
> 类 TestAdapter : BaseListAdapter < UserBean >( R .layout.item_xxxxx) {
> 
>     覆盖 fun  convert ( holder :  BaseViewHolder , item :  UserBean ) {
>          // holder.setText(R.id.xxx,"") 
>         // holder.setImageResource(R.id.xxx,R.drawable.xxx) 
>         // todo
> 
>     }
> }
> ```
> 
> **基表适配器**
> 
> ```kotlin
> 导入 androidx.annotation.LayoutRes
> 导入 com.chad.library.adapter.base.BaseQuickAdapter
> 导入 com.chad.library.adapter.base.viewholder.BaseViewHolder
> 
> 抽象 类 BaseListAdapter < T >(@LayoutRes private  val  layoutResId :  Int , data :  MutableList < T > ? = null) : BaseQuickAdapter<T, BaseViewHolder>(layoutResId, data) 
> ```
> 
> **基本加载更多列表适配器**
> 
> ```kotlin
> 导入 androidx.annotation.LayoutRes
> 导入 com.chad.library.adapter.base.module.LoadMoreModule
> 
> 抽象 类 BaseLoadMoreListAdapter < T >(@LayoutRes private  val  layoutResId :  Int , data :  MutableList < T > ? = null) : BaseListAdapter<T>(layoutResId, data), LoadMoreModule
> ```
> 
> **基绑定列表适配器**
> 
> ```kotlin
> 导入 androidx.annotation.LayoutRes
> 导入 androidx.databinding.ViewDataBinding
> 导入 com.chad.library.adapter.base.BaseQuickAdapter
> 导入 com.chad.library.adapter.base.viewholder.BaseDataBindingHolder
> 
> 抽象 类 BaseBindingListAdapter < T , Binding  :  ViewDataBinding >(@LayoutRes private  val  layoutResId :  Int , data :  MutableList < T > ? = null) : BaseQuickAdapter<T, BaseDataBindingHolder<Binding>>(layoutResId, data)
> ```



> 这是我在用的样子，应该能帮助到你
> 
> **业务adapter**
> 
> ```kotlin
> class TestAdapter : BaseListAdapter<UserBean>(R.layout.item_xxxxx) {
> 
>     override fun convert(holder: BaseViewHolder, item: UserBean) {
>         //holder.setText(R.id.xxx,"")
>         //holder.setImageResource(R.id.xxx,R.drawable.xxx)
>         //todo 
> 
>     }
> }
> ```
> 
> **BaseListAdapter**
> 
> ```kotlin
> import androidx.annotation.LayoutRes
> import com.chad.library.adapter.base.BaseQuickAdapter
> import com.chad.library.adapter.base.viewholder.BaseViewHolder
> 
> abstract class BaseListAdapter<T>(@LayoutRes private val layoutResId: Int, data: MutableList<T>? = null) : BaseQuickAdapter<T, BaseViewHolder>(layoutResId, data) 
> ```
> 
> **BaseLoadMoreListAdapter**
> 
> ```kotlin
> import androidx.annotation.LayoutRes
> import com.chad.library.adapter.base.module.LoadMoreModule
> 
> abstract class BaseLoadMoreListAdapter<T>(@LayoutRes private val layoutResId: Int, data: MutableList<T>? = null) : BaseListAdapter<T>(layoutResId, data), LoadMoreModule 
> ```
> 
> **BaseBindingListAdapter**
> 
> ```kotlin
> import androidx.annotation.LayoutRes
> import androidx.databinding.ViewDataBinding
> import com.chad.library.adapter.base.BaseQuickAdapter
> import com.chad.library.adapter.base.viewholder.BaseDataBindingHolder
> 
> abstract class BaseBindingListAdapter<T, Binding : ViewDataBinding>(@LayoutRes private val layoutResId: Int, data: MutableList<T>? = null) : BaseQuickAdapter<T, BaseDataBindingHolder<Binding>>(layoutResId, data)
> ```

啊，非常感谢，一目了然，还有一个问题想问下，点击事件的监听你是写在哪的，也在adapter类里还是在activity里😊

**Comment by songdehuai** [comment]
应该在哪里，就在哪里。比如你要在 RecyclerView里实现一个点击变色的功能，除此之外没有任何业务，那么他就写在adapter里面，挺好的。不过大部分业务场景都是需要做跳转、网络请求等，这时候显然不应该在adapter里做业务。

**Comment by SaltedFish-Extreme** [comment]
@songdehuai 老哥，请问你用过侧滑删除的功能吗？侧滑删除后怎么获取到这条item数据，他的BaseViewHolder没有相关的方法，position也获取不到对应的item😂
