### ISSUE TITLE
endView出现2次

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#357]
![image](https://cloud.githubusercontent.com/assets/7565399/18741569/84f48d3a-80e2-11e6-8e68-f79a5f81bd00.png)

切换账号再登录进来进出现这种情况，刷新不起作用，关掉程序再进了就正常了。

**Comment by CymChad** [comment]
你之前的尾部没有rm。

**Comment by wuzhaohui026** [comment]
怎么使用了remove掉了尾部的布局，再次下拉到底的时候就不出现了
