### ISSUE TITLE
可否在源码中加上注释。。

### ISSUE THREAD

**Issue by locHiH** [CymChad/BaseRecyclerViewAdapterHelper#358]
说deprecated就deprecated了。。有点任性啊。。那替换方案呢。。开放出来的api是用来干嘛的呢。。
一脸懵逼

**Comment by CymChad** [comment]
恩，好的，多谢建议。你是指哪一个？

**Comment by locHiH** [comment]
额，没问题了，我才更新没多会儿，对改动有点懵逼  =。=     btw，addOnItemTouchListener 可否以接口形式暴露，抽象类差点逼死强迫症啊。。SimpleOnItemClick前面那个 大写的 S ...  不说了  我搬砖去了，叨扰叨扰

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/18777139/301dde24-81a0-11e6-91e9-611eca007c7c.png)
![image](https://cloud.githubusercontent.com/assets/7698209/18777147/3b93e794-81a0-11e6-82e8-5e2e756effda.png)
有注释哦。

**Comment by locHiH** [comment]
suika...被 android studio惯坏了   close了吧   谢谢

**Comment by CymChad** [comment]
好的，以后多多提建议，只有用户的建议才能让这个库更加好用。

**Comment by locHiH** [comment]
kk
