### ISSUE TITLE
库为啥找不到呢，已经加了jitpack了

### ISSUE THREAD

**Issue by zhangshuliang** [CymChad/BaseRecyclerViewAdapterHelper#3591]
![image](https://user-images.githubusercontent.com/16489590/149716423-c77952b8-a07c-4f8b-a6a1-9f4175bd7190.png)

**Comment by zhangshuliang** [comment]
![image](https://user-images.githubusercontent.com/16489590/149716526-d3896d8a-70b4-44d9-a6d9-5ec7ec2069a0.png)

**Comment by SaltedFish-Extreme** [comment]
你导入的是`'com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.7'`吗？
如果没问题的话，你应该还需要在旧版as中的allprojects下的repositories中也加入
`maven { url "https://jitpack.io" }`
新版的as是在settings.gradle里配置

**Comment by zhangshuliang** [comment]
> 你导入的是`'com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.7'`吗？ 如果没问题的话，你应该还需要在旧版as中的allprojects下的repositories中也加入 `maven { url "https://jitpack.io" }` 新版的as是在settings.gradle里配置

非常感谢，我是新版as，没有在setting.gradle加配置，加上就ok了

**Comment by SaltedFish-Extreme** [comment]
> 非常感谢，我是新版as，没有在setting.gradle加配置，加上就ok了

没事，能帮到你就好了😉
