### ISSUE TITLE
替换emptyview

### ISSUE THREAD

**Issue by weavey** [CymChad/BaseRecyclerViewAdapterHelper#36]
作者你好，我又来提一波意见了。源码里面你只给出了setEmptyView的方法，你的本意可能只是在空数据的时候给用户一个友好的界面提示，但是网络错误以及正在加载的view我也想直接用你的setEmptyView(),发现有一种情况，就是当发送网络请求我传了一个正在加载的页面进去，请求成功发现没数据，我想替换emptyView，这时候直接setEmptyView是没效果的，最后发现得再重新set一次adpter才有效果，这样虽然能替换emptyView，但感觉这样用总不太好。所以在想，是否能对emptyView定义更广一些，不仅仅是emptyView，而是能传任何我想要的view。

**Comment by CymChad** [comment]
我建议你可以这样试试，setEmptyView后然后用adapter.notifyDataSetChanged();。

**Comment by weavey** [comment]
这样试过了，也是没效果

**Comment by CymChad** [comment]
行，我这边看下有什么好的解决方案。

**Comment by weavey** [comment]
可以  加油  (￣︶￣)

**Comment by CymChad** [comment]
mQuickAdapter.notifyItemChanged(0);

**Comment by CymChad** [comment]
这样可以，我刚试过

**Comment by weavey** [comment]
可以  我试一下

**Comment by weavey** [comment]
可以 行  再次感谢一下大神！！！

**Comment by CymChad** [comment]
那我就关闭bug了哦

**Comment by weavey** [comment]
好像还有问题  第三次setEmptyView 又没效果了

**Comment by CymChad** [comment]
解决了吗？

**Comment by weavey** [comment]
没有。。。 notifyItemChanged(0)，为什么第三次setemptyView就无效了。我的写法是这样的
实例化Adapter的时候 就直接传了空的list进去，然后开始从后台拿数据，这时候setEmptyView，传了一个正在加载的view进去。访问后台成功后，发现数据为空，再setEmptyView（），传一个表示无数据的view，这时候用notifyItemChanged(0)有效。后面重新访问网络，我再setEmptyView（），让正在加载重新显示出来，这时候就无效了，emptyView还是第二次传的那个无数据的view。

**Comment by CymChad** [comment]
哦，我这边再看看。

**Comment by CymChad** [comment]
我试了下，确实只能两种不同的布局切换，我怀疑是RecyclerView，缓存的问题。由于这是RecyclerView的原始API所以我这边也不好修改。

**Comment by CymChad** [comment]
实在不好意思。没有能帮助到你。

**Comment by weavey** [comment]
没事没事  老是麻烦你帮忙看问题我都不好意思  确定问题出在哪才关键 那只能再寻找别的方法替代

**Comment by CymChad** [comment]
恩，可以重新set adapter。
