### ISSUE TITLE
as 升级到最新版本bumblebee getItemViewType() getLayoutPostion() 找不到了

### ISSUE THREAD

**Issue by rcj60560** [CymChad/BaseRecyclerViewAdapterHelper#3601]
@benoitf @ravidsrk @elfman @beiliubei

**Comment by ender115** [comment]
有木有大神知道怎么解决此问题

**Comment by HelloAnyu** [comment]
我也遇到了这个问题

**Comment by rcj60560** [comment]
@HelloAnyu 我怀疑是不是我升级了最新的as 之前的都是好的，然后突然就爆红了
我重新下载了3.0.4的版本打开 也是可以点出来
就原来的项目不行了。。
你啥情况

**Comment by HelloAnyu** [comment]
@rcj60560 我情况跟你一样，我现在还没进行as的回退操作

**Comment by HelloAnyu** [comment]
我现在是不管库的版本是多少，在最新版的as上都找不到方法

**Comment by rcj60560** [comment]
@HelloAnyu 晚上回去我在试试，昨晚太晚了没来得及弄，
你as怎么回退啊 这个黄蜂简直有毒 一更新就爆红了 但是不影响运行，但是就是点不进去了奇怪

**Comment by HelloAnyu** [comment]
去官网下一个老版本就行了，我用的4.2的 没事

**Comment by Evillive4** [comment]
我也遇到了这个问题，BaseViewHolder里面去掉了getLayoutPostion方法，我现在解决了，在convert里面调用getItemPosition方法传对象进去即可获取到position

**Comment by itwangyong** [comment]
解决了吗 我看了源码 没有什么问题 就是继承关系 不知道为什么继承下来的方法找不到  
个人理解为编译器对kotlin和java兼容问题导致  因为使用kotlin编码是可以调用到的

**Comment by rcj60560** [comment]
@itwangyong 回退as 4.2.2 没问题 
不知道原因

**Comment by GXSZone** [comment]
我也遇到了

**Comment by Seasonxx** [comment]
itemView也红的，但是编译、运行、打包，都不报错

**Comment by 50kg** [comment]
+1 可以编译

**Comment by weiyang-6539** [comment]
> 

这些方法本就不是BaseViewHolder的，是父类RecyclerView.ViewHolder的，应该不是库的问题而是as 的问题

**Comment by rcj60560** [comment]
@weiyang-6539 回退到4.2.2先开发着吧 我感觉大黄本版本问题还是蛮多

**Comment by weiyang-6539** [comment]
> 解决了吗 我看了源码 没有什么问题 就是继承关系 不知道为什么继承下来的方法找不到 个人理解为编译器对kotlin和java兼容问题导致 因为使用kotlin编码是可以调用到的

测试了写了一个一样的类，可以访问，库里面的那个就是访问不到

**Comment by qhzzl** [comment]
kt 没问题 java 不行

**Comment by wflian** [comment]
同问。一样的问题。吐血

**Comment by AngelBo** [comment]
解决了吗大家

**Comment by rcj60560** [comment]
> 解决了吗大家

我回退了as版本。。。到4.x 没用那个大黄蜂版本的

**Comment by luyuan11233** [comment]
我也是升级了，一堆红 好难受

**Comment by rcj60560** [comment]
> 我也是升级了，一堆红 好难受

as回退到4.2的好像就好了

**Comment by rcj60560** [comment]
> 不回退不行吗？ @rcj60560

 我试了不太行 我直接回退了

**Comment by AndyYw** [comment]
kotlin写的类可以访问，java的不能

**Comment by DarkerWanglei** [comment]
int itemPosition = getAdapter().getItemPosition(entity); 我用的这个方法

**Comment by DarkerWanglei** [comment]
int itemPosition = getAdapter().getItemPosition(entity); 我用的这个方法
