### ISSUE TITLE
3.0.7 版本  DataBindingUtil.bind(viewHolder.itemView);中 viewHolder.itemView 报错

### ISSUE THREAD

**Issue by LXZCoder** [CymChad/BaseRecyclerViewAdapterHelper#3603]
3.0.7 版本 
public class InviteFriendsDataItemProvider extends BaseItemProvider<InviteFriendsMultiEntity> {

    @Override
    public int getItemViewType() {
        return InviteFriendsMultiEntity.INVITE_FRIENDS_TYPE_DATA;
    }

    @Override
    public int getLayoutId() {
        return R.layout.item_provider_invite_friends_data;
    }

    @Override
    public void onViewHolderCreated(@NotNull BaseViewHolder viewHolder, int viewType) {
        DataBindingUtil.bind(viewHolder.itemView);
    }

    @Override
    public void convert(@NonNull BaseViewHolder baseViewHolder, InviteFriendsMultiEntity inviteFriendsMultiEntity) {
        ItemProviderInviteFriendsDataBinding binding = baseViewHolder.getBinding();
        if (binding != null) {
            binding.setData(inviteFriendsMultiEntity.getInvitationBean());
            binding.executePendingBindings();
        }
    }
}

  DataBindingUtil.bind(viewHolder.itemView); 中 viewHolder.itemView 报错

**Comment by SheepYang1993** [comment]
@LXZCoder 怎么解决这个问题的？

**Comment by stone-gao** [comment]
很奇怪 使用android studio Arctic fox 以上版本都会报错 这个版本及其一下都没问题。哪位大神知道原因

**Comment by stone-gao** [comment]
> 这个

使用android studio Arctic fox 版本不会报错 具体问题也在纳闷中...

**Comment by HeavenWen** [comment]
> @LXZCoder 怎么解决这个问题的？

解决了吗

**Comment by HeavenWen** [comment]
> > 这个
> 
> 使用android studio Arctic fox 版本不会报错 具体问题也在纳闷中...

解决了吗

**Comment by kekegdsz** [comment]
？？？？
