### ISSUE TITLE
分组伸缩栏问题

### ISSUE THREAD

**Issue by personalxia** [CymChad/BaseRecyclerViewAdapterHelper#361]
首先感谢作者的辛勤付出，我有个问题想问下，就是在使用折叠效果的时候，我的第二层级嵌套了一个recyclerView进去，点击展开的时候这个recyclerview里面的内容显示不全，请问有什么办法可以解决吗？

**Comment by CymChad** [comment]
你可以参考一下 #354

**Comment by elfman** [comment]
你试下对内层的recyclerview调用requestLayout()方法强制刷新看看

**Comment by personalxia** [comment]
我在想这个显示不全会不会是因为这个分组伸缩览展开的时候对里面的RecyclerView的高度做了限制？

**Comment by personalxia** [comment]
我试了好多办法，重写LayoutManager，去重新计算RecyclerView所有子项的高度，然后对他进行重新布局，结果还是跟之前一样，只能显示3-4个子项，请帮忙查查

**Comment by elfman** [comment]
expand的过程只修改了内部数据集mData，然后调用notifyInsert通知recyclerView进行重绘和加载动画，并没有对View进行操作。
我觉得你这个错误应该是RecyclerView的高度没有确定好吧，跟LayoutManager应该没什么关系，LayoutManager管理的是内部项目。你的RecyclerView的高度是怎么定的？是固定值还是wrap_content？

**Comment by personalxia** [comment]
@elfman 谢谢你耐心的解答，这个问题我已完美解决

**Comment by dante312** [comment]
@personalxia 遇到同样问题，可以提供解决方法吗，谢谢！

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by personalxia** [comment]
@dante312 你是为什么要使用嵌套recyclerview呢

**Comment by dante312** [comment]
@personalxia 需求需要做一个极其复杂的页面，既然已改recyclerview,不想换listview

**Comment by personalxia** [comment]
@dante312 具体是什么样一个复杂的页面呢？
