### ISSUE TITLE
上拉加载更多问题

### ISSUE THREAD

**Issue by zou1755815609** [CymChad/BaseRecyclerViewAdapterHelper#362]
只有第一次上拉加载才会回调onLoadMoreRequested方法，从第二次以后都不会回调onLoadMoreRequested

**Comment by CymChad** [comment]
贴出你的代码

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD  ， 这是文档地址，demo也有使用代码。

**Comment by CymChad** [comment]
就几种情况，一个是下拉刷新你可以使用setNewData这个方法的意思就是清空之前的list填充新的list数据,一个是还有更多数据使用addData这个方法的意思就是追加list更多数据并且通知还有下一页数据，最后就是加载完毕loadComplete这个方法就是关闭掉加载监听，如果你要加一个尾部提示的话可以使用addFooterView,还有一种情况就是如果断网了，你可以调用showLoadMoreFailedView();这个方法会自动添加一个异常的item，点击可以继续上拉加载。
