### ISSUE TITLE
我的kotlin最高到1.3.72，无法使用3.x，怎么办？

### ISSUE THREAD

**Issue by yaojunyi** [CymChad/BaseRecyclerViewAdapterHelper#3620]
我项目中kotlin目前是1.3.72，使用3.x的brvah有报错提示module-was-compiled-with-an-incompatible-version-of-kotlin，
当我将kotlin升级到1.4.x时 再次编译要求升级gradle到5.x，但因为项目中其他lib在gradle和gradle plugin高版本无法编译通过，所以由此矛盾。有什么办法解决吗？（不想用brvah2.x 因为BaseItemProvider没有onCreateViewHolder回调）

**Comment by liangjingkanji** [comment]
换个在维护的库 [BRV](https://github.com/liangjingkanji/BRV/)

**Comment by limuyang2** [comment]
只能更新版本，项目总是要向前走的
