### ISSUE TITLE
项目废了？运行不起来？

### ISSUE THREAD

**Issue by wangzhankai** [CymChad/BaseRecyclerViewAdapterHelper#3628]
下载项目运行报错

**Comment by Uimix** [comment]
依赖不了了，项目运行不了了，请问解决了吗？

**Comment by wangzhankai** [comment]
解决了，bindingAdapter换掉就行了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月21日(星期四) 下午2:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 项目废了？运行不起来？ (Issue #3628)





 
依赖不了了，项目运行不了了，请问解决了吗？

**Comment by wangzhankai** [comment]
------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月21日(星期四) 下午2:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 项目废了？运行不起来？ (Issue #3628)





 
依赖不了了，项目运行不了了，请问解决了吗？

**Comment by Uimix** [comment]
> 解决了，bindingAdapter换掉就行了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月21日(星期四) 下午2:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 项目废了？运行不起来？ (Issue #3628) 依赖不了了，项目运行不了了，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



> 

怎么处理？

**Comment by wangzhankai** [comment]
报错的，重写方法，然后把bindingAdapterPosition换成layoutPosition

**Comment by limuyang2** [comment]
重新尝试3.0.8，推荐使用4.0.0
