### ISSUE TITLE
v2.1.6  切换adapter 添加header  导致 SimpleOnItemClick()  position错位 

### ISSUE THREAD

**Issue by leavesfallenlord** [CymChad/BaseRecyclerViewAdapterHelper#363]
你好，我有一个页面有三个选项卡  每个选项卡都对应一个带有header 的adapter 在选项卡切换了之后 发现header 也响应了SimpleOnItemClick()  事件 群主帮忙看下 这个是什么问题 谢谢

**Comment by CymChad** [comment]
贴出具体代码。如果可以的话录制一个gif，这样更加便于bug的查找和修复。

**Comment by leavesfallenlord** [comment]
findViewById(R.id.textview1).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mContentAdapter.removeAllHeaderView();
                mContentAdapter=new Adapter1(list1);
                mRv.setAdapter(mContentAdapter);
                mContentAdapter.addHeaderView(mHeaderView);
            }
        });
        findViewById(R.id.textview2).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mContentAdapter.removeAllHeaderView();
                mContentAdapter = new Adapter2(list2);
                mRv.setAdapter(mContentAdapter);
                mContentAdapter.addHeaderView(mHeaderView);
            }
        });
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(MainActivity.this);
        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        mRv.setLayoutManager(linearLayoutManager);
        mContentAdapter = new Adapter1(list1);
        mHeaderView=View.inflate(MainActivity.this, R.layout.layout_header, null);
        mContentAdapter.addHeaderView(mHeaderView);
        mContentAdapter.openLoadMore(10);
        mContentAdapter.setOnLoadMoreListener(this);
        mRv.setAdapter(mContentAdapter);
        mRv.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void SimpleOnItemClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                Toast.makeText(MainActivity.this, "点击了条目  " + i, Toast.LENGTH_SHORT).show();
                Log.i("@@@ 点击了  ",i+"");
            }
        });

**Comment by AllenCoder** [comment]
你好，这种情况下，建议你先修改你的代码, 每次点击你都重新创建了一个adapter对象，完全没有必要，你可以在headview 点击中 ，切换新的数据源，mQuickAdapter.setNewData(list);
通知刷新。再查看是否点击 headview 的 bug 还会复现。

**Comment by leavesfallenlord** [comment]
因为我的adapter 里都是不同的布局 差别很大  你的意思使用 BaseMultiItemQuickAdapter  么

**Comment by AllenCoder** [comment]
1. 采用BaseMultiItemQuickAdapter也可以解决
2. 或者你提前创建好对象不要每次频繁创建
3.Recyclerview 点击分发到相应的 adapter 会自己判断处理
