### ISSUE TITLE
3.0.0-beta10  jitpack链接错误

### ISSUE THREAD

**Issue by junyou131** [CymChad/BaseRecyclerViewAdapterHelper#3641]
https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/3.0.0-beta10
已经不存在了，我手里有一个老项目，是3.0.0-beta10版本，但是已经无法下载资源，是否可以提供该版本arr？

**Comment by limuyang2** [comment]
jitpack 经常抽风。可以更新下最新版本
