### ISSUE TITLE
两个RecylcyView嵌套 内容会错乱 ，3.0.6

### ISSUE THREAD

**Issue by pengjunshan** [CymChad/BaseRecyclerViewAdapterHelper#3649]
两个RecylcyView嵌套 内容会错乱， 3.0.6

**Comment by pengjunshan** [comment]
// 父-详情页多个对比结果table
    var mTableItemAdapter =
        object :
            BaseQuickAdapter<AnalysisDetailBean, BaseDataBindingHolder<ItemAnalysisTableItemBinding>>(R.layout.item_analysis_table_item) {
            override fun convert(holder: BaseDataBindingHolder<ItemAnalysisTableItemBinding>, item: AnalysisDetailBean) {
                val binding = holder.dataBinding
                binding?.apply {
                    mTime.text = item.time
                    mSonRecyclerView.layoutManager = LinearLayoutManager(application)
                    mSonRecyclerView.adapter = mTableSonAdapter
                    mTableSonAdapter.setList(item.data)
                    executePendingBindings()
                }
            }
        }

    // 子-详情页气体集合
    var mTableSonAdapter =
        object :
            BaseQuickAdapter<DataBean, BaseDataBindingHolder<ItemAnalysisTableBinding>>(R.layout.item_analysis_table) {
            override fun convert(holder: BaseDataBindingHolder<ItemAnalysisTableBinding>, item: DataBean) {
                val binding = holder.dataBinding
                binding?.apply {
                    bean = item
                    mOnLine.text = item.onlineData
                    executePendingBindings()
                }
            }
        }

**Comment by limuyang2** [comment]
不建议Rv嵌套
