### ISSUE TITLE
我把 androidstudio升级到2.2 报错 Failed to crunch file 

### ISSUE THREAD

**Issue by Freedomhxb** [CymChad/BaseRecyclerViewAdapterHelper#365]
一直解决不了 2个错误，网上能搜到的答案都用了，大神能否帮个忙，看下，谢谢啦
Failed to crunch file 

具体内容
 Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file        F:\android\androidStudio\androidStudioProjects\BaseRecyclerViewAdapterHelper-master\app\build\intermediates\exploded-aar\BaseRecyclerViewAdapterHelper-master\material-spinner-1.0.5\unspecified\res\drawable-xxhdpi-v4\ms__shadow_background.9.png into F:\android\androidStudio\androidStudioProjects\BaseRecyclerViewAdapterHelper-master\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\ms__shadow_background.9.png

Error:Execution failed for task ':app:mergeDebugResources'.
> Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file F:\android\androidStudio\androidStudioProjects\BaseRecyclerViewAdapterHelper-master\app\build\intermediates\exploded-aar\BaseRecyclerViewAdapterHelper-master\material-spinner-1.0.5\unspecified\res\drawable-xxhdpi-v4\ms__shadow_background.9.png into F:\android\androidStudio\androidStudioProjects\BaseRecyclerViewAdapterHelper-master\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\ms__shadow_background.9.png

**Comment by elfman** [comment]
可能是文件名（包括路径）太长了，把工程移到F盘根目录试试，windows路径名不能超过240个字符

**Comment by Freedomhxb** [comment]
大神果然厉害。。。。。小弟还有一事不太明白
  public void addData(int position, T data) {
        if(0 <= position && position < this.mData.size()) {
            this.mData.add(position, data);
            this.notifyItemInserted(position);
            this.notifyItemRangeChanged(position, this.mData.size() - position);
        } else {
            throw new ArrayIndexOutOfBoundsException("inserted position most greater than 0 and less than data size");
        }
    }

对于这个方法，如果adpter 中datalist原来的size=5；现在我 addData(5，data)，那么就会抛出异常，不应该直接 将data添加到datalist的队尾吗？还请大神指导下。
 IndexOutOfBoundsException    if location < 0 || location > size()

**Comment by elfman** [comment]
等下我们加个`addData(T data)`方法让你可以直接添加到列表的最末端。或者你自己写个也行的，`List.add(T data)`可以直接加到尾端

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.7' 这个版本新增了addData(T data)方法

**Comment by Freedomhxb** [comment]
嗯。大神好体贴，谢谢

**Comment by jimrueaster** [comment]
移动工程以后果然不会报错了，谢谢大神

**Comment by jimrueaster** [comment]
移动工程以后果然不会报错了，谢谢大神

**Comment by jimrueaster** [comment]
移动工程以后果然不会报错了，谢谢大神
