### ISSUE TITLE
比较老版本的无法拉取了吗？

### ISSUE THREAD

**Issue by DoveBarnett** [CymChad/BaseRecyclerViewAdapterHelper#3651]
前几天还运行的好好的，昨天突然拉不下来了，2.9.30以下的好像都不行了，是因为什么呢？

**Comment by FW883** [comment]
同问

**Comment by FW883** [comment]
我干脆修改代码升到最新版本算了

**Comment by DoveBarnett** [comment]
> 

跨度太大了不建议，而且有些方法内部是有变化的，比如2.9.15里面的setVisible等同于2,9,30里面的setGone

**Comment by zhoumoumou123year** [comment]
> 前几天还运行的好好的，昨天突然拉不下来了，2.9.30以下的好像都不行了，是因为什么呢？
[https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/](https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/),这里看具体的版本号，看他是否删除了对应的pom、aar、jar文件。最低好像[https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.26/](https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.26/)，反正找一个能用的版本就行。

**Comment by limuyang2** [comment]
抱歉，由于以前版本并不是发不到中央仓库的，所以有可能遇到包丢失的问题，从v4开始，BRVAH有自己的中央仓库了，不会再出现历史版本无法引入的问题，并且也无需配置三方仓库地址了
