### ISSUE TITLE
谁能把demo打包成apk嘛 我打包总是失败？太奇怪了

### ISSUE THREAD

**Issue by Yanruplus** [CymChad/BaseRecyclerViewAdapterHelper#3656]
如题 太感谢了！！

**Comment by Stonejxn** [comment]
你有Demo了嘛 ，Demo就运行不起来

**Comment by skyofsky** [comment]
[app-debug.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/9248848/app-debug.zip)

**Comment by limuyang2** [comment]
感谢您的反馈，后续会有v4的demo
