### ISSUE TITLE
android 11 运行app点击首页闪退

### ISSUE THREAD

**Issue by powerzd** [CymChad/BaseRecyclerViewAdapterHelper#3658]
步骤：
复现步骤，clone项目到本地后编译，运行在版本为android 11 的机器上，点击首页闪退。
报错：
 java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/app/~~vzizBRbi_zRBGeOckN_aLw==/com.chad.baserecyclerviewadapterhelper-98v0Y7KVlWSTBOuYnH-HEw==/base.apk)

**Comment by BugMen** [comment]
+1

**Comment by Nikotesla-s** [comment]
recyclerview使用1.2.1版本就可以了

**Comment by wangdaban** [comment]
> recyclerview使用1.2.1版本就可以了

已解决  多谢
