### ISSUE TITLE
3.0.7版本LoadMoreModule实现有问题

### ISSUE THREAD

**Issue by Stonejxn** [CymChad/BaseRecyclerViewAdapterHelper#3659]
这个版本的LoadMoreModule实现之后，老提示要实现这个方法
     @NonNull
        @Override
        public BaseLoadMoreModule addLoadMoreModule(@NonNull BaseQuickAdapter<?, ?> baseQuickAdapter) {
            return null;
        }
实现以后老报错，提示这个方法找不到。
然后查看官方Demo，是这么写的，迁移过来
 @NonNull
    @Override
    public BaseLoadMoreModule addLoadMoreModule(@NonNull BaseQuickAdapter<?, ?> baseQuickAdapter) {
        return LoadMoreModule.super.addLoadMoreModule(baseQuickAdapter);
    }

然后运行继续报错，如下
错误: 无法直接访问LoadMoreModule中的抽象方法 addLoadMoreModule(BaseQuickAdapter<?,?>)
            return LoadMoreModule.super.addLoadMoreModule(baseQuickAdapter);

**Comment by Stonejxn** [comment]
3.0.7版本的LoadMoreModule到底能不能使用，麻烦大神给指导一下！！

**Comment by Stonejxn** [comment]
还有就是3.0.7版本中的helper.getLayoutPosition()这个方法一直爆红，但是可以使用，好多方法掉不出来，还有就是helper.getItemView()也不能使用了。

**Comment by mahuaqing** [comment]
> 还有就是3.0.7版本中的helper.getLayoutPosition()这个方法一直爆红，但是可以使用，好多方法掉不出来，还有就是helper.getItemView()也不能使用了。

使用3.0.6

**Comment by zhanghang123456789** [comment]
同问 , 这个版本的加载更多怎么用的?

**Comment by gaoleilvzss** [comment]
> 

看下源码接口里已经有实现了，copy过来就行了。
return new BaseLoadMoreModule(baseQuickAdapter);

**Comment by limuyang2** [comment]
尝试 v4，beta01版本
