### ISSUE TITLE
3.0版本以后无法获取到helper.getlayoutpostion 以及helper.getadapterPostion方法,2.9.50版本还能获取到

### ISSUE THREAD

**Issue by billdizl** [CymChad/BaseRecyclerViewAdapterHelper#3660]
3.0版本以后无法获取到helper.getlayoutpostion 以及helper.getadapterPostion方法,2.9.50版本还能获取到
recyclview版本是1.2.1版本

**Comment by caishuwei** [comment]
是的，很神奇，用kotlin写的adapter没问题，用java写的adapter里面，helper转换成RecyclerView.ViewHolder会报错，无法识别出继承关系。

**Comment by suoyulee** [comment]
大佬 解决了吗 我也遇到了同样问题

**Comment by suoyulee** [comment]
> 是的，很神奇，用kotlin写的adapter没问题，用java写的adapter里面，helper转换成RecyclerView.ViewHolder会报错，无法识别出继承关系。
你好 最后怎么解决的呢 我也遇到了同样的问题

**Comment by caishuwei** [comment]
@suoyulee 没找到解决方法，就算报错代码跑起来也是正常的，所以应该是编辑器没有正确识别出继承关系，我把代码拉下来后将BaseViewHolder用java重写了一下打包成aar放到项目里面使用就不报错了，打算等以后修复了在改成动态依赖。你直接用3.0之前java版本的BaseViewHolder替换当前版本的BaseViewHolder打包成aar使用应该也是可以的。缺点是不知道为何打包成aar后adapter写监听lambda不自动提示了。

**Comment by xuxinjiang** [comment]
> 后
为何你如此优秀，这个库已经不在维护了，含泪放弃吗

**Comment by limuyang2** [comment]
更新 3.0.14
