### ISSUE TITLE
UpFetch有没有文档啊

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#3663]
一直没更新UpFetch的文档，啥时候更一下呢，DEMO也出现了点击模块闪退的问题，尽快修复一下吧

**Comment by liangjingkanji** [comment]
也许你应该可以换个在维护的框架[BRV](https://github.com/liangjingkanji/BRV)

**Comment by limuyang2** [comment]
v3的UpFetch有严重缺陷，不推荐使用。

v4对其进行了完善，向上、向下加载获得了同等能力
