### ISSUE TITLE
2.9.45-androidx  NullPointerException

### ISSUE THREAD

**Issue by jijiangrui** [CymChad/BaseRecyclerViewAdapterHelper#3665]
Attempt to invoke interface method 'void com.chad.library.adapter.base.BaseQuickAdapter$RequestLoadMoreListener.onLoadMoreRequested()' on a null object reference com.chad.library.adapter.base.BaseQuickAdapter$7.run(BaseQuickAdapter.java:1465)

#2 main

java.lang.NullPointerException

Attempt to invoke interface method 'void com.chad.library.adapter.base.BaseQuickAdapter$RequestLoadMoreListener.onLoadMoreRequested()' on a null object reference

1 com.chad.library.adapter.base.BaseQuickAdapter$7.run(BaseQuickAdapter.java:1465)
2 android.os.Handler.handleCallback(Handler.java:938)
3 android.os.Handler.dispatchMessage(Handler.java:99)
4 android.os.Looper.loop(Looper.java:257)
5 android.app.ActivityThread.main(ActivityThread.java:8215)
6 java.lang.reflect.Method.invoke(Native Method)
7 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
8 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by yangfeng1994** [comment]
在你的adapter里面，有实现LoadMoreModule 吗？
