### ISSUE TITLE
BaseSectionQuickAdapter的参数问题

### ISSUE THREAD

**Issue by qq71768174** [CymChad/BaseRecyclerViewAdapterHelper#3670]
使用BaseSectionQuickAdapter进行实现带头部的 Adapter，demo里面的参数格式是这样的
![QQ截图20220801091649](https://user-images.githubusercontent.com/37439911/182054810-d5bbf3b5-d568-45dc-b204-9fea57ad243e.png)
我的格式是：menuBean只嵌套一层
![image](https://user-images.githubusercontent.com/37439911/182054989-ad13d4a2-4e96-416e-8a55-b609b8dd47bf.png)
这个格式的数据可以设置带头部的adapter吗？

**Comment by zhuangzeqin** [comment]
同问；头部head 和childItemList  如何分组
