### ISSUE TITLE
您好，升级完Android studio2021.2.1 很多方法都报错，请问如何解决呢

### ISSUE THREAD

**Issue by rjyCoder** [CymChad/BaseRecyclerViewAdapterHelper#3671]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by rjyCoder** [comment]
baseViewHolder.getAdapterPosition()，baseViewHolder.getItemViewType()都获取不到了

**Comment by skyofsky** [comment]
> baseViewHolder.getAdapterPosition()，baseViewHolder.getItemViewType()都获取不到了

demo 升级recyclerview版本 试一下

**Comment by xuxinjiang** [comment]
recyclerview升级最新的1.2.1版本都没法获取

**Comment by jackandroid2016** [comment]
我也获取不到

**Comment by limuyang2** [comment]
尝试更下版本 3.0.8

**Comment by jackandroid2016** [comment]
还是不行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月26日 16:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CymChad/BaseRecyclerViewAdapterHelper] 您好，升级完Android studio2021.2.1 很多方法都报错，请问如何解决呢 (Issue #3671) |

尝试更下版本 3.0.8

**Comment by zuolq** [comment]
我也是Android studio升级到2021.2.1后就baseViewHolder.getAdapterPosition()，baseViewHolder.getItemViewType()都获取不到了

**Comment by fldevil** [comment]
我也遇到了同样的问题，方法获取不到，变红，但是运行不报错

**Comment by guominfang** [comment]
同样问题，ViewHolder中的itemView ide 爆红，但是运行没问题

**Comment by aiquantong** [comment]
同样问题，android studio 无法识别kotlin中super class的public fun。

**Comment by shenbengit** [comment]
`subprojects {
    project.configurations.all {
        //遍历所有依赖库，通过判断 requested.group 和 requested.name 来指定使用的版本
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'androidx.recyclerview' && requested.module.name == 'recyclerview') {
                //强制指定RecyclerView版本，解决多版本时，使用高版本方法，AS报红，但可正常运行问题。
                details.useVersion '1.2.1'
            }
        }
    }
}`
试试在根build.gradle 文件中添加，强制RecylerView依赖使用v1.2.1。

**Comment by jingzz1** [comment]
我也遇到这个问题，请问有办法解决吗？
