### ISSUE TITLE
4.0版本添加个 MultiITem 的Demo示例呗

### ISSUE THREAD

**Issue by felixcc** [CymChad/BaseRecyclerViewAdapterHelper#3674]
4.0版本添加个 MultiITem 的Demo示例呗

**Comment by fqingyang** [comment]
有4.0版本?

**Comment by limuyang2** [comment]
你好，4.0文档还未完全编写完成。4.0拥有极高的灵活度，并且与ConcatAdapter完美结合（目前三方库中首例）。
目前4.0的 API 相对稳定了，欢迎尝试。

demo 虽然不够完美，但已经覆盖有 4.0 的完整示例。可以切换至4.0_dev分支查看demo。
代码中注释也非常完善，希望对你有所帮助

**Comment by felixcc** [comment]
> 

谢谢！！！！

**Comment by limuyang2** [comment]
参考文档 [wiki](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki)
