### ISSUE TITLE
> baseViewHolder.getAdapterPosition()，baseViewHolder.getItemViewType()都获取不到了

### ISSUE THREAD

**Issue by xuxinjiang** [CymChad/BaseRecyclerViewAdapterHelper#3677]
> baseViewHolder.getAdapterPosition()，baseViewHolder.getItemViewType()都获取不到了

demo 升级recyclerview版本 试一下

_Originally posted by @skyofsky in https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/3671#issuecomment-1203559047_

**Comment by limuyang2** [comment]
更新 3.0.8 试试

**Comment by GAOli-cong** [comment]
我直接使用getItemPosition()方法，可以得到position

**Comment by daiwuzhou** [comment]
> 我用了笨方法，但是强迫症可以试下 自定义一个方法继承BaseViewHolder
> 
> ```
> open class BaseViewHolderEx (view: View) : BaseViewHolder(view) {
>     open fun  getItemView() : View {
>         return itemView
>     }
> 
>     open fun  getAdapterItemViewType() : Int {
>         return itemViewType
>     }
> }
> ```
> 
> 然后再Adapter里把BaseViewHolder替换成BaseViewHolderEx 其他在Java里爆红的可以在里面添加就ok了

我这边也是这样好像ViewHolder的方法，属性爆红

**Comment by billdizl** [comment]
kt版本有,java版本没有

**Comment by kimonic** [comment]
有人有办法解决这个Android Studio 版本2021.2.1在java中引用不到方法的问题么?

**Comment by limuyang2** [comment]
更新 3.0.14

**Comment by icecliffs** [comment]
牛逼

**Comment by shunlibest** [comment]
这是什么神奇BUG？有大佬能解释一下吗？为啥会存在这种情况？
