### ISSUE TITLE
4.0有没有BaseProviderMultiAdapter的DEMO了？

### ISSUE THREAD

**Issue by felixcc** [CymChad/BaseRecyclerViewAdapterHelper#3678]
如题

**Comment by limuyang2** [comment]
可以切换到 v4_dev 分支，查看demo。后续会补上文档

**Comment by limuyang2** [comment]
可以参考 HomeActivity 中的代码，HomeAdapter

**Comment by limuyang2** [comment]
参考文档 [wiki](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki)

**Comment by felixcc** [comment]
还想请教下，根据HomeAdapter是数据源的类型都是定死的。
比如上线前（1234）类型，上了线以后又下发了（5678）
onItemViewType 必须有一个else 返回int类型
这种时候就报错了，有没有什么好办法？

**Comment by felixcc** [comment]
@limuyang2 大佬回复下。

**Comment by felixcc** [comment]
> 

我想到用 QuickAdapterHelper 去解决多布局的问题，但是初始化还必传一个。

**Comment by limuyang2** [comment]
> 还想请教下，根据HomeAdapter是数据源的类型都是定死的。 比如上线前（1234）类型，上了线以后又下发了（5678） onItemViewType 必须有一个else 返回int类型 这种时候就报错了，有没有什么好办法？

这个属于业务问题了吧。onItemViewType 可以根据数据类型，返回对应的 layout ID
