### ISSUE TITLE
加载更多

### ISSUE THREAD

**Issue by shiheting** [CymChad/BaseRecyclerViewAdapterHelper#3679]
4.x怎么使用加载更多功能

**Comment by limuyang2** [comment]
使用 `QuickAdapterHelper`，参照 v4_dev 分支的demo，[AutoLoadMoreRefreshUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/v4_dev/app/src/main/java/com/chad/baserecyclerviewadapterhelper/activity/loadmore/AutoLoadMoreRefreshUseActivity.kt)

**Comment by limuyang2** [comment]
参考文档 [wiki] https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki
