### ISSUE TITLE
jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_leading_load_more.xml:2: error: resource dimen/dp_40

### ISSUE THREAD

**Issue by zgq105** [CymChad/BaseRecyclerViewAdapterHelper#3680]
Android resource linking failed
/Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_leading_load_more.xml:2: error: resource dimen/dp_40 (aka com.guoqiang.homepage:dimen/dp_40) not found.
/Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:2: error: resource dimen/dp_40 (aka com.guoqiang.homepage:dimen/dp_40) not found.
/Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:14: error: resource dimen/dp_4 (aka com.guoqiang.homepage:dimen/dp_4) not found.
/Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:21: error: resource dimen/dp_4 (aka com.guoqiang.homepage:dimen/dp_4) not found.
/Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:21: error: resource dimen/sp_14 (aka com.guoqiang.homepage:dimen/sp_14) not found.
error: failed linking file resources.

**Comment by zgq105** [comment]
> Android resource linking failed /Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_leading_load_more.xml:2: error: resource dimen/dp_40 (aka com.guoqiang.homepage:dimen/dp_40) not found. /Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:2: error: resource dimen/dp_40 (aka com.guoqiang.homepage:dimen/dp_40) not found. /Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:14: error: resource dimen/dp_4 (aka com.guoqiang.homepage:dimen/dp_4) not found. /Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:21: error: resource dimen/dp_4 (aka com.guoqiang.homepage:dimen/dp_4) not found. /Users/zgq/.gradle/caches/transforms-3/99e309e25dda7d065b4dec564bd16dc3/transformed/jetified-BaseRecyclerViewAdapterHelper-4.0.0-alpha6/res/layout/brvah_trailing_load_more.xml:21: error: resource dimen/sp_14 (aka com.guoqiang.homepage:dimen/sp_14) not found. error: failed linking file resources.

ScreenMatch官方屏幕适配方案，没问题了

**Comment by limuyang2** [comment]
请更新到 4.0.0-beta01
