### ISSUE TITLE
BaseSectionQuickAdapter 获取postion 错误

### ISSUE THREAD

**Issue by jeesk** [CymChad/BaseRecyclerViewAdapterHelper#3683]
我使用baseSeltionQucikAdapter + scrollView ， 在我滑动scrollbar 的时候， 需要获取到当前position, 但是这个位置是错误的， 有什么办法可以纠正过来？  我使用的是recycle , head只有一个textview , 但是每行的recycleview 有三个imageview, 这个时候我获取到的Postion 是错误的， 导致不能正确获取当前图片的position, 从而导致显示的内容是错误的。

**Comment by jeesk** [comment]
或者说换个思路， 能不能通过某个position 获取header 的postion ?

**Comment by limuyang2** [comment]
能简单画个图呢？
