### ISSUE TITLE
4.0版本没有了BaseNodeAdapter了，是后续会添加，还是就是去除了啊

### ISSUE THREAD

**Issue by Maxkinger** [CymChad/BaseRecyclerViewAdapterHelper#3686]

**Comment by limuyang2** [comment]
4.0暂时没有 BaseNodeAdapter，后续会考虑添加，因为实现方式还没想好。原有的3.x版本bug太多，实在不易维护

**Comment by Maxkinger** [comment]
好的，多谢

**Comment by aowoWolf** [comment]
> 4.0暂时没有 BaseNodeAdapter，后续会考虑添加，因为实现方式还没想好。原有的3.x版本bug太多，实在不易维护

那BaseBinderAdapter呢？目前项目中，基于该adapter进行了很多封装，项目主导也是使用该adapter

**Comment by jijiaxin** [comment]
现在这个库已经不维护了是吗
