### ISSUE TITLE
setEmptyView(XXX)无法设置高度

### ISSUE THREAD

**Issue by userPeng** [CymChad/BaseRecyclerViewAdapterHelper#369]
代码：
`
home_recycleview.setLayoutManager(new LinearLayoutManager(MainActivity.context));
        mAdapter = new HomeAdapter(R.layout.home_recycleview_item, mDatas);
 view_empty = getActivity().getLayoutInflater().inflate(R.layout.layout_empty, (ViewGroup) home_recycleview.getParent(), false);
        if (view_empty != null && view_empty.getParent() != null) {
            ((ViewGroup) view_empty.getParent()).removeView(view_empty);
        }
        mAdapter.setEmptyView(view_empty);
home_recycleview.setAdapter(mAdapter);
`

布局
`
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v4.widget.SwipeRefreshLayout
            android:id="@+id/swiperefreshlayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/home_recycleview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
        </android.support.v4.widget.SwipeRefreshLayout>

...

</FrameLayout>
`

现出现的的情况是：我在自己的empty布局里面设置match_parent并居中无法显示全屏

**Comment by CymChad** [comment]
你可以看下demo的代码。

**Comment by kubiAye** [comment]
我弄了好久 也按照Demo来写。也是不行，十分绝望

**Comment by CymChad** [comment]
demo是正常的呀。
