### ISSUE TITLE
4.x 版本 BaseMultiItemAdapter 怎么使用databinding

### ISSUE THREAD

**Issue by 287138531** [CymChad/BaseRecyclerViewAdapterHelper#3690]
按照demo中HomeAdapter 写法，会报错

错误: IncludedLayouts 在 ViewDataBinding 中是 protected 访问控制
    private static final androidx.databinding.ViewDataBinding.IncludedLayouts sIncludes;
                                                             ^

**Comment by limuyang2** [comment]
参考demo 中 `DataBindingAdapter`

**Comment by limuyang2** [comment]
可以直接使用 `DataBindingHolder` ，或者继承 `DataBindingHolder` 实现自己的 View Holder
