### ISSUE TITLE
4.0版本的兼容性问题建议

### ISSUE THREAD

**Issue by minwang1** [CymChad/BaseRecyclerViewAdapterHelper#3691]
**Describe the bug**
因为库使用了Databinding，而databindng的版本由Gradle plugin版本决定的，4.0.0-beta02使用了7.2.2，基本上老的项目就不能用了，并且还会和旧版本很库有依赖冲突

比如我的项目一开始无法编过，gradle报错也不正确。升级gradle版本才发现这个问题，报如下依赖错误
```
  1.  Dependency 'androidx.lifecycle:lifecycle-runtime-ktx:2.4.0' requires libraries and applications that
      depend on it to compile against version 31 or later of the
      Android APIs.

      :app is currently compiled against android-29.

      Recommended action: Update this project to use a newer compileSdkVersion
      of at least 31, for example 33.
```

感觉这个最好可以在wiki里指出来，引导大家使用合适的版本，避免浪费大家时间XD。

**Comment by limuyang2** [comment]
你项目的 Gradle 版本是多少呢？

**Comment by minwang1** [comment]
Android Gradle plugin 7.2.2
gradle 7.3.3

**Comment by limuyang2** [comment]
你好，麻烦尝试下 4.0.0-beta04

**Comment by limuyang2** [comment]
你好，为了ConcatAdapter使用GridLayoutManager，必须使用 `recyclerview 1.3.0` 版本。现在谷歌在新版本库中限制最低版本，以强制要求开发者进行API版本升级。

**Comment by minwang1** [comment]
@limuyang2 好的感谢，就像之前comment里写的，能把api要求wiki中指出就好了，问题先关了吧。
