### ISSUE TITLE
: ViewType: 0 found layoutResId，please use addItemType() first!

### ISSUE THREAD

**Issue by zhangmengjia** [CymChad/BaseRecyclerViewAdapterHelper#3693]
public class CheckListAdapter extends BaseMultiItemQuickAdapter<CheckListBean, BaseViewHolder> {

    public CheckListAdapter(List<CheckListBean> data) {
        super(data);
        addItemType(CheckListBean.TYPE_TIME, R.layout.item_check_title_view);
        addItemType(CheckListBean.TYPE_CONTENT, R.layout.item_check_list);
    }

    @Override
    protected void convert(@NonNull BaseViewHolder baseViewHolder, CheckListBean checkListBean) {

    }

运行时错误：  java.lang.IllegalArgumentException: ViewType: 0 found layoutResId，please use addItemType() first!

**Comment by zhangmengjia** [comment]
多类型处理不对

**Comment by Huping95** [comment]
请问解决了吗，我和你写的一模一样，数据什么的都还没开始处理，就一直报错，求教
