### ISSUE TITLE
分页最后一页加载了2次

### ISSUE THREAD

**Issue by SheepYang1993** [CymChad/BaseRecyclerViewAdapterHelper#3694]
4.0.0-beta02版本
快速下拉的时候，当trailingLoadState已经设置为NotLoading(endOfPaginationReached = true)时
TrailingLoadStateAdapter还是会调用loadAction()
导致分页最后一页加载了2次

**Comment by limuyang2** [comment]
麻烦贴一下你的代码片段

**Comment by limuyang2** [comment]
更新 beta13 再试试呢
