### ISSUE TITLE
ViewPager2 搭配 本苦Adapter使用，怎么获取item中的子View控件

### ISSUE THREAD

**Issue by camelsmith** [CymChad/BaseRecyclerViewAdapterHelper#3695]
版本2.9.26
本来想尝试调用 getViewByPosition() 获取，但调用前必须先绑定RecyclerView。
能否提供绑定 ViewPager2 的方法，便于该Api使用。

**Comment by limuyang2** [comment]
2.x版本已不维护，不会提供新功能了
