### ISSUE TITLE
4.0.0-beta02 使用EmptyView 宽度显示异常

### ISSUE THREAD

**Issue by PengShaoLei1997** [CymChad/BaseRecyclerViewAdapterHelper#3696]
问题：
设置启用EmptyView后，引用布局的layout_width为‘match_parent’，但是显示的实际宽度为GridLayoutManager(requireContext(), 3)中单个item的宽度，在3.0+的版本中使用未出现该问题。
启用空布局代码：
![image](https://user-images.githubusercontent.com/49141931/190987124-3c115501-376b-4490-a757-b720f98ca1c3.png)
布局：
![image](https://user-images.githubusercontent.com/49141931/190987244-375e9275-6403-4237-8941-eb779941dd7c.png)
样式：
![image](https://user-images.githubusercontent.com/49141931/190987580-d3033be6-5c45-477a-b6ce-2469c6760e93.png)

**Comment by limuyang2** [comment]
使用 `QuickGridLayoutManager`

**Comment by PengShaoLei1997** [comment]
十分感谢，您的回答完美解决了我的问题。
![image](https://user-images.githubusercontent.com/49141931/191472747-1a9e98f9-15de-42b1-8f23-280bc33d3dc2.png)

**Comment by PengShaoLei1997** [comment]
在使用过程中，我还注意到一点，在我注册adapter包括setOnItemClickListener在内等一系列监听的过程中，不能正确的在class中进行注册。

![image](https://user-images.githubusercontent.com/49141931/191473438-d9e2b752-ad6f-40bc-b395-3f5f79af534a.png)

后续这个地方会有改动吗？

**Comment by limuyang2** [comment]
你的类继承了

> 在使用过程中，我还注意到一点，在我注册adapter包括setOnItemClickListener在内等一系列监听的过程中，不能正确的在class中进行注册。（3.0+版本中未出现该问题）
> 
> ![image](https://user-images.githubusercontent.com/49141931/191473438-d9e2b752-ad6f-40bc-b395-3f5f79af534a.png)
> 
> 后续这个地方会有改动吗？

谢谢你的反馈，目前点击事件是使用的dsl实现的，class继承实现貌似有些问题，后续将改进

**Comment by eimori** [comment]
在使用LinearLayoutManager時，添加EmptyView同樣也有展開不完全的情況發生

**Comment by PengShaoLei1997** [comment]
> 在使用LinearLayoutManager時，添加EmptyView同樣也有展開不完全的情況發生

我这边尝试在LinearLayoutManager中使用EmptyView暂未发现展开不完全的情况存在。

**Comment by PengShaoLei1997** [comment]
> 

@limuyang2  感谢，刚刚已尝试更新至4.0.0-beta04版本，点击事件监听注册已恢复正常。
我在开发过程中发现了新的问题，使用4.0.0-beta04的版本也未能解决，详情已提交至issue。 #3697

**Comment by UserName-Haha** [comment]
> 在使用LinearLayoutManager時，添加EmptyView同樣也有展開不完全的情況發生

我也宇通和您同样的问题了，请问您解决了吗？盼复

**Comment by iostyle** [comment]
我这边使用QuickGridLayoutManager后问题依然存在
