### ISSUE TITLE
使用Provider实现多布局局部数据更新问题

### ISSUE THREAD

**Issue by fandroidg** [CymChad/BaseRecyclerViewAdapterHelper#3699]
1、使用Provider实现的多布局
2、使用的默认ViewHolder
3、需要更新列表中的某一项内容
使用默认adapter局部更新无效
使用provider局部更新也无效

目前未找到合适的方式进行局部数据的更新，只能列表整体刷新。解决方法要么使用代理或者默认的多布局方式来进行局部更新。

**Comment by limuyang2** [comment]
使用的库版本说明一下
