### ISSUE TITLE
3.0.9 版本请加上BaseDataBindingHolder混淆

### ISSUE THREAD

**Issue by 287138531** [CymChad/BaseRecyclerViewAdapterHelper#3703]
开启混淆会闪退报错
com.chad.library.adapter.base.viewholder.BaseViewHolder cannot be cast to com.chad.library.adapter.base.viewholder.BaseDataBindingHolder

demo中测试也一样，加上
-keep class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {*;}
不闪退，但是项目中加上。。没效果。。

**Comment by Goooler** [comment]
在 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/commit/234b8564ed899d8cdb269382ef8afdefabafa0a7 中修复了，发布在 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/3.0.10
