### ISSUE TITLE
使用payload 局部更新遇到的问题

### ISSUE THREAD

**Issue by MoonandMind** [CymChad/BaseRecyclerViewAdapterHelper#3706]
依赖版本是 3.0.9

通过adapter.notifyItemChange(payload) 进行局部更新，正常情况下不是convert(payload)执行吗？我遇到的问题是偶尔convert(payload)执行，大部分情况是convert()先执行然后在执行convert(payload)方法

**Comment by limuyang2** [comment]
可否贴下你的代码？

**Comment by MoonandMind** [comment]
下图是项目中需要局部更新的列表页面
![image](https://user-images.githubusercontent.com/5037839/197086198-7e25ae3e-712a-4e1f-974a-1266c7733d08.png)

发布完评论，局部更新adapter item中的评论列表
![image](https://user-images.githubusercontent.com/5037839/197085392-e42c31b1-87a8-4b21-987d-32d022862a79.png)

带payload参数和不带payload参数的部分convert()方法代码
![image](https://user-images.githubusercontent.com/5037839/197086541-6f62b99d-e200-4757-a897-d5f51bdf781f.png)
![image](https://user-images.githubusercontent.com/5037839/197086865-25545554-7ec4-40fd-99a1-a6da67296447.png)


局部更新时，我在带payload参数和不带payload参数的convert()方法打印日志或者debug，很多时候都是convert()执行完在执行convert(payload)，少数情况下只有convert(payload) 执行，convert()不执行。

不知道我的问题描述是否能使你明白
