### ISSUE TITLE
上拉加载更多问题

### ISSUE THREAD

**Issue by litaoyuan** [CymChad/BaseRecyclerViewAdapterHelper#3707]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

 版本依赖 "io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta02"

当设置了quickAdapterHelper.getTrailingLoadStateAdapter()).checkDisableLoadMoreIfNotFullPage() ，自动上拉加载失效
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/16474407/196663729-ba188075-573d-4dfb-860f-21e79b4c9506.png">

https://user-images.githubusercontent.com/16474407/196666766-99eb4421-a70f-404a-ad0b-7564cf1fc4a1.mp4

Uploading 9B971663990463B7E243ABC9534A101A.mp4…

**Comment by litaoyuan** [comment]
还有一个问题，当页面数据加载完成，尾部显示没有更多数据的时候，这个时候把数据清空，设置空布局，空布局展示了，但是在页面下面还会有尾部
![0396DB9F8CFB5222CE16199644BB9031](https://user-images.githubusercontent.com/16474407/196847951-95908319-3f32-452f-95ed-0419128a7a2d.jpg)
![6EBFE79998356B1DE058195C1316C31A](https://user-images.githubusercontent.com/16474407/196847971-064aca3b-1651-4e4f-8a41-6bd2a95b0350.jpg)

**Comment by limuyang2** [comment]
> 还有一个问题，当页面数据加载完成，尾部显示没有更多数据的时候，这个时候把数据清空，设置空布局，空布局展示了，但是在页面下面还会有尾部 ![0396DB9F8CFB5222CE16199644BB9031](https://user-images.githubusercontent.com/16474407/196847951-95908319-3f32-452f-95ed-0419128a7a2d.jpg) ![6EBFE79998356B1DE058195C1316C31A](https://user-images.githubusercontent.com/16474407/196847971-064aca3b-1651-4e4f-8a41-6bd2a95b0350.jpg)

设置 LoadState.None

**Comment by litaoyuan** [comment]
<img width="1172" alt="0A75891A-9E82-423A-9213-388F180B5E6C" src="https://user-images.githubusercontent.com/16474407/196899090-0deda276-26a6-4755-b75e-ebb9203c6da8.png">
LoadState.None 方法 是不是没有开放，我这边调用出错

**Comment by limuyang2** [comment]
> <img alt="0A75891A-9E82-423A-9213-388F180B5E6C" width="1172" src="https://user-images.githubusercontent.com/16474407/196899090-0deda276-26a6-4755-b75e-ebb9203c6da8.png">
> 
> LoadState.None 方法 是不是没有开放，我这边调用出错

java 使用方式：`LoadState.None.INSTANCE`

**Comment by litaoyuan** [comment]
第一个问题，当设置quickAdapterHelper.getTrailingLoadStateAdapter()).checkDisableLoadMoreIfNotFullPage() ，自动上拉加载失效了，这个是问题是我设置的问题吗？

**Comment by litaoyuan** [comment]
大佬，有时候点击item ,没有作用，啥原因呢

**Comment by wkbin** [comment]
4.0.0-beat4版本 空布局高度显示不全 ，SmartRefreshLayout 嵌套 RecyclerView

**Comment by UserName-Haha** [comment]
> 

我也遇到，请问您解决了吗？

**Comment by gaohequan** [comment]
> 第一个问题，当设置quickAdapterHelper.getTrailingLoadStateAdapter()).checkDisableLoadMoreIfNotFullPage() ，自动上拉加载失效了，这个是问题是我设置的问题吗？

4.1.4版本中，这个问题我也遇到了  请问您是否找到了解决办法
