### ISSUE TITLE
4.0版本能把addheader和addfooter加回来吗，没这个好别扭啊 (⊙o⊙)…

### ISSUE THREAD

**Issue by qq987212100** [CymChad/BaseRecyclerViewAdapterHelper#3709]
4.0版本能把addheader和addfooter加回来吗，没这个好别扭啊 (⊙o⊙)…

**Comment by chenlong0338** [comment]
你说的是这个添加列头列脚这个功能，还是说addheader和addfooter方法？列头列脚4.0版本还是提供了方法实现的。

**Comment by HaoTianhua** [comment]
> 你说的是这个添加列头列脚这个功能，还是说addheader和addfooter方法？列头列脚4.0版本还是提供了方法实现的。

请问怎么样才能比较优雅的获取到到添加的列头、脚的itemview呢。

**Comment by chenlong0225** [comment]
> > 你说的是这个添加列头列脚这个功能，还是说addheader和addfooter方法？列头列脚4.0版本还是提供了方法实现的。
> 
> 请问怎么样才能比较优雅的获取到到添加的列头、脚的itemview呢。

用recyclerView的实例获取吧，adapter里面是没存Holder那些东西的。

**Comment by limuyang2** [comment]
4.0有提供此功能，请查看文档
[](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/QuickAdapterHelper)
