### ISSUE TITLE
点击事件报错

### ISSUE THREAD

**Issue by Jasperben** [CymChad/BaseRecyclerViewAdapterHelper#3711]
implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.10'

mAdapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(@NonNull BaseQuickAdapter adapter, @NonNull View view, int position) {
                ModelHomeEntrance data = mAdapter.getItem(position);
                ToastUtils.showLong(data.getName());
            }
        });

adapter.getItem(position)报错日志：

java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/app

**Comment by limuyang2** [comment]
clean 下项目
