### ISSUE TITLE
submitList  重用布局出现数据不刷新

### ISSUE THREAD

**Issue by hfyqsy** [CymChad/BaseRecyclerViewAdapterHelper#3714]
ViewModel 传递数据，使用Adapter.submitList()的出现重用布局没有更新数据的情况   需要调用mAdapter.notifyDataSetChanged(),是我使用有问题吗？

**Comment by hisgod** [comment]
submitList源码里面第一行做了判断了，如果是同个地址的集合，直接return，就没执行刷新了

**Comment by limuyang2** [comment]
请重写带 `payloads` 的方法
