### ISSUE TITLE
4.0版本可否重新命名包名

### ISSUE THREAD

**Issue by EdminhPeng** [CymChad/BaseRecyclerViewAdapterHelper#3716]
maven的group Id与类的包名，是否可以重新命名？方便开发者逐步替换升级，否则两个版本无法同时引入导致修改量大，升级困难。

**Comment by Congx** [comment]
我也遇到了这个问题，像 RxJava 一样多个版本可以同时存在，可以逐步替换

**Comment by geeklx** [comment]
对 不然大家很难切换新的

**Comment by limuyang2** [comment]
目前暂时不会变更包名，抱歉
