### ISSUE TITLE
setLoadingView自定义界面怎么样设置才能match_parent?

### ISSUE THREAD

**Issue by 13588823551** [CymChad/BaseRecyclerViewAdapterHelper#372]
我用了setLoadingView(View view)，但是界面是在左上角，且大小是自适应，应该如何修改？

**Comment by 13588823551** [comment]
是我搞错了，setLoadingView设置的是footer的样式。
你可以加一个方法设置第一次加载时的loadingview吗？

**Comment by CymChad** [comment]
setLoadingView就是设置loadingview

**Comment by CymChad** [comment]
demo有案例，加载的时候记得传父布局。

**Comment by 13588823551** [comment]
setLoadingView之后，最开始的加载界面变了，但是loadmore的界面也一起变了，可以把loadingview和loadmoreview分开么？

**Comment by jesse920524** [comment]
@13588823551 inflate()第二个形参注意,要传入recyclerView的父布局,通过rv.getParent()得到.
遇到了同样的问题,刚刚解决.

**Comment by 13588823551** [comment]
@jesse920524 Match_Parent的问题已经解决，现在的问题是setLoadingView之后，loadmore的界面也一起变了

**Comment by CymChad** [comment]
一个是加载中的view，通过setLoadingView来改变，一个是加载完成的view，这是又开发者自己通过addFooterView来决定的。
