### ISSUE TITLE
你也因为【Called attach on a child which is not detached: BaseViewHolder】崩溃了吗？

### ISSUE THREAD

**Issue by longxuewei** [CymChad/BaseRecyclerViewAdapterHelper#3721]
如果你也遇到了这个问题，那大概是刷新Adapter的时候没有加上 Adapter 的 Header 数量 以及 EmptyView 数量。所以出现这种情况只需要像这样：

`mAdapter.notifyItemRangeChanged(positionStart + mAdapter.headerLayoutCount + if (mAdapter.hasEmptyView()) 1 else 0, itemCount)`

`mAdapter.notifyItemRangeInserted(positionStart + mAdapter.headerLayoutCount + if (mAdapter.hasEmptyView()) 1 else 0, itemCount)`

`mAdapter.notifyItemRangeRemoved(positionStart + mAdapter.headerLayoutCount + if (mAdapter.hasEmptyView()) 1 else 0, itemCount)`

**Comment by lsgmkk** [comment]
setFooterView 的情况呢
