### ISSUE TITLE
麻烦作者更新下4.x的拖拽功能的文档啊，或者给个demo也行

### ISSUE THREAD

**Issue by shannontech** [CymChad/BaseRecyclerViewAdapterHelper#3726]
麻烦作者更新下BRVAH 4.x的拖拽功能（drag and swpie）的文档啊，或者给个demo也行，没文档难受啊

**Comment by limuyang2** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%8B%96%E6%8B%BD%E5%8A%9F%E8%83%BD%EF%BC%88DragAndSwipeDataCallback%EF%BC%89
