### ISSUE TITLE
addFooterView 如何能添加在recyclerView高度的最下面

### ISSUE THREAD

**Issue by hy-liuyuzhe** [CymChad/BaseRecyclerViewAdapterHelper#3727]
比如 我列表目前只有2条数据，列表高度是整个屏幕的高，我想添加脚步局addFooterView 如何能添加在recyclerView高度的最下面。而不是放在列表2条数据的后面。

![561672364663_ pic](https://user-images.githubusercontent.com/84558612/210026395-8f00cee1-469e-4a63-9958-7737b02bc7e8.jpg)

目前addFooterView会跟随item后面添加。而不是放到屏幕底部边缘的上面。

com.chad.library.adapter：3.0.7 版本； 

求助，怎么实现

**Comment by hy-liuyuzhe** [comment]
类似 stickFooter

**Comment by hy-liuyuzhe** [comment]
1

**Comment by hy-liuyuzhe** [comment]
有人吗

**Comment by AlbertZyc** [comment]
> 

塞空白数据

**Comment by limuyang2** [comment]
这个需要你自己计算item的高度了。不属于本库的功能了
