### ISSUE TITLE
item的点击状态

### ISSUE THREAD

**Issue by zou1755815609** [CymChad/BaseRecyclerViewAdapterHelper#373]
请问下如果使用群主的adapter里面的item里面如果有自定义view ，这个view拦截了事件，item 的点击状态一直处于按下状态，这个怎么解决

**Comment by AllenCoder** [comment]
如果你拦截了 View 的点击事件，相应的 item 的 background 的状态无法通过点击事件的释放得到重置。所以就会处于一直按下状态，你能否在不通过 item 的 background 来控制状态，而直接在自定义 View里面控制状态呢？

**Comment by zou1755815609** [comment]
自定义只是item 的一小部分 如何通过自定义view控制item的背景状态

**Comment by qiangxi** [comment]
我也上报一个问题: 给item设置ripple效果时,每次不管手指点击在item的什么位置,ripple效果都是从item的中心位置往外发散,这样相当不好看,给用户的直接感觉像是残次品的ripple,

**Comment by zou1755815609** [comment]
普通item只要有点击事件点击就会一直处于按下状态，这个bug如何解决

**Comment by AllenCoder** [comment]
点击事件的背景控制是通过 drawable 里面的 xml 的 selector文件的 state 自动判断的，状态设置是否有误？

**Comment by AllenCoder** [comment]
@qiangxi 基于中心点的扩散，正在着手处理中

**Comment by 1109993488** [comment]
`public abstract class SimpleClickListener extends RecyclerView.SimpleOnItemTouchListener {

    private GestureDetectorCompat mGestureDetector;

    @Override
    public boolean onInterceptTouchEvent(RecyclerView rv, MotionEvent e) {
        if (mGestureDetector == null) {
            mGestureDetector = new GestureDetectorCompat(rv.getContext(), new ItemTouchHelperGestureListener(rv, this));
        }
        mGestureDetector.onTouchEvent(e);
        return false;
    }

    private static class ItemTouchHelperGestureListener extends GestureDetector.SimpleOnGestureListener {

        private RecyclerView mRecyclerView;
        private BaseQuickAdapter mBaseQuickAdapter;
        private SimpleClickListener mSimpleClickListener;

        public ItemTouchHelperGestureListener(RecyclerView recyclerView, SimpleClickListener simpleClickListener) {
            mRecyclerView = recyclerView;
            mBaseQuickAdapter = (BaseQuickAdapter) recyclerView.getAdapter();
            mSimpleClickListener = simpleClickListener;
        }

        @Override
        public boolean onSingleTapUp(MotionEvent e) {
            final View pressedView = mRecyclerView.findChildViewUnder(e.getX(), e.getY());
            BaseViewHolder vh = (BaseViewHolder) mRecyclerView.getChildViewHolder(pressedView);
            if (!isDataViewPosition(vh)) {
                return false;
            }
            HashSet<Integer> childClickViewIds = vh.getChildClickViewIds();
            if (childClickViewIds != null && childClickViewIds.size() > 0) {
                for (Iterator<Integer> it = childClickViewIds.iterator(); it.hasNext(); ) {
                    View childView = vh.getView(it.next());
                    if (inRangeOfView(childView, e) && childView.isEnabled()) {
                        mSimpleClickListener.onItemChildClick(mBaseQuickAdapter, childView, vh.getLayoutPosition() - mBaseQuickAdapter.getHeaderLayoutCount());
                        return true;
                    }
                }
            }
            mSimpleClickListener.onItemClick(mBaseQuickAdapter, pressedView, vh.getLayoutPosition() - mBaseQuickAdapter.getHeaderLayoutCount());
            return true;
        }

        @Override
        public void onLongPress(MotionEvent e) {
            final View pressedView = mRecyclerView.findChildViewUnder(e.getX(), e.getY());
            BaseViewHolder vh = (BaseViewHolder) mRecyclerView.getChildViewHolder(pressedView);
            if (!isDataViewPosition(vh)) {
                return;
            }
            HashSet<Integer> longClickViewIds = vh.getItemChildLongClickViewIds();
            if (longClickViewIds != null && longClickViewIds.size() > 0) {
                for (Iterator<Integer> it = longClickViewIds.iterator(); it.hasNext(); ) {
                    View childView = vh.getView(it.next());
                    if (inRangeOfView(childView, e) && childView.isEnabled()) {
                        mSimpleClickListener.onItemChildLongClick(mBaseQuickAdapter, childView, vh.getLayoutPosition() - mBaseQuickAdapter.getHeaderLayoutCount());
                        return;
                    }
                }
            }
            mSimpleClickListener.onItemLongClick(mBaseQuickAdapter, pressedView, vh.getLayoutPosition() - mBaseQuickAdapter.getHeaderLayoutCount());
        }

        public boolean inRangeOfView(View view, MotionEvent ev) {
            int[] location = new int[2];
            if (view.getVisibility() != View.VISIBLE) {
                return false;
            }
            view.getLocationOnScreen(location);
            int x = location[0];
            int y = location[1];
            if (ev.getRawX() < x
                    || ev.getRawX() > (x + view.getWidth())
                    || ev.getRawY() < y
                    || ev.getRawY() > (y + view.getHeight())) {
                return false;
            }
            return true;
        }

        private boolean isDataViewPosition(BaseViewHolder vh) {
            int type = vh.getItemViewType();
            return !(type == EMPTY_VIEW
                    || type == HEADER_VIEW
                    || type == FOOTER_VIEW
                    || type == LOADING_VIEW);
        }
    }

    /**
     * Callback method to be invoked when an item in this AdapterView has
     * been clicked.
     *
     * @param view     The view within the AdapterView that was clicked (this
     *                 will be a view provided by the adapter)
     * @param position The position of the view in the adapter.
     */
    public abstract void onItemClick(BaseQuickAdapter adapter, View view, int position);

    /**
     * callback method to be invoked when an item in this view has been
     * click and held
     *
     * @param view     The view whihin the AbsListView that was clicked
     * @param position The position of the view int the adapter
     * @return true if the callback consumed the long click ,false otherwise
     */
    public abstract void onItemLongClick(BaseQuickAdapter adapter, View view, int position);

    public abstract void onItemChildClick(BaseQuickAdapter adapter, View view, int position);

    public abstract void onItemChildLongClick(BaseQuickAdapter adapter, View view, int position);

}`
我是这么做的不过有点击状态的view要设置android:clickable="true"才行，可以解决ripple在正中间显示问题，就是不知道这样会不会有问题

**Comment by AllenCoder** [comment]
你好，观察你提供的代码，跟咱们的基本一样啊，你关于状态判断，省掉了，会影响释放后的状态复原。 关于点击中心点的扩散，这种好像不行吧？欢迎提供更佳的解决思路。我也将继续跟进

**Comment by AllenCoder** [comment]
@1109993488 @qiangxi  已经实现了基于任意位置点击的波纹扩散效果 ，代码测试无误后，将会在近期新版本中发布

**Comment by TpOut** [comment]
波纹扩散这个问题，我这里有个情况。就是layout，有上view，下view。各自添加了波纹效果，如果使用recyclerView.addOnItemTouchListener，添加两个子项点击效果，会有不管点击哪个view，两个view都扩散波纹的情况，也是从中间扩散。可能和@qiangxi说的情况一样。（如果已经解决，请忽略）

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.3'  已由 @AllenCoder  修复，请更新版本。

**Comment by zxy198717** [comment]
@CymChad 这种情况能解决吗？
1. 打开demo程序，选择RecyclerClickItemActivity
2. 点击头像，功能是正常的，但是背景的 波纹 效果也出来了

能做到点击item种某个view的时候，只显示这个view的 点击 效果吗？
