### ISSUE TITLE
differUtils可以在setNewDiffData这些方法里，不要去更改data对象么

### ISSUE THREAD

**Issue by a562536056** [CymChad/BaseRecyclerViewAdapterHelper#3736]
DifferUtils对ObserserList太不友好了，很不适用MVVM的数据双向绑定。
最终初始设置的具有Obserser的List会被替换成setNewInstances对象，如果用源数据ObserverList去setNewInstance又会因为里面的newdata == olddata 跳出differ逻辑。

**Comment by limuyang2** [comment]
3.0版本的这个逻辑不会再变动了
