### ISSUE TITLE
 4.0是不是某些方法已经不兼容java了？ 没看到4.0的示例代码 github的实力代码好像还是3.0的

### ISSUE THREAD

**Issue by 643063150** [CymChad/BaseRecyclerViewAdapterHelper#3737]
比图 recommendAdapter.setOnItemClickListener() 有些函数转换不过来 也不知道是不是我的kt配置有问题，项目比较老，还是混合项目 不敢升级Android studio

**Comment by 643063150** [comment]
找到问题所在了，项目中有其他库把org.jetbrains.kotlin:kotlin-stdlib升级到1.8.0了，但是这个版本的jvm.function全是空的，强行降级为1.7.10就行了，感觉现在as和kt的库都是一大堆问题

**Comment by limuyang2** [comment]
可以更新下4.0.0-beta06试试
