### ISSUE TITLE
adapter.getItem(position)为空

### ISSUE THREAD

**Issue by q1170541047** [CymChad/BaseRecyclerViewAdapterHelper#3740]
app退到后台一段时间再返回，adapter.getItem(position)有几率为空，
点击按钮创建新的Fragment，adapter.getItem(position)也一定为空，除非杀掉进程重启
  ConnectFragment frag = new ConnectFragment();页面其他元素都是正常的

**Comment by limuyang2** [comment]
什么版本？

**Comment by limuyang2** [comment]
长时间未回复，问题先关闭了
