### ISSUE TITLE
希望更新4.x的文档（拖拽和侧滑等）

### ISSUE THREAD

**Issue by shannontech** [CymChad/BaseRecyclerViewAdapterHelper#3746]
4.x的文档不完整（wiki介绍也比较简略），开发比较难受，希望作者可以把4.x的文档更新完整，包括侧滑和拖拽等功能的实现，并发布下demo工程参考参考

**Comment by maydaynicko** [comment]
那你试试https://github.com/liangjingkanji/BRV

**Comment by limuyang2** [comment]
拖拽文档已经更新在wiki里了
