### ISSUE TITLE
V4 希望不要以 holder class 进行判断

### ISSUE THREAD

**Issue by jinpengnice** [CymChad/BaseRecyclerViewAdapterHelper#3748]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/30205688/229023890-c930203b-9b81-4520-a9d1-6c628fd25a9e.png">

希望进一步封装，或onBind 以 itemViewType 作为判断依据

**Comment by buhuiming** [comment]
我还是自己写了个BaseMultiItemAdapter

**Comment by limuyang2** [comment]
可否详细解释下呢

**Comment by limuyang2** [comment]
可以更新下 4.0.0-beta06 试试，修复了在 ConcatAdapter 中，`BaseMultiItemAdapter `获取item可能错误的问题。不再以 holder class 进行判断
