### ISSUE TITLE
C:\Users\liyonglin\.gradle\caches\transforms-2\files-2.1\cd7d8fc55c555b0e080e29c934a4c09e\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.     

### ISSUE THREAD

**Issue by BruceLii** [CymChad/BaseRecyclerViewAdapterHelper#3749]
C:\Users\liyonglin\.gradle\caches\transforms-2\files-2.1\cd7d8fc55c555b0e080e29c934a4c09e\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
4.0.0-beta04    出现这个问题,

**Comment by limuyang2** [comment]
检查你项目的资源

**Comment by limuyang2** [comment]
根据错误内容，不是本库导致的。检查下你的 AndroidX `core`库
