### ISSUE TITLE
建议SimpleClickListener中的adapter，如无特别需求，还是用系统的adapter

### ISSUE THREAD

**Issue by linxin6560** [CymChad/BaseRecyclerViewAdapterHelper#375]
我为了实现加载更多，写了一个LoaderMoreHelper,该帮助类会重新设置RecyclerView的adapter为LoaderMoreAdapter，之前配置1.9.8版本的BaseRecyclerViewAdapterHelper一直用都没问题，改为2.0的之后，就出现了类型转换错误，我看了代码，是 
`this.baseQuickAdapter = (BaseQuickAdapter) recyclerView.getAdapter();` 这句代码导致的，然后SimpleClickListener貌似也不没用到BaseQuickAdapter中的方法，所以我建议改成源生的adapter，方便adapter的扩展

**Comment by AllenCoder** [comment]
SimpleClickListener 需要用到BaseQuickAdapter里面标记的 childview 的 id 用于区分是 item 的点击事件还是 childview 的点击事件

**Comment by linxin6560** [comment]
childview 的id，是通过BaseViewHolder去获取的，这个其实影响不大 ，我们没有动到ViewHolder，如果没办法改的话，那就蛋疼了，所有的adapter都替换，挺蛋疼的

**Comment by AllenCoder** [comment]
因为SimpleClickListener的点击事件是要配合 BaseQuickAdapter才能使用的，你单独用它做点击事件然后adapter用的是LoaderMoreAdapter ，这样在后续的点击事件中，肯定会出问题的，BaseQuickAdapter本身也支持加载更多，也可以基于 BaseQuickAdapter自己来实现啊

**Comment by linxin6560** [comment]
我们是在底层框架统一处理加载更多的，因为我们不希望在每个地方写重复的代码，所以在用这个框架之前，就那么设计了。现在想改的话，改动量太大了。

**Comment by CymChad** [comment]
框架需要，所以无法修改。
