### ISSUE TITLE
使用BaseMultiItemAdapter onItemViewType ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wishkity** [CymChad/BaseRecyclerViewAdapterHelper#3761]
问题1、
    版本：io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta02
    使用BaseMultiItemAdapter实现展开收起时，偶尔子item位置错误，会添加到其他parent下

问题2、升级到版本：io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta10
使用BaseMultiItemAdapter
操作item时会触发onItemViewType报错，position = -1
onItemViewType { position, list ->
    list[position].getItemType()
}
java.lang.ArrayIndexOutOfBoundsException: length=32; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)

**Comment by XueyiXia** [comment]
> 问题1、 版本：io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta02 使用BaseMultiItemAdapter实现展开收起时，偶尔子item位置错误，会添加到其他parent下
> 
> 问题2、升级到版本：io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta10 使用BaseMultiItemAdapter 操作item时会触发onItemViewType报错，position = -1 onItemViewType { position, list -> list[position].getItemType() } java.lang.ArrayIndexOutOfBoundsException: length=32; index=-1 at java.util.ArrayList.get(ArrayList.java:439)

同样的问题

**Comment by limuyang2** [comment]
你好，这个问题正在修复中
