### ISSUE TITLE
禁止复用

### ISSUE THREAD

**Issue by lovehua** [CymChad/BaseRecyclerViewAdapterHelper#3765]
public class BaseSurveyHolder<T> extends BaseViewHolder {...}
没有复用的这种用法了吗？
holder.setIsRecyclable(false);

**Comment by limuyang2** [comment]
`setIsRecyclable` ViewHolder 系统自带的方法，不是本库定义的。

**Comment by lovehua** [comment]
知道是系统自带的，难道是我使用的问题的吗？3.0.11版本 没有该方法 ，
![Uploading 1685349612359.png…]()

**Comment by limuyang2** [comment]
是recyclerView 库中自带的系统方法，和本库无关啊，你可以更新rv版本试试
