### ISSUE TITLE
onViewHolderCreated回调没有了吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [CymChad/BaseRecyclerViewAdapterHelper#3766]
原来有的控件操作是写在那里面的，在`onBindViewHolder`里写的话每个都要重复绑定好像有点耗费资源，在`onViewHolderCreated`回调里绑定的话好像只有第一页会执行，后面会复用，感觉好像好一点😂

**Comment by limuyang2** [comment]
还是有的，你使用的是哪一种Adapter？

**Comment by SaltedFish-Extreme** [comment]
> 还是有的，你使用的是哪一种Adapter？

基本的BaseQuickAdapter😂

**Comment by limuyang2** [comment]
你可以直接重写 `onCreateViewHolder` 方法，在里面直接写。`onViewHolderCreated `会稍显多余

**Comment by SaltedFish-Extreme** [comment]
😂好吧，我是之前打断点时候发现`onViewHolderCreated `好像只会在第一页数据加载的时候执行，后面就没在执行了，也许可以少耗费一些资源
