### ISSUE TITLE
V4-10 BaseMultiItemAdapter中有一个崩溃

### ISSUE THREAD

**Issue by Dboy233** [CymChad/BaseRecyclerViewAdapterHelper#3768]
<img width="672" alt="图片" src="https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/37604230/69ce0bd2-8274-42a1-866b-5ac734272836">

当Adapter移除item的时候，此时的ViewHodler的状态会提前被标记为移除，此时再获取位置的时候是-1。

如果业务adapter进行ItemType处理的时候使用了这个position,将不能进行正确的逻辑处理。

**Comment by limuyang2** [comment]
好的，感谢反馈

**Comment by Dboy233** [comment]
> 好的，感谢反馈

已经修复了 #3744

**Comment by Dboy233** [comment]
> 好的，感谢反馈

老哥，我不知道你回复这么快，你别重修了bug。我在 #3744 的PR中已经修过了

**Comment by limuyang2** [comment]
你更新 beta11 再试试
