### ISSUE TITLE
对于上拉加载如何处理返回的数据个数不一致的情况？

### ISSUE THREAD

**Issue by Eveninger** [CymChad/BaseRecyclerViewAdapterHelper#377]
现在上拉加载必须调用mVerTaskAdapter.openLoadMore(PAGE_SIZE);
假设PAGE_SIZE = 10。但返回的数据经过过滤后只有3个，则无法触发上拉加载

**Comment by CymChad** [comment]
如果你返回只有3个不满足一页，你还有下一页？

**Comment by CymChad** [comment]
PAGE_SIZE  只是指第一页的数量，如果你第一页满足10条你就可以上拉了，因为如果你不满足一屏幕的数量，也不可能有上拉操作。第二页或者第三页的数量随便多少都可以，你只需要通知，adapter是否有下一页即可。
