### ISSUE TITLE
BaseProviderMultiAdapter+viewbinding显示错乱了

### ISSUE THREAD

**Issue by tongfei21** [CymChad/BaseRecyclerViewAdapterHelper#3774]
1. 版本3.0.7,刚更新到3.0.13也是一样
2. BaseProviderMultiAdapter 添加多个 ItemProvider，复写onCreateViewHolder，用到了viewbinding
        @NonNull
        @Override
        public BaseViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            binding = ItemArticlesDefaultBinding.inflate(LayoutInflater.from(parent.getContext()));
            return new BaseViewHolder(binding.getRoot());
        }
       public void convert(@NonNull BaseViewHolder holder, AppListItemBean.BaseArticlesBean articlesBean) {
             binding.title.setTextView(articlesBean.title);
       }
上下滑动页面的时候（滑动一点 上下晃动），某一个位置的显示的数据就会变(图片和文字都会变)。开始没有用viewbinding这种写法的时候没发现问题，今天改了viewbinding就这样了。

**Comment by tongfei21** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/7554848/b2a40f7f-28af-4e24-b4aa-15867e2c76ba

**Comment by limuyang2** [comment]
检查你数据的设置代码

**Comment by tongfei21** [comment]
[部分代码.txt](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/11699535/default.txt)
数据绑定 两个版本的代码，除了把holder.set 改成binding.view 的，其他基本没变。辛苦帮忙看下

**Comment by tongfei21** [comment]
找到问题了  感谢
