### ISSUE TITLE
4.0 增加列表脚布局后，设置的ItemDecoration不起作用了

### ISSUE THREAD

**Issue by ggyg123** [CymChad/BaseRecyclerViewAdapterHelper#3777]
helper = QuickAdapterHelper.Builder(adapter).build()
    viewBinding.rv.addItemDecoration(HomeDecoration(requireContext()))
    viewBinding.rv.adapter = helper.adapter
    helper.addAfterAdapter(
            FooterAdapter(false).setOnItemClickListener { _, _, _ ->
                addFooter()
            }
        )

增加列表脚布局后，设置的ItemDecoration不起作用了，也不会走ItemDecoration的方法了，
话说现在4.0版本添加脚布局怎么这么麻烦了

**Comment by limuyang2** [comment]
经过测试是有效的，请问你的版本和你的代码片段贴一下

**Comment by limuyang2** [comment]
长时间未回复，问题先关闭了
