### ISSUE TITLE
4.0   BaseMultiItemAdapter和LeadingLoadStateAdapter一起使用   onItemViewType 中list[position]  角标越界

### ISSUE THREAD

**Issue by ASguy** [CymChad/BaseRecyclerViewAdapterHelper#3779]
binding.rvChat.layoutManager = LinearLayoutManager(this)
        helper = QuickAdapterHelper.Builder(mAdapter)
            // 使用默认样式的首部"加载更多"
            .setLeadingLoadStateAdapter(object : LeadingLoadStateAdapter.OnLeadingListener {
                override fun onLoad() {
                    // 执行加载更多的操作，通常都是网络请求
                    requestUoFetch()
                }

                override fun isAllowLoading(): Boolean {
                    // 是否允许触发“加载更多”
                    return true
                }
            }).build()
        /**
         * 第三步，给 RecyclerView 设置 Adapter，
         * 注意：这个adapter不是前面创建的 mAdapter，而是 helper 所提供的 adapter（ConcatAdapter）
         */
        binding.rvChat.adapter = helper.adapter

binding.rvChat.postDelayed({
            mAdapter.addAll(0, chatDataBeanList)
            if (count > 5) {
                /*
                 * Set the status to not loaded, and there is no paging data.
                 * 设置状态为未加载，并且没有分页数据了
                 */
                helper.leadingLoadState = LoadState.NotLoading(true)
            } else {
                /**
                 * Set the state to not loaded, and there is also paginated data
                 * 设置状态为未加载，并且还有分页数据
                 */
                helper.leadingLoadState = LoadState.NotLoading(false)
            }
        }, 600)

.onItemViewType { position, list -> // 根据数据，返回对应的 ItemViewType
            if (list[position].role == "user") {
                1
            } else {
                2
            }
        }
首次进入没有问题，向上加载的时候list.size = position了

**Comment by limuyang2** [comment]
版本号是多少？

**Comment by limuyang2** [comment]
我这里测试没有复现，检查下你是否中途修改了list

**Comment by limuyang2** [comment]
长时间未回复，问题先关闭了

**Comment by 50kg** [comment]
越界问题是不能重复clear list，必须每次new 新的list再submitList()进去

**Comment by 50kg** [comment]
@limuyang2 如果第二次submitList 使用上一个相同的list，clear在addAll数据，必崩
