### ISSUE TITLE
android:allowBackup问题

### ISSUE THREAD

**Issue by sweet2o09** [CymChad/BaseRecyclerViewAdapterHelper#378]
你好,我在使用你们的jar包的时候发现如果我的app里面设置android:allowBackup="true"的时候就没问题,设置成android:allowBackup="false"的话就无法编译,请问这个要如何解决,貌似要设置成false会比较安全

**Comment by CymChad** [comment]
收到，明天我看看。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.9' 已经改过来了。

**Comment by gushoubang** [comment]
![image](https://cloud.githubusercontent.com/assets/8435230/19217004/15229dfe-8e06-11e6-997f-f6ac51967390.png)
我也遇到了 2.1.9版本

**Comment by CymChad** [comment]
2.1.9 已经改成false 了。

**Comment by gushoubang** [comment]
![image](https://cloud.githubusercontent.com/assets/8435230/19218966/c9ba6dea-8e39-11e6-9747-945867812d62.png)
 但是我这里一直有问题

**Comment by gushoubang** [comment]
我的友盟分享类库设置了true，奇怪，2.1.7版本没问题，2.1.9就有问题了

**Comment by CymChad** [comment]
我知道了。回头我直接删除掉，又开发者了来决定吧。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.0' 已经删除了。
