### ISSUE TITLE
给recyclerView设置分割线，当设置emptyView的时候，没有数据，emptyView下有条分割线

### ISSUE THREAD

**Issue by ChenHaolong** [CymChad/BaseRecyclerViewAdapterHelper#3780]
给recyclerView设置分割线，当设置emptyView的时候，没有数据，emptyView下有条分割线，

**Comment by limuyang2** [comment]
设置分割线的class里，自己做一下判断。不属于本库涉及范围

**Comment by 704480904** [comment]
同样出现了这个问题 当设置emptyView的时候  没有数据  emptyView 下面会有一条分割线
