### ISSUE TITLE
3.0.14版本下不下来

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [CymChad/BaseRecyclerViewAdapterHelper#3784]
![image](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/54784104/8a5d6c07-f301-4c91-a53a-4caef6b35fdd)

老哥，三个周了，3.0.13版本能下下来，3.0.14版本死活下不下来😂

**Comment by SaltedFish-Extreme** [comment]
😂阿里的快啊，很多Android的库在外网下不下来，阿里的构建速度就很快了

**Comment by limuyang2** [comment]
> 😂阿里的快啊，很多Android的库在外网下不下来，阿里的构建速度就很快了

你这里的错误，就是因为 ali 镜像导致的无法找到 maven 仓库的包。

**Comment by SaltedFish-Extreme** [comment]
嗯，我知道，但是应该会同步过去的啊，3.0.13版本没问题，3.0.14就不行了😂

**Comment by limuyang2** [comment]
> 嗯，我知道，但是应该会同步过去的啊，3.0.13版本没问题，3.0.14就不行了😂

ali 的同步不是实时的。而且 maven 中央仓库并不需要翻墙访问啊

**Comment by limuyang2** [comment]
如果你实在不行，就从 maven 仓库直接下载 aar 包吧。[maven](https://search.maven.org/artifact/io.github.cymchad/BaseRecyclerViewAdapterHelper/3.0.14/aar)

**Comment by SaltedFish-Extreme** [comment]
![image](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/54784104/c0ce2d7b-58a0-4ea0-97e1-b18048e26870)

我就加了这四个阿里的镜像仓库地址😂4.0.0-beta14版本都能下下来，3.0.14就不行，不知道为什么没同步😥

**Comment by limuyang2** [comment]
你可以先注释掉ali的，先同步试试，是在不行就下aar

**Comment by SaltedFish-Extreme** [comment]
好吧😂

**Comment by jzh1996** [comment]
![image](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/40649610/ce613625-b8c6-4020-bcd9-ede6df7da3d0)
老哥咋解决的呀。屏蔽了阿里的也不行。用aar可以在手机运行也没法打包，kotlin插件版本冲突了

**Comment by SaltedFish-Extreme** [comment]
kotlin插件我用的最新版的，好像是8.0.20还是啥的，只要自己在build.gradle里写了不就行了吗，默认应该用自己配置的版本，或者你网上看看依赖的插件版本有冲突应该怎么解决，我之前lifecycle版本有冲突，好像就定义用我的版本的

**Comment by SaltedFish-Extreme** [comment]
话说现在3.0.14版本可以用阿里的远程仓库了，已经有了😂

**Comment by jzh1996** [comment]
https://maven.aliyun.com/repository/public  这个仓库吧  一直失败

**Comment by SaltedFish-Extreme** [comment]
我不记得了，要不你下下来我最新的项目，看看我怎么整的，我都是用的最新版的东西，一个用的3.0.14，一个用的4.0.0-beta14[WanAndroid](https://github.com/SaltedFish-Extreme/WanAndroid) [Smile](https://github.com/SaltedFish-Extreme/Smile)

**Comment by SaltedFish-Extreme** [comment]
原来4.0.0正式版已经出了啊，我这几天搞项目都没注意，下个周应该就能用阿里的仓库依赖最新版的这个框架了😆
