### ISSUE TITLE
addHeaderView addFooterView的问题

### ISSUE THREAD

**Issue by Ccixyj** [CymChad/BaseRecyclerViewAdapterHelper#379]
当RecyclerView为横向的时,HeaderLayout与FooterLayout的方向及LayoutParams会有问题.
addHeaderView 会使得RecyclerView的高度变为0.
addFooterView会占据一屏幕的宽度,但是我不需要那么宽.

**Comment by CymChad** [comment]
宽度是由开发者定义的。
