### ISSUE TITLE
GridLayoutManager 展示时排序数据异常

### ISSUE THREAD

**Issue by ZhangHaoChase** [CymChad/BaseRecyclerViewAdapterHelper#3790]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**
只是把layoutmanager 展示换了下 然后  拖动方式换了下  demo代码只支持上下 我换成了上下左右都加上了  但是拖动之后数据是不对的

![企业微信截图_16907739628913](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/24821863/fea678ee-e086-4eb3-a5dd-dfd615c30e48)
![企业微信截图_16907739824527](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/24821863/3a4bb721-edb6-4a81-86ab-1712355c513f)
![企业微信截图_16907740482103](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/24821863/c868d263-c7f1-45f2-8d0f-6ae89df5436b)

**Comment by limuyang2** [comment]
可否给个完整代码zip，我下载研究下

**Comment by ZhangHaoChase** [comment]
[新建文件夹.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/12226197/default.zip)
我就改了里面这个类的一个展示方式  用您的demo来改的   谢谢

**Comment by limuyang2** [comment]
已经验证，是 `swap` 方法的bug导致，这里出现了歧义，已经新增了方法解决

**Comment by limuyang2** [comment]
最新代码已经解决

**Comment by ZhangHaoChase** [comment]
好的  我试试
