### ISSUE TITLE
4.0.0版本源码加载失败

### ISSUE THREAD

**Issue by HQLIE2018** [CymChad/BaseRecyclerViewAdapterHelper#3791]
版本：4.0.0
问题：编译时报错：properties.getProperty("signing.keyId") must not be null

**Comment by limuyang2** [comment]
跑项目源码，需要自己注释下 maven 的一些上传配置。maven 中央仓库的key，我肯定不能公之于众啊……

**Comment by HQLIE2018** [comment]
已解决

**Comment by SakurajimaMaii** [comment]
> 跑项目源码，需要自己注释下 maven 的一些上传配置。maven 中央仓库的key，我肯定不能公之于众啊……

说下我对这个问题的看法，在clone项目并进行构建的过程中，系统如果发现找不到local.properties，会自动生成并包含以下内容：
```kotlin
sdk.dir=C\:\\Users\\XXXX\\AppData\\Local\\Android\\Sdk
```
这就会导致 [build.gradle.kts L72](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/library/build.gradle.kts#L72) 的判断返回 true ，进而判断 localProperties 存在并尝试执行 `properties.getProperty("signing.keyId")` 进而引发错误。针对这个问题我的处理方案是将 ossrhUsername 相关信息放在 maven.properties 文件内:
![image](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/46998172/9402707e-d87c-4105-9893-0b7ac75f6943)
并修改判断条件为：
```kotlin
val secretPropsFile: File = project.rootProject.file("maven.properties")
if (secretPropsFile.exists()) {
    secretPropsFile.reader().use {
        Properties().apply {
            load(it)
        }
    }.onEach { (name, value) ->
        ext[name.toString()] = value
    }
} else {
    ext["signing.keyId"] = System.getenv("SIGNING_KEY_ID")
    ext["signing.password"] = System.getenv("SIGNING_PASSWORD")
    ext["signing.secretKeyRingFile"] = System.getenv("SIGNING_SECRET_KEY_RING_FILE")
    ext["ossrhUsername"] = System.getenv("OSSRH_USERNAME")
    ext["ossrhPassword"] = System.getenv("OSSRH_PASSWORD")
}
```
这样的话就不会出现这样的问题
