### ISSUE TITLE
LinearLayoutManager stackFromEnd = false无效

### ISSUE THREAD

**Issue by MhuiHugh** [CymChad/BaseRecyclerViewAdapterHelper#3795]
使用版本4.0.0-beta14，LinearLayoutManager.orientation=LinearLayoutManager.VERTICAL   多布局BaseMultiItemAdapter ，列表长度不满屏时列表贴底部绘制，上半部分空白。正常需要的是LinearLayoutManager.reverseLayout=false    LinearLayoutManager.stackFromEnd=false

**Comment by MhuiHugh** [comment]
`  rv.apply {
                llManager = LinearLayoutManager(context)
                llManager.orientation = LinearLayoutManager.VERTICAL
                llManager.reverseLayout = false
                llManager.stackFromEnd = false
                layoutManager = llManager
            }`
`
  <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
        app:stackFromEnd="false"
        app:reverseLayout="false"
        />
`

**Comment by MhuiHugh** [comment]
排除过布局设置，reverseLayout stackFromEnd不同true,false组合设置情况。目前暂时解决方案是设置RecyclerView高度wrap_content

**Comment by limuyang2** [comment]
这不是本库的问题哈，本库对 LayoutManger 没有任何相关操作。

stackoverflow 里面有这个相关问题
[[Android only setStackFromEnd only if RecycleView/List is larger than screen](https://stackoverflow.com/questions/44873389/android-only-setstackfromend-only-if-recycleview-list-is-larger-than-screen)](https://stackoverflow.com/questions/44873389/android-only-setstackfromend-only-if-recycleview-list-is-larger-than-screen)
