### ISSUE TITLE
4.0.0-beta14 再次执行下拉刷新，执行submitList导致列表数据重复

### ISSUE THREAD

**Issue by zhangnin** [CymChad/BaseRecyclerViewAdapterHelper#3796]
首次加载执行了submitList，下拉刷新再次执行submitList，数据重复

在设置数据之前先置空adapter.submitList(data)也不行，调用刷新也不行notifyDataSetChanged

**Comment by limuyang2** [comment]
给个demo  呢？

**Comment by limuyang2** [comment]
长时间未回复，先关闭了
