### ISSUE TITLE
BaseMultiItemAdapter  submitList 一次添加大量数据 页面卡顿

### ISSUE THREAD

**Issue by chengyaoy51** [CymChad/BaseRecyclerViewAdapterHelper#3799]
类似微信的聊天界面，通过日期查询聊天数据后（数据量很大），submitList 添加数据后 页面明显会卡顿 ，有的手机会闪退，请问有什么好的方式处理一次性添加大量数据？

**Comment by chengyaoy51** [comment]
使用的是4.0.1版本

**Comment by chengyaoy51** [comment]
> 类似微信的聊天界面，通过日期查询聊天数据后（数据量很大），submitList 添加数据后 页面明显会卡顿 ，有的手机会闪退，请问有什么好的方式处理一次性添加大量数据？

**Comment by xm2017** [comment]
loadingmore分页加载 多简单
