### ISSUE TITLE
我觉得这个 LoadState.NotLoading()可以加上@JvmStatic优化一下 Java 调用

### ISSUE THREAD

**Issue by Dboy233** [CymChad/BaseRecyclerViewAdapterHelper#3800]
<img width="708" alt="图片" src="https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/37604230/0f4b850c-33e9-4c00-a343-f0ae158904ac">

**Comment by limuyang2** [comment]
谢谢建议

**Comment by limuyang2** [comment]
已在 4.1.1 版本中添加
