### ISSUE TITLE
4.x版本 相同List 排序后再次提交 界面无响应

### ISSUE THREAD

**Issue by smalldayday** [CymChad/BaseRecyclerViewAdapterHelper#3802]
![image](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/46509783/05284a8d-04dc-4ab2-a9c0-145e7c36dd6f)

希望相同list时 增加notifyDataSetChanged方法

**Comment by shenyw0825** [comment]
对我也遇到了这种情况， 这个===有毒

**Comment by limuyang2** [comment]
三个等号 `===` 是用来判断是否是同一个对象引用

**Comment by limuyang2** [comment]
仔细想了一下，这里的判断确实没有必要，已经在 `4.0.3` 版本中去除，更新下版本吧
