### ISSUE TITLE
无限轮询

### ISSUE THREAD

**Issue by shenyw0825** [CymChad/BaseRecyclerViewAdapterHelper#3803]
在我使用RecyclerView 自定义了一个viewpager 时，设置无限轮询时，发现getitem无法被重写，这样导致item为空，目前使用items[真实position]获取的数据，建议能放开getItemApi的重写 
![image](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/141467786/a98ef172-53cd-4ada-9c34-53d6a94bee09)

![image] (https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/141467786/f76844cb-b2c0-433d-8340-fe6c4187eeed)

**Comment by limuyang2** [comment]
你可以自定义一个 `getRealItem()` 方法，
```
fun  getRealItem(pos: Int) = getItem(getRealPosition(pos))

```
