### ISSUE TITLE
能否 3.x 与 4.x 共存

### ISSUE THREAD

**Issue by svran** [CymChad/BaseRecyclerViewAdapterHelper#3809]
既然 与3.x 不兼容升级. 为什么4.x不换个包名呢?
这样可以在项目中同时使用3.x 和4.x, 然后慢慢重构逐渐替换掉3.x.

**Comment by limuyang2** [comment]
明白你的意思了，后续会调整一下

**Comment by limuyang2** [comment]
`4.1.0`版本已经可以共存

```
implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper4:4.1.0"
```

说明如下：[4.1.0](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/4.1.0)
