### ISSUE TITLE
关于DiffUtil的问题

### ISSUE THREAD

**Issue by sweet2o09** [CymChad/BaseRecyclerViewAdapterHelper#381]
你好,我在更新UI的时候发现Item会闪烁,recyclerview-v7-24.2出了个DiffUtil,听说能解决闪烁问题,不知道你们这个adapter是否有自己的解决闪烁的方法或者说能加入DiffUtil解决数据更新时闪烁问题

**Comment by ArtisanM** [comment]
recyclerview.setItemAnimator(null);

**Comment by CymChad** [comment]
@ArtisanM 感谢
