### ISSUE TITLE
关于旧版本迁移到4.x的问题

### ISSUE THREAD

**Issue by androidMsy** [CymChad/BaseRecyclerViewAdapterHelper#3811]
2.x或者3.x有没有什么好的方法可以不用挨个替换旧的API的迁移方式啊

**Comment by Reginer** [comment]
感觉可以改个包名，类似RxJava那种方式，可以共存的，逐渐替换

**Comment by androidMsy** [comment]
> 感觉可以改个包名，类似RxJava那种方式，可以共存的，逐渐替换

也是一个可行的方案

**Comment by limuyang2** [comment]
`4.1.0`版本已经可以共存

```
implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper4:4.1.0"
```

说明如下：[4.1.0](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/4.1.0)

**Comment by Reginer** [comment]
棒棒棒 ！

**Comment by Reginer** [comment]
棒棒棒 ！
