### ISSUE TITLE
局部刷新方法会调用全量刷新方法

### ISSUE THREAD

**Issue by wxw-9527** [CymChad/BaseRecyclerViewAdapterHelper#3815]
![image](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/34825527/1c709d1d-e376-4f3e-b783-263d00589a86)
使用局部刷新时全量刷新方法也执行了，发现这里对全量刷新方法进行了调用，请问这是个bug吗？

**Comment by limuyang2** [comment]
这里是是一个默认执行方式，重写的时候，去除 super。
