### ISSUE TITLE
错位的问题

### ISSUE THREAD

**Issue by jiahongyu0529** [CymChad/BaseRecyclerViewAdapterHelper#382]
我添加了多个类型的Item，比如图片，文字，滑动出现了错位的现象，这个是为什么，要怎么解决啊？

**Comment by Ludejin** [comment]
@jiahongyu0529 你找找ListView或者RecyclerView错位的解决方法，然后convert方法里处理下。

**Comment by fWX228941** [comment]
@jiahongyu0529 我处理过一次错位场景，原因是我的图片加载框架设置了图片缓存。
