### ISSUE TITLE
同时依赖 3.0.14 和 4.1.1 报错

### ISSUE THREAD

**Issue by yangjianhong** [CymChad/BaseRecyclerViewAdapterHelper#3824]
Duplicate class com.chad.library.BuildConfig found in modules jetified-BaseRecyclerViewAdapterHelper-3.0.14-runtime (io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.14) and jetified-BaseRecyclerViewAdapterHelper4-4.1.1-runtime (io.github.cymchad:BaseRecyclerViewAdapterHelper4:4.1.1)

**Comment by limuyang2** [comment]
更新到 4.1.2 版本
