### ISSUE TITLE
设置setStateViewLayout后，当有数据加载到RecyclerView时显示不全

### ISSUE THREAD

**Issue by GodLikeThomas** [CymChad/BaseRecyclerViewAdapterHelper#3827]
当前使用的版本号: 4.1.3
先显示stateView再加载数据：
![Screenshot_20231208_134001](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/10253785/257acd80-e017-4c9d-9729-327e1afc3ffc)
![Screenshot_20231208_133859](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/10253785/f2cac5b1-4ab0-4741-8a5c-5c4a89ced9f0)
加载数据后，再把数据清空：
![Screenshot_20231208_134155](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/10253785/c623330f-8551-410a-990f-57230518576e)

如果不设置stateVeiew就会正常按数据内容变到最大：
![Screenshot_20231208_133917](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/10253785/274ff2e4-82c2-45df-80eb-a0232106ac5a)

需要延迟调用notifyDataSetChanged()，界面才会恢正常。submitList()之后马上再调用notifyDataSetChanged()无效

**Comment by limuyang2** [comment]
RecyclerView 的高度直接铺满，stateView 的尺寸看你的情况调整。

**Comment by GodLikeThomas** [comment]
情况不知道高度具体要多少，我这个布局跟BaseMultiItemAdapter一起使用，没办法设定一个具体高度，只是限制了最多显示数量

**Comment by limuyang2** [comment]
> > RecyclerView 的高度直接铺满，stateView 的尺寸看你的情况调整。
> 
> 这个界面是BaseMultiItemAdapter中的一个布局，这个列表是不能滑动的，只有一个最大显数量，所以没办法设置他的一个固定高度

recyclerView是一定需要一个可确定的高度，要不然 recyclerView 的复用机制都会出问题
