### ISSUE TITLE
真是烂尾, 白忙活一天

### ISSUE THREAD

**Issue by JasonQS** [CymChad/BaseRecyclerViewAdapterHelper#3831]
从2.9.49 尝试更新到最新板, 发现文档一坨屎, 函数名取的也屎

更新 Dragable 功能
不知道怎么实现旧版本的按住某一图标拖动, 只能长按任意位置一起拖动

引用一下文档的例子
> mAdapter.setOnItemClickListener((adapter, view, position) -> {
            Tips.show("点击了：" + position + "，侧滑可进行删除" + position);
            quickDragAndSwipe.startSwipe(position);//点击后，允许侧滑删除功能
        });

我就奇怪了, 点击触发完, 手都抬起来了, 还怎么拖动?

> mAdapter.setOnItemLongClickListener((adapter, view, position) -> {
            /*
             * 长按默认可拖动，可不进行设置此方法
             * 此方法可以做特殊使用进行调用
             * 如：长按此条position对应的item，触发 position+1 对应的item
             * 此处使用，关闭了默认长按拖拽功能
             */
            Tips.show("长按了：" + position + "，现在拖动可进行变换位置");
            quickDragAndSwipe.startDrag(position);//长按后，允许进行拖拽
            return false;
        });

我这根本接收不到 longClick 事件, 而且在示例 app 里, 也没有 longClick 相关的监听

更新向上向下加载, onLoad() 回调也出不来, 
LeadingLoad() TrailingLoad() 这函数名取的什么东西

setItems(), submitList(), addAll(), 为什么语义这么近的功能却有 3 个函数

真是烂尾

**Comment by liangjingkanji** [comment]
这么喜欢看文档?, 那给你看个够 [BRV拖拽](https://liangjingkanji.github.io/BRV/drag.html)

**Comment by limuyang2** [comment]
> 从2.9.49 尝试更新到最新板, 发现文档一坨屎, 函数名取的也屎
> 
> 更新 Dragable 功能 不知道怎么实现旧版本的按住某一图标拖动, 只能长按任意位置一起拖动
> 
> 引用一下文档的例子
> 
> > mAdapter.setOnItemClickListener((adapter, view, position) -> {
> > Tips.show("点击了：" + position + "，侧滑可进行删除" + position);
> > quickDragAndSwipe.startSwipe(position);//点击后，允许侧滑删除功能
> > });
> 
> 我就奇怪了, 点击触发完, 手都抬起来了, 还怎么拖动?
> 
> > mAdapter.setOnItemLongClickListener((adapter, view, position) -> {
> > /*
> > * 长按默认可拖动，可不进行设置此方法
> > * 此方法可以做特殊使用进行调用
> > * 如：长按此条position对应的item，触发 position+1 对应的item
> > * 此处使用，关闭了默认长按拖拽功能
> > */
> > Tips.show("长按了：" + position + "，现在拖动可进行变换位置");
> > quickDragAndSwipe.startDrag(position);//长按后，允许进行拖拽
> > return false;
> > });
> 
> 我这根本接收不到 longClick 事件, 而且在示例 app 里, 也没有 longClick 相关的监听
> 
> 更新向上向下加载, onLoad() 回调也出不来, LeadingLoad() TrailingLoad() 这函数名取的什么东西
> 
> setItems(), submitList(), addAll(), 为什么语义这么近的功能却有 3 个函数
> 
> 真是烂尾

那看来本酷不合适你，方法命名都是和 kotlin 一致的，由此推断看来 kotlin 也不适合你。wiki看不懂就去看demo，demo还看不懂请远离本库。
作者没收你们一分钱，上来就嘴巴不干净，你牛批，你可以写一个嘛，我们都来学习学习。觉得有bug提pr，或者自己下源码改啊。没有人，有义务为你们免费劳动。

楼上京东老哥给了他的库，你不喜欢这个就用别家的呗。哦，对了，你可能都没听说过楼上这位大神。

**Comment by limuyang2** [comment]
> 这么喜欢看文档?, 那给你看个够 [BRV拖拽](https://liangjingkanji.github.io/BRV/drag.html)
> 
> 添加数据只有一个属性一个方法, 一个Adapter处理所有功能
> 
> <img alt="image" width="456" src="https://private-user-images.githubusercontent.com/21078112/291091349-73b362bf-e79f-45af-9f2a-dfd7c63a916b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTEzNjksIm5iZiI6MTcwMjg5MTA2OSwicGF0aCI6Ii8yMTA3ODExMi8yOTEwOTEzNDktNzNiMzYyYmYtZTc5Zi00NWFmLTlmMmEtZGZkN2M2M2E5MTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA5MTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YzY4NTZmNDhmYjcxMWFiNjg5YjE3MDk2ZDkyNzQ5NWFkNTUxZGVhZDQxNzBjODJhODdiOTk5NTE3M2U1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7JR3JXJnts-RX5Rd6pinaFlHyQsJcmm6l7AtehRrwVk">

东哥，这个人劝你也远离，免得难受

**Comment by liangjingkanji** [comment]
@limuyang2  

我只是装个b, 开源的东西谁用了谁就有义务维护, 又不是出售商品还能找售后, 他觉得不好用就立刻删除自己写
不过这么大个项目也就靠小火龙你维护这么多年了

**Comment by JasonQS** [comment]
@liangjingkanji  谢谢. 我在当天就翻到了这里夸 BRV 的 issue, 看完你的 demo 和文档, 才发现有更好的选择

**Comment by JasonQS** [comment]
@limuyang2  当然, 我作为使用者, 完全不能要求贡献者怎样怎样, 这里我道歉. 
我记得 19 年时 这个库的 star 就很多了, 当时还是 2.x 版本. 
我这次想更新 是想加上动画, 但发现这些更新并不能兼容旧版本, 实现部分旧版本的功能. 并且并不觉得更方便. 或许你能给我上一课, 给 adapter 外再加一个 helper 的好处是什么? 本来链式直接猜函数名就好, 现在必须查文档

**Comment by limuyang2** [comment]
> @limuyang2 当然, 我作为使用者, 完全不能要求贡献者怎样怎样, 这里我道歉. 我记得 19 年时 这个库的 star 就很多了, 当时还是 2.x 版本. 我这次想更新 是想加上动画, 但发现这些更新并不能兼容旧版本, 实现部分旧版本的功能. 并且并不觉得更方便. 或许你能给我上一课, 给 adapter 外再加一个 helper 的好处是什么? 本来链式直接猜函数名就好, 现在必须查文档

没关系

**Comment by limuyang2** [comment]
> @limuyang2 当然, 我作为使用者, 完全不能要求贡献者怎样怎样, 这里我道歉. 我记得 19 年时 这个库的 star 就很多了, 当时还是 2.x 版本. 我这次想更新 是想加上动画, 但发现这些更新并不能兼容旧版本, 实现部分旧版本的功能. 并且并不觉得更方便. 或许你能给我上一课, 给 adapter 外再加一个 helper 的好处是什么? 本来链式直接猜函数名就好, 现在必须查文档

helper 是为了使用 `ConcatAdapter`

**Comment by limuyang2** [comment]
> @limuyang2
> 
> 我只是装个b, 开源的东西谁用了谁就有义务维护, 又不是出售商品还能找售后, 他觉得不好用或不会用就立刻删除自己写 不过这么大个项目也就靠小火龙你无私维护这么多年了

东哥境界高

**Comment by penggg2024** [comment]
东哥是刘强东吗，这么添
