### ISSUE TITLE
    设置 空 view 不显示

### ISSUE THREAD

**Issue by yangjianhong** [CymChad/BaseRecyclerViewAdapterHelper#3836]
var click = false
 homeAdapter.setStateViewLayout(homeAdapter.context, R.layout.loading_view)
 binding.btn.setOnClickListener {
            click = !click
            if (click) {
                homeAdapter.setStateViewLayout(homeAdapter.context, R.layout.empty_view)
                homeAdapter.submitList(arrayListOf())
            } else {
                homeAdapter.submitList(homeItemData)
            }
        }

demo 中 这样设置 空view 不显示

**Comment by GaaMf** [comment]
2b

**Comment by yangjianhong** [comment]
可能是我没说清楚  设置 了 laodingView 和 emptyView  这两个 没法自由切换 设置了 loadingView 再设置 emptyView 重复操作显示这两个view 只显示一个view  楼上的搞不清状况 瞎评论

**Comment by GaaMf** [comment]
你不说清楚，人家怎么给你解答，屁大点事就跑来问，人家是解决框架bug的不是给你一个人解决bug的。这么简单的问题都整不明白放弃吧。问题都描述不清楚你没事的时候想想谁在瞎评论。

**Comment by yangjianhong** [comment]
我问你了吗？

**Comment by GaaMf** [comment]
知道自己确实2b，准备换个角度了？Clown

**Comment by yangjianhong** [comment]
你牛b行了吧，懒得理你

**Comment by yangjianhong** [comment]
这里是解决问题的平台，你看看你

**Comment by GaaMf** [comment]
我看你就够开心的了，看我啥，我又不是巨婴

**Comment by yangjianhong** [comment]
谁家狗没栓绳跑出来了，乱咬，打死

**Comment by GaaMf** [comment]
恼羞成怒，没有理，玩不起，小丑竟是你自己。智商低，坏脾气，活脱一个小卡了咪。oh yeah~

**Comment by yangjianhong** [comment]
sb-------- 原始邮件 --------发件人： GaaMf ***@***.***>日期： 2024年1月1日周一 18:49收件人： CymChad/BaseRecyclerViewAdapterHelper ***@***.***>抄送： yangjh ***@***.***>, State change ***@***.***>主    题： Re: [CymChad/BaseRecyclerViewAdapterHelper]     设置 空 view 不显示 (Issue #3836)
恼羞成怒，没有理，玩不起，小丑竟是你自己。智商低，坏脾气，活脱一个小卡了咪。oh yeah~

**Comment by GaaMf** [comment]
引用：”var click = false
homeAdapter.setStateViewLayout(homeAdapter.context, R.layout.loading_view)
binding.btn.setOnClickListener {
click = !click
if (click) {
homeAdapter.setStateViewLayout(homeAdapter.context, R.layout.empty_view)
homeAdapter.submitList(arrayListOf())
} else {
homeAdapter.submitList(homeItemData)
}
}

demo 中 这样设置 空view 不显示“

你配得上sber 或者 sbest

**Comment by yangjianhong** [comment]
sb

**Comment by GaaMf** [comment]
is yangjianhong

**Comment by yangjianhong** [comment]
sb 网络喷子 键盘侠

**Comment by GaaMf** [comment]
sb 羊煎紅

**Comment by yangjianhong** [comment]
没有教养 随便咬人

**Comment by yangjianhong** [comment]
真是 看见谁咬谁

**Comment by GaaMf** [comment]
杨建红恼羞成怒，蠢不自知，浪费他人时间，毫无逻辑的巨婴还敢谈教养，真是想送他 ”春池嫣韵“

**Comment by yangjianhong** [comment]
sb

**Comment by GaaMf** [comment]
恶犬复读机 不要停

**Comment by GaaMf** [comment]
不要停  who is your daddy

**Comment by yangjianhong** [comment]
去年买了个表

**Comment by GaaMf** [comment]
建红小儿，你不但逻辑不行，脑子也不灵光啊，咬人要么重复要么包浆的词

**Comment by GaaMf** [comment]
建红小儿 为何还不回复  who is your daddy

**Comment by GaaMf** [comment]
建红小儿 为何改名

**Comment by Lemon-666-byte** [comment]
没有教育好 怕我孙子 天天挂在嘴边

**Comment by Lemon-666-byte** [comment]
sb
