### ISSUE TITLE
关于childView的点击事件

### ISSUE THREAD

**Issue by yuruxuan** [CymChad/BaseRecyclerViewAdapterHelper#384]
本人在使用BRVAH的时候  Item内部有个TextView 其中的一部分区域设置Touch事件，举例来说像是微博话题，但是我们在用这个Adapter的时候  只能绑定整个TextView，响应效果如下：
1.当我绑定TextView的时候，同时响应话题事件和SimpleOnItemChildClick（我可以不进行处理）
2.当我不绑定TextView时候，同时响应话题事件和onItemClick

我希望在TextView中点击话题链接仅响应话题事件，点击非话题链接文字部分响应onItemClick，这个应该怎么做呢？

Link 是 compile 'com.klinkerapps:link_builder:1.3.2' 这家的

下面是代码

            TextView text_content = baseViewHolder.getView(R.id.text_content);
            if (item.getTopic() != null) {
                        String str = "#" + item.getTopic().getCtname() + "# " + item.getTitle();
                        text_content.setText(str);
                        Link link = new Link("#" + item.getTopic().getCtname() + "#");
                        link.setTextColor(Color.parseColor("#ff5722"));
                        link.setUnderlined(false);
                        link.setOnClickListener(new Link.OnClickListener() {
                            @Override
                            public void onClick(String clickedText) {
                                Intent intent = new Intent(mContext, CircleContentActivity.class);
                                intent.putExtra("Circle", item.getTopic());
                                mContext.startActivity(intent);
                            }
                        });
                        LinkBuilder.on(text_content)
                                .addLink(link)
                                .build();
                    } else {
                        text_content.setText(item.getTitle());
        }

**Comment by AllenCoder** [comment]
测试发现，确实不能同时两个条件都满足。目前的点击事件是 顶层的Recyclerview先截获，然后消费掉，
Link 这个第三方组件之后才能收到点击事件 ，目前的处理办法是，能否把需要点击的话题部分单独抽成一个TextView，注入到childview 的点击事件里面 ，这样可以很好的区分 。
