### ISSUE TITLE
建议打包不要混淆吧...看源码很不舒服的。。。。

### ISSUE THREAD

**Issue by yygutn** [CymChad/BaseRecyclerViewAdapterHelper#385]

**Comment by CymChad** [comment]
打包是通过  https://jitpack.io  打包的，没有做过特殊处理。

**Comment by yygutn** [comment]
> 打包是通过 https://jitpack.io 打包的，没有做过特殊处理。


那为什么我的AS 通过 compile 之后点进去看到的代码是混淆过的= =
