### ISSUE TITLE
头部更多，页面初始化，没有手动下拉滑动，QuickAdapterHelper setLeadingLoadStateAdapter为何会自动加载更多？

### ISSUE THREAD

**Issue by DongJohnson** [CymChad/BaseRecyclerViewAdapterHelper#3857]
![%VHOE$~2TLO5YF_~)_}A@9P](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/assets/38447881/c8325db8-18fa-4566-adee-0c3a382dac81)头部更多，下拉加载更多的时候，页面初始化没有手动滑动，QuickAdapterHelper setLeadingLoadStateAdapter为何会自动加载更多？

**Comment by lixiongh-hou** [comment]
我也遇到同样问题，大佬是如何解决的，求告知
