### ISSUE TITLE
下拉加载数据 addData(int p,List l)

### ISSUE THREAD

**Issue by sujianqingfeng** [CymChad/BaseRecyclerViewAdapterHelper#386]
当List数据size为空  第一次调用addData（0，list）没有反应  
我自己加了一个第一次判断才可以 
 ` if (isMore)
            adapter.addData(list);
        else{
            if (isFrist){
                isFrist=false;
                adapter.addData(list);
            }
            else
                adapter.addData(0, list);
        }`

我希望的写法是这个样子的
 ` if (isMore)
            adapter.addData(list);
        else  
            adapter.addData(0, list);`

**Comment by Ludejin** [comment]
@sujianqingfeng 建议，以为list的size为0的时候if (0 <= position && position < mData.size())这里的第二个条件不符合，建议if (isMore) adapter.addData(list); else adapter.setNewData(list);

**Comment by Ludejin** [comment]
@sujianqingfeng 但是如果改为if (0 <= position && position <= mData.size())，有数据的时候，刚好在最后添加也会出现越界，得不偿失，又提供了setNewData()，也没必要。

**Comment by sujianqingfeng** [comment]
ok
