### ISSUE TITLE
2.1.9添加allowBackup="true"有何作用吗？

### ISSUE THREAD

**Issue by axkza** [CymChad/BaseRecyclerViewAdapterHelper#388]
本来2.1.8可以用的，换成2.1.9的时候提示
Manifest merger failed with multiple errors，see logs。

我暂时的解决办法的在application中添加replace解决这个冲突，但不是很明白为什么作者要添加这个？
如果没用可否在源码中直接删掉？
< application
        ...
        tools:replace="allowBackup">

**Comment by CymChad** [comment]
恩，可以。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.0'  已经删除了。
