### ISSUE TITLE
BaseQuickAdapter没有getViewHolderPosition方法，怎么在convert获取对应的position？

### ISSUE THREAD

**Issue by axkza** [CymChad/BaseRecyclerViewAdapterHelper#389]

**Comment by CymChad** [comment]
int position=viewhodler.getLayoutPosition();

**Comment by AlceZhang** [comment]
viewhodler.getLayoutPosition();这种方式获取的position是有问题的 只是针对屏幕能显示的position  并不是我想要的  我想要针对所所有数据的一个position
