### ISSUE TITLE
能否考虑一下加入RecyclerView的SwipeMenu操作？

### ISSUE THREAD

**Issue by palapalawj** [CymChad/BaseRecyclerViewAdapterHelper#39]
是从微博（伯乐在线的官博）上看到的，也是刚刚试用了一下，仅仅是看demo就感觉满足日常所需，但是我当前在重构之前的项目，由于之前使用的ListView使用了SwipeMenu，在重构过程中全部将ListView替换成RecyclerView，其它的感觉还比较好解决，使用了您的代码后确实是将Adapter代码量减少了很多，高度封装且接口使用简单，这个是我很短时间内的使用感受。只是有一个问题，如何将SwipeMenu集成进来，不想分开做，感觉很冗余，水平有限，特此求助。
另：附上实现SwipeMenu地址：http://www.open-open.com/lib/view/open1453175513105.html。
再次感谢，源码尚未全部阅读，已然受益匪浅。
以上。

**Comment by CymChad** [comment]
我先看看，SwipeMenu先。到时给你回复，就算不加入，我也给你封装的解决方案。

**Comment by CymChad** [comment]
我看了，不合适，因为需要改到RecyclerView，我这个只是负责adapter，不能越界。建议组合使用，这样解耦，并不冲突。你可以自己封装到项目里面。如果我集成进来，其他的使用者就会觉得我的adapter冗余了。所以非常抱歉。
