### ISSUE TITLE
item的长按事件和拖拽事件

### ISSUE THREAD

**Issue by Hao-Kid** [CymChad/BaseRecyclerViewAdapterHelper#392]
1.item的长按事件和拖拽事件会有冲突
2.先给itemView 设置背景:被点击时和默认状态背景
拖拽完成后,被拖拽的itemView 背景一直处于被点击时的背景

**Comment by myheat** [comment]
我也遇到了这样的问题，同求

**Comment by elfman** [comment]
1. enableDragItem时后面有两个参数可以指定长按触发还是触摸触发，以及触发拖拽的viewId。如果你是想在拖拽时同时执行一些事件，则需放到onItemDragListener内
2. listener的onItemDragEnd会在拖拽完成后执行，在那里将背景重置会拖拽前的背景即可

**Comment by MagnifierSun** [comment]
把点击事件的id 和拖拽的id设置成一样的就可以
