### ISSUE TITLE
expandableitem

### ISSUE THREAD

**Issue by personalxia** [CymChad/BaseRecyclerViewAdapterHelper#393]
点击一级item的会重新加载一级item的，能不能不重新加载呢

**Comment by elfman** [comment]
不太理解你这问题具体什么意思？“加载”指加载什么？你是指删除view后又重新生成吗？

**Comment by personalxia** [comment]
@elfman 就是点击一级item的时候，会闪一下

**Comment by elfman** [comment]
expand时会对被点击的item调用notifyItemChanged，因为我觉得在展开时被点击的item有可能需要做一些改变，这可能是导致在你项目里闪一下。如果你不想要这样，需要重写expand函数，复制我的源码，然后删了那句notify

**Comment by personalxia** [comment]
好的，我明白了，谢谢你的解答

**Comment by personalxia** [comment]
@elfman 话说你这里这个方法里面好多方法都是私有的，我复制过来也用不了啊

**Comment by personalxia** [comment]
@elfman 或者我觉得可以把这个交给使用者去设置，想改动被点击的item然后在加那句话，不想的话就算了

**Comment by elfman** [comment]
你继承后重写expand(int pos, Boolean anim, boolean notify)这一个函数就行了，没让你复制整个类啊

**Comment by personalxia** [comment]
已经搞好了，谢谢

**Comment by Jarvay** [comment]
@personalxia 请问这个你是怎么解决的？ 
expand(int pos, Boolean anim, boolean notify)这个方法里面有几个私有的方法的
