### ISSUE TITLE
OnItemDragListener和OnItemChildClickListener冲突

### ISSUE THREAD

**Issue by kealsoul** [CymChad/BaseRecyclerViewAdapterHelper#394]
使用OnItemDragListener之后，在使用OnItemChildClickListener没法监听到事件。

**Comment by CymChad** [comment]
拖拽 跟点击冲突 ，应该是recyclerview的onTouch消费掉了触摸事件，，导致拖拽失效

**Comment by CymChad** [comment]
onTouch被消费掉了。

**Comment by AllenCoder** [comment]
你好，测试没有发现冲突？是否跟你的代码使用有关？或者特殊情形我们还未考虑到？
[https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0Item%E4%BA%8B%E4%BB%B6](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0Item%E4%BA%8B%E4%BB%B6)
参考wiki ，修改你的itemchild的点击事件，如还有问题，请继续反馈。
