### ISSUE TITLE
分组的伸缩栏可以禁用折叠么，让他一直处于展开状态怎么设置？

### ISSUE THREAD

**Issue by yyf1994** [CymChad/BaseRecyclerViewAdapterHelper#395]
分组的伸缩栏可以禁用折叠么，让他一直处于展开状态怎么设置？

**Comment by elfman** [comment]
你不调用collapse函数就不会折叠了，这个是由你控制的

**Comment by yyf1994** [comment]
我想让他进入时是展开状态怎么设置呢

**Comment by elfman** [comment]
在初始化时就调用expand的另一版本，后面两个参数设置为false禁用动画，应该能满足你的需求了吧

**Comment by yyf1994** [comment]
可以说详细一点么 不太清楚 另一个版本是哪个

**Comment by elfman** [comment]
expand(int pos, boolean animation, boolean notify)，后面两个参数传入false

**Comment by yyf1994** [comment]
for (int i = 0; i < list.size(); i++) {
            adapter.expand(i,false,false);
        }
list有4条数据 但是只展开了2个

**Comment by elfman** [comment]
展开后的子项会插入到列表中，position的值就不一样，你应该从后往上遍历

**Comment by elfman** [comment]
展开后的子项会插入到列表中，position的值就不一样，你应该从后往上遍历

**Comment by elfman** [comment]
for(int i=list.size()-1; i>=0; i--)

**Comment by yyf1994** [comment]
谢谢 解决了
