### ISSUE TITLE
why not use notifydatainsert     

### ISSUE THREAD

**Issue by yanglichuan** [CymChad/BaseRecyclerViewAdapterHelper#397]
when adddata  you use notifydatasetchanged  

why not use notifydatainsert     

  public void addData(List<T> newData) {
        this.mData.addAll(newData);
        if(this.mNextLoadEnable) {
            this.mLoadingMoreEnable = false;
        }

        this.notifyDataSetChanged();
    }

**Comment by CymChad** [comment]
你的版本应该是低版本把？

**Comment by CymChad** [comment]
最新的代码是notifydatainsert
