### ISSUE TITLE
java.lang.NullPointerException in

### ISSUE THREAD

**Issue by yanglichuan** [CymChad/BaseRecyclerViewAdapterHelper#398]
#1 main
java.lang.NullPointerException
解析原始
}
1 com.chad.library.adapter.base.BaseQuickAdapter.showLoadMoreFailedView(BaseQuickAdapter.java:782)
2 com.ks.kaishustory.fragment.RecycleViewFregment_New.adapterLoadError(RecycleViewFregment_New.java:111)
3 com.ks.kaishustory.fragment.impl.CollctionStoryFragment.access$600(CollctionStoryFragment.java:32)
4 com.ks.kaishustory.fragment.impl.CollctionStoryFragment$2.onError(CollctionStoryFragment.java:122)
5 com.ks.kaishustory.request.HttpRequestHelper$3.onError(HttpRequestHelper.java:329)

**Comment by CymChad** [comment]
这个bug和 #399 一样
