### ISSUE TITLE
java.lang.NullPointerException in

### ISSUE THREAD

**Issue by yanglichuan** [CymChad/BaseRecyclerViewAdapterHelper#399]
#1 main
java.lang.NullPointerException
Attempt to invoke virtual method 'android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup)' on a null object reference
解析原始
}
1 com.chad.library.adapter.base.BaseQuickAdapter.showLoadMoreFailedView(BaseQuickAdapter.java:782)
2 com.ks.kaishustory.fragment.RecycleViewFregment_New.adapterLoadError(RecycleViewFregment_New.java:111)
3 com.ks.kaishustory.fragment.impl.CollctionStoryFragment.access$600(CollctionStoryFragment.java:32)
4 com.ks.kaishustory.fragment.impl.CollctionStoryFragment$2.onError(CollctionStoryFragment.java:122)
5 com.ks.kaishustory.request.HttpRequestHelper$3.onError(HttpRequestHelper.java:329)

**Comment by CymChad** [comment]
你的使用代码是？

**Comment by shichaohui** [comment]
参考 #253 #329 ，一样的问题。
