### ISSUE TITLE
 convert(BaseViewHolder helper, Status item) 建议返回增加一个position返回，某些情况下用到，过来人

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#400]
convert(BaseViewHolder helper, Status item) 建议返回增加一个position返回，某些情况下用到，过来人

**Comment by CymChad** [comment]
int position= helper.getLayoutPosition();

**Comment by ldqing666** [comment]
helper.getLayoutPosition();在最新的Android Studio Bumblebee 版本上报红，虽然也可以运行。
