### ISSUE TITLE
作者你好，我用了V1.9.8和2.0以上版本然后发现addData（）这个方法有bug

### ISSUE THREAD

**Issue by MaskEgo** [CymChad/BaseRecyclerViewAdapterHelper#401]
之前用了V1.9.8，调用addData（），然后刷新界面能够显示出新数据，但是2.0以上版本却不行了，显示不出来，有点不明白。因为你的demo都是这个方法，但是2.0以上却不行，我应该怎么办

**Comment by elfman** [comment]
请具体描述是什么BUG？

**Comment by MaskEgo** [comment]
就是addData（）这个方法，我上拉加载更多，然后适配器调用addData（），然后把新的数据展示在界面上，在V1.9.8这个版本，能够展示出我刷新的数据，但是2.0以上版，用同样的方法，展示不出刷新的数据。

**Comment by elfman** [comment]
你调试过了吗？执行addData之后数据有没有添加到mData里？你确定你的数据没有问题？

**Comment by MaskEgo** [comment]
数据没问题，都调试了。

**Comment by MaskEgo** [comment]
算了，我用v1.9.8把，也好用。

**Comment by CymChad** [comment]
贴一下使用代码？
