### ISSUE TITLE
不懂的地方，求指导

### ISSUE THREAD

**Issue by lsh123456789** [CymChad/BaseRecyclerViewAdapterHelper#405]
1、为什么刚进入页面就触发loadmore方法
 
2、加载完全部数据之后调用Adapter.loadComplete(); 如何在用户再次下拉时显示出加载更多布局。

**Comment by CymChad** [comment]
1.你没有`mQuickAdapter.openLoadMore(PAGE_SIZE);`
PageSize的作用
```java
private boolean isLoadMore() {
return mNextLoadEnable && pageSize != -1 && mRequestLoadMoreListener != null && mData.size() >= pageSize;
}
```

**Comment by CymChad** [comment]
2.下拉刷新的时候你setNewData就可以了。
具体你可以看到demo，案例。

**Comment by lsh123456789** [comment]
第一个知道了。第二个问题刚才说错了，是加载完全部数据之后调用Adapter.loadComplete(); 如何在用户再次上拉时显示出加载更多布局。

**Comment by lsh123456789** [comment]
是不是加载完全部数据之后添加一个无更多数据的脚布局

**Comment by CymChad** [comment]
恩 是的。demo的代码都有写的。

**Comment by lsh123456789** [comment]
好的，谢谢

**Comment by CymChad** [comment]
恩，感谢你的使用。
