### ISSUE TITLE
上滑加载更多不通用，和时间项目差距有点大，希望改进

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#406]
上滑加载更多不通用，和时间项目差距有点大，希望改进

**Comment by elfman** [comment]
请问你是想如何改进？你这样的提问完全不懂你想要改成什么样

**Comment by douya40** [comment]
private void showList(List<AllConsumeOrderInfo.DataBean> tlist) {
        if (recyclerAdapter == null) {
            mylist=tlist;
            recyclerAdapter = new RecyclerAdapter<AllConsumeOrderInfo.DataBean>(getActivity(), tlist, R.layout.xfinfo_item) {
                @Override
                public void convert(RecycleHolder holder, final AllConsumeOrderInfo.DataBean data, int position) {
                    GlideImgManager.loadImage(getActivity(), data.getUserIcon(), (ImageView) holder.findView(R.id.image_tx));
                    holder.setText(R.id.name, data.getUsername());
                    holder.setText(R.id.textView3, "订单号：" + data.getTradeId());
                    holder.setText(R.id.createTime, "订单时间：" + data.getCreateTime());
                    holder.setText(R.id.price, data.getNum() + "元");
                    if (data.getState() == 0) {
                        holder.setText(R.id.state, "未支付");
                    } else if (data.getState() == 1) {
                        holder.setText(R.id.state, "已支付");
                    }
                }
            };
            recyclerview.setAdapter(recyclerAdapter);
        }else {
            if (tlist == null || tlist.size() == 0) {
                tlist = tlist;
            } else {
                for (int i = 0; i < tlist.size(); i++) {
                    tlist.add(tlist.get(i));
                }
            }
            recyclerAdapter.onDateChange(tlist);
        }
    }

**Comment by douya40** [comment]
封装个万能RecyclerAdapter直接可以new出来，传对应的参数。返回对应的值，里面的封装一个上拉刷新的，在加个开关，这个很通过用。

**Comment by douya40** [comment]
最主要的是能够通用，使用泛型

**Comment by CymChad** [comment]
请具体说一下，改进建议？

**Comment by CymChad** [comment]
你是说扩展viewHolder吗？

**Comment by douya40** [comment]
定义一个Adapter接受泛型对象，可以直接在activity、fragment里面实列化，这样可以避免写很多adapter类，所以得都共用一个

**Comment by CymChad** [comment]
你是说实体数据类型对吗？

**Comment by douya40** [comment]
en

**Comment by CymChad** [comment]
现在是泛型呀。

**Comment by douya40** [comment]
现在是要单独建一个类，adapter不能所以的共用一个

**Comment by CymChad** [comment]
mRecyclerView.setAdapter(new BaseQuickAdapter<Status>(DataServer.getSampleData(100)) {
            @Override
            protected void convert(BaseViewHolder helper, Status item) {
                
            }
        });

**Comment by douya40** [comment]
convert能返回一个position 吗？有些情况下可能用到

**Comment by CymChad** [comment]
helper.getLayoutPosition 可以拿到。

**Comment by CymChad** [comment]
还有其他问题吗？

**Comment by douya40** [comment]
没有了谢谢

**Comment by CymChad** [comment]
恩，好的，感谢你的使用。
