### ISSUE TITLE
怎样向可分组的伸缩栏中的adapter中传入多个list

### ISSUE THREAD

**Issue by yyf1994** [CymChad/BaseRecyclerViewAdapterHelper#407]
我想在 TYPE_PERSON 中使用list 请问可以这样用么

**Comment by elfman** [comment]
你需要新建一个类，继承AbstractExpandableItem或IExpandable，在getSubItems方法中返回List，按照demo写有什么问题吗？

**Comment by CymChad** [comment]
联系到了提问者，问题已解决了。
