### ISSUE TITLE
onrefresh  is  after  then  onloadmore ?

### ISSUE THREAD

**Issue by yanglichuan** [CymChad/BaseRecyclerViewAdapterHelper#408]
when first enter， the  activity   run the  onloadmore

but  the first page  date  very long  and i did not scroll to end    so  onloadmore  should not be  apply

is  my wrong in use

**Comment by CymChad** [comment]
mQuickAdapter.openLoadMore(PAGE_SIZE);  这个你设置了吗？

**Comment by xqc63** [comment]
在只添加了footview的情况下，设置了pagesize依然会调用加载更多
if(position == this.mData.size() + this.getHeaderLayoutCount()) {
                    if(this.mNextLoadEnable) {
                        return 546;
                    }
                    return 819;
                }
这里应该返回footview，结果却返回了loadview

**Comment by CymChad** [comment]
footview 只能在数据加载完后你再加，否则不可能同时loadview 和 footview 一起出现。

**Comment by yanglichuan** [comment]
我pagesize 设置 10  但是我们的后台有可能返回 7个或者8个   但是还有下一页

所以就造成了如果设置了openLoadMore（size）

就无法加载下一页了

**Comment by CymChad** [comment]
那你就可以写小一点 pageSize 但是最起码要满足一个屏幕。
