### ISSUE TITLE
多类型item的适配器时

### ISSUE THREAD

**Issue by feer921** [CymChad/BaseRecyclerViewAdapterHelper#41]
目前BaseRecyclerViewAdapterHelpter在满足多类型的item时，需要使用方在写Bean时继承MultiItemEntity,
但是一般情况下使用方的Bean会继承他们自己的BaseBean,所以这样会导致别人要改，
我的建议是框架提供通用的item布局类型，eg:HEADER_VIEW;EMPTY_VIEW;LOADING_VIEW;FOOTER_VIEW;
剩下的item布局类型交给使用方的具体子类去依照他自己的Bean去区分提供，也即int getDefItemViewType(int position) {},但由于目前abstract class BaseMultiItemQuickAdapter<T extends MultiItemEntity> 中T 限制需要继承MultiItemEntity,所以对使用方有所限制,可以把 MultiltemEntity提升为接口，这样使用方自己的Bean仍然可以继承他们自己的BaseBean，并且实现MultiItemEntity提升后的接口就行了。

**Comment by CymChad** [comment]
感谢建议，我想想。

**Comment by walkthehorizon** [comment]
怎么说，我觉得将MultiltemEntity提升为接口的话，那内部的Type设置和返回又要使用者自己写了，当然尽管代码量很少。那可不可以让你的baseBean直接继承MultiltemEntity，那不是保证了固定的Type设定代码又可以继续扩充

**Comment by CymChad** [comment]
恩，越灵活的东西越麻烦。各有利弊。

**Comment by CymChad** [comment]
并且自己实现Type的话，理论上都是一样的代码。。

**Comment by HowardWW** [comment]
现在使用Realm的情况下，必须要继承RealmObject，所以建议在这一块提供两个标准，一是接口，二是基类。灵活度高的能更好适应现在的新型数据库。

**Comment by walkthehorizon** [comment]
为了使用Realm目前直接是写两个基本一样的module
