### ISSUE TITLE
拖动第一个item到其他地方时，有时候会出现其他的item不会自动填充到第一个item的位置，造成第一个item空着

### ISSUE THREAD

**Issue by Samge0** [CymChad/BaseRecyclerViewAdapterHelper#410]

**Comment by elfman** [comment]
你的recyclerview里有多少种itemtype？所有item的宽度都一样吗？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/312 如果是不同的itemType 可以参考。
