### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#412]
![fd6a40d5e20439d8f9643eec7ed78505_](https://cloud.githubusercontent.com/assets/7565399/19508635/d0fdc522-960c-11e6-8707-79fb26546f40.jpg)

请问下这个是怎么回事啊？

**Comment by CymChad** [comment]
你的datas为空。提示上很清楚。你是不是data为null就穿进去了？

**Comment by wuzhaohui026** [comment]
不是，是退出的时候，我把datas清空了。

**Comment by wuzhaohui026** [comment]
![35b308a58e84c799563f438d355d3b2a](https://cloud.githubusercontent.com/assets/7565399/19542625/6415775c-96a2-11e6-9fb5-c93d2b224f8c.jpg)

上一种已经解决了，但是现在有时候还会报这种错误

**Comment by wuzhaohui026** [comment]
![35b308a58e84c799563f438d355d3b2a_](https://cloud.githubusercontent.com/assets/7565399/19542653/a01f5e34-96a2-11e6-97d8-c3b8461b5505.jpg)

上一种已经解决了，但是现在有时候还会报这种错误

**Comment by CymChad** [comment]
具体操作流程？

**Comment by CymChad** [comment]
http://stackoverflow.com/questions/30693821/fragment-with-recyclerview-java-lang-illegalargumentexception-scrapped-or-att  在网上看到的。

**Comment by CymChad** [comment]
http://www.jianshu.com/p/c8610c9391cb 还有这个。

**Comment by CymChad** [comment]
因为没有遇到过这个bug，所以无法复现，以上两个链接都是根据你提供的crash来查找到的，希望对你有所帮助。

**Comment by wuzhaohui026** [comment]
谢谢啊，这个问题也是偶尔会发生

**Comment by CymChad** [comment]
恩，感谢你的使用。

**Comment by wuzhaohui026** [comment]
用着是挺方便的，不过由于自己发能力有限，会经常遇到问题
