### ISSUE TITLE
Cardview点击Ripple问题

### ISSUE THREAD

**Issue by nEdAy** [CymChad/BaseRecyclerViewAdapterHelper#413]
留给 @上海-AllenCoder 的备忘

**Comment by liuhui19991** [comment]
点击margin区域崩溃

**Comment by AllenCoder** [comment]
已收到。正在处理

**Comment by CymChad** [comment]
@liuhui19991 崩溃已解决   compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.4'

**Comment by AllenCoder** [comment]
点击margin区域崩溃 ，这个bug已经修复，关于cardview作为recyclerview的item背景的中心点发散，好像不止我一个人遇到这种问题，目前都没有找到解决方案，我也正在努力需找方案，如果找到完美方案，第一时间告知你们

**Comment by xiongyufeng12306** [comment]
弱弱的问一下，有没有上拉加载分页的demo?好像大神你这只有加载总数，然后根据总数进行加载的。因为我现在想做的是分页，用你这个BaseRecyclerViewAdapterHelper 的上拉加载。能搞成加载下一页就好了。谢谢

  

 

 ------------------ 原始邮件 ------------------
  发件人: "陈宇明";<notifications@github.com>;
 发送时间: 2016年10月20日(星期四) 下午2:30
 收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
 
 主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] Cardview点击Ripple问题 (#413)

 

 
@liuhui19991 崩溃已解决 compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.4'

**Comment by nEdAy** [comment]
Error:(145, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.2.4
我找不到 2.2.4 2016年10月20日 16:44:05 @CymChad

**Comment by CymChad** [comment]
打包失败了，我看看

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.9'
  用这个

**Comment by YenRen** [comment]
Apk 有问题

**Comment by CymChad** [comment]
@YenRen 请具体描述问题。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.6'
