### ISSUE TITLE
快速反复的向上滑动，加载更多的loading不消失

### ISSUE THREAD

**Issue by zxy198717** [CymChad/BaseRecyclerViewAdapterHelper#414]
1. 打开demo
2. 选择 PullToRefresh Use
3. 第一次加载后。点 “加载失败，请点我重试”
4. 反复快速向上滑动，偶尔会出现 “正在加载中” 不会消失的情况。

版本 2.2.3

**Comment by CymChad** [comment]
已收到，我看看。

**Comment by 1109993488** [comment]
@zxy198717 出现这种情况后往上滑动几下再滑动到底部可以加载吗？还是一直都是加载中？

**Comment by zxy198717** [comment]
@1109993488 你就一直滑，手不停的滑动。出现这种情况后，往上滑，在回到底部，还是能正常加载的。

**Comment by proud2008** [comment]
也发现了，

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.3.2'  已修复
