### ISSUE TITLE
点击item中某个view的时候，整个item都有点击效果

### ISSUE THREAD

**Issue by zxy198717** [CymChad/BaseRecyclerViewAdapterHelper#415]
这种情况是正常吗？
1. 打开demo程序，选择RecyclerClickItemActivity
2. 点击头像，功能是正常的，但是背景的 波纹 效果也出来了

能做到点击item中某个view的时候，只显示这个view的 点击 效果吗？

**Comment by AllenCoder** [comment]
这个是为了展示5.0以上的点击波纹的修复效果，一般情形下点击会触发整个item的波纹效果。如果不想有这种波纹效果，可以直接关闭

**Comment by zxy198717** [comment]
@AllenCoder 有办法做到: 比如 item上有个按钮，点击 按钮 显示 按钮的波纹效果，点击 按钮 以外的区域 显示 item的波纹效果吗?

**Comment by AllenCoder** [comment]
可以做到，目前在考虑这种需求，一般情况下，点击的波纹效果都是基于整个item发散的，如果基于摸个控件内发散也是可以做到的，需求需要论证，是跟原来一样单独设置还是根据google建议 ，基于整个item效果的发散

**Comment by nEdAy** [comment]
Error:(145, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.2.4
我找不到 2.2.4            2016年10月20日 16:44:05

**Comment by zxy198717** [comment]
@AllenCoder 谷歌也不会建议点击 某个 控件，整个item都有效果吧。这样会迷惑用户吧，点击 按钮，按钮高亮是正常的，整个item都有效果不多见，目前有app是这样做的吗?

**Comment by TpOut** [comment]
@zxy198717 = = 我和你一样，其实你不要用它封装好的  viewHolder.setOnclickListener，而是获取view = viewHolder.findView()，然后再用原生的view.setOnclickListener，就可以分开来了，不过要根据需要单独设置点击。

**Comment by zxy198717** [comment]
@TpOut 是的，单独设置view的click事件是可以的，这是常用的方式。但有封装好的，就是想用一下。
@AllenCoder 你怎么看？

**Comment by zxy198717** [comment]
@CymChad 有什么建议吗？

**Comment by AllenCoder** [comment]
可以基于viewholder自己处理， 也可以基于框架来实现。两种方案都可行

**Comment by zxy198717** [comment]
这个属于需求问题，bug关闭。
改了下SimpleClickListener.java的实现，达到了自己要的效果，供参考。
https://gist.github.com/zxy198717/2d86aacaf689585e25b521dbace9e617

**Comment by CymChad** [comment]
@zxy198717 恩，你的链接打不开。

**Comment by CymChad** [comment]
打开了，需要VPN，gist 被墙了
