### ISSUE TITLE
SimpleClickListener 不确定性崩溃

### ISSUE THREAD

**Issue by lijunguan** [CymChad/BaseRecyclerViewAdapterHelper#416]
点击事件 不确定性导致崩溃，概率不低，目前就有5款手机出现了，版本都集中在5.0以上， 使用 版本2.1.3，不知道新版本有问题没，   目前定位错误代码 在    

```ItemTouchHelperGestureListener``` 的 ```onDown(MotionEvent e)``` 方法中， mPressedView  为null, 然后调用 
mPressedView.getBackgrond //  java.lang.NullPointerException
```java 
SimpleClickListener.this.mPressedView = this.recyclerView.findChildViewUnder(e.getX(), e.getY());
            if(VERSION.SDK_INT >= 21 && SimpleClickListener.this.mPressedView.getBackground() != null) {
                SimpleClickListener.this.mPressedView.getBackground().setHotspot(e.getRawX(), e.getY() - SimpleClickListener.this.mPressedView.getY());
            }
```

###  下面是Bugly 上报的 部分错误日志
#1 main
>java.lang.NullPointerException
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.view.View.getBackground()' on a null object reference
解析原始
}
1 com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.boolean onDown(android.view.MotionEvent)(Unknown Source)
2 android.view.GestureDetector.onTouchEvent(GestureDetector.java:550)
3 android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(Unknown Source)
4 android.support.v4.view.GestureDetectorCompat.onTouchEvent(Unknown Source)
5 com.chad.library.adapter.base.listener.SimpleClickListener.boolean onInterceptTouchEvent(android.support.v7.widget.RecyclerView,android.view.MotionEvent)(Unknown Source)
6 ##_parent_##9##_parent_##
7 ##_child_## void onRequestDisallowInterceptTouchEvent(boolean)##_child_##
8 ##_child_## void onItemClick(com.chad.library.adapter.base.BaseQuickAdapter,android.view.View,int)##_child_##
9 ##_child_## boolean inRangeOfView(android.view.View,android.view.MotionEvent)##_child_##
10 ##_child_## boolean isHeaderOrFooterPosition(int)##_child_##

**Comment by zxy198717** [comment]
+1

**Comment by AllenCoder** [comment]
ok这个bug，马上修复

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.4'  已修复

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.9'
  用这个
