### ISSUE TITLE
LoadMore回调一直被自动触发，不知道是不是recyclerView在屏幕外加载的关系

### ISSUE THREAD

**Issue by yangchenZheng** [CymChad/BaseRecyclerViewAdapterHelper#418]
我的recyclerView嵌套在一个scrollView中，初始化的时候在view底部的recyclerView是在屏幕外加载的，不知道是不是这个原因一直触发loadMore。

**Comment by CymChad** [comment]
scrollView 和 adapter的上拉有冲突

**Comment by CymChad** [comment]
#204 如果你一定要嵌套的话，我建议你使用第三方的上拉下拉。

**Comment by yangchenZheng** [comment]
@CymChad 谢谢！

**Comment by RahulSDeshpande** [comment]
@CymChad Hey brother..
A very big fan of your library !!
Amazing work !!

Will you please explain the exact solution, like what do you mean by "use a third party pull down" ?
I am too facing the same solution, if I remove the NestedScrollView, RecyclerView scrolling is very laggy & non-smooth !!

Thanks in advance 👍
