### ISSUE TITLE
还是那个上拉加载更多的问题

### ISSUE THREAD

**Issue by JianJianZhang** [CymChad/BaseRecyclerViewAdapterHelper#420]
我怎么知道那个pageSize是有多少啊？不设置那个 adapter.openLoadMore(PAGE_SIZE);就一进入activity,就refreshDate和loadMoreDate方法都执行了

**Comment by CymChad** [comment]
pageSize是一页显示的数量，不是总页数的意思。

**Comment by JianJianZhang** [comment]
感谢您的回复，这个问题困扰我好久了，就是一进入，就同时加载。原来是没有设置这个pagesize，我以为是哪个加载的页面数量




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年10月20日(星期四) 下午2:34
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "健健"<694449594@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 还是那个上拉加载更多的问题 (#420)




pageSize是一页显示的数量，不是总页数的意思。

**Comment by CymChad** [comment]
恩，没事，感谢你的使用。

**Comment by xiongyufeng12306** [comment]
上拉加载，只有先执行下拉操作它才能加载出东西，刚进去的时候（RecyclerView）一片空白。解决了这个问题吗？github有更新吗？现在正在用这个上拉加载。谢谢



------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年10月20日(星期四) 下午2:40
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 

主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 还是那个上拉加载更多的问题 (#420)




Closed #420.

**Comment by JianJianZhang** [comment]
我还想问一个问题，就是这个recyclerView使用的时候，有重影，滚动的时候。怎么解决了？




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年10月20日(星期四) 下午2:40
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "健健"<694449594@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 还是那个上拉加载更多的问题 (#420)




Closed #420.

**Comment by JianJianZhang** [comment]
这个问题解决了，太感谢您的帮助了。






------------------ 原始邮件 ------------------
发件人: "xiongyufeng12306";<notifications@github.com>;
发送时间: 2016年10月20日(星期四) 下午2:44
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "健健"<694449594@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 还是那个上拉加载更多的问题 (#420)



上拉加载，只有先执行下拉操作它才能加载出东西，刚进去的时候（RecyclerView）一片空白。解决了这个问题吗？github有更新吗？现在正在用这个上拉加载。谢谢 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "陈宇明";<notifications@github.com>; 
 发送时间: 2016年10月20日(星期四) 下午2:40 
 收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;  
 
 主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 还是那个上拉加载更多的问题 (#420) 
 
 
 
 
 Closed #420.

**Comment by CymChad** [comment]
@xiongyufeng12306 不是呀，你第一次加载数据肯定是你自己请求的数据，第二次然后是通过回调触发请求的。

**Comment by CymChad** [comment]
重影？没有遇到过，你是不是开了动画？

**Comment by xiongyufeng12306** [comment]
哦，这样，谢谢。


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年10月20日(星期四) 下午2:46
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "大峰车"<1217255447@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 还是那个上拉加载更多的问题 (#420)




@xiongyufeng12306 不是呀，你第一次加载数据肯定是你自己请求的数据，第二次然后是通过回调触发请求的。

**Comment by JianJianZhang** [comment]
动画是默认开的？我没有开启




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年10月20日(星期四) 下午2:47
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "健健"<694449594@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 还是那个上拉加载更多的问题 (#420)




重影？没有遇到过，你是不是开了动画？

**Comment by CymChad** [comment]
没有。adapter是不会给item加任何显示效果的。
