### ISSUE TITLE
问下  是不是在SimpleOnItemChildClick 调用 notifyItem只能这样  自己加上Header的个数？

### ISSUE THREAD

**Issue by yuruxuan** [CymChad/BaseRecyclerViewAdapterHelper#421]
比如：
mAdapter.notifyItemChanged(position + mAdapter.getHeaderLayoutCount());

我在当前版本没有发现作者自己封装的notifyItemChanged，是不是我得自己加上这个值刷新对应条目？

**Comment by CymChad** [comment]
恩 是的。
