### ISSUE TITLE
横向布局的时候添加headview

### ISSUE THREAD

**Issue by beiliubei** [CymChad/BaseRecyclerViewAdapterHelper#425]
![image](https://cloud.githubusercontent.com/assets/1127875/19568175/18f9bf72-9723-11e6-8968-fe98d0e4035e.png)

当layoutmanage设置的是 new LinearLayoutManager(this, HORIZONTAL, false)
添加headview，希望也是横向的headview 布局

**Comment by CymChad** [comment]
addHeadView   不可以吗？

**Comment by beiliubei** [comment]
@CymChad addHeadView的话，mHeaderLayout new的是一个 VERTICAL的 但是需要一个HORIZONTAL，且layoutparm的 宽不是Match_PARENT的。所以，需要添加一个参数类似LinearLayoutManager一样把 orientation传过去。

**Comment by CymChad** [comment]
ok  明白了，我们这边处理一下。

**Comment by CymChad** [comment]
感谢你的pr。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.3.0'  已合成你的代码并且打包好了。
