### ISSUE TITLE
SimpleOnItemClick如果点击列表空的地方会报空指针

### ISSUE THREAD

**Issue by yuchen5202064** [CymChad/BaseRecyclerViewAdapterHelper#426]
<img width="1000" alt="qq20161021-0 2x" src="https://cloud.githubusercontent.com/assets/8627335/19570764/f210b54a-972d-11e6-88c8-6f1268766db3.png">
<img width="1304" alt="qq20161021-1 2x" src="https://cloud.githubusercontent.com/assets/8627335/19570768/f5afa206-972d-11e6-9f0d-2cac086435d8.png">
测试手机系统为6.0，谢谢你

**Comment by CymChad** [comment]
你把你的版本 更新到  2.2.9  应该就没问题了。

**Comment by yuchen5202064** [comment]
是的，更新以后没有问题了，谢谢你
