### ISSUE TITLE
你好 需要频繁请求服务器数据 设置了handle消息 5秒请求一次 请求完数据调用哪个方法可以完成数据刷新

### ISSUE THREAD

**Issue by zilingyao** [CymChad/BaseRecyclerViewAdapterHelper#427]
mQuickAdapter.notifyDataSetChanged(); 此方法并没有出现预期效果 没反应

**Comment by CymChad** [comment]
没有出现预期效果没反应是指 数据没有刷新？

**Comment by zilingyao** [comment]
是哦 但是重新下拉刷新就有数据更新 但我的需求是在这个列表页数据会自动更新 请问哪个方法可以实现

**Comment by CymChad** [comment]
你试试 setNewData

**Comment by zilingyao** [comment]
mQuickAdapter.setNewData(getdata());出现崩溃 
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 7(offset:7).state:8

**Comment by CymChad** [comment]
看下你的使用代码，还有你的版本号。我这边复现一下。

**Comment by zilingyao** [comment]
版本号2.1.7
主要是加了以下代码 其余跟demo中的PullToRefreshUseActivity.java一样    

private List<QuickPathBean> getdata(){

        mPathBeanList = DataServer.getFragItemData(PAGE_SIZE);
        return mPathBeanList;
    }

    private Handler mHandler = new Handler() {
        public void handleMessage(Message msg)
        {
            switch (msg.what)
            {
                case 1:
                    //添加刷新数据
                    mQuickAdapter.setNewData(getdata());
                    //getdata();
                    mQuickAdapter.notifyDataSetChanged();
                    GLogger.gLog().e("呵呵");
                    break;
            }
        };
    };

    private class MyTask extends TimerTask {
        @Override
        public void run() {
            Message message = new Message();
            message.what = 1;
            mHandler.sendMessage(message);
        }

    }

**Comment by CymChad** [comment]
你的getdata是异步去获取数据？

**Comment by CymChad** [comment]
_如果是的话那么应该把刷新和数据填充放在获取数据的回调里面吧？

**Comment by zilingyao** [comment]
不是 假数据 如下

    private static  int qq = 0;
    private  static Handler handler = new Handler();
    private  static Runnable runnable = new Runnable() {

        @Override
        public void run() {
            // handler自带方法实现定时器
            try {
                handler.postDelayed(this, 1000);
                qq++;
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
                System.out.println("exception...");
            }
        }
    };
    public static List<QuickPathBean> getFragItemData(int page) {
        handler.postDelayed(runnable, 1000); //每隔1s执行

        List<QuickPathBean> list = new ArrayList<>();
        for (int i = 1; i <= page/2; i++) {
            list.add(new QuickPathBean("金华"+qq,"杭州","2010-10-09","79.00","完成"));
            list.add(new QuickPathBean("金华","杭州","2010-10-09","- - -","进行中"));
        }
        return list;
    }

**Comment by AllenCoder** [comment]
你的数据前后引用地址肯定变了。正常情况下，只要data的引用地址不变，更新数据后，刷新适配器，列表就会改变的

**Comment by zilingyao** [comment]
我在网上查看是有这种说法 但是这个引用地址怎么看呢  全部代码
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        if (mView == null) {
            mView = inflater.inflate(R.layout.fragment_path, container, false);
        }
        return mView;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        EventBus.getDefault().register(getActivity());

        mRecyclerView = (RecyclerView) mView.findViewById(R.id.rv_list1);
        mSwipeRefreshLayout = (SwipeRefreshLayout) mView.findViewById(R.id.swipeLayout);
        mSwipeRefreshLayout.setOnRefreshListener(this);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
        int spacingInPixels = getResources().getDimensionPixelSize(R.dimen.space);
        mRecyclerView.addItemDecoration(new SpaceItemDecoration(spacingInPixels));
        initAdapter();
        mRecyclerView.setAdapter(mQuickAdapter);

        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new MyTask(), 1, 3000);
    }

    //条目行间距
    public class SpaceItemDecoration extends RecyclerView.ItemDecoration {

        private int space;

        public SpaceItemDecoration(int space) {
            this.space = space;
        }

        @Override
        public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {

            if (parent.getChildPosition(view) != 0)
                outRect.top = space;
        }
    }
  
    //初始化适配器
    private void initAdapter() {
        mQuickAdapter = new QuickPathAdapter(getdata());
        mQuickAdapter.openLoadMore(PAGE_SIZE);
        mRecyclerView.setAdapter(mQuickAdapter);

        mRecyclerView.setHasFixedSize(true);
        mCurrentCounter = mQuickAdapter.getData().size();
        mQuickAdapter.setOnLoadMoreListener(this);


        mRecyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void SimpleOnItemClick(BaseQuickAdapter adapter, View view, int position) {

            }

            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                super.onItemChildClick(adapter, view, position);
                switch (view.getId()) {
                    case R.id.ii_path_gotodetail:
                        QuickPathBean quickPathBean = (QuickPathBean) adapter.getItem(position);
                        Intent intent = new Intent(getActivity(), PathDetailActivity.class);
                        intent.putExtra("quickPathBean", quickPathBean);
                        startActivity(intent);
                        break;

                    default:
                        break;
                }

            }
        });
    }


    @Override
    public void onRefresh() {
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mQuickAdapter.setNewData(getdata());
                mQuickAdapter.openLoadMore(PAGE_SIZE);
                mQuickAdapter.removeAllFooterView();
                mCurrentCounter = PAGE_SIZE;
                mSwipeRefreshLayout.setRefreshing(false);
            }
        }, delayMillis);

    }

    @Override
    public void onLoadMoreRequested() {
        mRecyclerView.post(new Runnable() {
            @Override
            public void run() {

                if (mCurrentCounter >= TOTAL_COUNTER) { //加载完成
                    mQuickAdapter.loadComplete();
                    if (notLoadingView == null) {
                        notLoadingView = getActivity().getLayoutInflater().inflate(R.layout.layout_empty, (ViewGroup) mRecyclerView.getParent(), false);
                    }
                    mQuickAdapter.removeAllFooterView();
                    mQuickAdapter.addFooterView(notLoadingView);
                } else {
                    if (NetworkUtils.isAvailable(getActivity())) {
                        new Handler().postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                //加载一页
                                mQuickAdapter.addData(getdata());
                                mCurrentCounter = mQuickAdapter.getData().size();
                            }
                        }, delayMillis);
                    } else {
                        Toast.makeText(getActivity(), "网络错误", Toast.LENGTH_LONG).show();
                        mQuickAdapter.showLoadMoreFailedView();

                    }
                }
            }

        });

    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(getActivity());

    }


    private List<QuickPathBean> getdata(){

        mPathBeanList = DataServer.getFragItemData(PAGE_SIZE);
        return mPathBeanList;
    }

    private Handler mHandler = new Handler() {
        public void handleMessage(Message msg)
        {
            switch (msg.what)
            {
                case 1:
                    //添加数据
                    mQuickAdapter.setNewData(getdata());
                    //getdata();
                    mQuickAdapter.notifyDataSetChanged();
                    GLogger.gLog().e("呵呵");
                    break;
            }
        };
    };

    private class MyTask extends TimerTask {
        @Override
        public void run() {
            Message message = new Message();
            message.what = 1;
            mHandler.sendMessage(message);
        }

    }

**Comment by CymChad** [comment]
你可以通过mQuickAdapter.getData拿到adapter里面的数据源进行操作。这样就可以避免不是一个引用的问题。

**Comment by CymChad** [comment]
问题解决没？

**Comment by zilingyao** [comment]
mOldPathBeanList = mQuickAdapter.getData();
                    mOldPathBeanList.removeAll(mOldPathBeanList);
                    mOldPathBeanList.addAll(DataServer.getFragItemData(PAGE_SIZE));
按上边的方法 现在数据可以自动更新了 但是只有一屏的数据 下拉刷新不管用了 就是说可以一直下拉 但是一直只有一屏的（每页显示的条目数）数据

**Comment by CymChad** [comment]
上拉加载吧？下拉刷新不是adapter提供的，如果是上拉加载的话，你要开启监听和设置pageSize

**Comment by zilingyao** [comment]
额额 不好意思 口误 现在上拉加载一直加载但数据只有一屏 代码都写了 就是上边的完整代码  这是现在运行效果
[http://oegt3xt9o.bkt.clouddn.com/GIF.gif](url)

**Comment by zilingyao** [comment]
这个问题好像是上拉加载那有问题吧 起冲突了 不知道方便留个联系方式吗 具体探讨下

**Comment by CymChad** [comment]
54050520 我的Q，陈宇明

**Comment by CymChad** [comment]
问题已解决，代码使用问题。
