### ISSUE TITLE
2.2.3 SimpleClickListener

### ISSUE THREAD

**Issue by proud2008** [CymChad/BaseRecyclerViewAdapterHelper#432]
private class ItemTouchHelperGestureListener extends GestureDetector.SimpleOnGestureListener {

    private RecyclerView recyclerView;

    @Override
    public boolean onDown(MotionEvent e) {
        mIsPrepressed = true;
        mPressedView = recyclerView.findChildViewUnder(e.getX(), e.getY());
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            if (mPressedView.getBackground() != null) {
                mPressedView.getBackground().setHotspot(e.getRawX(), e.getY() - mPressedView.getY());
            }
        }
        super.onDown(e);
        return false;
    }

在6.0上设置ItemDecoration  
if (mPressedView.getBackground() != null) {
会出现空指针

**Comment by AllenCoder** [comment]
最新版已经修复了这个bug，请更新至最新版本

**Comment by CymChad** [comment]
2.2.9版本。
