### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.view.View.getBackground()' on a null object reference

### ISSUE THREAD

**Issue by CodingMartin** [CymChad/BaseRecyclerViewAdapterHelper#434]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.view.View.getBackground()' on a null object reference
1. 添加了ItemDecoration 触摸ItemDecoration报错
2.视图加载未完成时 触摸屏幕报错

**Comment by CymChad** [comment]
升级至2.2.9即可。
