### ISSUE TITLE
使用ExpandableItem如何从level2Item获取对应父级level1Item中的View

### ISSUE THREAD

**Issue by personalxia** [CymChad/BaseRecyclerViewAdapterHelper#435]
如题

**Comment by elfman** [comment]
如果Item能用`getLevel()`获取正确的分级，就能用BaseQuickAdapter里的`public int getParentPosition(@NonNull T item)`来获取父级的position

**Comment by personalxia** [comment]
可以正常获取父级的position，问题就在于我能通过什么方式获取到父级的控件呢？

**Comment by elfman** [comment]
这个是获取不了的，因为父级控件并不是不变的，当父级的控件超出屏幕范围时，父级的View有可能已经被其它同类型的View复用了

**Comment by personalxia** [comment]
嗯，确实是这样，我在想想别的办法吧，谢了啊@elfman
