### ISSUE TITLE
我pagesize 设置 10  但是我们的后台有可能返回 7个或者8个 

### ISSUE THREAD

**Issue by yanglichuan** [CymChad/BaseRecyclerViewAdapterHelper#438]
我pagesize 设置 10  但是我们的后台有可能返回 7个或者8个   但是还有下一页

所以就造成了如果设置了openLoadMore（size）

就无法加载下一页了

**Comment by CymChad** [comment]
你可以写小一些，pageSize ，但是最起码要满足一个屏幕 因为不满足一个屏幕理论上是不存在上拉的

**Comment by CymChad** [comment]
pagesize 只是控制第一页的数据，后面是否有下一页其实是通过你在回调中调用方法来控制的。
