### ISSUE TITLE
onLoadMoreRequested只执行一次

### ISSUE THREAD

**Issue by loody** [CymChad/BaseRecyclerViewAdapterHelper#44]
当我加载了一页或者几页数据后，这时候把网断了，滑到底部执行onLoadMoreRequested()，没有加载到数据，之后我再把网连上，我再滑到底部就不会执行onLoadMoreRequested()方法了

**Comment by CymChad** [comment]
是否继续加载取决于你的设置，没有联网了，没加载到数据理论上你一按是设置是否继续加载为false了，如果你想继续加载，你在设置加载为为true就好了
