### ISSUE TITLE
RecyclerView需要上下滑动一下才能刷新view

### ISSUE THREAD

**Issue by li-yu** [CymChad/BaseRecyclerViewAdapterHelper#442]
BaseRecyclerViewAdapterHelper - v2.4.2
RecyclerView-v7-24.2.1

大神你好，今天遇到一个很少发生的诡异问题，我不确定是adapter还是RecyclerView的问题，当然规避这个问题有许多措施（比如不让用户跳转），但是不清楚为什么会这样。

描述：在“某个activity中组装数据直到adapter.setNewData()的过程中“或者“填充完数据RecyclerView刚刚刷新”，突然跳转到另外一个activity，再回来，发现RecyclerView就不能正常刷新了，再次调用adapter.setNewData()也没用，此时需要上下滑动一下RecyclerView，才能正常刷新新内容，item的展开收起也是，需要滑动下RecyclerView才刷新界面。

谢谢。

**Comment by CymChad** [comment]
你换台手机看看，之前有人反映过这个情况，结果是因为手机问题。

**Comment by li-yu** [comment]
测试了两台三星平板（Android 5.0、Android 4.4）和nexus 5（Android 6.0.1）还是有这个现象

**Comment by CymChad** [comment]
行，我这边测试一下。你也可以用RecyclerView原生的Adapter看一下。

**Comment by li-yu** [comment]
好的，谢谢。我是用的BaseMultiItemQuickAdapter。
上面写的可能有些啰嗦了，我在稍微总结下复制手法吧：填充完数据，RecyclerView刷新完，**立马**跳转到另外一个activity，再返回，会出现RecyclerView需要上下滑动才能刷新的现象。

**Comment by feer921** [comment]
@li-yu 你那个不属于RecyclerView本身的问题，两个Activity界面切换太快确实在一些系统上机率出现上一个Activity停止渲染的问题，滑动视图则重新触发绘制

**Comment by li-yu** [comment]
@feer921   有可能。滑动视图则重新触发绘制确实是这样的，但是后面，RecyclerView的数据源每次更改都需要手动滑动一下才能重新绘制。感觉RecyclerView像坏了一下。

**Comment by feer921** [comment]
@li-yu  检查一下你的跳出的那个Activity有没有过重的代码逻辑

**Comment by li-yu** [comment]
使用原生adapter测试也发现了这个问题，应该不是BaseRecyclerViewAdapterHelper的bug，具体我再继续研究中。抱歉打扰了。

**Comment by hejiaun** [comment]
请问楼主问题弄好了吗，我也遇到同样问题呢

**Comment by li-yu** [comment]
@hejiaun 问题解决了，当时是自己代码的 bug，导致主线程异常，与 BaseRecyclerViewAdapterHelper 无关哦。我当时是在用 RxJava 时，把 .observeOn(AndroidSchedulers.mainThread()) 错误的写成了 .subscribeOn(AndroidSchedulers.mainThread())，粗心导致了主线程异常。

**Comment by hejiaun** [comment]
@li-yu  我也是用rxjava，一样的问题   .observeOn(Schedulers.newThread())    
                                                               改成      
                                                              .subscribeOn(Schedulers.newThread())
就解决了，哈哈哈，谢谢楼主，原来还没记清楚observeOn   和 subscribeOn 的意思，，一个是观察一个是被观察，被观察在子线程，观察在主线程

**Comment by Fomovet** [comment]
@li-yu @hejiaun @CymChad 我也遇到同样问题了，界面：ViewPager+4个Fragment当我切换到第1个或者第2个Fragment时做需要某些操作(不需要走网络)然后去动态刷新第0个Fragment里面的数据，回到第0个Fragment需要上下滑动一下才能刷新View

**Comment by cxmmxc** [comment]
哎，看了你们的回答，我的是只在Android6.0.1版本上需要拉一下才能显示，在其余的版本上是好的，这么是什么问题。。

**Comment by cxmmxc** [comment]
找到问题了。。。ri了够啊，就因为用了constraintlayout的alpha版本导致的，换回release版就好了。大家不要轻易用alpha，蛋都碎了

**Comment by Bruce8hou** [comment]
我的也是这个问题 千万不要用constraintlayout的测试版 坑太多

**Comment by guoleifei** [comment]
卧槽 蛋疼调了一天终于找到问题了 还是不是所有的手机
oppo vivo的特定机型才有的问题

**Comment by xiongtianqi** [comment]
> 卧槽 蛋疼调了一天终于找到问题了 还是不是所有的手机
> oppo vivo的特定机型才有的问题

请问是怎么解决的？是ConstraintLayout的原因吗？

**Comment by 50kg** [comment]
我也遇到了怎么解决啊。。线程也对了，ConstraintLayout也没用 求解。。

**Comment by guoleifei** [comment]
ConstraintLayout 换版本-- 试试要 我换了就好了

**Comment by Carlos2927** [comment]
OnPreDrawListener使用不当会到导致这种情况
![图片](https://user-images.githubusercontent.com/12493233/66969338-b6ec4980-f0bb-11e9-88db-ef505300b1cb.png)

**Comment by Dpuntu** [comment]
我也遇到同样的问题，求解

**Comment by HiPipilu** [comment]
我在红米 note 8 pro 遇到了这个问题，在模拟器上没有发现

**Comment by xing16** [comment]
我在主线程, 没有用 ConstraintLayout , 只是 viewpager+fragment 快速切换时会出现不刷新问题

**Comment by zhiyongzuo** [comment]
同一个fragment（包含recyclerview），在framelayout中正常，在viewpager中需要滑动一下（或者等1-60s不定）才刷新。解决方法delay100ms，mRecyclerView.smoothScrollBy(1,1)
