### ISSUE TITLE
上拉加载更多回调接口只走一次

### ISSUE THREAD

**Issue by xueweiyang** [CymChad/BaseRecyclerViewAdapterHelper#443]
第一次上拉回调获取数据后，再次拉到底部，不走回调接口，底部一直显示加载中，部分代码如下：
public class TestFragment extends Fragment {

    NewsListAdapter adapter;
    List<NewEntity> datas = new ArrayList<>();

    @BindView(R.id.recycler)
    RecyclerView recyclerView;

    private void init() {
        adapter = new NewsListAdapter(AppContext.getInstance(), datas);
        recyclerView.setAdapter(adapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(AppContext.getInstance()));
        adapter.openLoadMore(20);
        adapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                getData();
            }
        });
        getData();
    }

    private void getData() {

        ApiClient
                .api()
                .newsList("")
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new MyObserver<NewsListEntity2>(){

                    @Override
                    protected void onSuceess(NewsListEntity2 data) {
                        super.onSuceess(data);
                        datas.addAll(data.getResult().getItems());
                        adapter.setNewData(datas);
                        adapter.notifyDataSetChanged();
                    }

                });
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.test_fra, null);
        ButterKnife.bind(this, view);
        init();
        return view;
    }
}

希望大神帮忙解答！！！

**Comment by CymChad** [comment]
你调用的方法错了，你可以看看demo是怎么用的。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Pull-up-to-loadMore 这是文档。

**Comment by xueweiyang** [comment]
把setNewData换成addData就好了，那前者的作用是什么，为了初始化吗？

**Comment by xueweiyang** [comment]
哦哦，终于搞懂了，是自己看的太不仔细了，谢谢啦

**Comment by CymChad** [comment]
恩，感谢你的使用。
