### ISSUE TITLE
上拉加载更多的疑问

### ISSUE THREAD

**Issue by axkza** [CymChad/BaseRecyclerViewAdapterHelper#444]
上拉加载失败现在是点击继续加载，继续上拉无反应

要怎么才能实现  已出现“加载失败”，点击“加载失败”或者继续上拉 会自动加载？

**Comment by CymChad** [comment]
demo 有反应呀。

**Comment by CymChad** [comment]
![gif_20161026_142945](https://cloud.githubusercontent.com/assets/7698209/19715620/02154a50-9b89-11e6-895e-7148988c1c8c.gif)

**Comment by axkza** [comment]
不是，我的意思是
出现 加载失败 后，可以通过【点击】或者【往上滑动到达底部】，都可以再次加载数据

**Comment by CymChad** [comment]
哦，你是说不通过点击按钮，让他自动可以上拉对吗？

**Comment by axkza** [comment]
恩，是的

**Comment by CymChad** [comment]
开个延迟去跑openLoadMore(pageSize);这个方法。

**Comment by CymChad** [comment]
相当于就是网络加载失败了加载被关闭了，你延迟1秒在开启，这样用户就可以再上拉了。

**Comment by CymChad** [comment]
但是我个人觉得让他点击更加好一些，这也很正常。

**Comment by kexingmo** [comment]
adapter.showLoadMoreFailedView();
                            recyclerview.postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    adapter.removeAllFooterView();
                                    adapter.openLoadMore(2);
                                }
                            },1000);
你好，请问是这样吗？当调用adapter.removeAllFooterView();之后，这样开启加载更多？但是有个问题就是1秒后它会自动加载，而不是手动上拉加载

**Comment by axkza** [comment]
@kexingmo 这个我也没实现，所以还是用回listview了
我觉得也算是个刚需吧，毕竟手指上滑就是为了自动加载，出现失败，理论上也需要有这个上滑的动作让它自动加载，而不仅仅是点击，尤其是在大屏幕下，这个失败上滑加载的需求应该会更大。

等有时间再自己去实现以下，如果你有好的想法，麻烦告知。

**Comment by CymChad** [comment]
建议你们使用第三方的上拉库，可以使用https://github.com/anzaizai/EasyRefreshLayout 配合BRVAH项目，功能分离开更好控制
