### ISSUE TITLE
SectionAdapter的convert中如何获得所在section的header

### ISSUE THREAD

**Issue by liuxuebing2010** [CymChad/BaseRecyclerViewAdapterHelper#445]
@Override
            protected void convert(BaseViewHolder baseViewHolder, MyAgreementList item) {
                final Agreement agreement=item.t;
                switch (item.header) {
item.header是null

**Comment by CymChad** [comment]
SectionAdapter已经区分过头部和内容部分了。
头部会进convertHead方法。
内容会进convert方法。

**Comment by CymChad** [comment]
已联系到提问者问题已解决。
