### ISSUE TITLE
关于加载更多

### ISSUE THREAD

**Issue by shuiyouwen** [CymChad/BaseRecyclerViewAdapterHelper#448]
大神，有两个问题想咨询下。
1、loadMore监听只会执行一次吗。
2、我在mAdapter.loadComplete();方法之后再次调用penLoadMore(mPageCount)方法解决了第一个问题，但是加载到最底部的时候loadMore的那个view怎么让其消失呢

**Comment by axkza** [comment]
一般loadComplete()方法是在拉到最后一页才调用吧，平时访问网络获取数据后调用adapter.addData();
如果要隐藏loadMore,可以调用adapter.hideLoadingMore()试试

**Comment by shuiyouwen** [comment]
3q，完全是我使用姿势不对。。
