### ISSUE TITLE
library的清单中的app_name是否可以删除呢

### ISSUE THREAD

**Issue by MarnonDev** [CymChad/BaseRecyclerViewAdapterHelper#449]
![image](https://cloud.githubusercontent.com/assets/14787921/19751338/0216c964-9c2b-11e6-9637-a9a6c293f874.png)

**Comment by CymChad** [comment]
遇到什么问题了？

**Comment by MarnonDev** [comment]
我app清单中的application的label是用占位符动态在gradle中加载的，这个时候就会报错，提示 Manifest merger failed

**Comment by CymChad** [comment]
可以。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.4'
