### ISSUE TITLE
mAdapter.notifyDataSetChanged() not working

### ISSUE THREAD

**Issue by RamiTrabelsi** [CymChad/BaseRecyclerViewAdapterHelper#45]
mAdapter.notifyDataSetChanged() is not working

is someone else facing this problem ?

**Comment by CymChad** [comment]
mAdapter.getData() Modify the data source, then mAdapter.notifyDataSetChanged() ,You try?

**Comment by CymChad** [comment]
May be you modify the data adapter to the problems of data sources.
```
 public BaseQuickAdapter(Context context, int layoutResId, List<T> data) {
        this.mData = data == null ? new ArrayList<T>() : new ArrayList<T>(data);
        // ...
    }
```
If you are in the structure of the incoming data is null, then your data source, it is not the source of data for adapter
so mAdapter.notifyDataSetChanged() is not working.
Hope to be able to solve your problem, thank you for using my lib

**Comment by RamiTrabelsi** [comment]
Hello, I found the method setNewData(data) that should be set before calling mAdapter.notifyDataSetChanged().

Thank you for your library, it is really helping a lot

**Comment by CymChad** [comment]
Share with your friends
