### ISSUE TITLE
多布局问题

### ISSUE THREAD

**Issue by MarnonDev** [CymChad/BaseRecyclerViewAdapterHelper#450]
实现多布局，必须要通过实现接口MultiItemEntity么？现在我们做环信聊天，聊天消息封装在一个Message的实体中，无法集成该接口是不就没办法多布局了

**Comment by CymChad** [comment]
Message 这个实体你可以改吗？

**Comment by MarnonDev** [comment]
不可以的，返回后直接就是一个Message实体的List集合了。多布局可不可以由用户自己根据位置或者展示内容类型直接去判断使用哪个布局呢？

**Comment by CymChad** [comment]
可以，但是需要自己重写一些方法。

**Comment by CymChad** [comment]
http://www.jianshu.com/p/9d75c22f0964  我之前写过一篇文章，你可以参考一下。
注意：新的版本没有```onBindDefViewHolder``这个方法了，你直接用```convert```就好了。

**Comment by xiongyufeng12306** [comment]
recyclerView item 的点击事件和item里面的button 的点击事件发生冲突，也就是说，button 只有重压才能产生点击事件。轻压就只能点击到item ，item会抢走button 的点击事件，请问怎么解决？
  

 

 ------------------ 原始邮件 ------------------
  发件人: "陈宇明";<notifications@github.com>;
 发送时间: 2016年10月27日(星期四) 中午11:36
 收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
 
 主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 多布局问题 (#450)

 

 
http://www.jianshu.com/p/9d75c22f0964 我之前写过一篇文章，你可以参考一下。
注意：新的版本没有onBindDefViewHolder``这个方法了，你直接用convert```就好了。
