### ISSUE TITLE
加载失败，除了点击刷新，能否多一个功能就是继续上拉刷新

### ISSUE THREAD

**Issue by kexingmo** [CymChad/BaseRecyclerViewAdapterHelper#453]
最近公司用了recyclerview，但是以前的业务是加载失败，可以通过点击底部  加载失败 文字或者继续上拉都能实现重新加载的功能，但是BaseRecyclerViewAdapterHelper貌似只支持点击加载？

**Comment by CymChad** [comment]
恩，你也可以自定义，定时开启上拉。

**Comment by CymChad** [comment]
你可以参考一下  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/444

**Comment by kexingmo** [comment]
adapter.showLoadMoreFailedView();
                        recyclerview.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                adapter.removeAllFooterView();
                                adapter.openLoadMore(2);
                            }
                        },1000);
你好，请问是这样吗？当调用adapter.removeAllFooterView();之后，这样开启加载更多？但是有个问题就是1秒后它会自动加载，而不是手动上拉加载

**Comment by CymChad** [comment]
你如果在最后一个item的话他就会调用上拉加载。

**Comment by kexingmo** [comment]
本身LoadMoreFailedView就是最后一个item了所以会自动触发加载，还是实现不了手动上拉才触发，挺纠结的

**Comment by kexingmo** [comment]
LoadMoreFailedView本来就是在最后一个item吧，这还是会导致出现加载失败，然后马上加载更多
所以还是建议作者考虑一下这个问题，我觉得应该很多都有这个需求，失败点击或者上拉可加载

**Comment by CymChad** [comment]
现在是失败了，就可以显示一个加载失败，然后点击就可以就重新加载了。showLoadMoreFailedView

**Comment by kexingmo** [comment]
如果没有失败 可上拉加载，只能再选择其他框架了，谢谢作者的解答

**Comment by CymChad** [comment]
恩，好的。推荐使用 https://github.com/anzaizai/EasyRefreshLayout
