### ISSUE TITLE
使用说明

### ISSUE THREAD

**Issue by zxp0505** [CymChad/BaseRecyclerViewAdapterHelper#456]
发现2.4.4有些变化了 希望把使用说明写的细点   以前用的是1.9.7版本

**Comment by CymChad** [comment]
新的文档上面都有  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki

**Comment by CymChad** [comment]
新的文档上面都有  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki
