### ISSUE TITLE
当View为Gone时，点击View区域，OnItemChildClickListener里依然会有回调

### ISSUE THREAD

**Issue by asdzheng** [CymChad/BaseRecyclerViewAdapterHelper#457]
不同item，根据数据显示隐藏View,当View不可见时，不应该触发点击事件~

**Comment by AllenCoder** [comment]
当view不可见时，不会触发点击事件的吧，你是不是viewholder缓存了部分view,还是其他原因导致判断view不可见那里有问题

**Comment by asdzheng** [comment]
找到原因了，我设置了它父View为gone，但是它自己为Invisible。
不过我觉得这种情况应该也不能被触发点击~

**Comment by CymChad** [comment]
由于逻辑代码中是判断，当前点击的view是否处于gone，所以它如果不为gone就会被触发。
