### ISSUE TITLE
两个按钮叠加在一起，动态隐藏其中一个按钮，显示另一个按钮，点击事件还是之前的

### ISSUE THREAD

**Issue by BaiShou** [CymChad/BaseRecyclerViewAdapterHelper#461]
<FrameLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <Button
                    android:id="@+id/btn_payment"
                    android:layout_width="60dp"
                    android:layout_height="30dp"
                    android:layout_gravity="right"
                    android:layout_marginTop="5dp"
                    android:background="@color/be_apart_from"
                    android:text="支付"
                    android:textSize="16sp"
                    android:visibility="gone" />

                <Button
                    android:id="@+id/btn_complaint"
                    android:layout_width="60dp"
                    android:layout_height="30dp"
                    android:layout_gravity="right"
                    android:layout_marginTop="5dp"
                    android:background="@color/be_apart_from"
                    android:text="投诉"
                    android:textSize="16sp"
                    android:visibility="gone" />
            </FrameLayout>

这样的两个按钮，中途刷新动态改变按钮隐藏状态，点击事件还是之前的
Button payment = helper.getView(R.id.btn_payment);
        Button complaint = helper.getView(R.id.btn_complaint);
        if (isPayment) {
            payment.setVisibility(View.VISIBLE);
            complaint.setVisibility(View.GONE);
        } else {
            complaint.setVisibility(View.VISIBLE);
            payment.setVisibility(View.GONE);
        }

使用的是
.addOnClickListener(R.id.btn_payment)
 .addOnClickListener(R.id.btn_complaint);
添加的子控件点击事件

**Comment by BaiShou** [comment]
经过群里的建议，解决办法是在动态隐藏的时候重新设置点击事件。

**Comment by BaiShou** [comment]
经过测试，还是会这样，当滑动界面，复用ITEM之后，再滑回来，之前的点击事件不对了。具体的我在群里发过视频

**Comment by AllenCoder** [comment]
您好，具体bug,你是否介意在群上发给我一个测试Demo,我来看一下，具体原因，我这边经过测试是正常的，是不是哪里使用的问题？还是测试未完全覆盖到

**Comment by BaiShou** [comment]
新版本已经解决此问题，感谢AllenCoder抽出时间来看我的代码
