### ISSUE TITLE
setEmptyView() 与 addFooterView() 初始化配置

### ISSUE THREAD

**Issue by hongtaoStudio** [CymChad/BaseRecyclerViewAdapterHelper#462]
`setEmptyView()` 被调用后，在 `adapter` 初始化完成时（没有数据），会显示 `EmptyView`，但此时正处于获取数据的状态，`EmptyView` 不应该被隐藏吗？为了在第一次获取数据的时候不显示 `EmptyView` 我只能在获得数据后做处理，逻辑如下：
``` java
protected <T> void setData(List<T> datas, BaseQuickAdapter adapter) {
    if (mIsRefresh) {
        adapter.setNewData(datas);
        if (datas.size() == 0 && adapter.getEmptyView() == null) {
            adapter.setEmptyView(mEmptyView);
        } else if (datas.size() < ApiConstants.ParamValue.PAGE_SIZE) {
            adapter.loadComplete();
            adapter.addFooterView(mNoMoreView);
        }
    } else {
        if (datas.size() == 0) {
            adapter.loadComplete();
            adapter.addFooterView(mNoMoreView);
        } else adapter.addData(datas);
    }
}
```
这部分代码位于父类中，可以看到，逻辑比较繁琐，最理想的使用应该是在 `Adapter` 初始化时做配置，而不是在获得数据后写一堆的逻辑判断。

可能是我还没有理解这个库的使用方法，就我目前看来，只能使用如上的办法，希望能有更好的办法处理这方面的逻辑。

最后建议增加 `setErrorView()`。

thx

**Comment by CymChad** [comment]
EmptyView出现的条件是datas.size() == 0的时候出现。因为adapter不知道你是不是在加载数据中，所以也无法判断。

**Comment by CymChad** [comment]
ErrorView可以重置EmptyView内容达到效果

**Comment by hongtaoStudio** [comment]
谢谢回复！

是否可以在内部做一个初始化变量，当调用 `notifyDataSetChanged()` 系列方法时才显示 `EmptyView()`，在内部能完成的工作尽量在内部完成，最小化外部调用的代码量。

**Comment by CymChad** [comment]
做是肯定可以做的，但是如果这样做了，是不是就会让一进入页面就有数据的情况发生问题了？

**Comment by hongtaoStudio** [comment]
在我查看源码时找到一个 `mEmptyEnable` 变量，在 `getItemCount()` 和 `setEmptyView()` 中被赋值为 **true**，是否可以再增加一个变量 `mIsUseEmpty`，默认为 **true**，然后重载 `setEmptyView()` 从外部为 `mIsUseEmpty` 赋值，最后在 `getItemViewType()` 中多加个判断条件，这样就可以让使用者决定该什么时候显示 `EmptyView`

thx

**Comment by CymChad** [comment]
这个可以的，那我修改一下。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.5' 新增了一个isUseEmpty方法。在你在初始化adapter的时候设置false在回调的时候设置成true就可以了
