### ISSUE TITLE
SimpleOnItemClick点击事件UI反馈效果错乱

### ISSUE THREAD

**Issue by yulongxiao** [CymChad/BaseRecyclerViewAdapterHelper#467]
你好！在使用过程中发现点击某个item后，紧接着调用notifyDataSetChanged(); UI上的反馈效果错乱了，如：我点击第7项，反而第3项出现水波纹反馈效果；

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.6'
