### ISSUE TITLE
请问实现了MultipleItemUseActivity的界面布局，但是如何让item可以水平滚动呢

### ISSUE THREAD

**Issue by magic0908** [CymChad/BaseRecyclerViewAdapterHelper#468]
http://img.blog.csdn.net/20160901184302900?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center  就是这样的水平滚动效果，我想过用HorizontalScrollView，但是这个控件不支持回收复用，图片多了估计会崩掉。

**Comment by CymChad** [comment]
解决方案有很多种，你可以选择用recycleview

**Comment by CymChad** [comment]
设置横向的就行了
