### ISSUE TITLE
嵌套RecyclerView 问题

### ISSUE THREAD

**Issue by JakeWang123** [CymChad/BaseRecyclerViewAdapterHelper#469]
RecyclerView嵌套RecyclerView，在item 为RecyclerView的数据发生变化是，通过父recyclerView adapter 的notifyItemChanged(i)没有实现界面的刷新

**Comment by elfman** [comment]
RecyclerView不要互相嵌套，很容易出问题的，请尽量规避这种做法

**Comment by JakeWang123** [comment]
但是我现在有个要实现多header类型可伸缩的list，应该采用哪种方式实现比较好

**Comment by elfman** [comment]
多header使用多种itemtype来取代。可伸缩list可以使用expandableItem功能，或自己管理Adapter中的数据

**Comment by JakeWang123** [comment]
多header使用多种itemtype来取代是可以的，但是要同时实现多header可以伸缩怎么解决？

**Comment by elfman** [comment]
你是指点header然后展开子项？

**Comment by JakeWang123** [comment]
是的

**Comment by elfman** [comment]
你看看expandableItem的用法，不难做到的

**Comment by JakeWang123** [comment]
OK
