### ISSUE TITLE
怎么使用自定义的viewHolder的问题

### ISSUE THREAD

**Issue by JianJianZhang** [CymChad/BaseRecyclerViewAdapterHelper#472]
请问我的item中有自定义的控件，需要设置，怎么使用自定义的viewHolder?
      public class QuickAdapter extends BaseQuickAdapter<Status, BaseViewHolder> 

      在2.1.3版本中，没有这样一个构造方法啊，只有public class QuickAdapter extends BaseQuickAdapter<Status>

**Comment by elfman** [comment]
2.4.0之后才支持使用自定义的viewHolder的
