### ISSUE TITLE
能不能把侧划删除的功能也加入进来，这样就比较完美了

### ISSUE THREAD

**Issue by akingyin1987** [CymChad/BaseRecyclerViewAdapterHelper#475]
RT

**Comment by MrShui** [comment]
BaseItemDraggableAdapter应该就可以

**Comment by CymChad** [comment]
侧滑删除更多的是item的view操作，本库更多的是提供对adapter范围内的操作。

**Comment by CymChad** [comment]
只是侧滑删除BaseItemDraggableAdapter是支持的，但是如果像QQ那样侧滑出菜单然后点击菜单再删除就不支持了。

**Comment by CymChad** [comment]
可组合BRVAH使用：https://github.com/anzaizai/EasySwipeMenuLayout
