### ISSUE TITLE
希望文档能再详细点

### ISSUE THREAD

**Issue by MoneyNotFoundException** [CymChad/BaseRecyclerViewAdapterHelper#476]
由于作者的源码注释都是英文的，理解起来还是有一定难度，现有的文档有点简洁，希望作者能将api文档再完善下，对于提供的各种公开方法能说明用法与用途。感谢！

**Comment by CymChad** [comment]
恩，好的，后续会增加更多文档说明。近期有点事情，写好了告诉你。

**Comment by MoneyNotFoundException** [comment]
@CymChad 好的，感谢奉献精神！
