### ISSUE TITLE
上拉加载更多，我还没滑到底部就自动调用了onLoadMoreRequested();而且还隐藏不掉。

### ISSUE THREAD

**Issue by leguang** [CymChad/BaseRecyclerViewAdapterHelper#477]
上拉加载更多，我还没滑到底部就自动调用了onLoadMoreRequested();而且还隐藏不掉。
用的是2.4.5版本
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.5'

以下是初始化部分代码
        recyclerview.setLayoutManager(new LinearLayoutManager(_mActivity));
        mAdapter = new QuikeAdapter();
        mAdapter.openLoadAnimation();
        View customLoading = getLayoutInflater(savedInstanceState).inflate(R.layout.item_foot_recyclerview, (ViewGroup) recyclerview.getParent(), false);
        mAdapter.setLoadingView(customLoading);
        mAdapter.setOnLoadMoreListener(this);mAdapter.loadComplete();
        mAdapter.openLoadMore(20);
        recyclerview.setAdapter(mAdapter);

以下是下拉刷新代码
    @Override
    public void refresh(List<GongdianData> mGongdianData, int pagination) {
        KLog.e("refresh_pagination::" + pagination);
        if (null != mGongdianData && mGongdianData.size() > 0) {
            if (pagination == 0) {
                //刷明是第一页，或者是刷新。
                //把页码重置为0，代表第一页。
                this.pagination = 0;
                mCurrentPosition = 0;
                mAdapter.setNewData(mGongdianData);
                mAdapter.setItemChecked(0);
                mAdapter.openLoadMore(20);
                mAdapter.removeAllFooterView();
                recyclerview.setAdapter(mAdapter);
                mAdapter.hideLoadingMore();
                showProjectContent(0);
            } else {
                mAdapter.addData(mGongdianData);
            }
        }
    }

总是会自动调用onLoadMoreRequested();，而且无法隐藏customLoading，但是loadComplete();方法可以隐藏，但是无法上拉加载了。我参照了你的demo中的PullToRefreshUseActivity，真是搞了一下午了。哎，不知道是哪儿姿势不对。还请赐教。
如果还需要什么信息，我贴出来。

**Comment by leguang** [comment]
哎，放弃了，实在调不出来，一天时间就这么浪费了。
每一页都设置的20条数据，mAdapter.openLoadMore(20);也是设置的20条，一进来就自动加载更多，根本没滑到底部，没法子。

**Comment by AcgnCodeMonkey** [comment]
不建议直接使用这个刷新，我觉得为了统一性，最好使用单独的刷新库，推荐BGA

**Comment by githubzaibao** [comment]
可以使用https://github.com/anzaizai/EasyRefreshLayout 配合BRVAH项目，功能分离开更好控制

**Comment by CymChad** [comment]
你是不是嵌套了sv？

**Comment by CymChad** [comment]
如果是的话建议你使用第三方的上拉，可以使用https://github.com/anzaizai/EasyRefreshLayout 配合BRVAH项目，功能分离开更好控制

**Comment by CymChad** [comment]
因为sv和rv和冲突。

**Comment by CymChad** [comment]
addData是加载更多数据并且还有下一页，loadComplete是加载完毕没有下一页的，都可以关闭加载条。

**Comment by leguang** [comment]
我用的是android-Ultra-Pull-To-Refresh这个下拉刷新，我试试你们推荐的那个EasyRefreshLayout 。
