### ISSUE TITLE
自定义contentView

### ISSUE THREAD

**Issue by caicai123** [CymChad/BaseRecyclerViewAdapterHelper#478]
自定义contentView，如果使用这种构造方式 
public BaseQuickAdapter(View contentView, List<T> data) {}，程序崩溃  ，我想自定义contentView怎么使用呢？

**Comment by CymChad** [comment]
写在xml里面，最新的版本BaseQuickAdapter(View contentView, List<T> data)去除了这个构造了。

**Comment by githubzaibao** [comment]
super(R.layout.xxx, null);
在构造函数中调用父类的构造放假，传入你的contentView的layout资源文件即可，不懂你问的是不是这个功能

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/417  你可以参考一下。
