### ISSUE TITLE
BaseQuickAdapter中的setTag有什么意义

### ISSUE THREAD

**Issue by peterforme** [CymChad/BaseRecyclerViewAdapterHelper#48]
@Override
    public void onBindViewHolder(BaseAdapterHelper helper, int position) {
        helper.itemView.setTag(position);
        T item = getItem(position);
        convert((H) helper, item);
    }
代码如上

我看貌似没有地方用到这个tag啊

**Comment by CymChad** [comment]
这不是我的代码，你看错了吧。

**Comment by CymChad** [comment]
你看错项目了
