### ISSUE TITLE
分组的伸缩栏

### ISSUE THREAD

**Issue by bruceyu1994** [CymChad/BaseRecyclerViewAdapterHelper#480]
分组的伸缩栏中的效果图片没有
url地址：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E5%88%86%E7%BB%84%E7%9A%84%E4%BC%B8%E7%BC%A9%E6%A0%8F

**Comment by CymChad** [comment]
多谢提醒，现在好了。
