### ISSUE TITLE
关于点击回调的控件获取问题

### ISSUE THREAD

**Issue by smilEdit** [CymChad/BaseRecyclerViewAdapterHelper#481]
简单类型的recyclerView的item。 我的item布局里面有个add按钮，还有一个textview显示数量，我在点击add按钮的时候，想让textview的数量增加。我希望我的逻辑在RecyclerView所在的activity处理，可是
` public void SimpleOnItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i)`
这个回调里面并没有能够获取item的View的方法。通过baseQuickAdapter只能调用getItemId getItemType之类的，由于getItemView在baseQuickAdapter是protected的，所以不能调用。那么我怎么在点击add的时候获取到TextView控件呢。     不知道是否描述清楚了，小白求教。

**Comment by CymChad** [comment]
view.findbyid...应该可以获取你的当前item布局的view，当时我不推荐你这样使用，通过都是通过一个改变数据实体来实现这个view的内容改变，也就是说找到当前的entity的数量属性进行修改然后刷新界面。

**Comment by smilEdit** [comment]
谢谢

**Comment by CymChad** [comment]
没事，感谢你的使用。
