### ISSUE TITLE
BaseQuickAdapter的addData方法问什么position不能等于size

### ISSUE THREAD

**Issue by pzhangleo** [CymChad/BaseRecyclerViewAdapterHelper#482]
public void addData(int position, List<T> data) {
        if(0 <= position && position < this.mData.size()) {
            this.mData.addAll(position, data);
            this.notifyItemInserted(position);
            this.notifyItemRangeChanged(position, this.mData.size() - position - data.size());
        } else {
            throw new ArrayIndexOutOfBoundsException("inserted position most greater than 0 and less than data size");
        }
    }

**Comment by Ludejin** [comment]
这个方法是在指定的位置添加一个List到列表中！最后一条数据的position是size -1 ，而不是size，所以等于size的情况会出现越界的！

**Comment by pzhangleo** [comment]
是指this.mData.addAll(position, data)么？
List的addAll方法对于position的限制是：
IndexOutOfBoundsException	if the index is out of range (index < 0 || index > size())

**Comment by Ludejin** [comment]
@pzhangleo 我明白你的意思，但是position如果等于size的话，建议用addAll<data> 方法去实现，在这里就不需要这样的！

**Comment by pzhangleo** [comment]
ok，了解
