### ISSUE TITLE
请问onBindViewHolder中viewType 什么情况会为0? 

### ISSUE THREAD

**Issue by liuyuttkx** [CymChad/BaseRecyclerViewAdapterHelper#483]
我出现的问题是,在无网的情况下加载Adapter会出现OutOfBoundsException ,在这一步
 case 0:
            this.convert(holder, this.mData.get(holder.getLayoutPosition() - this.getHeaderLayoutCount()));

**Comment by CymChad** [comment]
默认就是0

**Comment by CymChad** [comment]
OutOfBoundsException 你可以debug一下你的数据看下什么原因

**Comment by liuyuttkx** [comment]
十分感谢!!!
 
您写的这个库实在太牛了.
有几个问题向您请教一下:
1. 在实现上拉接口后, 是否可以手动结束上拉刷新, 关闭上拉刷新 和 打开上拉刷新?

经过几天的摸索, 发现了几个小问题,向您请教一下.

1.在无网的情况下,data.size()为0的情况下, 我在adapter构造方法中添加了一个头布局(headview), 然后在展示adaper时, 报索引越界异常. debug发现adapter调用了onbindViewHolder方法, 该方法中调用了mDatas.get(position - .....); 此时mDatas.size()为0. 
我的解决方法: 将addHeadview的代码放在数据回调方法中
备注: 在有网的情况下(有数据); 一切正常. 

大神, 关于贵项目,我写了一个多条目自定义多个 与条目类型对应的ViewHolder  Demo, 就是每一种条目类型对应一个ViewHolder. 我到时发给您看看如何!!!!



liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-08 10:05
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
默认就是0

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/499

**Comment by CymChad** [comment]
你可以先试试看。有其他问题可以再提问。

**Comment by liuyuttkx** [comment]
您 好:

请问 该库有 手动禁用上拉加载 和 打开上拉加载的API吗?  版本号:2.1.4





liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-09 16:26
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
你可以先试试看。有其他问题可以再提问。

**Comment by CymChad** [comment]
有，你可以看下 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD

**Comment by liuyuttkx** [comment]
您 好:
 十分感谢这么晚您还在回答我的提问...!!!!
 
这个地方我已经看了, 这个是由加载的页数来控制的. 我遇到 的情况是每次上拉加载的数量并不确定, 有的是15 条,有的是14, 或者是其它数量,所以,这个方法并不适用.
我需要在需要禁止的地方,调用防止上拉加载, 在需要的时候开启上拉.




liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-10 00:03
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
有，你可以看下 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD

**Comment by CymChad** [comment]
pageSize只要满足一个屏幕数量就可以了，不需要十分精确。

**Comment by CymChad** [comment]
它只会影响第一页的加载，后续的加载不影响

**Comment by liuyuttkx** [comment]
请问有什么 方法 可以在关闭上拉加载后,再次打开上拉加载接口
版本2.1.4.  关闭上拉加载时调用mAdapter.loadComplete();



liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-10 00:32
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
它只会影响第一页的加载，后续的加载不影响
―

**Comment by CymChad** [comment]
如果加载失败了可以调用，setLoadMoewFailedView方法，这样会显示一个失败的view，然后点击就可以再次打开上拉加载。

**Comment by liuyuttkx** [comment]
非常感谢!!!
    请问楼主有v 2.1.4离线版的library库下载地址吗? 现在github上更新了,API发生了改变,但还是想用之前的版本 . 
        万分感谢!!!



liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-15 21:59
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
如果加载失败了可以调用，setLoadMoewFailedView方法，这样会显示一个失败的view，然后点击就可以再次打开上拉加载。
―

**Comment by liuyuttkx** [comment]
楼主:

        我用的这个版本的BaseQucikAdapter是有两个泛型,一个bean类型,一个BaseViewHolder;  可以自定义BaseViewHolder.有 mAdapter.openLoadMore(page);
不是现在最新的mAdapter.loadMoreplete();

        万分感谢!!!




liuyu195@126.com
 
发件人： liuyu195@126.com
发送时间： 2016-11-17 20:18
收件人： CymChad/BaseRecyclerViewAdapterHelper
主题： Re: Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
非常感谢!!!
    请问楼主有v 2.1.4离线版的library库下载地址吗? 现在github上更新了,API发生了改变,但还是想用之前的版本 . 
        万分感谢!!!



liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-15 21:59
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
如果加载失败了可以调用，setLoadMoewFailedView方法，这样会显示一个失败的view，然后点击就可以再次打开上拉加载。
―

**Comment by liuyuttkx** [comment]
您好,我已经找到了,谢谢!!!
https://libraries.io/github/CymChad/BaseRecyclerViewAdapterHelper


liuyu195@126.com
 
发件人： liuyu195@126.com
发送时间： 2016-11-17 20:18
收件人： CymChad/BaseRecyclerViewAdapterHelper
主题： Re: Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
非常感谢!!!
    请问楼主有v 2.1.4离线版的library库下载地址吗? 现在github上更新了,API发生了改变,但还是想用之前的版本 . 
        万分感谢!!!



liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-15 21:59
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
如果加载失败了可以调用，setLoadMoewFailedView方法，这样会显示一个失败的view，然后点击就可以再次打开上拉加载。
―

**Comment by liuyuttkx** [comment]
请问baserecycleradapterhelper中有无 分组悬停功能



liuyu195@126.com
 
发件人： 陈宇明
发送时间： 2016-11-09 16:26
收件人： CymChad/BaseRecyclerViewAdapterHelper
抄送： liuyuttkx; Author
主题： Re: [CymChad/BaseRecyclerViewAdapterHelper] 请问onBindViewHolder中viewType 什么情况会为0? (#483)
你可以先试试看。有其他问题可以再提问。
