### ISSUE TITLE
Adapter remove数据后Inconsistency detected

### ISSUE THREAD

**Issue by psv100** [CymChad/BaseRecyclerViewAdapterHelper#489]
要过滤(remove)adapter特定数据时，会报 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 3(offset:2).state:4，不设置OnLoadMore监听就不会报错，是我remove的姿势不对吗

**Comment by YSWing** [comment]
After removing view, call adapter's  notifyDataSetChanged().

**Comment by psv100** [comment]
Thanks, i go to try.

**Comment by CymChad** [comment]
@YSWing Thank you for your answer

**Comment by psv100** [comment]
@YSWing  Thanks! It worked,but if i set notifyDataSetChanged(), the REMOVE Animation will disappear, what should i do?

**Comment by psv100** [comment]
@CymChad 大大，设置 notifyDataSetChanged()之后 remove动画就没了，该咋办呀，试过设置notifyDataSetChanged()延迟或者onLoadMoreRequested()延迟也不行额
