### ISSUE TITLE
请教下 怎样判断 『正在加载更多』

### ISSUE THREAD

**Issue by wjehovah** [CymChad/BaseRecyclerViewAdapterHelper#49]
```java
 if (refreshLayout.isRefreshing()) {
      refreshLayout.setRefreshing(false);
    }
```
正则刷新 SwipeRefreshLayout 有接口，正在加载更多 该怎么判断呢？

**Comment by CymChad** [comment]
目前没有暴露这个方法，你有什么地方需要用到吗？

**Comment by wjehovah** [comment]
昨天 不是说 加载更多 容易奔溃嘛，弹出 dialog来避免。但是 dialog dismiss 要结束刷新，有了这个 方便 结束刷新。

**Comment by CymChad** [comment]
ok，了解，我想想。

**Comment by CymChad** [comment]
我想了下不用呀，你弹出应该就是你请求开始的时候，你dismiss应该就是你数据加载完的时候，所以不应该是依赖我的状态来，应该是依赖你请求的回调来的。不是控件决定，是你的数据决定。

**Comment by wjehovah** [comment]
有时候网络不好，加载很多时，用户按下 返回键 想取消 加载动作。这时候 数据没有加载完成，也没有加载失败

**Comment by CymChad** [comment]
你可以监听弹出框的关闭事件。因为『正在加载更多』是由你去告诉控件的，不是控件告诉你。

**Comment by wjehovah** [comment]
```java
  @Override public void onDismiss(DialogInterface dialog) {
    //结束刷新
    if (refreshLayout.isLoadingMore()) {
      refreshLayout.endLoadingMore();
    }
    refreshLayout.endRefreshing();
  }
```
我就是想在 dismiss listener 里面做取消加载更多
