### ISSUE TITLE
集成XRecyclerView,用BaseQuickAdapter的话,adapter下标从1开始,自己写Adapter没有问题

### ISSUE THREAD

**Issue by findvoid** [CymChad/BaseRecyclerViewAdapterHelper#490]
如题:
XRecyclerView:https://github.com/jianghejie/XRecyclerView

**Comment by CymChad** [comment]
BRVAH的下标是使用的getLayoutPosition拿到的，你是不是有头部？

**Comment by CymChad** [comment]
不建议组合使用，因为BRVAH没有适配过XRecyclerView，XRecyclerView也没适配过BRVAH

**Comment by findvoid** [comment]
使用getAdapterPosition()是不是好一些?

**Comment by CymChad** [comment]
getLayoutPosition 拿到的是position是事实的，比如你rm了一个item，他就会减去你的item坐标，更新所有item的坐标，如果你只是getPosition就算你rm了一个item，他的坐标是不会刷新的，所以会导致有问题。
