### ISSUE TITLE
自定义不同的item类型

### ISSUE THREAD

**Issue by bruceyu1994** [CymChad/BaseRecyclerViewAdapterHelper#491]
代码中两个构造函数是一样的,如下：
``` android
 public MultipleItem(int itemType, String content) {
        this.itemType = itemType;
    }
public MultipleItem(int itemType) {
    this.itemType = itemType;
}
```
另：多布局有两行布局的item都是一样的参考图片没有：
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/raw/develop/demo_res/multiple_demo.png

url地址如下：
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8D%E5%90%8C%E7%9A%84item%E7%B1%BB%E5%9E%8B

**Comment by CymChad** [comment]
感谢提醒，已修正过来了。

**Comment by bruceyu1994** [comment]
下面一张图还是没有

**Comment by CymChad** [comment]
ok，搞定
