### ISSUE TITLE
Expandable吸附顶部功能

### ISSUE THREAD

**Issue by sweet2o09** [CymChad/BaseRecyclerViewAdapterHelper#495]
请问是否能让所有的LEVEL_0布局在滑动的时候都吸附在顶部,不滑出界面?

**Comment by elfman** [comment]
这功能属于View层，超出Adapter的职责，建议使用其它库实现

**Comment by CymChad** [comment]
推荐 https://github.com/oubowu/PinnedSectionItemDecoration  本库不支持
