### ISSUE TITLE
add autorefresh

### ISSUE THREAD

**Issue by zhetengxiang** [CymChad/BaseRecyclerViewAdapterHelper#497]
你好，
    请问是否可以添加预加载功能，现在有需求就是当列表滑动到倒数第五个的时候，就自动运行loadMore的动作

**Comment by CymChad** [comment]
恩，可以。稍后我会合成你的代码

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.5.0' 

Add autoLoadMore methods
use setAutoLoadMoreSize(int autoLoadMoreSize)

**Comment by zhetengxiang** [comment]
thanks
