### ISSUE TITLE
自定义viewholder问题

### ISSUE THREAD

**Issue by scutcl** [CymChad/BaseRecyclerViewAdapterHelper#501]
自定义viewholder重载下面这个函数
@Override
    protected ViewHolder createBaseViewHolder(View view) {
        return new ViewHolder(view);
    }
下面是自定义viewholder类
public static class ViewHolder extends BaseViewHolder {
        
        @BindView(R.id.txt_order_no)
        TextView txtOrderNo;

        public ViewHolder(View view) {
            super(view);
            ButterKnife.bind(this, view);
        }
    }
在加载更多的时候会出现 txt_order_no 控件找不到为空而报错。
原因应该是加载更多的时候  createBaseViewHolder传的view是加载更多的布局，而不是显示数据的布局，导致初始化ViewHolder失败，希望解决这个问题。

**Comment by CymChad** [comment]
由于你使用的是自定义的LoadingView，所以就走createBaseViewHolder（View view）方法，你用ButterKnife它默认就去加载txt_order_no，所以空了，我建议你在你自定义的LoadingView里面加一个隐藏的txt_order_no。如果你不用ButterKnife，你就findbyid你可以做判空处理。

**Comment by CymChad** [comment]
或者你可以通过getItemViewType拿到type去判断是否是正常的显示数据的布局

**Comment by CymChad** [comment]
默认正常显示的数据type为0
