### ISSUE TITLE
上拉加载时会已加载的列表出现动画

### ISSUE THREAD

**Issue by zxp0505** [CymChad/BaseRecyclerViewAdapterHelper#504]
打开动画 上拉加载 操作 预期加载出的新的列表有动画 已加载过的列表不要动画效果

**Comment by CymChad** [comment]
收到

**Comment by zxp0505** [comment]
上面的问题 不知道您解决了吗

**Comment by CymChad** [comment]
代码已经提交到开发分支了已经在测试了。还没发布。
1.我建议你先关闭动画。
2.你可以重写addData方法。

**Comment by CymChad** [comment]
导致这个bug的原因是
```java
  public void addData(List<T> newData) {
        this.mData.addAll(newData);
        hideLoadingMore();
//        notifyItemRangeInserted(mData.size() - newData.size() + getHeaderLayoutCount(), newData.size());
        notifyDataSetChanged();
    }
```
`notifyDataSetChanged();`方法的问题，因为全部更新了，所以导致全部走了一遍动画代码。
还没发布新版本的原因是，这次对上拉刷新改动很大，所以需要测试一段时间。

**Comment by dalian3164** [comment]
你好，上拉加载条目应该增加到底部，并且不应该刷新已有的资源。
//        if (0 <= position && position < mData.size()) {
            mData.addAll(position, data);
            notifyItemInserted(position);
            notifyItemRangeChanged(position, mData.size() - position - data.size());
//        } else {
//            throw new ArrayIndexOutOfBoundsException("inserted position most greater than 0 and " +
//                    "less than data size");
//        }
我把这注掉以后只能上啦加载一次，第二次就触发不了了

**Comment by CymChad** [comment]
你重写错了，应该是addData（List list），

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.0'  已修复，这个版本重构了上拉加载，这是使用文档 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD
