### ISSUE TITLE
建议加上自动绑定，省去 手动 setOnclickListener

### ISSUE THREAD

**Issue by Alex-Cin** [CymChad/BaseRecyclerViewAdapterHelper#506]
> 建议加上自动绑定，省去 手动 setOnclickListener

<pre>

protected BaseViewHolder(View view) {
	super(view);
	this.views = new SparseArray<View>();
	this.childClickViewIds = new LinkedHashSet<>();
	this.itemChildLongClickViewIds = new LinkedHashSet<>();
	convertView = view;
	setOnClickListener(view);
}

public void setOnClickListener(@NonNull View view) {
	if (view == null) {
		//LogUtil.w("控件为空");
		return;
	}
	addOnClickListener(view.getId());
	if (view instanceof ViewGroup) {
		setOnClickListener((ViewGroup) view);
	}
}

private void setOnClickListener(@NonNull ViewGroup viewGroup) {
	if (viewGroup == null) {
		return;
	}
	//addOnClickListener(viewGroup.getId());
	for (int i = 0; i < viewGroup.getChildCount(); i++) {
		View v = viewGroup.getChildAt(i);
		if (v instanceof ViewGroup) {
			setOnClickListener((ViewGroup) v);
		} else if ((v != null) && (v instanceof View)) {
			setOnClickListener(v);
		}
	}

}
</pre>

> 在 Activity 中，不用写 两个回调去区分 子控件 和 一整条，可以省去不少代码量

<pre>
/\*点击事件 不需要手动绑定，直接就可以响应\*/
recyclerView.addOnItemTouchListener(new MyOnItemTouchListener());

private final class MyOnItemTouchListener extends OnItemTouchListener<NewsListAdapter> {

	@Override
	public void onItemTouch(NewsListAdapter adapter, @ClickType String clickType, View v, int position) {
		if (R.id.bt_1 == v.getId()) {
			ToastUtil.shortCenter("你好 " + position);
		} else if (R.id.bt_2 == v.getId()) {
			ToastUtil.shortCenter("你坏 " + position);
		} else if (R.id.iv == v.getId()) {
			ToastUtil.shortCenter("图片 " + position);
		} else if (ClickType.clickLayout.equals(clickType)) {
			ToastUtil.shortCenter("item-- " + position);
		}
	}
}
</pre>

**Comment by AllenCoder** [comment]
很多时候，没有必要对childviewid进行绑定监听，区分开来，会让业务逻辑的处理更清楚，事件的处理更高效。谢谢你的建议
