### ISSUE TITLE
RecyclerView Item TextView ClickSpan问题

### ISSUE THREAD

**Issue by songmao123** [CymChad/BaseRecyclerViewAdapterHelper#507]
RecyclerView Item中的TextView设置ClickableSpan事件时，同时走了OnItemClickListener中的SimpleOnItemClick()方法，会导致Item的click事件和TextView的Clickable事件生效。

**Comment by CymChad** [comment]
收到

**Comment by AllenCoder** [comment]
由于设计之初，考虑欠佳。将recyclerview的touch事件消费掉了，分发到了childview和itemview。所以，目前处理办法是，将childview的Textview的clickspan作为childview的click事件来监听，可以避免掉这个bug

**Comment by chenbinzhou** [comment]
也就是说不能使用simpleOnItemClick了？

**Comment by songmao123** [comment]
@CymChad 这个放到Touch事件里面处理点击事件可能不太合适(例如，像qq空间那样的图片列表，如果把这些图片放到一个LinearLayout容器里面，单独设置图片ImageView点击预览事件时，如果外层的LinearLayout容器没有设置那个addListener方法，将会导致内部的ImageView点击事件被屏蔽无法响应)！

还有之前版本里面有单独设置item点击事件的方法，但是新版本去掉了，个人觉得这个方法保留还是蛮好的！:smile:

**Comment by AllenCoder** [comment]
http://blog.csdn.net/zhaizu/article/details/51038113  今天研究clickspan的源码，发现针对点击事件，这一直都是个坑，并不是这个库引入的 ，源码在处理textview的click事件时遇到clickspan也会同时触发

**Comment by songmao123** [comment]
我现在的做法是，设置`TextView`的点击事件，但是它的点击事件什么也不错！同事设置它的ClickSpan事件，再重写`LinkMovementMethod`的`onTouchEvent`方法，这方法可以判断点击的是`TextView`链接还是链接以外的部分，点击链接的话就走ClickSpan的事件， 链接以外的部分就通过接口暴露给外部来进行相应的逻辑处理！这方式目前还是可行的。

**Comment by AllenCoder** [comment]
good .!!
