### ISSUE TITLE
remove(position)问题？

### ISSUE THREAD

**Issue by Destiny01** [CymChad/BaseRecyclerViewAdapterHelper#508]
这个remove的position数据会自动调整吗？假如我remove(0)，第一条删除，然后第二条到第一条位置，但是在此remove（position）时，position=1.我该如何调整移除后的position呢？

**Comment by CymChad** [comment]
position会自动调整

**Comment by CymChad** [comment]
你有head吗？

**Comment by Destiny01** [comment]
谢谢，已解决！

**Comment by stormlei** [comment]
@Destiny01  我也碰到了这个问题，请问你怎么解决的

**Comment by umeitime** [comment]
position不会自动调整啊？
