### ISSUE TITLE
PullToRefreshUseActivity上拉刷新

### ISSUE THREAD

**Issue by mpxl** [CymChad/BaseRecyclerViewAdapterHelper#51]
mQuickAdapter.openLoadMore(PAGE_SIZE, false)   设置为false,使其不能进行上拉加载，然而进行下拉刷新后，上拉加载就可以加载了，这是怎么回事？

**Comment by CymChad** [comment]
下拉刷新后，会重置的。

**Comment by CymChad** [comment]
因为你设置了加载更多的监听所有，下拉刷新的时候回重置为开始上拉刷新。

**Comment by mpxl** [comment]
搜嘎，我把上拉加载监听去掉，就可以了  感谢
