### ISSUE TITLE
同时设置头布局和空view的时候不显示空view

### ISSUE THREAD

**Issue by Tiannuo** [CymChad/BaseRecyclerViewAdapterHelper#510]
adapter.setEmptyView(emptyView);
     adapter.addHeaderView(view);

**Comment by EzioL** [comment]
在adapter里面重写 setEmptyView(true,true,view)

**Comment by CymChad** [comment]
@EzioL 感谢你回答。

**Comment by Tiannuo** [comment]
thankyou
