### ISSUE TITLE
如何判断是否已经添加了footerView?

### ISSUE THREAD

**Issue by Destiny01** [CymChad/BaseRecyclerViewAdapterHelper#512]
我有一个尾部加载完成的view，如何判断是否已经添加了footerView?

**Comment by shichaohui** [comment]
adapter.getFooterLayout() 获取 layout，然后就可以用下面的方法判断：
1. layout.indexOfChild(loadCompletedView) 返回 -1 表示不存在，>=0 表示存在；
2. 如果可以确定其他的 footer view 的数量的话，也可以根据 layout 的数量判断是否存在loadCompletedView；
3. 也可以遍历 layout 的 child view 判断是否存在loadCompletedView。

**Comment by Destiny01** [comment]
好的，谢谢！
