### ISSUE TITLE
请问该如何实现伸缩栏单开

### ISSUE THREAD

**Issue by tatsuyuki25** [CymChad/BaseRecyclerViewAdapterHelper#513]
目前有个需求
需要在一个item打开后其他的item必须关起来
在adapter中只有看到expandAll而已
但没有看到collapseAll
请问要怎么实现这个功能比较好呢
谢谢

**Comment by elfman** [comment]
你可以设置个变量存放已经展开的item（不是position，position是会变的，需要时用`getItemPosition(item)`获取position），当展开另一个item时就把上一次的item关闭，也就实现单开了吧

**Comment by tatsuyuki25** [comment]
好的 謝謝
我在試試看
