### ISSUE TITLE
在数据快速滑动时,轻触屏幕会触发点击事件

### ISSUE THREAD

**Issue by hxy493045049** [CymChad/BaseRecyclerViewAdapterHelper#515]
如题,
我使用原生的adapter时,在数据滚动时点击屏幕,效果是停止滚动,然后再次点击才触发单击事件
切换到base后,在数据快速滑动时点击屏幕,直接就触发事件了
感觉这种体验不好

**Comment by AllenCoder** [comment]
这个问题，后续我优化一下，针对快速滚动点击的触发问题

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/500  加入优化

**Comment by yuruxuan** [comment]
不知道现在解决了没……困扰好久了

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.3' 已修复
修复日志：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.6.3
