### ISSUE TITLE
addOnItemTouchListener之后，TextView设置 ClickableSpan 后点击事件重复响应

### ISSUE THREAD

**Issue by chenbinzhou** [CymChad/BaseRecyclerViewAdapterHelper#516]
响应了2次点击事件，请问这是为何？我有做处理并重写textview

**Comment by AllenCoder** [comment]
1. 可以不实现提供的单击方案，单独在adapter里面增加点击事件，后续，这块我将重点优化和重构
2. 使用库提供的单击事件，但同时屏蔽掉clickspan的点击事件，让其每次只有一种响应的回调

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/500 待优化

**Comment by AllenCoder** [comment]
http://blog.csdn.net/zhaizu/article/details/51038113  今天研究clickspan的源码，发现针对点击事件，这一直都是个坑，并不是这个库引入的 ，源码在处理textview的click事件时遇到clickspan也会同时触发，需要用户自己来重写改善
