### ISSUE TITLE
加载动画不在屏幕最低部

### ISSUE THREAD

**Issue by wasneverlonely** [CymChad/BaseRecyclerViewAdapterHelper#518]
如果加载的数据没有占据全屏  在次加载加载动画不会出现在屏幕最底部.这个有办法解决吗。是不是得重写swi..layout？

**Comment by CymChad** [comment]
上拉加载view，没有占满一行？

**Comment by CymChad** [comment]
你只需要设置pageSize设置成一个屏幕的数目就可以了，这个取决于你的pageSize
