### ISSUE TITLE
item长按事件

### ISSUE THREAD

**Issue by treycc** [CymChad/BaseRecyclerViewAdapterHelper#519]
使用OnItemClickListener，不设置onItemLongClick，默认长按事件还是被消费，不能触发onclick，这个是不是应该可以改成不设置还是触发onclick

**Comment by AllenCoder** [comment]
长按不设置onItemLongClick.应该是不触发任何事件的，我刚试了一下部分的App,例如手机QQ的列表，长按不会触发onclick,但是掘金的客户端 ，长按又可以触发。这个你根据具体的业务标准自己实现改动一下

**Comment by treycc** [comment]
QQ长按有弹出窗口啊

**Comment by treycc** [comment]
我的意思是觉得大部分都像掘金这样没有长按事件最终还被onclick拦截的比较常见。

**Comment by AllenCoder** [comment]
后续会加入点击的优化计划之中

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/500  加入优化中
