### ISSUE TITLE
上拉加载的 showLoadMoreFailedView 在没有数据时会报错

### ISSUE THREAD

**Issue by tatsuyuki25** [CymChad/BaseRecyclerViewAdapterHelper#520]
使用情况
有设定emptyView
第一次载入失败后 call showLoadMoreFailedView
但这时只会显示emptyView
不会显示 LoadMoreFailedView
而直接执行重载后让他失败在call showLoadMoreFailedView
就会出现 The specified child already has a parent. You must call removeView() on the child's parent first.

判断画面上没有显示 LoadMoreFailedView
而是显示emptyView
这时又没有对 LoadMoreFailedView 进行 click 的动作
就直接执行 showLoadMoreFailedView
导致错误
请问有何解呢？

**Comment by shichaohui** [comment]
1. 自定义加载更多失败的 View。
2. 使用 emptyView 提示无数据时加载失败，使用 loadMoreFailedView 提示有数据时加载失败。
