### ISSUE TITLE
异步加载图片的时候会错位，请问怎么解决

### ISSUE THREAD

**Issue by HuiLuan** [CymChad/BaseRecyclerViewAdapterHelper#521]
我用的是v1.8.5, 我看说明里有helper.setImagUrl， 我下载了好几个版本都么有找到该方法。
请问如果是异步加载图片，怎样处理错位的问题？
我用Glide.with(mContext).load(item.getUserAvatar()).crossFade().into((ImageView) helper.getView(R.id.iv)); 也不行

**Comment by HuiLuan** [comment]
Glide.with(mContext).load(item.getUserAvatar()).crossFade().into((ImageView) helper.getView(R.id.iv));

**Comment by gallonyin** [comment]
imageView.setTag(R.id, url);
请求后getTag进行比对
