### ISSUE TITLE
有个问题,希望有人能解答一下

### ISSUE THREAD

**Issue by qiangxi** [CymChad/BaseRecyclerViewAdapterHelper#523]
有这样一个需求:点击某个item,为这个item中的一些view设置属性,比如更换文本颜色或背景图片.同时重置其他item中的一些view的文本颜色或者背景图片为默认,这个需求使用ListView很好完成,但是使用recyclerView却没有找到实现方法,所以对于这种需求,RecyclerView怎么实现呢?或者说BaseRecyclerViewAdapterHelper库能满足这种需求吗?

**Comment by elfman** [comment]
你是设置了属性后view没有变化吗？有没有调用过`notifyItemRangeChanged`请求重绘？

**Comment by qiangxi** [comment]
view有变化.但是这还不够,最终需求是改变某个item里的某些view的属性,同时重置其他item中某些view的属性.

**Comment by elfman** [comment]
你是想让recyclerview来帮你自动改变view属性？但这些不是应该由你来做的吗？在listview里你是通过什么方法完成的？

**Comment by qiangxi** [comment]
你还是没明白我的意思,我知道这些都是我自己做的,我的意思是在我改变某一个item时,同时重置其他item的状态,就像ListView中可以getChildCount(),然后遍历ListView的childView一样,哎,算啦,我已经找到解决方式了,谢谢!!!

**Comment by elfman** [comment]
recyclerview的机制跟listview不一样，不管数据有多少，recyclerview只会根据视图需要不断复用有限的几个itemview，所以不可能遍历childView的，超出屏幕范围的childView可能都不存在，已经被其他item复用了

**Comment by qiangxi** [comment]
ListView同样是复用有限的几个itemview

**Comment by elfman** [comment]
ListView是在getView时传一个convertView给你去复用，你可以不使用这个convertView，每次都重新生成一个View，也就不会复用了。RecyclerView将create与bind的过程分开，强制进行复用

**Comment by qiangxi** [comment]
不管二者是不是强制进行复用,ListView的view复用机制确实和RecyclerView一样,你不能因为ListView可以不强制使用convertView而说二者的复用机制不一样,这有失偏颇吧.
