### ISSUE TITLE
采用demo中多类型item实现方式无法同时显示一列和多列的数据类型

### ISSUE THREAD

**Issue by loganguo** [CymChad/BaseRecyclerViewAdapterHelper#526]
多种类型item方式无法同时显示一列和多列的情况。我需要展示的列表有两类数据，一类是每一行有一列数据，一种是每一行有两列数据。我使用的是demo中MultipleItemUse方式，但是列表显示出来却全部是两列数据。
需要实现类似下图的效果
![image](https://cloud.githubusercontent.com/assets/9315399/20348732/fa668782-ac41-11e6-88a3-fab40b80213f.png)
实际效果是
![image](https://cloud.githubusercontent.com/assets/9315399/20348815/6de6174a-ac42-11e6-8471-b750ff534f50.png)

数据模型继承了MultiItemEntity，item类型和layout也绑定了。spanSize设置为2并且
        final GridLayoutManager manager = new GridLayoutManager(getActivity(), 2);
        getRecyclerView().setLayoutManager(manager);
        getQuickAdapter().setSpanSizeLookup(new BaseQuickAdapter.SpanSizeLookup() {｝
都设置了

**Comment by loganguo** [comment]
出现这个问题的原因是，先设置了
`mRecyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));`
然后又设置了
```
final GridLayoutManager manager = new GridLayoutManager(getActivity(), 2);
        mRecyclerView.setLayoutManager(manager);
```
直接设置为GridLayoutManager问题解决。
请问这是为什么呢？@CymChad

**Comment by CymChad** [comment]
第一步
```java
GridLayoutManager manager = new GridLayoutManager(this, 2);
```
第二步
```java
multipleItemAdapter.setSpanSizeLookup(new BaseQuickAdapter.SpanSizeLookup() {
            @Override
            public int getSpanSize(GridLayoutManager gridLayoutManager, int position) {
                 // 如果需要一行一个你就返回2，如果需要一行两个的你就返回1，这样就可以达到你的效果了
                return data.get(position).getSpanSize();
            }
        });
```
返回的SpanSize就和布局中的权重属性差不多。

**Comment by CymChad** [comment]
你可以看下文档  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8D%E5%90%8C%E7%9A%84item%E7%B1%BB%E5%9E%8B

**Comment by loganguo** [comment]
已经看了文档了。但是我的需求有所不同。我的大部分的页面需要用到的布局是LinearLayoutManager，因此我把`mRecyclerView.setLayoutManager(manager);`相关的代码重构到了基类中，子类继承这样的基类从而避免每次都写一份代码。问题是，当子类需要显示GridLayoutManager时，需要重新给mRecyclerView.setLayoutManager一个GridLayoutManager。这时候就出现了我上面的问题。

请问为什么直接RecyclerView.setLayoutManager(mGridLayoutManager);可以使用，但是先
RecyclerView.setLayoutManager(mGridLayoutManager);然后再RecyclerView.setLayoutManager(mLinearLayoutManager);就失效呢？失效后的效果入最上面我的截图。

**Comment by CymChad** [comment]
重复setLayoutManager这个没有了解过，我要去看看源码。我建议，你可以设置一个标示来控制，或者在基类写方法来控制setLayoutManager，默认是设置Linear的，如果需要特殊设置就子类重写基类的setLayoutManager方法即可。

**Comment by loganguo** [comment]
好的，谢谢。那我先关闭了，要是有新的发现please comment back。
