### ISSUE TITLE
Enhancement: Enable drag and drop from more than one view

### ISSUE THREAD

**Issue by yitz-grocerkey** [CymChad/BaseRecyclerViewAdapterHelper#528]
For example:

```
mDraggableAdapter.enableDragItem(itemTouchHelper, R.id.row_id, true);
mDraggableAdapter.enableDragItem(itemTouchHelper, R.id.drag_handle, false);
```

This would enable long press on the row to start drag OR short press on the "handle"

**Comment by elfman** [comment]
We don't support enable drag and drop from more than one view now, but we will add it soon.

**Comment by elfman** [comment]
I have finished the code, but I don't want to commit it to the master branch, because it changes some of  the current API, it may cause some app who are using these API not working correctly.
I don't think it an urgent request, maybe I can add it in version3.
