### ISSUE TITLE
点击item里面的子控件删除该item出错

### ISSUE THREAD

**Issue by TuringHuang** [CymChad/BaseRecyclerViewAdapterHelper#533]
我给recyclerView设置了一个 recyclerView.addOnItemTouchListener(new OnItemChildClickListener()），绑定了recyclerView的item里面的一张图片，当点击的这个图片的时候，我想删除当前item,用的是adapter里面的remove(int position),但是程序直接闪退了，出错： java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:3).state:5

**Comment by CymChad** [comment]
你可以跟一下position

**Comment by CymChad** [comment]
#499

**Comment by CymChad** [comment]
有可能是因为你add了Head，你自己要处理一下

**Comment by CymChad** [comment]
有问题再提
