### ISSUE TITLE
自定义 加载更多布局

### ISSUE THREAD

**Issue by sandsboy** [CymChad/BaseRecyclerViewAdapterHelper#534]
加自定义的  无论什么布局  都无法设置 布局居中    而已 靠边的
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center_horizontal"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:layout_centerInParent="true"
            android:text="我自定义加载更多" />

        <ImageView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:gravity="center"
            android:src="@mipmap/ic_launcher" />
    </LinearLayout>
</FrameLayout>

**Comment by CymChad** [comment]
你的版本号是？

**Comment by CymChad** [comment]
你看下demo的加载方式

**Comment by sandsboy** [comment]
2.4.4    
   /*自定加载更多布局*/

        myARecyclerviewAdpter.setLoadingView(LayoutInflater.from(this).inflate(R.layout.myloadmoreview, null));
        ;

**Comment by CymChad** [comment]
你安装demo上面来加载就好了。你没有给父布局所以不会占满一行。
