### ISSUE TITLE
setNewData not working (version 2.6.1)

### ISSUE THREAD

**Issue by jameltheone** [CymChad/BaseRecyclerViewAdapterHelper#538]
Hi,

I was using version 2.6.0 and had these lines
`adapter.setNewData(mData);
adapter.removeAllHeaderView();
adapter.addHeaderView(getHeaderView());`

so as to refresh the data and the header.

But with the last version (2.6.1) it's not working anymore (I get back to 2.6.0 and with this version it's working).

Please, could you try to fix it?

Thank you

Edit:

Please notice, that the header and the data are not refreshed both.

**Comment by 1109993488** [comment]
Running the exception or what has not changed?

**Comment by jameltheone** [comment]
The text inside the recyclerView and in the header view are no longer updated (while they were in the previous versions 2.6.0 included). But there is not any exception at all.

**Comment by CymChad** [comment]
show your code

**Comment by CymChad** [comment]
you post your code, I open the issue
