### ISSUE TITLE
2.0版本的多次上拉加载怎么实现？

### ISSUE THREAD

**Issue by ping999** [CymChad/BaseRecyclerViewAdapterHelper#539]
如题，遍寻adapter源码也没找出，求助

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD 
请更新至最新版，这是文档。

**Comment by ping999** [comment]
引用2.1.3依赖，BaseQuickAdapter中没有loadMoreEnd/loadMoreComplete方法

**Comment by CymChad** [comment]
新版本的API改了，文档已经改了。

**Comment by CymChad** [comment]
我建议你升级到2.6

**Comment by CymChad** [comment]
新的版本功能更加强大，以及更加稳定。

**Comment by CymChad** [comment]
如果你不更新，可以去https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.1.3
下载demo源码查看。

**Comment by ping999** [comment]
github上的文档最新版是2.1.3，烦请有空时更新文档以助更多的人学习。thx




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年11月21日(星期一) 中午11:39
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "占文平"<1101558280@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 2.0版本的多次上拉加载怎么实现？ (#539)




我建议你升级到2.6

**Comment by CymChad** [comment]
replace VERSION_CODE with real version name such as 2.1.3 released in [Here](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases)

文档上是说，VERSION_CODE替换成版本号，比如2.3.3,版本号参照released列表
