### ISSUE TITLE
数据不足一页时，仍然显示“加载中”

### ISSUE THREAD

**Issue by loganguo** [CymChad/BaseRecyclerViewAdapterHelper#541]
如题当数据不满一页（20条）时，比如只有3条数据，应该只显示这3条数据。但是用的2.6.0库，不仅显示了这三条数据而且还显示“加载中”。请问如何处理呢？

我需要去掉“加载中”这一条，通过
```
getQuickAdapter().loadMoreComplete();
getQuickAdapter().loadMoreEnd();

```
并没有去掉，变成了“没有更多数据了”。

**Comment by CymChad** [comment]
数据不足一页时，setEnableLoadMore(false);,开启上拉加载调用setEnableLoadMore(true)
