### ISSUE TITLE
item侧滑删除OnItemSwipeListener回调方法onItemSwiped中的i是个负数

### ISSUE THREAD

**Issue by keluokeda** [CymChad/BaseRecyclerViewAdapterHelper#543]
![image](https://cloud.githubusercontent.com/assets/16809185/20509347/0bec6b38-b0a3-11e6-8545-36daae78110c.png)
如图所示，这个i应该是正数啊，表示已经移除的下标，现在用debug观察是个负数

**Comment by elfman** [comment]
clearView是用于重置view的状态以便于复用，此时view已经从Recyclerview中移除，不再拥有position。你需要position的值的话应该在onItemSwiped中使用。注释里已注明了的

**Comment by keluokeda** [comment]
@elfman 非常感谢
