### ISSUE TITLE
展开某item，收缩其它item

### ISSUE THREAD

**Issue by hxxxxxxxk** [CymChad/BaseRecyclerViewAdapterHelper#544]
使用BaseMultiItemQuickAdapter，我点击某个item展开了，怎么收缩其它item？就是有且只有一个item能展开，谢谢！

**Comment by elfman** [comment]
目前没实现这个功能，只能你自己遍历查找其它同级item，并逐个收缩了

**Comment by hxxxxxxxk** [comment]
随着子item展开收缩，item的数量是变化的，position也变了，咋遍历？

**Comment by elfman** [comment]
收缩了一个之后，下一个就是跟他同级的item啊。先获取parent位置，然后从上往下逐个收缩，直到遇到与parent同级的item。
另一个方法是你在parent里用个变量记录下已经展开的item，展开另一个item时就把上一个收缩了，这样应该不难做吧

**Comment by hxxxxxxxk** [comment]
@elfman 搞定了，非常感谢
