### ISSUE TITLE
BaseMultiItemQuickAdapter addFooterView 高度似乎不对

### ISSUE THREAD

**Issue by kafka0102** [CymChad/BaseRecyclerViewAdapterHelper#545]
使用一个简单的footer，比如一个高度为80dp的空的TextView，
但显示的高度只是文本的高度，也就是20多像素的样子。

**Comment by kafka0102** [comment]
测试BaseQuickAdapter是可以正常显示高度的

**Comment by CymChad** [comment]
你的加载方式是？

**Comment by CymChad** [comment]
#499

**Comment by kafka0102** [comment]
是这样的，我修改了BaseRecyclerViewAdapterHelper里的MultipleItemUseActivity，加了两行代码
`View footerView = getLayoutInflater().inflate(R.layout.footer_view, null);
        multipleItemAdapter.addFooterView(footerView);
        mRecyclerView.setAdapter(multipleItemAdapter);`
footer_view的内容是：
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_width="match_parent"
                android:text="xx"
              android:layout_height="80dp">
</TextView>
在HeaderAndFooterUseActivity可以看到高度为80的footer，但BaseRecyclerViewAdapterHelper只显示文本高度，也就是20多像素的样子。

**Comment by CymChad** [comment]
`getLayoutInflater().inflate(R.layout.head_view, (ViewGroup) mRecyclerView.getParent(), false);`
 这样加载，给它父布局才知道会显示原来设置的大小，要不然没有根据对象它就只会包裹内容。

**Comment by CymChad** [comment]
demo代码有写

**Comment by kafka0102** [comment]
理解了，多谢。
