### ISSUE TITLE
关于TextView的Spannable自定义部分字符串点击事件的自定义问题，例如@xxx 内容

### ISSUE THREAD

**Issue by woniu0936** [CymChad/BaseRecyclerViewAdapterHelper#546]
做评论的时候，一条评论里面可能有多个@xxx，而且整个item也有点击事件，这时候，不能写holder.addOnClickListener(R.id.textview),但是不写的话，事件会被SimpleOnItemClick覆盖，导致@XXX点击无效，请问针对这种场景，有相关的支持吗？

**Comment by AllenCoder** [comment]
目前针对Spannable还没有完美的解决办法，建议独立添加点击事件。后续会对这个功能进行扩展和完善

**Comment by woniu0936** [comment]
@AllenCoder 好的

**Comment by psv100** [comment]
用ClickableSpan 单独设置点击事件后，点击TextView 波纹会变成从中间发散开， 如果再在XML文件单独给TextView设置波纹效果，点击后会产生 TextView本身、从中间发散两种波纹效果，有木有什么解决办法额。 @AllenCoder

**Comment by CymChad** [comment]
#500 待优化
