### ISSUE TITLE
加载更多的时候，没有loadComplete()方法。

### ISSUE THREAD

**Issue by gitzzh111** [CymChad/BaseRecyclerViewAdapterHelper#547]
我是通过这种方式加载的jar包
    maven { url "https://jitpack.io" }
   依赖：compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.7'
在是这样的话，BaseQuickAdapter下，没有loadComplete()这个方法。
而在给的demo里面，是引入的library。这个时候就有loadComplete()这个方法。
为什么？怎么解决啊？

**Comment by CymChad** [comment]
这是2.6.0的api
