### ISSUE TITLE
recyclerview里面有多种条目，而且还需要不同条目之间能够自由拖拽，请问应该如何解决？

### ISSUE THREAD

**Issue by whb7762300** [CymChad/BaseRecyclerViewAdapterHelper#548]
自由拖拽继承BaseItemDraggableAdapter，不同条目继承BaseMultiItemQuickAdapter，请问该如何解决？

**Comment by elfman** [comment]
请参考[#312](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/312)

**Comment by elfman** [comment]
参照[#473](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/473)
