### ISSUE TITLE
设置监听方法setOnLoadMoreListener(this)自动回调加载更多怎么回事啊2.13

### ISSUE THREAD

**Issue by 2064135029** [CymChad/BaseRecyclerViewAdapterHelper#549]
@Override
    public void onLoadMoreRequested() {
       
        apiGetBusiness.loadNextPage();

    }

**Comment by CymChad** [comment]
推荐更新2.6.1，已经重构上拉加载，文档在wiki。
2.1.3的话自动回调是因为你没有设置pageSize（每页显示数量）。
