### ISSUE TITLE
ClickableSpan 和Item 事件冲突

### ISSUE THREAD

**Issue by VectorWen** [CymChad/BaseRecyclerViewAdapterHelper#552]
如果一个TextView 里面的内容有ClickableSpan 事件，还添加使用BaseViewHolder.addOnClickListener() 为这个TextView 添加点击事件，那么当点击含有ClickableSpan 的字体的时候就会触发两个点击事件。

注：如果使用TextView.setOnClickListener 添加的item 点击事件就不会出发两个点击事件。

**Comment by AllenCoder** [comment]
目前针对目前针对Spannable还没有完美的解决办法，建议独立添加点击事件。后续会对这个功能进行扩展和完善

**Comment by CymChad** [comment]
#500 待优化

**Comment by yangyiRunning** [comment]
请问ClickableSpan的点击事件和列表中item的点击事件互相冲突，怎么解决？
