### ISSUE TITLE
刷新数据后，添加头部java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0

### ISSUE THREAD

**Issue by xialei92** [CymChad/BaseRecyclerViewAdapterHelper#555]
刷新数据后执行以下代码，添加头部 报错：java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
@Override
	public void showNewComment(NewCommentBean data) {
		mAdapter.removeAllHeaderView();
		mAdapter.addHeaderView(getHeaderView(data));
	}

**Comment by CymChad** [comment]
版本号是？

**Comment by xialei92** [comment]
2.6.1

**Comment by 1109993488** [comment]
removeAllHeaderView和addHeaderView最好不要同时执行，同时执行可能会报另一个错。你的getHeaderView怎么写的？

**Comment by xialei92** [comment]
private View getHeaderView(NewCommentBean data) {
		View view = View.inflate(mContext, R.layout.header_new_comment, null);
		LinearLayout llNewMessage = (LinearLayout) view.findViewById(R.id.ll_new_message);
		AvatarView newMessageAvatar = (AvatarView) view.findViewById(R.id.avatar_view);
		TextView tvNewMessage = (TextView) view.findViewById(R.id.tv_new_message);
		newMessageAvatar.setRoundImageUrl(data.image_url);
		tvNewMessage.setText(String.format(getString(R.string.how_many_new_message), data.new_comment));
		return view;
	}
我尝试过在刷新前调用removeAllHeaderView，也是报同样的错误

**Comment by 1109993488** [comment]
你这个刷新是指的setNewData？showNewComment之前还做了什么操作？

**Comment by 1109993488** [comment]
建议你在初始化adapter之前addHeaderView，showNewComment再去更新headerView

**Comment by 1109993488** [comment]
可否贴个完整的adapter，和操作，数据操作部分可删除

**Comment by xialei92** [comment]
private void initRecyclerView() {
		recyclerView.setLayoutManager(new LinearLayoutManager(mContext));
		recyclerView.addItemDecoration(new SpacesItemDecoration(10));
		mAdapter = new MyAdapter(Collections.EMPTY_LIST);
		recyclerView.setAdapter(mAdapter);
		mAdapter.setOnLoadMoreListener(() -> {
			recyclerView.postDelayed(() -> {
                              ....
				mPresenter.loadmore();
			}, 200);
		});
@Override//上拉加载到数据
	public void showMoreDynamic(List<DynamicBean> list) {
		mAdapter.addData(list);
		mAdapter.loadMoreComplete();
	}

@Override//刷新获取到数据
	public void showDynamic(List<DynamicBean> list) {
		mAdapter.setNewData(list);
	}


	@Override//上拉没有数据
	public void loadEnd() {
		mAdapter.loadMoreEnd();
	}
@Override//下拉调用另外一个接口，有数据就添加头
	public void showNewComment(NewCommentBean data) {
		mAdapter.removeAllHeaderView();
		mAdapter.addHeaderView(getHeaderView(data));
	}
另外能告诉为什么不能同时调用removeAllHeaderView和addHeaderView吗？类似的错误在别的地方也有遇到过

**Comment by 1109993488** [comment]
如果有header，removeAllHeaderView会notifyItemRemoved；addHeaderView会notifyItemInserted；
2个一起调用的话mHeaderLayout还没消失就要添加，会重新回调onCreateViewHolder重新创建新的mHeaderLayout，由于内部mHeaderLayout引用的一个所以会报错。
你这样调试试
`
public void showNewComment(NewCommentBean data) {
        mAdapter.removeAllHeaderView();
        mAdapter.addHeaderView(getHeaderView(data));
        mAdapter.notifyDataSetChanged();
}
`
或者
`
private View mHeaderView;
    public void showNewComment(NewCommentBean data) {
        if(mHeaderView==null){
            mHeaderView = getLayoutInflater().inflate( head_view,(ViewGroup) mRecyclerView.getParent(), false);
            mQuickAdapter.addHeaderView(mHeaderView);
            mRecyclerView.smoothScrollToPosition(0);//滑动到顶部
        }
        ((TextView) mHeaderView.findViewById(R.id.tv)).setText(" header--"+System.currentTimeMillis());
    }
`
