### ISSUE TITLE
为什么我使用只能加载两页数据，第三页就不执行加载更多了

### ISSUE THREAD

**Issue by JianJianZhang** [CymChad/BaseRecyclerViewAdapterHelper#556]
adapter.openLoadMore(count);
 adapter.setOnLoadMoreListener(this);
然后在加载更多的监听中，把页数增加一，但是好像加载第二页后，就没有执行加载更多的方法了。请问这是什么问题啊？

**Comment by CymChad** [comment]
请更新最新的版本，上拉已经重构。具体使用查看demo和文档

**Comment by JianJianZhang** [comment]
新的上拉加载这个几个参数，是不是下面的意思？分页加载我怎么知道总共有多少页了？

//这个是不是总共加载多少页？？？   
private static final int TOTAL_COUNTER = 18;
//这个不是每页加载6条数据
private static final int PAGE_SIZE = 6;
//延时1秒加载
private int delayMillis = 1000;
//当前是第几页吗？？？
private int mCurrentCounter = 0;

**Comment by CymChad** [comment]
这个判断规则看你自己，不一定要按demo的来。
