### ISSUE TITLE
2.4.5升级到2.6.1 addFooterView 没有替换底部的“没有更多数据”

### ISSUE THREAD

**Issue by lianghuiyong** [CymChad/BaseRecyclerViewAdapterHelper#558]
之前用的2.4.5版本的，现在升级到了2.6.1版本，怎么替换不了呢？求告知下，谢谢！

**Comment by CymChad** [comment]
不需要addFooterView了，使用方式你可以看demo和文档

**Comment by CymChad** [comment]
他的原理全部把（加载中、加载失败、没有更多数据）放在一个layout里面去了，只是显示和隐藏。
