### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by mpxl** [CymChad/BaseRecyclerViewAdapterHelper#56]
在Android studio中创建了一个新的项目，然后按照操作步骤创建adapter，运行时异常
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72330Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:app:prepareComGithubCymChadBaseRecyclerViewAdapterHelperV178Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources
AAPT err(Facade for 758995742): libpng error: Not a PNG file
Error:Execution failed for task ':app:mergeDebugResources'.
> Some file crunching failed, see logs for details

请问这是怎么回事？
另外我把github上down下的项目，按照上述操作，运行也是异常

**Comment by CymChad** [comment]
你是你的项目图片问题，不是adapter的问题，你看提示：Not a PNG file

**Comment by mpxl** [comment]
我把github上down下的项目，按照上述操作，运行也是异常
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareBaseRecyclerViewAdapterHelperMasterMaterialSpinner105UnspecifiedLibrary UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2321Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72321Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2321Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72330Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42330Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2321Library UP-TO-DATE
:app:prepareComGithubCymChadBaseRecyclerViewAdapterHelperV178Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources

**Comment by CymChad** [comment]
demo都运行不了吗？

**Comment by mpxl** [comment]
app下的build.gradle修改成
   dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    //compile project(path: ':library')
    compile project(':material-spinner-1.0.5')
    compile 'com.android.support:design:23.2.1'
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.7.8'
  }
整个项目下的build.gradle修改成
allprojects {
        repositories {
                jcenter()
                maven { url "https://jitpack.io" }
            }
    }
这样修改后，就不能运行了

**Comment by mpxl** [comment]
请问这到底怎么回事？急求呀

**Comment by CymChad** [comment]
你加群558178792
