### ISSUE TITLE
关于2.6.1的自动 loadmore 未满一页时，显示loadend的解决方案参考

### ISSUE THREAD

**Issue by tysheng** [CymChad/BaseRecyclerViewAdapterHelper#560]
现在的方案，可视的Item，在不滑动的情况下，也是会loadmore的，这对小数据(即未满一页)的情景并不友好，提供一个折中的解决方案。

setNewData的时候关闭loadmore，完成以后检查是否满一页，如超过一页，则打开。

参考如下:
https://gist.github.com/tysheng/fee8066031b0f62c39d827f18af0ae07

**Comment by 1109993488** [comment]
如果你只是想显示小数据你可以不设置setOnLoadMoreListener监听，这样就不会开启加载更多。如果这个页面是要分页加载的话你可以判断下获取到的数据是否小于一页，如果小于一页就调用loadMoreEnd()，否则addData(list);loadMoreComple();

**Comment by tysheng** [comment]
@1109993488 理论上是这样没错，但是有些特殊场景，比如说搜索，返回结果不定，但是我们根据返回值也得做好loadMore ，loadEnd的处理，现在这个机制，对于这种情景就不太好，第一次setNewData后自动会执行下一次的loadMore，导致出现loadEnd，甚至用户都没有去动他。

**Comment by 1109993488** [comment]
在不满一屏的情况下你能知道已经没数据了，还是不清楚需要再次请求服务器获取下一页数据？

**Comment by tysheng** [comment]
@1109993488 其实我就是提供一个 不满一屏时不显示```loadEnd```的方法，未满一屏的时候，用户已经知道到底了，不用显示End的view

**Comment by 1109993488** [comment]
```
setNewData(list);
if(没有更多数据){
    loadMoreEnd();
}
```
这样就不会回调加载更多，这样能满足你的需求吗？
如果你觉得不满一屏(就1条数据)下面不想显示endView的话，可以提供一个loadMoreEnd(boolean)的方法参数true为隐藏endView

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.2'  已更新，提供一个loadMoreEnd(boolean)的方法参数true为隐藏endView

**Comment by yubaokang** [comment]
@tysheng loadMoreEnd(true) 之后  loadMore的View是不会显示了，但是自动加载下一页也没有了；
现在需要的是当不满一屏幕的时候，去静默加载下一页，并且不显示loadmore的view。
用这个可以做到吗？

**Comment by tysheng** [comment]
@yubaokang 不满一屏还加载下一页？不过这是很简单的事，不用考虑框架

**Comment by yubaokang** [comment]
@tysheng 我提了个问题，你看看，可能理解错我的意思了
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/781

**Comment by yubaokang** [comment]
@tysheng 如果按照这样做的话：如果每个item的高度很小，显然是有问题的-->不会去自动加载第二页，

**Comment by tysheng** [comment]
@yubaokang 你可以摒弃原来的自动加载功能，根据网络请求返回结果来判断，无非就是一个footerview

**Comment by tysheng** [comment]
@yubaokang 可以重写loadview里的方法，来控制loadmore view
