### ISSUE TITLE
最新的上拉加载版本，需要知道一共加载多少页吗？

### ISSUE THREAD

**Issue by JianJianZhang** [CymChad/BaseRecyclerViewAdapterHelper#561]
看了一下demo,里面判断加载结束的方法：是根据当前一共加载多少条目，是否大于总共的条目判断是否加载完毕的。分页加载怎么需要知道一共加载多少条数据吗？

**Comment by CymChad** [comment]
这个不一定，如何判断是否有下一页，完全由开发者来定义的。demo只是做了一种方式的判断演示而已。
