### ISSUE TITLE
2.6.1 自定义Footer点击事件有时触发,有时不触发.

### ISSUE THREAD

**Issue by liaolintao** [CymChad/BaseRecyclerViewAdapterHelper#562]
问题现象描述: 每次点击自定义的Footer,都会显示pressed状态, 但是定义的onCLick事件却不是每次都触发了.( 之前用的2.0.0 版, 无此问题)

可能的原因: SimpleClickListener 类中对footer的事件进行了拦截, 正在分析中.

**Comment by tysheng** [comment]
是的，我也有这个问题，header中设置的onClick 很难触发

**Comment by liaolintao** [comment]
有问题的,将SimpleClickListener.java回滚 2.0.0版的, 等待作者解决.

**Comment by AllenCoder** [comment]
已收到反馈，预计下周更正解决

**Comment by CymChad** [comment]
#500 待优化
