### ISSUE TITLE
BaseMultiItemQuickAdapter

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#564]
如果在使用多布局的时候，我这两个值不是固定的
![image](https://cloud.githubusercontent.com/assets/7565399/20666804/fd79a040-b5a0-11e6-92ea-d2e25d0a9737.png)
是不是就没法实现多布局。
想实现一个聊天界面的效果，用用户ID来区别发送方和接收方。
但感觉这样不行，聊天的时候有一方的用户的ID不是固定的，

**Comment by tysheng** [comment]
自己在 ```addData()``` 前先判断一下，或者弄一个wrapped bean

**Comment by CymChad** [comment]
只是同一个用户ID一致就可以了。

**Comment by wuzhaohui026** [comment]
已经解决了
