### ISSUE TITLE
关于加载更多失败 2.6.1

### ISSUE THREAD

**Issue by hongtaoStudio** [CymChad/BaseRecyclerViewAdapterHelper#565]
加载失败后，重新加载，再次加载失败，列表没有滑动至底部，使用 `StaggeredGridLayoutManager`，调用 `mAdapter.loadMoreFail();`效果如下：
<img src="http://7xtixn.com1.z0.glb.clouddn.com/load_more_fail_click.gif" width="50%" height="50%">

**Comment by 1109993488** [comment]
你的加载中和加载失败高度不一致
