### ISSUE TITLE
.setEmptyView()不生效

### ISSUE THREAD

**Issue by liuyuttkx** [CymChad/BaseRecyclerViewAdapterHelper#566]
DeGug 已经走了.setEmptyView(),但没有生效. 是自定义view , mEmptyView = getLayoutInflater().inflate(R.layout.empty_view_my_fans, mRecycler, false);
 mAdapter.setEmptyView(mEmptyView);
请问有没有人遇,到过

**Comment by CymChad** [comment]
你的版本是？

**Comment by liuyuttkx** [comment]
2.4.4

**Comment by CymChad** [comment]
升级到最新版本

**Comment by CymChad** [comment]
还有问题吗？

**Comment by CymChad** [comment]
有问题在提，我先关闭了。
