### ISSUE TITLE
再viewpage中使用  Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by jttttttttttttt** [CymChad/BaseRecyclerViewAdapterHelper#569]
再viewpage中使用  Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by jttttttttttttt** [comment]
好像是我page都extend 同一个fragment   所以报了这个错   现在解决了  要懒加载fragment 才不会多次请求调用这个接口

**Comment by jttttttttttttt** [comment]
还是没解决。。。

**Comment by jttttttttttttt** [comment]
viewpage中加载出现情况：public void setLoadDataEmpty(int number, boolean isCanLoadMoreAgain) {
        if (number == 0) {
            isCanLoadMore = false;
            tableAdapter.setEmptyView(getEmptyView());
        } else {
            isCanLoadMore = isCanLoadMoreAgain;
            if (!isCanLoadMore)
                tableAdapter.loadMoreEnd();
            else
                tableAdapter.loadMoreComplete();
        }
    }

public LayoutInflater getLayoutInflater() {
        if (inflater == null)
            inflater = LayoutInflater.from(getCContext());
        return inflater;
    }

    public View getEmptyView() {
        if (emptyView1 == null) {
            emptyView1 = getLayoutInflater().inflate(R.layout.view_empty, (ViewGroup) rv.getParent(), false);
        }
        return emptyView1;
    }

当我重新加载，数量再次是0的情况下再设置setEmptyView 会报错  重新走到tableAdapter.setEmptyView(getEmptyView());

**Comment by 1109993488** [comment]
初始化的时候设置一次tableAdapter.setEmptyView(getEmptyView());
当number == 0时调用setNewData(null)就会显示emptyView

**Comment by jttttttttttttt** [comment]
是的   但是我加载失败数据为0时  也是走setEmptyView  如果这一步就set  万一加载失败还是会出错吧

**Comment by jttttttttttttt** [comment]
还是现在加载失败数据为0时   直接loadMoreFail() 求助

**Comment by jttttttttttttt** [comment]
tableAdapter.setEmptyView(getEmptyView());

if (tableLst.size() == 0) {
                    isCanLoadMore = false;
                    tableAdapter.setNewData(null);
                } else {
                    setLoadDataEmpty(tableLst.size(), tableInfo.getResult().isCanloadMore());
                }

在viewpage里面这样子并不好使  左右滑动，重新加载又走了一遍 还是会报java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

现在我在
@Override
    public void onDestroyView() {
        if (messageLst != null)
            if (messageLst.size() == 0)
                if (messageAdapter != null) {
                    mInited = false;
                    messageAdapter.removeEmptyView();
                }
        super.onDestroyView();
    }

只要是已经setEmptyView,在走onDestroyView的时候  我手动去 removeAllView();  然后再次加载的时候重新setEmptyView

**Comment by 1109993488** [comment]
你onCreateView里重新创建布局了？

**Comment by 1109993488** [comment]
你的ViewPager中Fragment可能是重新调onCreateView，然后你又重新创建了新的Adapter，EmptyView还在之前的Adapter布局中，解决方法很多种。

**Comment by jttttttttttttt** [comment]
是的  重走了onCreateView  又创建了新的adapter 我再ondestryView里面remove  发现各种刷新  各种崩  是不是重新创建的时候  判断是否为空  就好了？？

**Comment by 1109993488** [comment]
```
@Override
    public void onDestroyView() {
        super.onDestroyView();
        emptyView = null;
    }
```
这个不能解决？

**Comment by 1109993488** [comment]
你可以看下https://github.com/hxy493045049/MyApplication2这个demo

**Comment by CymChad** [comment]
@jttttttttttttt 问题解决没？

**Comment by jttttttttttttt** [comment]
解决了  viewpage左右滑的时候 不重新加载了 或者吧empty置空

**Comment by jttttttttttttt** [comment]
谢谢大腿

**Comment by CymChad** [comment]
ok，感谢你的使用。
