### ISSUE TITLE
左右滑动出现一个布局，布局完全出现后，不进行滑动，能不能给一点思路？

### ISSUE THREAD

**Issue by yangchun9525** [CymChad/BaseRecyclerViewAdapterHelper#570]
如题，具体类似于qq左滑出现删除，置顶的功能。

**Comment by CymChad** [comment]
悬浮功能：https://github.com/oubowu/PinnedSectionItemDecoration
侧滑功能：https://github.com/daimajia/AndroidSwipeLayout

**Comment by CymChad** [comment]
https://github.com/mcxtzhang/SwipeDelMenuLayout

**Comment by CymChad** [comment]
https://github.com/bingoogolapple/BGASwipeItemLayout-Android
