### ISSUE TITLE
setemptyview导致内存溢出

### ISSUE THREAD

**Issue by hxy493045049** [CymChad/BaseRecyclerViewAdapterHelper#573]
问题如题
具体描述如下
为了定位问题,我写了个demo

activity
1.简单的activity,布局中只有一个viewpager,属性match_parent
2.viewpager的adapter是FragmentPagerAdapter  (support v4版本的fragment)
3.在adapter中构造了3个简单的fragment

fragment
1.fragment布局中只有一个recycleview
2.recycleview的adapter是继承BaseQuickAdapter<bean,baseHolder>,内部实现全是空
3.设置好adapter的相关属性和recycleview相关属性后,在recycleview的setadapter之前,
调用了adapter的setEmptyView(),  view是一个普通的linearlayout,内部只有一张图片
4.启动app

报内存溢出问题,必现
如果注释setEmptyView,则能正常运行
另外,如果不用viewpager,单独使用fragment,并设置setEmptyView,是没问题的

没有仔细看内存的profile,但从studio中的内存监控中能发现内存有不正常的抖动

**Comment by CymChad** [comment]
版本号？

**Comment by 1109993488** [comment]
你图片很大吧，你不setEmptyView 你直接初始化用变量保存emptyView也会报内存溢出的

**Comment by hxy493045049** [comment]
图片不大
测试版本是2.6.1,我尝试在2.6.2的demo做测试,也有这个情况
我做了一个test项目
[git@github.com:hxy493045049/MyApplication2.git](url)
可以下载看看具体情况

**Comment by 1109993488** [comment]
```
public View getEmptyView() {
        return View.inflate(mContext, R.layout.empty_view, mSwipeOnly);
}
```
要改成下面的
```
public View getEmptyView() {
        return LayoutInflater.from(mContext).inflate( R.layout.empty_view, mSwipeOnly,false);
}
```

**Comment by hxy493045049** [comment]
好的  很感谢
