### ISSUE TITLE
RecyclerView addOnItemTouchListener OnItemClickListener  自定义控件的点击事件不能触发

### ISSUE THREAD

**Issue by githubityu** [CymChad/BaseRecyclerViewAdapterHelper#574]
我在MultiImageView 中的imageview设置了点击事件，然后RecyclerView addOnItemTouchListener OnItemClickListener   imageview的点击事件就不能触发了，注释掉addOnItemTouchListener 该方法就可以触发了

**Comment by AllenCoder** [comment]
因为OnItemClickListener 需要消费掉recyclerview的touch事件，imageview作为子控件需要绑定点击事件，可以在convert里面根据提供的API注册绑定，即可在子控件点击事件里面得到相应的回调
