### ISSUE TITLE
上拉加载 2.2.0版本

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#575]
为什么会一打开页面就开始同时加载第二页的内容？

**Comment by CymChad** [comment]
贴出你的代码，和布局。

**Comment by CymChad** [comment]
建议升级到最新版本，重构了上拉加载

**Comment by wuzhaohui026** [comment]
![image](https://cloud.githubusercontent.com/assets/7565399/20823174/d000354a-b88c-11e6-952a-82544f680090.png)
![image](https://cloud.githubusercontent.com/assets/7565399/20823175/d3f3a24a-b88c-11e6-9620-fab40780dcab.png)

![image](https://cloud.githubusercontent.com/assets/7565399/20823176/d9c8abb6-b88c-11e6-8700-8014b863ce39.png)
![image](https://cloud.githubusercontent.com/assets/7565399/20823179/de65e558-b88c-11e6-8a62-b8a7ad0d2d80.png)

**Comment by CymChad** [comment]
你布局有没有嵌套scrollview？

**Comment by wuzhaohui026** [comment]
没有啊

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:id="@+id/home_fragment_layout"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:orientation="vertical">

    <include layout="@layout/main_toolbar_layout"/>

    <LinearLayout
        android:layout_marginTop="?attr/actionBarSize"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">


        <android.support.v4.widget.SwipeRefreshLayout
            android:id="@+id/swipRefresh_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginLeft="12dp"
            android:layout_marginRight="12dp">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/events_recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
        </android.support.v4.widget.SwipeRefreshLayout>
    </LinearLayout>
</FrameLayout>

**Comment by wuzhaohui026** [comment]
没有啊

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:id="@+id/home_fragment_layout"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:orientation="vertical">

    <include layout="@layout/main_toolbar_layout"/>

    <LinearLayout
        android:layout_marginTop="?attr/actionBarSize"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">


        <android.support.v4.widget.SwipeRefreshLayout
            android:id="@+id/swipRefresh_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginLeft="12dp"
            android:layout_marginRight="12dp">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/events_recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
        </android.support.v4.widget.SwipeRefreshLayout>
    </LinearLayout>
</FrameLayout>

**Comment by CymChad** [comment]
你先更新至最新版本，因为现在这个版本就算有问题也无法解决。

**Comment by CymChad** [comment]
具体使用可以看文档，和demo都已经更新到最新版本了，有问题再提。
