### ISSUE TITLE
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by AngelBo** [CymChad/BaseRecyclerViewAdapterHelper#577]
针对这个问题，只有极少部分手机使用才会有这种现象。是因为每次切换频繁导致的这个问题，解决办法：我看stackfllows上面有很多都说要对RecyclerView设置android：animationlayoutChanges = true，才可以解决bug,但是我设置了然并卵，只能知己慢慢找原因，最后我每次在setNewData方法后面加上notifyDataChanged就会减少相应的报错几率，但是问题根本诶有得到解决，最后只能研究布局。那个图我贴不上上，尽量减少对recyclerView父布局的属性。具体情况请问我：QQ:70637935

**Comment by CymChad** [comment]
![700072394c8f00bf172d27fdeafa8f27](https://cloud.githubusercontent.com/assets/7698209/20822541/624a06f8-b886-11e6-8f51-1220005d0d31.jpg)

**Comment by CymChad** [comment]
留档便于查询

**Comment by AngelBo** [comment]
最后解决办法：     android:focusableInTouchMode="true"在recyclerView布局里面加这个属性就OK了

**Comment by Drolmen** [comment]
@AngelBo 大兄弟，666啊，为什么会这样啊，你知道吗？

**Comment by Dpuntu** [comment]
以上答案都不能解决问题啊

**Comment by h-zhouwenjun** [comment]
不能解决问题

**Comment by hl1716** [comment]
打扰了

**Comment by Darius-Chan** [comment]
我没有设置focusableInTouchMode，和animationlayoutChanges ，但是我在所有的setNewData、addData和设置header、footer、emptyview后面都加上了notityDataSetChanged()就解决了。。。也不知道为什么

**Comment by Liberations** [comment]
数据变化及时调用 notifyDataSetChanged
