### ISSUE TITLE
2.2.0如何开始上拉加载更多

### ISSUE THREAD

**Issue by sword30021** [CymChad/BaseRecyclerViewAdapterHelper#578]

**Comment by sword30021** [comment]
setEnableLoadMore(boolean);
这个方法没找到

**Comment by CymChad** [comment]
这是2.6.0的API

**Comment by sword30021** [comment]
那么2.2.0怎么做上拉加载更多？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.2.0  你可以下载demo源码，查看，不过还是建议你使用最新版。
