### ISSUE TITLE
为了解决itemView子视图的match_parent失效问题时重写onCreateViewHolder闪退

### ISSUE THREAD

**Issue by 2064135029** [CymChad/BaseRecyclerViewAdapterHelper#579]
//    @Override
    public BaseViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        //LayoutInflater mInflater = ;
        View view = LayoutInflater.from(mContext).inflate(R.layout.item_list_service_apply, parent, false);
        BaseViewHolder baseViewHolder = new BaseViewHolder(view);
      //  return baseViewHolder;
        return super.onCreateViewHolder(parent, viewType);
    }

**Comment by 2064135029** [comment]
知道闪退是怎么回事了，是mContext为null  ，但是item里边的控件macth_parent怎么解决啊？

**Comment by CymChad** [comment]
match_parent 失效？

**Comment by CymChad** [comment]
不建议重写`onCreateViewHolder`方法，默认是根据item的原始宽高来的。
有问题再提
