### ISSUE TITLE
在viewpager中使用,layoutInflate报空指针

### ISSUE THREAD

**Issue by hxy493045049** [CymChad/BaseRecyclerViewAdapterHelper#580]
有点尴尬,都是我的问题
不知道是我没用好还是什么的

描述如下
viewpager中嵌套3个fragment
在fragment中刷新数据后直接就崩溃了
版本2.6.1
详情看测试代码
https://github.com/hxy493045049/MyApplication2.git
3个fragment,第一个下拉能添加数据,然后直接崩溃

**Comment by hxy493045049** [comment]
好吧,我再次仔细的查看了下....
使用这个adapter库的话,不能再xml使用<view>控件....

**Comment by hxy493045049** [comment]
额...

**Comment by 1109993488** [comment]
```
    <view
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="#999999" />
```
view改为View
