### ISSUE TITLE
addHeaderView添加头部后 addData()出现问题

### ISSUE THREAD

**Issue by psv100** [CymChad/BaseRecyclerViewAdapterHelper#585]
不添加头部的时候， addData()不会出现问题；
  当添加了头部之后，问题来了，形象的说: 如果有一条新的数据要addData，就会发现新item展现的信息实际是旧数据的最后一条；  再添加新数据，item会在倒数第二（就是实际是旧数据的item上面）插入。将RecyclerView拉到底端然后添加新数据时一定出现这种情况。

**Comment by CymChad** [comment]
版本号？

**Comment by CymChad** [comment]
更新至最新版本，有问题再提

**Comment by psv100** [comment]
暂时更新到2.5.0，2.6新的加载还没琢磨透。现在那个问题还是存在，暂时用 数据源添加新数据，然后setNewData的办法了，这样不会出现上面的情况。弄懂之后更新到2.6我再试试 @CymChad

**Comment by CymChad** [comment]
恩，好的，有问题再提。麻烦了。
