### ISSUE TITLE
v2.2 RecyclerView的显示问题

### ISSUE THREAD

**Issue by kealsoul** [CymChad/BaseRecyclerViewAdapterHelper#586]
先为RecyclerView的item添加android:foreground="?attr/selectableItemBackground"，设置水波纹事件。
然后对RecyclerView的item长按后轻滑动一点，item将会处于选中状态，水波纹不会消退。
重复对每一item如此，每一个item都被选中，水波纹效果得不到消退。
![img_0011](https://cloud.githubusercontent.com/assets/5879400/20865375/d0c1472a-ba4a-11e6-8ada-9dd59e9058cf.JPG)

**Comment by CymChad** [comment]
更新最新版

**Comment by CymChad** [comment]
最新版本有问题再提

**Comment by kealsoul** [comment]
好
