### ISSUE TITLE
关于动画重复加载

### ISSUE THREAD

**Issue by wjbd** [CymChad/BaseRecyclerViewAdapterHelper#587]
我对adapter有如下设置
adapter.openLoadAnimation(BaseQuickAdapter.SCALEIN);
adapter.isFirstOnly(true);
正常不锁屏的时候是好好地，动画只加载了一次，但是当我锁屏以后重新打开，动画会再一次加载。体验很不好

**Comment by wjbd** [comment]
当我把APP放到后台，再重新打开的时候，动画也同样会重新加载一次

**Comment by wjbd** [comment]
已经解决，是我在onResume中刷新了

**Comment by CymChad** [comment]
👍
