### ISSUE TITLE
分隔符问题

### ISSUE THREAD

**Issue by hxy493045049** [CymChad/BaseRecyclerViewAdapterHelper#588]
recycleview使用decoration做分隔符
然后在自定义decoration中,在绘制分隔符的时候会减去footer或者header
但是使用了baseadapter后,尾部的分隔符还存在

追踪源码发现,adapter的loadview是不算在尾部或者头部的,而是在getItemCount()中额外添加了一个this.getLoadMoreViewCount(),而且这个this.getLoadMoreViewCount()是私有的方法

有什么办法能去掉loadview的分割线呢?

**Comment by CymChad** [comment]
你在自定义的decoration里面处理一下就好了。

**Comment by CymChad** [comment]
无论是头部还是尾部原理都是添加一个item，然后无论后续添加多少个头部还是尾部，其原理都是在这个item里面的layout上addView。
