### ISSUE TITLE
关于增加侧滑栏，以及多类型拖动支持。

### ISSUE THREAD

**Issue by MatchlessBrother** [CymChad/BaseRecyclerViewAdapterHelper#591]
对于侧滑和多类型拖动我其实就是一个小白，只是想去挑战一下。楼主能否给予帮助的指导一下方向，如果能改好，我也想贡献一下代码！谢谢

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/570

**Comment by CymChad** [comment]
目前是支持多类型的，只是限制了不同类型的item不能相互拖动替换

**Comment by MatchlessBrother** [comment]
Thank you very much for your reply.
Do you write the framework can have a direct modification of the way? 
Because I want to start with your BaseRecyclerViewAdapterHelper framework.


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年12月6日(星期二) 上午10:34
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "枣foreverWY "<1172246321@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 关于增加侧滑栏，以及多类型拖动支持。 (#591)




Closed #591.

**Comment by MatchlessBrother** [comment]
侧滑有了突破口了，是这样的，我这边的拖动大概有8种类型，但是要求彼此之间可以相互拖动，请问这个怎么实现？你说的可以自己扩展，请问有这个库扩展的引导文章吗？谢谢

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0%E6%8B%96%E6%8B%BD%E3%80%81%E6%BB%91%E5%8A%A8%E5%88%A0%E9%99%A4   这个文档有互相拖拽的解决方案
