### ISSUE TITLE
Best way to tint the Image view onclickitem click inside the Adapter?

### ISSUE THREAD

**Issue by LOG-TAG** [CymChad/BaseRecyclerViewAdapterHelper#592]
any samples available to tint the image view easily inside the item ? like how .setVisible(...) works!

**Comment by tysheng** [comment]
create your own viewHolder, and rewrite the adapter.

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Use-Custom-BaseViewHolder @tysheng Thank you for your answer
