### ISSUE TITLE
怎么实现长按伸缩分组子项item，实现所有本类子项item的checkbox控件的显示隐藏

### ISSUE THREAD

**Issue by zombiu** [CymChad/BaseRecyclerViewAdapterHelper#593]
想在这里实现批量删除功能，但是不知道该怎么做！

**Comment by elfman** [comment]
expand这个函数是由你来调用的，你可以绑定个长按事件来执行这个函数。

**Comment by zombiu** [comment]
@elfman  大神你好 这是我某一部分的代码`case TYPE_CHILD:
                //获取child对象
                final MyFocusChildBean childBean = (MyFocusChildBean) multiItemEntity;
                //给view填充内容
                baseViewHolder.setImageResource(R.id.imageView_item_icon,childBean.getResId());
                baseViewHolder.setText(R.id.textView_item_username,childBean.getUsername());
                baseViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                            ToastUtils.show(mContext, childBean.getUsername(), 1);

                    }
                });
                baseViewHolder.itemView.setOnLongClickListener(new View.OnLongClickListener() {
                    @Override
                    public boolean onLongClick(View view) {
                        displayCheckBox();
                        return false;
                    }
                });
                break;
        }
    }

    private void displayCheckBox() {
        for (BaseViewHolder holder : ) {

        }
    }`
如你所见，我在这里不知道通过什么方法获得该组子项下的item的对象来设置item上面view的显示隐藏

**Comment by elfman** [comment]
AbstractExpandableItem有个getSubItem来获取改组子项啊

**Comment by zombiu** [comment]
@elfman  大神 我继承的是BaseMultiItemQuickAdapter<MultiItemEntity>，是不是就不行了，需要修改代码，继承AbstractExpandableItem

**Comment by elfman** [comment]
这个不冲突的，你应该先看下demo里ExpandableItem的用法[ExpandableUseActivity.java](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ExpandableUseActivity.java)

**Comment by zombiu** [comment]
@elfman  大神，冲突很大啊，因为我现在用的是伸缩分组+子项grid布局，比demo里面的复杂很多，现在虽然实现了布局，但是长按显示该组子项所有item上面的checkbox这个要求没实现，希望大神能帮我解惑！

**Comment by zombiu** [comment]
@CymChad  大神，我该如何在br框架下实现此种效果，请指点我下！

**Comment by elfman** [comment]
我都不知道你的难点和疑问在哪里，怎么帮你解决？

**Comment by elfman** [comment]
一个思路，在bindview中判断是否需要显示checkbox，在item里用个变量记录checkbox的状态，checkbox被点击时修改此变量，在完成删除时检查所有子项的此变量，以决定删除哪些元素。在displayCheckBox里调用notifyDataSetChanged重新bind所有view。

**Comment by zombiu** [comment]
@elfman  大神，如果我长按子项item，怎么实现显示该组所有子项的item上的checkbox

**Comment by zombiu** [comment]
`public class FocusExpandableItemAdapter extends BaseMultiItemQuickAdapter<MultiItemEntity> {
    public static final int TYPE_GROUP = 4;
    public static final int TYPE_CHILD = 1;
    public FocusExpandableItemAdapter(List<MultiItemEntity> data) {
        super(data);
        //设置类型和相应的布局
        addItemType(TYPE_GROUP, R.layout.item_recyclerview_focus_group);
        addItemType(TYPE_CHILD, R.layout.item_recyclerview_focus_child);
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int positions) {
        super.onBindViewHolder(holder, positions);
    }

    @Override
    protected void convert(final BaseViewHolder baseViewHolder, MultiItemEntity multiItemEntity) {
        switch (baseViewHolder.getItemViewType()) {
            case TYPE_GROUP:
                //获取Group对象
                final MyFocusGroupBean groupBean = (MyFocusGroupBean) multiItemEntity;
                //给view填充内容
                baseViewHolder.setImageResource(R.id.iv_item_group,groupBean.getResId());
                baseViewHolder.setText(R.id.tv_item_group,groupBean.getTitle());
                baseViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        int pos = baseViewHolder.getAdapterPosition();
                        //设置recyclerView收缩展开及图片切换
                        if (groupBean.isExpanded()) {
                            collapse(pos);
                            baseViewHolder.setImageResource(R.id.iv_item_arrowdown,R.mipmap.icon_more_gray);
                        }else {
                            expand(pos);
                            baseViewHolder.setImageResource(R.id.iv_item_arrowdown,R.mipmap.icon_down_arrow_gray);
                        }
                    }
                });
                break;
            case TYPE_CHILD:
                //获取child对象
                final MyFocusChildBean childBean = (MyFocusChildBean) multiItemEntity;
                //给view填充内容
                baseViewHolder.setImageResource(R.id.iv_face,childBean.getResId());
                baseViewHolder.setText(R.id.textView_item_username,childBean.getUsername());
                baseViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                            ToastUtils.show(mContext, childBean.getUsername(), 1);

                    }
                });
                baseViewHolder.itemView.setOnLongClickListener(new View.OnLongClickListener() {
                    @Override
                    public boolean onLongClick(View view) {
                        displayCheckBox();
                        ToastUtils.show(mContext,"长按tosat",Toast.LENGTH_SHORT);
                        LogUtils.e("-->>我的关注适配器" + getData().size());
                        return true;
                    }
                });

                break;
        }
    }

    private void displayCheckBox() {

    }
}
`
@elfman  大神 这是完整代码！

**Comment by elfman** [comment]
我上面说了啊，在convert中添加一个判断是否需要显示子项的checkbox，在你的displayCheckbox函数中让上述判断为真，然后调用notify系列的接口刷新所有item。

**Comment by zombiu** [comment]
谢谢你大神 @elfman  按照你说的成功了！
