### ISSUE TITLE
how to get the BaseViewHolder helper instance in activity onItemChildClick

### ISSUE THREAD

**Issue by LOG-TAG** [CymChad/BaseRecyclerViewAdapterHelper#594]
```
 @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                super.onItemChildClick(adapter, view, position);
                switch (view.getId()) {

                  
                    case R.id.tweetAvatar:
                        Toast.makeText(RecyclerClickItemActivity.this, "The " + Integer.toString(position)+" tweetAvatar  is clicked", Toast.LENGTH_SHORT).show();
                        break;
                    case R.id.tweetName:
                        Toast.makeText(RecyclerClickItemActivity.this, "The " + Integer.toString(position)+" 

//      BaseViewHolder helper=(BaseViewHolder) mRecyclerView.getChildViewHolder(view); Toast.LENGTH_SHORT).show();
                        break;
                    default:
                        break;
                }
```
I want BaseViewHolder helper instance to get other the view from item 

ex: click on tweet name I should get bitmape drawable of  tweetAvatar or any image view form the item !!

or 

simply how do this helper.getView(R.id.tweetAvatar)); in activity onItemChildClick?? with position!!! 

Tried with     `  BaseViewHolder helper=(BaseViewHolder) mRecyclerView.getChildViewHolder(view);` not working

**Comment by tysheng** [comment]
Don't do like this, use ```view.getParent``` and ```findViewById```

**Comment by CymChad** [comment]
@tysheng Thank you for your answer，Another method by changing the data source to change the view of the item, not directly manipulate the view of the item

**Comment by CymChad** [comment]
Two methods are feasible

**Comment by LOG-TAG** [comment]
@CymChad  Didn't get your point !! I'm actually need a bitmap drawable from Image displayed in Recycler view item in onitemclick method to share the bitmap in whatsapp (when i click on the shre image button on the item) !!!

**Comment by LOG-TAG** [comment]
@tysheng Thanks , look into that!
