### ISSUE TITLE
使用自定义ViewHolder时，与butterknife冲突，报空指针找不到控件。

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [CymChad/BaseRecyclerViewAdapterHelper#598]
使用自定义ViewHolder时，与butterknife冲突，报空指针找不到控件。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/501  是和这个问题一样吗？

**Comment by AndroidJohnsonWang** [comment]
@CymChad 是的，不过用findViewById不会有问题就是了。

**Comment by CymChad** [comment]
我里面有说的解决方案，你试了没？是否解决了你的问题？

**Comment by CymChad** [comment]
解决了没？

**Comment by AndroidJohnsonWang** [comment]
@CymChad 
![qq 20161209090243](https://cloud.githubusercontent.com/assets/15881869/21033809/4c4f9436-bdee-11e6-83e7-3e785e42abaa.png)
是这样吗？

**Comment by CymChad** [comment]
恩 是的 不可以吗？

**Comment by AndroidJohnsonWang** [comment]
不行呢，也是空指针。

**Comment by CymChad** [comment]
使用控件的地方 ？ 具体是哪行代码？

**Comment by CymChad** [comment]
你是指base类里面的报错还是你自己的convert方法里面报错？

**Comment by AndroidJohnsonWang** [comment]
按照#501 的方法：
自己的convert方法报错,比如holder.setText(R.id.textView,"”)；空指针找不到这个View
直接使用ButterKnife.bind(this,view)：
MyViewHolder里面的@BindView(R.id.textView)空指针找不到这个View

**Comment by CymChad** [comment]
恩，我这边尝试一下ButterKnife。

**Comment by scutcl** [comment]
@AndroidJohnsonWang   加个可以为空的注解@Nullable

**Comment by CymChad** [comment]
@scutcl 感谢你的回答

**Comment by AndroidJohnsonWang** [comment]
@scutcl 也是个办法。不过子控件多的话，每个加个@Nullable就失去了使用注解框架的意义了。暂时这样吧。

**Comment by CymChad** [comment]
恩，我先把这个问题记录下来，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/500 待优化

**Comment by a483210** [comment]
请问这个问题解决了吗？

**Comment by a483210** [comment]
@CymChad 我目前通过这样解决，会出现其他问题吗？
```
public abstract class BaseAdapter<E, VH extends BaseViewHolder> extends BaseQuickAdapter<E, BaseViewHolder> {
    @SuppressWarnings("unchecked")
    @Override
    protected final void convert(BaseViewHolder holder, E item) {
        bindView((VH) holder, item);
    }

    @Override
    protected BaseViewHolder createBaseViewHolder(ViewGroup parent, int layoutResId) {
        return super.createBaseViewHolder(getItemView(layoutResId, parent));
    }

    @Override
    protected BaseViewHolder createBaseViewHolder(View view) {
        return new BaseViewHolder(view);
    }

    protected abstract void bindView(VH holder, E item);
}
```
