### ISSUE TITLE
点击item里任何一个view，其他未被点击的view的select会被触发

### ISSUE THREAD

**Issue by abc784990536** [CymChad/BaseRecyclerViewAdapterHelper#599]
点击item里任何一个view，其他未被点击的view的select状态会被触发，有什么办法解决吗，是否与item的点击机制有关

**Comment by AllenCoder** [comment]
@版本号 ？

**Comment by AllenCoder** [comment]
请更新至最新版，参照Demo的点击事件写法

**Comment by abc784990536** [comment]
2.6.1版，根据demo写的，点击事件都能响应的，就是点击view，同个item里其他有设置selecter的view都触发了selecter，变成了被press的背景色，所有的view都联动了

**Comment by AllenCoder** [comment]
请参考Demo里面的ItemClickActivity关于点击效果的写法，例子里面有区分item和itemchild各种点击 ，长按之间的不同点击效果。https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/ItemClickActivity.java  查看相关item的drawable是否跟你写法有出入
