### ISSUE TITLE
在item里面再放一个recycleview时出现了巨大的问题

### ISSUE THREAD

**Issue by BestSingerInSiHui** [CymChad/BaseRecyclerViewAdapterHelper#60]
我想在  recycleview  的  item  里面再放一个  recycleview
但是在  holder.setAdapter(R.id.rv_dragNames,adapter);  的时候
他需要的是   android.widget.Adapter
而recycleview的是  android.support.v7.widget.RecyclerView;
希望帅气又有才华的作者解决一下这个问题

**Comment by CymChad** [comment]
这个问题很好解决，你可以通过holder .getView（resId），拿到控件对象，然后去做你想做的事情。

**Comment by CymChad** [comment]
在后续的版本更新上，我会加上RecyclerView.Adapter的支持的。

**Comment by BestSingerInSiHui** [comment]
很强，解决了，谢谢
