### ISSUE TITLE
2.5.0 升级 2.6.3  openLoadMore 方法消失了 ？

### ISSUE THREAD

**Issue by xiaolongyuan** [CymChad/BaseRecyclerViewAdapterHelper#600]

**Comment by yuruxuan** [comment]
这次升级改动挺大的，尤其是上拉加载，可以参照Demo整理下（注意是Demo不是文档！！）

**Comment by CymChad** [comment]
恩 是的最新版不需要openLoadMore 了，
2.6.0上拉重构了，请参考文档：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD
和demo源码：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java

**Comment by mrchenmo** [comment]
不满一屏的情况下也会触发加载更多，去掉openLoadMore 这个限制之后，这部分逻辑需要开发者自己判断了
