### ISSUE TITLE
优化EmptyView后出现布局高度一直和父布局一致问题

### ISSUE THREAD

**Issue by yuruxuan** [CymChad/BaseRecyclerViewAdapterHelper#601]
一些信息：
库版本：2.6.3
测试设备： MI 4

问题是这样的，今早我把库从2.6.0升级到2.6.3，出现了emptyView显示异常的问题，主要体现在高度一直和RecyclerView一样。

使用代码是这样的
```
mAdapter.setHeaderAndEmpty(true);
mAdapter.setEmptyView(LayoutInflater.from(mContext).inflate(R.layout.item_detail_no_comment, new LinearLayout(mContext), true));
```

布局文件
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="64dp"
        android:layout_marginBottom="30dp"
        android:background="@color/bg_white"
        android:gravity="center"
        android:text="暂无评论内容" />

</LinearLayout>
```

我看了一眼提交日志，发现是这里导致的：
![d8111fe3-672c-4455-ad7e-c1400186ba8e](https://cloud.githubusercontent.com/assets/10010149/20953577/c2d6a2e6-bc6f-11e6-9b8a-ee6b002002f6.png)

我们每次传进去的emptyView都会在外层加一个FrameLayout 而且宽高和父布局（RecyclerView）是一致的，我不清楚是不是我使用的有问题，还是BRVAH故意这样做的，希望作者能解释下
……

**Comment by tysheng** [comment]
```
public void onEmptyView(ViewGroup parent) {
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_layout_loading, parent, false);
        setEmptyView(v);
    }
```
我的方案，传你的recyclerView，你 ```new LinearLayout(mContext)```好像没什么用的吧

**Comment by yuruxuan** [comment]
@tysheng 但是这还是会导致 真正的emptyView 和 RecyclerView大小一致啊

**Comment by 1109993488** [comment]
一般都是全屏的，有空改下。

**Comment by yuruxuan** [comment]
@1109993488 如果Header和empty同时显示的话，empty和RecyclerView一样大，这就有问题了

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.4'
	}

**Comment by largeCabbage** [comment]
@yuruxuan @CymChad  这个问题最后怎么解决的？
