### ISSUE TITLE
item中嵌套GridView问题

### ISSUE THREAD

**Issue by RuffianZhong** [CymChad/BaseRecyclerViewAdapterHelper#602]
我在item中嵌套gridView。在gridView的item中添加事件（查看大图）。在item中添加事件（跳转详情页），gridView的item事件被透传的感觉，执行了查看大图，立马跳转详情页
我想要点击gridview的item时不执行主item的事件，怎么做呢？（应该看得懂我的描述吧）
版本2.4.6

**Comment by AndroidJohnsonWang** [comment]
@RuffianZhong 我恰好也遇到同一个问题，这个问题是因为RecyclerView的onTouch和里层控件onClick，冲突造成的，我的解决办法是自定义ViewHolder，这是点击监听，以此区别RecyclerView的onTouch和里层控件onClick。

**Comment by AllenCoder** [comment]
item嵌套gridview会有问题，点击事件分发会被外层消费掉，要么直接用recyclerview的网格布局或者将gridview作为headerview或者footview,点击事件会被正确消费
