### ISSUE TITLE
可以设置正在loading

### ISSUE THREAD

**Issue by ihrthk** [CymChad/BaseRecyclerViewAdapterHelper#603]

**Comment by CymChad** [comment]
loading view 的自定义？

**Comment by ihrthk** [comment]
是的，列表数据下载比较慢，先展示这个loading view，当网路请求结束之后，在显示正常的数据

**Comment by CymChad** [comment]
setEmptyView 可以做到你要的效果

**Comment by CymChad** [comment]
解决了没？

**Comment by ihrthk** [comment]
不行，因为setEmptyView，只有当this.mData.size() == 0才有效

**Comment by CymChad** [comment]
你要的效果不是页面进来的时候就直接先显示进度条吗？还没加载成功的时候data.size应该就是0呀
