### ISSUE TITLE
支持插入在之前布局的前面BaseQuickAdapter修改？

### ISSUE THREAD

**Issue by pangli** [CymChad/BaseRecyclerViewAdapterHelper#607]
BaseQuickAdapter第336行加上等于
![image](https://cloud.githubusercontent.com/assets/7498978/20965251/d2b3fa8e-bcaf-11e6-8f71-a4139d0bade1.png)

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.4'
