### ISSUE TITLE
加载更多失效情况，急！

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#608]
页面布局android.support.design.widget.CoordinatorLayout+android.support.design.widget.AppBarLayout+android.support.design.widget.CollapsingToolbarLayout+android.support.v7.widget.RecyclerView 采用MD设计的布局使用上滑加载更多发现上滑加载不执行，只有第一次加载页面的时候执行一次，后面就不执行了，急

**Comment by 1109993488** [comment]
版本、代码

**Comment by wang0168** [comment]
我有类似问题，加载更多的回调只会执行一次 第二次就不执行了 版本是2.6.4

**Comment by CymChad** [comment]
建议大家先看demo和文档，再开始使用。。
