### ISSUE TITLE
使用sectionAdapter添加ItemChildClick事件没有触发？

### ISSUE THREAD

**Issue by isunkui** [CymChad/BaseRecyclerViewAdapterHelper#61]
我想监听section中Head区域子元素的点击事件，但是添加了setOnRecyclerViewItemChildClickListener监听事件，并没有触发onItemChildClick流程，item区域的点击也没有进入这个流程。。

**Comment by CymChad** [comment]
我吃完饭，看看。

**Comment by CymChad** [comment]
我试过了，可以的

**Comment by CymChad** [comment]
adapter：
@Override
    protected void convertHead(BaseViewHolder helper,final MySection item) {
        helper.setText(R.id.header, item.header);
        helper.setVisible(R.id.more,item.isMroe());
        helper.setOnClickListener(R.id.more,new OnItemChildClickListener());
    }
atc：
SectionAdapter sectionAdapter = new SectionAdapter(this, R.layout.item_section_content, R.layout.def_section_head, mData);
        sectionAdapter.setOnRecyclerViewItemClickListener(this);
        sectionAdapter.setOnRecyclerViewItemChildClickListener(new BaseQuickAdapter.OnRecyclerViewItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(SectionUseActivity.this, "onItemChildClick", Toast.LENGTH_LONG).show();
            }
        });
        mRecyclerView.setAdapter(sectionAdapter);

**Comment by CymChad** [comment]
具体demo已经上传了，你可以看下SectionUseActivity

**Comment by isunkui** [comment]
nice，问题已经解决了。

**Comment by CymChad** [comment]
恩，感谢使用，好用推荐给你身边的人😄

**Comment by yummyChina** [comment]
我使用MultiItem的时候 ，itemchildlick只能触发一次，完全找不到原因
