### ISSUE TITLE
如何修改“加载失败，点击重试”的字体颜色

### ISSUE THREAD

**Issue by baogaolion** [CymChad/BaseRecyclerViewAdapterHelper#611]
loadMoreFail的View能不能修改属性

**Comment by CymChad** [comment]
设置自定义加载布局
文档:https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD
也可以看看demo源码
