### ISSUE TITLE
第一个条目往下拖动，速度会特别快

### ISSUE THREAD

**Issue by whb7762300** [CymChad/BaseRecyclerViewAdapterHelper#612]
使用了条目拖动功能，但是第一个条目往下拖动的时候recyclerview会迅速滑动到底部，请问如何解决？或者有方法设置拖动时，recyclerview变为匀速滑动吗？

**Comment by whb7762300** [comment]
demo中滑动速度正常是有头部的原因，将头部去掉，或者滑动recyclerview（向下滑）头部不显示时，第一个条目往下拖动，也会迅速滑动到底部

**Comment by whb7762300** [comment]
只要拖动的条目上面没有可见的条目，都会出现recyclerview迅速滑到底部的问题

**Comment by CymChad** [comment]
版本号？

**Comment by whb7762300** [comment]
@CymChad 2.6.1

**Comment by CymChad** [comment]
我这边测试一下

**Comment by whb7762300** [comment]
@CymChad 好的，我有加群，群名片是 北京-阿兵 ，随时可以联系我
其实网上 拖的也有个bug，就是如果往上托，上一屏幕不满一屏幕（就是上面隐藏的条目不够一屏幕展示），条目拖到最上，经常出现上面的条目不会往下滑，而是拖动的条目直接放到屏幕上面去了（当前屏幕看不到的地方）

**Comment by elfman** [comment]
本库的拖拽实际只是将ItemTouchHelper做了一个包装以方便使用。
要匀速滚动可以重写ItemDragAndSwipeCallback的ItemDragAndSwipeCallback方法，返回一个固定值。比如：
```Java
    @Override
    public int interpolateOutOfBoundsScroll(RecyclerView recyclerView, int viewSize, int viewSizeOutOfBounds, int totalSize, long msSinceStartScroll) {
        final int direction = (int) Math.signum(viewSizeOutOfBounds);
        return 10 * direction;
    }
```

**Comment by whb7762300** [comment]
@elfman 谢谢答复，匀速的确是可以，但是第一个条目拖动速度过快的现象依然存在。。。

**Comment by elfman** [comment]
我无法重现你所描述的这个问题，我觉得是不是你在拖动时将条目拖到超出recyclerview的范围了

**Comment by whb7762300** [comment]
![2 z alx x e gl141 3r_d](https://cloud.githubusercontent.com/assets/19603046/21077816/ed5b7458-bf92-11e6-8b5d-4b2daa01e4ac.png)
@elfman 将recylerview滑动到此位置,往下拖动第一个条目,recylerview就会迅速滑动到底部

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.6'

**Comment by whb7762300** [comment]
@CymChad 感谢修复bug

**Comment by CymChad** [comment]
是@elfman 修复的。

**Comment by whb7762300** [comment]
@CymChad  @elfman  非常感谢，我又提了一个关于横向拖动的小bug，希望你们看一下

**Comment by MatchlessBrother** [comment]
亲，@CymChad @elfman，   compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.0'这个版本没有修复吗？如果你们是在不方便，可以说说问题原因不？我去修复！
