### ISSUE TITLE
当使用横向的recyclervview时，添加footview会导致footview占满屏幕

### ISSUE THREAD

**Issue by jiang330227** [CymChad/BaseRecyclerViewAdapterHelper#613]
如题，麻烦您请快速解决！！！

**Comment by CymChad** [comment]
ok

**Comment by CymChad** [comment]
新增 addFooterView(View footer, int index, int orientation) 
 compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.5'
