### ISSUE TITLE
RecyclerView 更新数据，使用什么什么方法呢

### ISSUE THREAD

**Issue by douya40** [CymChad/BaseRecyclerViewAdapterHelper#615]
RecyclerView 更新数据，使用什么什么方法呢

**Comment by CymChad** [comment]
setNewData 设置新的数据源
addData 追加数据
具体使用结合[demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)和看[文档](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki)

**Comment by douya40** [comment]
我说的不是设置新数据和追加数据说的是修改某一条数据，还有一个问题就是setNewData这个设置新数据数据会一闪，界面很不友好

**Comment by CymChad** [comment]
数据会一闪？是不是你开了动画？修改某一条，没有封装api，adapter原始的api就有notifyItemRangeChanged

**Comment by douya40** [comment]
修改某一条数据里面好像没有支持这个方法

**Comment by CymChad** [comment]
mAdapter.notifyItemChanged(position);

**Comment by douya40** [comment]
mAdapter.notifyItemChanged(position);这个之前修改数据怎么赋值呢

**Comment by 9h0st** [comment]
mAdapter.notifyItemChanged(position); 不起作用呀
