### ISSUE TITLE
看完了所有第错误帖子好像没有找到我要的问题解决方案

### ISSUE THREAD

**Issue by ybADMIN** [CymChad/BaseRecyclerViewAdapterHelper#616]
这边出现了个bug当recycleView倒序的时候有设置加载更多，这个时候加载更多是在上面出现的（类似qq聊天加载历史消息）
但是出现一个bug ：当列表滚动到底部，点击某个Item并且播放语音，在播放的时候刷新Adapter
刷新后如果在最上面会自动向下滚动一条数据，就好像执行了加载更多的动画一样只是没有加载更多的view出现

**Comment by ybADMIN** [comment]
经过测试，发现不论是否倒序，只要点击最后一条数据并触发刷新列表的时候都会向上滚动

**Comment by 1109993488** [comment]
你在点击播放的时候是怎样调用notify的？

**Comment by ybADMIN** [comment]
找到原因了，是因为RecyclerView没有填满父控件，不过我要的就是自动适应大小，最后还是根据RecyclerView的滑动监听自己写了一，因为赶时间
