### ISSUE TITLE
setOnItemXXListener方法，不应该需要viewId参数，默认就是itemId

### ISSUE THREAD

**Issue by ihrthk** [CymChad/BaseRecyclerViewAdapterHelper#618]
setOnItemClickListener(int viewId, AdapterView.OnItemClickListener listener) 
setOnItemLongClickListener(int viewId, AdapterView.OnItemLongClickListener listener)
setOnItemSelectedClickListener(int viewId, AdapterView.OnItemSelectedListener listener)

**Comment by CymChad** [comment]
这个是方法是提供给item的子控件listview或者gridview，而不是给item设置的。
