### ISSUE TITLE
使用 BaseSectionQuickAdapter 时, 如果adapter 调用了 addHeaderView()  方法, item 最后一项获取数据时出现异常

### ISSUE THREAD

**Issue by luketang3** [CymChad/BaseRecyclerViewAdapterHelper#62]
跟了下代码:
BaseSectionQuickAdapter.java 

@Override
    protected int getDefItemViewType(int position) {
        return ((SectionEntity) mData.get(position)).isHeader ? SECTION_HEADER_VIEW : 0;
    }

这边出了问题

**Comment by CymChad** [comment]
你的版本是？

**Comment by xzoomeye** [comment]
能贴下崩溃的日志吗？

**Comment by luketang3** [comment]
版本 1.7.2，刚更新到 1.7.9 发现已经ok 了
