### ISSUE TITLE
分页加载条目背景设置

### ISSUE THREAD

**Issue by ninety19** [CymChad/BaseRecyclerViewAdapterHelper#621]
![360 20161212095110621](https://cloud.githubusercontent.com/assets/17473472/21085785/db099fc8-c050-11e6-9f03-c0d61a0ec8f1.jpg)
整个recyclerview的效果和这个相似，整个有个圆角，条目之间用分割线分割。我现在是给headerview添加了一个向下的圆角，然后在适配器里判断条目是否是最后一条，如果是就设一个圆角背景，不是就设一个分割线的背景。现在分页加载会有些问题：如果一次加载5条数据，开始时第5条为最后一条，显示为圆角背景，这是正常的。然后上拉加载更多，此时第5条已不是最后一条了，应该显示为分割线背景，但还是显示的圆角背景。请问这该如何解决？

**Comment by CymChad** [comment]
你可以add一个footerview，这样就可以做到最后一条永远是圆角。

**Comment by ninety19** [comment]
多谢大神解答
