### ISSUE TITLE
有个小bug，横向recyclerview设置回可拖动的时候需要再次设置LinearLayoutManager才能拖动

### ISSUE THREAD

**Issue by whb7762300** [CymChad/BaseRecyclerViewAdapterHelper#622]
在项目中需要将横向recyclerview在条目拖动与不能拖动之间切换， 
      tabAdapter.disableDragItem();设置其不能拖动，
      但重新设置回拖动时tabAdapter.enableDragItem(tabItemTouchHelper);有个bug，需要点击一下recyclerview条目之后，才能拖动，后来试了好久发现，重新设置回可拖拽需重新设置LinearLayoutManager：
            `LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            linearLayoutManager.setOrientation(OrientationHelper.HORIZONTAL);
            rvTab.setLayoutManager(linearLayoutManager);
            tabAdapter.enableDragItem(tabItemTouchHelper);`
这样就可以不需要点击就能拖拽，纵向的recyclerview没有此问题，不知道这算不算个bug

**Comment by CymChad** [comment]
这不算bug
