### ISSUE TITLE
scrollView嵌套recycleView问题

### ISSUE THREAD

**Issue by yangzhenqi** [CymChad/BaseRecyclerViewAdapterHelper#623]
使用BaseRecyclerViewAdapterHelper的recycleview外加一层scrollview  且使用加载更多功能时，会一直调用onLoadMoreRequested方法

**Comment by CymChad** [comment]
恩 是的 有冲突，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/418

**Comment by yangzhenqi** [comment]
没有解决办法吗

**Comment by CymChad** [comment]
目前没有发现，这是机制的冲突。
