### ISSUE TITLE
设置禁止滑动，setOnLoadMoreListener一直被触发

### ISSUE THREAD

**Issue by ping999** [CymChad/BaseRecyclerViewAdapterHelper#624]
禁止滑动的方法：
`LinearLayoutManager linearLayoutManager = new LinearLayoutManager(context(), LinearLayoutManager.VERTICAL, false) {
            @Override
            public boolean canScrollVertically() {
                return false;
            }
        };`

**Comment by 1109993488** [comment]
麻烦贴一下版本、使用代码

**Comment by ping999** [comment]
不好意思，遗漏了
版本是：v2.6.1
说下部分代码（其实也是按常规的来写，不加scrollView也可以正常使用）
上拉加载代码：adapter．setOnLoadMoreListener('获取数据，更新ui')
xml代码：<SwipeRefreshLayout><ScrollView><LinearLayout(头部)><RecyclerView>

**Comment by 1109993488** [comment]
ScrollView下和加载更多冲突 [#418](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/418)

**Comment by ping999** [comment]
明了了解决思路，想请问下，监听scrollview滑动，如果滑动到底部就加载setOnLoadMoreListener内的方法，有没有直接调用加载动画view的方法呢？

**Comment by 1109993488** [comment]
你可以用FooterView实现加载动画

**Comment by ping999** [comment]
需要自定义footerView和自定义加载动画？

**Comment by 1109993488** [comment]
恩，你可以自定义加载动画添加到FooterView

**Comment by ping999** [comment]
OK，谢谢
