### ISSUE TITLE
偶现crash

### ISSUE THREAD

**Issue by pangli** [CymChad/BaseRecyclerViewAdapterHelper#625]
![image](https://cloud.githubusercontent.com/assets/7498978/21096537/560b2ddc-c09b-11e6-84d8-cbd2541cf6fa.png)
我给recyclerview添加了两个头一个banner一个水平的recyclerview，在上下滑动过程中点击item会报错

效果图
![image](https://cloud.githubusercontent.com/assets/7498978/21096883/bda21270-c09c-11e6-9c8a-8b5734227504.png) 两个recycleview使用的都是BaseSectionQuickAdapter实现的

**Comment by CymChad** [comment]
你的版本号是？

**Comment by pangli** [comment]
抱歉2.6.6，第二个头描述错误不是水平的recycleview而是九宫格样式的和下面是一样的，附上主fragment代码：
public class ChoicenessFragment extends Fragment {
    private LayoutInflater mInflater;
    @BindView(R.id.recycler_view)
    RecyclerView recyclerView;
    private ViewFlow banner;
    private ChoicenessAdapter adapter;
    private ViewFlowImageAdapter bannerAdapter;
    private ForeshowAdapter foreshowAdapter;
    private List<HotEnetity> hotList;
    private List<CourseBase> bannerList;
    private List<HotEnetity> foreshowtList;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        this.mInflater = inflater;
        View view = inflater.inflate(R.layout.recycler_view_layout, container, false);
        ButterKnife.bind(this, view);
        recyclerView.setLayoutManager(new StaggeredGridLayoutManager(4, StaggeredGridLayoutManager.VERTICAL));
        return view;
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        initAdpater();
        bindBannerView();
        bindData();
    }

    private void bindData() {
        RequestApi requestApi = HttpRequestManager.INSTANCE.build();
        requestApi.getBanner(RequestUtil.getNullJSONObject()).enqueue(new RetrofitCallback<ResultData<CourseBase>>() {
            @Override
            public void onSuccess(Call<ResultData<CourseBase>> call, Response<ResultData<CourseBase>> response) {
                if (response.body().getData() != null) {
                    bannerList.addAll(response.body().getData());
                    bannerAdapter.setData(bannerList);
                    banner.setAdapter(bannerAdapter, Integer.MAX_VALUE >> 1);
                }

            }
        });
        requestApi.getPredictionCourse(RequestUtil.getNullJSONObject()).enqueue(new RetrofitCallback<ResultData<CourseBase>>() {
            @Override
            public void onSuccess(Call<ResultData<CourseBase>> call, Response<ResultData<CourseBase>> response) {
                List<CourseBase> courseBase = response.body().getData();
                if (courseBase != null && !courseBase.isEmpty()) {
                    foreshowtList = new ArrayList<>();
                    foreshowtList.add(new HotEnetity(true, "预告"));
                    for (CourseBase item : courseBase) {
                        foreshowtList.add(new HotEnetity(item));
                    }
                    showForeshowView();
                }
            }
        });
        requestApi.getHotCourse(RequestUtil.getNullJSONObject()).enqueue(new RetrofitCallback<ResultData<CourseBase>>
                () {
            @Override
            public void onSuccess(Call<ResultData<CourseBase>> call, Response<ResultData<CourseBase>> response) {
                List<CourseBase> courseBase = response.body().getData();
                if (courseBase != null && !courseBase.isEmpty()) {
                    List<HotEnetity> hotEnetities = new ArrayList<>();
                    for (CourseBase item : courseBase) {
                        hotEnetities.add(new HotEnetity(item));
                    }for (CourseBase item : courseBase) {
                        hotEnetities.add(new HotEnetity(item));
                    }for (CourseBase item : courseBase) {
                        hotEnetities.add(new HotEnetity(item));
                    }
                    hotList.addAll(hotEnetities);
                }
            }
        });
    }

    private void initAdpater() {
        hotList = new ArrayList<>();
        hotList.add(new HotEnetity(true, "热门"));
        adapter = new ChoicenessAdapter(R.layout.course_item_layout, R.layout.header_layout, hotList);
        recyclerView.setAdapter(adapter);
        recyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                if (i > 0) {
                    HotEnetity courseBase = (HotEnetity) baseQuickAdapter.getItem(i);
                    Toast.makeText(getActivity(), courseBase.t.getName() + "----" + i, Toast.LENGTH_SHORT).show();
                }
            }
        });
    }

    private void bindBannerView() {
        bannerList = new ArrayList<>();
        View bannerView = mInflater.inflate(R.layout.banner_layout, (ViewGroup) recyclerView.getParent(), false);
        banner = (ViewFlow) bannerView.findViewById(R.id.banner);
        banner.setParentRecyclerView(recyclerView);
        bannerAdapter = new ViewFlowImageAdapter(getActivity(), mInflater);
        adapter.addHeaderView(bannerView);
    }

    private void showForeshowView() {
        View foreshowView = mInflater.inflate(R.layout.recycler_view_layout, (ViewGroup) recyclerView.getParent(),
                false);
        RecyclerView recyclerView = (RecyclerView) foreshowView.findViewById(R.id.recycler_view);
        recyclerView.setLayoutManager(new StaggeredGridLayoutManager(4, StaggeredGridLayoutManager.VERTICAL));
        foreshowAdapter = new ForeshowAdapter(R.layout.foreshow_item_layout, R.layout.header_layout, foreshowtList);
        recyclerView.setAdapter(foreshowAdapter);
        adapter.addHeaderView(foreshowView);
        recyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                if (i > 0) {
                    HotEnetity courseBase = (HotEnetity) baseQuickAdapter.getItem(i);
                    Toast.makeText(getActivity(), courseBase.t.getName() + "----" + i, Toast.LENGTH_SHORT).show();
                }
            }
        });
    }

}

**Comment by pangli** [comment]
2.2.6版本，这个问题比较急，希望你能尽快给出解决方式，谢谢，主要是第二个recycleview头部点击时会crash




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年12月13日(星期二) 上午8:56
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "唯爱薇 卟离卟弃"<674736456@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 偶现crash (#625)




你的版本号是？

**Comment by AllenCoder** [comment]
1. 请升级至最新版
2. 参考解决 recyclerview的bug 在数据clear时，适配器正在刷新会出现这个bug  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/590

**Comment by pangli** [comment]
已经是最新版本了我发现将第二个头StaggeredGridLayoutManager替换成GridLayoutManager使用BaseMultiItemQuickAdapter目前未出现crash，猜测是对你StaggeredGridLayoutManager的处理问题产生的问题

**Comment by CymChad** [comment]
#500 待优化

**Comment by CymChad** [comment]
用了你发我的demo，我还是没有复现bug。

**Comment by pangli** [comment]
我是用平板测试的，系统版本6.0和7.0还有7.1上都有此问题，我抽空发你重现操作视频




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年12月22日(星期四) 下午2:31
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "佐罗"<674736456@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 偶现crash (#625)




用了你发我的demo，我还是没有复现bug。

**Comment by CymChad** [comment]
恩 好的。
