### ISSUE TITLE
设置setOnLoadMoreListener，数据不足一页时，仍然显示“加载中”

### ISSUE THREAD

**Issue by zzy0990** [CymChad/BaseRecyclerViewAdapterHelper#626]
只要设置了setOnLoadMoreListener，数据不足一页就会在列表下方显示"加载中"，
即使是设置了setEnableLoadMore(false); 也一样会显示"加载中"，
如果是在这里进行判断
if(没有更多数据){
        mQuickAdapter.loadMoreEnd();
        //or
        mQuickAdapter.loadMoreEnd(true);
    }
也一样是会显示"加载中"，然后再调用上面的代码（隐藏或者显示没有更多数据）
测试时数据只有一条，尝试了issues里面的各种方法，都没什么效果，除了把setOnLoadMoreListener注释掉不会显示"加载中"
v2.6.6版本

**Comment by haegyeong** [comment]
刚刚我也发现这个问题，但是我的做法是 mQuickAdapter.loadMoreEnd();让他显示加载完毕了

**Comment by 1109993488** [comment]
你是不是调用的位置不对？setEnableLoadMore(false);要在setOnLoadMoreListener后调用，loadMoreEnd(true);后setNewData也不行，要在setNewData后调用loadMoreEnd(true).  实在不行你贴出代码

**Comment by CymChad** [comment]
@haegyeong 问题解决没？

**Comment by haegyeong** [comment]
没解决，项目比较赶，所以我灵活的用了你封装的方法，如果数据不满一屏，然后就调用了 mQuickAdapter.loadMoreEnd();，这样就会在最后一条数据下面加显示加载完毕 @CymChad

**Comment by 1109993488** [comment]
loadMoreEnd(true)就不显示没有更多数据了

**Comment by CymChad** [comment]
恩，其实 @1109993488 的回答已经解答你的问题了。

**Comment by CymChad** [comment]
因为现在上拉不需要像之前的版本一样设置pageSize所以数据不足一页时需要在回调中处理。
