### ISSUE TITLE
setNewData之后调用notifyItemChanged失效

### ISSUE THREAD

**Issue by shuiyouwen** [CymChad/BaseRecyclerViewAdapterHelper#627]
场景是：一个列表，每个条目都可以点赞。现在下拉刷新获取到数据之后我调用setNewData更新了列表数据，在这之后我再点赞调用notifyItemChanged刷新点赞条目的ui的时候就不起作用了，麻烦给点建议^ ^

**Comment by 1109993488** [comment]
1.看点击事件是否调用了
2.如果有头部position需要加1
3.看conver方法是否调用了，然后看设置代码

**Comment by MrShui** [comment]
按你说的试了，貌似是个bug。。

**Comment by MrShui** [comment]
原来是我的姿势不对- -，我是更改了，我传入adapter的那个集合数据再去刷新了，看了下源码应该修改BaseQuickAdapter中的mData集合再刷新。。

**Comment by liuyuttkx** [comment]
@MrShui 您好，我也遇到了你这样的问题，在调用setNewData后，立即调用notifyItemChanged（），notifyItemChanged无效
