### ISSUE TITLE
这边有一个小错误，是实现不是继承（英文办也有同样的错误）

### ISSUE THREAD

**Issue by ihrthk** [CymChad/BaseRecyclerViewAdapterHelper#629]
![2016-12-14 15 09 36](https://cloud.githubusercontent.com/assets/2418260/21172869/7e2eff80-c20f-11e6-8e8b-cf70a083e2fe.png)

**Comment by CymChad** [comment]
好的，多谢提醒，我马上修改。

**Comment by CymChad** [comment]
已修改
