### ISSUE TITLE
在对数据做add,remove操作时不加锁，是否可能有问题

### ISSUE THREAD

**Issue by kyleada** [CymChad/BaseRecyclerViewAdapterHelper#63]

**Comment by CymChad** [comment]
这个都是调用RecyclerView原生的方法。

**Comment by kyleada** [comment]
public void addData(List<T> data) {
        this.mData.addAll(data); //我是说对mData的操作
        notifyDataSetChanged();
    }

**Comment by CymChad** [comment]
mData就是你自己的数组，这也是原始的，没做过任何处理。

**Comment by zeng1990java** [comment]
这个不加锁是没有问题的，因为不会涉及到多线程操作。

**Comment by kyleada** [comment]
@zeng1990java  有可能会涉及到吧。一个场景，支持用户对列表数据删除，同时后台策略接收服务端推送数据对列表数据做删改 @CymChad

**Comment by xzoomeye** [comment]
但是方法调用还是会回到主线程操作吧，不然notifyDataSetChanged();就报错了
