### ISSUE TITLE
在adapter中使用item中子view调用点击事件,导致调用了notifyDataSetChanged()

### ISSUE THREAD

**Issue by liuyuttkx** [CymChad/BaseRecyclerViewAdapterHelper#631]
view.....setOnClickListener( ...)
点击事件后, 自动调用了notifyDataSetChanged()方法. 
有什么方法在点击事件时,不用调用notifyDataSetChanged() .
谢谢...
另外,在一个adapter中发现调用了点击事件,可能会导致 "no_data_view" (没有加载更多的view)消失

**Comment by AllenCoder** [comment]
最新版点击事件不是这样写的啊？请更新至最新版，参考Demo写法，支持itemview中对childview的点击事件绑定，详情参考Wiki https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister

**Comment by liuyuttkx** [comment]
我使用了Demo中的方法,还是一样的. 我的点击事件是开启一个Activity .
点击事件发生后, 调用了一遍convert方法,这样才导致刷新了界面. 因为我的adapter条目中有多个Banner图,Banner图有明显的闪烁现象

holder.addOnClickListener(R.id.tv_title);
....
  recycler.getRecyclerView().addOnItemTouchListener(new OnItemClickListener() {
...

**Comment by AllenCoder** [comment]
点击事件跟 adapter的刷新是完全分开的。点击事件在触发时是不会触发notify，你代码是不是自己做了处理

**Comment by CymChad** [comment]
按照你的问题，没有出现你说的情况。
![1](https://cloud.githubusercontent.com/assets/7698209/21290991/9ae72d5c-c50a-11e6-8ad7-267cf29941fd.gif)
我在convert里面打印了log，按照你说的在头像上面绑定了点击事件并且跳转了Activity，convert没有重新执行。
