### ISSUE TITLE
还是itemType的问题

### ISSUE THREAD

**Issue by ihrthk** [CymChad/BaseRecyclerViewAdapterHelper#635]
@tysheng
虽然可以通过多一个包装，来达到代码没有侵入的问题，但是已经违背了使用文档（实体类实现MultiItemEntity接口），个人感觉这种写法，可以有一点‘绕’，是否可以重写考虑沿用老的写法（即放在adapter里）

**Comment by tysheng** [comment]
个人喜好问题，我还是喜欢 java bean 管 java bean，让包装类去做包装的事，使用文档也只是 owner 自己的思路

**Comment by CymChad** [comment]
老的写法，主要是考虑到对新手使用比较复杂，因为要理解原始方法调用的顺序，所以改进成了现有的写法。

**Comment by CymChad** [comment]
不过也可以考虑下，做一下更好的优化方案。

**Comment by tysheng** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/636

供参考

**Comment by CymChad** [comment]
@tysheng  恩 好的。多谢
