### ISSUE TITLE
addFooterView方法后，上拉下载更多会出现问题

### ISSUE THREAD

**Issue by a5533348** [CymChad/BaseRecyclerViewAdapterHelper#637]
当我在项目中addFooterView设置了footerView后，数据加载成功之后列表会定位到最后一行，去掉addFooterView则正常。

**Comment by 1109993488** [comment]
框架没有进行移动操作，数据加载成功后你是如何操作的？

**Comment by a5533348** [comment]
mMerchandiseAdapter.addData(pageModel.getQueryList());
        if (mCurrentPage >= pageModel.getPcount()) {
            mMerchandiseAdapter.loadMoreEnd();
        }else{
            mMerchandiseAdapter.loadMoreComplete();
        }
        ++mCurrentPage;

没有做其他操作， 你可以写个例子测试一下看看

**Comment by 1109993488** [comment]
在demo里添加FooterView没有问题，你在demo里加FooterView试试。你说的加载成功后列表会定位到最后一行是什么意思？

**Comment by CymChad** [comment]
@a5533348 问题解决没？

**Comment by BaiMingxu** [comment]
上拉刷新和头布局怎么使用呀 求指教 谢谢

**Comment by CymChad** [comment]
@BaiMingxu 参考demo和wiki文档
