### ISSUE TITLE
BaseMultiItemQuickAdapter 如何删除中间节点和其子节点数据

### ISSUE THREAD

**Issue by lanrenyige008** [CymChad/BaseRecyclerViewAdapterHelper#638]
中间节点的点击事件中加下面代码 
  AbstractExpandableItem mAbstractExpandableItem = (AbstractExpandableItem) getItem(getParentPosition(item));
                                        List<Person> products = lv1.getSubItems();
// 在AbstractExpandableItem中加了  removeAllSubItem clean list
                                        ((Level1Item) item).removeAllSubItem();
                                        getData().remove(products);
                                        mAbstractExpandableItem.removeSubItem(item);
                                        getData().remove(item);
                                           mListener.deleteProduct(mOrderDetailProductEntity);
                                        notifyDataSetChanged();
第二层数据删除后 第三层数据 变成了第二层
试了很多方法   不知道怎么做

还有就是第三层回调事件发生 想改变第二层数据展示 怎么做   

最好就是有没有比较全的demo和文档啊   谢谢

**Comment by CymChad** [comment]
你说的是Expandable？还是MultiItem？

**Comment by CymChad** [comment]
直接通过删除数据然后notify。
