### ISSUE TITLE
图片加载可以优化，做成扩展

### ISSUE THREAD

**Issue by zhonghanwen** [CymChad/BaseRecyclerViewAdapterHelper#64]
如果项目已经集成了其他图片加载框架，但是你这个项目又集成了Glide图片加载库，这样项目就存在了两个图片加载框架，然而这不是我们想要达到的效果。期待作者可以优化这块~

**Comment by CymChad** [comment]
可以我这边考虑一下。

**Comment by CymChad** [comment]
我的想法是把BaseViewHolder的
setImageUrl(int viewId, String imageUrl)
setImageUrl(int viewId, String imageUrl, int defResourceId)
setImageUrl(int viewId, String imageUrl, int defResourceId, BitmapTransformation... transformations)
方法去除
去除glide的引用，
你可以通过getView拿到iv，然后随意你来加载？
你觉得呢？

**Comment by zhonghanwen** [comment]
@CymChad 这样也可以~

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.7.9' 已修改，感谢建议。

**Comment by locHiH** [comment]
哭哭哭哭死，2个月没升级库，一升级Glide被剔除了，setImageURL也被删除了。。啊啊啊啊啊啊啊，抓狂中
