### ISSUE TITLE
addFooterView之后footer点击事件无效

### ISSUE THREAD

**Issue by yangzhenqi** [CymChad/BaseRecyclerViewAdapterHelper#640]
如题 底部布局点击事件被拦截了，该怎么解决呢

**Comment by hezhipengzipp** [comment]
mFooterView = LayoutInflater.from(mContext).inflate(R.layout.item_add_newaddress,mRecyclerView);
        mKlineTradeTypeAdapter = new WithDrawBTCAdapter(R.layout.item_btc_coin,coinUserAddressBeanList);
点击footer没有响应
