### ISSUE TITLE
在Demo PullToRefreshUseActivity的页面中，item使用remove或notifyItemRemoved删除最后一个数据会报错

### ISSUE THREAD

**Issue by conghuahuadan** [CymChad/BaseRecyclerViewAdapterHelper#641]
你好，在Demo PullToRefreshUseActivity的页面中，item使用remove或notifyItemRemoved删除最后一个数据会报错，如果取消上拉加载功能则不会出现此问题，希望作者尽快修复~

原代码：
    private void initAdapter() {
        mQuickAdapter = new QuickAdapter(R.layout.tweet, sampleData);
        mQuickAdapter.setOnLoadMoreListener(this);
        mQuickAdapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_LEFT);
        mRecyclerView.setAdapter(mQuickAdapter);
        mCurrentCounter = mQuickAdapter.getData().size();

        mRecyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(final BaseQuickAdapter adapter, final View view, final int position) {
                Toast.makeText(PullToRefreshUseActivity.this, Integer.toString(position), Toast.LENGTH_LONG).show();
                mQuickAdapter.remove(position);
            }
        });
    }

报错原因：java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2bd3bdd position=0 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent}

**Comment by CymChad** [comment]
你的版本号是？

**Comment by CymChad** [comment]
![1](https://cloud.githubusercontent.com/assets/7698209/21291061/3bb5a7ca-c50d-11e6-8724-f0ae516b529e.gif)
刚测试demo上面的代码，最新版本，没发现你说的问题，请你更新到最新版本再试试。

**Comment by CymChad** [comment]
我刚才测试了一下，确实有这个情况，我想到一个解决办法：
```java
if (mData.size() == 1 ) {
            loadMoreEnd(true);
}
```
因为如果你要删除最后一个项的时候你也不可能在上拉加载更多了。

**Comment by 1109993488** [comment]
删除最后一个item的时候计算有误，近期会修复

**Comment by conghuahuadan** [comment]
嗯，我也是用了类似的方法

if (sampleData.size() == 1) {
                    sampleData.remove(position);
                    mQuickAdapter.notifyDataSetChanged();
                } else {
                    mQuickAdapter.remove(position);
                }

**Comment by conghuahuadan** [comment]
另外，我喜欢在RecyclerView的item中加入一个属性android:background="?attr/selectableItemBackground"或者android:background="?android:background：attr/selectableItemBackground"，但是如果使用android:background="?attr/selectableItemBackground"会报错，如果使用android:background="?android:background：attr/selectableItemBackground"，item的水纹效果呈现为白色，这样在白色背景下看不到效果，作者们也可以修复一下这个问题吗？

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.7'

**Comment by CymChad** [comment]
@conghuahuadan 你可以详细的描述下 你说的bg问题，并且贴出crash报告，从新new 一个 issues。
