### ISSUE TITLE
使用ItemType,convert打印数据变成倒序

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [CymChad/BaseRecyclerViewAdapterHelper#642]
BaseMultiItemQuickAdapter每个ItemType都包含一个时间字段，在convert打印时间字段，是倒序的。列表显示没有问题。
怀疑BaseRecyclerViewAdapterHelper是不是convert中设置数据的顺序是从最后一个开始的？

**Comment by CymChad** [comment]
收到，我这边核查一下。

**Comment by CymChad** [comment]
![1](https://cloud.githubusercontent.com/assets/7698209/21291029/280d421a-c50c-11e6-94a8-68370a4f72cb.gif)
我做了下测试，把每组item都加了一个index属性，并且在convert方法里面打印出来了，顺序一切正常。

**Comment by zhujunhua2012** [comment]
我也遇到这个问题，好像还是存在的。。。
同一个界面，有时候正序，有时候倒序，很奇怪。。。（界面显示是正常的，加载日志不正常）
