### ISSUE TITLE
添加了header之后局部刷新无效

### ISSUE THREAD

**Issue by huangdaisheng** [CymChad/BaseRecyclerViewAdapterHelper#644]
你好，我想给我的recycleview添加一个，使用你的adapter添加了一个header，但是局部刷新就无效了。如果不添加header，那么局部刷新是正常的。希望你能修复一下吧

**Comment by magic0908** [comment]
同遇到这个问题，用adapter添加headerView的时候，更新了数据源，之后调用notifyItemChanged方法不能局部刷新；如果不添加header是可以局部刷新的，麻烦作者有时间修复一下吧。

**Comment by CymChad** [comment]
你的position对了吗？

**Comment by magic0908** [comment]
确实是对的，我在局部更新的代码是这么写的
//更新数据源，同时修改item显示
mDataList.set(changePosition,bean);
mAdapter.notifyItemChanged(changePosition);
所以在不添加头部的时候可以实现局部更新，但是添加了头部后就没法更新了。

**Comment by huangdaisheng** [comment]
我目前是这样解决的,在onItemChildClick(final BaseQuickAdapter adapter, final View view, final int position) {
         TextView textView= (TextView) view.findViewById(R.id.tv);
           textView.setText("xxxx");
}



------------------ 原始邮件 ------------------
发件人: "magic0908";<notifications@github.com>;
发送时间: 2016年12月21日(星期三) 下午4:08
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "try"<1648412292@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 添加了header之后局部刷新无效 (#644)




确实是对的，我在局部更新的代码是这么写的
 //更新数据源，同时修改item显示
 mDataList.set(changePosition,bean);
 mAdapter.notifyItemChanged(changePosition);
 所以在不添加头部的时候可以实现局部更新，但是添加了头部后就没法更新了。

**Comment by CymChad** [comment]
我这边看看

**Comment by 1109993488** [comment]
```
mDataList.set(changePosition,bean);
mAdapter.notifyItemChanged(changePosition+mAdapter.getHeaderLayoutCount());
```

**Comment by CymChad** [comment]
@magic0908 你可以试一下 @1109993488 说的办法。

**Comment by magic0908** [comment]
这个方法只适合点击一个textView，然后textView的数据状态发生变化吧。我这边的逻辑是，在同一个item下，点击一个textView，然后是另一个textView的状态发生改变。

**Comment by CymChad** [comment]
原理都是一样的，无非就是id不一样吧。

**Comment by magic0908** [comment]
已经可以了，感谢！
