### ISSUE TITLE
Section模式下按组删除

### ISSUE THREAD

**Issue by farrywen** [CymChad/BaseRecyclerViewAdapterHelper#645]
Section模式下如何按组删除？

**Comment by CymChad** [comment]
目前只能按照item的position删除

**Comment by farrywen** [comment]
感觉现在的Section模式就是MultipleItem。Expandable那个封装更符合Section分组。

**Comment by CymChad** [comment]
恩 是的，Section是在Expandable没有开发的时候就已经有了，后续推荐使用Expandable

**Comment by CymChad** [comment]
这一点，我后续会在demo中体现，去除Section的写法。也多谢提醒。

**Comment by CymChad** [comment]
#500 待优化
