### ISSUE TITLE
上拉加载更多不会执行

### ISSUE THREAD

**Issue by PrinceOfAndroid** [CymChad/BaseRecyclerViewAdapterHelper#647]

**Comment by CymChad** [comment]
版本号？

**Comment by CymChad** [comment]
如果不是最新版本请更新至最新版本，然后根据demo和文档来。有问题再提。

**Comment by xyzeng12** [comment]
2.6.7，一会儿可以一会儿又不行，我都没对它做啥

**Comment by CymChad** [comment]
你使用代码是？

**Comment by xyzeng12** [comment]
/**
 * 散标列表adapter
 */
public class Product_OtherAdapter extends BaseQuickAdapter<HomeDispersingBean.DataBean.ResultBean, BaseViewHolder> {
    public Product_OtherAdapter(List<HomeDispersingBean.DataBean.ResultBean> data) {
        super(R.layout.item_san, data);

    }

    @Override
    protected void convert(BaseViewHolder viewHolder, HomeDispersingBean.DataBean.ResultBean info) {
        viewHolder
                // .setVisible(R.id.iv_xinshou, false)
                .setText(R.id.tv_item_san_nbr, info.getNbr())
                .setText(R.id.tv_item_san_title, info.getTitle())
                .setText(R.id.tv_item_san_nhsy, info.getNhsy() + "")
                .setText(R.id.tv_item_san_days, String.valueOf(info.getDays())   );
        if ("A002".equals(info.getActionCd())) {
            viewHolder.setBackgroundRes(R.id.tv_investnow, R.mipmap.tuan_can_invest)
                    .setText(R.id.tv_investnow, "立即\n加入");
            if ((int) Math.floor((info.getBidCharge() / info.getCharge() * 100)) == 100) {
                viewHolder.setBackgroundRes(R.id.tv_investnow, R.mipmap.tuan_cannot_invest)
                        .setText(R.id.tv_investnow, "已满额");
            }
        } else {
            viewHolder.setBackgroundRes(R.id.tv_investnow, R.mipmap.tuan_cannot_invest);
        }
        if ("A004".equals(info.getActionCd())) {
            viewHolder.setBackgroundRes(R.id.tv_investnow, R.mipmap.tuan_cannot_invest)
                    .setText(R.id.tv_investnow, "还款中");
        } else if ("A008".equals(info.getActionCd())) {
            viewHolder.setBackgroundRes(R.id.tv_investnow, R.mipmap.tuan_cannot_invest)
                    .setText(R.id.tv_investnow, "已完成");
        }
    }
}————————————————————————————
public class MoneyFg extends BaseFragment implements SwipeRefreshLayout.OnRefreshListener {


    @BindView(R.id.collapsing_toolbar_layout)
    CollapsingToolbarLayout collapsingToolbarLayout;

    @Override
    public int getContentViewId() {
        return R.layout.fragment_money;
    }
    private static final int PAGE_SIZE = 5;
    @BindView(R.id.rv_san)
    RecyclerView rvProductSan;
    @BindView(R.id.srl_san)
    SwipeRefreshLayout srlSan;
    private View mView;
    private int pageNum = 0;
    private List<HomeDispersingBean.DataBean.ResultBean> product_Other = new ArrayList<>();
    private Product_OtherAdapter product_OtherAdapter;
    @Override
    protected void initAllMembersView(Bundle savedInstanceState, View view) {
        mView = view;
        collapsingToolbarLayout.setTitle("精选理财");
        //通过CollapsingToolbarLayout修改字体颜色
        collapsingToolbarLayout.setExpandedTitleColor(Color.TRANSPARENT);//设置还没收缩时状态下字体颜色
        collapsingToolbarLayout.setCollapsedTitleTextColor(Color.WHITE);//设置收缩后Toolbar上字体的颜色
        srlSan.setOnRefreshListener(this);//下拉刷新
        srlSan.setColorSchemeColors(getResources().getColor(R.color.blue));
        initRV();
        product_OtherAdapter.removeAllFooterView();
        getProduct(pageNum);
    }
    private void initRV() {
        // 为RecyclerView指定布局管理对象
        rvProductSan.setLayoutManager(new WrapContentLinearLayoutManager(getActivity(), LinearLayoutManager.VERTICAL, false));
        rvProductSan.setHasFixedSize(true);
        product_OtherAdapter = new Product_OtherAdapter(product_Other);
        product_OtherAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
                                                       @Override
                                                       public void onLoadMoreRequested() {
                                                           getProduct(++pageNum);//上拉加载
                                                       }
                                                   }
        );
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
            product_OtherAdapter.openLoadAnimation(BaseQuickAdapter.SCALEIN);
        product_OtherAdapter.isFirstOnly(false);
        product_OtherAdapter.setAutoLoadMoreSize(3);
        rvProductSan.setAdapter(product_OtherAdapter);
        View header = LayoutInflater.from(getActivity()).inflate(R.layout.header_money, rvProductSan, false);
        product_OtherAdapter.addHeaderView(header);
        rvProductSan.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(BaseQuickAdapter adapter, View view, int position) {
                toast(getActivity(), "p:" + position);
            }
        });
    }

    /**
     * 获取列表数据
     * @param pageNum
     */
    private void getProduct(final int pageNum) {
        OkHttpUtils
                .post()
                .url(UrlConst.SERVICE_URL + UrlConst.PRODUCT_SAN_LIST)
                .addParams("pages", pageNum + "")
                .build()
                .execute(new StringCallback() {
                    @Override
                    public void onError(Call call, Exception e, int id) {
                        toastNetFail(getActivity());
                        log("e:" + e);
                        if (srlSan != null) srlSan.setRefreshing(false);
                        if (pageNum != 0) {
                            product_OtherAdapter.loadMoreFail();
                        }
                    }

                    @Override
                    public void onResponse(String response, int id) {
                        logJson(response);
                        HomeDispersingBean homeDispersingBean = tryGson(response,HomeDispersingBean.class);
                        if (srlSan != null) srlSan.setRefreshing(false);
                        if (homeDispersingBean != null && homeDispersingBean.getData() != null) {
                            if (homeDispersingBean.getData().getResult() != null && homeDispersingBean.getData().getResult().size() > 0) {
                                if (pageNum == 0) {
                                    product_Other.clear();
                                }
                                product_OtherAdapter.addData(homeDispersingBean.getData().getResult());
                                product_OtherAdapter.loadMoreComplete();
                                if (homeDispersingBean.getData().getResult().size() < PAGE_SIZE) {
                                    if (pageNum == 0) {
                                        product_OtherAdapter.setEnableLoadMore(false);
                                    } else {
                                        product_OtherAdapter.loadMoreEnd();
                                    }
                                } else {
                                    product_OtherAdapter.setEnableLoadMore(true);
                                }
                            } else {
                                log("loadMoreEnd");
                                product_OtherAdapter.loadMoreEnd();
                            }
                        }
                    }
                });
    }

    @Override
    public void onRefresh() {
        product_OtherAdapter.removeAllFooterView();
        pageNum = 0;
        getProduct(0);
    }
}





------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2016年12月21日(星期三) 中午11:17
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "曾翔宇"<1164968183@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 上拉加载更多不会执行 (#647)




你使用代码是？

**Comment by PrinceOfAndroid** [comment]
用的是最新的，照着上面的demo写，发现上拉加载不会执行。然后我尝试去用1.9.7，还是不执行。。。

**Comment by CymChad** [comment]
我这边看一下，你把代码贴一下。

**Comment by CymChad** [comment]
@xyzeng12 你下拉刷新的时候用使用setNewData这个函数来填充数据。

**Comment by CymChad** [comment]
因为当你调用loadMoreEnd的时候会关闭上拉，setNewData会重新开启上拉。

**Comment by PrinceOfAndroid** [comment]
public class MyLoadingMore extends LoadMoreView{
    @Override
    public int getLayoutId() {
        return R.layout.view_loading_more;
    }

    @Override
    protected int getLoadingViewId() {
        return R.id.load_more_view;
    }

    @Override
    protected int getLoadFailViewId() {
        return R.id.load_fail_view;
    }

    @Override
    protected int getLoadEndViewId() {
        return 0;
    }
}


public class ManagingLoanAdapter extends BaseQuickAdapter<ManagingLoan.ResponseBean,BaseViewHolder> {
    public ManagingLoanAdapter(int layoutResId, List<ManagingLoan.ResponseBean> data) {
        super(layoutResId, data);
    }

    @Override
    protected void convert(BaseViewHolder baseViewHolder, ManagingLoan.ResponseBean responseBean) {
        baseViewHolder.setText(R.id.tv_name, responseBean.getClient_Name());
        baseViewHolder.setText(R.id.tv_type, responseBean.getPro_Name());
        baseViewHolder.setText(R.id.tv_money, responseBean.getLoan_Money());
        baseViewHolder.setText(R.id.tv_rate, responseBean.getLoan_Interestrate());
        baseViewHolder.setText(R.id.tv_limit, responseBean.getLoan_Expires());
        baseViewHolder.setText(R.id.tv_date, responseBean.getCreateDate());
        if (responseBean.getLoan_Cycle().equals("1")) {
            baseViewHolder.setVisible(R.id.ll_cycle, true);
            if (responseBean.getCycle().equals("1")) {
                baseViewHolder.setText(R.id.tv_cycle, "是");
            } else {
                baseViewHolder.setText(R.id.tv_cycle, "否");
            }
        } else {
            baseViewHolder.setVisible(R.id.ll_cycle, false);
        }

        baseViewHolder.addOnClickListener(R.id.tv_delete_loan);
        baseViewHolder.addOnClickListener(R.id.tv_finish_loan);


    }
}


 adapter = new ManagingLoanAdapter(R.layout.view_managing_item, datas);
        adapter.setEnableLoadMore(true);
        adapter.setLoadMoreView(new MyLoadingMore());

        reList.setLayoutManager(new LinearLayoutManager(ManagingLoanActivity.this));
        reList.setAdapter(adapter);

        adapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                reList.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        adapter.loadMoreComplete();
                    }
                },1500);
            }
        });

**Comment by 1109993488** [comment]
```
    @Override
    public void onRefresh() {
        product_OtherAdapter.setEnableLoadMore(false);//禁用上拉
        pageNum = 0;
        getProduct(0);
    }

    @Override
    public void onLoadMoreRequested() {
        srlSan.setEnabled(false);//禁用下拉
        getProduct(++pageNum);//上拉加载
    }


    private void getProduct(final int pageNum) {
        OkHttpUtils
                .post()
                .url(UrlConst.SERVICE_URL + UrlConst.PRODUCT_SAN_LIST)
                .addParams("pages", pageNum + "")
                .build()
                .execute(new StringCallback() {
                    @Override
                    public void onError(Call call, Exception e, int id) {
                        requestEnd(true);
                    }

                    @Override
                    public void onResponse(String response, int id) {
                        HomeDispersingBean homeDispersingBean = tryGson(response, HomeDispersingBean.class);
                        if (homeDispersingBean != null && homeDispersingBean.getData() != null) {
                            final List<HomeDispersingBean.DataBean.ResultBean> list = homeDispersingBean.getData().getResult();
                            final int listSize = list == null ? 0 : list.size();
                            if (pageNum == 0) {
                                product_OtherAdapter.setNewData(list);
                                if (listSize < PAGE_SIZE) {
                                    product_OtherAdapter.loadMoreEnd();
                                }
                            } else {
                                if (list != null) {
                                    product_OtherAdapter.addData(list);
                                }
                                if (listSize < PAGE_SIZE) {
                                    product_OtherAdapter.loadMoreEnd();
                                } else {
                                    product_OtherAdapter.loadMoreComplete();
                                }
                            }
                            requestEnd(false);
                        } else {
                            //解析失败，此时也认为请求失败了
                            requestEnd(true);
                        }
                    }

                    private void requestEnd(boolean fail) {
                        if (pageNum == 0) {
                            srlSan.setRefreshing(false);
                            product_OtherAdapter.setEnableLoadMore(true);
                        } else {
                            srlSan.setEnabled(true);
                            if (fail) {
                                MoneyFg.this.pageNum--;
                                product_OtherAdapter.loadMoreFail();
                            }
                        }
                    }
                });
    }
```
这只是一种写法，第一页需要setNewData(list);
```
SwipeRefreshLayout.setEnabled(boolean);
BaseQuickAdapter.setEnableLoadMore(boolean);
这2个这里只是用来在下拉的时候禁用下拉，下拉的时候禁用上拉
```   
加载更多失败后pageNum需要-1，不然点击重新加载更多的时候会从下一页加载，而不是当前失败的这一页

**Comment by CymChad** [comment]
@PrinceOfAndroid 问题解决没？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/651 可以参考一下这个
