### ISSUE TITLE
没有效果啊

### ISSUE THREAD

**Issue by drduan** [CymChad/BaseRecyclerViewAdapterHelper#65]
<img width="967" alt="2016-06-07 18 58 26" src="https://cloud.githubusercontent.com/assets/7875572/15855400/e064bf6e-2ce1-11e6-9152-09a69486ec39.png">

**Comment by drduan** [comment]
<img width="1311" alt="2016-06-07 19 01 07" src="https://cloud.githubusercontent.com/assets/7875572/15855473/3b425004-2ce2-11e6-99d1-4fec12f10669.png">

**Comment by CymChad** [comment]
你的RecyclerView没有setLayoutM...
