### ISSUE TITLE
recyclerview嵌套recyclerview出现重复添加itemtouchlistener

### ISSUE THREAD

**Issue by bobingxin** [CymChad/BaseRecyclerViewAdapterHelper#656]
在外层recyclerview的adapter中对内部recyclerview执行recyclerview.addOnItemTouchListener结果出现重复添加的问题。

**Comment by bobingxin** [comment]
为什么不弄成setOnItemTouchListener而是弄成addOnItemTouchListener,是不是因为结合中保存了多个listener，导致多次调用。

**Comment by AllenCoder** [comment]
recyclerview 嵌套recyclerview  点击事件，建议分开写，setOnItemTouchListener会导致item的都被重复绑定listener. 。事件分发效率低下

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.7.9'
