### ISSUE TITLE
BaseQuickAdapter里面的addOnClickListener监听不到

### ISSUE THREAD

**Issue by huwencheng** [CymChad/BaseRecyclerViewAdapterHelper#657]
由于页面内容是不固定的，所以自己写了setOnClickListener，不知道是不是被自己写的setOnClickListener拦截了，不知道怎么处理，希望帮助下，谢谢
![iour iuw49v o 7 tu hi](https://cloud.githubusercontent.com/assets/8435177/21450028/1cc47e2a-c92e-11e6-9338-0624ef56b867.png)

**Comment by AllenCoder** [comment]
这样做可能会导致点击事件最先被自定义的点击事件消费掉，建议 将reLExpress作为childView 的id添加绑定事件里，事件分发优先级 是根据你绑定的顺序决定的，对于嵌套的view，事件分发的顺序是，最先绑定的最先分发到点击事件

**Comment by huwencheng** [comment]
可以了，谢谢，是我自己的问题
