### ISSUE TITLE
请教一个recyclerView嵌套问题

### ISSUE THREAD

**Issue by ping999** [CymChad/BaseRecyclerViewAdapterHelper#665]
在recyclerView的item中嵌套另外一个子recyclerView，子recyclerView的item数量不可控，这是为什么呢？
第一个adapter部分代码：
        @Override
        protected void convert(BaseViewHolder baseViewHolder, Info info) {
            baseViewHolder.setText(R.id.item_text , into.getitle);
            setItemAdapter(info.getPicList); // 设置picList的recyclerView
        }

**Comment by CymChad** [comment]
子recyclerView的item数量不可控？

**Comment by ping999** [comment]
举个例子，第一个item的子recyclerView的data.size为6，第二个子recycler的data.size为5，显示出来的效果是第一个item子recyclerView显示5个出来，第二个item为空

**Comment by ping999** [comment]
举个例子，第一个item的子recyclerView的data.size为6，第二个子recycler的data.size为5，显示出来的效果是第一个item子recyclerView显示5个出来，第二个item子recyclerView为空。
当页面下滑到 4 5 6的item时，再上滑回第一个item，他的子recylerView内容数量改变了，同时样式也改变了

**Comment by CymChad** [comment]
我这边试一下

**Comment by CymChad** [comment]
刚测试了一下，没有发现你说的情况

**Comment by CymChad** [comment]
数据正常显示。

**Comment by ping999** [comment]
蒽，单独试了一下也没问题，对比发现是我编写代码逻辑问题
问题：if(adapter== null){}else adapter.setnewdata();这样编写就会出现那种问题。thx

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.7.9'
