### ISSUE TITLE
recycleview局部刷新的小问题

### ISSUE THREAD

**Issue by xiongke15117937934** [CymChad/BaseRecyclerViewAdapterHelper#667]
比如：我给recycleview数据最后一条线不显示，但是翻页加载的时候调用的是这个
`loadMoreComplete();`就会导致，上个线没有刷新出来。
除非再次调用`notifyDataSetChanged()`才能刷新出来，有没有什么好的办法呢？

**Comment by 1109993488** [comment]
麻烦贴一下分割线的代码

**Comment by xiongke15117937934** [comment]
![image](https://cloud.githubusercontent.com/assets/19948815/21512088/d09fa8c6-cce3-11e6-9c78-b2a1ecd75928.png)
![image](https://cloud.githubusercontent.com/assets/19948815/21512097/eef31402-cce3-11e6-8491-fbe0a12604cd.png)
![image](https://cloud.githubusercontent.com/assets/19948815/21512103/095aefd6-cce4-11e6-82c6-a78d36203800.png)
![image](https://cloud.githubusercontent.com/assets/19948815/21512107/1615e46a-cce4-11e6-9591-c1ce43b51afe.png)
![image](https://cloud.githubusercontent.com/assets/19948815/21512109/1d4b257e-cce4-11e6-8c55-ef837c9abe0f.png)

写的是测试用例比较简单的代码。

**Comment by 1109993488** [comment]
dividerPaint写的有问题吧？

**Comment by Seasonxx** [comment]
我也遇到了一样的问题
