### ISSUE TITLE
使用横向RecyclerView时添加headerView,headerView是在RecyclerView左边.期望有一个添加在头部的功能

### ISSUE THREAD

**Issue by qzxing** [CymChad/BaseRecyclerViewAdapterHelper#668]
GridLayoutManager layoutManager = new GridLayoutManager(getActivity(), 2);
layoutManager.setOrientation(GridLayoutManager.HORIZONTAL);
homeListView.setLayoutManager(layoutManager);
我使用以上代码完成横向滑动列表。
使用addHeaderView()方法时无法使headerView在头部，headerView始终是在列表视图的左边

**Comment by CymChad** [comment]
headerView也是一个item，所以横向的就是在左边。

**Comment by qzxing** [comment]
可以提出新增这个功能不，还是有很多项目虽然是横向的，但是headerView会在顶部，footview在底部这样的需求

**Comment by CymChad** [comment]
这个可以用竖的Rv+横的Rv来解决
