### ISSUE TITLE
header离开界面时滑动距离从0重新计算了

### ISSUE THREAD

**Issue by xyzeng12** [CymChad/BaseRecyclerViewAdapterHelper#669]
我需要获取滑动的距离（相对于header顶部，而不是手指按下时），使用的int offset = recyclerView.computeVerticalScrollOffset();。但是上滑时当header离开界面时offset又从0开始计算了。

**Comment by CymChad** [comment]
header就是一个item的没有做过特殊处理。

**Comment by xyzeng12** [comment]
哦哦，谢谢，我已经结合findFirstVisibleItemPosition把我需要的效果实现了

**Comment by CymChad** [comment]
赞 @xyzeng12
