### ISSUE TITLE
minSdkVersion修改

### ISSUE THREAD

**Issue by Saxxhw** [CymChad/BaseRecyclerViewAdapterHelper#677]
请问可以将minSdkVersion修改为11吗？我迁出了一份项目运行了一下，测试后发现最低版本是可以支持到11的，我想直接在Studio里依赖这个项目，但是因为项目需求又不能修改我本地的minSdkVersion，拷贝代码的话不方便以后及时更新这个库，所以如果可以的话麻烦修改下minSdkVersion的版本把，谢谢

**Comment by CymChad** [comment]
可以

**Comment by CymChad** [comment]
com.github.CymChad:BaseRecyclerViewAdapterHelper:2.7.2

**Comment by Saxxhw** [comment]
谢谢！
