### ISSUE TITLE
上拉加载

### ISSUE THREAD

**Issue by wasneverlonely** [CymChad/BaseRecyclerViewAdapterHelper#679]
如果我只加载到一条数据 它会无限加载数据  只到数据填充满为止 这个怎么解决

**Comment by CymChad** [comment]
你可以调用加载完毕的API，这样就不会加载了。

**Comment by haoweizero** [comment]
我也是只是加载一条数据，然后我也调用了加载完毕的api，但是我的情况跟他是相反的，我的是出现了崩溃
崩溃信息：
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling.
错误代码位置：
` /**
   * 加载更多
   */
  @Override public void onLoadMoreRequested() {
    if (mData.size() < 20){
      mAdapter.loadMoreEnd(true);
    } else {
      pageNumber++;
      //拿到新页面的数据
      getData(userName, pageNumber, deviceCode.getText().toString(),
          companyName.getText().toString(), companyAddress.getText().toString(), startDate,
          endDate, deviceStatus, deviceType, qhdm, source, "", "", ADDMORE);
    }
  }
}`

还有一个问题就是进入这个页面之后会自动运行滑动监听。
`compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.0'`
这是我的版本号。
