### ISSUE TITLE
怎么加入 swipe layout 显示一个删除按钮

### ISSUE THREAD

**Issue by jiechu** [CymChad/BaseRecyclerViewAdapterHelper#68]
如题

**Comment by CymChad** [comment]
swipe layout ？

**Comment by MoriatyHe** [comment]
我们要明白一下侧滑删除的原理，首先是监控侧滑这个手势，然后显示一个或几个按钮，再点击执行相应的操作，所以需要变化的是itemview 的布局以及添加对按钮的监听事件。

**Comment by jiechu** [comment]
我已经实现了，
<com.chauthai.swipereveallayout.SwipeRevealLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/white"
    app:dragEdge="right"
    app:mode="same_level">
<FrameLayout/>
<FrameLayout/>
</com.chauthai.swipereveallayout.SwipeRevealLayout>

**Comment by bowen-xiao** [comment]
新的问题又来了，com.chauthai.swipereveallayout.SwipeRevealLayout 集成后，发现不能拖动排序了

**Comment by CymChad** [comment]
可组合BRVAH使用：https://github.com/anzaizai/EasySwipeMenuLayout
