### ISSUE TITLE
请教关于子控件的点击事件

### ISSUE THREAD

**Issue by yezizaiqiutian** [CymChad/BaseRecyclerViewAdapterHelper#683]
请问当点击一个子控件怎么让另一个子控件进行改变(点击暂停改变颜色或改变进度条样式)
SimpleOnItemChildClick(BaseQuickAdapter adapter, View view, int position)里的adapter怎么能获得BaseViewHolder去获得控件?

**Comment by AllenCoder** [comment]
数据绑定子控件，点击子控件，修改数据，通知刷新
