### ISSUE TITLE
material-spinner-1.0.5.aar 下面drawable-xxhdpi-v4\ms__shadow_background.9.png

### ISSUE THREAD

**Issue by ainiu** [CymChad/BaseRecyclerViewAdapterHelper#687]
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file D:\gitdemo\BaseRecyclerViewAdapterHelper-master\BaseRecyclerViewAdapterHelper-master\app\build\intermediates\exploded-aar\BaseRecyclerViewAdapterHelper-master\material-spinner-1.0.5\unspecified\res\drawable-xxhdpi-v4\ms__shadow_background.9.png into D:\gitdemo\BaseRecyclerViewAdapterHelper-master\BaseRecyclerViewAdapterHelper-master\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\ms__shadow_background.9.png

**Comment by CymChad** [comment]
你的工程路径太长了

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/365

**Comment by Jeffery336699** [comment]
谢谢!我也遇到这样的问题,用你的方法解决了
