### ISSUE TITLE
LinearLayoutManager.HORIZONTAL?

### ISSUE THREAD

**Issue by yanglichuan** [CymChad/BaseRecyclerViewAdapterHelper#688]
when set LinearLayoutManager.HORIZONTAL

the data list  is 9 
but  ui show only 8   lost the last one 

when set  LinearLayoutManager.VERTICAL 
the data list is 9
ui show 9  nomal 

why?

**Comment by CymChad** [comment]
Look at your code

**Comment by CymChad** [comment]
Reset setAdapter
