### ISSUE TITLE
没有更多数据的位置问题

### ISSUE THREAD

**Issue by bobingxin** [CymChad/BaseRecyclerViewAdapterHelper#689]
item的个数是奇数的情况
1.原来是layoutmanager的是gridlayoutmanager，没有更多数据的位置是正确的。
2.将gridlayoutmanager改为linearlayoutmanager，没有更多数据的位置是正确的。
3.将linearlayoutmanager改为gridlayoutmanager，没有更多数据的位置错误。

**Comment by 1109993488** [comment]
重新setAdapter就好了
