### ISSUE TITLE
save demo img

### ISSUE THREAD

**Issue by CymChad** [CymChad/BaseRecyclerViewAdapterHelper#694]

**Comment by CymChad** [comment]
![Uploading 6.png…]()
![Uploading 2.png…]()
![Uploading 1.png…]()
![Uploading 12.png…]()
![Uploading 11.png…]()
![Uploading 10.png…]()
![Uploading 9.png…]()
![Uploading 8.png…]()
![Uploading 7.png…]()
![Uploading 5.png…]()
![Uploading 4.png…]()
![Uploading 3.png…]()
![Uploading animation.gif…]()
![Uploading chlid_click.gif…]()

![Uploading demo.gif…]()
![Uploading drag_item.gif…]()
![Uploading empty_view.gif…]()
![Uploading expandable_item.gif…]()
![Uploading header_footer.gif…]()
![Uploading item_click.png…]()
![Uploading item_view.png…]()
![Uploading load_more.gif…]()
![Uploading logo.jpg…]()
![Uploading multiple_demo.png…]()
![Uploading multiple_item.gif…]()
![Uploading section_headers.gif…]()

**Comment by CymChad** [comment]
![1](https://cloud.githubusercontent.com/assets/7698209/21665836/1156b45e-d329-11e6-8ab0-c3b564042215.png)

**Comment by CymChad** [comment]
![2](https://cloud.githubusercontent.com/assets/7698209/21665844/1e00b3b2-d329-11e6-833e-dd1cb50c629b.png)

**Comment by CymChad** [comment]
![1](https://cloud.githubusercontent.com/assets/7698209/21665903/73b5dc2e-d329-11e6-813d-015ec12ab505.png)
![2](https://cloud.githubusercontent.com/assets/7698209/21665902/738a424e-d329-11e6-9904-46cc684a6df2.png)
![6](https://cloud.githubusercontent.com/assets/7698209/21665901/738a0644-d329-11e6-8741-c42085793057.png)
![12](https://cloud.githubusercontent.com/assets/7698209/21665905/73c84d96-d329-11e6-9360-15da8867a6f8.png)
![11](https://cloud.githubusercontent.com/assets/7698209/21665906/73d82446-d329-11e6-8780-e1ea9b27ccf8.png)
![10](https://cloud.githubusercontent.com/assets/7698209/21665909/73e19314-d329-11e6-930c-4155d67e9bc2.png)
![9](https://cloud.githubusercontent.com/assets/7698209/21665910/73e2162c-d329-11e6-8a74-22f5b793c938.png)
![8](https://cloud.githubusercontent.com/assets/7698209/21665907/73e15a98-d329-11e6-9ec6-1515f8996646.png)
![7](https://cloud.githubusercontent.com/assets/7698209/21665908/73e174ce-d329-11e6-827b-5c000c8cc20b.png)
![5](https://cloud.githubusercontent.com/assets/7698209/21665911/73f66050-d329-11e6-81c5-4a09f89a8ac0.png)
![4](https://cloud.githubusercontent.com/assets/7698209/21665912/74108674-d329-11e6-9cf4-27aff5daf0e5.png)
![3](https://cloud.githubusercontent.com/assets/7698209/21665913/741111b6-d329-11e6-929c-dbd47640c9a4.png)

**Comment by CymChad** [comment]
![animation](https://cloud.githubusercontent.com/assets/7698209/21666249/8498245a-d32b-11e6-80c8-103ddec5c390.gif)
![chlid_click](https://cloud.githubusercontent.com/assets/7698209/21666251/8498656e-d32b-11e6-8d4c-437f35f4258b.gif)
![drag_item](https://cloud.githubusercontent.com/assets/7698209/21666252/849885bc-d32b-11e6-86e1-7b856da8bf59.gif)
![empty_view](https://cloud.githubusercontent.com/assets/7698209/21666253/8498cb08-d32b-11e6-926e-b160e0c9a11b.gif)
![expandable_item](https://cloud.githubusercontent.com/assets/7698209/21666250/84983422-d32b-11e6-8e44-1887fdf752d4.gif)
![header_footer](https://cloud.githubusercontent.com/assets/7698209/21666254/849903b6-d32b-11e6-90f8-d88f6fdf0005.gif)
![item_click](https://cloud.githubusercontent.com/assets/7698209/21666255/84c1f5dc-d32b-11e6-9b12-10cde43a02b8.png)
![item_view](https://cloud.githubusercontent.com/assets/7698209/21666256/84c3e0ae-d32b-11e6-820d-26e41464f473.png)
![load_more](https://cloud.githubusercontent.com/assets/7698209/21666257/84c50ae2-d32b-11e6-8a7f-59b7e00e78e6.gif)
![logo](https://cloud.githubusercontent.com/assets/7698209/21666258/84d627c8-d32b-11e6-9912-4d36e82a2eb3.jpg)
![multiple_demo](https://cloud.githubusercontent.com/assets/7698209/21666259/84dd82e8-d32b-11e6-914f-a7a5ac2ebe05.png)
![multiple_item](https://cloud.githubusercontent.com/assets/7698209/21666260/84ee32b4-d32b-11e6-92be-121349a7d066.gif)
![section_headers](https://cloud.githubusercontent.com/assets/7698209/21666261/84f190da-d32b-11e6-93b8-fdf2e6bebdbd.gif)

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/21709381/923fdd64-d41b-11e6-8298-9bd1e427d636.png)

**Comment by CymChad** [comment]
![1024x500](https://cloud.githubusercontent.com/assets/7698209/25030068/f7b45d2a-20f4-11e7-8705-715f72144330.png)

**Comment by CymChad** [comment]
![1024x500 1](https://cloud.githubusercontent.com/assets/7698209/25030981/e09bcf0e-20fb-11e7-8f17-e9b257ea6bd3.png)

**Comment by CymChad** [comment]
![1024x500](https://cloud.githubusercontent.com/assets/7698209/25510674/8dae183e-2bf4-11e7-9cd5-525227bfd7d9.jpg)

**Comment by PeanutZhang** [comment]
如何给条目添加侧滑删除按钮呢

**Comment by 1242128273wangpeng** [comment]
如何给条目添加侧滑删除按钮呢

**Comment by CymChad** [comment]
@PeanutZhang @1242128273wangpeng   https://github.com/anzaizai/EasySwipeMenuLayout

**Comment by Adaclass** [comment]
头部可以添加banner 吗？我怎么添加就报错了

**Comment by hs4rzo** [comment]
good
