### ISSUE TITLE
自定义BaseViewHolder以后，上拉加载更多到最后一页加载完成后动画不消失

### ISSUE THREAD

**Issue by DebugKit** [CymChad/BaseRecyclerViewAdapterHelper#698]
自定义的BaseViewHolder ：
public class BaseRcViewHolder extends BaseViewHolder {
    public BaseRcViewHolder(View view) {
        super(view);
        AutoUtils.auto(view);
    }
}

自定义的BaseQuickAdapter：
public abstract class BaseRcQuickAdapter<T> extends BaseQuickAdapter<T,BaseRcViewHolder> {
    public BaseRcQuickAdapter(int layoutResId, List data) {
        super(layoutResId, data);
    }

    @Override
    protected BaseRcViewHolder createBaseViewHolder(View view) {
        return new BaseRcViewHolder(view);
    }
}

上拉加载的监听事件：
mAdapter.setOnLoadMoreListener(new BaseRcQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                mRecycler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        if (mCurrentPage >= TOTAL_PAGE) {
                            //数据全部加载完毕
                            LogUtil.e("数据全部加载完毕");
                            mAdapter.loadMoreEnd();
                        } else {
                            LogUtil.e("加载更多");
                            isRefresh = false;
                            mCurrentPage++;
                            mPresenter.getHypertensionRecordList();
                        }
                    }
                }, LOADING_DELAY);
            }
        });

数据获取成功后回调里面的方法：
if (isRefresh) {     
                TOTAL_PAGE = data.getPageTotal();
                mBPLineEntities.clear();
                mBPLineEntities.addAll(entities);
                mAdapter.setNewData(mBPLineEntities);
            } else {
                mBPLineEntities.addAll(entities);
                mRecycler.post(new Runnable() {
                    @Override
                    public void run() {
                        if (mCurrentPage == TOTAL_PAGE) {
                            mAdapter.loadMoreEnd();
                        } else {
                            mAdapter.loadMoreComplete();
                        }
                    }
                });
            }
设置为 mAdapter.loadMoreEnd(true);会隐藏，但是我想让他显示为暂无更多数据

**Comment by DebugKit** [comment]
没有，用的默认的LoadMoreView

**Comment by 1109993488** [comment]
不自定义BaseViewHolder没问题？按理说跟BaseViewHolder没关系的。是不是loadMoreEnd后别的地方又调loadMoreComplete了？还是不行的话贴下完整代码

**Comment by DebugKit** [comment]
使用自带的BaseViewHolder也是一样的情况，
下面是完整代码

public class BloodSugarRecordActivity extends BaseActivity implements SwipeRefreshLayout
        .OnRefreshListener, BloodSugarContract.IBloodSugarView {

    private static final int ADD_CODE = 0x0001;

    private ArrayMap<String, String> eatType = new ArrayMap<>();
    private ArrayMap<String, String> measureState = new ArrayMap<>();

    @BindView(R.id.head_left_image)
    ImageView mHeadLeftImage;
    @BindView(R.id.head_center_text)
    TextView mHeadCenterText;
    @BindView(R.id.recycler)
    RecyclerView mRecycler;
    @BindView(R.id.refresh)
    SwipeRefreshLayout mRefresh;
    @BindView(R.id.layout_empty)
    ViewStub mLayoutEmpty;

    private BaseRcQuickAdapter mAdapter;

    private BloodSugarPresenter mPresenter = new BloodSugarPresenter(this);

    private FamilyMemberEntity mMemberEntity;
    private long startDate;
    private long endDate;

    private List<BloodSugarEntity> mSugarEntities;

    private boolean isRefresh = true;

    private int mPageSize = 30;

    private int TOTAL_PAGE;//列表总页数
    private int mCurrentPage = 1;//当前页数

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        contentView(R.layout.activity_record_blood_sugar);
        super.onCreate(savedInstanceState);
        mMemberEntity = getIntent().getParcelableExtra("info");
        startDate = getIntent().getLongExtra("start", 0);
        endDate = getIntent().getLongExtra("end", 0);

        initView();
        initEvent();
    }


    private void initEvent() {
        mRefresh.setOnRefreshListener(this);

        mAdapter.setOnLoadMoreListener(new BaseRcQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                mRecycler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        LogUtil.e("执行了request");
                        LogUtil.e("bocomCurrentPage:" + mCurrentPage);
                        if (mCurrentPage >= TOTAL_PAGE) {
                            //数据全部加载完毕
                            LogUtil.e("数据全部加载完毕");
                            mAdapter.loadMoreEnd(true);
                        } else {
                            LogUtil.e("加载更多");
                            isRefresh = false;
                            mCurrentPage++;
                            mPresenter.getBloodSugerRecordList();
                        }
                    }

                }, LOADING_DELAY);
            }
        });
    }

    private void initView() {

        eatType.put("1", "早餐");
        eatType.put("2", "午餐");
        eatType.put("3", "晚餐");

        measureState.put("0", "前");
        measureState.put("1", "后一小时");
        measureState.put("2", "后两小时");
        measureState.put("3", "后三小时");

        mHeadLeftImage.setVisibility(View.VISIBLE);
        mHeadCenterText.setVisibility(View.VISIBLE);

        mHeadCenterText.setText("血糖记录");

        mRecycler.setLayoutManager(new LinearLayoutManager(this));
        mRecycler.setHasFixedSize(true);

        mSugarEntities = new ArrayList<>();
        mAdapter = new BaseRcQuickAdapter<BloodSugarEntity>(R.layout
                .item_record_blood_sugar, mSugarEntities) {

            @Override
            protected void convert(BaseRcViewHolder helper, BloodSugarEntity item) {
                int position = helper.getLayoutPosition();

                if (position == mSugarEntities.size() - 1) {//如果是最后一条，肯定会现实年月日
                    helper.setVisible(R.id.item_date_tv, true)
                            .setVisible(R.id.item_node_image, true)
                            .setVisible(R.id.cut_off_rule, true);
                    TextView textView = helper.getView(R.id.item_record_blood_pressure_date_tv);
                    textView.setText(CalendarUtil.dateToStr(new Date(item.getMeasuringDateStamp()
                    ), CalendarUtil.SLASH_TYPE));
                } else if (!(mSugarEntities.get(position).getMeasuringDateStamp() ==
                        mSugarEntities.get(position + 1).getMeasuringDateStamp()))
                {//如果当前item的时间和下一条的item的时间不想等，则表示此条item是当天的第一条，则显示年月日
                    helper.setVisible(R.id.item_date_tv, true)
                            .setVisible(R.id.item_node_image, true)
                            .setVisible(R.id.cut_off_rule, true);
                    TextView textView = helper.getView(R.id.item_record_blood_pressure_date_tv);
                    textView.setText(CalendarUtil.dateToStr(new Date(item.getMeasuringDateStamp()
                    ), CalendarUtil.SLASH_TYPE));
                } else {
                    helper.setVisible(R.id.item_date_tv, false)
                            .setVisible(R.id.item_node_image, false)
                            .setVisible(R.id.cut_off_rule, false);
                }

                helper.setText(R.id.item_time_tv, CalendarUtil.dateToStr(new Date(item
                        .getMeasuringTimeStamp()), CalendarUtil.TIME_TYPE))
                        .setText(R.id.item_type_tv, eatType.get(item.getEatCode()) + measureState
                                .get(item.getMeasureState()))
                        .setText(R.id.item_blood_sugar_tv, item.getBloodSuger() + "mmol/L");

                if (item.getDetectionResult().equals("3")) {
                    helper.setImageResource(R.id.item_index_image, R.mipmap.index_low);
                } else if (item.getDetectionResult().equals("1")) {
                    helper.setImageResource(R.id.item_index_image, R.mipmap.index_normal);
                } else if (item.getDetectionResult().equals("2")) {
                    helper.setImageResource(R.id.item_index_image, R.mipmap.index_hight);
                }

            }
        };

        mAdapter.setEnableLoadMore(true);
        mAdapter.openLoadAnimation(BaseRcQuickAdapter.SLIDEIN_BOTTOM);
        mAdapter.setAutoLoadMoreSize(1);

        mRecycler.setAdapter(mAdapter);

        mRefresh.setColorSchemeResources(R.color.color_53e0d7);

        startRefresh();
        LogUtil.e("initView完成！");
    }

    @OnClick({R.id.head_left_show})
    public void bindClick(View view) {
        switch (view.getId()) {
            case R.id.head_left_show:
                finish();
                break;
            default:
                break;
        }
    }


    @Override
    public String getUid() {
        return App.getInstance().getUser().getUid();
    }

    @Override
    public String getHealthFileCode() {
        return mMemberEntity.getHealthFileCode();
    }

    @Override
    public long getStartTime() {
        return 0;
    }

    @Override
    public long getEndTime() {
        return 0;
    }

    @Override
    public int getPageSize() {
        return mPageSize;
    }

    @Override
    public int getPageNo() {
        return mCurrentPage;
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == ADD_CODE && resultCode == RESULT_OK) {
            mPresenter.getBloodSugerRecordList();
        }
    }


    @Override
    public void onLoadSuccess(MyBloodSugarEntity data) {
        stopRefresh();
        List<BloodSugarEntity> entities = data.getList();
        if (entities.size() == 0) {
            mLayoutEmpty.setVisibility(View.VISIBLE);
            TextView mTextContent = (TextView) findViewById(R.id.textcontent);
            TextView mTextClick = (TextView) findViewById(R.id.textclick);
            mTextContent.setText("暂无血糖记录");
            mTextClick.setText("点击添加");
            mTextClick.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    mLayoutEmpty.setVisibility(View.GONE);
                    Intent intent = new Intent(BloodSugarRecordActivity.this,
                            AddBloodSugarActivity.class);
                    intent.putExtra("healthFileCode", mMemberEntity.getHealthFileCode());
                    startActivityForResult(intent, ADD_CODE);
                }
            });
        } else {
            LogUtil.e("boco:" + isRefresh);
            if (isRefresh) {
                TOTAL_PAGE = data.getPageTotal();
                mSugarEntities.clear();
                mSugarEntities.addAll(entities);
                mAdapter.setNewData(mSugarEntities);
            } else {
                mSugarEntities.addAll(entities);
                mRecycler.post(new Runnable() {
                    @Override
                    public void run() {
                        if (mCurrentPage == TOTAL_PAGE) {
                            mAdapter.loadMoreEnd();
                        } else {
                            mAdapter.loadMoreComplete();
                        }
                    }
                });
            }
        }
    }

    @Override
    public void onLoadFailed(String result) {
        stopRefresh();
        Toast.makeText(this, result, Toast.LENGTH_SHORT).show();

        mLayoutEmpty.setVisibility(View.VISIBLE);
        TextView mTextContent = (TextView) findViewById(R.id.textcontent);
        TextView mTextClick = (TextView) findViewById(R.id.textclick);
        mTextContent.setText(result);
        mTextClick.setText("点击重试");
        mTextClick.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mLayoutEmpty.setVisibility(View.GONE);
                mCurrentPage = 1;
                mPresenter.getBloodSugerRecordList();
            }
        });
    }

    @Override
    public void onRefresh() {
        isRefresh = true;
        mCurrentPage = 1;
        mPresenter.getBloodSugerRecordList();
    }

    private void startRefresh() {
        isRefresh = true;
        mRefresh.post(new Runnable() {
            @Override
            public void run() {
                mRefresh.setRefreshing(true);
            }
        });
        onRefresh();
    }

    public void stopRefresh() {

        mRefresh.post(new Runnable() {
            @Override
            public void run() {
                mRefresh.setRefreshing(false);
            }
        });
    }

}

**Comment by 1109993488** [comment]
你把`mSugarEntities.addAll(entities);`替换为`mAdapter.addData(entities);`试试

**Comment by DebugKit** [comment]
OK,就是这个问题，谢谢！
