### ISSUE TITLE
EditText in HeadView lost focus on notifyDataSetChange

### ISSUE THREAD

**Issue by biaomingzhong** [CymChad/BaseRecyclerViewAdapterHelper#70]
EditText 在HeadVIew中，使用了您的Adapter，相当于在RecyclerView的第一个元素，每次notifyDataSetChange的时候都会更新这个HeadView；

**问题是，我的需求是监听EditText，根据输入筛选列表内容，但是每输入一个会notifyDataSetChange，然后用户就没法连续输入第二个字了，输入一个字，notify的时候，EditText就失去焦点了**

**Comment by CymChad** [comment]
那个EditText本身不应该放到header

**Comment by biaomingzhong** [comment]
UI设计没办法改，是否有技巧可以不更新0，notify其他的更新

**Comment by CymChad** [comment]
notifyItemRangeChanged();

**Comment by biaomingzhong** [comment]
改用了其他交互，感谢指导
