### ISSUE TITLE
setEmptyView(int layoutResId, ViewGroup viewGroup) viewGroup传null的时候

### ISSUE THREAD

**Issue by whb7762300** [CymChad/BaseRecyclerViewAdapterHelper#703]
myAdapter.setEmptyView(R.layout.include_getdata_erro, null);
我一般viewgroup都会传null,但是这样会导致源码中
 public void setEmptyView(int layoutResId, ViewGroup viewGroup) {
        View view = LayoutInflater.from(viewGroup.getContext()).inflate(layoutResId, viewGroup, false);
        setEmptyView(view);
    }
获取上下文报空指针,我想这个上下文是不是应该让调用者传一下?

**Comment by whb7762300** [comment]
我对其他类似方法,传viewgroup的含义还未搞懂,还望博主答疑

**Comment by CymChad** [comment]
如果不传入，layoutResId布局找不到参考对象就会自动包裹内容，导致出现设置了填充父布局属性也不占满的现象。

**Comment by MaSiYuan** [comment]
博主可以详细说明一下传入的这个ViewGroup有什么具体要求吗？我直接将RecyclerView传进去报错

**Comment by CymChad** [comment]
mQuickAdapter.setEmptyView(R.layout.loading_view, (ViewGroup) mRecyclerView.getParent());   @MaSiYuan
