### ISSUE TITLE
notify造成屏幕闪烁

### ISSUE THREAD

**Issue by guotaogithub** [CymChad/BaseRecyclerViewAdapterHelper#704]
首次进入APP，activity加载数据后，adpter.setNewData(list);然后整个activity黑屏闪烁一下，在高配手机上没有这个问题，低配手机每次必出

**Comment by CymChad** [comment]
你开启了动画吗？

**Comment by guotaogithub** [comment]
没有设置画相关

**Comment by CymChad** [comment]
你通过其他方式设置数据呢？

**Comment by guotaogithub** [comment]
好的，我试试，因为列表里加载的是视频，也有可能是视频播放造成的，我再找找原因

**Comment by CymChad** [comment]
恩，好的，谢谢配合。

**Comment by CymChad** [comment]
问题找到原因了没？

**Comment by CymChad** [comment]
有问题我再开启

**Comment by guotaogithub** [comment]
问题已经解决了，原因是在recyclerView里动态添加VideoView造成的，因为window的格式和SurfaceView的格式不一样，被销毁重建了。在activity onCreate方法里面，设置window和SurfaceView的格式，解决了这个问题

**Comment by guotaogithub** [comment]
VideoView是继承自SurfaceView。

**Comment by CymChad** [comment]
👍
