### ISSUE TITLE
recylerview中嵌套子recyclerview，给子recyclerview设置点击事件时SimpleOnItemChildClick()会被多次调用

### ISSUE THREAD

**Issue by Codyooo** [CymChad/BaseRecyclerViewAdapterHelper#707]
请问该如何给recyclerview中的子recyclerview设置点击事件，且保证子view点击事件不会在一次点击时被多次调用?

**Comment by AllenCoder** [comment]
1. 更新至最新版com.github.CymChad:BaseRecyclerViewAdapterHelper:2.7.6
2. 参考https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/680

**Comment by Codyooo** [comment]
@AllenCoder  谢谢 我把listener写convert( )外面解决了

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.7.9'
