### ISSUE TITLE
开启动画后，进入Activity后白屏一秒的问题？

### ISSUE THREAD

**Issue by 897902334** [CymChad/BaseRecyclerViewAdapterHelper#711]
我用了大神写的库，用到了我的程序中，设置了动画之后呢，进入Activity后 屏幕白白的一秒后，数据才能出来，设置假数据也是如此，  把动画去掉后就快多了 直接显示数据，这个在低配手机上很明显，高配手机不怎么明显。麻烦问下，这个动画问题可否优化一下？？？

**Comment by CymChad** [comment]
第一页也是有动画的，不过是同时显示就同时进行了动画。

**Comment by CymChad** [comment]
这样我写一个方法，你设置一个数量，就可以控制一定数量的item不执行动画了。

**Comment by 897902334** [comment]
嗯嗯，谢谢回答, 这个原因我觉得就是，首次进来执行了一次动画效果，导致数据出来的有点慢了，  怎么就不让首次进来执行动画呢？，只是让下拉的时候Item执行动画效果。！

**Comment by CymChad** [comment]
我已经改好了，等下发个版本。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.7.7'
```java
mAnimationAdapter.setNotDoAnimationCount(mFirstPageItemCount);
```

**Comment by kouxinhong** [comment]
继承自BaseSectionQuickAdapter 怎么怎样添加头部？

**Comment by CymChad** [comment]
@kouxinhong demo有源码
