### ISSUE TITLE
数据少的情况下，进入界面，会自动上拉加载是什么原因？

### ISSUE THREAD

**Issue by PrinceOfAndroid** [CymChad/BaseRecyclerViewAdapterHelper#713]
if (bean.getResult_Code().equals("0")) {
                    if (action == ACTION_REFRESH) {
                        datas.clear();
                        for (DhTaskList.ResponseBean b : bean.getResponse()) {
                            datas.add(b);
                        }
                        adapter.notifyDataSetChanged();
                        pageIndex = 1;
                        storeHousePtrFrame.refreshComplete();
                    } else {
                        for (DhTaskList.ResponseBean b : bean.getResponse()) {
                            datas.add(b);
                        }
                        adapter.notifyDataSetChanged();
                        pageIndex++;
                        if (bean.getResponse().size() == 0) {
                            adapter.loadMoreEnd();
                        } else {
                            adapter.loadMoreComplete();
                        }
                    }

**Comment by 1109993488** [comment]
添加第一页数据后判断是否满足一页，不满足调用loadMoreEnd

**Comment by PrinceOfAndroid** [comment]
恩，解决了，谢谢
