### ISSUE TITLE
Fragment中用recyclerview显示内容，当recyclerview添加headview后，fragment重新可见时，recyclerview会自动滚动到顶部

### ISSUE THREAD

**Issue by vvvSkip** [CymChad/BaseRecyclerViewAdapterHelper#717]

**Comment by CymChad** [comment]
你是不是重置了adapter？请贴出具体代码和版本号。

**Comment by CymChad** [comment]
按照wiki使用是没有问题的，有问题再提吧。

**Comment by JayneeLegend** [comment]
我遇到了和@vvvSkip 相同的问题，也是在fragment重新show的时候recycler会自动向上滚动一段距离 但为滚到最顶部

**Comment by Jozhou** [comment]
这个问题由解决方案了吗我也碰到了

**Comment by zhangshuliang** [comment]
@CymChad 能将此问题重新打开吗，我也遇到了这个问题，viewpager2承载4个fragment，我的Favorite Tab是一个recyclerview，上面粉色快是一个空布局的headerview，当我上滑一段距离让粉色块隐藏，来回切换fragment，recyclerview位置不会变化，但是只要粉色块显示一点，来回切换，recyclerview就会滚动，滚动到顶部，使粉色块全部显示。
![WechatIMG133](https://user-images.githubusercontent.com/16489590/150506610-d2794ca3-429d-499a-abcd-e7598f6ebea9.jpeg)

**Comment by zhangshuliang** [comment]
切换到Orders 或者 Account是正常的，只有从Home切换到Favorite会使recyclerview滚动到顶部，调式发现重走了adapter的convert方法，而recyclerview的滚动监听并没有执行
