### ISSUE TITLE
你好，大哥。小弟今天在使用的过程中遇到一点问题。

### ISSUE THREAD

**Issue by godmarvin** [CymChad/BaseRecyclerViewAdapterHelper#722]
使用的版本是  2.0.0的，用的是eclipse开发的，把里面的jar包和资源文件拷贝出来了。集成的是下拉刷新和上拉加载更多的功能，可上拉加载更多无法调用其onLoadMoreRequested（）方法；
主要的代码放在这里：希望有空指点一二，谢谢大哥。

‘@Override
	public void initData() {
		// TODO Auto-generated method stub
		tradeList = new ArrayList<>();
		
		swipeLayout.setOnRefreshListener(this);
		
		
		tTradeOrderInfoAdapter = new TradeOrderInfoAdapter(R.layout.item_trade_order, tradeList);
		tradeOrder = new TradeOrder();

		LinearLayoutManager mLinearLayoutManager = new LinearLayoutManager(this);
		mLinearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
		recyclerview.setLayoutManager(mLinearLayoutManager);
		recyclerview.addItemDecoration(new DividerItemDecoration(this, LinearLayoutManager.VERTICAL));
		
	//这里已经调用了加载更多的方法。
		tTradeOrderInfoAdapter.setOnLoadMoreListener(new RequestLoadMoreListener() {

			@Override
			public void onLoadMoreRequested() {
				// TODO Auto-generated method stub
				curPage ++;
				   swipeLayout.setEnabled(false);
				if(curPage>=TOTAL_COUNTER){
					tTradeOrderInfoAdapter.loadMoreEnd(true);
					return;
				}
				tTradeOrderInfoAdapter.loadMoreEnd(false);
				
				getData(curPage);
			}
		});
		tTradeOrderInfoAdapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_LEFT);
		tTradeOrderInfoAdapter.setLoadMoreView(new CustomLoadMoreView());
		
		recyclerview.setAdapter(tTradeOrderInfoAdapter);
	
		
		tTradeOrderInfoAdapter.addHeaderView(getHeadView());
		’

**Comment by CymChad** [comment]
建议你更新到最新的版本，如果有时间的话。
如果没有时间，你可以看下，下载源码。https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/v2.0.0

**Comment by CymChad** [comment]
你的代码应该是新版本的上拉代码，不是2.0.0的

**Comment by CymChad** [comment]
一次都不进吗？

**Comment by godmarvin** [comment]
大哥，我今天用你的新的包，让后把它做成了eclipse的依赖包，可以使用了，加载更多的功能可以使用了，谢谢啦。

**Comment by CymChad** [comment]
不用谢，感谢你的使用。

**Comment by chenkexu** [comment]
@godmarvin 大佬，请你您是怎么导入Eclipse里面的呢？
