### ISSUE TITLE
屏幕可见部分Item中的View状态显示问题

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [CymChad/BaseRecyclerViewAdapterHelper#725]
版本号：2.7.8
一个列表，每个Item有个收藏选项。屏幕可见部分Item第一次全是显示未收藏（实际值是收藏），断点发现有走设置收藏状态的代码，但是Item上未更新。但是滑动列表再回来，状态会更新正确。
![qq 20170113230907](https://cloud.githubusercontent.com/assets/15881869/21934862/10c2a5d4-d9e6-11e6-847d-512d95ad1d32.png)
以下是Adapter convert相关代码
![qq 20170113232103](https://cloud.githubusercontent.com/assets/15881869/21935097/0a570608-d9e7-11e6-8ebb-82bfd621451d.png)
补充：额外再加个按钮notifyDataSetChanged一下，屏幕可见部分显示就正常了。

**Comment by CymChad** [comment]
你是如何修改他的值的？

**Comment by AndroidJohnsonWang** [comment]
@CymChad 我没用去改变那个值，是可见部分的Item初始化貌似 有问题，如下GIF图的收藏图标状态
![20170114_143420](https://cloud.githubusercontent.com/assets/15881869/21952984/b9399724-da66-11e6-9ccd-634e4d417dc5.gif)

**Comment by CymChad** [comment]
恩，我这边模拟一下你那边的情况试试，你就是说，显示的值和实际的值不符合对吧？

**Comment by AndroidJohnsonWang** [comment]
嗯，只是第一次屏幕可见的Item与实际不符合

**Comment by CymChad** [comment]
你刚才那个是单独的demo吗？可以发我调试一下吗？

**Comment by peerless2012** [comment]
我碰到一个类似的问题。
我的是网格布局，外面是FrameLayout，里面一个大ImageView，一个小ImageView（带状态选择器），两个都是可以点击的。
现在的问题有两个。
1. 当在大ImageView长按的时候，小的ImageView也会显示按下状态，滑动的时候状态也不会消失，只有抬起才会消失。
2 如果长按，然后侧滑被DrawerLayout拦截，RecycleView是收到了Cancel事件，但是小ImageView的状态还是按下，无法恢复原状。

**Comment by AndroidJohnsonWang** [comment]
@peerless2012 我这个问题解决了，我把item的xml里面的默认图标src去掉,就正常了。

**Comment by CymChad** [comment]
@AndroidJohnsonWang 👍
