### ISSUE TITLE
空布局宽高问题

### ISSUE THREAD

**Issue by xiongke15117937934** [CymChad/BaseRecyclerViewAdapterHelper#728]
当adapter含有头部布局的时候添加空布局，会填满整个屏幕，能不能把最里面那个空视图的
` android.support.v7.widget.RecyclerView.LayoutParams position = new android.support.v7.widget.RecyclerView.LayoutParams(-1, -1);`
设成WRAP_CONTENT，不然老是可以向下滑动。

**Comment by 1109993488** [comment]
传入的view是wrap_content就行，具体你可以看下`setEmptyView(View);`
