### ISSUE TITLE
openLoadMore如果设置为1，下拉刷新时自动调用onLoadMore方法

### ISSUE THREAD

**Issue by chenbinzhou** [CymChad/BaseRecyclerViewAdapterHelper#730]
大神，您好：
我在使用您的框架的时候，遇到这样一个问题。设置openLoadMore为1的时候，执行下拉刷新，调用了onLoadMore方法，导致currentPage+1了。请问这是为何？设置为1的理由是：当第一次请求20条数据的时候，服务端可能返会给我有效数据为19条，这样就打不开上拉加载了。请求大神帮忙指导！谢谢

**Comment by CymChad** [comment]
你使用的版本号是？

**Comment by CymChad** [comment]
你设置小一点，可以在onLoadMore做处理。

**Comment by CymChad** [comment]
理论上来说，如果服务器给你19条，应该就没有下一页了吧？

**Comment by CymChad** [comment]
有问题再提

**Comment by haoweizero** [comment]
阿斯蒂芬
