### ISSUE TITLE
自定义ViewHolder时报强转异常

### ISSUE THREAD

**Issue by LiaoFuYun** [CymChad/BaseRecyclerViewAdapterHelper#733]
由于我需要用到UIL加载图片，所以我继承自BaseViewHolder重写了一个ViewHolder，编译没问题，运行就报BaseViewHolder不能强转成ImageLoaderQuickViewHolder的错，不知道怎么解决，求助，库是gradle上的2.7.8。
下面是我重写的ViewHolder
`public static class ImageLoaderQuickViewHolder extends BaseViewHolder {
        private static DisplayImageOptions defaultOptions = new DisplayImageOptions.Builder()
                .showImageOnFail(R.mipmap.ic_noimage)
                // 设置图片加载或解码过程中发生错误显示的图片
                .showImageForEmptyUri(R.mipmap.ic_noimage)
                .showImageOnLoading(R.mipmap.ic_noimage)
                .cacheInMemory(true) // 设置下载的图片是否缓存在内存中
                .cacheOnDisk(false) // 设置下载的图片是否缓存在SD卡中
                .considerExifParams(true).build(); // 构建完成;

        public ImageLoaderQuickViewHolder(View view) {
            super(view);
        }

        public ImageLoaderQuickViewHolder setImageUri(int viewId, Uri uri) {
            ImageView imageView = getView(viewId);
            imageView.setImageURI(uri);
            return this;
        }

        public ImageLoaderQuickViewHolder setImageURL(int viewId, String url) {
            ImageView imageView = getView(viewId);
            ImageLoader.getInstance().displayImage(url, imageView, defaultOptions);
            return this;
        }

        public ImageLoaderQuickViewHolder setImageURL(int viewId, String url, DisplayImageOptions imageOptions) {
            ImageView imageView = getView(viewId);
            if (imageOptions == null) {
                imageOptions = defaultOptions;
            }
            ImageLoader.getInstance().displayImage(url, imageView, imageOptions);
            return this;
        }

        public ImageLoaderQuickViewHolder setImageURL(int viewId, String url, int emptyResId) {
            ImageView imageView = getView(viewId);
            DisplayImageOptions options;
            if (emptyResId != -1) {
                options = new DisplayImageOptions.Builder()
                        .showImageOnFail(emptyResId)
                        // 设置图片加载或解码过程中发生错误显示的图片
                        .showImageForEmptyUri(emptyResId)
                        .showImageOnLoading(emptyResId)
                        .cacheInMemory(true) // 设置下载的图片是否缓存在内存中
                        .cacheOnDisk(false) // 设置下载的图片是否缓存在SD卡中
                        .considerExifParams(true)
                        .build(); // 构建完成
            } else {
                options = defaultOptions;
            }
            ImageLoader.getInstance().displayImage(url, imageView, options);
            return this;
        }
    }`

**Comment by CymChad** [comment]
看下你adapter的代码

**Comment by LiaoFuYun** [comment]
`public class ComplainHandleAttachAdapter extends BaseQuickAdapter<PhotoInfo, ComplainHandleAttachAdapter.ImageLoaderQuickViewHolder> {

    public ComplainHandleAttachAdapter(List<PhotoInfo> data) {
        super(R.layout.complain_attach_item, data);
    }

    @Override
    protected void convert(ImageLoaderQuickViewHolder helper, PhotoInfo item) {
        if (item instanceof ComplainHandleActivity.HandleAttachInfoBean) {
            helper.setImageResource(R.id.attachIv, ((ComplainHandleActivity.HandleAttachInfoBean) item).getResId());
        } else {
            ImageView view = helper.getView(R.id.attachIv);
            view.setImageURI(Uri.parse(item.getPhotoPath()));
        }
    }

    public static class ImageLoaderQuickViewHolder extends BaseViewHolder {
        private static DisplayImageOptions defaultOptions = new DisplayImageOptions.Builder()
                .showImageOnFail(R.mipmap.ic_noimage)
                // 设置图片加载或解码过程中发生错误显示的图片
                .showImageForEmptyUri(R.mipmap.ic_noimage)
                .showImageOnLoading(R.mipmap.ic_noimage)
                .cacheInMemory(true) // 设置下载的图片是否缓存在内存中
                .cacheOnDisk(false) // 设置下载的图片是否缓存在SD卡中
                .considerExifParams(true).build(); // 构建完成;

        public ImageLoaderQuickViewHolder(View view) {
            super(view);
        }

        public ImageLoaderQuickViewHolder setImageUri(int viewId, Uri uri) {
            ImageView imageView = getView(viewId);
            imageView.setImageURI(uri);
            return this;
        }

        public ImageLoaderQuickViewHolder setImageURL(int viewId, String url) {
            ImageView imageView = getView(viewId);
            ImageLoader.getInstance().displayImage(url, imageView, defaultOptions);
            return this;
        }

        public ImageLoaderQuickViewHolder setImageURL(int viewId, String url, DisplayImageOptions imageOptions) {
            ImageView imageView = getView(viewId);
            if (imageOptions == null) {
                imageOptions = defaultOptions;
            }
            ImageLoader.getInstance().displayImage(url, imageView, imageOptions);
            return this;
        }

        public ImageLoaderQuickViewHolder setImageURL(int viewId, String url, int emptyResId) {
            ImageView imageView = getView(viewId);
            DisplayImageOptions options;
            if (emptyResId != -1) {
                options = new DisplayImageOptions.Builder()
                        .showImageOnFail(emptyResId)
                        // 设置图片加载或解码过程中发生错误显示的图片
                        .showImageForEmptyUri(emptyResId)
                        .showImageOnLoading(emptyResId)
                        .cacheInMemory(true) // 设置下载的图片是否缓存在内存中
                        .cacheOnDisk(false) // 设置下载的图片是否缓存在SD卡中
                        .considerExifParams(true)
                        .build(); // 构建完成
            } else {
                options = defaultOptions;
            }
            ImageLoader.getInstance().displayImage(url, imageView, options);
            return this;
        }
    }
}`

**Comment by Jarvay** [comment]
我也有这个问题，继承BaseViewHolder的ViewHolder只是添加了一个简单的方法

**Comment by qq764010928** [comment]
为什么我邮箱会受到你们回复的提醒？

**Comment by qq764010928** [comment]
噢  知道了 不知道什么时候watch了~

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Use-Custom-BaseViewHolder

**Comment by CymChad** [comment]
```java
// Override createBaseViewHolder methods
protected K createBaseViewHolder(View view) {
    return (K) new BaseViewHolder(view);
}
```

**Comment by LiaoFuYun** [comment]
非常感谢
`protected ImageLoaderQuickViewHolder createBaseViewHolder(View view) {
    return (ImageLoaderQuickViewHolder ) new BaseViewHolder(view);
}`这种方式还是会强转异常，
用这种方式成功了
`@Override
    protected ImageLoaderQuickViewHolder createBaseViewHolder(View view) {
        return new ImageLoaderQuickViewHolder(view);
    }`

**Comment by CymChad** [comment]
恩，问题解决了就好了。
