### ISSUE TITLE
onLoadMoreRequested回调问题

### ISSUE THREAD

**Issue by miaoyongjun** [CymChad/BaseRecyclerViewAdapterHelper#735]
版本:2.7.8
问题：调用adapter的loadMoreEnd方法会回调onLoadMoreRequested
设置adapter：

LinearLayoutManager manager = new LinearLayoutManager(getActivity());
recyclerView.setLayoutManager(manager);
initAdapter();
adapter.setOnLoadMoreListener(this);
 adapter.setLoadMoreView(new CustomLoadMoreView());
 recyclerView.setAdapter(adapter);

回调中的代码：

@Override
  public void onLoadMoreRequested() {
        pageIndex++;
        requestData();
    }

requestData方法是请求网络数据

数据不足时的设置：

tList.addAll(l);
                adapter.setNewData(tList);
                if (l.size() < DonateConstant.PAGE_SIZE) {
                    adapter.loadMoreEnd(true);
                }

**Comment by 1109993488** [comment]
```
        if(mCurrentPage==1){
            adapter.setNewData(list);
            if(list.size()<PAGE_SIZE){
                adapter.loadMoreEnd(true);
            }
        }else {
            adapter.addData(list);
            if(list.size()<PAGE_SIZE){
                adapter.loadMoreEnd(true);
            }else {
                adapter.loadMoreComplete();
            }
        }
```
如果走了loadMoreEnd(true)方法肯定会隐藏加载更多的

**Comment by miaoyongjun** [comment]
已经解决  是多次调用setNewData的问题
