### ISSUE TITLE
点击加载更多的ui bug

### ISSUE THREAD

**Issue by qq1728744610** [CymChad/BaseRecyclerViewAdapterHelper#737]
加载完第一页的数据后，关闭网络，点击“加载失败，请点我重试”，此时应该先隐藏加载失败的提示，再显示加载中的提示，然而加载失败的提示没有隐藏，加载中的提示显示在加载失败的下面。不知道是不是因为关闭了网络的原因，点击加载更多后又立即调用loadMoreFail()才导致加载失败的提示一直没有隐藏

**Comment by CymChad** [comment]
你的版本号是？

**Comment by CymChad** [comment]
还有你的使用代码贴一下

**Comment by qq1728744610** [comment]
用的是最新的版本，最简单的重现方式是把PullToRefreshUseActivity里的92行isErr = true注释掉，然后进入这个页面先下拉刷新一次，再滚动到底部点击加载更多，仔细看就可以看到了

**Comment by 1109993488** [comment]
这是由于通过notify更新界面的动画所致，可以通过RecyclerView.setItemAnimation(null)取消
