### ISSUE TITLE
recycleview SimpleClickListener onItemClick(BaseQuickAdapter var1..)第一个参数永远是第一次设置的adapter

### ISSUE THREAD

**Issue by proud2008** [CymChad/BaseRecyclerViewAdapterHelper#738]
recycleview 在调用多次setAdapter 
recycleview addOnItemTouchListener(new SimpleClickListener (){
onItemClick(BaseQuickAdapter var1..)
});

var1 一直是第一次设置的adapter ,而不是最新的，使用版本 2.7.2

**Comment by AllenCoder** [comment]
更新至最新版解决了这个bug
