### ISSUE TITLE
多布局报的错   求帮助

### ISSUE THREAD

**Issue by caoeryang** [CymChad/BaseRecyclerViewAdapterHelper#740]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getLayoutId(BaseMultiItemQuickAdapter.java:52)
	at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:48)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:547)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:57)

**Comment by CymChad** [comment]
你实体类没设置itemType

**Comment by caoeryang** [comment]
网络请求的数据，我的实体类直接实现MultiItemEntity接口的  这样还不行吗？
 public static final int TYPE_USER = 1;
 public static final int TYPE_SERVER = 2;

 private ListBean(int itemType){
                 this.itemType = itemType;
  }

 @Override
            public int getItemType() {
                return itemType;
            }

**Comment by caoeryang** [comment]
卡在这一天了    请大神指点迷津

**Comment by CymChad** [comment]
但是你填充数据的时候要设置具体的itemType，只要和你的adapter初始化布局设置一对一对应就不会出现问题

**Comment by caoeryang** [comment]
public WorkOrderDetailsMultipleAdapter3(List<WorkOrderDetailsBean.RetDataBean.ListBean> data) {
        super(data);

        addItemType(WorkOrderDetailsBean.RetDataBean.ListBean.TYPE_SERVER, R.layout.item_work_order_answer);
        addItemType(WorkOrderDetailsBean.RetDataBean.ListBean.TYPE_USER, R.layout.item_work_order_ask2);
    }

    @Override
    protected void convert(BaseViewHolder helper, WorkOrderDetailsBean.RetDataBean.ListBean item) {
        switch (helper.getItemViewType()) {
            case WorkOrderDetailsBean.RetDataBean.ListBean.TYPE_USER:
                helper.setText(R.id.tv_question,item.getDesc())
                        .setText(R.id.tv_time,item.getCreate_time());

//                RecyclerView recyclerView = helper.getView(R.id.recycleView);
//                recyclerView.setLayoutManager(new LinearLayoutManager(mContext,LinearLayoutManager.HORIZONTAL,false));
//                ImgAdapter adapter = new ImgAdapter(item.getPic_list());
//                recyclerView.setAdapter(adapter);
                break;
            case WorkOrderDetailsBean.RetDataBean.ListBean.TYPE_SERVER:

                break;
        }

**Comment by caoeryang** [comment]
我不知道是什么问题。。。

**Comment by CymChad** [comment]
看下你数据加载的时候有没有设置itemType？

**Comment by CymChad** [comment]
你可以看下demo，从加载数据，到设置多布局，到数据填充。只要姿势对了，就不会有问题。

**Comment by CymChad** [comment]
问题解决了没？

**Comment by caoeryang** [comment]
没有  哈哈   技术不达标    不过其他功能用的都挺好    谢谢了

**Comment by CymChad** [comment]
我觉得是你在获取数据的时候没有给没一个entity设置itemType

**Comment by CymChad** [comment]
你可以参考一下，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/633

**Comment by caoeryang** [comment]
好像没有   我网络请求数据直接jsonformat了     然后实现你的接口   如何给每一个实体设置itemType呢？能给我部分代码么？

**Comment by CymChad** [comment]
你参考一下 #633的写法就可以了，不同的类型服务器肯定会给你不一样的标示对吧？你在跟进不一样的表示来转换成对应的itemtype就好了
```java
  public static class MultipleItem implements MultiItemEntity {
       public static final int TYPE_USER = 1;
       public static final int TYPE_SERVER = 2;
       // 假设服务器给了一个0代表用户，给了一个1代表服务
       public int isUser；
        public MultipleItem() {
            
        }

        @Override
        public int getItemType() {
            // 你就根据服务器给的标示来转换成对应的type
            return isUser==0？TYPE_USER：TYPE_SERVER;
        }
    }
```

**Comment by caoeryang** [comment]
万分感谢

**Comment by caoeryang** [comment]
对了    我们服务器给我的type是String类型的  没关系吧

**Comment by caoeryang** [comment]
谢谢您  我搞懂了     但是我们后台不支持     没办法   我们后台返给我们的类型是String  再次感谢

**Comment by CymChad** [comment]
没关系，string 你就缓存equest就可以了。

**Comment by caoeryang** [comment]
解决了     谢谢大神    你在哪个区  请你吃饭

**Comment by CymChad** [comment]
不用了，感谢你的使用，如果你觉得这个库好用就分享给身边的人，这是我应该做的事情。

**Comment by Y-JH** [comment]
这个问题我也遇到过，问题就出在依赖库的itemtype在addItemType(...)在它之前就被调用了，所以在setdapter之前要初始itemtype的值；

**Comment by yanxinmiao** [comment]
这个问题在以下场景也会出现
比如v1.0版本 有三种布局， 等v1.1 产品更新 到五种类型布局， 服务端也返回了五种 ，那么 v1.0版本会崩溃。
`
// 这个方法会报错， layouts.get(type)  是 null
  private int getLayoutId(int viewType) {
        return layouts.get(viewType) ;
    }

    protected void addItemType(int type, @LayoutRes int layoutResId) {
        if (layouts == null) {
            layouts = new SparseArray<>();
        }
        layouts.put(type, layoutResId);
    }
`
希望以后的版本能兼容这种情况 。
