### ISSUE TITLE
我人品不好,完全用不了

### ISSUE THREAD

**Issue by inshyma** [CymChad/BaseRecyclerViewAdapterHelper#742]
protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test);
        objects = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            objects.add(""+i);
        }
        RecyclerView viewById = (RecyclerView) findViewById(R.id.rv);
        viewById.setAdapter(new QuickAdapter());
    }
    public class QuickAdapter extends BaseQuickAdapter<String> {
        public QuickAdapter() {
            super(R.layout.tweet, objects);
        }

        @Override
        protected void convert(BaseViewHolder helper, String item) {
            helper.setText(R.id.tweetName, item);
        }
    }

-----------------------------------------------------------------------------------------------------------maven { url "https://jitpack.io" }  和  compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.9.7'
都有   使用jdk是1.8   改变gradle版本  compileSdkVersion 还有buildToolsVersion 都不能用  想问一下其他人是怎么用的

**Comment by CymChad** [comment]
如果你上面BRVAH的代码是提示出来的，那么就没问题。
还有RecyclerView设置的时候你没有设置setLayoutManager

**Comment by inshyma** [comment]
你好,setLayoutManager设置了也没显示   等会我试一下是不是因为包冲突了- - - -- - -   方便留一下交流方式么?  你的BaseRecyclerViewAdapterHelper非常好   但是我昨天的确没调出来


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年1月23日(星期一) 上午8:08
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "洋葱头 "<1217865482@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 我人品不好,完全用不了 (#742)




如果你上面BRVAH的代码是提示出来的，那么就没问题。
 还有RecyclerView设置的时候你没有设置setLayoutManager

**Comment by CymChad** [comment]
54050520

**Comment by inshyma** [comment]
已申请  谢谢大神


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年1月23日(星期一) 上午9:53
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "洋葱头 "<1217865482@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 我人品不好,完全用不了 (#742)




54050520

**Comment by inshyma** [comment]
的确是包冲突了  谢谢大神耐心说明  代码节省很多   问题已解决
