### ISSUE TITLE
下拉加载

### ISSUE THREAD

**Issue by onlywsw** [CymChad/BaseRecyclerViewAdapterHelper#745]
我在用版本2.1.3中，下拉加载只执行了一次，找不到原因

public class SearchShowActivity extends BaseActivity implements BaseQuickAdapter.RequestLoadMoreListener{
    private RecyclerView recyclerView;

    private SearchShowAdapter adapter;
    private ArrayList<String> lists;
    private ArrayList<CardGroupBean> cardGroupBeens = new ArrayList<CardGroupBean>();
    private String [] strs;
    private int page = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_search_show);
        lists = getIntent().getStringArrayListExtra(Contants.Intent_list);

        strs = new String[lists.size()];
        for (int i = 0; i < lists.size(); i++){
            Logs.e(lists.get(i));
            strs[i] = lists.get(i);
        }
        cardGroupBeens.clear();
        page = 0;
        OkGo.post(URlUtils.SEARCHINFO)
                .upJson(new Gson().toJson(new PostSeachShowBean(Contants.interface_Keywords,strs, page)))
                .execute(new StringCallback() {
                    @Override
                    public void onSuccess(String s, Call call, Response response) {
                        Logs.e("搜索返回=="+s);
                        JSONObject object = jsonStr(s);
                        if (object != null){
                            JSONArray array = object.optJSONArray(Contants.resolve_data);
                            for (int i = 0; i < array.length(); i++){
                                JSONObject itemObject = array.optJSONObject(i);
                                CardGroupBean cardGroupBean = new CardGroupBean();
                                cardGroupBean.setName(itemObject.optString("name"));
                                cardGroupBean.setIcon(itemObject.optString("icon"));
                                cardGroupBean.setCategory(itemObject.optString("category"));
                                cardGroupBean.setFolderid(itemObject.optLong("folderid"));
                                cardGroupBean.setCreatorId(itemObject.optLong("creatorId"));
                                cardGroupBeens.add(cardGroupBean);
                            }
                            adapter.setNewData(cardGroupBeens);
                            //adapter.notifyDataSetChanged();
                        }
                    }
                    @Override
                    public void onError(Call call, Response response, Exception e) {
                        super.onError(call, response, e);

                    }
                });

        initView();
    }

    private void initView(){
        recyclerView = (RecyclerView) findViewById(R.id.recylerview);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL));
        Logs.e(cardGroupBeens.size()+"");
        adapter = new SearchShowAdapter(R.layout.show_item,cardGroupBeens);
        adapter.openLoadMore(20);
        recyclerView.setAdapter(adapter);
        adapter.openLoadAnimation();

        adapter.setOnLoadMoreListener(this);

    }

    @Override
    public void onLoadMoreRequested() {
        Logs.e("加载更多");
        recyclerView.post(new Runnable() {
            @Override
            public void run() {
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        OkGo.post(URlUtils.SEARCHINFO)
                                .upJson(new Gson().toJson(new PostSeachShowBean(Contants.interface_Keywords,strs, page)))
                                .execute(new StringCallback() {
                                    @Override
                                    public void onSuccess(String s, Call call, Response response) {
                                        Logs.e("搜索返回"+page+"=="+s);
                                        adapter.loadComplete();//加载完成
                                        JSONObject object = jsonStr(s);
                                        if (object != null){
                                            JSONArray array = object.optJSONArray(Contants.resolve_data);
                                            for (int i = 0; i < array.length(); i++){
                                                JSONObject itemObject = array.optJSONObject(i);
                                                CardGroupBean cardGroupBean = new CardGroupBean();
                                                cardGroupBean.setName(itemObject.optString("name"));
                                                cardGroupBean.setIcon(itemObject.optString("icon"));
                                                cardGroupBean.setCategory(itemObject.optString("category"));
                                                cardGroupBean.setFolderid(itemObject.optLong("folderid"));
                                                cardGroupBean.setCreatorId(itemObject.optLong("creatorId"));
                                                cardGroupBeens.add(cardGroupBean);
                                            }
                                            adapter.addData(cardGroupBeens);

                                            //adapter.isLoading();

                                            //adapter.loadComplete();
                                        }
                                    }
                                    @Override
                                    public void onError(Call call, Response response, Exception e) {
                                        super.onError(call, response, e);

                                    }
                                });
                    }
                },1000);

            }
        });

    }
}

**Comment by CymChad** [comment]
我看了下你的源码，你通知的Api都没有调用。
具体你看下demo源码，
我建议你更新到最新版本。

**Comment by CymChad** [comment]
这里可以下载2.1.3的源码
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases/tag/2.1.3
