### ISSUE TITLE
大神，请问在adapter里面，convert可以通过viewHolder.getLayoutPosition()来获取position，那getView()方法里面如何获得position呢。

### ISSUE THREAD

**Issue by JueShouGitHub** [CymChad/BaseRecyclerViewAdapterHelper#746]

**Comment by CymChad** [comment]
你指的是那个地方的getView()？

**Comment by JueShouGitHub** [comment]
在adapter里面，getItemView()方法里卖弄，如何获取到position呢

**Comment by CymChad** [comment]
通过viewholder就可以拿到position，为什么还要通过viewholder. getItemView在去获取position？

**Comment by CymChad** [comment]
有问题再提

**Comment by JueShouGitHub** [comment]
嗯嗯，现在明白了，是我想错了！！！




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年2月5日(星期天) 晚上8:56
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "1172783012"<1172783012@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 大神，请问在adapter里面，convert可以通过viewHolder.getLayoutPosition()来获取position，那getView()方法里面如何获得position呢。 (#746)




有问题再提
