### ISSUE TITLE
holder.getAdapterPosition() & adapter.getParentPosition(entity)

### ISSUE THREAD

**Issue by hxxxxxxxk** [CymChad/BaseRecyclerViewAdapterHelper#747]
你好，请问下两个方法返回结果的区别是什么？

**Comment by CymChad** [comment]
holder.getAdapterPosition()  这个是原生API，拿到当前item的位置。
adapter.getParentPosition(entity) 这个是BRVAH封装的，主要是针对IExpandable功能来做的，拿到父级的位置。

**Comment by hxxxxxxxk** [comment]
@CymChad 谢谢解答
