### ISSUE TITLE
添加头部遇到的问题    我的headview 是一个自定义组合控件   里面包含一个recycleview

### ISSUE THREAD

**Issue by caoeryang** [CymChad/BaseRecyclerViewAdapterHelper#749]
java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7109)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7073)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7061)

**Comment by 1109993488** [comment]
什么情况报错，自定义view不加RecyclerView报错吗？添加HeaderView代码

**Comment by caoeryang** [comment]
@Override
    public void onSuccess(String s, Call call, Response response) {
        Logger.e(TAG + "------" + s);
        try {
            JSONObject jo = new JSONObject(s);
            String ret = jo.getString("ret");
            String code = jo.getString("code");
            if (ret.equals("0") && code.equals("1")) {
                WorkOrderDetailsBean detailsBean = new Gson().fromJson(s, WorkOrderDetailsBean.class);
                WorkOrderDetailsBean.RetDataBean retData = detailsBean.getRet_data();
                initHead(retData);//填充头部数据
                mdata = retData.getList();
                Collections.reverse(mdata);
                mAdapter.setNewData(mdata);
                mAdapter.addHeaderView(mHeadView);
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }

    }
});
private void initHead(WorkOrderDetailsBean.RetDataBean retData) {
    mTvTitle.setText(retData.getCate_name());//toolbar 标题
    mTvCategory.setText(retData.getCate_name());
    mTvTime.setText(retData.getCreate_time());
    mHeadView.setData(retData); 
头部不加recycleview也报错    貌似是我代码有问题    请指导  谢谢

------------------ 原始邮件 ------------------
发件人: "BlingBling";<notifications@github.com>;
发送时间: 2017年1月25日(星期三) 下午4:11
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "只要妳過的比我好°"<460093233@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 添加头部遇到的问题 我的headview 是一个自定义组合控件 里面包含一个recycleview (#749)




什么情况报错，自定义view不加RecyclerView报错吗？添加HeaderView代码

**Comment by 1109993488** [comment]
mHeaderView不能add多次，第二次可以不add

**Comment by 1109993488** [comment]
@caoeryang 解决了吗

**Comment by caoeryang** [comment]
还没有呢  不知如何避免

**Comment by caoeryang** [comment]
我在onstart里面先判断是否有头部 如果有 我就remove   可是没效果

**Comment by 1109993488** [comment]
描述下什么时候出现异常，是每次都出现还是第二次onSuccess时异常的，如果第二次刷新异常，在addHeaderView前加removeAllHeaderView

**Comment by caoeryang** [comment]
解决了  谢谢
