### ISSUE TITLE
 dependencies添加失败：Failed to resolve

### ISSUE THREAD

**Issue by xubuhang** [CymChad/BaseRecyclerViewAdapterHelper#75]
Error:(34, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.7.9
<a href="openFile:C:/WorkSpace/svnspace/android_doctor/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by iurgnid** [comment]
have you try add this
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
in your build.gradle ?if it  also doesn't   work  , contact the author  again

**Comment by xubuhang** [comment]
我现在是直接复制library的代码到工程里运行就可以。
