### ISSUE TITLE
Demo中ExpandableUseActivity配合PinnedSectionItemDecoration点击第一个分组收缩栏不起作用

### ISSUE THREAD

**Issue by conghuahuadan** [CymChad/BaseRecyclerViewAdapterHelper#750]
你好，Demo中ExpandableUseActivity配合PinnedSectionItemDecoration点击第一个分组收缩栏不起作用
，但是添加adapter.addHeaderView(headerView)又恢复作用

源码如下

**ExpandableUseActivity**：

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_expandable_item_use);

        mRecyclerView = (RecyclerView) findViewById(R.id.rv);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));

        ArrayList<MultiItemEntity> list = generateData();
        ExpandableItemAdapter adapter = new ExpandableItemAdapter(list);

//        View headerView = getView();
//        adapter.addHeaderView(headerView);

//        View footerView = getView();
//        adapter.addFooterView(footerView);

        mRecyclerView.setAdapter(adapter);
//        mRecyclerView.addOnItemTouchListener(new MyOnItemClickListener());

        PinnedHeaderItemDecoration pinnedHeaderItemDecoration = new PinnedHeaderItemDecoration
                .Builder(ExpandableItemAdapter.TYPE_LEVEL_0)
                .create();

        mRecyclerView.addItemDecoration(pinnedHeaderItemDecoration);
    }
```
    
**ExpandableItemAdapter**：

```
    public ExpandableItemAdapter(List<MultiItemEntity> data) {
        super(data);
        addItemType(TYPE_LEVEL_0, R.layout.item_expandable_lv0);
        addItemType(TYPE_LEVEL_1, R.layout.item_expandable_lv1);
        addItemType(TYPE_PERSON, R.layout.item_text_view);
    }

    @Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
        FullSpanUtil.onAttachedToRecyclerView(recyclerView, this, TYPE_LEVEL_0);
    }

    @Override
    public void onViewAttachedToWindow(BaseViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        FullSpanUtil.onViewAttachedToWindow(holder, this, TYPE_LEVEL_0);
    }
```

![image](https://cloud.githubusercontent.com/assets/20864280/22333821/efade796-e412-11e6-8b93-80f5326ffadb.png)

另外，想问下如何在这两个分组之间添加间距？

![image](https://cloud.githubusercontent.com/assets/20864280/22333852/0d6d094c-e413-11e6-8790-c35bc5cd41a0.png)

**Comment by conghuahuadan** [comment]
作者，我找到问题的原因了，是因为悬浮列表距离顶部为0，所以只能由OnHeaderClickListener 触发，但是同时也衍生出另外一个问题，当我点击第一个伸缩栏时，会有一瞬间的闪烁，这个能否解决呢？

代码如下：

`PinnedHeaderItemDecoration pinnedHeaderItemDecoration = new PinnedHeaderItemDecoration
                .Builder(ExpandableItemAdapter.TYPE_LEVEL_0)
                .setHeaderClickListener(new MyOnHeaderClickListener())
                .create();`

`private class MyOnHeaderClickListener implements OnHeaderClickListener {

        @Override
        public void onHeaderClick(View view, int id, int position) {
            MultiItemEntity item = adapter.getItem(position);
            final Level0Item lv0 = (Level0Item) item;
            if (lv0.isExpanded()) {
                adapter.collapse(position);
            } else {
                adapter.expand(position);
            }
        }

        @Override
        public void onHeaderLongClick(View view, int id, int position) {

        }

        @Override
        public void onHeaderDoubleClick(View view, int id, int position) {

        }
    }`

**Comment by CymChad** [comment]
收到

**Comment by elfman** [comment]
一瞬间的闪烁？你看看是不是多次调用了notify进行刷新？

**Comment by conghuahuadan** [comment]
没有，你把我的代码复制Demo中运行就知道了

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/22860890/a894475c-f145-11e6-863a-2cdd99ce153c.png)

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/22860934/e799a20c-f146-11e6-89e3-c88cc55662fd.png)
你是指图片闪烁了的这一下？@conghuahuadan

**Comment by conghuahuadan** [comment]
这样吧？不知道算不算是个Bug。我用Gif截了图，图片有点大

![gif](https://cloud.githubusercontent.com/assets/20864280/22885885/4d75ebfe-f236-11e6-8e1a-b0620a54ed4f.gif)

**Comment by CymChad** [comment]
这是第三方库的时候发生的,单独使用本库不会发生这个情况。
