### ISSUE TITLE
关于给Recyclerview添加多个头布局导致的问题

### ISSUE THREAD

**Issue by androidXiaoHao** [CymChad/BaseRecyclerViewAdapterHelper#753]
您好，在使用您这个框架的时候遇到关于给Recyclerview添加多个头布局导致的问题，不知道是不是使用的姿势不对导致的还是？希望您能抽时间帮我看看，谢谢

这是我的代码
![error03](https://cloud.githubusercontent.com/assets/16314954/22627459/6b492b98-ebfe-11e6-97e9-165951cdf5d9.png)

这是报的错
![error01](https://cloud.githubusercontent.com/assets/16314954/22627465/7d48afe4-ebfe-11e6-8187-46a0d65cec91.png)

**Comment by CymChad** [comment]
你使用的版本号是？

**Comment by 1109993488** [comment]
每次onSuccess的时候创建新的headerView对象

**Comment by androidXiaoHao** [comment]
使用的是2.8.0版本的，由于我用到下拉刷新上拉加载更多的功能，然后在下拉里面再次执行这些请求，就导致了这个错误，是不是应该在下拉刷新代码中先removeAllHeaderView()？？

**Comment by 1109993488** [comment]
adapter不重新创建removeAllHeaderView可行

**Comment by androidXiaoHao** [comment]
好的，我试试

**Comment by androidXiaoHao** [comment]
在群主(也就是作者)以及群小伙伴的帮助下，我找到了导致这个问题的原因，这不是框架的问题，而是自己使用的姿势不正确。正确的姿势是这样的：
由于我们写的adapter是要继承BaseQuickAdapter的，所以当我们尽量将new adapter的代码写在需要多次调用（比如下拉刷新）的方法中的外面，并且，添加header之前需要先remove掉之前的headerView

**Comment by CymChad** [comment]
感谢你的使用
