### ISSUE TITLE
DragAndSwipe侧滑删除最后一个item

### ISSUE THREAD

**Issue by ldqmaybe** [CymChad/BaseRecyclerViewAdapterHelper#754]
刚下载下来的demo，修改ItemDragAndSwipeUseActivity。添加了上拉加载更多功能，其他不动。加载到最后“没有更多数据”后，再侧滑删除item，删到最后一个item出现
`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{3a1935ae position=0 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent}`
这个问题该如何处理呢？

**Comment by elfman** [comment]
这个错误通常是由于adapter内外数据集不一致引起的，你可以看下这篇文章[当RecyclerView遇到Inconsistency detected崩溃时](http://www.jianshu.com/p/2eca433869e9)
我猜测崩溃的原因可能是你没有调用notify来保持数据集一致

**Comment by ldqmaybe** [comment]
经测，调用notifyDataSetChanged()无碍（但是没有了动画），调用 notifyItemRemoved(pos);notifyItemRangeChanged(pos,datas.size());时就有这个问题

**Comment by elfman** [comment]
那就是你调用时的传参有问题了，不是本库的问题

**Comment by wang0168** [comment]
@ldqmaybe 遇到同样的问题，加载更多和滑动删除组合在滑动删除最后一条的时候崩溃，请问你是怎么解决的

**Comment by ldqmaybe** [comment]
@wang0168 我调用notifyDataSetChanged()，数据的position就能重新对应了，但是代价是没有了删除item的动画

**Comment by MapleDev** [comment]
我debug跟踪了一下，原因是显示 ‘没有更多数据’ 时 RecycleView#getAdapterPosition 会走2遍，后面移除pos为-1，导致了崩。所以我的解决方法是： OnItemSwipeListener#onItemSwiped之中
```
                if(mDataList.size() == 1) {
                    mAdapter.loadMoreEnd(true);
                    mAdapter.setEmptyView(R.layout.empty_view, (ViewGroup) mRecyclerView.getParent());
                }
```
