### ISSUE TITLE
请问如何限制某一个位置条目不能自由拖动，并且不能被其他位置的条目所挤占。

### ISSUE THREAD

**Issue by sj8521123** [CymChad/BaseRecyclerViewAdapterHelper#756]

**Comment by elfman** [comment]
重写`ItemDragAndSwipeCallback`的`getMovementFlags`和`onMove `方法。
`getMovementFlags`中`return makeMovementFlags(0, 0)`可让此条目不能移动。
`onMove`中`return false`可让此次移动无效，当target为你不想被挤占的条目时返回false即可

**Comment by sj8521123** [comment]
对了，按你的方式实现了，谢谢
