### ISSUE TITLE
child item点击和pull to refresh一起使用,item做删除功能

### ISSUE THREAD

**Issue by yongler** [CymChad/BaseRecyclerViewAdapterHelper#758]
当child item点击和pull to refresh一起使用,item做删除功能时,如果从第一条item开始删,这时删到开始加载更多时,就不能再加载剩下的item了,而且不能下拉刷新

**Comment by 1109993488** [comment]
已经回调加载更多，把下拉刷新给禁用了，你看下loadMoreComplete调用是否正确

**Comment by yongler** [comment]
@1109993488 好的谢谢
