### ISSUE TITLE
如果再增加一个侧滑菜单的功能就更好了

### ISSUE THREAD

**Issue by JxSx** [CymChad/BaseRecyclerViewAdapterHelper#760]
https://github.com/yanzhenjie/SwipeRecyclerView    在想如何将此项目的侧滑功能和本项目pullToRefresh结合在一起使用。

**Comment by CymChad** [comment]
多谢建议，我可以尝试一下看可不可以配合第三方的库来实现侧滑删除，此库为什么不加入侧滑其实有一个原因就是解耦，因为这个库是一个adapter，侧滑本上是对item的改变，所以完全可以不耦合。

**Comment by CymChad** [comment]
如果加好了会通知你。

**Comment by CymChad** [comment]
可组合BRVAH使用：https://github.com/anzaizai/EasySwipeMenuLayout
