### ISSUE TITLE
点击事件传递问题

### ISSUE THREAD

**Issue by abc784990536** [CymChad/BaseRecyclerViewAdapterHelper#762]
加OnItemChildClickListener，代码如下
 mBinding.recyclerView.addOnItemTouchListener(new OnItemChildClickListener() {
            @Override
            public void onSimpleItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                mAddressEntity = mAddressListAdapter.getItem(i);
                switch (view.getId()){
                    case R.id.bn_address:
                        if(mFrom==TypeConstant.SUBMINT_ORDER){
                            EventBus.getDefault().post(new CurrentAddressEvent(mAddressEntity));
                            finish();
                        }else {
                            NavigateManager.gotoEditAddress(mContext, mAddressEntity);
                        }
                        break;
                    case R.id.bn_edit:
                        NavigateManager.gotoEditAddress(mContext, mAddressEntity);
                        break;
                  
                }
            }
        });

bn_address里放着控件bn_edit，点击bn_edit事件没有传递到它，被外层的bn_address相应了，又没办法让bn_edit响应事件

**Comment by CymChad** [comment]
版本号？

**Comment by AllenCoder** [comment]
```
 viewHolder.addOnClickListener(R.id.bn_edit)

``

将 childview单独绑定，你再试一次

**Comment by abc784990536** [comment]
最新的2.8.0，我试下看看

**Comment by abc784990536** [comment]
Adapter里是这样加的，旧版和2.8.0都不行
helper.addOnClickListener(R.id.bn_address)
                .addOnClickListener(R.id.bn_edit)
                .addOnClickListener(R.id.tv_del_hit)
                .addOnClickListener(R.id.bn_del);

bn_address响应事件，点bn_edit还是bn_address响应事件，事件没有传递到子类bn_edit，被bn_address拦截了,按上面那位仁兄的方法“将 childview单独绑定，你再试一次”也不行，有没办法解决

**Comment by AllenCoder** [comment]
childview按钮的绑定遵循 优先级绑定顺序，最先绑定的优先分发，如果bn_address是父布局，bn_edit是内部的子布局，同时也需要响应点击事件，绑定顺序如下：

```java

helper.addOnClickListener(R.id.bn_edit)
.addOnClickListener(R.id.tv_del_hit)
.addOnClickListener(R.id.bn_del)
.addOnClickListener(R.id.bn_address);
```

**Comment by CymChad** [comment]
问题解决没@abc784990536

**Comment by abc784990536** [comment]
按照绑定的优先级顺序解决了，希望优化文档，在使用文档里提及这个优先级顺序，谢谢了

**Comment by AllenCoder** [comment]
好的，后续这块会优化处理，避免此内bug

**Comment by CymChad** [comment]
感谢使用，今天会把文档更新。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Add-OnItemClickLister 已更新
