### ISSUE TITLE
上拉加载问题

### ISSUE THREAD

**Issue by jinguangyue** [CymChad/BaseRecyclerViewAdapterHelper#763]
注意：在onLoadMoreRequested中添加数据要在mRecyclerView.post的Runnable中执行，否则会出现Cannot call this method while RecyclerView is computing a layout or scrolling 异常。
加载完成

如果再Runnable中执行就是在子线程中执行的， 再adddata的话就是在子线程更新ui了啊

**Comment by CymChad** [comment]
mRecyclerView.post  是ui线程

**Comment by CymChad** [comment]
可以更新ui

**Comment by CymChad** [comment]
为什么要在mRecyclerView.post 里面去做操作是因为要在mRecyclerView初始化布局之后才能在操作mRecyclerView的ui，否则会出现Cannot call this method while RecyclerView is computing a layout or scrolling

**Comment by CymChad** [comment]
你可以测试一下。

**Comment by CymChad** [comment]
有问题再提

**Comment by jinguangyue** [comment]
好的 多谢

**Comment by dingsh503** [comment]
BaseSectionQuickAdapter样式设置GridLayoutManager 样式 ;  第一层和第二层 都成为GridLayoutManager样式

**Comment by wenzhimin** [comment]
作者 您好！我在使用你的框架中遇到一个头疼的问题，上啦加载一直无限加载下去直接到后台没有更多数据返回的时候才停止！请教一下 如何解决！
