### ISSUE TITLE
onLoadMoreRequested 执行一次就没反应了

### ISSUE THREAD

**Issue by qq527743998** [CymChad/BaseRecyclerViewAdapterHelper#764]
public void onLoadMoreRequested() {
        OkGo.post(Urls.URL_RewardList)
                .tag(this)//
                .params("page", ++page)//
                .params("pagesize", Constants.PAGESIZE)//
                .execute(new JsonCallback<BaseResponse<RewardRecordEntity>>(this) {
                    @Override
                    public void onSuccess(BaseResponse<RewardRecordEntity> responseData, Call call, Response response) {

                        if (responseData.data == null || responseData.data.getList().size() == 0 || Constants.PAGESIZE > responseData.data.getList().size()) {
                            adapter.loadMoreEnd();
                        }else{
                            adapter.setEnableLoadMore(true);
                            adapter.addData(responseData.data.getList());
                        }
                        refreshLayout.setRefreshing(false);
                    }

                    @Override
                    public void onError(Call call, Response response, Exception e) {
                        super.onError(call, response, e);
                        --page;
                        adapter.loadMoreComplete();
                    }
                });
    }

方法只会执行一次 以后再次上啦不会执行。。

**Comment by qq527743998** [comment]
compile 'com.lzy.net:okgo:+'

**Comment by CymChad** [comment]
你的使用方法有误

**Comment by CymChad** [comment]
具体你可以参考demo和wiki

**Comment by CymChad** [comment]
adapter.addData(responseData.data.getList());
adapter.loadMoreComplete();
是一起使用的

错误应该用adapter. loadMoreFail()

**Comment by qq527743998** [comment]
加载更多的时候才要调用mQuickAdapter.loadMoreComplete();对吧/。。
解决了    谢谢

**Comment by CymChad** [comment]
恩 是的  感谢你的使用
