### ISSUE TITLE
点击Item重复错位

### ISSUE THREAD

**Issue by SheepYang1993** [CymChad/BaseRecyclerViewAdapterHelper#765]
点击Item重复错位
[图片](http://i1.piimg.com/567571/62ea1a5205eb2724.gif)

adapter代码:
```
    @Override
    protected void convert(final BaseViewHolder helper, final CourseListActivity.Course item) {
        helper.addOnClickListener(R.id.ll_body);
    }
```

**Comment by AllenCoder** [comment]
1. 你的图片状态的处理应该在数据层有字段保证 ，view层本身就会有缓存
2. 你更新至最新版本，在itemclick里面打印详细日志，观察是否会出现点击错乱，关于这一点，在之前版本确实出现过，后来已经修复
3. 如果重复出现，请贴出详细代码，以备我排查问题

**Comment by SheepYang1993** [comment]
已解决，之前是因为给itemview设了Tag引起的。换了个view设置tag。。。
[修改结果](http://p1.bpimg.com/567571/087a11ac071e41f5.gif)
