### ISSUE TITLE
上拉加载问题:add data()后自动向上滑动一行

### ISSUE THREAD

**Issue by ximencx** [CymChad/BaseRecyclerViewAdapterHelper#766]
操作流程：
快速向上滑动，触发上拉加载，
数据add data()后自动向上滑动一行。
造成卡顿的现象。代码按照demo写的。
怎么解决呢？？

**Comment by CymChad** [comment]
版本号？

**Comment by ximencx** [comment]
`    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.8.0'
`
经过测试，
`pullToRefreshAdapter.setAutoLoadMoreSize(count);`
与这个api有关，
快速下滑有缓存（加载快）的情况下，会多向上滚动count行
条目高度较高的情况比较明显，代码里默认最小1。
如果是0应该就好了。

**Comment by CymChad** [comment]
恩，你直接不设置就好了。这个是提起加载的api。

**Comment by ximencx** [comment]
adapter源码里默认最少预览1，所以不设置也会出错

**Comment by ximencx** [comment]
@CymChad 哥们这个问题没解决啊！！！能否给个联系方式 给你看下效果

**Comment by CymChad** [comment]
收到
