### ISSUE TITLE
OnItemClickListener 响应，OnItemChildClickListener不响应   求指导。版本  2.7.8

### ISSUE THREAD

**Issue by jxpanda** [CymChad/BaseRecyclerViewAdapterHelper#772]
![qq 20170215112526](https://cloud.githubusercontent.com/assets/7555777/22959462/89034d06-f371-11e6-954f-eb40348ccbfd.png)
![qq 20170215112554](https://cloud.githubusercontent.com/assets/7555777/22959467/8ebaf410-f371-11e6-9f24-9d069577ff38.png)

**Comment by CymChad** [comment]
是不是因为没有走case的代码？

**Comment by jxpanda** [comment]
不是，这个方法都没有走进来。

**Comment by AllenCoder** [comment]
你是否还有其他绑定事件？请贴出绑定部分的完整代码，以便排查问题？或者你是否在子控件里绑定了其他的点击事件，优先消费掉了点击事件？

**Comment by jxpanda** [comment]
应该是我自己的原因引起的， 我再排查下。谢谢~~

**Comment by jxpanda** [comment]
代码没为题，AS重启一遍就可以了， 不知道这是什么鬼，昨天还不行， 刚刚打开AS一跑，就正常了。
