### ISSUE TITLE
大神你好，我想问一个关于加载空指针的问题

### ISSUE THREAD

**Issue by JueShouGitHub** [CymChad/BaseRecyclerViewAdapterHelper#775]
如题，我在我的adapter里面有一个异步加载图片的方法和一个edittext监听的方法，当我在加载更多数据的时候，就会报ImageView和EditText空指针异常。这个怎么破啊......

public class OutAdapter extends BaseQuickAdapter<CanOutSideBean.ResponseParametersBean.CanWaidiaoBusListBean, BaseViewHolder> {
    public HashMap<Integer, String> mHashMap = new HashMap<>();
    private EditText price;
    private CircleImageView mImageView;

    public OutAdapter(int layoutResId, List<CanOutSideBean.ResponseParametersBean.CanWaidiaoBusListBean> data) {
        super(layoutResId, data);
    }

    @Override
    protected void convert(BaseViewHolder baseViewHolder, CanOutSideBean.ResponseParametersBean.CanWaidiaoBusListBean outBean) {
        baseViewHolder.setText(R.id.bus_brand, outBean.getLicense())
                .setText(R.id.dispatch_type, outBean.getSeat())
                .addOnClickListener(R.id.price)
                .addOnClickListener(R.id.parent_price);

        String url = "";
        if (outBean.getBus_pic().size() > 0) {
            url = outBean.getBus_pic().get(0);
            Log.d("url", url);
            mImageView.setTag(url);  //TODO 这句就会报空指针异常
        }
        //异步加载网络图片
        Utils.onLoadHttpImage(mImageView, url);

        price.setTag(baseViewHolder.getLayoutPosition()); //TODO 这句就会报空指针异常
        TextListener listener = new TextListener(price, mHashMap);
        price.addTextChangedListener(listener);
    }

    @Override
    protected View getItemView(int layoutResId, ViewGroup parent) {
        View view = super.getItemView(layoutResId, parent);
        price = (EditText) view.findViewById(R.id.price);
        mImageView = (CircleImageView) view.findViewById(R.id.profile_image);
        return view;
    }

//EditText 监听类
    private class TextListener implements TextWatcher {
        private int mPos;
        private HashMap<Integer, String> mHashMap;

        public TextListener(EditText text, HashMap<Integer, String> hashMap) {
            this.mPos = (int) text.getTag();
            this.mHashMap = hashMap;
        }

        @Override
        public void beforeTextChanged(CharSequence s, int start, int count, int after) {

        }

        @Override
        public void onTextChanged(CharSequence s, int start, int before, int count) {

        }

        @Override
        public void afterTextChanged(Editable s) {
            mHashMap.put(mPos, s.toString());
        }
    }
}

下面是异步加载图片的方法。该方法没有问题，我在其他的地方用是可以的

//异步加载网络图片
        new AsyncTask() {
            @Override
            protected Object doInBackground(Object[] params) {
                try {
                    URL picUrl = new URL(url);
                    Bitmap bitmap = BitmapFactory.decodeStream(picUrl.openStream());
                    return bitmap;
                } catch (Exception e) {
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            protected void onPostExecute(Object o) {
                super.onPostExecute(o);
                //加载完毕后判断该imageView等待的图片url是不是加载完毕的这张
                //如果是则为imageView设置图片,否则说明imageView已经被重用到其他item
                if (url.equals(imageView.getTag())) {
                    imageView.setImageBitmap((Bitmap) o);
                }
            }
        }.execute();

**Comment by CymChad** [comment]
为什么你要
```java
@Override
protected View getItemView(int layoutResId, ViewGroup parent) {
    View view = super.getItemView(layoutResId, parent);
    price = (EditText) view.findViewById(R.id.price);
    mImageView = (CircleImageView) view.findViewById(R.id.profile_image);
    return view;
}
```
如果你想获得EditText对象你可以直接
```java
protected void convert(BaseViewHolder baseViewHolder, CanOutSideBean.ResponseParametersBean.CanWaidiaoBusListBean outBean) {
             EditText price = baseViewHolder.getView(R.id.price);
}

```

**Comment by JueShouGitHub** [comment]
嗯嗯，好吧！我改成这样了
        mImageView = baseViewHolder.getView(R.id.profile_image);
        price = baseViewHolder.getView(R.id.price);
果然好了，谢啦了。原来如此，刚才又看了一下大神的源码，demo，自己太大意了。。。如此冒失的就提了简单的问题，惭愧，惭愧！！！

**Comment by CymChad** [comment]
没事，问题解决了就好了，感谢您的使用。
