### ISSUE TITLE
BaseQuickAdapter<T, K extends BaseViewHolder>没有意义

### ISSUE THREAD

**Issue by BanGyJ** [CymChad/BaseRecyclerViewAdapterHelper#777]
直接BaseQuickAdapter<T,BaseViewHolder>吧，自定义ViewHolder就算继承BaseViewHolder也报类型转换异常

**Comment by CymChad** [comment]
有没有重写`createBaseViewHolder`方法？

**Comment by QtyearLin** [comment]
@CymChad @BanGyJ  #767

**Comment by CymChad** [comment]
感谢你的pr @QtyearLin  已合并

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.1' @BanGyJ 版本升级一下就好了。
