### ISSUE TITLE
recyclerview嵌套，自动滑动问题

### ISSUE THREAD

**Issue by black1991** [CymChad/BaseRecyclerViewAdapterHelper#780]
父recyclerview中存在多个子recyclerview，点击其中子recyclerview的item跳转后返回，父recyclerview会自己滑动到点击处上面的另外一个recyclerview的开头处。（我说的好像不太清楚o(╯□╰)o）

**Comment by TestSmirk** [comment]
这个是RecyclerView的新特性,我特在找禁止滑动的方法.

**Comment by CymChad** [comment]
RecyclerView机制问题，本库也无法解决，十分抱歉。

**Comment by black1991** [comment]
那应该可以改善吧，我看其他的APP也存在多个子recyclerview，应该是我的嵌套方式有问题？

**Comment by CymChad** [comment]
看下你的嵌套方式？其实看是不是该库问题，很简单，你把adapter换成原生的看该问题还存在不存在，如果不存在那就证明是这个库的问题，如果还存在那就是与该库无关。

**Comment by black1991** [comment]
不好意思，回复晚了，嵌套方式就是普通的嵌套的呢，不是库的问题，我百度了下说记录上次滑动的位置，返回的时候滑动到上次的位置可以解决，这个目前还没有操作，不知道您有没有什么建议。

**Comment by CymChad** [comment]
由于我没有遇到过类似的问题场景，所以也给不了建议，十分抱歉，没有能帮上你。

**Comment by black1991** [comment]
不不不，大牛这个框架给我们这些小菜已经提供了很大的帮助了。

**Comment by lyylock** [comment]
在Recyclerview的父布局设置   android:descendantFocusability="blocksDescendants"可以解决自动滑动问题.

**Comment by alen252** [comment]
> 在Recyclerview的父布局设置 android:descendantFocusability="blocksDescendants"可以解决自动滑动问题.
确实解决了我的问题
