### ISSUE TITLE
如何做到第一页数据不满一屏幕的时候

### ISSUE THREAD

**Issue by yubaokang** [CymChad/BaseRecyclerViewAdapterHelper#781]
如何做到第一页数据不满一屏幕的时候
底部的“loading” “没有更多”都隐藏掉，但是呢又去偷偷的加载第二页？

**Comment by yubaokang** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/560#issuecomment-281007796
你可能理解错我的意思了
比如：pageSize是10，加载第一页的时候返回10条数据，但是没有占满整个竖屏（并且底部还会留有一点空白给loading view），然后加载第二页，底部会有loading 的view， 第二页数据为空，这时候底部显示 “没有更多”的view
我的意思是说，这种情况的话，底部的loading view能不能隐藏，但是确实是在加载第二页数据，并且如果第二页没有数据，底部的“没有更多”的view能不能隐藏？

**Comment by yubaokang** [comment]
超过一整个竖屏是 底部显示“-- end --”  这是希望的
![Uploading Screenshot_2017-02-20-16-13-03-370_com.goujiawang.png…]()

没有超过一屏幕是 底部还是显示了“-- end --” 这不太友好
![Uploading Screenshot_2017-02-20-16-13-12-758_com.goujiawang.png…]()
![Uploading Screenshot_2017-02-20-16-13-15-996_com.goujiawang.png…]()

**Comment by yubaokang** [comment]
超过一整个竖屏是 底部显示“-- end --”  这是希望的
![screenshot_2017-02-20-16-13-03-370_com goujiawang](https://cloud.githubusercontent.com/assets/7115700/23116910/0c3bb4c8-f788-11e6-90df-38873663c5df.png)
没有超过一屏幕是 底部还是显示了“-- end --” 这不太友好
![screenshot_2017-02-20-16-13-12-758_com goujiawang](https://cloud.githubusercontent.com/assets/7115700/23116918/1c66304e-f788-11e6-9bf3-996ef420c3c1.png)
![screenshot_2017-02-20-16-13-15-996_com goujiawang](https://cloud.githubusercontent.com/assets/7115700/23116919/1c701654-f788-11e6-87df-73eef1267add.png)

**Comment by guominfang** [comment]
目前我这边也是感觉到这样问题，请问你是怎么解决的？

**Comment by guominfang** [comment]
@yubaokang 目前我这边也是感觉到这样问题，请问你是怎么解决的？
