### ISSUE TITLE
multiselect or selectable recyclerview support / Demo using BaseRecyclerViewAdapterHelper

### ISSUE THREAD

**Issue by LOG-TAG** [CymChad/BaseRecyclerViewAdapterHelper#784]
I'm looking for a easy way to use this adapter as a multiselect recyclerview !! I'm already using BaseRecyclerViewAdapterHelper awesome library, but looking for ways to implement multiselct recyclrview  like below mentioned way by using simplicity of BaseRecyclerViewAdapterHelper!

![demo](https://cloud.githubusercontent.com/assets/1190344/23154526/45f70d00-f834-11e6-94a1-dca534c82f19.gif)

Ref: https://github.com/MFlisar/DragSelectRecyclerView

**Comment by CymChad** [comment]
received

**Comment by CymChad** [comment]
A little busy recently, function after the completion of the notice you
