### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AcgnCodeMonkey** [CymChad/BaseRecyclerViewAdapterHelper#787]
![image](https://cloud.githubusercontent.com/assets/19161307/23199262/70899f04-f908-11e6-95a1-2e26cd5ffc9e.png)
![image](https://cloud.githubusercontent.com/assets/19161307/23199338/c0e68f16-f908-11e6-9e4d-031150f643e2.png)

更新到2.8.1后出现泛型找不到的下标越界异常，之前并没有这个问题
![image](https://cloud.githubusercontent.com/assets/19161307/23199319/ab3798c2-f908-11e6-8439-ca5e16ec883e.png)
我自己封装时是传了两个泛型的，按理说不应该出现这个bug

**Comment by CymChad** [comment]
收到，我看看。

**Comment by QtyearLin** [comment]
@AcgnCodeMonkey 让我看下你的adapter 定义

**Comment by tysheng** [comment]
```public abstract class BaseRecyclerViewAdapter<T> extends BaseQuickAdapter<T, StyBaseViewHolder> ```

**Comment by AcgnCodeMonkey** [comment]
没有什么特别的自定义内容，就是简单封装了一个抽象BaseAdapter
![image](https://cloud.githubusercontent.com/assets/19161307/23244014/9072074c-f9bd-11e6-92cc-5b5d337e47fe.png)

**Comment by QtyearLin** [comment]
等我晚上回来看看

**Comment by QtyearLin** [comment]
可能因为超类变成了你自定义的抽象类而不是basequick

**Comment by QtyearLin** [comment]
@AcgnCodeMonkey  可以再试下

**Comment by QtyearLin** [comment]
@CymChad  @AcgnCodeMonkey  @tysheng fixed

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.3'

**Comment by BugMen** [comment]
为什么我的adapter继承了BaseQuickAdapter后没有setonclick事件啊，是我的使用方法不对么，拜托教我一下
