### ISSUE TITLE
item布局有输入框和选择框的时候，加载导致复用问题

### ISSUE THREAD

**Issue by JueShouGitHub** [CymChad/BaseRecyclerViewAdapterHelper#788]
我的Item布局里面有一个checkBox和一个EditText，当我加载更多的时候，出现了重复选择的情况，并且EditText的数据被清空了。。。。郁闷呐~~~~
大神，这个有解决办法吗？

**Comment by JueShouGitHub** [comment]
我用了一个map标记了Edittext，加载的时候，也是被清空了。。。

**Comment by wangzheng1509** [comment]
你好，这个问题解决了吗

**Comment by JueShouGitHub** [comment]
还没有解决。。。

**Comment by CymChad** [comment]
通过数据属性判断
```java
if（entity.ischeck）{
checkBox.isChecked(true);
}
else
{
checkBox.isChecked(false);
}
```

**Comment by JueShouGitHub** [comment]
@CymChad  大神，这样做可以保证checkbox不会乱；edittext的数据，虽然也保留住了，但是错位了。没有规律的错位，上下滑动的时候，就错乱了......

**Comment by JueShouGitHub** [comment]
我通过TextWatcher 监听输入的内容，然后赋值的！
public void afterTextChanged(Editable s) {
            
            mBean.setInputNewPrice(s.toString());
        }

**Comment by Pyuming** [comment]
@JueShouGitHub   我是这样处理的：在Adapter里面定义一个监听，把输入的数据传到Activity里面保存的。
edittext.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {

            }

            @Override
            public void afterTextChanged(Editable s) {
                listener.onItemEditTextAfterTextChanged(s,
                        baseViewHolder.getLayoutPosition());
            }
        });

**Comment by JueShouGitHub** [comment]
大神，像你说的这样，把数据保存在activity里面，那怎么才能让它在edittext输入框中显示所输入的信息啊，滑动列表还是会清空数据显示的。这就纠结了。。。

**Comment by Pyuming** [comment]
```java
@Override
public void onItemEditTextAfterTextChanged(Editable editable, int index) {
        DemoBean demoBean = mDemoBeanList.get(index);
        demoBean.setAmount(editable.toString());
    }
```
mDemoBeanList 就是传入Adapter的数据。
输入完之后的数据保存到相对应的实体里面，这样就可以保证输入的数据不会错乱了。

**Comment by JueShouGitHub** [comment]
大神，我找到一种办法来解决这个问题了。
在BaseViewHolder里面添加监听，然后在保存数据，这样就不会错乱了。但是当我加载的时候，就出现了NullPointerException问题了，
下面是我重写的BaseViewHolder。就在TODO出，加载就空指针了。。。。

@Override
    protected BaseViewHolder createBaseViewHolder(View view) {
        final BaseViewHolder holder = super.createBaseViewHolder(view);
        EditText price = holder.getView(R.id.price); //TODO 加载的时候就报NullPointerException
        price.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {

            }

            @Override
            public void afterTextChanged(Editable s) {
                mHashMap.put(holder.getLayoutPosition(),s.toString());
                mBean.setInputNewPrice(s.toString());
            }
        });
        return holder;
    }

**Comment by JueShouGitHub** [comment]
啦啦啦，这个问题，我已经自己解决了。我是用源生的adapter解决的，思路和上面一样，不在onBindViewHolder里面设置监听，而是在ViewHolder里面。这样就没有问题了。

我用这个辅助库，就出现NullPointerException的问题，大神，抽时间看一下，应该是有bug吧！！！

**Comment by CymChad** [comment]
NullPointerException的原因应该是所有的viewholder都走了createBaseViewHolder，比如头部，尾部，上拉布局，你使用的时候应该先判断一下holder的itemtype。

**Comment by Pyuming** [comment]
这是我写的Demo：https://github.com/Pyuming/RecyclerViewEditTextDemo

**Comment by CymChad** [comment]
@JueShouGitHub 你可以看下 @Pyuming 的demo，解决了你的问题。

**Comment by JueShouGitHub** [comment]
嗯嗯，好的。解决问题了。
谢谢大神们抽空帮我解决问题，真是太感动了~~~
