### ISSUE TITLE
setEmptyView / addFooterView在fragmentLayout中使用的bug

### ISSUE THREAD

**Issue by ping999** [CymChad/BaseRecyclerViewAdapterHelper#789]
if(adapter == null){
 adapter = new Adapter();
 adapter.setEmptyView();
 adapter.addFooterView();
}else adapter.setNewData();
以上代码是我在项目中使用的，当当前页面经过fragmentLayout.replace之后，执行的是setNewData，但页面不会再呈现任何画面了。

**Comment by CymChad** [comment]
被replace之后不应该重新new了吗？

**Comment by ping999** [comment]
new Adapter?

**Comment by CymChad** [comment]
恩

**Comment by ping999** [comment]
if(adapter == null)，fragment切换时adapter并为清除

**Comment by 1109993488** [comment]
重新setAdapter了吗，贴下相关代码

**Comment by ping999** [comment]
![image](https://cloud.githubusercontent.com/assets/20810003/23241402/d2b862b4-f9ad-11e6-8d03-c68c7fd73a7c.png)
正常可以显示，如果切换了fragment页面就不会呈现任何数据

**Comment by 1109993488** [comment]
fragmentLayout.replace后会重新创建RecyclerView，RecyclerView重新setAdapter了吗

**Comment by ping999** [comment]
因为我是根据adapter==null才会setAdaper，replace后不会重新创建Adapter嘛？

**Comment by 1109993488** [comment]
你这样写replace不重新创建

**Comment by ping999** [comment]
能否引导一下，
当前环境是：MainActivity中A Fragment包含一个Viewpager，B Fragment是个人主页。
                     ViewPager有三个页面，每个页面都是一个recyclerView，每次切换viewpager都需要刷新Recycler。
                     ViewPager中三个页面中设置了addFooterView，他们之间的切换就必须设置setNewData();，不然就会说重复添加footerView。
                     如果这样MainActivity中A B Fragment切换就会出现标题描述的BUG

**Comment by 1109993488** [comment]
RecyclerView还是之前的对象吗？如果A、B切换时replace，看下你的B Fragment

**Comment by ping999** [comment]
是的，还是那个，另外请问下能否判断当前adapter是否包含footerView?

**Comment by 1109993488** [comment]
你可以通过setFooterView方法操作

**Comment by ping999** [comment]
adapter只有addFooterView，没有setFooterView的方法

**Comment by ping999** [comment]
如果您的意思是每次设置addFooterView，这样会直接crash

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.2'

**Comment by ping999** [comment]
thx
