### ISSUE TITLE
2.8版本相比之前2.5版本改动有点大啊

### ISSUE THREAD

**Issue by debughao** [CymChad/BaseRecyclerViewAdapterHelper#790]
1.隐藏加载更多布局的方法不见了
2.设置加载每页数据大小方法换名字
3.item单击事件方法也换名字
感觉有些名字一换自己的代码也要换

**Comment by CymChad** [comment]
1和2都属于上拉功能，因为上拉重构了，api变了，item的点击事件之前的方法名不规范，所以修改了。
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases 每个版本的更新记录都有记录。
我们的改动只为了更让大家更好的使用，建议时间允许的情况下可以改动下。

**Comment by CymChad** [comment]
有什么问题，我们随时再沟通。
