### ISSUE TITLE
子条目点击事件中无法拿到其他控件，无法对其他空间操作，比如隐藏一个布局

### ISSUE THREAD

**Issue by tigersunboy** [CymChad/BaseRecyclerViewAdapterHelper#791]
![Uploading 子条目点击事件中无法拿到其他控件.png…]()
 mRecyclerView.addOnItemTouchListener(new OnItemChildClickListener() {
            @Override
            public void onSimpleItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                String content = null;
                Status status = (Status) adapter.getItem(position);
                TextView viewById = (TextView) view.findViewById(R.id.tweetName);  //此处无法拿到控件，

                RecyclerView.ViewHolder childViewHolder = mRecyclerView.getChildViewHolder(view);
                childViewHolder.getView()         //也不行拿不到
                switch (view.getId()) {
                    case R.id.img:
                        content = "img:" + status.getUserAvatar();
                        Toast.makeText(AnimationUseActivity.this, content, Toast.LENGTH_LONG).show();
                        break;
                    case R.id.tweetName:
                        content = "name:" + status.getUserName();
                        Toast.makeText(AnimationUseActivity.this, content, Toast.LENGTH_LONG).show();
                        break;
                    case R.id.tweetText:

                        viewById.setVisibility(View.GONE);     //空指针无法隐藏布局
                        // you have set clickspan .so there should not solve any click event ,just empty
                        break;

                }

            }

**Comment by Biswangluo** [comment]
你可以在实体类里面定义一个参数 通过参数控制布局显示隐藏，点击控件的时候 改变这个参数，刷新下列表 就能成功隐藏掉布局了

**Comment by Pyuming** [comment]
@tigersunboy   可以看看这个Demo，里面有类似的：https://github.com/Pyuming/RecyclerViewEditTextDemo

**Comment by Pyuming** [comment]
@tigersunboy   还没解决？？

**Comment by tigersunboy** [comment]
@Pyuming  @Biswangluo  谢谢俩位大神，通过设置数据状态能解决了，但是感觉这种方法不太好，这只是关闭打开，要是修改数字还要在adapter中修改方法，我刚刚通过
mRecyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void onSimpleItemClick(BaseQuickAdapter adapter, View view, int position) {
                String content = null;
                Status status = (Status) adapter.getItem(position);
                final TextView viewById = (TextView) view.findViewById(R.id.tweetName);
                TextView tweetText = (TextView) view.findViewById(R.id.tweetText);
                tweetText.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Toast.makeText(AnimationUseActivity.this, "dianjil", Toast.LENGTH_LONG).show();
                        viewById.setVisibility(View.GONE);
                    }
                });
这种方法，可以实现不过有个小坑，tweetText这个点击事件需要在布局文件中加上 android:clickable="true"，不然需要点击条目后再点击才有效。

**Comment by hellobenji** [comment]
小帅哥，你是在西雅图么？




------------------ 原始邮件 ------------------
发件人: "tigersunboy";<notifications@github.com>;
发送时间: 2017年2月23日(星期四) 晚上6:18
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 子条目点击事件中无法拿到其他控件，无法对其他空间操作，比如隐藏一个布局 (#791)




Closed #791.

**Comment by tigersunboy** [comment]
大神这么厉害，小帅哥你都知道了，不过还差点功力，我在上海


------------------ 原始邮件 ------------------
发件人: "hellobenji";<notifications@github.com>;
发送时间: 2017年2月24日(星期五) 中午1:53
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "阿猛"<1170017282@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 子条目点击事件中无法拿到其他控件，无法对其他空间操作，比如隐藏一个布局 (#791)



小帅哥，你是在西雅图么？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "tigersunboy";<notifications@github.com>; 
 发送时间: 2017年2月23日(星期四) 晚上6:18 
 收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;  
 抄送: "Subscribed"<subscribed@noreply.github.com>;  
 主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 子条目点击事件中无法拿到其他控件，无法对其他空间操作，比如隐藏一个布局 (#791) 
 
 
 
 
 Closed #791.
