### ISSUE TITLE
新手上路，关于demo里面RecyclerView嵌套RecyclerView时点击事件问题。

### ISSUE THREAD

**Issue by jxpanda** [CymChad/BaseRecyclerViewAdapterHelper#794]
![qq 20170224152145](https://cloud.githubusercontent.com/assets/7555777/23294167/12e3ab6c-faa5-11e6-8968-ef2128747b38.png)
响应onItemChildClick的时候，onItemChildClick怎么得到convert方法里面的ClickEntity 对象

**Comment by jxpanda** [comment]
如果用adapter.getData().get(position).getXXX得到的数据，在外层RecyclerView滑动的时候， 会出现数据错乱的情况。

**Comment by AllenCoder** [comment]
你是说adapter 获取的不对？打印一个详细日志看看。如果不对，你试着用 list.get(position).getXXX得到的数据试一下

**Comment by AllenCoder** [comment]
首先观察一下我的响应的postion是否正确

**Comment by jxpanda** [comment]
正常情况下， 是正常的， 但是有时候滑动一下，就GG。获取的不对了。。。

**Comment by AllenCoder** [comment]
GG的原因是索引异常吗？

**Comment by AllenCoder** [comment]
嵌套的处理要维护很多额外代码，如果没必要，可以替换成多布局，完全可以解决问题的

**Comment by jxpanda** [comment]
就是在每个多布局里面再嵌套了一个RecyclerView..

**Comment by AllenCoder** [comment]
你这么干，recyclerview 的优势完全体现不出来了呀，缓存也没啥用了

**Comment by jxpanda** [comment]
因为一个列表里面，还有一个列表， 除了这样做， 我也没啥办法了啊。。。这种。
![qq 20170224164633](https://cloud.githubusercontent.com/assets/7555777/23296604/cf94c3d0-fab0-11e6-8c9a-8d6f6c189281.png)

**Comment by AllenCoder** [comment]
那你现在点击崩溃的原因是啥？崩溃日志给我看一下

**Comment by jxpanda** [comment]
没有崩溃， 我说的GG ，就是获取到的数据出现问题了， 其实，我就是点击那个语音播放，有时候获取到的数据是另外的内容，

**Comment by AllenCoder** [comment]
看一下是不是我的adapter 地址错了？

**Comment by jxpanda** [comment]
adapter  如果放外面， 他是怎么精确到我点击的那个item嵌套的recyclerview 的呢。

**Comment by AllenCoder** [comment]
根据传入的recyclerview判断的是recyclerview 还是父rcyclerview

**Comment by AllenCoder** [comment]
你说的错乱是地址的错乱导致的数据错乱，还是adapter错乱，导致数据错乱？打印日志观察看下具体结果

**Comment by jxpanda** [comment]
position是正常的，应该是adapter错乱了。

**Comment by AllenCoder** [comment]
那你换成list.get(postion)获取数据 试试
 不要用 adapter.getData().get(position).

**Comment by jxpanda** [comment]
![qq 20170224171131](https://cloud.githubusercontent.com/assets/7555777/23297439/791a7bea-fab4-11e6-85ec-83de14e71436.png)
![qq 20170224171140](https://cloud.githubusercontent.com/assets/7555777/23297438/79090ba8-fab4-11e6-8c81-8e69de2c5212.png)
![qq 20170224171232](https://cloud.githubusercontent.com/assets/7555777/23297440/7a23129a-fab4-11e6-9bdb-8d2a6e5dec4d.png)
得到的东西，效果是一样的。我其他地方都只是显示数据， 没有其他操作。。

**Comment by AllenCoder** [comment]
嗯，你按照我那种方式试一下

**Comment by jxpanda** [comment]
list.get(postion)么， 我试了，效果一样

**Comment by AllenCoder** [comment]
既然 postion位置都是对的 子布局的数据list也是对的，那肯定是对的，除非你代码逻辑有问题，先检查看下

**Comment by jxpanda** [comment]
好的。

**Comment by jxpanda** [comment]
点中的postion位置都是对的，嵌套recyclerview的数据显示也是正常，但是，点击嵌套recyclerview的子view的时候，打印出来的list长度都是错的。我看不出啥问题了。/大哭

**Comment by jxpanda** [comment]
有没有可能是你们那边事件绑定那个list的时候，出问题了。

**Comment by AllenCoder** [comment]
我们绑定list也不会修改你的list数据源啊，你说list是没有改变，position位置是对的，那应该获取的数据也是对的呀

**Comment by smallmouse2009** [comment]
我有碰到了这个问题

**Comment by smallmouse2009** [comment]
我知道原因了  里面的Recyl;erView的listener需要一个个的new，不能直接写在外面，这样写所有嵌套的recylerview共用同一个listenner，从而造成数据的混乱.

**Comment by CymChad** [comment]
问题解决就好了，感谢你的使用。
