### ISSUE TITLE
添加了头部之后，recyclerView scrolltoposition的时候就混乱了

### ISSUE THREAD

**Issue by zengxiaocong** [CymChad/BaseRecyclerViewAdapterHelper#795]

**Comment by AllenCoder** [comment]
混乱了？会按照adapter的位置正常标记的

**Comment by zengxiaocong** [comment]
添加了4个header。 mrecyclerview.scroll(0)的时候,会滚动到第一个header，但是大于0到时候又会滚动到item相对应的位置

**Comment by AllenCoder** [comment]
大于0 时 ，你这样试试 
```
mrecyclerview.scrollToPosition(postion-mCustomAdapter.getHeaderLayoutCount());

```

**Comment by zengxiaocong** [comment]
如果是个1，那减去头部的count 不就是个负数了。。

**Comment by tysheng** [comment]
header就是个linear layout，你加10个头部，header的位置始终是0。
两个办法，
1.自己计算位置，滑动到相应的头部，麻烦，不推荐。
2.multi布局，每种头部算一种布局，那么四个头部的position就是0，1，2，3.这样就可以滚动了

**Comment by Guolei1130** [comment]
smoothScrollToPosition(0)，添加了头部之后，在中间一部分只能滑到除header之外的位置

**Comment by CymChad** [comment]
@zengxiaocong 问题解决没？
