### ISSUE TITLE
onItemChildClick 点击事件多次调用问题

### ISSUE THREAD

**Issue by yanlianhanlin** [CymChad/BaseRecyclerViewAdapterHelper#800]
使用时出现点一几次，会多次调用的问题
例：
     点击item中的按钮跳转页面，点击一次跳转多次页面出现

**Comment by AllenCoder** [comment]
你贴一下日志，和详细的使用代码。以及版本号便于排查问题。

**Comment by CymChad** [comment]
@yanlianhanlin 问题是否解决？

**Comment by yanlianhanlin** [comment]
您好，现在没有再出现这个问题，这个问题有点奇怪，同样的代码无改动任何代码，有的时候出现，有的时候没事

**Comment by CymChad** [comment]
没问题就好了，如果再次发现问题，需要能给到一个复现场景，我们这边才好定位问题以及解决，以为我们无法复现你所说的bug。感谢 @yanlianhanlin

**Comment by yanlianhanlin** [comment]
好的，谢谢，问题再出现的时候我会把日志信息等贴出来的
