### ISSUE TITLE
需要给适配器传两个list

### ISSUE THREAD

**Issue by yishangfei** [CymChad/BaseRecyclerViewAdapterHelper#807]
![image](https://cloud.githubusercontent.com/assets/15099278/23396981/4aa8ae2e-fdd1-11e6-8301-5de07e15c075.png)
![image](https://cloud.githubusercontent.com/assets/15099278/23396987/4fc0e94e-fdd1-11e6-83d7-1b8957b8bafe.png)
求教

**Comment by CymChad** [comment]
你的需求是？

**Comment by yishangfei** [comment]
我需要在是适配器中传入两个不同对象的list。如
![image](https://cloud.githubusercontent.com/assets/15099278/23442845/2480b63e-fe66-11e6-8220-0209bd1d3c99.png)

**Comment by CymChad** [comment]
那你自己重写一个构造就好了。

**Comment by wanwenxiu** [comment]
![image](https://cloud.githubusercontent.com/assets/12727888/23443210/2930c0a0-fe68-11e6-9386-e6e36ac329f4.png)
构造方法中写了两个list ，BaseQuickAdapter<？，BaseViewHolder>中需要什么类型？

**Comment by CymChad** [comment]
只能定义一个类型，如果你都要用到，你只能在外面封装一层

**Comment by CymChad** [comment]
或者你可以拿到position，自己去list里面获取另外一个list的值。

**Comment by CymChad** [comment]
在convert里面获取position的方法是viewholder.getLayoutPosition()

**Comment by yishangfei** [comment]
![image](https://cloud.githubusercontent.com/assets/15099278/23443312/ecb3868e-fe68-11e6-819c-7f1bd206b6c2.png)
直接传这个app home
![image](https://cloud.githubusercontent.com/assets/15099278/23443326/fefb92e6-fe68-11e6-98a5-f23ef43a7621.png)  就这里报问题

怎么在外面封装一层呀

**Comment by CymChad** [comment]
外层要必须是个list

**Comment by CymChad** [comment]
如果你要封装那也是,
List<AppHome>
然后AppHome里面是AppOrder对象和AppSaleList对象

**Comment by yishangfei** [comment]
以后这个不能加个可以传2个list的吗   我记得listview可以传两个耶

**Comment by CymChad** [comment]
原理是一样的，都是通过position去获取当前的entity，你传入一个，然后另外一个用position就可以满足你的需求了，listview它没有泛型，所以你无论传多少个都是更加position去获取当前entity然后set数据。这个库为了让用户使用的更加方面所以封装了一层，但是也不影响你用以前listview的那种方式去获取数据。

**Comment by yishangfei** [comment]
我和上面那个人沟通了还是没明白怎么搞      
![image](https://cloud.githubusercontent.com/assets/15099278/23443999/6b4f1f72-fe6d-11e6-8925-5d19dc66f8b1.png)
![image](https://cloud.githubusercontent.com/assets/15099278/23444009/78577782-fe6d-11e6-9c55-1212f617cf92.png)
我现在就是需要在适配器里面用到两个list的数据  求教一下

**Comment by CymChad** [comment]
![](https://cloud.githubusercontent.com/assets/15099278/23444009/78577782-fe6d-11e6-9c55-1212f617cf92.png)
这个保持不变，但是要变的是构造，在把List< AppSaleList > saleList传入进来，但是不要给super。
然后在convert里面你要用到AppSaleList的值，你可以saleList.get(viewholder.getLayoutPosition);

**Comment by CymChad** [comment]
明白了吗？

**Comment by yishangfei** [comment]
类里面是传apphome  还是传两个list   row和saleList

**Comment by CymChad** [comment]
两个list

**Comment by yishangfei** [comment]
![image](https://cloud.githubusercontent.com/assets/15099278/23444469/49f54a60-fe70-11e6-8123-19b71f544265.png)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/23444515/9859b42a-fe70-11e6-9509-1c4c34d6403e.png)
你看清楚我上一个回答的内容。

**Comment by CymChad** [comment]
你把你的adapter代码贴出来，我来改吧。

**Comment by yishangfei** [comment]
public class PickAdapter extends BaseQuickAdapter<AppHome, BaseViewHolder> {
    public PickAdapter(List<AppOrder> list,List<AppSaleList> saleLists) {
       super(R.layout.pick_item_layout, list);
    }


    @Override
    protected void convert(BaseViewHolder helper, AppHome item) {
//        String str1 = "送:　";
//        String str2 =item.getDingdanDizhi();
//        SpannableStringBuilder address = new SpannableStringBuilder(str1 + str2);
//        address.setSpan(new ForegroundColorSpan(Color.parseColor("#73C676")),
//                0, str1.length(), Spannable.SPAN_EXCLUSIVE_INCLUSIVE);
//
//        viewHolder.setText(R.id.pick_address,address )
//                .setText(R.id.pick_product,address)
//                .setText(R.id.pick_money, "¥ " + item.getDingdanTotalRmb())
//                .setText(R.id.pick_time, item.getDingdanXiadanTime())
//                .addOnClickListener(R.id.pick_button);
    }
}

**Comment by CymChad** [comment]
```java
public class PickAdapter extends BaseQuickAdapter<AppHome, BaseViewHolder> {
private List<AppSale> mAppSaleList;
public PickAdapter(List list,List saleLists) {
mAppSaleList = saleLists;
super(R.layout.pick_item_layout, list);
}

@Override
protected void convert(BaseViewHolder helper, AppHome item) {
 AppSale appSale = mAppSaleList.get(helper.getLayoutPosition());
// String str1 = "送:　";
// String str2 =item.getDingdanDizhi();
// SpannableStringBuilder address = new SpannableStringBuilder(str1 + str2);
// address.setSpan(new ForegroundColorSpan(Color.parseColor("#73C676")),
// 0, str1.length(), Spannable.SPAN_EXCLUSIVE_INCLUSIVE);
//
// viewHolder.setText(R.id.pick_address,address )
// .setText(R.id.pick_product,address)
// .setText(R.id.pick_money, "¥ " + item.getDingdanTotalRmb())
// .setText(R.id.pick_time, item.getDingdanXiadanTime())
// .addOnClickListener(R.id.pick_button);
}
}
```

**Comment by CymChad** [comment]
这是你要的效果吗？

**Comment by yishangfei** [comment]
![image](https://cloud.githubusercontent.com/assets/15099278/23444684/92dcd0f8-fe71-11e6-9852-adc18b242403.png)

public class PickAdapter extends BaseQuickAdapter<AppHome, BaseViewHolder> {
    private List<AppSaleList> mAppSaleList;
    public PickAdapter(List<AppOrder > list,List<AppSaleList > saleLists) {
        mAppSaleList = saleLists;
       super(R.layout.pick_item_layout,list);
    }


    @Override
    protected void convert(BaseViewHolder helper, AppHome item) {
        AppSaleList appSale = mAppSaleList.get(helper.getLayoutPosition());
//        String str1 = "送:　";
//        String str2 =item.getDingdanDizhi();
//        SpannableStringBuilder address = new SpannableStringBuilder(str1 + str2);
//        address.setSpan(new ForegroundColorSpan(Color.parseColor("#73C676")),
//                0, str1.length(), Spannable.SPAN_EXCLUSIVE_INCLUSIVE);
//
//        viewHolder.setText(R.id.pick_address,address )
//                .setText(R.id.pick_product,address)
//                .setText(R.id.pick_money, "¥ " + item.getDingdanTotalRmb())
//                .setText(R.id.pick_time, item.getDingdanXiadanTime())
//                .addOnClickListener(R.id.pick_button);
    }
}

**Comment by CymChad** [comment]
AppHom  改成 你之前的方式

**Comment by CymChad** [comment]
就改成你自己的AppOder

**Comment by CymChad** [comment]
![](https://cloud.githubusercontent.com/assets/15099278/23444009/78577782-fe6d-11e6-9c55-1212f617cf92.png)

**Comment by yishangfei** [comment]
三克油   感激涕零

**Comment by yishangfei** [comment]
我这边关了
