### ISSUE TITLE
自定义ViewHodler出现问题

### ISSUE THREAD

**Issue by gyyak46** [CymChad/BaseRecyclerViewAdapterHelper#808]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.sibosi.testrxjdk.adapter.RecyclerAutoLayoutAdapter$RecyclerViewHodler
                                                                        at com.sibosi.testrxjdk.adapter.RecyclerAutoLayoutAdapter.convert(RecyclerAutoLayoutAdapter.java:15)
请问这个错是怎么回事
public class RecyclerViewHodler extends BaseViewHolder{

        public RecyclerViewHodler(View view) {
            super(view);
            AutoUtils.autoSize(view);
        }
    }

**Comment by elfman** [comment]
版本号多少？

**Comment by gyyak46** [comment]
版本号是2.8.0

**Comment by elfman** [comment]
升到最新版试试

**Comment by gyyak46** [comment]
我试试最新版的 .

**Comment by gyyak46** [comment]
还是不行 是不是我创建的方式不对.你能写一下创建viewHodler吗??谢谢

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/adapter/DataBindingUseAdapter.java
