### ISSUE TITLE
BaseAdapter里面好像缺少删除全部数据

### ISSUE THREAD

**Issue by smallmouse2009** [CymChad/BaseRecyclerViewAdapterHelper#809]
公布一个删除全部数据的方法

**Comment by elfman** [comment]
`mData.clear()`，最简单的清空列表函数还要教吗？

**Comment by smallmouse2009** [comment]
简单是简单，但是我感觉也需要对外开放一个函数吧，毕竟mData是私有的

**Comment by smallmouse2009** [comment]
我现在只能addData(new ArrayList())做清空操作

**Comment by smallmouse2009** [comment]
嗯  感觉加个移除的方法比较好，但是我现在只能setNewData()

**Comment by CymChad** [comment]
恩，多谢建议。

**Comment by smallmouse2009** [comment]
额  因为我也是最近才用，觉得很好，中间也踩了几个坑，希望越写越完美~
