### ISSUE TITLE
加载更多setAutoLoadMoreSize方法在GridLayoutManager问题

### ISSUE THREAD

**Issue by huangyanbin** [CymChad/BaseRecyclerViewAdapterHelper#812]
使用LinearLayoutmanager正常加载更多，但是当使用GridLayoutManager时，每滑动一点就会去加载更多，我setAutoLoadMoreSize为0也是如此！感谢您的贡献！

**Comment by 1109993488** [comment]
回调加载更多是在`getItemViewType(int)`方法里判断的，默认是在最后一条item显示的时候RecyclerView去调getItemViewType方法，你自己调用了吗？

**Comment by huangyanbin** [comment]
我没有调用getItemViewType方法。

**Comment by 1109993488** [comment]
setAutoLoadMoreSize如果设置过，再设置0是不起作用的，需要大于等于1，LinerLaoutManager没问题的话GridLayoutManager也会没问题
