### ISSUE TITLE
加载数据重复

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#814]
我用convert设置完数据后发现有部分列表数据重复显示了，这个要怎么改啊

**Comment by AllenCoder** [comment]
贴出设置代码，可能是你使用方式不对

**Comment by BugMen** [comment]
![qq 20170302190914](https://cloud.githubusercontent.com/assets/15857673/23535198/ef9bcc54-fff7-11e6-89a9-c90e116bed14.png)
![Uploading QQ图片20170302191029.png…]()

**Comment by BugMen** [comment]
![qq 20170302191029](https://cloud.githubusercontent.com/assets/15857673/23535209/01b99d94-fff8-11e6-83d6-cf57dc1bcb66.png)

**Comment by BugMen** [comment]
@AllenCoder 
![qq 20170302190914](https://cloud.githubusercontent.com/assets/15857673/23543054/563ff1e6-002b-11e7-9b23-6ff6130e127f.png)
![qq 20170302191029](https://cloud.githubusercontent.com/assets/15857673/23543061/5dbb7864-002b-11e7-94d8-a12ef2aee945.png)

**Comment by BugMen** [comment]
顺便问下，加载图片的时候我把URL转成bitmap后图片无法显示是什么情况

**Comment by CymChad** [comment]
建议debug排查数据源问题

**Comment by BugMen** [comment]
嗯嗯，多谢多谢！已经解决了


------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年3月7日(星期二) 下午4:07
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 加载数据重复 (#814)




建议debug排查数据源问题
