### ISSUE TITLE
onLoadMore问题

### ISSUE THREAD

**Issue by zxdeng** [CymChad/BaseRecyclerViewAdapterHelper#815]
当使用加载更多的时候，进来会先执行onLoadMoreRequested，如果还有数据，就会调用loadMoreComplete，此时，列表最后一项会显示onLoadMoreRequested取回来的数据的第一项添加到列表最后，但是此项不会显示完，高度与loading的view一样高

**Comment by AllenCoder** [comment]
你先参考文档修改一下你的使用姿势

(https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD)

**Comment by CymChad** [comment]
@zxdeng 问题解决没？

**Comment by zxdeng** [comment]
按照文档走的，并没有解决，目前还在查询是哪里出了问题

**Comment by zxdeng** [comment]
@CymChad

**Comment by CymChad** [comment]
那么请提供，版本号，代码，（最好能有个小demo）。这样能让我们更好的快速定位问题。

**Comment by zxdeng** [comment]
使用的是2.8.1版本，只有我在使用rxjava+retrofit的时候才会出现，现在的框架是进来就会去请求第二页的数据，会把第二页的第一条数据渲染出来，但是高度为loading的高度

**Comment by zxdeng** [comment]
已经解决了，我开始是用SwipeRefreshLayout嵌套NestedScrollView在嵌套RecyclerView，导致无法使用，这是一个bug吧，我重新提了issue。 @CymChad

**Comment by CymChad** [comment]
恩
