### ISSUE TITLE
清单文件合并失败

### ISSUE THREAD

**Issue by weikjblue** [CymChad/BaseRecyclerViewAdapterHelper#817]
Error:Execution failed for task ':xueTang203:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs 

buildSdkVersion = 24
 buildToolVersion = "24.0.3"
supportVersion = "24.2.1"

 minSdkVersion 14
  targetSdkVersion 24

**Comment by CymChad** [comment]
你需要我怎么帮助你？

**Comment by weikjblue** [comment]
奥,已经解决了,谢谢  导入版本号错误导致的




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年3月6日(星期一) 下午2:02
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "長樂未央"<weikjblue@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 清单文件合并失败 (#817)




你需要我怎么帮助你？

**Comment by CymChad** [comment]
恩，问题解决就好，感谢你的使用。
