### ISSUE TITLE
setEmptyview 后 数据条目为1时 不展示数据 只展示emptyview

### ISSUE THREAD

**Issue by leavesfallenlord** [CymChad/BaseRecyclerViewAdapterHelper#82]
作者你好，我在使用您的项目时遇到了一个问题，就是 setEmptyview 后 数据条目为1时 不展示数据 只展示emptyview  数据条目不为1 时显示正常 希望您抽空予以解答

**Comment by FanYimin** [comment]
我也遇到这个问题了，我是先判断数据列表是否为空，如果是空，则setemptyview

**Comment by AllenCoder** [comment]
你好，bug 已经找到并修复，感谢提供建议和反馈

**Comment by CymChad** [comment]
已修复 com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.0
