### ISSUE TITLE
footerView也有分隔线的问题

### ISSUE THREAD

**Issue by ping999** [CymChad/BaseRecyclerViewAdapterHelper#820]
recyclerView数据较少未占满整个屏幕时，增加分隔线及footerView，footerView底部也有一条分隔先，发现这样特别不美观，请问下有设置去掉最后一条分隔线的方法嘛？

**Comment by CymChad** [comment]
footerView 你可以把它看做一个item。没有设置去掉最后一条分隔线的方法，你只能去控制你画分割线的方法。
