### ISSUE TITLE
添加多个头部，缺少返回已添加的头部下标方法

### ISSUE THREAD

**Issue by a362310485** [CymChad/BaseRecyclerViewAdapterHelper#821]
添加多个头部，缺少返回已添加的头部下标方法，不好判断是否已经添加过头部，容易报已经添加过头部的错

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.4'

**Comment by fuxianwen** [comment]
用 3个参数那不报错的啊
