### ISSUE TITLE
写了一个demo ImageView 布局重用出现问题

### ISSUE THREAD

**Issue by slimvan** [CymChad/BaseRecyclerViewAdapterHelper#822]
viewHolder.setText(R.id.tv_name, item);
        viewHolder.setText(R.id.tv_password, item + "123456," + position);
        Glide.with(mContext).load(R.mipmap.expression_1).into((ImageView) viewHolder.getView(R.id.iv_image));

Adapter中的代码是这样写的  用Glide加载本地的图片  但是列表滑下去 再滑上来后 ImageView把其他两个TextView的空间占掉了  整个Item只有一个ImageView。。

**Comment by slimvan** [comment]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_vertical">

        <ImageView
            android:id="@+id/iv_image"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@android:mipmap/sym_def_app_icon"/>

        <TextView
            android:id="@+id/tv_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:padding="30dp"
            android:text="aaa"/>

        <TextView
            android:id="@+id/tv_password"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="30dp"
            android:text="123456"/>
    </LinearLayout>

item  布局

**Comment by CymChad** [comment]
本地测试，并无描述问题出现，你能否给出一个复现的demo，我这边帮你调试一下？

**Comment by CymChad** [comment]
还有通常，iv会设置一个固定大小。

**Comment by slimvan** [comment]
已经发右键给你了，麻烦查看一下 谢谢！

**Comment by slimvan** [comment]
我把ImageView设置固定大小就可以了，之前设置的wrap_content 会有问题

**Comment by CymChad** [comment]
那这就是你设置的问题，不是adapter的问题了。

**Comment by CymChad** [comment]
如果这样的话，你用原始的adapter应该也会出现同样的问题。

**Comment by slimvan** [comment]
还有一个问题

**Comment by CymChad** [comment]
不满一屏的时候，为什么需要上拉加载？这个业务有些问题吧？如果要有这样的业务理论上也需要一个btn触发吧？因为理论上不满足一页是无法上拉的。

**Comment by slimvan** [comment]
setAutoLoadMoreSize  这个方法 有什么作用呢？

**Comment by CymChad** [comment]
提前加载

**Comment by CymChad** [comment]
还有其他问题吗？

**Comment by slimvan** [comment]
没有了 谢谢！！

**Comment by CymChad** [comment]
恩，好的，感谢你的使用。
