### ISSUE TITLE
ItemView有Selector情况下，onItemDragEnd无法恢复press为false状态

### ISSUE THREAD

**Issue by asan855** [CymChad/BaseRecyclerViewAdapterHelper#824]
public void onItemDragStart(RecyclerView.ViewHolder viewHolder, int pos) {
        viewHolder.itemView.setBackgroundColor(Color.LTGRAY);
    }

    public void onItemDragEnd(RecyclerView.ViewHolder viewHolder, int pos) {
        viewHolder.itemView.setBackgroundResource(R.drawable.item_selector);
        //viewHolder.itemView.setPressed(false);必须用这种方式恢复
    }

**Comment by elfman** [comment]
你试下在onItemDragEnd最后调用notifyItemChanged刷新下item
