### ISSUE TITLE
难道没人遇到数据加载重复的问题嘛？

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#826]
麻烦各位基友帮忙解决一下数据加载重复的问题啊！很急很关键

**Comment by aohanyao** [comment]
1.检查你请求的数据接口返回的数据是否有重复。
2.检查是的数据源是赋值呢？还是addAll

**Comment by BugMen** [comment]
数据接口返回的没有重复，我对列表赋值是addAll




------------------ 原始邮件 ------------------
发件人: "江俊超";<notifications@github.com>;
发送时间: 2017年3月6日(星期一) 下午4:13
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 难道没人遇到数据加载重复的问题嘛？ (#826)




1.检查你请求的数据接口返回的数据是否有重复。
 2.检查是的数据源是赋值呢？还是addAll

**Comment by BugMen** [comment]
已经解决啦！addAll之前加一句clear就好了

**Comment by CymChad** [comment]
如果是下拉刷新，建议你使用setNewData这个api。
