### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by 0kman** [CymChad/BaseRecyclerViewAdapterHelper#827]
Github最新版的BRVAH library代码，Eclipse开发：
adapter.addHeaderView()添加了Header的时候调用adapter.setEmptyView()报错；
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{42908910 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}

**Comment by 1109993488** [comment]
2个一起调用你加上notifyDataSetChanged试试

**Comment by 0kman** [comment]
notifyDataSetChanged后头没有了，有什么好的办法吗。

**Comment by 1109993488** [comment]
HeaderView没有了？单独调用有问题吗？

**Comment by 0kman** [comment]
adapter.addHeaderView()不调用adapter.setEmptyView()是有头的。

**Comment by 1109993488** [comment]
调用下`setHeaderAndEmpty(true)`方法
