### ISSUE TITLE
陈工，您好！数据都添加进去了，可怎么都无法上下滑动了

### ISSUE THREAD

**Issue by huangmango** [CymChad/BaseRecyclerViewAdapterHelper#828]
就是示例数据已经进去了。就是无法上下滑动了，不知道差哪了

**Comment by AllenCoder** [comment]
无法上下滑动，跟你的代码写法有关吧，参考具体Demo试一下

**Comment by CymChad** [comment]
只看你的描述无法找到你问题，请描述你的版本号，你的使用代码。

**Comment by CymChad** [comment]
@huangmango 问题解决了没？

**Comment by huangmango** [comment]
@CymChad 解决了。问题出在，代码中你用了两个recyclerview，第二层的recycleview，外层必须要有一层RelativeLayou，起初我觉得没用，就没加。  加上这个Layou就好了。谢谢关心！  顺便，再问一句，为啥是ItemClickAdapter  上的OnItemTouchListener 好用。   ItemClickActivity 上的OnItemTouchListener  却没有响应呢？
