### ISSUE TITLE
Expandable的展开收缩

### ISSUE THREAD

**Issue by zhou9527** [CymChad/BaseRecyclerViewAdapterHelper#829]
Expandable的展开和收缩会有个空的底色，间隔1s左右消失，想实现慢慢收回和慢慢展开的效果，请教怎么做呢

**Comment by CymChad** [comment]
删除和展开动画本质上都是recycler自带的添加和删除动画，你可以尝试修改设置recycler动画来实现你想要的效果。

**Comment by liusuqin** [comment]
Expandable的展开收缩功能：item可以再是个recyclerview吗？如果可以，item数据怎么处理

**Comment by GSven** [comment]
收缩展开，为什么父item会闪下。有什么办法去掉？

**Comment by GSven** [comment]
当使用加载本地图片不会闪，加载网络图片会闪。。。

**Comment by elfman** [comment]
初始化时执行这句代码
`((SimpleItemAnimator)mRecyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
`
参考[https://developer.android.com/reference/android/support/v7/widget/SimpleItemAnimator.html?hl=es#setSupportsChangeAnimations%28boolean%29](https://developer.android.com/reference/android/support/v7/widget/SimpleItemAnimator.html?hl=es#setSupportsChangeAnimations%28boolean%29)

**Comment by zhou9527** [comment]
好像要自定义RecycleView才可以，对Recycleview还不是好熟悉。陈哥空了帮我瞧瞧呢，让其添加删除动画没有那个背景色的闪现




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年3月7日(星期二) 下午4:12
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "文武"<1158042016@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] Expandable的展开收缩 (#829)




删除和展开动画本质上都是recycler自带的添加和删除动画，你可以尝试修改设置recycler动画来实现你想要的效果。

**Comment by CymChad** [comment]
恩 好的 @zhou9527
