### ISSUE TITLE
下拉选择框怎么去设置点击事件

### ISSUE THREAD

**Issue by yangruixiang** [CymChad/BaseRecyclerViewAdapterHelper#830]
在adpter里面获取到了下拉选择框的id，然后怎么去设置他的点击事件和获取选中的值

**Comment by CymChad** [comment]
viewholder.getView（id）获取控件对象，设置相关事件。

**Comment by yangruixiang** [comment]
那样不就是在adapter里面去设置他的条目点击事件？但是我获取到的值怎么办啊

**Comment by CymChad** [comment]
你可以在adapter里面定义一个接口，通过atctivity来设置实现这个接口，从而到达你要获取值的目的。

**Comment by yangruixiang** [comment]
package com.yxld.xzs.adapter;

import android.content.Context;

import android.util.Log;

import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.Spinner;
import android.widget.Toast;

import com.bumptech.glide.Glide;
import com.chad.library.adapter.base.BaseQuickAdapter;
import com.chad.library.adapter.base.BaseViewHolder;
import com.yxld.xzs.R;
import java.util.ArrayList;
import java.util.List;
import com.yxld.xzs.entity.AppWork;
import com.yxld.xzs.http.ServiceFactory;

/**
 * Created by Administrator on 2017/3/4.
 */
public class WorkAdapter extends BaseQuickAdapter<AppWork.RowBean,BaseViewHolder> {
    private ArrayAdapter<String> arr_adapter;
   private Context contenxt;
    private static ArrayList<String> list;

    public WorkAdapter(List<AppWork.RowBean> data, ArrayList<String> list, Context context) {

        super(R.layout.work_item_layout, data);
        this.list = list;
        this.contenxt=context;

    }

    @Override
    protected void convert(BaseViewHolder Viewholder, AppWork.RowBean item) {
        Spinner sp=Viewholder.getView(R.id.spinner);
        //适配器
//        Log.i(TAG, "convert+++++++++++++++++++: "+WorkFragment.ss);
        arr_adapter= new ArrayAdapter<String>(contenxt, android.R.layout.simple_spinner_item,list);
        //设置样式
        arr_adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
//        //加载适配器
        sp.setAdapter(arr_adapter);
        sp.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
                Log.i(TAG, "onItemSelected: "+list.get(i));
            }

            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
        });


//        //设置样式
//        arr_adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        Log.i(TAG, "convert: " + item.getBaoxiu_paidantime() + "----------------------------------");
//        String url = "http://s16.sinaimg.cn/orignal/89429f6dhb99b4903ebcf&690";


        Viewholder.setText(R.id.work_time, "时间：" + item.getBaoxiu_lrtime())
                .setText(R.id.work_site, "地点：" + item.getBaoxiu_didian())
                .setText(R.id.work_name, "报修人：" + item.getBaoxiu_name())
                .setText(R.id.pick_time, "电话：" + item.getBaoxiu_dianhua())

                .setText(R.id.work_zhipairen, "指派人：" + item.getBaoxiu_paidanren())


                .addOnClickListener(R.id.work_button)


        ;



        String url2 = item.getBaoxiu_img();
        String[] c = url2.split(";");
        String url = "";
        for (int i = 0; i < c.length; i++) {
            if (i == 0) {
                Log.i(TAG, "convert: " + "我是" + c[i] + "------------------------------------------------");
                url = ServiceFactory.Picture_URL + c[i];
                Glide.with(contenxt).load(url).into((ImageView) Viewholder.getView(R.id.work_tu1));
            } else if (i == 1) {
                url = ServiceFactory.Picture_URL + c[i];
                Glide.with(contenxt).load(url).into((ImageView) Viewholder.getView(R.id.work_tu2));
            } else if (i == 2) {
                url = ServiceFactory.Picture_URL + c[i];
                Glide.with(contenxt).load(url).into((ImageView) Viewholder.getView(R.id.work_tu3));
            }
        }


    }
我不太会。。。。。。。
}

**Comment by Pyuming** [comment]
@yangruixiang  https://github.com/Pyuming/RecyclerViewEditTextDemo 这里有定义接口的方式，可能跟你要的效果不一样，但是思路是一样的。
