### ISSUE TITLE
Expandable的展开收缩功能

### ISSUE THREAD

**Issue by liusuqin** [CymChad/BaseRecyclerViewAdapterHelper#831]
Expandable的展开收缩功能：item可以再是个recyclerview吗？如果可以，item数据怎么处理

**Comment by GSven** [comment]
可以的哦，用一个布局（如Linearlayout）把recyclerview包裹起来。

**Comment by elfman** [comment]
理论上是可以的，你需要给内部的Recyclerview指定一个固定高度。
但我基本上是不会在Recyclerview里面再嵌套一个Recyclerview的，容易出问题。遇上这种情况建议想想怎么把它弄成在一个Recyclerview里解决

**Comment by liusuqin** [comment]
像微信朋友圈那样展示最多9张图片的功能，item你会怎么做？我是把item布局成recyclerview去展示图片

**Comment by elfman** [comment]
使用GridLayout，里面动态添加ImageView
