### ISSUE TITLE
请问  setImageUrl(R.id.litPic, blog.getLitPic());怎么做到啊

### ISSUE THREAD

**Issue by yishangfei** [CymChad/BaseRecyclerViewAdapterHelper#835]
![image](https://cloud.githubusercontent.com/assets/15099278/23738611/f8134d30-04d4-11e7-9fff-f3be0753e788.png)

**Comment by CymChad** [comment]
这是前几个版本，集成了图片加载框架，后来考虑到耦合问题，所以移除了。目前只能自己获取iv对象在额外配和图片加载库来进行加载。如：
```java
Glide.with(mContext).load(item.getUserAvatar()).crossFade().into((ImageView) viewHolder.getView(R.id.iv));

```

**Comment by CymChad** [comment]
还有就是如果你觉得不够好，你可以自定义viewholder，自己写一个加载网络图片的方法。
