### ISSUE TITLE
item点击事件多次触发

### ISSUE THREAD

**Issue by pangli** [CymChad/BaseRecyclerViewAdapterHelper#836]
使用场景是这样的：进入界面先去请求网络，网络请求返回数据后再去new adapter并绑定到recycleview同时添加addOnItemTouchListener的item点击事件，添加下拉刷新功能后，因为绑定addOnItemTouchListener是在数据返回之后，也就是说下拉刷新了几次就多绑定addOnItemTouchListener了多少次，造成item点击后事件会被多次触发，能否像以前listview一样每次都是覆盖绑定而不是新增绑定item的点击事件
有问题的写法代码：
![image](https://cloud.githubusercontent.com/assets/7498978/23739855/dbfd781c-04db-11e7-8689-d99a47b16088.png)
或者直接修改源码PulToRefreshUseActivity中的代码如下：
![image](https://cloud.githubusercontent.com/assets/7498978/23739937/292623aa-04dc-11e7-9871-be23a978083e.png)
将红框中的代码移动到箭头所指地方，下拉刷新几下试试。
大概看了recycleview的源码，发现
![image](https://cloud.githubusercontent.com/assets/7498978/23739988/75ce3756-04dc-11e7-95ca-66275edb5823.png)
里面有一个removeOnItemTouchListener方法能否每次添加前先去判断先移除后再添加

**Comment by AllenCoder** [comment]
如果不停的addListener确实是出问题 ,源码这么设计应该是有他具体的原因，后续考虑要不要添加前检查一下，如果有就移除掉上一个。
