### ISSUE TITLE
关于加载更多，导致scrolling computing 异常

### ISSUE THREAD

**Issue by 13588823551** [CymChad/BaseRecyclerViewAdapterHelper#837]
onLoadMoreRequested() {
        mRecyclerView.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        //业务逻辑
                }, delayMillis);
}
为什么不在库里直接写mRecyclerView.postDelayed，这样用户在实现onLoadMoreRequested的时候只需要写业务即可，而不用在每个地方再自己加上mRecyclerView.postDelayed

**Comment by CymChad** [comment]
adapter无法获取mRecyclerView对象。

**Comment by 13588823551** [comment]
对，无法获取我知道。我的意思是因为你这个库是针对RecyclerView的，能否在构造函数里把recyclerview传进去

**Comment by CymChad** [comment]
恩，我再写一个`setOnLoadMoreListener`方法的重载，新增一个recyclerview的参数，如果传入了就帮自动post，如果没有就自己post，这样不会影响到之前的用户，只是提供更好的方法，然后标记上一个方法过时，注释中让用户使用新的方法。

**Comment by CymChad** [comment]
感谢你的建议。

**Comment by 13588823551** [comment]
嗯，这样不看文档用起来也不会报错，麻烦了

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.6'

已更新，你试一下。

**Comment by 13588823551** [comment]
可以了

**Comment by weiyf** [comment]
@CymChad 我想到另外一个方法。
如果在 `onCreateViewHolder` 方法中做这样的判断和赋值：
``` java
if (mParent == null) {
            mParent = parent;
    }
```
然后：
``` java
mParent.post(new Runnable() {
                @Override
                public void run() {
                    mRequestLoadMoreListener.onLoadMoreRequested();
                }
            });
```

这样做有什么不妥或者需要改进的地方么？

**Comment by CymChad** [comment]
可以是可以，但是感觉不太合适。为了mParent去循环的onCreateViewHolder方法里面去取。

**Comment by sunnyamuren** [comment]
大佬 这样互相引用 会内存泄漏的哇～～～
