### ISSUE TITLE
mQuickAdapter.loadMoreFail() Issues

### ISSUE THREAD

**Issue by AqiuBeats** [CymChad/BaseRecyclerViewAdapterHelper#838]
在使用 mQuickAdapter.loadMoreFail()时,
点击"加载失败,请点我重试",确实会重调onLoadMoreRequested()方法,但点击这一行字时,
文字并没有消失,将底部进度圈遮住了,功能不影响但影响UI效果,建议fix.

**Comment by 1109993488** [comment]
取消默认动画 setItemAnimator(null

**Comment by AqiuBeats** [comment]
@1109993488 我认为还有更好的解决方式,牺牲掉Animation的效果来完成一个UI的问题是不值得的,关于底部的xml布局我也看过了,在响应事件中使用visible就能避免这个问题.

**Comment by 1109993488** [comment]
加载更多的状态更新是通过notify来更新的，过快就会有这样重叠效果，感谢你的建议，后续会优化

**Comment by CymChad** [comment]
#500

**Comment by zhupengxiang** [comment]
使用visible就能避免这个问题.什么意思
