### ISSUE TITLE
请问 当底部显示没有更多数据时，再次上拉，怎么触发上拉监听

### ISSUE THREAD

**Issue by yuantanglong** [CymChad/BaseRecyclerViewAdapterHelper#839]
if (mCurrentCounter >= TOTAL_COUNTER) {
//                    pullToRefreshAdapter.loadMoreEnd();//default visible
                        pullToRefreshAdapter.loadMoreEnd(mLoadMoreEndGone);//true is gone,false is visible
                    } 

貌似显示没有更多数据时，上拉监听就禁用了，看了好长时间源码没有找到办法，需求是这样的，当数据不满一页时，不显示底部显示，上拉的时候，显示正在加载，如果加载到最后一页显示 没有更多数据，然后再上拉如果没有最新数据 显示 正在加载 然后显示没有更多数据 
求大神指教

**Comment by 1109993488** [comment]
目前无法做到这样的需求，你可以用PullToRefresh刷新
