### ISSUE TITLE
使用SwipeDelMenuLayout侧拉菜单，绑定不了控件事件

### ISSUE THREAD

**Issue by luXiuKun** [CymChad/BaseRecyclerViewAdapterHelper#840]
helper.addOnClickListener(R.id.comment_del);

swipeTarget.addOnItemTouchListener(new OnItemChildClickListener() {
            @Override
            public void onSimpleItemChildClick(BaseQuickAdapter adapter, View view, int position) {

                ToastUtil.showToast(VideoDetailsAct.this,"删除");
            }
        });

**Comment by AllenCoder** [comment]
swipeTarget 的adapter需要用BaseRecyclerViewAdapterHelper

**Comment by zwping** [comment]
adapter是使用了baseRecyclerViewAdapterHelper，像题主一样help.addOnClickListerner(R.id.xx)后，在childClick中监听失效，有标准答案嘛？

**Comment by AllenCoder** [comment]
监听失效？有其他组件消费掉点击事件吗？ 截图一下你的代码

**Comment by zwping** [comment]
是的，监听失效，没有其它点击冲突(swipeDelMenuLayout内部点击就未查看了)
![1](https://user-images.githubusercontent.com/26704739/27619772-79668842-5bf7-11e7-915e-2695e6851434.png)
![2](https://user-images.githubusercontent.com/26704739/27619771-7962a506-5bf7-11e7-93c9-6313c8ba2a42.png)
![3](https://user-images.githubusercontent.com/26704739/27619773-7967079a-5bf7-11e7-8cb9-531c35400d3b.png)
![4](https://user-images.githubusercontent.com/26704739/27619774-7991af22-5bf7-11e7-9fb0-aad6428611ba.png)

========================
不知你能不能理解我截图的意思，随时在线
