### ISSUE TITLE
7.1.1下，上拉加载更多自定义view不调用，调用的默认的。

### ISSUE THREAD

**Issue by TraxexLoveDonut** [CymChad/BaseRecyclerViewAdapterHelper#841]
再问下大神，上拉实现更多的原理是什么。看了半天原码没发现。

**Comment by tysheng** [comment]
简单说下：
加载更多，是不是要添加监听器，也就是```RequestLoadMoreListener```,有方法
```void onLoadMoreRequested();```

该方法只有在```void autoLoadMore(int position)```中调用，

再找到```int getItemViewType(int position)```这是一个获得item type的方法，在不少地方可以调用，但是主要是在```void onBindViewHolder(K holder, int positions)```中

         * Called by RecyclerView to display the data at the specified position. This method should
         * update the contents of the {@link ViewHolder#itemView} to reflect the item at the given
         * position.

简单来说就是在滚动到相应位置，要显示item的时候调用，也就是说无时无刻不在调用，然后```void autoLoadMore(int position)```判断是否是最后一个

总的来说不是上拉加载，而是是否到底部了，就调用加载

核心函数是```void autoLoadMore(int position)```

**Comment by TraxexLoveDonut** [comment]
7.1.1下自定义上拉更多视图view不调用，调用默认。7.0没测试。6.0正常。
