### ISSUE TITLE
请问怎么做到在最后加一张图片

### ISSUE THREAD

**Issue by yishangfei** [CymChad/BaseRecyclerViewAdapterHelper#842]
![image](https://cloud.githubusercontent.com/assets/15099278/23784274/fa9bab3e-059b-11e7-891d-3f4948f45746.png)

就是添加图片的那种

**Comment by a1510312433** [comment]
可以设置类型，这个也是dataset的一部分

**Comment by yishangfei** [comment]
@a1510312433   能不能详细指点一下呀

**Comment by a1510312433** [comment]
我的意思是这个加号图片也是列表中的一项，而不是列表展示完数据了又加上去的，只不过它和其他列表项数据的类型不同。判断是最后一项就让图片显示

**Comment by yishangfei** [comment]
我知道在最后一张加一个图片啊  主要怎么玩~

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.14'

设置头部，尾部不占一行（使用场景：gv添加+号）

setHeaderViewAsFlow
setFooterViewAsFlow

**Comment by Code6666** [comment]
@CymChad   为什么 我设置了 setHeaderViewAsFlow  不起作用啊
