### ISSUE TITLE
关于加载更多

### ISSUE THREAD

**Issue by newsolf** [CymChad/BaseRecyclerViewAdapterHelper#843]
1,项目中为啥第一次加载更多的时候会报加载失败???
2,必须重试才可以?
3,在网络请求到数据后的回调里,通过adapter.addData(list) 页面不刷新,导致页面空白,但是baseViewHolder里的mData却是有数据的,EmptyView也不能显示

**Comment by CymChad** [comment]
1.贴出你的crash日志。
2.不是必须的。
3.请参考demo的写法或者查看wiki。

**Comment by newsolf** [comment]
已经换另外的方式解决了,项目着急,我会持续关注的

**Comment by CymChad** [comment]
恩，好的。
