### ISSUE TITLE
LinearSnapHelper后  点击事件没有反应？

### ISSUE THREAD

**Issue by yanglichuan** [CymChad/BaseRecyclerViewAdapterHelper#844]
new LinearSnapHelper().attachToRecyclerView(bannerrecyclerView);

当添加上面的代码后   

点击事件有问题   点击没有反应

**Comment by AllenCoder** [comment]
请贴出更多代码，以便排查，应该是touch事件被拦截了

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.8'
