### ISSUE TITLE
加载空布局的问题

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#845]
我加载空布局后没有效果，提示No adapter attached; skipping layout。我的设置adapter.setEmptyView(R.layout.layout_nodata, (ViewGroup) recyclerViewBody.getParent());
哪里不对啊

**Comment by CymChad** [comment]
看下你的代码

**Comment by BugMen** [comment]
我想先问下，空布局应该放在recyclerview的初始化那里还是数据载入的那里啊




------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年3月12日(星期天) 上午10:37
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 加载空布局的问题 (#845)




看下你的代码

**Comment by CymChad** [comment]
初始化即可

**Comment by BugMen** [comment]
![4 plil1jm0swget4pjxj0b](https://cloud.githubusercontent.com/assets/15857673/23882524/2703c848-089c-11e7-95fa-9e4ab37067ee.png)
我是这样设置的，哪里有问题呢

**Comment by BugMen** [comment]
@CymChad 
![4 plil1jm0swget4pjxj0b](https://cloud.githubusercontent.com/assets/15857673/23882539/48cc9662-089c-11e7-988d-ef49266e4cd6.png)
我是这样设置的，有哪里不对么

**Comment by BugMen** [comment]
我这样设置哪里有问题呢
------------------ 原始邮件 ------------------
发件人: "陈宇明";<notifications@github.com>;
发送时间: 2017年3月13日(星期一) 晚上11:25
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 加载空布局的问题 (#845)




初始化即可
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
         
  


从QQ邮箱发来的超大附件

1.jpg (40.8K, 2017年04月13日 09:57 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=08666531d26dc7cbae92182a17310a1b025701540950590d1f545652021c0c000455480950555e190504060250050c0504525453313438051c0c1556310c&t=exs_ftn_download&code=2fe11184

**Comment by CymChad** [comment]
你发我一个demo，看下，我这边demo是正常的。

**Comment by BugMen** [comment]
又来麻烦你了，我想问下如果addItemType（）这个方法中的itemType是个从服务端返回过来的变量，那Adapter的构造方法中该怎么去根据返回的值去判断使用不同的layout呢，是用switch还是if呢？

**Comment by CymChad** [comment]
你直接重写entity的getItemType 方法里面做处理就可以了
