### ISSUE TITLE
这个adapter没有解决视图复用的问题么？

### ISSUE THREAD

**Issue by gaoshan12312** [CymChad/BaseRecyclerViewAdapterHelper#846]
数据正常展示正常，但是控件状态会复用。

**Comment by CymChad** [comment]
这个都是通过数据属性状态来控制的。

**Comment by CymChad** [comment]
通过数据属性判断
```java
if（entity.ischeck）{
checkBox.isChecked(true);
}
else
{
checkBox.isChecked(false);
}
```

**Comment by gaoshan12312** [comment]
//等待付款
            if (realItem.equals("daifukuan")) {
                //未付款订单，一定时间后会被清除
                orderTv1.setVisibility(View.GONE);
                orderTv2.setText("去付款");

            }
            //等待发货
//            else  if (realItem.equals("daifahuo")&&is_team_succ.equals("2")){

            else if (realItem.equals("daifahuo") && is_team_succ.equals("1")) {
                orderTv1.setText("申请退款");
                orderTv2.setText("等待发货");
//                orderTv2.setVisibility(View.GONE);
            }
            else if (realItem.equals("daifahuo") && is_team_succ.equals("2")) {
                orderTv1.setVisibility(View.GONE);
                orderTv2.setText("等待发货");

            }
            //全部发货
            else if (realItem.equals("yifahuo") && is_team_succ.equals("2")) {
                orderTv1.setText("查看物流");
                orderTv2.setText("确认收货");
            }

            //部分发货
            else if (delivery_status_sum.equals("1")) {
                orderTv1.setText("查看物流");
                orderTv2.setText("确认收货");
            }
            //无需发货
            else if (delivery_status_sum.equals("5")) {
                orderTv1.setText("无需发货");
                orderTv2.setVisibility(View.GONE);
            }


            //待评价
            else if (realItem.equals("daipingjia")) {
                if (items == null) {
                    Log.e(TAG, "items是null");
                    orderTv1.setText("申请退货");
                    orderTv2.setText("去评价");
                } else {
                    Log.e(TAG, "items不是null");
//                orderTv1.setText("申请售后");
                    orderTv1.setVisibility(View.GONE);
                    orderTv2.setText("去评价");
                }

            }

            //已评价
            else if (realItem.equals("yipingjia")) {
//                if (items==null) {
//                    Log.e(TAG, "items是null");
//                    orderTv1.setText("删除订单");
//                    orderTv2.setText("申请退货");
//                }else {
//                    Log.e(TAG, "items不是null");
                orderTv1.setText("删除订单");
//                orderTv2.setVisibility(View.GONE);
                orderTv2.setText("已评价");
                // }
            } else if (realItem.equals("bufenfukuan")) {
                orderTv1.setText("申请退款");
                orderTv2.setText("继续支付");
            } else if (realItem.equals("daituikuan")) {
                orderTv1.setText("售后中");
                orderTv2.setVisibility(View.GONE);
            } else if (realItem.equals("yituikuan")) {
                orderTv1.setText("删除订单");
                orderTv2.setText("售后完成");
            }
-------------------------------------------------------------------------------------------------------
以上是我在convert方法中的一些判断，主要判断物品的状态，然后让倆textview更换状态或者隐藏。这应该也是属于数据属性判断吧，为什么滑动的时候，这俩textview会出现复用状态呢。

**Comment by elfman** [comment]
itemview复用是Recyclerview的特性，所有itemview子控件的状态应该有你的控制，Adapter并不清楚你有哪些状态需要保存或重置

**Comment by Sky0202** [comment]
你好,  使用你这种方法好像 并不行啊   还是我哪里写的有问题呢?

     if (bean.isCheck()) {
                    holder.setChecked(R.id.cb_check, true);
                } else {
                    holder.setChecked(R.id.cb_check, false);
                }

                holder.setOnCheckedChangeListener(R.id.cb_check, new CompoundButton.OnCheckedChangeListener() {
                    @Override
                    public void onCheckedChanged(CompoundButton compoundButton, boolean isChecked) {
                        if (isChecked) {
                            bean.setCheck(true);
                        } else {
                            bean.setCheck(false);
                        }
                    }
                });

当我展开一个item时,  使用  holder.setChecked(R.id.cb_check, false);  会把全部的控件都设置为未选中
