### ISSUE TITLE
请教一些滑动删除的问题

### ISSUE THREAD

**Issue by richfuns** [CymChad/BaseRecyclerViewAdapterHelper#847]
请问咱这个库的滑动删除能不能控制滑动距离呢？ 或者滑动后后弦操作菜单？  现在需求是 删除之前弹出确认删除弹框，如果用户点击确认，再删除

**Comment by elfman** [comment]
1. 重写`ItemDragAndSwipeCallback`里的`getSwipeThreshold`方法可控制滑动距离。
2. 活动出现菜单并不属于Adapter的职责，建议你使用其他库来做。
3. 滑动删除恢复参考#297

**Comment by richfuns** [comment]
谢谢，基本了解了
