### ISSUE TITLE
onLoadMoreRequested 重复调用

### ISSUE THREAD

**Issue by hydewang** [CymChad/BaseRecyclerViewAdapterHelper#849]
上拉加载更多时，onLoadMoreRequested会一直被重复调用，因为我有在onLoadMoreRequested请求服务器中的数据，导致不停地像服务器发请求。按道理说，不是一次上拉只请求一次吗

**Comment by CymChad** [comment]
看下你的代码。

**Comment by CymChad** [comment]
应该是你使用写法姿势有问题，请参考demo中或wiki的写法。

**Comment by imLibo** [comment]
我也出现了同样的问题啊，一直不停地调用onLoadMoreRequested
我在加载数据完毕后也调了onLoadmoreComplete啊，纠结了我两天了
