### ISSUE TITLE
请教下关于item view中某个控件状态变化的问题。

### ISSUE THREAD

**Issue by gaoshan12312** [CymChad/BaseRecyclerViewAdapterHelper#852]
类似朋友圈的样式，在点赞的额时候，设置点赞字段为true，然后notifyItemChanged更新视图，因为一个item中包含好几个控件，为了只让点赞的控件变化。所以重写了adapter中的onBindViewHolder方法。如下：
 @Override
    public void onBindViewHolder(BaseViewHolder holder, int position, List<Object> payloads) {
//        super.onBindViewHolder(holder, position, payloads);
        //payloads的大小总是1
        if (payloads == null || payloads.isEmpty()) {
            onBindViewHolder(holder, position);
        } else {
//            List<MyBean.LstBean> lstBeen = (List<MyBean.LstBean>) payloads.get(0);
            int is_dianzan =  getItem(position).getIs_dianzan();
            int is_focusn = getItem(position).getIs_focusn();
            Log.e(TAG, "获取payload的zan值" + is_dianzan);
            if (is_dianzan==1) {
                ((ImageView) holder.getView(R.id.zanImage)).setImageResource(R.mipmap.yidianzan);

            }
            else {
//                zanImageview.setImageResource(R.mipmap.weidianzan);
                ((ImageView) holder.getView(R.id.zanImage)).setImageResource(R.mipmap.weidianzan);
            }
}
----------------------------------------------------------------------------------------
 然后调用recyclerAdapter.notifyItemChanged(position,lst);方法，功能可以正常实现。
但是当我添加个header之后，调用 recyclerAdapter.notifyItemChanged(position-1,lst);
确实也是点击到了该控件，但是视图死活不刷新了。我在onBindViewHolder放法中也试着修改了position的位置，但是还是没有效果。请大神指点下。

**Comment by elfman** [comment]
你能否去学一下markdown语法里怎么贴代码，你这代码简直没法看
