### ISSUE TITLE
长按item，item变色，同时下拉刷新，放开后item背景色不恢复

### ISSUE THREAD

**Issue by niq2003** [CymChad/BaseRecyclerViewAdapterHelper#859]
使用PtrFrameLayout增加下拉刷新功能，在adapter的item中通过selector方式设置item的pressed和normal背景色，长按item变色同时下拉刷新，放开后item背景色不恢复，目测是notifyDataSetChanged后item的pressed状态没恢复

**Comment by AllenCoder** [comment]
这个应该是view的状态没有被重置导致的item背景色有问题。之前看过第三方的下拉刷新和滑动删除在处理view的状态时，没有及时释放view的scoll状态，而系统提供的下拉刷新会重置到正常状态。后续会重构一个新的api来解决修复点击事件的bug

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.8'
