### ISSUE TITLE
关于setEmptyView的问题。

### ISSUE THREAD

**Issue by Vancly** [CymChad/BaseRecyclerViewAdapterHelper#86]
关于setEmptyView，假如一开始是没数据的，这个是有效的，但是如果已经有了数据，我需要加载其他的，请求网络没有数据，我需要setEmptyView一个友好的提示，发现没有效果，还是保留了上一次的数据，看能不能改进一下 ~~

**Comment by CymChad** [comment]
你可以通过notifyItemChanged(0);来改变
