### ISSUE TITLE
BaseQuickAdapter的onBindViewHolder方法报角标越界错误

### ISSUE THREAD

**Issue by MissMyDearBear** [CymChad/BaseRecyclerViewAdapterHelper#860]
`public void onBindViewHolder(ViewHolder holder, int positions) {
        int viewType = holder.getItemViewType();
        switch(viewType) {
        case 0:
            this.convert((BaseViewHolder)holder, this.mData.get(holder.getLayoutPosition() - this.getHeaderLayoutCount()));
        case 273:
        case 819:
        case 1365:
            break;
        case 546:
            this.addLoadMore(holder);
            break;
        default:
            this.convert((BaseViewHolder)holder, this.mData.get(holder.getLayoutPosition() - this.getHeaderLayoutCount()));
            this.onBindDefViewHolder((BaseViewHolder)holder, this.mData.get(holder.getLayoutPosition() - this.getHeaderLayoutCount()));
        }

    }`
其中default中的，this.convert报角标越界错误，代码中看了下holder.getLayoutPosition() - this.getHeaderLayoutCount()一直是-1，这里为什么不直接用position？项目中需要截取recyclerview长图需要调用这个方法，求大神给解决一下

**Comment by MissMyDearBear** [comment]
这个是1.9.8中的问题

**Comment by CymChad** [comment]
需要什么方法？

**Comment by MissMyDearBear** [comment]
在onCreateViewHolder之后，需要在外部调用convert 方法，以便用画布可以绘制出每个item的内容。如果是v7包中的是调用onBindViewHolder方法，同样调用quckbaseadapter的这个方法后一直角标越界，看了源码，position参数貌似没有用过。方便留个QQ活着邮箱么？很想和大神学习学习。

**Comment by MissMyDearBear** [comment]
我测试了下，继承brvah的adapter后，将convert暴漏出来后再次获取bitmao成功啦。目前我有些疑惑的是，源码中onBindViewHolder方法传了position参数为什么没有用到啊？

**Comment by CymChad** [comment]
如果你想在convert获取position，可以通过viewholder.getLayoutPosition

**Comment by wooden1985** [comment]
MissMyDearBear能把代码贴出来参考一下吗？
