### ISSUE TITLE
remove方法不对,应该notifyItemRangeChanged() 一次,要不会删除条目错乱;

### ISSUE THREAD

**Issue by AceInAndroid** [CymChad/BaseRecyclerViewAdapterHelper#862]
现在的remove方法是

    public void remove(int position) {
        mData.remove(position);
        notifyItemRemoved(position + getHeaderLayoutCount());
        compatibilityDataSizeChanged(0);
    }

应该再告诉adapter数据源更新 要不条目会错乱
notifyItemRangeChanged(position, data.size() - position);

**Comment by CymChad** [comment]
@AceInAndroid 感谢提醒，后续会进行改进。

**Comment by AceInAndroid** [comment]
嘻嘻,写的很好的,就是项目频繁要删除添加item,不通知后面的条目更新位置的话,都会错乱的,当然 如果删除的是最后一条也不用通知,insert方法也是~也要notifyItemRangeChanged

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.9'

**Comment by zhaohailongzhl** [comment]
请问这个解决了吗，我现在的的版本是2.9.30，多次删除还是会出现条目错乱的问题
