### ISSUE TITLE
如何从onSimpleItemChildClick()取到子控件

### ISSUE THREAD

**Issue by hulegithub** [CymChad/BaseRecyclerViewAdapterHelper#865]
mRecyclerView.addOnItemTouchListener(new OnItemChildClickListener() {
            @Override
            public void onSimpleItemChildClick(BaseQuickAdapter baseQuickAdapter, final View view, final int i) {
                final ImageView bgPhoto = (ImageView) view.findViewById(R.id.bg_photo);
                final ImageView addPhoto = (ImageView) view.findViewById(R.id.add_photo);
                final ImageView deletePhoto = (ImageView) view.findViewById(R.id.delete_photo);
 }
debug发现获取的控件（addPhoto ，deletePhoto ）为null，请问该如何从监听的事件方法onSimpleItemChildClick(BaseQuickAdapterbaseQuickAdapter, final View view, final int i) 中拿到子控件,多谢！

**Comment by AllenCoder** [comment]
这种方式返回的view是当前点击位置的itemview ，可能会因为itemType的不同，导致childView的返回为空，你需要根据ietmType去非空取childview

**Comment by hulegithub** [comment]
![qq 20170315095550](https://cloud.githubusercontent.com/assets/6002150/23930190/a3472066-0965-11e7-93ec-5d6f3d3580af.png)
只有一种类型，采用的是帧布局，itemView包含三个ImageVIew，但是我只能取到其中的一个，剩余的两个控件都是null，希望能够看一下，是什么原因，多谢！

**Comment by hulegithub** [comment]
经过测试，发现这是一个bug，onSimpleItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i)这个方法里面不能获取itemview，只能获取点击itemView中的某个控件，itemview中没有点击的控件是拿不到的，希望修复，或者提供获取子控件的方法，谢谢！

**Comment by AllenCoder** [comment]
近期会新增一个adapter 的点击事件入口，届时会修复上述bug

**Comment by tysheng** [comment]
2.8.7 新增 getViewByPosition，获取子控件

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.8.8'

**Comment by hulegithub** [comment]
好的，谢谢大神完善！

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0Item%E4%BA%8B%E4%BB%B6

**Comment by liaoxuanwei** [comment]
2.9.15  adapter加了headerview  
mCommentAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
adapter.getViewByPosition(rvComment,position,R.id.tv_comment_addscore)
获取的控件为null，或者是position-2位置的view，有时又能得到当前position的view

**Comment by tysheng** [comment]
这个是实际位置的 你要加上 getHeaderLayoutCount()
