### ISSUE TITLE
局部刷新当带有payload参数时没重写。

### ISSUE THREAD

**Issue by XiaoSeee** [CymChad/BaseRecyclerViewAdapterHelper#867]
如题，当使用`Adapter.notifyItemChanged(position, payload) `带上 payload 参数时。会调用
``` java
public void onBindViewHolder(VH holder, int position, List<Object> payloads)
```
从而可以实现只刷新这个 Item 中的某个控件的作用。
我们的库里面没有对这个方法重新，只重写了
``` java
public abstract void onBindViewHolder(VH holder, int position);
```
需要刷新整个 Item 不太方便。需要自己在 Adapter 里面重新，对于加了 Header 了的，处理 position 还容易出错，可以建议直接加到你们库里面去。

**Comment by CymChad** [comment]
恩，好的，感谢建议，后续我们会进行改进。

**Comment by CymChad** [comment]
#500 待优化
