### ISSUE TITLE
更新英文Wiki

### ISSUE THREAD

**Issue by qtstc** [CymChad/BaseRecyclerViewAdapterHelper#869]
发不了Wiki的PR, 就先放在这里了.
下面是修改后的 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki 的内容, 如果觉得可以的话请更新
https://gist.github.com/qtstc/3d1a471b3ae42d424cdca9bd98d25cb0

**Comment by CymChad** [comment]
好的，我看看先，感谢你的建议。

**Comment by CymChad** [comment]
已替换，十分感谢。
