### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by leavesfallenlord** [CymChad/BaseRecyclerViewAdapterHelper#87]
你好，在onItemChildClick 中使用 mQuickAdapter.remove(i);   连续点击非最后一个条目 会出现数据越界问题 而onItemClick 则不存在此问题  请检查相关position 是否计算正确

**Comment by CymChad** [comment]
恩 好的，我看看

**Comment by CymChad** [comment]
你添加了头部吗？
