### ISSUE TITLE
mAdapter.notifyItemChanged(circlePosition) 刷新报错

### ISSUE THREAD

**Issue by huaxiangyang** [CymChad/BaseRecyclerViewAdapterHelper#871]
当我添加了headerView之后，item的点击事件仍然返回的是未使用headerView时的position  在我调用item刷新之后  会抛出java.lang.IllegalArgumentException: Called attach on a child which is not detached  异常，建议修复若含有headerView   则position的值为加上headview之后的！

**Comment by CymChad** [comment]
你是如何获取的position的？

**Comment by huaxiangyang** [comment]
![image](https://cloud.githubusercontent.com/assets/13110756/24027429/86393aa6-0b02-11e7-8991-650968eb7c9a.png)
就是这样获取的  在OnItemClickListener中携带过来的

**Comment by CymChad** [comment]
这个position应该是处理过的

**Comment by huaxiangyang** [comment]
但是我打印出来的是错误的，
![image](https://cloud.githubusercontent.com/assets/13110756/24027603/b55000f8-0b03-11e7-91cd-b07bafad3274.png)
在这里打印出来是正确的   在外面打印出来的是没有处理的

**Comment by CymChad** [comment]
你直接通过helper来打印的应该是没处理过的。因为这个方法是原生的viewholder直接提供的方法。

**Comment by huaxiangyang** [comment]
我这边的意思是  通过helper打印的是正确的是加过header的   但是  在OnItenClickListener中打印的却是未处理的，这里添加header是否有什么限制？

**Comment by woitaylor** [comment]
我也碰到了

**Comment by woitaylor** [comment]
![_20170317112941](https://cloud.githubusercontent.com/assets/17422824/24027798/224a363c-0b05-11e7-8ae8-51e5ee9c387b.png)
![_20170317112957](https://cloud.githubusercontent.com/assets/17422824/24027799/2255107a-0b05-11e7-8881-6130a97ae3f5.png)
![_20170317113008](https://cloud.githubusercontent.com/assets/17422824/24027800/22656ad8-0b05-11e7-99d1-63022b13b68f.png)

如果是直接 mAdapter.notifyItemChanged(index);就会有问题，我记得以前是可以的。

**Comment by huaxiangyang** [comment]
对的  我现在也是这样做的，每次手动去加上HeaderView的count

**Comment by CymChad** [comment]
@huaxiangyang 点击事件里面的position是被处理过的，因为考虑到大多数场景是在事件内部获取对应的数据，所以-去了head。

**Comment by huaxiangyang** [comment]
那就是说  如果我要调用单条刷新或者单条删除  就必须自己手动去加上hederView  count

**Comment by CymChad** [comment]
恩 是的。后续我们会改进这一块的。

**Comment by huaxiangyang** [comment]
好的 。也感谢你们开源这么好用的库。

**Comment by CymChad** [comment]
感谢你的使用
