### ISSUE TITLE
Adapter.addData(List<T> data) 泛型问题

### ISSUE THREAD

**Issue by rednels** [CymChad/BaseRecyclerViewAdapterHelper#875]
现在我有一个数据`SampleEntity` `implements MultiItemEntity`, 当我使用`addData(List<T> data)`添加一个`List<SampleEntity>`列表，报错。
这里的泛型应该改为`List<? extends T>`，这样我的派生数据实体列表就可以加进来了。

目前我是使用如下方法将子类列表数据添加入adapter:
```java
...
List<MultiItemEntity> entityList = new ArrayList<>(samples);
Adapter.addData(entityList);
...
```

**Comment by CymChad** [comment]
MultiItemEntity需要你的实体类 implements MultiItemEntity 
具体用法https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8D%E5%90%8C%E7%9A%84item%E7%B1%BB%E5%9E%8B

**Comment by rednels** [comment]
抱歉，我可能没有说明白，造成了一些误解，解释如下。

我的实体类`SampleEntity`:
```java
public class SampleEntity implements MultiItemEntity{
...
}
```

1. 通过接口获取到数据 为:
```java
List<SampleEntity> entities = getSampleData();
```
2. 通过`addData()`添加到adapter:
```java
SampleListAdapter mAdapter;
....
mAdapter.addData(entities);
```

此时，`mAdapter.addData(entities);`会提示错误，因为`addData()`只接受`List<MultiItemEntity>`, 而我的数据的类型是`List<SampleEntity>`。所以，我不得不使用如下方法才能将`List<SampleEntity>`的数据加入进去：
```java
List<MultiItemEntity> entityList = new ArrayList<>(entities);
Adapter.addData(entityList);
```

我希望作者可以将`addData()`的数据类型放宽一些, 变更为 `addData(List<? extends MultiEntity> listData)`, 来接受一个子类列表。

更或者说，我的使用方法不对抑或有其他添加list的方法么？ @CymChad

**Comment by CymChad** [comment]
恩，行。我这边也看看。

**Comment by CymChad** [comment]
![image](https://cloud.githubusercontent.com/assets/7698209/24088843/7a593596-0d6a-11e7-8828-de06bda1f8a3.png)
![image](https://cloud.githubusercontent.com/assets/7698209/24088847/8a7a63f0-0d6a-11e7-87f2-e30229e60931.png)
![image](https://cloud.githubusercontent.com/assets/7698209/24088856/94aaee44-0d6a-11e7-9528-601f43b5a02b.png)

**Comment by CymChad** [comment]
我这边是正常的

**Comment by rednels** [comment]
我想，我可能发现了问题了。

我的adapter的类定义是：
```java
public class SampleAdapter extends BaseMultiItemQuickAdapter<MultiItemEntity, BaseViewHolder> {
    ...
}
```

同时，我定义了多个Item的Entity：
SampleEntity
```java
public class SampleEntity implements MultiItemEntity {
    ...
}
```

AnotherEntity
```java
public class AnotherEntity implements MultiItemEntity {
    ...
}
```

`AnotherEntity`和`SampleEntity`拥有不同的数据类型和布局，所以我用了两个，此时就出现了上述问题。

那像我这种数据类型不一样的多个item，定义多个`MultiItemEntity`，有好的实践么？

**Comment by CymChad** [comment]
这个的话，我建议要么把这两个实体都装到一个实体里面去。
``` java
public class MultiItem implements MultiItemEntity {
    public SampleEntity sample;
    public AnotherEntity another;
}
```

**Comment by rednels** [comment]
Thanks.

不太想新增一个实体了，最终还是用了我原来的方法，将`List<SampleEntity>`封装为`List<MultiItemEntity>`:

```java
List<MultiItemEntity> entityList = new ArrayList<>(entities);
```

**Comment by CymChad** [comment]
恩，方法有多种。
