### ISSUE TITLE
关于在viewpager fragment中notifyDataSetChanged无效问题 

### ISSUE THREAD

**Issue by AllanGuoxiLee** [CymChad/BaseRecyclerViewAdapterHelper#88]
recyclerview在viewpager中，adapter中数据有变动，调用notifyDataSetChanged方法无效，界面内容不刷新，但是在activity中没有此bug

**Comment by githubzaibao** [comment]
你可以贴下代码出来么？可能是哪里漏了什么代码

**Comment by AllanGuoxiLee** [comment]
在fragment 中
adapter 代码：
` private class MyAdapter extends BaseQuickAdapter<StatisticsInfo> {

        public MyAdapter(List<StatisticsInfo> list) {
            super(getActivity(), R.layout.employee_statistics_item, list);
        }

        @Override
        protected void convert(BaseViewHolder helper, StatisticsInfo item) {
            View commonTopDivider = helper.getView(R.id.common_top_divider);
            View commonBottomDivider = helper.getView(R.id.common_bottom_divider);
            View bottomDivider = helper.getView(R.id.bottom_divider);
            commonTopDivider.setVisibility(View.GONE);
            commonBottomDivider.setVisibility(View.GONE);
            bottomDivider.setVisibility(View.GONE);
            if (helper.getPosition() == 0) {
                commonTopDivider.setVisibility(View.VISIBLE);
                bottomDivider.setVisibility(View.VISIBLE);
            } else if (helper.getPosition() == getData().size() - 1) {
                commonBottomDivider.setVisibility(View.VISIBLE);
            } else {
                bottomDivider.setVisibility(View.VISIBLE);
            }

            helper.setText(R.id.type_tv, "订单数量：");
            helper.setText(R.id.unit_tv, "单");
            helper.setText(R.id.value_tv, item.getValue());
        }
    }`

初始化adapter对象代码：
` adapter = new MyAdapter(new ArrayList<>());
        LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(layoutManager);
        adapter.openLoadMore(pageSize, true);
        adapter.setOnLoadMoreListener(this);
        recyclerView.setAdapter(adapter);
`

**Comment by CymChad** [comment]
setNewData addHeaderView setEmptyView 都不需要你notifyDataSetChanged

**Comment by CymChad** [comment]
setEmptyView 你可以直接初始化的时候就set，因为他是会判断你没有数据了就显示EmptyView

**Comment by AllanGuoxiLee** [comment]
好的，太谢谢了！！

**Comment by CymChad** [comment]
问题解决了？
