### ISSUE TITLE
Expandable 如何实现默认展开一级列表

### ISSUE THREAD

**Issue by Sky0202** [CymChad/BaseRecyclerViewAdapterHelper#880]
你好，Expandable 如何实现默认展开一级列表，有个回答是逐项调用，我不知道具体的是在哪调用，adapter里边吗？

  case TYPE_LEVEL_COUNT:
                final ProductCount lv0 = (ProductCount) item;
                holder.setText(R.id.tv_jk, lv0.title);

                holder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        int pos = holder.getAdapterPosition();

                        if (lv0.isExpanded()) {
                            collapse(pos);
                        } else {
                            expand(pos);
                        }
                    }
                });
                break;

在上述代码（adapter中）不想使用点击事件，怎么调用展开？

**Comment by Sky0202** [comment]
找到解决办法了，  麻烦你了！

**Comment by Ljj-summer** [comment]
怎么解决的呀

**Comment by Sky0202** [comment]
// 使一级列表默认展开
        for (int i = multiList.size(); i >= 0; i--) {
            maopiOrderCateAdapter.expand(i, false, false);
        }
