### ISSUE TITLE
默认展开多级ExpandableItemAdapter

### ISSUE THREAD

**Issue by Jeffery336699** [CymChad/BaseRecyclerViewAdapterHelper#881]
我使用ExpandableItemAdapter想默认展示所有子类,调用expandAll方法,直接报错
` mRecyclerView = (RecyclerView) findViewById(R.id.rv);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));

        ArrayList<MultiItemEntity> list = generateData();
        ExpandableItemAdapter adapter = new ExpandableItemAdapter(list);

        adapter.openLoadAnimation(BaseQuickAdapter.SLIDEIN_LEFT);
        mRecyclerView.setAdapter(adapter);
        
        adapter.expandAll(0,true);
        adapter.expandAll(1,true);`
![image](https://cloud.githubusercontent.com/assets/16848549/24082726/29784294-0d05-11e7-8c66-2a60941c4b93.png)
请问大神该如何展示所有,多谢了

**Comment by CymChad** [comment]
贴出错误

**Comment by CymChad** [comment]
```java
private void expandAll() {
        for (int i = 0; i <list.size() ; i++) {
            adapter.expand(i + adapter.getHeaderLayoutCount(), false, false);
        }
    }
```

**Comment by Jeffery336699** [comment]
谢谢大声,用你的方法解决了
