### ISSUE TITLE
点击水波纹与列表下划线效果

### ISSUE THREAD

**Issue by BugMen** [CymChad/BaseRecyclerViewAdapterHelper#883]
如题，我想问下你们的点击水波纹效果以及列表的悬浮效果怎么实现的啊

**Comment by AllenCoder** [comment]
查看Demo

**Comment by BugMen** [comment]
就是没找到才问的啊




------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年3月20日(星期一) 中午11:29
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "START"<461239452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 点击水波纹与列表下划线效果 (#883)




查看Demo

**Comment by CymChad** [comment]
悬浮 ：https://github.com/oubowu/PinnedSectionItemDecoration
水波纹效果、下划线都不是属于adapter。
下划线属于RecyclerView设置ItemDecoration
波纹效果（Ripple）：

当你使用了Material主题后，波纹动画会自动应用在所有的控件上，我们当然可以来设置其属性来调整到我们需要的效果。

可以通过如下代码设置波纹的背景：
android:background="?android:attr/selectableItemBackground"波纹有边界
android:background="?android:attr/selectableItemBackgroundBorderless"波纹超出边界
