### ISSUE TITLE
更新指定条目无效，应当怎样解决

### ISSUE THREAD

**Issue by huangxiaojingCN** [CymChad/BaseRecyclerViewAdapterHelper#885]
// 更新评论数
            commentListAdapter.notifyItemChanged(position); 没有更新数据是怎么回事

**Comment by CymChad** [comment]
你的position有没有正确？

**Comment by CymChad** [comment]
@huangxiaojingCN 问题解决没？

**Comment by 957919019** [comment]
我也发生了同样的问题，数据源变了，调用了该方法后UI没有更改，找了2个小时问题，坐的屁股疼哈哈

**Comment by shichaohui** [comment]
position 传错了吧。传入的 position 的值要包含 headView 的数量。
`int postion = mData.indexOf(item) + mAdapter.getHeaderLayoutCount()`
