### ISSUE TITLE
怎么默认展开某一项

### ISSUE THREAD

**Issue by 08carmelo** [CymChad/BaseRecyclerViewAdapterHelper#888]
` ProblemMultiInfo multiInfo = new ProblemMultiInfo(ProblemDetailAdapter.TYPE_LEVEL_PROBLEM_POS_0,keyNames[3]);
   `multiInfo.addSubItem(new` ProblemPosInfo());
            multiInfo.setExpanded(true);`

我添加数据时已经设置true，  但是并没有默认展开，必须要点击这一行并且手动调用expand(helper.getAdapterPosition());  才能展开。  
why？

**Comment by 08carmelo** [comment]
已解决。 添加数据时，把展开的子项加入就OK了

**Comment by a48352433** [comment]
这样是不是不太合逻辑?要么手动调用一下,要么把所有要展开的子元素添加进去..感觉不应该是直接添加data时设置true,然后不做任何操作就默认展开了么?
