### ISSUE TITLE
fragment切换，页面不显示任何内容的问题

### ISSUE THREAD

**Issue by ping999** [CymChad/BaseRecyclerViewAdapterHelper#890]
fragment恢复可见时，这时候adapter != null && data有数据，这时候调用adapter.newData(data);，页面不显示任何内容，问题找到了，但没有解决思路...

**Comment by CymChad** [comment]
问题找到了？

**Comment by ping999** [comment]
/js，replace时每次都new Fragment能解决现象，但不知道会不会影响性能。
请谅解一个菜鸟求真之路，没找到问题？

**Comment by ping999** [comment]
╮(╯▽╰)╭，还是把这个问题关了吧
