### ISSUE TITLE
 添加 onItemLongClick     longClick不触发·· 2.8.8

### ISSUE THREAD

**Issue by sj853** [CymChad/BaseRecyclerViewAdapterHelper#892]
不知道为什么  版本是最新的 2.8.8 在fragment里面使用

onItemClick 是正常的 ·· 用法跟ontimeClick一样   这里我就不贴代码了哈 ·

难道我用到假的brvah了

**Comment by sj853** [comment]
还是贴一个哈··· 感觉很奇怪  android5.0 三星note3
![image](https://cloud.githubusercontent.com/assets/3139596/24136546/484743aa-0e4a-11e7-8763-b8a71a9a75c5.png)

![image](https://cloud.githubusercontent.com/assets/3139596/24136524/2698dca0-0e4a-11e7-97af-34e79a0a7d93.png)

![image](https://cloud.githubusercontent.com/assets/3139596/24136554/4d9290bc-0e4a-11e7-830b-304dbec5d9df.png)

**Comment by AllenCoder** [comment]
发测试Demo 以供排除问题，按道理来说调用的是系统长按事件接口？难道你用了个假的BRVAH?

**Comment by zxy198717** [comment]
@AllenCoder 
请看下代码：
`BaseQuickAdapter` 809行，这里的判断貌似有问题。
```
        view.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                if (getOnItemChildClickListener() != null&&baseViewHolder!=null) {
                    return getOnItemLongClickListener().onItemLongClick(BaseQuickAdapter.this, view, baseViewHolder.getLayoutPosition() - getHeaderLayoutCount());
                }
                return false;

            }
        });
```

**Comment by zxy198717** [comment]
@sj853 长按要 return true，告诉系统 事件已被消费。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.0'

**Comment by CymChad** [comment]
@sj853 再试试

**Comment by sj853** [comment]
@zxy198717 @ChadCym  好的 我试试

**Comment by sj853** [comment]
可以了····
