### ISSUE TITLE
首次显示到界面的item都依次执行加载动画，而不是一起执行的怎么解决？

### ISSUE THREAD

**Issue by tdxtxt** [CymChad/BaseRecyclerViewAdapterHelper#893]

**Comment by CymChad** [comment]
重写执行动画的方法，加入延迟动画的代码。

**Comment by tdxtxt** [comment]
protected void startAnim(Animator anim, int index) {
        if(index > 7){
            anim.setDuration(mDuration).start();
        }else{
            anim.setDuration(mDuration).setStartDelay(index * 200);
            anim.start();
        }
        anim.setInterpolator(mInterpolator);
    }

这样修改过后，先显示出item之后再播放的动画

**Comment by CymChad** [comment]
@tdxtxt 问题解决没？

**Comment by CymChad** [comment]
我当初实现这个效果是这样写的。
``` java
@Override
    protected void startAnim(Animator anim, int index) {
        super.startAnim(anim, index);
        if (index < 5)
        anim.setStartDelay(index * 150);
    }
```

**Comment by tdxtxt** [comment]
你这样做不是要执行两次动画吗

**Comment by CymChad** [comment]
不会setStartDelay只是延迟而已。

**Comment by tdxtxt** [comment]
我试一试，我之前做的就有些复杂了
if(isDetached){
            view.setVisibility(View.VISIBLE);
            anim.setDuration(mDuration).start();
            anim.start();
        }else {
            view.setVisibility(View.GONE);
            anim.setDuration(mDuration).setStartDelay(index * 200 + 10);
            anim.start();
        }
        anim.addListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animation) {
                view.setVisibility(View.VISIBLE);
            }
            @Override
            public void onAnimationEnd(Animator animation) {}
            @Override
            public void onAnimationCancel(Animator animation) {}
            @Override
            public void onAnimationRepeat(Animator animation) {}
        });
        anim.setInterpolator(mInterpolator);

**Comment by CymChad** [comment]
恩，你试试，看能不能满足你的需求，我之前写的第一页延迟就是这么写的。

**Comment by tdxtxt** [comment]
你这个方法可以的，另外我要是确定当前界面到底有几个需要延迟动画，有没有什么更好的思路

**Comment by tdxtxt** [comment]
我之前的做法是在onViewAttachedToWindow和onViewDetachedFromWindow方法里面记录一个状态，根据这个状态来判断是否做延迟动画的，但这样写会出现那种特殊情况，第一页的后面一条item，滚动之后会出现延迟动画

**Comment by CymChad** [comment]
如果你是LinearLayoutManager 
``` java
RecyclerView.LayoutManager manager = recyclerView.getLayoutManager();
final LinearLayoutManager linearLayoutManager = (LinearLayoutManager) manager;
             recyclerView.postDelayed(new Runnable() {
                 @Override
                 public void run() {
                          // 这一页的数量
                       linearLayoutManager.findLastCompletelyVisibleItemPosition() + 1
                 }
             }, 50);
```
