### ISSUE TITLE
分组的伸缩栏展开折叠后数据会乱掉

### ISSUE THREAD

**Issue by xiaoconggithup** [CymChad/BaseRecyclerViewAdapterHelper#896]
我选中了二级条目中的前两个条目的checkbox   ,这时候折叠起来  ,在展开,这时候选中的就不是我原来选的那两个了,

**Comment by CymChad** [comment]
这是缓存问题，需要你自己通过属性数据来控制。

**Comment by xiaoconggithup** [comment]
具体需要怎么做呢 ,能给个提示么

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/846
