### ISSUE TITLE
Extending BaseQuickAdapter in Inner Class使用内部类出错

### ISSUE THREAD

**Issue by p8499** [CymChad/BaseRecyclerViewAdapterHelper#899]
```
public class CategoriesDialog extends AppCompatDialog{
    //other codes
    class ItemsAdapter extends BaseQuickAdapter<Category, ItemsViewHolder> {
        public ItemsAdapter() {
            super(R.layout.dialog_categories_itemsrecycler, null);
        }
}
```

Error thrown out:

java.lang.NoSuchMethodException: <init> [class com.p8499.lang.CategoriesDialog$ItemsAdapter, class android.view.View]

**Comment by p8499** [comment]
2.6.1 的时候好的, 2.8.9升级出错

**Comment by p8499** [comment]
看了源代码,BaseQuickAdapter.java line:861
```
    private K createGenericKInstance(Class z, View view) {
        try {
            Constructor constructor;
            String buffer = Modifier.toString(z.getModifiers());
            String className = z.getName();
            // inner and unstatic class
            if (className.contains("$") && !buffer.contains("static")) {
                constructor = z.getDeclaredConstructor(getClass(), View.class); //Exception was thrown here
                return (K) constructor.newInstance(this, view);
            } else {
                constructor = z.getDeclaredConstructor(View.class);
                return (K) constructor.newInstance(view);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
        return null;
    }
```

**Comment by CymChad** [comment]
收到，我看看

**Comment by CymChad** [comment]
@QtyearLin 麻烦跟进一下

**Comment by QtyearLin** [comment]
@CymChad  收到

**Comment by QtyearLin** [comment]
@p8499  adapter单独写个类

**Comment by CymChad** [comment]
@QtyearLin 其原因是？

**Comment by luciferChou** [comment]
单独写了个类还发生这种情况是什么原因。只要签名就有这种问题，不签名没有

**Comment by luciferChou** [comment]
单独写了个类还发生这种情况是什么原因。只要签名就有这种问题，不签名没有。
错误日志如下 
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Class.getModifiers()' on a null object reference                                                       
at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:857)

**Comment by p8499** [comment]
我估计是新版本BRVAH用了反射，而反射的类名不支持内部类。
是否有考虑后续版本支持内部类？

**Comment by luxiao0314** [comment]
这个问题现在还有吗,没使用内部类,我这边出现了,也是最新的包,如果列表太多了,出现这个异常会卡顿
java.lang.NoSuchMethodException: <init> [class android.view.View]
    at java.lang.Class.getConstructor(Class.java:528)
    at java.lang.Class.getDeclaredConstructor(Class.java:507)
    at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:1034)
    at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1012)
    at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:989)
    at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:985)
    at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:762)
    at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:70)

**Comment by FrankKwok** [comment]
这个类库使用反射创建holder，adapter需要是顶级类或是静态内部类，而且需要泛型信息

**Comment by FrankKwok** [comment]
也不推荐使用内部类adpater，内部类会持有外围类的引用，容易导致内存泄漏

**Comment by FrankKwok** [comment]
@luxiao0314 重新开个issue
