### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by JueShouGitHub** [CymChad/BaseRecyclerViewAdapterHelper#900]
大神，我这边原来用着一直没有问题，直到今天，突然发生了大问题了。。。
我的加载过程中，就崩溃了。所有的加载同时出现这个问题。。。。
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
我一直都没有动过，这咋整啊

**Comment by JueShouGitHub** [comment]
这问题着实奇葩，我把项目迁移到一个新的项目，就解决了。好吧，虽然不知道什么原因，但是可以用了。。。 =_=!!!

**Comment by CymChad** [comment]
...问题解决就好
