### ISSUE TITLE
ExpandableIAdapter 折叠和子项点击问题

### ISSUE THREAD

**Issue by trustD** [CymChad/BaseRecyclerViewAdapterHelper#904]
1.Demo上 点击折叠子条目，获得的子条目位置不正确。
2.在使用ExpandableAdapter时，如果同时展开多个条目，然后从下面开始折叠，上面的条目会挤压到最下面来。但是Demo没有错误。求大神 帮助。。。

**Comment by CymChad** [comment]
demo没问题，那就是你使用姿势有问题，你可以对比下代码。
