### ISSUE TITLE
有个问题,当下拉刷新的时候,每次都addData 会多出来很多数据

### ISSUE THREAD

**Issue by AceInAndroid** [CymChad/BaseRecyclerViewAdapterHelper#905]
下拉刷新之后只有addData方法这样一直下拉一直有数据(我暂时判断currentPage和totalPage 数量来阻止刷新) , 但有没有setData方法?只加载第一页数据的

**Comment by Android-KJY** [comment]
/**
     * setting up a new instance to data;
     *
     * @param data
     */
    public void setNewData(List<T> data) {
        this.mData = data == null ? new ArrayList<T>() : data;
        if (mRequestLoadMoreListener != null) {
            mNextLoadEnable = true;
            mLoadMoreEnable = true;
            mLoading = false;
            mLoadMoreView.setLoadMoreStatus(LoadMoreView.STATUS_DEFAULT);
        }
        mLastPosition = -1;
        notifyDataSetChanged();
    }
看源码可知。。。setNewData方法可以实现

**Comment by CymChad** [comment]
@Android-KJY  正解，感谢你的回答。
