### ISSUE TITLE
添加头与上拉加载更多一起用的时候界面会置顶

### ISSUE THREAD

**Issue by wcglws** [CymChad/BaseRecyclerViewAdapterHelper#908]
大神，我给recyclerview加了个头，然后上拉加载更多的一瞬间列表自动瞬间滚到第一页，请问这是怎么回事？往下滑动，发现数据加载是成功的。。。跪求大神指点

**Comment by CymChad** [comment]
#906

**Comment by CymChad** [comment]
描述请详细一点。

**Comment by wcglws** [comment]
当前版本是2.9.0.。上拉加载的成功后列表自动置顶，不报错，大神，我这提问能理解么？

**Comment by CymChad** [comment]
你是不是上拉加载的时候 new adapter了？

**Comment by CymChad** [comment]
请贴出你的上拉加载成功后执行的代码

**Comment by wcglws** [comment]
找到错误了，没有new  只是重新setAdapter了一小下。。哈哈，打扰了

**Comment by CymChad** [comment]
ok，问题解决就好。
