### ISSUE TITLE
Tablayout+viewpage 使用有点问题

### ISSUE THREAD

**Issue by huangmango** [CymChad/BaseRecyclerViewAdapterHelper#909]
分了几个TAB页，每个页都是列表。  对其中一TAB页中的某一个列表进行move()操作正常，这时切换到另一TAB页，再move()其中一条数据，然后再切回原来 的TAB页，再move()一条，这时，onItemChildClick(BaseQuickAdapter adapter, View view, int position)    中的，  adaper 的数量不减。

望速解答。

**Comment by AllenCoder** [comment]
remove 之后，是否刷新适配器？你是复用同一个adapter 吗？

**Comment by huangmango** [comment]
恩，仔细看了下，果然不是同一个  adapter。  谢谢指点




------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年3月26日(星期天) 下午2:42
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>; 
抄送: "QQ"<1098424420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] Tablayout+viewpage 使用有点问题 (#909)




remove 之后，是否刷新适配器？你是复用同一个adapter 吗？
