### ISSUE TITLE
请问 scollview 嵌套RecyclerView 加载更多自动调用问题

### ISSUE THREAD

**Issue by Luoye99** [CymChad/BaseRecyclerViewAdapterHelper#910]
我在使用BaseRecyclerViewAdapterHelper 的时 用scollview 嵌套RecyclerView 的时候 adapter的onLoadMoreRequested 方法一直在不停的调用.请问有什么解决方法? 还请多多指教

**Comment by tysheng** [comment]
recyclerview 已经是滚动视图，为何还要包裹一个scrollview？

既然你开启了加载更多，那么必定有一个返回值是要去关闭加载更多的，请在合适的位置关闭它

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/623

**Comment by Luoye99** [comment]
@tysheng 进入页面还没有滑动RecyclerView 的时候就开始回调onLoadMoreRequested 方法  并且在加载更多里调用loadMoreComplete方法.    然后onLoadMoreRequested 还是会无限调用
