### ISSUE TITLE
添加头部后，position的问题

### ISSUE THREAD

**Issue by JueShouGitHub** [CymChad/BaseRecyclerViewAdapterHelper#914]
大神，如题，我添加了头后，position时怎么计算的，还是从0开始嘛？还是从1开始

通过item点击知道，貌似时从0开始的，但是再adapter里面，按照从0开始，数据乱了。
然后反过来从adapter里面，按照从1开始，数据就正常了。这个是当初就这么设计的吗？还是我这边出了问题

版本号：2.9.0

**Comment by CymChad** [comment]
如果你是在convert里面通过viewholder里面获取应该是从1开始，因为头部也是一个item。
如果是你从点击事件里面获取position的话应该是0开始，因为点击事件处理过headview的数量了。

**Comment by CymChad** [comment]
因为viewholder的getlayoutposition方法是系统方法我们无法做处理。

**Comment by JueShouGitHub** [comment]
哦哦，好的。谢谢解答奥。那我就知道了。
