### ISSUE TITLE
自定义BaseViewholder报强转错误

### ISSUE THREAD

**Issue by IsSwm** [CymChad/BaseRecyclerViewAdapterHelper#915]
`
//    主内容的  rv 适配器
    class MultipleItemQuickAdapter extends BaseMultiItemQuickAdapter<MultipleItem,MyBaseViewHolder> {

java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.swm.goodssale.view.MyBaseViewHolder
                                                                   
`
这是怎么回事呢？

**Comment by CymChad** [comment]
更新至最新版。

**Comment by IsSwm** [comment]
谢谢你的解答。

**Comment by CymChad** [comment]
恩，有问题再提。

**Comment by IsSwm** [comment]
好的，大力支持你。
