### ISSUE TITLE
使用BaseMultiItemQuickAdapter多布局问题

### ISSUE THREAD

**Issue by Y-JH** [CymChad/BaseRecyclerViewAdapterHelper#916]
使用BaseMultiItemQuickAdapter进行多布局时候，改变一个item布局的某个控件的状态，当前页面所有的该类型控件全部发生改变。请问怎么处理？？？

**Comment by CymChad** [comment]
根据你的描述我猜测有可能是RecyclerView的缓存机制问题，你可以参考 #846

**Comment by Y-JH** [comment]
我的问题好像跟那个不太一样；因为我的是在一个列表中，有一个删除按钮（ImageView）点击之后，我让ImageView 设置gone 让布局中Button显示替换Imageview的显示；但是我处理一个Imageview按钮所有的状态都发生了变换；
如果，我在bean中做判断处理，还是不行的。因为我调试的时候，看到所有的item布局中相同的Imageview出现的view.getid()结果都是一样的，说明不是缓存的问题，而是一直在复用同一个相同id的view导致！

**Comment by Y-JH** [comment]
我在想，每一个item布局中的控件view应该有不同的属于自己的id，就像new出来的新的对象是一样的；但是，出现的状况是现在一个列表下，所有的view控件id都是一样的！请问，这个是属于什么问题？

**Comment by CymChad** [comment]
你使用BRVAH的版本号是？
你的使用代码是？

**Comment by CymChad** [comment]
理论上布局的隐藏显示应该根据ben的属性来判断，要不然如果是当初的设置制定控件的隐藏显示在滑动的时候会出现布局缓存问题的。

**Comment by Y-JH** [comment]
我刚才使用你给我说的那个案例试了一下；结果是对的，因为我是第一次使用recycle人view，所以我不太明白他的使用即使是复用view但是，在不同的item中的view的id也不应该是相同的吧？！

**Comment by Y-JH** [comment]
这个是我写的代码：
public MessageNoticeAdapter(MessageNoticeActivity activity, List data) {
        super(data);

        addItemType(MessageNoticeMultipleItemBean.CONTAIN_IMG_CLOSE, R.layout.message_notice_recycler_item);//带  圆形关闭按钮
        addItemType(MessageNoticeMultipleItemBean.CONTAIN_LAYOUT, R.layout.message_notice_recycler_item_include);//只有布局
        setOnMessageNotice(activity);
    }




 @Override
    protected void convert(final BaseViewHolder helper, final MsgNoticeBean item) {
        switch (helper.getItemViewType()) {
            case MessageNoticeMultipleItemBean.CONTAIN_IMG_CLOSE://带 圆形关闭按钮
                setOnItemChildClickListener(this);
                setOnItemClickListener(this);
                helper.setText(R.id.tv_near_notice, item.APPEND_DATE_SHOW);//显示最近通知
                helper.setText(R.id.tv_title_notice, item.REMIND_CLASS_MC+"提醒");
                helper.setText(R.id.tv_title_time, item.APPEND_DATE_SHOW2);
                helper.setText(R.id.tv_notice_content, item.REMIND_CONTENT);
                break;

            case MessageNoticeMultipleItemBean.CONTAIN_LAYOUT://只有布局
                helper.setText(R.id.tv_title_notice, item.REMIND_CLASS_MC+"提醒");
                helper.setText(R.id.tv_title_time, item.APPEND_DATE_SHOW2);
                helper.setText(R.id.tv_notice_content, item.REMIND_CONTENT);
                break;
        }
    }

    @Override
    public boolean onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
        Toast.makeText(App.getApp(), "onItemChildClick=" + view.getId(), Toast.LENGTH_SHORT).show();
        return true;
    }

    @Override
    public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
        Toast.makeText(App.getApp(), "onItemClick=" + view.getId(), Toast.LENGTH_SHORT).show();
    }


弹出的view.getid结果是一样的。

**Comment by Y-JH** [comment]
还有我刚噶写代码的时候发现一个问题，如果按照根据bean的属性来判断，那么每次判断设置状态之后都需要使用notifyDataSetChanged();这个方法，是不是有点耗费资源了？谢谢！

**Comment by Y-JH** [comment]
谢谢作者！

**Comment by CymChad** [comment]
我知道了，你的布局不一样但是布局id一样，导致我内部缓存机制同一个id重用了。

**Comment by CymChad** [comment]
目前建议你id不要写成一致的。
