### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jameltheone** [CymChad/BaseRecyclerViewAdapterHelper#919]
Hi,

Started from the version 2.8.8 i have a NullPointerException when using a headerView. Please, notice that with the version below everything is working well, and even with the last update 2.9.1 i still have the issue.

The code causing the bug is below:

````
@Override
    protected void convertHead(BaseViewHolder baseViewHolder, MySection mySection) {
    //......
    baseViewHolder
                    .addOnClickListener(R.id.moreBtn) // <== Bugging here
                    .addOnClickListener(R.id.replayBtn)
                    .addOnClickListener(R.id.favoriteBtn);
    //.....
    }
````

And in the library it is getting the NullPointerException at

> com.chad.library.adapter.base.BaseViewHolder.addOnClickListener (BaseViewHolder line 355 with library version 2.9.1)

Thank you

**Comment by tysheng** [comment]
you cannot do like this when use convert, check out the source code.

```View headerView = inflate bla bla1
     Button button = headerView findView blabla
    button.setOnClickListener() bla bla
```

**Comment by jameltheone** [comment]
Maybe i'm wrong but i used the demo code and in the SectionAdapter.java there is:

```
@Override
    protected void convertHead(BaseViewHolder helper,final MySection item) {
        helper.setText(R.id.header, item.header);
        helper.setVisible(R.id.more,item.isMore());
        helper.addOnClickListener(R.id.more);
    }
```

Moreover, the code were working till the 2.8.8 update and i didn't change anything.

**Comment by tysheng** [comment]
@AllenCoder check this

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.2'

**Comment by jameltheone** [comment]
Great thank you, it's now working
