### ISSUE TITLE
添加头部刷新问题

### ISSUE THREAD

**Issue by 1programmer2dfg3** [CymChad/BaseRecyclerViewAdapterHelper#920]
我是数据请求成功之后设置的数据，然后把头部添加进去，但问题是现在点击一个页面，数据成功加载出来了，点击最后一个item的子控件会响应，然后当我下拉刷新一下，点击最后一个item的子控件的时候没有反应，无法响应（我在刷新的时候移除了头部，然后数据请求成功的时候添加的头部），请问这是啥原因？
这是我下拉刷新的代码
 //下拉刷新数据
    @Override
    public void onRefresh() {
        refreshstatus = 1;
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                page = 1;
                initData();
                isErr = false;
                newhouseListData.clear();
                houseAdapter.removeHeaderView(headView);
                houseAdapter.notifyDataSetChanged();
                swipeRefresh.setRefreshing(false);
            }
        }, 100);
    }

**Comment by CymChad** [comment]
版本号？
