### ISSUE TITLE
列表为空的时候，添加的头可以显示出来么？

### ISSUE THREAD

**Issue by wcglws** [CymChad/BaseRecyclerViewAdapterHelper#922]
当前版本2.9，
是这么个情况，给recyclerview添加的头是banner轮播和列表不是一个接口，banner有数据，列表没有，怎么让头部显示出来呢？当前这个版本可以实现么？请大神赐教

**Comment by CymChad** [comment]
setHeaderAndEmpty

**Comment by wcglws** [comment]
大神，添加的空布局显示不出来，有错么？
我在初始化的时候
![Uploading image.png…]()

数据判空的时候
![Uploading image.png…]()

**Comment by wcglws** [comment]
初始化recyclerview的时候
mEmptyView = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) mRlvBuyProduct.getParent(), false);

数据判空的时候
 new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    mAdapter.setEmptyView(mEmptyView);
                }
            }, 1000);

为啥为空的布局不显示呢

**Comment by wcglws** [comment]
解决了，哈哈

**Comment by wcglws** [comment]
大神又来麻烦你了。。头和空布局一起显示的时候出现了这个情况，只显示头的时候是好的
![78105463979031607](https://cloud.githubusercontent.com/assets/16982083/24387390/69bc4906-13a7-11e7-9ce2-233216ddfdd8.jpg)
