### ISSUE TITLE
上拉加载的问题

### ISSUE THREAD

**Issue by shoushuai** [CymChad/BaseRecyclerViewAdapterHelper#923]
我想用别的下拉上拉刷新框架,有没有和BRVAH结合使用的,我用的CommonPullToRefresh,发现加载有问题,谢谢.

**Comment by CymChad** [comment]
你只要不开启 BRVAH的上拉 应该不会和其他的有冲突的，有什么问题？

**Comment by shoushuai** [comment]
CommonPullToRefresh这个框架使用上拉加载时,适配器需继承RecyclerView.Adapter,然后 mAdapter = new RecyclerAdapterWithHF(adapter);封装一下才能用,继承冲突了

**Comment by CymChad** [comment]
建议你可以使用，https://github.com/anzaizai/EasyRefreshLayout

**Comment by shoushuai** [comment]
恩恩,我试试,还有个问题,我数据是直接传到适配器的,没用dataserver,是不是你那更好啊?

**Comment by CymChad** [comment]
都一样

**Comment by shoushuai** [comment]
嗯,谢谢解答

**Comment by CymChad** [comment]
恩，他的demo都有例子的，有问题再问。
