### ISSUE TITLE
adapter.setOnItemLongClickListener长按事件不能触发

### ISSUE THREAD

**Issue by jayleco** [CymChad/BaseRecyclerViewAdapterHelper#925]
**版本是最新的2.9.2**

followListAdapter.setOnItemLongClickListener(new BaseQuickAdapter.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(FollowListActivity.this, "姥姥的！你要删了老娘？：" + Integer.toString(position), Toast.LENGTH_SHORT).show();
                Log.e("长按执行了：", position + "");
                return false;
            }
        });

**adapter的代码如下：**

public class FollowListAdapter extends BaseQuickAdapter<FollowListItemBean, BaseViewHolder> {
    public FollowListAdapter(int layoutResId, List<FollowListItemBean> data) {
        super(layoutResId, data);
    }
    @Override
    protected void convert(BaseViewHolder helper, FollowListItemBean item) {
        helper.setText(R.id.tv_followListTitle, item.getItemTitle());
        Uri uri = Uri.parse(String.valueOf(Uri.parse(item.getItemImage())));
        SimpleDraweeView draweeView = helper.getView(R.id.iv_followListImage);
        draweeView.setImageURI(uri);
}

**同样的适配器，adapter.setOnItemClickListener点击事件正常**

**Comment by AllenCoder** [comment]
应该是你的使用姿势不对，我这边测试都是正常的。可以单独抽出一个Demo测试看下，如果还不能触发长按事件，请将Demo发送给我，我来排除原因

**Comment by whiteGG** [comment]
我也是setOnItemLongClickListener 不能触发

**Comment by manburenshenglu** [comment]
+1，长按不能触发

**Comment by 1913656443** [comment]
+1

**Comment by ihewro** [comment]
我也遇到这个问题，最后解决了：

1. 如果子view设置了`android:focusable="true" android:clickable="true"`，那么adapter的`setOnItemClickListener`是不起作用的

2. 如果要对整个Item设置点击事件，不能在`convert`函数里面`this.setOnItemClickListener`绑定，可以构造器里面，或者在activity里面绑定事件。对item的子view进行绑定事件，可以在`convert`函数里面
