### ISSUE TITLE
一个粗心的bug

### ISSUE THREAD

**Issue by DanteAndroid** [CymChad/BaseRecyclerViewAdapterHelper#928]
![image](https://cloud.githubusercontent.com/assets/10005563/24391225/5e5c84c2-13c0-11e7-970f-66f6f696c407.png)
前面判断了不为空，后面却把语句写在了判断不为空的外面。。。

解决办法：
```
if (!view.isClickable()) {
            view.setClickable(true);
        }
```
移动到
```
         if (view!=null){
}
```
内即可。感谢。

**Comment by AllenCoder** [comment]
新版本已经修复了。你这是哪个版本？

**Comment by DanteAndroid** [comment]
谢谢，你们更新速度也太快了。。。
