### ISSUE TITLE
addHeaderView(mGridView)会有问题

### ISSUE THREAD

**Issue by bowen-xiao** [CymChad/BaseRecyclerViewAdapterHelper#929]
在页面onResume的时候会莫名去滚动到GridView处。

**Comment by 1109993488** [comment]
onResume重新设置数据源了吗？

**Comment by bowen-xiao** [comment]
没有，GridView的高度不知道为何一直在变，每次onResume的时候

**Comment by 1109993488** [comment]
你可以把GridView换成RecyclerView，或者重新计算GridView的高度

**Comment by bowen-xiao** [comment]
是的这样可以解决这个问题。Thanks!

**Comment by alen252** [comment]
> 是的这样可以解决这个问题。Thanks!

是换成RecyclerView解决的吗？我也遇到这个问题，就是在滑动RecyclerView的时候也自动滚到GridView那里。
