### ISSUE TITLE
头部添加轮播图，如何在轮播图上就能下拉刷新

### ISSUE THREAD

**Issue by mpxl** [CymChad/BaseRecyclerViewAdapterHelper#93]
如题

**Comment by CymChad** [comment]
下拉刷新本框架不提供，可以由开发者组合第三方控件进行实现。

**Comment by mpxl** [comment]
好吧，感谢

**Comment by mpxl** [comment]
您能否提供一个思路？感谢<android.support.v4.widget.SwipeRefreshLayout android:id="@+id/swipeLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/bg"
    android:orientation="vertical"
    xmlns:android="http://schemas.android.com/apk/res/android">

        <include
            android:id="@+id/auto_viewpager"
            layout="@layout/viewpager_auto" />

        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </android.support.v4.widget.SwipeRefreshLayout>这样写，都不能下拉刷新

**Comment by CymChad** [comment]
你这样写，是不对的SwipeRefreshLayout只能包裹一个布局，思路监听RecyclerView的滑动，我建议你去看看有些开源项目，他们改了RecyclerView做了下拉刷新。
