### ISSUE TITLE
关于BaseSectionQuickAdapter的convertHead接口回调建议

### ISSUE THREAD

**Issue by yezishu** [CymChad/BaseRecyclerViewAdapterHelper#933]
我在导入我们这个库进行多一层封装的时候发现，这个类疑似还残留以前旧版本，写死入参数定义。

BaseSectionQuickAdapter的第57行代码 参数 BaseViewHolder helper：
`protected abstract void convertHead(BaseViewHolder helper, T item);`

后面我封装的时候只能进行代码拷贝封装了，没办法直接继承。建议修改如下
` protected abstract void convertHead(K helper, T item);`

**Comment by CymChad** [comment]
恩，收到，我看看。

**Comment by yezishu** [comment]
如果是我理解错误，可否指点一下，非常感谢。

**Comment by CymChad** [comment]
确实是残留固定参数定义，我马上修改并打包上传

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.3'
