### ISSUE TITLE
addHeadview issue

### ISSUE THREAD

**Issue by LiuShengDong** [CymChad/BaseRecyclerViewAdapterHelper#934]
![i8ntkpn4vwfh d2 k3i c8n](https://cloud.githubusercontent.com/assets/23098642/24402851/e98fb466-13ec-11e7-866c-6797cc79adbb.png)
如图，我用的版本是v2.0.0，烦请大神帮忙看下，谢谢。问题表现：点击headerview（第一个item）没问题，点击第二个item（第一条数据）就抛异常。点击后面的都没问题

**Comment by CymChad** [comment]
请更新至最新版，如果有问题修改都是针对最新版代码修改。

**Comment by LiuShengDong** [comment]
那请问最新版有修改addheaderview之后position的问题吗？

**Comment by LiuShengDong** [comment]
已改为最新版本，但是问题仍旧，能麻烦问下position要怎么处理吗？谢谢

**Comment by CymChad** [comment]
点击就报错？

**Comment by CymChad** [comment]
还是你操作了什么

**Comment by LiuShengDong** [comment]
没操作什么，就是点击后抛上面的异常，我也参照你源码试过了，也换过其他机型，都一样

**Comment by CymChad** [comment]
看下你的代码

**Comment by LiuShengDong** [comment]
我已经换成listview的addheaderview了。。。。谢谢回复啦。
