### ISSUE TITLE
NestedScrollView 嵌套RecyclerView使用的时候，咱这个组件onLoadMore事件总是自己触发？有没有解决方案呢？

### ISSUE THREAD

**Issue by richfuns** [CymChad/BaseRecyclerViewAdapterHelper#935]
页面打开之后，会连续触发onLoadMore事件，不停的加载下一页，直接所有数据加载完成，只有嵌套使用才有这种情况

请教大神，这是什么问题？ 求比较好的建议，谢谢

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/623

**Comment by richfuns** [comment]
mAdapter.disableLoadMoreIfNotFullPage();  不管用， 我的页面只是下半部分显示列表
