### ISSUE TITLE
子控件的点击事件问题

### ISSUE THREAD

**Issue by hellobenji** [CymChad/BaseRecyclerViewAdapterHelper#936]
在设置点击事件的同时。我想获取该位置的数据。请请问有什么方法可以直接过去该位置的数据么？

ps：因为是分页的每次请求的数据都是只有几条。现在的思路就是将每次请求的数据都放在一个集合里边
然后用这个list。get（posit）得到数据
还有更好的方法么

**Comment by CymChad** [comment]
点击事件不是给了你一个adapter对象吗？
你可以直接adapter.getData.get(position)
