### ISSUE TITLE
关于item布局自定义九宫格图片控件点击事件

### ISSUE THREAD

**Issue by Android-KJY** [CymChad/BaseRecyclerViewAdapterHelper#937]
package com.jiujiuyun.laijie.widget;

import android.content.Context;
import android.content.res.Resources;
import android.content.res.TypedArray;
import android.os.Build;
import android.support.annotation.RequiresApi;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;

import com.bumptech.glide.BitmapRequestBuilder;
import com.bumptech.glide.Glide;
import com.bumptech.glide.RequestManager;
import com.jiujiuyun.laijie.R;
import com.jiujiuyun.laijie.base.BaseRecyclerAdapter;
import com.jiujiuyun.laijie.base.api.remote.JiuJiuYunApi;
import com.jiujiuyun.laijie.media.ImageGalleryActivity;

/**
 * Created by JuQiu
 * on 16/8/26.
 */
public class TweetPicturesLayout extends ViewGroup implements View.OnClickListener {
    private static final int SINGLE_MAX_W = 120;
    private static final int SINGLE_MAX_H = 180;
    private static final int SINGLE_MIN_W = 34;
    private static final int SINGLE_MIN_H = 34;

    private String[] mImages;
    private float    mVerticalSpacing;
    private float    mHorizontalSpacing;
    private int      mColumn;
    private int      mMaxPictureSize;

    private boolean isShowBigPic = true;//单张图片是，是否显示大图！

    public TweetPicturesLayout(Context context) {
        this(context, null);
    }

    public TweetPicturesLayout(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public TweetPicturesLayout(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(attrs, defStyleAttr, 0);
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public TweetPicturesLayout(Context context, AttributeSet attrs, int defStyleAttr,
            int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
        init(attrs, defStyleAttr, defStyleRes);
    }

    private void init(AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        final Context   context   = getContext();
        final Resources resources = getResources();
        final float     density   = resources.getDisplayMetrics().density;

        int vSpace = (int) (4 * density);
        int hSpace = vSpace;

        if (attrs != null) {
            // Load attributes
            final TypedArray a = context
                    .obtainStyledAttributes(attrs, R.styleable.TweetPicturesLayout, defStyleAttr,
                                            defStyleRes);

            // Load clip touch corner radius
            vSpace = a
                    .getDimensionPixelOffset(R.styleable.TweetPicturesLayout_verticalSpace, vSpace);
            hSpace = a.getDimensionPixelOffset(R.styleable.TweetPicturesLayout_horizontalSpace,
                                               hSpace);
            setColumn(a.getInt(R.styleable.TweetPicturesLayout_column, 3));
            setMaxPictureSize(
                    a.getDimensionPixelOffset(R.styleable.TweetPicturesLayout_maxPictureSize, 0));
            a.recycle();
        }

        setVerticalSpacing(vSpace);
        setHorizontalSpacing(hSpace);
    }

    public void setHorizontalSpacing(float pixelSize) {
        mHorizontalSpacing = pixelSize;
    }

    public void setVerticalSpacing(float pixelSize) {
        mVerticalSpacing = pixelSize;
    }

    public void setColumn(int column) {
        if (column < 1) column = 1;
        if (column > 20) column = 20;
        mColumn = column;
    }

    public void setMaxPictureSize(int maxPictureSize) {
        if (maxPictureSize < 0) maxPictureSize = 0;
        mMaxPictureSize = maxPictureSize;
    }

    private BaseRecyclerAdapter adapter;

    //拼接地址
    public void setImages(String[] images, BaseRecyclerAdapter adapter) {
        final int size = images == null ? 0 : images.length;
        String[]  list = new String[size];
        for (int i = 0; i < size; i++) {
            list[i] = JiuJiuYunApi.getImageUrl(images[i]);
        }
        this.adapter = adapter;
        setImage(list);
    }

    //拼接地址
    public void setImages(String[] images) {
        final int size = images == null ? 0 : images.length;
        String[]  list = new String[size];
        for (int i = 0; i < size; i++) {
            list[i] = JiuJiuYunApi.getImageUrl(images[i]);
        }
        setImage(list);
    }

    public void setImage(String[] images, int size) {
        if (mImages == images) return;
        removeAllImage();
        mImages = images;
        if (images != null && images.length > 0) {
            LayoutInflater inflater       = LayoutInflater.from(this.getContext());
            RequestManager requestManager = Glide.with(getContext());
            for (int i = 0; i < size; i++) {
                View view = inflater.inflate(R.layout.lay_tweet_image_item, this, false);
                view.setTag(i);
                view.setOnClickListener(this);
                String path = images[i];
                //                KLog.w(path);
                BitmapRequestBuilder builder = requestManager.load(path).asBitmap().centerCrop()
                                                             //.placeholder(R.color.grey_50)
                                                             .error(R.mipmap.ic_split_graph);

                if (path.toLowerCase().endsWith("gif")) {
                    //builder = builder.diskCacheStrategy(DiskCacheStrategy.SOURCE);
                    view.findViewById(R.id.iv_is_gif).setVisibility(VISIBLE);
                }
                addView(view);
                builder.into((ImageView) view.findViewById(R.id.iv_picture));
            }

            // all do requestLayout
            if (getVisibility() == VISIBLE) {
                requestLayout();
                //                if (adapter != null) adapter.notifyDataSetChanged();
            } else {
                setVisibility(View.VISIBLE);
            }
        } else {
            setVisibility(View.GONE);
        }
    }

    public void setImage(String[] images) {
        if (mImages == images) return;
        removeAllImage();
        mImages = images;
        if (images != null && images.length > 0) {
            LayoutInflater inflater       = LayoutInflater.from(this.getContext());
            RequestManager requestManager = Glide.with(getContext());
            for (int i = 0; i < images.length; i++) {
                View view = inflater.inflate(R.layout.lay_tweet_image_item, this, false);
                view.setTag(i);
                view.setOnClickListener(this);
                String path = images[i];
                //KLog.w(path);
                BitmapRequestBuilder builder = requestManager.load(path).asBitmap().centerCrop()
                                                             // .placeholder(R.color.grey_50)
                                                             .error(R.mipmap.ic_split_graph);

                if (path.toLowerCase().endsWith("gif")) {
                    //builder = builder.diskCacheStrategy(DiskCacheStrategy.SOURCE);
                    view.findViewById(R.id.iv_is_gif).setVisibility(VISIBLE);
                }
                addView(view);
                builder.into((ImageView) view.findViewById(R.id.iv_picture));
            }

            // all do requestLayout
            if (getVisibility() == VISIBLE) {
                requestLayout();
                //                if (adapter != null) adapter.notifyDataSetChanged();
            } else {
                setVisibility(View.VISIBLE);
            }
        } else {
            setVisibility(View.GONE);
        }
    }

    public void removeAllImage() {
        removeAllViews();
        mImages = null;
    }

    private int getMaxChildSize(int size) {
        if (mMaxPictureSize == 0) return size;
        else return Math.min(mMaxPictureSize, size);
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int paddingLeft   = getPaddingLeft();
        int paddingTop    = getPaddingTop();
        int paddingRight  = getPaddingRight();
        int paddingBottom = getPaddingBottom();

        int       selfWidth    = resolveSize(paddingLeft + paddingRight, widthMeasureSpec);
        int       wantedHeight = paddingBottom + paddingTop;
        final int childCount   = getChildCount();

        //noinspection StatementWithEmptyBody
        if (childCount == 0) {
            // Not have child we can only need padding size
        } else if (childCount == 1 && isShowBigPic) {
            View child = getChildAt(0);
            //            int imageW = mImages[0].getW();
            //            int imageH = mImages[0].getH();
            int imageH = 60;
            int imageW = 60;

            float density = getResources().getDisplayMetrics().density;
            // Get max width and height
            float maxContentW = Math
                    .min(selfWidth - paddingRight - paddingLeft, density * SINGLE_MAX_W);
            float maxContentH = density * SINGLE_MAX_H;

            int childW, childH;

            float hToW = imageH / (float) imageW;
            if (hToW > (maxContentH / maxContentW)) {
                childH = (int) maxContentH;
                childW = (int) (maxContentH / hToW);
            } else {
                childW = (int) maxContentW;
                childH = (int) (maxContentW * hToW);
            }
            // Check the width and height below Min values
            int minW = (int) (SINGLE_MIN_W * density);
            if (childW < minW) childW = minW;
            int minH = (int) (SINGLE_MIN_H * density);
            if (childH < minH) childH = minH;

            child.measure(MeasureSpec.makeMeasureSpec(childW, MeasureSpec.EXACTLY),
                          MeasureSpec.makeMeasureSpec(childH, MeasureSpec.EXACTLY));

            wantedHeight += childH;
        } else {
            // Measure all child
            final float maxContentWidth = selfWidth - paddingRight - paddingLeft - mHorizontalSpacing * (mColumn - 1);
            // Get child size
            final int childSize = getMaxChildSize((int) (maxContentWidth / mColumn));

            for (int i = 0; i < childCount; ++i) {
                View childView = getChildAt(i);
                childView.measure(MeasureSpec.makeMeasureSpec(childSize, MeasureSpec.EXACTLY),
                                  MeasureSpec.makeMeasureSpec(childSize, MeasureSpec.EXACTLY));
            }

            int lines = (int) (childCount / (float) mColumn + 0.9);
            wantedHeight += (int) (lines * childSize + mVerticalSpacing * (lines - 1));
        }

        setMeasuredDimension(selfWidth, resolveSize(wantedHeight, heightMeasureSpec));
    }

    @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        float childCount = getChildCount();
        if (childCount > 0) {
            int paddingLeft = getPaddingLeft();
            int paddingTop  = getPaddingTop();

            if (childCount == 1) {
                View childView   = getChildAt(0);
                int  childWidth  = childView.getMeasuredWidth();
                int  childHeight = childView.getMeasuredHeight();
                childView.layout(paddingLeft, paddingTop, paddingLeft + childWidth,
                                 paddingTop + childHeight);
            } else {
                int mWidth       = r - l;
                int paddingRight = getPaddingRight();

                int lineHeight = 0;
                int childLeft  = paddingLeft;
                int childTop   = paddingTop;

                for (int i = 0; i < childCount; ++i) {
                    View childView = getChildAt(i);

                    if (childView.getVisibility() == View.GONE) {
                        continue;
                    }

                    int childWidth  = childView.getMeasuredWidth();
                    int childHeight = childView.getMeasuredHeight();

                    lineHeight = Math.max(childHeight, lineHeight);

                    if (childLeft + childWidth + paddingRight > mWidth) {
                        childLeft = paddingLeft;
                        childTop += mVerticalSpacing + lineHeight;
                        lineHeight = childHeight;
                    }
                    childView.layout(childLeft, childTop, childLeft + childWidth,
                                     childTop + childHeight);
                    childLeft += childWidth + mHorizontalSpacing;
                }
            }
        }
    }

    @Override
    public void onClick(View v) {
        String[] images = mImages;
        if (images == null) return;

        Object obj = v.getTag();
        if (obj == null || !(obj instanceof Integer)) return;

        int index = (int) obj;
        if (index < 0) index = 0;
        if (index >= images.length) index = images.length - 1;

        ImageGalleryActivity.show(getContext(), images, index);
    }

    public void setShowBigPic(boolean showBigPic) {
        isShowBigPic = showBigPic;
    }
}
这是自定义九宫格图片布局，但是里面的图片点击事件会监听不到

**Comment by AllenCoder** [comment]
你自定义控件实现了View.OnClickListener接口，那么你的子控件的点击应用是受他控制的，外层的adapter点击事件应该采用最新版2.9.2的写法去实现
