### ISSUE TITLE
刷新和加载时,添加数据的问题

### ISSUE THREAD

**Issue by shoushuai** [CymChad/BaseRecyclerViewAdapterHelper#938]
我刚开始用,对于setNewData和addData不懂,因为我以前刷新:数据清空,下载第一页数据添加集合,加载:下载第几页数据添加,最后刷新>>>>>
刷新和加载都是走getDataFromNet()下载数据,添加数据时不知道怎么办,难道是判断刷新还是加载用这两个方法?

**Comment by shoushuai** [comment]
刷新和加载都是走getDataFromNet()下载数据,添加数据时不知道怎么办

**Comment by CymChad** [comment]
addData 为追加数据，setNewData第一次加载数据和下拉刷新时使用。
