### ISSUE TITLE
自定义viewholder

### ISSUE THREAD

**Issue by zhupengxiang** [CymChad/BaseRecyclerViewAdapterHelper#939]
最新版还是必须要重写
![qq 20170329152054](https://cloud.githubusercontent.com/assets/17894209/24443065/ae2bd998-1493-11e7-9623-90b5b5762b64.png)

**Comment by CymChad** [comment]
@QtyearLin

**Comment by QtyearLin** [comment]
@zhupengxiang  adapter 作为内部类 请重写

**Comment by zhupengxiang** [comment]
@QtyearLin  我的不是内部类

**Comment by CymChad** [comment]
这周末我有空看看，你能抽出demo，我这边帮你看看 @zhupengxiang

**Comment by CymChad** [comment]
明天看看，上周有事去了，实在抱歉

**Comment by CymChad** [comment]
刚才测试了一下，没有问题。
[MyApplication 2.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/965885/MyApplication.2.zip)
我把demo上传了你可以看下
