### ISSUE TITLE
关于伸缩栏

### ISSUE THREAD

**Issue by cwjfeifei** [CymChad/BaseRecyclerViewAdapterHelper#940]
第一，展开视图不能是网格形式，只能是列表形式，第二，在head无法获取到展开视图数量（这个是因为如果展开视图为空的话就会崩溃）

**Comment by elfman** [comment]
1. 展开的view如果要使用网格形式，可以通过GridLayoutManager的setSpanSizeLookup来将展开后的view定义为限定宽度。
2. 这个应该是你使用方法有误，请自行处理
