### ISSUE TITLE
点击事件：有时点击item上的子view时，触发的却是item的点击事件

### ISSUE THREAD

**Issue by zhengjieAdriod** [CymChad/BaseRecyclerViewAdapterHelper#944]
sectionAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                MySection mySection = mData.get(position);
                if (mySection.isHeader)
                    Toast.makeText(SectionUseActivity.this, mySection.header, Toast.LENGTH_SHORT).show();
                else
                    Toast.makeText(SectionUseActivity.this, mySection.t.getName(), Toast.LENGTH_SHORT).show();
            }
        });
        sectionAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public boolean onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(SectionUseActivity.this, "onItemChildClick" + position, Toast.LENGTH_SHORT).show();
                return false;
            }
        });

**Comment by CymChad** [comment]
return false;  改成 return true;试一下

**Comment by zhengjieAdriod** [comment]
还是这样...

**Comment by AllenCoder** [comment]
请自查：1. 是否绑定了item childview的控件id  2. 绑定的childview 可点击区域太小没有触发

**Comment by zhengjieAdriod** [comment]
是的  是可点击区域太小导致的。   不是库的问题 。  谢谢啦...
