### ISSUE TITLE
关于adpter删除item的建议

### ISSUE THREAD

**Issue by lianghuiyong** [CymChad/BaseRecyclerViewAdapterHelper#946]
建议：新增一个 **remove（itemBean）** 的方法

原因：在使用拖拽重新排序和先删除了某一项的时候，列表的顺序不同了，需要重新找到对应的position，然后再对列表删除对应正确的item，比较繁琐，而且我现在还不能正确拿到position，在非itemOnListener点击事件对列表进行删除

**Comment by lianghuiyong** [comment]
刚刚查到，可以通过List 的 .indexOf()的方法解决，(*^__^*) 嘻嘻……

**Comment by CymChad** [comment]
👍
