### ISSUE TITLE
大神，BaseQuickAdapter<List<Goods>,BaseViewHolderHelper>List<List<>>,如果嵌套list,会报错

### ISSUE THREAD

**Issue by yxyaxng** [CymChad/BaseRecyclerViewAdapterHelper#947]
Methods addData(int, T) from com.chad.library.adapter.base.BaseQuickAdapter and addData(int, List<T>) from com.chad.library.adapter.base.BaseQuickAdapter are inherited with the same signatur

**Comment by CymChad** [comment]
版本号？

**Comment by yxyaxng** [comment]
版本号是2.9.3

**Comment by yxyaxng** [comment]
如果用Object代替，然后用的时候进行强转是没问题的

**Comment by MorrisWare01** [comment]
改成BaseQuickAdapter<ArrayList<Goods>,BaseViewHolderHelper>就可以了

**Comment by CymChad** [comment]
@MorrisWare01 感谢你的回答

**Comment by panhongzhi02** [comment]
错误原因是BaseQuickAdapter的addData（int，T）和addData（int，List<T>）名字一样的原因造成的嵌套，建议在新的版本是不是addDatas（int，List<T>）？

**Comment by CymChad** [comment]
恩，收录 建议  #907
