### ISSUE TITLE
自动加载的bug

### ISSUE THREAD

**Issue by Guolei1130** [CymChad/BaseRecyclerViewAdapterHelper#948]
private void autoLoadMore(int position) {
        if(this.getLoadMoreViewCount() != 0) {
            if(position >= this.getItemCount() - this.mAutoLoadMoreSize) {
                if(this.mLoadMoreView.getLoadMoreStatus() == 1) {
                    this.mLoadMoreView.setLoadMoreStatus(2);
                    if(!this.mLoading) {
                        this.mLoading = true;
                        this.mRequestLoadMoreListener.onLoadMoreRequested();
                    }

                }
            }
        }
    }

没考虑加header或者GridLayoutManager,之类的情况。

- [ ]

**Comment by 1109993488** [comment]
这个方法是从末尾计算数量的，getItemCount已经包含header，GridLayoutManager也是支持的，传入的position是要显示的ViewHolder的位置
