### ISSUE TITLE
关于BaseMultiItemQuickAdapter的问题

### ISSUE THREAD

**Issue by a48352433** [CymChad/BaseRecyclerViewAdapterHelper#949]
我在点击事件里动态添加的了一个subitem.然后adapter通知数据变化,但是recyckerview显示并没有变化.
然后手动调用一下展开或者收缩显示才有变化.
还有直接设置setSubItems(newSubLists);也有同样的问题.难道是我打开方式不对么?刚刚才用你们库,还没有仔细研究.
  
                       `TrainingModel m = (TrainingModel) adapter.getData().get(0);

                        TrainingModel submodel = new TrainingModel();

                        submodel.setName("tttttttt");

                        submodel.setLevle(1);

                        m.addSubItem(submodel);

                        adapter.notifyDataSetChanged();

                        adapter.notifyItemChanged(adapter.getData().indexOf(m));

                        adapter.notifyItemChanged(adapter.getData().indexOf(m), m);`

**Comment by CymChad** [comment]
折叠->展开：mData添加需展开的数据集，更新数据源；展开->折叠：mData移除需折叠的数据集，更新数据源。

**Comment by CymChad** [comment]
以上是实现原理，所以刷新无效。

**Comment by CymChad** [comment]
具体原理可以看  [BRVAH源码分析:分组、多布局、折叠](https://mp.weixin.qq.com/s?__biz=MzIwMzYwMTk1NA==&mid=2247483885&idx=1&sn=392e12f9576051a2536cc648abd22422&chksm=96cda0a0a1ba29b6dc3566d0180d148c5acc9194089f1252e6e1e1d47076806fb16c333af97b&mpshare=1&scene=23&srcid=03244moVeNrZ1jHouIy8Z0ZH#rd)
