### ISSUE TITLE
pullToRefreshAdapter加载数据失败时，添加头布局不显示

### ISSUE THREAD

**Issue by linxi926959** [CymChad/BaseRecyclerViewAdapterHelper#951]
pullToRefreshAdapter.setEmptyView(R.layout.empty);
pullToRefreshAdapter.addHeaderView(headView);
展示了空布局后再添加头布局，头布局就不显示了

**Comment by CymChad** [comment]
如果想同时显示可以使用`mQuickAdapter.setHeaderAndEmpty`
