### ISSUE TITLE
viewpager+fragment item点击事件执行2次

### ISSUE THREAD

**Issue by fuxianwen** [CymChad/BaseRecyclerViewAdapterHelper#952]
viewpager+fragment item点击事件执行2次  发生率很高

onSimpleItemClick
-

**Comment by JueShouGitHub** [comment]
对，这个问题我也遇见过，我不得已用一个变量标记判断了一下。。。

**Comment by CymChad** [comment]
估计是你的add点击事件执行了两次的问题， 你可以使用最新版的setOnItemClickListener。具体可看wiki

**Comment by fuxianwen** [comment]
那个事件没问题
