### ISSUE TITLE
进入界面的时候会自动走上拉方法.

### ISSUE THREAD

**Issue by zggxxsh** [CymChad/BaseRecyclerViewAdapterHelper#953]
上拉不 是通过滑动监听的吗

**Comment by CymChad** [comment]
不是的

**Comment by CymChad** [comment]
是通过判断是否滑到最后一个item来判断的

**Comment by zggxxsh** [comment]
当前分页未铺满当页时,会自动加载直至铺满当页?

**Comment by CymChad** [comment]
这个你可以在会调用处理。

**Comment by CymChad** [comment]
不满足一页理论上也不可能上拉加载。

**Comment by imLibo** [comment]
2.9.9我这里出现一个问题，一进入界面就会不停地调用onLoadMoreRequested
`mBinding.rcvPlanList.setLayoutManager(new LinearLayoutManager(mActivity));
        mAdapterOfList = new PlanNewDayAdapter(R.layout.item_plan_new_second, mPlanList);
        mAdapterOfList.setOnLoadMoreListener(this, mBinding.rcvPlanList);
        mAdapterOfList.openLoadAnimation(BaseQuickAdapter.SLIDEIN_BOTTOM);
        mAdapterOfList.setOnItemChildClickListener(this);
        mAdapterOfList.setOnItemClickListener(this);
        mBinding.rcvPlanList.setAdapter(mAdapterOfList);`
