### ISSUE TITLE
disableLoadMoreIfNotFullPage 无效

### ISSUE THREAD

**Issue by sj853** [CymChad/BaseRecyclerViewAdapterHelper#954]
disableLoadMoreIfNotFullPage 
我的理解是  是不是 列表项还没有沾满显示区域(可能数据很少的情况下) 是不会出发加载更多···
但是感觉每次进来的时候 onLoadMoreRequested走了回调实际上数据只有1 2条如下图

![image](https://cloud.githubusercontent.com/assets/3139596/24552768/55ddf7ee-165a-11e7-90a8-8e39e08ef809.png)

主要代码如下
![image](https://cloud.githubusercontent.com/assets/3139596/24552773/5c856d52-165a-11e7-9193-77634869dbcb.png)

**Comment by tysheng** [comment]
其实注释中有用法，我还是再说明一下

比如你第一次从网络中得到list,是不是要setNewData?,这个方法是在setNewData之后检查调用的

**Comment by sj853** [comment]
@tysheng  是的  第一次获取用了setNewData  
  我现在 就自己判断  如果没显示完 就 loadMoreEnd(true);

**Comment by tysheng** [comment]
```
adapter.setNewData;
adapter.disableLoadMoreIfNotFullPage;
```
这样用，你想达到什么效果？

**Comment by tysheng** [comment]
@sj853 我是说你调用的位置不对，应该在setNewData之后调用

**Comment by sj853** [comment]
哦哦 我以为是一个配置项

**Comment by sj853** [comment]
@tysheng  我刚又试了一次  第一次确实使用 setnewdata  后面 加入了 disableLoadMoreIfNotFullPage  依然无效

**Comment by sj853** [comment]
![image](https://cloud.githubusercontent.com/assets/3139596/24693411/0ce09f9c-1a10-11e7-8c08-2a9914e09d7a.png)

如图哈

**Comment by tysheng** [comment]
sorry,我自己封装过了，忘记加一行 setEnableLoadMore(false);了

加在disableLoadMoreIfNotFullPage 前面

**Comment by tysheng** [comment]
@CymChad 帮忙加一行 setEnableLoadMore(false); 在 disableLoadMoreIfNotFullPage 最前面,谢谢

**Comment by CymChad** [comment]
@tysheng 收到

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.4'
