### ISSUE TITLE
下拉刷新时，图标有一小部分露在外面。

### ISSUE THREAD

**Issue by wolfnx** [CymChad/BaseRecyclerViewAdapterHelper#956]
swiperefreshlayout下拉刷新时，如果下拉后不松手，再将其推上去，那个圆圈有一小部分露在外面。然后上划那一小部分还是一直留在外面不消失。我看github上面好多库都是这样，为什么？

**Comment by CymChad** [comment]
下拉刷新与本库无关。

**Comment by wolfnx** [comment]
与本库无关是什么意思？你这个库里不就是有下拉刷新啊，说的就是你这个库

**Comment by wolfnx** [comment]
上面的白圈有一点点留在外面

[cid:image001.jpg@01D2B3B6.949EA390]
发件人: 陈宇明 [mailto:notifications@github.com]
发送时间: 2017年4月6日 11:00
收件人: CymChad/BaseRecyclerViewAdapterHelper <BaseRecyclerViewAdapterHelper@noreply.github.com>
抄送: wolfnx <wolfnx@outlook.com>; Author <author@noreply.github.com>
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 下拉刷新时，图标有一小部分露在外面。 (#956)


下拉刷新与本库无关。

**Comment by CymChad** [comment]
这个库的下拉刷新是用的Google的下拉刷新控件SwipeRefreshLayout，还有这个上面可以发图片
![image](https://cloud.githubusercontent.com/assets/7698209/24967584/328a4e46-1fdd-11e7-9cd4-5001cdc4aae7.png)
