### ISSUE TITLE
版本更新Api更新

### ISSUE THREAD

**Issue by hxxxxxxxk** [CymChad/BaseRecyclerViewAdapterHelper#961]
请问，2.5.0版的adapter.showLoadMoreFailedView() 对应 2.6.8版的哪个api？

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD 

建议升级最新版本

**Comment by hxxxxxxxk** [comment]
@CymChad 谢谢
