### ISSUE TITLE
itemView的点击事件和item中子view的点击事件同时响应

### ISSUE THREAD

**Issue by llol** [CymChad/BaseRecyclerViewAdapterHelper#962]
同时给itemView和他里面的其他子view添加点击事件时，两个事件同时响应！建议修复

**Comment by AllenCoder** [comment]
请详细参考使用文档 ：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E6%B7%BB%E5%8A%A0Item%E4%BA%8B%E4%BB%B6
