### ISSUE TITLE
loadingView

### ISSUE THREAD

**Issue by shingohu** [CymChad/BaseRecyclerViewAdapterHelper#97]
loadingView 点击能否开放出来,而不是放到itemclick事件中,否则点击itemclick 不做处理会数组越界

**Comment by CymChad** [comment]
恩，好的。我看看先

**Comment by CymChad** [comment]
你需要默认loadingView的点击事件吗？不需要我就不设置了。因为如果需要的话，你可以自定义loadingView，点击事件就是又开发者来定了。你觉得这样如何？

**Comment by shingohu** [comment]
恩 我的意思是 不希望loadingview的点击事件传到了itemClick 那里,因为这样我就需要在itemClick判断越界的问题了

**Comment by CymChad** [comment]
恩，可以，没问题，这个是我的疏忽，多谢提醒，稍后给你修复一下。

**Comment by CymChad** [comment]
com.github.CymChad:BaseRecyclerViewAdapterHelper:v1.8.3 这个版本去除了，你试试

**Comment by shingohu** [comment]
谢谢 ，这速度太快

**Comment by CymChad** [comment]
我的行动和我的框架以及我的logo一样，快如闪电，哈哈。欢迎分享给你身边的人！
