### ISSUE TITLE
同一个item的长按事件执行后，其点击事件也会执行

### ISSUE THREAD

**Issue by softsnow** [CymChad/BaseRecyclerViewAdapterHelper#971]

**Comment by softsnow** [comment]
adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public boolean onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemChildClick: ");
                Toast.makeText(ItemClickActivity.this, "onItemChildClick" + position, Toast.LENGTH_SHORT).show();
                return false;
            }
        });
        adapter.setOnItemChildLongClickListener(new BaseQuickAdapter.OnItemChildLongClickListener() {
            @Override
            public void onItemChildLongClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemChildLongClick: ");
                Toast.makeText(ItemClickActivity.this, "onItemChildLongClick" + position, Toast.LENGTH_SHORT).show();
            }
        });
OnItemChildLongClickListener执行后，如何不让OnItemChildClickListener执行

**Comment by AllenCoder** [comment]
更新最新版本 ，长按事件，修改返回值 为  return true 就不会执行单击事件了

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.5'
