### ISSUE TITLE
header是webView，刷新数据的时候会把webview也重新加载一次

### ISSUE THREAD

**Issue by songlong446041** [CymChad/BaseRecyclerViewAdapterHelper#972]
如果header是webView，刷新数据的时候会把webview也重新加载一次，会闪屏

**Comment by songlong446041** [comment]
当前使用的版本号 2.9.4

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.7'

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.8'

**Comment by songlong446041** [comment]
OK了
