### ISSUE TITLE
the footer shows but loadmore listener not trigger

### ISSUE THREAD

**Issue by yummyChina** [CymChad/BaseRecyclerViewAdapterHelper#973]
I setEnableLoadMore(true), and bind the requestLoadMoreListener(); the footer is show but the listener not function,any idea?

**Comment by yummyChina** [comment]
我设置底部可以上拉加载，触发网络请求 加载下一页数据，但是加载两次之后 加载事件不触发了，底部loading是显示的，有什么建议吗，查了很久找到问题

**Comment by 1109993488** [comment]
更新数据时需要调用loadMoreComplete方法，检查下是否调用了
