### ISSUE TITLE
 能否将adapter.newData()的闪烁刷新去掉

### ISSUE THREAD

**Issue by HeJingWei** [CymChad/BaseRecyclerViewAdapterHelper#975]
我自己把取消动画的方法，写在外面再调用newData()一样会闪烁，能否处理下这个闪烁一下的动画呢。

**Comment by CymChad** [comment]
newData()?

**Comment by HeJingWei** [comment]
setNewData()  少打了个set

**Comment by CymChad** [comment]
版本

**Comment by HeJingWei** [comment]
现在是2.9.6   每次刷新页面调用setNewData()就会闪一闪

**Comment by CymChad** [comment]
你动画开启了吗？

**Comment by HeJingWei** [comment]
((SimpleItemAnimator) mRecycler.getItemAnimator()).setSupportsChangeAnimations(false);
加上这句话就好了

**Comment by CymChad** [comment]
@HeJingWei 👍 这是本身RecyclerView的东西
