### ISSUE TITLE
从2.9.6升级到2.9.8后，有的列表出不来了。

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [CymChad/BaseRecyclerViewAdapterHelper#977]
如题
  if (isLoadMore) {
                            myAdapter.addData(commodities);
                        } else {
                            myAdapter.setNewData(commodities);
                        }
                        MyLog.e("测试商品列表2", myAdapter.getData().toString());
打印有数据，但是列表没显示出来，2.9.6正常，切换到2.9.8后有问题

而且setNewData(null),或者setNewData(new ArrayList<String>)会挂掉。报空指针或者越界
                                                           java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{8f0ad6 position=0 id=-1, oldPos=0, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
以上同样是2.9.6正常，切换到2.9.8后有问题

**Comment by CymChad** [comment]
收到，我看下

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.9'
