### ISSUE TITLE
BaseQuickAdapter有问题吧

### ISSUE THREAD

**Issue by z8806c** [CymChad/BaseRecyclerViewAdapterHelper#98]
这个方法 mLoadingMoreEnable会锁住 那么onLoadMoreRequested 只会调用一次 翻到第二页上拉刷新就卡主了

private void addLoadMore(RecyclerView.ViewHolder holder) {
        if (isLoadMore() && !mLoadingMoreEnable) {
            mLoadingMoreEnable = true;
            mRequestLoadMoreListener.onLoadMoreRequested();
        }
    }

**Comment by CymChad** [comment]
你是如何使用的？

**Comment by CymChad** [comment]
按照demo上面来的吗？
