### ISSUE TITLE
关于BaseMultiItemQuickAdapter的问题

### ISSUE THREAD

**Issue by Sky0202** [CymChad/BaseRecyclerViewAdapterHelper#981]
我现在有一个复杂界面使用RecyclerView，继承这个adapter后，加入了头部和底部，头部底部都有输
入数据，需求是通过点击头部里的按钮后，跳到另一个页面，之后会返回一个list集合，并将集合中的数
据展示到此界面中。代码如下：

        rv_cate_orderconfirm.setLayoutManager(new LinearLayoutManager(this));
        jrOrderCateAdapter = new JrOrderCateAdapter(this, choosedProdList);
        //  此处的集合是空的
        jrOrderCateAdapter.addHeaderView(headerView);
        jrOrderCateAdapter.addFooterView(footerView);
        rv_cate_orderconfirm.setAdapter(jrOrderCateAdapter);

以下是多级数据的设置：

     // 多级列表数量 以及数据的设置
    private ArrayList<MultiItemEntity> generateData() {

        int productCount = 2;   // 产品类型

        ArrayList<MultiItemEntity> res = new ArrayList<>();

        for (int i = 0; i < productCount; i++) {
            if (i == 0){
                JingProductCount lv0 = new JingProductCount("单品");
                for (int j = 0; j < choosedProdList .size(); j++) {
                    JingProductName lv1 = new JingProductName("单品名称：热水器");

                    lv1.addSubItem(new JingProductInfo("产品信息"));

                    lv0.addSubItem(lv1);
                }
                res.add(lv0);
            }
            if (i == 1){
                JingProductCount lv1 = new JingProductCount("套餐");
                for (int j = 0; j < choosedProdList .size(); j++) {
                    JingProductName lv2 = new JingProductName("套餐名称：热水器");

                    lv2.addSubItem(new JingProductInfo("产品信息"));

                    lv1.addSubItem(lv2);
                }
                res.add(lv1);
            }
        }
        return res;
    }

现在从另一个界面取回 choosedProdList 后重新走了以上方法，并更新了集合数据，那么我该怎么将数据
填充到界面中，并保证头部底部数据不被销毁？

**Comment by CymChad** [comment]
从另一个界面取回 choosedProdList 后，你追加数据源后刷新就可以了。第一个界面你不用销毁。
