### ISSUE TITLE
上拉加载onLoadMoreRequested无限执行

### ISSUE THREAD

**Issue by imLibo** [CymChad/BaseRecyclerViewAdapterHelper#983]
在加载完数据后设置了loadMoreComplete()还是要无限执行onLoadMoreRequested
按理说onLoadMoreRequested这玩意儿不是要拉到最下面一个Item的时候才会执行吗
怎么会自己就执行了？

**Comment by CymChad** [comment]
版本号，代码。

**Comment by Biswangluo** [comment]
LinearLayoutManager 加载更多一点问题没有 GridLayoutManager 就不停onLoadMoreRequested 刚发现
GridLayoutManager 中用法不对吗 一样的代码 就是改下LayoutManager

**Comment by TONYYAM** [comment]
确实会无限执行

**Comment by imLibo** [comment]
版本号：2.9.9
代码：
mBinding.rcvPlanList.setLayoutManager(new LinearLayoutManager(mActivity));
mAdapterOfList = new PlanNewDayAdapter(R.layout.item_plan_new_second, mPlanList);
mAdapterOfList.setEnableLoadMore(true);
mAdapterOfList.setAutoLoadMoreSize(1);
mAdapterOfList.setOnLoadMoreListener(this, mBinding.rcvPlanList);
mBinding.rcvPlanList.setAdapter(mAdapterOfList);
数据加载完成后：mAdapterOfList.addData(planList);
mAdapterOfList.loadMoreComplete();
@Override
public void onLoadMoreRequested() {
    mPresenter.initPlansToday();
}
看了下BaseQuickAdapter源码，上面的getviewtype里面会一直执行this.autoLoadMore(position);这个方法
造成每次item渲染都会loadmore

**Comment by 1109993488** [comment]
没数据了要设置loadMoreEnd，如果没数据时调用loadMoreComplete的话会回调加载更多的

**Comment by imLibo** [comment]
@1109993488  有数据，也调用了loadMoreComplete，但关键是它会自动调用，而不是滑动到底部才调用，这样造成一次性就加载完毕了，没有起到分页的作用啊，而且这样不停地调，也会造成程序很卡

**Comment by 1109993488** [comment]
RecyclerView外面嵌套Scrollview了吗?

**Comment by imLibo** [comment]
@1109993488  没有嵌套，就是一个很普通的LinearLayoutManager的Recylerview

**Comment by imLibo** [comment]
@TONYYAM  你那里是什么样的情况呢

**Comment by 1109993488** [comment]
@imLibo 你换个手机试试是不是就正常了？

**Comment by CKTim** [comment]
我也同样情况 会多次调用那个下拉加载更多的方法

**Comment by CymChad** [comment]
com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.10

**Comment by CrazyStoneJy** [comment]
版本：2.9.12
加载更多调用loadMoreComplete会一直调用onLoadMoreRequested，问题还是没解决啊

**Comment by imLibo** [comment]
@CrazyStoneJy  我的问题已经解决，是因为用了AutoLayout，然后又是一个水平的LinearLayout嵌套的两个RecyclerView，就这样出了问题。我把水平的LinearLayout改成PersentFramLayout就可以了。应该是AutoLayout测量布局导致Adapter监听不到是否到了底部的原因。

**Comment by imLibo** [comment]
@CrazyStoneJy  也许你就是因为RecyclerView外面包含了一个什么layout，这个layout影响了Adapter的Measure等操作。

**Comment by CrazyStoneJy** [comment]
@imLibo 我就是在RecyclerView外面嵌套了一个SwipRefreshLayout呀

**Comment by CrazyStoneJy** [comment]
@imLibo RecyclerView嵌套SwipeRefreshLayout有影响吗?

**Comment by imLibo** [comment]
@CrazyStoneJy  按理说是不会的，因为官方案例就是用的SwipeRefreshLayout做的下拉刷新啊

**Comment by CrazyStoneJy** [comment]
@imLibo 
/**
     * 处理网络请求后的数据
     *
     * @param list
     */
    public void dealResult(List<T> list) {
        if (mPullState == PullRefreshRecyclerView.PullState.PULL_DOWN) {
            if (mSwipeRefreshLayout.isRefreshing()) {
                mSwipeRefreshLayout.setRefreshing(false);
            }
            mAdapter.setNewData(list);
            mRecyclerView.scrollToPosition(0);
            mPullState = PullState.IDEL;
        } else if (mPullState == PullRefreshRecyclerView.PullState.PULL_UP) {
            if (list == null || list.size() == 0) {
                Toasts.toast("没有更多数据！");
            } else {
                mAdapter.addData(list);
                mAdapter.loadMoreComplete();
            }
            mPullState = PullState.IDEL;
        }
    }
哪写的有问题？

**Comment by imLibo** [comment]
@CrazyStoneJy mChad 你用的PullRefreshRecyclerView这个控件哇？你把它换成原生的试试。自定义的Recyclerview可能与这个库有冲突

**Comment by CrazyStoneJy** [comment]
@imLibo 没有用，就是原生的RecyclerView,PullRefreshRecyclerView是我自己起得

**Comment by CrazyStoneJy** [comment]
@imLibo 你邮箱多少，我发给你看看，用的版本是'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.10'

**Comment by imLibo** [comment]
@CrazyStoneJy 744172447@qq.com

**Comment by CrazyStoneJy** [comment]
@imLibo 已发邮箱

**Comment by diaoxinqiang** [comment]
遇到同样的问题,有什么解决办法吗?

**Comment by wfxphoebus** [comment]
放在  NestedScrollView  里面 就会有这种情况

**Comment by diaoxinqiang** [comment]
已经解决这个问题，发现主要是因为recyclerview外面的布局影响的，应该是测量view的时候获取到错误的值，导致adapter以为到达底部，于是无限循环的调用自动加载更多。总之，用约束布局就没事了。

**Comment by LAzyOnline** [comment]
今天碰到这个问题，刚好也过来说一下我的出现问题的场景和解决方式：
场景：
界面多Fragment并且横屏显示，显示RecyclerView的Fragment的外层有一个Fragment包裹，这个外层的Fragment还被包裹着一个Fragment，也就是说3级的Fragment嵌套。在显示RecyclerView的布局文件中，根控件是LinearLayout，垂直显示，在RecyclerView的上方有个Toolbar；RecyclerView的宽高设置为match_parent或者高为wrap_content（两种方案）。使用的时候发现onLoadMoreRequested一直被调用...
查看源码，发现onLoadMoreRequested的调用是在autoLoadMore里边的，而autoLoadMore是在onBindViewHolder里边调用的，那么问题来了，为什么onBindViewHolder会在item不可视的时候被调用？通过监听RecyclerView的onScrollStateChanged，使用LinearLayoutManager获取第一个和最后一个可视的item的position，发现item的position是没有问题的。这时候就猜测应该是RecyclerView的高度的问题了。
解决思路：
设置RecyclerView的高度。
我的解决方法：在RecyclerView的布局上添加一个FrameLayout，使其包裹RecyclerView，然后通过监听FrameLayout的onGlobalLayout 得到它的测量的宽高，并将宽高值设置到RecyclerView上，ok，问题解决。

**Comment by niuwei1353103949** [comment]
我外部嵌套了Scrollview  然后就开始无限执行，这个该怎么解决呢，那个Scrollview根据UI图是得添加的
