### ISSUE TITLE
关于MultiItem,  ArrayList<MultiItemEntity>

### ISSUE THREAD

**Issue by Sky0202** [CymChad/BaseRecyclerViewAdapterHelper#989]
我使用的数据集合泛型为MultiItemEntity, 现在需要将此集合传给另一页使用, 可是无法序列化, 应该怎么做?

**Comment by CymChad** [comment]
为什么无法序列换？

**Comment by CymChad** [comment]
序列会只需要实现Serializable接口。

**Comment by Sky0202** [comment]
我应该序列化 MultiItemEntity吧?   可是依赖进来的类是加锁无法修改的, 我该怎么序列化

**Comment by CymChad** [comment]
收到，我这边下午看下。

**Comment by CymChad** [comment]
MultiItemEntity是一个接口，你把自己的类 实现 Serializable。
