### ISSUE TITLE
2.9.10出现的问题

### ISSUE THREAD

**Issue by sj853** [CymChad/BaseRecyclerViewAdapterHelper#991]
loadmore 中 上滑的时候 那个加载中的view不会显示··· 我不知道是不是个别机器的问题哈···

**Comment by CymChad** [comment]
上拉加载没改过。

**Comment by CymChad** [comment]
我看下demo

**Comment by CymChad** [comment]
收到

**Comment by AndroidJohnsonWang** [comment]
我也遇到这个问题，2.9.9上拉加载是黑色的字和progressbar,2.9.10是一片白的，功能没影响，但是显示有问题。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.12'
