### ISSUE TITLE
databinding中使用setLayoutManager设置 GridLayoutManager不生效

### ISSUE THREAD

**Issue by mgjnana** [CymChad/BaseRecyclerViewAdapterHelper#992]
使用的是BaseQuickAdapter，多列风格布局，但只能单行显示

**Comment by CymChad** [comment]
你的item布局高度宽度是否填充父布局了？

**Comment by mgjnana** [comment]
<?xml version="1.0" encoding="utf-8"?>
这样：
<layout xmlns:android="http://schemas.android.com/apk/res/android">
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:gravity="center"
    android:layout_margin="@dimen/grid_item_padding_size"
    >

**Comment by CymChad** [comment]
？

**Comment by mgjnana** [comment]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:gravity="center"
    android:layout_margin="@dimen/grid_item_padding_size"
    >

**Comment by mgjnana** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:gravity="center"
    android:layout_margin="@dimen/grid_item_padding_size"
    >
`

**Comment by CymChad** [comment]
版本号，你的使用代码，你的效果。

**Comment by mgjnana** [comment]
` compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.0'`  设置了4列，只显示一列，横向全屏显示

**Comment by CymChad** [comment]
使用staggeredgridlayoutmanager 呢？

**Comment by mgjnana** [comment]
不行，刚试了下

**Comment by mgjnana** [comment]
在？有知道原因么？在线等

**Comment by liu-hailin** [comment]
place add my QQ    790017828

**Comment by liu-hailin** [comment]
then describe the problems you have encountered and the functionality you need to implement

**Comment by CymChad** [comment]
我试了下demo中DataBinding的代码，修改成GridLayoutManager显示正常。
并没有出现你说的问题，请检查你的代码。

**Comment by CymChad** [comment]
![wechatimg6](https://cloud.githubusercontent.com/assets/7698209/24937450/5ad5933a-1f63-11e7-9acd-21893c0e3c6e.jpeg)

**Comment by mgjnana** [comment]
是的，这个我昨天晚上也试了，一会儿看下是不是其它嵌套的原因

**Comment by CymChad** [comment]
恩，感谢你的使用。
