### ISSUE TITLE
如何实现监听RequestLoadMoreListener的同时不显示LoadMoreView？

### ISSUE THREAD

**Issue by jeaman** [CymChad/BaseRecyclerViewAdapterHelper#996]
setOnLoadMoreListener后，会有默认的LoadMoreView，但是通过setLoadMoreView(null)会直接崩溃，要怎么实现不显示LoadMoreView？

**Comment by 1109993488** [comment]
你自定义个LoadMoreView，加载中布局高度设置0dp
