### ISSUE TITLE
GridLayoutManager上拉刷新，怎样才能不用自动刷新

### ISSUE THREAD

**Issue by huangxiaojingCN** [CymChad/BaseRecyclerViewAdapterHelper#998]
使用GridLayoutManager多列布局，一页数据为10个，怎样才能再最后一个条目数据才刷新，现在框架会自动刷新数据。版本为2.9.12

**Comment by 1109993488** [comment]
不设置setAutoLoadMoreSize的话是滑动到底部自动刷新

**Comment by huangxiaojingCN** [comment]
@1109993488    如果外层嵌套了ScrollView，那么内层的recycleview会自动刷新吗？

**Comment by CymChad** [comment]
恩，会有冲突

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/204
